registerExercises('analisis', '1', [
  {st: 'Resolver '+M('|x − 3| ≤ 2')+'.', opts: [M('[1, 5]'), M('(1, 5)'), M('[−5, 5]'), M('[−1, 5]')], c: 0, ex: 'Desigualdad doble: −2 ≤ x − 3 ≤ 2. Sumás 3: 1 ≤ x ≤ 5. Como NO es estricta, los extremos se incluyen → [1, 5]. ▸ Por qué las otras están mal: (B) abierto sería con &lt; estricto; (C) [−5,5] olvida restar el 3; (D) [−1,5] suma mal el límite inferior.'},
  {st: 'Resolver '+M('|2x + 1| > 5')+'.', opts: [M('(−3, 2)'), M('(−∞, −3) ∪ (2, +∞)'), M('[−3, 2]'), M('(−∞, −3] ∪ [2, +∞)')], c: 1, ex: 'Módulo &gt; número: la solución va POR FUERA. ▸ 2x+1 &gt; 5 → x &gt; 2. ▸ 2x+1 &lt; −5 → x &lt; −3. ▸ Como es estricto, los extremos NO se incluyen → (−∞,−3) ∪ (2,+∞). ▸ Por qué las otras están mal: (A) sería para |·| &lt; 5 (entre los extremos); (C) (D) incluyen extremos que se excluyen por la estrictez.'},
  {st: 'Resolver '+M('x² − 9 ≤ 0')+'.', opts: [M('[−3, 3]'), M('(−3, 3)'), M('(−∞, −3] ∪ [3, +∞)'), M('ℝ')], c: 0, ex: 'Factorizo: (x−3)(x+3) ≤ 0. Raíces ±3. Producto negativo o 0 cuando x está ENTRE las raíces → [−3,3]. ▸ Por qué las otras están mal: (B) abierto sería con &lt;; (C) "afuera" sería ≥ 0; (D) ℝ implicaría que es siempre ≤ 0 (falso para |x|&gt;3).'},
  {st: 'Resolver '+M('(x − 2)(x + 1) > 0')+'.', opts: [M('(−1, 2)'), M('(−∞, −1) ∪ (2, +∞)'), M('[−1, 2]'), M('(−∞, −1] ∪ [2, +∞)')], c: 1, ex: 'Raíces: −1 y 2. Producto &gt; 0 cuando ambos factores tienen MISMO signo → "afuera" de las raíces. Estricto → extremos excluidos. ▸ Por qué las otras están mal: (A) sería para "&lt; 0" (entre raíces); (C) (D) incluyen extremos.'},
  {st: 'Resolver '+M('x² − x − 6 ≥ 0')+'.', opts: [M('[−2, 3]'), M('(−2, 3)'), M('(−∞, −2] ∪ [3, +∞)'), M('(−∞, −3] ∪ [2, +∞)')], c: 2, ex: 'Factorizo: (x−3)(x+2) ≥ 0. Raíces 3 y −2. Producto no negativo "afuera" de las raíces, incluyéndolas (≥). ▸ Por qué las otras están mal: (A) (B) son "entre" raíces (parábola hacia arriba es positiva afuera, no entre); (D) usa raíces equivocadas (3 y 2, no 3 y −2).'},
  {st: 'Escribir como intervalo: '+M('{x ∈ ℝ : |x| ≥ 4}')+'.', opts: [M('[−4, 4]'), M('(−∞, −4] ∪ [4, +∞)'), M('(−4, 4)'), M('(−∞, 4]')], c: 1, ex: '|x| es la distancia al 0. ≥ 4 significa estar a 4 o más del 0: x ≤ −4 o x ≥ 4. Como admite igualdad, extremos incluidos. ▸ Por qué las otras están mal: (A) (C) son "cerca del 0" (lo opuesto); (D) solo cubre la mitad inferior.'}
]);

registerExercises('analisis', '2', [
  {st: 'Dominio de '+M('f(x) = ln(x − 5)')+'.', opts: [M('ℝ − {5}'), M('(5, +∞)'), M('[5, +∞)'), M('(−∞, 5)')], c: 1, ex: 'El argumento del ln debe ser ESTRICTAMENTE positivo: x − 5 &gt; 0 → x &gt; 5. ▸ Por qué las otras están mal: (A) ℝ−{5} permitiría valores negativos; (C) [5,+∞) incluye 5 pero ln(0) no está definido; (D) la otra mitad de la recta da argumento negativo.'},
  {st: 'Dominio de '+M('f(x) = √(x² − 4)')+'.', opts: [M('[−2, 2]'), M('(−∞, −2] ∪ [2, +∞)'), M('(−2, 2)'), M('ℝ')], c: 1, ex: 'Raíz par exige radicando ≥ 0: x²−4 ≥ 0 → (x−2)(x+2) ≥ 0 → x ≤ −2 o x ≥ 2 (extremos incluidos). ▸ Por qué las otras están mal: (A) (C) son "entre" raíces (donde x²−4 &lt; 0); (D) ℝ incluye valores prohibidos.'},
  {st: 'Dominio de '+M('f(x) = 1/(x² − 1)')+'.', opts: [M('ℝ − {1}'), M('ℝ − {−1, 1}'), M('(−1, 1)'), M('ℝ − {0}')], c: 1, ex: 'Denominador ≠ 0: x²−1 ≠ 0 → x ≠ ±1. ▸ Por qué las otras están mal: (A) excluye solo un cero; (C) sería para "&lt; 0"; (D) excluye 0 que SÍ está en el dominio.'},
  {st: 'Dominio de '+M('f(x) = √(x + 1)/(x − 3)')+'.', opts: [M('[−1, +∞)'), M('[−1, 3) ∪ (3, +∞)'), M('(−1, 3) ∪ (3, +∞)'), M('[−1, 3]')], c: 1, ex: 'Dos condiciones: ▸ Raíz: x+1 ≥ 0 → x ≥ −1. ▸ Denominador: x ≠ 3. ▸ Intersección: [−1, 3) ∪ (3, +∞). ▸ Por qué las otras están mal: (A) ignora la restricción del denominador; (C) excluye −1 (que sí está); (D) incluye 3 (donde el denominador es 0).'},
  {st: 'Dominio de '+M('f(x) = ln(x)/(x − 2)')+'.', opts: [M('(0, +∞)'), M('(0, 2) ∪ (2, +∞)'), M('[0, 2) ∪ (2, +∞)'), M('ℝ − {2}')], c: 1, ex: '▸ ln: x &gt; 0 (estricto). ▸ Denom: x ≠ 2. ▸ Intersección: (0, 2) ∪ (2, +∞). ▸ Por qué las otras están mal: (A) ignora x=2; (C) incluye 0 (ln(0) no existe); (D) ignora x ≤ 0.'},
  {st: 'Inversa de '+M('f(x) = 3x − 5')+'.', opts: [M('f<sup>−1</sup>(x) = (x + 5)/3'), M('f<sup>−1</sup>(x) = (x − 5)/3'), M('f<sup>−1</sup>(x) = 3x + 5'), M('f<sup>−1</sup>(x) = 1/(3x − 5)')], c: 0, ex: 'Procedimiento: y = 3x − 5 → despejo x: x = (y+5)/3. Intercambio variables: f<sup>−1</sup>(x) = (x+5)/3. ▸ Verificación: f(f<sup>−1</sup>(x)) = 3·(x+5)/3 − 5 = x ✓. ▸ Por qué las otras están mal: (B) signo invertido; (C) confunde con f directa modificada; (D) usaría 1/f, no inversa.'},
  {st: 'Inversa de '+M('f(x) = e<sup>x − 1</sup> + 2')+'.', opts: [M('ln(x) + 1'), M('ln(x − 2) + 1'), M('ln(x + 2) − 1'), M('e<sup>x + 1</sup> − 2')], c: 1, ex: 'y = e^(x−1) + 2 → y − 2 = e^(x−1) → ln(y−2) = x − 1 → x = ln(y−2) + 1. Intercambio: f<sup>−1</sup>(x) = ln(x−2) + 1. ▸ Por qué las otras están mal: (A) le falta el "−2"; (C) signos invertidos; (D) confunde con f.'}
]);

registerExercises('analisis', '3', [
  {st: 'Resolver '+M('e<sup>2x</sup> = 7')+'.', opts: [M('x = ln(7)'), M('x = ln(7)/2'), M('x = 7/2'), M('x = e<sup>7</sup>/2')], c: 1, ex: 'Aplico ln: 2x = ln(7). Despejo: x = ln(7)/2. ▸ Por qué las otras están mal: (A) "ln(7)" falta dividir por 2; (C) "7/2" confunde el ln con división; (D) e^7/2 no surge.'},
  {st: 'Resolver '+M('ln(x − 1) = 0')+'.', opts: [M('x = 0'), M('x = 1'), M('x = 2'), M('No tiene solución')], c: 2, ex: 'ln(algo) = 0 ⟺ algo = e^0 = 1. ▸ x − 1 = 1 → x = 2. Verificá dominio (x &gt; 1): 2 &gt; 1 ✓. ▸ Por qué las otras están mal: (A) (B) no satisfacen; (D) sí tiene solución.'},
  {st: 'Simplificar '+M('e<sup>ln(5)</sup> + ln(e<sup>2</sup>)')+'.', opts: [M('5 + 2 = 7'), M('5 · 2 = 10'), M('e<sup>7</sup>'), M('ln(7)')], c: 0, ex: 'Exp y log son inversas: e^(ln(5)) = 5; ln(e²) = 2. Suma: 5 + 2 = 7. ▸ Por qué las otras están mal: (B) multiplicar en lugar de sumar; (C) no aplica esa propiedad; (D) usar ln al final no corresponde.'},
  {st: 'Soluciones de '+M('cos(x) = −1/2')+' en '+M('[0, 2π]')+'.', opts: [M('π/3 y 5π/3'), M('2π/3 y 4π/3'), M('π/2 y 3π/2'), M('π/6 y 11π/6')], c: 1, ex: 'cos(x) = −1/2: ángulo de referencia π/3, pero NEGATIVO → 2º y 3er cuadrantes. ▸ x = π − π/3 = 2π/3 (2º cuad). ▸ x = π + π/3 = 4π/3 (3er cuad). ▸ Por qué las otras están mal: (A) cos = +1/2 (1º y 4º cuad); (C) cos = 0 en π/2 y 3π/2; (D) cos = +√3/2.'},
  {st: 'Soluciones de '+M('sen(x) = 0')+' en '+M('[0, 2π]')+'.', opts: [M('Solo 0'), M('0 y π'), M('0, π y 2π'), M('π/2 y 3π/2')], c: 2, ex: 'sen vale 0 en múltiplos enteros de π. En [0, 2π]: 0, π, 2π (tres puntos). ▸ Por qué las otras están mal: (A) (B) olvidan extremos; (D) son donde sen = ±1 (no 0).'},
  {st: 'Si '+M('ln(a) = 3')+', ¿cuánto vale '+M('ln(a³)')+'?', opts: [M('3'), M('9'), M('27'), M('ln(9)')], c: 1, ex: 'Propiedad: ln(a^n) = n·ln(a). ▸ ln(a³) = 3·ln(a) = 3·3 = 9. ▸ Por qué las otras están mal: (A) "3" es ln(a); (C) "27" sería 3³; (D) "ln(9)" no aplica directamente.'}
]);

registerExercises('analisis', '4', [
  {st: 'Sea '+M('f(x) = x + 1')+' si '+M('x &lt; 0')+', '+M('f(x) = x²')+' si '+M('x ≥ 0')+'. Calcular '+M('f(−2) + f(3)')+'.', opts: [M('8'), M('10'), M('7'), M('12')], c: 0, ex: '▸ x=−2 (negativo): rama 1, f(−2) = −2+1 = −1. ▸ x=3 (positivo): rama 2, f(3) = 9. ▸ Suma: −1 + 9 = 8. ▸ Por qué las otras están mal: (B) (C) (D) usan ramas equivocadas o suman mal.'},
  {st: 'Sea '+M('f(x) = x² − 1')+' si '+M('x ≤ 1')+', '+M('f(x) = ln(x)')+' si '+M('x &gt; 1')+'. ¿Cuáles son los ceros?', opts: [M('Solo x = 1'), M('x = −1 y x = 1'), M('Solo x = −1'), M('x = 0 y x = 1')], c: 1, ex: '▸ Rama 1 (x≤1): x²−1=0 → x=±1. Ambos cumplen x≤1 ✓. ▸ Rama 2 (x&gt;1): ln(x)=0 → x=1, NO cumple x&gt;1 ✗. ▸ Ceros: x=−1 y x=1. ▸ Por qué las otras están mal: (A) le falta −1; (C) le falta +1; (D) x=0 no es cero (f(0)=−1).'},
  {st: 'Para '+M('f(x) = x + 5')+' si '+M('x &gt; −2')+', '+M('f(x) = x²')+' si '+M('x ≤ −2')+'. ¿Cuánto es '+M('f(−1)')+'?', opts: [M('1'), M('4'), M('5'), M('−1')], c: 1, ex: '−1 &gt; −2 → rama 1: f(−1) = −1+5 = 4. ▸ Por qué las otras están mal: (A) "1" es (−1)² (rama equivocada); (C) "5" es f(0) en la rama 1; (D) "−1" sería f(−6) o algo así.'},
  {st: '¿Qué figura describe '+M('{(x,y): x ≥ 0, y ≥ 0, x + y ≤ 3}')+'?', opts: ['Un círculo centrado en el origen', 'Un triángulo con vértices (0,0), (3,0), (0,3)', 'Una recta', 'Un cuadrado de lado 3'], c: 1, ex: 'x≥0 y y≥0 → primer cuadrante. La recta x+y=3 pasa por (3,0) y (0,3). x+y≤3 recorta debajo de esa recta. ▸ Intersección: triángulo con vértices (0,0), (3,0), (0,3). ▸ Por qué las otras están mal: (A) círculo sería con desigualdad cuadrática; (C) recta es 1D; (D) cuadrado requeriría 4 lados rectos en X e Y.'},
  {st: 'La región '+M('y ≥ x²')+' corresponde a:', opts: ['Debajo de la parábola (sin incluirla)', 'Encima o sobre la parábola (incluida)', 'Solo los puntos de la parábola', 'El interior de un círculo'], c: 1, ex: 'y = x² es parábola hacia arriba. y ≥ x² significa y por arriba de x² o EN la curva (el ≥ incluye igualdad). ▸ Por qué las otras están mal: (A) "debajo" sería y ≤ x²; (C) "solo curva" sería y = x² (estricto); (D) círculo no aplica.'}
]);

registerExercises('analisis', '5', [
  {st: 'Calcular '+M('lim<sub>x→2</sub> (x² − 4)/(x − 2)')+'.', opts: [M('0'), M('2'), M('4'), M('No existe')], c: 2, ex: 'Reemplazar da 0/0 (indeterminación). Factorizo: x²−4 = (x−2)(x+2). Cancelo (x−2): queda x+2. Evalúo en 2: 4. ▸ Por qué las otras están mal: (A) "0" sería el numerador o denominador solo; (B) "2" es el límite si fuera (x²−2)/(x−1); (D) sí existe.'},
  {st: 'Calcular '+M('lim<sub>x→1</sub> (x − 1)/(√x − 1)')+'.', opts: [M('0'), M('1'), M('2'), M('1/2')], c: 2, ex: 'Da 0/0. Multiplico arriba y abajo por el conjugado (√x+1): (x−1)(√x+1)/((√x−1)(√x+1)) = (x−1)(√x+1)/(x−1) = √x+1. En x=1: 2. ▸ Por qué las otras están mal: (A) "0" no surge; (B) "1" es el reemplazo en √x; (D) "1/2" sería al revés.'},
  {st: 'Calcular '+M('lim<sub>x→+∞</sub> (3x² + 5)/(x² − 7)')+'.', opts: [M('0'), M('3'), M('+∞'), M('−5/7')], c: 1, ex: 'Polinomios de IGUAL grado (2). Límite = cociente de coeficientes principales: 3/1 = 3. ▸ Por qué las otras están mal: (A) "0" si el numerador fuera de menor grado; (C) "+∞" si el numerador fuera mayor; (D) "−5/7" es f(0) (sin tomar límite al ∞).'},
  {st: 'Calcular '+M('lim<sub>x→+∞</sub> (1 + 1/x)<sup>3x</sup>')+'.', opts: [M('1'), M('3'), M('e'), M('e<sup>3</sup>')], c: 3, ex: 'Forma 1^∞. Reescribo: ((1+1/x)^x)^3 → e^3 (porque (1+1/x)^x → e). ▸ Por qué las otras están mal: (A) (B) ignoran el límite notable; (C) le falta elevar al 3 el e.'},
  {st: 'Calcular '+M('lim<sub>x→0</sub> sen(5x)/x')+'.', opts: [M('0'), M('1'), M('5'), M('No existe')], c: 2, ex: 'Notable: sen(u)/u → 1. Multiplico y divido por 5: sen(5x)/x = 5·sen(5x)/(5x) → 5·1 = 5. ▸ Por qué las otras están mal: (A) sin aplicar el notable; (B) "1" sería sen(x)/x sin coeficiente; (D) sí existe.'},
  {st: 'Calcular '+M('lim<sub>x→0</sub> (e<sup>2x</sup> − 1)/x')+'.', opts: [M('0'), M('1'), M('2'), M('e')], c: 2, ex: 'Notable: (e^u − 1)/u → 1. Con u=2x: (e^(2x)−1)/x = 2·(e^(2x)−1)/(2x) → 2·1 = 2. ▸ Por qué las otras están mal: (A) sin aplicar notable; (B) "1" sería (e^x−1)/x; (D) "e" no surge.'},
  {st: 'Calcular '+M('lim<sub>x→+∞</sub> (2x² − x)/(x³ + 1)')+'.', opts: [M('0'), M('2'), M('+∞'), M('−1')], c: 0, ex: 'Grado numerador (2) &lt; grado denominador (3). En cociente al ∞ con denominador mayor → 0. ▸ Por qué las otras están mal: (B) "2" es coef principal numerador (no el límite); (C) "+∞" si fuera al revés; (D) "−1" no aplica.'},
  {st: 'Calcular '+M('lim<sub>x→+∞</sub> ((x + 1)/x)<sup>x</sup>')+'.', opts: [M('1'), M('e'), M('e<sup>2</sup>'), M('+∞')], c: 1, ex: '(x+1)/x = 1 + 1/x. Entonces (1+1/x)^x → e directamente. ▸ Por qué las otras están mal: (A) sin aplicar notable; (C) "e²" si fuera elevado a 2x; (D) "+∞" si la base no convergiera.'}
]);

registerExercises('analisis', '6', [
  {st: 'Sea '+M('f(x) = sen(3x)/x')+' si '+M('x ≠ 0')+', '+M('f(0) = k')+'. Hallar '+M('k')+' para continuidad.', opts: [M('k = 0'), M('k = 1'), M('k = 3'), M('k = 1/3')], c: 2, ex: 'Continuidad: k = lim_{x→0} sen(3x)/x = 3 (notable con factor 3). ▸ Por qué las otras están mal: (A) (B) ignoran el coef 3; (D) inverso de la respuesta.'},
  {st: 'Sea '+M('f(x) = (x² − 4)/(x − 2)')+' si '+M('x ≠ 2')+', '+M('f(2) = k')+'. Hallar '+M('k')+'.', opts: [M('k = 0'), M('k = 2'), M('k = 4'), M('k = −2')], c: 2, ex: 'Simplifico: (x²−4)/(x−2) = x+2. Límite en x=2: 4. Para continuidad k=4. ▸ Por qué las otras están mal: (A) (B) (D) no son el valor del límite.'},
  {st: 'Sea '+M('f(x) = (e<sup>x</sup> − 1)/x')+' si '+M('x ≠ 0')+', '+M('f(0) = 2a − 3')+'. Hallar '+M('a')+'.', opts: [M('a = 1'), M('a = 2'), M('a = 3/2'), M('a = 3')], c: 1, ex: 'Notable: lim (e^x−1)/x = 1. Para continuidad: 2a−3 = 1 → a = 2. ▸ Por qué las otras están mal: (A) "a=1" daría 2−3=−1; (C) "a=3/2" daría 0; (D) "a=3" daría 3.'},
  {st: 'Sea '+M('f(x) = 2x + 1')+' si '+M('x &lt; 1')+', '+M('f(x) = 3x')+' si '+M('x ≥ 1')+'. ¿Es continua en '+M('x = 1')+'?', opts: ['Sí', 'No, los laterales difieren', 'No, f(1) no existe', 'Depende'], c: 0, ex: '▸ Por izq: lim_{x→1−} 2x+1 = 3. ▸ Por der: lim_{x→1+} 3x = 3. ▸ Valor: f(1) = 3·1 = 3 (rama 2). Coinciden los 3 → continua. ▸ Por qué las otras están mal: (B) sí coinciden; (C) f(1) está definida; (D) sí se sabe.'},
  {st: 'Sea '+M('f(x) = x²')+' si '+M('x &lt; 2')+', '+M('f(x) = x + 3')+' si '+M('x ≥ 2')+'. ¿Es continua en '+M('x = 2')+'?', opts: ['Sí', 'No, los laterales difieren', 'Sí, ambas ramas son continuas', 'No hay forma de saberlo'], c: 1, ex: '▸ Izq: 2² = 4. ▸ Der: 2+3 = 5. ▸ 4 ≠ 5 → límites laterales DIFIEREN → no continua. ▸ Por qué las otras están mal: (A) (C) "sí" es falso por los laterales; (D) sí se puede saber.'},
  {st: 'Sea '+M('f(x) = ln(1 + 3x)/x')+' si '+M('x ≠ 0')+', '+M('f(0) = m')+'. Hallar '+M('m')+'.', opts: [M('m = 0'), M('m = 1'), M('m = 3'), M('m = 1/3')], c: 2, ex: 'Notable: ln(1+u)/u → 1. Con u=3x: ln(1+3x)/x = 3·ln(1+3x)/(3x) → 3. ▸ Por qué las otras están mal: ignoran el factor 3.'},
  {st: 'Para '+M('f(x) = x³ − x − 1')+' en '+M('[1, 2]')+', ¿qué afirma Bolzano?', opts: ['No se puede aplicar', 'No tiene raíces ahí', 'Tiene exactamente UNA raíz', 'Tiene al MENOS una raíz en (1, 2)'], c: 3, ex: 'f es continua (polinomio). f(1) = −1 (negativo), f(2) = 5 (positivo). Signos opuestos → Bolzano garantiza al MENOS una raíz en (1,2). ▸ Por qué las otras están mal: (A) sí se puede (continua); (B) sí tiene; (C) Bolzano garantiza "al menos una", no "exactamente".'}
]);

registerExercises('analisis', '7', [
  {st: 'Derivar '+M('f(x) = 3x⁴ − 2x² + 5')+'.', opts: [M("f'(x) = 12x³ − 4x"), M("f'(x) = 12x³ − 4x + 5"), M("f'(x) = 3x³ − 2x"), M("f'(x) = 12x⁴ − 4x²")], c: 0, ex: 'Derivo término a término: (3x⁴)\'=12x³, (−2x²)\'=−4x, (5)\'=0. ▸ Por qué las otras están mal: (B) deja la constante; (C) baja exponentes pero no multiplica; (D) no baja los exponentes.'},
  {st: 'Derivar '+M('f(x) = x · ln(x)')+'.', opts: [M("f'(x) = 1"), M("f'(x) = ln(x) + 1"), M("f'(x) = x + ln(x)"), M("f'(x) = 1/x")], c: 1, ex: 'PRODUCTO: (uv)\' = u\'v + uv\'. ▸ (x)\'·ln(x) + x·(ln(x))\' = 1·ln(x) + x·(1/x) = ln(x) + 1. ▸ Por qué las otras están mal: (A) "1" deriva como suma; (C) deriva incorrectamente; (D) deriva solo el ln.'},
  {st: 'Derivar '+M('f(x) = sen(x²)')+'.', opts: [M("f'(x) = cos(x²)"), M("f'(x) = 2x · cos(x²)"), M("f'(x) = 2x · sen(x²)"), M("f'(x) = −cos(x²) · 2x")], c: 1, ex: 'CADENA: (sen(u))\' = cos(u)·u\'. Con u=x²: u\'=2x. Resultado: 2x·cos(x²). ▸ Por qué las otras están mal: (A) sin la derivada interna; (C) deriva con sen en vez de cos; (D) signo invertido.'},
  {st: 'Derivar '+M('f(x) = ln(x³ + 2)')+'.', opts: [M("f'(x) = 1/(x³ + 2)"), M("f'(x) = 3x²/(x³ + 2)"), M("f'(x) = 3x² · ln(x³ + 2)"), M("f'(x) = ln(3x²)")], c: 1, ex: 'CADENA: (ln(u))\' = u\'/u. Con u=x³+2: u\'=3x². Resultado: 3x²/(x³+2). ▸ Por qué las otras están mal: (A) sin derivada interna; (C) multiplica en lugar de dividir; (D) confunde ln.'},
  {st: 'Derivar '+M('f(x) = e<sup>2x + 1</sup>')+'.', opts: [M("f'(x) = e<sup>2x + 1</sup>"), M("f'(x) = 2·e<sup>2x + 1</sup>"), M("f'(x) = (2x+1)·e<sup>2x</sup>"), M("f'(x) = e<sup>2</sup>")], c: 1, ex: 'CADENA: (e^u)\' = e^u·u\'. Con u=2x+1: u\'=2. Resultado: 2·e^(2x+1). ▸ Por qué las otras están mal: (A) sin derivada interna; (C) deriva como producto mal; (D) "e²" sin sentido.'},
  {st: 'Derivar '+M('f(x) = (3x + 1)⁵')+'.', opts: [M("f'(x) = 5(3x + 1)⁴"), M("f'(x) = 15(3x + 1)⁴"), M("f'(x) = 3(3x + 1)⁴"), M("f'(x) = (3x + 1)⁴")], c: 1, ex: 'CADENA: 5(3x+1)⁴·3 = 15(3x+1)⁴. La derivada interna de 3x+1 es 3. ▸ Por qué las otras están mal: (A) le falta el 3; (C) confunde con derivada interna; (D) baja exponente sin multiplicar.'},
  {st: 'Derivar '+M('f(x) = e<sup>x</sup>/x')+'.', opts: [M("f'(x) = e<sup>x</sup>"), M("f'(x) = e<sup>x</sup>(x − 1)/x²"), M("f'(x) = e<sup>x</sup>/x²"), M("f'(x) = (e<sup>x</sup> − 1)/x²")], c: 1, ex: 'COCIENTE: (u/v)\' = (u\'v − uv\')/v². ▸ (e^x·x − e^x·1)/x² = e^x(x−1)/x². ▸ Por qué las otras están mal: (A) deriva mal; (C) (D) confunden la regla.'},
  {st: '¿'+M('f(x) = |x − 2|')+' es derivable en '+M('x = 2')+'?', opts: ['Sí', 'No, no es continua', 'No, tiene un quiebre (derivadas laterales distintas)', 'Sí, f\'(2) = 0'], c: 2, ex: 'Es continua (f(2)=0). Pero la derivada lateral por izq es −1 (pendiente de la rama −(x−2)) y por der es +1 (rama x−2). NO coinciden → no derivable. ▸ Por qué las otras están mal: (A) (D) no derivable; (B) sí es continua.'}
]);

registerExercises('analisis', '8', [
  {st: 'Tangente a '+M('f(x) = x² − 4x + 7')+' en '+M('x = 1')+'.', opts: [M('y = −2x + 6'), M('y = 2x + 2'), M('y = −2x + 4'), M('y = 4x')], c: 0, ex: 'f(1) = 1−4+7 = 4. f\'(x) = 2x−4 → f\'(1) = −2. Ecuación: y − 4 = −2(x−1) → y = −2x + 6. ▸ Por qué las otras están mal: (B) signo de m mal; (C) constante mal; (D) no surge.'},
  {st: 'Tangente a '+M('f(x) = e<sup>x</sup>')+' en '+M('x = 0')+'.', opts: [M('y = x'), M('y = x + 1'), M('y = e<sup>x</sup>'), M('y = 1')], c: 1, ex: 'f(0) = 1. f\'(x) = e^x → f\'(0) = 1. y − 1 = 1·(x − 0) → y = x + 1. ▸ Por qué las otras están mal: (A) le falta el +1; (C) "y=e^x" es la curva original, no la tangente; (D) "y=1" es horizontal.'},
  {st: 'Pendiente de '+M('f(x) = ln(x)')+' en '+M('x = e')+'.', opts: [M('1'), M('1/e'), M('e'), M('ln(e) = 1')], c: 1, ex: 'f\'(x) = 1/x. En x=e: 1/e. ▸ Por qué las otras están mal: (A) (D) confunden valor con pendiente; (C) "e" es x, no la pendiente.'},
  {st: 'La tangente a '+M('f')+' en '+M('x = 2')+' es '+M('y = 3x − 1')+'. ¿Cuánto vale '+M('f(2)')+'?', opts: [M('3'), M('5'), M('−1'), M('2')], c: 1, ex: 'La tangente PASA por el punto (2, f(2)). Reemplazo x=2 en la tangente: y = 3·2 − 1 = 5 → f(2) = 5. ▸ Por qué las otras están mal: (A) "3" es la pendiente (m); (C) "−1" es la ordenada al origen; (D) "2" es x.'},
  {st: 'Sea '+M('g(x) = f(x² − 3)')+'. Si '+M("f'(1) = 4")+', ¿cuánto vale '+M("g'(2)")+'?', opts: [M('4'), M('8'), M('16'), M('2')], c: 2, ex: 'Cadena: g\'(x) = f\'(x²−3)·2x. ▸ En x=2: argumento = 4−3 = 1, así uso f\'(1) = 4. ▸ g\'(2) = 4·(2·2) = 4·4 = 16. ▸ Por qué las otras están mal: (A) solo f\'(1); (B) le falta multiplicar por 2x; (D) sin la cadena completa.'},
  {st: 'Sea '+M('h(x) = 3·f(x) + 2')+'. Si '+M("f'(1) = 5")+', ¿cuánto vale '+M("h'(1)")+'?', opts: [M('5'), M('15'), M('17'), M('2')], c: 1, ex: 'Linealidad: h\'(x) = 3·f\'(x). El +2 deriva 0. ▸ h\'(1) = 3·5 = 15. ▸ Por qué las otras están mal: (A) sin multiplicar por 3; (C) "17" suma 2 al 15; (D) "2" es la constante (no la deriv.).'},
  {st: 'La tangente a '+M('f')+' en '+M('x<sub>0</sub> = 1')+' es '+M('y = 2x + 3')+'. Si '+M('h(x) = f(x² + 2x − 2)')+', hallar '+M("h'(0)")+'.', opts: [M('2'), M('−2·f\'(−2)'), M('2·f\'(−2)'), M('Indefinido (no tenemos f\'(−2))')], c: 3, ex: 'Cadena: h\'(x) = f\'(x²+2x−2)·(2x+2). En x=0: arg = 0+0−2 = −2, factor = 2. ▸ h\'(0) = f\'(−2)·2. NO conocemos f\'(−2) (la tangente solo da info en x=1). Sin más info, INDEFINIDO. ▸ Por qué las otras están mal: las que asumen f\'(−2) sin info; (A) supone arg=1 sin justificación.'}
]);

registerExercises('analisis', '9', [
  {st: 'En '+M('x² + y² = 25')+', hallar '+M("y'")+'.', opts: [M("y' = −x/y"), M("y' = x/y"), M("y' = −2x"), M("y' = 25/(2y)")], c: 0, ex: 'Derivada implícita: 2x + 2y·y\' = 0 → y\' = −x/y. ▸ Por qué las otras están mal: (B) signo invertido; (C) trata y como constante; (D) ignora el 2x.'},
  {st: 'En '+M('xy + y² = 6')+', hallar '+M("y'")+'.', opts: [M("y' = −y/(x + 2y)"), M("y' = y/(x + 2y)"), M("y' = −y/x"), M("y' = (x + 2y)/y")], c: 0, ex: 'Derivada del producto xy: y + x·y\'. Más derivada de y²: 2y·y\'. Total: y + x·y\' + 2y·y\' = 0 → y\'(x+2y) = −y → y\' = −y/(x+2y). ▸ Por qué las otras están mal: (B) signo; (C) ignora 2y; (D) inversa.'},
  {st: 'Para '+M('f(x) = x³ + x')+', calcular '+M("(f<sup>−1</sup>)'(2)")+'.', opts: [M('1/2'), M('1/4'), M('1/3'), M('2')], c: 1, ex: 'Fórmula: (f⁻¹)\'(b) = 1/f\'(a) donde f(a)=b. ▸ Busco a con f(a)=2. Pruebo a=1: 1+1=2 ✓. ▸ f\'(x) = 3x²+1, f\'(1) = 4. ▸ (f⁻¹)\'(2) = 1/4. ▸ Por qué las otras están mal: (A) "1/2" sería con f\'(1)=2; (C) "1/3" es 1/3x²; (D) "2" es f(1).'},
  {st: 'Para '+M('f(x) = x⁵ + 3x')+', calcular '+M("(f<sup>−1</sup>)'(4)")+'.', opts: [M('1/5'), M('1/8'), M('1/4'), M('8')], c: 1, ex: 'Busco a con f(a)=4: a=1 → 1+3=4 ✓. ▸ f\'(x) = 5x⁴+3, f\'(1) = 8. ▸ (f⁻¹)\'(4) = 1/8. ▸ Por qué las otras están mal: similares confusiones de fórmula.'},
  {st: 'En '+M('e<sup>y</sup> = x + 1')+', hallar '+M("y'")+'.', opts: [M("y' = x + 1"), M("y' = 1/e<sup>y</sup> (= 1/(x+1))"), M("y' = e<sup>y</sup>"), M("y' = 1")], c: 1, ex: 'Derivo implícito: e^y·y\' = 1 → y\' = 1/e^y. Como e^y = x+1, también: y\' = 1/(x+1). ▸ Por qué las otras están mal: (A) y\' = x+1 sería e^y; (C) (D) no resuelven la implícita.'}
]);

registerExercises('analisis', '10', [
  {st: 'Calcular '+M('dy')+' para '+M('f(x) = x²')+' en '+M('x = 3')+' con '+M('dx = 0,2')+'.', opts: [M('0,6'), M('1,2'), M('0,2'), M('1,8')], c: 1, ex: 'dy = f\'(x)·dx. f\'(x)=2x, f\'(3)=6. dy = 6·0,2 = 1,2. ▸ Por qué las otras están mal: (A) (C) (D) usan factores incorrectos.'},
  {st: 'Aproximar '+M('f(2,01)')+' si '+M('f(x) = x³')+' usando diferencial.', opts: [M('8'), M('8,12'), M('8,03'), M('12')], c: 1, ex: 'f(2)=8. f\'(2)=3·4=12. ▸ f(2,01) ≈ f(2) + f\'(2)·0,01 = 8 + 0,12 = 8,12. ▸ Por qué las otras están mal: (A) sin diferencial; (C) usa 3 en lugar de 12; (D) confunde con f\'.'},
  {st: 'Aproximar '+M('√4,05')+' usando diferencial en '+M('x = 4')+'.', opts: [M('2'), M('2,0125'), M('2,05'), M('2,025')], c: 1, ex: 'f(x)=√x. f(4)=2. f\'(x)=1/(2√x), f\'(4)=1/4=0,25. ▸ √4,05 ≈ 2 + 0,25·0,05 = 2,0125. ▸ Por qué las otras están mal: (A) sin diferencial; (C) usa f\' = 1; (D) usa f\' = 0,5.'},
  {st: 'Para '+M('f(x) = x²')+' en '+M('x = 1')+' con '+M('Δx = 0,1')+': ¿cuánto es '+M('Δy')+' EXACTO?', opts: [M('0,2'), M('0,21'), M('0,01'), M('1,21')], c: 1, ex: 'Δy = f(1,1) − f(1) = 1,21 − 1 = 0,21. ▸ Compará con dy = 2·0,1 = 0,2 (aproximación; la diferencia 0,01 es el error del diferencial). ▸ Por qué las otras están mal: (A) "0,2" es dy aproximado; (C) "0,01" es el error; (D) "1,21" es f(1,1) sin restar.'}
]);

registerExercises('analisis', '11', [
  {st: 'Calcular '+M('lim<sub>x→0</sub> (1 − cos x)/x²')+'.', opts: [M('0'), M('1/2'), M('1'), M('No existe')], c: 1, ex: '0/0. L\'Hôpital: sen(x)/(2x) (sigue 0/0). L\'Hôpital de nuevo: cos(x)/2 → 1/2. ▸ Por qué las otras están mal: (A) (C) sin aplicar L\'Hôpital; (D) sí existe.'},
  {st: 'Calcular '+M('lim<sub>x→+∞</sub> ln(x)/x')+'.', opts: [M('0'), M('1'), M('+∞'), M('e')], c: 0, ex: '∞/∞. L\'Hôpital: (1/x)/1 = 1/x → 0. ▸ Por qué las otras están mal: ln crece mucho más lento que x. (B) sería para x/x; (C) sería sin L\'Hôpital mal aplicado; (D) "e" no surge.'},
  {st: 'Calcular '+M('lim<sub>x→0</sub> (e<sup>x</sup> − 1 − x)/x²')+'.', opts: [M('0'), M('1'), M('1/2'), M('2')], c: 2, ex: '0/0. L\'Hôpital: (e^x − 1)/(2x) (sigue 0/0). L\'Hôpital otra vez: e^x/2 → 1/2. ▸ Por qué las otras están mal: (A) sin L\'Hôpital; (B) (D) cálculos mal.'},
  {st: 'Calcular '+M('lim<sub>x→+∞</sub> x · e<sup>−x</sup>')+'.', opts: [M('0'), M('1'), M('+∞'), M('e')], c: 0, ex: '0·∞. Reescribo: x/e^x (∞/∞). L\'Hôpital: 1/e^x → 0. ▸ Por qué las otras están mal: el exponencial vence al polinomio.'},
  {st: '¿Se puede aplicar L\'Hôpital a '+M('lim<sub>x→0</sub> sen(x)/(x + 1)')+'?', opts: ['Sí', 'No, da 0/1 = 0 directo (no es indeterminación)', 'Sí, y el resultado es 1', 'No se puede porque sen(x) no es derivable'], c: 1, ex: 'Reemplazo: sen(0)/(0+1) = 0/1 = 0. NO es indeterminación → NO aplica L\'Hôpital. ▸ Por qué las otras están mal: (A) (C) confunden; (D) sen sí es derivable.'},
  {st: 'Calcular '+M('lim<sub>x→0</sub> ln(1 + x)/sen(x)')+'.', opts: [M('0'), M('1'), M('+∞'), M('e')], c: 1, ex: '0/0. L\'Hôpital: (1/(1+x))/cos(x). En x=0: 1/1 = 1. ▸ También sale por notables: ln(1+x) ≈ x, sen(x) ≈ x → x/x = 1.'}
]);

registerExercises('analisis', '12', [
  {st: 'AV de '+M('f(x) = 1/(x − 3)')+'.', opts: [M('x = 0'), M('x = 3'), M('x = −3'), 'No tiene AV'], c: 1, ex: 'AV: donde el denominador se anula y la función "explota". ▸ x − 3 = 0 → x = 3. lim_{x→3} 1/(x−3) = ±∞ → AV en x=3. ▸ Por qué las otras están mal: (A) (C) son valores donde el denominador NO se anula; (D) sí tiene.'},
  {st: 'AH de '+M('f(x) = (2x + 1)/(x − 5)')+'.', opts: [M('y = 0'), M('y = 2'), M('y = 1/−5'), 'No tiene AH'], c: 1, ex: 'AH: lim al ∞. Polinomios de IGUAL grado: cociente de coef. principales = 2/1 = 2. y = 2. ▸ Por qué las otras están mal: (A) sería con grado num &lt; grado denom; (C) "−1/5" es f(0); (D) sí tiene.'},
  {st: '¿'+M('f(x) = x²')+' tiene AH?', opts: ['Sí, y = 0', 'Sí, y = +∞', 'No tiene AH', 'Solo en +∞'], c: 2, ex: 'lim_{x→±∞} x² = +∞. NO tiende a número finito → NO hay AH. ▸ Por qué las otras están mal: (A) "y=0" sería para 1/x²; (B) "y=+∞" no es asíntota válida; (D) tampoco tiene.'},
  {st: 'AO de '+M('f(x) = (x² + 1)/x')+'.', opts: [M('y = x'), M('y = x + 1'), M('y = 0'), 'No tiene AO'], c: 0, ex: 'AO: y = mx + b cuando lim f(x)/x = m (finito) y lim (f(x) − mx) = b. ▸ m = lim (x²+1)/x² = 1. b = lim ((x²+1)/x − x) = lim 1/x = 0. ▸ y = x. ▸ Por qué las otras están mal: (B) "y=x+1" suma constante incorrecta; (C) "y=0" es horizontal; (D) sí tiene.'},
  {st: 'AV de '+M('f(x) = ln(x − 2)')+'.', opts: [M('x = 0'), M('x = 2'), M('x = −2'), 'No tiene AV'], c: 1, ex: 'Dominio: x &gt; 2. Cuando x → 2⁺, ln(x−2) → ln(0⁺) = −∞ → AV en x=2. ▸ Por qué las otras están mal: x=0, x=−2 fuera del dominio; sí tiene asíntota.'}
]);

registerExercises('analisis', '13', [
  {st: 'Puntos críticos de '+M('f(x) = x³ − 3x')+'.', opts: [M('Solo x = 0'), M('x = −1 y x = 1'), M('x = 3'), M('x = −√3 y x = √3')], c: 1, ex: 'f\'(x) = 3x² − 3 = 3(x²−1) = 0 → x² = 1 → x = ±1. ▸ Por qué las otras están mal: (A) (C) (D) no anulan f\'.'},
  {st: 'Si '+M("f'(x) > 0")+' en '+M('(−∞, −1) ∪ (1, +∞)')+' y '+M("f'(x) < 0")+' en '+M('(−1, 1)')+', ¿dónde hay máximo local?', opts: [M('x = −1'), M('x = 1'), M('x = 0'), 'No hay máximo'], c: 0, ex: 'En x=−1, f\' pasa de + a − → MÁXIMO local. En x=1, f\' pasa de − a + → mínimo local. ▸ Por qué las otras están mal: (B) es mín; (C) no es punto crítico; (D) sí hay.'},
  {st: 'Para '+M('f(x) = x² − 4·ln(x)')+', ¿dónde está el punto crítico?', opts: [M('x = 0'), M('x = √2'), M('x = 2'), M('x = −√2 y x = √2')], c: 1, ex: 'Dominio: x &gt; 0. f\'(x) = 2x − 4/x = (2x²−4)/x = 0 → x² = 2 → x = √2 (descarto −√2 por dominio). ▸ Por qué las otras están mal: (A) fuera del dominio; (C) no anula f\'; (D) incluye un valor fuera del dominio.'},
  {st: 'Imagen de '+M('f(x) = e<sup>x</sup> + 1')+'.', opts: [M('ℝ'), M('(0, +∞)'), M('(1, +∞)'), M('[1, +∞)')], c: 2, ex: 'e^x &gt; 0 siempre → e^x+1 &gt; 1 (estricto). lim_{x→+∞} = +∞; lim_{x→−∞} = 1 (sin alcanzar). Imagen: (1, +∞). ▸ Por qué las otras están mal: (A) ℝ incluye negativos; (B) "(0,+∞)" sería e^x sola; (D) "[1,+∞)" incluiría 1 (no alcanzable).'},
  {st: 'Si '+M('f')+' tiene mínimo en '+M('x = 2')+' con '+M('f(2) = −3')+', y '+M('lim<sub>x→±∞</sub> f(x) = +∞')+', ¿cuál es la imagen?', opts: [M('[−3, +∞)'), M('(−3, +∞)'), M('(−∞, −3]'), M('ℝ')], c: 0, ex: 'Mínimo absoluto vale −3 (alcanzado en x=2). Crece hacia +∞ en ambos lados. Imagen: [−3, +∞). ▸ Por qué las otras están mal: (B) excluye −3 que SE alcanza; (C) invertido; (D) ℝ incluye valores menores que el mín.'},
  {st: '¿Cuál es el punto crítico de '+M('f(x) = ln(x) + 2/x')+' (con dominio '+M('x > 0')+')?', opts: [M('x = 0'), M('x = 1'), M('x = 2'), M('x = e')], c: 2, ex: 'f\'(x) = 1/x − 2/x² = (x−2)/x². Se anula en x=2 (x=0 fuera del dominio). ▸ Por qué las otras están mal: (A) fuera del dominio; (B) (D) no anulan f\'.'}
]);

registerExercises('analisis', '14', [
  {st: 'En '+M('[0, 5]')+', sea '+M('f(x) = x² − 4x + 3')+'. ¿Dónde está el mínimo absoluto?', opts: [M('x = 0'), M('x = 2'), M('x = 5'), 'No tiene'], c: 1, ex: 'Para optimizar en intervalo cerrado: ▸ Puntos críticos interiores + extremos. ▸ f\'(x) = 2x−4 = 0 → x=2. ▸ f(0)=3, f(2)=−1, f(5)=8. Mínimo en x=2 (vale −1). ▸ Por qué las otras están mal: (A) (C) son extremos pero no mín.'},
  {st: 'Mismo caso (f(x)=x²−4x+3 en [0,5]): ¿dónde está el máximo absoluto?', opts: [M('x = 0'), M('x = 2'), M('x = 5'), 'No tiene'], c: 2, ex: 'Mismos valores: f(0)=3, f(2)=−1, f(5)=8. Máximo en x=5 (extremo del intervalo). ▸ Por qué las otras están mal: (B) es mín; (A) candidato pero menor que f(5).'},
  {st: 'En '+M('[0, 3]')+', sea '+M('f(x) = x³ − 3x')+'. ¿Dónde el máximo absoluto?', opts: [M('x = 0'), M('x = 1'), M('x = 3'), M('x = −1')], c: 2, ex: 'f\'(x) = 3x²−3 = 0 → x=±1. Solo x=1 está en [0,3]. ▸ f(0)=0, f(1)=−2, f(3)=18. Máximo en x=3. ▸ Por qué las otras están mal: (A) (B) son menores; (D) fuera del intervalo.'},
  {st: 'En '+M('[0, π]')+', sea '+M('f(x) = sen(x)')+'. ¿Dónde el máximo absoluto?', opts: [M('x = 0'), M('x = π/2'), M('x = π'), 'Ambos extremos'], c: 1, ex: 'f\'(x) = cos(x) = 0 en x = π/2 (interior). f(0)=0, f(π/2)=1, f(π)=0. Máximo en π/2. ▸ Por qué las otras están mal: (A) (C) (D) son donde sen=0.'},
  {st: 'En '+M('[−1, 2]')+', sea '+M('f(x) = e<sup>x</sup> − x')+'. ¿Dónde el mínimo absoluto?', opts: [M('x = −1'), M('x = 0'), M('x = 1'), M('x = 2')], c: 1, ex: 'f\'(x) = e^x − 1 = 0 → x=0. f(−1) ≈ 1,37, f(0)=1, f(2) ≈ 5,39. Mínimo en x=0 (vale 1). ▸ Por qué las otras están mal: (A) (D) son extremos del intervalo, mayores; (C) no es punto crítico.'},
  {st: 'En '+M('[1, e]')+', sea '+M('f(x) = 2x² − 9·ln(x)')+'. ¿Dónde el mínimo absoluto?', opts: [M('x = 1'), M('x = 3/2'), M('x = e'), 'No tiene'], c: 1, ex: 'f\'(x) = 4x − 9/x = (4x²−9)/x = 0 → x²=9/4 → x=3/2 (descarto −3/2). ▸ f(1)=2, f(3/2)≈0,85, f(e)≈5,78. Mínimo en x=3/2. ▸ Por qué las otras están mal: (A) (C) son extremos, mayores; (D) sí tiene.'}
]);

registerExercises('analisis', '15', [
  {st: '¿Cuál es el coeficiente del término '+M('(x − c)<sup>k</sup>')+' en el polinomio de Taylor de f centrado en c?', opts: [M('f<sup>(k)</sup>(c)'), M('f<sup>(k)</sup>(c) / k!'), M('f<sup>(k)</sup>(c) · k!'), M('f(c) / k')], c: 1, ex: 'Cada coeficiente es la derivada k-ésima evaluada en c, dividida por k!: f^(k)(c)/k!. ▸ Por qué las otras están mal: (A) olvida el factorial; (C) multiplica en vez de dividir; (D) no usa la derivada k-ésima.'},
  {st: 'El polinomio de Taylor de orden 1 de f centrado en c es:', opts: ['La recta tangente: '+M('f(c) + f′(c)(x − c)'), 'Una parábola', M('f(c)')+' solamente', 'La asíntota horizontal'], c: 0, ex: 'P₁(x) = f(c) + f′(c)(x−c) es exactamente la recta tangente a f en c. ▸ Por qué las otras están mal: la parábola es P₂ (agrega el término de f″); f(c) solo sería P₀ (orden 0); la asíntota no tiene relación.'},
  {st: 'Polinomio de Taylor de '+M('f(x) = e<sup>x</sup>')+' de orden 3 centrado en 0:', opts: [M('1 + x + x² + x³'), M('1 + x + x²/2 + x³/6'), M('x + x²/2 + x³/6'), M('1 + x + 2x² + 6x³')], c: 1, ex: 'Todas las derivadas de eˣ valen 1 en 0, así que el coeficiente de xᵏ es 1/k!: 1 + x + x²/2! + x³/3! = 1 + x + x²/2 + x³/6. ▸ Por qué las otras están mal: (A) olvida los factoriales; (C) le falta el término independiente 1 (= f(0)); (D) multiplica por el factorial en vez de dividir.'},
  {st: 'Si el polinomio de Taylor de f centrado en x = 3 es '+M('P(x) = 5(x−3)⁶ + 3(x−3) + 1')+', ¿cuánto vale '+M('f<sup>(6)</sup>(3)')+'?', opts: [M('5'), M('3600'), M('720'), M('30')], c: 1, ex: 'El coeficiente de (x−3)⁶ es f^(6)(3)/6!. Como ese coeficiente es 5: f^(6)(3) = 6!·5 = 720·5 = 3600. ▸ Por qué las otras están mal: (A) 5 es el coeficiente, no la derivada; (C) 720 es solo 6!; (D) 30 = 6·5 (no es el factorial).'},
  {st: 'Polinomio de Taylor de '+M('f(x) = ln(x)')+' de orden 2 centrado en c = 1:', opts: [M('(x−1) − ½(x−1)²'), M('(x−1) + ½(x−1)²'), M('x − x²/2'), M('1 + (x−1) − (x−1)²')], c: 0, ex: 'f(1)=0, f′=1/x→1, f″=−1/x²→−1. P₂ = 0 + 1(x−1) + (−1)/2!·(x−1)² = (x−1) − ½(x−1)². ▸ Por qué las otras están mal: (B) erra el signo del 2º término; (C) no está centrado en 1; (D) usa f(1)=1, pero ln(1)=0.'},
  {st: 'Para aproximar '+M('√37')+' con un polinomio de Taylor, ¿en qué valor conviene centrar?', opts: [M('c = 37'), M('c = 36'), M('c = 0'), M('c = 49')], c: 1, ex: 'Se centra en el cuadrado perfecto MÁS CERCANO a 37, que es 36 (√36 = 6 es exacto y las derivadas son fáciles de evaluar). Después se evalúa P(37). ▸ Por qué las otras están mal: (A) en 37 no conocemos √37 (es justo lo que buscamos); (C) 0 está lejísimo; (D) 49 está más lejos que 36.'},
  {st: 'El polinomio de Maclaurin (centrado en 0) de '+M('cos(x)')+' tiene:', opts: ['Solo potencias pares, con signos alternados', 'Solo potencias impares', 'Todas las potencias', 'Solo el término independiente'], c: 0, ex: 'cos(x) = 1 − x²/2! + x⁴/4! − x⁶/6! + … : solo potencias PARES con signos que alternan (las derivadas impares del coseno valen 0 en 0). ▸ Por qué las otras están mal: las impares aparecen en sen(x); "todas" mezclaría ambas; no es una constante.'}
]);

registerExercises('analisis', '16', [
  {st: '¿Cuál es la primitiva de '+M('x<sup>n</sup>')+' (con n ≠ −1)?', opts: [M('x<sup>n+1</sup>/(n+1) + C'), M('n·x<sup>n−1</sup> + C'), M('x<sup>n</sup> + C'), M('x<sup>n+1</sup> + C')], c: 0, ex: 'Se sube el exponente en 1 y se divide por el nuevo exponente: ∫xⁿdx = x^(n+1)/(n+1) + C. ▸ Por qué las otras están mal: (B) es la DERIVADA de xⁿ; (C) (D) olvidan dividir por (n+1). El caso n=−1 es la excepción: ∫1/x dx = ln|x|.'},
  {st: 'Por sustitución, '+M('∫(3x−5)<sup>8</sup> dx')+' es igual a:', opts: [M('(3x−5)<sup>9</sup>/27 + C'), M('(3x−5)<sup>9</sup>/9 + C'), M('8(3x−5)<sup>7</sup> + C'), M('(3x−5)<sup>9</sup> + C')], c: 0, ex: 'Con u = 3x−5, du = 3dx → dx = du/3. ∫u⁸·(du/3) = (1/3)·u⁹/9 = (3x−5)⁹/27 + C. ▸ Por qué las otras están mal: (B) olvida el 1/3 de la sustitución; (C) deriva en vez de integrar; (D) olvida ambos factores.'},
  {st: 'Por partes, '+M('∫x·cos(x) dx')+' es igual a:', opts: [M('x·sen(x) + cos(x) + C'), M('x·sen(x) − cos(x) + C'), M('−x·sen(x) + cos(x) + C'), M('x·sen(x) + C')], c: 0, ex: 'u = x (dv = cos x dx → v = sen x): ∫u dv = uv − ∫v du = x·sen x − ∫sen x dx = x·sen x + cos x + C. ▸ Por qué las otras están mal: (B) erra el signo de la última integral (∫sen = −cos); (C) intercambia mal; (D) olvida el término ∫v du.'},
  {st: 'La primitiva de '+M('1/x')+' es:', opts: [M('ln|x| + C'), M('−1/x² + C'), M('1 + C'), M('x<sup>0</sup>/0 + C')], c: 0, ex: 'Es la única excepción de la regla de la potencia: ∫(1/x)dx = ln|x| + C (con módulo, porque x puede ser negativo). ▸ Por qué las otras están mal: (B) es la derivada de 1/x; (C) no es primitiva; (D) dividir por 0 no tiene sentido (justo por eso se usa ln).'},
  {st: '¿Qué método conviene para '+M('∫3x·e<sup>x²</sup> dx')+'?', opts: ['Sustitución (u = x²)', 'Integración por partes', 'Fracciones simples', 'Está en la tabla directa'], c: 0, ex: 'La derivada de x² es 2x, que (salvo constante) está en el integrando: es el caso típico de sustitución u = x². Resultado: (3/2)e^(x²) + C. ▸ Por qué las otras están mal: por partes complica; fracciones simples es para cocientes de polinomios; no está en la tabla directa.'},
  {st: 'Por partes, '+M('∫ln(x) dx')+' es igual a:', opts: [M('x·ln(x) − x + C'), M('1/x + C'), M('x·ln(x) + C'), M('ln(x) − x + C')], c: 0, ex: 'Truco: u = ln x, dv = dx → v = x. ∫ln x dx = x·ln x − ∫x·(1/x)dx = x·ln x − ∫1 dx = x·ln x − x + C. ▸ Por qué las otras están mal: (B) es la derivada de ln x; (C) olvida el término −x; (D) no aplica bien partes.'},
  {st: 'Para integrar el cociente de polinomios '+M('(5y−3)/((y+1)(y−3))')+' conviene:', opts: ['Descomponer en fracciones simples', 'Sustitución directa', 'Integración por partes', 'No se puede integrar'], c: 0, ex: 'Se descompone en 2/(y+1) + 3/(y−3) y cada término integra a un logaritmo: 2·ln|y+1| + 3·ln|y−3| + C. ▸ Por qué las otras están mal: no hay una sustitución directa útil; partes es para productos; sí se puede integrar.'}
]);

registerExercises('analisis', '17', [
  {st: 'La Regla de Barrow dice que '+M('∫<sub>a</sub><sup>b</sup> f(x) dx')+' es igual a (con F primitiva de f):', opts: [M('F(b) − F(a)'), M('F(a) − F(b)'), M('F(b)·F(a)'), M('f(b) − f(a)')], c: 0, ex: 'La integral definida = primitiva evaluada en el límite superior menos en el inferior: F(b) − F(a). ▸ Por qué las otras están mal: (B) está al revés (cambia el signo); (C) no se multiplican; (D) usa f, no su primitiva F.'},
  {st: 'Por el Teorema Fundamental del Cálculo, '+M('d/dx ∫<sub>0</sub><sup>x</sup> e<sup>−t+4</sup> dt')+' vale:', opts: [M('e<sup>−x+4</sup>'), M('−e<sup>−x+4</sup>'), M('e<sup>−x+4</sup> + C'), M('e<sup>−t+4</sup>')], c: 0, ex: 'Derivar una integral con límite superior x "deshace" la integral: reemplazás t por x. Da e^(−x+4). ▸ Por qué las otras están mal: (B) inventa un signo; (C) no lleva +C (es una derivada, da una función concreta); (D) deja la variable muda t (hay que poner x).'},
  {st: 'Usando la Regla de Barrow, '+M('∫<sub>0</sub><sup>4</sup> 2(t−3) dt')+' vale:', opts: [M('−8'), M('8'), M('−4'), M('16')], c: 0, ex: 'Primitiva: t² − 6t. Evalúo: (4²−6·4) − (0) = 16 − 24 = −8. ▸ Da negativo porque el área queda mayormente bajo el eje. ▸ Por qué las otras están mal: (B) olvida el signo; (C) (D) son cálculos parciales mal hechos.'},
  {st: 'El área entre las curvas '+M('y = x')+' e '+M('y = x²')+' (entre x = 0 y x = 1) es:', opts: [M('1/6'), M('1/2'), M('1/3'), M('1')], c: 0, ex: 'En (0,1) la recta y=x está arriba de y=x². A = ∫₀¹(x − x²)dx = [x²/2 − x³/3]₀¹ = 1/2 − 1/3 = 1/6. ▸ Por qué las otras están mal: 1/2 y 1/3 son cada integral por separado (sin restar); 1 no corresponde.'},
  {st: 'Si '+M('F(x) = ∫<sub>0</sub><sup>x²</sup> g(t) dt')+', entonces '+M("F'(x)")+' vale:', opts: [M('g(x²)·2x'), M('g(x²)'), M('g(x)·2x'), M('2x')], c: 0, ex: 'El límite superior es x² (no x), así que se aplica la regla de la cadena: F′(x) = g(x²)·(x²)′ = g(x²)·2x. ▸ Por qué las otras están mal: (B) olvida multiplicar por la derivada del límite (2x); (C) evalúa g en x en vez de x²; (D) olvida la g.'},
  {st: 'La integral '+M('∫<sub>−1</sub><sup>1</sup> (x⁵ − 3x) dx')+' vale:', opts: [M('0'), M('2'), M('−2'), M('6')], c: 0, ex: 'x⁵ − 3x es una función IMPAR (f(−x) = −f(x)) y el intervalo [−1,1] es simétrico: la integral da 0 (lo positivo y lo negativo se cancelan). ▸ Por qué las otras están mal: cualquier valor ≠ 0 ignora la simetría impar. (También sale por Barrow: [x⁶/6 − 3x²/2] da lo mismo en 1 y en −1.)'},
  {st: 'Al resolver la ecuación diferencial separable '+M("y'/y = −x")+' e integrar ambos lados, la solución general tiene la forma:', opts: [M('y = e<sup>(−x²/2 + C)</sup>'), M('y = −x²/2 + C'), M('y = ln(x) + C'), M('y = e<sup>x</sup> + C')], c: 0, ex: 'Integrando: ln|y| = −x²/2 + C → y = e^(−x²/2 + C). Después se usa la condición inicial para hallar C. ▸ Por qué las otras están mal: (B) es el resultado ANTES de despejar y (falta el exponencial); (C) (D) no surgen de integrar y′/y = −x.'}
]);

registerExercises('analisis', '18', [
  {st: 'Calcular '+M('lim<sub>n→∞</sub> (1 + 1/n)<sup>n</sup>')+'.', opts: [M('1'), M('e'), M('+∞'), M('0')], c: 1, ex: 'Es el límite notable de sucesiones: (1 + a/n)ⁿ → eᵃ. Con a = 1 da e. ▸ Es el mismo que aparece en interés compuesto: capitalizar n veces y mandar n→∞ da capitalización continua C·eʳ. ▸ Por qué las otras están mal: (A) la base 1+1/n → 1, pero elevada a n NO da 1 (es indeterminación 1^∞); (C) no diverge, está acotado por e; (D) no tiende a 0.'},
  {st: '¿Por qué '+M('Σ<sub>n=1</sub><sup>∞</sup> n/(n+3)')+' diverge?', opts: ['Porque es una serie p con p ≤ 1', 'Porque '+M('lim a<sub>n</sub> = 1 ≠ 0')+' (falla la condición necesaria)', 'Porque es alternada', 'Porque es geométrica de razón &gt; 1'], c: 1, ex: 'Condición necesaria: si una serie converge, su término general → 0. Acá lim n/(n+3) = 1 ≠ 0, así que la serie NO puede converger (diverge). ▸ Por qué las otras están mal: (A) no tiene forma 1/nᵖ; (C) no hay (−1)ⁿ; (D) no es geométrica. El test del término general ya alcanza.'},
  {st: 'Calcular '+M('Σ<sub>n=0</sub><sup>∞</sup> (1/2)<sup>n</sup>')+'.', opts: [M('1'), M('2'), M('1/2'), M('Diverge')], c: 1, ex: 'Geométrica de razón r = 1/2 (|r| &lt; 1) que arranca en n=0: suma = 1/(1−r) = 1/(1−1/2) = 2. ▸ Por qué las otras están mal: (A) sería la suma desde n=1 (le falta el término n=0 que vale 1); (C) es el primer término, no la suma; (D) converge porque |r| &lt; 1.'},
  {st: '¿La serie '+M('Σ<sub>n=1</sub><sup>∞</sup> 1/√n')+' converge o diverge?', opts: ['Converge', 'Diverge', 'Converge a 0', 'Depende del criterio'], c: 1, ex: 'Es una serie p: 1/√n = 1/n^(1/2), o sea p = 1/2. Como p ≤ 1, DIVERGE. ▸ Recordá: Σ1/nᵖ converge solo si p &gt; 1. ▸ Por qué las otras están mal: (A) (C) p=1/2 no alcanza para converger; (D) el criterio de la serie p es concluyente.'},
  {st: 'Para estudiar '+M('Σ<sub>n=1</sub><sup>∞</sup> ((n+1)/(2n+3))<sup>n</sup>')+' conviene el criterio de la raíz. ¿Qué se concluye?', opts: ['Converge (L = 1/2 &lt; 1)', 'Diverge (L = 2 &gt; 1)', 'El criterio no decide (L = 1)', 'Converge (L = 0)'], c: 0, ex: 'Todo está elevado a la n → criterio de la raíz: ⁿ√aₙ = (n+1)/(2n+3) → 1/2. Como L = 1/2 &lt; 1, CONVERGE. ▸ Por qué las otras están mal: (B) el límite del cociente es 1/2, no 2; (C) L=1 sería si los grados dieran cociente 1; (D) el límite no es 0.'},
  {st: 'La serie '+M('Σ<sub>n=1</sub><sup>∞</sup> (−1)<sup>n</sup>/n')+' es:', opts: ['Absolutamente convergente', 'Condicionalmente convergente', 'Divergente', 'No es alternada'], c: 1, ex: 'Por Leibniz converge (1/n decrece y → 0). Pero la de módulos es Σ1/n (armónica), que DIVERGE. Converge pero no absolutamente → CONDICIONALMENTE convergente. ▸ Por qué las otras están mal: (A) la de módulos diverge; (C) sí converge (Leibniz); (D) sí es alternada por el (−1)ⁿ.'},
  {st: 'Para '+M('Σ<sub>n=1</sub><sup>∞</sup> (x+1)<sup>n</sup>/(n·2<sup>n</sup>)')+' el radio es R = 2. ¿Cuál es el intervalo de convergencia?', opts: [M('(−3, 1)'), M('[−3, 1)'), M('(−3, 1]'), M('[−3, 1]')], c: 1, ex: 'Por la raíz: |x+1|/2 &lt; 1 → |x+1| &lt; 2 → −3 &lt; x &lt; 1 (R=2). Hay que analizar los extremos: en x=1 queda Σ1/n (armónica) → diverge (se excluye); en x=−3 queda Σ(−1)ⁿ/n → converge (se incluye). Intervalo: [−3, 1). ▸ Por qué las otras están mal: dar (−3,1) olvida que −3 sí entra; las que incluyen 1 ignoran que la armónica diverge ahí.'}
]);
