// Física I · UTN FRBA — Simulacros de final.
// Fuentes: los 12 finales distintos de UTN.BA transcriptos en _fisica1_ingest/porTema/_finales.md
// (21 fotos con duplicados, 2022-2025). La unidad 1 es el final del 14/02/24 completo y verbatim.
// Las unidades 2 y 3 son simulacros armados sobre esos arquetipos con los datos cambiados.
// La unidad 4 son 24 preguntas conceptuales verbatim de UTN Facultad Regional San Rafael
// (_fisica1_ingest/porTema/_conceptuales_sr.json) — otra regional, sellado en cada enunciado.
// g = 10 m/s² en todo el archivo, como imprime la hoja de FRBA.

/* ==================== UNIDAD 1 · CÓMO ES EL FINAL Y CÓMO SE RINDE ==================== */

registerReveals('fisica1-utn-simulacros', '1', [

  {st: '<b>Final UTN FRBA 14/02/24 · Problema 1.</b> Para el sistema de la figura (m = 1 kg; β = 37°), y considerando que entre el bloque y la pared el coeficiente de roce cinético es 0,1 y el estático 0,6. Determine la máxima fuerza que puede hacerse sin que el bloque se mueva.',
   ans: 'F<sub>máx</sub> = 83,3 N (exactamente 250/3 N). El coeficiente cinético 0,1 <b>no entra</b>: es un dato puesto a propósito para que sobre.',
   sol: '<b>Paso 1 · Sistema de referencia y DCL.</b> Tomo x positivo hacia la pared (horizontal) e y positivo hacia arriba. Sobre el bloque actúan cuatro fuerzas y ninguna más: el peso P = mg = 10 N hacia abajo; la fuerza F, que forma β = 37° con la horizontal, con componentes F·cos37° = 0,8F hacia la pared y F·sen37° = 0,6F hacia arriba; la normal N que la pared le hace, horizontal y saliendo de la pared; y el rozamiento f, que es <b>vertical</b> porque la superficie de contacto es vertical.<br><br><b>Paso 2 · Hipótesis.</b> El bloque está en equilibrio (no se mueve), así que ΣF = 0 y el rozamiento es <b>estático</b>: sólo vale la desigualdad f ≤ μ<sub>e</sub>·N. Por eso el μ<sub>c</sub> = 0,1 no aparece en ninguna ecuación.<br><br><b>Paso 3 · Equilibrio horizontal.</b> N = F·cos37° = 0,8F. Fijate que la normal la fija la propia F: cuanto más apretás, más normal hay y más rozamiento disponible.<br><br><b>Paso 4 · Equilibrio vertical.</b> 0,6F + f = 10 N (tomando f positivo hacia arriba). Si F crece, llega un momento en que 0,6F &gt; 10 y f cambia de signo: el bloque <b>tiende a subir</b> y el rozamiento pasa a apuntar hacia abajo. Ese es el caso de la fuerza máxima.<br><br><b>Paso 5 · Condición límite.</b> f = 0,6F − 10 y se pide f ≤ μ<sub>e</sub>N:<br>0,6F − 10 ≤ 0,6 · 0,8F = 0,48F &nbsp;⟹&nbsp; 0,12F ≤ 10 &nbsp;⟹&nbsp; <b>F ≤ 83,3 N</b>.<br><br><b>Paso 6 · El regalo que casi nadie escribe.</b> Existe también una fuerza <b>mínima</b>: si F es chica el bloque tiende a caer y el rozamiento apunta hacia arriba: 10 − 0,6F ≤ 0,48F ⟹ F ≥ 9,26 N. El rango completo es <b>9,26 N ≤ F ≤ 83,3 N</b>. Escribir esa segunda cuenta muestra que entendiste que el rozamiento estático se acomoda.'},

  {st: '<b>Final UTN FRBA 14/02/24 · Problema 2.</b> El resorte de la figura inicialmente comprimido entre los carritos A y B libera al soltarse una energía de 1500 J. No hay rozamiento entre los carritos y la superficie. ¿A qué altura máxima llegará cada uno de los carritos? m<sub>A</sub> = 20 kg ; m<sub>B</sub> = 30 kg.',
   ans: 'v<sub>A</sub> = 9,49 m/s y v<sub>B</sub> = 6,32 m/s · <b>h<sub>A</sub> = 4,5 m</b> y <b>h<sub>B</sub> = 2 m</b>.',
   sol: '<b>Paso 1 · Separar las dos etapas.</b> Son dos problemas distintos pegados: (i) la <b>explosión</b> del resorte, donde se conserva la cantidad de movimiento; (ii) la <b>subida</b> de cada carrito por su rampa, donde se conserva la energía mecánica. Nunca mezcles las dos: la energía no se conserva de un lado y la p no sirve del otro.<br><br><b>Paso 2 · Cantidad de movimiento en la explosión.</b> El sistema arranca en reposo y la fuerza del resorte es interna, así que p se conserva:<br>0 = m<sub>A</sub>v<sub>A</sub> − m<sub>B</sub>v<sub>B</sub> &nbsp;⟹&nbsp; 20 v<sub>A</sub> = 30 v<sub>B</sub> &nbsp;⟹&nbsp; v<sub>A</sub> = 1,5 v<sub>B</sub>.<br><br><b>Paso 3 · Energía del resorte.</b> Los 1500 J se reparten como energía cinética:<br>½·20·v<sub>A</sub>² + ½·30·v<sub>B</sub>² = 1500 &nbsp;⟹&nbsp; 10 v<sub>A</sub>² + 15 v<sub>B</sub>² = 1500.<br>Reemplazo v<sub>A</sub> = 1,5 v<sub>B</sub>: 10·2,25 v<sub>B</sub>² + 15 v<sub>B</sub>² = 37,5 v<sub>B</sub>² = 1500 ⟹ <b>v<sub>B</sub>² = 40</b> (v<sub>B</sub> = 6,32 m/s) y <b>v<sub>A</sub>² = 90</b> (v<sub>A</sub> = 9,49 m/s).<br><br><b>Paso 4 · Subida de cada uno.</b> Sin rozamiento, toda la cinética se vuelve potencial: ½mv² = mgh ⟹ h = v²/(2g).<br>h<sub>A</sub> = 90/20 = <b>4,5 m</b> &nbsp;·&nbsp; h<sub>B</sub> = 40/20 = <b>2 m</b>.<br><br><b>Paso 5 · Control de coherencia.</b> El liviano sale más rápido y sube más alto: 20·4,5·10 = 900 J y 30·2·10 = 600 J, que suman los 1500 J del resorte. Que la energía cierre es la mejor verificación que tenés.'},

  {st: '<b>Final UTN FRBA 14/02/24 · Problema 3.</b> De un extremo de una soga inextensible y de masa despreciable se cuelga un cuerpo 1. La soga pasa sin resbalar por el borde de una polea de masa despreciable. El otro extremo de la soga se enrolla alrededor de un disco 2 de radio R que rueda sin deslizar a lo largo del plano horizontal. Calcular: la aceleración del centro de masa del disco, la aceleración del bloque. Datos: momento de inercia de un disco respecto del centro de masa: mR²/2, m<sub>disco</sub> = 6 kg; m<sub>bloque</sub> = 1,5 kg, R = 0,1 m.',
   ans: '<b>a<sub>CM</sub> = 2 m/s²</b> y <b>a<sub>bloque</sub> = 4 m/s²</b> (T = 9 N). El radio R = 0,1 m <b>se cancela</b>: no aparece en ninguna respuesta.',
   sol: '<b>Paso 1 · La hipótesis que resuelve el problema.</b> La soga sale por el <b>punto más alto</b> del disco. En un cuerpo que rueda sin deslizar el punto de contacto tiene velocidad nula y el punto más alto tiene <b>el doble</b> de la del centro: v<sub>alto</sub> = 2v<sub>CM</sub>. Como la soga es inextensible, el bloque se mueve con la velocidad del punto donde la soga se desenrolla:<br><b>v<sub>bloque</sub> = 2 v<sub>CM</sub> &nbsp;⟹&nbsp; a<sub>bloque</sub> = 2 a<sub>CM</sub></b>. Ese es el vínculo cinemático, y es lo que separa un 4 de un 8.<br><br><b>Paso 2 · Disco: torques respecto del punto de contacto.</b> Al rodar sin deslizar conviene tomar momentos en el punto de contacto P, porque ahí la normal y el rozamiento no hacen torque y desaparecen del problema. I<sub>P</sub> = I<sub>CM</sub> + mR² = ½mR² + mR² = (3/2)mR² <span class="muted">(Steiner: acá lo usás sin darte cuenta)</span>.<br>La tensión T actúa arriba, a distancia 2R de P:<br>(3/2)m<sub>d</sub>R²·α = T·2R, con α = a<sub>CM</sub>/R &nbsp;⟹&nbsp; <b>T = (3/4)·m<sub>d</sub>·a<sub>CM</sub></b>.<br>Reemplazando: T = (3/4)·6·a<sub>CM</sub> = 4,5 a<sub>CM</sub>.<br><br><b>Paso 3 · Bloque.</b> m<sub>b</sub>g − T = m<sub>b</sub>·a<sub>bloque</sub> = m<sub>b</sub>·2a<sub>CM</sub>:<br>15 − 4,5 a<sub>CM</sub> = 1,5·2·a<sub>CM</sub> = 3 a<sub>CM</sub> &nbsp;⟹&nbsp; 15 = 7,5 a<sub>CM</sub> &nbsp;⟹&nbsp; <b>a<sub>CM</sub> = 2 m/s²</b>, <b>a<sub>bloque</sub> = 4 m/s²</b>, T = 9 N.<br><br><b>Paso 4 · Dónde está el rozamiento.</b> Traslación del disco: T − f = m<sub>d</sub>a<sub>CM</sub> ⟹ f = 9 − 12 = −3 N. El signo dice que el rozamiento apunta <b>en el mismo sentido del movimiento</b>, no en contra. Es normal: el rozamiento estático de rodadura apunta para donde haga falta para que se cumpla v<sub>CM</sub> = ωR.<br><br><b>Paso 5 · El dato que sobra.</b> R = 0,1 m se simplificó en el Paso 2 y nunca volvió. Que te sobre un dato no significa que lo hiciste mal.'},

  {st: '<b>Final UTN FRBA 14/02/24 · Problema 4.</b> El cilindro de radio R de la figura sube por el plano inclinado rodando sin deslizar hasta llegar a B. A partir de B la superficie no presenta rozamiento. Cuando se encuentra en A la velocidad de su centro de masa es de 4 m/s. Calcular: la velocidad del centro de masa y la velocidad angular del cilindro en B y en C. Datos: I<sub>cilindro</sub> = MR²/2, M = 1 kg, R = 10 cm.',
   ans: '<b>En B:</b> v<sub>B</sub> = 3,46 m/s (√12) y ω<sub>B</sub> = 34,6 rad/s. <b>En C:</b> v<sub>C</sub> = 2,45 m/s (√6) y ω<sub>C</sub> = 34,6 rad/s, <b>la misma que en B</b>.',
   sol: '<b>Paso 1 · Tramo A→B: rueda sin deslizar.</b> El rozamiento estático <b>no hace trabajo</b> (el punto de aplicación tiene velocidad nula), así que se conserva la energía mecánica. Con ω = v/R:<br>E<sub>c</sub> = ½Mv² + ½·(½MR²)·(v/R)² = ½Mv² + ¼Mv² = <b>¾Mv²</b>.<br>¾·v<sub>A</sub>² = ¾·v<sub>B</sub>² + g·h &nbsp;⟹&nbsp; ¾·16 = ¾·v<sub>B</sub>² + 10·0,3<br>12 = ¾v<sub>B</sub>² + 3 &nbsp;⟹&nbsp; v<sub>B</sub>² = 12 &nbsp;⟹&nbsp; <b>v<sub>B</sub> = 3,46 m/s</b>, ω<sub>B</sub> = 3,46/0,1 = <b>34,6 rad/s</b>.<br><br><b>Paso 2 · Tramo B→C: la trampa.</b> Sin rozamiento no hay <b>ninguna</b> fuerza que haga torque respecto del centro de masa (el peso pasa por el CM, la normal también). Entonces α = 0 y <b>ω se mantiene constante</b>: ω<sub>C</sub> = ω<sub>B</sub> = <b>34,6 rad/s</b>. El cilindro sigue girando igual mientras sube, pero ya <b>no rueda</b>: patina.<br><br><b>Paso 3 · Velocidad en C.</b> Como la energía de rotación queda congelada, sólo la traslación paga la subida:<br>½Mv<sub>B</sub>² = ½Mv<sub>C</sub>² + Mg·h &nbsp;⟹&nbsp; v<sub>C</sub>² = 12 − 2·10·0,3 = 6 &nbsp;⟹&nbsp; <b>v<sub>C</sub> = 2,45 m/s</b>.<br><br><b>Paso 4 · Verificá que entendiste.</b> En C: ωR = 34,6·0,1 = 3,46 m/s ≠ v<sub>C</sub> = 2,45 m/s. <b>Esa desigualdad es la respuesta del problema</b>: a partir de B la condición de rodadura deja de valer, y si la seguís usando te da mal. Si hubieras aplicado ¾Mv² en todo el recorrido habrías obtenido v<sub>C</sub> = √8 = 2,83 m/s, que es el error típico.'},

  {st: '<b>Final UTN FRBA 14/02/24 · Problema 5.</b> El gráfico corresponde a la velocidad de un móvil de masa 3 kg que se desplaza sobre un camino recto. En el instante t<sub>0</sub> = 0 se encuentra en la posición x<sub>0</sub> = 0. a) ¿Cuál es la posición del móvil en el instante final de su recorrido? b) Calcular módulo, dirección y sentido del impulso que recibe el móvil entre t = 6 s y t = 8 s.',
   ans: 'a) <b>x = 14 m</b> <span class="muted">(dato reconstruido: la foto es de baja resolución; si la meseta negativa terminara en t = 10,5 s en lugar de t = 11 s, daría 14,5 m — el método es idéntico)</span>. b) <b>|J| = 12 N·s</b>, dirección la del movimiento (el eje x), <b>sentido contrario</b> al de la marcha inicial.',
   sol: '<b>Paso 1 · El método: área bajo la curva.</b> En un gráfico v-t el <b>área</b> es el desplazamiento, y el área bajo el eje cuenta <b>negativa</b>. No hay que integrar nada: son triángulos y rectángulos.<br><br><b>Paso 2 · Tramo por tramo.</b><br>· 0 a 4 s (triángulo de 0 a 4 m/s): ½·4·4 = <b>+8 m</b><br>· 4 a 6 s (rectángulo en 4 m/s): 4·2 = <b>+8 m</b><br>· 6 a 8 s (triángulo, baja de 4 a 0): ½·2·4 = <b>+4 m</b><br>· 8 a 9 s (triángulo, de 0 a −2): ½·1·2 = <b>−1 m</b><br>· 9 a 11 s (rectángulo en −2): −2·2 = <b>−4 m</b><br>· 11 a 12 s (triángulo, de −2 a 0): ½·1·2 = <b>−1 m</b><br>Suma: 8 + 8 + 4 − 1 − 4 − 1 = <b>x = 14 m</b>. Ojo: el móvil llegó a estar en x = 20 m en t = 8 s y después <b>volvió</b> 6 m. La posición final no es el camino recorrido (que es 26 m).<br><br><b>Paso 3 · El impulso.</b> Teorema del impulso: J = Δp = m·(v<sub>f</sub> − v<sub>i</sub>). Entre t = 6 s (v = 4 m/s) y t = 8 s (v = 0):<br>J = 3·(0 − 4) = <b>−12 kg·m/s</b>.<br><b>Módulo</b> 12 N·s, <b>dirección</b> la de la recta del movimiento, <b>sentido</b> opuesto al que traía el móvil (o sea, frenándolo). Escribir las tres cosas es lo que pide el enunciado: si sólo ponés el 12 te descuentan.<br><br><b>Paso 4 · Chequeo.</b> En ese tramo la pendiente es a = (0 − 4)/2 = −2 m/s², y F = ma = −6 N durante 2 s da J = −12 N·s. Coincide.'},

  {st: '<b>Final UTN FRBA 14/02/24 · Problema 6.</b> Un gran bloque de hielo (densidad 917 kg/m³) flota en agua de mar (densidad 1030 kg/m³). ¿Si el área superficial del hielo es 20 m² y tiene 0,20 m de espesor, cuál es la masa del oso polar más pesado que puede estar parado en el hielo sin que se moje las patas?',
   ans: '<b>m<sub>oso</sub> = 452 kg</b>.',
   sol: '<b>Paso 1 · Traducir "sin que se moje las patas".</b> Es la <b>situación límite</b>: la cara superior de la placa queda justo al ras del agua, es decir el hielo está <b>totalmente sumergido</b> y el volumen desplazado es todo el volumen de la placa. Un miligramo más y se hunde.<br><br><b>Paso 2 · Volumen y masa del hielo.</b> V = 20 m² · 0,20 m = <b>4 m³</b>. &nbsp; m<sub>hielo</sub> = 917 · 4 = <b>3668 kg</b>.<br><br><b>Paso 3 · Equilibrio: empuje = peso total.</b> Con Arquímedes, E = ρ<sub>mar</sub>·V<sub>desplazado</sub>·g:<br>ρ<sub>mar</sub>·V·g = (m<sub>hielo</sub> + m<sub>oso</sub>)·g &nbsp;⟹&nbsp; la g se cancela y queda todo en kilos:<br>1030·4 = 3668 + m<sub>oso</sub> &nbsp;⟹&nbsp; 4120 − 3668 = <b>m<sub>oso</sub> = 452 kg</b>.<br><br><b>Paso 4 · Por qué este era el problema para arrancar.</b> Dos renglones y está cerrado. En 5 de los 8 finales que traen fluidos, el de fluidos es el problema 6 y es el más corto de la hoja. Si arrancaste por el 1, llegaste a este cansada y con el reloj encima; si arrancaste por acá, tenías un problema entero guardado en cinco minutos.'}

]);

registerExercises('fisica1-utn-simulacros', '1', [

  {st: 'El encabezado dice «Para aprobar se requiere el 50% del examen bien resuelto» y la hoja trae seis problemas. ¿Qué te está pidiendo exactamente?',
   opts: [
     'Sumar la mitad de los puntos, así que seis problemas empezados por la mitad alcanzan',
     '<b>Tres problemas enteros y bien resueltos</b>; los otros tres pueden quedar en blanco',
     'Sacar el 50% de cada problema, uno por uno',
     'Resolver los tres primeros de la hoja, que son los obligatorios'
   ], c: 1,
   ex: 'La grilla se llena <b>problema por problema</b> con una letra (M, R, B), no con puntos parciales que se suman. Tres «B» y tres casilleros vacíos aprueban. ▸ Por qué las otras: la <b>a</b> es exactamente lo que hizo el alumno del 2/3/2023 — grilla <b>R · R · B · M · vacío · vacío</b> y <b>NOTA 3</b>: cuatro problemas empezados, uno solo bien; el del 27/2/2025 puso <b>B · B · B · B · B</b> y aprobó; la <b>c</b> es el criterio de los <i>parciales</i> de la cátedra (que en 2013 llegó a exigir «50% de cada problema»), no el del final; la <b>d</b> inventa una obligatoriedad: los seis problemas son sueltos y numerados sin jerarquía, elegís vos.'},

  {st: 'De estas cuatro fórmulas, ¿cuál <b>no</b> aparece nunca impresa en las hojas de final que tenemos, y por lo tanto tenés que llevarla de memoria?',
   opts: [
     'I<sub>CM</sub> = mR²/2 del disco o el cilindro',
     'I<sub>CM</sub> = mL²/12 de la barra',
     '<b>I = I<sub>CM</sub> + Md²</b>, el teorema de Steiner',
     'I<sub>CM</sub> = 2/5·mr² de la esfera maciza'
   ], c: 2,
   ex: 'Los tres momentos de inercia aparecen impresos: el del disco en seis finales distintos, el de la barra en el encabezado del 2/3/23 y el de la esfera en el problema 1 del final «s/f (esfera)». <b>Steiner no está en ninguna hoja</b>, y sin él el péndulo físico del 2/3/2023 (barra de 2 m con un disco a 1,67 m del eje) es irresoluble. Escribilo en el margen apenas te den la hoja. ▸ Por qué las otras: las tres son datos que la cátedra regala justamente porque no le interesa que memorices integrales; lo que le interesa es que sepas <b>trasladar</b> un momento de inercia a otro eje.'},

  {st: 'Mirás la hoja de un vistazo: un problema habla de un témpano que flota, otro de un disco con una cupla que sube un plano inclinado, otro de un gráfico v-t y otro de una polea con masa. ¿Por cuál arrancás?',
   opts: [
     'Por el 1, siempre, para no perder el hilo del examen',
     'Por el del disco con la cupla, porque el cuerpo rígido es lo que más peso tiene',
     '<b>Por el del témpano y después por el del gráfico</b>: son los dos más cortos y valen lo mismo que los otros',
     'Por el de la polea con masa, para sacarte de encima el más difícil mientras estás fresca'
   ], c: 2,
   ex: 'Los cuatro problemas valen <b>lo mismo</b>: un casillero cada uno. Los de fluidos reales se cierran con dos ecuaciones («¿qué volumen tiene el témpano?», «¿cuántos troncos necesitan?») y el gráfico v-t se resuelve <b>contando áreas</b>. Sacás dos casilleros en quince minutos y te quedás con todo el tiempo para los caros. ▸ Por qué las otras: la <b>a</b> es la estrategia que produjo el NOTA 3 del 2/3/23; la <b>b</b> confunde «tema importante» con «vale más puntos» — el rígido aparece en los doce finales, pero cada problema sigue siendo un casillero; la <b>d</b> gasta la mejor media hora en un problema de tres cuerpos con vínculo cinemático que podés perder igual.'},

  {st: 'En el problema 1 del 14/02/24 te dan μ<sub>c</sub> = 0,1 y μ<sub>e</sub> = 0,6, resolvés todo con el 0,6 y el 0,1 no entra en ninguna cuenta. ¿Qué significa?',
   opts: [
     'Que te equivocaste de planteo: si te dan un dato es porque hay que usarlo',
     'Que hay que promediar los dos coeficientes y usar 0,35',
     'Que el problema tiene dos partes y te falta hacer la segunda',
     '<b>Que es un distractor deliberado</b>: el bloque nunca desliza, así que sólo interviene el estático'
   ], c: 3,
   ex: 'La cátedra avisa que <b>puede haber datos que no interesen</b>, y los pone. Los casos que ya vimos: μ<sub>c</sub> cuando el cuerpo no desliza (14/2/24 P1), el radio R que se cancela (14/2/24 P3), el radio de la polea en todo problema de energía, la masa del cilindro en rodadura por energía. ▸ Por qué las otras: la <b>a</b> es la regla que te hace perder veinte minutos buscando dónde meter un número que no va; la <b>b</b> es física inventada — μ<sub>e</sub> y μ<sub>c</sub> describen situaciones distintas y no se promedian nunca; la <b>c</b> te hace inventar incisos que el enunciado no pide. Regla operativa: <b>que sobre un dato no es señal de error; que falte, sí</b>.'},

  {st: 'Faltan dos minutos y tenés el problema de rígido planteado pero sin terminar la cuenta. ¿Qué te conviene escribir?',
   opts: [
     '<b>El sistema de referencia, el DCL completo y las hipótesis</b> («cuerda ideal ⟹ misma tensión», «rueda sin deslizar ⟹ v<sub>CM</sub> = ωR»)',
     'El número que te parece más probable, aunque no lo hayas calculado',
     'Una nota al corrector explicando que te faltó tiempo',
     'Nada: si no llegaste al resultado el problema no suma'
   ], c: 0,
   ex: 'El enunciado de la cátedra <b>exige y puntúa aparte</b> declarar el sistema de referencia, hacer el DCL y decir las hipótesis. Un planteo bien fundamentado con la aritmética a medias se corrige mucho mejor que un número solo, y a veces es la diferencia entre una M y una R. ▸ Por qué las otras: la <b>b</b> es lo peor que podés hacer — un número sin planteo no se puede corregir y delata que adivinaste; la <b>c</b> no cambia nada, el corrector ya ve que quedó incompleto; la <b>d</b> es falso: la corrección es por criterio, no por resultado final, y por eso existe la letra «R» (regular) en la grilla.'}

]);

/* ==================== UNIDAD 2 · SIMULACRO 1 ==================== */

registerReveals('fisica1-utn-simulacros', '2', [

  {st: '<b>Simulacro 1 · Problema 1</b> <span class="muted">(arquetipo: final UTN.BA 27/2/25, problema 1 — tiro horizontal + impulso; datos cambiados)</span>. Desde una altura de 12,25 m se lanza horizontalmente una piedra de 200 g, que se incrusta en una pared vertical ubicada a 30 m del lugar de lanzamiento, a 1 m de altura sobre el piso. Calcule: a) la velocidad con la que fue lanzada; b) el módulo, la dirección y el sentido del impulso que la pared le entrega a la piedra.',
   ans: 'a) <b>v<sub>0</sub> = 20 m/s</b> (el vuelo dura 1,5 s). b) <b>|J| = 5 N·s</b>, en la dirección de la velocidad de impacto y en <b>sentido contrario</b>: apunta hacia atrás y hacia arriba, formando 37° con la horizontal.',
   sol: '<b>Paso 1 · Sistema de referencia.</b> Origen en el punto de lanzamiento, x positivo hacia la pared, y positivo hacia arriba. Tiro horizontal: v<sub>0x</sub> = v<sub>0</sub> constante, v<sub>0y</sub> = 0, a<sub>y</sub> = −g = −10 m/s².<br><br><b>Paso 2 · El tiempo sale de la vertical.</b> Baja Δy = 12,25 − 1 = 11,25 m:<br>11,25 = ½·10·t² &nbsp;⟹&nbsp; t² = 2,25 &nbsp;⟹&nbsp; <b>t = 1,5 s</b>.<br><br><b>Paso 3 · La velocidad sale de la horizontal.</b> x = v<sub>0</sub>·t &nbsp;⟹&nbsp; 30 = v<sub>0</sub>·1,5 &nbsp;⟹&nbsp; <b>v<sub>0</sub> = 20 m/s</b>.<br><br><b>Paso 4 · Velocidad justo antes del impacto.</b> v<sub>x</sub> = 20 m/s (nunca cambia) y v<sub>y</sub> = −g·t = −15 m/s. Módulo |v| = √(20² + 15²) = <b>25 m/s</b>, formando con la horizontal un ángulo θ = arctg(15/20) = <b>37°</b> por debajo.<br><br><b>Paso 5 · Impulso.</b> La piedra queda incrustada, o sea v<sub>final</sub> = 0:<br>J = Δp = m(v<sub>f</sub> − v<sub>i</sub>) = −0,2·(20 î − 15 ĵ) = <b>(−4 î + 3 ĵ) N·s</b>.<br><b>Módulo</b> |J| = 0,2·25 = <b>5 N·s</b>; <b>dirección</b> la de la velocidad de impacto; <b>sentido</b> opuesto a ella, o sea hacia atrás y hacia arriba, a 37° de la horizontal.<br><br><b>Paso 6 · Hipótesis que hay que escribir.</b> Desprecio el rozamiento con el aire, considero la piedra puntual, y durante el choque desprecio el peso frente a la fuerza de la pared (por eso el impulso es exactamente −p<sub>i</sub>).'},

  {st: '<b>Simulacro 1 · Problema 2</b> <span class="muted">(arquetipo: final UTN.BA 27/2/25, problema 2 y final «s/f (esfera)» problema 5 — estática en plano inclinado con F horizontal; datos cambiados)</span>. Un bloque de masa m = 2 kg se encuentra en reposo sobre un plano inclinado que forma α = 37° con la horizontal, sostenido por una fuerza horizontal F que apunta hacia adentro del plano, como muestra la figura. Los coeficientes de rozamiento entre el bloque y el plano son μ<sub>e</sub> = 0,5 y μ<sub>c</sub> = 0,3. Encuentre la máxima fuerza F antes de que el bloque se deslice hacia arriba por el plano.',
   ans: '<b>F<sub>máx</sub> = 40 N.</b> El μ<sub>c</sub> = 0,3 no interviene: el bloque no desliza.',
   sol: '<b>Paso 1 · Sistema de referencia inclinado.</b> Tomo x paralelo al plano y positivo <b>hacia arriba</b> del plano, e y perpendicular al plano saliendo de él. Con α = 37°: sen37° = 0,6 y cos37° = 0,8.<br><br><b>Paso 2 · DCL y descomposición.</b> Cuatro fuerzas: peso mg = 20 N (vertical, hacia abajo), normal N (perpendicular al plano), fuerza F (horizontal, hacia adentro del plano) y rozamiento f (paralelo al plano). Al proyectar:<br>· Peso: componente −mg·senα sobre x, y −mg·cosα sobre y.<br>· F horizontal: componente <b>+F·cosα</b> sobre x (empuja hacia arriba del plano) y <b>−F·senα</b> sobre y (aprieta contra el plano). <span class="muted">Este cruce de senos y cosenos es donde se pierde el problema: la fuerza horizontal se proyecta al revés que el peso.</span><br><br><b>Paso 3 · Perpendicular al plano.</b> N = mg·cosα + F·senα = 16 + 0,6F. Fijate que <b>F aumenta la normal</b>, y por lo tanto el rozamiento disponible.<br><br><b>Paso 4 · Condición de máximo.</b> Si el bloque está a punto de subir, el rozamiento apunta <b>hacia abajo</b> del plano y vale su máximo f = μ<sub>e</sub>N. Equilibrio en x:<br>F·cosα = mg·senα + μ<sub>e</sub>(mg·cosα + F·senα)<br>0,8F = 12 + 0,5(16 + 0,6F) = 12 + 8 + 0,3F<br>0,5F = 20 &nbsp;⟹&nbsp; <b>F = 40 N</b>.<br><br><b>Paso 5 · Verificación.</b> Con F = 40 N: N = 16 + 24 = 40 N, f<sub>máx</sub> = 0,5·40 = 20 N; componente de F sobre el plano = 32 N; componente del peso = 12 N. Y 32 = 12 + 20 ✓.<br><br><b>Paso 6 · El dato que sobra.</b> μ<sub>c</sub> = 0,3 no aparece: es un problema de <b>estática</b> y el rozamiento cinético sólo actuaría si el bloque ya estuviera deslizando.'},

  {st: '<b>Simulacro 1 · Problema 3</b> <span class="muted">(arquetipo: final UTN.BA 27/2/25, problema 3 — dinámica circular en el punto más bajo + energía + resorte; datos cambiados)</span>. Una partícula de masa 2 kg, que puede considerarse puntual, baja por una pista semicircular de radio R = 1,5 m. La pista finaliza en un tramo horizontal con rozamiento y finalmente la masa comprime un resorte de constante k = 500 N/m, comprimiéndolo 40 cm. Si en el punto más bajo de la trayectoria (A) la fuerza vertical que la pista realiza sobre la masa es de 100 N, calcule el trabajo de las fuerzas no conservativas sobre la masa entre el punto A y la compresión máxima.',
   ans: 'v<sub>A</sub> = 7,75 m/s (v<sub>A</sub>² = 60 m²/s²) · <b>W<sub>nc</sub> = −20 J</b>.',
   sol: '<b>Paso 1 · La velocidad en A sale de la dinámica, no de la energía.</b> En el punto más bajo la aceleración es <b>centrípeta y apunta hacia arriba</b> (al centro de la circunferencia). DCL en A: la normal N = 100 N hacia arriba y el peso mg = 20 N hacia abajo.<br>N − mg = m·v<sub>A</sub>²/R &nbsp;⟹&nbsp; 100 − 20 = 2·v<sub>A</sub>²/1,5<br>80 = 1,333·v<sub>A</sub>² &nbsp;⟹&nbsp; <b>v<sub>A</sub>² = 60 m²/s²</b> (v<sub>A</sub> = 7,75 m/s).<br><span class="muted">Nunca escribas «N = mg» en un punto de una curva: la normal vale mg sólo cuando no hay aceleración centrípeta.</span><br><br><b>Paso 2 · Energía en A.</b> E<sub>A</sub> = ½·2·60 = <b>60 J</b> de energía cinética. Tomo el tramo horizontal como nivel de referencia, así que no hay potencial gravitatoria en juego entre A y el final.<br><br><b>Paso 3 · Energía en la compresión máxima.</b> Ahí la masa está detenida y toda la energía es elástica:<br>E<sub>f</sub> = ½·k·x² = ½·500·0,4² = ½·500·0,16 = <b>40 J</b>.<br><br><b>Paso 4 · Teorema del trabajo y la energía para fuerzas no conservativas.</b><br>W<sub>nc</sub> = E<sub>f</sub> − E<sub>A</sub> = 40 − 60 = <b>−20 J</b>.<br>El signo negativo era obligatorio: el rozamiento sólo puede sacar energía.<br><br><b>Paso 5 · Por qué este problema se hace en cuatro renglones.</b> No hace falta saber cuánto mide el tramo rugoso, ni cuánto vale μ<sub>c</sub>, ni cuánta energía se disipó mientras el resorte se comprimía. <b>Una sola ecuación escalar</b> entre el estado inicial y el final. Es el típico problema para atacar tercero.'},

  {st: '<b>Simulacro 1 · Problema 4</b> <span class="muted">(arquetipo: final UTN.BA «s/f (LaTeX)» problema 1 — cilindro que rueda + polea con masa + cuerpo colgante; datos cambiados)</span>. Un cilindro de radio R y masa m<sub>1</sub> = 6 kg descansa sobre un plano horizontal con rozamiento y tiene arrollada una cuerda inextensible, muy delgada y de masa despreciable, que sale por su punto más alto. La cuerda pasa por una polea fija de masa m<sub>2</sub> = 4 kg (I<sub>CM</sub> = ½m<sub>2</sub>r²) y de su otro extremo cuelga un cuerpo de masa M = 2 kg. Al dejar el sistema en libertad, el cilindro rueda sin deslizar. Calcule la aceleración del cuerpo colgante y la fuerza de rozamiento sobre el cilindro.',
   ans: '<b>a<sub>M</sub> = 3,2 m/s²</b> y a<sub>CM</sub> del cilindro = 1,6 m/s² · T<sub>1</sub> = 7,2 N y T<sub>2</sub> = 13,6 N · <b>f = 2,4 N hacia adelante</b> (en el mismo sentido en que avanza el cilindro).',
   sol: '<b>Paso 1 · Los dos vínculos cinemáticos.</b> (i) La cuerda sale del punto más alto del cilindro, que en rodadura tiene el doble de velocidad que el centro: <b>a<sub>M</sub> = 2·a<sub>CM</sub></b>. (ii) La cuerda no resbala sobre la polea, así que la polea gira con α<sub>p</sub> = a<sub>M</sub>/r. Como la polea <b>tiene masa</b>, la tensión <b>no</b> es la misma a los dos lados: hay T<sub>1</sub> (lado cilindro) y T<sub>2</sub> (lado cuerpo).<br><br><b>Paso 2 · Cilindro, torques respecto del punto de contacto.</b> I<sub>P</sub> = ½m<sub>1</sub>R² + m<sub>1</sub>R² = (3/2)m<sub>1</sub>R² (Steiner). La tensión actúa a 2R del contacto:<br>(3/2)m<sub>1</sub>R²·(a<sub>CM</sub>/R) = T<sub>1</sub>·2R &nbsp;⟹&nbsp; T<sub>1</sub> = (3/4)m<sub>1</sub>a<sub>CM</sub> = (3/8)m<sub>1</sub>a<sub>M</sub> = 2,25·a<sub>M</sub>.<br><br><b>Paso 3 · Polea con masa.</b> Ecuación de torques: (T<sub>2</sub> − T<sub>1</sub>)·r = ½m<sub>2</sub>r²·(a<sub>M</sub>/r) &nbsp;⟹&nbsp; <b>T<sub>2</sub> − T<sub>1</sub> = ½m<sub>2</sub>a<sub>M</sub> = 2·a<sub>M</sub></b>. El radio r se cancela: no hacía falta.<br><br><b>Paso 4 · Cuerpo colgante.</b> Mg − T<sub>2</sub> = M·a<sub>M</sub> &nbsp;⟹&nbsp; 20 − T<sub>2</sub> = 2a<sub>M</sub>.<br><br><b>Paso 5 · Armar y despejar.</b> Sumando todo: Mg = a<sub>M</sub>·(M + ½m<sub>2</sub> + (3/8)m<sub>1</sub>) = a<sub>M</sub>·(2 + 2 + 2,25)<br>20 = 6,25·a<sub>M</sub> &nbsp;⟹&nbsp; <b>a<sub>M</sub> = 3,2 m/s²</b>, a<sub>CM</sub> = <b>1,6 m/s²</b>.<br>T<sub>1</sub> = 2,25·3,2 = <b>7,2 N</b> &nbsp;·&nbsp; T<sub>2</sub> = 7,2 + 2·3,2 = <b>13,6 N</b> (verificación: 20 − 13,6 = 6,4 = 2·3,2 ✓).<br><br><b>Paso 6 · La fuerza de rozamiento.</b> Traslación del cilindro: T<sub>1</sub> − f = m<sub>1</sub>a<sub>CM</sub> ⟹ f = 7,2 − 9,6 = <b>−2,4 N</b>. El signo dice que apunta <b>hacia adelante</b>, acompañando el movimiento. No es un error: el rozamiento estático de rodadura toma el valor y el sentido que hagan falta para sostener v<sub>CM</sub> = ωR, y sólo está acotado por μ<sub>e</sub>N.<br><br><b>Paso 7 · Hipótesis a declarar.</b> Cuerda ideal e inextensible; polea con masa ⟹ dos tensiones distintas y ecuación de torques obligatoria; rodadura sin deslizamiento ⟹ el rozamiento es estático y no disipa energía.'},

  {st: '<b>Simulacro 1 · Problema 5</b> <span class="muted">(arquetipo: finales UTN.BA «s/f (LaTeX)» problema 3 y «s/f (cohete)» problema 3 — choque unidimensional acoplado a MAS; datos cambiados)</span>. Un bloque de masa m<sub>1</sub> = 4 kg desliza por una superficie horizontal sin rozamiento con una velocidad v<sub>0</sub> = 5 m/s. En cierto instante choca con otro bloque de masa m<sub>2</sub> = 8 kg, unido a un resorte de constante k = 200 N/m que en el instante del choque tiene su longitud natural y cuyo otro extremo está fijo a una pared. Después del choque el bloque m<sub>1</sub> retrocede con una velocidad de módulo 1 m/s. Calcule: a) la amplitud de las oscilaciones que realiza m<sub>2</sub> después del choque; b) la energía perdida en el choque.',
   ans: 'v<sub>2</sub> después del choque = 3 m/s · a) <b>A = 0,6 m</b> (y T = 1,26 s si te lo piden) · b) <b>ΔE<sub>c</sub> = −12 J</b>.',
   sol: '<b>Paso 1 · Separar el choque de lo que pasa después.</b> Son dos etapas con dos leyes distintas: en el <b>choque</b> se conserva la cantidad de movimiento (y sólo eso); en la <b>oscilación</b> posterior se conserva la energía mecánica. Mezclarlas es el error más caro de este tipo de problema.<br><br><b>Paso 2 · Cantidad de movimiento en el choque.</b> Eje x positivo en el sentido de v<sub>0</sub>. m<sub>1</sub> rebota, así que su velocidad final es <b>−1 m/s</b>:<br>m<sub>1</sub>v<sub>0</sub> = m<sub>1</sub>·(−1) + m<sub>2</sub>·v<sub>2</sub><br>4·5 = −4 + 8·v<sub>2</sub> &nbsp;⟹&nbsp; 24 = 8v<sub>2</sub> &nbsp;⟹&nbsp; <b>v<sub>2</sub> = 3 m/s</b>.<br><span class="muted">Hipótesis: el choque dura un instante y las fuerzas externas (peso, normal, resorte en su longitud natural) son despreciables frente a la fuerza de contacto ⟹ se conserva p.</span><br><br><b>Paso 3 · Amplitud del MAS.</b> Justo después del choque el resorte está en su longitud natural: toda la energía de m<sub>2</sub> es cinética, y en la elongación máxima toda es elástica.<br>½m<sub>2</sub>v<sub>2</sub>² = ½kA² &nbsp;⟹&nbsp; A = v<sub>2</sub>·√(m<sub>2</sub>/k) = 3·√(8/200) = 3·0,2 = <b>0,6 m</b>.<br>De paso: ω = √(k/m<sub>2</sub>) = 5 rad/s y T = 2π/ω = <b>1,26 s</b>.<br><br><b>Paso 4 · Energía perdida en el choque.</b><br>E<sub>c inicial</sub> = ½·4·5² = 50 J.<br>E<sub>c final</sub> = ½·4·1² + ½·8·3² = 2 + 36 = 38 J.<br><b>ΔE<sub>c</sub> = 38 − 50 = −12 J</b> (se perdieron 12 J en deformación y calor: el choque es inelástico).<br><br><b>Paso 5 · Control.</b> Si el choque hubiera sido elástico, con m<sub>2</sub> = 2m<sub>1</sub> el primero rebotaría a v<sub>0</sub>/3 = 1,67 m/s. Rebota más despacio (1 m/s), así que perdió energía: coherente con el ΔE<sub>c</sub> negativo.'},

  {st: '<b>Simulacro 1 · Problema 6</b> <span class="muted">(arquetipo: finales UTN.BA «s/f (prisma)» problema 3 y «s/f (LaTeX)» problema 4 — tanque presurizado, Bernoulli y tiro horizontal; datos cambiados)</span>. Un tanque hermético de gran sección contiene agua (δ = 1000 kg/m³) hasta una altura H = 4,25 m. Sobre la superficie libre hay aire a una presión p<sub>0</sub> = 1,2·10⁵ Pa. En la pared lateral, a una altura y = 1,25 m sobre el piso, hay un orificio pequeño que descarga a la atmósfera (p<sub>atm</sub> = 1,0·10⁵ Pa). Determine: a) la velocidad con la que sale el agua por el orificio; b) la distancia horizontal d, medida desde la pared del tanque, a la que el chorro llega al piso.',
   ans: 'a) <b>v = 10 m/s</b> · b) <b>d = 5 m</b> (el chorro tarda 0,5 s en caer).',
   sol: '<b>Paso 1 · Bernoulli entre la superficie libre (1) y el orificio (2).</b><br>p<sub>0</sub> + δ·g·h<sub>1</sub> + ½δv<sub>1</sub>² = p<sub>atm</sub> + δ·g·h<sub>2</sub> + ½δv<sub>2</sub>².<br><b>Hipótesis:</b> el tanque es de gran sección ⟹ por continuidad A<sub>1</sub>v<sub>1</sub> = A<sub>2</sub>v<sub>2</sub> con A<sub>1</sub> ≫ A<sub>2</sub>, así que v<sub>1</sub> ≈ 0; fluido ideal, incompresible y estacionario; el chorro sale a presión atmosférica.<br><br><b>Paso 2 · La profundidad del orificio.</b> h = H − y = 4,25 − 1,25 = <b>3 m</b> por debajo de la superficie libre.<br>½δv² = (p<sub>0</sub> − p<sub>atm</sub>) + δ·g·h = 20 000 + 1000·10·3 = 20 000 + 30 000 = 50 000 Pa<br>v² = 2·50 000/1000 = 100 &nbsp;⟹&nbsp; <b>v = 10 m/s</b>.<br><span class="muted">Si el tanque estuviera abierto (p<sub>0</sub> = p<sub>atm</sub>) quedaría el Torricelli puro v = √(2gh) = 7,75 m/s. La presurización aporta los otros 2,25 m/s.</span><br><br><b>Paso 3 · Ahora es un tiro horizontal.</b> El agua sale horizontal con 10 m/s desde una altura y = 1,25 m:<br>y = ½g·t² &nbsp;⟹&nbsp; 1,25 = 5t² &nbsp;⟹&nbsp; t² = 0,25 &nbsp;⟹&nbsp; <b>t = 0,5 s</b>.<br><br><b>Paso 4 · Alcance.</b> d = v·t = 10·0,5 = <b>5 m</b>.<br><br><b>Paso 5 · Lo que este problema te enseña.</b> Es <b>dos problemas cortos pegados</b>: hidrodinámica y cinemática. Cada uno por separado es de dos renglones. Cuando veas «tanque», «orificio» y «distancia horizontal», ya sabés que la segunda mitad es tiro horizontal y que el único puente entre las dos mitades es la velocidad de salida.'}

]);

registerExercises('fisica1-utn-simulacros', '2', [

  {st: 'Tenés el simulacro 1 delante y quince minutos para el primer casillero. ¿Cuál atacás primero?',
   opts: [
     'El 4 (cilindro + polea con masa), que es el que más practicaste',
     'El 1 (tiro horizontal), porque está numerado primero',
     '<b>El 6 (tanque presurizado)</b>: Bernoulli más tiro horizontal, dos ecuaciones cortas y cerrás un problema entero',
     'El 5 (choque + resorte), porque el choque es lo más fácil que hay'
   ], c: 2,
   ex: 'El 6 se resuelve con <b>una</b> ecuación de Bernoulli (que además se simplifica sola porque v en la superficie es cero) y <b>una</b> caída libre. Diez minutos, casillero cerrado. ▸ Por qué las otras: la <b>a</b> es el problema más caro de la hoja — tres cuerpos, dos tensiones distintas y dos vínculos cinemáticos; la <b>b</b> es la estrategia del NOTA 3; la <b>d</b> no está mal como segunda opción, pero el 5 tiene dos etapas y dos leyes distintas, mientras que el 6 tiene menos donde equivocarse.'},

  {st: 'En el problema 2 (bloque sobre el plano con F horizontal) te dan μ<sub>e</sub> = 0,5 y μ<sub>c</sub> = 0,3. ¿Cómo entran en el planteo?',
   opts: [
     'Se usa μ<sub>c</sub> porque el bloque está por deslizar, que es casi lo mismo que deslizando',
     '<b>Sólo entra μ<sub>e</sub></b>, con f = μ<sub>e</sub>N en la condición límite; μ<sub>c</sub> es distractor',
     'Se usan los dos: μ<sub>e</sub> para la normal y μ<sub>c</sub> para la fuerza paralela',
     'Se usa el promedio de ambos porque el bloque está en la frontera'
   ], c: 1,
   ex: 'El problema pide la fuerza <b>máxima antes</b> de que deslice: el bloque nunca llega a moverse, así que el rozamiento es estático todo el tiempo y en el límite vale f = μ<sub>e</sub>N. Y ojo con la normal: como F es horizontal y aprieta contra el plano, <b>N = mg·cosα + F·senα</b>, no mg·cosα. ▸ Por qué las otras: la <b>a</b> confunde «a punto de deslizar» (donde el rozamiento estático llega a su máximo) con «deslizando»; la <b>c</b> inventa una repartición de coeficientes que no existe — hay un único coeficiente actuando por vez; la <b>d</b> promedia coeficientes que describen situaciones físicas distintas.'},

  {st: 'En el problema 4, la cuerda sale por el <b>punto más alto</b> del cilindro que rueda. ¿Cuál es el vínculo cinemático correcto?',
   opts: [
     'a<sub>M</sub> = a<sub>CM</sub>, porque la cuerda es inextensible',
     'a<sub>M</sub> = a<sub>CM</sub>/2, porque el punto de contacto está quieto',
     'a<sub>M</sub> = a<sub>CM</sub>·R, para pasar de lineal a angular',
     '<b>a<sub>M</sub> = 2·a<sub>CM</sub></b>, porque el punto más alto de un cuerpo que rueda tiene el doble de velocidad que el centro'
   ], c: 3,
   ex: 'En rodadura sin deslizamiento el punto de contacto tiene velocidad cero, el centro tiene v<sub>CM</sub> y el punto más alto tiene <b>2v<sub>CM</sub></b>: es una rotación pura alrededor del contacto, y el punto alto está al doble de distancia del eje instantáneo. La cuerda se desenrolla desde ahí, así que el cuerpo colgante baja al doble de rápido. ▸ Por qué las otras: la <b>a</b> es exactamente el error que hace fallar el problema y también el problema 3 del 14/02/24; la <b>b</b> invierte el factor; la <b>c</b> mezcla unidades — a<sub>CM</sub>·R no tiene unidades de aceleración. <b>Regla:</b> si la cuerda saliera del <b>eje</b> del cilindro, ahí sí a<sub>M</sub> = a<sub>CM</sub>.'},

  {st: 'En el problema 5 (choque y después resorte), ¿qué método usás en cada etapa?',
   opts: [
     'Energía en las dos etapas, porque no hay rozamiento en ninguna',
     '<b>Cantidad de movimiento en el choque y energía después</b>: en el choque se pierden 12 J',
     'Cantidad de movimiento en las dos, porque el resorte es una fuerza interna',
     'Energía en el choque y cantidad de movimiento en la oscilación'
   ], c: 1,
   ex: 'El choque es inelástico: la p se conserva pero la energía cinética <b>no</b> (se perdieron 12 J). Después del choque, m<sub>2</sub> sola con el resorte sin rozamiento sí conserva la energía mecánica, y de ahí sale la amplitud. ▸ Por qué las otras: la <b>a</b> es el error clásico — «no hay rozamiento» no significa que el choque sea elástico, y si aplicás energía al choque te da otra velocidad y toda la segunda parte queda mal; la <b>c</b> no se puede: durante la oscilación el resorte es una fuerza <b>externa</b> sobre m<sub>2</sub> y la p de m<sub>2</sub> cambia todo el tiempo; la <b>d</b> invierte las dos leyes.'},

  {st: 'En el problema 3, después de calcular v<sub>A</sub> desde la dinámica circular, ¿cómo seguís para hallar W<sub>nc</sub>?',
   opts: [
     'Buscás la longitud del tramo rugoso y μ<sub>c</sub>, y calculás −μ<sub>c</sub>mgL',
     'Aplicás la segunda ley de Newton en el tramo horizontal e integrás',
     'Calculás la fuerza media del resorte y la multiplicás por 0,4 m',
     '<b>Una sola ecuación escalar:</b> W<sub>nc</sub> = E<sub>final</sub> − E<sub>inicial</sub> = ½kx² − ½mv<sub>A</sub>²'
   ], c: 3,
   ex: 'El teorema del trabajo y la energía te deja saltar directamente del estado A al estado de compresión máxima sin saber nada de lo que pasó en el medio: 40 J − 60 J = <b>−20 J</b>. Por eso este problema es corto y conviene atacarlo temprano. ▸ Por qué las otras: la <b>a</b> no se puede — el enunciado no da ni L ni μ<sub>c</sub>, y no los necesitás; la <b>b</b> te obliga a conocer la fuerza en cada punto, que es justamente lo que el teorema te ahorra; la <b>c</b> calcula el trabajo del resorte, que es una fuerza <b>conservativa</b> y ya está contabilizada dentro de ½kx²: sumarla otra vez sería contarla dos veces.'}

]);

/* ==================== UNIDAD 3 · SIMULACRO 2 ==================== */

registerReveals('fisica1-utn-simulacros', '3', [

  {st: '<b>Simulacro 2 · Problema 1</b> <span class="muted">(arquetipo: final UTN.BA 2/3/23, problema 1 — momento angular con radio variable; datos cambiados)</span>. Una masa puntual m<sub>1</sub> = 0,5 kg se halla sujeta a un extremo de una soga ideal girando sobre un plano horizontal sin rozamiento. Su velocidad en módulo es inicialmente v<sub>1i</sub> = 3 m/s cuando el radio de giro es r<sub>1i</sub> = 0,6 m. Para esto es necesario contar con una masa m<sub>2</sub> que cuelga desde el otro extremo de la cuerda, que pasa por un agujero en el centro de la mesa. Si se añade masa extra de modo tal que m<sub>1</sub> describe ahora una trayectoria circular de radio r<sub>1f</sub> = 0,3 m, calcule: (i) el valor de m<sub>2</sub> inicialmente; (ii) la velocidad en módulo cuando se aumenta la masa que cuelga; (iii) el valor de la nueva masa colgante.',
   ans: '(i) <b>m<sub>2</sub> = 0,75 kg</b> · (ii) <b>v<sub>1f</sub> = 6 m/s</b> · (iii) <b>m<sub>2 final</sub> = 6 kg</b>.',
   sol: '<b>Paso 1 · (i) La masa colgante fija la tensión, y la tensión es la fuerza centrípeta.</b> La masa que cuelga está en equilibrio (se mueve con velocidad constante o está quieta), así que T = m<sub>2</sub>g. Y sobre m<sub>1</sub>, la tensión es la única fuerza horizontal:<br>T = m<sub>1</sub>v<sub>1i</sub>²/r<sub>1i</sub> &nbsp;⟹&nbsp; m<sub>2</sub>·10 = 0,5·9/0,6 = 7,5 N &nbsp;⟹&nbsp; <b>m<sub>2</sub> = 0,75 kg</b>.<br><br><b>Paso 2 · (ii) Por qué se conserva el momento angular y no la energía.</b> La tensión es una fuerza <b>central</b>: siempre apunta al agujero. Su torque respecto del agujero es nulo (r y F son paralelos), así que <b>L se conserva</b>. La energía cinética de m<sub>1</sub>, en cambio, <b>no</b> se conserva: la tensión hace trabajo mientras la soga se acorta.<br>L = m<sub>1</sub>v<sub>1i</sub>r<sub>1i</sub> = m<sub>1</sub>v<sub>1f</sub>r<sub>1f</sub> &nbsp;⟹&nbsp; v<sub>1f</sub> = v<sub>1i</sub>·(r<sub>1i</sub>/r<sub>1f</sub>) = 3·(0,6/0,3) = <b>6 m/s</b>.<br><br><b>Paso 3 · (iii) La nueva masa colgante.</b> En el nuevo estado estacionario:<br>m<sub>2f</sub>·g = m<sub>1</sub>v<sub>1f</sub>²/r<sub>1f</sub> = 0,5·36/0,3 = 60 N &nbsp;⟹&nbsp; <b>m<sub>2f</sub> = 6 kg</b>.<br><br><b>Paso 4 · Control físico.</b> Al partir el radio a la mitad, la velocidad se duplicó y la fuerza necesaria se multiplicó por 8 (v² sube 4 veces y r baja a la mitad). La energía cinética pasó de 2,25 J a 9 J: esos 6,75 J los puso el peso de la masa que bajó. Ninguna magnitud se conservó salvo L, y esa es toda la física del problema.'},

  {st: '<b>Simulacro 2 · Problema 2</b> <span class="muted">(arquetipo: final UTN.BA 21/2/24, problema 2 — disco con par de fuerzas subiendo un plano; datos cambiados)</span>. Un disco de masa m = 6 kg y radio R = 0,3 m está sobre un plano inclinado un ángulo α = 30°. Se le aplica un par de fuerzas de módulo F = 24 N y el disco sube rodando sin deslizar. Si parte del reposo, se pide hallar: (i) la fuerza de roce en módulo, dirección y sentido; (ii) la energía cinética a los 2 segundos.',
   ans: '(i) <b>f = 42 N</b>, paralela al plano y dirigida <b>hacia arriba</b> del plano (a = 2 m/s²) · (ii) <b>E<sub>c</sub> = 72 J</b> a los 2 s (v = 4 m/s, ω = 13,3 rad/s).',
   sol: '<b>Paso 1 · Qué es un par de fuerzas.</b> Dos fuerzas iguales, antiparalelas y aplicadas en los extremos de un diámetro. Su <b>resultante es cero</b> (no aparecen en la ecuación de traslación) pero su <b>momento no</b>: M = F·d = F·2R = 24·0,6 = <b>14,4 N·m</b>, y ese momento es el mismo respecto de cualquier punto. Esa propiedad es la que hace fácil el problema.<br><br><b>Paso 2 · Torques respecto del punto de contacto.</b> I<sub>P</sub> = ½mR² + mR² = (3/2)mR² (Steiner). Torques respecto de P: el par aporta M; la componente del peso paralela al plano (mg·senα, hacia abajo del plano) actúa en el CM, que está a R de P, y frena la rodadura; la normal y el rozamiento pasan por P y no aportan.<br>(3/2)mR²·(a/R) = F·2R − mg·senα·R &nbsp;⟹&nbsp; (3/2)m·a = 2F − mg·senα<br>9·a = 48 − 30 = 18 &nbsp;⟹&nbsp; <b>a = 2 m/s²</b>, hacia arriba del plano.<br><br><b>Paso 3 · (i) El rozamiento, de la traslación.</b> Tomando positivo hacia arriba del plano, y recordando que el par no aporta fuerza neta:<br>f − mg·senα = m·a &nbsp;⟹&nbsp; f = 6·2 + 30 = <b>42 N</b>, <b>paralela al plano y hacia arriba</b>.<br><span class="muted">Chequeo de coherencia: N = mg·cosα = 6·10·0,866 = 52 N, así que hace falta μ<sub>e</sub> ≥ 42/52 = 0,81. Es un rozamiento alto pero posible; si diera f &gt; N el enunciado sería inconsistente y habría que decirlo.</span><br><br><b>Paso 4 · (ii) Energía cinética a los 2 s.</b> Parte del reposo con a constante: v = a·t = 2·2 = <b>4 m/s</b>, ω = v/R = 4/0,3 = <b>13,3 rad/s</b>.<br>E<sub>c</sub> = ½mv² + ½I<sub>CM</sub>ω² = ¾mv² = 0,75·6·16 = <b>72 J</b>.<br><br><b>Paso 5 · Verificación por energía.</b> En 2 s recorrió d = ½at² = 4 m, subiendo h = 4·sen30° = 2 m. Trabajo del par: M·θ, con θ = d/R = 13,33 rad ⟹ 14,4·13,33 = 192 J. Trabajo del peso: −mgh = −120 J. El rozamiento estático no trabaja. Total: 192 − 120 = <b>72 J</b> ✓.'},

  {st: '<b>Simulacro 2 · Problema 3</b> <span class="muted">(arquetipo: final UTN.BA 21/2/24, problema 1 — patinador con tramo rugoso, problema iterativo; datos cambiados)</span>. Un patinador se dirige hacia una pista, como se observa en la figura, con una velocidad inicial v<sub>0</sub> que es la mínima necesaria para poder alcanzar el primer desnivel de h<sub>i</sub> = 3,2 m. Suponiendo que se deja caer desde el reposo desde allí, el patinador encontrará un tramo de longitud D = 4 m donde la superficie posee rozamiento y su coeficiente cinético es μ<sub>c</sub> = 0,3. La pista culmina con otro desnivel similar al primero. Se pide determinar: (i) el valor de la velocidad inicial v<sub>0</sub>; (ii) la altura h<sub>1</sub> a la que llega en la segunda elevación luego de pasar una vez por la zona de rozamiento; (iii) el número de veces necesarias que debe pasar para que su altura máxima sea h<sub>f</sub> = 0,8 m.',
   ans: '(i) <b>v<sub>0</sub> = 8 m/s</b> · (ii) <b>h<sub>1</sub> = 2 m</b> · (iii) <b>2 pasadas</b>.',
   sol: '<b>Paso 1 · (i) Qué quiere decir "la mínima necesaria".</b> Que llega justo arriba del primer desnivel <b>con velocidad nula</b>. Fuera del tramo rugoso no hay rozamiento, así que se conserva la energía:<br>½mv<sub>0</sub>² = mg·h<sub>i</sub> &nbsp;⟹&nbsp; v<sub>0</sub> = √(2·10·3,2) = √64 = <b>8 m/s</b>.<br>Fijate que la masa se cancela y nunca aparece: es otro dato que no hace falta.<br><br><b>Paso 2 · La cuenta clave: cuánta altura cuesta cada pasada.</b> Al cruzar el tramo D, el rozamiento disipa<br>|W<sub>roz</sub>| = μ<sub>c</sub>·m·g·D, que en unidades de altura equivale a <b>Δh = μ<sub>c</sub>·D = 0,3·4 = 1,2 m</b>.<br>Esta es la idea que convierte un problema iterativo en una resta: <b>cada pasada por la zona rugosa le baja 1,2 m a la altura máxima</b>, siempre lo mismo, porque D y μ<sub>c</sub> no cambian.<br><br><b>Paso 3 · (ii) Después de una pasada.</b> h<sub>1</sub> = h<sub>i</sub> − μ<sub>c</sub>D = 3,2 − 1,2 = <b>2 m</b>.<br><br><b>Paso 4 · (iii) Cuántas pasadas para llegar a 0,8 m.</b><br>h<sub>n</sub> = h<sub>i</sub> − n·μ<sub>c</sub>D = 3,2 − 1,2n ≤ 0,8 &nbsp;⟹&nbsp; 1,2n ≥ 2,4 &nbsp;⟹&nbsp; <b>n = 2 pasadas</b> (y da exactamente 0,8 m).<br><br><b>Paso 5 · La trampa del "va y viene".</b> El patinador cruza el tramo rugoso una vez de ida, sube, vuelve a bajar y lo cruza otra vez de vuelta: cada <b>cruce</b> es una pasada, no cada ciclo completo. Después de la primera pasada llega a 2 m; después de la segunda (que es cuando vuelve), a 0,8 m. Y si te preguntaran cuándo se queda en el tramo rugoso: cuando la altura acumulada no alcance para cruzarlo entero.'},

  {st: '<b>Simulacro 2 · Problema 4</b> <span class="muted">(arquetipo: final UTN.BA «s/f (esfera)» problema 3 — caída libre + choque plástico en 2D; datos cambiados)</span>. Se deja caer una partícula de masa m<sub>1</sub> = 2 kg desde el reposo, desde una altura de 25 m. Un segundo después de iniciada su caída es alcanzada por un proyectil de masa m<sub>2</sub> = 0,5 kg, el cual, en el momento previo al impacto, tiene una velocidad horizontal hacia la derecha v<sub>2</sub> = 40 m/s. Si el proyectil queda incrustado en la partícula, determine el módulo de la velocidad con que el sistema llega al suelo.',
   ans: 'Justo después del choque: v<sub>x</sub> = 8 m/s y v<sub>y</sub> = 8 m/s (hacia abajo), a 20 m del piso · <b>|v| = 23,0 m/s</b> al llegar al suelo (v<sub>y</sub> = 21,5 m/s, v<sub>x</sub> = 8 m/s).',
   sol: '<b>Paso 1 · Estado justo antes del choque.</b> A t = 1 s de caída libre: v<sub>1</sub> = g·t = <b>10 m/s</b> hacia abajo, y ya bajó ½·10·1² = 5 m, o sea que está a <b>20 m del piso</b>. Anotá las dos cosas: la velocidad y la altura que <b>queda</b>.<br><br><b>Paso 2 · Choque plástico: p se conserva componente a componente.</b> El choque es instantáneo, así que el peso es despreciable frente a la fuerza de impacto. Masa total = 2,5 kg.<br>· Horizontal: 0,5·40 = 20 kg·m/s &nbsp;⟹&nbsp; v<sub>x</sub> = 20/2,5 = <b>8 m/s</b>.<br>· Vertical: 2·10 = 20 kg·m/s hacia abajo &nbsp;⟹&nbsp; v<sub>y</sub> = 20/2,5 = <b>8 m/s</b> hacia abajo.<br><span class="muted">Ojo: la cantidad de movimiento es un vector. Hay que plantear <b>dos</b> ecuaciones, una por eje. Sumar los módulos es el error típico.</span><br><br><b>Paso 3 · Después del choque, tiro oblicuo.</b> Desde 20 m, con v<sub>x</sub> = 8 m/s constante y v<sub>y0</sub> = 8 m/s hacia abajo:<br>v<sub>y</sub>² = v<sub>y0</sub>² + 2g·h = 64 + 2·10·20 = 464 &nbsp;⟹&nbsp; v<sub>y</sub> = <b>21,54 m/s</b>.<br><br><b>Paso 4 · Módulo final.</b><br>|v| = √(v<sub>x</sub>² + v<sub>y</sub>²) = √(64 + 464) = √528 = <b>23,0 m/s</b>.<br><br><b>Paso 5 · Hipótesis a declarar.</b> Desprecio la resistencia del aire; considero ambos cuerpos puntuales; el choque es perfectamente plástico (quedan pegados ⟹ una sola velocidad final) y dura un instante, por lo que durante el choque se conserva p pero <b>no</b> la energía cinética. Si te lo piden: la energía perdida en el choque es 100 + 400 − ½·2,5·128 = 500 − 160 = <b>340 J</b>.'},

  {st: '<b>Simulacro 2 · Problema 5</b> <span class="muted">(arquetipo: final UTN.BA 2/3/23, problema 5 — péndulo físico barra + disco; datos cambiados)</span>. Con una barra y un disco se construye un dispositivo para un reloj de péndulo antiguo. La barra tiene una longitud L = 1,5 m y una masa m<sub>b</sub> = 1 kg. El disco es homogéneo, de masa m<sub>d</sub> = 2 kg y radio r = 0,2 m. Si la distancia a entre el punto de suspensión y el centro del disco es de 1,2 m, halle el período de oscilación del péndulo. <span class="muted">Datos de la hoja: I<sub>CM</sub><sup>disco</sup> = ½mr², I<sub>CM</sub><sup>barra</sup> = mL²/12.</span>',
   ans: 'I<sub>O</sub> = 3,67 kg·m² · d<sub>CM</sub> = 1,05 m · <b>T = 2,14 s</b>.',
   sol: '<b>Paso 1 · La fórmula del péndulo físico.</b> T = 2π·√( I<sub>O</sub> / (M<sub>total</sub>·g·d<sub>CM</sub>) ), donde <b>I<sub>O</sub></b> es el momento de inercia respecto del <b>eje de suspensión</b> y <b>d<sub>CM</sub></b> la distancia de ese eje al centro de masa <b>del conjunto</b>. Todo el trabajo está en calcular esos dos números.<br><br><b>Paso 2 · Momento de inercia de la barra respecto del extremo (Steiner).</b><br>I<sub>barra</sub> = m<sub>b</sub>L²/12 + m<sub>b</sub>(L/2)² = m<sub>b</sub>L²/3 = 1·2,25/3 = <b>0,75 kg·m²</b>.<br><br><b>Paso 3 · Momento de inercia del disco respecto del mismo eje (Steiner otra vez).</b><br>I<sub>disco</sub> = ½m<sub>d</sub>r² + m<sub>d</sub>a² = ½·2·0,04 + 2·1,44 = 0,04 + 2,88 = <b>2,92 kg·m²</b>.<br>Fijate que el término de Steiner (2,88) es <b>72 veces</b> más grande que el propio: por eso la posición del disco es lo que gobierna el reloj.<br><br><b>Paso 4 · Sumar.</b> I<sub>O</sub> = 0,75 + 2,92 = <b>3,67 kg·m²</b>. Los momentos de inercia respecto del <b>mismo eje</b> se suman: esa es la única razón por la que hay que llevar los dos hasta el punto de suspensión antes de sumarlos.<br><br><b>Paso 5 · Centro de masa del conjunto.</b> Midiendo desde el eje:<br>d<sub>CM</sub> = (m<sub>b</sub>·L/2 + m<sub>d</sub>·a)/(m<sub>b</sub> + m<sub>d</sub>) = (1·0,75 + 2·1,2)/3 = 3,15/3 = <b>1,05 m</b>.<br><br><b>Paso 6 · Período.</b> M<sub>total</sub>·g·d<sub>CM</sub> = 3·10·1,05 = 31,5 N·m.<br>T = 2π·√(3,67/31,5) = 2π·√0,1165 = 2π·0,3413 = <b>2,14 s</b>.<br><br><b>Paso 7 · Hipótesis.</b> Oscilaciones de <b>amplitud pequeña</b> (sen θ ≈ θ): sin esa aproximación no existe la fórmula del período, porque el movimiento deja de ser armónico. Escribilo: es una de las hipótesis que la cátedra puntúa.'},

  {st: '<b>Simulacro 2 · Problema 6</b> <span class="muted">(arquetipo: final UTN.BA 2/3/23, problema 6 — balsa de troncos, hidrostática; datos cambiados)</span>. Cuatro chicos fabrican una balsa uniendo troncos cilíndricos de diámetro D = 0,25 m y longitud L = 1,5 m. Cada chico tiene una masa de 45 kg. Si la densidad del agua es δ<sub>a</sub> = 1000 kg/m³ y la de la madera es δ<sub>m</sub> = 600 kg/m³, ¿cuántos troncos serán necesarios como mínimo para mantenerlos a flote?',
   ans: 'Cada tronco sostiene 29,45 kg de carga · se necesitan 6,11 troncos ⟹ <b>7 troncos</b>.',
   sol: '<b>Paso 1 · Volumen de un tronco.</b> V = π·(D/2)²·L = π·(0,125)²·1,5 = π·0,015625·1,5 = <b>0,0736 m³</b>.<br><br><b>Paso 2 · La situación límite.</b> «Mantenerlos a flote como mínimo» significa que la balsa queda <b>justo totalmente sumergida</b>, con los chicos al ras del agua. Un tronco menos y se hunde.<br><br><b>Paso 3 · Equilibrio: empuje total = peso total.</b> Con n troncos:<br>δ<sub>a</sub>·(n·V)·g = (n·δ<sub>m</sub>·V + m<sub>chicos</sub>)·g<br>La g se cancela y todo queda en kilos:<br>n·V·(δ<sub>a</sub> − δ<sub>m</sub>) = m<sub>chicos</sub> &nbsp;⟹&nbsp; n·0,0736·400 = 4·45 = 180<br>n·29,45 = 180 &nbsp;⟹&nbsp; n = <b>6,11</b>.<br><br><b>Paso 4 · Redondeo con criterio físico.</b> Con 6 troncos el empuje neto es 176,7 kg &lt; 180 kg: se hunden. Hay que <b>redondear hacia arriba</b>: <b>7 troncos</b>. En estos problemas el redondeo es parte de la respuesta, no un detalle; escribí la comparación que lo justifica.<br><br><b>Paso 5 · La idea que hay que retener.</b> «Empuje neto por tronco» = (δ<sub>agua</sub> − δ<sub>madera</sub>)·V. Todo problema de flotación con carga se reduce a: <b>cuánta masa extra puede levantar cada unidad de volumen sumergido</b>. Con esa frase resolvés el témpano del oso polar, la balsa y el bloque con la capa de aceite.'}

]);

registerExercises('fisica1-utn-simulacros', '3', [

  {st: 'En el problema 1 del simulacro 2, la soga se acorta y la masa gira más rápido. ¿Qué magnitud se conserva y por qué?',
   opts: [
     'La energía cinética, porque la mesa no tiene rozamiento',
     'La cantidad de movimiento, porque no hay fuerzas externas horizontales',
     '<b>El momento angular respecto del agujero</b>, porque la tensión es una fuerza central y su torque es nulo',
     'La velocidad angular, porque nada la frena'
   ], c: 2,
   ex: 'La tensión siempre apunta al agujero, así que r y F son paralelos y τ = r × F = 0 respecto de ese punto: <b>L = m·v·r se conserva</b>, y de ahí sale v<sub>f</sub> = v<sub>i</sub>·r<sub>i</sub>/r<sub>f</sub>. ▸ Por qué las otras: la <b>a</b> es falsa aunque no haya rozamiento — la tensión <b>hace trabajo</b> mientras la soga se acorta y la energía cinética pasa de 2,25 J a 9 J; la <b>b</b> es falsa porque la tensión es una fuerza externa sobre m<sub>1</sub> y su p cambia de dirección todo el tiempo; la <b>d</b> es lo opuesto a lo que pasa: ω pasa de 5 a 20 rad/s.'},

  {st: 'El problema 2 dice «se le aplica un par de fuerzas de módulo F = 24 N». ¿Cómo entra ese par en las ecuaciones?',
   opts: [
     'Como una fuerza de 48 N hacia arriba del plano en la ecuación de traslación',
     'Como una fuerza de 24 N y además un momento de 24·R',
     'Como un momento de F·R = 7,2 N·m, tomado en el centro del disco',
     '<b>Resultante nula en la traslación y momento M = F·2R = 14,4 N·m</b> en la ecuación de rotación'
   ], c: 3,
   ex: 'Un <b>par</b> son dos fuerzas iguales y opuestas aplicadas en los extremos de un diámetro: se cancelan como fuerza, pero su momento vale F por la distancia entre las rectas de acción (2R) y es <b>el mismo respecto de cualquier punto</b>. Por eso la traslación queda gobernada sólo por el rozamiento y el peso, y el par empuja la rotación. ▸ Por qué las otras: la <b>a</b> y la <b>b</b> le inventan resultante a un par, que por definición no la tiene; la <b>c</b> usa R en lugar de 2R y te deja el momento a la mitad.'},

  {st: 'El problema 3 pregunta cuántas pasadas hacen falta para que la altura baje a 0,8 m. ¿Cuál es la forma corta de resolverlo?',
   opts: [
     'Plantear la energía en cada pasada por separado y repetir la cuenta hasta llegar',
     '<b>Ver que cada pasada cuesta siempre lo mismo</b>, Δh = μ<sub>c</sub>·D = 1,2 m, y despejar n de h<sub>i</sub> − n·Δh = h<sub>f</sub>',
     'Usar la fórmula de una progresión geométrica de razón μ<sub>c</sub>',
     'Calcular el tiempo total y dividirlo por el período del recorrido'
   ], c: 1,
   ex: 'El rozamiento disipa μ<sub>c</sub>·m·g·D en cada cruce, y esa energía dividida por mg da una <b>pérdida de altura constante</b> de 1,2 m por pasada, independiente de la velocidad con que llegue. Entonces 3,2 − 1,2n ≤ 0,8 ⟹ n = 2, en un renglón. ▸ Por qué las otras: la <b>a</b> llega al mismo resultado pero te cuesta diez minutos y tres oportunidades de equivocarte; la <b>c</b> es falsa — la pérdida es <b>aditiva</b> (siempre 1,2 m), no proporcional a la altura; la <b>d</b> mezcla un problema de energía con uno de cinemática que nadie pidió.'},

  {st: 'Para el péndulo físico del problema 5, ¿qué hace falta antes de poder usar T = 2π√(I/(Mgd))?',
   opts: [
     'Sumar los dos momentos de inercia tal como vienen en la hoja de datos',
     'Calcular sólo el centro de masa, porque los I<sub>CM</sub> ya te los dan',
     'Convertir el conjunto a un péndulo simple equivalente de longitud L = 1,5 m',
     '<b>Llevar los dos I<sub>CM</sub> al eje de suspensión con Steiner</b> y calcular el centro de masa del conjunto'
   ], c: 3,
   ex: 'Los datos impresos son <b>I respecto del centro de masa de cada pieza</b>, y la fórmula del período necesita I respecto del <b>eje de suspensión</b>. Hay que aplicar I = I<sub>CM</sub> + Md² a la barra (0,75 kg·m²) y al disco (2,92 kg·m²) y recién ahí sumarlos; además hace falta d<sub>CM</sub> = 1,05 m del conjunto. ▸ Por qué las otras: la <b>a</b> suma momentos referidos a ejes distintos, que es como sumar peras con manzanas — daría I = 0,165 kg·m² y un período absurdo; la <b>b</b> se olvida de la mitad del trabajo; la <b>c</b> no existe como atajo: la longitud equivalente es L<sub>eq</sub> = I<sub>O</sub>/(M·d<sub>CM</sub>) = 1,17 m, que hay que calcular igual.'},

  {st: 'Con el simulacro 2 sobre la mesa, ¿en qué orden lo hacés?',
   opts: [
     '<b>6 (balsa) → 3 (patinador) → 1 (momento angular) → 4 (choque 2D) → 2 (cupla) → 5 (péndulo físico)</b>',
     '1 → 2 → 3 → 4 → 5 → 6, respetando la numeración impresa',
     '5 y 2 primero, que son los de rígido y valen más',
     '4 primero porque el choque plástico es siempre de dos renglones'
   ], c: 0,
   ex: 'Arrancás por los dos más cortos (la balsa se cierra con una ecuación; el patinador, con una resta repetida), seguís con los dos de dificultad media (momento angular es una igualdad; el choque 2D son dos ecuaciones de p más una caída) y dejás para el final los dos caros: la cupla con la ecuación de torques y el péndulo físico con doble Steiner. Con los tres primeros ya tenés el 50%. ▸ Por qué las otras: la <b>b</b> es la estrategia del NOTA 3 del 2/3/23; la <b>c</b> gasta la mejor hora en los dos problemas más largos; la <b>d</b> subestima el 4 — es un choque en <b>dos dimensiones</b> con una etapa de caída libre antes y un tiro oblicuo después, no es de dos renglones.'}

]);

/* ==================== UNIDAD 4 · BANCO DE PREGUNTAS CONCEPTUALES ==================== */
// Verbatim de UTN Facultad Regional San Rafael (finales y parciales 2018-2020, altillo.com).
// OTRA REGIONAL: allá usan g = 9,8 m/s²; en FRBA la hoja imprime g = 10 m/s².
// Tu final de UTN.BA no tiene preguntas conceptuales: esto es gimnasio de justificación.

registerReveals('fisica1-utn-simulacros', '4', [

  {st: '<b>P1 · Recuperatorio 2018, tema 1, pregunta P1 · UTN San Rafael</b> <span class="muted">(otra regional — para entrenar la justificación, no es el formato de tu examen; allá g = 9,8 m/s², en FRBA g = 10)</span>. «Imagine que toma dos pelotas de tenis idénticas y llena una de agua. Deja caer las dos pelotas simultáneamente desde la azotea de un edificio alto. Si la resistencia del aire es insignificante, ¿cuál pelota llegará primero al piso? Explique. ¿Y si la resistencia del aire no es insignificante?»',
   ans: '<b>Sin aire: llegan juntas. Con aire: llega primero la llena de agua.</b>',
   sol: '<b>Sin resistencia:</b> la única fuerza es el peso, m·a = m·g ⟹ a = g <b>para cualquier masa</b>. Parten del reposo desde la misma altura, así que t = √(2h/g) es el mismo. Empatan.<br><br><b>Con resistencia:</b> aparece el arrastre D = ½·ρ·C·A·v², que depende del <b>tamaño y la forma</b> (idénticos: son la misma pelota por fuera) pero <b>no de la masa</b>. Entonces a = g − D/m: a igual velocidad, la pelota más pesada tiene el mismo D pero más m, o sea menor D/m y mayor aceleración. Su velocidad límite (donde D = mg) también es mayor. <b>Llega primero la llena de agua.</b><br><br><span class="muted">La frase que hay que decir: «la aceleración de caída libre no depende de la masa <b>porque la fuerza que acelera es proporcional a la masa</b>; en cuanto aparece una fuerza que no lo es (el arrastre), la masa vuelve a importar».</span>'},

  {st: '<b>P2 · Recuperatorio 2018, tema 1, pregunta P2 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «En un mundo sin fricción, ¿cuál de las siguientes actividades podría usted hacer (o no hacer)? Explique su razonamiento. a) Manejar por una curva de autopista sin peralte; b) saltar en el aire; c) empezar a caminar en una acera horizontal; d) subir por una escalera vertical; e) cambiar de carril en una carretera.»',
   ans: '<b>Se puede: b) saltar y d) subir la escalera. No se puede: a) la curva sin peralte, c) empezar a caminar, e) cambiar de carril.</b>',
   sol: '<b>El criterio único:</b> sin fricción una superficie sólo puede ejercer fuerza <b>normal</b> (perpendicular a ella). Toda maniobra que necesite una fuerza <b>paralela</b> al piso horizontal es imposible.<br><br><b>a) NO.</b> En una curva plana la fuerza centrípeta la da el rozamiento (f = mv²/R). Sin peralte la normal es vertical y no tiene componente horizontal: el auto sigue recto por la primera ley. <span class="muted">Con peralte sí se podría: ahí la normal se inclina y aporta la centrípeta.</span><br><b>b) SÍ.</b> Se salta empujando el piso hacia abajo; la reacción es la normal, vertical. No hace falta fricción.<br><b>c) NO.</b> Caminar es empujar el piso hacia atrás para que te empuje hacia adelante: esa fuerza horizontal es rozamiento estático.<br><b>d) SÍ.</b> Te agarrás de los peldaños horizontales y tirás; el peldaño te empuja con una <b>normal vertical</b> hacia arriba.<br><b>e) NO.</b> Cambiar de carril pide aceleración lateral, y en camino plano sólo el rozamiento puede darla.'},

  {st: '<b>P3 · Final de Abril de 2019, pregunta P1 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Explique por qué razón la función y(t) = |3t − 4| no puede ser una función posición físicamente factible.»',
   ans: '<b>Porque en t = 4/3 s la velocidad salta de −3 a +3 m/s: la aceleración sería infinita y haría falta una fuerza infinita.</b>',
   sol: 'Derivo a los dos lados del quiebre:<br>· Para t &lt; 4/3 s: y(t) = 4 − 3t ⟹ v = <b>−3 m/s</b>.<br>· Para t &gt; 4/3 s: y(t) = 3t − 4 ⟹ v = <b>+3 m/s</b>.<br>La posición es continua (en t = 4/3 vale 0), pero la <b>velocidad no lo es</b>: Δv = 6 m/s en Δt → 0, así que a = Δv/Δt → ∞, y por la segunda ley F = ma → ∞.<br><br><b>El criterio general:</b> una función posición físicamente aceptable tiene que ser continua <b>y con derivada primera continua</b> (clase C¹), porque un cuerpo de masa finita bajo fuerzas finitas no puede cambiar su velocidad en tiempo nulo. El módulo introduce un pico donde las derivadas laterales existen pero no coinciden.'},

  {st: '<b>P4 · Final de Marzo de 2020, pregunta P3 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Un secarropas gira con velocidad angular constante. ¿Un punto en su borde tiene aceleración tangencial? ¿Y aceleración radial? ¿Estas aceleraciones tienen magnitud constante? ¿Y dirección constante? Justifique.»',
   ans: '<b>a<sub>t</sub> = 0 · a<sub>r</sub> = ω²R ≠ 0 · módulo constante · dirección variable</b> (siempre hacia el centro, pero el centro queda en distinta dirección a cada instante).',
   sol: '<b>Tangencial:</b> a<sub>t</sub> = α·R y α = dω/dt = 0 porque ω es constante ⟹ <b>a<sub>t</sub> = 0</b>. La <i>rapidez</i> v = ωR no cambia.<br><br><b>Radial:</b> a<sub>r</sub> = v²/R = ω²R ≠ 0, siempre <b>hacia el eje</b>. Es la que cambia la <b>dirección</b> de la velocidad, y es la única componente presente.<br><br><b>Módulo:</b> los dos son constantes (0 y ω²R, con ω y R fijos).<br><br><b>Dirección:</b> la de a<sub>r</sub> <b>no</b> es constante: apunta siempre al centro, pero como el punto gira, el versor radial rota con él y en una vuelta el vector barre los 360°. En forma vectorial a = −ω²R(cos ωt, sen ωt).<br><br><span class="muted">Conclusión que hay que decir: el movimiento es <b>acelerado aunque la rapidez no cambie</b>, y por eso el tambor tiene que empujar la ropa hacia adentro con N = mω²R — que es lo que centrifuga.</span>'},

  {st: '<b>P5 · Final de Marzo de 2020, pregunta P1 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Diga si la siguiente afirmación es correcta: <i>En ausencia de resistencia del aire, la trayectoria de un proyectil lanzado cerca de la superficie terrestre es una elipse, no una parábola.</i> Justifique.»',
   ans: '<b>Es correcta en sentido estricto:</b> la trayectoria exacta es un arco de elipse con un foco en el centro de la Tierra; la parábola es la aproximación de campo uniforme.',
   sol: '<b>De dónde sale la parábola:</b> de suponer <b>g uniforme</b> (mismo módulo y misma dirección en todo punto). Con esa hipótesis a<sub>x</sub> = 0 y a<sub>y</sub> = −g, e integrando queda y(x) = x·tgθ<sub>0</sub> − gx²/(2v<sub>0</sub>²cos²θ<sub>0</sub>): una parábola.<br><br><b>Qué pasa en realidad:</b> la gravedad es una fuerza central F = −GM<sub>T</sub>m/r², dirigida al <b>centro</b> de la Tierra (no «hacia abajo» en direcciones paralelas) y de módulo creciente al bajar. Bajo una fuerza central 1/r² las trayectorias son cónicas con un foco en el centro de fuerzas, y para un cuerpo ligado (E &lt; 0) la cónica es una <b>elipse</b>.<br><br><b>Por qué no se nota:</b> el proyectil recorre un arco minúsculo de esa elipse (metros frente a R<sub>T</sub> ≈ 6,37·10⁶ m), y ahí la elipse es indistinguible de una parábola. La parábola es el <b>límite</b> de la elipse cuando el alcance es muy chico frente al radio terrestre.<br><br><span class="muted">Ésta es la pregunta ideal para entrenar el reflejo de decir <b>bajo qué hipótesis</b> vale una fórmula: en tu final vas a escribir «supongo campo uniforme» sin pensarlo, y esto te recuerda que es una suposición.</span>'},

  {st: '<b>P6 · Final de Noviembre de 2019, pregunta P1 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Una caja grande cuelga del extremo de una cuerda vertical. ¿La tensión en la cuerda es mayor cuando la caja está en reposo o cuando sube con rapidez constante? Si la caja sube, ¿la tensión en la cuerda es mayor cuando está acelerando o cuando está frenando? En cada caso, explique en términos de las leyes del movimiento de Newton.»',
   ans: '<b>Reposo y rapidez constante: la misma tensión, T = mg.</b> Subiendo: <b>mayor cuando acelera</b> (T &gt; mg) y menor cuando frena (T &lt; mg).',
   sol: 'Eje y positivo hacia arriba. DCL: la cuerda tira con T hacia arriba, el peso mg hacia abajo. Segunda ley:<br><b>T − mg = m·a<sub>y</sub> &nbsp;⟹&nbsp; T = m(g + a<sub>y</sub>)</b>.<br><br><b>Primera parte:</b> «rapidez constante» ⟹ a<sub>y</sub> = 0, exactamente igual que en reposo (primera ley). En los dos casos <b>T = mg</b>. El error típico es pensar que subir «cuesta más tensión»: lo que cuesta tensión es <b>cambiar</b> la velocidad, no tenerla.<br><br><b>Segunda parte:</b> subiendo y acelerando, a<sub>y</sub> &gt; 0 ⟹ T = m(g + a) &gt; mg. Subiendo y frenando, la aceleración apunta hacia abajo ⟹ T = m(g − |a|) &lt; mg. Si el frenado fuera tan brusco que |a| &gt; g, la cuerda quedaría floja (T = 0): una cuerda no puede empujar.<br><br><span class="muted">Frase para memorizar: <b>velocidad constante ⟹ a = 0 ⟹ ΣF = 0</b>. Resuelve media docena de preguntas de este banco.</span>'},

  {st: '<b>P7 · Final de Abril de 2019, pregunta P3 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Un caballo está enganchado a un carro. Puesto que el carro tira hacia atrás del caballo tan fuerte como éste tira del carro, ¿por qué el carro no está en equilibrio, sin importar qué tan fuerte el caballo tire del carro?»',
   ans: '<b>Porque las dos fuerzas del par acción-reacción actúan sobre cuerpos distintos y nunca se cancelan entre sí.</b> El equilibrio del carro se decide con <b>su</b> DCL.',
   sol: 'El par es T<sub>(caballo→carro)</sub> = −T<sub>(carro→caballo)</sub>: mismo módulo, sentidos opuestos, pero <b>una se aplica al carro y la otra al caballo</b>. Nunca aparecen en el mismo diagrama.<br><br><b>DCL del carro:</b> la tensión T hacia adelante y el rozamiento del suelo f<sub>c</sub> hacia atrás. ΣF = T − f<sub>c</sub> = m<sub>c</sub>·a. Si T &gt; f<sub>c</sub>, el carro acelera. <b>No está en equilibrio.</b><br><br><b>DCL del caballo:</b> la tensión T hacia atrás y el rozamiento del suelo sobre los cascos F<sub>s</sub> hacia adelante (el caballo empuja el suelo hacia atrás y el suelo lo empuja hacia adelante). ΣF = F<sub>s</sub> − T = m<sub>h</sub>·a.<br><br><b>Sistema completo:</b> ahí sí T y su reacción son <b>internas</b> y se cancelan: ΣF = F<sub>s</sub> − f<sub>c</sub> = (m<sub>h</sub> + m<sub>c</sub>)a. El conjunto avanza gracias a una tercera fuerza externa que casi nadie nombra: <b>el rozamiento del suelo sobre los cascos</b>.'},

  {st: '<b>P8 · Final de Febrero de 2020, pregunta P4 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Si un camión grande y pesado choca con un auto, es más probable que se lesionen los ocupantes del auto que el conductor del camión. ¿Por qué? ¿Qué magnitud física es importante en esta pregunta?»',
   ans: '<b>Las fuerzas son iguales (tercera ley); las aceleraciones no.</b> La magnitud clave es la <b>masa</b> (la inercia): a = F/m.',
   sol: '<b>Tercera ley:</b> |F<sub>camión→auto</sub>| = |F<sub>auto→camión</sub>| = F. El camión <b>no</b> le hace más fuerza al auto que el auto al camión.<br><br><b>Segunda ley:</b> a<sub>auto</sub> = F/m<sub>auto</sub> y a<sub>camión</sub> = F/m<sub>camión</sub>. Con 20 000 kg contra 1000 kg, el auto sufre <b>20 veces</b> más aceleración.<br><br><b>En términos de impulso:</b> ambos reciben el mismo J = F·Δt, o sea el mismo |Δp|, pero |Δv| = |Δp|/m es mucho mayor para el auto.<br><br><b>Por qué lesiona:</b> los ocupantes tienen que cambiar su velocidad junto con el vehículo, y el cinturón o el airbag deben ejercer sobre cada persona F = m<sub>persona</sub>·a<sub>vehículo</sub>. La lesión se correlaciona con la <b>aceleración</b> y con el Δv, no con la fuerza de contacto entre los dos vehículos.'},

  {st: '<b>P9 · Recuperatorio 2018, tema 1, pregunta P4 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Las básculas pueden dividirse en las que usan resortes y las que usan masas estándar para equilibrar masas desconocidas. ¿Cuál grupo sería más exacto en una nave espacial en aceleración? ¿Y en la Luna?»',
   ans: '<b>La de masas estándar en los dos casos</b>, porque compara dos pesos y la gravedad efectiva se cancela.',
   sol: '<b>Qué mide cada una:</b><br>· <b>Resorte (dinamómetro):</b> mide la <b>fuerza</b> F = m·g<sub>ef</sub>, y su escala está calibrada dividiendo por el g terrestre. Sólo acierta donde g<sub>ef</sub> = 9,8 m/s².<br>· <b>Masas patrón (balanza de dos platillos):</b> el equilibrio es m<sub>desconocida</sub>·g<sub>ef</sub> = m<sub>patrón</sub>·g<sub>ef</sub>, y <b>g<sub>ef</sub> se cancela</b>: da la masa correcta valga lo que valga.<br><br><b>Nave acelerando:</b> gana la de masas patrón — la aceleración afecta por igual a los dos platillos. La de resorte marcaría m·a<sub>nave</sub>/9,8, un valor erróneo. <span class="muted">Salvedad honesta: si la nave no acelerara (o cayera libremente) g<sub>ef</sub> = 0 y la balanza de brazos no daría lectura, aunque tampoco daría una lectura equivocada.</span><br><br><b>En la Luna:</b> otra vez la de masas patrón. La de resorte marcaría m·g<sub>L</sub>/g<sub>T</sub> ≈ m/6.'},

  {st: '<b>P10 · Recuperatorio 2018, tema 1, pregunta P5 · UTN San Rafael</b> <span class="muted">(otra regional; ojo con el 9,8 — en FRBA es 10)</span>. «La aceleración de un cuerpo que cae se mide en un elevador que viaja hacia arriba a una rapidez constante de 9.8 m/s. ¿Qué resultado se obtiene?»',
   ans: '<b>Se mide g</b> (9,8 m/s² allá; 10 m/s² en FRBA), exactamente igual que en el piso.',
   sol: '<b>El dato es una trampa doble:</b> 9,8 m/s es una <b>rapidez</b> (m/s, no m/s²) y además es <b>constante</b>.<br><br>Si el ascensor sube con velocidad constante, su aceleración es cero, así que es un <b>sistema de referencia inercial</b>, tan válido como el piso del edificio. Las aceleraciones medidas desde dos sistemas con velocidad relativa constante son iguales:<br>a<sub>cuerpo/ascensor</sub> = a<sub>cuerpo/tierra</sub> − a<sub>ascensor/tierra</sub> = g − 0 = <b>g</b>.<br><br><span class="muted">Sólo si el ascensor <b>acelerara</b> con aceleración a la medición daría g − a: eso es la «gravedad aparente». Y una advertencia de traducción: en tu final FRBA imprime <b>g = 10 m/s²</b>; el 9,8 de esta hoja es de San Rafael.</span>'},

  {st: '<b>P11 · Final de Julio de 2018, pregunta P1 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Un automóvil aumenta su rapidez mientras el motor produce potencia constante. ¿La aceleración es mayor al inicio de este proceso o al final? Explique su respuesta.»',
   ans: '<b>Mayor al inicio</b>: con P constante, a = P/(m·v), inversamente proporcional a la rapidez.',
   sol: 'La potencia mecánica es P = F·v. Si la fuerza impulsora neta es la que acelera, F = m·a, entonces<br><b>P = m·a·v &nbsp;⟹&nbsp; a = P/(m·v)</b>.<br>Con P y m constantes, la aceleración es <b>inversamente proporcional a v</b>: al principio v es chica y a es grande; a medida que el auto gana rapidez, a cae (y en la práctica, cuando aparece el arrastre aerodinámico, llega a cero en la velocidad máxima).<br><br><b>Justificación energética (la que suma):</b> a potencia constante el motor entrega la misma energía por segundo, pero conseguir el mismo Δv a alta rapidez cuesta mucha más energía, porque E<sub>c</sub> crece con v²: ΔE<sub>c</sub> ≈ m·v·Δv. Cada m/s adicional «sale más caro» y por eso tarda más.'},

  {st: '<b>P12 · Final de Noviembre de 2019, pregunta P2 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Una caja se desliza hacia abajo por una rampa, en tanto que las fuerzas de gravedad y de fricción realizan trabajo sobre ella. El trabajo realizado por cada una de estas fuerzas ¿puede expresarse en términos del cambio en una función de energía potencial? Para cada fuerza explique el porqué.»',
   ans: '<b>La gravedad sí</b> (es conservativa: W = −ΔU con U = mgy). <b>La fricción no</b> (depende del camino).',
   sol: '<b>El criterio:</b> sólo una fuerza <b>conservativa</b> admite energía potencial, y conservativa significa que su trabajo entre dos puntos <b>no depende del camino</b> (equivalentemente, es nulo en todo camino cerrado).<br><br><b>Gravedad → SÍ.</b> W<sub>grav</sub> = mg·y<sub>i</sub> − mg·y<sub>f</sub> = −ΔU con U = mgy. Depende sólo de las alturas: da lo mismo bajar por una rampa larga, corta o en escalones. Bajando una altura h = L·senα, W = +mgL·senα.<br><br><b>Fricción cinética → NO.</b> Dos motivos: (i) W<sub>fr</sub> = −μ<sub>c</sub>·N·<b>L</b>, proporcional a la <b>longitud del camino</b>, así que por caminos más largos disipa más; (ii) en un ciclo cerrado el trabajo no es cero, siempre es negativo, porque la fuerza se da vuelta cuando se invierte la velocidad. No existe ninguna función de estado U cuya variación lo represente.<br><br><b>Balance completo:</b> ½mv<sub>f</sub>² − ½mv<sub>i</sub>² = mgh − μ<sub>c</sub>mg·cosα·L. La gravedad va <b>adentro</b> de la energía potencial y la fricción obligatoriamente <b>afuera</b>, en W<sub>nc</sub>.'},

  {st: '<b>P13 · Recuperatorio 2018, tema 1, pregunta P3 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Un resorte atado en su posición comprimida se disuelve en ácido. ¿Qué pasa con su energía potencial?»',
   ans: '<b>No desaparece: se degrada a energía interna</b> del sistema resorte-ácido (calor), y se ve como un aumento de temperatura de la solución.',
   sol: 'Mientras está atado y comprimido, el resorte almacena U = ½kx² en la deformación elástica de su red cristalina. Cuando el ácido va rompiendo los enlaces que sostenían esa tensión, la energía almacenada se libera gradualmente hacia los átomos y moléculas que se separan: se convierte en <b>energía interna</b> (cinética desordenada), es decir en calor, más algo de agitación del líquido.<br><br><b>El balance es el mismo que si cortaras el hilo:</b> ahí la energía elástica se volvería primero cinética del resorte y después, por rozamiento con el aire y disipación interna, también energía interna. Sólo cambia el camino, no el destino.<br><br><span class="muted">Lo que la pregunta evalúa es que no digas «se pierde». La energía no se pierde nunca: se <b>degrada</b>, y por eso la energía potencial elástica es recuperable pero la interna no.</span>'},

  {st: '<b>P14 · Final de Marzo de 2019, pregunta P1 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Se dispara una ametralladora hacia una placa de acero. ¿La fuerza media que actúa sobre la placa por los impactos es mayor si las balas rebotan o si se aplastan y pegan a la placa? Explique.»',
   ans: '<b>Mayor si rebotan</b>, hasta el doble si el rebote fuera perfectamente elástico.',
   sol: 'Teorema del impulso, bala por bala: J = F<sub>media</sub>·Δt = Δp.<br><br><b>Caso A, se pegan (plástico):</b> p<sub>i</sub> = mv, p<sub>f</sub> = 0 ⟹ |Δp<sub>A</sub>| = <b>mv</b>.<br><b>Caso B, rebotan con rapidez v<sub>r</sub>:</b> p<sub>i</sub> = mv, p<sub>f</sub> = −mv<sub>r</sub> ⟹ |Δp<sub>B</sub>| = <b>m(v + v<sub>r</sub>)</b>.<br>Como |Δp<sub>B</sub>| &gt; |Δp<sub>A</sub>|, y por tercera ley la placa recibe el impulso opuesto, con una cadencia de N balas por segundo:<br>F<sub>media</sub>(rebote) = N·m(v + v<sub>r</sub>) &gt; F<sub>media</sub>(se pegan) = N·m·v.<br><br><b>La razón física en una frase:</b> al rebotar, la placa no sólo tiene que <b>frenar</b> la bala, además tiene que <b>impulsarla</b> en sentido contrario, así que le entrega más cantidad de movimiento. En el límite elástico (v<sub>r</sub> = v) el impulso es exactamente el doble.'},

  {st: '<b>P15 · Final de Agosto de 2018, pregunta P2 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Una partícula puntual viaja en línea recta con rapidez constante y la distancia más cercana que parte del origen de las coordenadas es una distancia l. Con respecto a este origen, ¿la partícula tiene momento lineal cero? Conforme la partícula se mueve en línea recta, ¿cambia su momento angular con respecto al origen?»',
   ans: '<b>p no es cero</b> (y es constante) · <b>L tampoco cambia:</b> vale L = m·v·l y se conserva.',
   sol: '<b>Momento lineal:</b> p = m·v <b>no se define respecto de un punto</b>, se define respecto de un sistema de referencia; no depende del origen que elijas. Con rapidez constante y no nula, p es distinto de cero y además constante (no hay fuerza neta).<br><br><b>Momento angular:</b> L = r × p, de módulo L = m·v·r·senθ = m·v·d<sub>⊥</sub>, donde d<sub>⊥</sub> es la distancia <b>perpendicular</b> del origen a la recta de movimiento. Esa distancia es justamente la de máximo acercamiento, <b>l</b>, y es la misma en todo instante porque la recta es fija:<br><b>L = m·v·l = constante</b>, con dirección perpendicular al plano y siempre la misma.<br><br><b>Coherencia:</b> fuerza neta nula ⟹ torque nulo respecto de cualquier punto ⟹ dL/dt = 0. Una partícula libre tiene momento angular <b>constante y en general no nulo</b>: no hace falta girar para tener L.'},

  {st: '<b>P16 · Final de Julio de 2018, pregunta P2 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Al calcular el momento de inercia de un objeto, ¿podemos tratar toda su masa como si estuviera concentrada en el centro de masa del objeto? Justifique su respuesta.»',
   ans: '<b>No.</b> I = Σm<sub>i</sub>r<sub>i</sub>² depende de cómo está <b>distribuida</b> la masa. Lo correcto es Steiner: I = I<sub>CM</sub> + M·d².',
   sol: '<b>Contraejemplo inmediato:</b> si concentráramos toda la masa en el centro de masa y el eje pasara por ahí, daría I = M·0² = 0, que es absurdo — un disco tiene ½MR² y una esfera 2/5·MR² girando sobre su propio eje.<br><br><b>Lo correcto:</b> I = I<sub>CM</sub> + M·d². El término M·d² <b>sí</b> es «toda la masa concentrada en el CM, a distancia d del eje», pero hay que <b>sumarle I<sub>CM</sub></b>, que es exactamente la contribución de la distribución de masa alrededor del centro. La aproximación puntual sólo vale si el cuerpo es chico frente a d (I<sub>CM</sub> ≪ Md²).<br><br><b>El contraste que conviene decir:</b> para la <b>traslación</b> sí se puede tratar al cuerpo como una masa puntual en el CM (ΣF = M·a<sub>CM</sub>), y también para la energía potencial gravitatoria. Para la <b>rotación</b>, no.<br><br><span class="muted">Ésta es la pregunta que más se parece a lo que tu final te va a exigir sin preguntártelo: Steiner en el péndulo físico y en toda rodadura.</span>'},

  {st: '<b>P17 · Final de Abril de 2019, pregunta P5 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «¿Cómo podría usted determinar experimentalmente el momento de inercia de un cuerpo de forma irregular alrededor de un eje dado?»',
   ans: '<b>Como péndulo físico:</b> se mide el período de oscilaciones chicas y se despeja I<sub>O</sub> = M·g·d·T²/(4π²); después se traslada al eje pedido con Steiner.',
   sol: '<b>Método 1 · Péndulo físico (el que se espera).</b><br>1) Medir la masa M. 2) Ubicar el centro de masa colgando el cuerpo de dos puntos distintos y cruzando las verticales. 3) Suspenderlo de un eje horizontal O con rozamiento despreciable. 4) Medir d = distancia de O al CM. 5) Apartarlo un ángulo <b>pequeño</b> (menos de 5°, para que valga sen θ ≈ θ) y cronometrar N oscilaciones (20 a 50) para que T = t/N tenga poco error.<br>De Στ = Iα con ángulo chico sale T = 2π√(I<sub>O</sub>/(Mgd)) ⟹ <b>I<sub>O</sub> = M·g·d·T²/(4π²)</b>.<br>6) Si el eje pedido no es el de suspensión, se pasa con Steiner: I<sub>CM</sub> = I<sub>O</sub> − Md², y después I<sub>eje</sub> = I<sub>CM</sub> + M·d′².<br><br><b>Método 2 · Péndulo de torsión.</b> Colgar el cuerpo de un alambre a lo largo del eje: T = 2π√(I/k) ⟹ I = kT²/(4π²), calibrando k con un cuerpo de I conocido.<br><br><b>Método 3 · Torque conocido.</b> Enrollar un hilo en un tambor de radio r solidario al eje y colgar una masa m que cae; midiendo la aceleración a con h = ½at² se despeja I ≈ m·r²(g/a − 1).<br><br><b>Método 4 · Rodadura</b> (sólo si es de revolución): a = g·senβ/(1 + I<sub>CM</sub>/MR²) ⟹ I<sub>CM</sub> = MR²(g·senβ/a − 1).'},

  {st: '<b>P18 · Final de Noviembre de 2019, pregunta P3 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Si la amplitud de un péndulo simple aumenta, ¿debería aumentar o disminuir su periodo? Mencione un argumento cualitativo. ¿Su argumento también es válido para un péndulo físico?»',
   ans: '<b>El período aumenta</b>, y <b>sí</b>, el argumento vale igual para el péndulo físico.',
   sol: '<b>Argumento cualitativo:</b> la ecuación exacta es d²θ/dt² = −(g/L)·sen θ, y la aproximación armónica que da T<sub>0</sub> = 2π√(L/g) —independiente de la amplitud— reemplaza sen θ por θ. Como <b>sen θ &lt; θ</b> para todo θ &gt; 0, el torque restaurador <b>real es menor</b> que el del modelo lineal, y la diferencia crece con el ángulo. Un «resorte más blando» devuelve la masa más despacio: el período se alarga.<br><br><b>Cuantitativamente (serie de Borda):</b> T = T<sub>0</sub>·[1 + ¼·sen²(θ<sub>0</sub>/2) + (9/64)·sen⁴(θ<sub>0</sub>/2) + …]. Para θ<sub>0</sub> = 30° el período es ~1,7 % mayor; para 90°, ~18 %.<br><br><b>Péndulo físico:</b> su ecuación es I·d²θ/dt² = −Mgd·sen θ, formalmente idéntica con g/L → Mgd/I. Aparece el mismo sen θ, así que el mismo argumento y la misma corrección se aplican. El péndulo simple es el caso particular I = mL², d = L.<br><br><span class="muted">Consecuencia práctica para tu final: cuando uses T = 2π√(I/Mgd), <b>escribí</b> «para amplitudes pequeñas». Es una hipótesis, no un detalle.</span>'},

  {st: '<b>P19 · Final de Febrero de 2020, pregunta P1 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Usted empuja un trozo de madera para que quede bajo la superficie de una alberca. Después de que está sumergido por completo, usted sigue empujándolo más y más profundamente. Conforme usted hace esto, ¿qué sucederá a la fuerza de flotación sobre el trozo de madera? ¿Esta fuerza seguirá aumentando, permanecerá igual o disminuirá? ¿Por qué?»',
   ans: '<b>Permanece igual.</b> E = ρ·g·V<sub>desplazado</sub>, y una vez totalmente sumergido V<sub>desplazado</sub> es el volumen del cuerpo y ya no cambia.',
   sol: '<b>Por Arquímedes:</b> E = ρ<sub>agua</sub>·g·V<sub>desplazado</sub>. Mientras se hunde parcialmente, V<sub>desplazado</sub> crece y E crece. Apenas queda <b>totalmente sumergido</b>, V<sub>desplazado</sub> = V<sub>cuerpo</sub> = constante, y como el agua es prácticamente incompresible y g no cambia, el empuje se congela.<br><br><b>La justificación fuerte, por presiones</b> (es la que hace la respuesta completa): tomo un prisma de área A y altura h con la cara superior a profundidad y:<br>E = (p<sub>abajo</sub> − p<sub>arriba</sub>)·A = [ρg(y+h) − ρgy]·A = <b>ρ·g·h·A = ρ·g·V</b>.<br>El término ρgy <b>se cancela</b>: al bajar el cuerpo aumentan las dos presiones en la misma cantidad, y el empuje sale de la <b>diferencia</b>, no de la presión absoluta.<br><br><span class="muted">Salvedad que suma puntos: si la madera fuera porosa y absorbiera agua, o si se considerara la compresibilidad, V bajaría un poco y el empuje también. En el modelo ideal, permanece igual.</span>'},

  {st: '<b>P20 · Final de Marzo de 2020, pregunta P2 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «La presión del aire disminuye al aumentar la altitud. ¿Por qué entonces el aire cerca de la superficie no es succionado continuamente hacia las regiones altas que están a menor presión?»',
   ans: '<b>Porque la atmósfera está en equilibrio hidrostático:</b> el gradiente de presión es exactamente el que hace falta para sostener el peso del aire, dP/dy = −ρg.',
   sol: 'Tomo un elemento de aire de área A y espesor dy. Fuerzas verticales: P(y)·A hacia arriba, P(y+dy)·A hacia abajo y el peso ρ·A·dy·g hacia abajo. En equilibrio:<br>P(y)A − P(y+dy)A − ρgA·dy = 0 &nbsp;⟹&nbsp; <b>dP/dy = −ρg</b>.<br>La fuerza neta por unidad de volumen es −dP/dy − ρg = ρg − ρg = <b>0</b>: el empuje de presión hacia arriba ya está íntegramente «gastado» en sostener el peso.<br><br><b>Dos aclaraciones que cierran la respuesta:</b><br>· La <b>succión no es una fuerza</b>. No existe nada que «tire» desde la zona de baja presión: lo único que hay son empujes de contacto, que van siempre de mayor a menor presión.<br>· Para que el aire acelerara hacia arriba haría falta |dP/dy| &gt; ρg, es decir un gradiente <b>superior</b> al hidrostático. Eso pasa localmente y produce vientos, corrientes ascendentes y tormentas; en promedio la atmósfera está en equilibrio y no se vacía.<br><br><span class="muted">Analogía válida: en un vaso la presión abajo también es mayor que arriba, y el agua no se escapa hacia arriba.</span>'},

  {st: '<b>P21 · Final de Agosto de 2018, pregunta P1 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Un trozo de hierro está pegado encima de un bloque de madera. Si éste se coloca en una cubeta de agua con el hierro arriba, flota. Ahora se voltea el bloque para que el hierro quede sumergido bajo el bloque. ¿El bloque flotará o se hundirá? ¿El nivel de agua en la cubeta subirá, bajará o no cambiará? Explique.»',
   ans: '<b>Sigue flotando</b> y el <b>nivel no cambia</b>.',
   sol: '<b>Condición de flotación:</b> E = P ⟹ ρ<sub>agua</sub>·g·V<sub>desplazado</sub> = (m<sub>Fe</sub> + m<sub>mad</sub>)·g ⟹<br>V<sub>desplazado</sub> = (m<sub>Fe</sub> + m<sub>mad</sub>)/ρ<sub>agua</sub>.<br>Ese volumen depende <b>sólo de la masa total y de la densidad del agua</b>: no depende de la orientación.<br><br><b>¿Flota?</b> Sí. La densidad media del conjunto, (m<sub>Fe</sub>+m<sub>mad</sub>)/(V<sub>Fe</sub>+V<sub>mad</sub>), es la misma dado vuelta o no, y como era menor que la del agua (flotaba), lo sigue siendo. Lo que cambia es el reparto: ahora el hierro sumergido aporta su propio empuje y la madera queda <b>menos</b> sumergida que antes.<br><br><b>¿Y el nivel?</b> No cambia: el volumen de agua desplazado es idéntico porque el peso total no cambió. Mismo volumen desplazado, mismo nivel.<br><br><span class="muted">La trampa es creer que «hundir el hierro» hace desplazar más agua. Lo que fija el desplazamiento es el <b>peso</b>, no dónde está cada pieza.</span>'},

  {st: '<b>P22 · Final de Agosto de 2018, pregunta P3 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «Un planeta gira con una órbita circular con periodo T alrededor de una estrella. Si fuera a orbitar a la misma distancia de una estrella con una masa cuatro veces mayor que la estrella original, ¿cuánto sería el nuevo período? (en términos de T)»',
   ans: '<b>T′ = T/2.</b>',
   sol: 'En órbita circular la gravedad <b>es</b> la fuerza centrípeta:<br>G·M·m/r² = m·ω²·r = m·(4π²/T²)·r &nbsp;⟹&nbsp; <b>T² = 4π²r³/(G·M)</b> (tercera ley de Kepler).<br><br>Con r fijo, T es inversamente proporcional a √M:<br>T′/T = √(M/M′) = √(1/4) = <b>1/2</b> &nbsp;⟹&nbsp; T′ = T/2.<br><br><span class="muted">La frase que hay que decir en cualquier problema de órbita: «igualo la atracción gravitatoria a la fuerza centrípeta». Con eso salen todos, incluido el problema 5 del final del 13/2/25.</span>'},

  {st: '<b>P23 · Final de Marzo de 2020, pregunta P4 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «¿Entre qué límites de posiciones del objeto, un espejo esférico cóncavo forma una imagen real? ¿Y un espejo esférico convexo? Justifique.»',
   ans: '<b>Cóncavo:</b> imagen real si el objeto está más allá del foco (f &lt; s &lt; ∞). <b>Convexo:</b> nunca forma imagen real de un objeto real.',
   sol: 'Con 1/s + 1/s′ = 1/f = 2/R, la imagen es <b>real</b> si s′ &gt; 0 y <b>virtual</b> si s′ &lt; 0. Despejando: s′ = s·f/(s − f).<br><br><b>Cóncavo (f = R/2 &gt; 0):</b><br>· s &gt; f ⟹ s′ &gt; 0: <b>imagen real</b>, invertida.<br>· s = f ⟹ s′ → ∞: los rayos salen paralelos, no hay imagen.<br>· 0 &lt; s &lt; f ⟹ s′ &lt; 0: imagen <b>virtual</b>, derecha y aumentada (el espejo de maquillaje).<br>Subcasos de la imagen real: si s &gt; R queda entre F y C, invertida y menor; si s = R queda en C, del mismo tamaño; si f &lt; s &lt; R queda más allá de C, invertida y mayor.<br><br><b>Convexo (f &lt; 0):</b> s′ = s·f/(s − f) tiene numerador negativo y denominador positivo para todo s &gt; 0 ⟹ <b>s′ &lt; 0 siempre</b>: la imagen es virtual, derecha y menor, detrás del espejo entre el vértice y el foco. Por eso se usan como espejos de seguridad.<br><br><span class="muted">Ésta sí entra en tu final: la óptica de UTN.BA es siempre <b>espejos esféricos</b> o lámina de caras paralelas, nunca lentes.</span>'},

  {st: '<b>P24 · Final de Agosto de 2018, pregunta P4 · UTN San Rafael</b> <span class="muted">(otra regional)</span>. «En la parte inferior del espejo lateral del lado del pasajero de un automóvil se lee: <i>los objetos en el espejo están más cerca de lo que parecen</i>. ¿Esto es verdadero? ¿Por qué?»',
   ans: '<b>Verdadero.</b> Es un espejo <b>convexo</b>: da imagen virtual, derecha y <b>reducida</b>, y el cerebro lee ese tamaño chico como «está lejos».',
   sol: 'El espejo del lado del acompañante es <b>convexo</b> (f = R/2 &lt; 0), elegido así para ampliar el campo visual y achicar el punto ciego.<br><br>Con 1/s + 1/s′ = 1/f y f &lt; 0 se obtiene s′ &lt; 0 (imagen virtual, detrás del espejo) y un aumento<br>m = −s′/s = |f|/(|f| + s), que cumple <b>0 &lt; m &lt; 1</b> para cualquier objeto real: imagen derecha y más chica. Además |s′| &lt; |f|: la imagen queda comprimida entre el espejo y el foco.<br><br><b>La parte perceptiva:</b> el cerebro estima distancias por el <b>tamaño angular</b>, calibrado con la experiencia de los espejos planos. Como el convexo devuelve una imagen más chica, el auto de atrás subtiende un ángulo menor y se interpreta como más lejano. De ahí la advertencia impresa.<br><br><span class="muted">El del lado del conductor suele ser plano: por eso la leyenda va sólo en el del pasajero.</span>'}

]);

registerExercises('fisica1-utn-simulacros', '4', [

  {st: 'Te preguntan qué pasa con el empuje al hundir más un cuerpo que ya está totalmente sumergido. ¿Cuál de estas respuestas está <b>completa</b>?',
   opts: [
     '«El empuje no cambia»',
     '«El empuje no cambia porque el agua es incompresible»',
     '<b>«No cambia porque E = ρ·g·V<sub>desplazado</sub> y, ya totalmente sumergido, V<sub>desplazado</sub> es el volumen del cuerpo; por presiones, E sale de la <i>diferencia</i> entre la cara de abajo y la de arriba, y esa diferencia no depende de la profundidad»</b>',
     '«No cambia porque la presión aumenta igual arriba y abajo»'
   ], c: 2,
   ex: 'La consigna de esta unidad no es acertar el sí o el no: es <b>nombrar la ley y decir la hipótesis</b>. La <b>c</b> nombra Arquímedes, escribe la fórmula, dice qué término es el que deja de crecer y da el argumento por presiones. ▸ Por qué las otras: la <b>a</b> es la mitad de la respuesta — acierta y no justifica nada; la <b>b</b> menciona una hipótesis correcta pero secundaria, y no explica por qué el volumen desplazado deja de crecer; la <b>d</b> es el principio del argumento por presiones pero se queda sin decir que lo que produce el empuje es la <b>diferencia</b>, no la presión absoluta.'},

  {st: 'Una caja cuelga de una cuerda y sube con <b>rapidez constante</b>. Comparada con la caja en reposo, la tensión es…',
   opts: [
     'Mayor, porque además del peso hay que vencer la inercia',
     'Mayor, porque la caja se mueve',
     'Menor, porque la caja ya está en movimiento',
     '<b>Igual: T = mg en los dos casos, porque rapidez constante significa a = 0 y por lo tanto ΣF = 0</b>'
   ], c: 3,
   ex: 'De T − mg = m·a<sub>y</sub> sale T = m(g + a<sub>y</sub>), y con a<sub>y</sub> = 0 queda T = mg tanto en reposo como subiendo parejo. Lo que cambia las fuerzas es la <b>aceleración</b>, nunca la velocidad. ▸ Por qué las otras: la <b>a</b> y la <b>b</b> son la intuición equivocada de que «moverse cuesta fuerza» — es la primera ley la que dice que no; la <b>c</b> confunde la fuerza necesaria para <b>arrancar</b> (donde sí hay aceleración) con la de mantener el movimiento. La misma frase resuelve la pregunta del ascensor y la del auto a potencia constante.'},

  {st: '¿Se puede calcular el momento de inercia de un cuerpo tratando toda su masa como concentrada en el centro de masa?',
   opts: [
     'Sí, igual que para la traslación y para la energía potencial gravitatoria',
     '<b>No: daría I = 0 para un eje que pasa por el CM. Hay que usar I = I<sub>CM</sub> + M·d²</b>',
     'Sí, siempre que el eje no pase por el centro de masa',
     'Sólo si el cuerpo es homogéneo'
   ], c: 1,
   ex: 'I = Σm<sub>i</sub>r<sub>i</sub>² depende de cómo está <b>distribuida</b> la masa respecto del eje. El término M·d² de Steiner sí representa «toda la masa en el CM», pero hay que sumarle I<sub>CM</sub>, que es exactamente la contribución que la aproximación puntual borra. ▸ Por qué las otras: la <b>a</b> confunde traslación con rotación — para ΣF = M·a<sub>CM</sub> y para U = Mgh<sub>CM</sub> sí vale, para I no; la <b>c</b> es el error más peligroso, porque el M·d² es sólo <b>una parte</b> de I (en el péndulo físico del simulacro 2, olvidarse de I<sub>CM</sub> te cambia el período); la <b>d</b> mezcla homogeneidad con distribución: una barra homogénea tampoco cumple.'},

  {st: 'Una respuesta de este banco cita «g = 9,8 m/s²». En tu final, ¿qué hacés?',
   opts: [
     'Usás 9,8 porque es el valor real de la gravedad',
     'Usás 9,81 para tener más precisión',
     'Aclarás que tomás 9,8 y seguís',
     '<b>Usás 10 m/s²: la hoja de FRBA lo imprime en el encabezado</b>, y el 9,8 es de San Rafael'
   ], c: 3,
   ex: 'Las dos hojas de tu cátedra que conservan encabezado dicen «Utilice cuando sea necesario |g| = 10 m/s²» y «Para todos los ejercicios use g = 10 m/s²». Con 10 las cuentas cierran redondas y el corrector espera esos números. ▸ Por qué las otras: la <b>a</b> y la <b>b</b> te dan resultados que no coinciden con la clave de corrección; la <b>c</b> además pierde tiempo aclarando algo que la propia hoja ya resolvió. Lo mismo con sen37° = 0,6 · cos37° = 0,8 · cos30° = 0,866 · ρ<sub>agua</sub> = 1000 kg/m³.'},

  {st: 'Tu final de UTN.BA no tiene preguntas conceptuales escritas. Entonces, ¿para qué sirve esta unidad?',
   opts: [
     'Para prepararte por si cambian el formato del examen',
     'Para el oral, que es obligatorio después del escrito',
     '<b>Para entrenar las hipótesis</b>, que el enunciado de tu cátedra exige y puntúa aparte junto con el sistema de referencia y el DCL',
     'Para repasar temas que en los problemas de cuenta no aparecen'
   ], c: 2,
   ex: 'Los doce finales de UTN.BA que analizamos son <b>100% desarrollo numérico</b>: seis problemas de cuenta y cero teoría escrita. Pero el enunciado pide «diga las hipótesis que hace para justificar las ecuaciones que usa», y eso se corrige por separado. Cada pregunta de este banco te obliga a decir <b>por qué</b> una ecuación vale y <b>cuándo</b> deja de valer: es el mismo músculo. ▸ Por qué las otras: la <b>a</b> especula con un cambio de formato del que no hay ningún indicio en 12 finales; la <b>b</b> inventa un oral que ninguna hoja menciona (el oral es de San Rafael, y sólo en las mesas de pandemia 2020); la <b>d</b> es falsa — casi todos los temas de estas preguntas (rozamiento, empuje, Steiner, péndulo, espejos) aparecen también en los problemas de cuenta.'}

]);
