registerExercises('ingles-tecnico-ii', '1', [
  {st: 'Las 8 partes de un paper académico, en orden, son:', opts: ['Title, Abstract, Methods, Results, Conclusions, References, Author, Discussion', 'Title, Author/Affiliation, Abstract, Introduction, Methodology, Results, Discussion, References', 'Author, Title, Methods, Discussion, Abstract, Introduction, Results, References', 'Abstract, Title, Author, References, Introduction, Results, Methods, Conclusions'], c: 1, ex: 'El orden estándar es: Title → Author/Affiliation → Abstract → Introduction → Methodology → Results → Discussion/Conclusion → References. Las 4 secciones medulares (Intro, Methods, Results, Discussion) forman el esquema IMRAD.'},
  {st: 'IMRAD significa:', opts: ['International Method of Research And Discussion', 'Introduction, Methods, Results And Discussion', 'Investigation, Methodology, Results And Data', 'Introduction, Material, Reference And Data'], c: 1, ex: 'IMRAD = Introduction, Methods, Results, And Discussion. Es la estructura medular del paper científico, estándar en ingeniería y ciencias desde mediados del siglo XX. Title + Abstract + Author la preceden; References la cierra.'},
  {st: '¿Cuál es la sección que más se lee de un paper?', opts: ['Title', 'Abstract', 'Methods', 'References'], c: 1, ex: 'El abstract (típicamente 150–300 palabras) es lo más leído. Los lectores deciden a partir de él si vale la pena leer el resto del paper. Por eso el examen de IT2 enfatiza su lectura, comprensión y reconocimiento.'},
  {st: 'Si querés saber rápido qué aporta un paper, deberías leer:', opts: ['Métodos completos', 'Title + Abstract + Conclusion', 'Solamente las references', 'Tablas y gráficos primero'], c: 1, ex: 'Title te dice de qué trata, Abstract resume todo (incluye gap, métodos, resultados, conclusión) y Conclusion expande las implicaciones. Es la lectura más eficiente para evaluar un paper sin leerlo entero.'},
  {st: 'La sección "References" en un paper:', opts: ['Es decorativa', 'Es la lista de trabajos previos consultados y citas utilizadas; permite rastrear el estado del arte', 'Solo aparece en papers de matemática', 'Es lo mismo que el Abstract'], c: 1, ex: 'Las References muestran sobre qué bibliografía se apoya el paper. Son fundamentales para evaluar la solidez del trabajo y para que un lector pueda seguir profundizando en el tema. No son decorativas.'}
]);

registerExercises('ingles-tecnico-ii', '2', [
  {st: 'El abstract de un paper académico es:', opts: ['La conclusión final', 'Un resumen autocontenido de 150–300 palabras que sintetiza todo el paper, incluyendo métodos y resultados', 'La introducción', 'Una lista de palabras clave'], c: 1, ex: 'El abstract es el resumen completo del paper. Es autocontenido (debe entenderse sin leer el resto). Incluye background, gap, objetivo, métodos, resultados y conclusiones. Suele tener 150–300 palabras.'},
  {st: 'Las "Keywords" en un paper:', opts: ['Son parte del cuerpo narrativo del abstract', 'Son etiquetas (4–8 términos) que aparecen debajo del abstract para indexación en bases de datos', 'Son lo mismo que las references', 'Son las hipótesis del autor'], c: 1, ex: 'Las keywords son una lista de términos para indexación en Scopus, Google Scholar, etc. Aparecen debajo del abstract pero NO forman parte del texto narrativo. Ejemplo: "Keywords: expert system, information management, dashboard, data".'},
  {st: 'Un abstract estructurado se diferencia de uno no estructurado en que:', opts: ['Tiene más palabras', 'Incluye subtítulos explícitos (Background, Methods, Results, Conclusions)', 'No tiene gap', 'Es más corto'], c: 1, ex: 'El estructurado divide el abstract en subsecciones con títulos visibles (común en revistas médicas). El no estructurado es un párrafo único continuo donde los movimientos retóricos se identifican por las marcas lingüísticas. Es el más común en ingeniería.'},
  {st: 'Diferencia clave entre abstract e introducción:', opts: ['Son sinónimos', 'El abstract incluye resultados y conclusiones; la introducción solo presenta el contexto y el problema', 'La introducción es más corta', 'El abstract va al final'], c: 1, ex: 'Abstract: resumen completo (150–300 palabras), incluye qué encontraron y qué concluyeron. Introducción: 1–3 páginas, presenta el contexto, el problema y el gap, pero NO da resultados. El abstract responde "¿qué encontraré si lo leo?"; la intro, "¿por qué importa?".'},
  {st: 'En un abstract no estructurado:', opts: ['No hay movimientos retóricos', 'Los movimientos están presentes pero sin subtítulos; se reconocen por las marcas lingüísticas (verbos, conectores, tiempos verbales)', 'No se puede identificar el gap', 'Solo hay metodología'], c: 1, ex: 'Aunque sea un párrafo único, el abstract no estructurado contiene los mismos movimientos retóricos que el estructurado. Hay que identificarlos por pistas: tiempos verbales, conectores ("However", "Yet"), frases típicas ("has not been...", "Results show...").'},
  {st: '¿Cuál de estas oraciones pertenece típicamente a las CONCLUSIONS de un abstract?', opts: ['"This phenomenon has not been studied in tropical climates."', '"The findings suggest a novel perspective on the benefits of community energy membership."', '"A survey was conducted with N=3963."', '"Recycling is considered the most successful strategy to deal with waste."'], c: 1, ex: 'La conclusión usa verbos como "suggest, imply, conclude" y modal verbs (may, can, should). La opción 1 es gap (has not been); la 3 es methods (was conducted, pasado simple pasivo); la 4 es background (presente simple, hecho general).'}
]);

registerExercises('ingles-tecnico-ii', '3', [
  {st: 'El "marco teórico" en un abstract es:', opts: ['Los trabajos previos puntuales', 'La fundamentación teórica dentro de la cual se enmarca la investigación; resume conocimientos existentes en el área', 'La hipótesis del autor', 'La conclusión'], c: 1, ex: 'El marco teórico es el cuerpo conceptual general que sirve como sustento de la investigación. Se distingue de los antecedentes, que son trabajos previos puntuales con resultados concretos.'},
  {st: 'La diferencia entre PROPÓSITO y OBJETIVO en un abstract es:', opts: ['Son sinónimos', 'Propósito = aspiración o "para qué" amplio; Objetivo = meta concreta y medible', 'El propósito es para papers cualitativos y el objetivo para cuantitativos', 'El objetivo va antes y el propósito después'], c: 1, ex: 'Propósito: el "para qué" más amplio ("para mejorar la salud pública"). Objetivo: meta concreta ("evaluar la eficacia del fármaco X en N pacientes"). Un paper puede tener un propósito y varios objetivos específicos que lo concretan.'},
  {st: 'En el abstract aparece la frase: "Several studies have shown that soft skills improve employability." Este movimiento retórico es:', opts: ['Gap', 'Antecedentes', 'Conclusión', 'Métodos'], c: 1, ex: 'La frase "Several studies have shown..." es un antecedente: refiere a investigaciones previas que ya reportaron resultados. Su tiempo verbal típico es present perfect ("have shown") o pasado simple. No describe un vacío sino un conocimiento ya establecido.'},
  {st: 'Lectura: "It has been suggested that participation in community energy initiatives may foster positive attitudes." Este movimiento es:', opts: ['Gap', 'Marco teórico / background', 'Conclusión', 'Hipótesis del autor'], c: 1, ex: 'Es background o marco teórico: presenta una afirmación general aceptada en el campo ("it has been suggested..."). Reconocer marco teórico vs gap es clave: marco teórico afirma lo que se sabe; gap señala lo que falta saber.'},
  {st: 'En "This article empirically analyzes the relations between community energy membership and attitudes toward RE", el movimiento retórico es:', opts: ['Marco teórico', 'Encuadre + objetivo concreto del paper', 'Resultados', 'Hipótesis'], c: 1, ex: '"This article analyzes..." ubica el paper dentro del campo (encuadre) y declara su objetivo concreto. El verbo principal en presente simple ("analyzes") es típico de propósito/objetivo del paper actual.'},
  {st: 'Si un abstract dice "We hypothesize that variable X is correlated with Y", esto es:', opts: ['Marco teórico', 'Hipótesis', 'Resultados', 'Antecedentes'], c: 1, ex: 'La hipótesis es lo que el autor supone que va a comprobar. Marcas típicas: "We hypothesize that...", "It is expected that...", "We assume...". En ingeniería suele estar implícita en el objetivo, pero en ciencias experimentales aparece formalmente.'},
  {st: 'El "encuadre" en un abstract sirve para:', opts: ['Concluir', 'Ubicar la investigación en un determinado campo de estudio, a veces a través de referencias a investigaciones previas', 'Mostrar resultados', 'Definir términos'], c: 1, ex: 'El encuadre posiciona el paper. Suele aparecer con frases como "This study focuses on...", "Within the context of...", "In this paper, we address...". Distingue al paper concreto del campo más general (marco teórico).'}
]);

registerExercises('ingles-tecnico-ii', '4', [
  {st: 'El "gap" en una investigación es:', opts: ['La hipótesis del autor', 'El vacío de conocimiento; lo que se desconoce hasta el momento y la investigación intentará cubrir', 'Los resultados', 'La conclusión'], c: 1, ex: 'El gap es la declaración de una necesidad de investigación: lo que aún no se sabe en el campo. Toda investigación seria debe abordar al menos un gap, sino no aporta nada nuevo. Es lo que justifica que el paper exista.'},
  {st: '¿Cuál de estas frases en inglés indica casi siempre un gap?', opts: ['"Results show that..."', '"Has not been clarified..."', '"The aim of this paper is..."', '"In conclusion..."'], c: 1, ex: 'Frases típicas de gap (en present perfect negativo): "has/have not been studied/reported/clarified/elucidated", "is required/needed", "the key question is/remains", "it is important to address", "little is known about", "yet, ...".'},
  {st: 'La construcción gramatical canónica del gap en inglés es:', opts: ['Past simple negativo', 'Present perfect negativo (has/have + not + past participle)', 'Future simple', 'Present continuous'], c: 1, ex: 'El gap usa present perfect en negativo porque conecta pasado con presente: "no ha sido + participio". Ejemplo: "This phenomenon has not been investigated in tropical climates" = "este fenómeno no ha sido investigado en climas tropicales (hasta ahora)".'},
  {st: 'En el abstract aparece "Yet, little is known about how members differ from non-members." Esto es:', opts: ['Marco teórico', 'Antecedentes', 'Gap', 'Conclusión'], c: 2, ex: '"Yet" introduce un contraste; "little is known about" es marca canónica de gap (poco se sabe sobre...). El autor dice "esto SE sabe... PERO esto NO se sabe", y eso último es justamente el gap que viene a cubrir.'},
  {st: '"The relationship between the four damping factors has not yet been clarified" expresa:', opts: ['Un resultado positivo', 'Un gap (la relación no ha sido aclarada aún → es lo que el paper viene a aclarar)', 'Una hipótesis', 'Un antecedente'], c: 1, ex: 'Frase clásica de Hosaka, Itao & Kuroda (1995): "has not yet been clarified" = "no ha sido aclarado aún". Es la marca lingüística del gap. El paper viene precisamente a aclarar esa relación.'},
  {st: 'Un mismo paper puede tener:', opts: ['Solo un gap', 'Múltiples gaps; en ese caso deben identificarse todos claramente', 'Ningún gap si es un review', 'Solo gap si es paper experimental'], c: 1, ex: 'Un paper puede atacar varios gaps simultáneamente: por ejemplo, gap metodológico (nuevo método) + gap empírico (en una nueva población) + gap geográfico (en una nueva región). Si los hay, deben identificarse cada uno.'},
  {st: '¿Dónde NO suele aparecer el gap en un paper?', opts: ['En el abstract', 'En la introducción', 'En la sección de objetivos', 'En la sección de references'], c: 3, ex: 'El gap aparece en el abstract (forma compacta), en la introducción (forma extensa, párrafo dedicado) y en la sección de objetivos/propuesta. Las references son la lista bibliográfica: no contienen gap, solo citas.'}
]);

registerExercises('ingles-tecnico-ii', '5', [
  {st: 'El "skimming" como estrategia de lectura sirve para:', opts: ['Buscar un dato puntual (un número, un nombre)', 'Captar la idea general del texto rápidamente', 'Memorizar vocabulario', 'Traducir palabra por palabra'], c: 1, ex: 'Skimming = mirar por encima para captar el panorama general. Lo opuesto es el scanning, que busca información puntual (un número, una fecha). Ambas estrategias son complementarias y se usan juntas en lectura técnica.'},
  {st: 'El "scanning" sirve para:', opts: ['Captar la idea general', 'Encontrar información puntual barriendo el texto en busca de palabras clave', 'Traducir el texto', 'Memorizar el abstract'], c: 1, ex: 'Scanning = "barrer" el texto buscando una palabra o dato específico (un número, un nombre, una fecha). No se lee todo: el ojo se desliza buscando solo la palabra clave. Es muy útil para responder consignas puntuales del parcial.'},
  {st: '¿Cuál es un FALSO AMIGO (false friend) en inglés?', opts: ['"Method" significa "método"', '"Actually" NO significa "actualmente", significa "en realidad"', '"Conclusion" significa "conclusión"', '"Process" significa "proceso"'], c: 1, ex: 'Falsos amigos confunden por el parecido pero significan otra cosa: "actually" = "en realidad" (no "actualmente"); "library" = "biblioteca" (no "librería"); "realize" = "darse cuenta" (no "realizar"); "sensible" = "sensato" (no "sensible"); "eventually" = "finalmente" (no "eventualmente").'},
  {st: '"Library" en inglés significa:', opts: ['Librería (negocio que vende libros)', 'Biblioteca', 'Lectura', 'Librar'], c: 1, ex: '"Library" = biblioteca. La librería en español (negocio que vende libros) en inglés es "bookstore" o "bookshop". Es uno de los falsos amigos clásicos.'},
  {st: 'El conector "However" al inicio de una oración suele preceder a:', opts: ['Una confirmación de lo dicho', 'Un contraste, frecuentemente introduciendo el gap', 'Una conclusión final', 'Un agradecimiento'], c: 1, ex: '"However" (sin embargo) introduce contraste. En abstracts es señal típica de que viene el gap: el autor describe lo que se sabe y luego "However, ... has not been studied / little is known...". Pista clave para detectar gap.'},
  {st: 'La estrategia recomendada para leer un paper desconocido en orden es:', opts: ['Leer todo de principio a fin', 'Title → Abstract → Headings → Conclusion → Introduction → Methods/Results si hace falta', 'Solo references', 'De atrás hacia adelante'], c: 1, ex: 'Estrategia eficiente: title (¿de qué trata?) → keywords → abstract entero (resumen) → headings (mapa) → conclusion (qué encontraron) → introduction (contexto extendido) → methods/results solo si necesitás detalle técnico. No hace falta leer linealmente.'},
  {st: 'En lecto-comprensión, ¿qué hacer al toparse con una palabra desconocida?', opts: ['Detenerse y buscar en diccionario inmediatamente', 'Saltarla si no es clave para la idea, o intentar deducirla por contexto', 'Traducirla literalmente', 'Suponer que es clave'], c: 1, ex: 'Si la palabra no es clave para la idea principal, seguir adelante: el contexto suele aclararla más tarde. Solo detenerse a buscar si es central para entender la idea. Detenerse en cada palabra rompe el flujo y pierde tiempo.'}
]);

registerExercises('ingles-tecnico-ii', '6', [
  {st: 'El tiempo verbal típico para describir el GAP es:', opts: ['Past simple', 'Present perfect en negativo (has/have not been + past participle)', 'Future simple', 'Present continuous'], c: 1, ex: 'Present perfect negativo conecta pasado y presente: "ha sido (o no ha sido) hecho". El gap dice "esto NO ha sido + participio" hasta ahora. Ejemplo: "X has not been investigated in this context".'},
  {st: 'Para describir METHODS en un abstract, el tiempo verbal típico es:', opts: ['Past simple, frecuentemente en voz pasiva', 'Future simple', 'Present continuous', 'Present perfect'], c: 0, ex: 'Methods describe lo ya hecho: pasado simple, frecuentemente con voz pasiva ("a survey was conducted", "data were analyzed"). La pasiva pone foco en lo hecho, no en quién lo hizo (estilo científico estándar).'},
  {st: 'En "Recycling is considered the most successful strategy to deal with waste", el tiempo verbal indica:', opts: ['Resultado del estudio', 'Background o marco teórico (verdad general del campo, en presente simple)', 'Gap', 'Methods'], c: 1, ex: 'Presente simple = verdades generales o conocimiento aceptado del campo. Es típico de marco teórico/background. Si fuera un resultado del paper actual, usaría pasado simple ("Results showed that...") o present perfect.'},
  {st: 'En "A survey was conducted with N=3963 households", la estructura gramatical es:', opts: ['Present simple activo', 'Past simple en voz pasiva', 'Present perfect', 'Future simple'], c: 1, ex: 'Past simple pasivo: "was conducted" (subject + was/were + past participle). Estilo típico de Methods. Equivale a "se realizó una encuesta" o "una encuesta fue realizada". Foco en la acción, no en quién la hizo.'},
  {st: 'Los modal verbs (may, can, should) en un abstract aparecen típicamente en:', opts: ['Methods', 'Conclusions / Implications, para hablar de posibilidad o recomendación', 'Background', 'Results'], c: 1, ex: 'Modal verbs en conclusión: "may" (posibilidad: "this may contribute to..."), "can" (capacidad: "this approach can improve..."), "should" (recomendación: "future studies should address..."), "must" (necesidad). Suavizan o matizan las afirmaciones finales.'},
  {st: 'Reconocer "have shown" en un abstract sugiere que estás leyendo:', opts: ['Methods', 'Antecedentes (estudios previos que ya mostraron algo)', 'Conclusiones', 'Hipótesis'], c: 1, ex: 'Present perfect "have shown / have demonstrated / have found" indica que se trata de antecedentes: estudios previos que reportaron resultados. La frase "Several studies have shown..." es marca canónica de antecedentes.'},
  {st: '"The findings suggest that policy interventions should focus on..." es un ejemplo de:', opts: ['Methods', 'Gap', 'Conclusion / implications', 'Background'], c: 2, ex: 'Verbos como "suggest", "imply" + modal "should" son típicos de conclusiones e implicaciones. El autor sugiere qué deberían hacer otros (policymakers, futuros investigadores) a partir de los resultados encontrados.'}
]);

registerExercises('ingles-tecnico-ii', '7', [
  {st: 'El texto "Internet of Things for a Smart and Ubiquitous eHealth System" trata sobre:', opts: ['Reciclaje de residuos en países en desarrollo', 'Aplicación de IoT (Internet of Things) a un sistema de salud electrónica ubicua', 'Habilidades blandas en RRHH', 'Sistemas expertos para banca'], c: 1, ex: 'Es un paper de Chatterjee y Armentano (2015, IEEE CICN). Define IoT, su rol en eHealth y la "ubicuidad" (sistemas accesibles en cualquier momento y lugar). Cifra emblemática: "50 billion connected devices by 2020" (Cisco IBSG).'},
  {st: 'El texto "Soft Skills in the Workplace" sostiene que:', opts: ['Las hard skills son más importantes que las soft skills', 'Las soft skills son cada vez más valoradas por empleadores junto a las hard skills', 'Las soft skills no son enseñables', 'Solo importa la experiencia técnica'], c: 1, ex: 'El autor (Bhati, 2022) cita que los empleadores valoran a quien es comunicativo, ético, con actitud positiva, capaz de trabajar en equipo. Las soft skills se aprenden mediante entrenamiento. Son tan o más importantes que las hard skills en muchos puestos.'},
  {st: 'En el texto "Soft Skills", la definición tomada de Purdue dice que las soft skills son:', opts: ['Habilidades técnicas medibles', '"the cluster of personality traits, social graces, facility with language, personal habits, friendliness, and optimism"', 'Lo mismo que las hard skills', 'Habilidades exclusivas de gerentes'], c: 1, ex: 'Centre for Career Opportunities at Purdue University: "the cluster of personality traits, social graces, facility with language, personal habits, friendliness, and optimism that mark each of us to varying degrees" (citado por Jungsun K., 2011).'},
  {st: 'El texto "Empowering Innovation in Banking Insurance" propone:', opts: ['Una crítica al sistema bancario', 'Un expert system para gestión de información en banking insurance, con dashboard analítico', 'Un nuevo método de marketing', 'Una reforma legal del sistema asegurador'], c: 1, ex: 'Paper de Rojas Serrano et al. (2024, F1000Research). Es un "Software Tool Article": presenta una herramienta concreta. Vocabulario: expert system, information management, dashboard, decision-making, software tool. Propone integrar la información del sector banking insurance.'},
  {st: 'El texto "Consumers Attitude...Recycling" estudia:', opts: ['Reciclaje en países desarrollados de Europa', 'Actitudes y comportamiento de consumidores hacia el reciclado domiciliario en países en desarrollo (caso UAE)', 'Métodos de incineración de residuos', 'Política ambiental global'], c: 1, ex: 'Bendak & Attili (2017, University of Sharjah, UAE). El argumento central: separar reciclables en origen (en el hogar) es más eficiente que separar después en centros de recolección. Estudio empírico con datos de UAE como caso de país en desarrollo.'},
  {st: 'Todos los textos del aula virtual comparten:', opts: ['El mismo idioma materno del autor', 'La estructura del abstract con los movimientos retóricos clásicos (background, gap, objetivo, métodos, resultados, conclusión)', 'La misma disciplina', 'El mismo año'], c: 1, ex: 'Aunque tratan temas distintos (IoT, soft skills, banking, recycling) y son de disciplinas diversas, los 4 abstracts comparten la estructura clásica: background → gap → objetivo → métodos → resultados → conclusión. Eso es lo que el examen evalúa.'},
  {st: 'Para responder consignas de comprensión en un texto desconocido del parcial:', opts: ['Inferir y suponer', 'Responder con información explícita en el texto, citando o parafraseando con precisión', 'Buscar en Google', 'Traducir todo el paper'], c: 1, ex: 'Las consignas piden información explícita. Las respuestas suelen estar literalmente en el texto (en el abstract, intro o conclusión). Hay que ubicar la frase, citarla o parafrasearla. No suponer ni inferir más allá de lo que el texto dice.'}
]);

registerExercises('ingles-tecnico-ii', '8', [
  {st: 'El parcial de Inglés Técnico II consiste en:', opts: ['Traducir un texto extenso al español palabra por palabra', 'Lectura de un texto auténtico en inglés NO trabajado previamente, consignas de comprensión y reconocimiento/escritura del abstract', 'Examen oral en inglés', 'Solo vocabulario de memoria'], c: 1, ex: 'Según los lineamientos: "lectura de un texto auténtico en inglés, no trabajado previamente, y responder consignas de comprensión lectora. Escritura de un resumen (abstract) en inglés, reconocimiento de sus partes, reconocimiento en el texto". El texto del parcial NO es uno visto en clase.'},
  {st: 'En el parcial de Cátedra Güelpa, ¿qué tipo de diccionario se admite?', opts: ['Solo online', 'Solo de papel (no online ni celular)', 'Cualquier tipo', 'Ninguno'], c: 1, ex: 'En los exámenes parciales solo se admite diccionario bilingüe de PAPEL. El celular no se admite. Conviene tener uno preparado: por ejemplo, Larousse o Oxford bilingüe. Para el día a día sí se puede usar online.'},
  {st: 'La fecha del 1° parcial 2026 es:', opts: ['08/05/2026', '15/05/2026', '22/05/2026', '26/06/2026'], c: 1, ex: 'Lineamientos cátedra: 1° Parcial 15/05/2026, 2° Parcial 26/06/2026, 1° Recuperatorio 03/07/2026. Cursada Viernes 19:00-22:15 hs en sede Campus Mozart (UTN FRBA).'},
  {st: 'Para promocionar la materia (sin examen final), se necesita:', opts: ['60% asistencia y promedio 5', '75% asistencia, ambos parciales aprobados (≥6 con recup), último parcial ≥8 y nota final ≥8', 'Aprobar solo un parcial', 'Solo asistencia'], c: 1, ex: 'Promoción directa requiere: 75% asistencia, TPs aprobados, parciales ≥6 (con recuperatorio posible), último parcial ≥8, calificación final ≥8. Si no se llega a estos números pero se aprueban con ≥6 promedio, queda regular para final.'},
  {st: 'La "Final Reward" del sistema de premios:', opts: ['Es un descuento en la matrícula', 'Equivale a 1 punto entero y se obtiene completando todas las actividades de la sección "Actividades para obtener la Final Reward" antes del 2° parcial', 'Es solo simbólica', 'Se obtiene asistiendo a todas las clases'], c: 1, ex: 'La Final Reward = 1 punto entero. Se obtiene si se completan TODAS las actividades cargadas en la sección "Actividades para obtener la Final Reward" del aula virtual, antes del 2° parcial. Hay también "Spontaneous Rewards" en clase, que se sortean.'},
  {st: 'La estrategia recomendada al recibir el texto del parcial es:', opts: ['Empezar a traducir desde la primera línea', 'Skimming inicial (título, abstract, conclusión) → leer consignas → scanning para responderlas → marcar el texto', 'Leer linealmente sin saltar', 'Traducir todo el abstract literalmente'], c: 1, ex: 'Plan eficiente: 1) skimming (~5 min): título, abstract, conclusión; 2) leer consignas; 3) scanning para encontrar respuestas; 4) marcar gap, objetivo, métodos, resultados; 5) responder primero las claras y dejar dudas para el final. NO traducir todo: no alcanza el tiempo.'},
  {st: 'Una de las consignas frecuentes del parcial es:', opts: ['Recitar las references', 'Identificar el gap del abstract y citarlo en inglés con su traducción', 'Reescribir el paper completo', 'Resolver una ecuación'], c: 1, ex: 'Identificar el gap es una de las consignas estrella. Por eso conocer las marcas lingüísticas ("has not been studied", "is required", "yet little is known", "the key question remains") es esencial. Suele pedirse cita literal + traducción.'}
]);
