registerExercises('papiloscopia-rastros', '1', [
  {st: 'La papiloscopía se define como:', opts: ['La ciencia que estudia el comportamiento criminal', 'La disciplina técnico-científica, parte de la Criminalística, que estudia la conformación de las crestas papilares en dígitos, palmas y plantas para establecer identidad física humana', 'El estudio de las huellas de pisadas en el barro', 'Una rama exclusiva de la medicina forense'], c: 1, ex: 'La palabra proviene del latín "papilos" (papila) y el griego "skopein" (mirar). Estudia las crestas papilares en las yemas de los dedos, palmas de las manos y plantas de los pies, con el fin de establecer identidad en forma categórica e indubitable.'},
  {st: 'Las tres ramas sistematizadas de la papiloscopía son:', opts: ['Dactiloscopía, palametoscopía y poroscopía', 'Dactiloscopía, palametoscopía y pelmatoscopía', 'Dactiloscopía, antropometría y pelmatoscopía', 'Dactiloscopía, odontología forense y poroscopía'], c: 1, ex: 'Las tres ramas sistematizadas son: Dactiloscopía (dígitos), Palametoscopía o Palmoscopía (palmas) y Pelmatoscopía (plantas de los pies). La Poroscopía es la <b>cuarta rama NO sistematizada</b>, en desarrollo.'},
  {st: 'Los principios científicos de la papiloscopía son:', opts: ['Antigüedad, durabilidad y uniformidad', 'Perennidad, inmutabilidad y variedad', 'Legalidad, reproducibilidad e identidad', 'Individualidad, repetitividad y estabilidad'], c: 1, ex: 'Perennidad: las huellas acompañan al sujeto toda la vida y persisten tras la muerte hasta la putrefacción. Inmutabilidad: no cambian naturalmente, salvo en tamaño o por cicatrices. Variedad: no hay dos iguales entre personas ni entre dígitos de la misma persona.'},
  {st: '¿A partir de cuándo se forman los diseños papilares?', opts: ['Al nacer', 'Entre el 3° y 6° mes de vida intrauterina', 'A los 2 años de edad', 'En la pubertad'], c: 1, ex: 'Los diseños papiloscópicos comienzan a formarse a partir del tercer mes de vida intrauterina y se perfeccionan en el sexto mes. Este es el sustento anatómico del principio de perennidad (aporte de José Engel).'},
  {st: 'La poroscopía, dentro de la papiloscopía, es:', opts: ['Una rama sistematizada que estudia los poros de la piel', 'Una rama no sistematizada, en desarrollo, que estudia la disposición de los poros de los conductos sudoríparos en las crestas', 'Lo mismo que la dactiloscopía', 'Una técnica médica de estudio de la piel'], c: 1, ex: 'La poroscopía es la cuarta rama de la papiloscopía, NO sistematizada (en desarrollo). Estudia la disposición de los poros que son la salida de los conductos sudoríparos ubicados en las crestas papilares.'},
  {st: 'Un quemadura profunda que destruye la dermis:', opts: ['No afecta la identificación porque las crestas se regeneran idénticas', 'Modifica el diseño papilar por cicatriz, siendo una excepción al principio de inmutabilidad', 'Elimina los tres principios a la vez', 'Solo afecta al principio de variedad'], c: 1, ex: 'La inmutabilidad dice que las crestas NO se modifican naturalmente, salvo por cicatrices que comprometen la dermis. Una quemadura superficial se recupera; una profunda deja cicatriz permanente que altera el diseño en esa zona.'}
]);

registerExercises('papiloscopia-rastros', '2', [
  {st: '¿En qué año y caso se aplicó por primera vez en el mundo la identificación dactiloscópica en un hecho criminal?', opts: ['1680, Londres, caso Newgate', '1892, Necochea (Argentina), doble filicidio de Francisca Rojas', '1901, Scotland Yard, caso Stratton', '1925, París, caso Landru'], c: 1, ex: 'El caso Rojas de Necochea (1892) es considerado el primer crimen del mundo resuelto por huellas dactilares. Las huellas ensangrentadas en la puerta identificaron a Francisca Rojas como autora del asesinato de sus dos hijos.'},
  {st: 'El 1° de septiembre de 1891 en Argentina corresponde a:', opts: ['La creación de Scotland Yard', 'La primera aplicación mundial del sistema dactiloscópico administrativo, sobre 23 detenidos', 'La publicación del libro de Galton', 'El nacimiento de Juan Vucetich'], c: 1, ex: 'Ese día, en el Departamento Central de la Policía de la Provincia de Buenos Aires, Vucetich realizó por primera vez en el mundo la identificación dactiloscópica administrativa de 23 detenidos. Marca el inicio práctico de la dactiloscopía como sistema.'},
  {st: 'Juan Vucetich redujo los 101 tipos de la Icnofalangometría a:', opts: ['3 tipos (arco, presilla, verticilo)', '4 tipos fundamentales (arco, presilla interna, presilla externa, verticilo)', '9 tipos (siguiendo a Purkinje)', '10 tipos (uno por dígito)'], c: 1, ex: 'En 1896 Vucetich reformuló su sistema reduciéndolo a 4 tipos fundamentales: Arco, Presilla interna, Presilla externa y Verticilo. Este es el núcleo del Sistema Dactiloscópico Argentino (SDA) tal como se usa hoy.'},
  {st: 'En la historia de la papiloscopía, Jan Evangelista Purkinje es considerado:', opts: ['El abuelo de los dactilóscopos', 'El padre de los dactilóscopicos, por su clasificación de 1823 en 9 categorías', 'El creador del SDA', 'El primero en identificar un crimen por huellas'], c: 1, ex: 'Purkinje (1823) clasificó los dibujos digitales en 9 categorías. Aunque no propuso su uso identificativo, su trabajo sistemático le vale el título de padre. Malpighi (1687) es el "abuelo" por estudiar los arabescos digitales desde el punto de vista fisiológico.'},
  {st: 'Francis Galton aportó a la dactiloscopía:', opts: ['El Sistema Dactiloscópico Argentino', 'La publicación de Fingerprints (1892) y la clasificación inicial en arcos, presillas y verticilos', 'La creación de la ficha decadactilar', 'El uso policial por primera vez'], c: 1, ex: 'Sir Francis Galton publicó Fingerprints en 1892, estableciendo científicamente la variedad (ninguna huella igual a otra) y proponiendo la clasificación en 3 grandes grupos. Vucetich tomó estos 101 tipos iniciales (atribuidos a Galton) y los redujo a 4.'},
  {st: '¿Quién creó por primera vez en el mundo la ficha decadactilar?', opts: ['Marcelo Malpighi', 'Sir Edward Henry', 'Juan Vucetich', 'Henry Faulds'], c: 2, ex: 'Vucetich creó la ficha decadactilar (las 10 impresiones tomadas sistemáticamente), junto con el SDA y sus 4 tipos. Es la base del archivo dactiloscópico que hoy sobrevive en los sistemas AFIS digitales.'}
]);

registerExercises('papiloscopia-rastros', '3', [
  {st: 'La cresta papilar es:', opts: ['El bajo relieve entre las papilas', 'El alto relieve formado por papilas dérmicas dispuestas en dos líneas paralelas que llegan a la superficie', 'Una capa de grasa cutánea', 'Lo mismo que un surco interpapilar'], c: 1, ex: 'Cresta papilar = alto relieve. Se genera en la capa superficial de la dermis por la disposición de las papilas en dos líneas paralelas que forman cordones visibles en la epidermis. El surco interpapilar es el bajo relieve que las separa.'},
  {st: 'La diferencia entre huella y rastro papilar es:', opts: ['Son sinónimos sin distinción', 'La huella es involuntaria de la vida cotidiana; el rastro es la misma marca pero ligada a un hecho criminal', 'La huella es artificial y el rastro natural', 'La huella está entintada y el rastro no'], c: 1, ex: 'Físicamente son la misma marca. La diferencia es CONTEXTUAL: se llama "rastro" cuando está vinculada a un hecho criminal (y por lo tanto entra en la investigación pericial). La huella es la marca dejada involuntariamente en actos de la vida cotidiana.'},
  {st: 'El dactilograma artificial:', opts: ['Se observa directamente sobre la piel', 'Se estampa entintando el dígito y presionándolo sobre papel; aparece invertido respecto del natural', 'Es lo mismo que el natural', 'Se obtiene por fotografía UV'], c: 1, ex: 'El artificial es la estampa obtenida entintando el dígito y presionándolo sobre papel. Se encuentra INVERTIDO respecto del natural. Todas las clasificaciones del SDA se hacen sobre dactilogramas artificiales.'},
  {st: 'Las tres regiones del dactilograma artificial son:', opts: ['Superior, media e inferior', 'Nuclear, marginal y basilar', 'Norte, sur y ecuador', 'Anterior, posterior y lateral'], c: 1, ex: 'Región nuclear: parte central. Región marginal: rodea al núcleo por los laterales y arriba. Región basilar: parte inferior, paralela al pliegue de flexión. Las tres están delimitadas por los deltas.'},
  {st: 'El delta es:', opts: ['Un punto característico más', 'La confluencia o convergencia de tres sistemas de líneas, similar al signo < o >, que delimita las tres regiones del dactilograma', 'Una cicatriz', 'Un poro'], c: 1, ex: 'El delta es la figura (similar a la letra griega Δ o al signo matemático <>) formada por la confluencia de tres sistemas de líneas. Delimita la región nuclear, marginal y basilar. Su posición y cantidad define el tipo fundamental.'},
  {st: 'Un pseudodelta se diferencia del delta verdadero en que:', opts: ['Es más grande', 'Carece de punto déltico y no delimita regiones del dactilograma', 'Siempre es blanco', 'Solo aparece en verticilos'], c: 1, ex: 'El pseudodelta no cumple con los requisitos de delta verdadero (no tiene punto déltico, no delimita nuclear/basilar/marginal). Es común en arcos impuros y "presta a confusión" con una presilla verdadera. No debe contarse como delta para la clasificación.'},
  {st: 'El límite inferior del dactilograma natural corresponde a:', opts: ['La uña', 'El pliegue de flexión entre la 3ra y 2da falange', 'La punta del dedo', 'La base del dedo'], c: 1, ex: 'El limbo inferior del dactilograma es el pliegue de flexión entre la 3ra y 2da falange. Los limbos laterales y superior son el borde del campo visual del observador (la "aureola" del pulpejo).'}
]);

registerExercises('papiloscopia-rastros', '4', [
  {st: 'El SDA clasifica los dactilogramas considerando:', opts: ['El color de las líneas', 'La presencia o ausencia de deltas, y en caso de haberlos, su posición y cantidad', 'El tamaño del dedo', 'La densidad de poros'], c: 1, ex: 'El SDA observa deltas: presencia/ausencia, posición (izquierda o derecha del observador) y cantidad (uno, dos, más). Sobre esto define los 4 tipos fundamentales: Arco (sin delta), Presilla Interna (delta a derecha), Presilla Externa (delta a izquierda), Verticilo (dos deltas).'},
  {st: 'Un arco es:', opts: ['Un dactilograma con un solo delta a la izquierda', 'Un dactilograma con dos deltas enfrentados', 'Un dactilograma que carece de deltas, líneas directrices y núcleo; con líneas paralelas que lo atraviesan', 'Un dactilograma con más de dos deltas'], c: 2, ex: 'El Arco es el primer tipo del SDA. Sus líneas atraviesan el dactilograma de un extremo a otro en forma transversal, algo curvas y paralelas entre sí. Carece de deltas, líneas directrices y núcleo. Se clasifica con "A" en pulgares y "1" en el resto.'},
  {st: 'La presilla interna se caracteriza por:', opts: ['Tener delta a la izquierda del observador con asas hacia la derecha', 'Tener delta a la derecha del observador con asas hacia la izquierda', 'No tener deltas', 'Tener dos deltas'], c: 1, ex: 'Presilla INterna: delta a la derecha del observador; las líneas directrices que envuelven al núcleo se dirigen hacia la izquierda. Se clasifica con "I" en pulgares y "2" en el resto. Truco: la presilla lleva el nombre del lado de sus ASAS (contrario al delta).'},
  {st: '¿Con qué clave se clasifican los verticilos?', opts: ['A en pulgares, 1 en resto', 'I en pulgares, 2 en resto', 'E en pulgares, 3 en resto', 'V en pulgares, 4 en resto'], c: 3, ex: 'El Verticilo es el 4° tipo. Presenta 2 deltas (uno a la derecha y uno a la izquierda), enfrentados. Se clasifica con "V" en los pulgares y con "4" en los dígitos restantes. Sus líneas directrices circunscriben al núcleo en distintas formas (circular, espiral, ovoidal, etc.).'},
  {st: 'La individual dactiloscópica A1111-A1111 indica:', opts: ['10 arcos en los 10 dígitos', '10 presillas internas', '5 arcos en una mano y 5 presillas en la otra', 'Una huella falsificada'], c: 0, ex: 'La individual se lee: mano derecha (pulgar-índice-medio-anular-meñique) – mano izquierda (pulgar-índice-medio-anular-meñique). A1111-A1111 = arco en ambos pulgares y arco en los 8 restantes. Es un patrón raro pero posible.'},
  {st: 'Cuando un dactilograma se aparta de la descripción estricta del tipo:', opts: ['No puede clasificarse', 'Es "impuro" (variante)', 'Pasa automáticamente a ser verticilo', 'Se descarta por pericia'], c: 1, ex: 'Cada tipo fundamental puede ser puro o impuro. El arco impuro, por ejemplo, puede ser piramidal, angular, piniforme, o con pseudodelta. Las presillas y verticilos tienen sus propias subclasificaciones según recorrido de líneas.'},
  {st: '¿Cuál es la utilidad del sistema AFIS?', opts: ['Reemplaza al perito', 'Permite comparar en segundos una huella digitalizada contra millones de huellas archivadas', 'Solo sirve para tomar fichas', 'Es un sistema obsoleto'], c: 1, ex: 'AFIS (Automated Fingerprints Identification System) digitaliza la huella y la compara automáticamente contra una base de datos. Acelera enormemente la identificación, pero un perito humano valida la coincidencia final antes de que tenga valor legal.'}
]);

registerExercises('papiloscopia-rastros', '5', [
  {st: 'Los puntos característicos (minucias) del SDA son:', opts: ['Los dibujos generales del dactilograma', 'Pequeños detalles que presentan las crestas en su recorrido, usados para individualizar', 'Los poros de las crestas', 'Las zonas marginales'], c: 1, ex: 'Los puntos característicos (o minucias) son los detalles de las crestas (horquilla, bifurcación, extremo, empalme, etc.) que permiten individualizar dentro de un mismo tipo fundamental. Una huella completa tiene 60-120 puntos; para identificar basta con 12.'},
  {st: '¿Cuántos puntos característicos coincidentes se exigen para afirmar identidad dactiloscópica en el SDA?', opts: ['3', '6', '12', '25'], c: 2, ex: 'En el SDA basta con 12 puntos coincidentes en ubicación, situación y dirección para afirmar categóricamente la identidad. Son los mínimos; en pericias se suelen marcar más (15, 20) para reforzar.'},
  {st: 'La horquilla es:', opts: ['Un islote pequeño', 'Una línea que en su recorrido vuelve sobre sí misma, pudiendo tener cola o apéndice', 'Dos líneas unidas por una tercera', 'Una cresta que empieza y termina dentro del dactilograma'], c: 1, ex: 'La horquilla es una línea que retorna sobre sí misma (U invertida). En el punto de mayor curvatura puede tener una cola o apéndice. No confundir con bifurcación (dos líneas que se unen) ni con encierro (línea que se abre y cierra).'},
  {st: 'La bifurcación es:', opts: ['Una línea que empieza y termina dentro del dactilograma', 'Una línea a la que se le adhiere otra en cualquier punto de su recorrido, formando un ángulo agudo', 'Una cresta que vuelve sobre sí misma', 'Un poro aislado'], c: 1, ex: 'Bifurcación: una línea a la que se le adhiere otra, formando un ángulo agudo (V). Es distinta del empalme (dos líneas unidas por una tercera, con dos ángulos agudos) y de la horquilla (giro de 180° sobre sí misma).'},
  {st: '¿Qué dos condiciones agrupa la IDONEIDAD como norma de cotejo?', opts: ['Cantidad y calidad', 'Nitidez suficiente e integridad suficiente', 'Ubicación y dirección', 'Similitud y situación'], c: 1, ex: 'Idoneidad = nitidez (trazos claros, sin borrones) + integridad (superficie legible suficiente, no un fragmento mínimo). Si falla cualquiera, el dactilograma no es idóneo para cotejo. Las demás normas son: similitud, cantidad de puntos y calidad de puntos.'},
  {st: 'Los tres requisitos de CALIDAD de los puntos característicos son:', opts: ['Tamaño, color y posición', 'Ubicación, situación y dirección, los tres concurrentes', 'Nitidez, integridad y cantidad', 'Tipo, subtipo y forma'], c: 1, ex: 'Cada punto debe tener: Ubicación (posición relativa dentro del dactilograma), Situación (posición respecto del punto déltico) y Dirección (sentido/orientación). Los tres deben ser CONCURRENTES. Si falta uno, ese punto no suma a los 12.'},
  {st: 'El orden correcto de las normas de cotejo es:', opts: ['Similitud → idoneidad → cantidad → calidad', 'Idoneidad → similitud → cantidad → calidad (los tres de cada una concurrentes)', 'Cantidad → calidad → idoneidad → similitud', 'No hay orden, se evalúan simultáneamente'], c: 1, ex: 'Primero idoneidad (¿sirve para cotejar?), luego similitud (¿es del mismo tipo?), luego cantidad (¿hay 12 puntos coincidentes?) y finalmente calidad (¿esos 12 puntos cumplen ubicación-situación-dirección concurrente?). Los cuatro requisitos son ineludibles.'}
]);

registerExercises('papiloscopia-rastros', '6', [
  {st: 'La huella latente se caracteriza porque:', opts: ['Es visible a simple vista sin ayuda', 'No media sustancia entre pulpejo y soporte; solo se ve con reactivos', 'Se forma cuando el soporte es deformable', 'Siempre contiene sangre'], c: 1, ex: 'Huella latente: no hay sustancia visible entre pulpejo y soporte. Se produce por la secreción sudoríparo-sebácea natural. Invisible al ojo; hace falta reactivo físico, químico o instrumental para revelarla.'},
  {st: 'Los componentes de la secreción papilar más duraderos son:', opts: ['Agua y sales', 'Grasas y aceites', 'Aminoácidos (pueden durar años)', 'Urea y bicarbonato'], c: 2, ex: 'El agua se evapora en minutos, las grasas duran semanas, pero los aminoácidos pueden persistir años. Por eso los reactivos químicos que reaccionan con aminoácidos (ninhidrina, DFO) son clave para rastros antiguos, especialmente sobre papel.'},
  {st: 'La ninhidrina reacciona con:', opts: ['Grasas', 'Sales de cloruro', 'Aminoácidos, produciendo el púrpura de Rhuemann', 'Sangre'], c: 2, ex: 'La ninhidrina reacciona con aminoácidos dando una coloración púrpura. Útil en superficies porosas (especialmente papel). Revelado hasta 10 días, acelerable con calor/humedad. No funciona si el elemento estuvo expuesto al agua (el agua arrastra los aminoácidos).'},
  {st: 'La técnica del cianocrilato (superglue) sirve para:', opts: ['Superficies porosas como el papel', 'Superficies no porosas (vidrio, metal, plástico, piel humana); vapor que forma depósito blanco sobre la huella', 'Solo metales preciosos', 'Rastros mojados únicamente'], c: 1, ex: 'El cianocrilato es el gold standard para superficies no porosas. Se hace en cámara de ahumado: el vapor reacciona con el agua y componentes de la huella formando un depósito blanco sólido. Útil en vidrio, plástico, metal e incluso piel humana de cadáveres.'},
  {st: 'Regla crítica al combinar reactivos químicos y físicos:', opts: ['Primero físicos, después químicos', 'Primero químicos, después físicos (nunca al revés)', 'Indistinto', 'Nunca combinar'], c: 1, ex: 'Se pueden usar químicos y luego físicos, pero nunca al revés. Un polvo físico contamina la superficie y bloquea la reacción química posterior. Secuencia típica en papel: DFO → ninhidrina → nitrato de plata, y después, si hace falta, un polvo.'},
  {st: 'El vapor de yodo es considerado:', opts: ['El reactivo final por excelencia', 'El reactivo de exploración por excelencia — se fija a las grasas por sublimación, coloración ocre que se desvanece rápido', 'Un reactivo físico', 'Solo útil en metales'], c: 1, ex: 'El yodo por sublimación se fija a los depósitos grasos del rastro dando coloración ocre-purpúrea. Al desvanecer rápido, hay que fotografiar inmediatamente. Es el reactivo de exploración: se usa primero, antes de ninhidrina y nitrato de plata.'},
  {st: 'Una huella moldeada se produce cuando:', opts: ['Hay sangre o tinta en el pulpejo', 'El soporte es blando o deformable (gelatina, masilla, jabón); las crestas quedan hundidas y los surcos en alto relieve', 'No hay sustancia entre pulpejo y soporte', 'Hay humedad ambiental'], c: 1, ex: 'Las huellas plásticas o moldeadas se generan sobre soportes deformables. Adoptan relieve invertido (crestas hundidas, surcos sobresalientes). Se colecta el objeto y se hace vaciado con yeso o látex para obtener un calco físico del rastro.'}
]);

registerExercises('papiloscopia-rastros', '7', [
  {st: 'Al aplicar un polvo reactivo sobre una superficie:', opts: ['Se apoya todo el pincel con presión', 'Se toca la superficie apenas con la punta del pincel, en movimientos circulares, sin exceso de reactivo', 'Se derrama el polvo directamente', 'Se usa el dedo del perito'], c: 1, ex: 'El pincel se carga en la tapa del frasco (no directo en el frasco, para no contaminar) y se apoya apenas en la superficie, moviéndolo en círculos. Si se apoya todo el pincel, la fuerza del raspado corre o destruye el rastro.'},
  {st: 'En el levantamiento con cinta engomada:', opts: ['Se pega la cinta sobre el rastro y se arranca rápido', 'Se pega la cinta arriba del rastro y se desplaza hacia abajo evitando burbujas; se levanta de abajo hacia arriba con cuidado', 'La cinta debe tener aire entre medio', 'Se usa solo cinta scotch común'], c: 1, ex: 'La cinta se pega al costado/arriba del rastro (no encima directamente), se baja pegándola poco a poco evitando burbujas de aire. Luego se levanta en sentido contrario (de abajo a arriba) con mucho cuidado. Cualquier burbuja implica pérdida de esa porción.'},
  {st: 'La perennidad de las huellas en un cadáver permite obtener impresiones hasta:', opts: ['30 minutos post-mortem', 'Aproximadamente 120 horas post-mortem (antes de putrefacción avanzada)', 'Un año', 'Solo mientras está vivo'], c: 1, ex: 'Hasta ~120 hs (5 días) en cadáver, si no hay putrefacción avanzada. Este es el principio de la necropapiloscopía. La putrefacción desintegra la epidermis; pasado ese punto, hay que recurrir a identificación odontológica o genética.'},
  {st: 'La incidencia oblicua de luz con linterna sirve para:', opts: ['Limpiar el soporte', 'Localizar el rastro por reflexión antes de aplicar reactivo', 'Calentar la superficie', 'Fotografiar el rastro ya revelado'], c: 1, ex: 'Primero localizar, después revelar. La luz angular permite que los microrrelieves del rastro reflejen diferencialmente, haciendo posible verlos antes de aplicar un reactivo (y ahorrar reactivo + evitar destrucción innecesaria).'},
  {st: 'En necropapiloscopía sobre cadáver carbonizado con dermis parcialmente destruida:', opts: ['Es imposible identificar', 'Se puede intentar sobre la cara externa/dorsal del dedo si la interna está destruida', 'Basta con hidratar los dedos', 'Se usa ninhidrina inyectada'], c: 1, ex: 'Si la cara interna (palmar) está destruida por fuego, se puede intentar obtener impresión de la cara dorsal del dedo, que a veces conserva el tejido. La dermis profunda puede sobrevivir a quemaduras superficiales y reconstruirse parcialmente.'},
  {st: 'En la fijación fotográfica del rastro revelado, se busca:', opts: ['Fotografía de baja resolución para agilidad', 'Contraste perfecto entre reactivo y soporte, con patrón métrico, luz adecuada y macro', 'Solo fotografía general sin macro', 'Únicamente escanear con fotocopia'], c: 1, ex: 'La fotografía pericial requiere: contraste (blanco del reactivo sobre soporte oscuro, o viceversa), patrón métrico visible (regla), luz oblicua halógena, fotografía general + macro. Sin fijación fotográfica adecuada el rastro se pierde.'}
]);

registerExercises('papiloscopia-rastros', '8', [
  {st: 'Los elementos DUBITADOS del informe pericial son:', opts: ['La ficha decadactilar indubitada del presunto', 'Los rastros o documentos obtenidos en la escena, cuya autoría se pretende determinar', 'Solo fotografías ilustrativas', 'Los anexos del informe'], c: 1, ex: 'Dubitados: los elementos de autoría incierta (lo que se debe identificar). Indubitados: los elementos de autoría conocida (ficha decadactilar del presunto, generalmente tomada por la policía). El perito coteja dubitado contra indubitado.'},
  {st: 'En el informe pericial, la sección "Fundamentos técnicos" debe contener:', opts: ['Solo la conclusión final', 'Definiciones de papiloscopía, sus ramas, principios, identidad dactiloscópica, grupos de dactilograma y normas de cotejo', 'Lista de honorarios', 'El currículum del perito'], c: 1, ex: 'Los fundamentos técnicos explican al juez por qué los métodos empleados son científicamente válidos: se definen papiloscopía, sus 3 ramas + 1 no sistematizada, perennidad/inmutabilidad/variedad, el SDA y sus 4 tipos, y las normas de cotejo (idoneidad, similitud, cantidad, calidad).'},
  {st: 'Las conclusiones de un informe pericial dactiloscópico deben redactarse:', opts: ['En minúsculas, con tono dubitativo', 'En mayúsculas, negrita e inclinadas, en forma categórica y fehaciente, respondiendo estrictamente lo solicitado', 'En forma verbal ante el juez sin escrito', 'Con ambigüedad para dejar abiertas posibilidades'], c: 1, ex: 'Las conclusiones van en MAYÚSCULAS, negrita e inclinadas. Deben ser CATEGÓRICAS ("fueron estampadas por el mismo pulpejo..." o "no pertenecen al mismo individuo"), nunca probabilísticas. Responden estrictamente a lo solicitado en el "Objeto del informe".'},
  {st: 'En un informe oficial al juzgado:', opts: ['Se pone fecha siempre al inicio', 'No se pone fecha ni número de página: el juzgado timbra y folia', 'Se numeran las páginas con romanos', 'Se firma con seudónimo'], c: 1, ex: 'En informe oficial, el juzgado agrega timbrado con fecha y folia las páginas. El perito NO pone fecha (salvo informe privado) ni número de página (salvo pericia particular). Sí firma al final con nombre, DNI y datos profesionales.'},
  {st: 'Al marcar los puntos característicos en las macrofotografías:', opts: ['Se usan el mismo color para dubitado e indubitado', 'Recuadros del dubitado en rojo, del indubitado en verde', 'Se pintan con acuarela', 'No se marcan visualmente'], c: 1, ex: 'Convención estándar: recuadros y numeración del dubitado en ROJO, del indubitado en VERDE. Técnica de la figura geométrica: perforar cada punto (1 a 15), unir los orificios por el dorso con una secuencia. Las dos figuras resultantes deben coincidir.'},
  {st: 'Si las individuales dactiloscópicas de dos fichas son A1111-A1111 vs I2222-I2222, la conclusión es:', opts: ['Pertenecen al mismo individuo', 'No pertenecen al mismo individuo: la no correspondencia en la individual lo establece categóricamente', 'No se puede concluir sin puntos característicos', 'Hay que repetir la pericia'], c: 1, ex: 'La no correspondencia de la individual (distintos tipos fundamentales en los dígitos correspondientes) permite concluir categóricamente que no pertenecen al mismo individuo. No hace falta pasar a buscar puntos característicos; el cotejo falla en la etapa de similitud.'},
  {st: 'Un "latiguillo" pericial típico para concluir es:', opts: ['"Tal vez sea la misma persona"', '"Atento lo precedentemente expuesto y el material analizado, se concluye que..." o "De acuerdo a lo analizado, se determina que..."', '"No sé, difícil de decir"', '"Firmen ambas partes"'], c: 1, ex: 'El lenguaje pericial usa fórmulas estandarizadas ("latiguillos") que dan formalidad y claridad: "Atento lo precedentemente expuesto...", "De la observación analítica comparada se pudo establecer fehacientemente que...", "Es cuanto se puede informar, saludo a V.S., muy atentamente".'}
]);
