registerExercises('led-segundo-parcial', '1', [
  {st: 'El segundo parcial de LED tiene 5 ejercicios. ¿Cuál NO entra como bloque temático?', opts: ['Recurrencias lineales', 'Conjuntos ordenados, redes y Boole', 'Lógica proposicional y razonamientos', 'Grafos y árboles binarios'], c: 2, ex: 'La lógica proposicional y razonamientos es el bloque del Ej 1 del PRIMER parcial. En el segundo parcial: Ej 1 recurrencias, Ej 2 redes, Ej 3 congruencias, Ej 4 grupos, Ej 5 grafos.'},
  {st: 'Para clasificar una recurrencia como "lineal de orden 2 con coeficientes constantes", necesitás que:', opts: ['El término libre sea cero', 'Cada aₙ aparezca elevado a 1, los coeficientes sean números fijos y la diferencia entre subíndices máx y mín sea 2', 'Tenga al menos 2 condiciones iniciales', 'La recurrencia tenga grado 2'], c: 1, ex: 'Lineal = aₙ a la 1 (no aₙ²). Orden 2 = diferencia max−min de subíndices. Coeficientes constantes = los multiplicadores de aₙ no dependen de n. La homogeneidad y las condiciones iniciales son atributos aparte.'},
  {st: '¿Cuántas soluciones principales tiene ax ≡ b (n) si MCD(a,n) = d y d | b?', opts: ['1', 'd', 'n', 'No tiene solución'], c: 1, ex: 'Si d=MCD(a,n) divide a b, hay exactamente d soluciones principales mod n. Si d no divide a b, no hay solución.'},
  {st: 'Una red de 8 elementos isomorfa a (P({a,b,c}), ⊆) corresponde a:', opts: ['(D₄₀, |)', '(D₃₀, |)', '(D₈, |)', '(D₂₄, |)'], c: 1, ex: '(P(X), ⊆) con |X|=3 es Álgebra de Boole de 8 elementos. (D_n, |) es Álgebra de Boole solo si n es libre de cuadrados con 3 factores primos: 30 = 2·3·5 ✓. 40 = 2³·5 NO. 8 = 2³ NO. 24 = 2³·3 NO.'},
  {st: 'En INV(ℤ₁₀, ·), el orden del grupo es:', opts: ['10', '4 (elementos coprimos con 10: 1,3,7,9)', '5', '8'], c: 1, ex: 'INV(ℤ₁₀) = {x : MCD(x,10)=1} = {1, 3, 7, 9}. |INV(ℤ₁₀)| = φ(10) = 4. Es cíclico de orden 4 (generador: 3).'}
]);

registerExercises('led-segundo-parcial', '2', [
  {st: 'La ecuación característica de aₙ₊₂ − 5aₙ₊₁ + 6aₙ = 0 tiene raíces:', opts: ['r = 1 y r = 6', 'r = 2 y r = 3', 'r = −2 y r = −3', 'Una sola raíz r = 5/2'], c: 1, ex: 'r² − 5r + 6 = 0 → r = (5 ± √(25−24))/2 = (5 ± 1)/2 → r = 3 ó r = 2.'},
  {st: 'Si la recurrencia tiene raíz característica doble r = 4, la solución general es:', opts: ['α·4ⁿ + β·4ⁿ', '(α + β·n)·4ⁿ', 'α·4ⁿ + β·n', 'α + β·n²'], c: 1, ex: 'Cuando la raíz es doble, la solución de la homogénea es (α + β·n)·rⁿ. Es importante el factor n para que haya 2 grados de libertad.'},
  {st: 'Para resolver aₙ₊₁ − 4aₙ = 12·4ⁿ, ¿qué forma tomás para la solución particular?', opts: ['K·4ⁿ', 'K·n·4ⁿ (porque 4 ES raíz simple de la homogénea)', 'K (constante)', 'K + n'], c: 1, ex: 'Como 4 es raíz simple de la característica r − 4 = 0, hay que multiplicar por n. La forma es K·n·4ⁿ. Reemplazando se despeja K.'},
  {st: 'Resolución de aₙ₊₁ = 2aₙ + 3ⁿ con a₀ = 1: la solución particular tiene forma:', opts: ['K·2ⁿ', 'K·n·3ⁿ', 'K·3ⁿ', 'K·n'], c: 2, ex: '3 NO es raíz de la homogénea (la raíz es 2). Forma de la particular: K·3ⁿ. Reemplazando: K·3ⁿ⁺¹ = 2·K·3ⁿ + 3ⁿ → 3K = 2K + 1 → K = 1. a^(p) = 3ⁿ.'},
  {st: 'Para demostrar por inducción que aₙ explícita satisface la recurrencia, en el paso h→h+1:', opts: ['Solo verificás aₕ₊₁ con la fórmula', 'Suponés HI para h y h−1, y probás que aₕ₊₁ cumple la recurrencia', 'No hace falta paso inductivo', 'Probás solo el caso base'], c: 1, ex: 'Si la recurrencia es de orden 2, necesitás dos hipótesis: para h y h−1. Reemplazás en la recurrencia y verificás que la fórmula explícita la cumple.'},
  {st: 'Si las raíces son complejas, ¿qué forma tiene la solución?', opts: ['Sigue siendo α·r₁ⁿ + β·r₂ⁿ con r₁, r₂ complejas (o usar forma trigonométrica con módulo y argumento)', 'No tiene solución real', 'Solo soluciones imaginarias', 'Una sola raíz'], c: 0, ex: 'Las raíces complejas conjugadas se manejan igual algebraicamente. En forma real, se puede escribir |r|ⁿ·(α·cos(nθ) + β·sin(nθ)). En LED suelen evitar este caso.'}
]);

registerExercises('led-segundo-parcial', '3', [
  {st: 'En (ℕ, |), el subconjunto B = {6, 8, 12, 18}. Una cota superior de B es:', opts: ['72 (común múltiplo de todos)', '6 (común divisor)', '24 (no es múltiplo de 18)', '4'], c: 0, ex: 'Cota superior = m tal que todo b ∈ B divide a m. MCM(6,8,12,18) = 72. Cualquier múltiplo de 72 también vale (144, 216, etc.).'},
  {st: 'Si A = {6, 8, 12, 16, 18, 24, 36} con divisibilidad, los maximales de A son:', opts: ['Solo 36', '24, 36, 18 y 16 (los que no tienen ningún múltiplo en A)', 'Solo 24', '6 y 8'], c: 1, ex: 'Maximal: no hay nadie en A que sea múltiplo propio. 36 (no hay múltiplo en A). 24 (48∉A). 18 (36 sí está, falla? 18|36, sí, entonces 18 NO es maximal). Recheck: 16, 24, 36 son maximales. 18 NO porque 36∈A es múltiplo.'},
  {st: '(D₄₀, |) con D₄₀ = {1,2,4,5,8,10,20,40}. ¿Es Álgebra de Boole?', opts: ['Sí', 'No, 40=2³·5 NO es libre de cuadrados → 4 no tiene complemento', 'Sí, isomorfa a (P({a,b,c}), ⊆)', 'No, no es red'], c: 1, ex: '40 = 2³·5. Para Álgebra de Boole con divisores se necesita n libre de cuadrados (cada primo aparece a la 1). 4 = 2² no tiene complemento porque no hay c con MCD(4,c)=1 y MCM(4,c)=40 simultáneamente.'},
  {st: '¿Cuántos elementos tiene (P(X), ⊆) si |X| = 4?', opts: ['4', '8', '16 = 2⁴', '24'], c: 2, ex: 'P(X) tiene 2^|X| elementos. Para |X|=4: 2⁴ = 16. Es Álgebra de Boole de 16 elementos, isomorfa a (D_n, |) con n libre de cuadrados de 4 factores primos: ej. 2·3·5·7 = 210.'},
  {st: 'Una red distributiva siempre cumple:', opts: ['x ∧ (y ∨ z) = (x ∧ y) ∨ (x ∧ z)', 'Es complementada', 'Es Álgebra de Boole', 'Tiene 2ⁿ elementos'], c: 0, ex: 'Distributiva: a ∧ (b ∨ c) = (a ∧ b) ∨ (a ∧ c). NO toda red distributiva es complementada (ej. (D₈, |) es distributiva pero 2 no tiene complemento).'},
  {st: '"Toda red de 8 elementos es Álgebra de Boole". V o F:', opts: ['V (porque 8 = 2³)', 'F. Contraej: cadena de 8 elementos (orden total) es red distributiva pero NO complementada', 'V solo si es distributiva', 'F: nunca lo es'], c: 1, ex: 'La cadena 1≤2≤3≤...≤8 es una red de 8 elementos distributiva pero no complementada (no hay complementos en cadenas largas). Para Álgebra de Boole de 8 elementos hace falta D₃₀, D₄₂, D₇₈, etc.'}
]);

registerExercises('led-segundo-parcial', '4', [
  {st: 'En 22x ≡ 30 (150), MCD(22,150) = 2 y 2 | 30. ¿Cuántas soluciones principales tiene?', opts: ['1', '2', '22', '150'], c: 1, ex: 'Si MCD(a,n) = d y d | b, hay exactamente d soluciones principales mod n. Acá d=2.'},
  {st: 'Para resolver 22x ≡ 30 (150), el primer paso es:', opts: ['Buscar inverso de 22 mod 150', 'Dividir todo por 2: 11x ≡ 15 (75)', 'Multiplicar por 22', 'Calcular MCD(22, 30)'], c: 1, ex: 'Como hay solución, dividís ambos miembros y módulo por d=2, obteniendo una congruencia con MCD(a, n) = 1, que tiene solución única mod 75.'},
  {st: 'Si a·c ≡ b·c (n), ¿siempre podés cancelar c?', opts: ['Sí siempre', 'NO. Solo si MCD(c, n) = 1', 'Solo si c es primo', 'Solo si c | n'], c: 1, ex: 'Cancelación válida si MCD(c,n)=1. Sino, queda a ≡ b (n / MCD(c,n)). Contraej: 2·3 ≡ 4·3 (6) (6=12=12), pero 2≢4 (6).'},
  {st: 'Las últimas dos cifras de 7^2451 son las mismas que:', opts: ['7² mod 100 = 49', '7³ mod 100 = 43 (porque 2451 = 4·612 + 3 y 7⁴ ≡ 1 mod 100)', '7^2451 mod 10', '7 mod 100'], c: 1, ex: 'Calculo 7^k mod 100: 7=7, 7²=49, 7³=343=43, 7⁴=7·43=301=1. El ciclo es de longitud 4. 2451 mod 4 = 3. Por lo tanto 7^2451 ≡ 7³ ≡ 43 mod 100.'},
  {st: 'V o F: si ax ≡ b (n) tiene 2 soluciones principales, entonces MCD(a,b) = 2.', opts: ['V', 'F. La condición es MCD(a, n) = 2 (no MCD(a,b))', 'V solo si b es par', 'V si a y b son coprimos'], c: 1, ex: 'La cantidad de soluciones depende de MCD(a, n), NO de MCD(a, b). El b solo determina si HAY solución (cuando d | b).'},
  {st: 'Para a, b, c, d enteros y n natural: si a ≡ b (n) y c ≡ d (n), entonces:', opts: ['a − c ≡ b − d (n) (válido por propiedades)', 'a/c ≡ b/d (n) (siempre)', 'a^c ≡ b^d (n)', 'aᶜ ≡ b^c (n) requiere condiciones extra'], c: 0, ex: 'La suma, resta y producto se preservan por congruencia mod n. División no, en general. Potencias: a^k ≡ b^k para mismo k entero.'}
]);

registerExercises('led-segundo-parcial', '5', [
  {st: 'INV(ℤ₈, ·) = {1, 3, 5, 7}. ¿Es cíclico?', opts: ['Sí', 'NO (cada elemento al cuadrado da 1, no se llega al orden 4)', 'Sí, gen 3', 'No es grupo'], c: 1, ex: 'En INV(ℤ₈): 3²=9=1, 5²=25=1, 7²=49=1. Cada elemento tiene orden 2. No hay generador de orden 4 → NO es cíclico. Es ≅ ℤ₂ × ℤ₂.'},
  {st: 'Para INV(ℤ₉, ·), el grupo es cíclico de orden:', opts: ['9', '6 (φ(9) = 6, gen: 2)', '4', '3'], c: 1, ex: '|INV(ℤ₉)| = φ(9) = 6 (los coprimos con 9: 1,2,4,5,7,8). Es cíclico, generador 2: 2¹=2, 2²=4, 2³=8, 2⁴=16=7, 2⁵=14=5, 2⁶=10=1.'},
  {st: 'H = {x ∈ ℚ : x = 3ᵏ con k ∈ ℤ} con la multiplicación. ¿Es subgrupo de (ℚ−{0}, ·)?', opts: ['Sí (cierre, neutro 1=3⁰, inverso 3⁻ᵏ)', 'No', 'Solo si k ≥ 0', 'Solo si k es par'], c: 0, ex: 'Cierre: 3ᵃ · 3ᵇ = 3^(a+b) ∈ H. Neutro: 1 = 3⁰ ∈ H. Inverso: (3ᵏ)⁻¹ = 3⁻ᵏ ∈ H. Todas las condiciones se cumplen → es subgrupo.'},
  {st: 'Sea f: (ℤ, +) → (H, ·) con f(x) = 3ˣ. ¿Es homomorfismo? ¿Cómo se clasifica?', opts: ['No es homomorfismo', 'Sí, es isomorfismo: inyectivo y sobreyectivo', 'Sí, solo monomorfismo', 'No, no respeta operación'], c: 1, ex: 'f(x+y) = 3^(x+y) = 3ˣ·3ʸ = f(x)·f(y) ✓ homomorfismo. Inyectivo: f(x)=f(y) ⇒ 3ˣ=3ʸ ⇒ x=y. Sobreyectivo: todo elemento de H es 3ᵏ = f(k). Es isomorfismo.'},
  {st: 'Un grupo producto ℤ₂ × ℤ₃ es cíclico porque:', opts: ['Tiene 6 elementos', 'MCD(2,3) = 1, así que ℤ₂×ℤ₃ ≅ ℤ₆ (cíclico)', 'Es abeliano', 'No es cíclico'], c: 1, ex: 'ℤₘ × ℤₙ es cíclico ⇔ MCD(m,n) = 1. Como MCD(2,3)=1, sí lo es. ℤ₂ × ℤ₂ NO (MCD=2).'},
  {st: 'En el grupo de matrices ({X, −X, I, −I}, ·) con X dado, para que sea grupo necesitás:', opts: ['Que X sea simétrica', 'Que X² = ±I (para que el conjunto sea cerrado bajo producto)', 'Que det(X) = 0', 'Que X = X⁻¹'], c: 1, ex: 'Verificás que el conjunto sea cerrado: X·X = X², debe estar en {X, −X, I, −I}. Si X² = I, el grupo es ≅ ℤ₂×ℤ₂. Si X² = −I, también funciona. Sin esta condición, no es cerrado.'}
]);

registerExercises('led-segundo-parcial', '6', [
  {st: 'Un grafo simple con V vértices y A aristas es necesariamente conexo si:', opts: ['A ≥ V', 'A > C(V−1, 2) = (V−1)(V−2)/2', 'A = V − 1', 'A < V/2'], c: 1, ex: 'El grafo no conexo más denso es K_(V−1) (que tiene C(V−1,2) aristas) más un vértice aislado. Una arista más obliga la conexión.'},
  {st: 'Un grafo tiene camino de Euler si y sólo si:', opts: ['Es conexo y tiene exactamente 0 ó 2 vértices de grado impar', 'Tiene un vértice de grado impar', 'Todos los vértices son de grado par', 'Es bipartito'], c: 0, ex: 'Teorema de Euler: el grafo conexo tiene camino de Euler ⇔ tiene exactamente 0 ó 2 vértices de grado impar. Si tiene 0, es circuito de Euler.'},
  {st: 'Un grafo simple con V=20 y A=170 ¿es necesariamente conexo?', opts: ['Sí (170 > C(19,2) = 171? No, 170 ≤ 171)', 'No: 170 = C(19,2) − 1 NO supera el umbral, podría ser K₁₉ + vértice aislado', 'Sí siempre', 'Depende de los grados'], c: 1, ex: 'C(19,2) = 171. 170 ≤ 171, así que puede ser no conexo (K₁₉ tiene 171 aristas, sacando una se pueden distribuir 170 en una componente más un vértice aislado). NO necesariamente conexo.'},
  {st: 'En notación polaca inversa, para evaluar 5, 2, ·, 8, 2, /, −, 4, 6, 3, −, +, /, usás:', opts: ['Leer de derecha a izquierda', 'Pila: apilás operandos, al ver operador sacás los 2 topes y aplicás', 'Cola FIFO', 'Recorrido in-orden'], c: 1, ex: 'Polaca inversa = post-orden. Algoritmo de pila: operandos se apilan; operadores sacan los 2 topes (primero el segundo operando=tope, luego el primero) y apilan el resultado.'},
  {st: 'Un árbol binario regular con 7 vértices internos tiene cuántas hojas?', opts: ['7', '8 (i + 1 con i=7)', '6', '14'], c: 1, ex: 'Fórmula: en árbol binario regular, hojas = i + 1 donde i = vértices internos. Aquí 7+1 = 8.'},
  {st: 'Un árbol cuaternario regular de altura 5 puede tener como mínimo:', opts: ['1 vértice', '5 vértices (cadena de altura 5)', '6 vértices: 1 raíz + altura 5 → al menos 5 niveles más con 4 hijos cada nivel inicial requerido. Mínimo: 1+4+1·1+1·1+1·1+1 = 9 (una rama de altura 5)... pensar mejor', 'Necesita 4⁵ = 1024 vértices'], c: 2, ex: 'En un árbol cuaternario regular: cada nodo interno tiene 4 hijos. Para altura mínima 5, una rama larga: la raíz tiene 4 hijos (1 sigue, 3 son hojas), y así niveles 1,2,3,4 hasta el nivel 5 que tiene 4 hojas. Total = 1 + 4 + 4 + 4 + 4 + 4 = 21 mínimo (cuidado con los 4 obligatorios por nivel).'}
]);

registerExercises('led-segundo-parcial', '7', [
  {st: 'aₙ₊₂ + 28aₙ = 11aₙ₊₁ + 18·2ⁿ⁻¹ se reescribe como aₙ₊₂ − 11aₙ₊₁ + 28aₙ = 9·2ⁿ. Las raíces de la característica son:', opts: ['r = 3 y r = 4', 'r = 4 y r = 7', 'r = −4 y r = −7', 'r = 2 y r = 14'], c: 1, ex: 'r² − 11r + 28 = 0 → r = (11 ± √(121−112))/2 = (11 ± 3)/2 → r = 7 ó r = 4.'},
  {st: 'Resolver 168x ≡ 350 (1001). MCD(168, 1001) por Euclides:', opts: ['1', '7 (porque 1001 = 7·11·13 y 168 = 2³·3·7)', '21', '168'], c: 1, ex: '1001 = 7·143; 168 = 7·24. MCD = 7. Como 7 | 350 (=7·50), hay 7 soluciones principales mod 1001.'},
  {st: 'INV(ℤ₂₀, ·) tiene cuántos elementos?', opts: ['20', 'φ(20) = 8 (elementos coprimos con 20: 1,3,7,9,11,13,17,19)', '4', '10'], c: 1, ex: 'φ(20) = φ(4)·φ(5) = 2·4 = 8. NO es cíclico (≅ ℤ₂×ℤ₄).'},
  {st: 'Un grafo simple de 13 vértices y 65 aristas. ¿Es necesariamente conexo?', opts: ['Sí (65 > C(12,2) = 66? No)', 'No: 65 ≤ 66 = C(12,2). Puede ser K₁₂ + vértice aislado', 'Sí siempre', 'Depende del grado'], c: 1, ex: 'C(12, 2) = 66. 65 ≤ 66, así que NO necesariamente conexo. ¿k-regular? 13k = 130 → k = 10. Posible si se construye apropiadamente.'},
  {st: 'En un árbol binario, polaca inversa: a, b, +, c, /, d, e, ·, f, +, g, h, ^, −, /. La altura del árbol es:', opts: ['3', '4 (necesitás simular con pila para ver el nivel más profundo)', '5', '6'], c: 1, ex: 'Simulando con pila y reconstruyendo el árbol, el nivel más profundo da altura 4. La estrategia es construir el árbol desde la raíz e ir contando.'},
  {st: 'Estrategia para el día del 2° parcial. ¿Cuál NO es buena idea?', opts: ['Empezar por recurrencias (mecánico)', 'Dibujar todos los grafos antes de analizar', 'Verificar primero si la congruencia tiene solución (MCD divide a b)', 'Saltarse las V/F sobre Álgebras de Boole'], c: 3, ex: 'NUNCA saltarse V/F: son rápidas si tenés contraejemplos preparados (ej. D₈ no es Álgebra de Boole). Suelen ser ítems de 1 punto que cierran el 60% de aprobación.'}
]);
