registerExercises('led-segundo-parcial', '1', [
  {st: 'El segundo parcial de LED tiene 5 ejercicios. ¿Cuál NO entra como bloque temático?', opts: ['Recurrencias lineales', 'Conjuntos ordenados, redes y Álgebra de Boole', 'Lógica proposicional y razonamientos', 'Grafos y árboles binarios'], c: 2, ex: 'La lógica proposicional + razonamientos es el bloque del Ej 1 del PRIMER parcial, no del segundo. ▸ El 2° parcial cubre: Ej 1 recurrencias, Ej 2 redes/orden/Boole, Ej 3 congruencias, Ej 4 grupos, Ej 5 grafos. ▸ Por qué las otras están mal: (A) (B) (D) son los bloques 1, 2 y 5 del 2° parcial.'},
  {st: 'Para clasificar una recurrencia como "lineal de orden 2 con coeficientes constantes", necesitás que:', opts: ['El término libre sea cero', 'Cada aₙ esté elevado a 1, los coeficientes sean números fijos y la diferencia entre subíndices máx y mín sea 2', 'Tenga al menos 2 condiciones iniciales', 'La recurrencia tenga grado 2'], c: 1, ex: 'Lineal = aₙ a la 1 (no aₙ²). Orden 2 = diferencia max−min de subíndices (ej: aₙ₊₂ y aₙ → diferencia 2). Coef. constantes = los multiplicadores no dependen de n. ▸ Por qué las otras están mal: (A) "término libre cero" describe HOMOGENEIDAD, no orden ni linealidad; (C) las condiciones iniciales son DATOS aparte de la clasificación; (D) "grado 2" se refiere a la potencia, no orden.'},
  {st: '¿Cuántas soluciones principales tiene ax ≡ b (n) si MCD(a,n) = d y d | b?', opts: ['1 (única)', 'Exactamente d', 'n soluciones', 'No tiene solución'], c: 1, ex: 'Teorema: si d=MCD(a,n) divide a b, hay EXACTAMENTE d soluciones principales mod n. ▸ Si d ∤ b, no hay solución. ▸ Por qué las otras están mal: (A) "1" sería siempre que MCD=1 (en este caso d=MCD podría ser >1); (C) "n" es el módulo, no las soluciones; (D) "no tiene solución" sería si d ∤ b (la pregunta dice d | b).'},
  {st: 'Una red de 8 elementos isomorfa a (P({a,b,c}), ⊆) corresponde a:', opts: ['(D₄₀, |)', '(D₃₀, |)', '(D₈, |)', '(D₂₄, |)'], c: 1, ex: '(P(X), ⊆) con |X|=3 es Álgebra de Boole de 8 elementos. (D_n, |) es Boole ⟺ n es libre de cuadrados. ▸ 30 = 2·3·5 (libre de cuadrados con 3 primos) ✓. ▸ Por qué las otras están mal: (A) 40 = 2³·5, NO libre de cuadrados; (C) 8 = 2³, NO libre; (D) 24 = 2³·3, NO libre.'},
  {st: 'En INV(ℤ₁₀, ·), el orden del grupo es:', opts: ['10', '4 (los coprimos con 10: {1, 3, 7, 9})', '5', '8'], c: 1, ex: 'INV(ℤₙ) = {x : MCD(x,n) = 1}. Para n=10: coprimos = {1, 3, 7, 9}. ▸ |INV(ℤ₁₀)| = φ(10) = 4. Es cíclico de orden 4 (generador 3: 3¹=3, 3²=9, 3³=27≡7, 3⁴=81≡1). ▸ Por qué las otras están mal: (A) "10" es el módulo (no el orden del grupo); (C) "5" no aparece; (D) "8" sería φ de otro número.'}
]);

registerExercises('led-segundo-parcial', '2', [
  {st: 'La ecuación característica de aₙ₊₂ − 5aₙ₊₁ + 6aₙ = 0 tiene raíces:', opts: ['r = 1 y r = 6', 'r = 2 y r = 3', 'r = −2 y r = −3', 'Una sola raíz r = 5/2'], c: 1, ex: 'r² − 5r + 6 = 0 → factorizo: (r−2)(r−3) = 0 → r = 2 ó r = 3. ▸ Verificación con Bhaskara: r = (5 ± √(25−24))/2 = (5 ± 1)/2 → 3 ó 2 ✓. ▸ Por qué las otras están mal: (A) (1)(6) = 6 ✓ pero 1+6=7≠5 (suma de raíces = coeficiente de r con signo opuesto); (C) signos cambiados; (D) la cuadrática tiene 2 raíces distintas (discriminante=1>0).'},
  {st: 'Si la recurrencia tiene raíz característica doble r = 4, la solución general homogénea es:', opts: ['α·4ⁿ + β·4ⁿ', '(α + β·n)·4ⁿ', 'α·4ⁿ + β·n', 'α + β·n²'], c: 1, ex: 'Cuando la raíz es doble, la solución de la homogénea NO es α·rⁿ+β·rⁿ (=(α+β)·rⁿ, un solo grado de libertad). ▸ Hay que multiplicar el segundo término por n: (α + β·n)·rⁿ. Así se obtienen los 2 grados de libertad necesarios. ▸ Por qué las otras están mal: (A) "α·4ⁿ + β·4ⁿ" colapsa en una constante por 4ⁿ; (C) "α·4ⁿ + β·n" no respeta la estructura; (D) sin la potencia rⁿ.'},
  {st: 'Para resolver aₙ₊₁ − 4aₙ = 12·4ⁿ, ¿qué forma tomás para la solución particular?', opts: ['K·4ⁿ', 'K·n·4ⁿ (porque 4 ES raíz simple de la homogénea)', 'K (constante)', 'K + n'], c: 1, ex: 'La homogénea aₙ₊₁−4aₙ=0 tiene raíz r=4 (simple). El término libre 12·4ⁿ usa la base 4, que ES raíz → hay que MULTIPLICAR por n. ▸ Forma: K·n·4ⁿ. Reemplazo: K(n+1)·4^(n+1) − 4·Kn·4ⁿ = 12·4ⁿ → 4K(n+1) − 4Kn = 12 → 4K = 12 → K = 3. ▸ Por qué las otras están mal: (A) K·4ⁿ no respeta que 4 es raíz; (C) (D) no incluyen la potencia 4ⁿ.'},
  {st: 'En aₙ₊₁ = 2aₙ + 3ⁿ con a₀ = 1, ¿qué forma tomás para la solución particular?', opts: ['K·2ⁿ', 'K·n·3ⁿ', 'K·3ⁿ', 'K·n'], c: 2, ex: 'Homogénea: aₙ₊₁−2aₙ=0, raíz r=2. Término libre 3ⁿ con base 3 (NO es raíz) → forma simple: K·3ⁿ. ▸ Reemplazando: K·3^(n+1) = 2K·3ⁿ + 3ⁿ → 3K = 2K + 1 → K = 1. Particular: 3ⁿ. ▸ Por qué las otras están mal: (A) K·2ⁿ duplicaría con la homogénea; (B) K·n·3ⁿ se usa solo si 3 fuera raíz; (D) K·n no aplica al término exponencial.'},
  {st: 'Para demostrar por inducción que aₙ explícita satisface la recurrencia (orden 2), en el paso h→h+1 partís de:', opts: ['Solo verificás aₕ₊₁ con la fórmula', 'Suponés HI para h y h−1, y probás aₕ₊₁ usando la recurrencia', 'No hace falta paso inductivo', 'Probás solo el caso base'], c: 1, ex: 'En recurrencia de orden 2, la TI(h+1) depende de los DOS términos anteriores aₕ y aₕ₋₁. Por eso necesitás dos hipótesis (HI doble): asumir vale para h y para h−1, sustituir en la recurrencia, y demostrar para h+1. ▸ Por qué las otras están mal: (A) sin HI no podés usar la fórmula explícita en el paso; (C) la inducción REQUIERE paso inductivo; (D) caso base solo no demuestra para todo n.'},
  {st: 'Si las raíces de la característica son complejas conjugadas, ¿qué forma tiene la solución?', opts: ['Sigue siendo α·r₁ⁿ + β·r₂ⁿ con r₁,r₂ complejas (o forma trigonométrica equivalente)', 'No tiene solución real', 'Solo soluciones imaginarias', 'Una sola raíz'], c: 0, ex: 'Las raíces complejas conjugadas (a±bi) se manejan algebraicamente igual que reales. La solución α·r₁ⁿ + β·r₂ⁿ se puede reescribir en forma real: |r|ⁿ·(A·cos(nθ) + B·sin(nθ)). ▸ En LED suelen evitar este caso (raíces siempre reales). ▸ Por qué las otras están mal: (B) (C) son interpretaciones erróneas (las soluciones SÍ pueden ser reales si las constantes son conjugadas); (D) "una sola raíz" sería caso de raíz doble.'}
]);

registerExercises('led-segundo-parcial', '3', [
  {st: 'En (ℕ, |), el subconjunto B = {6, 8, 12, 18}. Una cota superior de B es:', opts: ['72 (común múltiplo de todos)', '6 (común divisor)', '24 (no es múltiplo de 18)', '4'], c: 0, ex: 'Cota superior de B = m tal que ∀b∈B: b | m. ▸ MCM(6,8,12,18) = 72 (mínima cota superior). Cualquier múltiplo de 72 (144, 216,...) también es cota. ▸ Por qué las otras están mal: (B) "6" es cota INFERIOR (divisor común); (C) "24" no es múltiplo de 18 (24/18 no entero), así que 18 no divide a 24 → NO cota; (D) "4" tampoco es común múltiplo.'},
  {st: 'Si A = {6, 8, 12, 16, 18, 24, 36} con divisibilidad, los maximales de A son:', opts: ['Solo 36', '16, 24 y 36 (los que no tienen ningún múltiplo dentro de A)', 'Solo 24', '6 y 8'], c: 1, ex: 'Maximal: x es maximal si NO existe y∈A con x|y, x≠y. ▸ Verifico cada uno: 36 (no hay múltiplos en A) ✓. 24 (48∉A) ✓. 18 (36∈A y 18|36 → NO maximal). 16 (32∉A, 48∉A) ✓. 12 (24,36∈A → NO maximal). 8 (16,24∈A → NO maximal). 6 (12,18,24,36∈A → NO maximal). ▸ Maximales: {16, 24, 36}. ▸ Por qué las otras están mal: (A) (C) son incompletas; (D) 6 y 8 NO son maximales.'},
  {st: '(D₄₀, |) con D₄₀ = {1,2,4,5,8,10,20,40}. ¿Es Álgebra de Boole?', opts: ['Sí, isomorfa a (P({a,b,c}), ⊆)', 'No: 40 = 2³·5 NO es libre de cuadrados → 4 no tiene complemento', 'Sí, todas las redes de 8 elementos lo son', 'No, ni siquiera es red'], c: 1, ex: '40 = 2³·5 (el 2 está al cubo). Para Boole con divisores se necesita libre de cuadrados (cada primo a la 1). ▸ ¿Cuál sería el complemento de 4? Necesita c con MCD(4,c)=1 y MCM(4,c)=40. MCD=1 → c impar; MCM=40 → c|40 y c·4/MCD=40 → c=10 (par). Contradicción → NO existe complemento. ▸ Por qué las otras están mal: (A) NO es Boole (4 sin complemento); (C) cadena de 8 elem es red distributiva pero no Boole; (D) sí es red (todo par tiene MCD/MCM en D₄₀).'},
  {st: '¿Cuántos elementos tiene (P(X), ⊆) si |X| = 4?', opts: ['4', '8', '16 = 2⁴', '24'], c: 2, ex: '|P(X)| = 2^|X|. Para |X|=4: 2⁴ = 16 subconjuntos. ▸ Es Álgebra de Boole de 16 elementos, isomorfa a (D_n, |) con n libre de cuadrados de 4 primos: ej. 2·3·5·7 = 210 → (D₂₁₀, |) tiene 16 divisores. ▸ Por qué las otras están mal: (A) "4" sería |X| (no |P(X)|); (B) "8" = 2³ (no 2⁴); (D) "24" = 4! (permutaciones, no subconjuntos).'},
  {st: 'Una red distributiva siempre cumple:', opts: ['x ∧ (y ∨ z) = (x ∧ y) ∨ (x ∧ z)', 'Es complementada (Boole)', 'Tiene cardinal 2ⁿ', 'Es totalmente ordenada'], c: 0, ex: 'Distributiva ⟺ a ∧ (b ∨ c) = (a ∧ b) ∨ (a ∧ c) Y a ∨ (b ∧ c) = (a ∨ b) ∧ (a ∨ c). ▸ Por qué las otras están mal: (B) NO toda distributiva es complementada (ej: cadena lineal y D₈ son distributivas pero no Boole); (C) Boole tiene 2ⁿ, no toda red distributiva; (D) cadena lineal sí es total pero no es la única red distributiva.'},
  {st: '"Toda red de 8 elementos es Álgebra de Boole". V o F:', opts: ['V (porque 8 = 2³)', 'F. Contraej: cadena 1 ≤ 2 ≤ ... ≤ 8 es red distributiva pero NO complementada', 'V solo si es distributiva', 'F: nunca lo es'], c: 1, ex: 'Una cadena (orden total) de 8 elementos es red, distributiva, pero NO complementada (en cadenas largas no hay complementos). ▸ Para Boole con 8 elementos hace falta D₃₀, D₄₂, D₇₈ o similares (n libre de cuadrados con 3 primos). ▸ Por qué las otras están mal: (A) cardinal 2³ no garantiza Boole; (C) distributiva no implica Boole; (D) hay redes de 8 que SÍ son Boole (D₃₀).'}
]);

registerExercises('led-segundo-parcial', '4', [
  {st: 'En 22x ≡ 30 (150), MCD(22, 150) = 2 y 2 | 30. ¿Cuántas soluciones principales tiene?', opts: ['1', '2', '22', '150'], c: 1, ex: 'Si MCD(a,n)=d divide a b, hay EXACTAMENTE d soluciones principales mod n. Acá d=2 → 2 soluciones. ▸ Por qué las otras están mal: (A) "1" sería con MCD=1; (C) "22" es a (no las soluciones); (D) "150" es n.'},
  {st: 'Para resolver 22x ≡ 30 (150) con MCD=2, el primer paso es:', opts: ['Buscar inverso de 22 mod 150', 'Dividir todo por 2: 11x ≡ 15 (75)', 'Multiplicar por 22', 'Calcular MCD(22, 30)'], c: 1, ex: 'Procedimiento: como MCD=d divide a b, dividís ambos miembros y módulo por d. Quedás con MCD(a\',n\')=1 → solución única en mod n\'. ▸ Acá: 22/2=11, 30/2=15, 150/2=75 → 11x ≡ 15 (75). ▸ Por qué las otras están mal: (A) buscar inverso sin reducir es más complicado; (C) multiplicar por 22 no simplifica; (D) MCD(22,30) no aplica (lo relevante es MCD(a,n)).'},
  {st: 'Si a·c ≡ b·c (n), ¿siempre podés cancelar c?', opts: ['Sí, siempre', 'NO. Solo si MCD(c, n) = 1', 'Solo si c es primo', 'Solo si c | n'], c: 1, ex: 'Cancelación VÁLIDA si MCD(c,n)=1. Sino, queda a ≡ b (n / MCD(c,n)). ▸ Contraej: 2·3 ≡ 4·3 (6) ⟺ 6 ≡ 12 (6) ⟺ 0 ≡ 0 ✓. Pero 2 ≢ 4 (6). MCD(3,6)=3≠1, no se puede cancelar. ▸ Por qué las otras están mal: (A) sin condición es falso; (C) c primo no garantiza MCD=1 con n; (D) c|n es lo opuesto a MCD=1.'},
  {st: 'Las últimas dos cifras de 7^2451 son las mismas que:', opts: ['7² mod 100 = 49', '7³ mod 100 = 43 (porque 7⁴ ≡ 1 mod 100 y 2451 = 4·612 + 3)', '7^2451 mod 10', '7 mod 100'], c: 1, ex: 'Calculo potencias de 7 mod 100: 7¹=7, 7²=49, 7³=343=343−3·100=43, 7⁴=7·43=301=1. ▸ Ciclo de longitud 4 → 7^k depende de k mod 4. ▸ 2451 = 4·612 + 3 → 2451 mod 4 = 3 → 7^2451 ≡ 7³ ≡ 43 mod 100. ▸ Por qué las otras están mal: (A) "49" sería 7² (mal exponente); (C) mod 10 da última cifra (no las DOS últimas); (D) mod 100 directo es lo que estamos calculando.'},
  {st: 'V o F: si ax ≡ b (n) tiene 2 soluciones principales, entonces MCD(a,b) = 2.', opts: ['V', 'F. La condición correcta es MCD(a, n) = 2 (no MCD(a,b))', 'V solo si b es par', 'V si a y b son coprimos'], c: 1, ex: 'La cantidad de soluciones depende de MCD(a, n), NO de MCD(a, b). El b solo determina si HAY solución (cuando d | b). ▸ Por qué las otras están mal: (A) confunde a con n; (C) (D) usan a y b cuando lo relevante es a y n.'},
  {st: 'Si a ≡ b (n) y c ≡ d (n), entonces:', opts: ['a − c ≡ b − d (n) (válido por propiedades de congruencia)', 'a/c ≡ b/d (n) (siempre)', 'a^c ≡ b^d (n) (siempre)', 'aᶜ ≡ b^c (n) requiere condiciones extra'], c: 0, ex: 'La SUMA, RESTA y PRODUCTO se preservan por congruencia mod n. Para POTENCIAS: a^k ≡ b^k para mismo exponente entero k. ▸ Por qué las otras están mal: (B) la división NO se preserva en general; (C) "a^c ≡ b^d" mezcla bases y exponentes; (D) aᶜ ≡ bᶜ (mismo c) sí vale, no requiere extra (la otra forma sí).'}
]);

registerExercises('led-segundo-parcial', '5', [
  {st: 'INV(ℤ₈, ·) = {1, 3, 5, 7}. ¿Es cíclico?', opts: ['Sí, generador 3', 'NO: cada elemento al cuadrado da 1 (orden 2), no hay generador de orden 4', 'Sí, generador 5', 'No es grupo'], c: 1, ex: 'Cálculos en INV(ℤ₈): 3²=9≡1, 5²=25≡1, 7²=49≡1. Todos los elementos no triviales tienen orden 2. ▸ Para ser cíclico, necesitás un generador que recorra los 4 elementos (orden 4). NO existe. ▸ INV(ℤ₈) ≅ ℤ₂ × ℤ₂ (Klein four-group). ▸ Por qué las otras están mal: (A) (C) confirman cíclico cuando no lo es; (D) sí es grupo (cierre, asociativo, neutro 1, inversos).'},
  {st: 'Para INV(ℤ₉, ·), el grupo es cíclico de orden:', opts: ['9', '6 (φ(9) = 6, generador 2)', '4', '3'], c: 1, ex: '|INV(ℤ₉)| = φ(9) = 9·(1−1/3) = 6 (los coprimos con 9: {1,2,4,5,7,8}). ▸ Verifico ciclicidad con 2: 2¹=2, 2²=4, 2³=8, 2⁴=16≡7, 2⁵=14≡5, 2⁶=10≡1. Genera los 6 elementos → cíclico. ▸ Por qué las otras están mal: (A) "9" es el módulo; (C) "4" sería para INV(ℤ₈); (D) "3" no es φ(9).'},
  {st: 'H = {x ∈ ℚ : x = 3ᵏ con k ∈ ℤ} con la multiplicación. ¿Es subgrupo de (ℚ−{0}, ·)?', opts: ['Sí (cierre, neutro 1=3⁰, inverso 3⁻ᵏ)', 'No, no es cerrado', 'Solo si k ≥ 0', 'Solo si k es par'], c: 0, ex: 'Test del subgrupo: ▸ Cierre: 3ᵃ · 3ᵇ = 3^(a+b) ∈ H ✓. ▸ Neutro: 1 = 3⁰ ∈ H ✓. ▸ Inverso: (3ᵏ)⁻¹ = 3⁻ᵏ ∈ H (k entero, así que −k también) ✓. ▸ Por qué las otras están mal: (B) sí es cerrado; (C) si k≥0 sólo, NO sería cerrado bajo inverso (3⁻ᵏ daría k<0); (D) k par excluye 3¹=3 (que está en H).'},
  {st: 'Sea f: (ℤ, +) → (H, ·) con f(x) = 3ˣ. ¿Cómo se clasifica?', opts: ['No es homomorfismo', 'Isomorfismo: inyectivo y sobreyectivo', 'Solo monomorfismo (inyectivo no sobre)', 'No respeta operación'], c: 1, ex: 'Verifico homomorfismo: f(x+y) = 3^(x+y) = 3ˣ · 3ʸ = f(x)·f(y) ✓. ▸ Inyectivo: f(x)=f(y) → 3ˣ=3ʸ → x=y (función exponencial inyectiva) ✓. ▸ Sobreyectivo: todo elemento de H es 3ᵏ = f(k) ✓. ▸ Inyectivo+sobre = isomorfismo. ▸ Por qué las otras están mal: (A) (D) descartado por la verificación; (C) sí es sobreyectivo además.'},
  {st: 'El grupo producto ℤ₂ × ℤ₃ es cíclico porque:', opts: ['Tiene 6 elementos', 'MCD(2,3) = 1, así que ℤ₂ × ℤ₃ ≅ ℤ₆ (cíclico)', 'Es abeliano', 'No es cíclico'], c: 1, ex: 'Teorema: ℤₘ × ℤₙ es cíclico ⟺ MCD(m,n) = 1. ▸ Acá MCD(2,3)=1 → cíclico ≅ ℤ₆. Generador: (1,1) tiene orden lcm(2,3)=6. ▸ Por qué las otras están mal: (A) tener 6 elementos no garantiza ciclicidad (S₃ tiene 6 y no es); (C) "abeliano" es necesario pero no suficiente (ℤ₂×ℤ₂ es abeliano y NO cíclico); (D) sí es cíclico.'},
  {st: 'En el grupo ({X, −X, I, −I}, ·) con X dado, para que sea cerrado bajo producto necesitás:', opts: ['Que X sea simétrica', 'Que X² ∈ {X, −X, I, −I} (típicamente X² = ±I)', 'Que det(X) = 0', 'Que X = X⁻¹'], c: 1, ex: 'El grupo necesita CIERRE. Verificás X·X=X². Para ser cerrado, X² debe estar en el conjunto {X,−X,I,−I}. ▸ Si X² = I: el grupo es ≅ ℤ₂×ℤ₂ (Klein). Si X² = −I: similar. ▸ Por qué las otras están mal: (A) simetría no implica cierre del producto; (C) det(X)=0 implicaría X no inversible (problema en grupos); (D) X=X⁻¹ ⟺ X²=I (caso particular del b).'}
]);

registerExercises('led-segundo-parcial', '6', [
  {st: 'Un grafo simple con V vértices y A aristas es necesariamente conexo si:', opts: ['A ≥ V', 'A > C(V−1, 2) = (V−1)(V−2)/2', 'A = V − 1', 'A < V/2'], c: 1, ex: 'El grafo NO conexo más denso es K_(V−1) (que tiene C(V−1,2) aristas) MÁS un vértice aislado. Si tu grafo tiene ESTRICTAMENTE más aristas, debe ser conexo. ▸ Por qué las otras están mal: (A) A≥V no garantiza conexión (ej: K₃+K₃ tiene 6 aristas y 6 vértices); (C) A=V−1 es árbol mínimo (puede o no ser conexo); (D) A<V/2 sería muy escaso.'},
  {st: 'Un grafo CONEXO tiene camino de Euler si y sólo si:', opts: ['Tiene exactamente 0 ó 2 vértices de grado impar', 'Tiene un solo vértice de grado impar', 'Todos los vértices son de grado par', 'Es bipartito'], c: 0, ex: 'Teorema de Euler: en grafo conexo, ▸ 0 vértices grado impar → CIRCUITO de Euler (cerrado). ▸ 2 vértices grado impar → CAMINO de Euler (entre esos dos). ▸ ≥4 impares → NO hay camino. ▸ Por qué las otras están mal: (B) "1 impar" es imposible (suma de grados par); (C) describe circuito específicamente; (D) bipartito no es condición ni necesaria ni suficiente.'},
  {st: 'Un grafo simple con V=20 y A=170 ¿es necesariamente conexo?', opts: ['Sí, siempre', 'No: 170 ≤ 171 = C(19,2). Puede ser K₁₉ + un vértice aislado', 'Sí, porque A > V', 'Depende de los grados específicos'], c: 1, ex: 'Umbral: A > C(V−1, 2) garantiza conexión. C(19, 2) = 171. ▸ Como 170 ≤ 171, NO se cumple el umbral → puede ser no conexo (K₁₉ tiene 171 aristas; sacando una y agregando un vértice aislado se llega a 170 aristas y no conexo). ▸ Por qué las otras están mal: (A) (C) afirman conexión sin evidencia; (D) la conexión depende de la estructura, no solo de los grados.'},
  {st: 'Para evaluar la expresión en notación polaca inversa "5, 2, ·, 8, 2, /, −, 4, 6, 3, −, +, /", se usa:', opts: ['Leer de derecha a izquierda', 'Pila: apilar operandos, al ver operador sacar 2 topes y aplicar', 'Cola FIFO', 'Recorrido in-orden'], c: 1, ex: 'Polaca inversa = post-orden = pila. ▸ Algoritmo: leer de izq a der, si es operando lo apilás, si es operador sacás los 2 topes (primero 2º operando, luego 1º) y apilás el resultado. ▸ Por qué las otras están mal: (A) la lectura es izq→der; (C) FIFO daría orden incorrecto; (D) in-orden es para árboles binarios, no la evaluación con pila.'},
  {st: 'Un árbol binario regular con 7 vértices internos tiene cuántas hojas?', opts: ['7', '8 (fórmula: hojas = i + 1)', '6', '14'], c: 1, ex: 'En árbol binario REGULAR (cada interno tiene exactamente 2 hijos), siempre hojas = internos + 1, total = 2·internos + 1. ▸ Para i=7: hojas = 8, total = 15. ▸ Por qué las otras están mal: (A) "7" iguala internos y hojas (incorrecto); (C) "6" estaría por debajo de internos; (D) "14" = 2·i (total nodos sin la raíz).'},
  {st: 'Un árbol cuaternario regular de altura 5 tiene como cantidad MÍNIMA de vértices:', opts: ['1', '5 (cadena de altura 5)', '21 (1 raíz + 5 niveles · 4 hijos = 1 + 5·4 = 21)', '4⁵ = 1024 (caso máximo)'], c: 2, ex: 'En árbol cuaternario REGULAR, cada nodo interno tiene EXACTAMENTE 4 hijos. ▸ Para minimizar con altura 5: hago una "rama" larga. Cada interno (en niveles 0 a 4) tiene 4 hijos: 1 sigue la rama, 3 son hojas. El nivel 5 son las 4 hojas finales del último interno. ▸ Total: 1 raíz + niveles 1-4 (4 nodos cada uno) + nivel 5 (4 hojas) = 1 + 4·4 + 4 = 21 vértices. ▸ Por qué las otras están mal: (A) (B) ignoran que cada interno DEBE tener 4 hijos; (D) 4⁵ es el máximo (árbol completo lleno).'}
]);

registerExercises('led-segundo-parcial', '7', [
  {st: 'aₙ₊₂ + 28aₙ = 11aₙ₊₁ + 18·2ⁿ⁻¹ se reescribe como aₙ₊₂ − 11aₙ₊₁ + 28aₙ = 9·2ⁿ. Las raíces de la característica son:', opts: ['r = 3 y r = 4', 'r = 4 y r = 7', 'r = −4 y r = −7', 'r = 2 y r = 14'], c: 1, ex: 'Característica: r² − 11r + 28 = 0. ▸ Por Bhaskara: r = (11 ± √(121−112))/2 = (11 ± 3)/2 → r = 7 ó r = 4. ▸ Verificación: 4·7=28 ✓, 4+7=11 ✓ (suma de raíces = coef. con signo opuesto). ▸ Por qué las otras están mal: (A) 3·4=12≠28; (C) signos cambiados; (D) 2·14=28 ✓ pero 2+14=16≠11.'},
  {st: 'Resolver 168x ≡ 350 (1001). MCD(168, 1001) por Euclides:', opts: ['1', '7 (porque 1001 = 7·11·13 y 168 = 2³·3·7)', '21', '168'], c: 1, ex: '▸ 1001 = 168·5 + 161 ▸ 168 = 161·1 + 7 ▸ 161 = 7·23 + 0 → MCD = 7. ▸ Verificación con factorización: 1001 = 7·11·13, 168 = 2³·3·7 → factor común = 7. ▸ Como 7 | 350 (=7·50), hay 7 soluciones principales mod 1001. ▸ Por qué las otras están mal: (A) "1" implicaría coprimos; (C) 21 no divide a 1001; (D) 168 mismo no es MCD.'},
  {st: 'INV(ℤ₂₀, ·) tiene cuántos elementos?', opts: ['20', 'φ(20) = 8 (coprimos con 20: {1,3,7,9,11,13,17,19})', '4', '10'], c: 1, ex: 'φ(20) = φ(4)·φ(5) = 2·4 = 8. ▸ Coprimos con 20 = aquellos sin factor 2 ni 5: {1,3,7,9,11,13,17,19} (8 elementos). ▸ NO es cíclico (≅ ℤ₂×ℤ₄). ▸ Por qué las otras están mal: (A) "20" es el módulo; (C) "4" sería φ(8) o φ(10); (D) "10" no es φ de 20.'},
  {st: 'Un grafo simple de 13 vértices y 65 aristas. ¿Es necesariamente conexo?', opts: ['Sí, siempre', 'No: 65 ≤ 66 = C(12,2). Puede ser K₁₂ + un vértice aislado', 'Sí, porque 65 > 13', 'Depende de los grados'], c: 1, ex: 'Umbral: A > C(V−1, 2) = C(12,2) = 66. ▸ A=65 ≤ 66 → NO supera el umbral → puede ser no conexo. Construcción: K₁₂ tiene 66 aristas, sacar 1 deja 65 aristas; agregás un vértice aislado → 13 vértices, 65 aristas, NO conexo. ▸ Por qué las otras están mal: (A) (C) sin justificar la cota; (D) los grados no determinan conexión por sí solos.'},
  {st: 'En notación polaca inversa: a, b, +, c, /, d, e, ·, f, +, g, h, ^, −, /. ¿Cuál es la altura del árbol asociado?', opts: ['3', '4', '5', '6'], c: 1, ex: 'Reconstruyo con pila (cada operador combina los 2 topes): ▸ a, b, +: nodo "+" con hojas a, b (altura 1). ▸ c, /: nodo "/" con izq=(+ a,b), der=c (altura 2). ▸ d, e, ·: nodo "·" con d, e (altura 1). ▸ f, +: nodo "+" con izq=(· d,e), der=f (altura 2). ▸ g, h, ^: nodo "^" con g, h (altura 1). ▸ −: nodo "−" con izq=(+ ...), der=(^ g,h) (altura 3). ▸ /: nodo raíz "/" con izq=(/ ...), der=(− ...). Altura = 1 + max(2,3) = 4. ▸ Por qué las otras están mal: requiere construir el árbol; sin pila se equivoca el conteo.'},
  {st: 'Estrategia para el día del 2° parcial. ¿Cuál NO es buena idea?', opts: ['Empezar por recurrencias (procedimiento mecánico)', 'Dibujar todos los grafos antes de analizar', 'Verificar primero si la congruencia tiene solución (MCD divide a b)', 'Saltarse las V/F sobre Álgebras de Boole'], c: 3, ex: 'NUNCA saltarse V/F: son rápidas si tenés contraejemplos preparados (ej: D₈ no es Boole, cadena no es complementada, MCD propiedades). Suelen valer 1 punto cada una y son las más fáciles. ▸ Por qué las otras están bien: (A) recurrencias = receta; (B) dibujar evita errores; (C) chequeo de existencia ahorra tiempo; (D) saltar es la mala estrategia.'}
]);
