// Quizzes por unidad — Lógica y Estructuras Discretas (LED) UTN FRBA · Cátedra Piñeiro

registerExercises('led', '1', [
  {st: '¿Cuál es la negación de '+M('p ∧ q')+'?', opts: [M('¬p ∧ ¬q'), M('¬p ∨ ¬q'), M('p ∨ q'), M('p ∧ ¬q')], c: 1, ex: 'Ley de De Morgan: ¬(p∧q) ≡ ¬p ∨ ¬q (la negación de una conjunción es la disyunción de las negaciones). ▸ Por qué las otras están mal: (A) ¬p∧¬q es la negación de p∨q (la otra De Morgan); (C) p∨q no niega nada; (D) p∧¬q no respeta la negación de p.'},
  {st: '¿Cuál de estas fórmulas es una tautología?', opts: [M('p → q'), M('p ∧ ¬p'), M('p ∨ ¬p'), M('p ↔ ¬p')], c: 2, ex: 'p ∨ ¬p es siempre verdadera (principio del tercero excluido): si p es V, el primer término la hace V; si p es F, ¬p la hace V. ▸ Por qué las otras están mal: (A) p→q es contingencia (F cuando p=V, q=F); (B) p∧¬p es contradicción (siempre F); (D) p↔¬p es contradicción (p nunca equivale a su negación).'},
  {st: 'La proposición "Si llueve entonces me mojo" es FALSA únicamente cuando:', opts: ['Llueve y me mojo', 'No llueve y no me mojo', 'Llueve y no me mojo', 'No llueve y me mojo'], c: 2, ex: 'El condicional p→q es FALSO solo cuando el antecedente es V y el consecuente es F: llueve (p=V) pero NO me mojo (q=F). ▸ Por qué las otras están mal: (A) V→V = V; (B) F→F = V (antecedente falso hace el condicional verdadero); (D) F→V = V. Regla: un condicional con antecedente falso siempre es verdadero.'},
  {st: '¿Qué fórmula es la contrarrecíproca de '+M('p → q')+'?', opts: [M('q → p'), M('¬p → ¬q'), M('¬q → ¬p'), M('¬p → q')], c: 2, ex: 'La contrarrecíproca de p→q es ¬q→¬p, y es lógicamente EQUIVALENTE al original. ▸ Por qué las otras están mal: (A) q→p es la recíproca (NO equivalente); (B) ¬p→¬q es la contraria (NO equivalente); (D) ¬p→q no es ninguna de las variantes clásicas. Truco: en la contrarrecíproca se intercambian y se niegan ambos términos.'},
  {st: 'El razonamiento "Todos los A son B; Ningún B es C; luego ningún A es C" es:', opts: ['Inválido', 'Válido', 'Válido solo si A es finito', 'Inválido porque falta premisa'], c: 1, ex: 'Es VÁLIDO: A⊆B y B∩C=∅ obligan a A∩C=∅. Si todo A está dentro de B, y B no toca a C, entonces A tampoco toca a C. ▸ Por qué las otras están mal: (A) la conclusión se sigue necesariamente; (C) la validez no depende de la cardinalidad; (D) las dos premisas alcanzan (silogismo categórico tipo "Celarent").'},
  {st: '¿Cuál es la negación de '+M('∀x: P(x)')+'?', opts: [M('∀x: ¬P(x)'), M('¬∀x: P(x)'), M('∃x: ¬P(x)'), M('∃x: P(x)')], c: 2, ex: 'Negar un universal da un existencial con la proposición negada: ¬(∀x: P(x)) ≡ ∃x: ¬P(x) ("existe al menos un x que NO cumple P"). ▸ Por qué las otras están mal: (A) ∀x:¬P(x) dice "ninguno cumple" (más fuerte); (B) ¬∀x:P(x) está sin desarrollar (es la expresión a simplificar); (D) ∃x:P(x) no niega nada.'},
  {st: 'Valor de verdad de '+M('∃y ∈ ℝ : ∀x ∈ ℝ, x² = y')+':', opts: ['Verdadera', 'Falsa', 'No es proposición', 'Depende del dominio'], c: 1, ex: 'FALSA: afirma que existe UN mismo y que sea igual a x² para TODO x. Pero x² varía con x (0²=0, 1²=1, 2²=4...), así que ningún y único sirve para todos. ▸ Por qué las otras están mal: (A) sería V si la y pudiera depender de x, pero el orden ∃y:∀x lo impide; (C) sí es proposición (está cuantificada, tiene valor de verdad); (D) el dominio ℝ ya está fijado.'},
  {st: '¿Qué conectivo tiene MAYOR precedencia al evaluar una fórmula sin paréntesis?', opts: [M('∧'), M('∨'), M('¬'), M('→')], c: 2, ex: 'Orden de precedencia (de mayor a menor): ¬ (negación) → ∧ (conjunción) → ∨ (disyunción) → → (condicional) → ↔ (bicondicional). La negación se aplica primero. ▸ Por qué las otras están mal: ∧, ∨ y → tienen menor prioridad; por eso ¬p∧q se lee (¬p)∧q, no ¬(p∧q).'}
]);

registerExercises('led', '2', [
  {st: '¿Cuántos elementos tiene el conjunto potencia (partes) de un conjunto de 4 elementos?', opts: ['4', '8', '16', '12'], c: 2, ex: 'Si |A|=n entonces |P(A)|=2ⁿ. Con n=4: 2⁴=16. Cada elemento puede estar o no en cada subconjunto (2 opciones × 4 elementos). ▸ Por qué las otras están mal: (A) "4" es |A|; (B) "8"=2³ (sería n=3); (D) "12"=4·3 no surge de ninguna fórmula de partes.'},
  {st: 'Si |A|=10, |B|=7 y |A∩B|=3, ¿cuánto vale |A∪B|?', opts: ['14', '17', '20', '13'], c: 0, ex: 'Inclusión-exclusión: |A∪B| = |A|+|B|−|A∩B| = 10+7−3 = 14. Se resta la intersección porque al sumar |A| y |B| los elementos comunes se cuentan dos veces. ▸ Por qué las otras están mal: (B) "17"=10+7 sin restar la intersección; (C) "20" no surge; (D) "13" resta de más.'},
  {st: '¿Cuál equivalencia es correcta para la diferencia de conjuntos?', opts: [M('A−B = A∩B'), M('A−B = A∩Bᶜ'), M('A−B = Aᶜ∩B'), M('A−B = A∪Bᶜ')], c: 1, ex: 'A−B = los elementos que están en A pero NO en B = A∩Bᶜ (en A y en el complemento de B). ▸ Por qué las otras están mal: (A) A∩B son los comunes (lo opuesto); (C) Aᶜ∩B = B−A (al revés); (D) A∪Bᶜ es mucho más grande (todo A más todo lo que no es B).'},
  {st: 'La BASE de la inducción en "∀n≥1: 1+2+…+n = n(n+1)/2" consiste en verificar:', opts: ['El caso n=0', 'El caso n=1', 'El caso n=2', 'El paso inductivo'], c: 1, ex: 'La inducción arranca en el primer valor del dominio: como dice "∀n≥1", el caso base es n=1 (se verifica: suma=1 y 1·2/2=1 ✓). ▸ Por qué las otras están mal: (A) n=0 está fuera del dominio (n≥1); (C) n=2 no es el primero; (D) el paso inductivo es la OTRA parte (no la base).'},
  {st: 'En el PASO inductivo se asume que P(k) es verdadera (hipótesis inductiva) para demostrar:', opts: [M('P(k−1)'), M('P(k+1)'), M('P(2k)'), M('P(k²)')], c: 1, ex: 'Inducción: suponiendo P(k) (HI), se demuestra P(k+1). Así, valiendo el caso base y "k⟹k+1", la propiedad vale para todos los naturales en cadena. ▸ Por qué las otras están mal: (A) P(k−1) va hacia atrás; (C) (D) saltan valores y rompen la cadena 1→2→3→…'},
  {st: 'Si A⊆B y B⊆A, entonces:', opts: [M('A=∅'), M('B=∅'), M('A=B'), M('A∩B=∅')], c: 2, ex: 'Doble inclusión: A⊆B (todo lo de A está en B) y B⊆A (todo lo de B está en A) ⟹ A=B. Es la técnica estándar para probar igualdad de conjuntos. ▸ Por qué las otras están mal: (A) (B) no se deduce vaciedad; (D) A∩B=∅ contradice que sean iguales (salvo que ambos sean vacíos).'},
  {st: '¿Cuál es el cardinal de A∆B (diferencia simétrica) si |A|=5, |B|=4, |A∩B|=2?', opts: ['3', '5', '7', '9'], c: 1, ex: 'A∆B = (A−B)∪(B−A), y |A∆B| = |A|+|B|−2|A∩B| = 5+4−2·2 = 9−4 = 5. Se resta DOS veces la intersección porque la diferencia simétrica excluye los elementos comunes. ▸ Por qué las otras están mal: (A) "3" resta de más; (C) "7"=5+4−2 resta solo una vez (eso sería |A∪B|−nada); (D) "9"=5+4 sin restar.'},
  {st: 'Para demostrar por inducción que 5ⁿ ≥ 4n para n≥1, la hipótesis inductiva (HI) asume:', opts: ['La fórmula para n=1', 'La fórmula para n=k y se prueba para n=k+1', 'La fórmula para todos los n', 'Que n es par'], c: 1, ex: 'La HI asume que la propiedad vale para n=k (un valor genérico), y con eso se demuestra para n=k+1. ▸ Por qué las otras están mal: (A) "para n=1" es el caso BASE, no la HI; (C) asumir "para todos los n" sería asumir lo que se quiere probar (petición de principio); (D) la paridad no tiene relación con esta inducción.'}
]);

registerExercises('led', '3', [
  {st: '¿De cuántas formas se pueden ordenar 5 libros distintos en una estantería?', opts: ['25', '60', '120', '100'], c: 2, ex: 'Permutación de 5 elementos distintos: 5! = 5·4·3·2·1 = 120. Importa el orden y se usan todos. ▸ Por qué las otras están mal: (A) "25"=5²; (B) "60"=5·4·3 sería ordenar solo 3 de los 5; (D) "100" no surge de ninguna fórmula combinatoria.'},
  {st: '¿Cuántas palabras de 3 letras DISTINTAS se pueden formar con {A,B,C,D,E}?', opts: ['10', '60', '120', '15'], c: 1, ex: 'Importa el orden y NO se repite: variaciones V(5,3) = 5·4·3 = 60. ▸ Por qué las otras están mal: (A) "10"=C(5,3) (combinaciones, sin orden); (C) "120"=5! (usaría las 5 letras); (D) "15" no corresponde.'},
  {st: '¿Cuántos comités de 3 personas se pueden elegir de un grupo de 8?', opts: ['56', '24', '336', '512'], c: 0, ex: 'Un comité NO tiene orden (los mismos 3 son el mismo comité) → combinaciones C(8,3) = 8!/(3!·5!) = (8·7·6)/(3·2·1) = 336/6 = 56. ▸ Por qué las otras están mal: (B) "24" no surge; (C) "336"=8·7·6 son variaciones (con orden, error típico); (D) "512"=8³ (con repetición y orden).'},
  {st: 'El coeficiente de '+M('x³y²')+' en el desarrollo de '+M('(x+y)⁵')+' es:', opts: ['5', '10', '20', '15'], c: 1, ex: 'Binomio de Newton: el término con x³y² es C(5,2)·x³·y² (el exponente de y, que es 2, da el índice). C(5,2) = C(5,3) = 10. ▸ Por qué las otras están mal: (A) "5"=C(5,1) o C(5,4); (C) "20"=V(5,2) (con orden); (D) "15" no es coeficiente binomial de fila 5.'},
  {st: 'Si se reparten 10 palomas en 9 palomares, ¿qué garantiza el principio del palomar?', opts: ['Hay un palomar vacío', 'Al menos un palomar tiene ≥2 palomas', 'Hay exactamente un palomar con 2 palomas', 'Todos tienen la misma cantidad'], c: 1, ex: 'Principio del palomar: si hay más objetos (10) que cajas (9), al menos una caja tiene ≥2 objetos. Solo garantiza la EXISTENCIA, no cuántas ni cuáles. ▸ Por qué las otras están mal: (A) podría no haber vacíos; (C) "exactamente uno con 2" es más específico de lo que garantiza el principio; (D) 10 no se reparte uniforme en 9.'},
  {st: '¿Cuántos anagramas (permutaciones) tiene la palabra MATEMÁTICA (10 letras: M,A,T,E,M,A,T,I,C,A)?', opts: [M('10!'), M('10!/(3!·2!·2!)'), M('10!/(2!·2!·2!)'), M('10!/3!')], c: 1, ex: 'Letras repetidas: A aparece 3 veces, M 2 veces, T 2 veces (E, I, C una vez). Permutaciones con repetición = 10!/(3!·2!·2!) = 151.200. ▸ Por qué las otras están mal: (A) 10! cuenta como si todas fueran distintas (sobreestima); (C) divide por 2!·2!·2! tratando la A como si se repitiera 2 veces (son 3); (D) 10!/3! olvida las repeticiones de M y T.'},
  {st: '¿Cuántos anagramas tiene la palabra AZUL?', opts: ['4', '12', '24', '6'], c: 2, ex: 'Las 4 letras son distintas → permutaciones = 4! = 24. ▸ Por qué las otras están mal: (A) "4" es la cantidad de letras; (B) "12"=4·3 (solo 2 posiciones); (D) "6"=3! (3 letras).'},
  {st: 'El número de subconjuntos de k elementos de un conjunto de n elementos es:', opts: [M('n!'), M('n!/k!'), M('C(n,k)'), M('n·k')], c: 2, ex: 'Elegir un subconjunto de k elementos = combinaciones (sin orden): C(n,k) = n!/(k!·(n−k)!). ▸ Por qué las otras están mal: (A) n! ordena todos; (B) n!/k! son variaciones V(n,n−k)... no cuenta subconjuntos; (D) n·k no tiene sentido combinatorio.'}
]);

registerExercises('led', '4', [
  {st: '¿Cuál es el mcd(224, 120) por el algoritmo de Euclides?', opts: ['4', '8', '12', '16'], c: 1, ex: 'Divisiones sucesivas: 224=1·120+104; 120=1·104+16; 104=6·16+8; 16=2·8+0. El último resto no nulo es 8 → mcd=8. ▸ Por qué las otras están mal: son divisores comunes parciales o múltiplos, pero el máximo común divisor exacto es 8 (verificable: 224=8·28, 120=8·15, y mcd(28,15)=1).'},
  {st: 'Si mcd(a,b)=1, ¿cómo se llaman a y b?', opts: ['Divisibles', 'Coprimos (primos entre sí)', 'Múltiplos', 'Primos'], c: 1, ex: 'mcd=1 significa que no comparten factores primos → son COPRIMOS o primos entre sí (ej: 8 y 15). ▸ Por qué las otras están mal: (A) "divisibles" implicaría que uno divide al otro; (C) "múltiplos" lo mismo; (D) "primos" es ser primo individualmente (ej: 8 no es primo pero es coprimo con 15).'},
  {st: 'El teorema de Bézout afirma que existen enteros s,t tales que:', opts: [M('mcd(a,b)=a·b'), M('mcd(a,b)=s·a+t·b'), M('mcd(a,b)=s+t'), M('mcd(a,b)=a/b')], c: 1, ex: 'Bézout: el mcd siempre se escribe como combinación lineal entera de a y b: mcd(a,b)=s·a+t·b. Los coeficientes s,t se hallan con el algoritmo de Euclides extendido. ▸ Por qué las otras están mal: (A) a·b se relaciona con el mcm, no el mcd; (C) (D) no son identidades válidas.'},
  {st: '¿La ecuación diofántica 6x+10y=9 tiene solución entera?', opts: ['Sí, porque 6 divide a 10', 'No, porque mcd(6,10)=2 no divide a 9', 'Sí, siempre hay solución entera', 'Sí, porque mcd(6,10)=1'], c: 1, ex: 'Una diofántica ax+by=c tiene solución entera ⟺ mcd(a,b) divide a c. Acá mcd(6,10)=2, y 2 NO divide a 9 (9 es impar) → NO tiene solución. ▸ Por qué las otras están mal: (A) 6 no divide a 10 y eso no es el criterio; (C) no siempre hay solución; (D) mcd(6,10)=2, no 1.'},
  {st: 'En base 2, el número '+M('(1101)₂')+' equivale en base 10 a:', opts: ['11', '13', '14', '12'], c: 1, ex: 'Cada dígito por su potencia de 2: 1·2³+1·2²+0·2¹+1·2⁰ = 8+4+0+1 = 13. ▸ Por qué las otras están mal: (A) "11"=(1011)₂; (C) "14"=(1110)₂; (D) "12"=(1100)₂. La clave es el peso posicional de cada bit.'},
  {st: '¿Cuántos números primos hay entre 1 y 10?', opts: ['3', '4', '5', '6'], c: 1, ex: 'Primos entre 1 y 10: 2, 3, 5, 7 → son 4. ▸ Por qué las otras están mal: (A) "3" olvida uno; (C) "5" incluiría el 1 (que NO es primo por definición) o el 9 (=3²); (D) "6" cuenta de más. Recordá: el 1 no es primo y el 2 es el único primo par.'},
  {st: 'Si a|b y a|c, entonces necesariamente:', opts: [M('a|(b·c)'), M('a|(b+c)'), 'a|(b−c) solo si b>c', M('a²|(b+c)')], c: 1, ex: 'Si a divide a b y a c, divide a cualquier combinación lineal entera: en particular a b+c (y también a b−c, b·c, etc.). Es la propiedad de linealidad de la divisibilidad. ▸ Por qué las otras están mal: (A) a|(b·c) es verdad pero ya se sigue de a|b solo (más débil); (C) a|(b−c) vale siempre, no "solo si b>c" (la divisibilidad admite negativos); (D) a²|(b+c) es falso en general (ej: 2|4 y 2|6, pero 4∤10).'},
  {st: '¿Cuál es el mcm(12,18)?', opts: ['6', '36', '72', '216'], c: 1, ex: 'mcm(a,b) = (a·b)/mcd(a,b). mcd(12,18)=6, entonces mcm = (12·18)/6 = 216/6 = 36. ▸ Por qué las otras están mal: (A) "6" es el mcd (no el mcm); (C) "72" no es múltiplo común mínimo; (D) "216"=12·18 sin dividir por el mcd (error típico).'}
]);

registerExercises('led', '5', [
  {st: 'La relación "=" (igualdad) en ℤ es:', opts: ['Solo reflexiva', 'Solo simétrica', 'De equivalencia', 'De orden estricto'], c: 2, ex: 'La igualdad es reflexiva (a=a), simétrica (a=b⟹b=a) y transitiva (a=b∧b=c⟹a=c) → relación de EQUIVALENCIA. ▸ Por qué las otras están mal: (A) (B) cumple las tres, no solo una; (D) un orden estricto es irreflexivo (a<a es falso), pero a=a sí vale.'},
  {st: '¿Cuál propiedad NO tiene la relación "≤" en ℝ?', opts: ['Reflexiva', 'Antisimétrica', 'Transitiva', 'Simétrica'], c: 3, ex: '"≤" es reflexiva (a≤a), antisimétrica (a≤b∧b≤a⟹a=b) y transitiva (orden parcial), pero NO simétrica: 2≤3 es V pero 3≤2 es F. ▸ Por qué las otras están mal: (A) (B) (C) sí las cumple. La asimetría es justamente lo que la hace un ORDEN y no una equivalencia.'},
  {st: 'Una PARTICIÓN de un conjunto A es una colección de subconjuntos que son:', opts: ['Vacíos y disjuntos', 'No vacíos, disjuntos dos a dos y cuya unión es A', 'Iguales entre sí', 'Subconjuntos de A∩B'], c: 1, ex: 'Partición = bloques NO vacíos, disjuntos dos a dos (no se solapan) y que juntos cubren todo A. ▸ Por qué las otras están mal: (A) los bloques no pueden ser vacíos; (C) no tienen que ser iguales (al contrario, son distintos); (D) no tiene sentido (A∩B no aparece).'},
  {st: 'Si R es una relación de equivalencia en A, sus clases de equivalencia forman:', opts: ['Un subconjunto de A', 'Una partición de A', 'Un subgrupo de A', 'Un orden en A'], c: 1, ex: 'Las clases de equivalencia son no vacías, disjuntas y cubren A → forman una PARTICIÓN. Es el teorema fundamental que conecta equivalencias con particiones (biyección). ▸ Por qué las otras están mal: (A) son subconjuntos pero el conjunto de clases es una partición; (C) "subgrupo" es de teoría de grupos; (D) una equivalencia no es un orden.'},
  {st: 'Una función f:A→B es INYECTIVA si:', opts: [M('f(x)=f(y) ⟹ x=y'), 'Para todo b∈B existe a con f(a)=b', M('f(x)=x para todo x'), 'Es sobreyectiva'], c: 0, ex: 'Inyectiva = elementos distintos tienen imágenes distintas; equivalentemente, si dos imágenes coinciden, los originales coinciden: f(x)=f(y)⟹x=y. ▸ Por qué las otras están mal: (B) es la definición de SOBREYECTIVA; (C) es la función identidad (caso particular); (D) inyectiva y sobreyectiva son propiedades independientes.'},
  {st: 'La relación de divisibilidad "|" en ℕ es de ORDEN porque es:', opts: ['Reflexiva y simétrica', 'Reflexiva, antisimétrica y transitiva', 'Solo transitiva', 'Simétrica y transitiva'], c: 1, ex: 'En ℕ: a|a (reflexiva); a|b ∧ b|a ⟹ a=b (antisimétrica, válida en ℕ); a|b ∧ b|c ⟹ a|c (transitiva). Las tres → orden parcial. ▸ Por qué las otras están mal: (A) no es simétrica (2|4 pero 4∤2); (C) le faltan reflexiva y antisimétrica; (D) la simetría falla.'},
  {st: '¿Cuántas relaciones de equivalencia existen en el conjunto {1,2,3}?', opts: ['3', '4', '5', '6'], c: 2, ex: 'Hay tantas relaciones de equivalencia como PARTICIONES. Las particiones de {1,2,3} son 5 (número de Bell B₃=5): {{1,2,3}}, {{1},{2,3}}, {{2},{1,3}}, {{3},{1,2}}, {{1},{2},{3}}. ▸ Por qué las otras están mal: (A) (B) cuentan de menos; (D) "6" cuenta de más (sería si hubiera 6 particiones).'},
  {st: 'Una función BIYECTIVA es aquella que es:', opts: ['Inyectiva pero no sobreyectiva', 'Sobreyectiva pero no inyectiva', 'Inyectiva Y sobreyectiva', 'Ni inyectiva ni sobreyectiva'], c: 2, ex: 'Biyección = inyectiva + sobreyectiva: cada elemento del codominio tiene exactamente un original. Establece una correspondencia uno a uno. ▸ Por qué las otras están mal: (A) (B) le falta una de las dos propiedades; (D) no cumple ninguna. Solo las biyecciones tienen función inversa.'}
]);

registerExercises('led', '6', [
  {st: 'En un diagrama de Hasse, un elemento a CUBRE a b si:', opts: ['a>b y no existe c con a>c>b', 'a=b', 'a&lt;b', 'a y b son comparables'], c: 0, ex: 'a cubre a b cuando a>b y no hay ningún elemento intermedio (no existe c con a>c>b). Son los "vecinos inmediatos" que se dibujan unidos por una línea en el Hasse. ▸ Por qué las otras están mal: (B) a=b no es cobertura; (C) a<b es el orden inverso; (D) ser comparables no implica ser vecinos inmediatos (puede haber elementos en el medio).'},
  {st: '¿Cuántos elementos tiene el álgebra de Boole NO TRIVIAL más chica?', opts: ['1', '2', '4', '8'], c: 1, ex: 'El álgebra de Boole no trivial mínima es {0, 1} con 2 elementos (n=1 variable): tiene un mínimo 0 y un máximo 1 distintos. ▸ Por qué las otras están mal: (A) "1" sería el álgebra trivial degenerada (0=1); (C) "4"=2² es la siguiente (P({a,b})); (D) "8"=2³. Toda álgebra de Boole tiene 2ⁿ elementos; la más chica no trivial es 2¹=2.'},
  {st: 'El SUPREMO de un subconjunto S en un orden parcial es:', opts: ['El máximo de S', 'La menor de las cotas superiores de S', 'La mayor de las cotas inferiores de S', 'El mínimo de S'], c: 1, ex: 'Supremo (join) = la MENOR cota superior de S. Puede no pertenecer a S. ▸ Por qué las otras están mal: (A) el máximo es el supremo solo SI pertenece a S; (C) "mayor cota inferior" es el ÍNFIMO; (D) el mínimo es lo opuesto.'},
  {st: 'En una RED (lattice), todo par de elementos tiene:', opts: ['Un máximo y un mínimo globales', 'Supremo e ínfimo', 'Solo supremo', 'Solo ínfimo'], c: 1, ex: 'Una red es un orden parcial donde TODO par {a,b} tiene supremo (a∨b) e ínfimo (a∧b). ▸ Por qué las otras están mal: (A) máximo/mínimo globales los tiene una red ACOTADA, no toda red; (C) (D) hacen falta AMBOS (sup e ínf) para ser red.'},
  {st: '¿Cuántos mintérminos tiene una función booleana de 3 variables?', opts: ['4', '6', '8', '16'], c: 2, ex: 'Con n variables hay 2ⁿ mintérminos (uno por cada combinación de valores). Con n=3: 2³=8. ▸ Por qué las otras están mal: (A) "4"=2²; (B) "6" no es potencia de 2; (D) "16"=2⁴ (4 variables).'},
  {st: 'La ley de ABSORCIÓN en álgebra de Boole establece que:', opts: [M('a∨(a∧b)=a'), M('a∧(a∨b)=b'), M('a∨b=b∨a'), M('a∧1=0')], c: 0, ex: 'Absorción: a∨(a∧b)=a y a∧(a∨b)=a (el término "absorbe" al otro). ▸ Por qué las otras están mal: (B) a∧(a∨b)=a, no b; (C) a∨b=b∨a es conmutatividad; (D) a∧1=a (elemento neutro del ∧), no 0.'},
  {st: '(D₃₃₀; |) es isomorfo a (P({a,b,c,d}); ⊆) porque 330=2·3·5·11 tiene:', opts: ['3 factores primos', '4 factores primos distintos', '5 factores primos', '2 factores primos'], c: 1, ex: '330=2·3·5·11 tiene 4 factores primos DISTINTOS, igual que |{a,b,c,d}|=4. (Dₙ,|) es isomorfo a (P(X),⊆) con |X| = nº de primos distintos de n, cuando n es libre de cuadrados. Ambos son álgebras de Boole de 2⁴=16 elementos. ▸ Por qué las otras están mal: 330 tiene exactamente 4 primos distintos (contá: 2,3,5,11).'},
  {st: 'El complemento de un elemento a en un álgebra de Boole cumple:', opts: [M("a∧a'=1 y a∨a'=0"), M("a∧a'=0 y a∨a'=1"), M("a∧a'=a"), M("a∨a'=a")], c: 1, ex: "El complemento a' satisface a∧a'=0 (ínfimo: el mínimo) y a∨a'=1 (supremo: el máximo). ▸ Por qué las otras están mal: (A) tiene los resultados invertidos; (C) (D) darían que a' no cambia nada (sería a=a', falso salvo casos triviales)."}
]);

registerExercises('led', '7', [
  {st: 'La recurrencia '+M('aₙ = 5aₙ₋₁ − 6aₙ₋₂')+' es:', opts: ['No homogénea de orden 1', 'Homogénea de orden 2', 'No homogénea de orden 2', 'Homogénea de orden 1'], c: 1, ex: 'Lineal (cada aₙ a la 1), coeficientes constantes, SIN término independiente (homogénea), y orden 2 (la diferencia entre el subíndice mayor n y el menor n−2 es 2). ▸ Por qué las otras están mal: (A) (D) el orden no es 1 (depende de DOS términos previos); (C) no hay término libre, así que es homogénea.'},
  {st: 'La ecuación característica de '+M('aₙ = 5aₙ₋₁ − 6aₙ₋₂')+' es:', opts: [M('r²=5r−6'), M('r=5−6r'), M('r²−5r+6=0'), M('r+5r−6=0')], c: 2, ex: 'Sustituyo aₙ=rⁿ: rⁿ=5rⁿ⁻¹−6rⁿ⁻². Divido todo por rⁿ⁻²: r²=5r−6, o sea r²−5r+6=0. ▸ Por qué las otras están mal: (A) r²=5r−6 es lo mismo pero sin pasar a la forma =0 (aceptable pero la forma estándar es la C); (B) (D) no resultan de la sustitución correcta. Resolviendo: (r−2)(r−3)=0 → raíces 2 y 3.'},
  {st: 'Si la ecuación característica tiene raíces simples r₁≠r₂, la solución general es:', opts: [M('aₙ=c·r₁ⁿ'), M('aₙ=c₁·r₁ⁿ+c₂·r₂ⁿ'), M('aₙ=c₁·n·r₁ⁿ+c₂·r₂ⁿ'), M('aₙ=(c₁+c₂n)·r₁ⁿ')], c: 1, ex: 'Dos raíces distintas → solución = combinación lineal de las dos potencias: aₙ = c₁·r₁ⁿ + c₂·r₂ⁿ. Las constantes c₁,c₂ se hallan con las condiciones iniciales. ▸ Por qué las otras están mal: (A) le falta el segundo término; (C) (D) la forma con el factor n se usa para raíz DOBLE, no simples.'},
  {st: 'Si la ecuación característica tiene raíz DOBLE r₁=r₂=r, la solución general es:', opts: [M('aₙ=c·rⁿ'), M('aₙ=c₁·rⁿ+c₂·rⁿ'), M('aₙ=(c₁+c₂·n)·rⁿ'), M('aₙ=c₁·r²ⁿ')], c: 2, ex: 'Raíz doble → aₙ=(c₁+c₂·n)·rⁿ. El factor n es necesario para tener DOS soluciones linealmente independientes (rⁿ y n·rⁿ). ▸ Por qué las otras están mal: (A) tiene un solo grado de libertad; (B) c₁·rⁿ+c₂·rⁿ=(c₁+c₂)·rⁿ colapsa en una constante; (D) r²ⁿ no surge.'},
  {st: '¿Cuál de las siguientes PUEDE ser solución general de una recurrencia homogénea de orden 2?', opts: [M('aₙ=k·(−3)ⁿ+t·5ⁿ'), M('aₙ=k·(−3)ⁿ+t·5ⁿ+n²'), M('aₙ=k·2ⁿ+t·2ⁿ'), M('aₙ=k·(−4)ⁿ+t')], c: 0, ex: 'Una homogénea de orden 2 tiene solución con DOS raíces distintas y dos constantes: k·(−3)ⁿ+t·5ⁿ (raíces −3 y 5) ✓. ▸ Por qué las otras están mal: (B) el +n² indica una recurrencia NO homogénea; (C) k·2ⁿ+t·2ⁿ=(k+t)·2ⁿ tiene una sola raíz (debería llevar factor n); (D) el "+t" suelto (=t·1ⁿ) tiene raíz 1, válido, pero "t" sin potencia mezcla mal — la forma canónica con dos raíces distintas y dos potencias es la A.'},
  {st: 'Para la recurrencia NO homogénea '+M('aₙ₊₂ − 6aₙ₊₁ + 5aₙ = −12')+', la solución general se obtiene:', opts: ['Solo con la solución homogénea', 'Solo con una solución particular', 'Sumando solución homogénea + solución particular', 'Por inducción'], c: 2, ex: 'Solución general de una no homogénea = solución de la homogénea asociada (aₙ₊₂−6aₙ₊₁+5aₙ=0) MÁS una solución particular del término independiente. ▸ Por qué las otras están mal: (A) (B) ninguna sola alcanza; (D) la inducción sirve para verificar, no para hallar la solución general.'},
  {st: 'Si una recurrencia tiene solución particular aₙ=3·2ⁿ y la homogénea aₙ=c·2ⁿ, la solución general es:', opts: [M('aₙ=3·2ⁿ'), M('aₙ=(c+3)·2ⁿ'), M('aₙ=c·n·2ⁿ+3·2ⁿ'), M('aₙ=c·2ⁿ')], c: 1, ex: 'General = homogénea + particular = c·2ⁿ + 3·2ⁿ = (c+3)·2ⁿ. ▸ Ojo: si la particular tiene la MISMA base que la homogénea (ambas 2ⁿ), en rigor la particular debería llevar factor n (c·n·2ⁿ) para ser independiente; pero con los datos dados como están, la suma directa da (c+3)·2ⁿ. ▸ Por qué las otras están mal: (A) (D) son solo una de las dos partes; (C) tendría sentido si la base coincidiera y se aplicara el ajuste.'},
  {st: 'La sucesión de Fibonacci '+M('Fₙ=Fₙ₋₁+Fₙ₋₂')+' tiene ecuación característica:', opts: [M('r²−r−1=0'), M('r²+r−1=0'), M('r²−r+1=0'), M('r²+r+1=0')], c: 0, ex: 'Sustituyo Fₙ=rⁿ: rⁿ=rⁿ⁻¹+rⁿ⁻², divido por rⁿ⁻²: r²=r+1 → r²−r−1=0. Sus raíces son φ=(1+√5)/2 (número áureo) y (1−√5)/2. ▸ Por qué las otras están mal: (B) (C) (D) tienen signos incorrectos; al sustituir bien queda r²−r−1=0.'}
]);

registerExercises('led', '8', [
  {st: '¿Cuánto vale 541 mod 3?', opts: ['0', '1', '2', '3'], c: 1, ex: '541 = 180·3 + 1, así que el resto es 1 → 541≡1 (mod 3). Truco: la suma de cifras 5+4+1=10, y 10≡1 (mod 3). ▸ Por qué las otras están mal: (A) "0" sería si 3 dividiera exacto; (C) (D) el resto al dividir por 3 solo puede ser 0,1,2 — nunca 3.'},
  {st: 'Si a≡b (mod n) y c≡d (mod n), entonces:', opts: [M('a·c≡b·d (mod n)'), M('a·c≡b+d (mod n)'), M('a+c≡b·d (mod n)'), M('a−c≡b+d (mod n)')], c: 0, ex: 'Las congruencias se pueden multiplicar miembro a miembro: a≡b y c≡d ⟹ a·c≡b·d (mod n). También se pueden sumar y restar. ▸ Por qué las otras están mal: (B) (C) (D) mezclan suma con producto incorrectamente. La regla preserva la operación: producto con producto, suma con suma.'},
  {st: 'El inverso multiplicativo de 3 en ℤ₇ es:', opts: ['3', '4', '5', '6'], c: 2, ex: 'Busco x con 3x≡1 (mod 7). Pruebo: 3·5=15=2·7+1≡1 ✓. El inverso de 3 es 5. ▸ Por qué las otras están mal: (A) 3·3=9≡2; (B) 3·4=12≡5; (D) 3·6=18≡4. Solo 5 da 1. Existe inverso porque mcd(3,7)=1.'},
  {st: 'El Pequeño Teorema de Fermat dice: si p es primo y p∤a, entonces:', opts: [M('aᵖ≡1 (mod p)'), M('aᵖ⁻¹≡1 (mod p)'), M('aᵖ≡a (mod p)'), M('aᵖ⁻¹≡a (mod p)')], c: 1, ex: 'Fermat: si p es primo y no divide a a, entonces aᵖ⁻¹≡1 (mod p). ▸ Por qué las otras están mal: (A) aᵖ≡a (mod p) es la versión equivalente (no aᵖ≡1); (C) aᵖ≡a sí vale pero es otra forma (vale incluso si p|a); (D) aᵖ⁻¹≡a es falsa en general. La forma estándar es aᵖ⁻¹≡1.'},
  {st: '¿Cuál es el resto de dividir 3⁶⁰ por 61?', opts: ['1', '3', '60', '0'], c: 0, ex: '61 es primo y mcd(3,61)=1. Por el Pequeño Teorema de Fermat: 3⁶¹⁻¹ = 3⁶⁰ ≡ 1 (mod 61). El resto es 1. ▸ Por qué las otras están mal: (B) "3"=3¹; (C) "60" es p−1 (el exponente, no el resto); (D) "0" sería si 61 dividiera a 3⁶⁰, imposible porque 3 y 61 son coprimos.'},
  {st: 'Para resolver el sistema x≡3 (mod 7), x≡2 (mod 8) se usa:', opts: ['Teorema de Lagrange', 'Teorema Chino del Resto', 'Teorema de Fermat', 'Algoritmo de Euclides directamente'], c: 1, ex: 'El Teorema Chino del Resto resuelve sistemas de congruencias con módulos coprimos (mcd(7,8)=1) y garantiza solución única mód 56 (=7·8). ▸ Por qué las otras están mal: (A) Lagrange es de teoría de grupos; (C) Fermat es para potencias; (D) Euclides halla mcd/inversos (es una herramienta auxiliar, no resuelve el sistema por sí solo).'},
  {st: 'φ(p) (función de Euler) para p primo vale:', opts: [M('p'), M('p−1'), M('p+1'), M('p/2')], c: 1, ex: 'φ(p)=p−1: todos los enteros de 1 a p−1 son coprimos con p (porque p es primo, no comparte factores con ninguno menor). ▸ Por qué las otras están mal: (A) "p" incluiría al propio p (no coprimo consigo mismo); (C) (D) no surgen de la definición. Ej: φ(7)=6.'},
  {st: 'La congruencia 4x≡2 (mod 6) tiene solución porque:', opts: ['4 divide a 6', 'mcd(4,6)=2 divide a 2', 'mcd(4,6)=1', '4 divide a 2'], c: 1, ex: 'ax≡b (mod n) tiene solución ⟺ mcd(a,n) divide a b. Acá mcd(4,6)=2 y 2 | 2 ✓ → tiene solución (de hecho 2 soluciones módulo 6). ▸ Por qué las otras están mal: (A) 4 no divide a 6; (C) mcd(4,6)=2, no 1; (D) "4 divide a 2" es falso (al revés).'}
]);

registerExercises('led', '9', [
  {st: 'Un grupo (G,·) requiere que la operación sea:', opts: ['Cerrada, asociativa, con neutro y con inversos', 'Cerrada y conmutativa', 'Asociativa y conmutativa', 'Cerrada y con neutro solamente'], c: 0, ex: 'Los 4 axiomas de grupo: clausura (a·b∈G), asociatividad, existencia de neutro (e) y existencia de inverso de cada elemento. ▸ Por qué las otras están mal: (B) la conmutatividad NO es obligatoria (define grupo ABELIANO, un caso particular); (C) le faltan neutro e inversos; (D) le faltan asociatividad e inversos.'},
  {st: 'El grupo (ℤ,+) es:', opts: ['Finito y abeliano', 'Infinito y no abeliano', 'Infinito y abeliano', 'Finito y no abeliano'], c: 2, ex: '(ℤ,+) es INFINITO (ℤ tiene infinitos elementos) y ABELIANO (a+b=b+a). Neutro: 0. Inverso de a: −a. ▸ Por qué las otras están mal: (A) (D) ℤ no es finito; (B) la suma sí es conmutativa.'},
  {st: 'El ORDEN de un grupo finito G es:', opts: ['El número de subgrupos de G', 'El número de elementos de G (cardinalidad)', 'El orden del generador', 'El número de operaciones'], c: 1, ex: 'El orden |G| es la cantidad de elementos del conjunto G. ▸ Por qué las otras están mal: (A) la cantidad de subgrupos es otra cosa; (C) el orden de un elemento es distinto del orden del grupo; (D) no se cuentan operaciones.'},
  {st: 'El Teorema de Lagrange establece que si H es subgrupo de un grupo finito G:', opts: [M('|H|=|G|'), M('|H| divide a |G|'), M('|G| divide a |H|'), M('|H|+|G|=|G|')], c: 1, ex: 'Lagrange: el orden de todo subgrupo DIVIDE al orden del grupo (|H| | |G|). Por eso un grupo de orden 12 solo puede tener subgrupos de orden 1,2,3,4,6,12. ▸ Por qué las otras están mal: (A) solo si H=G; (C) al revés (el grande no divide al chico); (D) no tiene sentido.'},
  {st: 'Un grupo G es CÍCLICO si:', opts: ['Todo elemento tiene orden 2', 'Existe un elemento g que genera todo G (todo elemento es potencia de g)', 'G es abeliano', 'G tiene un único subgrupo'], c: 1, ex: 'Cíclico = existe un GENERADOR g tal que G={g⁰,g¹,g²,…}. Ej: (ℤ₆,+) generado por 1. ▸ Por qué las otras están mal: (A) "orden 2" describe otra cosa; (C) todo cíclico es abeliano pero NO todo abeliano es cíclico (ℤ₂×ℤ₂ es abeliano y no cíclico); (D) los cíclicos tienen varios subgrupos (uno por cada divisor del orden).'},
  {st: 'En el grupo (ℤ₆,+), el orden del elemento 2 es:', opts: ['2', '3', '6', '1'], c: 1, ex: 'El orden de 2 es el menor k>0 con k·2≡0 (mod 6). Sumo: 2, 2+2=4, 4+2=6≡0. Llegué a 0 en 3 pasos → ord(2)=3. ▸ Por qué las otras están mal: (A) 2·2=4≠0; (C) "6" es el orden del grupo; (D) "1" sería para el neutro (0). Nota: ord(2)=6/mcd(2,6)=6/2=3.'},
  {st: '¿Cuál de los siguientes NO es un grupo con la operación indicada?', opts: [M('(ℤ, +)'), M('(ℕ, +)'), M('(ℤ, ·)'), M('(ℚ−{0}, ·)')], c: 1, ex: '(ℕ,+) NO es grupo: los naturales no tienen inverso aditivo (el inverso de 3 sería −3 ∉ ℕ). Falta el axioma de inversos. ▸ Por qué las otras están mal: (A) (ℤ,+) sí es grupo; (D) (ℚ−{0},·) también (inverso de a es 1/a). OJO: (ℤ,·) tampoco es grupo (2 no tiene inverso entero), pero la pregunta pide UNA y (ℕ,+) es el ejemplo canónico — verificá igual que (ℤ,·) comparte el problema.'},
  {st: 'Todo grupo de orden primo p es:', opts: ['No abeliano', 'Cíclico y abeliano', 'Con subgrupos propios no triviales', 'Isomorfo a ℤ'], c: 1, ex: 'Por Lagrange, un grupo de orden primo p solo tiene subgrupos de orden 1 y p (no hay divisores intermedios) → cualquier elemento ≠ e genera todo el grupo → es CÍCLICO, y todo cíclico es ABELIANO. ▸ Por qué las otras están mal: (A) es abeliano; (C) no tiene subgrupos propios no triviales; (D) es isomorfo a ℤ_p (finito), no a ℤ (infinito).'}
]);

registerExercises('led', '10', [
  {st: 'En un grafo simple con 5 vértices, la suma de los grados es 8. ¿Cuántas aristas tiene?', opts: ['4', '8', '16', '5'], c: 0, ex: 'Lema del apretón de manos (handshaking): la suma de grados = 2·|aristas|. Entonces |aristas| = 8/2 = 4. ▸ Por qué las otras están mal: (B) "8" es la suma de grados (no las aristas); (C) "16"=8·2 (al revés); (D) "5" es la cantidad de vértices.'},
  {st: 'Un grafo EULERIANO (tiene circuito de Euler) es aquel que:', opts: ['Tiene un camino que visita cada vértice una vez', 'Tiene un circuito que recorre cada ARISTA exactamente una vez', 'Es conexo y sin ciclos', 'Tiene todos los vértices de grado impar'], c: 1, ex: 'Circuito euleriano = recorre cada ARISTA exactamente una vez y vuelve al inicio. Existe ⟺ el grafo es conexo y TODOS los vértices tienen grado par. ▸ Por qué las otras están mal: (A) eso es HAMILTONIANO (vértices, no aristas); (C) "sin ciclos" sería un árbol; (D) al revés: Euler necesita grados PARES.'},
  {st: 'Un ÁRBOL con n vértices tiene exactamente:', opts: ['n aristas', 'n−1 aristas', 'n+1 aristas', '2n aristas'], c: 1, ex: 'Un árbol (grafo conexo y acíclico) siempre tiene n−1 aristas. Agregar una arista crea un ciclo; quitar una lo desconecta. ▸ Por qué las otras están mal: (A) "n" tendría un ciclo; (C) (D) demasiadas aristas para mantenerse acíclico.'},
  {st: 'El algoritmo de Dijkstra resuelve:', opts: ['Árbol generador mínimo', 'Camino más corto desde un vértice origen', 'Coloración de grafos', 'Circuito hamiltoniano'], c: 1, ex: 'Dijkstra halla el camino de menor peso desde un origen a todos los demás vértices (pesos no negativos). ▸ Por qué las otras están mal: (A) el árbol generador mínimo lo resuelven Kruskal/Prim; (C) coloración es otro problema; (D) el circuito hamiltoniano es NP-difícil, no lo resuelve Dijkstra.'},
  {st: 'El algoritmo de Kruskal construye un árbol generador mínimo (MST) seleccionando aristas:', opts: ['De mayor peso primero', 'De menor peso primero, descartando las que formen ciclo', 'Adyacentes al árbol parcial', 'Al azar'], c: 1, ex: 'Kruskal (greedy): ordena todas las aristas de menor a mayor peso y las va agregando si NO forman ciclo, hasta conectar todo. ▸ Por qué las otras están mal: (A) menor peso, no mayor; (C) "adyacentes al árbol parcial" describe a PRIM (no Kruskal); (D) no es aleatorio.'},
  {st: 'Un grafo HAMILTONIANO tiene:', opts: ['Un circuito que pasa por cada arista una vez', 'Un camino que pasa por cada vértice una vez', 'Un circuito que pasa por cada VÉRTICE exactamente una vez', 'Todos los vértices de grado ≥2'], c: 2, ex: 'Circuito hamiltoniano = recorre cada VÉRTICE exactamente una vez y vuelve al inicio. ▸ Por qué las otras están mal: (A) "cada arista" es EULERIANO; (B) describe un CAMINO hamiltoniano (no circuito, no vuelve); (D) grado ≥2 es necesario pero no suficiente.'},
  {st: 'Un grafo es BIPARTITO si sus vértices se pueden partir en dos conjuntos tales que:', opts: ['Todas las aristas están dentro del mismo conjunto', 'Toda arista conecta un vértice de un conjunto con uno del otro', 'Ambos conjuntos tienen igual tamaño', 'No tiene ciclos'], c: 1, ex: 'Bipartito: V se parte en V₁ y V₂ y toda arista va de V₁ a V₂ (ninguna interna). Equivale a que no tenga ciclos de longitud impar. ▸ Por qué las otras están mal: (A) lo contrario (no puede haber aristas internas); (C) los conjuntos pueden tener distinto tamaño; (D) un bipartito sí puede tener ciclos (pares).'},
  {st: 'El algoritmo de Prim difiere de Kruskal en que:', opts: ['Kruskal usa fuerza bruta', 'Prim hace crecer el árbol desde un vértice inicial; Kruskal selecciona aristas globalmente', 'Prim da un MST de mayor peso', 'No hay diferencia en el resultado ni en el método'], c: 1, ex: 'Prim parte de un vértice y agrega la arista de menor peso que CONECTA el árbol parcial con un vértice nuevo. Kruskal mira TODAS las aristas globalmente, de menor a mayor, evitando ciclos. Ambos dan un MST (mismo peso total). ▸ Por qué las otras están mal: (A) Kruskal es greedy, no fuerza bruta; (C) ambos dan MÍNIMO; (D) el resultado (peso) coincide, pero el MÉTODO es distinto.'}
]);
