// ESTRATEGIA GENERAL Y FÓRMULAS CLAVE
registerExercises('fisica-parcial', '1', [
  {st: 'En el 1° parcial Torti, ¿qué unidades NO entran?', opts: ['Mediciones', 'Vectores y Estática', 'Hidrostática y Cinemática 1D', 'Tiro oblicuo, Dinámica y Energía'], c: 3, ex: 'El 1° parcial cubre Unidades 0–4 (Medición, Vectores, Estática, Hidrostática, Cinemática 1D). ▸ Tiro oblicuo (U5), Dinámica (U6) y Energía (U7) caen en el 2° parcial. ▸ Por qué las otras están mal: (A) (B) (C) son temas que SÍ entran al 1° parcial.'},
  {st: 'Si el enunciado dice "presión a una profundidad", "prensa hidráulica" o "qué fracción del cuerpo flota", el tema es:', opts: ['Vectores', 'Estática', 'Hidrostática', 'Cinemática 1D'], c: 2, ex: 'Profundidad y presión → teorema fundamental p = p₀ + δgh. Prensa → Pascal F₁/A₁ = F₂/A₂. Flotación → Arquímedes E = δVg. Todos hidrostática. ▸ Por qué las otras están mal: (A) vectores no habla de fluidos; (B) estática trata fuerzas en sólidos; (D) cinemática es movimiento.'},
  {st: 'La estrategia general antes de meter números en cualquier ejercicio del parcial es:', opts: ['Probar las 4 opciones', 'Convertir todas las cantidades a unidades SI y dibujar un esquema', 'Calcular en la calculadora directamente', 'Buscar la fórmula más larga'], c: 1, ex: 'Convertir a SI evita errores de factor 3,6 (km/h vs m/s) o 1000 (g/cm³ vs kg/m³). Dibujar el esquema (DCL, sistema de referencia, vectores) evita errores de signo. ▸ El 60% de los errores en parciales vienen de no convertir o no dibujar. ▸ Por qué las otras están mal: (A) lento y poco confiable; (C) sin entender el problema; (D) la fórmula más simple suele ser la correcta.'},
  {st: 'Para el equilibrio de un cuerpo extenso (no puntual), las condiciones necesarias son:', opts: ['Solo ΣF = 0', 'Solo ΣM = 0', 'ΣF = 0 Y ΣM = 0', 'ΣF = m·a'], c: 2, ex: 'Cuerpo extenso necesita AMBAS condiciones: ▸ ΣF=0 evita traslación. ▸ ΣM=0 evita rotación. ▸ Sin la 2ª, podría haber un par puro (par de fuerzas iguales y opuestas que rotan al cuerpo). ▸ Por qué las otras están mal: (A) (B) condiciones individuales son insuficientes; (D) implica aceleración (no equilibrio).'},
  {st: '¿Cuál es la conversión rápida de km/h a m/s?', opts: ['Multiplicar por 3,6', 'Dividir por 3,6', 'Multiplicar por 60', 'Dividir por 60'], c: 1, ex: 'km/h → m/s: dividir por 3,6 (que es 3600 s/h ÷ 1000 m/km). ▸ Por ejemplo: 72 km/h ÷ 3,6 = 20 m/s. ▸ Para el camino inverso (m/s → km/h): multiplicar por 3,6. ▸ Por qué las otras están mal: (A) es la conversión inversa; (C) (D) corresponden a otras conversiones (s/min, etc.).'}
]);

// TIPO 1: MEDICIONES, UNIDADES Y DIMENSIONES
registerExercises('fisica-parcial', '2', [
  {st: 'Pasar 90 km/h a m/s.', opts: ['9 m/s', '15 m/s', '25 m/s', '324 m/s'], c: 2, ex: 'km/h → m/s se DIVIDE por 3,6. ▸ 90/3,6 = 25 m/s. ▸ Verificación: 90·1000/3600 = 90.000/3600 = 25 m/s. ▸ Por qué las otras están mal: (A) divide por 10; (B) divide por 6; (D) multiplica por 3,6 en lugar de dividir.'},
  {st: 'Convertir 2,7 g/cm³ a kg/m³.', opts: ['0,0027 kg/m³', '2,7 kg/m³', '270 kg/m³', '2700 kg/m³'], c: 3, ex: 'g/cm³ → kg/m³: MULTIPLICAR por 1000. ▸ 2,7 · 1000 = 2700 kg/m³ (densidad del aluminio). ▸ Cálculo detallado: (1 kg/1000 g) · (10⁶ cm³/1 m³) = 1000 (factor neto). ▸ Por qué las otras están mal: (A) divide por 1000; (B) sin conversión; (C) factor 100 incorrecto.'},
  {st: '¿Cuántas cifras significativas tiene 0,00405?', opts: ['2', '3', '5', '6'], c: 1, ex: 'Reglas: ceros a la izquierda NO cuentan; ceros entre dígitos no nulos SÍ cuentan. ▸ Cifras: 4, 0 (entre 4 y 5), 5 → <b>3 cifras</b>. ▸ Por qué las otras están mal: (A) ignora el cero del medio; (C) cuenta los ceros de la izquierda; (D) cuenta todos los dígitos del número.'},
  {st: 'Resultado de 12,4 + 0,356 con cifras significativas:', opts: ['12,756', '12,76', '12,8', '13'], c: 2, ex: 'Regla de SUMA: el resultado conserva tantos DECIMALES como el dato con menos decimales. ▸ 12,4 (1 decimal) + 0,356 (3 decimales) → resultado con 1 decimal. ▸ 12,756 → redondeado a 1 decimal: 12,8. ▸ Por qué las otras están mal: (A) (B) más decimales que 12,4; (D) entero (cero decimales) ya redondea de más.'},
  {st: 'Expresar 384.000.000 en notación científica.', opts: [M('38,4 · 10⁷'), M('3,84 · 10⁸'), M('0,384 · 10⁹'), M('3,84 · 10⁶')], c: 1, ex: 'Notación científica: a · 10ⁿ con 1 ≤ |a| < 10. ▸ Corro la coma 8 lugares hacia la izquierda: 3,84 · 10⁸. ▸ Por qué las otras están mal: (A) "38,4" no cumple a<10; (C) "0,384" no cumple a≥1; (D) la coma está corrida solo 6 lugares.'},
  {st: '¿Es dimensionalmente consistente la ecuación v = a·t?', opts: ['Sí, ambos lados son m/s', 'No, a·t da m/s²', 'Sí, ambos lados son m/s²', 'No, los signos no coinciden'], c: 0, ex: '[v] = m/s. [a·t] = (m/s²)·s = m/s. ▸ Coinciden → CONSISTENTE. ▸ Por qué las otras están mal: (B) confunde unidades de a con a·t; (C) v no tiene unidades de aceleración; (D) las unidades no tienen "signo".'},
  {st: '¿Cuál de las siguientes NO es una unidad fundamental del SI?', opts: ['kg', 'm', 's', 'N'], c: 3, ex: 'El Newton es DERIVADA: N = kg·m/s². Las 7 fundamentales son: m (longitud), kg (masa), s (tiempo), A (corriente), K (temperatura), mol (cantidad), cd (intensidad luminosa). ▸ Por qué las otras están mal: kg, m, s SÍ son fundamentales.'},
  {st: 'El orden de magnitud de 4,8·10⁵ es:', opts: [M('10⁴'), M('10⁵'), M('10⁶'), M('5')], c: 1, ex: 'Orden de magnitud = potencia de 10 más cercana. ▸ Como 4,8 < 5, el redondeo va hacia abajo → 10⁵. ▸ Si fuera 5·10⁵ o más, sería 10⁶. ▸ Por qué las otras están mal: (A) "10⁴" sería para 0,1–0,5; (C) requiere coeficiente ≥ 5; (D) "5" es solo el coeficiente, no orden de magnitud.'}
]);

// TIPO 2: VECTORES EN EL PLANO
registerExercises('fisica-parcial', '3', [
  {st: 'Si '+M('A⃗ = 3î + 4ĵ')+', ¿cuál es su módulo?', opts: ['3', '4', '5', '7'], c: 2, ex: '|A| = √(Aₓ² + Aᵧ²) = √(9+16) = √25 = 5. ▸ Triángulo 3-4-5 (Pitágoras clásico). ▸ Por qué las otras están mal: (A) (B) son las componentes individuales; (D) "7" sería 3+4 (suma sin Pitágoras).'},
  {st: 'Un vector de módulo 10 forma 30° con el eje x. ¿Cuál es su componente x?', opts: ['5', '5√3 ≈ 8,66', '10', '10/√3'], c: 1, ex: 'Aₓ = |A|·cos(θ) = 10·cos(30°) = 10·(√3/2) = 5√3 ≈ 8,66. ▸ Por qué las otras están mal: (A) "5" sería con sen 30° (es decir, la componente y); (C) "10" es el módulo total; (D) no surge de la fórmula.'},
  {st: 'Calcular '+M('A⃗ + B⃗')+' con '+M('A⃗ = (2, 3)')+' y '+M('B⃗ = (−1, 4)')+'.', opts: [M('(1, 7)'), M('(3, −1)'), M('(1, 12)'), M('(−2, 12)')], c: 0, ex: 'Suma componente a componente: (2+(−1), 3+4) = (1, 7). ▸ Por qué las otras están mal: (B) hace resta en lugar de suma; (C) (D) multiplican componentes en lugar de sumarlas.'},
  {st: 'Producto escalar de '+M('A⃗ = 2î + 3ĵ')+' y '+M('B⃗ = 4î − ĵ')+'.', opts: ['5', '8', '11', '14'], c: 0, ex: 'A·B = AₓBₓ + AᵧBᵧ = 2·4 + 3·(−1) = 8 − 3 = 5. ▸ Por qué las otras están mal: (B) "8" es solo Aₓ·Bₓ (sin sumar la 2ª); (C) (D) confunden suma con multiplicación.'},
  {st: '¿Cuándo dos vectores son perpendiculares?', opts: ['Cuando tienen el mismo módulo', 'Cuando su producto escalar es cero', 'Cuando su suma es cero', 'Cuando su producto vectorial es cero'], c: 1, ex: 'A·B = |A||B|·cos(θ). Si θ = 90° → cos = 0 → A·B = 0. ▸ Por qué las otras están mal: (A) módulos iguales no implican ángulo; (C) suma cero implica que son opuestos (paralelos en sentidos opuestos); (D) producto vectorial cero implica que son PARALELOS, no perpendiculares.'},
  {st: 'Si '+M('A⃗ = 3î + 4ĵ')+' y '+M('B⃗ = 2î − ĵ')+', ¿cuánto vale '+M('A⃗ × B⃗')+'?', opts: [M('(−11) k̂'), M('11 k̂'), M('2 k̂'), M('10 k̂')], c: 0, ex: 'Producto vectorial 2D: (AₓBᵧ − AᵧBₓ)·k̂ = (3·(−1) − 4·2)·k̂ = (−3 − 8)·k̂ = −11 k̂. ▸ Apunta hacia −k̂. ▸ Por qué las otras están mal: (B) signo invertido; (C) (D) cálculos parciales.'},
  {st: 'El ángulo entre '+M('A⃗ = (1, 0)')+' y '+M('B⃗ = (1, 1)')+' es:', opts: ['0°', '30°', '45°', '60°'], c: 2, ex: 'cos(θ) = (A·B)/(|A||B|) = 1/(1·√2) = √2/2 → θ = 45°. ▸ Geométricamente: B = (1,1) está en la diagonal entre el eje x y el eje y → 45° respecto a x. ▸ Por qué las otras están mal: (A) sería si fueran iguales; (B) (D) cosenos no coinciden con esos ángulos.'},
  {st: 'Dos fuerzas de 100 N y 80 N actúan en direcciones opuestas. ¿Cuál es la fuerza resultante?', opts: ['20 N en el sentido de la de 80 N', '20 N en el sentido de la de 100 N', '180 N', '0 N'], c: 1, ex: 'Direcciones opuestas → restar módulos. |100 − 80| = 20 N en sentido de la mayor (la de 100 N). ▸ Por qué las otras están mal: (A) sentido invertido; (C) suma como si fueran paralelas (mismo sentido); (D) cero solo si fueran iguales.'}
]);

// TIPO 3: ESTÁTICA
registerExercises('fisica-parcial', '4', [
  {st: 'Un niño de 21 kg se sienta a 2 m del centro de un subibaja. ¿A qué distancia del centro debe sentarse, del otro lado, su padre de 105 kg para equilibrar?', opts: ['0,20 m', '0,40 m', '0,80 m', '10 m'], c: 1, ex: 'Equilibrio de momentos: m₁·d₁ = m₂·d₂ → 21·2 = 105·d → d = 42/105 = 0,40 m. ▸ Intuición: el padre pesa 5× más → debe estar a 1/5 de la distancia. ▸ Por qué las otras están mal: cálculos parciales o invertidos.'},
  {st: '¿Qué es la "fuerza normal" en un DCL?', opts: ['La fuerza gravitatoria', 'La reacción de la superficie, perpendicular a ella', 'La fuerza de rozamiento', 'Siempre es igual al peso'], c: 1, ex: 'Normal: reacción de la superficie de apoyo, perpendicular a esa superficie. ▸ Por qué las otras están mal: (A) "gravitatoria" es el peso; (C) "rozamiento" es paralelo (no perpendicular); (D) "siempre igual al peso" es FALSO en planos inclinados o cuando hay otras fuerzas verticales.'},
  {st: 'Una lámpara de peso P está sostenida por dos cuerdas simétricas con tensión T. Si la tensión en cada cuerda vale exactamente P, ¿qué ángulo α forman las cuerdas con la horizontal?', opts: ['45°', '37°', '60°', '30°'], c: 3, ex: 'Por simetría: ambas cuerdas tienen el mismo α. Equilibrio vertical: 2·T·sen(α) = P. Como T = P: 2P·sen(α) = P → sen(α) = 1/2 → α = 30°. ▸ Por qué las otras están mal: (A) requeriría T = P/√2 ≈ 0,71·P; (B) requeriría sen 37° ≈ 0,6 → T ≈ 0,83·P; (C) sen 60° ≈ 0,87 → T ≈ 0,58·P.'},
  {st: 'Un cable vertical sostiene un peso P. ¿Cuál es la tensión del cable?', opts: ['0', 'P/2', 'P', '2P'], c: 2, ex: 'Equilibrio vertical: T − P = 0 → T = P. ▸ Una sola cuerda vertical sostiene todo el peso. ▸ Por qué las otras están mal: (A) cero implicaría cuerda floja (no sostiene); (B) (D) no surgen del equilibrio simple.'},
  {st: 'Un auto tiene 53% de su peso sobre las ruedas delanteras y 47% sobre las traseras, con 2,46 m entre ejes. ¿A qué distancia del eje TRASERO está el centro de gravedad?', opts: ['1,16 m', '1,30 m', '1,50 m', '2,46 m'], c: 1, ex: 'Tomando momentos respecto al eje trasero: el peso (en el CG, a distancia x del eje trasero) genera momento P·x. La fuerza del eje delantero (0,53·P, a distancia 2,46 m del trasero) genera momento 0,53·P·2,46. Iguales: x = 0,53·2,46 ≈ 1,30 m. ▸ Por qué las otras están mal: (A) usaría el 47% mal; (C) (D) sin cálculo.'},
  {st: 'En una palanca en equilibrio, si DUPLICÁS la fuerza en un extremo sin cambiar la distancia, ¿qué pasa con el otro extremo?', opts: ['Se duplica su fuerza (manteniendo d)', 'La distancia debe duplicarse', 'Nada cambia', 'La fuerza debe reducirse a la mitad'], c: 0, ex: 'F₁·d₁ = F₂·d₂. Si duplicás F₁ con d₁ fijo → 2F₁·d₁ = F₂·d₂. Para mantener la igualdad, F₂ debe duplicarse (con d₂ fijo). ▸ Por qué las otras están mal: (D) sería el caso si quisiéramos mantener la palanca con la mitad del momento.'},
  {st: 'El momento de una fuerza depende de:', opts: ['Solo de la magnitud de la fuerza', 'Solo de la distancia al eje', 'De la fuerza, la distancia al eje y el ángulo entre ambos', 'Solo del ángulo'], c: 2, ex: 'M = F·d·sen(α). Los tres factores intervienen. ▸ F paralela al brazo (α = 0) → torque cero (sen 0 = 0). Perpendicular (α = 90) → torque máximo (sen 90 = 1). ▸ Por qué las otras están mal: (A) (B) (D) factores parciales (incompletos).'},
  {st: '¿Dónde conviene plantear la ecuación de momentos en un problema de estática?', opts: ['En el centro del cuerpo', 'En cualquier punto, pero conviene donde haya una fuerza desconocida', 'Siempre en el piso', 'Siempre en el punto más alto'], c: 1, ex: '"Cualquier punto" da una ecuación válida. Estratégicamente: si elegís el punto donde actúa una fuerza desconocida, su momento es 0 (brazo cero) y la ecuación queda con menos incógnitas. ▸ Por qué las otras están mal: (A) (C) (D) son opciones rígidas, sin estrategia.'}
]);

// TIPO 4: HIDROSTÁTICA
registerExercises('fisica-parcial', '5', [
  {st: '¿Cuál es la unidad SI de la presión?', opts: ['Newton (N)', 'Pascal (Pa)', 'kg/m³', 'atm'], c: 1, ex: 'Pa = N/m² (fuerza por unidad de área). ▸ 1 atm = 1,013·10⁵ Pa (presión atmosférica al nivel del mar). ▸ Por qué las otras están mal: (A) Newton es FUERZA, no presión; (C) "kg/m³" es DENSIDAD; (D) atm no es SI (es una unidad práctica).'},
  {st: '¿Cómo varía la presión con la profundidad en un fluido en reposo?', opts: ['Constante', 'Aumenta linealmente', 'Aumenta con el cuadrado', 'Disminuye'], c: 1, ex: 'Teorema fundamental: p = p₀ + δ·g·h. Lineal en h. ▸ Por qué las otras están mal: (A) sí cambia con h; (C) sería δ·g·h² (no es así); (D) la presión AUMENTA con la profundidad, no disminuye.'},
  {st: 'Un cubo de 8,5 cm de lado tiene masa de 0,650 kg. ¿Flota en agua? (δ_agua = 1000 kg/m³)', opts: ['Sí, porque δ < 1000', 'No, porque δ > 1000', 'Sí, siempre flota', 'Depende de la temperatura'], c: 1, ex: 'V = (0,085 m)³ ≈ 6,14·10⁻⁴ m³. δ = m/V ≈ 1059 kg/m³ > 1000 → SE HUNDE. ▸ Por qué las otras están mal: (A) requiere δ < 1000 (no se cumple); (C) sin verificar densidad; (D) la temperatura cambia poco la densidad del agua.'},
  {st: 'Una pieza de metal pesa 90 g en aire y 75 g sumergida en agua. ¿Cuál es su densidad? (δ_agua = 1 g/cm³)', opts: ['1,2 g/cm³', '6,0 g/cm³', '15 g/cm³', '90 g/cm³'], c: 1, ex: 'Empuje = peso aire − peso sumergido = 90 − 75 = 15 g (corresponde al peso del agua desalojada). ▸ Como δ_agua = 1 g/cm³, ese empuje implica V_desalojado = 15 cm³ (volumen del cuerpo). ▸ δ_metal = m/V = 90/15 = 6 g/cm³. ▸ Por qué las otras están mal: cálculos parciales.'},
  {st: 'En una prensa hidráulica, el émbolo pequeño tiene área A y el grande 6A. ¿Qué fuerza necesitás en el pequeño para sostener 600 N en el grande?', opts: ['100 N', '600 N', '1200 N', '3600 N'], c: 0, ex: 'Pascal: F₁/A₁ = F₂/A₂ → F₁/A = 600/(6A) → F₁ = 600/6 = 100 N. ▸ La prensa multiplica la fuerza por un factor 6. ▸ Por qué las otras están mal: (B) ignora el factor de multiplicación; (C) (D) invierten o exageran.'},
  {st: 'Un objeto tiene densidad mayor que la del agua. Si lo tirás al agua:', opts: ['Flota en la superficie', 'Queda en el medio', 'Se hunde hasta el fondo', 'Flota con la mitad sumergida'], c: 2, ex: 'δ_cuerpo > δ_fluido → empuje < peso → el cuerpo se HUNDE. ▸ Por qué las otras están mal: (A) requeriría densidad menor; (B) requeriría densidad igual; (D) requeriría densidad específica = 0,5·δ_agua.'},
  {st: '¿Por qué se usa mercurio (no agua) en barómetros?', opts: ['Es más barato', 'Su densidad es mucho mayor → columna corta', 'Es transparente', 'Por razones históricas'], c: 1, ex: 'p_atm = δ·g·h. Con Hg (13,6 g/cm³): h ≈ 76 cm. Con agua (1 g/cm³): h ≈ 10 m (impractical para un instrumento). ▸ Por qué las otras están mal: (A) Hg es caro; (C) Hg no es transparente; (D) la razón es física, no histórica.'},
  {st: 'Un cubo de madera (δ = 0,6 g/cm³) flota en agua (δ = 1 g/cm³). ¿Qué fracción del cubo queda sumergida?', opts: ['40%', '50%', '60%', '100%'], c: 2, ex: 'En equilibrio: peso = empuje. ▸ δ_madera·V·g = δ_agua·V_sumergido·g → V_sum/V = δ_madera/δ_agua = 0,6/1 = 60%. ▸ Por encima del agua queda el 40% restante. ▸ Por qué las otras están mal: (A) es el complemento (la parte fuera del agua); (B) requeriría δ = 0,5; (D) sería sumergido total (cuerpo más denso que el fluido).'}
]);

// TIPO 5: CINEMÁTICA EN UNA DIMENSIÓN
registerExercises('fisica-parcial', '6', [
  {st: '¿Cuál es la diferencia entre velocidad y rapidez?', opts: ['Son lo mismo', 'Velocidad es vectorial (con dirección y sentido); rapidez es escalar (solo módulo)', 'Rapidez es vectorial; velocidad escalar', 'Rapidez es la derivada de la velocidad'], c: 1, ex: 'Velocidad = vector (módulo + dirección + sentido). Rapidez = solo módulo (escalar). ▸ 60 km/h al N tiene la misma rapidez que 60 km/h al S, pero distintas velocidades. ▸ Por qué las otras están mal: (A) son distintas; (C) invertido; (D) la derivada de la velocidad es la ACELERACIÓN.'},
  {st: 'En MRUV con aceleración constante a, ¿cuál es la ecuación horaria de POSICIÓN?', opts: [M('x(t) = x₀ + v·t'), M('x(t) = x₀ + v₀·t + ½·a·t²'), M('x(t) = x₀ + a·t²'), M('x(t) = v₀ + a·t')], c: 1, ex: 'MRUV: posición es CUADRÁTICA en t. ▸ x(t) = x₀ + v₀·t + ½·a·t². ▸ Por qué las otras están mal: (A) es MRU (sin aceleración); (C) le falta el ½ y el v₀·t; (D) es la ecuación de la VELOCIDAD, no de la posición.'},
  {st: 'Un antílope con aceleración constante tarda 7,00 s en pasar 70,0 m, con rapidez final 15 m/s. ¿Rapidez inicial?', opts: ['3 m/s', '5 m/s', '10 m/s', '12,5 m/s'], c: 1, ex: 'v_media = Δx/Δt = 70/7 = 10 m/s. En MRUV: v_media = (v_i + v_f)/2 → (v_i + 15)/2 = 10 → v_i = 5 m/s. ▸ Por qué las otras están mal: (C) "10" es la velocidad media; (A) (D) no surgen.'},
  {st: 'Con los datos del ejercicio anterior (Δx=70, Δt=7, v_f=15), ¿qué aceleración lleva?', opts: ['0,71 m/s²', '1,43 m/s²', '2,14 m/s²', '4,29 m/s²'], c: 1, ex: 'a = (v_f − v_i)/Δt = (15 − 5)/7 = 10/7 ≈ 1,43 m/s². ▸ Por qué las otras están mal: (A) "0,71" sería 5/7; (C) "2,14" sería 15/7; (D) "4,29" no surge.'},
  {st: 'Un malabarista lanza un cuchillo hacia arriba con v₀ = 8,2 m/s. ¿Cuánto tarda en volver a su mano? (g = 9,8)', opts: ['0,84 s', '1,67 s', '2,5 s', '8,2 s'], c: 1, ex: 'En el punto más alto v = 0: 0 = 8,2 − 9,8·t_sub → t_sub ≈ 0,837 s. ▸ Por simetría, el tiempo de bajada al mismo nivel es igual: t_total = 2·0,837 ≈ 1,67 s. ▸ Por qué las otras están mal: (A) solo el tiempo de subida; (C) (D) órdenes de magnitud equivocados.'},
  {st: 'En Marte (g = 3,71 m/s²), una pelota golpeada hacia arriba vuelve al mismo nivel 8,5 s después. ¿Rapidez inicial?', opts: ['7,9 m/s', '15,8 m/s', '31,5 m/s', '63 m/s'], c: 1, ex: 't_subida = 8,5/2 = 4,25 s (por simetría). v₀ = g·t_sub = 3,71·4,25 ≈ 15,8 m/s. ▸ Por qué las otras están mal: (A) usa todo el tiempo dividido por 2; (C) (D) sin dividir el tiempo total.'},
  {st: 'Una piedra cae desde el reposo desde 20 m de altura. ¿Cuánto tarda en tocar el suelo? (g = 10 m/s²)', opts: ['1 s', '2 s', '4 s', '20 s'], c: 1, ex: '0 = 20 − ½·10·t² → 5t² = 20 → t² = 4 → t = 2 s. ▸ Por qué las otras están mal: (A) "1 s" sería para 5 m de caída; (C) "4 s" sería para 80 m; (D) "20 s" daría una caída descomunal.'},
  {st: 'En un gráfico v(t) de un movimiento, ¿qué representa el ÁREA bajo la curva?', opts: ['La aceleración', 'La velocidad media', 'El desplazamiento Δx', 'La posición inicial'], c: 2, ex: 'Geometría: ∫v·dt = Δx. ▸ Por qué las otras están mal: (A) la aceleración es la PENDIENTE de v(t), no el área; (B) v_media es Δx/Δt (no el área directamente); (D) x₀ es solo un valor.'},
  {st: 'Un cohete parte del suelo con v₀ = 50 m/s y acelera 2 m/s² hacia arriba durante 150 m. ¿Rapidez al apagarse?', opts: ['50 m/s', '54 m/s', '56 m/s', '70 m/s'], c: 2, ex: 'Ecuación sin tiempo: v² = v₀² + 2·a·Δx = 2500 + 2·2·150 = 2500 + 600 = 3100 → v = √3100 ≈ 55,7 ≈ 56 m/s. ▸ Por qué las otras están mal: (A) "50" sería sin acelerar; (B) (D) cálculos parciales.'}
]);

// MIX INTEGRADOR
registerExercises('fisica-parcial', '7', [
  {st: 'El error más caro al resolver problemas de cinemática es:', opts: ['Memorizar mal una fórmula', 'No convertir las unidades a SI antes de calcular', 'Usar cifras significativas', 'No usar calculadora'], c: 1, ex: 'Mezclar km/h con m, o g/cm³ con kg, da errores de factor 3,6 o 1000. ▸ El 60% de los errores en parciales vienen de no convertir. ▸ Por qué las otras están mal: (A) puede pasar pero menos frecuente; (C) las cifras significativas no afectan al resultado, solo a su precisión final; (D) la calculadora ayuda, no entorpece.'},
  {st: 'En un problema de cuerpo extenso (viga apoyada), si SOLO planteás ΣF = 0 y NO ΣM = 0:', opts: ['Tenés suficiente información', 'Te falta una ecuación, no podés resolver dos incógnitas', 'Da el mismo resultado', 'No se necesitan ecuaciones de momento en estática'], c: 1, ex: 'ΣF = 0 da una ecuación. Si tenés 2 incógnitas (R_A y R_B), necesitás otra ecuación → ΣM = 0. ▸ Por qué las otras están mal: (A) (C) (D) ignoran que hay dos incógnitas y se necesitan dos ecuaciones.'},
  {st: 'Si elegís "arriba positivo" como sentido del eje en un problema de tiro vertical, ¿qué signo tiene la aceleración?', opts: ['+g', '−g', 'Cero', 'Cambia con el tiempo'], c: 1, ex: 'Eje y positivo hacia arriba → la gravedad apunta HACIA ABAJO → a = −g. ▸ Esto es válido durante TODA la trayectoria (subida, punto alto, bajada). ▸ Por qué las otras están mal: (A) sería con eje positivo hacia abajo; (C) cero es solo durante MRU; (D) g es constante (cerca de la superficie terrestre).'},
  {st: 'Un cubo de 5 cm de lado tiene masa 750 g. ¿Cuál es su densidad?', opts: ['3 g/cm³', '6 g/cm³', '60 g/cm³', '6000 g/cm³'], c: 1, ex: 'V = 5³ = 125 cm³. δ = m/V = 750/125 = 6 g/cm³ (probablemente un acero o aleación). ▸ Por qué las otras están mal: (A) 750/250; (C) (D) errores de potencias en el volumen.'},
  {st: 'Si un vector A tiene componentes (−3, 4), ¿en qué cuadrante está?', opts: ['Primer cuadrante', 'Segundo cuadrante (x<0, y>0)', 'Tercer cuadrante', 'Cuarto cuadrante'], c: 1, ex: 'Aₓ = −3 < 0 e Aᵧ = 4 > 0 → segundo cuadrante. ▸ |A| = √(9+16) = 5. El ángulo desde el eje +x es 180° − arctan(4/3) ≈ 180° − 53° = 127°. ▸ Por qué las otras están mal: cada cuadrante tiene combinación distinta de signos.'},
  {st: 'Una placa cuadrada de 0,5 m² está sumergida horizontalmente a 2 m de profundidad. ¿Qué fuerza ejerce el agua sobre ella? (no contar atmósfera, δ_agua = 1000 kg/m³, g = 10 m/s²)', opts: ['10 N', '1000 N', '10.000 N', '20.000 N'], c: 2, ex: 'p_man = δ·g·h = 1000·10·2 = 2·10⁴ Pa. F = p·A = 2·10⁴·0,5 = 10⁴ = 10.000 N. ▸ Por qué las otras están mal: (A) (B) cálculos parciales; (D) duplica al usar p en lugar de p_manométrica.'},
  {st: 'En un MRUV, si la velocidad y la aceleración tienen MISMO signo:', opts: ['El cuerpo está frenando', 'El cuerpo está acelerando (rapidez crece)', 'Está en reposo', 'No tiene sentido físico'], c: 1, ex: 'Mismo signo → la aceleración "empuja" en el mismo sentido que la velocidad → la rapidez aumenta. ▸ Si signos opuestos → frena (rapidez disminuye). ▸ Por qué las otras están mal: (A) es el caso de signos opuestos; (C) reposo es v = 0; (D) sí tiene sentido (auto que arranca y acelera).'},
  {st: 'Estrategia general para empezar cualquier problema de estática:', opts: ['Calcular las reacciones directamente con una fórmula', 'Hacer el DCL del cuerpo aislado, luego plantear ΣF y ΣM', 'Buscar el centro de gravedad', 'Aplicar la 2ª ley de Newton'], c: 1, ex: 'Sin DCL no sabés qué fuerzas actúan. ▸ Receta: aislar cuerpo → identificar interacciones (peso, normal, tensión, etc.) → dibujar flechas → elegir ejes → ΣF=0 (y ΣM=0 si extenso). ▸ Por qué las otras están mal: (A) "fórmula directa" no existe; (C) parte secundaria del análisis; (D) en estática no hay aceleración (la 2ª ley se reduce a ΣF=0).'}
]);
