// Física I · UTN FRBA · Trabajo y energía
// Ejercicios reales: parciales de la cátedra Martinelli 2009-2017 (_fisica1_ingest/porTema/energia.json)
// + finales UTN.BA 2022-2025 (_fisica1_ingest/porTema/_finales.md).
// Convención de la cátedra en TODA resolución: g = 10 m/s², sen37° = 0,6 · cos37° = 0,8 · sen30° = 0,5.

/* ==================== UNIDAD 1 · ΔE = W de las no conservativas ==================== */

registerExercises('fisica1-utn-energia', '1', [
  {st: 'Un cuerpo baja por una rampa rugosa. ¿Qué fuerzas van del lado derecho de ΔE = W<sub>NC</sub>?',
   opts: ['El peso y el rozamiento dinámico',
          'El peso, la normal y el rozamiento dinámico',
          'Solo el rozamiento dinámico',
          'El rozamiento dinámico y la normal'],
   c: 2,
   ex: 'Del lado derecho van únicamente las fuerzas <b>no conservativas que trabajan</b>. Acá la única es el rozamiento dinámico: W<sub>roz</sub> = −μ<sub>d</sub>·N·d. ▸ Por qué las otras: el <b>peso</b> es conservativo y ya está contabilizado adentro de E como m·g·h, ponerlo también a la derecha te duplica el término (es el error que más descuenta); la <b>normal</b> es perpendicular al desplazamiento, así que su trabajo es exactamente cero y no aporta nada, ni a un lado ni al otro; la opción que junta las tres suma los dos errores a la vez.'},

  {st: 'En el problema C del 1er parcial 2013 la energía en A vale 2000 J y en B vale 1000 J. ¿Cuánto vale el trabajo del rozamiento en el tramo AB?',
   opts: ['+1000 J', '−2000 J', '0 J: la energía mecánica se conserva', '−1000 J'],
   c: 3,
   ex: 'W<sub>roz</sub> = ΔE = E<sub>B</sub> − E<sub>A</sub> = 1000 − 2000 = <b>−1000 J</b>. El signo negativo no es un detalle: el rozamiento siempre se come energía. ▸ Por qué las otras: <b>+1000 J</b> es el mismo número pero con el signo dado vuelta, y si lo ponés positivo el cuerpo terminaría con más energía de la que arrancó; <b>−2000 J</b> confunde el trabajo del rozamiento con la energía potencial inicial completa (el cuerpo llega a B con 1000 J, no con cero); <b>0 J</b> sería el caso de un riel liso, pero el enunciado dice explícitamente que el riel tiene rozamiento.'},

  {st: 'Te piden el <b>tiempo</b> que tarda un cilindro en detenerse mientras sube un plano inclinado. ¿Con qué lo resolvés?',
   opts: ['Con Newton (y después cinemática): la energía no tiene el tiempo adentro',
          'Con energía sola: ΔE = W<sub>NC</sub> alcanza y sobra',
          'Con energía, y después dividiendo la distancia por la velocidad inicial',
          'No se puede resolver sin conocer el coeficiente de rozamiento'],
   c: 0,
   ex: 'La ecuación de energía conecta dos <b>estados</b>, no dos instantes: en ΔE = W<sub>NC</sub> el tiempo no aparece por ningún lado. Apenas el enunciado dice <i>tiempo</i>, <i>aceleración</i>, <i>fuerza</i>, <i>tensión</i> o <i>normal</i>, necesitás ΣF = m·a (y ΣM = I·α si rota). ▸ Por qué las otras: la energía te da la distancia recorrida o la velocidad, pero nunca el tiempo; dividir la distancia por la velocidad inicial supondría movimiento uniforme, y acá el cilindro frena (el movimiento es uniformemente variado, así que habría que usar la velocidad media, y aun así primero necesitás la aceleración); el coeficiente de rozamiento no hace falta cuando el cilindro rueda sin resbalar, ahí el rozamiento es estático y sale como incógnita de las ecuaciones.'},

  {st: 'En el problema del patinador (final UTN.BA 21/2/2024) la pérdida de altura por cada pasada por la zona rugosa de longitud D vale…',
   opts: ['μ<sub>c</sub>·D·m, o sea que un patinador más pesado pierde más altura',
          'μ<sub>c</sub>·D·cos α, con α el ángulo de la loma',
          'μ<sub>c</sub>·D, y no depende de la masa',
          'μ<sub>c</sub>·m·g·D, medido en metros'],
   c: 2,
   ex: 'Planteás m·g·h<sub>f</sub> − m·g·h<sub>i</sub> = −μ<sub>c</sub>·m·g·D y la masa <b>se cancela entera</b>: Δh = μ<sub>c</sub>·D = 0,5·2 = 1 m por pasada. Por eso el problema se puede resolver sin que te den la masa del patinador. ▸ Por qué las otras: dejar la masa adentro significa que no la cancelaste, y además el resultado te quedaría en kg·m, que no es una altura; el cos α aparecería si la zona rugosa estuviera <b>inclinada</b>, pero acá es el tramo horizontal entre las dos lomas; μ<sub>c</sub>·m·g·D es una <b>energía</b> en joules, no una altura en metros (ese es el chequeo de unidades que te salva).'},

  {st: 'Un cuerpo de m = 1 kg está sobre un plano de 37° y lo empujan con una fuerza F = 100 N <b>paralela al plano</b>. ¿Cuánto vale la normal?',
   opts: ['10 N', '108 N', '6 N', '8 N'],
   c: 3,
   ex: 'N = m·g·cos37° = 1·10·0,8 = <b>8 N</b>. Una fuerza paralela al plano no tiene componente perpendicular, así que no toca la normal: es exactamente el caso del problema 4 del parcial 2009. ▸ Por qué las otras: <b>10 N</b> es m·g, la normal del piso horizontal, y usarla te infla el rozamiento un 25%; <b>108 N</b> sale de sumarle F a la normal, que solo valdría si F fuera perpendicular al plano (si fuera <b>horizontal</b> tampoco se suma entera: entraría F·senα); <b>6 N</b> es m·g·sen37°, que es la componente del peso <i>a lo largo</i> del plano, no la perpendicular — intercambiar seno y coseno rompe todo el ejercicio.'},

  {st: 'En el ascensor del final del 2/3/2023 el freno aplica 2500 N durante los 6 m de caída y <b>deja de actuar</b> cuando el ascensor toca el paragolpes. Para calcular la compresión máxima del resorte…',
   opts: ['entre el contacto y la compresión máxima la energía se conserva: ½M·v² + M·g·x = ½·k·x²',
          'hay que seguir descontando el rozamiento a lo largo de la compresión',
          'el peso ya no trabaja, porque a partir del contacto lo sostiene el resorte',
          'v = 0 en el momento del contacto, así que solo queda energía potencial elástica'],
   c: 0,
   ex: 'El enunciado te dice que la fuerza del freno <b>cesa</b> al tocar el paragolpes, así que en ese segundo tramo no hay ninguna fuerza no conservativa: ΔE = 0. El ascensor sigue bajando x mientras comprime, entonces el término M·g·x va del lado de lo que aporta, y te queda una cuadrática. ▸ Por qué las otras: seguir restando el rozamiento contradice el enunciado (y es la trampa deliberada del problema); el peso <b>sí</b> sigue trabajando durante la compresión, el resorte no lo anula, lo frena; y v en el contacto no es cero, es 6,7 m/s — el punto donde v = 0 es el de <b>máxima compresión</b>, no el de contacto.'},
]);

registerReveals('fisica1-utn-energia', '1', [

  {st: '<span class="muted">1er parcial 2013, cátedra Martinelli · 3/9/2013 · curso O1122 · UTN FRBA</span><br><b>C (debe ser resuelto utilizando conceptos de trabajo y energía):</b> Un cuerpo de masa 10 kg, se deja caer desde el punto A (h<sub>A</sub> = 20 m) y desliza por un riel con rozamiento, hasta que lo abandona en B (h<sub>B</sub> = 5 m) con una velocidad cuyo módulo vale 10 m/s. El cuerpo continúa su movimiento hasta tocar el piso por primera vez en C. Determine:<br>a) El trabajo promedio realizado por la fuerza de rozamiento en el tramo AB.<br>b) El módulo de la velocidad del cuerpo en C y el trabajo del peso entre A y C.',
   ans: 'a) W<sub>roz</sub> = −1000 J · b) v<sub>C</sub> = √200 = 14,14 m/s y W<sub>peso</sub>(A→C) = 2000 J',
   sol: '<b>Paso 0. Referencias e hipótesis.</b> Cero de energía potencial gravitatoria en el <b>piso</b> (nivel de C). "Se deja caer" significa v<sub>A</sub> = 0. g = 10 m/s².<br><b>Paso 1. Energías en A y en B.</b><br>E<sub>A</sub> = m·g·h<sub>A</sub> = 10·10·20 = <b>2000 J</b> (no hay cinética).<br>E<sub>B</sub> = m·g·h<sub>B</sub> + ½·m·v<sub>B</sub>² = 10·10·5 + ½·10·10² = 500 + 500 = <b>1000 J</b>.<br><b>Paso 2. a) El trabajo del rozamiento.</b> En AB la única no conservativa que trabaja es el rozamiento (la normal es perpendicular):<br>W<sub>roz</sub> = ΔE<sub>AB</sub> = E<sub>B</sub> − E<sub>A</sub> = 1000 − 2000 = <b>−1000 J</b>.<br>El signo negativo es obligatorio: el riel se comió la mitad de la energía.<br><b>Paso 3. b) La velocidad en C.</b> Entre B y C el cuerpo está <b>en el aire</b>: la única fuerza es el peso, que es conservativo, así que la energía mecánica se conserva. No hace falta el tiempo de vuelo ni el alcance:<br>E<sub>C</sub> = E<sub>B</sub> &nbsp;⟹&nbsp; ½·m·v<sub>C</sub>² = 1000 J &nbsp;⟹&nbsp; 5·v<sub>C</sub>² = 1000<br>v<sub>C</sub>² = 200 m²/s² &nbsp;⟹&nbsp; <b>v<sub>C</sub> = 14,14 m/s</b>.<br><b>Paso 4. El trabajo del peso entre A y C.</b> El peso es conservativo: su trabajo depende solo de las alturas, no del camino (ni del riel curvo ni de la parábola).<br>W<sub>P</sub> = m·g·(h<sub>A</sub> − h<sub>C</sub>) = 10·10·(20 − 0) = <b>2000 J</b>.<br><b>Paso 5. Chequeo de coherencia.</b> El peso puso 2000 J, el rozamiento sacó 1000 J, y al cuerpo le quedan 1000 J de cinética en C. Cierra. Ojo: W<sub>P</sub> = 2000 J <b>no</b> es igual a ½m·v<sub>C</sub>² = 1000 J, justamente por esos 1000 J que se llevó el riel.'},

  {st: '<span class="muted">Final UTN.BA · EXAMEN FINAL 21/2/2024 · problema 1 · el encabezado imprime "Para todos los ejercicios use g = 10 m/s²"</span><br><b>1.</b> Un patinador se dirige hacia una pista, como se observa en la figura, con una velocidad inicial v<sub>0</sub> que es la mínima necesaria para poder alcanzar el primer desnivel de h<sub>i</sub> = 5 m. Suponiendo que se deja caer desde el reposo desde allí, el patinador encontrará un tramo de longitud D = 2 m donde la superficie posee rozamiento y su coeficiente cinético es μ<sub>c</sub> = 0.5. La pista cullmina [sic] con otro desnivel similar al primero. Se pide determinar<br>(i) El valor de la velocidad inicial v<sub>0</sub>.<br>(ii) La altura h<sub>1</sub> a la que llega en la segunda elevación luego de pasar una vez por la zona de rozamiento.<br>(iii) El número de veces necesarias que debe pasar para que su altura máxima sea h<sub>f</sub> = 2 m.',
   ans: '(i) v<sub>0</sub> = 10 m/s · (ii) h<sub>1</sub> = 4 m · (iii) 3 pasadas',
   sol: '<b>Paso 0. Hipótesis.</b> Las lomas son <b>lisas</b> (el enunciado solo pone rozamiento en el tramo D). Cero de V<sub>g</sub> en el piso. La masa del patinador no te la dan… y no hace falta.<br><b>Paso 1. (i) "La mínima necesaria para alcanzar h<sub>i</sub>".</b> Mínima significa que llega arriba con <b>v = 0</b> justo:<br>½·m·v<sub>0</sub>² = m·g·h<sub>i</sub> &nbsp;⟹&nbsp; v<sub>0</sub> = √(2·g·h<sub>i</sub>) = √(2·10·5) = <b>10 m/s</b>. La masa se cancela.<br><b>Paso 2. (ii) Una pasada por la zona rugosa.</b> Baja de h<sub>i</sub>, cruza D y vuelve a subir hasta h<sub>1</sub>:<br>m·g·h<sub>1</sub> − m·g·h<sub>i</sub> = −μ<sub>c</sub>·m·g·D<br>Dividís todo por m·g y te queda un resultado precioso: la altura perdida por pasada es<br><b>Δh = μ<sub>c</sub>·D = 0,5·2 = 1 m</b>, independiente de la masa y de g.<br>h<sub>1</sub> = 5 − 1 = <b>4 m</b>.<br><b>Paso 3. (iii) Cuántas pasadas.</b> Cada cruce le saca el mismo metro, así que después de n cruces:<br>h<sub>n</sub> = h<sub>i</sub> − n·μ<sub>c</sub>·D = 5 − n<br>Pedís h<sub>n</sub> = 2 m &nbsp;⟹&nbsp; n = <b>3 pasadas</b>.<br><b>Paso 4. El detalle que puntúa.</b> Decí explícitamente que la pérdida es la <b>misma en cada cruce</b> porque la normal en el tramo horizontal es constante (N = m·g) y la longitud D también. Ese es el argumento que convierte el inciso (iii) en una división en vez de tres balances encadenados.'},

  {st: '<span class="muted">Final UTN.BA · EXAMEN FINAL 2/3/2023 · problema 2</span><br><b>2.</b> Un ascensor de masa M = 400 kg está en reposo a 6 m del extremo superior de un resorte paragolpes cuya constante elastica es k = 20000 N/m. Súbitamente, se corta el cable que lo sostiene y para detener la caída actúa inmediatamente un freno de fricción contra las guías que le aplica una fuerza, opuesta al desplazamiento, de 2500 N. Esta fuerza sólo cesa cuando el ascensor toma contacto con el paragolpes. Halle:<br>(i) La velocidad del ascensor al llegar al extremo del resorte.<br>(ii) La máxima distancia que lo comprimirá.',
   ans: '(i) v = √45 = 6,71 m/s · (ii) x = 1,17 m',
   sol: '<b>Paso 0. Los dos tramos.</b> Tramo 1: caída libre frenada, 6 m, con la fuerza del freno F<sub>r</sub> = 2500 N. Tramo 2: compresión del resorte, <b>sin</b> freno (el enunciado dice que cesa al tocar). Cero de V<sub>g</sub> en el extremo superior del resorte.<br><b>Paso 1. (i) Tramo 1: ΔE = W<sub>NC</sub>.</b> La única no conservativa es el freno, y su trabajo es negativo porque se opone al desplazamiento:<br>½·M·v² − M·g·h = −F<sub>r</sub>·h<br>½·400·v² = 400·10·6 − 2500·6 = 24000 − 15000 = <b>9000 J</b><br>200·v² = 9000 &nbsp;⟹&nbsp; v² = 45 m²/s² &nbsp;⟹&nbsp; <b>v = 6,71 m/s</b>.<br><b>Paso 2. (ii) Tramo 2: ahora la energía se conserva.</b> Desde el contacto hasta la compresión máxima x (donde v = 0), el ascensor <b>sigue bajando x metros más</b>, así que sigue entregando energía potencial gravitatoria:<br>½·M·v² + M·g·x = ½·k·x²<br>9000 + 400·10·x = ½·20000·x²<br>9000 + 4000·x = 10000·x² &nbsp;⟹&nbsp; 10·x² − 4·x − 9 = 0<br><b>Paso 3. Resolvés la cuadrática.</b><br>x = [4 ± √(16 + 360)]/20 = (4 ± 19,39)/20<br>Se descarta la raíz negativa: <b>x = 1,17 m</b>.<br><b>Paso 4. Las dos trampas.</b> (1) Si seguís restando el freno durante la compresión, el enunciado te contradice: dice <i>"sólo cesa cuando el ascensor toma contacto"</i>. (2) Si te olvidás del término M·g·x pensando que al tocar el resorte el peso deja de trabajar, te da x = 0,95 m y perdés el inciso. El peso trabaja mientras el ascensor se mueva, punto.'},

  {st: '<span class="muted">Final UTN.BA · FINAL 27/2/25 · problema 3</span><br><b>3)</b> Una partícula de masa 1 kg, que puede considerarse puntual, es lanzada por una pista semicircular de radio 1 m. La pista finaliza en un tramo horizontal con rozamiento y finalmente la masa comprime un resorte de constante K = 250 N/m comprimiéndolo 20 cm. Si en el punto más bajo de la trayectoria (A) la fuerza vertical que la pista realiza sobre la masa es de 46 N, calcule el trabajo de las fuerzas no conservativas sobre la masa entre el punto A y la compresión máxima.',
   ans: 'v<sub>A</sub> = 6 m/s y W<sub>NC</sub> = −13 J',
   sol: '<b>Paso 0. Por qué este problema necesita las dos herramientas.</b> El dato que te dan es una <b>fuerza</b> (la normal en A), y lo que te piden es un <b>trabajo</b>. Newton primero, energía después.<br><b>Paso 1. Newton radial en A para sacar v<sub>A</sub>.</b> A es el punto más bajo de la pista semicircular: el centro está arriba, la normal apunta hacia arriba (hacia el centro) y el peso en contra.<br>N − m·g = m·v<sub>A</sub>²/R<br>46 − 1·10 = 1·v<sub>A</sub>²/1 &nbsp;⟹&nbsp; v<sub>A</sub>² = 36 m²/s² &nbsp;⟹&nbsp; <b>v<sub>A</sub> = 6 m/s</b>.<br><b>Paso 2. Energías en los dos estados.</b> Cero de V<sub>g</sub> en el tramo horizontal, que es donde están tanto A como el resorte: la altura no cambia y el término gravitatorio se cancela.<br>E<sub>A</sub> = ½·m·v<sub>A</sub>² = ½·1·36 = <b>18 J</b><br>E<sub>final</sub> = ½·K·Δl² = ½·250·(0,20)² = ½·250·0,04 = <b>5 J</b> &nbsp;(en la compresión máxima v = 0)<br><b>Paso 3. El balance.</b><br>W<sub>NC</sub> = ΔE = E<sub>final</sub> − E<sub>A</sub> = 5 − 18 = <b>−13 J</b>.<br><b>Paso 4. Chequeos.</b> El signo <b>tiene</b> que dar negativo: el único no conservativo que trabaja es el rozamiento del tramo horizontal. Y fijate que el radio de 1 m se usó <b>solo</b> en la ecuación de Newton — no hace falta la altura de la que se lanzó ni el largo del tramo rugoso, porque el trabajo te lo pregunta como un todo, no como −μ·N·d.'},
]);

/* ==================== UNIDAD 2 · Resorte + rozamiento + plano inclinado ==================== */

registerExercises('fisica1-utn-energia', '2', [
  {st: 'Un cuerpo de M<sub>2</sub> = 2 kg cuelga de una cuerda que pasa por una polea ideal y tira de un resorte de k = 100 N/m, inicialmente trabado en su longitud natural. Se destraba. ¿Cuánto desciende M<sub>2</sub> <b>hasta detenerse</b>?',
   opts: ['10 cm', '20 cm', '40 cm', '80 cm'],
   c: 2,
   ex: 'El punto donde se detiene es el de <b>máximo estiramiento</b>, y sale de energía con v = 0: ½·k·Δh² = M<sub>2</sub>·g·Δh ⟹ Δh = 2·M<sub>2</sub>·g/k = 2·2·10/100 = <b>0,40 m</b>. Es el B2 del 1er parcial 2014. ▸ Por qué las otras: <b>20 cm</b> es la respuesta equivocada más frecuente de todo el primer parcial — sale de plantear <i>equilibrio</i> (k·x = M<sub>2</sub>·g), pero el equilibrio es el punto <i>medio</i> del recorrido, el que atraviesa a máxima velocidad, no donde frena; <b>10 cm</b> es M<sub>2</sub>·g/(2k), o sea el error de equilibrio y encima dividido a la mitad; <b>80 cm</b> duplica dos veces (usaría 4·M<sub>2</sub>·g/k).'},

  {st: 'Un cilindro macizo rueda sin resbalar y el módulo de la velocidad de su centro de masa es v. Su energía cinética total vale…',
   opts: ['¾·m·v²', '½·m·v²', '7/10·m·v²', 'm·v²'],
   c: 0,
   ex: 'E<sub>c</sub> = ½·m·v² + ½·I<sub>CM</sub>·Ω² con I<sub>CM</sub> = ½mR² y Ω = v/R: el radio se cancela y queda ½mv² + ¼mv² = <b>¾·m·v²</b>. ▸ Por qué las otras: <b>½mv²</b> es olvidarse la rotación, y es el error que más se repite en los ejercicios de 2do parcial (en el B2 de 2015 te daría 1,0 m/s en vez de 0,816 m/s); <b>7/10·mv²</b> es el factor de la <b>esfera maciza</b> (I = 2/5 mr²), que también aparece pero en otros problemas; <b>m·v²</b> es el del <b>aro o cilindro hueco</b> (I = mR²), donde la rotación se lleva tanto como la traslación.'},

  {st: 'El resorte de un problema mide 60 cm en el instante inicial y su longitud natural es 50 cm; k = 100 N/m. La energía potencial elástica <b>inicial</b> vale…',
   opts: ['0 J, porque el problema recién arranca', '½·k·(0,60 m)² = 18 J', '½·k·(0,50 m)² = 12,5 J', '½·k·(0,10 m)² = 0,5 J'],
   c: 3,
   ex: 'La energía elástica se calcula con la <b>deformación</b>, o sea la diferencia entre la longitud actual y la natural: Δl = 0,60 − 0,50 = 0,10 m, y ½·100·0,01 = <b>0,5 J</b>. Es el arranque del problema 2 del 2do parcial 2009. ▸ Por qué las otras: <b>0 J</b> vale solo cuando el enunciado dice que el resorte parte <i>en su longitud natural</i> o <i>sin deformación</i> — acá te dijeron lo contrario, y olvidarte esos 0,5 J te cambia la cuadrática final; <b>18 J</b> usa la longitud <i>total</i> del resorte como si fuera deformación; <b>12,5 J</b> usa la longitud natural, que por definición no guarda energía.'},

  {st: 'Un cuerpo sube una altura h sobre un plano rugoso de 37°. El trabajo del rozamiento vale…',
   opts: ['−μ<sub>d</sub>·m·g·cos37°·h', '−μ<sub>d</sub>·m·g·cos37°·(h/sen37°)', '−μ<sub>d</sub>·m·g·h', '−μ<sub>d</sub>·m·g·sen37°·(h/cos37°)'],
   c: 1,
   ex: 'El rozamiento actúa a lo largo de <b>lo que recorre sobre el plano</b>, que es D = h/sen37°, y con la normal del plano N = m·g·cos37°. En el B2 de 2011 la altura da 8,93 m pero la distancia recorrida es 14,9 m. ▸ Por qué las otras: usar h como distancia recorrida te deja el término chico por un factor 1/sen37° = 1,67; usar N = m·g olvida que sobre un plano inclinado la normal es la <b>componente perpendicular</b> del peso; y la última intercambia seno con coseno en los dos lugares, que es la forma más rápida de romper el ejercicio (acordate: <b>sen37° = 0,6</b>, <b>cos37° = 0,8</b>).'},

  {st: 'En el B2 del 2do parcial 2010 el enunciado te da μ<sub>D</sub> = 0,6 y aclara que el cilindro <b>rueda sin resbalar</b>. ¿Qué hacés con ese coeficiente?',
   opts: ['No interviene: el rozamiento es estático, se aplica en un punto de velocidad nula y no realiza trabajo',
          'Lo metés en el balance como −μ<sub>D</sub>·N·d',
          'Lo usás para calcular la normal sobre el plano',
          'Te avisa que la energía mecánica no se conserva'],
   c: 0,
   ex: 'Si rueda sin resbalar, el punto de contacto está <b>instantáneamente quieto</b>: dl = 0 y por lo tanto W<sub>roz</sub> = 0 aunque haya rozamiento. La energía se conserva y μ<sub>D</sub> es uno de esos "datos que no interesan" que la cátedra avisa en el encabezado. Escribilo en la hoja: sumás puntos por decirlo. ▸ Por qué las otras: meterlo como −μ<sub>D</sub>·N·d te hace perder energía que en realidad nunca se disipó; el coeficiente no interviene en el cálculo de la normal (la normal sale de Newton perpendicular al plano); y decir que la energía no se conserva es exactamente la conclusión opuesta a la que pide el ejercicio, que además pedía resolver "aplicando sólo conceptos de energía".'},

  {st: 'Un cuerpo de 2 kg cae 2 m tirando de una cuerda que pasa por una polea de 0,5 kg (I = ½m<sub>p</sub>R²) y estira un resorte de k = 10 N/m desde su longitud natural. ¿Con qué velocidad llega al piso?',
   opts: ['6,32 m/s', '4,47 m/s', '4,22 m/s', '5,96 m/s'],
   c: 2,
   ex: 'Balance completo: m·g·h = ½·m·v² + ¼·m<sub>p</sub>·v² + ½·k·x², con x = h = 2 m por la cuerda inextensible. 40 = (1 + 0,125)·v² + 20 ⟹ v² = 17,78 ⟹ <b>v = 4,22 m/s</b> (final UTN.BA 21/2/2024, problema 4). ▸ Por qué las otras: <b>6,32 m/s</b> es √(2gh), o sea caída libre: te olvidaste del resorte <i>y</i> de la polea; <b>4,47 m/s</b> descuenta el resorte pero ignora que la polea con masa se lleva ¼·m<sub>p</sub>·v²; <b>5,96 m/s</b> hace lo inverso, cuenta la polea y se olvida los 20 J que se guardó el resorte.'},
]);

registerReveals('fisica1-utn-energia', '2', [

  {st: '<span class="muted">1er parcial 2009, cátedra Martinelli · TEMA 1 · 22/10/09 · UTN FRBA</span><br><b>4)</b> Se empuja un cuerpo partiendo del reposo con una fuerza constante F como indica la figura. En el plano inclinado hay rozamiento mientras que en el horizontal el rozamiento es despreciable.<br>a) Calcular la velocidad del cuerpo en el punto B.<br>b) Si a partir del punto B la fuerza F se anula, calcule la compresión máxima del resorte.<br><b>Datos:</b> m = 10 kg &nbsp; k = 10000 N/m &nbsp; μ<sub>D</sub> = 0,1 &nbsp; F = 100 N &nbsp; AB = 5 m &nbsp; α = 37º',
   ans: 'a) v<sub>B</sub> = 5,66 m/s · b) Δl = 17,9 cm <span class="muted">(la clave oficial, que usa sen37° = 0,6018 y cos37° = 0,7986 en vez de los valores redondos de la cátedra, da 5,642 m/s y 17,84 cm)</span>',
   sol: '<b>Paso 0. Referencias.</b> Cero de V<sub>g</sub> en A. Parte del reposo: v<sub>A</sub> = 0. g = 10 m/s², sen37° = 0,6, cos37° = 0,8.<br><b>Paso 1. a) Las no conservativas del tramo AB son dos: F y el rozamiento.</b> Como F es <b>paralela al plano</b> (así viene en la figura), no modifica la normal:<br>N = m·g·cos37° = 10·10·0,8 = <b>80 N</b><br>W<sub>F</sub> = +F·AB = 100·5 = 500 J &nbsp;(a favor del movimiento)<br>W<sub>roz</sub> = −μ<sub>D</sub>·N·AB = −0,1·80·5 = −40 J<br>W<sub>NC</sub> = 500 − 40 = <b>460 J</b><br><b>Paso 2. La energía en B.</b> El cuerpo subió h = AB·sen37° = 5·0,6 = 3 m:<br>E<sub>B</sub> = ½·m·v<sub>B</sub>² + m·g·h = 5·v<sub>B</sub>² + 10·10·3 = 5·v<sub>B</sub>² + 300 J<br><b>Paso 3. Igualás.</b> E<sub>B</sub> − E<sub>A</sub> = W<sub>NC</sub>:<br>5·v<sub>B</sub>² + 300 = 460 &nbsp;⟹&nbsp; v<sub>B</sub>² = 32 m²/s² &nbsp;⟹&nbsp; <b>v<sub>B</sub> = 5,66 m/s</b>.<br><b>Paso 4. b) Del punto B al resorte.</b> A partir de B se anula F y el tramo horizontal es liso: <b>no hay ninguna fuerza no conservativa</b>, la energía se conserva. Además el resorte está a la <b>misma altura</b> que B, así que el término m·g·h aparece a los dos lados y se cancela solo:<br>½·k·Δl² = ½·m·v<sub>B</sub>² = ½·10·32 = <b>160 J</b><br>½·10000·Δl² = 160 &nbsp;⟹&nbsp; Δl² = 0,032 m² &nbsp;⟹&nbsp; <b>Δl = 0,179 m = 17,9 cm</b>.<br><b>Paso 5. Las trampas.</b> No le sumes ni le restes una componente de F a la normal (es paralela al plano); no arrastres F después de B (el enunciado la anula); no metas rozamiento en el tramo horizontal (es despreciable); y pasá el resultado a cm, que es como lo escribe la clave.'},

  {st: '<span class="muted">1er parcial 2011, cátedra Martinelli · 20/10/11 · Prof. H. Patricia Martinelli · UTN FRBA</span><br><b>B2:</b> Un cuerpo puntual, de masa 1 kg, es lanzado por la pista de la figura mediante un resorte ideal, de constante elástica K = 1000 N/m, que inicialmente se encuentra comprimido 50 cm. El plano inclinado forma un ángulo de 37° con la horizontal y presenta rozamiento, siendo sus coeficientes de rozamiento estático y dinámico 0.4 y 0.3, respectivamente. El tramo horizontal carece de rozamiento.<br>a) Determine con qué velocidad llega el bloque a la base del plano inclinado<br>b) Calcule hasta que altura h asciende sobre el plano inclinado.',
   ans: 'a) v<sub>B</sub> = 15,81 m/s · b) h = 8,93 m (recorriendo 14,9 m sobre el plano)',
   sol: '<b>Paso 0. Puntos e hipótesis.</b> A = partida con el resorte comprimido 0,5 m y v<sub>A</sub> = 0; B = pie del plano; C = altura máxima, con v<sub>C</sub> = 0. Cero de V<sub>g</sub> en el tramo horizontal. Resorte ideal.<br><b>Paso 1. a) Tramo AB: liso ⟹ la energía se conserva.</b> Toda la elástica se hace cinética, y la altura no cambia:<br>½·K·Δl² = ½·m·v<sub>B</sub>²<br>½·1000·(0,5)² = <b>125 J</b> = ½·1·v<sub>B</sub>²<br>v<sub>B</sub>² = 250 m²/s² &nbsp;⟹&nbsp; <b>v<sub>B</sub> = 15,81 m/s</b>.<br><b>Paso 2. b) Tramo BC: rugoso ⟹ ΔE = W<sub>roz</sub>.</b><br>m·g·h − ½·m·v<sub>B</sub>² = −μ<sub>d</sub>·N·D<sub>BC</sub><br><b>Paso 3. Los tres reemplazos que hay que escribir.</b><br>½·m·v<sub>B</sub>² = 125 J &nbsp;·&nbsp; N = m·g·cos37° = 1·10·0,8 = <b>8 N</b> &nbsp;·&nbsp; D<sub>BC</sub> = h/sen37° = h/0,6<br><b>Paso 4. Reemplazás y despejás.</b><br>10·h − 125 = −0,3·8·(h/0,6) = −4·h<br>14·h = 125 &nbsp;⟹&nbsp; <b>h = 8,93 m</b> &nbsp;(y D<sub>BC</sub> = 8,93/0,6 = 14,9 m sobre el plano).<br><b>Paso 5. El dato que no interesa.</b> μ<sub>e</sub> = 0,4 <b>no se usa</b>: el cuerpo está deslizando todo el tiempo. Solo serviría para decidir si queda frenado en C, y como tg37° = 0,75 > 0,4, en realidad vuelve a bajar. Escribilo en la hoja.<br><b>Paso 6. Chequeo por Newton.</b> a = −g·(sen37° + μ<sub>d</sub>·cos37°) = −10·(0,6 + 0,24) = −8,4 m/s²; D = v<sub>B</sub>²/(2·8,4) = 14,88 m; h = 14,88·0,6 = 8,93 m. Da lo mismo, pero por energía son tres renglones.'},

  {st: '<span class="muted">1er parcial 2014, cátedra Martinelli · 21/8/2014 · curso I1021 · UTN.BA</span><br><b>B2:</b> Se tiene el sistema mostrado en la figura, donde el resorte, las cuerdas y la polea son ideales, y la superficie horizontal carece de rozamiento. Las masas de los bloques son M<sub>1</sub> = M<sub>2</sub> = 2 kg. Inicialmente, el resorte de constante elástica K = 100 N/m, se encuentra trabado en su longitud natural, l<sub>o</sub>, y en determinado momento se lo destraba. Determine cuánto descenderá el cuerpo 2 hasta detenerse, a partir de su posición inicial.',
   ans: 'Δh = 0,4 m = 40 cm',
   sol: '<b>Paso 0. Hipótesis explícitas.</b> Superficie sin rozamiento, resorte y polea ideales ⟹ <b>la energía mecánica se conserva</b>: ΔE = 0.<br><b>Paso 1. Los dos estados.</b><br>Inicial: reposo (sin cinética) y resorte en su longitud natural (sin elástica).<br>Final: <b>máximo estiramiento</b>, que es donde el cuerpo 2 <i>se detiene</i>: v = 0 otra vez, pero ahora sí hay elástica.<br><b>Paso 2. El vínculo, que es el paso que hace cerrar el problema.</b> La cuerda es inextensible y pasa por una polea ideal, así que lo que <b>baja</b> M<sub>2</sub> es exactamente lo que se <b>estira</b> el resorte:<br><b>Δl = Δh</b><br><b>Paso 3. El balance.</b> M<sub>1</sub> se mueve horizontal, su energía potencial no cambia; solo baja M<sub>2</sub>:<br>ΔE = ½·K·Δh² − M<sub>2</sub>·g·Δh = 0<br>Dividís por Δh (descartando la solución trivial Δh = 0, que es el estado inicial):<br>Δh = <b>2</b>·M<sub>2</sub>·g/K = 2·2·10/100 = <b>0,4 m = 40 cm</b>.<br><b>Paso 4. LA trampa.</b> Si planteás <b>equilibrio</b> (K·x = M<sub>2</sub>·g) te da 20 cm, exactamente la mitad, y es el error más frecuente del ejercicio. El punto donde el cuerpo <b>se detiene</b> no es el de fuerza neta cero: es el de máximo estiramiento, donde el resorte tira más fuerte que el peso y lo va a hacer rebotar. El equilibrio es el punto <i>medio</i>, el que atraviesa a máxima velocidad.<br><b>Paso 5. El dato que no interesa.</b> M<sub>1</sub> = 2 kg <b>no aparece en la respuesta</b>: interviene en la cinética intermedia, pero en el estado final v = 0 para los dos cuerpos y se cancela. Decilo por escrito.'},

  {st: '<span class="muted">2do parcial 2009, cátedra Martinelli · TEMA 1 · 07/12/2009 · UTN FRBA</span><br><b>Problema 2:</b> Un disco de radio R = 10 cm y masa M = 2 kg (I<sub>CM</sub> = MR²/2), rueda sin resbalar sobre la superficie de un plano inclinado de ángulo α = 30°. El centro del disco está unido por una cuerda a un resorte de longitud natural l<sub>0</sub> = 50 cm y constante elástica k = 100 N/m, cuyo otro extremo está unido a una pared, como se muestra en la figura. Considere que la polea, la cuerda y el resorte son ideales. En determinado momento, la longitud del resorte es 60 cm y el centro de masa del disco se mueve con una velocidad v de módulo 0.8 m/s, en la dirección indicada. Determine la elongación máxima del resorte.',
   ans: 'Δl<sub>máx</sub> = 23,86 cm (longitud máxima del resorte ≈ 73,9 cm)',
   sol: '<b>Paso 0. Hipótesis.</b> Rueda sin resbalar ⟹ el rozamiento es estático, se aplica en un punto de velocidad nula y <b>no disipa</b>: la energía se conserva. Polea, cuerda y resorte ideales. Cero de V<sub>g</sub> en la posición inicial A del centro de masa. El disco <b>baja</b> por el plano (así apunta v en la figura).<br><b>Paso 1. Estado A.</b> Δl<sub>A</sub> = 0,60 − 0,50 = <b>0,1 m</b> (el resorte YA venía estirado):<br>½·M·v² = ½·2·0,64 = 0,64 J<br>½·I<sub>CM</sub>·Ω² = ½·(½·2·0,1²)·(0,8/0,1)² = 0,32 J &nbsp;<span class="muted">(juntos: ¾·M·v², el radio se cancela)</span><br>½·k·Δl<sub>A</sub>² = ½·100·0,01 = 0,50 J<br><b>E<sub>A</sub> = 1,46 J</b><br><b>Paso 2. Estado B: elongación máxima, v = 0.</b> El vínculo dice que el centro del disco se desplaza por el plano lo mismo que <b>aumenta</b> la elongación, o sea (Δl<sub>máx</sub> − Δl<sub>A</sub>), y como baja, la altura desciende ese desplazamiento por sen30°:<br>E<sub>B</sub> = −M·g·(Δl<sub>máx</sub> − Δl<sub>A</sub>)·sen30° + ½·k·Δl<sub>máx</sub>²<br>−2·10·0,5·(Δl<sub>máx</sub> − 0,1) + 50·Δl<sub>máx</sub>² = 1,46<br><b>Paso 3. Cuadrática.</b><br>50·Δl<sub>máx</sub>² − 10·Δl<sub>máx</sub> − 0,46 = 0<br>Δl<sub>máx</sub> = [10 ± √(100 + 92)]/100 = (10 ± 13,856)/100<br>Se descarta la raíz negativa (−3,86 cm no tiene sentido físico: con una cuerda de por medio el resorte no se comprime).<br><b>Δl<sub>máx</sub> = 0,2386 m = 23,86 cm</b>.<br><b>Paso 4. Los cuatro lugares donde se pierde este ejercicio.</b> (1) Olvidar la energía cinética de rotación: E<sub>A</sub> te daría 1,14 J; (2) poner cero la elástica inicial, cuando el resorte ya venía estirado 10 cm; (3) usar el <i>aumento</i> de elongación en vez de la elongación <b>total</b> Δl<sub>máx</sub> dentro de ½kΔl²; (4) equivocar el signo del término gravitatorio (el disco baja, la potencial disminuye).'},

  {st: '<span class="muted">2do parcial 2015, cátedra Martinelli · 25/11/2015 · curso Z1102 · UTN FRBA</span><br><b>B2:</b> El cilindro C, de masa m<sub>c</sub> = 5 kg y radio R<sub>c</sub> = 20 cm, está vinculado a un resorte de constante elástica k = 100 N/m mediante una cuerda que pasa por la polea P. El cilindro está apoyado sobre un plano inclinado con rozamiento, de ángulo α = 37º. La soga, el resorte y la polea P, son ideales. El momento de inercia del cilindro respecto de su centro de masa es I<sub>CM</sub> = m<sub>c</sub>·R<sub>c</sub>²/2. Suponiendo que el mismo parte del reposo cuando el resorte tiene su longitud natural y que rueda sin deslizar, calcule la velocidad de su centro de masa cuando el resorte se estiró 10 cm.',
   ans: 'v<sub>CM</sub> = 0,816 m/s',
   sol: '<b>Paso 0. La justificación que vale medio ejercicio.</b> Aunque el plano "tiene rozamiento", <b>no disipa</b>: el cilindro rueda sin deslizar, el punto de contacto está instantáneamente en reposo (dl = 0) y W<sub>roz</sub> = 0. La normal tampoco trabaja. La tensión no es conservativa, pero lo que le saca al cilindro se lo da al resorte y la suma es cero (cuerda y polea ideales). <b>Conclusión: la energía mecánica del sistema cilindro + resorte se conserva.</b><br><b>Paso 1. Los vínculos.</b><br>El centro de masa recorre sobre el plano lo mismo que se estira el resorte: d = Δl = <b>0,1 m</b><br>La altura que <b>baja</b> es h = Δl·sen37° = 0,1·0,6 = <b>0,06 m</b> &nbsp;<span class="muted">(no 0,1 m: hay que proyectar)</span><br>Rodadura: Ω = v<sub>CM</sub>/R<sub>c</sub><br><b>Paso 2. El balance.</b><br>m<sub>c</sub>·g·Δl·sen37° = ½·m<sub>c</sub>·v<sub>CM</sub>² + ½·(½m<sub>c</sub>R<sub>c</sub>²)·(v<sub>CM</sub>/R<sub>c</sub>)² + ½·k·Δl²<br>Los dos términos cinéticos se juntan en <b>¾·m<sub>c</sub>·v<sub>CM</sub>²</b> y el radio se cancela:<br>50 N·0,06 m = ¾·5·v<sub>CM</sub>² + ½·100·(0,1)²<br><b>3 J = 3,75·v<sub>CM</sub>² + 0,5 J</b><br><b>Paso 3. Despejás.</b><br>v<sub>CM</sub>² = 2,5/3,75 = 0,667 m²/s² &nbsp;⟹&nbsp; <b>v<sub>CM</sub> = 0,816 m/s</b>.<br><b>Paso 4. El error caro.</b> Si te olvidás la rotación te queda 2,5·v² = 2,5 y v = 1,0 m/s. Ese 1,0 tan redondo es tentador y está mal: la rotación se lleva un tercio de la cinética.'},

  {st: '<span class="muted">Final UTN.BA · hoja sin fecha visible (la del prisma de caras paralelas y el péndulo balístico) · problema 6</span><br><b>6-</b> El sistema de la figura parte del reposo, el resorte ideal (k = 250 N/m), no presenta deformación inicial. Luego el cilindro macizo y homogéneo (I<sub>CM</sub> = 1/2 mr²) de masa 10 Kg, comienza a descender rodando sin resbalar por el plano (α = 30º). Determine la velocidad del centro de masa del mismo, cuando su centro se desplazó una distancia d = 20 cm, a lo largo del plano.',
   ans: 'v<sub>CM</sub> = 0,816 m/s',
   sol: '<b>Paso 0. Es el mismo problema del 2do parcial 2015 con otros números.</b> Mismo esquema, misma justificación: rueda sin resbalar ⟹ el rozamiento estático no trabaja; resorte ideal ⟹ la energía se conserva. Vínculo: el desplazamiento del centro a lo largo del plano es igual al estiramiento del resorte, d = Δl = 0,2 m.<br><b>Paso 1. Lo que entrega la gravedad.</b> La altura que baja es d·sen30° = 0,2·0,5 = 0,1 m:<br>m·g·d·sen30° = 10·10·0,1 = <b>10 J</b><br><b>Paso 2. Lo que se guarda el resorte.</b><br>½·k·Δl² = ½·250·(0,2)² = ½·250·0,04 = <b>5 J</b><br><b>Paso 3. Lo que queda como cinética de rototraslación.</b><br>½·m·v² + ½·(½mr²)·(v/r)² = ¾·m·v² = ¾·10·v² = <b>7,5·v²</b><br><b>Paso 4. Igualás.</b><br>10 J = 7,5·v² + 5 J &nbsp;⟹&nbsp; v² = 5/7,5 = 0,667 m²/s² &nbsp;⟹&nbsp; <b>v<sub>CM</sub> = 0,816 m/s</b>.<br><b>Paso 5. Guiño.</b> Da <i>exactamente</i> el mismo número que el B2 del 2do parcial 2015. No es magia: en los dos casos la mitad de la energía que entrega la gravedad se la queda el resorte. Si en el final te sale 0,816 m/s, es buena señal.'},

  {st: '<span class="muted">Final UTN.BA · hoja sin fecha visible (la que abre con el radio de curvatura a 53°) · problema 4</span><br><b>4)</b> El sistema representado en la figura parte del reposo, y el resorte (de constante K = 100 N/m) se encuentra inicialmente sin deformación. Un cilindro macizo de masa 10 kg, cuyo momento de inercia respecto a su eje es I = mR²/2, comienza a descender sin deslizar por el plano inclinado de 30°. Determinar la velocidad del centro de masa del cilindro luego de haber descendido 50 cm a lo largo del plano.',
   ans: 'v<sub>CM</sub> = 1,29 m/s',
   sol: '<b>Paso 0. Tercera vez el mismo arquetipo.</b> Cambian k (100 N/m) y d (0,5 m); el planteo es idéntico. Cero de V<sub>g</sub> en la posición final del centro de masa, vínculo d = Δl = 0,5 m.<br><b>Paso 1. Energía que entrega la gravedad.</b><br>m·g·d·sen30° = 10·10·0,5·0,5 = <b>25 J</b><br><b>Paso 2. Energía que absorbe el resorte.</b><br>½·K·Δl² = ½·100·(0,5)² = ½·100·0,25 = <b>12,5 J</b><br><b>Paso 3. Cinética de rototraslación.</b><br>¾·m·v² = ¾·10·v² = <b>7,5·v²</b><br><b>Paso 4. Balance y despeje.</b><br>25 = 7,5·v² + 12,5 &nbsp;⟹&nbsp; v² = 12,5/7,5 = 1,667 m²/s² &nbsp;⟹&nbsp; <b>v<sub>CM</sub> = 1,29 m/s</b>.<br><b>Paso 5. Chequeo rápido de que no te pasaste.</b> El resorte se quedó con la mitad exacta de los 25 J. Como acá d es más grande, el resorte llegó a estirarse 50 cm y la energía elástica crece con el <b>cuadrado</b>: si hubieras usado ½·K·d en vez de ½·K·d², te daría cualquier cosa. Y si te olvidás la rotación: 25 = 5·v² + 12,5 ⟹ v = 1,58 m/s, mal.'},

  {st: '<span class="muted">Final UTN.BA · EXAMEN FINAL 2/3/2023 · problema 4</span><br><b>4.</b> Un cuerpo de masa m₁ = 3 kg se encuentra, en el instante inicial, descendiendo a una velocidad de v<sub>i</sub> = 5 m/s. El disco de la polea, que es homogéneo y de masa m₂ = 2 kg, gira sin rozamiento y esta ligado a través de una cuerda ideal a un tercer cuerpo de masa m₃ = 2 kg apoyado sobre un plano horizontal con rozamiento μ<sub>c</sub> = 0,35. Este cuerpo está vinculado a un resorte de constante elástica k = 50 N/m que en ese instante se encuentra elongado Δx<sub>i</sub> = 0,5 m. Halle la velocidad del cuerpo 1 después de que éste desciende una distancia de 1 m.',
   ans: 'v = 4 m/s',
   sol: '<b>Paso 0. Este es el arquetipo completo: resorte + rozamiento + polea con masa, todo junto.</b> Cuerda inextensible ⟹ los dos cuerpos y el borde de la polea van con el mismo módulo de velocidad v, y Ω = v/R. La polea es un disco: I = ½m₂R², así que aporta ½·I·Ω² = <b>¼·m₂·v²</b>.<br><b>Paso 1. Vínculos y estados.</b> Cuando el cuerpo 1 baja d = 1 m, el cuerpo 3 avanza 1 m y el resorte pasa de Δx<sub>i</sub> = 0,5 m a Δx<sub>f</sub> = <b>1,5 m</b>.<br><b>Paso 2. Energía inicial.</b><br>Cinética: ½·(m₁+m₃)·v<sub>i</sub>² + ¼·m₂·v<sub>i</sub>² = ½·5·25 + ¼·2·25 = 62,5 + 12,5 = 75 J<br>Elástica: ½·50·(0,5)² = 6,25 J<br><b>E<sub>i</sub> = 81,25 J</b> (con V<sub>g</sub> = 0 en la posición inicial del cuerpo 1)<br><b>Paso 3. Energía final.</b><br>Cinética: (2,5 + 0,5)·v² = 3·v²<br>Elástica: ½·50·(1,5)² = 56,25 J<br>Gravitatoria: −m₁·g·d = −3·10·1 = −30 J<br><b>E<sub>f</sub> = 3·v² + 26,25 J</b><br><b>Paso 4. El trabajo no conservativo.</b> Solo el rozamiento del cuerpo 3 sobre el plano horizontal (N = m₃·g = 20 N):<br>W<sub>roz</sub> = −μ<sub>c</sub>·m₃·g·d = −0,35·20·1 = <b>−7 J</b><br><b>Paso 5. Balance.</b><br>3·v² + 26,25 − 81,25 = −7 &nbsp;⟹&nbsp; 3·v² = 48 &nbsp;⟹&nbsp; v² = 16 &nbsp;⟹&nbsp; <b>v = 4 m/s</b>.<br><b>Paso 6. Lo que hay que no perder de vista.</b> (1) El sistema <b>arranca en movimiento</b>: la cinética inicial de 75 J no es cero; (2) el resorte ya venía estirado, así que se resta ½k(0,5)² y no cero; (3) el resorte se lleva 50 J netos, más de lo que aporta el peso — por eso el cuerpo termina más <i>lento</i> (4 m/s) de lo que arrancó (5 m/s), y eso está bien.'},

  {st: '<span class="muted">Final UTN.BA · hoja sin fecha visible (la del rizo circular y la cañería) · problema 2</span><br><b>2-</b> En el sistema de la figura el resorte ideal (k = 20 N/m), se halla en un extremo, fijo al piso y en el otro a una partícula de masa m1 = 8 kg. La polea de geometría cilíndrica (I<sub>CM</sub> = 1/2Mr²), no tiene rozamiento en su eje, y tiene una masa M = 2 kg. La otra partícula, de masa m2 = 15 kg, se encuentra posicionada a la misma altura h = 4 m, con respecto al piso que la otra. Cuando el sistema se deja en libertad, desde el reposo, el resorte está estirado 1 m. La cuerda es inextensible y de masa despreciable. Determine el módulo de la velocidad de la partícula m2 cuando llegue al piso.',
   ans: 'v = √(10/3) = 1,83 m/s',
   sol: '<b>Paso 0. Qué se mueve y hacia dónde.</b> m2 = 15 kg pesa más que m1 = 8 kg, así que <b>m2 baja 4 m y m1 sube 4 m</b>, estirando el resorte todavía más. La cuerda es inextensible: los dos van con el mismo módulo v, y la polea gira con Ω = v/r.<br><b>Paso 1. El resorte va de 1 m a 5 m de estiramiento.</b> Ese es el paso que decide el problema: no se estira 4 m, <b>pasa</b> de 1 m a 5 m.<br>ΔE<sub>elástica</sub> = ½·k·(5² − 1²) = ½·20·24 = <b>+240 J</b><br><b>Paso 2. Los términos gravitatorios.</b><br>m2 baja 4 m: −15·10·4 = <b>−600 J</b><br>m1 sube 4 m: +8·10·4 = <b>+320 J</b><br><b>Paso 3. La cinética final.</b> Los dos cuerpos más la polea:<br>½·(m1+m2)·v² + ¼·M·v² = ½·23·v² + ¼·2·v² = 11,5·v² + 0,5·v² = <b>12·v²</b><br><b>Paso 4. Balance (todo ideal ⟹ ΔE = 0).</b><br>12·v² − 600 + 320 + 240 = 0 &nbsp;⟹&nbsp; 12·v² = 40<br>v² = 3,33 m²/s² &nbsp;⟹&nbsp; <b>v = 1,83 m/s</b>.<br><b>Paso 5. Por qué da tan poco.</b> Los 600 J que suelta m2 se los comen casi enteros el ascenso de m1 (320 J) y el resorte (240 J): quedan 40 J para repartir entre 25 kg de materia. Si te da 6 o 7 m/s, seguro te olvidaste el estiramiento previo del resorte o el ascenso de m1.'},
]);

/* ==================== UNIDAD 3 · Movimiento circular ==================== */

registerExercises('fisica1-utn-energia', '3', [
  {st: 'Un cuerpo puntual recorre por adentro un loop de R = 1 m. ¿Cuál es la velocidad mínima que necesita en el punto más alto para no desprenderse? (g = 10 m/s²)',
   opts: ['0 m/s', '3,16 m/s', '4,47 m/s', '10 m/s'],
   c: 1,
   ex: 'La condición límite es <b>N = 0</b>: el peso solo alcanza justo para dar toda la fuerza centrípeta. m·g = m·v²/R ⟹ v<sub>mín</sub> = √(g·R) = √10 = <b>3,16 m/s</b>. ▸ Por qué las otras: <b>0 m/s</b> sería quedarse quieto en el techo del loop, que es literalmente caerse; <b>4,47 m/s</b> es √(2gR), que es la velocidad de caída libre desde una altura R, un número que no tiene nada que ver con la condición de no desprendimiento; <b>10 m/s</b> es √(2g·h) con h = 5 m, otro número que aparece en problemas vecinos pero no acá.'},

  {st: 'Una partícula da vueltas en un plano vertical atada a una cuerda de longitud L. La diferencia de altura entre el punto más alto y el más bajo vale…',
   opts: ['L/2', 'L', '2L', '2πL'],
   c: 2,
   ex: 'Es el <b>diámetro</b> de la circunferencia: <b>2L</b>. Con eso, en el B2 de 2017, L = (v<sub>B</sub>² − v<sub>A</sub>²)/(4g) = (64 − 16)/40 = 1,2 m. ▸ Por qué las otras: <b>L</b> es el radio, y usarlo te da L = 2,4 m, el doble, y arrastra el error a las dos tensiones del inciso b); <b>L/2</b> no corresponde a ninguna distancia del dibujo; <b>2πL</b> es la longitud de la circunferencia, o sea lo que <i>recorre</i> dando una vuelta, no la altura que sube.'},

  {st: 'En el punto más alto de una trayectoria circular vertical con cuerda, ¿cómo queda la ecuación de Newton en dirección radial?',
   opts: ['T = m·v²/L − m·g', 'T = m·v²/L + m·g', 'T = m·g − m·v²/L', 'T = m·v²/L'],
   c: 0,
   ex: 'Arriba el centro está <b>abajo</b>, así que la tensión y el peso apuntan los dos hacia el centro y se suman: T + m·g = m·v²/L ⟹ <b>T = m·v²/L − m·g</b>. En el B2 de 2017 da 6,67 N. ▸ Por qué las otras: <b>T = mv²/L + mg</b> es la ecuación del punto más <b>bajo</b> (allá la tensión apunta hacia arriba y el peso en contra), y da 126,67 N — no te asustes de que sea 19 veces más grande, está bien; <b>T = mg − mv²/L</b> tiene el signo dado vuelta y te daría tensión negativa; <b>T = mv²/L</b> confunde la resultante centrípeta con la tensión sola, olvidando el peso.'},

  {st: 'En el B1 del 1er parcial 2010 la zona rugosa está <b>después</b> del loop, entre el loop y la rampa. Para calcular la velocidad en el punto más alto del loop…',
   opts: ['hay que descontar −μ<sub>d</sub>·m·g·d antes de llegar al loop',
          'hay que sumar el trabajo del rozamiento porque el cuerpo acelera',
          'hace falta conocer el ángulo de la rampa',
          'se usa conservación pura desde el resorte: E<sub>A</sub> = E<sub>B</sub>'],
   c: 3,
   ex: 'Seguí el recorrido con el dedo antes de plantear nada: entre el resorte y el loop la pista es <b>lisa</b>, así que E<sub>A</sub> = ½KΔl² = 20 J se conserva entera hasta B. El rozamiento recién entra después, para calcular la altura sobre la rampa. ▸ Por qué las otras: descontarlo antes te baja v<sub>B</sub> y te tira todo el ejercicio; el trabajo del rozamiento <b>nunca</b> es positivo, va siempre restando; y el ángulo de la rampa es otro dato que no hace falta, porque lo que te piden es la <b>altura</b> h, no la distancia recorrida sobre la rampa.'},

  {st: 'Una partícula gira en un plano horizontal atada a un resorte de longitud natural l<sub>0</sub> y constante k, describiendo un círculo de radio R. La ecuación correcta es…',
   opts: ['k·R = m·v²/R', 'k·(R − l<sub>0</sub>) = m·v²/R', 'k·(R − l<sub>0</sub>) = m·v²/(R − l<sub>0</sub>)', 'k·l<sub>0</sub> = m·v²/R'],
   c: 1,
   ex: 'Conviven dos longitudes distintas: la <b>deformación</b> (R − l<sub>0</sub>), que es la que va en la fuerza elástica, y el <b>radio</b> R, que es la longitud actual del resorte y va en la aceleración centrípeta v²/R. ▸ Por qué las otras: <b>k·R</b> usa la longitud actual como si fuera deformación, y un resorte en su longitud natural no hace fuerza; la tercera pone la deformación también en el denominador de la centrípeta, pero el radio del círculo que describe la partícula es R, no lo que se estiró el resorte; <b>k·l<sub>0</sub></b> es el error opuesto, usar la longitud natural como deformación.'},

  {st: 'Una partícula hace MCU en un plano horizontal atada a una soga que pasa por un agujero. Se tira de la soga hasta que el radio queda a la <b>mitad</b>. La fuerza centrípeta pasa a valer…',
   opts: ['el doble', 'cuatro veces mayor', 'ocho veces mayor', 'la misma'],
   c: 2,
   ex: 'La fuerza es radial, no hace momento respecto del centro, y <b>se conserva el momento angular</b>: L = m·v·r ⟹ al mitad de radio la velocidad se <b>duplica</b>. Entonces F = m·v²/r queda con v² cuatro veces mayor sobre un r a la mitad: <b>8 veces</b> (F ∝ 1/r³). En el final de la hoja del cohete: de 1 N a 8 N. ▸ Por qué las otras: <b>el doble</b> es el error automático de escribir F = m·v²/(r/2) dejando v igual — pero al tirar hacia adentro hay desplazamiento radial, la fuerza <i>sí</i> hace trabajo y la partícula acelera; <b>cuatro veces</b> cuenta el aumento de v² pero se olvida de que el radio también cambió; <b>la misma</b> ignoraría las dos cosas.'},
]);

registerReveals('fisica1-utn-energia', '3', [

  {st: '<span class="muted">1er parcial 2010, cátedra Martinelli · 26/10/10 · UTN FRBA</span><br><b>B1:</b> Un cuerpo puntual es lanzado por la pista de la figura mediante un resorte que inicialmente se encuentra comprimido una distancia de 20 cm.<br>a) Calcular la velocidad en la parte superior del loop. Compárela con la velocidad mínima para que pase por la pista sin desprenderse.<br>b) Calcular la altura máxima que alcanza sobre la rampa inclinada.<br><b>Datos:</b> R = 1 m, K = 1000 N/m, d = 20 m, m = 100 gr, μ<sub>d</sub> = 0.5',
   ans: 'a) v<sub>B</sub> = 18,97 m/s frente a v<sub>mín</sub> = 3,16 m/s: no se desprende · b) h = 10 m',
   sol: '<b>Paso 0. Unidades y puntos.</b> m = 100 gr = <b>0,1 kg</b>, Δl = 20 cm = <b>0,2 m</b>. A = partida contra el resorte; B = punto más alto del loop; C y D = principio y fin de la zona rugosa; H = punto más alto sobre la rampa. Cero de V<sub>g</sub> en el piso. Los tramos A-C y D-H son <b>lisos</b>.<br><b>Paso 1. a) Conservación pura entre A y B.</b> La zona rugosa está <i>después</i> del loop, así que acá no se descuenta nada:<br>E<sub>A</sub> = ½·K·Δl² = ½·1000·(0,2)² = <b>20 J</b><br>E<sub>B</sub> = ½·m·v<sub>B</sub>² + m·g·<b>2R</b> = 0,05·v<sub>B</sub>² + 0,1·10·2 = 0,05·v<sub>B</sub>² + 2 J<br>20 = 0,05·v<sub>B</sub>² + 2 &nbsp;⟹&nbsp; v<sub>B</sub>² = 360 m²/s² &nbsp;⟹&nbsp; <b>v<sub>B</sub> = 18,97 m/s</b>.<br><b>Paso 2. La velocidad mínima: la condición es N = 0.</b><br>m·g = m·v<sub>mín</sub>²/R &nbsp;⟹&nbsp; v<sub>mín</sub> = √(g·R) = √10 = <b>3,16 m/s</b><br>Como 18,97 ≫ 3,16, <b>no se desprende</b>; y si pasa por B sin desprenderse, tampoco se desprende en ningún otro punto del loop, porque arriba es el punto más exigente.<br><b>Paso 3. b) De B a H, la única pérdida es el tramo CD.</b> Podés saltarte todos los puntos intermedios y aplicar el balance directo desde el resorte:<br>W<sub>roz</sub> = −μ<sub>d</sub>·m·g·d = −0,5·0,1·10·20 = <b>−10 J</b><br>E<sub>H</sub> = E<sub>A</sub> + W<sub>roz</sub> = 20 − 10 = <b>10 J</b><br><b>Paso 4. En H solo hay potencial (v<sub>H</sub> = 0).</b><br>E<sub>H</sub> = m·g·h &nbsp;⟹&nbsp; 10 J = (0,1·10)·h = 1 N·h &nbsp;⟹&nbsp; <b>h = 10 m</b>.<br><b>Paso 5. Los cuatro errores clásicos.</b> (1) Usar R en vez de <b>2R</b> para la altura de B; (2) descontar el rozamiento antes del loop; (3) restar el rozamiento dos veces (el cuerpo pasa <i>una sola</i> vez por CD antes de subir la rampa); (4) confundir h (altura vertical) con la distancia sobre la rampa — el ángulo de la rampa ni te lo dan, señal de que no hace falta.'},

  {st: '<span class="muted">1er parcial 2017, cátedra Martinelli · 26/6/2017 · curso R1022 · UTN FRBA</span><br><b>B2:</b> Una partícula de masa m = 2 kg realiza un movimiento circular en el plano vertical, unida a una cuerda inextensible de masa despreciable. La velocidad en el punto más alto de su trayectoria es 4 m/s, mientras que en el punto más bajo es 8 m/s.<br>a) Utilizando conceptos de trabajo y energía, calcule la longitud de la cuerda.<br>b) Determine la tensión de la cuerda en cada uno de esos dos puntos.',
   ans: 'a) L = 1,2 m · b) T<sub>arriba</sub> = 20/3 N = 6,67 N y T<sub>abajo</sub> = 380/3 N = 126,67 N',
   sol: '<b>Paso 0. La justificación que el inciso a) pide explícitamente.</b> La tensión <b>no es conservativa</b>, pero en todo momento es perpendicular al desplazamiento (que es tangente a la circunferencia): W<sub>T</sub> = 0. El peso es conservativo. Por lo tanto <b>la energía mecánica se conserva</b>. Escribí ese renglón: es la mitad del puntaje del inciso.<br><b>Paso 1. a) Balance entre A (arriba) y B (abajo).</b> Cero de V<sub>g</sub> en B; la altura de A sobre B es <b>2L</b>, el diámetro:<br>½·m·v<sub>A</sub>² + m·g·2L = ½·m·v<sub>B</sub>²<br>La masa se cancela:<br>L = (v<sub>B</sub>² − v<sub>A</sub>²)/(4·g) = (64 − 16)/40 = 48/40 = <b>1,2 m</b>.<br><b>Paso 2. b) Newton radial arriba.</b> El centro está abajo: T y P apuntan los dos hacia el centro.<br>T<sub>A</sub> + m·g = m·v<sub>A</sub>²/L<br>T<sub>A</sub> = 2·16/1,2 − 2·10 = 26,67 − 20 = <b>20/3 N = 6,67 N</b><br><b>Paso 3. Newton radial abajo.</b> El centro está arriba: T va hacia el centro y P en contra.<br>T<sub>B</sub> − m·g = m·v<sub>B</sub>²/L<br>T<sub>B</sub> = 2·64/1,2 + 2·10 = 106,67 + 20 = <b>380/3 N = 126,67 N</b><br><b>Paso 4. Chequeos.</b> (1) La diferencia de casi 19 veces entre las dos tensiones es <b>correcta</b> y suele hacer dudar: dejá los resultados como fracciones exactas 20/3 y 380/3. (2) Arriba se necesita v<sub>A</sub>² ≥ g·L = 12 m²/s² para que la cuerda no se afloje; acá v<sub>A</sub>² = 16 > 12, por eso T<sub>A</sub> sale positiva pero chica. (3) Si usás h = L en vez de 2L te da L = 2,4 m y los dos incisos quedan mal.<br><b>Paso 5. Ojo con esto.</b> No es un MCU: la velocidad varía entre 8 y 4 m/s, así que hay aceleración tangencial. Pero justo en el punto más alto y en el más bajo la aceleración tangencial es <b>perpendicular</b> a la dirección radial, así que no ensucia la ecuación radial que usaste.'},

  {st: '<span class="muted">Final UTN.BA · hoja sin fecha visible (la del prisma de caras paralelas) · problema 2</span><br><b>2-</b> Se dispone de un péndulo simple (masa puntual y cuerda ideal). La masa del mismo vale m = <b>1</b> kg <span class="muted">(dato reconstruido: en la foto el valor está tapado por un garabato en lapicera roja del corrector; los resultados escalan proporcionalmente con m)</span>, y la longitud de la cuerda es l = 1,5 m. En el instante inicial se lo libera desde el reposo con un ángulo α = 37º, medido desde la vertical. Cuando el péndulo pasa por la vertical (instante final), la velocidad de la masa es v<sub>f</sub> = 2,25 m/s. Determine:<br>a) El trabajo realizado por todas las fuerzas en juego, entre ambos instantes.<br>b) El trabajo de las fuerzas NO conservativas, entre ambos instantes.<br>c) La tensión que soporta la cuerda en el instante final.',
   ans: 'a) W<sub>total</sub> = 2,53 J · b) W<sub>NC</sub> = −0,47 J · c) T = 13,4 N &nbsp;<span class="muted">(por cada kg de masa)</span>',
   sol: '<b>Paso 0. La geometría del péndulo.</b> Al soltarlo a 37° de la vertical, la masa está más alta que en la posición de equilibrio en<br>h = l·(1 − cos37°) = 1,5·(1 − 0,8) = <b>0,3 m</b><br>Cero de V<sub>g</sub> en la posición más baja. Parte del reposo: v<sub>i</sub> = 0.<br><b>Paso 1. a) El trabajo de TODAS las fuerzas es la variación de energía cinética.</b> Ese es el teorema del trabajo y la energía, sin más:<br>W<sub>total</sub> = ΔE<sub>c</sub> = ½·m·v<sub>f</sub>² − 0 = ½·1·(2,25)² = <b>2,53 J</b><br><b>Paso 2. b) El trabajo de las NO conservativas es la variación de energía MECÁNICA.</b> Ojo con la diferencia: acá entra la potencial.<br>W<sub>NC</sub> = ΔE = (½·m·v<sub>f</sub>²) − (m·g·h) = 2,53 − 1·10·0,3 = 2,53 − 3 = <b>−0,47 J</b><br><b>Paso 3. Chequeo de que el signo tiene sentido.</b> Si no hubiera pérdidas, la velocidad en la vertical sería √(2·g·h) = √6 = 2,45 m/s. Te dicen que llega a 2,25 m/s, o sea <b>menos</b>: hubo rozamiento con el aire (o en el punto de sujeción), y por eso W<sub>NC</sub> da negativo. Si te diera positivo, revisá la cuenta.<br><b>Paso 4. c) La tensión sale de Newton, no de energía.</b> En el punto más bajo el centro está arriba: T hacia el centro, el peso en contra.<br>T − m·g = m·v<sub>f</sub>²/l<br>T = 1·10 + 1·(2,25)²/1,5 = 10 + 3,375 = <b>13,4 N</b><br><b>Paso 5. Por qué la tensión no trabaja pero igual existe.</b> W<sub>T</sub> = 0 porque es perpendicular al desplazamiento — eso es lo que usaste en b). Pero que no trabaje no significa que valga cero: es la que sostiene a la masa <i>y</i> le da la aceleración centrípeta. Son dos preguntas distintas y por eso hacen falta las dos herramientas.'},

  {st: '<span class="muted">Final UTN.BA · hoja sin fecha visible (la del rizo circular y la cañería) · problema 4</span><br><b>4-</b> Determine desde qué altura H, se debería dejar caer desde el reposo, una partícula de masa m, por una pista sin fricción como muestra el gráfico, para que, al llegar a la parte más elevada del rizo circular, la fuerza normal, tenga allí un valor igual al triple de su peso.',
   ans: 'H = 4·R',
   sol: '<b>Paso 0. Es un problema de dos ecuaciones y ningún número.</b> No te dan ni m ni R ni g: la respuesta tiene que salir en función de R. Eso ya te avisa que todo se va a cancelar.<br><b>Paso 1. Newton radial en el punto más alto del rizo.</b> Ahí el centro está abajo, y la normal (la pista empuja desde afuera hacia adentro) y el peso apuntan los dos hacia el centro:<br>N + m·g = m·v²/R<br>Con la condición del enunciado, N = <b>3·m·g</b>:<br>3·m·g + m·g = m·v²/R &nbsp;⟹&nbsp; 4·g·R = v² &nbsp;⟹&nbsp; <b>v² = 4·g·R</b><br><b>Paso 2. Energía entre la partida y el punto más alto.</b> La pista es <b>sin fricción</b>: la energía se conserva. Cero de V<sub>g</sub> en el piso; la altura del punto más alto del rizo es <b>2R</b>:<br>m·g·H = m·g·(2R) + ½·m·v²<br>La masa se cancela:<br>g·H = 2·g·R + ½·(4·g·R) = 2·g·R + 2·g·R = 4·g·R<br><b>Paso 3. Despejás.</b> También se cancela g:<br><b>H = 4·R</b><br><b>Paso 4. Chequeo con el caso límite.</b> Si en vez de N = 3P pidieran N = 0 (el mínimo para pasar), sería v² = g·R y H = 2R + R/2 = <b>2,5·R</b>. Como acá pedís que la pista apriete tres veces el peso, la altura tiene que ser <i>mayor</i> que 2,5R: 4R > 2,5R. ✓<br><b>Paso 5. La trampa.</b> Usar R en vez de 2R como altura del punto más alto te da H = 3R y perdés el ejercicio por un factor que no se ve en el resultado. Dibujá el rizo y marcá el diámetro.'},

  {st: '<span class="muted">Final UTN.BA · 26/05/22 · problema 5</span><br><b>5.</b> Una esfera sólida de masa m = 1 kg y de radio r = 0,1 m rueda sin deslizar a lo largo de la pista mostrada en la figura que posee un loop de R = 0,5 m. Si parte del reposo en la parte superior de la pista donde el centro de masa está a una altura h<sub>cm</sub> = 1,5 m. Hallar el valor de la fuerza normal actuante sobre la esfera en A (punto superior de la pista).',
   ans: 'v<sub>CM</sub>² = 8,57 m²/s² y N = 11,4 N (≈ 1,14 veces el peso)',
   sol: '<b>Paso 0. Por qué acá el radio de la esfera SÍ importa.</b> El enunciado te da r = 0,1 m y te habla del <b>centro de masa</b>: eso te está diciendo que la esfera no es puntual. Rodando por adentro del loop, su centro describe una circunferencia de radio <b>R − r = 0,4 m</b>, y en el punto más alto ese centro está a <b>2R − r = 0,9 m</b> del piso.<br><b>Paso 1. Energía entre la partida y A.</b> Rueda sin deslizar ⟹ el rozamiento es estático y no disipa: la energía se conserva. Esfera maciza: E<sub>c</sub> = ½mv² + ½·(2/5 mr²)·(v/r)² = <b>7/10·m·v²</b>.<br>m·g·(h<sub>cm</sub> − 0,9) = 7/10·m·v<sub>CM</sub>²<br>1·10·(1,5 − 0,9) = <b>6 J</b> = 0,7·v<sub>CM</sub>²<br>v<sub>CM</sub>² = 60/7 = <b>8,57 m²/s²</b> &nbsp;(v<sub>CM</sub> = 2,93 m/s)<br><b>Paso 2. Newton radial en A.</b> El radio de la trayectoria del centro es R − r = 0,4 m:<br>N + m·g = m·v<sub>CM</sub>²/(R − r)<br>N = 1·8,57/0,4 − 1·10 = 21,43 − 10 = <b>11,4 N</b><br><b>Paso 3. Chequeo.</b> N sale positiva, así que la esfera efectivamente <b>no se despega</b>. Si hubiera dado negativa, la esfera se habría desprendido antes de llegar arriba y el resultado no tendría sentido físico.<br><b>Paso 4. La versión "de apuro".</b> Si tratás la esfera como puntual (r despreciable, altura 2R = 1 m y radio R = 0,5 m) te da v² = 7,14 m²/s² y N = 4,3 N. Es un planteo defendible si lo aclarás, pero el enunciado te dio r y h<sub>cm</sub> justamente para que uses R − r y 2R − r.<br><b>Paso 5. El error que sí es error.</b> Olvidarte la rotación: con ½mv² en vez de 7/10·mv² te daría v² = 12 y N = 20 N, casi el doble.'},

  {st: '<span class="muted">Final UTN.BA · EXAMEN FINAL 2/3/2023 · problema 1</span><br><b>1.</b> Una masa puntual m₁ = 0,2 kg se halla sujeta a un extremo de una soga ideal girando sobre un plano horizontal sin rozamiento. Su velocidad en módulo es inicialmente v₁ⁱ = 2 m/s cuando el radio de giro es r₁ⁱ = 0,4 m. Para esto es necesario contar con una masa m₂ que cuelga desde el otro extremo de la cuerda. Si añadimos una masa extra de modo tal que la masa m₁ describe ahora una trayectoria circular de radio r₁ᶠ = 0,2 m. Calcule:<br>(i) El valor de la masa m₂ inicialmente.<br>(ii) La velocidad en modulo cuando se aumenta la masa que cuelga de la soga',
   ans: '(i) m₂ = 0,2 kg · (ii) v₁ᶠ = 4 m/s',
   sol: '<b>Paso 0. El montaje.</b> La soga pasa por un agujero en el centro de la mesa: arriba m₁ gira, abajo m₂ cuelga <b>quieta</b>. La tensión es la misma en los dos extremos.<br><b>Paso 1. (i) m₂ está en equilibrio, m₁ hace MCU.</b> Dos ecuaciones, una tensión.<br>Para m₂ (en reposo, ΣF = 0): &nbsp; T = m₂·g<br>Para m₁ (MCU, la tensión es toda la centrípeta): &nbsp; T = m₁·v₁ⁱ²/r₁ⁱ = 0,2·4/0,4 = <b>2 N</b><br>m₂ = T/g = 2/10 = <b>0,2 kg</b>.<br><b>Paso 2. (ii) Al tirar hacia adentro se conserva el momento angular.</b> La tensión es <b>radial</b>: su momento respecto del centro es cero, así que L = m₁·v·r se mantiene constante.<br>v₁ⁱ·r₁ⁱ = v₁ᶠ·r₁ᶠ<br>v₁ᶠ = 2·(0,4/0,2) = <b>4 m/s</b>.<br><b>Paso 3. Lo que NO se conserva.</b> La energía cinética pasa de ½·0,2·4 = 0,4 J a ½·0,2·16 = 1,6 J: se cuadruplicó. No hay contradicción — al tirar de la soga hacia adentro hay <b>desplazamiento radial</b>, y ahí la tensión <i>sí</i> hace trabajo positivo. Ese trabajo se lo pone la masa extra que agregaste.<br><b>Paso 4. La trampa.</b> Suponer que la velocidad "no tiene por qué cambiar" y calcular la nueva tensión con v = 2 m/s. Al mitad de radio la velocidad se <b>duplica</b>, y por eso la fuerza necesaria queda 2³ = <b>8 veces</b> mayor: 16 N en vez de 2 N.'},

  {st: '<span class="muted">Final UTN.BA · hoja sin fecha visible (la del tanque de gasolina y el cohete) · problema 5</span><br><b>5.</b> Una partícula de masa m = 0,1 kg realiza un movimiento circular uniforme en un plano horizontal con una velocidad v = 2 m/s bajo la acción de una fuerza centrípeta F = 1 N. Luego se incrementa la fuerza (siempre en dirección centrípeta) hasta un valor final tal que la partícula recorre una trayectoria circular cuyo radio es la mitad del inicial. Calcule el valor final de la fuerza centrípeta.',
   ans: 'F<sub>f</sub> = 8 N (ocho veces la inicial)',
   sol: '<b>Paso 0. Es el mismo problema del agujero, escrito al revés.</b> Acá te dan la fuerza y tenés que sacar el radio.<br><b>Paso 1. El radio inicial.</b><br>F<sub>i</sub> = m·v<sub>i</sub>²/r<sub>i</sub> &nbsp;⟹&nbsp; r<sub>i</sub> = m·v<sub>i</sub>²/F<sub>i</sub> = 0,1·4/1 = <b>0,4 m</b><br>Entonces r<sub>f</sub> = 0,2 m.<br><b>Paso 2. Momento angular constante.</b> La fuerza es siempre <b>centrípeta</b>, o sea radial: no hace momento respecto del centro.<br>m·v<sub>i</sub>·r<sub>i</sub> = m·v<sub>f</sub>·r<sub>f</sub> &nbsp;⟹&nbsp; v<sub>f</sub> = v<sub>i</sub>·(r<sub>i</sub>/r<sub>f</sub>) = 2·2 = <b>4 m/s</b><br><b>Paso 3. La fuerza final.</b><br>F<sub>f</sub> = m·v<sub>f</sub>²/r<sub>f</sub> = 0,1·16/0,2 = <b>8 N</b><br><b>Paso 4. La regla general que conviene saberse.</b> Con L constante, v ∝ 1/r, así que<br>F = m·v²/r ∝ <b>1/r³</b> &nbsp;⟹&nbsp; F<sub>f</sub> = F<sub>i</sub>·(r<sub>i</sub>/r<sub>f</sub>)³ = 1·2³ = 8 N.<br>Con ese cociente resolvés el ejercicio en un renglón, sin calcular ni r<sub>i</sub> ni v<sub>f</sub>.<br><b>Paso 5. El error automático.</b> Escribir F<sub>f</sub> = m·v²/(r/2) = 2·F<sub>i</sub> = 2 N dejando v igual. La respuesta 2 N está en la cabeza de todo el mundo y está mal por un factor 4.'},
]);

/* ==================== UNIDAD 4 · Cinemática dentro de un problema de energía ==================== */

registerExercises('fisica1-utn-energia', '4', [
  {st: 'Una partícula sube por una rampa de 37° y abandona la pista por el vértice superior. Su velocidad inicial de tiro…',
   opts: ['es horizontal',
          'es vertical, porque en el vértice se frena',
          'forma 53° sobre la horizontal',
          'forma 37° sobre la horizontal, con componente vertical hacia arriba'],
   c: 3,
   ex: 'La partícula <b>conserva la dirección del plano</b> en el instante en que lo abandona: si venía subiendo por una rampa de 37°, sale a 37° hacia arriba, con v<sub>0y</sub> = v·sen37° positiva. Eso hace que primero <i>siga subiendo</i> un poco y recién después caiga. ▸ Por qué las otras: suponerla horizontal es el error más caro de la unidad (te cambia el tiempo de vuelo y el alcance); vertical no tiene ningún sustento (en el vértice no se frena, llega con v<sub>B</sub> = 3,49 m/s en el B2 de 2012); y 53° sería el ángulo <b>complementario</b>, el que forma el plano con la vertical.'},

  {st: 'En el problema del radio de curvatura, el objeto se lanza a 53°. ¿Cuánto vale cos53°?',
   opts: ['0,5', '0,6', '0,8', '1'],
   c: 1,
   ex: '53° es el complemento de 37°, así que seno y coseno se intercambian: <b>sen53° = cos37° = 0,8</b> y <b>cos53° = sen37° = 0,6</b>. Con eso v₀ = 30/0,6 = 50 m/s. ▸ Por qué las otras: <b>0,8</b> es el error exacto que te deja v₀ = 37,5 m/s, un problema entero perdido por un coseno mal puesto; <b>1</b> es cos0°; <b>0,5</b> es cos60°, que es el otro par de valores que conviene tener a mano (sen30° = 0,5, cos30° = 0,866).'},

  {st: 'En la altura máxima de un tiro oblicuo, ¿cómo se reparte la aceleración entre tangencial y centrípeta?',
   opts: ['a<sub>c</sub> = 0 y a<sub>t</sub> = g', 'a<sub>c</sub> = a<sub>t</sub> = g/2', 'a<sub>c</sub> = g y a<sub>t</sub> = 0', 'La aceleración es nula: por eso está en el máximo'],
   c: 2,
   ex: 'En el vértice la velocidad es <b>horizontal</b> y g es vertical: quedan perpendiculares, así que <b>toda</b> g es centrípeta y nada es tangencial. De ahí sale g = v<sub>vértice</sub>²/R ⟹ v<sub>vértice</sub> = √(g·R). ▸ Por qué las otras: a<sub>t</sub> = g solo pasaría en una caída o subida <i>vertical</i>, donde g es paralela a v; el reparto mitad y mitad no corresponde a ningún punto en particular; y la aceleración <b>nunca</b> es nula en un tiro — lo que se anula en el vértice es la <i>componente vertical de la velocidad</i>, que es otra cosa.'},

  {st: 'Un objeto se lanza a 53° y en la altura máxima el radio de curvatura de la trayectoria es R = 90 m. ¿Cuál es el módulo de v₀? (g = 10 m/s²)',
   opts: ['50 m/s', '30 m/s', '37,5 m/s', '45 m/s'],
   c: 0,
   ex: 'En el vértice v<sub>vértice</sub> = √(g·R) = √900 = 30 m/s, y como esa es la componente <b>horizontal</b>, que es constante en todo el tiro: v₀ = 30/cos53° = 30/0,6 = <b>50 m/s</b>. ▸ Por qué las otras: <b>30 m/s</b> es la velocidad <i>en el vértice</i>, no la inicial — te frenaste un renglón antes; <b>37,5 m/s</b> sale de usar cos53° = 0,8 (el intercambio de seno y coseno); <b>45 m/s</b> saldría de dividir por sen53° pensando que la componente que se conserva es la vertical.'},

  {st: 'Una partícula despega a 1,2 m del piso con v<sub>0y</sub> = 2,1 m/s hacia arriba y v<sub>0x</sub> = 2,8 m/s. El tiempo hasta tocar el suelo sale de…',
   opts: ['t = 2·v<sub>0y</sub>/g, la fórmula de tiempo de vuelo',
          't = √(2h/g), como si cayera desde el reposo',
          '5t² − 2,1t − 1,2 = 0, la cuadrática completa',
          't = x/v<sub>0x</sub>, con el alcance de la fórmula a igual nivel'],
   c: 2,
   ex: 'Como el despegue está a 1,2 m sobre el piso, la salida y la llegada <b>no están al mismo nivel</b>: hay que escribir la horaria completa y = 1,2 + 2,1·t − 5·t² = 0 y resolver la cuadrática. Da t = 0,743 s (se descarta la raíz negativa) y después x = 2,8·0,743 = 2,08 m. Es el B2 del 1er parcial 2012. ▸ Por qué las otras: 2·v<sub>0y</sub>/g vale solo cuando el proyectil vuelve a la <i>misma</i> altura; √(2h/g) ignora que la partícula sale con componente vertical hacia arriba (sería el caso semiparabólico); y usar el alcance de la fórmula a igual nivel arrastra el mismo error, más que necesitarías el alcance que justamente te están pidiendo.'},
]);

registerReveals('fisica1-utn-energia', '4', [

  {st: '<span class="muted">1er parcial 2012, cátedra Martinelli · 18/10/12 · UTN FRBA</span><br><b>B2:</b> Una partícula se mueve primero sobre una superficie horizontal carente de rozamiento, en la dirección indicada, con una velocidad de módulo V<sub>0</sub> = 7 m/s. Luego, la misma asciende por un plano inclinado de longitud D = 2 m y ángulo 37º, cuyo coeficiente de rozamiento dinámico es μ<sub>d</sub> = 0.4. Determine:<br>a) Con qué velocidad llega la partícula al punto superior del plano (resuelva utilizando conceptos de energía).<br>b) A qué distancia de la base del plano impacta nuevamente con el suelo.',
   ans: 'a) v<sub>B</sub> = 3,49 m/s ≅ 3,5 m/s (a 37° sobre la horizontal) · b) x<sub>C</sub> = 2,08 m desde el pie de la pared vertical',
   sol: '<b>Paso 0. Los dos actos.</b> Acto 1: energía sobre la rampa rugosa, para conseguir el módulo de la velocidad en el vértice. Acto 2: tiro oblicuo desde esa altura. La bisagra entre los dos es que la <b>dirección</b> te la da la geometría del plano, no la energía.<br><b>Paso 1. a) La altura del vértice.</b><br>h<sub>B</sub> = D·sen37° = 2·0,6 = <b>1,2 m</b><br><b>Paso 2. Balance A→B (el tramo horizontal es liso, no disipa).</b><br>½·m·v<sub>B</sub>² + m·g·h<sub>B</sub> − ½·m·v<sub>A</sub>² = −μ<sub>d</sub>·m·g·cos37°·D &nbsp;<span class="muted">(la masa se cancela entera)</span><br>v<sub>B</sub>² = v<sub>A</sub>² − 2·g·D·(sen37° + μ<sub>d</sub>·cos37°)<br>v<sub>B</sub>² = 49 − 2·10·2·(0,6 + 0,4·0,8) = 49 − 40·0,92 = 49 − 36,8 = <b>12,2 m²/s²</b><br><b>v<sub>B</sub> = 3,49 m/s ≅ 3,5 m/s</b>, dirigida a <b>37° sobre la horizontal</b>.<br><b>Paso 3. b) Descomponés la velocidad de despegue.</b><br>v<sub>Bx</sub> = 3,5·cos37° = <b>2,8 m/s</b> &nbsp;·&nbsp; v<sub>By</sub> = 3,5·sen37° = <b>2,1 m/s hacia arriba</b><br><b>Paso 4. Las horarias con origen al pie de la pared vertical.</b><br>x(t) = 2,8·t<br>y(t) = 1,2 + 2,1·t − 5·t²<br><b>Paso 5. Impacto: y = 0.</b><br>5t² − 2,1t − 1,2 = 0<br>t = [2,1 + √(4,41 + 24)]/10 = (2,1 + 5,33)/10 = <b>0,743 s</b> (se descarta la raíz negativa)<br>x<sub>C</sub> = 2,8·0,743 = <b>2,08 m</b>.<br><b>Paso 6. Las cinco trampas.</b> (1) El rozamiento actúa sobre D = 2 m, no sobre la altura; (2) N = m·g·cos37°, no m·g; (3) el paréntesis (0,6 + 0,4·0,8) = 0,92 junta la subida y el rozamiento, no te olvides ninguno de los dos; (4) <b>no sale horizontal</b>: v<sub>By</sub> = 2,1 m/s hacia arriba; (5) el lanzamiento es desde 1,2 m, así que el tiempo sale de la cuadrática completa. Y antes de seguir, chequeá que v<sub>B</sub>² = 12,2 > 0, o sea que efectivamente llega arriba.'},

  {st: '<span class="muted">Final UTN.BA · hoja sin fecha visible (la de las poleas concéntricas y el MAS del resorte vertical) · problema 1</span><br><b>1)</b> Un objeto es lanzado con un ángulo de 53° con la horizontal. Cuando alcanza la altura máxima, el radio de curvatura de la trayectoria es de R = 90 m. Calcular el modulo de la velocidad inicial v<sub>0</sub> del objeto, despreciando el rozamiento con el aire.',
   ans: 'v<sub>0</sub> = 50 m/s',
   sol: '<b>Paso 0. Este problema no cae en ningún parcial de Martinelli: es exclusivo de los finales.</b> Y cuando cae, cae como problema 1. Son tres renglones si entendés la idea.<br><b>Paso 1. La idea.</b> La aceleración de un cuerpo se descompone en <b>tangencial</b> (cambia el módulo de v) y <b>normal o centrípeta</b> (cambia la dirección). En un tiro la única aceleración es <b>g</b>, vertical hacia abajo. En la <b>altura máxima</b> la velocidad es <b>horizontal</b>, así que g queda perpendicular a ella:<br><b>toda g es centrípeta y nada es tangencial.</b><br><b>Paso 2. Escribís eso.</b><br>g = v<sub>vértice</sub>²/R &nbsp;⟹&nbsp; v<sub>vértice</sub> = √(g·R) = √(10·90) = √900 = <b>30 m/s</b><br><b>Paso 3. Del vértice al lanzamiento.</b> En el vértice la velocidad es puramente horizontal, y la componente horizontal <b>es constante durante todo el tiro</b>:<br>v<sub>vértice</sub> = v<sub>0</sub>·cos53° &nbsp;⟹&nbsp; v<sub>0</sub> = 30/cos53° = 30/0,6 = <b>50 m/s</b>.<br><b>Paso 4. Las dos trampas.</b> (1) <b>cos53° = 0,6</b>, no 0,8: 53° es el complemento de 37° y los valores se intercambian. Con 0,8 te da 37,5 m/s y el ejercicio entero queda mal por un solo coseno. (2) Frenarte en los 30 m/s: esa es la velocidad <i>en el vértice</i>, y te preguntan la <b>inicial</b>.<br><b>Paso 5. Guiño.</b> v = √(g·R) es la misma cara que la condición de no desprendimiento en el loop. No es casualidad: en los dos casos el peso es exactamente la resultante centrípeta.'},

  {st: '<span class="muted">Final UTN.BA · FINAL 27/2/25 · problema 1</span><br><b>1)</b> Desde una altura de 2 m se lanza horizontalmente una flecha que se clava en una pared ubicada horizontalmente a 5 m del lugar de lanzamiento y a una altura de 0.75 m, calcule:<br>a. La velocidad con la cual fue lanzada la flecha.<br>b. El impulso que recibe la flecha de la pared donde se incrusta, sabiendo que la masa de la flecha es de 100 g.',
   ans: 'a) v<sub>0</sub> = 10 m/s · b) |J| = 1,12 N·s, con componentes J<sub>x</sub> = −1 N·s y J<sub>y</sub> = +0,5 N·s (opuesto a la velocidad de impacto)',
   sol: '<b>Paso 0. Tiro semiparabólico: se lanza HORIZONTAL.</b> v<sub>0y</sub> = 0, así que la componente vertical arranca de cero y la horizontal es constante. Origen en el punto de lanzamiento, eje y hacia arriba.<br><b>Paso 1. a) Primero el tiempo, por la vertical.</b> La flecha baja<br>Δy = 2 − 0,75 = <b>1,25 m</b><br>1,25 = ½·g·t² = 5·t² &nbsp;⟹&nbsp; t² = 0,25 &nbsp;⟹&nbsp; <b>t = 0,5 s</b><br><b>Paso 2. Y con ese tiempo, la horizontal.</b><br>v<sub>0</sub> = x/t = 5/0,5 = <b>10 m/s</b>.<br><b>Paso 3. b) La velocidad justo antes del impacto.</b><br>v<sub>x</sub> = 10 m/s (constante) &nbsp;·&nbsp; v<sub>y</sub> = −g·t = −5 m/s<br>|v| = √(100 + 25) = √125 = <b>11,18 m/s</b><br><span class="muted">Chequeo por energía: ½v² = ½v<sub>0</sub>² + g·Δy ⟹ v² = 100 + 2·10·1,25 = 125. ✓</span><br><b>Paso 4. El impulso es la variación de la cantidad de movimiento.</b> Se <b>clava</b>, o sea que queda en reposo: p<sub>final</sub> = 0. Con m = 100 g = <b>0,1 kg</b>:<br>J = Δp = 0 − m·v = −0,1·(10 î − 5 ĵ) = <b>(−1 î + 0,5 ĵ) N·s</b><br>|J| = 0,1·11,18 = <b>1,12 N·s</b><br><b>Paso 5. Dirección y sentido (el enunciado lo pide implícitamente).</b> El impulso apunta <b>exactamente en contra</b> de la velocidad de impacto: hacia atrás y hacia arriba, formando 26,6° con la horizontal. Tiene que ser así: la pared frena a la flecha.<br><b>Paso 6. La trampa de unidades.</b> 100 g = 0,1 kg. Si dejás 100, el impulso te da 1118 N·s y ninguna pared del mundo aguanta eso.'},

  {st: '<span class="muted">Final UTN.BA · hoja sin fecha visible (la del tanque de gasolina y el MCU con radio variable) · problema 6</span><br><b>6.</b> Un cohete parte del reposo elevándose con una aceleración constante de 19,5 m/s² durante un minuto. En ese momento se agota el combustible y sigue subiendo como partícula libre. Calcule la altura máxima alcanzada por el cohete.',
   ans: 'H<sub>máx</sub> = 35100 m + 68445 m = 103545 m ≈ 103,5 km',
   sol: '<b>Paso 0. Otra vez dos actos, pero al revés que en el B2 de 2012.</b> Acto 1: cinemática pura (MRUV con motor). Acto 2: energía (tiro vertical libre). Marcá el instante que los separa: cuando se agota el combustible.<br><b>Paso 1. Acto 1, con las horarias del MRUV.</b> t<sub>1</sub> = un minuto = <b>60 s</b>, a = 19,5 m/s², parte del reposo:<br>h<sub>1</sub> = ½·a·t<sub>1</sub>² = ½·19,5·3600 = <b>35100 m</b><br>v<sub>1</sub> = a·t<sub>1</sub> = 19,5·60 = <b>1170 m/s</b><br><b>Paso 2. Acto 2, por energía (más corto que por cinemática).</b> A partir de ahí solo actúa el peso, la energía mecánica se conserva y en la altura máxima v = 0:<br>½·m·v<sub>1</sub>² = m·g·h<sub>2</sub> &nbsp;⟹&nbsp; h<sub>2</sub> = v<sub>1</sub>²/(2·g) = 1170²/20 = 1368900/20 = <b>68445 m</b><br><b>Paso 3. La altura total.</b><br>H<sub>máx</sub> = h<sub>1</sub> + h<sub>2</sub> = 35100 + 68445 = <b>103545 m ≈ 103,5 km</b>.<br><b>Paso 4. La trampa del enunciado.</b> "Durante un minuto" son <b>60 s</b>, no 1. Con t = 1 s te da h ≈ 29 m y el resultado no tiene ningún sentido para un cohete.<br><b>Paso 5. El error conceptual.</b> Suponer que la altura máxima es solo h<sub>2</sub>, o solo h<sub>1</sub>. El cohete <b>sigue subiendo</b> después de que se apaga el motor: la altura final es la suma de los dos tramos. Y ojo, en el segundo tramo la aceleración deja de ser 19,5 m/s² hacia arriba y pasa a ser g = 10 m/s² hacia abajo.'},
]);
