// ============================================================
// FÍSICA I · UTN FRBA · CHOQUES Y CANTIDAD DE MOVIMIENTO
// Fuentes:
//   · 8 ejercicios de choque de los 2dos parciales de la cátedra
//     Martinelli (2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017)
//   · choques que aparecen en los finales de UTN.BA relevados
//     (26/05/22, 12/12/23, 14/02/24, 21/02/24, 27/02/25, 13/02/25
//      y dos hojas sin fecha visible)
// Convención de la cátedra en TODAS las resoluciones: g = 10 m/s².
// ============================================================

// ============================================================
// SECCIÓN 1 · LA SECUENCIA OBLIGADA DE TRES ETAPAS
// ============================================================
registerExercises('fisica1-utn-choques', '1', [
  {st: 'En un choque plástico (los cuerpos quedan pegados), ¿qué se conserva?',
   opts: ['La energía cinética y la cantidad de movimiento', 'Solo la cantidad de movimiento', 'Solo la energía cinética', 'Ninguna de las dos'],
   c: 1,
   ex: 'En el choque plástico se conserva <b>solo la cantidad de movimiento</b>: las fuerzas impulsivas son internas al sistema y el choque dura un instante, así que el impulso de las externas es despreciable. ▸ La energía cinética <b>no</b> se conserva: en el A1 de 2016 se disipa el 95% (237,5 de 250 J), en el A2 de 2011 la mitad (50 de 100 J). ▸ Por qué las otras: (A) es el choque <b>elástico</b>, que en los parciales de Martinelli no aparece nunca; (C) sería al revés y es imposible — sin conservar p no hay tercera ley; (D) p siempre se conserva en el choque.'},

  {st: 'Un problema tiene un péndulo que baja, choca plásticamente con un bloque y el conjunto sube por un plano rugoso. ¿Dónde cortás exactamente el problema?',
   opts: ['En el instante en que se suelta el péndulo y en el instante final', 'Justo ANTES del choque y justo DESPUÉS del choque', 'A la mitad del recorrido del péndulo', 'No hace falta cortarlo: se plantea energía de punta a punta'],
   c: 1,
   ex: 'Los dos cortes son <b>justo antes</b> y <b>justo después</b> del choque. Entre esos dos instantes no hay desplazamiento, ni cambio de altura, ni trabajo del roce: por eso ahí, y solo ahí, vale escribir la ecuación de cantidad de movimiento sola. ▸ El tramo previo se resuelve con energía; el posterior también, ahora con el trabajo del rozamiento. ▸ Por qué las otras: (D) es el error nº1 del tema — energía de punta a punta ignora que en el choque se pierde energía; (A) y (C) cortan donde no cambia nada del planteo.'},

  {st: 'Un péndulo ideal de longitud L se suelta con la soga horizontal. ¿Con qué rapidez llega al punto más bajo y por qué se puede usar conservación de la energía?',
   opts: ['v = √(2gL), porque la tensión es perpendicular al desplazamiento y no realiza trabajo', 'v = √(gL), porque la altura de caída es L/2', 'v = 2gL, porque la tensión hace trabajo positivo', 'Depende de la masa del cuerpo'],
   c: 0,
   ex: 'La soga arranca <b>horizontal</b>, así que el desnivel hasta el punto más bajo es exactamente <b>L</b>: m·g·L = ½·m·v² → <b>v = √(2gL)</b>. Con L = 0,8 m y g = 10: v = √16 = 4 m/s (es el número de los parciales 2014 y 2017). ▸ La justificación que puntúan: la <b>tensión es siempre perpendicular al desplazamiento, por lo tanto no trabaja</b>, y sin rozamiento la única fuerza que trabaja es el peso, que es conservativa. ▸ Por qué las otras: (B) usa L/2 sin motivo; (C) confunde v con v²; (D) la masa se cancela, no aparece en el resultado.'},

  {st: 'Después de un choque plástico entre m₁ y m₂, el conjunto entra en una zona rugosa. ¿Cuánto vale la normal que usás en el trabajo del rozamiento?',
   opts: ['m₁·g', 'm₂·g', '(m₁ + m₂)·g', 'La misma que antes del choque'],
   c: 2,
   ex: 'Después del choque plástico los cuerpos van <b>pegados</b>: la masa que apoya sobre la superficie es la suma. N = <b>(m₁ + m₂)·g</b> y W<sub>roz</sub> = −μ<sub>d</sub>·(m₁+m₂)·g·d. ▸ Y la misma masa total va en la energía cinética: E = ½·(m₁+m₂)·v′². ▸ Usar solo m₁ en el rozamiento es uno de los errores más frecuentes del A2 2011 y del A1 2016. ▸ Por qué las otras: (D) antes del choque solo apoyaba uno de los dos.'},

  {st: 'El enunciado te da μe = 0,3 y μd = 0,2 para el tramo por el que se desliza el conjunto después del choque. ¿Cuál usás?',
   opts: ['μe, porque el cuerpo termina detenido', 'μd, porque el cuerpo está deslizando; μe es un distractor', 'El promedio de los dos', 'μe para frenar y μd para arrancar'],
   c: 1,
   ex: 'El cuerpo <b>está deslizando</b> sobre la superficie, así que corresponde el coeficiente <b>dinámico</b>. ▸ El μ<sub>e</sub> es un <b>dato deliberadamente inútil</b>: la cátedra avisa en el encabezado que "puede haber datos que no interesen". Aparece como distractor en el A1 2012, el A1 2013, el A1 2015 y el A1 2016. ▸ Por qué las otras: (A) que termine detenido no cambia que durante el frenado deslizaba; (C) promediar coeficientes no existe; (D) invierte los roles y además acá nunca hay que verificar arranque.'},

  {st: 'Se pide el impulso que recibe el cuerpo A, que llegaba a 4 m/s (mA = 1 kg) y queda moviéndose a 1 m/s en el mismo sentido. ¿Cuál es la respuesta completa?',
   opts: ['3 kg·m/s', '5 kg·m/s en el sentido del movimiento', '−3 kg·m/s î, es decir 3 N·s en sentido opuesto al movimiento de A', '4 kg·m/s'],
   c: 2,
   ex: 'I⃗ = Δp⃗ = m·v⃗<sub>f</sub> − m·v⃗<sub>i</sub> = 1·1 − 1·4 = <b>−3 kg·m/s</b> en el eje adoptado. ▸ El signo tiene sentido físico: a A <b>lo frenaron</b>, así que el impulso apunta en sentido contrario a su movimiento. ▸ Cuando el enunciado dice "exprese en forma vectorial" (A1 2010) hay que declarar el versor y escribir <b>ΔP⃗<sub>A</sub> = −3 kg·m/s î</b>. ▸ Por qué las otras: (A) da el módulo pero pierde el sentido, que es lo que se está evaluando; (B) suma en vez de restar; (D) es la cantidad de movimiento inicial, no su variación.'}
]);

registerReveals('fisica1-utn-choques', '1', [

  {st: '<b>Final UTN.BA · 27/02/25 · Problema 1.</b> Enunciado verbatim: «Desde una altura de 2 m se lanza horizontalmente una flecha que se clava en una pared ubicada horizontalmente a 5 m del lugar de lanzamiento y a una altura de 0.75 m, calcule: a. La velocidad con la cual fue lanzada la flecha. b. El impulso que recibe la flecha de la pared donde se incrusta, sabiendo que la masa de la flecha es de 100 g.»',
   ans: 'a) v₀ = 10 m/s (horizontal). b) I⃗ = (−1 î + 0,5 ĵ) kg·m/s ▸ módulo 1,12 N·s, dirigido hacia atrás y hacia arriba, formando 26,6° con la horizontal — exactamente opuesto a la velocidad con la que la flecha llegó a la pared.',
   sol: 'Este ejercicio es la etapa 2 sola, sin choque entre cuerpos: la pared le pega un impulso a la flecha y la deja quieta. Pero antes hay que resolver un tiro horizontal para saber con qué velocidad llegó. ▸ <b>Sistema de referencia:</b> x horizontal en el sentido del lanzamiento, y vertical hacia arriba, origen en el punto de lanzamiento. g = 10 m/s². <br><br><b>a) La velocidad de lanzamiento.</b> ▸ <b>Paso 1 · cuánto cayó.</b> Sale a 2 m y se clava a 0,75 m: Δy = 2 − 0,75 = <b>1,25 m</b>. ▸ <b>Paso 2 · el tiempo lo da la vertical</b> (es tiro horizontal, v<sub>0y</sub> = 0): 1,25 = ½·10·t² → t² = 0,25 → <b>t = 0,5 s</b>. ▸ <b>Paso 3 · la horizontal es MRU:</b> v₀ = 5 m / 0,5 s = <b>10 m/s</b>. <br><br><b>b) El impulso de la pared.</b> ▸ <b>Paso 4 · con qué velocidad llega.</b> v<sub>x</sub> = 10 m/s (constante, no hay fuerza horizontal) y v<sub>y</sub> = −g·t = −10·0,5 = −5 m/s. Entonces v⃗<sub>i</sub> = (10 î − 5 ĵ) m/s, con módulo √(100+25) = <b>11,18 m/s</b>. ▸ <b>Paso 5 · queda clavada</b>, o sea v⃗<sub>f</sub> = 0. Con m = 100 g = <b>0,1 kg</b>:<br>I⃗ = m·v⃗<sub>f</sub> − m·v⃗<sub>i</sub> = 0 − 0,1·(10 î − 5 ĵ) = <b>(−1 î + 0,5 ĵ) kg·m/s</b>. ▸ <b>Paso 6 · módulo y sentido:</b> |I⃗| = 0,1·11,18 = <b>1,12 N·s</b>, y el ángulo con la horizontal es arctg(0,5/1) = <b>26,6°</b>. Apunta hacia atrás y hacia arriba: exactamente opuesto a la velocidad de llegada, como tiene que ser cuando el cuerpo queda en reposo. <div class="trap"><div class="tr-t">Los dos descuidos del inciso b</div><b>1 ·</b> Calcular el impulso con la velocidad de <b>lanzamiento</b> (10 m/s) en vez de la de <b>llegada</b> (11,18 m/s): la flecha llega más rápido de lo que salió porque ganó componente vertical. ▸ <b>2 ·</b> Contestar solo el módulo. El enunciado pide "el impulso", que es un vector: sin el versor y sin el sentido, el inciso queda a medias. ▸ Y ojo con las unidades: 100 g son <b>0,1 kg</b>; con 100 el resultado sale mil veces más grande.</div>'},

  {st: '<b>Final UTN FRBA · 14/02/24 · Problema 5.</b> Enunciado verbatim: «El gráfico corresponde a la velocidad de un móvil de masa 3 kg que se desplaza sobre un camino recto. En el instante t0 = 0 se encuentra en la posición x0 = 0. a) ¿Cuál es la posición del móvil en el instante final de su recorrido? b) Calcular módulo dirección y sentido del impulso que recibe el móvil entre t = 6 s y t = 8 s.» <span class="muted">(dato reconstruido: el gráfico v-t está fotografiado en baja resolución. Los quiebres seguros son: sube de 0 a 4 m/s entre t = 0 y t = 4 s, meseta en 4 m/s hasta t = 6 s, baja cruzando cero en t = 8 s hasta −2 m/s, meseta en −2 m/s y vuelve a 0 en t = 12 s. La meseta negativa podría empezar en t = 9 o terminar en t = 10,5: eso afecta al inciso a, no al b.)</span>',
   ans: 'a) x_final ≈ 14 m (con la lectura de la meseta negativa entre t = 9 s y t = 11 s). b) I = 3·(0 − 4) = −12 kg·m/s ▸ módulo 12 N·s, dirección la del camino recto, sentido OPUESTO al del movimiento inicial: es un impulso frenante.',
   sol: '<b>a) La posición es el área bajo la curva v-t.</b> Como x₀ = 0, x<sub>final</sub> = Σ áreas, contando <b>negativas</b> las que quedan por debajo del eje. ▸ 0 a 4 s: triángulo ½·4·4 = <b>+8 m</b>. ▸ 4 a 6 s: rectángulo 4·2 = <b>+8 m</b>. ▸ 6 a 8 s: triángulo ½·2·4 = <b>+4 m</b> (todavía va para adelante, aunque frenando). ▸ 8 a 9 s: triángulo ½·1·2 = <b>−1 m</b> (ya volvió). ▸ 9 a 11 s: rectángulo 2·2 = <b>−4 m</b>. ▸ 11 a 12 s: triángulo ½·1·2 = <b>−1 m</b>. ▸ Total: 8 + 8 + 4 − 1 − 4 − 1 = <b>x<sub>final</sub> = 14 m</b>. <br><br><b>b) El impulso es la variación de la cantidad de movimiento</b>, no hace falta ninguna fuerza: I⃗ = m·v⃗(8) − m·v⃗(6). ▸ Del gráfico: v(6 s) = <b>+4 m/s</b> y v(8 s) = <b>0</b> (la recta cruza el eje justo ahí). ▸ I = 3 kg·(0 − 4 m/s) = <b>−12 kg·m/s = −12 N·s</b>. ▸ <b>Respuesta completa:</b> módulo <b>12 N·s</b>, dirección la del camino recto (horizontal), sentido <b>opuesto</b> al del movimiento que traía el móvil. Es lógico: entre 6 y 8 s el móvil frena, así que el impulso que recibe apunta al revés. <div class="trap"><div class="tr-t">El área negativa y el impulso "sin fuerza"</div><b>1 ·</b> En el inciso a, sumar todas las áreas en valor absoluto da 26 m, que sería la <b>distancia recorrida</b>, no la posición. La posición pide el <b>desplazamiento</b>, con signo: el tramo en que v &lt; 0 resta. ▸ <b>2 ·</b> Muchos buscan calcular la fuerza y multiplicar por el tiempo. No hace falta: el teorema del impulso dice que <b>I⃗ = Δp⃗</b>, y con leer dos velocidades del gráfico ya está. ▸ <b>3 ·</b> El enunciado pide <b>módulo, dirección y sentido</b>: contestar "−12" sin interpretarlo deja puntos en la mesa.</div>'}
]);

// ============================================================
// SECCIÓN 2 · CHOQUE PLÁSTICO 1D · LOS 8 DEL PARCIAL
// ============================================================
registerExercises('fisica1-utn-choques', '2', [
  {st: 'A2 · 2do parcial 2011: un bloque de 2 kg es lanzado por un resorte de k = 800 N/m comprimido 50 cm sobre superficie lisa. ¿Con qué velocidad llega al choque?',
   opts: ['5 m/s', '10 m/s', '20 m/s', '14,1 m/s'],
   c: 1,
   ex: 'Toda la energía elástica se convierte en cinética (tramo liso): ½·k·Δx² = ½·m·v² → ½·800·0,5² = <b>100 J</b> = ½·2·v² → v² = 100 → <b>v = 10 m/s</b>. ▸ Cuidado con Δx = 50 cm = <b>0,5 m</b>, que al cuadrado da 0,25 m². ▸ Por qué las otras: (A) 5 m/s es la velocidad <b>después</b> del choque con el otro bloque de 2 kg; (C) 20 m/s sale de olvidar el ½ en un lado; (D) 14,1 m/s = √200, sale de usar 200 J en vez de 100 J.'},

  {st: 'A1 · 2do parcial 2010: después del choque el par (4 kg) entra a la zona rugosa con 1 m/s. El tramo mide d = 50 cm con μd = 0,5. ¿Qué pasa?',
   opts: ['Atraviesa el tramo y sube por el plano inclinado', 'Se detiene dentro del tramo rugoso, a 10 cm de la entrada', 'Atraviesa y llega al plano con 1 m/s', 'Se detiene justo al final del tramo'],
   c: 1,
   ex: 'Primero <b>verificás si llega</b>: energía de entrada E = ½·4·1² = <b>2 J</b>; trabajo que le sacaría el roce en todo el tramo = μ<sub>d</sub>·(m₁+m₂)·g·d = 0,5·4·10·0,5 = <b>10 J</b>. ▸ Como 2 J &lt; 10 J, <b>no atraviesa</b>. ▸ La distancia real: 2 J = 0,5·4·10·d′ → d′ = <b>0,1 m = 10 cm</b>. Queda a 40 cm del pie del plano y nunca sube. ▸ Por qué las otras: suponer que llega al plano (A, C) da un resultado absurdo — es el motivo por el que hay que hacer la comparación antes de calcular; (D) sería si la energía de entrada fuera exactamente 10 J.'},

  {st: 'A1 · 2do parcial 2015: la zona rugosa empieza 1,5 m antes de la pared, el resorte tiene longitud natural 50 cm y se comprime 20 cm. ¿Qué distancia recorre el bloque CON rozamiento hasta detenerse?',
   opts: ['1,5 m', '1,2 m', '1,0 m', '1,7 m'],
   c: 1,
   ex: 'La geometría es la trampa central del ejercicio. El bloque entra a la zona gris en A, avanza hasta tocar el extremo libre del resorte y todavía lo comprime 20 cm: <b>D = 1,5 − l₀ + Δl<sub>máx</sub> = 1,5 − 0,5 + 0,2 = 1,2 m</b>. ▸ Con 1,5 m el trabajo del roce te da 15 J en vez de 12 J y v₀ sale mal. ▸ Por qué las otras: (A) es la zona gris completa, sin descontar el resorte; (C) descuenta el resorte pero olvida sumar la compresión; (D) suma la compresión en vez de restarla al revés.'},

  {st: 'A1 · 2do parcial 2014: el péndulo (m₁ = 0,25 kg) llega a 4 m/s hacia la IZQUIERDA y choca de frente con m₂ = 1 kg que va a 3 m/s hacia la derecha. ¿Velocidad del conjunto?',
   opts: ['3,2 m/s hacia la derecha', '1,6 m/s hacia la derecha', '1,6 m/s hacia la izquierda', '5,6 m/s hacia la derecha'],
   c: 1,
   ex: 'Es un choque <b>frontal</b>: con x positivo hacia la derecha, el péndulo entra con signo negativo. ▸ 0,25·(−4) + 1·(+3) = 1,25·v′ → −1 + 3 = 2 = 1,25·v′ → <b>v′ = +1,6 m/s, hacia la derecha</b> (gana m₂, que trae más cantidad de movimiento). ▸ Por qué las otras: (A) 3,2 m/s es el error clásico de sumar todo positivo (0,25·4 + 1·3 = 4); (C) tiene el módulo bien pero el sentido al revés, y el enunciado pide explícitamente indicar el sentido; (D) suma las velocidades sin pesar por las masas.'},

  {st: 'Un cuerpo de masa m y velocidad v choca plásticamente con otro de igual masa en reposo. ¿Qué fracción de la energía cinética se pierde?',
   opts: ['Nada, se conserva', 'Un cuarto', 'La mitad', 'Todo'],
   c: 2,
   ex: 'Cantidad de movimiento: m·v = 2m·v′ → v′ = v/2. ▸ E<sub>i</sub> = ½·m·v²; E<sub>f</sub> = ½·(2m)·(v/2)² = ½·m·v²/2 = <b>E<sub>i</sub>/2</b>. ▸ Se pierde <b>la mitad</b>, y no depende del valor de m ni de v. Es el caso del A2 2011 (100 J → 50 J) y del A1 2015. ▸ Por qué las otras: (A) confunde con elástico; (D) la pérdida total solo pasaría si el conjunto quedara en reposo, o sea si las cantidades de movimiento iniciales se cancelaran.'},

  {st: 'A1 · 2do parcial 2016: bala de 50 g a 100 m/s que queda incrustada en un bloque de 950 g. ¿Cuál es la velocidad del conjunto justo después?',
   opts: ['100 m/s', '5 m/s', '22,4 m/s', '95 m/s'],
   c: 1,
   ex: 'Cantidad de movimiento: 0,05·100 = (0,95 + 0,05)·v → 5 = 1,00·v → <b>v = 5 m/s</b>. ▸ Fijate que la cátedra elige los números para que la masa total dé exactamente 1,00 kg: si no te queda redondo, revisá las unidades (950 g = 0,95 kg). ▸ Por qué las otras: (C) 22,4 m/s = √(2·250/1) es lo que sale de <b>conservar energía en el choque</b>, el error prohibido: en este choque se disipa el 95% de los 250 J iniciales; (A) y (D) ignoran el reparto de masa.'}
]);

registerReveals('fisica1-utn-choques', '2', [

  {st: '<b>1 · 2do parcial 2014 · A1 · Curso I1021, Prof. Patricia Martinelli, UTN.BA, 29/11/2014.</b> Enunciado verbatim: «A1: Un péndulo ideal, formado por una soga de longitud L=0,8m y un cuerpo de masa m1=0.25kg, se deja caer desde una posición donde la soga esta horizontal. Cuando llega al punto más bajo de su trayectoria choca plásticamente con otro cuerpo de masa m2=4m1, que tiene una velocidad horizontal constante v2=3m/s en la dirección indicada. Las masas son puntuales y no hay rozamiento. a) Determine la velocidad del cuerpo 1 justo antes de chocar con el cuerpo 2. b) Calcule la velocidad de las masas justo después del choque. Indique si es hacia la derecha o hacia la izquierda.»',
   ans: 'a) |v₁| = 4 m/s, dirigida hacia la izquierda (v₁ₓ = −4 m/s). b) v′ = 1,6 m/s HACIA LA DERECHA, los dos cuerpos juntos.',
   sol: '<b>Hipótesis y sistema de referencia.</b> Masas puntuales, sin rozamiento, soga ideal. Eje x positivo <b>hacia la derecha</b> (el sentido de v₂), y positivo hacia arriba. g = 10 m/s². m₂ = 4·m₁ = 4·0,25 = <b>1 kg</b>. <br><br><b>a) Etapa 1 · el descenso del péndulo (energía).</b> La tensión de la soga es perpendicular al desplazamiento en todo momento, por lo tanto <b>no realiza trabajo</b>; sin rozamiento, la única fuerza que trabaja es el peso y se conserva la energía mecánica. La soga arranca horizontal, así que el desnivel es exactamente L: <br>m₁·g·L = ½·m₁·v₁² → v₁² = 2·g·L = 2·10·0,8 = 16 → <b>|v₁| = 4 m/s</b>. ▸ Como el cuerpo 1 llega al punto más bajo moviéndose <b>hacia la izquierda</b>: <b>v₁ₓ = −4 m/s</b>. La masa se canceló, como tenía que pasar. <br><br><b>b) Etapa 2 · el choque (cantidad de movimiento).</b> El choque es instantáneo: el impulso de las fuerzas externas es despreciable frente al de las internas, así que se conserva la componente x de la cantidad de movimiento.<br>m₁·v₁ₓ + m₂·v₂ₓ = (m₁ + m₂)·v′ₓ<br>0,25·(−4) + 1·(+3) = 1,25·v′ₓ<br>−1 + 3 = 2 kg·m/s = 1,25 kg · v′ₓ → <b>v′ₓ = 1,6 m/s</b>. ▸ El signo es <b>positivo</b>: el conjunto sale <b>hacia la derecha</b>, en el sentido en que venía el cuerpo 2. <div class="trap"><div class="tr-t">Las tres cosas que hunden este ejercicio</div><b>1 · El choque es frontal.</b> Los cuerpos van en sentidos opuestos, así que v₁ entra <b>con signo negativo</b>. Quien suma todo positivo obtiene 4/1,25 = 3,2 m/s, que es el resultado erróneo más común de este parcial. ▸ <b>2 · m₂ = 4·m₁ = 1 kg</b>, no 4 kg. Es una masa definida en función de la otra, no un dato numérico. ▸ <b>3 ·</b> El enunciado pide <b>expresamente</b> indicar si es hacia la derecha o hacia la izquierda: la interpretación del signo es parte de la respuesta.</div>'},

  {st: '<b>2 · 2do parcial 2017 · A1 · Curso R1022, Prof. Patricia Martinelli, UTN FRBA, 13/11/2017.</b> Enunciado verbatim: «A1: Un péndulo ideal, formado por una soga de longitud L=0.8m y un cuerpo de masa m1=0.25kg, se deja caer desde una posición donde la soga esta horizontal. Cuando llega al punto más bajo de su trayectoria (punto A) choca plásticamente con otro cuerpo de masa m2=3m1 que se encuentra en reposo. Las masas son puntuales y no hay rozamiento. a) Calcule la velocidad del cuerpo 1 justo antes del choque y la velocidad de ambos cuerpos justo después del choque. b) Determine la altura máxima que alcanzan ambas masas luego del choque.»',
   ans: 'a) v₁ = 4 m/s justo antes (hacia −x); v′ = 1 m/s para los dos cuerpos juntos, en el mismo sentido. b) h = 0,05 m = 5 cm.',
   sol: '<b>Datos y referencia.</b> L = 0,8 m, m₁ = 0,25 kg, m₂ = 3·m₁ = <b>0,75 kg</b>, los dos parten del reposo, g = 10 m/s². Eje x hacia la derecha, cero de energía potencial en el punto A. Este ejercicio es el arquetipo puro de las <b>tres etapas</b>. <br><br><b>Etapa 1 · bajada (energía).</b> Tensión perpendicular al desplazamiento ⇒ no trabaja ⇒ energía mecánica constante:<br>m₁·g·L = ½·m₁·v₁² → v₁ = √(2·10·0,8) = √16 = <b>4 m/s</b>, llegando a A hacia −x ⇒ v⃗₁ = −4 m/s x̂. <br><br><b>Etapa 2 · choque plástico (cantidad de movimiento).</b> Instantáneo ⇒ se conserva p en x, y <b>no</b> la energía:<br>m₁·(−4) = (m₁ + m₂)·v′ → 0,25·(−4) = (0,25 + 0,75)·v′ → −1 = 1·v′ → <b>v′ = −1 m/s</b>. ▸ Los dos cuerpos van pegados: la respuesta de a) es <b>la misma velocidad para ambos</b>, 1 m/s en el sentido en que venía el péndulo. <br><br><b>Etapa 3 · subida (energía otra vez).</b> Sin rozamiento y con la tensión que sigue sin trabajar:<br>½·(m₁+m₂)·v′² = (m₁+m₂)·g·h → ½·1² = 10·h → <b>h = 0,05 m = 5 cm</b>. La masa vuelve a cancelarse. <div class="trap"><div class="tr-t">Control de resultado: 80 cm de caída, 5 cm de subida</div>El conjunto sube <b>5 cm</b> después de haber caído <b>80 cm</b>. No es un error: es la firma del choque plástico. La energía cinética después del choque es E′ = ½·1·1² = 0,5 J contra los 2 J que traía el péndulo (½·0,25·16): <b>quedó solo la cuarta parte</b>. ▸ El error clásico acá es plantear m₁gL = (m₁+m₂)gh de un tirón, saltándose el choque: daría h = 20 cm, cuatro veces de más. ▸ Segundo cuidado: <b>m₂ = 3·m₁ = 0,75 kg</b>, no 3 kg — con 3 kg la masa total no daría el 1 kg redondo que hace salir los números.</div>'},

  {st: '<b>3 · 2do parcial 2010 · A1 · UTN FRBA, 30/11/2010.</b> Enunciado verbatim: «A1: Sobre una pista como indica la figura se deja caer un cuerpo A, al llegar a la parte horizontal choca plásticamente con otro B, el cual estaba en reposo. Después de la interacción la pista presenta una zona horizontal con rozamiento y un plano inclinado sin rozamiento. Considerando ambos cuerpos puntuales: a) Calcule la velocidad de los cuerpos después del choque y el impulso recibido por A, expréselos en forma vectorial. b) Determine donde se detienen los cuerpos después del choque. Datos: d=50 cm, h=80cm, μD=0,5, mA=1kg, mB=3kg,»',
   ans: 'a) v⃗₃ = 1 m/s î (con î hacia la izquierda, el sentido en que se mueve A) ▸ ΔP⃗_A = −3 kg·m/s î, o sea 3 N·s en sentido opuesto al movimiento de A. b) Se detienen DENTRO de la zona rugosa, a 10 cm de su entrada (a 40 cm del pie del plano inclinado): nunca suben por el plano.',
   sol: '<b>Hipótesis y referencia.</b> Cuerpos puntuales, cero de energía potencial en la superficie plana, eje x positivo <b>hacia la izquierda</b> (el sentido en que se mueve A). g = 10 m/s². Definimos cuatro puntos: <b>1</b> = A se suelta a altura h con velocidad nula, <b>2</b> = A justo antes del choque, <b>3</b> = ambos justo después, <b>4</b> = posición final en reposo. <br><br><b>a) Etapa 1 · tramo 1→2 (curva sin rozamiento).</b> Se conserva la energía mecánica:<br>m<sub>A</sub>·g·h = ½·m<sub>A</sub>·v<sub>A2</sub>² → v<sub>A2</sub> = √(2gh) = √(2·10·0,8) = <b>4 m/s</b>. <br><br><b>Etapa 2 · el choque plástico.</b> Se conserva la componente x de p (fuerzas impulsivas internas):<br>m<sub>A</sub>·v<sub>A2</sub> = (m<sub>A</sub> + m<sub>B</sub>)·v₃ → 1·4 = 4·v₃ → <b>v₃ = 1 m/s</b> ⇒ <b>v⃗₃ = 1 m/s î</b>, los dos juntos hacia el plano inclinado. <br><br><b>El impulso sobre A</b> (¡sobre A, no sobre el sistema!):<br>ΔP<sub>Ax</sub> = m<sub>A</sub>·v₃ − m<sub>A</sub>·v<sub>A2</sub> = 1·1 − 1·4 = <b>−3 kg·m/s</b> ⇒ <b>ΔP⃗<sub>A</sub> = −3 kg·m/s î</b>: módulo 3 N·s, <b>opuesto</b> al movimiento de A, porque el choque lo frenó. <br><br><b>b) Etapa 3 · ¿llegan al plano?</b> Energía al entrar al tramo rugoso: E₃ = ½·4·1² = <b>2 J</b>. Trabajo que le sacaría el roce en el tramo <b>completo</b>: |W| = μ<sub>D</sub>·(m<sub>A</sub>+m<sub>B</sub>)·g·d = 0,5·4·10·0,5 = <b>10 J</b>. ▸ Como <b>2 J &lt; 10 J, no atraviesan</b>: se detienen adentro. ▸ La distancia real d′:<br>0 − 2 J = −μ<sub>D</sub>·(m<sub>A</sub>+m<sub>B</sub>)·g·d′ → 2 = 0,5·4·10·d′ → <b>d′ = 0,1 m = 10 cm</b>. ▸ Se detienen definitivamente a <b>10 cm de la entrada</b> de la zona rugosa, o sea a 40 cm del pie del plano, y ahí se quedan: no hay resorte ni pendiente que los devuelva. <div class="trap"><div class="tr-t">Cuatro trampas en un solo ejercicio</div><b>1 · Verificar antes de calcular.</b> Si suponés sin chequear que llegan al plano inclinado, la ecuación te devuelve una altura negativa o una raíz de número negativo. La comparación 2 J contra 10 J es un renglón y decide todo el inciso b. ▸ <b>2 · El ángulo de 37° no se usa.</b> Es un dato deliberado que "no interesa", igual que el propio plano inclinado. ▸ <b>3 · El impulso da negativo</b> y hay que expresarlo <b>vectorialmente</b>: poner "+3 kg·m/s" pierde el punto. ▸ <b>4 ·</b> En el rozamiento la normal es <b>(m<sub>A</sub>+m<sub>B</sub>)·g = 40 N</b>, no el peso de A solo.</div>'},

  {st: '<b>4 · 2do parcial 2011 · A2 · Prof. Patricia Martinelli, UTN FRBA, 24/11/2011.</b> Enunciado verbatim: «A2: Un bloque de masa m=2kg, es lanzado por la pista de la figura mediante un resorte ideal de constante elástica K=800N/m, que inicialmente se encuentra comprimido 50cm. Luego, este bloque choca plásticamente con un segundo bloque, de igual masa, que inicialmente se encontraba en reposo, y finalmente ambos ascienden por el plano inclinado. Las superficies carecen de rozamiento, salvo en el tramo horizontal de longitud d=0.5m, que presenta un coeficiente de rozamiento dinámico µd=0.5. El plano inclinado forma un ángulo de 70° con la horizontal. a) Determine la velocidad de los bloques justo después del choque. b) Calcule hasta que altura máxima h ascenderán sobre el plano inclinado.»',
   ans: 'a) v_C = 5 m/s (los dos bloques juntos, hacia el plano inclinado). b) h = 1 m de altura vertical (la distancia recorrida sobre el plano sería h/sen70° = 1,06 m).',
   sol: '<b>Referencia.</b> Nivel cero de energía potencial en la superficie horizontal, g = 10 m/s². Recorrido: resorte → tramo liso → <b>choque</b> → tramo rugoso d → plano inclinado liso. <br><br><b>a) Etapa 1 · del resorte al choque (energía).</b> Superficie lisa: la normal no trabaja, y peso y fuerza elástica son conservativas ⇒ se conserva la energía mecánica.<br>½·K·Δx² = ½·m₁·v₁²<br>½·800·(0,5)² = <b>100 J</b> = ½·2·v₁² → v₁² = 100 → <b>v₁ = 10 m/s</b>. <br><br><b>Etapa 2 · el choque plástico.</b> No se conserva la energía; sí la cantidad de movimiento:<br>m₁·v₁ = (m₁ + m₂)·v<sub>C</sub> → v<sub>C</sub> = (2/4)·10 = <b>5 m/s</b>. ▸ Control: de los 100 J iniciales quedan ½·4·25 = <b>50 J</b>. Se perdió la mitad, exactamente lo que corresponde a un plástico entre masas iguales. <br><br><b>b) Etapa 3 · del choque a la altura máxima.</b> Ahora la masa es 2m = <b>4 kg</b>. En el tramo rugoso de largo d el rozamiento resta:<br>|W<sub>roz</sub>| = μ<sub>d</sub>·(2m)·g·d = 0,5·4·10·0,5 = <b>10 J</b>.<br>Y en el punto más alto la velocidad es cero, así que toda la energía que sobra es potencial:<br>(2m)·g·h = ½·(2m)·v<sub>C</sub>² − 10 J<br>4·10·h = 50 − 10 = 40 J → <b>h = 1 m</b>. <div class="trap"><div class="tr-t">Dónde se pierde este ejercicio</div><b>1 · El orden de los tramos.</b> El rugoso está <b>después</b> del choque (entre el bloque 2 y el plano). Si aplicás el rozamiento antes del choque, la masa que frena es 2 kg en vez de 4 kg y todo el resultado cambia. Leé la figura antes de escribir. ▸ <b>2 · La masa en el roce es 4 kg</b>: N = (2m)·g = 40 N. Usar 2 kg da |W| = 5 J y h = 1,125 m. ▸ <b>3 · El ángulo de 70° NO se usa</b> para la altura: es un dato que no interesa. Solo haría falta si pidieran la distancia recorrida sobre el plano (1 m / sen70° = 1,06 m) o el tiempo. ▸ <b>4 ·</b> El plano inclinado es <b>liso</b>: el rozamiento existe únicamente en el tramo horizontal d, y se recorre una sola vez.</div>'},

  {st: '<b>5 · 2do parcial 2013 · A1 · Curso O1122, Prof. Patricia Martinelli, UTN FRBA, 26/11/2013.</b> Enunciado verbatim: «A1: Dos carritos de masas M1=2kg y M2=3kg están engarzados en un riel que posee un desnivel de altura H=0.5m, como de muestra en la figura. Hasta el punto A, el riel carece de rozamiento. A partir de este punto comienza una zona horizontal, cuyos coeficientes de rozamiento estático y dinámico son μe=0.6 y μd=0.5. Inicialmente, el carrito 1 se mueve hacia la derecha con velocidad v0=2m/s y el carrito 2 está en reposo. En determinado instante, el carro 1 choca plásticamente contra el carro 2, y luego ambos descienden por el riel hasta detenerse en el punto B, situado a una distancia D del punto A. a) Determine las velocidades de ambos carritos justo después del choque. b) Determine con qué velocidad llegan al punto A, y calcule D.»',
   ans: 'a) Los dos carritos quedan unidos: v_f = 0,8 m/s hacia la derecha (la misma para ambos). b) V_A = 3,26 m/s ▸ D = 1,064 m.',
   sol: '<b>Referencia.</b> Eje x hacia la derecha, cero de energía potencial en el nivel inferior del riel, g = 10 m/s². <br><br><b>a) El choque (cantidad de movimiento).</b> Ocurre en el tramo alto, que es liso:<br>M₁·v₀ + M₂·0 = (M₁ + M₂)·v<sub>f</sub> → 2·2 = 5·v<sub>f</sub> → <b>v<sub>f</sub> = 0,8 m/s</b>. ▸ La respuesta correcta al inciso es "<b>ambos con la misma velocidad</b>, 0,8 m/s hacia la derecha": quedaron unidos. <br><br><b>b) Del choque al punto A (energía).</b> Ese tramo es liso, así que se conserva la energía mecánica y el desnivel H se usa entero:<br>½·(M₁+M₂)·v<sub>f</sub>² + (M₁+M₂)·g·H = ½·(M₁+M₂)·V<sub>A</sub><sup>2</sup><br>V<sub>A</sub>² = v<sub>f</sub>² + 2·g·H = 0,64 + 2·10·0,5 = <b>10,64 m²/s²</b> → <b>V<sub>A</sub> = 3,26 m/s</b>. <br><br><b>De A a B (teorema del trabajo y la energía).</b> Recién acá aparece el rozamiento, y en B la velocidad es cero:<br>0 − ½·(M₁+M₂)·V<sub>A</sub>² = −μ<sub>d</sub>·(M₁+M₂)·g·D<br>D = V<sub>A</sub>²/(2·μ<sub>d</sub>·g) = 10,64/(2·0,5·10) = <b>1,064 m</b>. ▸ Fijate que la masa total se cancela: D no depende de cuánto pesen los carritos. <div class="trap"><div class="tr-t">Los cuatro detalles del enunciado</div><b>1 ·</b> En a) hay que contestar <b>las dos</b> velocidades: son iguales porque el choque es plástico. Muchos escriben una sola y pierden medio inciso. ▸ <b>2 · μ<sub>e</sub> = 0,6 no se usa</b>: los carritos están deslizando, va el dinámico. Distractor deliberado. ▸ <b>3 ·</b> El rozamiento arranca <b>recién en A</b>: el descenso es conservativo y H entra completo. No hay que mezclar el trabajo del roce con la bajada, son dos tramos distintos. ▸ <b>4 ·</b> No confundir "descienden hasta detenerse en B" con que se frenen en la bajada: en la bajada <b>aceleran</b> (de 0,8 a 3,26 m/s) y frenan después, sobre el horizontal rugoso.</div>'},

  {st: '<b>6 · 2do parcial 2012 · A1 · Curso Z1022, Prof. Patricia Martinelli, UTN FRBA, 29/11/2012.</b> Enunciado verbatim: «A1: Dos carritos de masas M1=3kg y M2=2kg se encuentran sobre una superficie horizontal, como se muestra en la figura. La superficie carece de rozamiento, salvo entre los puntos A y B, los cuales están separados una distancia D=4.75m. Los coeficientes de rozamiento estático y dinámico en ese tramo son µe=0.3 y µd=0.2, respectivamente. Inicialmente, el carrito 1 se mueve hacia la derecha con velocidad de módulo v0=10m/s y el carrito 2 está en reposo. Luego de atravesar la zona A-B, el carro 1 choca plásticamente contra el carro 2. a) Determine la velocidad del carrito 1 al pasar por el punto B. b) Calcule la velocidad de ambos luego del choque.»',
   ans: 'a) v_B = 9 m/s hacia la derecha. b) v_f = 5,4 m/s hacia la derecha, los dos carritos unidos.',
   sol: 'Este es el ejercicio que tiene la zona rugosa <b>antes</b> del choque, y por eso es el más simple de los ocho: la etapa 3 no existe. <br><br><b>a) Etapa 1 · el tramo A-B (teorema del trabajo y la energía).</b> La única fuerza que hace trabajo es el rozamiento dinámico (N y P son perpendiculares al desplazamiento), y la masa que frena es <b>solo la del carrito 1</b>:<br>½·M₁·v<sub>B</sub>² − ½·M₁·v₀² = −μ<sub>d</sub>·M₁·g·D<br>v<sub>B</sub>² = v₀² − 2·μ<sub>d</sub>·g·D = 100 − 2·0,2·10·4,75 = 100 − 19 = <b>81 m²/s²</b> → <b>v<sub>B</sub> = 9 m/s</b>. ▸ La masa M₁ se cancela: el frenado no depende de cuánto pese el carrito. <br><br><b>b) Etapa 2 · el choque plástico.</b> Fuera del tramo A-B la superficie es lisa, así que el carrito 1 llega al choque todavía con 9 m/s (no hay más frenado). Durante el choque no se conserva la energía, pero sí la cantidad de movimiento:<br>M₁·v<sub>B</sub> + M₂·0 = (M₁ + M₂)·v<sub>f</sub><br>v<sub>f</sub> = (3·9)/5 = <b>5,4 m/s</b> hacia la derecha, ambos carritos unidos. <div class="trap"><div class="tr-t">Por qué acá la masa del roce es 3 kg y no 5 kg</div>Porque el tramo rugoso está <b>antes</b> del choque: el carrito 2 nunca lo pisa, está en reposo del otro lado de B. Es el espejo exacto del A2 2011, donde el rugoso está después y hay que usar la masa total. <b>Mirá la figura antes de decidir qué masa va en la normal.</b> ▸ Otros dos detalles: μ<sub>e</sub> = 0,3 es un distractor (el carrito ya desliza), y en el choque no se puede plantear ½M₁v<sub>B</sub>² = ½(M₁+M₂)v<sub>f</sub>², que daría 6,97 m/s en vez de 5,4 m/s. ▸ Control de que la cátedra usa g = 10: 100 − 19 = 81 da raíz exacta 9. Con g = 9,8 daría v<sub>B</sub> ≈ 9,10 m/s.</div>'},

  {st: '<b>7 · 2do parcial 2015 · A1 · Curso Z1102, Prof. Patricia Martinelli, UTN FRBA, 25/11/2015.</b> Enunciado verbatim: «A1: Dos bloques de igual masa, M1=M2=2kg, se encuentran sobre una superficie horizontal que carece de rozamiento, salvo en la zona indicada en color gris. Esta zona comienza 1.5m antes de la pared, y tiene coeficientes de rozamiento estático y dinámico μe=0.3 y μd=0.25, respectivamente. Inicialmente, el bloque 1 se mueve hacia la derecha con velocidad v0 y el bloque 2 está en reposo. En determinado instante ambos bloques chocan plásticamente, y finalmente van a comprimir al resorte ideal, de longitud natural l0=50cm y constante elástica k=200N/m. Determine v0, sabiendo que la compresión máxima del resorte es Δlmax=20cm.»',
   ans: 'v₀ = 5,66 m/s (exactamente 4√2 m/s). Paso intermedio: v_A = 2,83 m/s (= 2√2) justo después del choque.',
   sol: 'Es el mismo esqueleto de siempre, pero recorrido <b>al revés</b>: la incógnita está al principio y el dato al final. Se plantea igual y se despeja último. <br><br><b>Puntos:</b> A = entrada de la zona gris, B = máxima compresión del resorte. Eje x hacia la derecha, g = 10 m/s². <br><br><b>Paso 1 · la geometría (esto es lo que hace difícil el ejercicio).</b> La zona gris mide 1,5 m, pero el bloque <b>no</b> la recorre entera: se frena antes, al comprimir el resorte. La distancia realmente recorrida con rozamiento es<br><b>D<sub>AB</sub> = 1,5 − l₀ + Δl<sub>máx</sub> = 1,5 − 0,5 + 0,2 = 1,2 m</b>. <br><br><b>Paso 2 · el choque.</b> Ocurre en la zona lisa, y las masas son iguales:<br>M₁·v₀ = (M₁ + M₂)·v<sub>A</sub> → <b>v₀ = 2·v<sub>A</sub></b>. ▸ Como entre el choque y el punto A no hay rozamiento, la velocidad no cambia: la velocidad justo después del choque es la misma con la que entra a la zona gris. <br><br><b>Paso 3 · tramo A→B (energía con rozamiento y resorte).</b> En B la velocidad es cero pero hay energía elástica acumulada:<br>ΔE<sub>AB</sub> = E<sub>B</sub> − E<sub>A</sub> = W<sub>roz</sub><br>½·k·Δl<sub>máx</sub>² − ½·(M₁+M₂)·v<sub>A</sub>² = −μ<sub>d</sub>·(M₁+M₂)·g·D<sub>AB</sub><br>½·200·0,04 − ½·4·v<sub>A</sub>² = −0,25·40·1,2<br>4 − 2·v<sub>A</sub>² = −12 → 2·v<sub>A</sub>² = 16 → v<sub>A</sub>² = 8 → <b>v<sub>A</sub> = 2,83 m/s</b>. <br><br><b>Paso 4 · volver al principio.</b> v₀ = 2·2,83 = <b>5,66 m/s</b> (4√2 m/s). <div class="trap"><div class="tr-t">Siete formas de perder este ejercicio (es el más difícil de los ocho)</div><b>1 · La distancia NO es 1,5 m.</b> Hay que descontar la longitud natural del resorte y sumar la compresión. Es el error más frecuente. ▸ <b>2 ·</b> Va μ<sub>d</sub> = 0,25; μ<sub>e</sub> = 0,3 es distractor. ▸ <b>3 ·</b> No se puede plantear energía desde el inicio hasta B de un tirón: en el medio hay un choque plástico. ▸ <b>4 ·</b> La normal es (M₁+M₂)·g = <b>40 N</b>. ▸ <b>5 ·</b> En B la velocidad es cero pero la <b>energía no</b>: hay ½kΔl² = 4 J guardados en el resorte. ▸ <b>6 ·</b> El trabajo del rozamiento es <b>negativo</b>. ▸ <b>7 ·</b> Δl = 20 cm = 0,2 m y l₀ = 50 cm = 0,5 m: pasá todo a metros antes de operar.</div>'},

  {st: '<b>8 · 2do parcial 2016 · A1 · Curso R1022, Prof. Patricia Martinelli, UTN.BA, 14/11/2016.</b> Enunciado verbatim: «A1: Un bloque de madera de masa M=950g se halla en reposo, unido a un resorte ideal, cuyo otro extremo está sujeto a una pared como se muestra en la figura. La superficie horizontal sobre la cual se encuentra apoyado el bloque tiene coeficientes de rozamiento estático y dinámico, μe=0.3 y μd=0.2, respectivamente. En determinado instante, se dispara sobre el bloque un proyectil de masa m=50g, con velocidad v0=100m/s, que queda incrustado en el bloque, y luego de esto, el resorte sufre una compresión máxima Δl=25cm. a) Calcule la velocidad del conjunto bloque + proyectil justo después del choque. b) Determine el valor de la constante elástica del resorte, K, utilizando conceptos de trabajo y energía.» <span class="muted">(este parcial se distribuyó sin la solución oficial: la resolución de abajo está verificada con g = 10 m/s², la convención de la cátedra)</span>',
   ans: 'a) v = 5 m/s hacia la derecha. b) K = 384 N/m.',
   sol: '<b>Datos en SI:</b> M = 0,95 kg, m = 0,05 kg, v₀ = 100 m/s, Δl = 0,25 m, μ<sub>d</sub> = 0,2, g = 10 m/s². Eje x positivo hacia la derecha (sentido del proyectil). <br><br><b>a) El choque plástico.</b> El choque es instantáneo, así que durante el impacto el impulso del rozamiento y el del resorte son despreciables frente al impulso interno ⇒ se conserva la cantidad de movimiento del sistema proyectil+bloque:<br>m·v₀ = (M + m)·v<br>0,05·100 = 1,00·v → <b>v = 5 m/s</b>. ▸ Fijate que la masa total da exactamente <b>1,00 kg</b>: la cátedra elige los números para eso. <br><br><b>Cuánta energía se fue:</b> E<sub>i</sub> = ½·0,05·100² = <b>250 J</b>; E<sub>f</sub> = ½·1,00·5² = <b>12,5 J</b>. Se disiparon <b>237,5 J, el 95%</b>. Ese solo número explica por qué no se puede usar energía en el choque. <br><br><b>b) Del choque a la máxima compresión (trabajo y energía).</b> Entre el instante justo posterior al choque (resorte en su longitud natural, v = 5 m/s) y el de máxima compresión (v = 0, Δl = 0,25 m). El resorte es conservativo; el rozamiento dinámico es la única fuerza no conservativa que trabaja, con N = (M+m)·g:<br>ΔE<sub>mec</sub> = W<sub>roz</sub><br>½·K·Δl² − ½·(M+m)·v² = −μ<sub>d</sub>·(M+m)·g·Δl<br>½·K·(0,25)² = ½·1,00·25 − 0,2·1,00·10·0,25<br>0,03125·K = 12,5 − 0,5 = <b>12,0 J</b> → <b>K = 384 N/m</b>. <div class="trap"><div class="tr-t">El dato de más y el detalle de la distancia</div>Acá el <b>μ<sub>e</sub> = 0,3 es el distractor</b>. Se puede verificar que no interviene: en la máxima compresión la fuerza elástica vale F = K·Δl = 384·0,25 = <b>96 N</b>, mientras que el rozamiento estático máximo es μ<sub>e</sub>·(M+m)·g = 0,3·1·10 = <b>3 N</b>. Como 96 N ≫ 3 N, el conjunto no queda pegado ahí: rebota. ▸ <b>Otros errores:</b> usar M = 0,95 kg en vez de (M+m) = 1,00 kg en la etapa de energía; olvidar el trabajo del roce (daría K = 400 N/m); sumarlo en vez de restarlo; y confundir Δl = 25 cm (la <b>compresión</b>) con una longitud del resorte. ▸ La distancia sobre la que actúa el roce es justamente Δl, porque el bloque arranca con el resorte en longitud natural.</div>'}
]);

// ============================================================
// SECCIÓN 3 · CHOQUE ELÁSTICO Y COEFICIENTE DE RESTITUCIÓN
// ============================================================
registerExercises('fisica1-utn-choques', '3', [
  {st: 'Choque elástico frontal entre dos cuerpos de IGUAL masa, con el segundo inicialmente en reposo. ¿Qué pasa?',
   opts: ['Quedan pegados y siguen a v/2', 'Intercambian velocidades: el que venía queda quieto y el otro sale con v', 'Los dos salen a v/2', 'El que venía rebota con −v'],
   c: 1,
   ex: 'Con m₁ = m₂ las fórmulas dan v′₁ = [(m₁−m₂)/(m₁+m₂)]·v = <b>0</b> y v′₂ = [2m₁/(m₁+m₂)]·v = <b>v</b>: <b>intercambian velocidades</b>. Es el choque de bolas de billar. ▸ Control: se conservan p (m·v = m·v) y E<sub>c</sub> (½mv² = ½mv²). ▸ Por qué las otras: (A) es el choque <b>plástico</b> entre masas iguales, donde se pierde la mitad de la energía; (C) no conserva la energía (½m(v/2)²·2 = ¼mv²); (D) solo pasaría contra una masa enormemente mayor.'},

  {st: '¿Cuánto vale el coeficiente de restitución e en un choque perfectamente plástico?',
   opts: ['e = 1', 'e = 0,5', 'e = 0', 'e > 1'],
   c: 2,
   ex: 'e = (rapidez de separación)/(rapidez de acercamiento). En el plástico los cuerpos <b>quedan pegados</b>: se separan a rapidez cero, así que <b>e = 0</b>, y ahí la pérdida de energía es la <b>máxima posible</b> compatible con conservar p. ▸ Por qué las otras: (A) e = 1 es el elástico (energía cinética conservada); (B) e = 0,5 sería un inelástico parcial; (D) e &gt; 1 significaría que sale más energía de la que entró — solo pasa en una explosión, donde la energía la aporta un resorte o una carga.'},

  {st: 'Una bala de 10 g choca ELÁSTICAMENTE contra la masa de 10 kg de un péndulo en reposo. ¿Qué pasa con la bala y con el péndulo?',
   opts: ['La bala queda incrustada y el conjunto sale lento', 'La bala rebota con casi la misma rapidez y el péndulo sale muy lento', 'La bala sigue de largo con la misma velocidad y el péndulo queda quieto', 'Los dos salen con la mitad de la velocidad inicial'],
   c: 1,
   ex: 'Con m₁ ≪ m₂: v′₁ = [(m₁−m₂)/(m₁+m₂)]·v ≈ <b>−v</b> (rebota casi con la misma rapidez, para atrás) y v′₂ = [2m₁/(m₁+m₂)]·v ≈ <b>2·(m₁/m₂)·v</b>, chiquita. ▸ Con m₁ = 0,01 kg y m₂ = 10 kg: v′₂ ≈ 0,002·v. Es la pelotita contra la pared. ▸ Por qué las otras: (A) es plástico, no elástico — la palabra "elástico" prohíbe que queden pegados; (C) sería si no hubiera choque; (D) no conserva ni p ni energía.'},

  {st: 'Un bloque de 6 kg a 3 m/s choca con uno de 12 kg en reposo. Después, el de 6 kg retrocede a 1 m/s. ¿Qué tipo de choque fue?',
   opts: ['Plástico', 'Elástico (podés verificarlo con las energías)', 'Inelástico parcial, e ≈ 0,5', 'Faltan datos para saberlo'],
   c: 1,
   ex: 'Primero sacás v′₂ con cantidad de movimiento: 6·3 = 6·(−1) + 12·v′₂ → v′₂ = <b>2 m/s</b>. ▸ Después comparás energías: E<sub>i</sub> = ½·6·9 = <b>27 J</b> y E<sub>f</sub> = ½·6·1 + ½·12·4 = 3 + 24 = <b>27 J</b>. Iguales ⇒ <b>elástico</b>, aunque el enunciado nunca usa la palabra. ▸ Verificación por e: e = (2 − (−1))/(3 − 0) = 3/3 = 1. ▸ Por qué las otras: (A) en plástico saldrían juntos; (D) los datos alcanzan y de sobra — es justamente el control que hay que saber hacer.'},

  {st: 'El enunciado dice que el proyectil "no queda adherido" al péndulo. ¿Podés usar conservación de la energía cinética en el choque?',
   opts: ['Sí: si no queda pegado, es elástico', 'No: la única palabra que lo habilita es "elástico"; acá la segunda ecuación la tiene que dar otro dato', 'Sí, pero solo la mitad de la energía', 'No, y tampoco se conserva la cantidad de movimiento'],
   c: 1,
   ex: '"No queda adherido" solo dice que <b>no es plástico</b>: puede ser cualquier e entre 0 y 1. ▸ En el final del 12/12/23 el proyectil rebota y aun así se pierden 12,2 de los 16 J (e ≈ 0,47). ▸ La segunda ecuación te la da otro dato del enunciado: la amplitud angular del péndulo después del choque, que por energía te devuelve la velocidad de la masa. ▸ Por qué las otras: (D) la cantidad de movimiento <b>siempre</b> se conserva en el choque, sea del tipo que sea.'}
]);

registerReveals('fisica1-utn-choques', '3', [

  {st: '<b>Final UTN.BA (hoja sin fecha visible, tipografía LaTeX) · Problema 3.</b> Enunciado verbatim: «Un bloque de masa m1 = 6 kg desliza por una superficie horizontal sin rozamiento con una velocidad v0 = 3 m/s. En cierto instante choca con otro bloque de masa m2 = 12 kg que está unido a un resorte de constante elástica k = 300 N/m, el cual posee, en el instante del choque, su longitud natural y su otro extremo está fijo a una pared. Después del choque el bloque de masa m1 retrocede con una velocidad de módulo 1 m/s. Calcule la amplitud de las oscilaciones que realiza el cuerpo m2 después del choque.»',
   ans: 'A = 0,4 m = 40 cm. (Bonus verificable: el choque resulta ser elástico, e = 1, y v′₂ = 2 m/s.)',
   sol: '<b>Referencia.</b> Eje x en el sentido de v₀. Superficie lisa: no hay rozamiento en ningún tramo, así que después del choque la energía cinética de m₂ se transforma íntegramente en energía elástica. <br><br><b>Paso 1 · el choque (cantidad de movimiento).</b> El enunciado no dice de qué tipo es, pero <b>no hace falta saberlo</b>: da una velocidad final, y con eso alcanza.<br>m₁·v₀ = m₁·v′₁ + m₂·v′₂<br>6·3 = 6·(−1) + 12·v′₂ &nbsp;<span class="muted">(retrocede ⇒ signo negativo)</span><br>18 + 6 = 12·v′₂ → <b>v′₂ = 2 m/s</b>. <br><br><b>Paso 2 · la amplitud (energía).</b> En el instante del choque el resorte está en su <b>longitud natural</b>, así que m₂ arranca en la posición de equilibrio con toda su energía en forma cinética. La amplitud es la elongación donde la velocidad se anula:<br>½·m₂·v′₂² = ½·k·A²<br>½·12·2² = ½·300·A² → 24 = 150·A² → A² = 0,16 → <b>A = 0,4 m = 40 cm</b>. <br><br><b>Paso 3 · el control que conviene hacer (y que a veces piden).</b> ¿Fue elástico? E<sub>i</sub> = ½·6·3² = <b>27 J</b>; E<sub>f</sub> = ½·6·1² + ½·12·2² = 3 + 24 = <b>27 J</b>. Iguales ⇒ <b>choque elástico</b>. También se puede verificar con el coeficiente de restitución: e = (v′₂ − v′₁)/(v₀ − 0) = (2 + 1)/3 = <b>1</b>. <div class="trap"><div class="tr-t">El signo del retroceso y qué es la amplitud</div><b>1 · "Retrocede" significa v′₁ = −1 m/s.</b> Si lo ponés positivo, la ecuación da 6·3 = 6·1 + 12·v′₂ → v′₂ = 1 m/s, y la amplitud sale 0,2 m: la mitad. Es el error que decide el ejercicio. ▸ <b>2 ·</b> La <b>amplitud</b> es la máxima separación respecto del <b>equilibrio</b>, y el equilibrio acá es la longitud natural del resorte (superficie horizontal, sin peso que corra el punto de equilibrio). Por eso toda la cinética se convierte en elástica sin restar nada. ▸ <b>3 ·</b> Como no hay rozamiento, el bloque oscila indefinidamente con esa amplitud: no hay que descontar ningún trabajo.</div>'},

  {st: '<b>Final UTN.BA · 12/12/23 · Problema 3.</b> Enunciado verbatim: «Un proyectil de masa m₁ = 0,5 kg con una velocidad de modulo v₀ = 8 m/s impacta horizontalmente en un péndulo ideal de masa m₂ = 20 kg y longitud l = 3 m, que se encuentra inicialmente en reposo en su posición de equilibrio. Después del choque el proyectil no queda adherido a la masa del péndulo y este realiza oscilaciones con una amplitud angular de 3°. Calcule la perdida de energía en el choque.»',
   ans: 'ΔE ≈ −12,2 J (de los 16 J iniciales quedan 3,8 J). El proyectil REBOTA: sale a 3,47 m/s hacia atrás, y el péndulo arranca con 0,287 m/s. Coeficiente de restitución e ≈ 0,47.',
   sol: 'Acá el orden es <b>al revés</b>: el dato del final (la amplitud angular) es el que abre el problema. <br><br><b>Paso 1 · qué velocidad tenía el péndulo justo después del choque (energía, hacia atrás).</b> El péndulo sube hasta 3° y ahí se detiene. La altura ganada es<br>h = l·(1 − cos α) = 3·(1 − cos3°) = 3·(1 − 0,99863) = <b>4,11·10⁻³ m</b><br>y por conservación de la energía en el péndulo (la tensión no trabaja):<br>½·m₂·v′₂² = m₂·g·h → v′₂ = √(2·10·4,11·10⁻³) = <b>0,287 m/s</b>. <br><br><b>Paso 2 · el choque (cantidad de movimiento).</b> Eje x en el sentido del proyectil:<br>m₁·v₀ = m₁·v′₁ + m₂·v′₂<br>0,5·8 = 0,5·v′₁ + 20·0,287<br>4 = 0,5·v′₁ + 5,735 → v′₁ = (4 − 5,735)/0,5 = <b>−3,47 m/s</b>. ▸ El signo negativo dice que el proyectil <b>rebota</b>: sale para atrás a 3,47 m/s. Tiene sentido físico — es un cuerpo liviano contra uno 40 veces más pesado. <br><br><b>Paso 3 · la pérdida de energía (restar cinéticas).</b><br>E<sub>c,antes</sub> = ½·0,5·8² = <b>16 J</b><br>E<sub>c,después</sub> = ½·0,5·3,47² + ½·20·0,287² = 3,01 + 0,82 = <b>3,83 J</b><br>ΔE = 3,83 − 16 = <b>−12,2 J</b>: se perdieron 12,2 J, el 76% de la energía inicial. <br><br><b>Control de coherencia.</b> Coeficiente de restitución: e = (v′₂ − v′₁)/(v₀ − 0) = (0,287 + 3,47)/8 = <b>0,47</b>. Está entre 0 y 1, como corresponde a un inelástico parcial. Si el choque hubiera sido plástico, v′ sería 4/20,5 = 0,195 m/s; si hubiera sido elástico, v′₂ = 2·0,5·8/20,5 = 0,39 m/s. El 0,287 obtenido cae <b>entre</b> los dos: el resultado es consistente. <div class="trap"><div class="tr-t">3° es un ángulo chiquito, pero no se puede aproximar de cualquier manera</div><b>1 ·</b> La altura es <b>l·(1 − cos α)</b>, no l·sen α ni l·α. Con α = 3° la diferencia es brutal: l·(1−cos3°) = 0,0041 m contra l·sen3° = 0,157 m, cuarenta veces más. ▸ <b>2 ·</b> Poné la calculadora en <b>grados</b>: en radianes, cos(3) = −0,99 y todo el ejercicio se rompe. ▸ <b>3 · No es un choque plástico</b> aunque lo parezca por la escena: el enunciado dice "no queda adherido", así que hay dos velocidades finales y hay que despejar la del proyectil. ▸ <b>4 ·</b> La pérdida se calcula restando <b>solo energías cinéticas</b> en los dos instantes del choque; la potencial no entra porque el choque es instantáneo y nadie cambió de altura todavía.</div>'},

  {st: '<b>Final UTN.BA · 13/02/25 · Problema 3</b>, según la <b>recreación de memoria hecha por alumnos</b>. Enunciado verbatim de esa recreación: «Una bala de 0, 01 kg de masa con una velocidad horizontal de módulo v, impacta un péndulo ideal de 10 kg de masa y 2, 5 m de longitud, que se encuentra inicialmente en reposo en su posición de equilibrio. hay un choque elástico. pide las amplitud de oscilaciones (no recuerdo que datos daba) […] Pide hallar, la cantidad de oscilaciones que tuvo el péndulo luego del choque.» <span class="muted">(dato reconstruido: la fuente declara que NO recuerda el valor de v. Abajo se resuelve simbólicamente y después con v = 400 m/s como valor de trabajo, para que veas el mecanismo.)</span>',
   ans: 'Simbólico: v′_péndulo = 2m·v/(m+M) = 1,998·10⁻³·v ▸ amplitud A = v′/ω con ω = √(g/l) = 2 rad/s ▸ T = π ≈ 3,14 s y f = 0,318 Hz. Con v = 400 m/s: v′ = 0,799 m/s, A = 0,40 m (amplitud angular 9,2°), T = 3,14 s. La "cantidad de oscilaciones" solo tiene respuesta finita si el enunciado da un intervalo de tiempo: un péndulo ideal sin rozamiento oscila indefinidamente.',
   sol: 'Este es el único choque <b>declarado elástico</b> de todo el material relevado, y encima engancha con oscilaciones. Vale la pena aunque el enunciado esté incompleto en la fuente. <br><br><b>Paso 1 · el choque elástico (dos ecuaciones, o la fórmula directa).</b> Con m = 0,01 kg (bala), M = 10 kg (péndulo, en reposo):<br>v′<sub>M</sub> = <b>2m/(m+M) · v</b> = 2·0,01/10,01 · v = 1,998·10⁻³·v<br>v′<sub>m</sub> = <b>(m−M)/(m+M) · v</b> = −0,998·v ▸ la bala <b>rebota casi con la misma rapidez</b>, como corresponde a m ≪ M. ▸ Con v = 400 m/s: <b>v′<sub>M</sub> = 0,799 m/s</b> y v′<sub>m</sub> = −399,2 m/s. <br><br><b>Paso 2 · el péndulo como oscilador armónico.</b> Para amplitudes chicas, el péndulo ideal es un MAS con<br>ω = √(g/l) = √(10/2,5) = <b>2 rad/s</b>&nbsp;·&nbsp;T = 2π/ω = <b>π ≈ 3,14 s</b>&nbsp;·&nbsp;f = 1/T = <b>0,318 Hz</b>. ▸ Fijate que ω, T y f <b>no dependen de la velocidad de la bala ni de la masa</b>: solo de l y g. <br><br><b>Paso 3 · la amplitud.</b> El péndulo arranca en el equilibrio con velocidad v′<sub>M</sub>, o sea en el punto de máxima rapidez del MAS, donde v<sub>máx</sub> = ω·A:<br>A = v′<sub>M</sub>/ω = 0,799/2 = <b>0,40 m</b> (amplitud lineal) ⇒ amplitud angular θ₀ = A/l = 0,40/2,5 = 0,16 rad = <b>9,2°</b>. ▸ Control: 9,2° es chico, así que la aproximación de MAS es válida. <br><br><b>Paso 4 · la cantidad de oscilaciones.</b> Acá hay que ser honesta en la hoja: <b>un péndulo ideal sin rozamiento no deja de oscilar nunca</b>. Si el enunciado pide un número finito, es porque da un intervalo de tiempo (n = t/T) o alguna disipación. Con T = 3,14 s, el péndulo da <b>0,318 oscilaciones por segundo ≈ 19 por minuto</b>. <div class="trap"><div class="tr-t">Qué llevarte de este ejercicio, más allá de los números faltantes</div><b>1 ·</b> Si dice <b>elástico</b>, tenés <b>dos</b> ecuaciones y no necesitás ningún dato extra sobre lo que pasa después: podés resolver el choque solo. Es la diferencia con el ejercicio del 12/12/23, donde hacía falta la amplitud angular. ▸ <b>2 ·</b> Bala liviana contra péndulo pesado ⇒ la bala <b>rebota</b>, no sigue de largo ni queda incrustada. ▸ <b>3 ·</b> El puente entre choque y MAS es siempre el mismo: el cuerpo arranca <b>en el equilibrio</b>, así que su velocidad es la <b>máxima</b> del MAS y vale v<sub>máx</sub> = ω·A. ▸ <b>4 ·</b> Ni T ni f dependen de la amplitud ni de la masa: eso es un regalo de puntos si te lo preguntan aparte.</div>'}
]);

// ============================================================
// SECCIÓN 4 · 2D, EXPLOSIONES Y PÉNDULO BALÍSTICO
// ============================================================
registerExercises('fisica1-utn-choques', '4', [
  {st: 'En un choque sobre un plano (2D), ¿cuántas ecuaciones de conservación de la cantidad de movimiento escribís?',
   opts: ['Una sola, con los módulos', 'Dos: una por cada eje', 'Tres', 'Ninguna, hay que usar energía'],
   c: 1,
   ex: 'La cantidad de movimiento es un <b>vector</b>: se conserva componente por componente, así que en el plano se escriben <b>dos ecuaciones</b>, una en x y otra en y. ▸ Conviene poner el eje x en la dirección de la velocidad inicial: así el miembro izquierdo de la ecuación en y arranca en cero. ▸ Por qué las otras: (A) sumar módulos es el error central del tema — los vectores no se suman así; (D) en el choque nunca se arranca por energía.'},

  {st: 'Un resorte comprimido entre dos carritos en reposo (mA = 20 kg, mB = 30 kg) libera 1500 J. ¿Cuál sube más alto y en qué proporción?',
   opts: ['El más pesado, porque tiene más energía', 'Suben lo mismo: la energía se reparte igual', 'El más liviano, y la relación de alturas es (mB/mA)² = 2,25', 'El más liviano, y las alturas son iguales a la razón de masas'],
   c: 2,
   ex: 'Cantidad de movimiento total cero ⇒ m<sub>A</sub>·v<sub>A</sub> = m<sub>B</sub>·v<sub>B</sub> ⇒ el <b>liviano sale más rápido</b> (v<sub>A</sub> = 1,5·v<sub>B</sub>). ▸ Como h = v²/(2g), las alturas van con el <b>cuadrado</b> de las velocidades: h<sub>A</sub>/h<sub>B</sub> = (v<sub>A</sub>/v<sub>B</sub>)² = (m<sub>B</sub>/m<sub>A</sub>)² = <b>2,25</b>. Los números reales del final: 4,5 m y 2 m. ▸ Por qué las otras: (A) al revés — la energía se reparte al revés de las masas (900 J para A, 600 J para B); (B) solo si las masas fueran iguales.'},

  {st: 'Un cuerpo cae libremente y un proyectil horizontal lo impacta y queda incrustado. ¿Se conserva la cantidad de movimiento en el eje VERTICAL durante el choque, con la gravedad actuando?',
   opts: ['No, porque el peso es una fuerza externa', 'Sí, porque el choque dura un instante y el impulso del peso es despreciable', 'Solo si el cuerpo está en el punto más alto', 'Se conserva únicamente en el eje horizontal'],
   c: 1,
   ex: 'Sí, <b>durante el choque</b>. El peso es externo, pero el choque dura Δt ≈ 0 y su impulso (m·g·Δt) es despreciable frente al impulso interno del impacto. Por eso se conserva p en <b>los dos ejes</b>. ▸ Lo que <b>no</b> podés hacer es usar conservación de p en el tramo de caída antes o después: ahí la gravedad actúa un tiempo largo y sí cambia p — esos tramos van con cinemática o energía. ▸ Por qué las otras: (D) es el error típico, y deja el problema sin la componente vertical del conjunto.'},

  {st: 'Péndulo balístico: la bala queda incrustada en el saco y el conjunto sube hasta que la cuerda forma un ángulo α con la vertical. ¿Cuál es la cadena correcta?',
   opts: ['Energía de punta a punta: ½mv² = (M+m)·g·h', 'Cantidad de movimiento en el choque y energía después: h = l(1−cosα) → V = √(2gh) → v = (M+m)V/m', 'Energía primero y cantidad de movimiento después', 'Cinemática del tiro oblicuo'],
   c: 1,
   ex: 'Se recorre <b>al revés</b>: del ángulo sacás la altura h = l·(1−cos α); de la altura, la velocidad del conjunto <b>justo después</b> del choque, V = √(2gh); y recién ahí, con cantidad de movimiento, la velocidad de la bala: v = (M+m)·V/m. ▸ Por qué las otras: (A) es el error fatal del ejercicio — usar energía a través del choque plástico, donde se pierde más del 99% de la energía cinética, da una velocidad de bala muchísimo menor que la real; (C) invierte la secuencia y no cierra.'},

  {st: 'Un proyectil ATRAVIESA un bloque (sale con velocidad propia) y el bloque va a comprimir un resorte. Tenés dos incógnitas y una sola ecuación de cantidad de movimiento. ¿Por dónde empezás?',
   opts: ['Por el choque, suponiendo que el proyectil se detiene', 'Por la etapa 3: con el resorte sacás la velocidad del bloque, y recién después vas al choque', 'Por conservación de la energía en el choque', 'Faltan datos'],
   c: 1,
   ex: 'La ecuación del choque tiene dos incógnitas (velocidad de salida del proyectil y velocidad del bloque), así que no se puede atacar primero. ▸ El enunciado te da qué le pasa al bloque <b>después</b>: ½·M·v² = ½·k·Δx² te devuelve la velocidad del bloque justo después del choque, y con ese valor la ecuación de p queda con una sola incógnita. ▸ Por qué las otras: (A) inventa un dato; (C) el choque no es elástico — justamente el ejercicio pide cuánta energía se perdió; (D) los datos alcanzan, hay que leerlos en el orden correcto.'}
]);

registerReveals('fisica1-utn-choques', '4', [

  {st: '<b>Final Física I · 26/05/22 · Problema 1.</b> Enunciado verbatim: «Dos partículas A y B de 3 kg. Y 6 kg. respectivamente están sobre una superficie horizontal sin roce. La partícula A se mueve con una velocidad de módulo 20 m/s y choca con la partícula B que está inicialmente en reposo. Después del choque la partícula A se mueve 6 m/s en una dirección perpendicular a la que tenía inicialmente. Determinar la variación de la Ec durante el choque.»',
   ans: 'v⃗_B = (10 î − 3 ĵ) m/s ▸ |v_B| = 10,44 m/s, a 16,7° por debajo de la dirección original de A. ΔEc = 381 J − 600 J = −219 J (se perdieron 219 J).',
   sol: '<b>Sistema de referencia.</b> x en la dirección con la que llegaba A; y perpendicular, positivo en el sentido en que sale A después del choque. Superficie sin roce, choque instantáneo ⇒ se conserva p en los dos ejes. <br><br><b>Paso 1 · eje x.</b> Después del choque A sale <b>perpendicular</b>, así que su componente x es <b>cero</b> y toda la cantidad de movimiento en x se la lleva B:<br>m<sub>A</sub>·20 = m<sub>B</sub>·v<sub>Bx</sub> → 3·20 = 6·v<sub>Bx</sub> → <b>v<sub>Bx</sub> = 10 m/s</b>. <br><br><b>Paso 2 · eje y.</b> Antes del choque no había nada de movimiento en y, así que la suma después también tiene que ser cero:<br>0 = m<sub>A</sub>·6 + m<sub>B</sub>·v<sub>By</sub> → 0 = 3·6 + 6·v<sub>By</sub> → <b>v<sub>By</sub> = −3 m/s</b>. ▸ B sale hacia el otro lado del eje y que A: si A salió "para arriba", B sale "para abajo". Tiene que ser así, porque el total en y era cero. <br><br><b>Paso 3 · el módulo de v<sub>B</sub>.</b><br>|v<sub>B</sub>| = √(10² + 3²) = √109 = <b>10,44 m/s</b>, formando arctg(3/10) = <b>16,7°</b> con la dirección original de A. <br><br><b>Paso 4 · la variación de energía cinética.</b><br>E<sub>c,antes</sub> = ½·3·20² = <b>600 J</b><br>E<sub>c,después</sub> = ½·3·6² + ½·6·(√109)² = 54 + ½·6·109 = 54 + 327 = <b>381 J</b><br><b>ΔE<sub>c</sub> = 381 − 600 = −219 J</b>. El signo negativo dice que el choque fue <b>inelástico</b>: se disiparon 219 J, el 36,5% de la energía inicial. <div class="trap"><div class="tr-t">El cuadrado del módulo, no el cuadrado de una componente</div><b>1 ·</b> El error que se lleva puntos: calcular la energía de B con v<sub>Bx</sub> = 10 m/s. En la energía va el <b>módulo al cuadrado</b>: 109, no 100. La diferencia son 27 J. ▸ <b>2 ·</b> No hace falta hallar |v<sub>B</sub>| = 10,44 para la energía: podés usar directamente v<sub>Bx</sub>² + v<sub>By</sub>² = 100 + 9 = 109 y evitás arrastrar redondeos. ▸ <b>3 ·</b> "Perpendicular a la que tenía inicialmente" es la clave que vacía el eje x del cuerpo A: si no la usás, el sistema queda con más incógnitas que ecuaciones. ▸ <b>4 ·</b> El resultado tiene que dar <b>negativo</b>. Si te da positivo, revisá: sin explosión ni resorte, la energía cinética no puede aumentar en un choque.</div>'},

  {st: '<b>Final UTN.BA (hoja sin encabezado visible) · Problema 3.</b> Enunciado verbatim: «Se deja caer una partícula de masa m1 = 1kg desde el reposo, y desde una altura de 20m. Un segundo después de iniciada su caída es alcanzada por un proyectil de masa m2 = 0,1kg el cual, en el momento previo al impacto, tiene una velocidad horizontal hacia la derecha v2 = 100m/s. Si el proyectil queda incrustado en la partícula, determine el módulo de la velocidad con que el sistema llega al suelo.»',
   ans: 'El choque ocurre a 15 m del suelo, con m1 cayendo a 10 m/s. Justo después: v⃗ = (9,09 î − 9,09 ĵ) m/s. El sistema llega al suelo con vₓ = 9,09 m/s y v_y = 19,56 m/s ▸ |v| = 21,6 m/s.',
   sol: 'Son <b>cuatro</b> etapas encadenadas: caída libre, choque plástico en 2D, tiro oblicuo del conjunto y llegada al suelo. Eje x hacia la derecha, y hacia arriba, g = 10 m/s². <br><br><b>Paso 1 · dónde y cómo está m₁ en el instante del impacto.</b> Cayó libremente durante 1 s desde el reposo:<br>bajó Δy = ½·10·1² = <b>5 m</b> ⇒ está a <b>15 m del suelo</b><br>con velocidad v<sub>1y</sub> = −g·t = <b>−10 m/s</b> (y v<sub>1x</sub> = 0). <br><br><b>Paso 2 · el choque plástico (dos ejes).</b> El choque es instantáneo, así que se conserva p en x y en y, pese a la gravedad. La masa total es <b>1,1 kg</b>:<br><b>x:</b> 0,1·100 = 1,1·v<sub>x</sub> → v<sub>x</sub> = 10/1,1 = <b>9,09 m/s</b><br><b>y:</b> 1·(−10) = 1,1·v<sub>y</sub> → v<sub>y</sub> = −10/1,1 = <b>−9,09 m/s</b><br>(coinciden por casualidad: los dos numeradores valen 10). <br><br><b>Paso 3 · el tiro oblicuo del conjunto.</b> Desde 15 m de altura, con esa velocidad inicial. La horizontal es MRU (no cambia) y la vertical es MRUV:<br>v<sub>y,final</sub>² = v<sub>y</sub>² + 2·g·Δh = 9,09² + 2·10·15 = 82,64 + 300 = 382,6 → <b>v<sub>y,final</sub> = 19,56 m/s</b>. <br><br><b>Paso 4 · el módulo al llegar al suelo.</b><br>|v| = √(v<sub>x</sub>² + v<sub>y,final</sub>²) = √(82,64 + 382,6) = √465,3 = <b>21,6 m/s</b>. <div class="trap"><div class="tr-t">Los tres momentos en que este ejercicio se cae</div><b>1 · El choque NO pasa a 20 m.</b> Pasa un segundo después de soltarla, o sea a 15 m del suelo y con m₁ ya moviéndose a 10 m/s. Quien usa los 20 m completos o supone m₁ en reposo, se equivoca en las dos componentes. ▸ <b>2 · Después del choque hay que seguir con cinemática, no con cantidad de movimiento.</b> En la caída posterior la gravedad actúa durante un tiempo largo y p cambia: ahí van MRU en x y MRUV en y (o energía, que da lo mismo). ▸ <b>3 · La componente horizontal no desaparece.</b> El conjunto llega al suelo con v<sub>x</sub> = 9,09 m/s todavía: si la olvidás, te da 19,6 m/s en vez de 21,6 m/s. ▸ Y la masa total es <b>1,1 kg</b>, no 1 kg: el proyectil quedó adentro.</div>'},

  {st: '<b>Final UTN.BA · EXAMEN FINAL 21/2/2024 · Problema 5</b> (el encabezado indica «Para todos los ejercicios use g = 10 m/s²»). Enunciado verbatim: «Un proyectil de 5 g moviéndose con una rapidez inicial de 400 m/s es disparado hacia un bloque de 1 kg al cual atraviesa. El bloque, que al inicio está en reposo sobre una superficie horizontal sin fricción, comienza a moverse hasta chocar contra un resorte de constante 900 N/m. Si el bloque comprime al resorte una distancia de 5 cm hasta quedar detenido encuentre: (i) la rapidez con la cual sale el proyectil del bloque. (ii) la energía perdida en la colisión..»',
   ans: '(i) v′_proyectil = 100 m/s (sigue en el mismo sentido). (ii) Se perdieron 373,9 J: de 400 J iniciales quedaron 26,1 J.',
   sol: 'Es el caso del <b>proyectil que atraviesa</b>: hay dos velocidades finales distintas y una sola ecuación de cantidad de movimiento. Por eso el problema se resuelve <b>de atrás para adelante</b>. Datos en SI: m = 0,005 kg, M = 1 kg, v₀ = 400 m/s, k = 900 N/m, Δx = 0,05 m. <br><br><b>Paso 1 · la velocidad del BLOQUE justo después del choque (etapa 3).</b> La superficie es lisa, así que toda la energía cinética del bloque se guarda en el resorte:<br>½·M·V² = ½·k·Δx²<br>½·1·V² = ½·900·0,05² = <b>1,125 J</b> → V² = 2,25 → <b>V = 1,5 m/s</b>. <br><br><b>Paso 2 · el choque (etapa 2).</b> Ahora la ecuación de cantidad de movimiento tiene una sola incógnita:<br>m·v₀ = m·v′ + M·V<br>0,005·400 = 0,005·v′ + 1·1,5<br>2 = 0,005·v′ + 1,5 → 0,005·v′ = 0,5 → <b>v′ = 100 m/s</b>. ▸ Positivo: el proyectil sale <b>en el mismo sentido</b>, a la cuarta parte de su rapidez inicial. <br><br><b>Paso 3 · la energía perdida en la colisión.</b> Se comparan las energías cinéticas <b>en los dos instantes del choque</b>, no antes ni después:<br>E<sub>antes</sub> = ½·0,005·400² = <b>400 J</b><br>E<sub>después</sub> = ½·0,005·100² + ½·1·1,5² = 25 + 1,125 = <b>26,1 J</b><br>ΔE = 26,1 − 400 = <b>−373,9 J</b>: se perdieron <b>373,9 J</b>, el 93,5% de la energía inicial (fue a deformar y calentar la madera). <div class="trap"><div class="tr-t">El orden es obligatorio, y la energía del resorte no entra en la cuenta</div><b>1 ·</b> Si intentás arrancar por la ecuación del choque, tenés dos incógnitas y no salís. El resorte es el que abre el problema. ▸ <b>2 ·</b> La <b>energía perdida en la colisión</b> se calcula solo con las cinéticas de antes y después del choque. Los 1,125 J que después terminan en el resorte <b>ya están contados</b> dentro de los 26,1 J: no se restan de nuevo. ▸ <b>3 ·</b> Unidades: 5 g = <b>0,005 kg</b> y 5 cm = <b>0,05 m</b>. Con gramos y centímetros el resultado sale en otro planeta. ▸ <b>4 ·</b> Esto <b>no</b> es un choque plástico: el proyectil sale con velocidad propia, así que no existe una "velocidad del conjunto".</div>'},

  {st: '<b>Final UTN FRBA · 14/02/24 · Problema 2</b> (encabezado: «Utilice cuando sea necesario |g| = 10 m/s²»). Enunciado verbatim: «El resorte de la figura inicialmente comprimido entre los carritos A y B libera al soltarse una energía de 1500 J. No hay rozamiento entre los carritos y la superficie. A que altura maxima llegara cada uno de los carritos? mA = 20 kg ; mB = 30 kg.»',
   ans: 'v_A = 9,49 m/s y v_B = 6,32 m/s (en sentidos opuestos) ▸ h_A = 4,5 m y h_B = 2 m. El carrito liviano sube 2,25 veces más alto.',
   sol: 'Una explosión es un choque plástico <b>filmado al revés</b>: en vez de dos cuerpos que llegan y quedan pegados, hay dos pegados que se separan. La cantidad de movimiento se conserva igual. <br><br><b>Paso 1 · cantidad de movimiento (vale cero).</b> Los carritos parten del reposo, así que p<sub>total</sub> = 0 antes y después:<br>0 = m<sub>A</sub>·v<sub>A</sub> + m<sub>B</sub>·v<sub>B</sub> → 20·v<sub>A</sub> = −30·v<sub>B</sub> ⇒ <b>|v<sub>A</sub>| = 1,5·|v<sub>B</sub>|</b>. ▸ El liviano sale más rápido, siempre. <br><br><b>Paso 2 · la energía que aportó el resorte.</b> Los 1500 J se convierten íntegramente en cinética (superficie lisa):<br>½·20·v<sub>A</sub>² + ½·30·v<sub>B</sub>² = 1500<br>Sustituyendo v<sub>A</sub> = 1,5·v<sub>B</sub>:<br>10·(2,25·v<sub>B</sub>²) + 15·v<sub>B</sub>² = 22,5·v<sub>B</sub>² + 15·v<sub>B</sub>² = 37,5·v<sub>B</sub>² = 1500<br>v<sub>B</sub>² = 40 → <b>v<sub>B</sub> = 6,32 m/s</b> y v<sub>A</sub>² = 2,25·40 = 90 → <b>v<sub>A</sub> = 9,49 m/s</b>. <br><br><b>Paso 3 · cada uno sube por su rampa (energía, sin rozamiento).</b><br>h = v²/(2g):&nbsp;&nbsp;<b>h<sub>A</sub> = 90/20 = 4,5 m</b>&nbsp;·&nbsp;<b>h<sub>B</sub> = 40/20 = 2 m</b>. <br><br><b>Control.</b> Reparto de energía: E<sub>A</sub> = ½·20·90 = <b>900 J</b> y E<sub>B</sub> = ½·30·40 = <b>600 J</b>, que suman los 1500 J. La energía se reparte <b>al revés de las masas</b> (900/600 = 30/20), y las alturas van con el cuadrado: h<sub>A</sub>/h<sub>B</sub> = (m<sub>B</sub>/m<sub>A</sub>)² = 1,5² = <b>2,25</b> ✓. <div class="trap"><div class="tr-t">La energía no se reparte mitad y mitad</div><b>1 ·</b> Dar 750 J a cada carrito es el error clásico. La única cantidad que se reparte simétricamente es <b>la cantidad de movimiento</b> (iguales y opuestas); la energía se reparte <b>inversamente a las masas</b>, y por eso el liviano se lleva más. ▸ <b>2 ·</b> Acá <b>sí</b> se usa energía "en el choque", y no es contradicción: en una explosión la energía no se conserva, <b>aumenta</b>, y el enunciado te dice exactamente cuánto entra (1500 J). Eso reemplaza a la ecuación que en un choque común no tenés. ▸ <b>3 ·</b> Los 1500 J son de <b>los dos juntos</b>: la ecuación de energía lleva los dos términos. ▸ <b>4 ·</b> Piden la altura <b>de cada uno</b>: son dos respuestas, y son distintas.</div>'},

  {st: '<b>Final UTN.BA (hoja sin encabezado visible) · Problema 5.</b> Enunciado verbatim: «Dos partículas de masas m1 = 1 kg y m2 = 2 kg están unidas por un resorte de masa despreciable, ubicadas sobre un plano horizontal sin rozamiento. Inicialmente, la masa m2 está en reposo y m1 tiene una velocidad v0 = 5 m/s en dirección perpendicular al resorte como indica la figura. En un instante posterior la velocidad de la masa m1 es v⃗1 = 2 m/s i − 1,5 m/s j en el sistema de coordenadas indicado. Asumiendo que no actuaron fuerzas externas, calcule para ese mismo instante el vector velocidad de la masa m2.»',
   ans: 'v⃗₂ = (1,5 î + 0,75 ĵ) m/s ▸ módulo 1,68 m/s.',
   sol: 'No hay choque, pero es exactamente el mismo principio: <b>sin fuerzas externas, la cantidad de movimiento total del sistema se conserva</b>, sea cual sea la interacción interna (acá, un resorte que tira de las dos masas). <br><br><b>Paso 1 · la cantidad de movimiento total inicial.</b> Según la figura, v⃗₀ de m₁ es horizontal (eje x) y m₂ está en reposo:<br>p⃗<sub>i</sub> = m₁·v⃗₀ + m₂·0 = 1·(5 î) = <b>5 î kg·m/s</b>. ▸ La componente y del total es <b>cero</b>. <br><br><b>Paso 2 · igualar en el instante posterior.</b><br>m₁·v⃗₁ + m₂·v⃗₂ = p⃗<sub>i</sub><br>1·(2 î − 1,5 ĵ) + 2·v⃗₂ = 5 î<br>2·v⃗₂ = 5 î − 2 î + 1,5 ĵ = 3 î + 1,5 ĵ<br><b>v⃗₂ = 1,5 î + 0,75 ĵ (m/s)</b>. <br><br><b>Paso 3 · componente por componente (por si preferís verlo así).</b><br><b>x:</b> 1·5 = 1·2 + 2·v<sub>2x</sub> → v<sub>2x</sub> = <b>1,5 m/s</b><br><b>y:</b> 0 = 1·(−1,5) + 2·v<sub>2y</sub> → v<sub>2y</sub> = <b>+0,75 m/s</b><br>Módulo: |v⃗₂| = √(1,5² + 0,75²) = √2,8125 = <b>1,68 m/s</b>. <div class="trap"><div class="tr-t">Por qué el resorte no aparece en ninguna cuenta</div>La constante k, la elongación y la fuerza que hace el resorte son <b>internas</b> al sistema: por la tercera ley de Newton tiran de m₁ y de m₂ con fuerzas iguales y opuestas, y su efecto sobre la cantidad de movimiento <b>total</b> se cancela. Por eso el ejercicio se resuelve sin saber nada del resorte. ▸ <b>El signo del eje y es la trampa:</b> como el total en y valía cero y m₁ pasó a tener −1,5 ĵ, m₂ tiene que compensar con <b>+0,75 ĵ</b>. Si copiás el signo de m₁ en vez de invertirlo, el resultado no conserva nada. ▸ Y ojo: acá <b>no</b> se conserva la energía cinética del sistema, porque el resorte va guardando y devolviendo energía elástica. Solo p.</div>'},

  {st: '<b>Final UTN.BA (hoja sin encabezado visible; el mismo ejercicio aparece en dos hojas relevadas) · Problema 4 · el péndulo balístico del regimiento.</b> Enunciado verbatim: «En un regimiento se compra un nuevo armamento. La masa del proyectil es m = 25 g. Según el catálogo del fabricante, declara que la velocidad de disparo v es de 550 m/s, con un error relativo porcentual del 2 %. Antes de abonarlo se lo quiere ensayar. A tal efecto, un ingeniero armó el péndulo balístico mostrado en el esquema. Se sabe que el saco de arena (considerado puntual) posee una masa M = 3 kg, la longitud de la cuerda (ideal) es l = 2 m. Se efectúa un único disparo contra este saco de arena, el cual se detiene cuando la cuerda queda inclinada un ángulo α = 60°, medido desde la vertical. Determine Si el arma cumple o no con la declaración de fábrica (Justificar).»',
   ans: 'v_medida = 541,1 m/s. El intervalo declarado por el fabricante es 550 ± 11 m/s, es decir [539 ; 561] m/s. Como 541,1 cae adentro (error relativo 1,6% < 2%), EL ARMA CUMPLE con la declaración de fábrica.',
   sol: '<b>Referencia y hipótesis.</b> El proyectil queda incrustado en el saco (choque perfectamente plástico); la cuerda es ideal y su tensión no realiza trabajo; no hay rozamiento en el ascenso. g = 10 m/s². Se recorre la cadena <b>al revés</b>: del ángulo a la velocidad de la bala. <br><br><b>Paso 1 · la altura que sube el conjunto (geometría).</b><br>h = l·(1 − cos α) = 2·(1 − cos60°) = 2·(1 − 0,5) = <b>1 m</b>. <br><br><b>Paso 2 · la velocidad del conjunto justo DESPUÉS del choque (energía).</b> Del instante posterior al choque hasta el punto más alto se conserva la energía mecánica:<br>½·(M+m)·V² = (M+m)·g·h → V = √(2·g·h) = √(2·10·1) = <b>4,47 m/s</b>. ▸ La masa se cancela. <br><br><b>Paso 3 · la velocidad de la bala (cantidad de movimiento).</b> Con m = 25 g = <b>0,025 kg</b> y M + m = <b>3,025 kg</b>:<br>m·v = (M + m)·V<br>v = (3,025/0,025)·4,472 = 121·4,472 = <b>541,1 m/s</b>. <br><br><b>Paso 4 · la decisión (y esto es lo que se pide).</b> El fabricante declara 550 m/s con error relativo del 2%, o sea una tolerancia de 0,02·550 = <b>11 m/s</b> ⇒ intervalo aceptado <b>[539 ; 561] m/s</b>. ▸ El error relativo del valor ensayado:<br>ε<sub>r</sub>% = |541,1 − 550|/550 · 100 = 8,9/550 · 100 = <b>1,6%</b><br>Como <b>1,6% &lt; 2%</b> (y 541,1 m/s cae dentro del intervalo declarado), <b>el arma CUMPLE con la declaración de fábrica y se puede abonar</b>. <div class="trap"><div class="tr-t">Cuatro cosas: la energía prohibida, el cos60°, la masa total y el margen</div><b>1 · No se puede usar energía a través del choque.</b> Si planteás ½mv² = (M+m)gh te da v = √(2·3,025·10·1/0,025) ≈ 49 m/s: absurdo. En este choque plástico se pierde el <b>99,4%</b> de la energía cinética (de 3660 J quedan 30 J), y por eso la única herramienta válida en la etapa 2 es la cantidad de movimiento. ▸ <b>2 · h = l·(1 − cos α)</b>, no l·cos α ni l·sen α. Con α = 60° el cos vale justo 0,5 y h = 1 m redondo: si te da otra cosa, revisá la calculadora en grados. ▸ <b>3 ·</b> La masa después del choque es <b>M + m = 3,025 kg</b>. Usar 3 kg da 536,7 m/s, error 2,4%, y entonces contestarías "no cumple": el resultado se da vuelta por ese detalle. ▸ <b>4 ·</b> No alcanza con el número: el enunciado dice <b>"Justificar"</b>, así que hay que escribir el intervalo [539 ; 561] o el error relativo, y la conclusión con todas las letras. <span class="muted">Nota sobre g: con g = 9,8 m/s² daría V = 4,427 m/s y v = 535,7 m/s, con un error del 2,6%, y la conclusión se invertiría. La cátedra usa g = 10 m/s² y el encabezado de los finales lo imprime; resolvelo con 10.</span></div>'}
]);
