/* Quizzes basados en parciales reales 2022-2024 de la Cátedra Szwarcberg
   Cada quiz tiene ~7-10 preguntas, mezcla literales del parcial + variaciones
*/

registerExercises('biologia-segundo-parcial', '1', [
  {st: '¿Cuántas preguntas tiene el 2° parcial de Biología 008?', opts: ['10 preguntas, todas iguales', '33 preguntas multiple choice + 1 o 2 de completar con pistas', '40 preguntas de desarrollo', '20 preguntas de verdadero/falso'], c: 1, ex: 'El formato real: 12 preguntas de 0,15 pts + 1 de completar de ~2,2 pts + 20 preguntas de 0,30 pts. Total 10 puntos. ▸ Las otras opciones no corresponden al formato real de la cátedra.'},
  {st: 'En el parcial, si marcás MÁS DE UNA opción en una pregunta:', opts: ['Se promedian las 2 opciones', 'Se considera la primera marcada', 'La respuesta se ANULA', 'Vale media nota'], c: 2, ex: 'Las consignas explícitamente dicen que marcar más de una opción anula la respuesta. ▸ Hay que estar muy seguro de tachar bien antes de definir.'},
  {st: 'Si una opción de MC dice "el ARN SIEMPRE tiene timina", ¿qué tendrías que pensar primero?', opts: ['Que es verdadera porque dice SIEMPRE', 'Que es falsa por 2 razones: SIEMPRE es palabra-trampa Y el ARN tiene URACILO, no timina', 'Que depende del organismo', 'Que es ambigua'], c: 1, ex: 'Dos errores en una: SIEMPRE suele indicar opción falsa, y el ARN tiene U no T. ▸ Estas opciones con doble error son fáciles si las identificás.'},
  {st: 'Una célula es 2n=46. ¿Cuántas moléculas de ADN tendrá en la profase mitótica?', opts: ['46', '92 (46 cromosomas × 2 cromátides cada uno)', '23', '184'], c: 1, ex: 'En profase mitótica los cromosomas YA están duplicados (vienen de fase S). Cada cromosoma tiene 2 cromátides = 2 moléculas de ADN. ▸ Esta cuenta cae en TODOS los parciales.'},
  {st: 'Un ARNm tiene 80 codones desde el inicio AUG hasta el codón stop INCLUSIVE. ¿Cuántos aminoácidos tendrá la proteína?', opts: ['80 aa', '81 aa', '79 aa (el stop no codifica)', '160 aa'], c: 2, ex: 'Cada codón codifica 1 aa, EXCEPTO el stop (UAA/UAG/UGA) que no codifica nada. 80 - 1 = 79 aminoácidos. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'Para PROMOCIÓN DIRECTA (sin examen final) necesitás:', opts: ['7 o más promediando 1° y 2° parcial', '4 o más en cada parcial', '10 en al menos un parcial', '6 promediando'], c: 0, ex: 'Promoción directa: promedio >= 7 sin haber sacado menos de 4 en ninguno. Si te queda entre 4 y 7 → vas a final. ▸ Esto está en la fundamentación del programa.'},
  {st: '¿Cuál de las siguientes NO entra en el 2° parcial?', opts: ['Mitosis y meiosis', 'Replicación del ADN', 'Fotosíntesis y respiración celular', 'Genética mendeliana'], c: 2, ex: 'Fotosíntesis y respiración son temas del 1° parcial (Unidad 3). El 2° parcial es sobre Unidades 4 y 5: continuidad de la vida y evolución. ▸ Si te aparece una pregunta de Krebs o Calvin en el 2° parcial, podés sospechar.'}
]);

registerExercises('biologia-segundo-parcial', '2', [
  {st: 'Los cromosomas pertenecientes a un par homólogo:', opts: ['Provienen de un mismo progenitor y llevan distintos genes', 'Son aportados cada uno por un progenitor distinto y llevan la MISMA SECUENCIA DE GENES (mismos genes, no necesariamente mismos alelos)', 'Provienen del mismo progenitor y tienen información idéntica', 'Son siempre 100% idénticos en secuencia de nucleótidos'], c: 1, ex: 'Homólogos: 1 de cada progenitor, MISMOS genes (mismos loci), pero alelos pueden ser diferentes. ▸ Pregunta literal del parcial 12/06/2024 y 08/11/2023.'},
  {st: '¿Qué se sintetiza en el nucléolo?', opts: ['ARNm que luego madura', 'ARNr que se ensambla con proteínas ribosomales formando las subunidades del ribosoma', 'ARNt y ARNr', 'ARNr y histonas'], c: 1, ex: 'El nucléolo (sin membrana) es la fábrica de ARNr y de ensamblaje de subunidades ribosomales. Las histonas se hacen en el citoplasma y entran al núcleo. ▸ Pregunta clásica.'},
  {st: 'A través de los poros nucleares:', opts: ['Sale del núcleo la molécula de ADN', 'Salen del núcleo nucleótidos para la transcripción', 'Regresan al núcleo las subunidades ribosomales maduras', 'Ingresan al núcleo enzimas de la transcripción y proteínas asociadas al ADN (histonas)'], c: 3, ex: 'Por los poros entran las histonas, las ARN pol, las proteínas ribosomales (que se ensamblan en el nucléolo). Salen ARNm, ARNt y subunidades ribosomales maduras. El ADN NUNCA sale del núcleo. ▸ Pregunta del recuperatorio 2022.'},
  {st: 'Un nucleosoma se caracteriza porque:', opts: ['Posee histonas y forma parte de los poros nucleares', 'Posee histonas y representa la mínima unidad de enrollamiento del ADN', 'Forma parte de la lámina nuclear', 'Es exclusivo de procariotas'], c: 1, ex: 'Nucleosoma = unidad mínima de la cromatina: ADN enrollado en un octámero de 8 histonas. NO forma parte de poros (que son proteicos) ni de la lámina nuclear (que es de lamininas). ▸ Pregunta literal del 2022.'},
  {st: 'Los yacarés son animales 2n=42. Un espermatozoide de yacaré tendrá:', opts: ['42 cromosomas', '21 cromosomas (resultado de meiosis: mitad de la dotación)', 'No se puede determinar', '11 cromosomas'], c: 1, ex: 'Espermatozoide = gameta = haploide = n. Si 2n=42 entonces n=21. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'Los loros son 2n=70. En un óvulo de loro encontraremos:', opts: ['34 cromosomas sexuales y 1 autosómico', '34 pares de cromosomas autosómicos y 1 par sexual', '34 cromosomas autosómicos duplicados y 1 sexual duplicado', '34 cromosomas autosómicos y 1 cromosoma sexual'], c: 3, ex: 'Óvulo = gameta = n = 35 cromosomas (mitad de 70). De esos, 34 autosomas + 1 sexual. NO hay pares (eso sería diploide) y NO están duplicados (las cromátides se separaron en anafase II). ▸ Pregunta del recuperatorio 2022.'},
  {st: '¿Qué se puede afirmar con certeza de una célula n=24 de un chimpancé?', opts: ['Se formó por meiosis de una célula n=48', 'Se formó por meiosis de una célula n=12', 'Se formó por meiosis de una célula 2n=48', 'Se formó por mitosis de una célula 2n=48'], c: 2, ex: 'n=24 es haploide. Viene de meiosis de una 2n=48 (el doble). Una célula haploide NO puede dividirse por meiosis (eso requiere homólogos para parearse). ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'En el cariotipo humano, los cromosomas se ordenan en metafase porque:', opts: ['Es cuando se replica el ADN', 'Es cuando los cromosomas están MÁXIMAMENTE CONDENSADOS y se ven mejor', 'Es cuando se forman los nucleosomas', 'Es cuando aparece la envoltura nuclear'], c: 1, ex: 'Metafase = máxima condensación. Por eso los cariotipos se hacen en células detenidas en metafase. ▸ Concepto fundamental.'},
  {st: '¿Qué opción describe información que podría estar en el MISMO LOCUS de 2 cromosomas homólogos A y B?', opts: ['Color de flor en A y color de semilla en B', 'Textura rugosa de semilla en A y textura lisa de semilla en B (mismo gen, distintos alelos)', 'Textura rugosa en A y color amarillo en B', 'Color blanco en A y textura lisa en B'], c: 1, ex: 'Mismo locus en homólogos = MISMO gen = mismos tipos de información. Pueden tener distintos alelos (rugoso/liso) pero NO genes distintos (textura/color son genes distintos en loci distintos). ▸ Pregunta literal del recuperatorio 2022.'}
]);

registerExercises('biologia-segundo-parcial', '3', [
  {st: 'Un gen eucariota se transcribe desde:', opts: ['El ORI hasta la secuencia terminadora', 'El codón de inicio hasta el codón stop', 'El promotor hasta la secuencia de terminación', 'El promotor hasta el codón stop'], c: 2, ex: 'Transcripción: promotor → terminador. Traducción: codón inicio (AUG) → codón stop. ORI es replicación. ▸ Pregunta literal del 12/06/2024.'},
  {st: 'El transcripto primario sintetizado a partir de la hebra molde de ADN 3´ GGATATTC 5´ será:', opts: ['3´ CCTATAAG 5´ en citoplasma de procariotas', '3´ CCUAUAAG 5´ en citoplasma de procariotas', '5´ CCUAUAAG 3´ en el núcleo de eucariotas', '5´ CCUAUAAG 3´ en el citoplasma de eucariotas'], c: 2, ex: 'ARN es complementario y antiparalelo al molde, dirección 5→3, con U en vez de T. Si molde es 3´GGATATTC 5´ → ARN es 5´CCUAUAAG 3´. En eucariotas se sintetiza en el núcleo. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'La hebra codificante del gen miosina es 5´ TATGGCATTAAC 3´. ¿Cómo será el ARNm primario?', opts: ['3´CATGGCTATAAC 5´', '5´GTACCGATATTG 3´', '3´GUACCGAUAUUG 5´', '5´UAUGGCAUUAAC 3´ (igual a la codificante pero con U en lugar de T)'], c: 3, ex: 'El ARN es IGUAL a la hebra codificante, pero las T se reemplazan por U. Mantiene la dirección 5→3. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'En procariotas la traducción es CO-TRANSCRIPCIONAL porque:', opts: ['Tienen núcleo que separa ambos procesos', 'Al no tener envoltura nuclear, mientras se transcribe el ARNm, los ribosomas ya empiezan a traducirlo', 'No tienen ARNm', 'Hacen splicing simultáneo'], c: 1, ex: 'En procariotas NO hay núcleo: ambos procesos ocurren en el citoplasma y al mismo tiempo. En eucariotas hay separación física y temporal. ▸ Concepto que cae siempre.'},
  {st: 'Una bacteria sintetiza las proteínas A y B a partir de un MISMO ARNm. Esto es posible porque:', opts: ['En procariotas los ARNm son policistrónicos (codifican varias proteínas)', 'Los ARNm procariotas son monocistrónicos', 'En procariotas hay maduración cotranscripcional', 'En procariotas hay splicing alternativo'], c: 0, ex: 'ARNm policistrónico = característico y exclusivo de procariotas. Permite un solo promotor para varios genes relacionados (operones). ▸ Pregunta del 2022 y 2024.'},
  {st: 'Sobre el proceso de transcripción es CORRECTO:', opts: ['La poliadenilación ocurre similar en bacteria y levadura', 'La transcripción ocurre similar en bacteria y levadura (enzimas y sustratos similares)', 'La ARN pol cataliza la unión peptídica', 'La exportación de ARNm es similar en bacteria y levadura'], c: 1, ex: 'Aunque ocurra en distintos compartimentos, los principios básicos son similares (ARN pol, ribonucleótidos trifosfatados, dirección 5→3). Lo que cambia mucho son los procesos posteriores (maduración solo en eucariotas, exportación solo en eucariotas). ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'Dado un gen: Promotor 2500 NT | Exón 1: 2000 NT | Intrón 1: 20 NT | Exón 2: 200 NT | Intrón 2: 100 NT | Exón 3: 500 NT. ¿Cuántos nucleótidos tiene el ARNm maduro?', opts: ['5200 NT (todo)', '120 NT (intrones)', '700 NT', '2700 NT (suma de exones: 2000+200+500)'], c: 3, ex: 'ARNm maduro = solo exones. El promotor NO se transcribe; los intrones SÍ se transcriben pero se eliminan en splicing. 2000+200+500 = 2700 NT. ▸ Pregunta literal del 12/06/2024.'},
  {st: 'Indica el triplete que NO PUEDE haber sido sintetizado por la ARN polimerasa:', opts: ['ACT (porque tiene T, y el ARN tiene U)', 'ACG', 'GAG', 'CCC'], c: 0, ex: 'El ARN nunca tiene timina; en su lugar lleva uracilo (U). Cualquier triplete con T no puede ser ARN. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'El splicing alternativo permite obtener:', opts: ['Distintas proteínas a partir de un mismo gen (eligiendo qué exones empalmar del pre-ARNm)', 'Distintas proteínas a partir del mismo ARNm maduro', 'Distintos transcritos primarios a partir del mismo gen', 'Distintos ARNt a partir del mismo gen'], c: 0, ex: 'Splicing alternativo = de un solo pre-ARNm se generan varios ARNm maduros y por ende varias proteínas. Por eso 20.000 genes producen >90.000 proteínas en humanos. ▸ Pregunta literal del 08/11/2023.'}
]);

registerExercises('biologia-segundo-parcial', '4', [
  {st: 'El código genético establece relaciones entre:', opts: ['Un nucleótido y un aminoácido', 'Un triplete de bases y un triplete de aminoácidos', 'Un aminoácido y una base nitrogenada', 'Un TRIPLETE de bases del ARN y UN aminoácido'], c: 3, ex: 'Código genético: codón (3 nucleótidos del ARNm) ↔ 1 aminoácido. 64 codones, 61 codifican aa, 3 son stop. ▸ Pregunta literal del 12/06/2024.'},
  {st: 'Una mutación puede llevar a un ARNm con una base cambiada y la proteína resultante NO necesariamente cambia. Esto se debe a que el código es:', opts: ['Universal', 'Solapado', 'REDUNDANTE o DEGENERADO (varios codones pueden codificar el mismo aa)', 'No ambiguo'], c: 2, ex: 'Redundancia: codones sinónimos (ej: CCA, CCC, CCU, CCG = prolina). Si la mutación cambia la 3ra base de un codón, suele dar el mismo aa = mutación silenciosa. ▸ Pregunta literal de 2023 y 2024.'},
  {st: 'Un picornavirus se traduce en los ribosomas de la célula infectada porque el código genético es:', opts: ['Redundante', 'Solapado', 'No ambiguo', 'UNIVERSAL (igual en todos los seres vivos y virus)'], c: 3, ex: 'Universalidad = mismo código en bacterias, plantas, animales, virus. Por eso un ARN viral puede traducirse en cualquier célula. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'Un algodón modificado expresa un gen bacteriano cuyas proteínas se traducen en ribosomas vegetales. ¿Qué propiedad del código lo explica?', opts: ['Cada nucleótido pertenece a un solo codón', 'Tiene codones sinónimos', 'Un codón codifica un aminoácido', 'El código es el MISMO PARA TODOS los organismos (universal)'], c: 3, ex: 'Universalidad. Es la misma respuesta independientemente del organismo del que venga el ARN. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'La formación de los aminoacil-ARNt (activación de aminoácidos):', opts: ['Es citoplasmática y CONSUME energía (ATP)', 'Es citoplasmática y no consume energía', 'Es nuclear y no consume', 'Es nuclear y consume'], c: 0, ex: 'Aminoacilación: ocurre en el citoplasma y gasta ATP. Cada ARNt se une a su aa correspondiente catalizado por enzimas específicas. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'En la producción de proteínas del coronavirus (ARN) en una célula huésped intervienen:', opts: ['ARNm viral, ribosomas del huésped, aminoácidos virales', 'ARNm viral, ribosomas virales, aminoácidos del huésped', 'ARNm viral, RIBOSOMAS DEL HUÉSPED, AMINOÁCIDOS DEL HUÉSPED', 'ARNm viral, ribosomas virales, aminoácidos virales'], c: 2, ex: 'Los virus NO tienen ribosomas ni aminoácidos propios. Aportan SOLO su material genético; usan toda la maquinaria de la célula huésped (ribosomas, aa activados, ATP). ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'Dos polipéptidos A y B tienen exactamente la misma secuencia de 5 aa. Estos polipéptidos:', opts: ['Pueden provenir de la traducción de 2 ARNm DISTINTOS (por la redundancia del código)', 'Se traducen sí o sí con los mismos codones', 'Se traducen sí o sí con distintos codones', 'Vienen únicamente del mismo ARNm'], c: 0, ex: 'Por la redundancia, un mismo aa puede estar codificado por varios codones distintos. La misma secuencia de aa puede venir de ARNm distintos. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: '¿Qué proteínas necesitan PÉPTIDO SEÑAL HIDROFÓBICO para su síntesis?', opts: ['Las proteínas de membrana tipo bomba (se sintetizan en el REG)', 'Las enzimas citosólicas de la glucólisis', 'Las histonas', 'Las enzimas mitocondriales del ciclo de Krebs'], c: 0, ex: 'Solo las proteínas que terminarán en membrana plasmática, secreción, lisosomas o sistema de endomembranas tienen péptido señal hidrofóbico → se sintetizan en REG. Las del citosol, núcleo, mitocondrias y peroxisomas NO. ▸ Pregunta literal del 12/06/2024.'},
  {st: 'Una mutación INSERTA un nucleótido en el codón siguiente al AUG. ¿Qué ocurre?', opts: ['No hay corrimiento del marco pero la proteína es diferente', 'Se produce CORRIMIENTO DEL MARCO DE LECTURA de ese gen', 'La proteína resultante es idéntica', 'Es una mutación silenciosa'], c: 1, ex: 'Insertar o quitar un nucleótido (que no sea múltiplo de 3) corre el marco de lectura: a partir del punto de mutación todos los codones cambian. Mucho más grave que una sustitución. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'Si comparas 2 proteínas que difieren en 5 aminoácidos, los ARNm que las originan se diferencian:', opts: ['Como mínimo en 5 ribonucleótidos', 'Como mínimo en 5 codones (15 nucleótidos)', 'Solamente en 5 ribonucleótidos', 'Solamente en 5 codones'], c: 1, ex: 'Cada aminoácido distinto requiere al menos 1 codón distinto = 3 nucleótidos. 5 aa distintos = mínimo 5 codones. Por redundancia podría haber más diferencias en otros codones que codifiquen el mismo aa. ▸ Pregunta literal del 08/11/2023.'}
]);

registerExercises('biologia-segundo-parcial', '5', [
  {st: '¿Qué diferencia a una célula de la piel que respira de otra que libera veneno (misma rana)?', opts: ['La cantidad de moléculas de ADN', 'LOS GENES QUE SE TRANSCRIBEN Y TRADUCEN en uno u otro tipo', 'Los genes que se duplican', 'La cantidad de genes'], c: 1, ex: 'Mismo individuo = mismo ADN. La diferenciación celular se debe a expresión génica diferencial. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: '¿Qué moléculas son diferentes entre un bastón (ojo) y una célula ciliada (oído) de un mismo individuo?', opts: ['Los genes y los ARNm', 'LOS ARNm Y LAS PROTEÍNAS', 'Únicamente las proteínas', 'Los genes, los ARNm y las proteínas'], c: 1, ex: 'Como son del mismo individuo, los genes son idénticos. Pero la expresión diferencial hace que distintas células tengan distintos ARNm y distintas proteínas. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: '¿Cuáles son MECANISMOS DE REGULACIÓN DE LA EXPRESIÓN génica en eucariotas?', opts: ['Splicing alternativo + sistema de operones', 'COMPACTACIÓN DE LA CROMATINA + SPLICING ALTERNATIVO', 'Factores de transcripción + operones', 'FPS + metilación de la cromatina'], c: 1, ex: 'Cromatina compactada → no se expresa; laxa → sí. El splicing alternativo permite varias proteínas de un gen. Los operones son DE PROCARIOTAS, no de eucariotas. El FPS regula el ciclo celular, NO la expresión. ▸ Pregunta literal del 12/06/2024 y 08/11/2023.'},
  {st: '¿A qué nivel se puede regular la expresión de un gen?', opts: ['Duplicación y transcripción', 'Transcripción y duplicación', 'TRANSCRIPCIÓN Y TRADUCCIÓN', 'Duplicación y traducción'], c: 2, ex: 'La expresión génica se controla a nivel de transcripción (cuánto ARN se hace) y traducción (qué se hace con el ARN). La duplicación es replicación, otro proceso. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'Los factores de transcripción:', opts: ['Permiten la maduración de los ARNm', 'Se unen a secuencias reguladoras y permiten compactar la cromatina', 'Permiten pasar de G1 a S', 'Se unen a SECUENCIAS REGULADORAS y modifican la síntesis de ARNm (y de proteínas)'], c: 3, ex: 'Factores de transcripción = proteínas que se unen al promotor/regulador del gen. Activadores aumentan la transcripción; inhibidores la bloquean. NO actúan sobre el ARNm maduro ni regulan el ciclo. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'La insulina (proteína del páncreas) y los anticuerpos (proteínas del sistema inmune). Podemos decir:', opts: ['El gen de la hemoglobina está eucromatina en ambas', 'El gen de la hemoglobina está heterocromatina en ambas', 'El gen de la INSULINA está EUCROMATINA en páncreas y HETEROCROMATINA en células inmunes', 'El gen de la insulina está eucromatina en ambas'], c: 2, ex: 'Eucromatina = abierta = se expresa. El gen de la insulina se debe expresar en páncreas (eucromatina) y no en células inmunes (heterocromatina). Es regulación epigenética. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'En una micrografía se ven dos estructuras en el núcleo: A (oscura, condensada) y B (clara, laxa). ¿Qué afirmar?', opts: ['A y B presentan genes que se expresan', 'A y B carecen de genes', 'A es heterocromatina, sus genes son inaccesibles a la ARN pol y NO se transcriben', 'A son los nucleosomas y B son los poros'], c: 2, ex: 'Heterocromatina (oscura, condensada) = transcripcionalmente inactiva, inaccesible. Eucromatina (clara) = activa. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'En el operón lac, en AUSENCIA de lactosa:', opts: ['Se transcriben las enzimas que la degradan', 'El REPRESOR se une al operador y BLOQUEA la transcripción', 'La lactosa se sintetiza', 'El ADN se replica más'], c: 1, ex: 'Sin lactosa = represor unido al operador = ARN pol bloqueada = no se hacen las enzimas. Tiene sentido biológico: no fabricar enzimas para un sustrato que no está. ▸ Concepto del operón lac.'}
]);

registerExercises('biologia-segundo-parcial', '6', [
  {st: 'En el ciclo celular es CORRECTO que:', opts: ['La cromatina se condensa en cromosomas durante la PROFASE', 'La síntesis de ADN se lleva a cabo en G2', 'El punto de control de G1 permite el pasaje a M', 'Las ciclinas mitóticas aumentan durante la metafase'], c: 0, ex: 'Cromatina condensa al iniciar la fase M (profase). G1 controla pasaje a S (no a M). Ciclinas mitóticas aumentan en G2 (no en metafase). ▸ Pregunta literal del 08/11/2023.'},
  {st: 'La transcripción y traducción en el ciclo celular ocurren:', opts: ['Sólo durante G1', 'A lo largo de TODA LA INTERFASE (G1, S y G2)', 'Durante todo el ciclo celular', 'Entre meiosis I y II'], c: 1, ex: 'Transcripción y traducción ocurren en interfase entera (G1, S, G2). En fase M no hay transcripción significativa (cromatina condensada). Entre meiosis I y II NO hay nada de replicación. ▸ Pregunta literal del 12/06/2024.'},
  {st: '¿Cuál célula contiene MAYOR cantidad de ADN?', opts: ['Célula epitelial en G1 (46 moléculas)', 'Célula de la médula ósea al finalizar la división (46 moléculas)', 'Óvulo (23 moléculas)', 'ESPERMATOCITO PRIMARIO EN PROFASE I (92 moléculas: 46 cromosomas × 2 cromátides)'], c: 3, ex: 'El espermatocito primario en profase I es 2n=46 con cada cromosoma duplicado (2 cromátides) = 92 moléculas de ADN. Es el que tiene MÁS. ▸ Pregunta literal del 12/06/2024.'},
  {st: '¿Cuál tiene MAYOR cantidad de ADN?', opts: ['Una célula hepática en PROFASE MITÓTICA (46 cromosomas × 2 cromátides = 92 ADN)', 'Un espermatozoide (23 ADN)', 'Una neurona en G0 (46 ADN)', 'Una célula epitelial al finalizar la división (46 ADN)'], c: 0, ex: 'Profase mitótica: cromosomas duplicados pero no separados → máximo ADN. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'Una célula 2n=6 con cromosomas de 2 cromátides:', opts: ['Tiene 6 cromosomas y está en G2', '3 cromosomas duplicados en G2', '3 cromosomas simples en G1', '6 cromosomas en G1'], c: 0, ex: '2n=6 significa 6 cromosomas en TOTAL. Si cada uno tiene 2 cromátides, ya replicó (fase S terminó) y está en G2. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'Cuando aumentan los niveles de p53 (por daño en ADN), el ciclo se frena en G1. Consecuencia:', opts: ['Se bloquea la síntesis de ciclinas mitóticas', 'Se favorece la formación del FPM', 'NO SE FORMARÁN CROMÁTIDES HERMANAS (se bloquea la replicación)', 'Se permite la síntesis del FPS'], c: 2, ex: 'Si el ciclo se detiene en G1, no se forma el FPS → no se entra a S → no se replica el ADN → no se forman cromátides hermanas. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'En una horquilla de replicación, durante la duplicación del ADN:', opts: ['Primero se sintetiza la hebra continua y luego la discontinua', 'Se sintetizan SIMULTÁNEAMENTE las hebras continua y discontinua', 'La continua se sintetiza más lento', 'En una horquilla solo se sintetiza una hebra'], c: 1, ex: 'En cada horquilla, AMBAS hebras se replican al mismo tiempo (continua hacia la apertura, discontinua en fragmentos de Okazaki en sentido opuesto). ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'Durante la replicación del ADN, los CEBADORES (primers):', opts: ['Reconocen sitio de anclaje de factores de transcripción', 'Reconocen el ORI', 'PROPORCIONAN EL EXTREMO LIBRE 3´-OH para la ADN polimerasa', 'Proporcionan unión a la ADN ligasa'], c: 2, ex: 'La ADN pol solo puede agregar nucleótidos a un OH 3´ libre. El cebador (ARN) provee ese extremo. Luego se elimina y reemplaza por ADN. ▸ Pregunta literal del 12/06/2024.'},
  {st: 'Una arquea y un fibroblasto incorporan tinción fluorescente en sus orígenes de replicación. ¿Cuál es el patrón?', opts: ['1 marca en arquea y 1 en fibroblasto', 'Múltiples marcas en ambos', 'Múltiples en arquea y 1 en fibroblasto', 'UNA MARCA EN LA ARQUEA (procariota, 1 ORI) Y MÚLTIPLES EN EL FIBROBLASTO (eucariota, muchos ORI)'], c: 3, ex: 'Procariotas (arquea): un solo ORI (ADN circular chico). Eucariotas (fibroblasto humano): MUCHOS ORI distribuidos a lo largo de los cromosomas (para acelerar replicación de un genoma enorme). ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'En una variedad de maíz que CARECE de gen para ARN polimerasa, al final de la etapa S:', opts: ['ADN equivalente a mitad de una cromátide', 'ADN equivalente a UNA CROMÁTIDE por cromosoma (no se duplicó)', '4 cromátides por cromosoma', '2 cromátides por cromosoma'], c: 1, ex: 'Sin ARN pol no se pueden hacer cebadores → la ADN pol no puede iniciar la replicación. El ADN queda como estaba al inicio de S: 1 cromátide por cromosoma. ▸ Pregunta literal del recuperatorio 2022.'}
]);

registerExercises('biologia-segundo-parcial', '7', [
  {st: 'Como resultado de la meiosis se obtienen:', opts: ['4 células hijas haploides DISTINTAS entre sí', '4 células hijas idénticas', '4 células diploides', '2 células haploides'], c: 0, ex: 'Meiosis: 1 célula 2n → 4 células n DIFERENTES (por crossing over y segregación al azar). Mitosis: 1 → 2 idénticas. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'En la división celular es CORRECTO:', opts: ['En anafase mitótica se separan homólogos', 'El CROSSING OVER ocurre al azar (entre cromátides no hermanas de homólogos en profase I)', 'Cantidad de ADN en telofase mitótica = doble que en telofase I', 'Formación de tétradas es de profase II'], c: 1, ex: 'Crossing over: profase I de meiosis, entre cromátides no hermanas de homólogos. Ocurre en sitios al azar. Anafase mitótica separa CROMÁTIDES. Tétradas se forman en profase I (no II). ▸ Pregunta literal del 12/06/2024.'},
  {st: 'Una célula tiene 20 cromosomas en G1. Por meiosis se generan:', opts: ['4 células hijas con 10 CROMOSOMAS SIMPLES', '2 células con 10 duplicados', '2 con 20 duplicados', '2 con 20 simples'], c: 0, ex: 'Meiosis: 1 célula 2n=20 → tras S tiene 20 cromosomas duplicados → meiosis I separa homólogos (queda n=10 con 2 cromátides) → meiosis II separa cromátides (4 células n=10 con 1 cromátide cada cromosoma). ▸ Pregunta literal del 12/06/2024.'},
  {st: 'Un espermatocito II (producto de la 1° división meiótica) tiene:', opts: ['2n cromosomas con 2 cromátides cada uno', 'n CROMOSOMAS CON 2 CROMÁTIDES CADA UNO', '2n con 1 cromátide', 'n con 1 cromátide'], c: 1, ex: 'Espermatocito II = post meiosis I = ya es haploide (n), pero las cromátides hermanas aún no se separaron (eso es en meiosis II). Tiene n cromosomas, cada uno con 2 cromátides. ▸ Pregunta literal del 12/06/2024.'},
  {st: 'La cantidad de ADN al finalizar la fase S en una célula epitelial:', opts: ['Se forman pares de cromosomas homólogos', 'El CONTENIDO DE HISTONAS SE DUPLICA respecto de G1 (junto con el ADN)', 'La ploidía cambia de n a 2n', 'Cada cromosoma tiene 2 telómeros'], c: 1, ex: 'En fase S se duplica el ADN Y las histonas (porque hay que asociar las histonas al nuevo ADN). Los pares de homólogos se forman en fecundación; la ploidía no cambia; cada cromosoma duplicado tiene 4 telómeros (2 por cromátide). ▸ Pregunta literal del 08/11/2023.'},
  {st: 'Una figura muestra una célula con 3 cromosomas migrando a cada polo, cada uno con UNA cromátide. ¿Qué etapa es?', opts: ['Metafase I', 'Anafase I', 'ANAFASE II (separan cromátides hermanas, en célula haploide)', 'Anafase II con 6 cromosomas a cada polo'], c: 2, ex: 'Separación de cromátides en una célula con pocos cromosomas (haploide) = anafase II. Anafase I separaría homólogos (cromosomas duplicados de 2 cromátides). ▸ Pregunta literal del 08/11/2023.'},
  {st: 'Una célula radiomarcada con desoxirribonucleótidos durante la fase S. ¿Cómo se distribuye la marca en los cromosomas hijos?', opts: ['En AMBAS cromátides de cada cromosoma (replicación semiconservativa)', 'En una sola cromátide', 'En segmentos discontinuos', 'En ninguna'], c: 0, ex: 'Replicación SEMICONSERVATIVA: cada cromátide hija tiene una hebra vieja (no marcada) + una nueva (marcada). Por eso ambas cromátides hermanas tienen marca. ▸ Pregunta literal del 08/11/2023.'},
  {st: '¿Qué característica COMPARTEN la ADN polimerasa y la ARN polimerasa?', opts: ['Sintetizan cromátides hermanas', 'Participan de procesos catabólicos', 'Ambas requieren cebador', 'SINTETIZAN POLINUCLEÓTIDOS A PARTIR DE UN ÁCIDO NUCLEICO MOLDE'], c: 3, ex: 'Ambas usan un ácido nucleico como molde para polimerizar otro. La ADN pol hace ADN nuevo, la ARN pol hace ARN. Solo la ADN pol necesita cebador. Ambas son anabólicas. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'En la ovogénesis humana, a partir de UNA ovogonia se obtiene:', opts: ['4 óvulos viables', '1 ÓVULO VIABLE + cuerpos polares que degeneran', '2 óvulos y 2 espermatozoides', '4 cuerpos polares'], c: 1, ex: 'Citocinesis DESIGUAL en ovogénesis: todo el citoplasma queda en una sola célula → 1 óvulo grande + cuerpos polares chicos que mueren. Por eso la mujer produce mucha menos descendencia que el varón. ▸ Concepto clave de gametogénesis.'}
]);

registerExercises('biologia-segundo-parcial', '8', [
  {st: 'El genotipo HETEROCIGOTA se caracteriza porque:', opts: ['Los ALELOS para una característica son DIFERENTES', 'Se manifiesta siempre el dominante (esto solo aplica en dominancia completa)', 'Los 2 alelos son recesivos', 'Los 2 alelos son iguales'], c: 0, ex: 'Heterocigota = 2 alelos distintos (ej. Aa). En dominancia completa se expresa el dominante; en codominancia los dos; en dominancia incompleta el intermedio. ▸ Pregunta literal del 12/06/2024.'},
  {st: 'Una hembra de pelo negro homocigota (AA) × macho de pelo gris (aa). ¿Cómo será la descendencia?', opts: ['50% pelo negro y 50% pelo gris', '25% pelo gris', '0% pelo negro', 'TODOS pelo negro (100% Aa)'], c: 3, ex: 'AA × aa → todos Aa. Como A (negro) es dominante sobre a (gris), todos son pelo negro. No aparecen individuos grises porque para ser gris hay que ser aa. ▸ Pregunta literal del recuperatorio 2022 y 12/06/2024.'},
  {st: 'Una mujer A heterocigota (A0) tiene hijos con un hombre AB. Proporciones genotípicas esperadas:', opts: ['½ AB; ½ A0', '¼ AA; ¼ B0; ¼ AB; ¼ A0', '¼ AA; ¼ BB; ¼ B0; ¼ AB', '¼ AB; ½ AA; ¼ A0'], c: 1, ex: 'A0 × AB: mujer da A o 0 (50% cada uno); hombre da A o B (50% cada uno). Punnett: AA, A0, AB, B0 → ¼ cada uno. ▸ Pregunta literal del 12/06/2024.'},
  {st: 'Qué padres generan: 25% AA, 25% B0, 25% AB, 25% A0?', opts: ['A0 × B0', 'AO Y AB', 'AB × 00', 'A0 × 00'], c: 1, ex: 'Padre 1 (A0): da A o 0. Padre 2 (AB): da A o B. Combinaciones: AA, A0, AB, B0 = 25% cada uno. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'Los genes ligados al cromosoma X:', opts: ['Están en el cromosoma Y y ausentes en X', 'Están ausentes en machos', 'Solamente en hembras', 'ESTÁN EN EL X Y AUSENTES EN EL Y (por eso los machos son hemicigotas)'], c: 3, ex: 'Definición: genes presentes en X pero no en Y. Los varones tienen 1 solo alelo (hemicigotas). Por eso enfermedades recesivas ligadas al X afectan más a varones. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'Hemofilia: una mujer homocigota dominante (X^H X^H) × hombre hemofílico (X^h Y). Resultado:', opts: ['50% hijas y 50% hijos varones hemofílicos', '50% hijos hemofílicos; todas las hijas portadoras', 'TODOS LOS HIJOS VARONES SANOS Y TODAS LAS HIJAS PORTADORAS', 'Ninguna hija enferma y todos los hijos portadores'], c: 2, ex: 'X^H X^H × X^h Y: hijas heredan X^H de mamá y X^h de papá = X^H X^h = portadoras sanas. Hijos varones heredan X^H de mamá y Y de papá = X^H Y = sanos sin alelo h. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'Homero Simpson (X^c Y, calvo) × Marge (X^C X^c, portadora). ¿Cuántos hijos varones serán calvos?', opts: ['Ningún varón será calvo', 'Todos los varones serán calvos', '50% DE LOS HIJOS VARONES SERÁN CALVOS', '25% de toda la descendencia'], c: 2, ex: 'Marge da X^C o X^c (50% cada uno). Homero da X^c o Y. Hijos varones: 50% X^C Y (sanos) + 50% X^c Y (calvos). ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'Una enfermedad autosómica recesiva. Un individuo heterocigota Dd (D dominante = pigmentado, d recesivo = no pigmentado). Fenotipo:', opts: ['PIGMENTADO Y NO EXPRESA LA ENFERMEDAD (el dominante "tapa")', 'Pigmentado y expresa la enfermedad', 'Dd (el genotipo no es fenotipo)', 'DdDd'], c: 0, ex: 'Heterocigota Dd: en dominancia completa se expresa el dominante (pigmentado). El fenotipo se refiere a lo que se ve, no a los alelos. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'Para 2 alelos CODOMINANTES:', opts: ['Producto intermedio en el fenotipo', 'Producto de uno solo se expresa', 'AMBOS PRODUCTOS se expresan en el fenotipo', 'No se observa producto'], c: 2, ex: 'Codominancia: se expresan los dos alelos con misma intensidad. Ej: grupo AB tiene antígenos A y B en el mismo glóbulo rojo. Esto NO es dominancia incompleta (donde el producto sería intermedio). ▸ Pregunta literal del recuperatorio 2022.'}
]);

registerExercises('biologia-segundo-parcial', '9', [
  {st: 'Según la teoría de LAMARCK:', opts: ['Una característica adquirida en vida NO se hereda', 'Las mutaciones son fuente de variabilidad', 'El entrecruzamiento es fuente de variabilidad', 'UNA CARACTERÍSTICA ADQUIRIDA EN VIDA SE HEREDA a la descendencia'], c: 3, ex: 'Lamarck: herencia de caracteres adquiridos (la jirafa estira el cuello y lo transmite). Hoy se considera FALSA salvo casos epigenéticos puntuales. Lamarck no conocía mutaciones ni entrecruzamiento. ▸ Pregunta literal del recuperatorio 2022 y 12/06/2024.'},
  {st: 'DARWIN explicó la evolución basándose en:', opts: ['Supervivencia de los más fuertes físicamente', 'MAYOR REPRODUCCIÓN DE LOS QUE TIENEN MAYOR ADECUACIÓN AL MEDIO', 'Fuerza vital de los organismos (eso es Lamarck)', 'Variaciones en las frecuencias alélicas (eso es Sintética)'], c: 1, ex: 'Darwin: variaciones favorables → mejor adaptados → más se reproducen → transmiten esas variaciones. La selección natural NO es por fuerza física, sino por adecuación al ambiente. ▸ Pregunta literal del 08/11/2023.'},
  {st: 'Según la TEORÍA SINTÉTICA, el surgimiento de NUEVAS variantes alélicas:', opts: ['Es consecuencia de CAMBIOS EN LAS SECUENCIAS DE NUCLEÓTIDOS DEL ADN (mutaciones)', 'Es por la separación al azar de homólogos en anafase I', 'Por mutaciones y recombinación génica', 'Por procesos azarosos y no azarosos'], c: 0, ex: 'Solo las MUTACIONES generan nuevos alelos. Recombinación, deriva, flujo génico y selección natural modifican las frecuencias de alelos preexistentes, pero no crean nuevos. ▸ Pregunta literal del 12/06/2024.'},
  {st: 'Una población con modificación ALEATORIA en sus frecuencias alélicas atravesó:', opts: ['Selección natural', 'DERIVA GÉNICA (cambios al azar, sobre todo en poblaciones pequeñas)', 'Herencia de caracteres adquiridos', 'Entrecruzamiento'], c: 1, ex: 'Deriva génica = cambios AL AZAR en frecuencias alélicas. La selección natural NO es al azar (actúa el ambiente). Herencia de caracteres adquiridos es Lamarck. Entrecruzamiento no necesariamente cambia frecuencias poblacionales. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'Una plantación de pinos es fecundada con polen traído por vientos desde 100 km. ¿Qué fenómeno afecta a la siguiente generación?', opts: ['Selección natural', 'Mutación', 'Deriva génica', 'MIGRACIÓN (flujo génico): el polen lleva alelos de una población a otra'], c: 3, ex: 'Flujo génico = intercambio de alelos entre poblaciones. El polen trae alelos preexistentes en la población origen y modifica frecuencias en la receptora. No es selección natural (no hay agente selector), no es mutación (no genera nuevos alelos), no es deriva (no es al azar interno). ▸ Pregunta literal del 12/06/2024.'},
  {st: 'Los virus como el VIH (ARN) evolucionan. Las secuencias de aa de sus proteínas se modifican porque:', opts: ['MUTACIONES AZAROSAS ocurridas en el ARN viral', 'Necesidad de adaptarse', 'Mutaciones en las proteínas (las mutaciones están en el ADN/ARN, no en proteínas)', 'Mutaciones NO azarosas en respuesta al entorno'], c: 0, ex: 'Mutaciones siempre AL AZAR, en el material genético (ADN o ARN, según el organismo/virus). Las que dan ventaja adaptativa se seleccionan. Las proteínas no mutan directamente; reflejan los cambios del ARN/ADN. ▸ Pregunta literal del 12/06/2024 y 08/11/2023.'},
  {st: 'La avena (Avena fatua) hoy resiste un herbicida que antes mataba muchos individuos. Secuencia que mejor lo explica:', opts: ['Exposición → aparición por mutación de alelos resistentes → eliminación total de no resistentes', 'Exposición → alelos se vuelven resistentes por necesidad → aumentan resistentes', 'APARICIÓN DE ALELOS RESISTENTES POR MUTACIÓN (preexistentes) → EXPOSICIÓN AL HERBICIDA → INCREMENTO DE RESISTENTES (selección natural)', 'Exposición → resistentes por entrecruzamiento → aumentan resistentes'], c: 2, ex: 'Orden correcto: las mutaciones ocurren PRIMERO, al azar, ANTES de la presión selectiva. La exposición filtra: los resistentes sobreviven y se reproducen más → aumenta la frecuencia del alelo resistente. La opción "se vuelven resistentes por necesidad" es lamarckismo (incorrecto). ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'Orden evolutivo más probable según teoría aceptada actualmente:', opts: ['Bacteria → hongo → protozoo', 'BACTERIA ENTÉRICA → PROTOZOO → HONGO DE SOMBRERO', 'Hongo → protozoo → bacteria', 'Protozoo → bacteria → hongo'], c: 1, ex: 'Cronología: 1) primeros seres vivos = procariotas unicelulares (bacteria); 2) eucariotas unicelulares (protozoo, por endosimbiosis); 3) eucariotas pluricelulares (hongo). ▸ Pregunta literal del recuperatorio 2022.'},
  {st: 'Según la Teoría Sintética, la SELECCIÓN NATURAL lleva, entre otros, a:', opts: ['Variaciones por mutaciones en secuencias de ADN', 'MAYOR REPRODUCCIÓN DE LOS FENOTIPOS Y GENOTIPOS CON MAYOR ADECUACIÓN AL MEDIO', 'Modificaciones por deriva génica', 'Capacidad de adaptarse según necesidades (eso es Lamarck)'], c: 1, ex: 'Selección natural = reproducción diferencial: los más aptos se reproducen más → sus alelos aumentan en frecuencia. NO genera variabilidad (eso es mutación). ▸ Pregunta literal del 08/11/2023.'}
]);

/* Quiz 10: Mix integrador - 15 preguntas mezcladas estilo parcial real */
registerExercises('biologia-segundo-parcial', '10', [
  {st: '[Tema núcleo] Una arquea y un fibroblasto: ¿qué elementos COMUNES tienen?', opts: ['REGIONES PROMOTORAS Y ORÍGENES DE REPLICACIÓN (ambos transcriben y replican)', 'ORI e intrones (los procariotas no tienen intrones)', 'ORI y exones (procariotas no tienen exones)', 'Promotores y telómeros (procariotas tienen ADN circular sin telómeros)'], c: 0, ex: 'Tanto procariotas (arquea) como eucariotas (fibroblasto) tienen promotores (señalan inicio transcripción) y ORI (señalan inicio replicación). Los intrones, exones y telómeros son SOLO de eucariotas. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: '[Transcripción] La poliadenilación, capping y splicing son MODIFICACIONES característicamente:', opts: ['De procariotas', 'POST-TRANSCRIPCIONALES EN EUCARIOTAS (maduración del ARNm)', 'De la replicación', 'De la traducción'], c: 1, ex: 'Estas 3 son maduración del ARNm eucariota. Procariotas no maduran ARNm. ▸ Concepto fundamental.'},
  {st: '[Genotipo] El genotipo de una paloma doméstica:', opts: ['Comprende solo los genes que se expresan', 'Interactúa con el fenotipo y se manifiesta en el ambiente', 'INTERACTÚA CON EL AMBIENTE Y SE MANIFIESTA COMO FENOTIPO', 'Comprende todos los genes menos los que se expresan'], c: 2, ex: 'Genotipo = conjunto de genes. Fenotipo = manifestación visible = interacción genotipo × ambiente. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: '[Mitosis vs meiosis] En la METAFASE MITÓTICA:', opts: ['Todos los pares de homólogos alineados (eso es metafase I)', 'TODOS LOS CROMOSOMAS TIENEN UNA CROMÁTIDE Y SU HERMANA (están duplicados, se alinean individuales)', 'Hay crossing over (eso es profase I)', 'Cada cromosoma tiene una sola cromátide'], c: 1, ex: 'En metafase mitótica: cada cromosoma TIENE 2 cromátides (vienen de S). Se alinean cromosomas INDIVIDUALES en el ecuador (no por pares). Las hermanas se separarán en anafase. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: '[Ciclo + ciclinas] Luego del punto de control de G2:', opts: ['Se reduce la ciclina mitótica', 'Aumenta el FPS', 'Se reduce el FPS', 'SE INCREMENTA LA CICLINA MITÓTICA (la ciclina del FPM)'], c: 3, ex: 'Las ciclinas mitóticas aumentan a lo largo de G2 y al alcanzar el umbral, activan las quinasas y forman el FPM → inicia la fase M. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: '[Replicación + traducción] ¿Qué requieren cebador?', opts: ['La replicación y la transcripción', 'La REPLICACIÓN del ADN únicamente (la ADN polimerasa necesita un OH 3´ libre)', 'La traducción y la transcripción', 'Ninguna'], c: 1, ex: 'La ADN pol necesita cebador (primer de ARN) para empezar. La ARN pol y los ribosomas NO lo necesitan. ▸ Concepto crítico.'},
  {st: '[Bivalentes] La formación de bivalentes o tétradas es característica de:', opts: ['Profase II', 'PROFASE I de meiosis (apareamiento de homólogos)', 'Anafase mitótica', 'Telofase I'], c: 1, ex: 'Bivalentes = pareja de homólogos apareados. Solo en profase I. Ahí ocurre el crossing over también. ▸ Pregunta literal del 12/06/2024.'},
  {st: '[Heterocromatina/eucromatina] Una célula muestra área A (oscura, condensada) y B (clara, laxa):', opts: ['A y B se transcriben', 'A y B no tienen genes', 'A es ACCESIBLE a ARN pol', 'A es HETEROCROMATINA, sus genes están presentes pero INACCESIBLES a la ARN pol (no se transcriben)'], c: 3, ex: 'Heterocromatina (oscura, condensada) tiene genes pero ARN pol no accede → no se transcriben. Eucromatina (clara) sí. ▸ Pregunta literal del 08/11/2023.'},
  {st: '[Splicing alternativo] Permite obtener:', opts: ['DISTINTAS PROTEÍNAS DE UN MISMO GEN (eligiendo combinaciones de exones)', 'Distintas proteínas del mismo ARNm maduro', 'Distintos pre-ARNm del mismo gen', 'Distintos ARNt'], c: 0, ex: 'Splicing alternativo: distintos ARNm maduros → distintas proteínas, todas de un solo gen. Por eso 20.000 genes humanos producen 90.000 proteínas. ▸ Pregunta literal del 08/11/2023.'},
  {st: '[Ciclo daño en ADN] Si una célula presenta daño en ADN y se detiene en G1:', opts: ['Se bloquea la síntesis de ciclinas mitóticas (no actúan en G1)', 'SE IMPIDE LA SÍNTESIS DE CROMÁTIDES HERMANAS (no entra a S, no replica)', 'No se forma el FPM (no se forma en G1)', 'Se permite la síntesis de FPS'], c: 1, ex: 'Si no se forma el FPS → no se entra a S → no se replica el ADN → no se forman cromátides hermanas (que se forman justamente al replicar). ▸ Pregunta literal del 12/06/2024 y 08/11/2023.'},
  {st: '[Genética] Patas largas (A, dominante) × cortas (a). Macho aa × hembra AA homocigota dominante. Descendencia:', opts: ['50% pata larga', 'Siempre patas cortas', '0% pata larga', 'SIEMPRE PATAS LARGAS (100% Aa)'], c: 3, ex: 'AA × aa → todos Aa = todos fenotipo dominante (pata larga). La hembra solo aporta gametas A. ▸ Pregunta literal del 12/06/2024 y recuperatorio 2022.'},
  {st: '[Evolución] La AVENA hoy resiste herbicida que antes la mataba. Causa:', opts: ['Exposición → mutación → eliminación total de no resistentes', 'Por necesidad los alelos se volvieron resistentes (lamarckismo, incorrecto)', 'APARICIÓN DE ALELOS RESISTENTES POR MUTACIÓN (al azar, preexistentes) → EXPOSICIÓN AL HERBICIDA → SELECCIÓN AUMENTA SU FRECUENCIA', 'Entrecruzamiento generó resistencia'], c: 2, ex: 'Las mutaciones aparecen ANTES y al azar. La presión selectiva luego favorece a los que ya tenían la mutación. ▸ Pregunta literal del recuperatorio 2022.'},
  {st: '[Núcleo] El nucléolo:', opts: ['Tiene membrana propia', 'SINTETIZA ARNr y ENSAMBLA SUBUNIDADES RIBOSOMALES', 'Sintetiza ARNm que luego madura', 'Contiene las histonas listas'], c: 1, ex: 'Nucléolo = sin membrana. Allí se transcribe ARNr y se ensambla con proteínas ribosomales (que vienen del citoplasma) para formar subunidades. ▸ Pregunta literal del 08/11/2023.'},
  {st: '[Traducción] Iniciación de la traducción implica:', opts: ['ENSAMBLE DE LAS SUBUNIDADES RIBOSÓMICAS junto con ARNm y el primer aminoacil-ARNt', 'Unión de aa específico al ARNt (eso es aminoacilación, anterior)', 'Translocación (eso es elongación)', 'Llegada de codón stop al sitio A (eso es terminación)'], c: 0, ex: 'Iniciación: la subunidad menor encuentra el AUG, llega el ARNt iniciador con Met al sitio P, se acopla la subunidad mayor. ▸ Pregunta literal del 12/06/2024.'},
  {st: '[Eucariotas vs procariotas] Lo común a una bacteria entérica y un hongo microscópico:', opts: ['SÍNTESIS DE PROTEÍNAS EN EL CITOPLASMA Y POLIRRIBOSOMAS', 'Síntesis de ARN y proteínas simultáneas (solo procariotas)', 'Síntesis de proteínas en el núcleo', 'Síntesis de ARN y proteínas separadas en el tiempo (solo eucariotas)'], c: 0, ex: 'Tanto en procariotas como eucariotas la traducción es citoplasmática y puede haber polirribosomas (varios ribosomas en un mismo ARNm). Lo que NO comparten: cotranscripcionalidad (solo procariotas) y compartimentalización (solo eucariotas). ▸ Pregunta literal del recuperatorio 2022.'}
]);

/* Quiz 11: SIMULACRO de la "pregunta 13 de completar con pistas" (vale ~2,2 pts).
   El parcial real da un cuadro de términos y un texto con huecos sobre MEIOSIS + TRANSCRIPCIÓN.
   Acá se simula hueco por hueco: cada pregunta es UN hueco; las 4 opciones son términos del cuadro de pistas.
   PISTAS (cuadro): profase I · anafase I · anafase II · bivalentes/tétradas · crossing over · homólogos ·
   cromátides hermanas · haploide · diploide · promotor · ARN polimerasa · molde · uracilo · 5´→3´ · exones · intrones · splicing */
registerExercises('biologia-segundo-parcial', '11', [
  {st: 'COMPLETAR (1/8) · "El apareamiento de cromosomas homólogos para formar ______ ocurre en profase I." El término del cuadro de pistas que completa es:', opts: ['cromátides hermanas', 'BIVALENTES (o tétradas)', 'nucléolos', 'cebadores'], c: 1, ex: 'Los homólogos apareados forman bivalentes (= tétradas, porque hay 4 cromátides). Solo ocurre en profase I de meiosis. ▸ Las cromátides hermanas NO se aparean entre homólogos; son las dos copias de un mismo cromosoma.'},
  {st: 'COMPLETAR (2/8) · "El intercambio de segmentos entre cromátides no hermanas de homólogos se llama ______." Pista correcta:', opts: ['splicing', 'replicación semiconservativa', 'CROSSING OVER (entrecruzamiento)', 'translocación'], c: 2, ex: 'Crossing over = entrecruzamiento, en profase I, entre cromátides NO hermanas de homólogos. Es fuente de variabilidad (recombina alelos preexistentes). ▸ El splicing es maduración del ARNm, no tiene que ver con cromosomas.'},
  {st: 'COMPLETAR (3/8) · "En ______ se separan los cromosomas homólogos (cada uno todavía con sus 2 cromátides)." Pista correcta:', opts: ['anafase II', 'ANAFASE I', 'anafase mitótica', 'metafase I'], c: 1, ex: 'Anafase I: se separan los HOMÓLOGOS, reduciendo de 2n a n. Cada cromosoma viaja al polo aún con 2 cromátides. ▸ En anafase II (y en anafase mitótica) lo que se separan son las cromátides hermanas.'},
  {st: 'COMPLETAR (4/8) · "En ______ se separan las cromátides hermanas, dando 4 células ______." Pistas correctas (en orden):', opts: ['anafase I — diploides', 'ANAFASE II — HAPLOIDES', 'profase I — haploides', 'anafase II — diploides'], c: 1, ex: 'Anafase II separa cromátides hermanas. El producto final de la meiosis son 4 células haploides (n), cada cromosoma con 1 sola cromátide. ▸ Diploide (2n) sería el error clásico: la meiosis REDUCE la ploidía.'},
  {st: 'COMPLETAR (5/8) · "La transcripción comienza cuando la ARN polimerasa reconoce el ______ del gen." Pista correcta:', opts: ['codón de inicio AUG', 'origen de replicación (ORI)', 'PROMOTOR', 'terminador'], c: 2, ex: 'La ARN pol reconoce el PROMOTOR para iniciar la transcripción (termina en el terminador). ▸ El AUG es señal de inicio de la TRADUCCIÓN; el ORI es de la replicación. No confundir los tres "inicios".'},
  {st: 'COMPLETAR (6/8) · "La ARN polimerasa lee la hebra ______ del ADN y sintetiza el ARN en dirección ______." Pistas correctas (en orden):', opts: ['codificante — 3´→5´', 'MOLDE — 5´→3´', 'molde — 3´→5´', 'codificante — 5´→3´'], c: 1, ex: 'La ARN pol usa la hebra MOLDE (template) como guía y sintetiza el ARN en dirección 5´→3´ (siempre agrega nucleótidos al extremo 3´-OH). El ARN resultante es idéntico a la hebra codificante, salvo U por T. ▸ Recordá: SE LEE el molde, NO la codificante.'},
  {st: 'COMPLETAR (7/8) · "En el ARN, la base ______ reemplaza a la timina del ADN." Pista correcta:', opts: ['citosina', 'adenina', 'URACILO', 'guanina'], c: 2, ex: 'El ARN lleva uracilo (U) en lugar de timina (T). Cualquier secuencia de ARN con T es imposible. ▸ Las demás bases (A, G, C) están en ambos ácidos nucleicos.'},
  {st: 'COMPLETAR (8/8) · "Durante la maduración del pre-ARNm eucariota, el ______ elimina los ______ y une los ______." Pistas correctas (en orden):', opts: ['capping — exones — intrones', 'SPLICING — INTRONES — EXONES', 'splicing — exones — intrones', 'poliadenilación — intrones — exones'], c: 1, ex: 'Splicing = corte y empalme: ELIMINA intrones y UNE exones para dar el ARNm maduro. Solo en eucariotas. ▸ Capping y poliadenilación son otras dos modificaciones de la maduración, pero no cortan intrones.'}
]);
