// ============================================================
// FÍSICA I · UTN FRBA · FLUIDOS
// Fuentes:
//   · 6 ejercicios de 1er parcial, cátedra Martinelli (2009, 2010,
//     2012, 2013, 2014, 2016) — cantera de arquetipos.
//   · 8 problemas de fluidos de los finales de UTN.BA
//     (2/3/23, 26/5/22, 14/2/24, 21/2/24, 13/2/25 y tres hojas sin fecha).
// Convenciones de la cátedra: g = 10 m/s² (= 1000 cm/s²),
// δ_agua = 1 g/cm³, resoluciones planteadas en CGS y pasadas a SI.
// ============================================================

// ============================================================
// SECCIÓN 1 · HIDROSTÁTICA DESDE CERO
// ============================================================
registerExercises('fisica1-utn-fluidos', '1', [
  {st: 'El enunciado te da δ = 0,8 g/cm³. ¿Cuánto vale en el SI?',
   opts: ['0,8 kg/m³', '80 kg/m³', '800 kg/m³', '8000 kg/m³'],
   c: 2,
   ex: '<b>1 g/cm³ = 1000 kg/m³</b>, así que 0,8 g/cm³ = <b>800 kg/m³</b>. ▸ Sale de 1 g = 10⁻³ kg y 1 cm³ = 10⁻⁶ m³: el cociente da 10³. ▸ Truco: para pasar de g/cm³ a kg/m³ <b>corré la coma tres lugares a la derecha</b>. ▸ Por qué las otras: (A) no convierte nada; (B) usa un factor 100 (confunde con cm→m lineal); (D) usa 10⁴, un lugar de más.'},

  {st: 'La cátedra escribe "P₁ = 6 Pa = 60 dinas/cm²". ¿Cuál es el factor correcto entre Pa y din/cm²?',
   opts: ['1 Pa = 1 din/cm²', '1 Pa = 10 din/cm²', '1 Pa = 100 din/cm²', '1 Pa = 10⁵ din/cm²'],
   c: 1,
   ex: '<b>1 Pa = 1 N/m² = 10⁵ din / 10⁴ cm² = 10 din/cm².</b> ▸ Es el factor que aparece textual en la resolución del 1er parcial 2009: 6 Pa → 60 din/cm². ▸ Por qué las otras: (A) confunde con que Pa y din/cm² fueran la misma unidad; (C) usa 10² (mezcla el factor de longitud sin elevar al cuadrado); (D) es el factor <b>N → dina</b>, no el de presión.'},

  {st: 'Un buzo está a 20 m de profundidad en agua (δ = 1000 kg/m³, p_atm = 101 300 Pa, g = 10 m/s²). ¿Cuál es la presión ABSOLUTA a esa profundidad?',
   opts: ['2,00·10⁵ Pa', '3,01·10⁵ Pa', '1,01·10⁵ Pa', '2,01·10⁶ Pa'],
   c: 1,
   ex: '<b>p_abs = p₀ + δ·g·h</b> = 101 300 + 1000·10·20 = 101 300 + 200 000 = <b>301 300 Pa ≈ 3,01·10⁵ Pa</b>. ▸ Por qué las otras: (A) 2,00·10⁵ Pa es la presión <b>manométrica</b> (el término δgh solo) — es la respuesta correcta a otra pregunta, cuidado con cuál te piden; (C) es solo la atmosférica, como si el buzo estuviera en la superficie; (D) corre la coma un lugar.'},

  {st: 'Dos recipientes distintos, uno angosto y uno ancho, tienen agua hasta la misma altura y están abiertos. ¿Dónde es mayor la presión en el fondo?',
   opts: ['En el ancho, porque tiene más agua', 'En el angosto, porque el agua está más concentrada', 'Es la misma: la presión depende de h, no del volumen', 'Depende de la forma de las paredes'],
   c: 2,
   ex: 'La presión hidrostática es <b>p = p₀ + δ·g·h</b>: depende solo de la <b>profundidad</b>, la densidad y g. ▸ Ni el volumen total ni la forma del recipiente entran en la fórmula (es la llamada paradoja hidrostática). ▸ Consecuencia directa que usás todo el tiempo: <b>dentro de un mismo fluido conectado, misma altura ⟹ misma presión</b>. ▸ Por qué las otras: (A) y (B) razonan con el peso total del líquido, que no es lo que determina la presión; (D) la forma cambia la fuerza total sobre el fondo solo si cambia el área, no la presión.'},

  {st: 'Una compuerta rectangular vertical de 2 m de ancho va desde la superficie libre hasta 3 m de profundidad. La atmósfera actúa de los dos lados. ¿Qué fuerza le hace el agua? (δ = 1000 kg/m³, g = 10 m/s²)',
   opts: ['90 kN', '180 kN', '45 kN', '30 kN'],
   c: 0,
   ex: 'Como la presión crece con la profundidad, la carga es <b>triangular</b>: se usa la presión en el <b>centro geométrico</b>, a h = 1,5 m. ▸ F = δ·g·h_CG·A = 1000·10·1,5·(2·3) = <b>90 000 N = 90 kN</b>. ▸ Fórmula directa: F = ½·δ·g·b·H² = 0,5·1000·10·2·3² = 90 kN. ▸ La resultante se aplica a <b>2H/3 = 2 m</b> de la superficie, no en el medio. ▸ Por qué las otras: (B) 180 kN es el error clásico de usar la presión del <b>fondo</b> (30 000 Pa) por toda la compuerta: da el doble; (C) 45 kN olvida un factor 2 del ancho; (D) 30 kN confunde la presión (30 kPa) con la fuerza.'},

  {st: 'Un bloque de densidad 0,6 g/cm³ flota libremente en agua (1 g/cm³). ¿Qué fracción del volumen queda sumergida?',
   opts: ['40%', '60%', '100%', 'Depende del volumen del bloque'],
   c: 1,
   ex: 'En flotación libre E = P, y al cancelar V y g queda <b>V_sum/V = δ_cuerpo/δ_líq</b> = 0,6/1 = <b>0,6 = 60%</b>. ▸ Es la fórmula que más se usa en toda la unidad, y <b>no depende ni de g ni del tamaño</b>: vale igual para una pelotita o para un iceberg. ▸ Por qué las otras: (A) 40% es la parte que <b>emerge</b> (el complemento) — ojo con qué te preguntan; (C) 100% sería si δ_cuerpo ≥ δ_líq, o sea si se hundiera; (D) el volumen se cancela, por eso nunca hace falta como dato.'}
]);

// ============================================================
// SECCIÓN 2 · ARQUÍMEDES CON UNA TERCERA FUERZA
// ============================================================
registerExercises('fisica1-utn-fluidos', '2', [
  {st: 'Una esfera flota parcialmente sumergida y está atada al FONDO por una cuerda. ¿Cuál es la ecuación de equilibrio correcta?',
   opts: ['E + T = P', 'E = P + T', 'E = P − T', 'P = E + T'],
   c: 1,
   ex: 'La cuerda va al <b>fondo</b>, así que tira de la esfera <b>hacia abajo</b>: entra del mismo lado que el peso. ▸ <b>E = P + T</b>. ▸ El chequeo conceptual: estar amarrada obliga a la esfera a sumergirse <b>más</b> que en flotación libre (en el parcial 2012: 50% amarrada contra 30% libre). ▸ Por qué las otras: (A) es el error del 2012 que da 10% en vez de 50%: pone la tensión hacia arriba; (C) le cambia el signo a T sin justificación; (D) invertiría el sentido del empuje y haría que la esfera se hundiera sola.'},

  {st: 'En el parcial 2013, una esfera de δ = 2 g/cm³ y V = 600 cm³ está a MITAD sumergida en agua, colgada de un resorte estirado 10 cm. ¿Cuánto vale k?',
   opts: ['120 N/m', '90 N/m', '30 N/m', '9 N/m'],
   c: 1,
   ex: 'Tres fuerzas verticales: resorte hacia arriba, empuje hacia arriba, peso hacia abajo. ▸ <b>P</b> = δ_e·V·g = 2·600·1000 = 1,2·10⁶ din = <b>12 N</b>. ▸ <b>E</b> = δ_a·(V/2)·g = 1·300·1000 = 3·10⁵ din = <b>3 N</b> (¡la mitad del volumen!). ▸ F_el = P − E = <b>9 N</b> → k = 9 N / 0,10 m = <b>90 N/m</b>. ▸ Por qué las otras: (A) 120 N/m es olvidarse del empuje (usar solo el peso); (C) 30 N/m usaría el volumen total en el empuje; (D) 9 N/m confunde la fuerza (9 N) con la constante y deja el estiramiento en 10 cm sin pasar a metros.'},

  {st: 'Un cubo de 400 g flota con 1/5 de su volumen sumergido. Te preguntan qué fuerza hacia abajo hay que aplicarle para hundirlo del todo, pero NO te dan ni la densidad del líquido ni el volumen. ¿Qué hacés?',
   opts: ['Faltan datos, no se puede resolver', 'Asumo que el líquido es agua', 'Escribo el peso de dos formas (mg y δ_c·V·g) y uso la condición de flotación: se cancelan', 'Uso la densidad del cubo como 1 g/cm³'],
   c: 2,
   ex: 'La condición "1/5 sumergido" equivale a <b>δ_líq = 5·δ_cubo</b>. ▸ Con eso, el empuje total vale 5 veces el peso: mg + F = 5mg ⟹ <b>F = 4mg</b> = 4·0,4·10 = <b>16 N</b>. ▸ Ni δ_líq ni V hacen falta: es el "puede haber datos que no interesen" del encabezado, pero al revés — <b>datos que parecen faltar y en realidad se cancelan</b>. ▸ Por qué las otras: (A) es la reacción de pánico más cara del parcial; (B) inventar datos cambia el resultado y se descuenta; (D) si el cubo fuera de densidad 1 no flotaría con 1/5 sumergido.'},

  {st: 'Un bloque de madera está apoyado en el FONDO de un recipiente con agua, con una pesa de hierro encima; todo bajo el agua. ¿Cuántos diagramas de cuerpo libre conviene hacer?',
   opts: ['Uno solo, con el conjunto', 'Dos: uno para la pesa y otro para la madera, vinculados por el par acción-reacción', 'Tres, uno por cada fuerza', 'Ninguno, se resuelve con energía'],
   c: 1,
   ex: 'Son <b>dos cuerpos</b>: hay que hacer <b>dos DCL</b> y unirlos con la normal de contacto, que es un <b>par de acción y reacción</b> (empuja hacia arriba a la pesa y hacia abajo al bloque). ▸ Sumando las dos ecuaciones esa normal interna se cancela y queda N_fondo = P_fe + P_m − E_fe − E_m. ▸ Es el parcial 2016: N = 15,72 + 6 − 2 − 10 = <b>9,72 N</b>. ▸ Por qué las otras: (A) se puede tomar el conjunto y llegar a lo mismo, pero <b>solo si no te olvidás ninguna de las cuatro fuerzas</b>, que es justo lo que falla; (C) los DCL son por cuerpo, no por fuerza; (D) es estática, no hay movimiento ni energía en juego.'},

  {st: 'En ese mismo problema, la pesa de hierro está apoyada ARRIBA del bloque pero bajo el agua. ¿Recibe empuje?',
   opts: ['No, porque está apoyada sobre otro cuerpo', 'No, porque el hierro se hunde', 'Sí: está totalmente sumergida, así que E = δ_agua·V_pesa·g', 'Solo la mitad del empuje'],
   c: 2,
   ex: 'El empuje lo da <b>el volumen de fluido desplazado</b>, y la pesa está enteramente bajo el agua: <b>E_fe = 1 g/cm³ · 200 cm³ · 1000 cm/s² = 2·10⁵ din = 2 N</b>. ▸ Que se hunda no significa que no reciba empuje: significa que el empuje es <b>menor que su peso</b>. ▸ Por qué las otras: (A) apoyarse en otro cuerpo no cambia el fluido desalojado; (B) confunde "se hunde" con "no hay empuje"; (D) el medio empuje aplicaría si estuviera medio sumergida, no es el caso.'}
]);

// ============================================================
// SECCIÓN 3 · FLOTACIÓN CARGADA
// ============================================================
registerExercises('fisica1-utn-fluidos', '3', [
  {st: 'Un tronco de madera (δ = 800 kg/m³) tiene V = 0,12 m³ y flota en agua (1000 kg/m³). ¿Qué masa máxima puede cargar antes de quedar totalmente sumergido? (g = 10 m/s²)',
   opts: ['24 kg', '96 kg', '120 kg', '200 kg'],
   c: 0,
   ex: 'En el límite el tronco está <b>totalmente sumergido</b>: E = P_tronco + P_carga. ▸ δ_ag·V·g = δ_m·V·g + m·g ⟹ <b>m = (δ_L − δ_f)·V</b> = (1000 − 800)·0,12 = <b>24 kg</b>. ▸ Fijate que <b>g desaparece</b>: la capacidad de carga es una masa y no depende de la gravedad. ▸ Por qué las otras: (B) 96 kg = 800·0,12, que es la masa <b>del tronco</b>, no lo que carga; (C) 120 kg = 1000·0,12 es la masa del agua desalojada (el empuje entero, sin restar el peso propio del tronco); (D) 200 kg confunde la diferencia de densidades con una masa.'},

  {st: 'Los troncos del final del 2/3/23 tienen D = 0,3 m de DIÁMETRO y L = 1,7 m. ¿Cuál es el volumen de cada uno?',
   opts: ['0,481 m³', '0,120 m³', '0,153 m³', '0,038 m³'],
   c: 1,
   ex: 'El dato es el <b>diámetro</b>: el radio es 0,15 m. ▸ V = π·r²·L = π·0,15²·1,7 = π·0,03825 = <b>0,120 m³</b>. ▸ Por qué las otras: (A) 0,481 m³ es el error estrella: usar D = 0,3 como radio, lo que <b>cuadruplica</b> el volumen y te haría contestar 2 troncos en vez de 5; (C) usa el diámetro sin elevar al cuadrado; (D) 0,038 m³ es r²·L sin multiplicar por π.'},

  {st: 'Un oso PESA 3540 N y se sube a un témpano hasta dejarlo totalmente sumergido (δ_agua = 1000, δ_hielo = 900 kg/m³, g = 10). ¿Qué volumen tiene el témpano?',
   opts: ['0,354 m³', '3,54 m³', '35,4 m³', '354 m³'],
   c: 1,
   ex: 'Témpano totalmente sumergido: <b>δ_ag·V·g = δ_h·V·g + P_oso</b>. ▸ 10 000·V − 9000·V = 3540 ⟹ 1000·V = 3540 ⟹ <b>V = 3,54 m³</b>. ▸ Clave de lectura: el enunciado te da un <b>peso en newtons</b>, no una masa. Su masa sería 354 kg, pero acá ni hace falta calcularla. ▸ Por qué las otras: (A) y (C) corren la coma un lugar; (D) 354 m³ confunde el peso con la masa y encima divide mal.'},

  {st: 'La cuenta de la balsa te da 4,99 troncos. ¿Qué contestás?',
   opts: ['4 troncos', '4,99 troncos', '5 troncos', 'No se puede saber'],
   c: 2,
   ex: 'Piden la cantidad <b>mínima para mantenerlos a flote</b>: con 4 troncos el empuje no alcanza y se hunden. ▸ La cantidad mínima se redondea <b>siempre hacia arriba</b>, aunque el decimal sea 0,99 o 0,01: <b>5 troncos</b>. ▸ Escribí la justificación en la hoja ("con 4 el empuje es insuficiente"): es lo que corrige el docente. ▸ Por qué las otras: (A) redondea hacia abajo y la balsa se hunde; (B) no existen troncos fraccionarios; (D) el criterio es claro y explícito en el enunciado.'},

  {st: 'Un cuerpo queda con su parte de arriba dentro de una capa de aceite y su parte de abajo en agua, con la cara superior justo al nivel del aceite. ¿Cómo planteás el equilibrio?',
   opts: ['P = E_agua, el aceite no cuenta porque es más liviano', 'P = E_aceite + E_agua, un empuje por cada capa con su densidad y su espesor', 'P = E_aceite, porque es la capa de arriba', 'P = (δ_agua + δ_aceite)·V·g'],
   c: 1,
   ex: 'Con <b>dos líquidos superpuestos hay dos empujes</b> y se suman: cada capa aporta δ_capa · V_del cuerpo en esa capa · g. ▸ En el final del 26/5/22: δ_c·e = δ_ac·H + δ_ag·(e − H), con e = 10 cm. Con δ_c = 750 kg/m³ (venía flotando con 3/4 sumergido) sale <b>H = 7,14 cm</b>. ▸ El área se cancela: por eso el enunciado no te la da. ▸ Por qué las otras: (A) y (C) ignoran media escena; (D) suma las densidades y aplica el volumen entero a las dos, que es contar dos veces el mismo volumen.'}
]);

// ============================================================
// SECCIÓN 4 · HIDRODINÁMICA DESDE CERO
// ============================================================
registerExercises('fisica1-utn-fluidos', '4', [
  {st: 'Una cañería pasa de 25 mm a 12 mm de diámetro interior. Si en la parte ancha el agua va a 1 m/s, ¿a qué velocidad va en la angosta?',
   opts: ['2,08 m/s', '4,34 m/s', '0,48 m/s', '1 m/s'],
   c: 1,
   ex: 'Continuidad: A₁v₁ = A₂v₂ con A = π·(D/2)², así que <b>v₂ = v₁·(D₁/D₂)²</b>. ▸ v₂ = 1·(25/12)² = 1·(2,0833)² = <b>4,34 m/s</b>. ▸ Por qué las otras: (A) 2,08 m/s es el error más frecuente: usar la razón de diámetros <b>sin elevarla al cuadrado</b>; (C) 0,48 m/s invierte la razón (el fluido acelera al angostarse, no frena); (D) 1 m/s sería si la sección no cambiara.'},

  {st: 'El parcial 2009 da Q = 25 l/min. ¿Cuánto es en CGS?',
   opts: ['25 cm³/s', '416,67 cm³/s', '1500 cm³/s', '0,42 cm³/s'],
   c: 1,
   ex: '25 litros = <b>25 000 cm³</b> (1 l = 1000 cm³) y 1 min = 60 s. ▸ Q = 25 000/60 = <b>416,67 cm³/s</b>. ▸ En SI serían 4,167·10⁻⁴ m³/s. ▸ Por qué las otras: (A) usa el número tal cual, sin convertir ni litros ni minutos; (C) 1500 cm³/s convierte los minutos pero no los litros al revés (25·60); (D) divide por 1000 de más.'},

  {st: 'En una cañería HORIZONTAL que se angosta, ¿qué le pasa a la presión?',
   opts: ['Aumenta, porque el fluido está más apretado', 'Disminuye, porque la velocidad aumenta', 'No cambia', 'Depende de la densidad del fluido'],
   c: 1,
   ex: 'Bernoulli horizontal: p + ½δv² = cte. ▸ Continuidad manda v₂ &gt; v₁ al angostarse, así que <b>p₂ &lt; p₁</b>: es el <b>efecto Venturi</b>. ▸ Control de signo: si te da p₂ &gt; p₁ en un caño horizontal que se angosta, tenés un error — el paréntesis (v₁² − v₂²) es <b>negativo</b>. ▸ Por qué las otras: (A) es la intuición equivocada más común del tema: la energía que gana en velocidad la pierde en presión; (C) solo si la sección no cambiara; (D) la densidad cambia <b>cuánto</b> baja, no <b>si</b> baja.'},

  {st: 'Un tanque abierto y grande tiene un orificio chico a 5 m por debajo de la superficie libre. ¿Con qué velocidad sale el agua? (g = 10 m/s²)',
   opts: ['5 m/s', '10 m/s', '50 m/s', '100 m/s'],
   c: 1,
   ex: 'Torricelli: <b>v = √(2·g·h)</b> = √(2·10·5) = √100 = <b>10 m/s</b>. ▸ Es la misma velocidad que tendría un cuerpo en caída libre desde 5 m: sale de Bernoulli con p_atm de los dos lados (se cancela) y v ≈ 0 en la superficie porque el tanque es grande. ▸ Por qué las otras: (A) 5 m/s confunde h con v; (C) 50 m/s es 2gh sin la raíz; (D) 100 m/s es directamente v² sin la raíz.'},

  {st: 'Vas a resolver una cañería que cambia de sección Y de altura, y te piden la presión en el punto 2. ¿Qué usás?',
   opts: ['Solo Bernoulli', 'Solo continuidad', 'Continuidad primero (para v₂) y después Bernoulli completa con el término δgh', 'Solo hidrostática, p = p₀ + δgh'],
   c: 2,
   ex: 'Bernoulli tiene <b>dos velocidades incógnitas</b> y una sola ecuación: no cierra sola. ▸ Orden correcto: <b>1)</b> continuidad A₁v₁ = A₂v₂ para sacar v₂; <b>2)</b> Bernoulli con los tres términos, incluido δ·g·(h₁ − h₂). ▸ Por qué las otras: (A) te faltan velocidades; (B) continuidad no dice nada de presiones; (D) hidrostática solo vale si el fluido está en <b>reposo</b>, y acá circula.'},

  {st: 'En un tubo en U abierto en las dos ramas hay agua (1 g/cm³) y sobre ella, en una rama, una columna de aceite (0,8 g/cm³) de 10 cm. ¿Cómo se comparan las alturas de las columnas medidas desde la interfaz?',
   opts: ['Son iguales, porque los dos son líquidos', 'La columna de aceite es MÁS alta que el desnivel de agua que la compensa', 'La columna de aceite es más baja', 'No hay relación posible'],
   c: 1,
   ex: 'Debajo de la interfaz todo es agua conectada, así que a esa altura las presiones se igualan: <b>δ_ac·h_ac = δ_ag·h_ag</b>. ▸ 0,8·10 = 1·h_ag ⟹ h_ag = 8 cm. ▸ O sea: <b>el líquido más liviano forma la columna más alta</b> (10 cm de aceite equilibran solo 8 cm de agua). ▸ Por qué las otras: (A) si fueran iguales las densidades no importarían; (C) invierte la relación; (D) la relación es exactamente δ₁h₁ = δ₂h₂.'}
]);

// ============================================================
// SECCIÓN 5 · LOS FLUIDOS DEL FINAL
// ============================================================
registerExercises('fisica1-utn-fluidos', '5', [
  {st: 'Tanque hermético con aire a p₀ = 202 600 Pa arriba. En un punto A a profundidad h (lejos del orificio) la presión es pA = 207 600 Pa. ¿Cuánto vale h? (δ = 1000 kg/m³, g = 10 m/s²)',
   opts: ['0,5 m', '5 m', '2 m', '20,76 m'],
   c: 0,
   ex: 'El punto A está en <b>fluido en reposo</b> (el enunciado aclara "muy lejos del orificio"), así que vale hidrostática pura: <b>pA = p₀ + δ·g·h</b>. ▸ 207 600 − 202 600 = 5000 = 1000·10·h ⟹ <b>h = 0,5 m</b>. ▸ Este es el paso 1 obligatorio del problema: sin h no podés seguir. ▸ Por qué las otras: (B) 5 m sale de dividir 5000 por 1000 (olvidando g); (C) 2 m no sale de ninguna cuenta del enunciado; (D) 20,76 m divide pA por 10 000.'},

  {st: 'En ese mismo tanque, el agua llega hasta H = 4 m y el orificio está a h = 0,5 m bajo la superficie. Para el tiro horizontal del chorro, ¿desde qué altura cae?',
   opts: ['0,5 m', '4 m', '3,5 m', '4,5 m'],
   c: 2,
   ex: 'El chorro sale del orificio y cae hasta el piso: la altura de caída es la <b>altura del orificio sobre el piso</b>, o sea <b>y = H − h = 4 − 0,5 = 3,5 m</b>. ▸ Después t = √(2y/g) = √0,7 = 0,837 s y d = v·t. ▸ Por qué las otras: (A) 0,5 m es la <b>profundidad</b> bajo la superficie, que sirve para la presión, no para la caída — es la confusión que más se cobra en este problema; (B) 4 m sería si el orificio estuviera en el fondo; (D) 4,5 m suma en vez de restar.'},

  {st: 'Cañería horizontal de 25 mm a 10⁵ Pa que se angosta a 12 mm y BAJA 3 m. ¿La presión final es mayor o menor que 10⁵ Pa? (δ = 1000 kg/m³, g = 10)',
   opts: ['Menor, porque se angosta (Venturi)', 'Mayor: bajar 3 m suma 30 000 Pa y el estrechamiento solo resta ≈ 8900 Pa', 'Igual, los dos efectos se cancelan exactamente', 'No se puede saber sin el caudal'],
   c: 1,
   ex: 'Compiten dos términos. ▸ <b>Venturi</b>: ½δ(v₁² − v₂²) = 500·(1 − 18,84) = <b>−8919 Pa</b>. ▸ <b>Altura</b>: δ·g·Δh = 1000·10·3 = <b>+30 000 Pa</b>. ▸ p₂ = 100 000 − 8919 + 30 000 = <b>121 081 Pa ≈ 1,21·10⁵ Pa</b>: gana la altura. ▸ Moraleja: 1 m de agua vale 10 000 Pa, un orden de magnitud por encima de los términos dinámicos típicos. ▸ Por qué las otras: (A) mira solo la mitad del problema; (C) los números no dan lo mismo; (D) el caudal sale de v₁ y A₁, que ya te los dan.'},

  {st: 'Tanque de gasolina (δ = 720 kg/m³) con aire comprimido a p₀ = 130,1 kPa, lleno hasta h = 1 m, que descarga a la atmósfera (101,3 kPa). ¿Con qué velocidad sale? (g = 10, A₂ ≪ A₁)',
   opts: ['4,5 m/s', '10 m/s', '20 m/s', '14,6 m/s'],
   c: 1,
   ex: 'Bernoulli entre la superficie (v ≈ 0, p = p₀, altura h) y la salida (p = p_atm, altura 0): ▸ <b>½δv² = (p₀ − p_atm) + δ·g·h</b> = 28 800 + 7200 = 36 000. ▸ 360·v² = 36 000 ⟹ v² = 100 ⟹ <b>v = 10 m/s</b>. ▸ Es Torricelli con un empujón extra: la sobrepresión aporta 28 800 Pa y la columna 7200 Pa. ▸ Por qué las otras: (A) 4,5 m/s es Torricelli puro √(2gh) = 4,47, ignorando la presurización; (C) 20 m/s duplica; (D) 14,6 m/s es la respuesta del <b>otro</b> problema (el tanque de agua a 202 600 Pa) — no mezcles los dos tanques.'},

  {st: 'Tubo en U con el extremo izquierdo cerrado por un émbolo con un resorte (cámara a presión atmosférica) y el derecho abierto. El agua queda h = 10 cm por encima del émbolo. ¿Cuál es la ecuación del émbolo? (S = 10 cm², k = 50 N/m, g = 10)',
   opts: ['p_atm·S = k·Δx', 'δ·g·h·S = k·Δx', '(p_atm + δgh)·S = k·Δx', 'δ·g·h = k·Δx'],
   c: 1,
   ex: 'Sobre el émbolo actúan: el agua desde abajo con (p_atm + δgh)·S hacia arriba, el aire de la cámara con p_atm·S hacia abajo y el resorte comprimido con k·Δx hacia abajo. ▸ La atmosférica <b>se cancela</b> y queda <b>δ·g·h·S = k·Δx</b>. ▸ Números: 1000·10·0,1·10⁻³ = 1 N ⟹ Δx = 1/50 = <b>0,02 m = 2 cm</b> ✔ (coincide con la respuesta de la hoja). ▸ Por qué las otras: (A) ignora el agua; (C) no cancela la atmosférica y te da un Δx absurdo (más de 2 m); (D) se olvida de multiplicar por el área: una presión no es una fuerza.'}
]);

// ============================================================
// REVEALS · EJERCICIOS REALES
// ============================================================

// --- SECCIÓN 2 · Los 5 ejercicios de Arquímedes de los parciales ---
registerReveals('fisica1-utn-fluidos', '2', [
  {st: '<b>1er parcial 26/10/10 · UTN FRBA · Prof. Patricia Martinelli · Problema A2</b><br><br>A2: Dos cuerpos unidos por una soga ideal están en reposo dentro de un recipiente que contiene un líquido como se muestra en la figura; como puede observarse el 2 esta totalmente sumergido y el 1 parcialmente. Calcular:<br>a) La tensión en la soga.<br>b) El volumen del cuerpo 1 que sobresale por encima de la superficie libre del líquido.<br><br>δ1=0,7gr/cm3 , δ2=2gr/cm3 , δLiq=1,2gr/cm3 , V1=100cm3, V2=10cm3',
   ans: 'a) T = 8000 dinas = 0,08 N &nbsp;·&nbsp; b) V que sobresale = 35 cm³ (queda sumergido 65 cm³ de los 100 cm³)',
   sol: '<b>Sistema de referencia e hipótesis.</b> Eje y positivo hacia arriba. Reposo ⟹ ΣF_y = 0 en cada cuerpo. Trabajo en CGS con g = 1000 cm/s² (= 10 m/s²). Soga ideal: la tensión es la misma en los dos extremos y de sentido opuesto en cada cuerpo.<br><br><b>Paso 1 · Elegí bien por dónde empezar.</b> El cuerpo 2 tiene <b>una sola incógnita</b> (está totalmente sumergido, su volumen es dato). El cuerpo 1 tiene dos (T y el volumen sumergido). Empezá por el 2.<br><br><b>Paso 2 · DCL del cuerpo 2.</b> Como δ₂ = 2 &gt; δ_Liq = 1,2, tiende a hundirse: la soga tira de él <b>hacia arriba</b>.<br>T + E₂ − P₂ = 0<br>T = P₂ − E₂ = (δ₂ − δ_Liq)·V₂·g = (2 − 1,2)·10·1000<br><b>T = 8000 dinas = 0,08 N</b><br><br><b>Paso 3 · DCL del cuerpo 1.</b> Flota parcialmente (δ₁ = 0,7 &lt; 1,2), y por reacción la soga tira de él <b>hacia abajo</b>. El empuje se calcula <b>solo con el volumen sumergido</b> V_sum:<br>δ_Liq·V_sum·g − T − δ₁·V₁·g = 0<br>1,2·V_sum·1000 = 8000 + 0,7·100·1000 = 8000 + 70 000 = 78 000<br>V_sum = 78 000 / 1200 = <b>65 cm³</b><br><br><b>Paso 4 · Lo que piden.</b> El volumen que <b>sobresale</b>:<br>V_emergido = V₁ − V_sum = 100 − 65 = <b>35 cm³</b><br><br><b>Control.</b> El inciso b) <b>no depende de g</b>: si usás g = 980 cm/s², T pasa a 7840 din pero V_emergido sigue siendo 35 cm³. Buena verificación de que no metiste g de más en algún lado.'},

  {st: '<b>1er parcial 18/10/12 · UTN FRBA · Prof. H. Patricia Martinelli · Problema A2</b><br><br>A2: Una esfera de densidad δ=0.3g/cm3 y volumen V=1500cm3, se encuentra parcialmente sumergida en agua como se muestra en la figura, estando unida al fondo del recipiente por medio de una cuerda ideal.<br>a) Sabiendo que la densidad del agua es 1g/cm3 y que la tensión en la cuerda es 3N, determine qué porcentaje del volumen de la esfera está sumergido.<br>b) ¿Qué porcentaje quedaría sumergido si se cortara la cuerda?',
   ans: 'a) 50% del volumen sumergido &nbsp;·&nbsp; b) 30% del volumen sumergido',
   sol: '<b>Sistema de referencia e hipótesis.</b> Eje y positivo hacia arriba; equilibrio (ΣF_y = 0). CGS con g = 1000 cm/s². Paso previo de unidades: <b>T = 3 N = 3·10⁵ dinas</b>.<br><br><b>Paso 1 · Sentido de la tensión.</b> La cuerda va al <b>fondo</b> ⟹ tira de la esfera <b>hacia abajo</b>, del mismo lado que el peso:<br><b>E = P + T</b><br><br><b>Paso 2 · Inciso a).</b> Llamá x a la fracción sumergida (V_sum = x·V):<br>δ_agua·g·x·V = δ·g·V + T<br>1·1000·x·1500 = 0,3·1000·1500 + 300 000<br>1 500 000·x = 450 000 + 300 000 = 750 000<br>x = 0,5 ⟹ <b>50% sumergido</b><br><br>Escrito como fórmula: x = δ/δ_agua + T/(δ_agua·g·V) = 0,3 + 0,2 = 0,5.<br><br><b>Paso 3 · Inciso b).</b> Si se corta la cuerda, T = 0 y queda <b>flotación libre</b>:<br>δ_agua·g·x·V = δ·g·V ⟹ x = δ/δ_agua = 0,3/1<br><b>x = 30% sumergido</b><br><br><b>Control conceptual.</b> Estar amarrada al fondo la obliga a sumergirse <b>más</b> (50%) que si flotara libre (30%). Si te da al revés, revisá el signo de T. ▸ Y fijate que el inciso b) <b>no depende ni de g, ni de V, ni de la tensión</b>: es puro cociente de densidades.'},

  {st: '<b>1er parcial 3/9/2013 · Curso O1122 · Prof. Patricia Martinelli · UTN FRBA · Problema A</b><br><br>A: Una esfera de densidad δe = 2g/cm3 y volumen Ve = 600cm3, tiene la mitad de su volumen sumergido en agua y está sostenida por medio de un resorte ideal, como se muestra en la figura. La densidad del agua es δa = 1g/cm3. Sabiendo que el resorte está estirado 10cm, determine su constante elástica.',
   ans: 'k = 9·10⁴ dina/cm = 90 N/m',
   sol: '<b>Sistema de referencia e hipótesis.</b> Eje y positivo hacia arriba; esfera en equilibrio. El resorte está <b>estirado y por encima</b> de la esfera ⟹ su fuerza es <b>hacia arriba</b>. CGS con g = 1000 cm/s².<br><br><b>Paso 1 · DCL: tres fuerzas verticales.</b><br>F_el (arriba) + E (arriba) − P (abajo) = 0<br><br><b>Paso 2 · Peso.</b><br>P = δ_e·V_e·g = 2 · 600 · 1000 = 1 200 000 dina = <b>12 N</b><br><br><b>Paso 3 · Empuje (¡solo la mitad sumergida!).</b><br>V_sum = V_e/2 = 300 cm³<br>E = δ_a·V_sum·g = 1 · 300 · 1000 = 300 000 dina = <b>3 N</b><br><br><b>Paso 4 · Fuerza elástica y constante.</b><br>F_el = P − E = 1 200 000 − 300 000 = 900 000 dina = <b>9 N</b><br>k = F_el / Δl = 900 000 din / 10 cm = <b>9·10⁴ din/cm</b><br>En SI: k = 9 N / 0,10 m = <b>90 N/m</b><br><br><b>Los errores que este ejercicio caza.</b> ▸ Olvidar el empuje da k = 120 N/m. ▸ Usar el volumen total en el empuje da k = 60 N/m. ▸ Dejar el estiramiento en 10 cm en vez de 0,10 m te divide por 100. ▸ Y ojo: la esfera flota parcialmente pero <b>no está en flotación libre</b>, porque δ_e &gt; δ_a: la que compensa la diferencia es la fuerza del resorte.'},

  {st: '<b>1er parcial 21/8/2014 · Curso I1021 · Prof. Patricia Martinelli · UTN.BA · Problema A2</b><br><br>A2: Un cubo de masa m=400g se encuentra flotando en equilibrio en un líquido, con 1/5 de su volumen sumergido. ¿Qué fuerza hacia abajo habría que aplicarle al cubo para mantenerlo totalmente sumergido en ese líquido?',
   ans: 'F = 16 N (equivale a 4 veces el peso del cubo)',
   sol: '<b>Sistema de referencia e hipótesis.</b> Eje y positivo hacia arriba; equilibrio en las dos situaciones. g = 10 m/s². Peso: P = m·g = 0,4 kg · 10 m/s² = <b>4 N</b>.<br><br><b>Paso 1 · Situación inicial (flotando, 1/5 sumergido).</b> P = E:<br>m·g = δ_liq·g·(V/5) &nbsp;&nbsp;y también&nbsp;&nbsp; m·g = δ_cubo·g·V<br>Igualando: δ_liq·V/5 = δ_cubo·V ⟹ <b>δ_liq = 5·δ_cubo</b> &nbsp;<span class="muted">…(1)</span><br><br><b>Paso 2 · Situación final (totalmente sumergido, con F hacia abajo).</b><br>P + F = E-prima = δ_liq·g·V<br>Usando (1): m·g + F = 5·δ_cubo·g·V = 5·m·g<br><b>F = 4·m·g = 4 · 0,4 · 10 = 16 N</b><br><br><b>El punto del ejercicio.</b> No te dan ni δ_liq ni V, y <b>no hacen falta</b>: se cancelan. El truco es escribir el peso de <b>dos maneras</b> (m·g y δ_cubo·V·g) para eliminar V. Si te trabás buscando datos que no están, perdiste el problema.<br><br><b>Chequeo.</b> Sumergido del todo, el empuje vale 5 veces el peso; para equilibrar hay que agregar 4 pesos hacia abajo. ▸ Errores típicos: contestar F = 4 N (el peso), o calcular el empuje final con V/5 en lugar de V.'},

  {st: '<b>1er parcial 1/8/2016 · Curso R1022 · Prof. Patricia Martinelli · UTN.BA · Problema A2</b> <span class="muted">(de esta fecha solo tenemos la hoja de resolución; el enunciado está transcripto de ahí)</span><br><br>Problema A2: Un cubo de madera de 10 cm de lado, se encuentra completamente sumergido, en el fondo de un recipiente que contiene agua. Sobre el mismo está apoyada una pesa de hierro de volumen 200 cm³. Las densidades del agua, el hierro y la madera son δag=1g/cm³, δm=0.6g/cm³ y δfe=7.86g/cm³, respectivamente. Determine el valor de la fuerza normal que hace el fondo del recipiente sobre el bloque de madera.',
   ans: 'N_madera = 972 000 dinas = 9,72 N',
   sol: '<b>Sistema de referencia e hipótesis.</b> Eje y positivo hacia arriba; los dos cuerpos en equilibrio. Los dos están <b>totalmente sumergidos</b>, así que los dos reciben empuje. CGS con g = 1000 cm/s².<br><br><b>Paso 0 · El volumen del cubo.</b> Te dan el <b>lado</b>: V_m = (10 cm)³ = <b>1000 cm³</b>. Olvidar el cubo del lado es el error más frecuente del problema.<br><br><b>Paso 1 · Dos DCL.</b><br>Pesa de hierro: E_fe (arriba) + N_fe (arriba, contacto con la madera) − P_fe (abajo) = 0 &nbsp;<span class="muted">…(1)</span><br>Bloque de madera: E_m (arriba) + N_m (arriba, del fondo) − N-prima_fe (abajo) − P_m (abajo) = 0 &nbsp;<span class="muted">…(2)</span><br>N_fe y N-prima_fe son <b>par de acción y reacción</b>: mismo módulo.<br><br><b>Paso 2 · Sumá (1) y (2).</b> La normal interna se cancela:<br><b>N_m = P_fe + P_m − E_fe − E_m</b><br><br><b>Paso 3 · Los cuatro términos.</b><br>E_fe = δ_ag·V_fe·g = 1·200·1000 = 200 000 din = <b>2 N</b><br>E_m = δ_ag·V_m·g = 1·1000·1000 = 10⁶ din = <b>10 N</b><br>P_fe = δ_fe·V_fe·g = 7,86·200·1000 = 1 572 000 din = <b>15,72 N</b><br>P_m = δ_m·V_m·g = 0,6·1000·1000 = 600 000 din = <b>6 N</b><br><br><b>Paso 4 · Resultado.</b><br>N_m = 15,72 + 6 − 2 − 10 = <b>9,72 N</b><br><br><b>Verificación de sentido.</b> La madera sola flotaría (δ_m = 0,6 &lt; 1): es la pesa de hierro la que la mantiene contra el fondo. Que dé <b>N_m &gt; 0</b> confirma que el conjunto efectivamente apoya; si te diera negativa, significaría que el sistema flota y la hipótesis era falsa.<br><br><span class="muted">Nota: en la hoja original la ecuación aparece escrita como "N_m = P_fe + P_m − E_fe − E_m = 0". Ese "= 0" final es un error de tipeo del apunte: el resultado no es cero, es 9,72 N.</span>'}
]);

// --- SECCIÓN 3 · Flotación cargada (los 4 del final) ---
registerReveals('fisica1-utn-fluidos', '3', [
  {st: '<b>Examen Final 2/3/2023 · UTN.BA · Problema 6</b><br><br>6. Tres niños fabrican una balsa uniendo troncos de diámetro D = 0,3 m y longitud L = 1,7 m. Cada niño tiene una masa de 40 kg. Si la densidad del agua es δ_a = 1000 kg/m³ y la de la madera es δ_m = 800 kg/m³, ¿cuántos troncos serán necesarios como mínimo para mantenerlos a flote?<br><br><span class="muted">(datos reconstruidos: la foto recorta el margen derecho de la hoja y se cortan "Cada niño tiene un[a masa de 40 kg]" y "¿cuántos tronc[os]". El resto está completo.)</span>',
   ans: 'N = 5 troncos (la cuenta da 4,99 y se redondea hacia arriba)',
   sol: '<b>Sistema de referencia e hipótesis.</b> Eje y positivo hacia arriba. Condición límite: la balsa queda <b>totalmente sumergida</b> pero los chicos no se mojan — es el máximo empuje disponible. g = 10 m/s².<br><br><b>Paso 1 · Volumen de un tronco (cilindro).</b> El dato es el <b>diámetro</b> D = 0,3 m ⟹ r = 0,15 m.<br>V = π·r²·L = π·(0,15)²·1,7 = π·0,03825 = <b>0,1202 m³</b><br><br><b>Paso 2 · Equilibrio de la balsa en el límite.</b><br>E = P_troncos + P_niños<br>N·V·δ_a·g = N·V·δ_m·g + m_niños·g<br>N·V·(δ_a − δ_m) = m_niños<br><br><b>Paso 3 · Despejá N.</b><br>m_niños = 3 · 40 kg = <b>120 kg</b><br>N = 120 / [0,1202 · (1000 − 800)] = 120 / 24,03 = <b>4,99</b><br><br><b>Paso 4 · Redondeo (esto es lo que se corrige).</b> Piden el <b>mínimo</b>: con 4 troncos la capacidad es 4·24,03 = 96,1 kg &lt; 120 kg y la balsa se hunde. Con 5 son 120,2 kg ≥ 120 kg.<br><b>Respuesta: 5 troncos.</b><br><br><b>La fórmula de bolsillo.</b> Cada tronco carga (δ_a − δ_m)·V = 200 · 0,1202 = <b>24 kg</b>. Nada más que eso: el resto de su empuje se lo come su propio peso. ▸ Error nº 1: usar D = 0,3 m como radio — el volumen se cuadruplica (0,481 m³) y contestarías 2 troncos. ▸ Error nº 2: redondear 4,99 a 4.'},

  {st: '<b>Examen Final 21/2/2024 · UTN.BA · Problema 6</b> <span class="muted">(el día impreso podría ser 21 o 24; el mes y el año se leen sin duda)</span><br><br>6. Un oso pesa 3540 N, se sube a un témpano de hielo, en alta mar, de tal manera que el témpano quede totalmente sumergido, ¿qué volumen tiene el témpano?. DATOS: δagua = 1000kg/m³, δhielo = 900kg/m³<br><br><span class="muted">Encabezado de la hoja: "Para todos los ejercicios use g = 10 m/s²."</span>',
   ans: 'V = 3,54 m³',
   sol: '<b>Sistema de referencia e hipótesis.</b> Eje y positivo hacia arriba; equilibrio. Condición del enunciado: <b>témpano totalmente sumergido</b> ⟹ V_sumergido = V_total. g = 10 m/s².<br><br><b>Paso 1 · Leé bien el dato.</b> "Un oso <b>pesa</b> 3540 N": eso ya es un <b>peso</b> (fuerza), no una masa. No lo multipliques por g otra vez. (Su masa, si la quisieras, sería 354 kg.)<br><br><b>Paso 2 · DCL del conjunto témpano + oso.</b><br>E = P_hielo + P_oso<br>δ_agua·V·g = δ_hielo·V·g + P_oso<br><br><b>Paso 3 · Reemplazá y despejá.</b><br>1000·10·V = 900·10·V + 3540<br>10 000·V − 9000·V = 3540<br>1000·V = 3540<br><b>V = 3,54 m³</b><br><br><b>Atajo (la fórmula de capacidad de carga).</b> m_carga = (δ_L − δ_f)·V ⟹ 354 = (1000 − 900)·V ⟹ V = 3,54 m³. Mismo resultado en una línea.<br><br><b>Control de razonabilidad.</b> 3,54 m³ de hielo son unos 3186 kg: un témpano de poco más de 1,5 m × 1,5 m × 1,5 m sosteniendo a un oso de 354 kg. Razonable. ▸ Si te da 35,4 o 0,354, revisá dónde se te fue un factor 10 (casi siempre en g).'},

  {st: '<b>Examen Final 14/02/24 · UTN FRBA · Problema 6</b><br><br>6) Un gran bloque de hielo (densidad 917 kg/m³) flota en agua de mar (densidad 1030 kg/m³). ¿Si el área superficial del hielo es 20 m² y tiene 0,20 m de espesor, cuál es la masa del oso polar más pesado que puede estar parado en el hielo sin que se moje las patas?<br><br><span class="muted">Encabezado de la hoja: "Para aprobar se requiere el 50% del examen bien resuelto. Utilice cuando sea necesario |g| = 10 m/s²."</span>',
   ans: 'm_oso = 452 kg',
   sol: '<b>Sistema de referencia e hipótesis.</b> Eje y positivo hacia arriba; equilibrio. <b>Traducción de la consigna:</b> "sin que se moje las patas" = el agua llega justo hasta la cara superior de la placa ⟹ <b>la placa queda totalmente sumergida</b>, que es el máximo empuje posible. g = 10 m/s².<br><br><b>Paso 1 · Volumen de la placa.</b><br>V = A · e = 20 m² · 0,20 m = <b>4 m³</b><br><br><b>Paso 2 · Equilibrio del conjunto hielo + oso.</b><br>E = P_hielo + P_oso<br>δ_mar·V·g = δ_hielo·V·g + m_oso·g<br><br><b>Paso 3 · Cancelá g y despejá.</b><br>m_oso = (δ_mar − δ_hielo)·V = (1030 − 917)·4 = 113·4<br><b>m_oso = 452 kg</b><br><br><b>Lo bueno de esta forma.</b> Al cancelar g te queda la fórmula de capacidad de carga directa: <b>m = (δ_L − δ_f)·V</b>. No hace falta calcular ningún peso.<br><br><b>Diferencia con el problema del 21/2/24.</b> Ahí te daban el <b>peso</b> del oso y pedían el <b>volumen</b> del témpano; acá te dan el <b>volumen</b> de la placa y piden la <b>masa</b> del oso. Es la misma ecuación despejada al revés — reconocerlo te ahorra la mitad del tiempo.'},

  {st: '<b>Examen Final 26/05/22 · Física I · Problema 2</b><br><br>2. Un cuerpo de forma rectangular de 10 cm de espesor está flotando en una laguna pequeña con tres cuartos de su volumen sumergido (densidad del agua: 1000 kg/m³). Si un camión cisterna derrama en la laguna aceite de densidad 0,65 g/cm³, quedando la cara superior del cuerpo justamente a nivel de la superficie del líquido. ¿Cuál es el espesor de la capa de aceite?',
   ans: 'H = 7,14 cm ≈ 0,0714 m',
   sol: '<b>Sistema de referencia e hipótesis.</b> Eje y positivo hacia arriba; equilibrio en las dos situaciones. El cuerpo es un prisma de área A (que se va a cancelar) y espesor e = 10 cm. Aceite: δ_ac = 0,65 g/cm³ = 650 kg/m³.<br><br><b>Paso 1 · Sacá la densidad del cuerpo de la situación INICIAL.</b> Flotación libre en agua con 3/4 sumergido:<br>V_sum/V = δ_c/δ_ag ⟹ 3/4 = δ_c/1000<br><b>δ_c = 750 kg/m³</b><br><br><b>Paso 2 · Interpretá la situación FINAL.</b> El aceite (más liviano) queda <b>arriba</b> formando una capa de espesor H. La cara superior del cuerpo está justo a nivel de la superficie del aceite, así que:<br>· la parte de arriba del cuerpo, de altura <b>H</b>, está en <b>aceite</b>;<br>· la parte de abajo, de altura <b>e − H</b>, está en <b>agua</b>.<br><br><b>Paso 3 · Dos líquidos ⟹ dos empujes.</b><br>P = E_aceite + E_agua<br>δ_c·A·e·g = δ_ac·A·H·g + δ_ag·A·(e − H)·g<br>El área A y g se cancelan:<br><b>δ_c·e = δ_ac·H + δ_ag·(e − H)</b><br><br><b>Paso 4 · Números (en cm, que es lo cómodo acá).</b><br>750·10 = 650·H + 1000·(10 − H)<br>7500 = 650H + 10 000 − 1000H<br>7500 = 10 000 − 350H<br>350H = 2500<br><b>H = 7,14 cm ≈ 7,1 cm (0,0714 m)</b><br><br><b>Controles.</b> ▸ H = 7,14 cm &lt; e = 10 cm: coherente, el cuerpo todavía tiene 2,86 cm dentro del agua. ▸ El cuerpo se hundió más que antes (ahora está 100% sumergido contra 75% antes) porque el aceite es <b>menos denso</b> que el agua y empuja menos. ▸ Si te da H &gt; 10 cm, revisá: significaría que el cuerpo flota entero en el aceite, imposible con δ_c = 750 &gt; 650.'}
]);

// --- SECCIÓN 4 · El único de hidrodinámica que cayó en parcial ---
registerReveals('fisica1-utn-fluidos', '4', [
  {st: '<b>1er parcial 22/10/09 · TEMA 1 · UTN FRBA · Dra. Patricia Martinelli · Problema 3</b><br><br>3) Una bomba de agua mantiene el caudal constante ( 25lt/min) a lo largo de una cañería horizontal; a la salida de la bomba el diámetro es de 7cm y la presión 6 Pa, luego el diámetro disminuye gradualmente hasta tener una sección de 30 cm2. Considere que la viscosidad es despreciable.<br><br>a) Calcule la presión del fluido en la parte mas estrecha.<br>b) Si la cañería tuviera un desnivel de 1m cambiaria el resultado anterior, justifique.',
   ans: 'a) P₂ = 22,17 din/cm² = 2,22 Pa &nbsp;·&nbsp; b) Sí cambia: aparece el término δ·g·(h₂ − h₁), que con 1 m vale 10⁵ din/cm² (10⁴ Pa), enormemente mayor que las presiones del inciso a)',
   sol: '<b>Hipótesis (declaralas, la cátedra las puntúa).</b> Fluido ideal: incompresible (agua, δ = 1 g/cm³), <b>no viscoso</b> (lo dice el enunciado), <b>régimen estacionario</b> ("caudal constante") y sin turbulencia ("el diámetro disminuye <b>gradualmente</b>"). Cañería <b>horizontal</b> en el inciso a) ⟹ h₁ = h₂. Trabajo en CGS.<br><br><b>Paso 0 · Numerá los puntos y convertí todo.</b><br>Punto 1 = salida de la bomba (D = 7 cm). Punto 2 = donde S = 30 cm².<br>Q = 25 l/min = 25 000 cm³ / 60 s = <b>416,67 cm³/s</b><br>P₁ = 6 Pa = <b>60 din/cm²</b> &nbsp;<span class="muted">(1 Pa = 10 din/cm²)</span><br>S₁ = π·r₁² = π·(3,5 cm)² = <b>38,48 cm²</b> &nbsp;<span class="muted">(el dato es el DIÁMETRO: r = 3,5 cm)</span><br>S₂ = <b>30 cm²</b> &nbsp;<span class="muted">(este viene ya como área)</span><br><br><b>Paso 1 · Continuidad ⟹ las velocidades.</b><br>v₁ = Q/S₁ = 416,67 / 38,48 = <b>10,83 cm/s</b><br>v₂ = Q/S₂ = 416,67 / 30 = <b>13,89 cm/s</b><br>Como S₂ &lt; S₁, efectivamente v₂ &gt; v₁. ✔<br><br><b>Paso 2 · Bernoulli horizontal ⟹ la presión.</b><br>P₁ + ½·δ·v₁² = P₂ + ½·δ·v₂²<br>P₂ = P₁ + ½·δ·(v₁² − v₂²)<br>P₂ = 60 + ½·1·(117,3 − 192,9) = 60 − 37,8<br><b>P₂ = 22,17 din/cm² = 2,22 Pa</b><br><br><b>Paso 3 · Inciso b) — no alcanza con decir "sí".</b> Con desnivel, Bernoulli lleva el tercer término:<br>P₁ + ½δv₁² + δ·g·h₁ = P₂ + ½δv₂² + δ·g·h₂<br>P₂ = P₁ + ½δ(v₁² − v₂²) <b>+ δ·g·(h₁ − h₂)</b><br>· Las <b>velocidades no cambian</b>: dependen solo de Q y de las secciones, no de la altura.<br>· Con Δh = 1 m = 100 cm: δ·g·Δh = 1 · 1000 · 100 = <b>10⁵ din/cm² = 10⁴ Pa</b>.<br>· <b>Si el punto 2 está más bajo</b> (h₂ &lt; h₁), P₂ <b>aumenta</b> en 10⁵ din/cm². <b>Si está más alto</b>, disminuye en lo mismo.<br>· Magnitud: ese término es <b>miles de veces</b> más grande que los 60 din/cm² del enunciado. El desnivel domina completamente.<br><br><b>Trampas de este ejercicio.</b> ▸ El dato de arriba es <b>diámetro</b> (7 cm) y el de abajo es <b>área</b> (30 cm²): mezclarlos es el error más caro. ▸ 6 Pa = 60 din/cm², no 6 ni 600. ▸ Hay que usar continuidad <b>y</b> Bernoulli: con una sola no cierra. ▸ Control de signo: caño horizontal que se angosta ⟹ P₂ &lt; P₁ siempre.<br><br><span class="muted">Nota física: 6 Pa es una presión absurdamente baja para la salida de una bomba real (es 17 000 veces menos que la atmosférica). Es un dato de enunciado, no un valor realista — usalo tal cual viene y seguí.</span>'}
]);

// --- SECCIÓN 5 · Los 4 problemas de hidrodinámica del final ---
registerReveals('fisica1-utn-fluidos', '5', [
  {st: '<b>Examen Final UTN.BA · hoja sin encabezado visible (aparece idéntico en dos hojas de final distintas) · Problema 3</b><br><br>3- Un tanque hermético, de gran volumen de agua, está presurizado y en su parte superior hay aire a una presión p0 = 202.600 Pa. Dicho tanque presenta un orificio pequeño a una profundidad h. Se sabe que la presión en el punto A, que está a la misma profundidad h que el orificio, pero muy lejos de éste, es pA = 207600 Pa. El tanque está lleno hasta una altura H = 4 m. Determine La distancia horizontal d que llegará el fluido, medido desde el borde del tanque.',
   ans: 'h = 0,5 m · v = 14,58 m/s · t = 0,837 s · <b>d ≈ 12,2 m</b>',
   sol: '<b>Hipótesis.</b> Fluido ideal; "gran volumen" y "orificio pequeño" ⟹ la velocidad de descenso de la superficie libre es despreciable (v₁ ≈ 0). Tomo p_atm = 101 300 Pa (el enunciado te lo insinúa: p₀ = 202 600 Pa es <b>exactamente 2 atm</b>). δ_agua = 1000 kg/m³, g = 10 m/s².<br><br><b>Paso 1 · Sacá h con HIDROSTÁTICA.</b> El punto A está "muy lejos del orificio" ⟹ fluido en reposo:<br>pA = p₀ + δ·g·h<br>207 600 = 202 600 + 1000·10·h<br>5000 = 10 000·h ⟹ <b>h = 0,5 m</b><br><br><b>Paso 2 · Velocidad de salida con BERNOULLI.</b> Punto 1 = superficie libre (p = p₀, v ≈ 0). Punto 2 = orificio (p = p_atm, altura h por debajo del 1).<br>p₀ + δ·g·h = p_atm + ½·δ·v²<br>½·1000·v² = 202 600 + 5000 − 101 300 = <b>106 300</b><br>v² = 212,6 ⟹ <b>v = 14,58 m/s</b><br><span class="muted">(Atajo equivalente: ½δv² = pA − p_atm, porque pA ya incluye p₀ + δgh.)</span><br><br><b>Paso 3 · Altura de caída del chorro.</b> Acá está la trampa: la altura de caída <b>no es h</b>. El agua llega hasta H = 4 m y el orificio está 0,5 m por debajo de la superficie:<br><b>y = H − h = 4 − 0,5 = 3,5 m</b><br><br><b>Paso 4 · Tiro horizontal.</b> Sale horizontal con v y cae desde y:<br>t = √(2y/g) = √(2·3,5/10) = √0,7 = <b>0,837 s</b><br>d = v·t = 14,58 · 0,837 = <b>12,2 m</b><br><br><b>Los tres errores que este problema busca.</b> ▸ Creer que la p_atm se cancela: <b>no se cancela</b>, porque el tanque está presurizado a p₀ ≠ p_atm. ▸ Usar h = 0,5 m como altura de caída (te daría d = 4,6 m). ▸ Usar Torricelli pelado v = √(2gh) = 3,16 m/s, ignorando la presurización.'},

  {st: '<b>Examen Final UTN.BA · hoja sin encabezado visible (aparece idéntico en dos hojas de final distintas) · Problema 6</b><br><br>6- Una cañería horizontal, con sección circular de 25 mm de diámetro interior, transporta agua de densidad 1 kg/dm³ con velocidad de 1 m/s y a la presión de 10⁵ Pa. En cierto lugar la cañería reduce su diámetro interior a 12mm y desciende 3m, con respecto al nivel inicial. Determine, la presión que tendrá el agua en el nuevo nivel.',
   ans: 'v₂ = 4,34 m/s · <b>p₂ ≈ 1,21·10⁵ Pa (121 081 Pa)</b>',
   sol: '<b>Hipótesis.</b> Fluido ideal, régimen estacionario. δ = 1 kg/dm³ = <b>1000 kg/m³</b> (1 dm³ = 1 litro = 1000 cm³). g = 10 m/s². Punto 1 = tramo ancho y alto; punto 2 = tramo angosto y 3 m más abajo.<br><br><b>Paso 1 · Continuidad ⟹ v₂.</b> Los datos son <b>diámetros</b>, y como A ∝ D², la razón de velocidades va con el cuadrado:<br>v₂ = v₁·(D₁/D₂)² = 1 · (25/12)² = 1 · 4,340<br><b>v₂ = 4,34 m/s</b><br><span class="muted">(equivalentemente: A₁ = π·0,0125² = 4,909·10⁻⁴ m², A₂ = π·0,006² = 1,131·10⁻⁴ m²)</span><br><br><b>Paso 2 · Bernoulli COMPLETA.</b> Tomo el nivel de referencia en el punto 2 ⟹ h₁ = 3 m, h₂ = 0:<br>p₁ + ½δv₁² + δ·g·h₁ = p₂ + ½δv₂² + δ·g·h₂<br>p₂ = p₁ + ½δ(v₁² − v₂²) + δ·g·(h₁ − h₂)<br><br><b>Paso 3 · Término por término.</b><br>· Venturi: ½·1000·(1² − 4,34²) = 500·(1 − 18,84) = <b>−8919 Pa</b><br>· Altura: 1000·10·3 = <b>+30 000 Pa</b><br>p₂ = 100 000 − 8919 + 30 000<br><b>p₂ = 121 081 Pa ≈ 1,21·10⁵ Pa</b><br><br><b>La lectura del resultado.</b> La presión final es <b>mayor</b> que la inicial, aunque el caño se angoste. ▸ Bajar 3 m de agua aporta 30 000 Pa; el estrechamiento solo quita 8919 Pa. <b>Gana la altura</b>, y por goleada. ▸ Regla mental: <b>1 m de columna de agua ≈ 10 000 Pa</b>. Cualquier desnivel de metros aplasta a los términos dinámicos de velocidades chicas.<br><br><b>Errores típicos.</b> ▸ Olvidar el cuadrado en la razón de diámetros (te da v₂ = 2,08 y todo mal). ▸ Poner el signo de δgΔh al revés (te daría 61 081 Pa). ▸ Usar 1 kg/dm³ como 1 kg/m³.'},

  {st: '<b>Examen Final UTN.BA · hoja sin encabezado visible (aparece idéntico en dos hojas de final distintas) · Problema 4</b><br><br>4. La figura ilustra un tanque de gasolina con área transversal A1, lleno hasta una altura h = 1 m. El espacio arriba de la gasolina está con aire comprimido a una presión p0 = 130,1 kPa y la gasolina sale a la atmósfera por un tubo muy corto de área A2. Se asume que A2 es mucho menor que A1, de modo que pueda despreciarse la velocidad del fluido en esta última sección. Sabiendo que la densidad de la gasolina es δ = 720 kg/m³, determine la velocidad con la que sale la misma por el tubo inferior. Dato: p_atm = 101,3 kPa.',
   ans: 'v = 10 m/s',
   sol: '<b>Hipótesis.</b> Fluido ideal. El propio enunciado te regala la hipótesis clave: <b>A₂ ≪ A₁ ⟹ v₁ ≈ 0</b> en la superficie libre. g = 10 m/s².<br><br><b>Paso 0 · Unidades.</b> p₀ = 130,1 kPa = <b>130 100 Pa</b>; p_atm = 101,3 kPa = <b>101 300 Pa</b>.<br><br><b>Paso 1 · Elegí los puntos.</b><br>Punto 1 = superficie de la gasolina: p₁ = p₀, v₁ ≈ 0, altura h = 1 m.<br>Punto 2 = salida del tubo: p₂ = p_atm, altura 0 (nivel de referencia acá).<br><br><b>Paso 2 · Bernoulli.</b><br>p₀ + ½δ·0² + δ·g·h = p_atm + ½·δ·v² + 0<br>½·δ·v² = (p₀ − p_atm) + δ·g·h<br><br><b>Paso 3 · Números.</b><br>p₀ − p_atm = 130 100 − 101 300 = <b>28 800 Pa</b> &nbsp;<span class="muted">(el aporte de la presurización)</span><br>δ·g·h = 720·10·1 = <b>7200 Pa</b> &nbsp;<span class="muted">(el aporte de la columna)</span><br>½·720·v² = 36 000 ⟹ 360·v² = 36 000<br>v² = 100 ⟹ <b>v = 10 m/s</b><br><br><b>Cómo leerlo.</b> Es <b>Torricelli con un empujón</b>: si el tanque estuviera abierto, v = √(2gh) = √20 = 4,47 m/s. La sobrepresión del aire comprimido (28 800 Pa, cuatro veces el aporte de la columna) más que duplica la velocidad de salida.<br><br><b>Errores típicos.</b> ▸ Dejar los kPa sin pasar a Pa. ▸ Cancelar la atmosférica (no se puede: adentro hay p₀, afuera p_atm, y son distintas). ▸ Usar la densidad del agua en vez de la de la gasolina: δ = 720, no 1000.'},

  {st: '<b>Examen Final 13/2/25 · UTN.BA</b> <span class="muted">(el enunciado del final está incompletamente recordado en la recreación que hicieron los alumnos — "En un tubo de venturi, se halla un resorte… Pide hallar la compresión del resorte. K = (nos la da). No recuerdo qué datos da". El propio documento adjunta este ejercicio "parecido" completo y con respuestas, y aclara: "único que nos daba la altura en el final, pedía sacar la contracción nomás". Es el que conviene estudiar.)</span><br><br>Se tiene un tubo en U de sección uniforme S = 10 cm² con uno de sus extremos cerrado y el otro abierto. Al extremo cerrado está sujeto un resorte de constante elástica k = 50 N/m fijo a un émbolo como indica la figura. Considere que en la cámara que contiene al resorte hay aire a presión atmosférica. Se vierte agua (δ = 1 g/cm³) por el extremo abierto del tubo hasta que el nivel de la misma se encuentre a una altura h = 10 cm por encima del émbolo.<br>a) Calcule la compresión inicial Δxi del resorte.<br>A continuación se agrega en el brazo derecho del tubo una columna de aceite (δ = 0,8 g/cm³) de altura H hasta que el nivel del agua coincida con el del émbolo.<br>b) Calcule el valor de H.<br><br><span class="muted">Rta. de la hoja: a) Δxi = 2 cm ; b) H = 0,438 m</span>',
   ans: 'a) Δx_i = 0,02 m = 2 cm &nbsp;·&nbsp; b) H = 0,4375 m ≈ 0,438 m',
   sol: '<b>Hipótesis y datos en SI.</b> Todo en reposo ⟹ <b>hidrostática pura</b> (acá no hay Bernoulli). S = 10 cm² = <b>10⁻³ m²</b>; k = 50 N/m; δ_ag = 1000 kg/m³; δ_ac = 800 kg/m³; h = 0,10 m; g = 10 m/s². Émbolo de masa despreciable.<br><br><b>Paso 1 · DCL del émbolo (inciso a).</b> Tres fuerzas verticales:<br>· El <b>agua desde abajo</b> lo empuja hacia arriba con (p_atm + δ_ag·g·h)·S. <span class="muted">Esa es la presión del agua a la altura del émbolo, porque en la rama abierta el agua está h por encima.</span><br>· El <b>aire de la cámara</b> lo empuja hacia abajo con p_atm·S (el enunciado aclara que está a presión atmosférica).<br>· El <b>resorte comprimido</b> empuja hacia abajo con k·Δx.<br><br>(p_atm + δ_ag·g·h)·S = p_atm·S + k·Δx_i<br>La atmosférica <b>se cancela</b>:<br><b>δ_ag·g·h·S = k·Δx_i</b><br><br><b>Paso 2 · Números del inciso a).</b><br>δ_ag·g·h = 1000·10·0,10 = 1000 Pa<br>Fuerza neta del agua: 1000 Pa · 10⁻³ m² = <b>1 N</b><br>Δx_i = 1 N / 50 N/m = <b>0,02 m = 2 cm</b> ✔<br><br><b>Paso 3 · El paso geométrico del inciso b) (el que casi nadie ve).</b> Al agregar aceite, la presión sobre el émbolo aumenta y el émbolo <b>sube</b> una distancia δ, comprimiendo más el resorte. Pero el agua es la misma: si el émbolo sube δ, el agua de la rama izquierda ocupa ese espacio y <b>el nivel de la rama derecha baja δ</b>.<br>· Nivel inicial del agua (derecha) = posición del émbolo + 0,10 m.<br>· Nivel final del agua = émbolo_inicial + 0,10 − δ. Posición final del émbolo = émbolo_inicial + δ.<br>· El enunciado pide que <b>coincidan</b>: 0,10 − δ = δ ⟹ <b>δ = 0,05 m</b>.<br><b>Δx_f = Δx_i + δ = 0,02 + 0,05 = 0,07 m</b><br><br><b>Paso 4 · Equilibrio final del émbolo.</b> Ahora, a la altura del émbolo, la columna que hay encima en la rama derecha es <b>solo aceite</b> (el agua quedó justo al nivel del émbolo):<br>(p_atm + δ_ac·g·H)·S = p_atm·S + k·Δx_f<br><b>δ_ac·g·H·S = k·Δx_f</b><br>800·10·H·10⁻³ = 50·0,07<br>8·H = 3,5<br><b>H = 0,4375 m ≈ 0,438 m</b> ✔<br><br><b>Por qué este ejercicio es difícil.</b> No es la física: son las <b>dos ecuaciones acopladas</b>. La de fuerzas (presión ↔ resorte) y la de <b>conservación del volumen de agua</b> (émbolo sube δ ⟹ nivel derecho baja δ). Si te olvidás de la segunda, planteás δ_ac·g·H·S = k·(0,02) y te da H = 0,125 m, que es la respuesta equivocada más común.<br><br><b>Chequeo de coherencia.</b> Hacen falta 43,75 cm de aceite (δ = 0,8) para lograr lo mismo que harían 35 cm de agua: el líquido más liviano necesita <b>columna más alta</b>. ✔'}
]);
