registerExercises('analisis-parcial', '1', [
  {st: 'Si en el enunciado aparece "intervalo cerrado [a, b]" + "máximo y mínimo absolutos", la receta es:', opts: ['Calcular f\'(x) y verlo en cualquier punto', 'Aplicar Weierstrass: evaluar f en los bordes a, b y en los críticos interiores', 'Aplicar L\'Hôpital', 'Buscar la asíntota'], c: 1, ex: 'Weierstrass: si f es continua en [a,b] cerrado, los extremos absolutos EXISTEN y solo pueden estar en 3 lugares: ▸ los bordes a y b, ▸ los puntos críticos interiores. Evaluás f en todos y comparás. ▸ Por qué las otras están mal: (A) f\' aporta info de monotonía pero no resuelve el problema; (C) L\'Hôpital es para límites indeterminados; (D) asíntotas no aplican en intervalo cerrado.'},
  {st: 'Si te dan "la tangente a f en x₀ = 1 es y = 3x + 1", lo PRIMERO que anotás al margen es:', opts: ['f(1) = 1 y f\'(1) = 3', 'f\'(1) = 3 y f(1) = 4', 'f(3) = 1', 'No se puede saber sin más datos'], c: 1, ex: 'La tangente y = mx + b da DOS datos gratis: ▸ Pendiente: f\'(x₀) = m = 3. ▸ Punto: f(x₀) = m·x₀ + b = 3·1 + 1 = 4. ▸ Por qué las otras están mal: (A) confunde valor con coef; (C) usa el 3 de la pendiente como x; (D) sí se puede.'},
  {st: 'Reemplazás en el límite y obtenés "0/0". ¿Qué hacés?', opts: ['Eso es 0, listo', 'Es indeterminación: aplicá factorización, conjugado, notable o L\'Hôpital según el tipo', 'Aplicás siempre L\'Hôpital sin pensar', 'El límite no existe'], c: 1, ex: '0/0 NO es valor, es INDETERMINACIÓN. Hay que "levantarla". Técnicas: ▸ Polinomios → factorizar y simplificar. ▸ Raíces → multiplicar por conjugado. ▸ Trig/log/exp → notables o L\'Hôpital. ▸ Por qué las otras están mal: (A) "0" es solo un caso particular; (C) L\'Hôpital aplicado a ciegas a veces complica; (D) puede existir.'},
  {st: 'En la fórmula del e: lim (1 + α(x))^β(x), las condiciones son:', opts: ['α → 1 y β → 0', 'α → 0 y β → ∞', 'α y β → ∞', 'No hay condiciones'], c: 1, ex: 'Forma 1^∞: la "parte chica" α tiende a 0 (para que 1+α → 1) y el exponente β tiende a ∞. ▸ Resultado: e^(lim α·β). ▸ Por qué las otras están mal: (A) base 2, no 1^∞; (C) sería ∞^∞; (D) sí hay condiciones para aplicar el notable.'},
  {st: 'En "continuidad con parámetro", la receta es:', opts: ['Calcular f\'(x) y evaluarla', 'Calcular el límite, igualarlo a f(x₀), despejar el parámetro', 'Hacer Bolzano', 'Buscar las asíntotas'], c: 1, ex: 'Continuidad en x₀: lim_{x→x₀} f(x) = f(x₀). Como f(x₀) tiene parámetro, calculás el límite y despejás. ▸ Por qué las otras están mal: (A) la derivada no se relaciona; (C) Bolzano es para raíces; (D) asíntotas no entran.'}
]);

registerExercises('analisis-parcial', '2', [
  {st: '¿Por qué el primer paso del estudio de función es el dominio (y no la derivada)?', opts: ['Por costumbre', 'Porque cualquier crítico que encuentres después debe estar en el dominio para ser válido', 'No es importante el orden', 'Para ahorrar tinta'], c: 1, ex: 'Si calculás f\' antes que el dominio, podrías incluir críticos fuera del dominio (típico con ln o √). Trampa frecuente. ▸ Por qué las otras están mal: (A) (D) trivialidades; (C) sí importa.'},
  {st: 'Si f\'(x) = (x − 7)/(x − 4)², ¿cuál es el signo de f\' en (4, 7)?', opts: ['Positivo', 'Negativo', 'Cero', 'No se puede saber'], c: 1, ex: 'Análisis de signo: ▸ (x−4)² siempre &gt; 0. ▸ (x−7) en (4,7) es negativo. ▸ Producto: negativo. → f decrece en (4,7). ▸ Por qué las otras están mal: (A) sería en (7,+∞); (C) en x=7; (D) sí se puede.'},
  {st: 'En el estudio de f(x) = 6x/(16x²+1), los puntos críticos son x = ±1/4. La imagen es:', opts: ['ℝ', '[f(−1/4), f(1/4)] = [−3/8, 3/8]... revisar', '[−3/4, 3/4]', '(0, +∞)'], c: 2, ex: 'f(1/4) = 6·(1/4)/(16·1/16+1) = (3/2)/2 = 3/4. f(−1/4) = −3/4. f(±∞) → 0. ▸ Decrece en (−∞,−1/4): de 0 a −3/4. Crece en (−1/4,1/4): de −3/4 a 3/4. Decrece en (1/4,+∞): de 3/4 a 0. ▸ Imagen: [−3/4, 3/4]. ▸ Por qué las otras están mal: (A) no llega a todo ℝ; (B) tiene cálculo erróneo; (D) incluye negativos.'},
  {st: 'Para f(x) = √x · e^(−36x²+2), el dominio es:', opts: ['ℝ', '[0, +∞)', '(0, +∞)', 'ℝ − {0}'], c: 1, ex: 'Raíz par exige radicando ≥ 0: x ≥ 0 (x=0 está bien, √0=0 definida). Exponencial sin restricción. ▸ Por qué las otras están mal: (A) ℝ incluye negativos donde √ no existe; (C) excluye 0 que SÍ está; (D) excluye 0.'},
  {st: 'En f(x) = √x · e^(−36x²+2), la imagen es:', opts: ['(0, f(1/12)]', '[0, f(1/12)]', '(0, +∞)', 'ℝ'], c: 1, ex: 'f(0) = 0 (alcanzado, pertenece a la imagen). Crece hasta máximo en x=1/12 (alcanzado). Decrece y → 0 (sin alcanzar otra vez, asintóticamente). ▸ Imagen: [0, f(1/12)]. ▸ Por qué las otras están mal: (A) excluye 0 que SÍ se alcanza; (C) (D) demasiado amplias.'},
  {st: 'Para encontrar la imagen necesitás:', opts: ['Solo el dominio', 'Solo los críticos', 'Los valores en los críticos + los límites en los bordes del dominio', 'La derivada segunda'], c: 2, ex: 'La imagen son los valores que f toma. Para mapearla: ▸ Críticos = techos y pisos locales (extremos). ▸ Límites en bordes = a dónde se va. ▸ Por qué las otras están mal: (A) (B) parciales; (D) la 2ª derivada es para concavidad, no imagen.'}
]);

registerExercises('analisis-parcial', '3', [
  {st: 'Para f(x) = (cos(5x) − 1)/x² con f(0) = k − 1/2 continua, k =', opts: ['12', '−12', '−25/2', '0'], c: 1, ex: 'Notable: (cos(u)−1)/u² → −1/2. Con u=5x: (cos(5x)−1)/(5x)² · 25 → −1/2 · 25 = −25/2. ▸ Igualar: k − 1/2 = −25/2 → k = −12. ▸ Por qué las otras están mal: (A) signo invertido; (C) "−25/2" es el valor del límite, no k; (D) k=0 daría f(0)=−1/2 (no coincide).'},
  {st: 'Para f(x) = ln(1+x²)/(e^(x²)−1) con f(0) = 2a − 3 continua, a =', opts: ['1', '2', '3', '−2'], c: 1, ex: 'Sea u = x² → 0. ln(1+u)/u → 1 y u/(e^u−1) → 1. Producto → 1·1 = 1. ▸ Igualar: 2a−3 = 1 → a = 2. ▸ Por qué las otras están mal: (A) a=1 → −1; (C) a=3 → 3; (D) a=−2 → −7.'},
  {st: 'Si reemplazando en el límite obtenés algo finito (NO indeterminación), ¿qué hacés?', opts: ['Aplicás L\'Hôpital igual', 'Ese es directamente el valor del límite', 'Conjugado', 'Reemplazar por otro valor'], c: 1, ex: 'L\'Hôpital aplica SOLO con 0/0 o ∞/∞. Si reemplazo da finito, no hay nada que levantar: ese ES el límite. ▸ Por qué las otras están mal: (A) aplicar L\'Hôpital sin indeterminación es un error grave; (C) (D) no tienen sentido.'},
  {st: 'Para f(x) = a·sen²(ax)/x² con f(0) = 64 continua, a =', opts: ['4', '8', '64', '−4'], c: 0, ex: 'a·sen²(ax)/x² = a·a²·(sen(ax)/(ax))² → a³·1 = a³. ▸ Igualar: a³ = 64 → a = 4. ▸ Por qué las otras están mal: (B) 8³=512; (C) "64" es el límite, no a; (D) a=−4 daría a³=−64.'},
  {st: 'En continuidad con parámetro, ¿cuál es el último paso?', opts: ['Calcular el límite', 'Igualar a f(x₀)', 'Despejar el parámetro', 'Verificar que f sea continua en otros puntos'], c: 2, ex: 'Receta de 3 pasos: (1) calcular el límite, (2) igualar a f(x₀) que tiene el parámetro, (3) DESPEJAR. ▸ Por qué las otras están mal: (A) (B) son pasos previos; (D) la verificación en otros puntos no se exige aquí.'}
]);

registerExercises('analisis-parcial', '4', [
  {st: 'Tangente a f en x₀=1 es y = 3x+1. h(x) = 3 + f(7x + e^x). h\'(0) =', opts: ['3', '8', '24', '7'], c: 2, ex: 'De la tangente: f\'(1)=3, f(1)=4. ▸ Cadena: h\'(x) = f\'(7x+e^x)·(7+e^x). ▸ En x=0: argumento = 0+1 = 1 (¡cierra con f\'(1)!), factor = 7+1 = 8. h\'(0) = f\'(1)·8 = 3·8 = 24. ▸ Por qué las otras están mal: (A) sólo f\'(1); (B) sólo el factor; (D) sin la f\'.'},
  {st: 'Misma h del ejercicio anterior. La recta tangente a h en x₀=0 es:', opts: ['y = 24x', 'y = 24x + 7', 'y = 7x + 24', 'y = 3x + 7'], c: 1, ex: 'h(0) = 3 + f(1) = 3+4 = 7. h\'(0) = 24. Tangente: y − 7 = 24(x − 0) → y = 24x + 7. ▸ Por qué las otras están mal: (A) sin la ordenada; (C) intercambia m y b; (D) usa la pendiente original f\'(1).'},
  {st: 'Tangente a f en x=1 es y = 8x − 6. h(x) = ln(f(x)) + e^sen(x−1). h\'(1) =', opts: ['8', '5', '2', '0'], c: 1, ex: 'f\'(1)=8, f(1)=8−6=2. ▸ h\'(x) = f\'(x)/f(x) + e^sen(x−1)·cos(x−1). ▸ En x=1: 8/2 + e^0·cos(0) = 4 + 1 = 5. ▸ Por qué las otras están mal: (A) sólo f\'(1); (C) sólo el cos(0); (D) "0" no surge.'},
  {st: 'Tangente a f en x=1 es y = 4x − 2. h(x) = ln(f(x)) + e^sen(x−1). h\'(1) =', opts: ['1', '2', '3', '4'], c: 2, ex: 'f\'(1)=4, f(1)=2. ▸ h\'(1) = 4/2 + 1·1 = 2+1 = 3. ▸ Por qué las otras están mal: (A) "1" sería sólo el segundo término; (B) "2" sólo el primero; (D) "4" es f\'(1).'},
  {st: '¿Por qué x=0 "cierra" perfectamente cuando la tangente está en x₀=1, en h(x) = 3 + f(7x + e^x)?', opts: ['Casualidad', 'Porque 7·0 + e^0 = 1, justo el x₀ donde tenemos f\'', 'Porque h(0) = 0', 'Porque la cadena así lo exige'], c: 1, ex: 'EN TODO PARCIAL, el x donde piden h\' está elegido para que el argumento interno caiga en x₀ donde te dieron la tangente. Eso "cierra" el ejercicio. ▸ Por qué las otras están mal: (A) no es casualidad; (C) h(0)=7, no 0; (D) la cadena no lo exige por sí misma.'},
  {st: 'En f(x) = 2e^(x−1) + sen(1−x) − 3x·ln(2x−1), f\'(1) =', opts: ['−5', '5', '0', '−2'], c: 0, ex: 'Derivar término a término. ▸ 2e^(x−1) → 2e^(x−1) en x=1: 2. ▸ sen(1−x) → −cos(1−x) en 1: −1. ▸ −3x·ln(2x−1) (producto): −3·[ln(2x−1) + 2x/(2x−1)]. En x=1: −3·[ln(1) + 2] = −3·2 = −6. ▸ Suma: 2 − 1 − 6 = −5. ▸ Por qué las otras están mal: (B) signo; (C) (D) cálculos parciales.'}
]);

registerExercises('analisis-parcial', '5', [
  {st: 'lim x→+∞ √(x²+12x) − √(x²+13) =', opts: ['0', '6', '12', '+∞'], c: 1, ex: '∞−∞ con raíces → CONJUGADO. Multiplico por (√(x²+12x) + √(x²+13))/(idem): numerador queda (x²+12x) − (x²+13) = 12x−13. Denominador ≈ 2x para x grande. Cociente → 12x/(2x) = 6. ▸ Por qué las otras están mal: (A) si fueran iguales; (C) sin dividir entre 2; (D) si fuera ∞·∞.'},
  {st: 'Si la tangente a f en x=1 es y = 3x + 2, lim x→1 [f(4x−3) − 5]/(x²−1) =', opts: ['3', '6', '12', '0'], c: 1, ex: 'De la tangente: f(1)=5, f\'(1)=3. ▸ Reemplazo: f(1)−5=0 / 1−1=0. 0/0. ▸ L\'Hôpital con cadena: 4·f\'(4x−3)/(2x). En x=1: argumento=1, así uso f\'(1)=3 → 4·3/2 = 6. ▸ Por qué las otras están mal: (A) (C) cálculos parciales; (D) "0" si ignoras la cadena.'},
  {st: 'lim x→3 (2x − 6)/(4√(x+1) − 8) =', opts: ['0', '1', '2', '4'], c: 2, ex: '0/0 con raíz → CONJUGADO. Multiplico por (4√(x+1)+8)/(idem). Después de simplificar (x−3) queda (4√(x+1)+8)/8. En x=3: (4·2+8)/8 = 16/8 = 2. ▸ Por qué las otras están mal: las otras son cálculos intermedios o errores comunes.'},
  {st: 'Para resolver lim x→0 (e^(2x) − 1)/x usás:', opts: ['Conjugado', 'Notable: vale 2', 'Factorización', 'No se puede'], c: 1, ex: '0/0 con exponencial. ▸ Notable: (e^u−1)/u → 1. Con u=2x: (e^(2x)−1)/(2x) · 2 → 2. ▸ Por qué las otras están mal: (A) sin raíces no aplica; (C) no es polinomio; (D) sí se puede.'},
  {st: 'lim x→+∞ ln(x)/x =', opts: ['0', '1', '+∞', 'No existe'], c: 0, ex: '∞/∞. L\'Hôpital: (1/x)/1 = 1/x → 0. ▸ Intuición: el polinomio crece más rápido que el log. ▸ Por qué las otras están mal: (B) sería x/x; (C) "∞" si fuera al revés; (D) sí existe.'},
  {st: 'lim x→+∞ ((x²−1)/(x²−5))^(2x²+1) =', opts: ['1', 'e', 'e^4', 'e^8'], c: 3, ex: 'Forma 1^∞. Reescribo: (x²−1)/(x²−5) = 1 + 4/(x²−5). ▸ α·β = 4(2x²+1)/(x²−5). Grados iguales (2 y 2): cociente de líderes = 4·2/1 = 8. ▸ Resultado: e^8. ▸ Por qué las otras están mal: (A) sin notable; (B) (C) factor mal calculado.'},
  {st: 'Trampa típica: lim x→+∞ (x + sen x)/x. Si aplicás L\'Hôpital sale (1 + cos x)/1 que oscila. ¿Cuánto vale el límite real?', opts: ['No existe', '1', '0', '+∞'], c: 1, ex: 'Reescribo SIN L\'Hôpital: 1 + sen(x)/x. Como |sen x| ≤ 1 y x → ∞, sen(x)/x → 0. Total: 1+0 = 1. ▸ Moraleja: L\'Hôpital no siempre es la mejor herramienta. ▸ Por qué las otras están mal: (A) la oscilación de cos confunde, pero el límite real existe; (C) (D) no son los valores reales.'}
]);

registerExercises('analisis-parcial', '6', [
  {st: 'f(x) = 2x² − 9·ln(x) en [1, e]. ¿Dónde está el mínimo absoluto?', opts: ['x = 1', 'x = 3/2', 'x = e', 'No existe'], c: 1, ex: 'f\'(x) = 4x − 9/x = (4x²−9)/x. Crítico: 4x²=9 → x=3/2 (descarto −3/2 por ln). ▸ f(1)=2, f(3/2)≈0,85, f(e)≈5,78. Mínimo en x=3/2. ▸ Por qué las otras están mal: (A) (C) son extremos pero mayores; (D) sí existe (Weierstrass).'},
  {st: 'Misma función en [1, e]. ¿Dónde está el máximo absoluto?', opts: ['x = 1', 'x = 3/2', 'x = e', 'No existe'], c: 2, ex: 'Mismos valores: f(1)=2, f(3/2)≈0,85, f(e)≈5,78. Máximo en e (borde derecho). ▸ Lección: el máximo NO está en el crítico, está en el BORDE. ▸ Por qué las otras están mal: (A) menor que f(e); (B) es mín; (D) sí existe.'},
  {st: 'f(x) = 15x + 80/x³ en [1, 3]. ¿Dónde está el mínimo absoluto?', opts: ['x = 1', 'x = 2', 'x = 3', 'En un borde'], c: 1, ex: 'f\'(x) = 15 − 240/x⁴. Crítico: x⁴=16 → x=±2, solo x=2 ∈ (1,3). ▸ f(1)=95, f(2)=40, f(3)≈47,96. Mínimo en x=2. ▸ Por qué las otras están mal: (A) (C) bordes mayores; (D) "borde" no es preciso (es x=2, interior).'},
  {st: 'f(x) = 15x + 80/x³ en [1, 3]. ¿Dónde está el máximo absoluto?', opts: ['x = 1', 'x = 2', 'x = 3', 'No existe'], c: 0, ex: 'Mismos valores: f(1)=95, f(2)=40, f(3)≈47,96. Máximo en x=1 (borde izquierdo). ▸ Por qué las otras están mal: (B) es mín; (C) menor que f(1); (D) sí existe.'},
  {st: '¿Por qué Weierstrass garantiza que los extremos absolutos existen?', opts: ['Por casualidad', 'Por ser intervalo cerrado [a,b] y función continua', 'Por la derivada', 'Solo si hay críticos'], c: 1, ex: 'Teorema de Weierstrass: si f continua en [a,b] cerrado y acotado → existen máximo y mínimo absolutos. ▸ Si el intervalo es ABIERTO o f discontinua, NO se garantiza. ▸ Por qué las otras están mal: (A) es teorema; (C) la derivada localiza, no garantiza; (D) los críticos no son requisito (puede ser todo monótono).'},
  {st: '¿Cuál es el error #1 en máx/mín absolutos?', opts: ['Calcular mal la derivada', 'Olvidarse de evaluar en los BORDES del intervalo', 'No saber Weierstrass', 'Aplicar L\'Hôpital'], c: 1, ex: 'En muchos parciales el extremo verdadero está en un BORDE, no en el crítico. SIEMPRE evaluar en los 3 candidatos: a, b y críticos válidos. ▸ Por qué las otras están mal: errores menos frecuentes o menos graves.'}
]);

registerExercises('analisis-parcial', '7', [
  {st: 'lim x→+∞ ((x²+a)/(x²−6))^(2x²+1) = e^4. Hallar a.', opts: ['−2', '−4', '4', '6'], c: 1, ex: 'Reescribo: (x²+a)/(x²−6) = 1 + (a+6)/(x²−6). ▸ α·β = (a+6)(2x²+1)/(x²−6) → 2(a+6) (grados iguales, líderes 1). ▸ Igualar al exponente: 2(a+6) = 4 → a+6=2 → a=−4. ▸ Por qué las otras están mal: (A) (C) (D) no satisfacen la ecuación.'},
  {st: 'lim x→+∞ ((x²+a)/(x²−6))^(2x²+1) = e^6. Hallar a.', opts: ['−3', '0', '3', '6'], c: 0, ex: 'Mismo método: 2(a+6) = 6 → a+6=3 → a=−3. ▸ Por qué las otras están mal: (B) (C) (D) no satisfacen.'},
  {st: 'f(x) = sen²(x)/(2x) si x≠0, f(0)=0. f\'(0) =', opts: ['0', '1/2', '1', '2'], c: 1, ex: 'Cociente incremental: f\'(0) = lim h→0 [f(h)−f(0)]/h = lim h→0 [sen²(h)/(2h)]/h = lim sen²(h)/(2h²) = (1/2)·(sen h/h)² → 1/2·1 = 1/2. ▸ Por qué las otras están mal: cálculos parciales o ignoran el factor 1/2.'},
  {st: 'f(x) = (cos(6x)−1)/x si x>0, kx si x≤0. ¿Para qué k es derivable en 0?', opts: ['−18', '0', '18', '−6'], c: 0, ex: 'Primero verifico continuidad: lim_{x→0+} (cos(6x)−1)/x = 0 (notable da −18·x → 0). lim_{x→0−} kx = 0. Continua si f(0)=0 ✓. ▸ Derivada lateral derecha: lim_{h→0+} [(cos(6h)−1)/h]/h = lim (cos(6h)−1)/h² = −1/2·36 = −18. ▸ Lateral izquierda: lim_{h→0−} kh/h = k. ▸ Igualar: k = −18. ▸ Por qué las otras están mal: (B) (C) (D) signos o factores erróneos.'},
  {st: 'En "forma del e", ¿cómo reescribís (x²+1)/(x²−5)?', opts: ['1 + 6/(x²−5)', '6/(x²−5)', '1 + (x²+1)/(x²−5)', 'No se puede reescribir'], c: 0, ex: 'Sumo y resto 5: (x²−5+5+1)/(x²−5) = (x²−5)/(x²−5) + 6/(x²−5) = 1 + 6/(x²−5). Ahí α = 6/(x²−5) → 0 como necesita el notable. ▸ Por qué las otras están mal: (B) le falta el "1"; (C) deja la fracción original (no reescribe); (D) sí se puede.'}
]);

registerExercises('analisis-parcial', '8', [
  {st: 'En f(x) = (5x³+15x²)/(x²−9), ¿cuál es la asíntota oblicua?', opts: ['No tiene', 'y = 5x', 'y = 5x + 15', 'y = x'], c: 2, ex: 'Como no hay AH (grado num &gt; grado denom): busco AO. ▸ m = lim f(x)/x = lim (5x³+15x²)/(x³−9x) = 5. ▸ b = lim (f(x) − 5x) = lim (5x³+15x² − 5x³+45x)/(x²−9) = lim 15x²/(x²−9) ... wait. Recalculo: (5x³+15x²)−5x(x²−9) = 5x³+15x²−5x³+45x = 15x²+45x. Dividido entre x²−9 → 15. AO: y = 5x + 15. ▸ Por qué las otras están mal: (A) sí tiene; (B) le falta b; (D) m mal.'},
  {st: 'En f(x) = (5x³+15x²)/(x²−9), x = −3 es:', opts: ['Asíntota vertical', 'Un agujero (no es AV)', 'Un punto crítico', 'La imagen'], c: 1, ex: '5x³+15x² = 5x²(x+3); x²−9 = (x−3)(x+3). Cancelo (x+3): f(x) = 5x²/(x−3) para x ≠ −3. ▸ En x=−3: 45/(−6) = −15/2 (finito) → AGUJERO, no AV. ▸ Por qué las otras están mal: (A) factor cancelable no da AV; (C) crítico requiere f\'=0; (D) imagen es un conjunto, no un punto.'},
  {st: 'Si cos(g(x)) = (1+x)/2 y g(0) = π/3, entonces g\'(0) =', opts: ['√3/3', '−√3/3', '1/2', '−1/2'], c: 1, ex: 'Verifico: cos(π/3) = 1/2 = (1+0)/2 ✓. ▸ Derivada implícita: −sen(g(x))·g\'(x) = 1/2. ▸ En x=0: −sen(π/3)·g\'(0) = 1/2 → −(√3/2)·g\'(0) = 1/2 → g\'(0) = −1/√3 = −√3/3. ▸ Por qué las otras están mal: (A) signo invertido; (C) (D) no surgen.'},
  {st: 'En implícita, derivada de y² respecto de x (con y dependiente de x) es:', opts: ['2y', '2x·y', '2y·y\'', '2'], c: 2, ex: 'Cadena: el "afuera" es u² → 2u, el "adentro" es y → y\'. Producto: 2y·y\'. ▸ Por qué las otras están mal: (A) "2y" trata y como variable independiente; (B) "2xy" mezcla mal; (D) "2" es la derivada del exponente.'},
  {st: 'En implícita, derivada de xy respecto de x es:', opts: ['y\'', 'y + xy\'', 'x·y\'', 'xy\''], c: 1, ex: 'Producto: (xy)\' = (x)\'·y + x·(y)\' = 1·y + x·y\' = y + xy\'. ▸ Por qué las otras están mal: (A) (C) (D) olvidan algún término del producto.'}
]);

registerExercises('analisis-parcial', '9', [
  {st: 'Para f(x) = x² + 2/x, el dominio es:', opts: ['ℝ', 'ℝ − {0}', '(0, +∞)', '[0, +∞)'], c: 1, ex: '2/x exige x ≠ 0; x² está bien siempre. ▸ Por qué las otras están mal: (A) incluye 0 (división por cero); (C) (D) excluyen los negativos sin razón.'},
  {st: 'Para f(x) = x² + 2/x, el único punto crítico (en el dominio) es:', opts: ['x = 0', 'x = 1', 'x = 2', 'x = −1'], c: 1, ex: 'f\'(x) = 2x − 2/x² = (2x³−2)/x². Cero: 2x³=2 → x=1 (real). x=0 fuera del dominio. ▸ Por qué las otras están mal: (A) fuera del dominio; (C) (D) no anulan f\'.'},
  {st: 'Para f(x) = x² + 2/x, la imagen es:', opts: ['(0, +∞)', '[3, +∞)', '(−∞, 3]', 'ℝ'], c: 3, ex: 'Análisis: ▸ En x &gt; 0: tiene mín en x=1, f(1)=3. Crece a +∞ por ambos lados. Imagen parcial: [3, +∞). ▸ En x &lt; 0: x²&gt;0 pero 2/x&lt;0; cuando x → 0⁻, 2/x → −∞ (función baja); cuando x → −∞, x² → +∞ (función sube). Imagen parcial: ℝ (toma todos los valores). ▸ Combinando ambas ramas: ℝ. ▸ Por qué las otras están mal: (A) (B) (C) parciales.'},
  {st: 'Para f(x) = e^(2x)/(9x²+2), las asíntotas son:', opts: ['Solo y=0 en −∞', 'y=0 en ambos infinitos', 'AV en x=0', 'No tiene asíntotas'], c: 0, ex: '9x²+2 &gt; 0 siempre → no AV. ▸ lim_{x→−∞} e^(2x)/(...) → 0/+∞ = 0 → AH y=0 en −∞. ▸ lim_{x→+∞}: e^(2x) crece más rápido → +∞ → no AH ni AO en +∞. ▸ Por qué las otras están mal: (B) en +∞ no hay AH; (C) denominador no se anula; (D) sí tiene en −∞.'},
  {st: 'Para f(x) = e^(2x)/(9x²+2), los puntos críticos son:', opts: ['x = 0', 'x = 1/3', 'x = 1/3 y x = 2/3', 'x = 2/3'], c: 2, ex: 'f\'(x) = 2e^(2x)·(9x²−9x+2)/(9x²+2)². Resolver 9x²−9x+2=0: discriminante = 81−72 = 9. Raíces: (9±3)/18 = 12/18=2/3 ó 6/18=1/3. ▸ Por qué las otras están mal: (A) (B) (D) son cálculos parciales.'},
  {st: 'Para f(x) = e^(2x)/(9x²+2), la imagen es:', opts: ['ℝ', '[0, +∞)', '(0, +∞)', '(0, f(2/3))'], c: 2, ex: 'f &gt; 0 siempre (numerador y denominador positivos). lim_{−∞} = 0 (no alcanzado), lim_{+∞} = +∞. Toma todos los valores positivos. ▸ Imagen: (0, +∞). ▸ Por qué las otras están mal: (A) incluye negativos; (B) incluye 0 (no alcanzado); (D) demasiado restrictivo.'}
]);
