// Ejercicios PC · 2° Parcial — basados en parciales reales (Balbiano/Camejo 2023-2025)
registerExercises('pc-segundo-parcial', '1', [
  {st: '¿Cómo es el formato del 2° parcial de PC?', opts: ['Hay que escribir programas completos desde cero', 'Son entre 9 y 11 preguntas de opción múltiple (una sola correcta)', 'Es oral', 'Es un único ejercicio largo'], c: 1, ex: 'El 2° parcial es 100% opción múltiple: entre 9 y 11 preguntas, cada una con una sola respuesta correcta que se vuelca en una grilla. Nunca se escribe código desde cero: o predecís la salida, o elegís cuál de 4 versiones funciona. ▸ Por qué las otras: nunca se programa desde cero ni es oral; siempre son varias preguntas.'},
  {st: '¿Cuál es el tema que MÁS aparece en el 2° parcial?', opts: ['Recursión', 'map() y filter()', 'Ordenamiento de listas a mano', 'Clases y objetos'], c: 1, ex: 'map() y filter() aparecen en TODOS los parciales, normalmente 2 a 4 veces. Dominarlos asegura varios puntos. La segunda estrella son los diccionarios (clave → lista de datos). ▸ Por qué las otras: recursión, ordenamientos a mano y clases NO entran en este parcial.'},
  {st: 'Si una pregunta muestra <code>list(filter(func, datos))</code>, el tema es:', opts: ['Archivos', 'Funciones de orden superior (map/filter)', 'Pandas', 'Matplotlib'], c: 1, ex: 'map() y filter() son funciones de orden superior: reciben una función y una secuencia. filter deja los elementos donde la función devuelve True. ▸ Por qué las otras: archivos usa open/readlines; pandas usa df[...]; matplotlib usa ax/plt.'},
  {st: 'Abrir un archivo con <code>open("datos.txt", "w")</code> (modo write):', opts: ['Agrega al final sin borrar lo anterior', 'Borra TODO el contenido previo y escribe de cero', 'Falla si el archivo ya existe', 'Solo permite leerlo'], c: 1, ex: 'El modo "w" abre para escribir y BORRA todo el contenido previo (crea el archivo si no existe). Si querías conservar lo anterior y agregar al final, el modo es "a" (append). ▸ Por qué las otras: agregar sin borrar es "a"; "w" no falla si existe (lo pisa); "w" no es de lectura.'},
  {st: 'Para combinar dos condiciones en un filtro de pandas (DataFrame) se usa:', opts: ['<code>and</code> / <code>or</code>', '<code>&amp;</code> / <code>|</code> con paréntesis en cada condición', '<code>+</code> / <code>-</code>', '<code>&amp;&amp;</code> / <code>||</code>'], c: 1, ex: 'En pandas los filtros se combinan con &amp; (y), | (o), ~ (no), y CADA condición va entre paréntesis: <code>df[(df["a"] &gt; 1) &amp; (df["b"] != "C")]</code>. ▸ Por qué las otras: <code>and</code>/<code>or</code> de Python tiran error con Series; <code>+/-</code> no son lógicos; <code>&amp;&amp;/||</code> no existen en Python.'},
  {st: 'La función <code>input()</code> en Python siempre devuelve un valor de tipo:', opts: ['<code>int</code>', '<code>float</code>', '<code>str</code> (string)', '<code>bool</code>'], c: 2, ex: 'input() SIEMPRE devuelve str, aunque el usuario escriba un número. Por eso para usarlo como número hay que convertir: <code>int(input(...))</code> o <code>float(input(...))</code> — y eso puede lanzar ValueError si el texto no es numérico (de ahí el try/except). ▸ Por qué las otras: Python no "adivina" el tipo de lo que escribe el usuario.'}
]);

registerExercises('pc-segundo-parcial', '2', [
  {st: 'Cuál de estos diccionarios tiene TODAS sus claves numéricas (int/float)?', opts: ['<code>{"1":2, "23":5, "0":13}</code>', '<code>{0:"cero", 2:66, 5:3.45, 1:[-2,5]}</code>', '<code>{("1","0"):2, ("3","5"):44}</code>', '<code>{"a":1, "b":2}</code>'], c: 1, ex: 'Las claves de la opción B son 0, 2, 5 y 1: todas enteras (lo que esté del lado del VALOR no importa). ▸ Por qué las otras están mal: (A) y (D) tienen claves entre comillas → son strings, no números; (C) tiene claves que son tuplas. ▸ Detalle fino: <code>True</code> y <code>False</code> también cuentan como numéricos (bool es subtipo de int, True==1), una trampa habitual del parcial.'},
  {st: 'En <code>botones = {"MET 002": ["plata", 350.0, 1]}</code>, ¿qué línea aumenta 10% el precio (2° dato)?', opts: ['<code>botones["MET 002"] = 1.1</code>', '<code>botones["MET 002"][1] *= 1.1</code>', '<code>botones["MET 002"][2] -= 1</code>', '<code>precio = 350 * 1.1</code>'], c: 1, ex: '<code>botones["MET 002"]</code> es la lista <code>["plata", 350.0, 1]</code>; el índice [1] es el precio (350.0); <code>*= 1.1</code> lo modifica DENTRO de la lista → 385.0. ▸ Por qué las otras están mal: (A) pisa toda la lista por el número 1.1; (C) modifica el tamaño (índice 2), no el precio; (D) calcula aparte pero no toca el diccionario.'},
  {st: 'Para que <code>estructura[0] = "primero"</code> se ejecute SIN error, <code>estructura</code> puede ser:', opts: ['Una lista vacía <code>[]</code>', 'Una tupla de dos elementos', 'Un diccionario', 'La cadena vacía <code>""</code>'], c: 2, ex: 'En un diccionario, <code>d[0] = "primero"</code> CREA la clave 0 (o la pisa) — siempre funciona. ▸ Por qué las otras fallan: la lista vacía da IndexError (no hay posición 0 para asignar); la tupla es inmutable (TypeError); el string es inmutable (TypeError).'},
  {st: 'Con <code>datos = {41234225: ["Juan", "Aguirre", 301]}</code>, ¿qué devuelve <code>datos[41234225][2]</code>?', opts: ['<code>"Juan"</code>', '<code>301</code>', '<code>"Aguirre"</code>', 'Error'], c: 1, ex: 'Se encadenan dos accesos: <code>datos[41234225]</code> da la lista <code>["Juan", "Aguirre", 301]</code>, y <code>[2]</code> toma su índice 2 → 301. ▸ Por qué las otras: el índice 0 sería "Juan", el 1 "Aguirre"; no hay error porque la clave existe y el índice es válido.'},
  {st: 'Al recorrer un diccionario con <code>for k in d:</code>, la variable <code>k</code> toma:', opts: ['las claves', 'los valores', 'los pares (clave, valor)', 'las posiciones 0,1,2…'], c: 0, ex: 'Iterar un diccionario directo recorre las CLAVES. Para los valores se usa <code>for v in d.values()</code>, y para ambos a la vez <code>for k, v in d.items()</code>. ▸ Por qué las otras: los valores y los pares requieren .values()/.items(); los diccionarios no se recorren por posición.'},
  {st: 'El diccionario es <code>mail → [password, usuario]</code>. ¿Qué comparación valida que coincidan los DOS datos?', opts: ['<code>if usr[datos][0] == usuario:</code>', '<code>if usr[datos] == [passw, usuario]:</code>', '<code>if usuario in usr:</code>', '<code>if passw in usr:</code>'], c: 1, ex: 'El valor de cada clave es la lista <code>[password, usuario]</code>. Comparar contra <code>[passw, usuario]</code> exige que coincidan AMBOS datos en el orden correcto. ▸ Por qué las otras: (A) valida solo el password; (C) y (D) chequean si un texto es una CLAVE (mail) del diccionario, no los datos de acceso.'}
]);

registerExercises('pc-segundo-parcial', '3', [
  {st: '¿Qué imprime?<br><pre class="code-block">def mes31(m):\n    de30dias = (4, 6, 9, 11)\n    return m not in de30dias and m != 2\n\nmeses = [1, 5, 6, 2, 7]\nprint(list(filter(mes31, meses)))</pre>', opts: ['<code>[1, 5, 6, 2, 7]</code>', '<code>[1, 5, 7]</code>', '<code>[6, 2]</code>', '<code>[]</code>'], c: 1, ex: 'filter deja los <code>m</code> donde la función da True. ▸ 1: no está en (4,6,9,11) y ≠2 → True. ▸ 5: True. ▸ 6: está en de30dias → False (sale). ▸ 2: <code>m != 2</code> es False → sale. ▸ 7: True. Quedan [1, 5, 7]. ▸ Por qué las otras: (A) sería sin filtrar; (C) son justo los que NO pasan; (D) vacío implicaría que ninguno cumple.'},
  {st: 'Para que la salida sea <code>["ASA", "UTO", "ANCO", "ARTEL", "EMÁFORO"]</code> (saca la 1ª letra y pasa a mayúsculas), con <code>def edita(p): return p[1:].upper()</code> y <code>palabras = ["casa","auto","banco","cartel","semáforo"]</code>, la línea es:', opts: ['<code>nueva = list(map(palabras, edita))</code>', '<code>nueva = list(map(edita, palabras))</code>', '<code>nueva = list(filter(edita, palabras))</code>', '<code>nueva = palabras.map(edita)</code>'], c: 1, ex: 'map aplica la función a CADA elemento y devuelve la misma cantidad transformada. El orden es SIEMPRE <code>map(función, secuencia)</code>. ▸ Por qué las otras: (A) invierte los argumentos; (C) filter espera una función que devuelva True/False y selecciona, no transforma; (D) las listas no tienen método .map().'},
  {st: '¿Qué imprime?<br><pre class="code-block">def mayus(t): return t.upper()\ndef tilde(t): return ("á" in t) or ("ó" in t)\n\nciudades = ["anillaco", "san javier", "la dársena", "fiambalá"]\nsel = list(filter(tilde, ciudades))\nprint(list(map(mayus, sel)))</pre>', opts: ['<code>["anillaco", "san javier", "la dársena", "fiambalá"]</code>', '<code>["LA DÁRSENA", "FIAMBALÁ"]</code>', '<code>["ANILLACO", "SAN JAVIER"]</code>', '<code>[]</code>'], c: 1, ex: 'Primero filter deja las que tienen á u ó: "la dársena" y "fiambalá" (las otras no tienen tilde). Después map(mayus) las pasa a mayúsculas → ["LA DÁRSENA", "FIAMBALÁ"]. ▸ Lógica clave: primero SELECCIONAR (filter), después TRANSFORMAR (map). ▸ Por qué las otras: (A) no aplica map; (C) son justo las que filter descarta; (D) sí hay resultados.'},
  {st: '¿Cuál es la diferencia entre <code>map</code> y <code>filter</code>?', opts: ['Hacen exactamente lo mismo', 'map TRANSFORMA cada elemento (misma cantidad); filter SELECCIONA los que dan True', 'filter transforma y map selecciona', 'Ninguna devuelve algo útil'], c: 1, ex: 'map(func, sec) aplica func a cada elemento y devuelve la MISMA cantidad, pero transformados. filter(func, sec) usa una func que devuelve True/False y deja SOLO los elementos que dan True (devuelve los originales, no transformados). ▸ Por qué las otras: no son lo mismo, y los roles no están invertidos.'},
  {st: '¿Qué imprime?<br><pre class="code-block">def calc(n): return (n, n % 2)\nnumeros = [36, 14007, 33, 20]\nprint(list(map(calc, numeros)))</pre>', opts: ['<code>[36, 14007, 33, 20]</code>', '<code>[(36, 0), (14007, 1), (33, 1), (20, 0)]</code>', '<code>[0, 1, 1, 0]</code>', '<code>[(0, 36), (1, 14007)]</code>'], c: 1, ex: 'map aplica calc a cada número; calc devuelve la tupla <code>(n, n%2)</code> (el número y su resto al dividir por 2: 0 si es par, 1 si es impar). ▸ 36 par → (36,0); 14007 impar → (14007,1); 33 impar → (33,1); 20 par → (20,0). ▸ Por qué las otras: (A) no transforma; (C) muestra solo el resto; (D) invierte el orden de la tupla y pierde elementos.'},
  {st: '¿Por qué se escribe <code>list(map(...))</code> y no solo <code>map(...)</code>?', opts: ['Porque map ya imprime la lista solo', 'Porque map devuelve un iterador; <code>list()</code> lo convierte en una lista visible', 'Porque list() ordena los elementos', 'Porque no hace falta, da igual'], c: 1, ex: 'En Python 3, map() y filter() devuelven un objeto iterador "perezoso" (no una lista). Si lo imprimís directo ves algo como <code>&lt;map object at 0x...&gt;</code>. Hay que envolverlo en <code>list(...)</code> para materializar y ver la lista. ▸ Por qué las otras: map no imprime solo, list() no ordena, y sí hace falta convertir.'}
]);

registerExercises('pc-segundo-parcial', '4', [
  {st: 'Un programa hace <code>arch.write(...)</code> en dos archivos que se crean de cero. ¿Qué par de modos NO produce error?', opts: ['<code>"r"</code> y <code>"r"</code>', '<code>"w"</code> y <code>"a"</code>', '<code>"r"</code> y <code>"w"</code>', '<code>"r+"</code> y <code>"r"</code>'], c: 1, ex: 'Para ESCRIBIR hace falta "w" (crea/sobrescribe) o "a" (crea/agrega): ambos sirven y no fallan aunque el archivo no exista. ▸ Por qué las otras: "r" es solo lectura (write da error) y además lanza FileNotFoundError si el archivo no existe; "r+" también falla si el archivo no existe todavía.'},
  {st: '¿Qué modo de apertura conserva el contenido previo y agrega al final?', opts: ['<code>"r"</code>', '<code>"w"</code>', '<code>"a"</code> (append)', '<code>"x"</code>'], c: 2, ex: '"a" (append) abre el archivo conservando lo que ya tenía y escribe a continuación, al final. ▸ Por qué las otras: "r" es solo lectura; "w" BORRA todo antes de escribir; "x" es creación exclusiva (falla si ya existe), no se usa en estos parciales.'},
  {st: '¿Qué devuelve <code>archivo.readlines()</code>?', opts: ['Una sola línea (string)', 'Una LISTA con todas las líneas (cada una termina en <code>\\n</code>)', 'Todo el archivo como un único string', 'La cantidad de líneas'], c: 1, ex: 'readlines() devuelve una lista de strings, una por línea, y cada string conserva su <code>\\n</code> final. ▸ Por qué las otras: readline() (singular) lee UNA línea; read() devuelve todo como un solo string; para contar usarías len(readlines()).'},
  {st: 'Si <code>linea = "ana,25,CABA"</code>, ¿qué devuelve <code>linea.split(",")</code>?', opts: ['<code>"ana"</code>', '<code>["ana", "25", "CABA"]</code>', '<code>("ana", 25, "CABA")</code>', '<code>3</code>'], c: 1, ex: 'split(",") parte el texto usando la coma como separador y devuelve una LISTA de strings. Ojo: el "25" queda como string, no como número. ▸ Por qué las otras: no devuelve un solo dato ni una tupla ni la cantidad; para procesar campos de un CSV este es el patrón estándar (strip + split).'},
  {st: 'Para escribir en líneas separadas con <code>arch.write(...)</code>, hay que:', opts: ['Nada, write() agrega el salto de línea solo', 'Agregar <code>"\\n"</code> al final de cada texto escrito', 'Usar print() en su lugar', 'Llamar a append()'], c: 1, ex: 'A diferencia de print(), write() NO agrega el salto de línea: hay que ponerlo manualmente con <code>"\\n"</code>, sino queda todo pegado en una sola línea. ▸ Por qué las otras: write no lo agrega solo; print escribe en pantalla, no en archivo; append es de listas.'},
  {st: '¿Qué ocurre al ejecutar <code>open("noexiste.txt", "r")</code> si el archivo no existe?', opts: ['Crea el archivo vacío', 'Lanza <code>FileNotFoundError</code>', 'Devuelve <code>None</code>', 'Lo abre en modo escritura'], c: 1, ex: 'El modo "r" exige que el archivo exista; si no, lanza FileNotFoundError (por eso a veces se envuelve en try/except). ▸ Por qué las otras: "r" no crea archivos (eso hacen "w" y "a"); no devuelve None ni cambia de modo solo.'}
]);

registerExercises('pc-segundo-parcial', '5', [
  {st: '¿Qué excepción lanza <code>int("hola")</code>?', opts: ['<code>ValueError</code>', '<code>ZeroDivisionError</code>', '<code>KeyError</code>', '<code>TypeError</code>'], c: 0, ex: 'Intentar convertir a entero un texto que no representa un número lanza ValueError. Por eso al validar input numérico se captura <code>except ValueError</code>. ▸ Por qué las otras: ZeroDivisionError es dividir por 0; KeyError es clave inexistente en dict; TypeError es operar tipos incompatibles (como "a" + 5).'},
  {st: 'En el patrón <code>while/try</code> para validar un dato, ¿con qué valor debe arrancar la bandera <code>sigue</code>?', opts: ['<code>sigue = False</code>', '<code>sigue = True</code>', '<code>sigue = 0</code>', '<code>sigue = None</code>'], c: 1, ex: 'Debe arrancar en True para que <code>while sigue:</code> ENTRE al ciclo; recién se pone en False cuando el dato es válido. ▸ Por qué las otras: con False (o 0 o None, que son "falsos") el while no arrancaría nunca y el programa no pediría el dato. Es el error de bandera más típico de los distractores.'},
  {st: '¿Qué versión evita que el programa aborte si la patente buscada no está en el diccionario?', opts: ['Acceder <code>titulares[pat]</code> sin try', 'Poner el acceso <code>titulares[pat]</code> dentro de <code>try:</code> y manejar el fallo en <code>except:</code>', 'Poner <code>except:</code> sin <code>try:</code>', 'Calcular el acceso ANTES del try'], c: 1, ex: 'Si la clave no existe, <code>titulares[pat]</code> lanza KeyError. La forma correcta es hacer el acceso DENTRO del try y, en el except, devolver un cartel tipo "desconocido". ▸ Por qué las otras: sin try el programa se corta; except sin try es error de sintaxis; calcular el acceso antes del try no lo protege (igual explota).'},
  {st: '¿Qué contiene <code>nombres</code> al final?<br><pre class="code-block">nombres = ["julio", "ana", "lía"]\nsigue = True\nwhile sigue:\n    try:\n        nombres.pop()\n    except IndexError:\n        sigue = False</pre>', opts: ['<code>[]</code> (lista vacía)', '<code>["julio"]</code>', '<code>["julio", "ana", "lía"]</code>', 'Error'], c: 0, ex: 'pop() saca el último elemento una y otra vez. Cuando la lista queda vacía, pop() lanza IndexError, que el except captura poniendo <code>sigue = False</code> y cortando el ciclo. La lista termina vacía: []. ▸ Por qué las otras: el while no para hasta vaciarla; no hay error sin manejar porque IndexError se captura.'},
  {st: '¿Cuándo se produce un <code>FileNotFoundError</code>?', opts: ['Al abrir con modo <code>"r"</code> un archivo que no existe', 'Al dividir por cero', 'Al hacer <code>int("abc")</code>', 'Al acceder a una clave inexistente'], c: 0, ex: 'Abrir en modo lectura "r" un archivo inexistente lanza FileNotFoundError. ▸ Por qué las otras: dividir por cero es ZeroDivisionError; int de texto no numérico es ValueError; clave inexistente en dict es KeyError.'},
  {st: 'Si por error se escribe <code>sigue = True</code> y luego <code>while not sigue:</code>, ¿qué pasa?', opts: ['Entra al ciclo y se repite', 'NO entra al ciclo nunca (se saltea)', 'Da error de sintaxis', 'Es un bucle infinito'], c: 1, ex: '<code>not True</code> es False, así que <code>while not sigue:</code> evalúa False y el ciclo NO se ejecuta ni una vez. Es un distractor clásico: el código "se ve bien" pero la condición está negada. ▸ Por qué las otras: no entra (así que no se repite ni es infinito) y es sintácticamente válido.'}
]);

registerExercises('pc-segundo-parcial', '6', [
  {st: 'Con la columna <code>humedad = [60, 75, 79, 68, 62, 55]</code>, ¿qué devuelve <code>print(df["humedad"].sum())</code>?', opts: ['<code>75</code>', '<code>399</code>', 'Todo el DataFrame', '<code>6</code>'], c: 1, ex: '.sum() de una columna devuelve un ÚNICO número: la suma de todos sus valores. 60+75+79+68+62+55 = 399. ▸ Por qué las otras: 75 es solo un valor; no devuelve el DataFrame; 6 sería la cantidad de filas (.count()).'},
  {st: '¿Qué hace <code>df[df["cantidad"] &lt; 32]</code>?', opts: ['Ordena el DataFrame por cantidad', 'Devuelve las FILAS donde cantidad es menor a 32', 'Suma la columna cantidad', 'Borra la columna cantidad'], c: 1, ex: 'Es un filtro: la condición <code>df["cantidad"] &lt; 32</code> genera una máscara de True/False, y <code>df[...]</code> deja solo las filas con True (cantidad menor a 32). ▸ Por qué las otras: ordenar es sort_values; sumar es .sum(); borrar es drop.'},
  {st: '¿Qué produce <code>lluvias.groupby("mes")["mm"].mean()</code>?', opts: ['El total general de mm', 'El PROMEDIO de mm por cada mes', 'La primera fila', 'Las columnas mes y mm sin cambios'], c: 1, ex: 'groupby("mes") junta las filas del mismo mes; <code>["mm"].mean()</code> calcula el promedio de mm dentro de cada grupo. Si abril tiene 65 y 96 → 80.5; si marzo tiene 120 y 115 → 117.5. Devuelve un valor por mes (ordenado por mes). ▸ Por qué las otras: no es el total ni una fila suelta; agrupar transforma la salida.'},
  {st: 'Para quedarte con las filas que tienen un valor NULO (NaN) en la columna calorías, usás:', opts: ['<code>df[df["calorías"].isnull()]</code>', '<code>df["calorías"].sum()</code>', '<code>df.head()</code>', '<code>df.dropna()</code>'], c: 0, ex: '.isnull() devuelve True donde el valor es NaN/None; usado como filtro <code>df[...]</code> deja justo esas filas vacías. ▸ Por qué las otras: .sum() suma; .head() muestra las primeras; .dropna() hace lo CONTRARIO (elimina las filas con nulos). Para "los que NO son nulos" se usa <code>~df["col"].isnull()</code>.'},
  {st: '¿Qué hace <code>df.loc[5] = ["Heinz", 12558741, 3, "A", "flex"]</code>?', opts: ['Borra la fila con índice 5', 'AGREGA (o define) la fila con índice 5 con esos valores', 'Lee la fila 5', 'Da error siempre'], c: 1, ex: '.loc[5] = [...] asigna toda una fila en el índice 5: si no existía, la AGREGA al DataFrame con esos valores. ▸ Por qué las otras: borrar es drop(5); leer es solo <code>df.loc[5]</code> sin el =; no da error si la cantidad de valores coincide con las columnas.'},
  {st: 'En pandas, combinar dos condiciones de filtro con <code>and</code> (en vez de <code>&amp;</code>):', opts: ['Funciona igual que <code>&amp;</code>', 'Lanza un error (hay que usar <code>&amp;</code> con paréntesis)', 'Ordena el DataFrame', 'Suma las columnas'], c: 1, ex: 'Con Series de pandas hay que usar &amp; (y), | (o), ~ (no), y paréntesis en cada condición: <code>df[(c1) &amp; (c2)]</code>. Usar <code>and</code>/<code>or</code> lanza un ValueError ("ambiguous truth value"). ▸ Por qué las otras: no funciona igual, no ordena ni suma.'}
]);

registerExercises('pc-segundo-parcial', '7', [
  {st: 'Para un gráfico de BARRAS verticales con <code>jugadores</code> en el eje x y <code>altura</code> como valor, ¿qué instrucción usás?', opts: ['<code>ax.scatter(altura, jugadores)</code>', '<code>ax.barh(jugadores)</code>', '<code>ax.bar(jugadores, altura)</code>', '<code>ax.set_title(altura)</code>'], c: 2, ex: '<code>ax.bar(categorías, valores)</code>: primer argumento las etiquetas del eje x (jugadores), segundo las alturas. ▸ Por qué las otras: scatter dibuja puntos (y acá invierte ejes); barh es horizontal y le falta el valor; set_title pone un título, no dibuja barras.'},
  {st: 'Para un gráfico de LÍNEA de <code>precioDol</code> a lo largo de <code>meses</code>, la instrucción correcta es:', opts: ['<code>ax.plot(meses, precioDol)</code>', '<code>ax.scatter(precioDol)</code>', '<code>ax.bar(precioDol)</code>', '<code>plt.set_label(x, "Precio")</code>'], c: 0, ex: '<code>ax.plot(x, y)</code> dibuja una línea uniendo los puntos (meses en x, precio en y). ▸ Por qué las otras: scatter y bar reciben x e y (acá les falta un argumento) y además no son líneas; set_label no es una función válida de pyplot.'},
  {st: 'En <code>ax.bar(categorías, valores)</code>, el PRIMER argumento representa:', opts: ['los valores (las alturas de las barras)', 'las categorías que van en el eje x', 'el título del gráfico', 'el color de las barras'], c: 1, ex: 'El orden es <code>bar(categorías, valores)</code>: primero las etiquetas del eje x, después las alturas. Invertirlos es un distractor típico del parcial. ▸ Por qué las otras: las alturas son el 2° argumento; el título es set_title; el color es el parámetro color=.'},
  {st: 'En la interfaz orientada a objetos (con <code>ax</code>), para poner el título del gráfico se usa:', opts: ['<code>ax.title("Ventas")</code>', '<code>ax.set_title("Ventas")</code>', '<code>plt.label("Ventas")</code>', '<code>ax.nombre("Ventas")</code>'], c: 1, ex: 'Con un objeto <code>ax</code> (de <code>fig, ax = plt.subplots()</code>) los textos se ponen con set_*: <code>ax.set_title(...)</code>, <code>ax.set_xlabel(...)</code>, <code>ax.set_ylabel(...)</code>. ▸ Por qué las otras: ax.title sin set_ no asigna; plt.label no existe; ax.nombre tampoco.'},
  {st: '<code>ax.scatter(x, y)</code> dibuja:', opts: ['barras', 'una línea continua', 'puntos sueltos (gráfico de dispersión)', 'un título'], c: 2, ex: 'scatter dibuja un punto por cada par (x, y), sin unirlos: sirve para ver la relación/correlación entre dos variables. ▸ Por qué las otras: barras es bar/barh; la línea es plot; el título es set_title.'},
  {st: 'Con <code>fig, ax = plt.subplots(nrows=3, ncols=3)</code>, ¿a qué gráfico apunta <code>ax[1, 1]</code>?', opts: ['la esquina superior izquierda', 'el gráfico del CENTRO de la grilla 3×3', 'el último (abajo a la derecha)', 'da error'], c: 1, ex: 'En una grilla, ax se indexa <code>ax[fila, columna]</code> empezando en 0. En una 3×3, las filas/columnas son 0,1,2; <code>ax[1,1]</code> es el del medio. ▸ Por qué las otras: la esquina superior izquierda es ax[0,0]; la inferior derecha es ax[2,2]; no da error.'}
]);

registerExercises('pc-segundo-parcial', '8', [
  {st: '¿Qué imprime?<br><pre class="code-block">def noLaborable(d):\n    finde = (6, 7)\n    return d in finde\n\ndias = [1, 5, 4, 6, 2, 7]\nprint(list(filter(noLaborable, dias)))</pre>', opts: ['<code>[1, 5, 4, 2]</code>', '<code>[6, 7]</code>', '<code>[1, 5, 4, 6, 2, 7]</code>', '<code>[]</code>'], c: 1, ex: 'filter deja los días donde <code>d in finde</code> es True, o sea los que están en (6,7): el 6 y el 7. ▸ Por qué las otras: (A) son los que NO cumplen; (C) sería sin filtrar; (D) vacío implicaría que ninguno está en finde.'},
  {st: '¿Qué imprime?<br><pre class="code-block">def nomDia(d):\n    dias = {1:"domingo",2:"lunes",5:"jueves",6:"viernes",7:"sábado"}\n    return dias[d]\n\ndias = [1, 5, 2, 6, 7]\nprint(list(map(nomDia, dias)))</pre>', opts: ['<code>["domingo", "jueves", "lunes", "viernes", "sábado"]</code>', '<code>[1, 5, 2, 6, 7]</code>', '<code>["SABADO"]</code>', 'Error'], c: 0, ex: 'map aplica nomDia a cada número, devolviendo el nombre del diccionario en ese orden: dias[1]="domingo", dias[5]="jueves", dias[2]="lunes", dias[6]="viernes", dias[7]="sábado". ▸ Por qué las otras: (B) no transforma; (C) toma uno solo; no hay error porque todas las claves existen.'},
  {st: 'Tras <code>df["región"] = df["región"].map({"cuyo":"centro", "pampa":"centro"})</code>, las regiones que NO eran cuyo ni pampa quedan:', opts: ['igual que antes', 'como <code>NaN</code> (nulo), porque .map() solo reemplaza las claves del diccionario', 'borradas del DataFrame', 'en 0'], c: 1, ex: 'Series.map(dicc) reemplaza cada valor por el del diccionario; los valores que NO son claves del diccionario quedan como NaN. Por eso "litoral" y "patagonia" (que no están en el dict) se vuelven nulos. ▸ Por qué las otras: no quedan igual ni en 0; .map() no borra filas (eso lo haría un filtro posterior con isnull).'},
  {st: 'Querés AGREGAR una línea a un archivo de log sin borrar lo anterior. El modo correcto de open() es:', opts: ['<code>"r"</code>', '<code>"w"</code>', '<code>"a"</code>', '<code>"x"</code>'], c: 2, ex: '"a" (append) conserva el contenido y escribe al final: justo lo que necesita un log. ▸ Por qué las otras: "r" no escribe; "w" BORRARÍA todo el historial; "x" falla si el archivo ya existe.'},
  {st: '¿Qué imprime?<br><pre class="code-block">def organiza(n):\n    return n % 3 == 0 and n % 2 == 0 or n &lt; 100\n\na = [15, -150, 150, 66]\nprint(list(filter(organiza, a)))</pre>', opts: ['<code>[150]</code>', '<code>[15, -150, 150, 66]</code>', '<code>[-150, 66]</code>', '<code>[]</code>'], c: 1, ex: 'Por precedencia, <code>and</code> se evalúa antes que <code>or</code>: la condición es <code>(n%3==0 and n%2==0) or (n &lt; 100)</code>. ▸ 15, −150 y 66 son &lt; 100 → True. ▸ 150: es múltiplo de 3 y de 2 → True. Pasan todos. ▸ Por qué las otras: ninguna excluye correctamente; el truco está en la precedencia and/or.'},
  {st: 'El error MÁS caro del parcial al filtrar un DataFrame es:', opts: ['Usar <code>&amp;</code> con paréntesis', 'Usar <code>and</code>/<code>or</code> en vez de <code>&amp;</code>/<code>|</code>', 'Poner el filtro entre corchetes', 'Usar comillas en los nombres de columnas'], c: 1, ex: 'Combinar condiciones de pandas con <code>and</code>/<code>or</code> lanza error: hay que usar &amp; / | / ~ y paréntesis en cada condición. ▸ Por qué las otras: usar &amp; con paréntesis es justamente lo correcto; el filtro va entre corchetes <code>df[...]</code>; los nombres de columnas SÍ van entre comillas.'}
]);
