// Ejercicios Física · 2° Parcial — basados en parciales reales (Cátedra Torti, 2023-2025)
registerExercises('fisica-segundo-parcial', '1', [
  {st: '¿Qué unidades entran en el 2° parcial de Física (Torti)?', opts: ['Medición, vectores y estática', 'Hidrostática y cinemática en 1 dimensión', 'Cinemática 2D, dinámica y energía (unidades 5 a 7)', 'Solo energía'], c: 2, ex: 'El 2° parcial cubre las unidades 5 a 7: cinemática en dos dimensiones (tiro oblicuo, circular), dinámica (Newton, rozamiento) y trabajo/energía. ▸ Por qué las otras: medición, vectores, estática e hidrostática y cinemática 1D fueron del 1° parcial.'},
  {st: '¿Cuál es el formato del 2° parcial?', opts: ['Opción múltiple de 10 preguntas', '3 problemas numéricos con varios incisos, 3 cifras significativas y unidades', 'Examen oral', 'Un único problema largo'], c: 1, ex: 'Son 3 problemas de respuesta numérica (no multiple choice), cada uno con varios incisos. Hay que expresar con 3 cifras significativas y unidades (es criterio de corrección) y asumir g = 9,80 m/s². ▸ Por qué las otras: no es multiple choice ni oral, y son 3 problemas, no uno.'},
  {st: 'En la altura máxima de un tiro oblicuo, la velocidad del proyectil:', opts: ['Es cero', 'Tiene solo componente vertical', 'Tiene solo componente horizontal (vₓ); la vertical vᵧ es 0', 'Es la máxima del recorrido'], c: 2, ex: 'En el punto más alto vᵧ = 0 (deja de subir), pero vₓ = v₀·cos(α) NUNCA cambia (no hay fuerza horizontal). Por eso la velocidad ahí es puramente horizontal y la energía cinética NO es cero. ▸ Por qué las otras: "cero" y "solo vertical" son el error clásico; la rapidez ahí es la mínima, no la máxima.'},
  {st: 'Expresada en m/s, una rapidez de 72 km/h es:', opts: ['72 m/s', '20 m/s', '259 m/s', '7,2 m/s'], c: 1, ex: 'km/h → m/s se divide por 3,6: 72/3,6 = 20 m/s. ▸ Por qué las otras: 72 es no convertir; 259 es multiplicar por 3,6 (al revés); 7,2 es dividir por 10. No convertir es el error N°1 del parcial.'},
  {st: '¿Cuándo conviene resolver con CONSERVACIÓN DE ENERGÍA en vez de Newton?', opts: ['Cuando piden fuerzas o tensiones', 'Cuando piden la aceleración instantánea', 'Cuando piden velocidad o distancia y hay alturas/resortes, sin importar los tiempos', 'Nunca, siempre conviene Newton'], c: 2, ex: 'La energía conecta velocidades y posiciones inicial y final sin pasar por las fuerzas ni el tiempo: ideal para "rapidez al pie de la rampa" o "compresión del resorte". ▸ Por qué las otras: si piden fuerzas, tensiones o aceleraciones, ahí sí conviene Newton (ΣF = m·a).'},
  {st: '¿La fuerza normal hace trabajo sobre un cuerpo que se desliza horizontalmente?', opts: ['Sí, trabajo positivo', 'Sí, trabajo negativo', 'No: es perpendicular al desplazamiento (cos 90° = 0)', 'Solo si hay rozamiento'], c: 2, ex: 'W = F·d·cos(θ). La normal es perpendicular al movimiento (θ = 90°), y cos 90° = 0, así que su trabajo es nulo. ▸ Por qué las otras: la normal nunca aporta ni quita energía al deslizar; el que hace trabajo (negativo) es el rozamiento.'}
]);

registerExercises('fisica-segundo-parcial', '2', [
  {st: 'Un proyectil sale con v₀ = 20 m/s a 30° de la horizontal. ¿Componente horizontal vₓ? (cos30° ≈ 0,866)', opts: ['10 m/s', '17,3 m/s', '20 m/s', '11,5 m/s'], c: 1, ex: 'vₓ = v₀·cos(α) = 20·cos(30°) = 20·0,866 = 17,3 m/s (se mantiene todo el vuelo). ▸ Por qué las otras: 10 es la componente vertical (sen30°); 20 es el módulo total; 11,5 no corresponde.'},
  {st: 'Mismo proyectil (v₀ = 20 m/s, 30°). ¿Componente vertical inicial vᵧ? (sen30° = 0,5)', opts: ['10 m/s', '17,3 m/s', '20 m/s', '0 m/s'], c: 0, ex: 'vᵧ = v₀·sen(α) = 20·sen(30°) = 20·0,5 = 10 m/s. ▸ Por qué las otras: 17,3 es la horizontal (cos30°); 20 es el módulo; 0 sería en la altura máxima, no al inicio.'},
  {st: 'Si la componente vertical inicial es vᵧ = 10 m/s, ¿qué altura sube el proyectil sobre el punto de lanzamiento? (g = 9,8)', opts: ['5,10 m', '10,2 m', '1,02 m', '20,4 m'], c: 0, ex: 'h = vᵧ²/(2g) = 10²/(2·9,8) = 100/19,6 = 5,10 m. ▸ Por qué las otras: 10,2 olvida el factor 2; 1,02 divide de más; 20,4 no corresponde. Surge de v² = v₀² − 2g·h con v = 0 arriba.'},
  {st: 'Una catapulta lanza una piedra de 40,0 kg a 80,0 km/h (22,2 m/s) y 45°. ¿Energía cinética en la altura máxima? (vₓ = 15,7 m/s)', opts: ['0 J', '4,94 × 10³ J', '9,86 × 10³ J', '1,07 × 10⁴ J'], c: 1, ex: 'En la altura máxima solo queda vₓ = 15,7 m/s. E_c = ½·m·vₓ² = ½·40·15,7² = 4,94×10³ J. ▸ Por qué las otras: 0 es la trampa (creer que la velocidad es nula); 9,86×10³ olvida el ½; 1,07×10⁴ es la energía MECÁNICA total (cinética + potencial).'},
  {st: 'En la altura máxima de un tiro oblicuo, la componente vertical de la velocidad vᵧ vale:', opts: ['v₀', 'v₀·sen(α)', '0', 'v₀·cos(α)'], c: 2, ex: 'vᵧ se va frenando por la gravedad hasta hacerse 0 en el punto más alto (ahí el proyectil deja de subir). ▸ Por qué las otras: v₀ y v₀·sen(α) son al inicio; v₀·cos(α) es la componente horizontal, que NO se anula.'},
  {st: 'Un proyectil viaja en MRU horizontal hacia un blanco a distancia d con velocidad vₓ. ¿Tiempo de vuelo?', opts: ['d · vₓ', 'd / vₓ', 'd / vᵧ', '½·g·d'], c: 1, ex: 'El movimiento horizontal es MRU (velocidad constante vₓ), así que t = distancia/velocidad = d/vₓ. ▸ Por qué las otras: d·vₓ tiene unidades incorrectas; vᵧ es el eje vertical; ½gd no es un tiempo.'}
]);

registerExercises('fisica-segundo-parcial', '3', [
  {st: 'Un auto a 20 m/s toma una curva de radio 50 m. ¿Aceleración centrípeta?', opts: ['0,400 m/s²', '8,00 m/s²', '400 m/s²', '2,50 m/s²'], c: 1, ex: 'a_c = v²/R = 20²/50 = 400/50 = 8,00 m/s², apuntando al centro de la curva. ▸ Por qué las otras: 0,4 invierte (R/v²); 400 olvida dividir por R; 2,5 es v/(R/...) mal armado.'},
  {st: 'En un movimiento circular uniforme, la aceleración centrípeta apunta:', opts: ['En la dirección del movimiento', 'Hacia el centro de la circunferencia', 'Hacia afuera (centrífuga)', 'Es cero'], c: 1, ex: 'La aceleración centrípeta apunta siempre HACIA EL CENTRO; es la que "curva" la trayectoria cambiando la dirección de la velocidad. ▸ Por qué las otras: en la dirección del movimiento iría la tangencial (que en MCU es 0); "hacia afuera" es la ficticia centrífuga (no existe en un sistema inercial); cero contradice que la dirección cambia.'},
  {st: 'Un cuerpo gira en MCU con rapidez constante. ¿Tiene aceleración?', opts: ['No, porque la rapidez no cambia', 'Sí, porque cambia la DIRECCIÓN de la velocidad (aceleración centrípeta)', 'Solo si cambia el radio', 'Solo en el arranque'], c: 1, ex: 'La velocidad es un vector: aunque el módulo (rapidez) sea constante, su dirección cambia continuamente, y eso ya es una aceleración (la centrípeta). ▸ Por qué las otras: "no" confunde rapidez con velocidad; el radio es fijo en MCU; la aceleración está presente todo el tiempo, no solo al arrancar.'},
  {st: 'Un bote apunta perpendicular a la orilla a 4 m/s respecto del agua; la corriente lleva 3 m/s. ¿Rapidez del bote respecto de la orilla?', opts: ['1 m/s', '7 m/s', '5 m/s', '3,50 m/s'], c: 2, ex: 'Las velocidades son perpendiculares, así que se suman con Pitágoras: √(4² + 3²) = √(16+9) = √25 = 5 m/s. ▸ Por qué las otras: 1 las resta; 7 las suma como si fueran paralelas; 3,5 es el promedio (sin sentido físico).'},
  {st: 'La relación entre la velocidad tangencial v y la velocidad angular ω en un movimiento circular es:', opts: ['v = ω / R', 'v = ω · R', 'v = ω² · R', 'v = 2π·R'], c: 1, ex: 'v = ω·R: la rapidez sobre la circunferencia es la velocidad angular por el radio. ▸ Por qué las otras: ω/R y ω²·R tienen unidades incorrectas; 2πR es la longitud de una vuelta, no una velocidad.'},
  {st: 'Si una rueda da una vuelta cada T = 2 s, su frecuencia es:', opts: ['0,500 Hz', '2,00 Hz', '4,00 Hz', '0,250 Hz'], c: 0, ex: 'f = 1/T = 1/2 = 0,500 Hz (media vuelta por segundo). ▸ Por qué las otras: 2 es el período (no la frecuencia); 4 y 0,25 no surgen de 1/T.'}
]);

registerExercises('fisica-segundo-parcial', '4', [
  {st: 'Un F1 de 800 kg acelera de 0 a 96,6 km/h (26,8 m/s) en 1,70 s. ¿Fuerza promedio del motor?', opts: ['1,26 × 10⁴ N', '4,55 × 10⁴ N', '800 N', '472 N'], c: 0, ex: 'a = Δv/t = 26,8/1,70 = 15,8 m/s²; F = m·a = 800·15,8 = 1,26×10⁴ N. ▸ Por qué las otras: 4,55×10⁴ usa 96,6 sin convertir a m/s (¡el error clásico!); 800 es solo la masa; 472 no corresponde.'},
  {st: 'Una caja de 70,0 kg sobre piso horizontal con μ_s = 0,650. ¿Fuerza mínima para empezar a moverla?', opts: ['446 N', '309 N', '70,0 N', '686 N'], c: 0, ex: 'Hay que vencer el rozamiento estático máximo: F = μ_s·N = μ_s·m·g = 0,650·70·9,8 = 446 N. ▸ Por qué las otras: 309 usa μ_d (= 0,450, sirve para mantenerla, no para arrancar); 70 es la masa; 686 es el peso (m·g).'},
  {st: 'Cuerpo C de 16,5 kg sobre mesa rugosa (μ_s = 0,450) unido por una polea a un balde de 2,00 kg. ¿Masa mínima a agregar al balde para que C arranque?', opts: ['5,43 kg', '7,43 kg', '16,5 kg', '3,42 kg'], c: 0, ex: 'El peso colgante debe igualar el rozamiento estático máximo de C: (2,00 + m)·g = μ_s·m_C·g → 2,00 + m = 0,450·16,5 = 7,43 kg → m = 5,43 kg. ▸ Por qué las otras: 7,43 es el total colgante (sin restar el balde); 16,5 es la masa de C; 3,42 no corresponde.'},
  {st: 'Dos vagones (850 kg y 250 kg) sobre vía sin rozamiento se tiran con F = 400 N. ¿Aceleración del sistema?', opts: ['0,364 m/s²', '0,471 m/s²', '1,60 m/s²', '400 m/s²'], c: 0, ex: 'a = F/(m_total) = 400/(850+250) = 400/1100 = 0,364 m/s². ▸ Por qué las otras: 0,471 usa solo 850; 1,60 usa solo 250; 400 es la fuerza, no la aceleración.'},
  {st: 'En ese sistema, la cuerda que une los vagones arrastra al de 250 kg. ¿Tensión en esa cuerda? (a = 0,364 m/s²)', opts: ['90,9 N', '309 N', '400 N', '250 N'], c: 0, ex: 'La cuerda solo tiene que acelerar al vagón de atrás (250 kg): T = m·a = 250·0,364 = 90,9 N. ▸ Por qué las otras: 309 usaría 850 kg; 400 es la fuerza total aplicada al sistema; 250 es la masa.'},
  {st: 'Un bloque baja un plano inclinado de ángulo α SIN rozamiento. ¿Cuál es su aceleración?', opts: ['g', 'g·sen(α)', 'g·cos(α)', 'g·tan(α)'], c: 1, ex: 'Sobre el eje del plano: m·g·sen(α) = m·a → a = g·sen(α) (no depende de la masa). ▸ Por qué las otras: g sería en caída libre (α = 90°); g·cos(α) es la componente perpendicular (relacionada con la normal); g·tan(α) no corresponde.'}
]);

registerExercises('fisica-segundo-parcial', '5', [
  {st: 'De un resorte ideal cuelga una pesa de 12,5 kg y el resorte se estira 5,00 cm. ¿Constante k del resorte?', opts: ['2450 N/m', '245 N/m', '2,45 N/m', '122,5 N/m'], c: 0, ex: 'En equilibrio el peso iguala la fuerza elástica: m·g = k·Δx → k = (12,5·9,8)/0,05 = 122,5/0,05 = 2450 N/m. ▸ Por qué las otras: 122,5 es el peso (olvida dividir por Δx); 245 y 2,45 tienen el decimal corrido (usar Δx en cm o mal).'},
  {st: 'Mismo resorte (k = 2450 N/m, Δx = 5,00 cm). ¿Energía potencial elástica acumulada?', opts: ['3,06 J', '61,3 J', '6,13 J', '0,153 J'], c: 0, ex: 'E_pe = ½·k·Δx² = ½·2450·(0,05)² = ½·2450·0,0025 = 3,06 J. ▸ Por qué las otras: 61,3 olvida elevar Δx al cuadrado (usa ½·k·Δx); 6,13 y 0,153 tienen el factor mal.'},
  {st: 'Si al mismo resorte se le cuelga el DOBLE de masa, la energía potencial elástica:', opts: ['Se duplica', 'Se cuadruplica (×4)', 'No cambia', 'Se reduce a la mitad'], c: 1, ex: 'El doble de peso estira el doble (Δx se duplica). Como E_pe = ½·k·Δx² depende del cuadrado, al duplicar Δx la energía se multiplica por 2² = 4. ▸ Por qué las otras: se cuadruplica, no se duplica; sí cambia y aumenta. Es el mismo motivo por el que un choque al doble de velocidad es 4 veces más violento.'},
  {st: 'Una jarra de 0,800 kg se desliza a 4,00 m/s; μ_d (vidrio-acero) = 0,155. ¿Distancia hasta detenerse?', opts: ['5,27 m', '2,64 m', '1,03 m', '10,5 m'], c: 0, ex: 'El rozamiento disipa toda la energía cinética: ½·m·v² = μ_d·m·g·L → L = v²/(2·μ_d·g) = 16/(2·0,155·9,8) = 5,27 m. ▸ La masa se cancela. ▸ Por qué las otras: 2,64 es la mitad (olvida un factor); 1,03 y 10,5 tienen mal el 2 o el μ.'},
  {st: 'Un F1 de 800 kg frena de 250 km/h (69,4 m/s) a 80,0 km/h (22,2 m/s). ¿Trabajo de la fuerza de frenado?', opts: ['−1,73 × 10⁶ J', '+1,73 × 10⁶ J', '−5,73 × 10⁴ J', '−3,02 × 10⁴ J'], c: 0, ex: 'W = ΔE_c = ½·m·(v_f² − v_i²) = ½·800·(22,2² − 69,4²) = 400·(493 − 4816) = −1,73×10⁶ J. Es negativo porque la fuerza se opone al movimiento (frena). ▸ Por qué las otras: el signo + ignora que frena; 5,73×10⁴ es el espacio; 3,02×10⁴ es la FUERZA de frenado, no el trabajo.'},
  {st: 'Un cuerpo se suelta desde una altura h y cae sin rozamiento. ¿Velocidad al llegar al suelo?', opts: ['√(2·g·h)', '2·g·h', '√(g·h)', 'g·h'], c: 0, ex: 'Por conservación: m·g·h = ½·m·v² → v = √(2·g·h) (no depende de la masa). ▸ Por qué las otras: 2gh y gh no tienen unidades de velocidad; √(gh) olvida el factor 2.'}
]);

registerExercises('fisica-segundo-parcial', '6', [
  {st: 'Un F1 de 800 kg acelera de 0 a 96,6 km/h (26,8 m/s) en 1,70 s. ¿Potencia promedio del motor?', opts: ['1,69 × 10⁵ W', '1,26 × 10⁴ W', '22,8 W', '2,68 × 10⁴ W'], c: 0, ex: 'El trabajo del motor es la energía cinética ganada: W = ½·m·v² = ½·800·26,8² = 2,88×10⁵ J. P = W/t = 2,88×10⁵/1,70 = 1,69×10⁵ W. ▸ Por qué las otras: 1,26×10⁴ es la fuerza; 22,8 es la distancia; 2,68×10⁴ no corresponde.'},
  {st: 'El cañón Gustav dispara un proyectil a 720 m/s con 63,0° (sin aire). ¿Altura máxima? (vᵧ = 642 m/s, g = 9,8)', opts: ['2,10 × 10⁴ m', '2,64 × 10⁴ m', '1,07 × 10⁴ m', '720 m'], c: 0, ex: 'h_max = vᵧ²/(2g) = 642²/(2·9,8) = 412164/19,6 = 2,10×10⁴ m (≈21 km). ▸ Por qué las otras: 2,64×10⁴ usaría el v total (720) en lugar de la componente vertical; 1,07×10⁴ olvida un factor; 720 es la rapidez inicial.'},
  {st: 'En una montaña rusa sin rozamiento, ¿con qué rapidez pasa el carrito por un punto que está a la MISMA altura que el de partida?', opts: ['Con rapidez cero', 'Con la misma rapidez que al partir', 'Con el doble de rapidez', 'Con la mitad'], c: 1, ex: 'Sin rozamiento, la energía mecánica se conserva: a igual altura, igual energía potencial, así que igual energía cinética → igual rapidez (sin importar el recorrido intermedio). ▸ Por qué las otras: la rapidez no se anula ni cambia si la altura es la misma.'},
  {st: '¿Cuál es el error MÁS caro en un problema de tiro oblicuo?', opts: ['Convertir las unidades a m/s', 'Poner energía cinética = 0 en la altura máxima', 'Usar g = 9,8 m/s²', 'Descomponer la velocidad en vₓ y vᵧ'], c: 1, ex: 'En la altura máxima vᵧ = 0 pero vₓ NO, así que E_c = ½·m·vₓ² ≠ 0. Ponerla en cero pierde el inciso. ▸ Por qué las otras: convertir, usar g = 9,8 y descomponer son justamente los pasos CORRECTOS.'},
  {st: 'Para que un cuerpo apoyado EMPIECE a moverse, la fuerza aplicada debe vencer:', opts: ['El rozamiento dinámico (μ_d·N)', 'El rozamiento estático máximo (μ_s·N)', 'Solo el peso', 'Solo la normal'], c: 1, ex: 'Mientras está quieto actúa el rozamiento estático, que puede crecer hasta μ_s·N; recién al superarlo arranca. Como μ_s > μ_d, cuesta más arrancar que mantener. ▸ Por qué las otras: el dinámico recién aparece cuando ya se mueve; peso y normal son verticales, no se oponen al empuje horizontal.'},
  {st: 'Una caja de 70,0 kg se mueve 3,50 m a velocidad constante con μ_d = 0,450. ¿Trabajo realizado contra el rozamiento?', opts: ['1,08 × 10³ J', '446 J', '216 J', '3,50 J'], c: 0, ex: 'A velocidad constante la fuerza iguala el rozamiento dinámico: F = μ_d·m·g = 0,450·70·9,8 = 309 N. W = F·d = 309·3,50 = 1,08×10³ J. ▸ Por qué las otras: 446 es la fuerza para ARRANCAR (con μ_s); 216 es la potencia (si fue en 5 s); 3,50 es la distancia.'}
]);
