// Ejercicios PC - escapar las comillas y usar &quot; donde haga falta
registerExercises('pc', '1', [
  {st: '¿Cuál de las siguientes NO es un nombre válido para una variable en Python?', opts: ['<code>edad_usuario</code>', '<code>2edad</code>', '<code>Edad</code>', '<code>_temp</code>'], c: 1, ex: 'Los nombres de variables NO pueden empezar con un número. <code>2edad</code> es inválido. Pueden empezar con letra o con guion bajo. Las otras tres opciones son válidas (Python distingue mayúsculas, así que <code>Edad</code> es distinto de <code>edad</code> pero ambos son nombres válidos).'},
  {st: '¿Qué muestra en pantalla este código?<br><pre class="code-block">nombre = "Ariel"\nprint(nombre)</pre>', opts: ['<code>nombre</code>', '<code>Ariel</code>', '<code>"Ariel"</code>', 'Error'], c: 1, ex: 'La variable <code>nombre</code> guarda el string <code>"Ariel"</code>. Al hacer <code>print(nombre)</code> se imprime el <b>contenido</b> de la variable (sin las comillas), no el nombre de la variable.'},
  {st: '¿Qué hace la función <code>print()</code>?', opts: ['Guarda datos en un archivo', 'Muestra texto en pantalla', 'Lee datos del usuario', 'Ejecuta un archivo'], c: 1, ex: '<code>print()</code> muestra en pantalla lo que le pases entre paréntesis. Para leer datos del usuario se usa <code>input()</code>.'},
  {st: 'En Python, el signo <code>=</code> sirve para:', opts: ['Comparar dos valores', 'Asignar un valor a una variable', 'Declarar una función', 'Terminar una línea'], c: 1, ex: '<code>=</code> asigna: guarda el valor de la derecha en la variable de la izquierda. Para comparar si dos cosas son iguales se usa <code>==</code> (doble igual).'},
  {st: '¿Qué valor tiene <code>x</code> después de ejecutar estas líneas?<br><pre class="code-block">x = 10\nx = x + 5</pre>', opts: ['<code>10</code>', '<code>5</code>', '<code>15</code>', 'Error'], c: 2, ex: 'En la segunda línea, Python primero calcula <code>x + 5</code> (que vale 15 porque x era 10), y después guarda 15 en x. La idea "x = x + 5" no es una ecuación matemática, es "tomá el valor de x, sumale 5, y guardalo de nuevo en x".'}
]);

registerExercises('pc', '2', [
  {st: '¿Qué tipo de dato devuelve <code>type(3.14)</code>?', opts: ['<code>int</code>', '<code>float</code>', '<code>str</code>', '<code>bool</code>'], c: 1, ex: 'Los números con punto decimal son de tipo <code>float</code> (punto flotante). Los enteros son <code>int</code>.'},
  {st: '¿Cuánto vale <code>10 % 3</code>?', opts: ['<code>3</code>', '<code>3.33</code>', '<code>1</code>', '<code>0</code>'], c: 2, ex: 'El operador <code>%</code> devuelve el <b>resto</b> de la división. 10 dividido 3 da 3 con resto 1. Entonces <code>10 % 3</code> es 1.'},
  {st: '¿Cuánto vale <code>10 // 3</code>?', opts: ['<code>3</code>', '<code>3.33</code>', '<code>1</code>', '<code>0</code>'], c: 0, ex: '<code>//</code> es la división entera: el cociente sin decimales. 10 entre 3 da cociente 3 (y resto 1). <code>/</code> sí daría 3.33...'},
  {st: 'Si <code>edad = input("Edad: ")</code> y el usuario escribe <code>25</code>, ¿qué tipo tiene <code>edad</code>?', opts: ['<code>int</code>', '<code>float</code>', '<code>str</code>', 'Depende'], c: 2, ex: '<code>input()</code> SIEMPRE devuelve un string, aunque el usuario escriba un número. Para tener un entero habría que convertir: <code>edad = int(input("Edad: "))</code>.'},
  {st: '¿Qué devuelve esta función?<br><pre class="code-block">def f(x, y):\n    return x + y * 2\n\nprint(f(3, 4))</pre>', opts: ['<code>14</code>', '<code>11</code>', '<code>10</code>', '<code>7</code>'], c: 1, ex: 'Por precedencia, primero se calcula <code>y * 2</code> (= 8) y después se suma x: 3 + 8 = 11. Los operadores de multiplicación tienen mayor precedencia que los de suma.'},
  {st: '¿Qué resultado da <code>not (5 > 3 and 2 &lt; 1)</code>?', opts: ['<code>True</code>', '<code>False</code>', 'Error', '<code>None</code>'], c: 0, ex: '<code>5 > 3</code> es True, <code>2 &lt; 1</code> es False. El <code>and</code> entre True y False da False. El <code>not</code> invierte: <code>not False</code> es True.'}
]);

registerExercises('pc', '3', [
  {st: '¿Qué imprime este código?<br><pre class="code-block">x = 7\nif x > 10:\n    print("grande")\nelif x > 5:\n    print("medio")\nelse:\n    print("chico")</pre>', opts: ['<code>grande</code>', '<code>medio</code>', '<code>chico</code>', 'Nada'], c: 1, ex: 'Python evalúa en orden. <code>x > 10</code> es False. Pasa a <code>elif x > 5</code>: como 7 > 5, imprime "medio" y termina (no evalúa el else).'},
  {st: '¿Qué imprime este ciclo?<br><pre class="code-block">for i in range(3):\n    print(i)</pre>', opts: ['<code>1 2 3</code>', '<code>0 1 2</code>', '<code>0 1 2 3</code>', '<code>1 2</code>'], c: 1, ex: '<code>range(3)</code> genera 0, 1, 2 (NO incluye el 3). El ciclo for recorre esos valores e imprime cada uno.'},
  {st: '¿Cuántas veces se imprime "hola" en este código?<br><pre class="code-block">i = 0\nwhile i &lt; 5:\n    print("hola")\n    i = i + 1</pre>', opts: ['<code>4</code>', '<code>5</code>', '<code>6</code>', 'Infinitas'], c: 1, ex: 'El ciclo se ejecuta con i = 0, 1, 2, 3, 4 (5 veces). Cuando i llega a 5, la condición <code>i &lt; 5</code> se vuelve falsa y termina.'},
  {st: '¿Qué genera <code>range(2, 10, 3)</code>?', opts: ['<code>2, 3, 4, 5, 6, 7, 8, 9</code>', '<code>2, 5, 8</code>', '<code>2, 5, 8, 11</code>', '<code>2, 10, 3</code>'], c: 1, ex: '<code>range(inicio, fin, paso)</code> empieza en 2, va sumando 3, sin llegar a 10: 2, 5, 8. El siguiente sería 11 pero ya supera 10.'},
  {st: '¿Cuál es el riesgo principal de este código?<br><pre class="code-block">i = 0\nwhile i &lt; 10:\n    print(i)</pre>', opts: ['No imprime nada', 'Se ejecuta infinitas veces (ciclo infinito)', 'Da error de sintaxis', 'Imprime 0 solamente'], c: 1, ex: 'Falta incrementar i adentro del ciclo. Como i nunca cambia, la condición <code>i &lt; 10</code> siempre es verdadera y el ciclo nunca termina. Hay que agregar <code>i = i + 1</code>.'},
  {st: '¿Qué imprime este código?<br><pre class="code-block">for i in range(5):\n    if i == 3:\n        break\n    print(i)</pre>', opts: ['<code>0 1 2 3 4</code>', '<code>0 1 2</code>', '<code>0 1 2 3</code>', '<code>3</code>'], c: 1, ex: '<code>break</code> corta el ciclo cuando i llega a 3, ANTES del print. Se imprimen solo 0, 1, 2.'}
]);

registerExercises('pc', '4a', [
  {st: 'Si <code>nums = [10, 20, 30, 40, 50]</code>, ¿qué devuelve <code>nums[-2]</code>?', opts: ['<code>50</code>', '<code>40</code>', '<code>20</code>', 'Error'], c: 1, ex: 'Los índices negativos cuentan desde el final: -1 es el último (50), -2 es el anteúltimo (40).'},
  {st: '¿Qué devuelve <code>nums[1:4]</code> si <code>nums = [10, 20, 30, 40, 50]</code>?', opts: ['<code>[10, 20, 30, 40]</code>', '<code>[20, 30, 40]</code>', '<code>[20, 30, 40, 50]</code>', '<code>[10, 20, 30]</code>'], c: 1, ex: 'El slicing <code>[1:4]</code> toma desde el índice 1 hasta el 3 (el 4 NO se incluye). Posiciones 1, 2, 3 corresponden a 20, 30, 40.'},
  {st: '¿Qué hace <code>lista.append(5)</code>?', opts: ['Crea una lista nueva con 5', 'Agrega 5 al final de la lista', 'Reemplaza el primer elemento con 5', 'Quita el 5 de la lista'], c: 1, ex: '<code>append()</code> modifica la lista agregando el elemento al final. La lista original cambia.'},
  {st: '¿Qué devuelve <code>len([1, [2, 3], 4, 5])</code>?', opts: ['<code>3</code>', '<code>4</code>', '<code>5</code>', '<code>6</code>'], c: 1, ex: '<code>len()</code> cuenta los elementos del primer nivel. La lista tiene 4 elementos: 1, [2,3] (que cuenta como 1), 4, 5.'},
  {st: '¿Qué pasa al ejecutar <code>t = (1, 2, 3); t[0] = 99</code>?', opts: ['t queda (99, 2, 3)', 'Error: las tuplas son inmutables', 't queda (1, 99, 3)', 't queda [99, 2, 3]'], c: 1, ex: 'Las tuplas son inmutables: no podés modificar sus elementos. Si necesitás modificar, tendrías que usar una lista.'},
  {st: 'Si <code>a = [1, 2, 3]</code> y <code>b = a</code>, ¿qué pasa al hacer <code>a.append(4)</code>?', opts: ['b queda [1, 2, 3]', 'b también queda [1, 2, 3, 4]', 'Error', 'a queda [1, 2, 3] y b queda [1, 2, 3, 4]'], c: 1, ex: 'Cuando hacés <code>b = a</code>, ambas variables apuntan a la MISMA lista en memoria. Modificar a modifica también lo que ve b. Para hacer una copia independiente: <code>b = a.copy()</code> o <code>b = a[:]</code>.'}
]);

registerExercises('pc', '4b', [
  {st: 'Si <code>d = {"a": 1, "b": 2}</code>, ¿qué devuelve <code>d["a"]</code>?', opts: ['<code>"a"</code>', '<code>1</code>', '<code>2</code>', 'Error'], c: 1, ex: 'Los diccionarios se acceden por clave. <code>d["a"]</code> devuelve el valor asociado a la clave "a", que es 1.'},
  {st: '¿Qué devuelve <code>d.get("x", 0)</code> si la clave "x" no existe?', opts: ['<code>None</code>', '<code>0</code>', 'Error', '<code>"x"</code>'], c: 1, ex: '<code>get()</code> con un segundo argumento devuelve ese valor si la clave no existe (en vez de tirar error). Devuelve 0.'},
  {st: '¿Cómo agregás una clave nueva al diccionario <code>d</code>?', opts: ['<code>d.append("nueva", valor)</code>', '<code>d["nueva"] = valor</code>', '<code>d + {"nueva": valor}</code>', '<code>d.insert("nueva", valor)</code>'], c: 1, ex: 'Para agregar (o modificar) una entrada, se asigna directamente: <code>d["clave"] = valor</code>. Si la clave no existía, se crea; si existía, se sobrescribe.'},
  {st: '¿Qué imprime este código?<br><pre class="code-block">d = {"nombre": "Ana", "edad": 25}\nfor k in d:\n    print(k)</pre>', opts: ['<code>nombre Ana edad 25</code>', '<code>nombre edad</code>', '<code>Ana 25</code>', '<code>("nombre","Ana") ("edad",25)</code>'], c: 1, ex: 'Al iterar un diccionario directamente con for, se recorren las <b>claves</b>. Para recorrer pares clave-valor usarías <code>d.items()</code>.'},
  {st: 'Dado <code>users = {"ariel": "pwd1", "juan": "pwd2"}</code>, ¿qué hace <code>users["ariel"] == "pwd1"</code>?', opts: ['Cambia la contraseña', 'Verifica si la clave coincide (True/False)', 'Tira error', 'Elimina el usuario'], c: 1, ex: 'Es una comparación con <code>==</code>. Devuelve True si el valor en la clave "ariel" es igual a "pwd1". No modifica nada.'},
  {st: '¿Qué devuelve este código?<br><pre class="code-block">personas = [{"nombre":"Ana","edad":25},{"nombre":"Bruno","edad":30}]\nsuma = 0\nfor p in personas:\n    suma += p["edad"]\nprint(suma)</pre>', opts: ['<code>2</code>', '<code>25</code>', '<code>30</code>', '<code>55</code>'], c: 3, ex: 'Es una lista de diccionarios. Se recorre sumando la edad de cada uno: 25 + 30 = 55.'}
]);

registerExercises('pc', '5', [
  {st: '¿Qué modo abre un archivo para escribir sobrescribiendo?', opts: ['<code>"r"</code>', '<code>"w"</code>', '<code>"a"</code>', '<code>"x"</code>'], c: 1, ex: '<code>"w"</code> (write) abre para escritura y BORRA el contenido anterior. Para agregar al final se usa <code>"a"</code> (append). Para leer es <code>"r"</code>.'},
  {st: '¿Cuál es la forma recomendada de abrir un archivo en Python?', opts: ['<code>archivo = open("f.txt")</code>', '<code>with open("f.txt") as archivo:</code>', '<code>archivo = file("f.txt")</code>', '<code>open("f.txt").read()</code>'], c: 1, ex: 'El <code>with</code> cierra automáticamente el archivo al terminar el bloque, incluso si hay un error. Es la forma más segura y concisa.'},
  {st: '¿Qué excepción se lanza al hacer <code>int("hola")</code>?', opts: ['<code>TypeError</code>', '<code>ValueError</code>', '<code>NameError</code>', '<code>SyntaxError</code>'], c: 1, ex: '<code>ValueError</code> ocurre cuando el tipo es correcto (string) pero el VALOR no se puede convertir. "hola" no es un número.'},
  {st: '¿Qué hace el bloque <code>except:</code> sin especificar excepción?', opts: ['Atrapa solo errores de sintaxis', 'Atrapa cualquier excepción', 'Es un error de sintaxis', 'Ignora el try'], c: 1, ex: 'Un <code>except:</code> sin tipo captura TODAS las excepciones. No es recomendado porque oculta errores inesperados. Es mejor capturar excepciones específicas.'},
  {st: '¿Qué imprime este código?<br><pre class="code-block">try:\n    n = int("123")\n    print("OK", n)\nexcept ValueError:\n    print("Error")</pre>', opts: ['<code>Error</code>', '<code>OK 123</code>', '<code>OK 0</code>', 'Nada'], c: 1, ex: '"123" sí se puede convertir a int (vale 123). No se lanza excepción, entonces se ejecuta el <code>print("OK", n)</code> normalmente.'},
  {st: '¿Para qué sirve el método <code>.strip()</code> en strings?', opts: ['Divide en partes', 'Convierte a mayúsculas', 'Quita espacios y saltos de línea al principio y al final', 'Cuenta caracteres'], c: 2, ex: '<code>.strip()</code> saca los espacios en blanco y saltos de línea (\\n) de los bordes. Es muy útil al leer archivos línea por línea, porque cada línea viene con \\n al final.'}
]);

registerExercises('pc', '6a', [
  {st: '¿Cómo se importa Pandas con el alias convencional?', opts: ['<code>import pandas</code>', '<code>import pandas as pd</code>', '<code>from pandas import *</code>', '<code>include pandas</code>'], c: 1, ex: '<code>import pandas as pd</code> es la convención universal. Todos los ejemplos y tutoriales usan <code>pd</code> como alias.'},
  {st: '¿Cómo cargás un archivo CSV en un DataFrame?', opts: ['<code>pd.read_csv("datos.csv")</code>', '<code>pd.open("datos.csv")</code>', '<code>pd.load("datos.csv")</code>', '<code>pd.csv("datos.csv")</code>'], c: 0, ex: '<code>pd.read_csv()</code> es la función estándar para leer archivos CSV y convertirlos en un DataFrame.'},
  {st: '¿Qué hace <code>df.head()</code>?', opts: ['Devuelve los títulos de las columnas', 'Muestra las primeras 5 filas', 'Muestra las últimas 5 filas', 'Muestra el tamaño del DataFrame'], c: 1, ex: '<code>head()</code> muestra las primeras filas (5 por defecto). Útil para echarle un vistazo rápido a los datos. Para ver las últimas: <code>tail()</code>.'},
  {st: '¿Cómo filtrás en Pandas las filas donde la columna "edad" sea mayor a 18?', opts: ['<code>df[df.edad > 18]</code>', '<code>df.filter(edad > 18)</code>', '<code>df.where(edad > 18)</code>', '<code>df[df["edad"] > 18]</code>'], c: 3, ex: 'Se pasa una condición booleana entre corchetes: <code>df[df["edad"] > 18]</code>. La forma con punto (<code>df.edad</code>) también funciona pero solo si el nombre de columna no tiene espacios ni caracteres especiales.'},
  {st: 'Para combinar dos condiciones en un filtro de Pandas, ¿qué operador se usa?', opts: ['<code>and</code>', '<code>&&</code>', '<code>&</code>', '<code>+</code>'], c: 2, ex: 'En pandas se usa <code>&</code> (and lógico bit a bit), no <code>and</code>. Y hay que envolver cada condición con paréntesis: <code>df[(df["edad"] > 18) & (df["ciudad"] == "CABA")]</code>.'},
  {st: '¿Qué devuelve <code>df["edad"].mean()</code>?', opts: ['La edad más frecuente', 'El promedio de la columna edad', 'El máximo', 'La cantidad de filas'], c: 1, ex: '<code>mean()</code> calcula el promedio (media aritmética) de una columna numérica.'}
]);

registerExercises('pc', '6b', [
  {st: '¿Cómo se importa matplotlib con el alias convencional?', opts: ['<code>import matplotlib as plt</code>', '<code>import matplotlib.pyplot as plt</code>', '<code>from matplotlib import plt</code>', '<code>import plt</code>'], c: 1, ex: 'Se importa el submódulo pyplot: <code>import matplotlib.pyplot as plt</code>. Es la convención universal.'},
  {st: '¿Qué función muestra el gráfico en pantalla?', opts: ['<code>plt.print()</code>', '<code>plt.draw()</code>', '<code>plt.show()</code>', '<code>plt.display()</code>'], c: 2, ex: '<code>plt.show()</code> renderiza y muestra el gráfico. Se llama al final, después de armar todo.'},
  {st: '¿Qué tipo de gráfico usarías para mostrar cómo cambió una variable a lo largo del tiempo?', opts: ['Torta', 'Barras', 'Línea', 'Dispersión'], c: 2, ex: 'Los gráficos de línea son ideales para series temporales o para mostrar evolución. Las barras se usan para comparar categorías y las tortas para proporciones.'},
  {st: '¿Para qué sirve <code>plt.xlabel("Tiempo")</code>?', opts: ['Hacer el eje X más corto', 'Etiquetar el eje X', 'Cambiar la escala del eje X', 'Ocultar el eje X'], c: 1, ex: '<code>xlabel()</code> pone el título del eje X. Para el Y: <code>ylabel()</code>. Para el título general: <code>title()</code>.'},
  {st: '¿Qué hace <code>plt.legend()</code>?', opts: ['Agrega leyenda usando los labels de cada plot', 'Cambia el tamaño de fuente', 'Guarda el gráfico', 'Añade cuadrícula'], c: 0, ex: '<code>legend()</code> muestra la leyenda con los labels que pusiste en cada <code>plt.plot(..., label="nombre")</code>. Sin labels no muestra nada.'},
  {st: '¿Cuál es el gráfico recomendado para ver la <b>distribución</b> de una variable numérica?', opts: ['Línea', 'Histograma', 'Dispersión', 'Torta'], c: 1, ex: 'El histograma agrupa los valores en rangos y muestra la frecuencia de cada rango. Perfecto para ver si la distribución es simétrica, sesgada, con picos, etc.'}
]);
