// Ejercicios PC - escapar las comillas y usar &quot; donde haga falta
registerExercises('pc', '1', [
  {st: '¿Cuál de las siguientes NO es un nombre válido para una variable en Python?', opts: ['<code>edad_usuario</code>', '<code>2edad</code>', '<code>Edad</code>', '<code>_temp</code>'], c: 1, ex: 'Reglas: las variables NO pueden empezar con número. ▸ <code>2edad</code> es INVÁLIDO. ▸ Las otras 3 SÍ son válidas: pueden empezar con letra (mayúscula o minúscula) o con guión bajo. ▸ Por qué las otras están bien: (A) <code>edad_usuario</code> empieza con letra; (C) <code>Edad</code> con mayúscula (Python distingue mayús/minús, así que <code>Edad ≠ edad</code> pero ambos son nombres válidos); (D) <code>_temp</code> con guión bajo (común para variables "privadas").'},
  {st: '¿Qué muestra en pantalla este código?<br><pre class="code-block">nombre = "Ariel"\nprint(nombre)</pre>', opts: ['<code>nombre</code>', '<code>Ariel</code>', '<code>"Ariel"</code>', 'Error'], c: 1, ex: 'La variable <code>nombre</code> guarda el string "Ariel". Al hacer <code>print(nombre)</code> se imprime el CONTENIDO (sin las comillas), no el nombre de la variable. ▸ Por qué las otras están mal: (A) "nombre" sería si imprimieras el literal <code>print("nombre")</code>; (C) "<code>"Ariel"</code>" con comillas no aparece, las comillas son delimitadores en el código; (D) no hay error, sintaxis válida.'},
  {st: '¿Qué hace la función <code>print()</code>?', opts: ['Guarda datos en un archivo', 'Muestra texto en pantalla', 'Lee datos del usuario', 'Ejecuta un archivo'], c: 1, ex: '<code>print()</code> imprime en pantalla lo que recibe entre paréntesis. Es la función básica de salida. ▸ Por qué las otras están mal: (A) "guardar en archivo" se hace con <code>open</code> + <code>write</code>; (C) "leer del usuario" es <code>input()</code>; (D) "ejecutar archivo" es <code>exec()</code> u otras técnicas.'},
  {st: 'En Python, el signo <code>=</code> sirve para:', opts: ['Comparar dos valores', 'Asignar un valor a una variable', 'Declarar una función', 'Terminar una línea'], c: 1, ex: '<code>=</code> es ASIGNACIÓN: guarda el valor de la derecha en la variable de la izquierda. ▸ Por qué las otras están mal: (A) comparar es <code>==</code> (doble igual); (C) declarar función es <code>def</code>; (D) terminar línea no es necesario en Python (a diferencia de C/Java con ;).'},
  {st: '¿Qué valor tiene <code>x</code> después de ejecutar estas líneas?<br><pre class="code-block">x = 10\nx = x + 5</pre>', opts: ['<code>10</code>', '<code>5</code>', '<code>15</code>', 'Error'], c: 2, ex: 'En la 2ª línea Python primero CALCULA <code>x + 5</code> (lado derecho) usando el valor actual de x (=10), obteniendo 15. Luego ASIGNA 15 a x. ▸ <code>x = x + 5</code> NO es ecuación matemática (que sería 0 = 5, absurda), es asignación. ▸ Por qué las otras están mal: (A) "10" sería el valor antes de la 2ª línea; (B) "5" sería el sumando; (D) no hay error.'}
]);

registerExercises('pc', '2', [
  {st: '¿Qué tipo de dato devuelve <code>type(3.14)</code>?', opts: ['<code>int</code>', '<code>float</code>', '<code>str</code>', '<code>bool</code>'], c: 1, ex: 'Los números con punto decimal son <code>float</code> (punto flotante). ▸ Por qué las otras están mal: (A) <code>int</code> son enteros sin decimales (3, 100); (C) <code>str</code> son cadenas de texto entre comillas ("3.14"); (D) <code>bool</code> son True/False.'},
  {st: '¿Cuánto vale <code>10 % 3</code>?', opts: ['<code>3</code>', '<code>3.33</code>', '<code>1</code>', '<code>0</code>'], c: 2, ex: '<code>%</code> es el operador MÓDULO (resto). 10 entre 3: cociente 3, resto 1. <code>10 % 3 = 1</code>. ▸ Por qué las otras están mal: (A) "3" es el cociente entero (10//3); (B) "3.33" es la división normal (10/3); (D) "0" sería si 3 dividiera exactamente a 10.'},
  {st: '¿Cuánto vale <code>10 // 3</code>?', opts: ['<code>3</code>', '<code>3.33</code>', '<code>1</code>', '<code>0</code>'], c: 0, ex: '<code>//</code> es DIVISIÓN ENTERA: cociente sin decimales. 10/3 = 3.33..., truncado a 3. ▸ Por qué las otras están mal: (B) "3.33" es la división normal con <code>/</code>; (C) "1" es el resto (con <code>%</code>); (D) "0" no aplica.'},
  {st: 'Si <code>edad = input("Edad: ")</code> y el usuario escribe <code>25</code>, ¿qué tipo tiene <code>edad</code>?', opts: ['<code>int</code>', '<code>float</code>', '<code>str</code>', 'Depende'], c: 2, ex: '<code>input()</code> SIEMPRE devuelve <code>str</code>, aunque el usuario escriba un número. Para usar como entero hay que convertir: <code>edad = int(input("Edad: "))</code>. ▸ Esta es la trampa más común para principiantes: si comparás <code>edad &gt; 18</code> sin convertir, error. ▸ Por qué las otras están mal: (A) (B) (D) implican que Python "adivina" el tipo del usuario, pero NO lo hace.'},
  {st: '¿Qué devuelve esta función?<br><pre class="code-block">def f(x, y):\n    return x + y * 2\n\nprint(f(3, 4))</pre>', opts: ['<code>14</code>', '<code>11</code>', '<code>10</code>', '<code>7</code>'], c: 1, ex: 'Por PRECEDENCIA, <code>*</code> tiene mayor prioridad que <code>+</code>. ▸ Primero: <code>y * 2 = 4·2 = 8</code>. Luego: <code>x + 8 = 3+8 = 11</code>. ▸ Por qué las otras están mal: (A) "14" sería <code>(x+y)·2</code> (paréntesis cambiarían el orden); (C) "10" sería <code>x·2 + y</code>; (D) "7" es <code>x+y</code> sin multiplicar.'},
  {st: '¿Qué resultado da <code>not (5 > 3 and 2 &lt; 1)</code>?', opts: ['<code>True</code>', '<code>False</code>', 'Error', '<code>None</code>'], c: 0, ex: '▸ <code>5 &gt; 3</code> = True. ▸ <code>2 &lt; 1</code> = False. ▸ <code>True and False</code> = False. ▸ <code>not False</code> = True. ▸ Por qué las otras están mal: (B) "False" sería sin el <code>not</code>; (C) sintaxis correcta; (D) <code>None</code> no surge de operadores booleanos.'}
]);

registerExercises('pc', '3', [
  {st: '¿Qué imprime este código?<br><pre class="code-block">x = 7\nif x > 10:\n    print("grande")\nelif x > 5:\n    print("medio")\nelse:\n    print("chico")</pre>', opts: ['<code>grande</code>', '<code>medio</code>', '<code>chico</code>', 'Nada'], c: 1, ex: 'Python evalúa en ORDEN, hasta encontrar la primera condición True (luego salta el resto). ▸ <code>x &gt; 10</code>: 7&gt;10 = False → continúa. ▸ <code>elif x &gt; 5</code>: 7&gt;5 = True → imprime "medio" Y SALE (no evalúa el else). ▸ Por qué las otras están mal: (A) "grande" requiere x&gt;10; (C) "chico" requiere que ambos if y elif fallen; (D) algo siempre se imprime con else final.'},
  {st: '¿Qué imprime este ciclo?<br><pre class="code-block">for i in range(3):\n    print(i)</pre>', opts: ['<code>1 2 3</code>', '<code>0 1 2</code>', '<code>0 1 2 3</code>', '<code>1 2</code>'], c: 1, ex: '<code>range(n)</code> genera 0, 1, ..., n−1 (NO incluye n). ▸ Para n=3: 0, 1, 2. ▸ Por qué las otras están mal: (A) (D) empezarían en 1 (Python empieza en 0); (C) incluye el 3 (range no lo incluye).'},
  {st: '¿Cuántas veces se imprime "hola" en este código?<br><pre class="code-block">i = 0\nwhile i &lt; 5:\n    print("hola")\n    i = i + 1</pre>', opts: ['<code>4</code>', '<code>5</code>', '<code>6</code>', 'Infinitas'], c: 1, ex: 'El ciclo se ejecuta para i = 0, 1, 2, 3, 4 (5 valores). En i=5, la condición <code>i &lt; 5</code> es False y termina. ▸ Por qué las otras están mal: (A) "4" se obtendría con <code>i &lt; 4</code> o si arrancara en 1; (C) "6" implicaría ejecutar también con i=5; (D) "infinito" sería sin <code>i = i + 1</code>.'},
  {st: '¿Qué genera <code>range(2, 10, 3)</code>?', opts: ['<code>2, 3, 4, 5, 6, 7, 8, 9</code>', '<code>2, 5, 8</code>', '<code>2, 5, 8, 11</code>', '<code>2, 10, 3</code>'], c: 1, ex: '<code>range(inicio, fin, paso)</code>: arranca en 2, suma 3, sin llegar a 10. ▸ Genera 2, 5, 8. El siguiente sería 11 pero ya supera 10 (el fin no se incluye). ▸ Por qué las otras están mal: (A) sería con paso=1; (C) "11" no se incluye; (D) imprime los 3 argumentos literales.'},
  {st: '¿Cuál es el riesgo principal de este código?<br><pre class="code-block">i = 0\nwhile i &lt; 10:\n    print(i)</pre>', opts: ['No imprime nada', 'Se ejecuta infinitas veces (ciclo infinito)', 'Da error de sintaxis', 'Imprime 0 solamente'], c: 1, ex: 'Falta INCREMENTAR i adentro del ciclo. Como i nunca cambia (queda en 0), <code>i &lt; 10</code> siempre es True → bucle infinito. Imprimirá 0 sin parar. ▸ Solución: agregar <code>i = i + 1</code> dentro del while. ▸ Por qué las otras están mal: (A) imprime infinitas veces; (C) sintácticamente válido; (D) bajo ejecución, sí imprime, pero infinitamente.'},
  {st: '¿Qué imprime este código?<br><pre class="code-block">for i in range(5):\n    if i == 3:\n        break\n    print(i)</pre>', opts: ['<code>0 1 2 3 4</code>', '<code>0 1 2</code>', '<code>0 1 2 3</code>', '<code>3</code>'], c: 1, ex: '<code>break</code> CORTA el ciclo. ▸ i=0: 0≠3, imprime 0. i=1: imprime 1. i=2: imprime 2. i=3: <code>break</code> ANTES del print → corta sin imprimir 3. ▸ Por qué las otras están mal: (A) sin break; (C) imprime 3 antes de salir (pero break va antes del print); (D) "3" sería si solo imprimiera el último.'}
]);

registerExercises('pc', '4a', [
  {st: 'Si <code>nums = [10, 20, 30, 40, 50]</code>, ¿qué devuelve <code>nums[-2]</code>?', opts: ['<code>50</code>', '<code>40</code>', '<code>20</code>', 'Error'], c: 1, ex: 'Índices negativos cuentan desde el FINAL: -1 último, -2 anteúltimo, etc. ▸ nums[-1]=50, nums[-2]=40. ▸ Por qué las otras están mal: (A) "50" es nums[-1]; (C) "20" es nums[1] (positivo); (D) no hay error con índices válidos.'},
  {st: '¿Qué devuelve <code>nums[1:4]</code> si <code>nums = [10, 20, 30, 40, 50]</code>?', opts: ['<code>[10, 20, 30, 40]</code>', '<code>[20, 30, 40]</code>', '<code>[20, 30, 40, 50]</code>', '<code>[10, 20, 30]</code>'], c: 1, ex: 'Slicing <code>[a:b]</code>: desde a (inclusive) hasta b (exclusive). ▸ nums[1:4] = posiciones 1, 2, 3 = 20, 30, 40. ▸ Por qué las otras están mal: (A) (D) empiezan en 0 mal; (C) incluye el índice 4 (que SÍ debería excluirse).'},
  {st: '¿Qué hace <code>lista.append(5)</code>?', opts: ['Crea una lista nueva con 5', 'Agrega 5 al final de la lista (modifica la lista original)', 'Reemplaza el primer elemento con 5', 'Quita el 5 de la lista'], c: 1, ex: '<code>append()</code> MUTA la lista agregando el elemento al final. La lista original CAMBIA, no devuelve nada (None). ▸ Por qué las otras están mal: (A) si quisieras lista nueva: <code>lista + [5]</code>; (C) reemplazar primero: <code>lista[0] = 5</code>; (D) quitar: <code>lista.remove(5)</code>.'},
  {st: '¿Qué devuelve <code>len([1, [2, 3], 4, 5])</code>?', opts: ['<code>3</code>', '<code>4</code>', '<code>5</code>', '<code>6</code>'], c: 1, ex: '<code>len()</code> cuenta elementos del PRIMER nivel. La lista tiene 4 elementos: 1, [2,3] (sub-lista cuenta como UNO), 4, 5. ▸ Por qué las otras están mal: (A) "3" descarta uno; (C) "5" cuenta los elementos internos de [2,3] como 2; (D) "6" no surge.'},
  {st: '¿Qué pasa al ejecutar <code>t = (1, 2, 3); t[0] = 99</code>?', opts: ['t queda (99, 2, 3)', 'Error: las tuplas son INMUTABLES', 't queda (1, 99, 3)', 't queda [99, 2, 3]'], c: 1, ex: 'Las TUPLAS son inmutables (no se pueden modificar después de creadas). ▸ Para modificar: usar lista [1,2,3] (mutable). ▸ Error: <code>TypeError: \'tuple\' object does not support item assignment</code>. ▸ Por qué las otras están mal: (A) (C) suponen mutación posible; (D) no convierte a lista automáticamente.'},
  {st: 'Si <code>a = [1, 2, 3]</code> y <code>b = a</code>, ¿qué pasa al hacer <code>a.append(4)</code>?', opts: ['b queda [1, 2, 3]', 'b también queda [1, 2, 3, 4]', 'Error', 'a queda [1, 2, 3] y b queda [1, 2, 3, 4]'], c: 1, ex: 'Cuando hacés <code>b = a</code>, AMBAS variables apuntan a la MISMA lista en memoria (no es copia). Modificar a también afecta a b. ▸ Para copia independiente: <code>b = a.copy()</code> o <code>b = a[:]</code>. ▸ Por qué las otras están mal: (A) (D) suponen copia independiente; (C) no hay error.'}
]);

registerExercises('pc', '4b', [
  {st: 'Si <code>d = {"a": 1, "b": 2}</code>, ¿qué devuelve <code>d["a"]</code>?', opts: ['<code>"a"</code>', '<code>1</code>', '<code>2</code>', 'Error'], c: 1, ex: 'Diccionarios se acceden por CLAVE. <code>d["a"]</code> devuelve el VALOR asociado, que es 1. ▸ Por qué las otras están mal: (A) "a" es la clave en sí (no su valor); (C) "2" es el valor de "b"; (D) no hay error con clave existente.'},
  {st: '¿Qué devuelve <code>d.get("x", 0)</code> si la clave "x" no existe?', opts: ['<code>None</code>', '<code>0</code>', 'Error', '<code>"x"</code>'], c: 1, ex: '<code>d.get(clave, default)</code>: si la clave existe, devuelve su valor; si NO existe, devuelve el default (acá 0) sin lanzar error. ▸ Por qué las otras están mal: (A) "None" es el default cuando NO especificás (<code>d.get("x")</code>); (C) acceso directo <code>d["x"]</code> SÍ daría error (KeyError); (D) "x" no se devuelve.'},
  {st: '¿Cómo agregás una clave nueva al diccionario <code>d</code>?', opts: ['<code>d.append("nueva", valor)</code>', '<code>d["nueva"] = valor</code>', '<code>d + {"nueva": valor}</code>', '<code>d.insert("nueva", valor)</code>'], c: 1, ex: 'Para agregar (o modificar) entrada en dict: <code>d["clave"] = valor</code>. Si la clave NO existía, se crea; si existía, se sobrescribe. ▸ Por qué las otras están mal: (A) <code>append</code> es de listas; (C) los dicts no soportan <code>+</code> directamente (sí <code>**</code> para fusionar en Python 3.5+); (D) <code>insert</code> es de listas.'},
  {st: '¿Qué imprime este código?<br><pre class="code-block">d = {"nombre": "Ana", "edad": 25}\nfor k in d:\n    print(k)</pre>', opts: ['<code>nombre Ana edad 25</code>', '<code>nombre edad</code>', '<code>Ana 25</code>', '<code>("nombre","Ana") ("edad",25)</code>'], c: 1, ex: 'Iterar un diccionario directamente con <code>for</code> recorre las CLAVES. ▸ Imprime: nombre, edad (cada una en línea aparte). ▸ Por qué las otras están mal: (A) imprimiría todo; (C) recorrería <code>d.values()</code>; (D) recorrería <code>d.items()</code>.'},
  {st: 'Dado <code>users = {"ariel": "pwd1", "juan": "pwd2"}</code>, ¿qué hace <code>users["ariel"] == "pwd1"</code>?', opts: ['Cambia la contraseña', 'Verifica si el valor coincide y devuelve True/False', 'Tira error', 'Elimina el usuario'], c: 1, ex: 'Es una COMPARACIÓN con <code>==</code>. Devuelve True si el valor en la clave "ariel" es igual a "pwd1", sino False. NO modifica nada. ▸ Por qué las otras están mal: (A) cambiar sería con <code>=</code> (asignación); (C) no hay error con clave existente; (D) eliminar es <code>del users["ariel"]</code>.'},
  {st: '¿Qué devuelve este código?<br><pre class="code-block">personas = [{"nombre":"Ana","edad":25},{"nombre":"Bruno","edad":30}]\nsuma = 0\nfor p in personas:\n    suma += p["edad"]\nprint(suma)</pre>', opts: ['<code>2</code>', '<code>25</code>', '<code>30</code>', '<code>55</code>'], c: 3, ex: 'Lista de diccionarios. Recorre y suma cada edad: ▸ p={"nombre":"Ana","edad":25}: suma = 0+25 = 25. ▸ p={"nombre":"Bruno","edad":30}: suma = 25+30 = 55. ▸ Por qué las otras están mal: (A) "2" es len(personas); (B) (C) son las edades individuales.'}
]);

registerExercises('pc', '5', [
  {st: '¿Qué modo abre un archivo para escribir SOBRESCRIBIENDO?', opts: ['<code>"r"</code>', '<code>"w"</code>', '<code>"a"</code>', '<code>"x"</code>'], c: 1, ex: '<code>"w"</code> (write) abre para escritura y BORRA contenido anterior (sobrescribe). ▸ Por qué las otras están mal: (A) <code>"r"</code> (read) es solo lectura; (C) <code>"a"</code> (append) agrega al FINAL sin borrar; (D) <code>"x"</code> (exclusive) crea archivo nuevo, falla si existe.'},
  {st: '¿Cuál es la forma RECOMENDADA de abrir un archivo en Python?', opts: ['<code>archivo = open("f.txt")</code>', '<code>with open("f.txt") as archivo:</code>', '<code>archivo = file("f.txt")</code>', '<code>open("f.txt").read()</code>'], c: 1, ex: 'Context manager <code>with</code>: cierra el archivo automáticamente al salir del bloque, INCLUSO si hay excepción. Es lo más seguro y conciso. ▸ Por qué las otras están mal: (A) requiere <code>archivo.close()</code> manual (fácil de olvidar); (C) <code>file()</code> no existe en Python 3; (D) funciona pero el archivo queda abierto.'},
  {st: '¿Qué excepción se lanza al hacer <code>int("hola")</code>?', opts: ['<code>TypeError</code>', '<code>ValueError</code>', '<code>NameError</code>', '<code>SyntaxError</code>'], c: 1, ex: '<code>ValueError</code>: el TIPO es correcto (string) pero el VALOR no se puede convertir a int. ▸ Por qué las otras están mal: (A) <code>TypeError</code> sería tipo incorrecto (ej. <code>int([1,2])</code>); (C) <code>NameError</code> es variable no definida; (D) <code>SyntaxError</code> es código mal escrito.'},
  {st: '¿Qué hace el bloque <code>except:</code> sin especificar excepción?', opts: ['Atrapa solo errores de sintaxis', 'Atrapa CUALQUIER excepción (no recomendado)', 'Es un error de sintaxis', 'Ignora el try'], c: 1, ex: '<code>except:</code> sin tipo captura TODAS las excepciones (incluso KeyboardInterrupt y SystemExit, que no deberían atraparse). ▸ Mejor práctica: capturar tipos específicos (ValueError, KeyError, etc.). ▸ Por qué las otras están mal: (A) atrapa todo, no solo sintaxis; (C) sintaxis válida; (D) no ignora.'},
  {st: '¿Qué imprime este código?<br><pre class="code-block">try:\n    n = int("123")\n    print("OK", n)\nexcept ValueError:\n    print("Error")</pre>', opts: ['<code>Error</code>', '<code>OK 123</code>', '<code>OK 0</code>', 'Nada'], c: 1, ex: '"123" SÍ se puede convertir a int (vale 123). NO hay excepción. Se ejecuta el cuerpo del try: <code>print("OK", 123)</code> imprime "OK 123" (con espacio entre los dos). ▸ Por qué las otras están mal: (A) "Error" sería con <code>int("hola")</code> (no convertible); (C) "OK 0" no surge del valor 123; (D) sí imprime.'},
  {st: '¿Para qué sirve el método <code>.strip()</code> en strings?', opts: ['Divide en partes', 'Convierte a mayúsculas', 'Quita espacios y saltos de línea al principio y al final', 'Cuenta caracteres'], c: 2, ex: '<code>.strip()</code> elimina whitespace (espacios, tabs, \\n) de los EXTREMOS de la string. ▸ Útil al leer archivos línea por línea (cada línea termina con \\n). ▸ Por qué las otras están mal: (A) "dividir" es <code>.split()</code>; (B) "mayúsculas" es <code>.upper()</code>; (D) "contar" es <code>len()</code>.'}
]);

registerExercises('pc', '6a', [
  {st: '¿Cómo se importa Pandas con el alias convencional?', opts: ['<code>import pandas</code>', '<code>import pandas as pd</code>', '<code>from pandas import *</code>', '<code>include pandas</code>'], c: 1, ex: 'Convención universal: <code>import pandas as pd</code>. Todos los tutoriales y código profesional usan <code>pd</code>. ▸ Por qué las otras están mal: (A) válido pero requeriría escribir <code>pandas.DataFrame()</code> cada vez (verboso); (C) importa todo al namespace global (mala práctica); (D) <code>include</code> no es Python.'},
  {st: '¿Cómo cargás un archivo CSV en un DataFrame?', opts: ['<code>pd.read_csv("datos.csv")</code>', '<code>pd.open("datos.csv")</code>', '<code>pd.load("datos.csv")</code>', '<code>pd.csv("datos.csv")</code>'], c: 0, ex: '<code>pd.read_csv()</code> es la función estándar para leer CSV y devolver un DataFrame. ▸ Hermanos: <code>pd.read_excel</code>, <code>pd.read_json</code>, <code>pd.read_sql</code>, etc. ▸ Por qué las otras están mal: (B) (C) (D) no son funciones reales de pandas.'},
  {st: '¿Qué hace <code>df.head()</code>?', opts: ['Devuelve los títulos de las columnas', 'Muestra las primeras 5 filas (por defecto)', 'Muestra las últimas 5 filas', 'Muestra el tamaño del DataFrame'], c: 1, ex: '<code>df.head()</code> muestra las primeras 5 filas (parámetro opcional: <code>head(n)</code>). Útil para vista rápida. ▸ Por qué las otras están mal: (A) "títulos" es <code>df.columns</code>; (C) "últimas" es <code>df.tail()</code>; (D) "tamaño" es <code>df.shape</code> o <code>len(df)</code>.'},
  {st: '¿Cómo filtrás en Pandas las filas donde la columna "edad" sea mayor a 18?', opts: ['<code>df[df.edad > 18]</code>', '<code>df.filter(edad > 18)</code>', '<code>df.where(edad > 18)</code>', '<code>df[df["edad"] > 18]</code>'], c: 3, ex: 'Sintaxis estándar: <code>df[condición_booleana]</code>. La condición se construye con <code>df["columna"] operador valor</code>. ▸ Acá: <code>df[df["edad"] &gt; 18]</code>. ▸ La forma con punto <code>df.edad</code> también funciona pero solo con nombres "limpios". ▸ Por qué las otras están mal: (A) válido pero menos seguro; (B) <code>filter()</code> existe pero filtra columnas, no filas; (C) <code>where()</code> mantiene filas pero pone NaN, no las elimina.'},
  {st: 'Para combinar dos condiciones en un filtro de Pandas, ¿qué operador se usa?', opts: ['<code>and</code>', '<code>&&</code>', '<code>&</code> (con paréntesis en cada condición)', '<code>+</code>'], c: 2, ex: 'En pandas se usa <code>&</code> (and bit a bit) para combinar Series booleanas. Cada condición DEBE ir entre paréntesis. ▸ Ej: <code>df[(df["edad"] &gt; 18) & (df["ciudad"] == "CABA")]</code>. ▸ Por qué las otras están mal: (A) <code>and</code> da error con Series; (B) <code>&&</code> no existe en Python; (D) <code>+</code> sumaría booleanos como números.'},
  {st: '¿Qué devuelve <code>df["edad"].mean()</code>?', opts: ['La edad más frecuente', 'El promedio (media aritmética) de la columna edad', 'El máximo', 'La cantidad de filas'], c: 1, ex: '<code>mean()</code> calcula la media aritmética de una columna numérica. ▸ Por qué las otras están mal: (A) "más frecuente" es <code>mode()</code>; (C) máximo es <code>max()</code>; (D) cantidad es <code>count()</code> o <code>len()</code>.'}
]);

registerExercises('pc', '6b', [
  {st: '¿Cómo se importa matplotlib con el alias convencional?', opts: ['<code>import matplotlib as plt</code>', '<code>import matplotlib.pyplot as plt</code>', '<code>from matplotlib import plt</code>', '<code>import plt</code>'], c: 1, ex: 'Se importa el SUBMÓDULO <code>pyplot</code> con alias <code>plt</code>. Es la convención universal. ▸ Por qué las otras están mal: (A) sin <code>.pyplot</code> no tenés acceso directo a <code>plt.plot()</code>, <code>plt.show()</code>; (C) no es la sintaxis correcta de Python; (D) <code>plt</code> no es módulo.'},
  {st: '¿Qué función muestra el gráfico en pantalla?', opts: ['<code>plt.print()</code>', '<code>plt.draw()</code>', '<code>plt.show()</code>', '<code>plt.display()</code>'], c: 2, ex: '<code>plt.show()</code> renderiza y muestra el gráfico en una ventana. Se llama al FINAL, después de <code>plt.plot()</code>, <code>plt.title()</code>, etc. ▸ Por qué las otras están mal: (A) (D) no existen en plt; (B) <code>draw()</code> es de bajo nivel y no abre ventana en scripts.'},
  {st: '¿Qué tipo de gráfico usarías para mostrar cómo cambió una variable A LO LARGO DEL TIEMPO?', opts: ['Torta', 'Barras', 'Línea', 'Dispersión'], c: 2, ex: 'Gráfico de LÍNEA: ideal para series temporales y mostrar evolución. ▸ Por qué las otras están mal: (A) torta para PROPORCIONES de un total; (B) barras para COMPARAR categorías; (D) dispersión para ver RELACIÓN entre dos variables (puntos).'},
  {st: '¿Para qué sirve <code>plt.xlabel("Tiempo")</code>?', opts: ['Hacer el eje X más corto', 'Etiquetar (poner título) al eje X', 'Cambiar la escala del eje X', 'Ocultar el eje X'], c: 1, ex: '<code>xlabel()</code> pone el TÍTULO del eje X. ▸ Análogos: <code>ylabel()</code> para el eje Y, <code>title()</code> para el título general. ▸ Por qué las otras están mal: (A) longitud es por <code>xlim()</code>; (C) escala con <code>xscale()</code>; (D) ocultar con <code>plt.gca().axes.xaxis.set_visible(False)</code>.'},
  {st: '¿Qué hace <code>plt.legend()</code>?', opts: ['Agrega leyenda usando los labels de cada plot', 'Cambia el tamaño de fuente', 'Guarda el gráfico', 'Añade cuadrícula'], c: 0, ex: '<code>legend()</code> muestra la leyenda con los <code>label</code> que pusiste en cada <code>plt.plot(..., label="nombre")</code>. ▸ Sin labels, no muestra nada útil. ▸ Por qué las otras están mal: (B) tamaño con <code>plt.rcParams</code> o <code>fontsize</code>; (C) guardar con <code>plt.savefig()</code>; (D) cuadrícula con <code>plt.grid()</code>.'},
  {st: '¿Cuál es el gráfico recomendado para ver la DISTRIBUCIÓN de una variable numérica?', opts: ['Línea', 'Histograma', 'Dispersión', 'Torta'], c: 1, ex: 'HISTOGRAMA: agrupa valores en rangos (bins) y muestra la frecuencia de cada rango. Perfecto para ver simetría, sesgo, picos, normalidad. ▸ Por qué las otras están mal: (A) línea para evolución temporal; (C) dispersión para 2 variables; (D) torta para proporciones (no distribuciones).'}
]);
