registerExercises('algebra-parcial', '1', [
  {st: 'El parcial Escayola tiene 8 ejercicios de opción múltiple. ¿Cuánto vale cada uno?', opts: ['1 punto', '1,25 puntos', '1,5 puntos', '2 puntos'], c: 1, ex: 'El parcial suma 10 puntos repartidos en 8 ejercicios: 10/8 = 1,25 puntos cada uno. No hay ejercicios que valgan más que otros.'},
  {st: 'Si en el enunciado ves "norma", "ángulo" y "producto escalar", el tema es:', opts: ['Subespacios', 'Cónicas', 'Vectores', 'Rectas y planos'], c: 2, ex: 'Norma, ángulo y producto escalar son conceptos exclusivos de la unidad de vectores (sesión 1). La fórmula clave es v·w = ‖v‖·‖w‖·cos(α).'},
  {st: 'Si el enunciado pide "la ecuación de la recta directriz y las coordenadas del foco", el tema es:', opts: ['Vectores', 'Rectas y planos', 'Subespacios', 'Cónicas'], c: 3, ex: 'Foco y directriz son elementos exclusivos de las parábolas (cónicas). El método es siempre completar cuadrados para llevar a la forma canónica (y−k)² = 4p(x−h).'},
  {st: 'La estrategia cuando un ejercicio tiene un parámetro k desconocido es:', opts: ['Probar las 4 opciones', 'Adivinar por descarte', 'Reemplazar k en la condición del enunciado y despejar', 'No se puede resolver sin más datos'], c: 2, ex: 'Siempre que hay un parámetro, la receta es: identificar la condición del enunciado (centro dado, det=0, etc.), reemplazar la expresión con k, y despejar. Es la estrategia universal del parcial.'},
  {st: 'La fórmula de distancia de un punto A = (x₀, y₀, z₀) al plano ax+by+cz = d es:', opts: ['‖A‖ / √(a²+b²+c²)', '|ax₀+by₀+cz₀−d| / √(a²+b²+c²)', '|ax₀+by₀+cz₀| / √(a²+b²+c²)', '|ax₀+by₀+cz₀+d| / ‖A‖'], c: 1, ex: 'La fórmula directa es d = |ax₀+by₀+cz₀−d| / √(a²+b²+c²). También se puede calcular via recta normal: escribís la recta normal al plano por A, calculás la intersección B con el plano, y medís ‖AB‖.'},
  {st: 'Para reconocer si un conjunto de 3 vectores en R³ es base, el test definitivo es:', opts: ['Verificar que ningún vector es nulo', 'Calcular el determinante de la matriz formada por los vectores', 'Ver si los vectores suman cero', 'Verificar que tienen distintas normas'], c: 1, ex: 'Un conjunto es base de R³ si y solo si los vectores son L.I., lo que equivale a que el determinante de la matriz formada por ellos (filas o columnas) sea distinto de cero.'}
]);

registerExercises('algebra-parcial', '2', [
  {st: 'v tiene norma √5, w tiene norma 8 y el ángulo entre ellos es 2π/3. ¿Cuánto vale v·w?', opts: ['−4√5', '4√5', '−4√3', '8√5'], c: 0, ex: 'v·w = ‖v‖·‖w‖·cos(α) = √5·8·cos(2π/3) = 8√5·(−1/2) = −4√5. cos(2π/3) = −1/2 (ángulo en el segundo cuadrante).'},
  {st: 'v = (k, −k, k), w = (0, 0, −k) con k > 0. cos(ángulo entre v y w) vale:', opts: ['−1/3', '1/3', '−1/√3', '1/√3'], c: 2, ex: 'v·w = k·0+(−k)·0+k·(−k) = −k². ‖v‖ = √(3k²) = k√3. ‖w‖ = k. cos(α) = −k²/(k√3·k) = −1/√3.'},
  {st: 'w es paralelo a v = (5/7, −1/7, −2/7) y tiene norma 3√30. ¿Cuántas soluciones posibles tiene w?', opts: ['Solo una (k > 0)', 'Dos (k positivo y k negativo)', 'Infinitas', 'Ninguna'], c: 1, ex: 'w = k·v para algún k ≠ 0. Imponiendo ‖w‖ = |k|·‖v‖ = 3√30, se obtiene dos valores de k (positivo y negativo). El enunciado suele dar una condición adicional para elegir uno.'},
  {st: 'β·(3/11, −1/11, 2/11) + (−10, 9, 1) = (−7, 8, 3). ¿Cuánto vale β?', opts: ['−11', '1/11', '11', '−1/11'], c: 2, ex: 'Coordenada x: 3β/11 − 10 = −7 → 3β/11 = 3 → β = 11. Verificás con y: −β/11 + 9 = 8 → β = 11 ✓. Y con z: 2β/11 + 1 = 3 → β = 11 ✓.'},
  {st: 'A = (−1/3, 2/3, 1/3), B = (0, 4/3, −7/3), C = (1, m, −m), D = (1, 0, −m). Si ‖AB‖ = ‖CD‖, entonces:', opts: ['m = 23/3', 'm ∈ ℝ', '|m| = √(23/3)', 'm = ±√(23/3)'], c: 2, ex: 'AB = B−A = (1/3, 2/3, −8/3). ‖AB‖² = 1/9+4/9+64/9 = 69/9. CD = D−C = (−k, −m, 0). ‖CD‖² = k²+m²... El cálculo da m² = 23/3, es decir |m| = √(23/3). Hay dos soluciones.'},
  {st: 'v es paralelo al versor î, tiene norma 7 y una coordenada negativa. ¿Cuáles son sus coordenadas?', opts: ['(7, 0, 0)', '(0, −7, 0)', '(−7, 0, 0)', '(0, 0, −7)'], c: 2, ex: 'Paralelo al versor î = (1,0,0) significa que v = (a, 0, 0). Norma 7 → |a| = 7 → a = ±7. Coordenada negativa → a = −7. v = (−7, 0, 0).'},
  {st: 'v = (−7, 0, 0) y M = (15/2, 17/4, −1/10) es punto medio entre los extremos de v y u. ¿Cuánto vale u?', opts: ['(−22, −17/2, 1/5)', '(22, 17/2, −1/5)', '(4, 17/2, −1/5)', '(22, −17/2, 1/5)'], c: 1, ex: 'u = 2M − v. Coord x: 2·(15/2) − (−7) = 15+7 = 22. Coord y: 2·(17/4) − 0 = 17/2. Coord z: 2·(−1/10) − 0 = −1/5. u = (22, 17/2, −1/5).'}
]);

registerExercises('algebra-parcial', '3', [
  {st: 'Para hallar la distancia del punto A al plano Π, el método del parcial es:', opts: ['Evaluar A en la ecuación del plano directamente', 'Escribir la recta normal al plano por A, hallar intersección B con Π, medir ‖AB‖', 'Calcular el producto escalar de A con el normal del plano', 'Sumar las coordenadas de A'], c: 1, ex: 'La recta normal al plano ax+by+cz=d que pasa por A tiene dirección (a, b, c). Se parametriza, se reemplaza en la ecuación del plano para hallar t, se calcula B y luego ‖AB‖. También existe la fórmula directa |ax₀+by₀+cz₀−d|/√(a²+b²+c²).'},
  {st: 'A = (−1, 2, 3), Π: 2x+y−z+1 = 0. La distancia de A a Π es:', opts: ['√6', '√6/3', '6/√3', '0'], c: 1, ex: 'Recta normal: X = t(2,1,−1)+(−1,2,3). Punto: (2t−1, t+2, −t+3). En Π: 2(2t−1)+(t+2)−(−t+3)+1=0 → 6t−2=0 → t=1/3. B=(−1/3, 7/3, 8/3). ‖AB‖=‖(2/3,1/3,−1/3)‖=√(6/9)=√6/3.'},
  {st: 'Dos rectas tienen vectores directores d₁ = (−4/3, 0, −3) y d₂ = (1/2, 2/7, −2/9). d₁·d₂ vale:', opts: ['−2/3 + 0 + 2/3 = 0', '1', '−1', '2/3'], c: 0, ex: 'd₁·d₂ = (−4/3)(1/2) + 0·(2/7) + (−3)(−2/9) = −2/3 + 0 + 2/3 = 0. Si el producto escalar es cero Y las rectas no se intersectan, son ortogonales (en R³ las rectas pueden ser ortogonales sin cruzarse).'},
  {st: 'Si dos rectas tienen vectores directores que NO son múltiplos y su intersección es vacía, son:', opts: ['Paralelas', 'Coincidentes', 'Ortogonales (si d₁·d₂=0)', 'Concurrentes'], c: 2, ex: 'Si los directores no son múltiplos → no paralelas ni coincidentes. Si la intersección es vacía → no concurrentes. La única opción restante es que sean ortogonales (cruces perpendiculares en R³), lo que se verifica con d₁·d₂ = 0.'},
  {st: 'Recta X = α(3,6,9)+(4,2,−1), plano −x+y−z = 1. La posición relativa es:', opts: ['La recta está contenida en el plano', 'La recta y el plano son paralelos', 'La recta y el plano son ortogonales', 'La recta y el plano se cortan en un único punto'], c: 3, ex: 'Reemplazamos (3α+4, 6α+2, 9α−1) en −x+y−z=1: −(3α+4)+(6α+2)−(9α−1)=1 → −6α−1=1 → α=−1/3. Único valor de α → se cortan en un punto.'},
  {st: 'A = (7,−10,−1). Plano: 2x−3y+z=1. El simétrico de A respecto del plano es:', opts: ['(2,−3,1)', '(5,−8,7)', '(1,−1,−4)', '(−5,8,−7)'], c: 3, ex: 'Recta normal: X=t(2,−3,1)+(7,−10,−1). En plano: 2(2t+7)−3(−3t−10)+(t−1)=1 → 14t+43=1 → t=−3. Pie B=(1,−1,−4). A\'=2B−A=(2·1−7, 2·(−1)−(−10), 2·(−4)−(−1))=(−5,8,−7).'},
  {st: 'Para el plano paramétrico X = s(1,1,0)+t(2,0,2)+(1,1,1) y el plano 2: x+z=1+y, la posición relativa es:', opts: ['Son perpendiculares', 'La intersección es una recta y no son perpendiculares', 'Son paralelos', 'Son coincidentes'], c: 1, ex: 'Normal de π₂: n₂=(1,−1,1). Normal de π₁: n₁=(1,1,0)×(2,0,2)=(2,−2,−2). ¿Múltiplos? (1,−1,−1) vs (1,−1,1): la 3° componente da −1 vs 1. No. → No paralelos → intersecan en recta. n₁·n₂=(1)(1)+(−1)(−1)+(−1)(1)=1+1−1=1≠0 → no perpendiculares.'}
]);

registerExercises('algebra-parcial', '4', [
  {st: '{(1,0,−1),(−1,k,0),(0,−2,k+1)} no es base de R³ para k ∈ Z>0. ¿Cuál es ese k?', opts: ['−2', '1', '2', '−1'], c: 1, ex: 'det = k(k+1) − (−2) = k²+k+2−2... cuidado, expandiendo bien: det = k²+k−2 = 0 → (k+2)(k−1)=0 → k=−2 o k=1. Como k ∈ Z>0 → k=1.'},
  {st: 'S = {(x₁,x₂,x₃,x₄) ∈ R⁴ : nx₁+2x₂=0 ∧ x₂+mx₃−x₄=0}. Base de S: {(−2,1,0,1),(0,0,1,3)}. Valores de n y m:', opts: ['n=−1, m=3', 'n=1, m=−3', 'n=−1, m=−3', 'n=1, m=3'], c: 3, ex: 'Reemplazamos (−2,1,0,1) en nx₁+2x₂=0: −2n+2=0 → n=1. Reemplazamos (0,0,1,3) en x₂+mx₃−x₄=0: 0+m−3=0 → m=3.'},
  {st: 'A = {(0,−2,−1),(k,1,0),(−8,0,k+3)}. Para que A sea generador de R³, k debe ser:', opts: ['k ∈ {1,−4}', 'k ∈ ℝ \\ {−1,4}', 'k ∈ ℝ \\ {1,−4}', 'k ∈ ∅'], c: 2, ex: 'Para que NO sea generador: det=0. El determinante da k²+3k−4=0 → (k+4)(k−1)=0 → k=1 o k=−4. Entonces para que SÍ sea generador: k ∈ ℝ \\ {1,−4}.'},
  {st: 'S = {(x₁,x₂,x₃,x₄) ∈ R⁴ : x₁+x₄=0}. ¿Cuál conjunto es generador de S?', opts: ['{(1,0,0,−1),(0,1,0,0),(1,0,0,1)}', '{(1,1,0,−1),(0,1,0,0),(1,0,0,−1)}', '{(1,0,0,−1),(0,1,0,0),(0,0,1,0)}', '{(0,1,0,0),(1,0,−1,0),(1,0,0,−1)}'], c: 2, ex: 'Opción C: (1,0,0,−1): 1+(−1)=0 ✓. (0,1,0,0): 0+0=0 ✓. (0,0,1,0): 0+0=0 ✓. Son L.I. (det≠0) y dim S = 3 → generan S. En la opción A, el vector (1,0,0,1) no cumple 1+1=0. En la B, los vectores son L.D.'},
  {st: '¿Cuál vector es combinación lineal de (1,2,−1) y (−1,−1,2)?', opts: ['(−1,0,3)', '(0,1,−1)', '(2,3,3)', '(0,−1,1)'], c: 0, ex: '(1,2,−1) + 2(−1,−1,2) = (1−2, 2−2, −1+4) = (−1,0,3). Verificamos: α=1, β=2 satisface las 3 ecuaciones del sistema.'},
  {st: '{(1,0,2),(0,−2,−k),(1/2,−k−1,0)}. k ∈ Z (negativo) para que NO sea base. ¿Cuál k?', opts: ['2', '1', '−2', '−1'], c: 2, ex: 'det = 1·(0−(−k)(−k−1)) − 0 + 2·(0·(−k−1)−(−2)·(1/2)) = −k²−k + 2 = 0 → k²+k−2 = 0 → k=1 o k=−2. Como k ∈ Z (negativo) → k=−2.'},
  {st: 'S = {x ∈ R⁴ : 6x₁+nx₂=0 ∧ 2x₂+x₃+mx₄=0}. Base: {(1,2,0,1),(0,0,−3,1)}. Valores n y m:', opts: ['n=−3, m=−3', 'n=3, m=−3', 'n=−3, m=3', 'n=3, m=3'], c: 1, ex: 'Reemplazamos (1,2,0,1) en 6x₁+nx₂=0: 6+2n=0 → n=−3. Reemplazamos (0,0,−3,1) en 2x₂+x₃+mx₄=0: 0+(−3)+m=0 → m=3. ¡Cuidado! n=−3 y m=3, opción B.'}
]);

registerExercises('algebra-parcial', '5', [
  {st: 'En la hipérbola (x−h)²/a² − (y−k)²/b² = 1, ¿cuál es la relación entre a, b y c (semidistancia focal)?', opts: ['c² = a² − b²', 'c² = a² + b²', 'a² = b² + c²', 'b² = a² + c²'], c: 1, ex: 'Para la hipérbola siempre c² = a² + b² (con c > a). A diferencia de la elipse donde c² = a² − b² (con c < a). Confundirlas es el error más caro en cónicas.'},
  {st: '144x² − 24kx + 16y² = 63 es una elipse con centro (−0,75; 0). ¿Cuánto vale k?', opts: ['9', '−18', '−9', '0,5'], c: 2, ex: 'Completar cuadrados en x: 144(x−k/12)²+16y²=63+k²/1. Centro: k/12=−0,75 → k=−9. Respuesta C).'},
  {st: 'Hipérbola H con excentricidad 1,8 y focos F₁=(0,−8) y F₂=(0,10). El centro de H es:', opts: ['(0,0)', '(0,1)', '(0,2)', '(0,−1)'], c: 1, ex: 'El centro es el punto medio entre los focos: ((0+0)/2, (−8+10)/2) = (0, 1).'},
  {st: 'Misma hipérbola H (e=1,8, focos en y). Sabiendo que c=9, los vértices de H son:', opts: ['(0,±5)', '(0,1±5) = (0,6) y (0,−4)', '(0,±9)', '(0,1±9) = (0,10) y (0,−8)'], c: 1, ex: 'e = c/a → 1,8 = 9/a → a = 5. Centro (0,1). Vértices en (0, 1+5) = (0,6) y (0, 1−5) = (0,−4).'},
  {st: '3x² − y² − 6x − 30y − 546 = 0. Completando cuadrados, la forma canónica es:', opts: ['(x−1)²/108 − (y+15)²/324 = 1', '(x+1)²/108 − (y−15)²/324 = 1', '(y+15)²/324 − (x−1)²/108 = 1', '(x−1)²/324 − (y+15)²/108 = 1'], c: 0, ex: '3(x²−2x) − (y²+30y) = 546. 3(x−1)²−3 − (y+15)²+225 = 546. 3(x−1)² − (y+15)² = 324. Divido por 324: (x−1)²/108 − (y+15)²/324 = 1.'},
  {st: 'y² − 8x + 3 = 6y. La directriz de la parábola es:', opts: ['x = −2,75', 'y = −2,75', 'x = 1,25', 'y = 1,25'], c: 0, ex: 'Reordenamos: y²−6y = 8x−3. (y−3)²−9 = 8x−3. (y−3)² = 8(x+3/4). Vértice (−0,75; 3), 4p=8 → p=2. Directriz: x = −0,75−2 = −2,75.'},
  {st: 'M = {(x+4)²+(y+3)²=9}, N = {3x²+y²+6y=−6}. ¿Cuántos puntos tienen en común?', opts: ['Ninguno', 'Exactamente dos', 'Exactamente uno', 'Más de dos'], c: 2, ex: 'M: circunferencia centro (−4,−3) radio 3. N: 3x²+(y+3)²=3 → x²+(y+3)²/3=1, elipse centro (0,−3). El punto del borde derecho de M hacia el centro de N es (−1,−3). En N: 1+0=1 ✓. Solo ese punto.'}
]);

registerExercises('algebra-parcial', '6', [
  {st: 'El simétrico A\' de A respecto del plano se calcula como:', opts: ['A\' = B − A (B = pie de la normal)', 'A\' = 2B − A (B = pie de la normal)', 'A\' = B/2', 'A\' = A − 2B'], c: 1, ex: 'B es el punto medio entre A y A\'. Entonces B = (A+A\')/2, despejando: A\' = 2B − A. Este es el error más caro del parcial: usar B−A en lugar de 2B−A.'},
  {st: 'En una elipse, la relación entre a (semieje mayor), b (semieje menor) y c (semidistancia focal) es:', opts: ['c² = a² + b²', 'c² = a² − b²', 'a² = b² − c²', 'b² = a² + c²'], c: 1, ex: 'En la elipse: c² = a² − b² con a > b > 0 y c < a. En la hipérbola es al revés: c² = a² + b² con c > a. No los confundas.'},
  {st: 'Para verificar si un conjunto {v₁,v₂} es base de un subespacio S de R⁴ con dim 2, hay que:', opts: ['Solo verificar que v₁ y v₂ pertenecen a S', 'Verificar que v₁,v₂ ∈ S y que son L.I.', 'Verificar que la suma v₁+v₂ ∈ S', 'Calcular el determinante de la matriz 2×4'], c: 1, ex: 'Para ser base de S: (1) ambos vectores deben cumplir las ecuaciones de S (pertenecer a S), (2) deben ser L.I. (det de la submatriz cuadrada ≠ 0 o verificar directamente). Solo con la primera condición no alcanza.'},
  {st: 'Recta r₁: directora (4/7, 0, 4) y r₂: directora (1/2, 1/8, −1/14). Calculás el producto escalar de los directores:', opts: ['(4/7)(1/2) + 0·(1/8) + 4·(−1/14) = 2/7 + 0 − 2/7 = 0', '(4/7)(1/2) + 4·(−1/14) = 1', '0 + 1/8 + 4/14 = 1', 'No se puede calcular'], c: 0, ex: '(4/7)(1/2) = 4/14 = 2/7. 0·(1/8) = 0. 4·(−1/14) = −4/14 = −2/7. Total: 2/7 + 0 − 2/7 = 0. Producto escalar nulo → si además la intersección es vacía → las rectas son ortogonales.'},
  {st: 'Para la parábola (y−k)² = 4p(x−h) con p > 0, el foco está en:', opts: ['(h−p, k)', '(h+p, k)', '(h, k+p)', '(h, k−p)'], c: 1, ex: 'La parábola (y−k)²=4p(x−h) abre hacia la derecha. El foco está p unidades a la derecha del vértice (h, k): foco = (h+p, k). La directriz es x = h−p.'},
  {st: '¿Cuál de estos pasos del cálculo del simétrico está en el orden correcto?', opts: ['Calcular A\', luego buscar B, luego la recta normal', 'Recta normal por A → pie B → A\' = 2B−A', 'Proyectar A sobre el plano → calcular ‖A‖', 'Calcular el normal, luego igualar a A, luego A\'=2A−normal'], c: 1, ex: 'El orden correcto siempre es: (1) escribir la recta normal al plano que pasa por A, (2) hallar el pie B como intersección de la recta con el plano, (3) calcular A\' = 2B−A. Nunca en otro orden.'}
]);
