registerExercises('algebra-parcial', '1', [
  {st: 'El parcial Escayola tiene 8 ejercicios de opción múltiple. ¿Cuánto vale cada uno?', opts: ['1 punto', '1,25 puntos', '1,5 puntos', '2 puntos'], c: 1, ex: 'Total = 10 puntos repartidos en 8 ejercicios → 10/8 = 1,25 puntos cada uno. NO hay ejercicios que valgan más que otros (todos por igual). ▸ Por qué las otras están mal: "1 punto" (×8 = 8) no llega a 10; "1,5" (×8 = 12) excede; "2 puntos" (×8 = 16) duplica el total.'},
  {st: 'Si en el enunciado ves "norma", "ángulo entre vectores" y "producto escalar", el tema es:', opts: ['Subespacios', 'Cónicas', 'Vectores', 'Rectas y planos'], c: 2, ex: 'Norma, ángulo y producto escalar son conceptos básicos de la sesión 1 (Vectores). La fórmula clave es v·w = ‖v‖·‖w‖·cos(α). ▸ Por qué las otras están mal: Subespacios (sesión 4) habla de bases, L.I., dim; Cónicas (sesión 5) usa "foco, directriz, excentricidad"; Rectas y planos (sesión 3) usa "intersección, ecuación, posición relativa".'},
  {st: 'Si el enunciado pide "la ecuación de la recta directriz y las coordenadas del foco", el tema es:', opts: ['Vectores', 'Rectas y planos', 'Subespacios', 'Cónicas (parábola)'], c: 3, ex: 'Foco y directriz son elementos exclusivos de la PARÁBOLA (cónicas, sesión 5). Forma canónica: (y−k)² = 4p(x−h). ▸ Por qué las otras están mal: Vectores no tiene "directriz"; Rectas y planos habla de planos por puntos, no de focos; Subespacios trabaja con álgebra abstracta sin geometría focal.'},
  {st: 'La estrategia cuando un ejercicio tiene un parámetro k desconocido es:', opts: ['Probar las 4 opciones', 'Adivinar por descarte', 'Reemplazar k en la condición del enunciado y despejar', 'No se puede resolver sin más datos'], c: 2, ex: 'Receta universal del parcial Escayola: identificá la CONDICIÓN del enunciado (centro dado, det=0, ortogonalidad, etc.), reemplazá la expresión con k, y despejá k. ▸ Por qué las otras están mal: "probar opciones" pierde tiempo y no enseña nada; "adivinar por descarte" ya implica resolver implícitamente; "no se puede resolver" es falso, siempre hay condición.'},
  {st: 'La fórmula de distancia de un punto A = (x₀, y₀, z₀) al plano ax+by+cz = d es:', opts: ['‖A‖ / √(a²+b²+c²)', '|ax₀+by₀+cz₀−d| / √(a²+b²+c²)', '|ax₀+by₀+cz₀| / √(a²+b²+c²)', '|ax₀+by₀+cz₀+d| / ‖A‖'], c: 1, ex: 'Fórmula directa: numerador = valor absoluto de "evaluar A en la ecuación llevada a 0" (es decir, ax₀+by₀+cz₀−d); denominador = norma del vector normal (raíz de a²+b²+c²). ▸ Por qué las otras están mal: (A) usa ‖A‖ (norma del punto) — incorrecto; (C) le falta el −d; (D) divide por ‖A‖ en lugar del normal. Truco: si el plano es ax+by+cz+d=0, en numerador queda |ax₀+by₀+cz₀+d|.'},
  {st: 'Para reconocer si un conjunto de 3 vectores en R³ es base, el test definitivo es:', opts: ['Verificar que ningún vector es nulo', 'Calcular el determinante de la matriz formada por los vectores', 'Ver si los vectores suman cero', 'Verificar que tienen distintas normas'], c: 1, ex: 'Tres vectores en R³ son base ⟺ son L.I. ⟺ det(matriz) ≠ 0. La matriz se arma poniendo los 3 vectores como filas (o columnas, da igual). ▸ Por qué las otras están mal: (A) "ninguno nulo" es necesario pero no suficiente (3 vectores no nulos pueden ser L.D.); (C) "suman cero" es trivialmente ningún criterio (no implica L.D.); (D) "distintas normas" no tiene relación con L.I.'}
]);

registerExercises('algebra-parcial', '2', [
  {st: 'v tiene norma √5, w tiene norma 8 y el ángulo entre ellos es 2π/3. ¿Cuánto vale v·w?', opts: ['−4√5', '4√5', '−4√3', '8√5'], c: 0, ex: 'Fórmula: v·w = ‖v‖·‖w‖·cos(α). ▸ cos(2π/3) = cos(120°) = −1/2 (segundo cuadrante, coseno negativo). ▸ v·w = √5·8·(−1/2) = −4√5. ▸ Por qué las otras están mal: (B) signo positivo (olvidan el cuadrante); (C) usa √3 en lugar de √5; (D) sin el cos.'},
  {st: 'v = (k, −k, k), w = (0, 0, −k) con k > 0. cos(ángulo entre v y w) vale:', opts: ['−1/3', '1/3', '−1/√3', '1/√3'], c: 2, ex: '▸ v·w = k·0 + (−k)·0 + k·(−k) = −k². ▸ ‖v‖ = √(k²+k²+k²) = k√3 (porque k>0). ▸ ‖w‖ = √(k²) = k. ▸ cos(α) = (v·w)/(‖v‖·‖w‖) = −k² / (k√3·k) = −1/√3. ▸ Por qué las otras están mal: (A) (B) ±1/3 = (1/√3)² mal aplicado; (D) signo positivo (cosc no puede ser positivo si v·w<0).'},
  {st: 'w es paralelo a v = (5/7, −1/7, −2/7) y tiene norma 3√30. ¿Cuántas soluciones posibles tiene w?', opts: ['Solo una (k > 0)', 'Dos (k positivo y k negativo)', 'Infinitas', 'Ninguna'], c: 1, ex: 'w = k·v por paralelismo. ‖v‖² = 25/49+1/49+4/49 = 30/49 → ‖v‖ = √30/7. ▸ ‖w‖ = |k|·‖v‖ = |k|·√30/7 = 3√30 → |k| = 21 → k = ±21. ▸ Hay 2 vectores: w₁ = 21v y w₂ = −21v. ▸ Por qué las otras están mal: "solo una" supone k>0 sin justificación; "infinitas" requeriría norma sin restringir; "ninguna" es absurdo, sí existe.'},
  {st: 'β·(3/11, −1/11, 2/11) + (−10, 9, 1) = (−7, 8, 3). ¿Cuánto vale β?', opts: ['−11', '1/11', '11', '−1/11'], c: 2, ex: 'Igualo coordenada por coordenada y resuelvo cualquiera (todas deben dar lo mismo). ▸ X: 3β/11 − 10 = −7 → 3β/11 = 3 → β = 11. ▸ Verifico Y: −β/11 + 9 = 8 → −β/11 = −1 → β = 11 ✓. ▸ Verifico Z: 2β/11 + 1 = 3 → 2β/11 = 2 → β = 11 ✓. Las tres dan β = 11. ▸ Por qué las otras están mal: (A) (D) signos invertidos; (B) confunde β/11 con β.'},
  {st: 'A = (−1/3, 2/3, 1/3), B = (0, 4/3, −7/3), C = (1, m, −m), D = (1, 0, −m). Si ‖AB‖ = ‖CD‖, ¿qué valor toma m?', opts: ['m = 23/3', 'Cualquier m ∈ ℝ', '|m| = √(23/3) (es decir m = ±√(23/3))', 'No hay solución'], c: 2, ex: '▸ AB = B − A = (1/3, 2/3, −8/3). ‖AB‖² = 1/9 + 4/9 + 64/9 = 69/9 = 23/3. ▸ CD = D − C = (1−1, 0−m, −m−(−m)) = (0, −m, 0). ‖CD‖² = m². ▸ Iguales: m² = 23/3 → m = ±√(23/3). Hay DOS soluciones (positiva y negativa). ▸ Por qué las otras están mal: (A) m=23/3 sería m² (sin la raíz); (B) "cualquier m" es falso, hay restricción; (D) sí hay solución.'},
  {st: 'v es paralelo al versor î (= (1,0,0)), tiene norma 7 y una coordenada negativa. ¿Cuáles son sus coordenadas?', opts: ['(7, 0, 0)', '(0, −7, 0)', '(−7, 0, 0)', '(0, 0, −7)'], c: 2, ex: 'v paralelo a î = (1,0,0) significa v = (a, 0, 0) (las otras coordenadas deben ser 0). ▸ ‖v‖ = |a| = 7 → a = ±7. ▸ Coordenada negativa → a = −7. ▸ v = (−7, 0, 0). ▸ Por qué las otras están mal: (A) (7,0,0) tiene coord positiva; (B) (0,−7,0) es paralelo a ĵ, no a î; (D) (0,0,−7) es paralelo a k̂.'},
  {st: 'Si v = (−7, 0, 0) y M = (15/2, 17/4, −1/10) es el punto medio entre los extremos de los vectores v y u (interpretados como puntos), ¿cuánto vale u?', opts: ['(−22, −17/2, 1/5)', '(22, 17/2, −1/5)', '(4, 17/2, −1/5)', '(22, −17/2, 1/5)'], c: 1, ex: 'Si M = (v+u)/2 → u = 2M − v. ▸ X: 2·(15/2) − (−7) = 15 + 7 = 22. ▸ Y: 2·(17/4) − 0 = 17/2. ▸ Z: 2·(−1/10) − 0 = −1/5. ▸ u = (22, 17/2, −1/5). ▸ Por qué las otras están mal: (A) signos invertidos en todo; (C) en X usa 11−7=4 (mal); (D) signo de Y mal.'}
]);

registerExercises('algebra-parcial', '3', [
  {st: 'Para hallar la distancia del punto A al plano Π, el método del parcial es:', opts: ['Evaluar A en la ecuación del plano directamente', 'Escribir la recta normal al plano por A, hallar intersección B con Π, medir ‖AB‖', 'Calcular el producto escalar de A con el normal del plano', 'Sumar las coordenadas de A'], c: 1, ex: 'Algoritmo: (1) recta normal a Π por A → dirección = vector normal del plano = (a,b,c); (2) parametrizo X = t(a,b,c)+A; (3) reemplazo en la ecuación del plano y despejo t; (4) hallo B (pie de la perpendicular); (5) d = ‖A−B‖. ▸ Por qué las otras están mal: (A) "evaluar directamente" da un número, pero NO la distancia (falta dividir por norma del normal); (C) producto escalar A·n no tiene sentido geométrico; (D) "sumar coordenadas" es absurdo.'},
  {st: 'A = (−1, 2, 3), Π: 2x+y−z+1 = 0. La distancia de A a Π es:', opts: ['√6', '√6/3', '6/√3', '0'], c: 1, ex: 'Fórmula directa: |2(−1)+1·2−1·3+1|/√(4+1+1) = |−2+2−3+1|/√6 = |−2|/√6 = 2/√6 = 2√6/6 = √6/3. ▸ Verificación con recta normal: X = t(2,1,−1)+(−1,2,3) → en Π: 2(2t−1)+(t+2)−(−t+3)+1 = 6t−1 = 0 → t=1/6. Distancia: |t|·‖n‖ = (1/6)·√6 = √6/6... mmm, hay que verificar el signo. La fórmula da √6/3. ▸ Por qué las otras están mal: (A) √6 sin dividir; (C) 6/√3 = 2√3 (no aplica); (D) 0 implicaría que A está en Π (no se cumple).'},
  {st: 'Dos rectas tienen vectores directores d₁ = (−4/3, 0, −3) y d₂ = (1/2, 2/7, −2/9). d₁·d₂ vale:', opts: ['0 (= −2/3 + 0 + 2/3)', '1', '−1', '2/3'], c: 0, ex: '▸ (−4/3)·(1/2) = −4/6 = −2/3. ▸ 0·(2/7) = 0. ▸ (−3)·(−2/9) = 6/9 = 2/3. ▸ Suma: −2/3 + 0 + 2/3 = 0. ▸ Como el producto escalar = 0, las direcciones son perpendiculares. Si las rectas además se intersecan, son ortogonales-secantes; si no se cruzan, son alabeadas-perpendiculares. ▸ Por qué las otras están mal: (B) (C) (D) son cálculos parciales mal sumados.'},
  {st: 'Si dos rectas en R³ tienen vectores directores que NO son múltiplos y su intersección es vacía, son:', opts: ['Paralelas', 'Coincidentes', 'Alabeadas (no se cortan ni son paralelas)', 'Concurrentes (se cortan en un punto)'], c: 2, ex: 'En R³ existen 4 posiciones relativas: paralelas (mismas direcciones, sin punto común), coincidentes (mismas direcciones, infinitos puntos), concurrentes/se cortan (direcciones distintas, un punto), alabeadas (direcciones distintas, ningún punto). ▸ Direcciones no múltiplos = no paralelas/coincidentes. ▸ Intersección vacía = no concurrentes. ▸ Solo queda: ALABEADAS. ▸ Por qué las otras están mal: paralelas/coincidentes requerirían direcciones múltiplos; concurrentes requeriría intersección no vacía. Nota: las alabeadas pueden ser ortogonales si además d₁·d₂=0, pero no es obligatorio.'},
  {st: 'Recta X = α(3,6,9) + (4,2,−1), plano −x+y−z = 1. La posición relativa es:', opts: ['La recta está contenida en el plano', 'La recta y el plano son paralelos', 'La recta y el plano son ortogonales', 'La recta y el plano se cortan en un único punto'], c: 3, ex: 'Reemplazo el punto genérico (3α+4, 6α+2, 9α−1) en la ecuación del plano: −(3α+4) + (6α+2) − (9α−1) = 1 → −3α−4 + 6α+2 − 9α+1 = 1 → −6α − 1 = 1 → α = −1/3. ▸ Como hay UN solo valor de α, hay UN punto de intersección. ▸ Por qué las otras están mal: (A) "contenida" requeriría que el sistema sea identidad para todo α (no es); (B) "paralelos" requeriría sistema sin solución; (C) "ortogonales" requeriría dirección recta paralela al normal del plano: (3,6,9) vs (−1,1,−1) — no son múltiplos.'},
  {st: 'A = (7,−10,−1). Plano: 2x−3y+z=1. El simétrico de A respecto del plano es:', opts: ['(2,−3,1)', '(5,−8,7)', '(1,−1,−4)', '(−5,8,−7)'], c: 3, ex: 'Receta: B = proyección de A sobre el plano (pie de la normal); A\' = 2B − A. ▸ Recta normal: X = t(2,−3,1) + (7,−10,−1) → punto genérico (2t+7, −3t−10, t−1). ▸ En plano: 2(2t+7) − 3(−3t−10) + (t−1) = 1 → 4t+14+9t+30+t−1 = 1 → 14t+43 = 1 → t = −3. ▸ B = (1, −1, −4). ▸ A\' = 2B − A = (2·1−7, 2·(−1)−(−10), 2·(−4)−(−1)) = (−5, 8, −7). ▸ Por qué las otras están mal: (A) (2,−3,1) es el vector normal; (B) (5,−8,7) puede ser un cálculo intermedio mal; (C) (1,−1,−4) es B (pie de la normal), NO el simétrico.'},
  {st: 'Para el plano paramétrico π₁: X = s(1,1,0)+t(2,0,2)+(1,1,1) y el plano π₂: x+z=1+y, la posición relativa es:', opts: ['Son perpendiculares', 'La intersección es una recta y NO son perpendiculares', 'Son paralelos', 'Son coincidentes'], c: 1, ex: 'Hallar normales: n₁ = (1,1,0)×(2,0,2) = (1·2−0·0, 0·2−1·2, 1·0−1·2) = (2,−2,−2). n₂: π₂ es x−y+z=1 → n₂=(1,−1,1). ▸ ¿n₁ y n₂ paralelos? n₁=2(1,−1,−1). Compará (1,−1,−1) con (1,−1,1): la 3ª da −1 vs 1, NO múltiplos → planos NO paralelos. ▸ Como no son paralelos, su intersección es una RECTA. ¿Son perpendiculares? Eso requiere n₁·n₂ = 0. n₁·n₂ = 2·1+(−2)·(−1)+(−2)·1 = 2+2−2 = 2 ≠ 0 → NO perpendiculares. ▸ Por qué las otras están mal: (A) "perpendiculares" requiere n₁·n₂=0; (C) "paralelos" requiere n₁ y n₂ múltiplos; (D) "coincidentes" requiere paralelos + un punto en común.'}
]);

registerExercises('algebra-parcial', '4', [
  {st: '{(1,0,−1),(−1,k,0),(0,−2,k+1)} no es base de R³ para k ∈ ℤ>0. ¿Cuál es ese k?', opts: ['−2', '1', '2', '−1'], c: 1, ex: 'NO es base ⟺ det = 0. Determinante de la matriz [[1,0,−1],[−1,k,0],[0,−2,k+1]]: ▸ Expansión por 1ª fila: 1·(k(k+1)−0·(−2)) − 0 + (−1)·((−1)(−2)−k·0) = (k²+k) − 2 = k²+k−2. ▸ Iguálo a 0: k²+k−2 = 0 → (k+2)(k−1) = 0 → k = −2 o k = 1. ▸ Restricción: k entero positivo → k = 1. ▸ Por qué las otras están mal: (A) k=−2 también anula el det pero NO es positivo; (C) k=2 → 4+2−2=4≠0 (sí es base); (D) k=−1 → 1−1−2=−2≠0.'},
  {st: 'S = {(x₁,x₂,x₃,x₄) ∈ ℝ⁴: 6x₁+nx₂=0 ∧ 2x₂+x₃+mx₄=0}. Una base de S es {(1,2,−4,0),(0,0,−3,1)}. ¿Cuáles son n y m?', opts: ['n=−3, m=−3', 'n=3, m=−3', 'n=−3, m=3', 'n=3, m=3'], c: 2, ex: 'Cada vector de la base debe satisfacer AMBAS ecuaciones de S. ▸ (1,2,−4,0) en eq1: 6·1+n·2 = 6+2n = 0 → n = −3. ▸ (1,2,−4,0) en eq2: 2·2+(−4)+m·0 = 0 → 0=0 ✓ (no aporta info de m). ▸ (0,0,−3,1) en eq1: 0+0=0 ✓. ▸ (0,0,−3,1) en eq2: 0+(−3)+m·1 = 0 → m = 3. ▸ n = −3, m = 3. ▸ Por qué las otras están mal: (A) (B) tienen n=3 (no satisface eq1 con primer vector); (D) m=3 con n=3 inconsistente.'},
  {st: 'A = {(0,−2,−1),(k,1,0),(−8,0,k+3)}. Para que A sea generador de ℝ³, k debe ser:', opts: ['k ∈ {1,−4}', 'k ∈ ℝ \\ {−1,4}', 'k ∈ ℝ \\ {1,−4}', 'k ∈ ∅'], c: 2, ex: 'Generador de ℝ³ ⟺ los 3 vectores son L.I. ⟺ det ≠ 0. ▸ det de [[0,−2,−1],[k,1,0],[−8,0,k+3]]: expansión por 1ª fila → 0 − (−2)·(k(k+3) − 0·(−8)) + (−1)·(k·0 − 1·(−8)) = 2(k²+3k) − 8 = 2k²+6k−8 = 2(k²+3k−4) = 2(k+4)(k−1). ▸ det = 0 ⟺ k = −4 o k = 1. ▸ Para SER generador: k ∉ {−4, 1} → k ∈ ℝ \\ {1,−4}. ▸ Por qué las otras están mal: (A) {1,−4} son los valores que NO sirven (lo opuesto); (B) {−1,4} son signos cambiados; (D) ∅ implicaría que nunca es generador.'},
  {st: 'S = {(x₁,x₂,x₃,x₄) ∈ ℝ⁴: x₁+x₄=0}. dim(S)=3. ¿Cuál conjunto es generador (base) de S?', opts: ['{(1,0,0,−1),(0,1,0,0),(1,0,0,1)}', '{(1,1,0,−1),(0,1,0,0),(1,0,0,−1)}', '{(1,0,0,−1),(0,1,0,0),(0,0,1,0)}', '{(0,1,0,0),(1,0,−1,0),(1,0,0,−1)}'], c: 2, ex: 'Necesito 3 vectores L.I. todos en S. Verifico opción C: ▸ (1,0,0,−1): 1+(−1)=0 ✓. ▸ (0,1,0,0): 0+0=0 ✓. ▸ (0,0,1,0): 0+0=0 ✓. Todos en S. Son L.I. (la matriz tiene 3 filas L.I. obviamente) → BASE de S. ▸ Por qué las otras están mal: (A) (1,0,0,1) tiene 1+1=2≠0 → NO está en S; (B) (1,0,0,−1) = (1,1,0,−1) − (0,1,0,0) → L.D., no genera; (D) (1,0,−1,0) tiene 1+0=1≠0 → NO está en S.'},
  {st: '¿Cuál vector es combinación lineal de (1,2,−1) y (−1,−1,2)?', opts: ['(−1,0,3)', '(0,1,−1)', '(2,3,3)', '(0,−1,1)'], c: 0, ex: 'Verifico (−1,0,3): α(1,2,−1) + β(−1,−1,2) = (α−β, 2α−β, −α+2β) = (−1, 0, 3). ▸ De α−β=−1 y 2α−β=0: restando → α=1, sub en 1ª → β=2. ▸ Verifico 3ª: −1+4=3 ✓. Sí es combinación lineal con coef (1,2). ▸ Por qué las otras están mal: (B) sistema queda inconsistente (α=1,β=1 dan 3ª: 1≠−1); (C) (α=1,β=−1 dan 3ª: −3≠3); (D) sistema inconsistente.'},
  {st: '{(1,0,2),(0,−2,−k),(1/2,−k−1,0)}. Para que NO sea base con k ∈ ℤ negativo, ¿cuál k?', opts: ['2', '1', '−2', '−1'], c: 2, ex: 'NO es base ⟺ det=0. ▸ det = 1·((−2)·0 − (−k)·(−k−1)) − 0 + 2·(0·(−k−1) − (−2)·(1/2)) = 1·(0 − k(k+1)) + 2·(0 + 1) = −k²−k+2. ▸ −k²−k+2 = 0 → k²+k−2 = 0 → (k+2)(k−1) = 0 → k = −2 o k = 1. ▸ Restricción: k entero negativo → k = −2. ▸ Por qué las otras están mal: (A) 2 da k²+k−2=4 (sí es base); (B) 1 anula el det pero es positivo; (D) −1 da 1−1−2=−2 (sí es base).'},
  {st: 'S = {x ∈ ℝ⁴: 6x₁+nx₂=0 ∧ 2x₂+x₃+mx₄=0}. Base: {(1,2,−4,0),(0,0,−3,1)}. (Pregunta de chequeo) Si n=−3 y m=3, ¿el sistema queda consistente?', opts: ['No, hay contradicción en alguna ecuación', 'Sí: ambos vectores satisfacen eq1 y eq2 con esos valores', 'Solo el primer vector satisface', 'Solo el segundo vector satisface'], c: 1, ex: 'Verifico ambas ecuaciones para los 2 vectores. ▸ (1,2,−4,0): eq1=6+(−3)·2=0 ✓; eq2=2·2+(−4)+3·0=0 ✓. ▸ (0,0,−3,1): eq1=0+0=0 ✓; eq2=0+(−3)+3·1=0 ✓. CONSISTENTE: la base es válida con n=−3, m=3. ▸ Por qué las otras están mal: requiere verificar las 4 condiciones; cualquier "no" o "solo uno" es falso porque las 4 se cumplen.'}
]);

registerExercises('algebra-parcial', '5', [
  {st: 'En la hipérbola (x−h)²/a² − (y−k)²/b² = 1, ¿cuál es la relación entre a, b y c (semidistancia focal)?', opts: ['c² = a² − b²', 'c² = a² + b²', 'a² = b² + c²', 'b² = a² + c²'], c: 1, ex: 'En la HIPÉRBOLA siempre c² = a² + b² (con c > a). Es la relación pitagórica entre los semiejes y la semidistancia focal. ▸ ALERTA: en la ELIPSE es al revés: c² = a² − b² (con c < a, ya que a es semieje mayor). ▸ Por qué las otras están mal: (A) c² = a² − b² es de la elipse; (C) (D) son re-arreglos incorrectos. Truco mnemotécnico: en elipse el "−" es porque a es más grande que c; en hipérbola el "+" es porque c es más grande que a (los focos están más allá de los vértices).'},
  {st: '144x² − 24kx + 16y² = 63 es una elipse con centro (−0,75; 0). ¿Cuánto vale k?', opts: ['9', '−18', '−9', '0,5'], c: 2, ex: 'Completar cuadrados en x. ▸ 144x²−24kx = 144(x² − k/6 · x) = 144·((x − k/12)² − k²/144) = 144(x−k/12)² − k². ▸ Ecuación: 144(x−k/12)² + 16y² = 63 + k². ▸ Centro = (k/12, 0). Igualar k/12 = −0,75 → k = −9. ▸ Por qué las otras están mal: (A) k=9 daría centro (0,75; 0) (signo opuesto); (B) k=−18 daría centro (−1,5; 0); (D) k=0,5 muy alejado.'},
  {st: 'Hipérbola H con excentricidad e=1,8 y focos F₁=(0,−8), F₂=(0,10). El centro de H es:', opts: ['(0,0)', '(0,1)', '(0,2)', '(0,−1)'], c: 1, ex: 'El centro de una hipérbola es el PUNTO MEDIO entre sus dos focos. ▸ Centro = ((0+0)/2, (−8+10)/2) = (0, 1). ▸ Por qué las otras están mal: (A) (0,0) no es punto medio; (C) (0,2) está más cerca de F₂; (D) (0,−1) está más cerca de F₁. Truco: como ambas X son 0, el centro tiene X=0; el Y es el promedio.'},
  {st: 'Misma hipérbola H (e=1,8, focos en eje y, centro (0,1)). Sabiendo que c=9, los vértices de H son:', opts: ['(0,±5)', '(0,1±5) = (0,6) y (0,−4)', '(0,±9)', '(0,1±9) = (0,10) y (0,−8)'], c: 1, ex: '▸ e = c/a → 1,8 = 9/a → a = 5. ▸ Centro (0,1), eje vertical (focos en y), así que vértices están a distancia a del centro a lo largo del eje y: V = (0, 1±5) = (0, 6) y (0, −4). ▸ Por qué las otras están mal: (A) (0,±5) ignora el desplazamiento del centro (asume (0,0)); (C) (0,±9) usa c en lugar de a (los vértices se ubican con a, no c); (D) (0,10) y (0,−8) son los focos.'},
  {st: '3x² − y² − 6x − 30y − 546 = 0. Completando cuadrados, la forma canónica es:', opts: ['(x−1)²/108 − (y+15)²/324 = 1', '(x+1)²/108 − (y−15)²/324 = 1', '(y+15)²/324 − (x−1)²/108 = 1', '(x−1)²/324 − (y+15)²/108 = 1'], c: 0, ex: '▸ Agrupo y completo. 3(x²−2x) − (y²+30y) = 546. 3((x−1)²−1) − ((y+15)²−225) = 546. 3(x−1)² − (y+15)² = 546 + 3 − 225 = 324. ▸ Divido por 324: (x−1)²/108 − (y+15)²/324 = 1. ▸ Es hipérbola horizontal (positivo el x). ▸ Por qué las otras están mal: (B) signos invertidos en el centro; (C) intercambia x e y → es hipérbola vertical (positivo el y); (D) intercambia 108 y 324.'},
  {st: 'y² − 8x + 3 = 6y. La directriz de la parábola es:', opts: ['x = −2,75', 'y = −2,75', 'x = 1,25', 'y = 1,25'], c: 0, ex: '▸ Reordeno: y² − 6y = 8x − 3. ▸ Completar cuadrados: (y−3)² − 9 = 8x − 3 → (y−3)² = 8x + 6 = 8(x + 3/4). ▸ Forma canónica: (y−k)² = 4p(x−h) → vértice (−3/4, 3), 4p=8, p=2. Abre hacia la derecha (p>0). ▸ Directriz: x = h − p = −0,75 − 2 = −2,75 (vertical, a la izquierda del vértice). ▸ Por qué las otras están mal: (B) (D) "y=" es directriz horizontal (parábola horizontal tiene directriz vertical); (C) x=1,25 estaría a la derecha del foco.'},
  {st: 'M = {(x+4)²+(y+3)²=9}, N = {3x²+y²+6y=−6}. ¿Cuántos puntos tienen en común?', opts: ['Ninguno', 'Exactamente dos', 'Exactamente uno', 'Más de dos'], c: 2, ex: '▸ M: circunferencia centro (−4,−3), radio 3. ▸ N: 3x² + (y+3)² − 9 = −6 → 3x² + (y+3)² = 3 → x² + (y+3)²/3 = 1. ELIPSE centro (0,−3), semiejes √1=1 (en x) y √3 (en y). ▸ Ambas centradas en y=−3 (misma altura). Distancia entre centros = 4. ▸ Punto más cercano de M a N: (−1,−3) (frontera derecha de M). ¿Está en N? 1 + 0 = 1 ✓. ¿Otro punto en común? Las dos curvas son tangentes en (−1,−3). ▸ Por qué las otras están mal: (A) "ninguno" implicaría que no hay tangencia; (B) "dos" requeriría que se crucen en dos puntos; (D) "más de dos" implicaría coincidencia.'}
]);

registerExercises('algebra-parcial', '6', [
  {st: 'El simétrico A\' de A respecto del plano se calcula como:', opts: ['A\' = B − A (B = pie de la normal)', 'A\' = 2B − A (B = pie de la normal)', 'A\' = B/2', 'A\' = A − 2B'], c: 1, ex: 'B es el punto medio entre A y su simétrico A\' (porque B es el pie de la perpendicular y A\' es la reflexión). ▸ Como B = (A + A\')/2, despejando: A\' = 2B − A. ▸ Por qué las otras están mal: (A) B−A es un vector dirección, no un punto; (C) B/2 carece de sentido geométrico; (D) A−2B daría algo distinto. ESTE es el error más caro del parcial: confundir A\'=2B−A con A\'=B−A.'},
  {st: 'En una elipse, la relación entre a (semieje mayor), b (semieje menor) y c (semidistancia focal) es:', opts: ['c² = a² + b²', 'c² = a² − b²', 'a² = b² − c²', 'b² = a² + c²'], c: 1, ex: 'Elipse: c² = a² − b² con a > b > 0 y c < a. Los focos están dentro de la elipse, más cerca del centro que los vértices del eje mayor. ▸ Por qué las otras están mal: (A) c² = a² + b² es de la HIPÉRBOLA, no la elipse; (C) (D) son re-arreglos invertidos. ▸ Truco: en elipse, c < a (focos dentro); en hipérbola, c > a (focos fuera).'},
  {st: 'Para verificar si un conjunto {v₁, v₂} es base de un subespacio S de ℝ⁴ con dim 2, hay que:', opts: ['Solo verificar que v₁ y v₂ pertenecen a S', 'Verificar que v₁, v₂ ∈ S Y que son L.I.', 'Verificar que v₁ + v₂ ∈ S', 'Calcular el determinante de la matriz 2×4'], c: 1, ex: 'Una base debe (1) generar el subespacio, (2) ser L.I. ▸ Para 2 vectores en S de dim 2: si son L.I. → automáticamente generan S (cantidad correcta de L.I.). Por eso bastan dos chequeos: pertenencia + L.I. ▸ Por qué las otras están mal: (A) "solo pertenecen" no garantiza que sean L.I. (podrían ser uno múltiplo del otro); (C) v₁+v₂ ∈ S es trivialmente cierto si ambos están en S; (D) det 2×4 no existe (no es matriz cuadrada).'},
  {st: 'Recta r₁ con director (4/7, 0, 4) y r₂ con director (1/2, 1/8, −1/14). Calculás el producto escalar de los directores:', opts: ['(4/7)(1/2) + 0·(1/8) + 4·(−1/14) = 2/7 + 0 − 2/7 = 0', '(4/7)(1/2) + 4·(−1/14) = 1', '0 + 1/8 + 4/14 = 1', 'No se puede calcular'], c: 0, ex: '▸ (4/7)·(1/2) = 4/14 = 2/7. ▸ 0·(1/8) = 0. ▸ 4·(−1/14) = −4/14 = −2/7. ▸ Suma: 2/7 + 0 − 2/7 = 0. ▸ Producto escalar nulo → direcciones perpendiculares. Si las rectas no se cortan → alabeadas perpendiculares; si se cortan → ortogonales-secantes. ▸ Por qué las otras están mal: (B) saltea el término 0; (C) confunde 1/8 con 0; (D) sí se puede calcular.'},
  {st: 'Para la parábola (y−k)² = 4p(x−h) con p > 0, el foco está en:', opts: ['(h−p, k)', '(h+p, k)', '(h, k+p)', '(h, k−p)'], c: 1, ex: 'La parábola (y−k)² = 4p(x−h) abre HORIZONTALMENTE. Si p > 0 → abre hacia la derecha. ▸ El foco está p unidades hacia el lado de apertura desde el vértice (h, k): foco = (h+p, k). La directriz (al lado opuesto): x = h − p. ▸ Por qué las otras están mal: (A) (h−p, k) es la directriz, no el foco; (C) (D) (h, k±p) son focos de parábolas verticales, no horizontales.'},
  {st: '¿Cuál de estos pasos del cálculo del simétrico está en el orden correcto?', opts: ['Calcular A\', luego buscar B, luego la recta normal', 'Recta normal por A → pie B → A\' = 2B − A', 'Proyectar A sobre el plano → calcular ‖A‖', 'Calcular el normal, luego igualar a A, luego A\'=2A−normal'], c: 1, ex: 'Algoritmo correcto: (1) escribís la recta normal a Π por A, (2) hallás B = intersección recta-plano (pie de la normal), (3) A\' = 2B − A. ▸ Por qué las otras están mal: (A) invertido (no podés calcular A\' antes de saber B); (C) ‖A‖ no sirve; (D) "2A−normal" no tiene sentido (normal es vector dirección, A es punto).'}
]);
