registerExercises('pc-parcial', '1', [
  {st: '¿Cuántas consignas tiene el primer parcial de PC (Cátedra Balbiano/Vizioli/Gimeno) y cuánto vale cada una?', opts: ['5 consignas, 2 puntos cada una', '10 consignas, 1 punto cada una', '20 consignas, 0.5 puntos cada una', '10 consignas, 0.5 puntos cada una'], c: 1, ex: 'El parcial tiene 10 consignas de opción múltiple, cada una vale 1 punto (total 10 puntos). Duración: 1 hora 30 minutos. No hay puntaje parcial.'},
  {st: 'Si en la consigna aparece "completá el enunciado para que sea una tautología", la receta es:', opts: ['Buscar una conjunción verdadera', 'Usar la forma P ∨ ¬P (un enunciado o su negación)', 'Buscar una premisa verdadera empíricamente', 'Usar Modus Ponens'], c: 1, ex: 'Una tautología es necesariamente verdadera por su FORMA. La forma más común en el parcial es P ∨ ¬P ("P o no P"), que siempre es verdadera independientemente del contenido de P.'},
  {st: 'Si la consigna pide "cuál argumento es válido" y hay una opción que afirma el consecuente (P→Q; Q ∴ P), ¿es válida?', opts: ['Sí, siempre que las premisas sean verdaderas', 'No, porque es una falacia formal (afirmación del consecuente)', 'Sí, si Q es verdadero', 'Depende del contenido del argumento'], c: 1, ex: 'La afirmación del consecuente es siempre inválida: P→Q; Q no implica P (Q puede ser verdadero por otra causa distinta de P). La validez depende de la forma, no del contenido.'},
  {st: 'Aparece "Klimovsky" en la consigna. ¿Cuál es la pregunta clave para clasificar el enunciado?', opts: ['¿Tiene términos teóricos?', '¿La población mencionada es abarcable o no por la experiencia?', '¿El enunciado es universal o existencial?', '¿El enunciado habla de ciencias fácticas?'], c: 1, ex: 'La clave de Klimovsky es el tamaño de la muestra: si refiere a un grupo concreto y finito (el estudio, los pacientes del experimento) = enunciado empírico básico. Si refiere a una población inabarcable (toda la humanidad, todos los casos de X enfermedad) = generalización empírica.'},
  {st: 'El parcial tiene 4 temas distintos (Tema 1, 2, 3, 4). ¿Qué diferencia hay entre ellos?', opts: ['Preguntas completamente distintas por tema', 'Las mismas preguntas en diferente orden (anti-copia)', 'Distinto nivel de dificultad', 'Distintos contenidos según la cátedra'], c: 1, ex: 'Los 4 temas son rotaciones anti-copia: las mismas consignas en diferente orden y con las opciones reordenadas. Esto es por qué estudiar los patrones de todos los temas te da ventaja.'},
  {st: 'El parcial siempre incluye una consigna sobre Darwin o Lamarck (Unidad 2 de la materia). ¿Cuál es la diferencia clave entre ambas teorías?', opts: ['Darwin: herencia de caracteres adquiridos. Lamarck: selección natural.', 'Darwin: selección natural (los más aptos dejan más descendencia). Lamarck: herencia de rasgos adquiridos por uso/desuso.', 'Son la misma teoría con distinto nombre.', 'Darwin es creacionista, Lamarck es evolucionista.'], c: 1, ex: 'Darwin: los rasgos favorables para la supervivencia en un ambiente se seleccionan porque los organismos más aptos dejan más descendencia. Lamarck: el uso prolongado de un órgano lo desarrolla y ese rasgo adquirido se hereda a la descendencia.'}
]);

registerExercises('pc-parcial', '2', [
  {st: '¿Cuál de los siguientes fragmentos es un argumento? A) "Si las angiospermas son del Cretácico, compartieron territorio con los dinosaurios." B) "Las orquídeas necesitan insectos para polinizar, ya que todas las plantas con flor polinizan con insectos. Y la orquídea es planta con flor." C) "Las primeras plantas aparecieron hace 450 millones de años." D) "Las plantas con flor son angiospermas. Sin embargo, existen plantas sin flor."', opts: ['A', 'B', 'C', 'D'], c: 1, ex: 'B es el único argumento: el "ya que" es indicador de premisa. La conclusión es "Las orquídeas necesitan insectos para polinizar". A es solo un condicional (no hay premisas/conclusión separadas). C y D son descripciones sin que una se infiera de las otras.'},
  {st: '"Las flores contienen polen. De esto se sigue que las abejas necesitan de las flores." ¿Cuál es la conclusión de este argumento?', opts: ['Las flores contienen polen.', 'Las abejas necesitan de las flores.', 'De esto se sigue que las abejas necesitan de las flores.', 'No tiene conclusión porque no hay indicadores.'], c: 1, ex: '"De esto se sigue que" es indicador de conclusión. La conclusión es "Las abejas necesitan de las flores" (sin el indicador, que no forma parte de la conclusión). Regla: los indicadores nunca forman parte de premisa ni conclusión.'},
  {st: 'Un enunciado condicional "Si P, entonces Q" (sin nada más):', opts: ['Es un argumento con P como premisa y Q como conclusión', 'No es un argumento: es un solo enunciado que relaciona dos proposiciones', 'Es un argumento válido', 'Es un argumento deductivo'], c: 1, ex: 'Un enunciado condicional NO es un argumento. Es un solo enunciado complejo: tiene antecedente (P) y consecuente (Q), pero no tiene la estructura argumental de premisas que apoyan una conclusión. Esta distinción aparece siempre en el parcial.'},
  {st: '"Es recomendable no comer hongos sin determinar su especie, puesto que algunos hongos resultan venenosos." ¿Cuál es la premisa?', opts: ['Es recomendable no comer hongos sin determinar su especie.', 'Algunos hongos resultan venenosos.', 'Puesto que algunos hongos resultan venenosos.', 'No tiene premisas claramente identificables.'], c: 1, ex: '"Puesto que" es indicador de premisa. La premisa es lo que va después: "algunos hongos resultan venenosos" (sin el indicador). La conclusión es la primera cláusula: "Es recomendable no comer hongos sin determinar su especie."'},
  {st: '¿Cuál de los siguientes indicadores señala una CONCLUSIÓN?', opts: ['"dado que"', '"puesto que"', '"porque"', '"por lo tanto"'], c: 3, ex: '"Dado que", "puesto que" y "porque" son indicadores de PREMISA. "Por lo tanto" (junto con "luego", "en consecuencia", "se sigue que", "podemos inferir") es indicador de CONCLUSIÓN.'},
  {st: '"Los hongos resultan fundamentales para tratar enfermedades infecciosas. Los hongos son utilizados en campos como la medicina. Fleming descubrió que la penicilina, proveniente de un hongo, inhibía el crecimiento bacterial." ¿Cuál es la conclusión?', opts: ['Los hongos resultan fundamentales para tratar enfermedades infecciosas.', 'Los hongos son utilizados en campos como la medicina.', 'Fleming descubrió que la penicilina inhibía el crecimiento bacterial.', 'La penicilina proviene de un hongo.'], c: 0, ex: 'La primera oración es la que se pretende establecer (conclusión). Las otras dos ofrecen evidencia (ejemplos y hechos concretos). Cuando no hay indicador explícito, buscá cuál enunciado se apoya en los demás.'}
]);

registerExercises('pc-parcial', '3', [
  {st: 'Dadas las oraciones verdaderas: P = "Las flores contienen polen" y Q = "Las abejas producen miel". ¿Cuál de estos enunciados es verdadero?', opts: ['Las flores NO contienen polen y las abejas producen miel.', 'Si las flores contienen polen, las abejas producen miel.', 'Las flores no contienen polen o las abejas no producen miel.', 'Las abejas no producen miel.'], c: 1, ex: 'Opción A: ¬P ∧ Q = F ∧ V = FALSO. Opción B: P → Q = V → V = VERDADERO (el condicional es falso solo si el antecedente es V y el consecuente F). Opción C: ¬P ∨ ¬Q = F ∨ F = FALSO. Opción D: ¬Q = FALSO.'},
  {st: '"Los crisantemos repelen a los mosquitos..." — completá para que sea TAUTOLOGÍA:', opts: ['pero no repelen a los mosquitos.', 'o no repelen a los mosquitos.', 'y su extracto se usa como insecticida.', 'si no repelen a los mosquitos.'], c: 1, ex: '"P o no-P" (disyunción de P con su negación) es siempre verdadera = tautología. Opción A sería P ∧ ¬P = contradicción. Opción C sería contingencia (depende de hechos empíricos). Opción D es un condicional con contenido, también contingencia.'},
  {st: 'El enunciado "Buenos Aires es la capital de Argentina" es:', opts: ['Una tautología, porque es un hecho establecido y universalmente aceptado.', 'Una contradicción, porque podría ser falso.', 'Una contingencia, porque depende de hechos del mundo que podrían haber sido distintos.', 'Un enunciado teórico.'], c: 2, ex: 'Las tautologías son verdaderas por su FORMA, no por su contenido. "Buenos Aires es la capital" es una contingencia: si el proyecto de trasladar la capital hubiera prosperado, sería falso. Las tautologías son verdaderas en todo mundo posible, las contingencias no.'},
  {st: 'Un condicional P → Q es FALSO en exactamente un caso. ¿Cuál?', opts: ['Cuando P es falsa y Q es verdadera.', 'Cuando P es verdadera y Q es falsa.', 'Cuando P y Q son ambas falsas.', 'Cuando P y Q son ambas verdaderas.'], c: 1, ex: 'El condicional P → Q es falso únicamente cuando el antecedente (P) es verdadero y el consecuente (Q) es falso. En los otros 3 casos es verdadero. Mnemotécnica: "Si llueve me mojo" — solo lo violo si llueve Y no me mojo.'},
  {st: 'Dadas P = "El micelio está compuesto por filamentos" (verdadera) y Q = "Los filamentos se conectan a través de grandes distancias" (verdadera). El enunciado "El micelio está compuesto por filamentos PERO estos no se conectan a través de grandes distancias" es:', opts: ['Verdadero, porque P es verdadera.', 'Falso, porque es una conjunción P ∧ ¬Q = V ∧ F.', 'Verdadero, porque es una disyunción.', 'No se puede evaluar sin más datos.'], c: 1, ex: '"Pero" expresa conjunción (P ∧ ¬Q). Como P = V y ¬Q = F (ya que Q es verdadera), la conjunción es V ∧ F = FALSO. Las conjunciones requieren que ambas partes sean verdaderas.'},
  {st: '"El micelio absorbe nutrientes de su entorno o no absorbe nutrientes de su entorno." ¿Qué tipo de enunciado es?', opts: ['Contingencia', 'Contradicción', 'Tautología', 'Enunciado empírico básico'], c: 2, ex: 'Es P ∨ ¬P = tautología. Sin importar si el micelio absorbe o no absorbe nutrientes, la disyunción de cualquier enunciado con su negación es siempre verdadera. Esto es independiente del contenido empírico.'}
]);

registerExercises('pc-parcial', '4', [
  {st: '¿Qué hace que un argumento deductivo sea válido o inválido?', opts: ['Que sus premisas y conclusión sean verdaderas.', 'Su forma lógica: que no sea posible que las premisas sean verdaderas y la conclusión falsa.', 'Que sea aceptado por la comunidad científica.', 'Que sus premisas sean más numerosas que la conclusión.'], c: 1, ex: 'La validez depende exclusivamente de la FORMA del argumento. Un argumento es válido si no existe ningún contraejemplo posible (un caso donde las premisas sean verdaderas y la conclusión falsa). La verdad efectiva de los enunciados no determina la validez.'},
  {st: '"Los pacientes de esquizofrenia pueden tener alucinaciones. Han tiene esquizofrenia. → Han puede padecer de alucinaciones." ¿Es válido o inválido?', opts: ['Inválido, porque la conclusión puede ser falsa.', 'Válido: es instanciación del universal; si las premisas son verdaderas, la conclusión no puede ser falsa.', 'Válido, porque Han es famoso.', 'Inválido, porque no se puede saber si Han tiene alucinaciones.'], c: 1, ex: 'Es válido por instanciación del universal. Si todos los esquizofrénicos pueden tener alucinaciones, y Han es esquizofrénico, necesariamente puede tener alucinaciones. No se puede negar la conclusión sin contradecir las premisas.'},
  {st: '"La esquizofrenia puede generar alucinaciones. Leia tuvo alucinaciones. → Leia padece de esquizofrenia." ¿Es válido?', opts: ['Válido, porque las premisas son plausibles.', 'Inválido: afirmación del consecuente. Las alucinaciones pueden tener otras causas.', 'Válido, porque la conclusión es coherente con las premisas.', 'No se puede determinar sin más información.'], c: 1, ex: 'Es inválido: afirmación del consecuente (P→Q; Q ∴ P). Las alucinaciones pueden producirse por causas distintas a la esquizofrenia (drogas, fiebre alta, etc.). Hay contraejemplo posible: premisas verdaderas + conclusión falsa.'},
  {st: '"Los claustrofóbicos padecen de ansiedad extrema ante los espacios cerrados. Hipócrates es claustrofóbico. → Hipócrates padece de ansiedad extrema ante los espacios cerrados." ¿Cuál es la correcta justificación de que es válido?', opts: ['Porque las premisas son verdaderas.', 'Porque la conclusión es verdadera.', 'Porque la información de la conclusión se encuentra implícita en sus premisas.', 'Porque la conclusión no es falsa.'], c: 2, ex: 'La justificación correcta es que la conclusión está implícita en las premisas: si todos los claustrofóbicos tienen ansiedad e Hipócrates es claustrofóbico, la conclusión ya está contenida en esas dos afirmaciones. La verdad real de Hipócrates no importa.'},
  {st: '¿Puede un argumento válido tener premisas falsas?', opts: ['No, la validez requiere premisas verdaderas.', 'Sí, la validez solo dice que SI las premisas fueran verdaderas, la conclusión también lo sería.', 'Solo si la conclusión también es falsa.', 'Solo en argumentos inductivos.'], c: 1, ex: 'Sí. Un argumento puede ser válido con premisas falsas. La validez es una propiedad de la FORMA: garantiza que si las premisas son verdaderas, la conclusión también lo es. Pero si las premisas son falsas, la conclusión puede ser verdadera o falsa.'},
  {st: '¿Es posible que exista un argumento inválido que sea sólido?', opts: ['Sí, si sus premisas son verdaderas.', 'Sí, si su conclusión es verdadera.', 'No: la solidez exige validez + premisas verdaderas; los inválidos tienen contraejemplos (conclusión puede ser falsa).', 'Sí, en lógica inductiva.'], c: 2, ex: 'No puede existir. Solidez = válido + premisas verdaderas. Si un argumento es inválido, tiene contraejemplos: hay algún caso donde las premisas son verdaderas y la conclusión es falsa. Los argumentos sólidos no pueden tener conclusión falsa. Contradicción.'}
]);

registerExercises('pc-parcial', '5', [
  {st: '"La orquídea mariposa es epífita y crece sobre otros árboles. La orquídea cattleya es epífita y crece sobre otros árboles. [premisa faltante] / La orquídea vanda crece sobre otros árboles." ¿Qué premisa faltante hace de este un argumento por ANALOGÍA?', opts: ['Todas las plantas epífitas crecen sobre otros árboles.', 'La mayoría de las plantas epífitas crece sobre otros árboles.', 'La orquídea vanda es una planta epífita.', 'La orquídea vanda no crece sobre otros árboles.'], c: 2, ex: 'En la analogía se comparan casos individuales similares. La premisa faltante debe introducir la orquídea vanda como un caso más del mismo tipo (epífita), para luego concluir que comparte la otra propiedad (crece sobre árboles). Las opciones A y B convertirían el argumento en enumeración incompleta.'},
  {st: '¿Qué diferencia hay entre un argumento inductivo por enumeración incompleta y uno por analogía?', opts: ['No hay diferencia, son el mismo tipo.', 'Enumeración incompleta: de una muestra se generaliza a todo el conjunto. Analogía: se comparan casos individuales y se infiere que uno tiene la propiedad de los otros.', 'Analogía: de una muestra se generaliza. Enumeración: se comparan individuos.', 'Solo la diferencia está en el número de premisas.'], c: 1, ex: 'Enumeración incompleta: "Rosa, girasol y tulipán tienen pétalos → todas las flores tienen pétalos" (muestra → generalización sobre el conjunto). Analogía: "La seta y el champiñón tienen sombrero y tallo fibroso; el rebozuelo tiene sombrero → el rebozuelo tiene tallo fibroso" (casos individuales similares → propiedad nueva en un caso).'},
  {st: '¿Qué pasa si en un silogismo inductivo se reemplaza "El 90% de los X hacen Y" por "El 100% de los X hacen Y"?', opts: ['El argumento se fortalece como inductivo.', 'El argumento se debilita.', 'El argumento deja de ser inductivo y se vuelve deductivo (instanciación universal).', 'No cambia nada.'], c: 2, ex: 'Si el 100% de los X hacen Y y Z es X, entonces necesariamente Z hace Y: es instanciación universal = argumento deductivo. Para que siga siendo inductivo (probabilístico), el porcentaje debe ser menor al 100%.'},
  {st: '"El 90% de los hongos filamentosos se desarrolla en ambientes oscuros. El moho negro es hongo filamentoso. → Probablemente el moho se desarrolla en ambientes oscuros." ¿Qué premisa lo fortalece sin que deje de ser silogismo inductivo?', opts: ['El 100% de los hongos filamentosos se desarrolla en ambientes oscuros.', 'El 99% de los hongos filamentosos se desarrolla en ambientes oscuros.', 'El moho negro se desarrolla en ambientes húmedos.', 'Todos los hongos filamentosos se desarrollan en ambientes oscuros.'], c: 1, ex: 'Pasar del 90% al 99% hace el silogismo más fuerte (mayor probabilidad), pero sigue siendo inductivo porque no llega al 100%. Las opciones A y D lo convertirían en deductivo. La opción C no tiene relación con el fortalecimiento.'},
  {st: '"Las semillas de la grevilea, la rosa y el acezintle se encuentran dentro de un fruto. → Es probable que todas las plantas florales tengan semillas dentro de un fruto." ¿Qué premisa fortalece este argumento por enumeración incompleta?', opts: ['Las semillas del hipérico (planta floral) se encuentran dentro de un fruto.', 'Las semillas del hipérico NO se encuentran dentro de un fruto.', 'La grevilea, la rosa y el acezintle son los únicos tres tipos de plantas florales.', 'Las semillas de la azalea se encuentran dentro de un fruto (sin aclarar que la azalea es planta floral).'], c: 0, ex: 'Para fortalecer la enumeración hay que ampliar la muestra con casos que pertenezcan al dominio (plantas florales). La opción A agrega el hipérico (planta floral) con la propiedad = fortalece. La C reduciría la muestra al conjunto total (lo volvería deductivo). La D no especifica que la azalea es planta floral.'},
  {st: 'En un argumento inductivo, si las premisas son verdaderas, la conclusión:', opts: ['Necesariamente es verdadera.', 'Es probablemente verdadera, pero puede ser falsa.', 'Siempre es falsa.', 'No tiene relación con las premisas.'], c: 1, ex: 'Esta es la diferencia fundamental con los deductivos. En los inductivos el apoyo es en grados: las premisas hacen la conclusión más o menos probable, pero no necesaria. Siempre es posible imaginar que las premisas sean verdaderas y la conclusión sea falsa (aunque improbable).'}
]);

registerExercises('pc-parcial', '6', [
  {st: '"El 42% de los voluntarios del estudio reportó haber tenido ataques de pánico." Según Klimovsky, ¿qué tipo de enunciado es?', opts: ['Generalización empírica estadística, porque tiene porcentaje.', 'Enunciado empírico básico, porque refiere a un estudio concreto con muestra abarcable.', 'Enunciado teórico, porque habla de ataques de pánico.', 'Generalización empírica existencial.'], c: 1, ex: 'Aunque tiene porcentaje, refiere a "los voluntarios del estudio" = grupo finito y concreto = abarcable por la experiencia. Es enunciado empírico básico. Sería generalización empírica estadística si dijera "el 42% de las personas del mundo" (inabarcable).'},
  {st: '"El 6% de la población mundial padece de claustrofobia." Según Klimovsky, ¿qué tipo de enunciado es?', opts: ['Enunciado empírico básico, porque tiene porcentaje.', 'Generalización empírica universal.', 'Generalización empírica estadística, porque afirma un porcentaje de una población inabarcable.', 'Enunciado teórico.'], c: 2, ex: '"La población mundial" es inabarcable por la experiencia. El porcentaje sobre esa población inabarcable = generalización empírica estadística. Si fuera "el 6% de los pacientes del estudio", sería básico.'},
  {st: '"Todos los casos de claustrofobia presentan aumento de la frecuencia cardíaca." ¿Qué tipo de enunciado es?', opts: ['Enunciado empírico básico, porque usa el cuantificador "todos".', 'Generalización empírica universal, porque afirma algo de todos los casos de claustrofobia del mundo (inabarcable).', 'Generalización empírica existencial.', 'Enunciado teórico.'], c: 1, ex: '"Todos los casos de claustrofobia" implica la totalidad de los casos del mundo = inabarcable = generalización empírica universal. Si dijera "todos los pacientes del estudio", sería básico (muestra concreta).'},
  {st: 'El ejemplo de Kinsey y McMillen (entrevistas estructuradas, cuestionarios, análisis estadísticos) ilustra qué característica de Bunge:', opts: ['La sistematicidad de la ciencia.', 'La claridad y precisión de la ciencia.', 'La metodicidad de la ciencia.', 'La utilidad de la ciencia.'], c: 2, ex: 'La metodicidad refiere a que la investigación científica se produce a través de investigaciones planificadas y procedimientos ordenados. Kinsey y McMillen usaron métodos organizados rigurosos. No es sistematicidad (que sería sobre la organización lógica de las teorías entre sí).'},
  {st: '"El conocimiento científico no es un conjunto desordenado de proposiciones desconectadas, sino que se encuentra lógica y jerárquicamente organizado." ¿Qué característica de Bunge es?', opts: ['Metódica', 'Clara y precisa', 'Sistemática', 'Analítica'], c: 2, ex: 'La sistematicidad refiere a que los contenidos de la ciencia están organizados y conectados entre sí de manera lógica y jerárquica. La metodicidad refiere al proceso de investigación (cómo se produce el conocimiento). La claridad refiere al lenguaje.'},
  {st: '"La hipótesis de la lateralización cerebral fue aceptada ampliamente y luego refutada por investigaciones recientes." ¿Qué característica de Bunge ilustra esto?', opts: ['La metodicidad de la ciencia.', 'La apertura de la ciencia (es corregible y refutable).', 'La utilidad de la ciencia.', 'La sistematicidad de la ciencia.'], c: 1, ex: 'El conocimiento científico es abierto: siempre está en condiciones de ser continuado, corregido o refutado por la comunidad científica. Este ejemplo muestra que una hipótesis aceptada puede ser refutada sin inconvenientes por nuevas investigaciones.'}
]);

registerExercises('pc-parcial', '7', [
  {st: '"Mucha gente dice que las vacunas son peligrosas. Si tanta gente lo cree, debe ser porque hay algo de cierto en ello." ¿Qué falacia es?', opts: ['Ad verecundiam', 'Ad populum', 'Ad hominem', 'Falacia de la causa falsa'], c: 1, ex: 'Ad populum: la validez del argumento se basa en el apoyo popular ("mucha gente"). No se apela a una autoridad experta (eso sería ad verecundiam), sino a la cantidad de personas que lo creen. La popularidad no es evidencia de verdad.'},
  {st: '"La Dra. Pérez recomienda la meditación diaria, por lo cual debe ser efectiva para reducir el estrés." ¿Qué falacia es?', opts: ['Ad populum', 'Ad hominem', 'Ad verecundiam', 'Falacia naturalista'], c: 2, ex: 'Ad verecundiam: se apela a la autoridad de una persona reconocida (la Dra. Pérez, con título) para justificar la afirmación. Diferencia clave con ad populum: aquí es una autoridad experta, no la masa genérica.'},
  {st: '"Desde que tomo vitamina C todos los días, no he tenido resfriados. Eso demuestra que la vitamina C previene el resfrío común." ¿Qué falacia es?', opts: ['Ad hominem', 'Ad verecundiam', 'Ad populum', 'Post hoc ergo propter hoc (falacia de la causa falsa)'], c: 3, ex: 'Post hoc ergo propter hoc: "después de esto, por lo tanto a causa de esto". Se concluye una relación causal a partir de una mera sucesión temporal. Tomar vitamina C antes de no tener resfriados no prueba que la vitamina C cause esa ausencia de resfriados.'},
  {st: '"No deberías opinar sobre política, apenas tenés 20 años." ¿Qué falacia es?', opts: ['Ad verecundiam', 'Ad populum', 'Ad hominem', 'Falacia naturalista'], c: 2, ex: 'Ad hominem: ataca a la persona (su edad) en vez de al argumento. Se evita refutar el contenido del argumento descalificando al que argumenta. La edad no invalida lógicamente ningún argumento sobre política.'},
  {st: '"Los sujetos que realicen ejercicio regularmente mostrarán una mejora significativa en su capacidad cardiovascular." ¿A qué elemento de la contrastación de hipótesis pertenece (Díez y Moulines)?', opts: ['Datos', 'Condiciones iniciales', 'Predicción', 'Hipótesis auxiliar'], c: 2, ex: 'Es una predicción: afirmación empírica constatable derivada de la hipótesis que anticipa lo que debería observarse. Está en futuro/condicional (lo que "se espera" ver). Los datos son lo efectivamente observado (pasado). La hipótesis es más general.'},
  {st: '"Los sujetos del grupo experimental registraron una media de 7 horas de sueño por noche durante el estudio." ¿A qué elemento de la contrastación pertenece?', opts: ['Predicción', 'Hipótesis', 'Hipótesis auxiliar', 'Datos'], c: 3, ex: 'Son datos: hechos efectivamente detectados durante la contrastación. Están en tiempo pasado y describen lo que realmente ocurrió. Si coinciden con la predicción, brindan evidencia a favor de la hipótesis. Si no coinciden, hay evidencia en contra.'}
]);
