registerExercises('pc-parcial', '1', [
  {st: 'El parcial de PC tiene preguntas de opción múltiple. Las últimas 3–4 preguntas valen:', opts: ['1 punto cada una', '2 puntos o 0 (sin término medio)', '3 puntos', 'Depende del tema'], c: 1, ex: 'Las primeras 5–7 preguntas valen 1 punto cada una si son correctas. Las últimas 3–4 valen 2 puntos o 0: NO hay puntaje parcial (no podés sacar 1 punto por una "media respuesta"). ▸ Por qué las otras están mal: "1 punto cada una" describe las primeras, no las últimas; "3 puntos" no aparece en la escala de Balbiano; "depende del tema" es falso, depende de la POSICIÓN en el examen. Estrategia: asegurate las simples (5–7 puntos) antes de meterte en las grandes.'},
  {st: '¿Cuántos puntos necesitás para obtener nota 4 (aprobado)?', opts: ['4 puntos', '7 puntos', '10 puntos', '13 puntos'], c: 1, ex: 'Tabla oficial Balbiano: 7 puntos → nota 4 (aprobado mínimo). 10 puntos → 7. 13 puntos → 10 (todo perfecto). ▸ Por qué las otras están mal: "4 puntos" da nota 2 (desaprobado); "10 puntos" ya es nota 7; "13 puntos" es la nota máxima 10. Truco: 7 puntos = todas las preguntas de 1 punto (5–7) + UNA de 2 puntos. Con eso ya aprobás.'},
  {st: '¿Cuál es el resultado de a=3; b=0; c=2.5; print((a + b*c - c**b) * c)?', opts: ['5.0', '7.5', '0.0', '2.5'], c: 0, ex: 'Hay que respetar la precedencia: ** primero, luego * y /, después + y -. ▸ Paso 1: c**b = 2.5**0 = 1.0 (cualquier número a la 0 es 1). ▸ Paso 2: b*c = 0*2.5 = 0. ▸ Paso 3: dentro del paréntesis: a + 0 − 1.0 = 3 − 1.0 = 2.0 (queda float porque hay un float). ▸ Paso 4: 2.0 * 2.5 = 5.0. ▸ Por qué las otras están mal: "7.5" sale si no calculás c**b y dejás (3+0)·2.5=7.5; "0.0" sale si multiplicás todo por b=0 mal; "2.5" sale si te olvidás de multiplicar por c al final.'},
  {st: '¿Qué hace el operador ** en Python?', opts: ['División entera', 'Módulo (resto)', 'Potencia', 'Multiplicación doble'], c: 2, ex: '** es POTENCIA: 2**3 = 8 (2 elevado a 3), 4**2 = 16, 5**0 = 1. Tiene la precedencia más alta entre los operadores aritméticos (se evalúa antes que *, /, +, −). ▸ Por qué las otras están mal: "división entera" es // (doble barra); "módulo/resto" es % (porcentaje); "multiplicación doble" no existe en Python.'},
  {st: 'El operador // en Python calcula:', opts: ['División normal (float)', 'La raíz cuadrada', 'El cociente entero (sin decimales)', 'El resto de la división'], c: 2, ex: '// es la DIVISIÓN ENTERA: 7//2 = 3 (no 3.5), trunca hacia el infinito negativo (por eso −7//2 = −4, no −3). ▸ Por qué las otras están mal: "división normal" es solo / (devuelve float siempre); "raíz cuadrada" no es un operador, es math.sqrt() o **0.5; "resto de la división" es % (7%2 = 1).'},
  {st: 'Con a=10 y ok=True, en el código: if a==1 and ok: ... elif a>1: print("OK"). ¿Cuántas condiciones se evalúan?', opts: ['1', '2', '3', '4'], c: 1, ex: '▸ Paso 1: se evalúa a==1 → 10==1 → False (1ª condición evaluada). ▸ Paso 2: como el primer operando del "and" es False, Python NO evalúa ok (cortocircuito de "and"). ok queda sin evaluar. ▸ Paso 3: como el if dio False, pasa al elif y evalúa a>1 → 10>1 → True (2ª condición evaluada). Total: 2 condiciones. ▸ Por qué las otras están mal: "1" supondría que solo se evalúa la del if; "3" supondría que también se evalúa ok (pero el cortocircuito lo evita); "4" no tiene sentido (solo hay 3 condiciones en total).'}
]);

registerExercises('pc-parcial', '2', [
  {st: '¿Cuál es el resultado de a=0; b=1; c=2; d=-2; cant=d-b*b+c*2/b+4; print(int(cant))?', opts: ['3', '4', '5', '6'], c: 2, ex: 'Respeto precedencia: * y / antes que + y −. ▸ Paso 1: b*b = 1*1 = 1. ▸ Paso 2: c*2/b = 2*2/1 = 4/1 = 4.0 (la / siempre da float). ▸ Paso 3: cant = d − 1 + 4.0 + 4 = −2 − 1 + 4.0 + 4 = 5.0. ▸ Paso 4: int(5.0) = 5 (trunca el .0). ▸ Por qué las otras están mal: "3" sale si haces d-b*b+c*2/b sin el +4 final; "4" sale si te olvidás del −1 (b*b); "6" sale si sumás mal alguna parte.'},
  {st: 'El truco "num == int(num)" sirve para:', opts: ['Convertir un número a entero', 'Detectar si un float es en realidad un número entero (ej. 3.0 vs 3.5)', 'Calcular el valor absoluto', 'Redondear hacia arriba'], c: 1, ex: 'int() trunca la parte decimal. Si num=3.0, int(3.0)=3, y la comparación 3.0==3 es True (Python compara numéricamente). Si num=3.5, int(3.5)=3, pero 3.5==3 es False. Así detectás si el float "es realmente un entero disfrazado" o si tiene parte decimal. ▸ Por qué las otras están mal: "convertir a entero" es lo que hace int(num) solo, sin la comparación; "valor absoluto" es abs(num); "redondear hacia arriba" es math.ceil(num).'},
  {st: '"hola"*3 en Python produce:', opts: ['Error de tipo', '"hola3"', '"holaholahola"', '"h o l a 3"'], c: 2, ex: 'El operador * con una string y un entero REPITE la string. "hola"*3 concatena "hola" tres veces seguidas → "holaholahola". Funciona igual con listas: [0]*3 = [0,0,0]. ▸ Por qué las otras están mal: "error" sería si multiplicaras dos strings ("hola"*"hola" sí da error); "hola3" sería con + ("hola"+"3"); "h o l a 3" no es una operación válida en Python.'},
  {st: 'Si varios if están encadenados (sin elif), ¿cuántos se evalúan con a=5?', opts: ['Solo el primero que sea True', 'Solo 1', 'Todos, sin excepción', 'Ninguno si el primero es False'], c: 2, ex: 'Cada if INDEPENDIENTE (sin elif) se evalúa SIEMPRE, sin importar lo que pasó antes. Si tenés 3 ifs separados, se evalúan los 3. ▸ Por qué las otras están mal: "solo el primero que sea True" describe el comportamiento de if/elif/elif (con elif sí hay cortocircuito); "solo 1" es lo mismo, no aplica a ifs sueltos; "ninguno si el primero es False" es lo opuesto a la realidad. ESTA es la trampa clásica del parcial: confundir "if + if + if" (todos se evalúan) con "if + elif + elif" (al primero True se cortan los demás).'},
  {st: '¿Cuál es la diferencia entre / y // en Python?', opts: ['No hay diferencia', '/ da float, // da el cociente entero', '// da float, / da entero', '/ es potencia, // es raíz'], c: 1, ex: '/ siempre devuelve float (incluso si la división es exacta: 6/2 = 3.0). // devuelve el cociente entero, truncando hacia el infinito negativo: 7//2 = 3, −7//2 = −4. ▸ Por qué las otras están mal: "no hay diferencia" es falso; "// da float, / da entero" es invertido; "/ es potencia, // es raíz" no existe (potencia es **, raíz es **0.5).'},
  {st: 'Esta es una pregunta clásica de "equivalencia de condiciones": te dan 4 expresiones booleanas (NO son ifs, son condiciones que dan True o False) y tenés que detectar cuál da un resultado distinto a las otras tres con los mismos valores. Si a=2, b=False, c=3, ¿cuál NO es equivalente?', opts: ['(1) a in range(1,8,2) or b or c>a', '(2) a in range(1,8,2) and b and c>a', '(3) (a>0 and a&lt;8 and a%2!=0) or a&lt;c', '(4) a&lt;c or a in (1,3,5,7)'], c: 1, ex: 'CLAVE: range(1,8,2) NO incluye todos los enteros entre 1 y 8. El "2" final es el PASO. Genera: 1, 3, 5, 7 (arranca en 1, suma 2, no llega a 8). Por eso a=2 NO está en range(1,8,2). Ahora evalúo cada una con a=2, b=False, c=3: ▸ (1) False or False or (3>2)=True → TRUE. ▸ (2) False and False and True → FALSE (el "and" cortocircuita en False). ▸ (3) a%2=0 → a%2!=0 es False → (T and T and F)=False; a&lt;c=2&lt;3=True → False or True → TRUE. ▸ (4) (2&lt;3)=True or (2 in (1,3,5,7))=False → TRUE. Resultado: (1), (3), (4) dan True; (2) da False. La (2) es la diferente. ▸ Truco: cuando hay "and" entre términos y uno es False, todo el "and" se hace False; cuando hay "or" entre términos y uno es True, todo el "or" se hace True.'}
]);

registerExercises('pc-parcial', '3', [
  {st: 'Con producto="birome", unidad="caja", precio=60, en el código: if producto in ("block A4","etiqueta"): ... elif producto in ("plasticola","hoja","birome"): if unidad in ("ciento","docena","bolsa"): print("barato") else: print("caro"). ¿Qué muestra?', opts: ['"barato"', '"caro"', 'Nada', 'Error'], c: 1, ex: '▸ Paso 1: ¿"birome" está en ("block A4","etiqueta")? NO → no entra al primer if. ▸ Paso 2: ¿"birome" está en ("plasticola","hoja","birome")? SÍ → entra al elif. ▸ Paso 3: dentro del elif, ¿"caja" está en ("ciento","docena","bolsa")? NO → va al else → imprime "caro". ▸ Por qué las otras están mal: "barato" sería si unidad fuera "ciento", "docena" o "bolsa"; "Nada" sería si producto no estuviera en ninguna tupla; "Error" no aplica porque la sintaxis es válida.'},
  {st: '¿Qué hace el operador "in" con una tupla? Por ejemplo: animal in ("sapo","caballo","cacatúa")', opts: ['Solo funciona con listas, no con tuplas', 'Verifica si animal es igual a alguno de los elementos de la tupla (devuelve True/False)', 'Cuenta cuántos elementos hay', 'Concatena animal con la tupla'], c: 1, ex: '"in" verifica PERTENENCIA y devuelve True si el elemento aparece, False si no. Funciona con listas, tuplas, strings y ranges. Ej: "sapo" in ("sapo","caballo","cacatúa") → True; "rana" in (...) → False. ▸ Por qué las otras están mal: funciona con TODAS las secuencias, no solo con listas; "contar" sería .count() o len(); "concatenar" sería con +.'},
  {st: 'En una cadena if/elif/elif/else, si la primera condición es True:', opts: ['Se evalúan todas las condiciones siguientes', 'Se ejecuta el bloque del if y se saltan todos los elif y else', 'Se ejecuta el if y luego el else', 'Se ejecuta solo el else'], c: 1, ex: 'En if/elif/else, apenas Python encuentra una condición True, ejecuta SU bloque y salta TODO el resto (no evalúa los elif siguientes ni el else). Esto se llama "estructura excluyente". ▸ Por qué las otras están mal: "evaluar todas" describe ifs separados (sin elif); "ejecutar if y luego else" es imposible en una misma cadena (son excluyentes); "solo else" pasaría si todas las condiciones fueran False.'},
  {st: 'Con a=2, b=False, ¿cómo evalúa la condición "a>0 and b"?', opts: ['True', 'False y NO evalúa b (cortocircuito)', 'False y SÍ evalúa b (no hay cortocircuito)', 'Error'], c: 2, ex: 'El "and" SOLO cortocircuita cuando el operando IZQUIERDO es False (porque ya garantiza False). Acá a>0 = 2>0 = True, así que Python TIENE que evaluar b para saber el resultado. b=False → True and False → False. SÍ evaluó b. ▸ Por qué las otras están mal: "True" es imposible si b=False (porque True and False = False); "NO evalúa b" describiría el caso a&lt;0 and b (donde el cortocircuito sí actúa); "Error" no aplica. REGLA DE ORO: "and" cortocircuita en False; "or" cortocircuita en True.'},
  {st: 'Con a=2, b=True, ¿cómo evalúa la condición "a>0 or b"?', opts: ['True y SÍ evalúa b', 'True y NO evalúa b (cortocircuito)', 'False', 'Error'], c: 1, ex: 'El "or" cortocircuita cuando el operando IZQUIERDO es True (porque ya garantiza True). Acá a>0=True, así que Python NO necesita evaluar b → resultado: True, sin tocar b. ▸ Por qué las otras están mal: "SÍ evalúa b" sería si a>0 fuera False (entonces sí debería ver b); "False" no es posible porque al menos una parte es True; "Error" no aplica.'},
  {st: 'Con animal="cacatúa", el código: if animal in ("sapo","caballo","cacatúa"): print("X") if animal in ("guacamayo","pitón"): print("Y"). ¿Cuántas condiciones se evalúan?', opts: ['1', '2', '3', '0'], c: 1, ex: 'Son DOS if INDEPENDIENTES (no hay elif), por lo tanto AMBOS se evalúan SIEMPRE, sin importar el resultado del primero. ▸ Paso 1: 1ª condición → animal in ("sapo","caballo","cacatúa") → True → imprime "X". ▸ Paso 2: 2ª condición → animal in ("guacamayo","pitón") → False → no imprime "Y". Total: 2 condiciones evaluadas. ▸ Por qué las otras están mal: "1" supondría cortocircuito (no aplica entre ifs separados); "3" no tiene sentido (solo hay 2 ifs); "0" supondría que ningún if se evalúa.'}
]);

registerExercises('pc-parcial', '4', [
  {st: '¿Cuántas veces itera "for i in range(1, 15, 5)"?', opts: ['2', '3', '4', '14'], c: 1, ex: 'range(inicio, fin, paso) genera valores desde "inicio" sumando "paso" mientras sean MENORES que "fin" (no incluye el fin). ▸ Genera: 1 (start), 1+5=6, 6+5=11. El siguiente sería 11+5=16, pero 16 ≥ 15 → corta. Lista: [1, 6, 11] → 3 valores. ▸ Por qué las otras están mal: "2" se obtendría si confundieras y empezaras desde 0; "4" si incluyeras el 16 erróneamente; "14" si pensaras que recorre del 1 al 14 de a 1 (ignorando el paso).'},
  {st: '¿Cuántas veces itera "for i in range(1, 10, -4)"?', opts: ['0 (no itera)', '2', '3', '10'], c: 0, ex: 'Con paso negativo, range necesita inicio > fin para producir valores. Acá inicio=1 y fin=10, así que 1 NO es mayor que 10 → range vacío → el bucle no itera ninguna vez. ▸ Por qué las otras están mal: "2", "3", "10" supondrían que el rango produce valores cuando en realidad está vacío. Para iterar con paso negativo necesitarías por ej. range(10, 1, -4) → 10, 6, 2 (3 iteraciones).'},
  {st: 'En el código "for i in range(3): i=0", ¿cuántas veces itera el bucle?', opts: ['1 (se queda en 0)', '3', 'Infinito', '0'], c: 1, ex: 'Reasignar i DENTRO del cuerpo del for NO afecta al iterador. range(3) ya generó internamente la secuencia [0,1,2]; en cada iteración Python le asigna a i el siguiente valor del range, ignorando lo que vos hayas escrito. El cuerpo se ejecuta 3 veces aunque al final de cada iteración i valga 0. ▸ Por qué las otras están mal: "1" supondría que el for chequea i; "infinito" no aplica porque el range tiene tamaño fijo; "0" requiere range vacío.'},
  {st: 'Con i=100, el while: while i>0: i-=70. ¿Cuántas veces itera?', opts: ['1', '2', '3', 'Infinito'], c: 1, ex: '▸ Iteración 1: i=100, 100>0 True → i = 100−70 = 30. ▸ Iteración 2: i=30, 30>0 True → i = 30−70 = −40. ▸ Chequeo siguiente: i=−40, −40>0 False → SALE. Total: 2 iteraciones (las dos en las que el cuerpo se ejecutó). ▸ Por qué las otras están mal: "1" si te quedaras solo con la primera vuelta; "3" si contaras la verificación final como iteración; "infinito" no aplica porque i se va achicando.'},
  {st: '¿Qué muestra el código: for i in range(3): for j in (2,1): print("a"*j)?', opts: ['"aa","aaa","aa","aaa","aa","aaa"', '"aa","a","aa","a","aa","a"', '"a","a","a"', '"aaa","aa"'], c: 1, ex: 'For externo itera 3 veces (i=0,1,2). Para CADA i, el for interno itera sobre la tupla (2, 1): primero j=2 → "a"*2 = "aa"; después j=1 → "a"*1 = "a". Total: 3 × 2 = 6 prints, en orden aa/a/aa/a/aa/a. ▸ Por qué las otras están mal: "aa,aaa,..." multiplica por (2,3) en lugar de (2,1); "a,a,a" sería si solo el for interno corriera con j=1; "aaa,aa" sería con (3,2) y solo una iteración.'},
  {st: '¿Cuántas veces imprime "a" el código: for letra in "sabana": if letra=="a": i=1; while i&lt;2: print("a"); i+=2?', opts: ['1', '2', '3', '7'], c: 2, ex: '"sabana" tiene 6 letras: s, a, b, a, n, a. La "a" aparece 3 veces (en posiciones 1, 3, 5). Cada vez que letra=="a": ▸ i=1; while 1&lt;2 True → print "a"; i = 1+2 = 3; while 3&lt;2 False → sale del while (1 print por cada "a"). Total: 3 letras "a" × 1 print = 3 impresiones. ▸ Por qué las otras están mal: "1" si solo procesaras la primera "a"; "2" si te olvidaras de una; "7" si confundieras letras totales o repetidas.'}
]);

registerExercises('pc-parcial', '5', [
  {st: 'Si a=[10,20,30,40], ¿qué devuelve a[-2]?', opts: ['10', '20', '30', '40'], c: 2, ex: 'Los índices negativos cuentan desde el FINAL: a[-1] es el último, a[-2] el penúltimo, etc. ▸ a[-1] = 40 (último), a[-2] = 30 (penúltimo), a[-3] = 20, a[-4] = 10 (primero). Por lo tanto a[-2] = 30. ▸ Por qué las otras están mal: "10" es a[0] o a[-4]; "20" es a[1] o a[-3]; "40" es a[3] o a[-1].'},
  {st: 'Con a=[0,3,1] y b=[3,6,11,0], el código: c=[]; for num in a: c.append(b[num]*2). ¿Cuál es c?', opts: ['[0,3,1]', '[3,6,11]', '[6,0,12]', '[0,6,2]'], c: 2, ex: 'Recorré a y para cada num, agregás b[num]*2 a c. ▸ num=0: b[0]=3, 3*2=6. ▸ num=3: b[3]=0 (último de b), 0*2=0. ▸ num=1: b[1]=6, 6*2=12. Resultado: c = [6, 0, 12]. ▸ Por qué las otras están mal: "[0,3,1]" es a sin tocar; "[3,6,11]" es b sin multiplicar; "[0,6,2]" sería si multiplicaras a por 2 sin usar b como índice.'},
  {st: '¿Cuál es la diferencia entre a.extend(b) y a+b?', opts: ['No hay diferencia', 'extend() modifica a en su lugar; + genera una nueva lista sin modificar a ni b', '+ modifica a; extend() genera una nueva lista', 'extend() solo funciona con listas de números'], c: 1, ex: 'a.extend(b) MUTA la lista a, agregándole los elementos de b al final (a queda más larga, b igual). a+b crea una NUEVA lista con la concatenación, sin tocar a ni b. ▸ Ej: a=[1,2], b=[3]. Después de a.extend(b): a=[1,2,3], b=[3]. Después de c=a+b: a=[1,2], b=[3], c=[1,2,3]. ▸ Por qué las otras están mal: "no hay diferencia" es falso; "+ modifica a" es lo opuesto al comportamiento real (+ no muta); extend() funciona con cualquier iterable, no solo listas de números.'},
  {st: 'Con numeros=[-3.36,10,2,0.25,-3]: separás en lista de enteros y de floats, y a cada una le aplicás sort()+reverse(). ¿Cuál queda como lista de enteros?', opts: ['[-3,2,10]', '[10,2,-3]', '[2,10,-3]', '[-3.36,0.25]'], c: 1, ex: 'Enteros (donde num==int(num)): de [-3.36, 10, 2, 0.25, -3] son 10, 2, -3 (los que no tienen decimal). ▸ sort() ordena ascendente: [-3, 2, 10]. ▸ reverse() invierte: [10, 2, -3]. ▸ Por qué las otras están mal: "[-3,2,10]" es solo después de sort() sin el reverse(); "[2,10,-3]" no corresponde a ningún paso; "[-3.36,0.25]" es la lista de FLOATS, no de enteros.'},
  {st: 'El método list.remove(x) hace:', opts: ['Elimina todos los elementos iguales a x', 'Elimina solo la PRIMERA ocurrencia de x', 'Elimina el elemento en la posición x', 'Elimina el último elemento'], c: 1, ex: 'remove(x) busca de izquierda a derecha y elimina la PRIMERA aparición de x. Si x no está, lanza ValueError. ▸ Ej: a=[1,2,3,2]; a.remove(2) → a=[1,3,2] (queda el segundo 2). ▸ Por qué las otras están mal: "todos los iguales" requeriría un loop; "elimento en posición x" es a.pop(x) o del a[x]; "último elemento" es a.pop() sin argumento.'},
  {st: '[0]*6 en Python produce:', opts: ['Error', '[0,0,0,0,0,0]', '[6]', 'Una lista con el número 06'], c: 1, ex: 'El operador * con una lista y un entero REPITE la lista n veces. [0]*6 = [0,0,0,0,0,0] (lista con 6 ceros). Es la forma idiomática de inicializar listas de tamaño fijo. ▸ Por qué las otras están mal: "Error" no, esta es una operación válida; "[6]" es una lista con un solo 6; "[06]" no es sintaxis Python (los números no llevan ceros a la izquierda).'}
]);

registerExercises('pc-parcial', '6', [
  {st: 'Si pal="GEMELO", ¿qué devuelve pal[2:]?', opts: ['"GE"', '"MELO"', '"EMELO"', '"GEMELO"'], c: 1, ex: 'Slicing pal[a:b] toma desde la posición a (inclusive) hasta b (exclusive). pal[2:] sin b toma desde 2 hasta el final. ▸ Posiciones de "GEMELO": G=0, E=1, M=2, E=3, L=4, O=5. ▸ Desde la 2 al final: M, E, L, O → "MELO". ▸ Por qué las otras están mal: "GE" es pal[:2] (las primeras 2); "EMELO" tomaría desde la 1 (pal[1:]); "GEMELO" sería pal[:] o pal entero.'},
  {st: 'Si nom1="juan", ¿qué devuelve nom1[::-1]?', opts: ['"juan"', '"nauj"', '"j"', 'Error'], c: 1, ex: '[::-1] es el truco para INVERTIR una string (paso negativo en el slicing). Lee la string de atrás para adelante. "juan" → "nauj". ▸ Por qué las otras están mal: "juan" sería [::1] o [:]; "j" sería [0] o [:1]; "Error" no, es sintaxis válida. Truco: el formato [inicio:fin:paso] con paso=-1 invierte; con paso=2 saltea de a uno.'},
  {st: 'Con frase="hola mundo": ejecuto frase.replace("hola","chau"). Después de esa línea, ¿cuánto vale frase?', opts: ['"chau mundo"', '"hola mundo" (no cambió)', '"chau"', 'Error'], c: 1, ex: 'Las strings en Python son INMUTABLES. replace() devuelve una NUEVA string con el cambio aplicado, pero NO modifica la original. Para que frase cambie tenés que reasignarla: frase = frase.replace("hola","chau"). Sin la asignación, frase sigue siendo "hola mundo". ▸ Por qué las otras están mal: "chau mundo" sería el resultado SI hubieras hecho frase = frase.replace(...); "chau" no, replace cambia la palabra pero conserva el resto; "Error" no aplica. Esta es una trampa MUY frecuente del parcial.'},
  {st: '"hola qué tal".split() devuelve:', opts: ['"hola,qué,tal"', '["hola","qué","tal"]', '("hola","qué","tal")', 'Error'], c: 1, ex: 'split() sin argumento divide por espacios en blanco (espacios, tabs, saltos de línea) y devuelve una LISTA de strings. ▸ "hola qué tal".split() → ["hola", "qué", "tal"]. ▸ Por qué las otras están mal: "hola,qué,tal" es una string, no una lista; ("hola","qué","tal") es una tupla (no, split devuelve lista); "Error" no, es sintaxis válida.'},
  {st: '" ".join(["hola","mundo"]) devuelve:', opts: ['["hola","mundo"]', '"hola mundo"', '"hola,mundo"', '"holaMundo"'], c: 1, ex: 'join() une los elementos de una lista usando como separador la string que está antes del punto. " ".join(...) une con un espacio → "hola mundo". Es la operación INVERSA de split(). ▸ Por qué las otras están mal: ["hola","mundo"] es la lista original (join SIEMPRE devuelve string); "hola,mundo" sería con ",".join(...); "holaMundo" sería con "".join(...) (sin separador).'},
  {st: 'Con pal1="Hola", nom1="juan", nom2="Elena": texto = pal1 + nom1[::-1] + " y " + nom2[:3]. ¿Cuánto vale texto?', opts: ['"Holanauj y Ele"', '"Holajuan y Ele"', '"Hola y Elena"', '"holanauj y ele"'], c: 0, ex: '▸ pal1 = "Hola". ▸ nom1[::-1] invierte "juan" → "nauj". ▸ " y " es texto literal. ▸ nom2[:3] toma posiciones 0,1,2 de "Elena" → "Ele". ▸ Concatenación: "Hola" + "nauj" + " y " + "Ele" = "Holanauj y Ele". ▸ Por qué las otras están mal: "Holajuan y Ele" sería sin invertir nom1; "Hola y Elena" sería sin slices; "holanauj y ele" sería todo en minúscula (.lower() no se aplicó).'}
]);

registerExercises('pc-parcial', '7', [
  {st: 'Con lista=[1,0,3] y factor=[3,6,2], la función producto(n1,n2) debe dar las salidas 3 / 0 / 6 (una por cada par). ¿Cuál definición es correcta?', opts: ['def producto(n1): return n1*n1', 'def producto(n1,n2): return n1*n2', 'def producto(): return n1*n2', 'def producto(n1,n2): return n2'], c: 1, ex: 'La función se llama con 2 argumentos producto(lista[i], factor[i]) → necesita 2 parámetros. ▸ Verifico: producto(1,3) = 1*3 = 3 ✓; producto(0,6) = 0*6 = 0 ✓; producto(3,2) = 3*2 = 6 ✓. La operación es multiplicación. ▸ Por qué las otras están mal: "def producto(n1)" tiene 1 parámetro (no acepta 2 args); "def producto():" sin parámetros usaría n1, n2 globales (UnboundLocalError); "return n2" devolvería 3,6,2 (no 3,0,6).'},
  {st: '¿Qué devuelve una función si no tiene instrucción "return" (o tiene return sin valor)?', opts: ['0', 'Error', 'None', 'La última variable que usó'], c: 2, ex: 'En Python, las funciones SIEMPRE devuelven algo. Si no escribís return (o lo escribís solo, sin valor), Python devuelve None implícitamente. Hacer print(funcion_sin_return()) imprimiría "None". ▸ Por qué las otras están mal: "0" es un valor numérico, no es lo que retorna por defecto; "Error" no, no es un error sino comportamiento normal; "última variable" no, las variables locales se destruyen al salir.'},
  {st: 'Con term1=[5,0,3] y term2=[3,6,2], la función calcula(n1,n2) debe dar las salidas 8 / 6 / 5. ¿Qué operación hace?', opts: ['Multiplicación: n1*n2', 'Suma: n1+n2', 'Resta: n1-n2', 'División: n1/n2'], c: 1, ex: 'Llama calcula(term2[i], term1[i]). ▸ calcula(3,5) = 8 → 3+5=8 ✓; calcula(6,0) = 6 → 6+0=6 ✓; calcula(2,3) = 5 → 2+3=5 ✓. Operación: SUMA. ▸ Por qué las otras están mal: multiplicación daría 15/0/6 (no 8/6/5); resta daría -2/6/-1; división daría 0.6/inf/0.66.'},
  {st: 'Una variable definida dentro de una función (variable local):', opts: ['Es accesible desde cualquier parte del programa', 'Solo existe dentro de la función; fuera no existe', 'Reemplaza a una variable global del mismo nombre permanentemente', 'No puede tener el mismo nombre que una variable global'], c: 1, ex: 'Las variables locales viven solo durante la ejecución de la función. Apenas la función termina, desaparecen. Si intentás usarlas afuera → NameError. ▸ Por qué las otras están mal: "accesible desde cualquier parte" describe variables GLOBALES; "reemplaza a la global permanentemente" es falso (la global no se toca, salvo con la palabra "global"); "no puede tener el mismo nombre" es falso (sí puede, y la local tiene prioridad dentro de la función — esto se llama "shadowing").'},
  {st: 'El patrón "crear lista vacía → recorrer con for → agregar con append → retornar la lista" sirve principalmente para:', opts: ['Solo ordenar listas', 'Filtrar o transformar elementos y devolver una nueva lista', 'Invertir una lista', 'Contar elementos'], c: 1, ex: 'Es el patrón estrella del parcial: resultado=[]; for x in entrada: if condicion: resultado.append(transformar(x)); return resultado. Permite filtrar (qué cumplen X), mapear (transformar uno a uno) o ambos. ▸ Por qué las otras están mal: "ordenar" se hace con sort()/sorted() (no necesita el patrón); "invertir" con [::-1] o reverse(); "contar" con len() o count() (no necesita lista nueva).'},
  {st: 'def fun(t): vocales="AEIOU"; rep=""; for letra in t: if letra in vocales and letra not in rep: rep+=letra; return rep.lower(). Con t="ESTUDIO", ¿qué devuelve?', opts: ['"euio"', '"estudio"', '"ESTUDIO"', '"eee"'], c: 0, ex: 'Recorre "ESTUDIO" letra por letra y va guardando las vocales NO REPETIDAS en mayúscula, después devuelve todo en minúscula. ▸ E: en "AEIOU" y no en "" → rep="E". ▸ S: no es vocal → skip. ▸ T: no es vocal → skip. ▸ U: en vocales y no en "E" → rep="EU". ▸ D: no es vocal → skip. ▸ I: en vocales y no en "EU" → rep="EUI". ▸ O: en vocales y no en "EUI" → rep="EUIO". ▸ return "EUIO".lower() = "euio". ▸ Por qué las otras están mal: "estudio" sería t.lower() entera (no filtra); "ESTUDIO" es t sin tocar; "eee" repite E sin avanzar (la condición "not in rep" lo evita).'}
]);
