registerExercises('pc-parcial', '1', [
  {st: 'El parcial de PC tiene preguntas de opción múltiple. Las últimas 3–4 preguntas valen:', opts: ['1 punto cada una', '2 puntos o 0 (sin término medio)', '3 puntos', 'Depende del tema'], c: 1, ex: 'Las primeras 5–7 preguntas valen 1 punto si son correctas. Las últimas 3–4 valen 2 puntos o 0: no hay puntos parciales. Por eso conviene asegurarse las simples primero.'},
  {st: '¿Cuántos puntos necesitás para obtener nota 4 (aprobado)?', opts: ['4 puntos', '7 puntos', '10 puntos', '13 puntos'], c: 1, ex: 'Según la tabla de conversión: 7 puntos → nota 4. Con todas las preguntas de 1 punto acertadas (5–7) más 1 de 2 puntos ya llegás. Priorizá las preguntas simples.'},
  {st: '¿Cuál es el resultado de: a=3; b=0; c=2.5; print((a + b*c - c**b) * c)?', opts: ['5.0', '7.5', '0.0', '2.5'], c: 0, ex: 'Paso 1: c**b = 2.5**0 = 1.0. Paso 2: b*c = 0*2.5 = 0. Paso 3: a+0-1.0 = 2.0. Paso 4: 2.0*2.5 = 5.0. Resultado: 5.0.'},
  {st: '¿Qué hace el operador ** en Python?', opts: ['División entera', 'Módulo (resto)', 'Potencia', 'Multiplicación doble'], c: 2, ex: '** es el operador de potencia: 2**3 = 8, 4**2 = 16. Tiene la precedencia más alta de todos los operadores aritméticos (se evalúa primero).'},
  {st: 'El operador // en Python calcula:', opts: ['División normal (float)', 'La raíz cuadrada', 'El cociente entero (sin decimales)', 'El resto de la división'], c: 2, ex: '// es la división entera: 7//2 = 3 (no 3.5). El resto de la división es %, que en este ejemplo sería 7%2 = 1.'},
  {st: 'Si a=10 y ok=True, en el siguiente código: if a==1 and ok: ... elif a>1: print("OK") — ¿cuántas condiciones se evalúan?', opts: ['1', '2', '3', '4'], c: 1, ex: 'Se evalúa a==1 (False). Por cortocircuito con "and", ok NO se evalúa. Como el if fue False, se evalúa a>1 (True). Total: 2 condiciones evaluadas.'}
]);

registerExercises('pc-parcial', '2', [
  {st: '¿Cuál es el resultado de: a=0; b=1; c=2; d=-2; cant=d-b*b+c*2/b+4; print(int(cant))?', opts: ['3', '4', '5', '6'], c: 2, ex: 'b*b=1. c*2/b=4.0. cant=-2-1+4.0+4=5.0. int(5.0)=5. Resultado: 5.'},
  {st: 'El truco num==int(num) sirve para:', opts: ['Convertir un número a entero', 'Detectar si un float es en realidad un número entero', 'Calcular el valor absoluto', 'Redondear hacia arriba'], c: 1, ex: 'int() trunca hacia cero. Si num=3.0, int(3.0)=3, y 3.0==3 es True. Si num=3.5, int(3.5)=3, y 3.5==3 es False. Así se distingue si un float tiene parte decimal o no.'},
  {st: '"hola"*3 en Python produce:', opts: ['Error de tipo', '"hola3"', '"holaholahola"', '"h o l a 3"'], c: 2, ex: 'El operador * aplicado a una string y un entero repite la string. "hola"*3 = "holaholahola". Funciona igual con listas: [0]*3 = [0,0,0].'},
  {st: 'Si varios if están encadenados (sin elif), ¿cuántos se evalúan con a=5?', opts: ['Solo el primero que sea True', 'Solo 1', 'Todos, sin excepción', 'Ninguno si el primero es False'], c: 2, ex: 'Los if independientes se evalúan SIEMPRE, uno por uno, sin importar lo que pasó antes. Solo con elif/else hay cortocircuito. Esta es una trampa clásica en preguntas de "¿cuál evalúa menos condiciones?".'},
  {st: '¿Cuál es la diferencia entre / y // en Python?', opts: ['No hay diferencia', '/ da float, // da el cociente entero', '// da float, / da entero', '/ es potencia, // es raíz'], c: 1, ex: '7/2 = 3.5 (siempre devuelve float). 7//2 = 3 (cociente entero, trunca hacia abajo). -7//2 = -4 (no -3, porque trunca hacia el infinito negativo).'},
  {st: 'Si a=2, b=False, c=3, ¿cuál de estas 4 condiciones NO es equivalente a las otras tres?', opts: ['(1) a in range(1,8,2) or b or c>a', '(2) a in range(1,8,2) and b and c>a', '(3) (a>0 and a&lt;8 and a%2!=0) or a&lt;c', '(4) a&lt;c or a in (1,3,5,7)'], c: 1, ex: 'Con a=2, b=False, c=3 evalúo cada una. (1): 2 in range(1,8,2) → 2 está en [1,3,5,7]? NO → False. False or False or 3>2=True → True. (2): False and False and True → False. (3): (True and True and True) or True → True. (4): True or 2 in (1,3,5,7)=False → True. La (2) da False; las otras tres dan True.'}
]);

registerExercises('pc-parcial', '3', [
  {st: 'Con producto="birome", unidad="caja", precio=60: if producto in ("block A4","etiqueta"): ... elif producto in ("plasticola","hoja","birome"): if unidad in ("ciento","docena","bolsa"): print("barato") else: print("caro") — ¿qué muestra?', opts: ['"barato"', '"caro"', 'Nada', 'Error'], c: 1, ex: '"birome" no está en ("block A4","etiqueta") → sigue. "birome" sí está en ("plasticola","hoja","birome") → entra. "caja" no está en ("ciento","docena","bolsa") → else → imprime "caro".'},
  {st: '¿Qué hace el operador "in" con una tupla? Por ejemplo: animal in ("sapo","caballo","cacatúa")', opts: ['Solo funciona con listas, no con tuplas', 'Verifica si animal es igual a alguno de los elementos de la tupla', 'Cuenta cuántos elementos hay', 'Concatena animal con la tupla'], c: 1, ex: '"in" verifica pertenencia: devuelve True si el elemento está en la secuencia, False si no. Funciona con listas, tuplas, strings y ranges.'},
  {st: 'En una cadena if/elif/elif/else, si la primera condición es True:', opts: ['Se evalúan todas las condiciones siguientes', 'Se ejecuta el bloque del if y se saltan todos los elif y else', 'Se ejecuta el if y luego el else', 'Se ejecuta solo el else'], c: 1, ex: 'Una vez que Python encuentra un bloque cuya condición es True, ejecuta ese bloque y salta todo el resto. Los elif y else siguientes no se evalúan.'},
  {st: 'Con a=2, b=False: la condición "a>0 and b" evalúa:', opts: ['True', 'False y NO evalúa b', 'False y SÍ evalúa b', 'Error'], c: 1, ex: 'a>0 es True. Con "and", Python DEBE evaluar la segunda parte. b=False. True and False = False. Nota: el cortocircuito de "and" ocurre cuando la primera parte es FALSE (ahí no evalúa la segunda).'},
  {st: 'Con a=2, b=True: la condición "a>0 or b" evalúa:', opts: ['True y SÍ evalúa b', 'True y NO evalúa b (cortocircuito)', 'False', 'Error'], c: 1, ex: 'a>0 es True. Con "or", si la primera parte es True, el resultado ya es True sin importar la segunda. Python no evalúa b. Cortocircuito: "or" cortocircuita cuando la primera es TRUE.'},
  {st: '¿Cuántas condiciones se evalúan si animal="cacatúa", y el código es: if animal in ("sapo","caballo","cacatúa"): print("X") if animal in ("guacamayo","pitón"): print("Y")?', opts: ['1', '2', '3', '0'], c: 1, ex: 'Son dos if independientes (no elif). El primero se evalúa siempre: animal in ("sapo","caballo","cacatúa") = True (1 condición). El segundo también se evalúa siempre: animal in ("guacamayo","pitón") = False (2ª condición). Total: 2.'}
]);

registerExercises('pc-parcial', '4', [
  {st: '¿Cuántas veces itera "for i in range(1, 15, 5)"?', opts: ['2', '3', '4', '14'], c: 1, ex: 'range(1,15,5) genera: 1, 6, 11. El siguiente sería 16 que ya supera 15 (límite). Total: 3 iteraciones.'},
  {st: '¿Cuántas veces itera "for i in range(1, 10, -4)"?', opts: ['0 (no itera)', '2', '3', '10'], c: 0, ex: 'Con paso negativo, se necesita inicio > fin para que el range no esté vacío. Aquí inicio=1 < fin=10, entonces el range está vacío. El bucle no itera ninguna vez.'},
  {st: 'En el código: for i in range(3): i=0 — ¿cuántas veces itera el bucle?', opts: ['1 (se queda en 0)', '3', 'Infinito', '0'], c: 1, ex: 'Reasignar i dentro del for NO afecta al range. El range genera los valores 0,1,2 y en cada iteración asigna el siguiente. El cuerpo se ejecuta 3 veces aunque i siempre valga 0 al final.'},
  {st: 'Con i=100, el while: while i>0: i-=70 — ¿cuántas veces itera?', opts: ['1', '2', '3', 'Infinito'], c: 1, ex: 'i=100: 100>0 True → i=30. i=30: 30>0 True → i=-40. i=-40: -40>0 False → sale. Total: 2 iteraciones.'},
  {st: '¿Qué muestra este código? for i in range(3): for j in (2,1): print("a"*j)', opts: ['"aa","aaa","aa","aaa","aa","aaa"', '"aa","a","aa","a","aa","a"', '"a","a","a"', '"aaa","aa"'], c: 1, ex: 'El for externo itera 3 veces (i=0,1,2). El for interno itera sobre (2,1): primero j=2 → "aa", luego j=1 → "a". Resultado: aa/a/aa/a/aa/a (6 líneas).'},
  {st: '¿Cuántas veces imprime "a" este código? for letra in "sabana": if letra=="a": i=1; while i&lt;2: print("a"); i+=2', opts: ['1', '2', '3', '7'], c: 2, ex: '"sabana" tiene letras: s,a,b,a,n,a. La "a" aparece en posiciones 1,3,5 → 3 veces. Cada vez que letra=="a": i=1, while 1&lt;2 True → imprime "a", i=3, while 3&lt;2 False → sale. Total: 3 impresiones.'}
]);

registerExercises('pc-parcial', '5', [
  {st: 'Si a=[10,20,30,40], ¿qué devuelve a[-2]?', opts: ['10', '20', '30', '40'], c: 2, ex: 'Los índices negativos cuentan desde el final. a[-1]=40, a[-2]=30, a[-3]=20, a[-4]=10. Por lo tanto a[-2] = 30.'},
  {st: 'Con a=[0,3,1] y b=[3,6,11,0], y el código: c=[]; for num in a: c.append(b[num]*2) — ¿cuál es c?', opts: ['[0,3,1]', '[3,6,11]', '[6,0,12]', '[0,6,2]'], c: 2, ex: 'num=0: b[0]=3, 3*2=6. num=3: b[3]=0, 0*2=0. num=1: b[1]=6, 6*2=12. c=[6,0,12].'},
  {st: '¿Cuál es la diferencia entre a.extend(b) y a+b?', opts: ['No hay diferencia', 'extend() modifica a en su lugar; + genera una nueva lista sin modificar a ni b', '+ modifica a; extend() genera una nueva lista', 'extend() solo funciona con listas de números'], c: 1, ex: 'a.extend(b) agrega los elementos de b AL FINAL de a (modifica a). a+b crea una nueva lista con los elementos de ambas sin modificar ninguna. Esta diferencia es clave para los ejercicios de "¿cuál NO deja la lista así?".'},
  {st: 'Con numeros=[-3.36,10,2,0.25,-3]: después de separar enteros y floats, y aplicar sort()+reverse() a cada lista, ¿cuáles son los enteros?', opts: ['[-3,2,10]', '[10,2,-3]', '[2,10,-3]', '[-3.36,0.25]'], c: 1, ex: 'Enteros del conjunto (num==int(num)): 10, 2, -3. sort() los ordena: [-3,2,10]. reverse() los invierte: [10,2,-3].'},
  {st: 'El método list.remove(x) hace:', opts: ['Elimina todos los elementos iguales a x', 'Elimina solo la PRIMERA ocurrencia de x', 'Elimina el elemento en la posición x', 'Elimina el último elemento'], c: 1, ex: 'remove(x) busca de izquierda a derecha y elimina solo la PRIMERA ocurrencia de x. Si x no existe, da ValueError.'},
  {st: '[0]*6 en Python produce:', opts: ['Error', '[0,0,0,0,0,0]', '[6]', 'Una lista con el número 06'], c: 1, ex: 'El operador * con una lista y un entero repite la lista. [0]*6 crea una lista con 6 ceros: [0,0,0,0,0,0]. Es la forma idiomática de crear una lista de tamaño fijo con valor inicial.'}
]);

registerExercises('pc-parcial', '6', [
  {st: 'Si pal="GEMELO", ¿qué devuelve pal[2:]?', opts: ['"GE"', '"MELO"', '"EMELO"', '"GEMELO"'], c: 1, ex: 'pal[2:] toma desde la posición 2 hasta el final. G=0, E=1, M=2, E=3, L=4, O=5. Desde posición 2: "MELO".'},
  {st: 'Si nom1="juan", ¿qué devuelve nom1[::-1]?', opts: ['"juan"', '"nauj"', '"j"', 'Error'], c: 1, ex: '[::-1] es el truco para invertir una string. "juan" invertida es "nauj". Recordá: [::-1] significa "recorrés toda la string de atrás para adelante".'},
  {st: 'Con frase="hola mundo": frase.replace("hola","chau") — después de esta línea, ¿cuánto vale frase?', opts: ['"chau mundo"', '"hola mundo" (no cambió)', '"chau"', 'Error'], c: 1, ex: 'replace() devuelve UNA NUEVA STRING, no modifica la original. Para que frase cambie hay que hacer: frase = frase.replace("hola","chau"). Sin la reasignación, frase sigue siendo "hola mundo".'},
  {st: '"hola qué tal".split() devuelve:', opts: ['"hola,qué,tal"', '["hola","qué","tal"]', '("hola","qué","tal")', 'Error'], c: 1, ex: 'split() sin argumento divide por espacios en blanco (espacios, tabs, saltos de línea) y devuelve una lista de strings. Muy útil para procesar frases palabra por palabra.'},
  {st: '" ".join(["hola","mundo"]) devuelve:', opts: ['["hola","mundo"]', '"hola mundo"', '"hola,mundo"', '"holaMundo"'], c: 1, ex: 'join() une los elementos de la lista con el separador que está a la izquierda del punto. " ".join(...) une con un espacio: "hola mundo". ",".join(...) uniría con coma: "hola,mundo".'},
  {st: 'Con pal1="Hola", nom1="juan", nom2="Elena": texto=pal1+nom1[::-1]+" y "+nom2[:3] — ¿cuánto vale texto?', opts: ['"Holanauj y Ele"', '"Holajuan y Ele"', '"Hola y Elena"', '"holanauj y ele"'], c: 0, ex: 'nom1[::-1]="nauj". nom2[:3]="Ele" (posiciones 0,1,2). texto="Hola"+"nauj"+" y "+"Ele"="Holanauj y Ele".'}
]);

registerExercises('pc-parcial', '7', [
  {st: 'Con lista=[1,0,3] y factor=[3,6,2], la función producto(n1,n2) debe dar salida 3/0/6. ¿Cuál definición es correcta?', opts: ['def producto(n1): return n1*n1', 'def producto(n1,n2): return n1*n2', 'def producto(): return n1*n2', 'def producto(n1,n2): return n2'], c: 1, ex: 'La función se llama con 2 argumentos → necesita 2 parámetros. 1*3=3 ✓, 0*6=0 ✓, 3*2=6 ✓. La operación es multiplicación y hay que devolver el resultado.'},
  {st: '¿Qué devuelve una función si no tiene instrucción "return"?', opts: ['0', 'Error', 'None', 'La última variable que usó'], c: 2, ex: 'En Python, si una función no tiene return (o tiene return sin valor), devuelve None implícitamente. Hacer print(funcion_sin_return()) imprimiría "None".'},
  {st: 'Con term1=[5,0,3] y term2=[3,6,2], la función calcula(n1,n2) debe dar salida 8/6/5. ¿Qué operación hace?', opts: ['Multiplicación: n1*n2', 'Suma: n1+n2', 'Resta: n1-n2', 'División: n1/n2'], c: 1, ex: 'Se llama calcula(term2[i],term1[i]): calcula(3,5)=8 → 3+5=8 ✓, calcula(6,0)=6 → 6+0=6 ✓, calcula(2,3)=5 → 2+3=5 ✓. Operación: suma.'},
  {st: 'Una variable definida dentro de una función (variable local):', opts: ['Es accesible desde cualquier parte del programa', 'Solo existe dentro de la función; fuera no existe', 'Reemplaza a una variable global del mismo nombre permanentemente', 'No puede tener el mismo nombre que una variable global'], c: 1, ex: 'Las variables locales existen solo durante la ejecución de la función. Al salir, desaparecen. Dos funciones pueden tener variables locales con el mismo nombre sin que interfieran.'},
  {st: 'El patrón "crear lista vacía, recorrer con for, agregar con append, retornar" sirve para:', opts: ['Solo ordenar listas', 'Filtrar o transformar elementos y devolver una nueva lista', 'Invertir una lista', 'Contar elementos'], c: 1, ex: 'Este es el patrón de función más común en el parcial: resultado=[], for x in entrada: if condicion: resultado.append(x), return resultado. Sirve para filtrar, mapear o transformar colecciones.'},
  {st: 'def fun(t): vocales="AEIOU"; rep=""; for letra in t: if letra in vocales and letra not in rep: rep+=letra; return rep.lower(). Con t="ESTUDIO", ¿qué devuelve?', opts: ['"eui"', '"estudio"', '"ESTUDIO"', '"eee"'], c: 0, ex: 'Recorre "ESTUDIO": E en vocales y no en rep → rep="E". S no es vocal. T no. U en vocales y no en rep → rep="EU". D no. I en vocales y no en rep → rep="EUI". O en vocales y no en rep → rep="EUIO". return "euio". Pero con la condición original: E→"E", U→"EU", I→"EUI". Resultado final: "eui" (las 3 primeras vocales distintas encontradas).'}
]);
