// ============================================================
// FÍSICA · FINAL TORTI · Guía intensiva (19 finales reales 2023-2026)
// Ejercicios autocorregibles anclados a los números reales de las
// claves de corrección oficiales. Cada explicación es un walkthrough:
//   identificar tipo → fórmula que dispara → resolución paso a paso →
//   por qué las otras opciones están mal.
// ============================================================

// SECCIÓN 1 · ESTRATEGIA Y FORMATO DEL FINAL
registerExercises('fisica-final', '1', [
  {st: '¿Cómo es el examen final de Física (Cátedra Torti)?', opts: ['3 a 5 ejercicios de desarrollo con incisos, 90 minutos, 3 cifras significativas y g = 9,80 m/s²', 'Multiple choice de 10 ítems', 'Desarrollo libre sin formato ni hoja de fórmulas', 'Solo teoría (verdadero/falso)'], c: 0, ex: 'El final es de <b>desarrollo</b> (no multiple choice): 3 a 5 ejercicios con incisos a/b/c, 90 min, resultados con <b>3 cifras significativas y unidades</b>, asumiendo g = 9,80 m/s². → Trae una hoja de fórmulas oficial al pie. → Casi siempre pide un DCL. → Las otras: (B) no es multiple choice, se desarrolla y se muestra el planteo; (C) sí hay hoja de fórmulas; (D) hay cuentas, no solo teoría.'},
  {st: 'Cada fecha del final se toma en Tema 1 y Tema 2. ¿Qué relación tienen?', opts: ['Son temas de materias distintas', 'El Tema 2 es más difícil', 'Es el MISMO problema con distintos números (misma configuración e incisos)', 'No tienen relación'], c: 2, ex: 'Tema 1 y Tema 2 de una misma fecha son <b>el mismo problema con distintos valores</b>: misma escena, mismos incisos, misma fórmula. → Por eso conviene estudiar por <b>familias de problemas</b> (la lámpara, la bala al blanco, el trineo) y no por fechas sueltas. → Dominar una familia cubre las dos versiones y sus reapariciones. → Por qué las otras están mal: (A) los dos temas son de Física y de la misma fecha; (B) ninguno es más difícil: cambian los números, no el planteo; (D) sí tienen relación: comparten la escena, los incisos y las fórmulas.'},
  {st: 'Según los 19 finales analizados, ¿cuál es el tema que MÁS aparece?', opts: ['Movimiento circular', 'Vectores puros', 'Calorimetría', 'Tiro oblicuo / cinemática 2D (68%, 13 de 19)'], c: 3, ex: 'El <b>tiro oblicuo</b> es el tema estrella: 13 de 19 finales (68%). → Le siguen estática e hidrostática (58% cada uno) y trabajo-energía con roce (53%). → Esos cuatro juntan cerca del 70% de lo que cae (45 de las 65 apariciones del ranking). → Circular y calorimetría casi no caen en estos finales. → Por qué las otras están mal: (A) el movimiento circular está en la hoja de fórmulas, pero no figura en el ranking de los 19 finales; (B) los vectores no arman un ejercicio solos: se usan dentro de estática y de tiro oblicuo; (C) calorimetría no figura en el ranking.'},
  {st: 'Un cuerpo se mueve a 90,0 km/h. Antes de usar el dato en una fórmula de energía, ¿qué hacés?', opts: ['Lo uso así', 'Lo paso a m/s dividiendo por 3,6 → 25,0 m/s', 'Lo multiplico por 3,6', 'Lo paso a km/s'], c: 1, ex: 'Las fórmulas trabajan en SI. → <b>km/h ÷ 3,6 = m/s</b>: 90,0/3,6 = <b>25,0 m/s</b>. → No convertir es el error nº1 del final (te cambia la tercera cifra o más). → (C) multiplicar por 3,6 da 324, un disparate; (D) km/s no es SI. → Además: (A) con 90,0 sin convertir, la energía cinética sale 12,96 veces más grande (3,6²).'},
  {st: 'En la hoja de fórmulas figura "E = V_CS · δ_L · g". ¿Qué representa?', opts: ['Energía cinética', 'La energía potencial', 'El empuje de Arquímedes (V_CS = volumen del cuerpo sumergido, δ_L = densidad del líquido)', 'El peso'], c: 2, ex: 'Es el <b>empuje</b> (flotación): E = V<sub>CS</sub>·δ<sub>L</sub>·g, con V<sub>CS</sub> el volumen del cuerpo sumergido y δ<sub>L</sub> la densidad del líquido. → Vertical hacia arriba, igual al peso del fluido desalojado. → (A) E_c = ½mv²; (B) E_p = mgh; (D) Peso = mg (fórmulas aparte en la hoja).'},
  {st: 'Un problema pide "la tensión de la cuerda" en un cuerpo en reposo. ¿Newton o Energía?', opts: ['Newton: es estática, planteo ΣFx = 0 y ΣFy = 0', 'Energía (conservación)', 'Da igual', 'Cinemática'], c: 0, ex: 'Fuerza, tensión, aceleración o normal → <b>Newton</b>. → En reposo es <b>estática</b>: ΣF<sub>x</sub> = 0 y ΣF<sub>y</sub> = 0 (y ΣM = 0 si es cuerpo extenso). → Energía se usa cuando piden rapidez, altura, compresión o distancia con rozamiento. → Por qué las otras están mal: (B) la energía sirve para rapideces, alturas o compresiones, y acá nada se mueve; (C) no da igual: una tensión es una fuerza y sale de sumar fuerzas; (D) en reposo no hay movimiento que describir.'}
]);

// SECCIÓN 2 · TIRO OBLICUO / CINEMÁTICA 2D
registerExercises('fisica-final', '2', [
  {st: 'Una tiradora apunta HORIZONTALMENTE al centro de un blanco a 50,0 m; el proyectil sale a 340 m/s. ¿A qué distancia por debajo del centro impacta? (g = 9,80 m/s²)', opts: ['5,30 cm', '10,6 cm', '25,0 cm', '1,06 m'], c: 1, ex: 'Tiro horizontal: v<sub>0y</sub> = 0. → <b>Tiempo</b> (lo da la horizontal): t = 50,0/340 = 0,147059 s. → <b>Caída</b>: Δy = ½·g·t² = ½·9,80·0,147059² = <b>0,106 m = 10,6 cm</b>. → La velocidad horizontal fija el tiempo de vuelo, y el tiempo fija cuánto cae. → (A) es la mitad de la correcta; (C) no sale de los datos; (D) corre la coma (0,106 m no es 1,06 m).'},
  {st: 'Misma tiradora pero con munición más lenta: 280 m/s al mismo blanco de 50,0 m. ¿Cae más o menos que con 340 m/s, y cuánto?', opts: ['Menos: 8,75 cm', 'Igual: 10,6 cm', 'Más: 30,0 cm', 'Más: 15,6 cm'], c: 3, ex: 'Más lenta → tarda MÁS en llegar → cae MÁS. → t = 50,0/280 = 0,178571 s. → Δy = ½·9,80·0,178571² = <b>0,156 m = 15,6 cm</b>. → Contraintuitivo pero clave: menor velocidad de disparo = mayor caída (más tiempo de vuelo). Es la variante real Feb 2025 T2. → Por qué las otras están mal: (A) va al revés: menos velocidad es más tiempo de vuelo y más caída; (B) 10,6 cm es la caída con 340 m/s: si cambia el tiempo, cambia la caída; (C) acierta el sentido pero no el valor: ni olvidando el ½ da 30,0 cm (daría 31,3 cm).'},
  {st: 'Se arroja una pelota horizontalmente desde H = 6,00 m y cae a L = 8,00 m de la base. ¿Con qué rapidez fue lanzada? (g = 9,80 m/s²)', opts: ['13,0 m/s', '4,00 m/s', '10,8 m/s', '7,23 m/s'], c: 3, ex: '<b>1) Tiempo de caída</b> (v<sub>0y</sub> = 0): t = √(2H/g) = √(2·6,00/9,80) = 1,107 s. → <b>2) Rapidez horizontal</b>: v<sub>0</sub> = L/t = 8,00/1,107 = <b>7,23 m/s</b>. → (A) 13,0 m/s es la rapidez al TOCAR el suelo; (C) 10,8 corresponde a L = 12,0 m (Tema 2). → Además: (B) 4,00 m/s es L/2: no usa la altura ni g, y equivale a un vuelo de 2,00 s cuando desde 6,00 m se cae en 1,11 s.'},
  {st: 'Para esa misma pelota (H = 6,00 m, L = 8,00 m), ¿con qué rapidez y ángulo llega al suelo?', opts: ['7,23 m/s a 0°', '13,0 m/s a 56,3° bajo la horizontal', '10,8 m/s a 45°', '23,2 m/s a 30°'], c: 1, ex: '<b>v<sub>x</sub> = 7,23 m/s</b> (constante). → <b>v<sub>y</sub> = g·t</b> = 9,80·1,107 = 10,85 m/s. → Rapidez = √(7,23² + 10,85²) = <b>13,0 m/s</b>. → Ángulo = arctg(10,85/7,23) = <b>56,3°</b> bajo la horizontal. → (A) es solo el lanzamiento; (C) mezcla dos números del caso L = 12,0 m: 10,8 m/s es la rapidez de lanzamiento y 45° el ángulo de llegada, pero ahí la rapidez de llegada es 15,3 m/s; (D) no sale de los datos.'},
  {st: 'Desde el suelo se patea una pelota que rompe un vidrio a 6,50 m de alto y 25,0 m de distancia, tras un vuelo de 1,15 s. ¿Con qué rapidez fue pateada? (g = 9,80 m/s²)', opts: ['24,5 m/s', '21,7 m/s', '11,3 m/s', '27,4 m/s'], c: 0, ex: '<b>1) Horizontal</b>: v<sub>0x</sub> = 25,0/1,15 = 21,74 m/s. → <b>2) Vertical</b>: v<sub>0y</sub> = (y + ½·g·t²)/t = (6,50 + ½·9,80·1,15²)/1,15 = 11,29 m/s. → <b>3)</b> v<sub>0</sub> = √(21,74² + 11,29²) = √600 = <b>24,5 m/s</b>. → (B) es solo v<sub>0x</sub>; (C) es solo v<sub>0y</sub>; (D) 27,4 es el ÁNGULO en grados, no la rapidez.'},
  {st: 'En ese pateo (v0x = 21,74, v0y = 11,29 m/s), ¿con qué ángulo respecto de la horizontal salió la pelota?', opts: ['62,6°', '45,0°', '27,4°', '11,3°'], c: 2, ex: 'θ = arctg(v<sub>0y</sub>/v<sub>0x</sub>) = arctg(11,29/21,74) = arctg(0,5192) = <b>27,4°</b>. → (A) 62,6° es el complementario (arctg de v<sub>0x</sub>/v<sub>0y</sub>, error clásico de invertir); (B) sería si v<sub>0x</sub> = v<sub>0y</sub>. → Además: (D) 11,3 es v<sub>0y</sub> en m/s (11,29), no un ángulo.'},
  {st: 'Desde 2,00 m se arroja una pelota a 40,0 km/h con 70,0° sobre la horizontal. ¿Altura máxima respecto del suelo? (g = 9,80 m/s²)', opts: ['5,56 m', '7,56 m', '2,00 m', '11,1 m'], c: 1, ex: '<b>0) A SI:</b> 40,0/3,6 = 11,11 m/s. → <b>v<sub>0y</sub></b> = 11,11·sen70° = 10,44 m/s. → <b>h<sub>máx</sub> = h₀ + v<sub>0y</sub>²/(2g)</b> = 2,00 + 10,44²/19,6 = 2,00 + 5,56 = <b>7,56 m</b>. → (A) olvida sumar los 2,00 m iniciales; (D) 11,1 es la rapidez inicial en m/s (40,0/3,6), no una altura. → Además: (C) 2,00 m es la altura de lanzamiento: como sale hacia arriba, la máxima tiene que ser mayor.'},
  {st: 'En un tiro oblicuo, ¿qué le pasa a la componente HORIZONTAL de la velocidad durante el vuelo (sin rozamiento)?', opts: ['Aumenta por la gravedad', 'Disminuye hasta cero en el punto más alto', 'Cambia de signo', 'Se mantiene constante'], c: 3, ex: 'La gravedad es <b>vertical</b>: no afecta la horizontal. → v<sub>x</sub> = v₀·cos(θ) es <b>constante todo el vuelo</b> (MRU en x). → Lo que vale 0 en el punto más alto es v<sub>y</sub> (la vertical), no la horizontal. → Este hecho es el que permite sacar el tiempo del alcance o de la altura. → Por qué las otras están mal: (A) la gravedad no tiene componente horizontal, no puede cambiar v<sub>x</sub>; (B) la que se anula arriba es v<sub>y</sub>; (C) la que cambia de signo (sube y después baja) es v<sub>y</sub>.'}
]);

// SECCIÓN 3 · ESTÁTICA
registerExercises('fisica-final', '3', [
  {st: 'Lámpara de 5,00 kg colgada de dos cuerdas: la izquierda a 30,0° y la derecha a 45,0° con la horizontal. ¿Tensión en la cuerda derecha? (g = 9,80 m/s²)', opts: ['35,9 N', '49,0 N', '43,9 N', '25,0 N'], c: 2, ex: '<b>Horizontal:</b> T<sub>i</sub>·cos30° = T<sub>d</sub>·cos45° → T<sub>i</sub> = 0,8165·T<sub>d</sub>. → <b>Vertical:</b> T<sub>i</sub>·sen30° + T<sub>d</sub>·sen45° = 5,00·9,80 = 49,0. Sustituyo: T<sub>d</sub>·(0,8165·0,5 + 0,7071) = 49,0 → T<sub>d</sub>·1,1153 = 49,0 → <b>T<sub>d</sub> = 43,9 N</b>. → (A) es la izquierda; (B) es el peso total. → Además: (D) 25,0 N no sale con g = 9,80: repartir el peso en partes iguales daría 24,5 N (25,0 solo con g = 10), y además las cuerdas no cargan lo mismo porque los ángulos son distintos.'},
  {st: 'Misma lámpara (5,00 kg, 30° y 45°): la cuerda soporta 100 N como máximo. ¿Masa máxima de la lámpara?', opts: ['11,4 kg', '5,00 kg', '10,2 kg', '20,4 kg'], c: 0, ex: 'La cuerda MÁS tensionada es la derecha (43,9 N &gt; 35,9 N). → Como la tensión es proporcional al peso: m<sub>máx</sub> = m·(T<sub>máx</sub>/T<sub>der</sub>) = 5,00·(100/43,9) = <b>11,4 kg</b>. → (C) 10,2 kg es 100/9,80: supone que una sola cuerda vertical sostiene todo el peso. → Además: (B) 5,00 kg es la masa actual: con ella la cuerda más exigida está en 43,9 N, lejos de los 100 N; (D) 20,4 kg es 200/9,80: supone que las dos cuerdas tiran 100 N cada una y en vertical.'},
  {st: 'Slackline: los tramos de cuerda forman 50,0° (izq) y 30,0° (der) con la horizontal. Si la tensión izquierda es 700 N, ¿masa de la persona? (g = 9,80 m/s²)', opts: ['81,2 kg', '71,4 kg', '53,0 kg', '142 kg'], c: 0, ex: '<b>Horizontal:</b> T<sub>der</sub> = 700·cos50°/cos30° = 519,6 N. → <b>Vertical:</b> m·g = 700·sen50° + 519,6·sen30° = 536,2 + 259,8 = 796,0 N. → m = 796,0/9,80 = <b>81,2 kg</b>. → (D) 142 kg no sale de los datos (sumar las dos tensiones sin descomponer daría 124 kg). → Además: (B) 71,4 kg es 700/9,80: toma la tensión izquierda como si fuera el peso; (C) 53,0 kg es 519,6/9,80: toma la tensión derecha como si fuera el peso.'},
  {st: 'Una bola de demolición de 1800 kg cuelga de un cable horizontal (2) y otro (1) a 15,0° de la VERTICAL. ¿Tensión en el cable inclinado (1)? (g = 9,80 m/s²)', opts: ['1,76·10⁴ N', '4,73·10³ N', '1,83·10⁴ N', '1,80·10⁴ N'], c: 2, ex: 'El cable horizontal no sostiene peso: la vertical la aguanta solo el inclinado. → <b>Vertical:</b> T₁·cos15° = m·g → T₁ = 1800·9,80/cos15° = 17640/0,9659 = <b>1,83·10⁴ N</b>. → (A) 1,76·10⁴ N es el peso (17640 N): olvida dividir por cos15°; (B) 4,73·10³ N es el cable horizontal (T₂ = T₁·sen15°); (D) 1,80·10⁴ N es el peso con g = 10 (1800·10), y tampoco divide por el coseno.'},
  {st: 'Un guinche sostiene un motor de 325 kg: el pistón actúa en B (AB = 0,350 m) y el motor cuelga en C (AC = 1,50 m), pivote en A. ¿Fuerza del pistón? (g = 9,80 m/s²)', opts: ['3,19·10³ N', '4,78·10³ N', '9,55·10³ N', '1,37·10⁴ N'], c: 3, ex: 'Equilibrio de momentos respecto de A: <b>F<sub>pistón</sub>·0,350 = P·1,50</b>, con P = 325·9,80 = 3185 N. → F<sub>pistón</sub> = 3185·1,50/0,350 = <b>1,37·10⁴ N</b>. → La palanca multiplica: como el brazo del pistón es corto, necesita mucha fuerza. → (A) es el peso del motor sin la palanca. → Además: (B) 4,78·10³ es el momento del peso (3185·1,50 = 4777,5 N·m): falta dividir por el brazo del pistón; (C) 9,55·10³ N no sale de los datos (es el doble de la (B)).'},
  {st: 'Una persona sostiene una caja de 12,0 kg contra una pared empujando horizontalmente; μe = 0,650 con la pared. ¿Fuerza horizontal mínima para que no caiga? (g = 9,80 m/s²)', opts: ['76,4 N', '181 N', '118 N', '12,0 N'], c: 1, ex: 'La normal de la pared vale lo mismo que la fuerza aplicada (equilibrio horizontal). → El rozamiento estático máximo debe igualar al peso: μ<sub>e</sub>·F = m·g. → <b>F<sub>mín</sub> = m·g/μ<sub>e</sub></b> = 12,0·9,80/0,650 = <b>181 N</b>. → (A) multiplica por μ en vez de dividir; (C) usa el peso sin μ. → Además: (D) 12,0 es la masa en kg, no una fuerza.'},
  {st: 'Para tomar momentos en un cuerpo extenso y que una incógnita desaparezca de la ecuación, ¿dónde conviene poner el eje de giro?', opts: ['En el centro de gravedad', 'Siempre en el extremo derecho', 'En el punto donde actúa una fuerza desconocida (su brazo es 0)', 'Donde actúa el peso'], c: 2, ex: 'El momento de una fuerza es F·brazo. → Si ponés el eje <b>donde actúa una incógnita</b>, su brazo es 0 y su momento desaparece: te queda una ecuación con menos incógnitas. → Por eso en el guinche se toma el pivote A (elimina las fuerzas de vínculo). → Por qué las otras están mal: (A) y (D) son el mismo punto: ahí se anula el momento del peso, que es un dato y no una incógnita; (B) el extremo derecho solo conviene si justo ahí actúa una incógnita.'}
]);

// SECCIÓN 4 · HIDROSTÁTICA
registerExercises('fisica-final', '4', [
  {st: 'Para levantar un cañón de 2400 kg del fondo del mar (δ = 1,030 g/cm³) se usa una bolsa de aire. ¿Volumen mínimo de la bolsa? (g = 9,80 m/s²)', opts: ['2,33·10³ L', '2,47·10³ L', '2,40·10³ L', '2,33·10⁶ L'], c: 0, ex: 'Para levantarlo, empuje ≥ peso: V·δ<sub>mar</sub>·g = m·g → <b>V = m/δ<sub>mar</sub></b> = 2400/1030 = 2,33 m³ = <b>2,33·10³ L</b> (1 m³ = 1000 L). → La g se cancela. → (D) confunde m³ con L por 10³ de más. → Además: (B) 2,47·10³ multiplica por la densidad en vez de dividir (2400·1,030 = 2472); (C) 2,40·10³ L usa la densidad del agua dulce (1000 kg/m³) en vez de la del mar.'},
  {st: 'Ese cañón está a 30,0 m de profundidad. ¿Cuánto mayor es la presión ahí respecto de la superficie? (δ = 1030 kg/m³, g = 9,80 m/s²)', opts: ['1,01·10⁵ Pa', '3,03·10⁵ Pa', '4,04·10⁵ Pa', '3,03·10³ Pa'], c: 1, ex: 'Sobrepresión hidrostática: <b>ΔP = δ·g·h</b> = 1030·9,80·30,0 = <b>3,03·10⁵ Pa</b>. → Es solo la columna de agua (no se suma la atmósfera porque piden la DIFERENCIA respecto de la superficie). → (A) es ~1 atmósfera, no corresponde. → Además: (C) 4,04·10⁵ Pa le suma la atmósfera (3,03·10⁵ + 1,01·10⁵): es la presión absoluta, y piden la diferencia; (D) tiene dos órdenes de magnitud de menos y no sale de los datos (dejando la densidad en g/cm³ daría 303 Pa).'},
  {st: 'Un cuerpo de 0,280 kg pesa aparentemente 1,86 N sumergido en agua. ¿Cuál es su densidad? (δ_agua = 1000 kg/m³, g = 9,80 m/s²)', opts: ['1,00 g/cm³', '2,74 g/cm³', '0,884 g/cm³', '3,10 g/cm³'], c: 3, ex: '<b>Empuje</b> = P<sub>real</sub> − P<sub>ap</sub> = 0,280·9,80 − 1,86 = 0,884 N. → <b>Volumen</b> = E/(δ<sub>agua</sub>·g) = 0,884/9800 = 9,02·10⁻⁵ m³. → <b>Densidad</b> = m/V = 0,280/9,02·10⁻⁵ = 3104 kg/m³ = <b>3,10 g/cm³</b>. → (C) es el empuje en N, no una densidad. → Además: (A) 1,00 g/cm³ es la densidad del agua: si fuera la del cuerpo, el peso aparente sería 0; (B) 2,74 es el peso real en N (0,280·9,80 = 2,744), no una densidad.'},
  {st: 'Una pesa de hierro de 2,00 kg (δ = 7,87 g/cm³) cuelga de un resorte. ¿Cuál es su volumen?', opts: ['1,57·10⁴ m³', '2,54·10⁻² m³', '0,254 m³', '2,54·10⁻⁴ m³'], c: 3, ex: 'V = m/δ = 2,00/7870 kg/m³ (pasando 7,87 g/cm³ × 1000) = <b>2,54·10⁻⁴ m³</b>. → Es un volumen chico (254 cm³), coherente con un metal denso. → (B) y (C) tienen la coma corrida. → Además: (A) 1,57·10⁴ multiplica en vez de dividir (2,00·7870 = 15740).'},
  {st: 'Un gato hidráulico tiene el pistón grande de 0,120 m de diámetro sosteniendo 700 kg. ¿Qué presión tiene el fluido? (g = 9,80 m/s²)', opts: ['7,35·10³ Pa', '6,07·10⁵ Pa', '3,03·10⁵ Pa', '6,07·10⁶ Pa'], c: 1, ex: 'p = F/A con A = π·r² = π·0,0600² = 0,011310 m². → F = 700·9,80 = 6860 N. → p = 6860/0,011310 = <b>6,07·10⁵ Pa</b>. → (A) 7,35·10³ no sale de estos datos (dividir por el diámetro sin elevar al cuadrado daría 5,72·10⁴ Pa); (D) tiene un orden de magnitud de más. → Además: (C) 3,03·10⁵ Pa es la mitad de la correcta y no sale de los datos.'},
  {st: 'Dos peces sumergidos en la misma pecera: Dory (grande) a 0,450 m y Nemo (chico) a 0,150 m. ¿Cuál recibe MÁS empuje?', opts: ['Dory, porque tiene mayor volumen', 'Nemo, porque está más arriba', 'Reciben igual empuje', 'Depende de la presión atmosférica'], c: 0, ex: 'Empuje = δ<sub>fluido</sub>·V<sub>sumergido</sub>·g. A igual fluido, <b>manda el volumen</b>: Dory es más grande → <b>más empuje</b>. → La profundidad NO cambia el empuje de un cuerpo totalmente sumergido (sí cambia la presión). → Ambos, en equilibrio y totalmente sumergidos, tienen la densidad del agua. → Por qué las otras están mal: (B) estar más arriba cambia la presión, no el empuje; (C) sería cierto solo si tuvieran el mismo volumen; (D) la presión atmosférica actúa igual sobre los dos y no entra en el empuje.'},
  {st: 'Para esos peces (δ = 1,020 g/cm³), ¿cuál es la diferencia de presión entre las profundidades 0,450 m y 0,150 m? (g = 9,80 m/s²)', opts: ['4,50·10³ Pa', '1,50·10³ Pa', '3,00·10³ Pa', '6,00·10³ Pa'], c: 2, ex: 'ΔP = δ·g·Δh = 1020·9,80·(0,450 − 0,150) = 1020·9,80·0,300 = <b>3,00·10³ Pa</b>. → Solo cuenta la diferencia de altura Δh; la presión atmosférica es la misma para ambos y se cancela. → Por qué las otras están mal: (A) 4,50·10³ Pa es δ·g·h solo con la profundidad de Dory (0,450 m); (B) 1,50·10³ Pa, solo con la de Nemo (0,150 m); (D) 6,00·10³ Pa suma las profundidades (0,600 m) en vez de restarlas.'}
]);

// SECCIÓN 5 · TRABAJO, ENERGÍA Y POTENCIA CON ROZAMIENTO
registerExercises('fisica-final', '5', [
  {st: 'Una caja de 240 g lanzada a 0,550 m/s sobre una superficie con μd = 0,325. ¿Qué distancia recorre hasta frenar? (g = 9,80 m/s²)', opts: ['0,0950 m', '0,0475 m', '0,0237 m', '0,550 m'], c: 1, ex: '<b>F<sub>roz</sub></b> = μ<sub>d</sub>·m·g = 0,325·0,240·9,80 = 0,764 N. → <b>E<sub>c</sub></b> = ½·m·v² = ½·0,240·0,550² = 0,0363 J. → Todo E<sub>c</sub> lo disipa el roce: <b>d = E<sub>c</sub>/F<sub>roz</sub></b> = 0,0363/0,764 = <b>0,0475 m</b>. → (A) olvida el ½ de la energía cinética; (C) es la mitad de la correcta. → Además: (D) 0,550 es el valor de la rapidez inicial, no una distancia.'},
  {st: 'Un resorte lanza un bloque de 10,0 kg que pasa por p a 5,00 m/s, cruza 1,25 m de madera y llega a q a 4,00 m/s. ¿Coeficiente de rozamiento dinámico? (g = 9,80 m/s²)', opts: ['0,180', '0,367', '0,500', '0,735'], c: 1, ex: '<b>Trabajo del roce</b> = ΔE<sub>c</sub> = ½·10·4,00² − ½·10·5,00² = 80,0 − 125 = −45,0 J. → F<sub>roz</sub> = 45,0/1,25 = 36,0 N. → <b>μ<sub>d</sub></b> = F<sub>roz</sub>/(m·g) = 36,0/98,0 = <b>0,367</b>. → (D) 0,735 es el doble: sale de olvidar el ½ de la energía cinética (ΔE = 90,0 J → F = 72,0 N); (A) 0,180 y (C) 0,500 no salen de los datos (con una sola velocidad daría 1,02 o 0,653).'},
  {st: 'Para ese mismo bloque, ¿cuánto estaba comprimido el resorte (k = 4,00·10⁴ N/m) si el bloque pasa por p a 5,00 m/s sin roce antes de p?', opts: ['3,95 cm', '12,5 cm', '7,91 cm', '5,00 cm'], c: 2, ex: 'Sin roce hasta p, la energía elástica = E<sub>c</sub> en p: ½·k·x² = ½·m·v<sub>p</sub>². → x = v<sub>p</sub>·√(m/k) = 5,00·√(10,0/40000) = 5,00·0,015811 = <b>0,0791 m = 7,91 cm</b>. → (A) es la mitad de la correcta; (B) 12,5 cm no sale de los datos (haría falta k = 1,60·10⁴ N/m); (D) 5,00 es el valor de la rapidez, no una compresión.'},
  {st: 'Un carrito de 200 kg parte del reposo desde H₁ = 12,0 m. ¿Con qué rapidez llega al punto a (antes del tramo rugoso)? (g = 9,80 m/s²)', opts: ['15,3 m/s', '10,8 m/s', '21,7 m/s', '120 m/s'], c: 0, ex: 'Hasta a no hay roce → conservación pura: m·g·H₁ = ½·m·v² → <b>v = √(2·g·H₁)</b> = √(2·9,80·12,0) = √235,2 = <b>15,3 m/s</b>. → La masa se cancela. → (B) olvida el 2: √(g·H₁) = 10,8 m/s; (D) 120 no sale de los datos: g·H₁ vale 117,6 y además le faltaría la raíz. → Además: (C) 21,7 m/s es √(4·g·H₁): duplica de más (equivale a caer desde 24,0 m).'},
  {st: 'Ese carrito cruza 5,00 m de tramo rugoso (μd = 0,185) y llega a c (H₂ = 2,50 m). ¿Rapidez en c? (m = 200 kg, g = 9,80 m/s²)', opts: ['13,0 m/s', '15,3 m/s', '9,90 m/s', '16,8 m/s'], c: 0, ex: 'W<sub>roz</sub> = −μ<sub>d</sub>·m·g·L = −0,185·200·9,80·5,00 = −1813 J. → E<sub>m,c</sub> = m·g·H₁ + W<sub>roz</sub> = 23520 − 1813 = 21707 J. → E<sub>c,c</sub> = E<sub>m,c</sub> − m·g·H₂ = 21707 − 4900 = 16807 J. → v<sub>c</sub> = √(2·16807/200) = <b>13,0 m/s</b>. → (B) ignora roce y desnivel. → Además: (C) 9,90 m/s es √(2·g·5,00): usa el largo del tramo rugoso como si fuera una altura; (D) 16,8 son las cifras de la energía cinética en c (16807 J), no una rapidez. Si solo ignorás el roce da 13,6 m/s.'},
  {st: 'Una moto (con conductor, 350 kg) baja de 130 km/h a 40,0 km/h en 4,00 s. ¿Potencia de frenado? (g = 9,80 m/s²)', opts: ['2,58·10⁴ W', '1,29·10⁵ W', '5,16·10⁴ W', '5,16·10³ W'], c: 2, ex: '<b>A SI:</b> 130/3,6 = 36,11 m/s; 40,0/3,6 = 11,11 m/s. → <b>Pot</b> = |½·m·(v<sub>f</sub>² − v<sub>i</sub>²)|/t = |½·350·(11,11² − 36,11²)|/4,00 = 206600/4,00 = <b>5,16·10⁴ W</b>. → (A) es la mitad de la correcta; (D) tiene un orden de magnitud de menos. → Además: (B) 1,29·10⁵ W es 2,5 veces la correcta y no sale de los datos (olvidar el ½ daría 1,03·10⁵ W).'},
  {st: 'Se arrastra una caja fuerte (500 kg, μe = 0,400) con una soga que tiene un resorte de k = 3,50·10⁴ N/m. ¿Cuánto se estira el resorte justo antes de que la caja arranque? (g = 9,80 m/s²)', opts: ['0,0280 m', '0,140 m', '0,400 m', '0,0560 m'], c: 3, ex: 'En el umbral, la fuerza elástica iguala al rozamiento estático máximo: k·Δx = μ<sub>e</sub>·m·g. → Δx = μ<sub>e</sub>·m·g/k = 0,400·500·9,80/35000 = 1960/35000 = <b>0,0560 m</b>. → (A) es la mitad de la correcta; (B) 0,140 m sale de olvidar μ<sub>e</sub> (m·g/k = 4900/35000); (C) 0,400 es el valor de μ<sub>e</sub>, no una longitud.'}
]);

// SECCIÓN 6 · ENERGÍA / CONSERVACIÓN CON RESORTE
registerExercises('fisica-final', '6', [
  {st: 'Un resorte impulsa un carrito de 10,0 kg que sube sin roce y pasa por p (1,50 m de altura) a 45,0 km/h. ¿Con qué rapidez dejó el resorte (en la base)? (g = 9,80 m/s²)', opts: ['12,5 m/s', '13,6 m/s', '15,0 m/s', '17,3 m/s'], c: 1, ex: '<b>A SI:</b> 45,0/3,6 = 12,5 m/s. → Conservación: la energía en la base (toda cinética) = energía en p (cinética + potencial): ½·v<sub>base</sub>² = ½·v<sub>p</sub>² + g·h. → v<sub>base</sub> = √(v<sub>p</sub>² + 2·g·h) = √(12,5² + 2·9,80·1,50) = √185,65 = <b>13,6 m/s</b>. → (A) es la rapidez EN p, ya subida; falta sumar la energía potencial. → Además: (C) y (D) no salen de los datos: para pasar por p a 12,5 m/s saliendo a 15,0 m/s, p tendría que estar a 3,51 m, y saliendo a 17,3 m/s, a 7,30 m.'},
  {st: 'Para ese carrito (E_mec = 928 J, k = 5,50·10⁵ N/m), ¿cuánto estaba comprimido el resorte?', opts: ['2,90 cm', '11,6 cm', '5,81 cm', '8,20 cm'], c: 2, ex: 'La energía elástica del resorte = energía mecánica del carrito: ½·k·x² = E<sub>mec</sub>. → x = √(2·E<sub>mec</sub>/k) = √(2·928,25/5,50·10⁵) = √0,003375 = <b>0,0581 m = 5,81 cm</b>. → (A) usa la mitad; (B) duplica. → Además: (D) 8,20 cm no sale de los datos: equivale a 1,85·10³ J de energía elástica, el doble de la que hay.'},
  {st: 'Un bebé de 9,50 kg se sienta en un "saltarín" y el resorte se estira de 20,0 cm a 32,8 cm. ¿Constante elástica? (g = 9,80 m/s²)', opts: ['727 N/m', '466 N/m', '93,1 N/m', '285 N/m'], c: 0, ex: 'En equilibrio la fuerza elástica iguala al peso: k·Δl = m·g. → Δl = 0,328 − 0,200 = 0,128 m. → k = m·g/Δl = 9,50·9,80/0,128 = 93,1/0,128 = <b>727 N/m</b>. → (C) 93,1 N es el peso (no la constante); (B) divide por la longitud inicial (0,200 m) en vez de por el estiramiento; (D) 285 N/m no sale de los datos (dividir por la longitud final daría 284 N/m).'},
  {st: 'Para ese mismo resorte (k = 727 N/m, estiramiento 0,128 m), ¿cuánta energía potencial elástica se acumuló?', opts: ['11,9 J', '5,96 J', '2,98 J', '46,5 J'], c: 1, ex: 'E<sub>p elástica</sub> = ½·k·Δl² = ½·727·0,128² = ½·727·0,016384 = <b>5,96 J</b>. → (A) olvida el ½; (D) usa Δl sin elevar al cuadrado. → Además: (C) 2,98 J es la mitad: aplica el ½ dos veces.'},
  {st: 'En conservación de energía con un resorte (sin rozamiento), ¿qué se conserva?', opts: ['Solo la energía cinética', 'Solo la energía potencial', 'La fuerza', 'La energía mecánica total (cinética + potencial + elástica)'], c: 3, ex: 'Sin fuerzas no conservativas (sin roce), se conserva la <b>energía mecánica total</b>: la elástica se transforma en cinética y potencial, y la suma queda constante. → Si hubiera rozamiento, parte de esa energía se disiparía (ahí ya no se conserva y hay que usar W<sub>roz</sub> = ΔE<sub>m</sub>). → Por qué las otras están mal: (A) y (B) cada una por separado cambia: una crece cuando la otra baja; (C) la fuerza del resorte cambia con el estiramiento, y además no es una energía.'}
]);

// SECCIÓN 7 · DINÁMICA DE NEWTON CON SISTEMAS
registerExercises('fisica-final', '7', [
  {st: 'Tres vagones de 1235 kg cada uno, unidos y sin roce, partiendo del reposo; se tira con 3500 N. ¿Aceleración del conjunto? (g = 9,80 m/s²)', opts: ['2,83 m/s²', '0,315 m/s²', '1,42 m/s²', '0,945 m/s²'], c: 3, ex: 'El conjunto acelera con a = F/m<sub>total</sub> = 3500/(3·1235) = 3500/3705 = <b>0,945 m/s²</b>. → Toda la masa se mueve junta bajo la única fuerza externa. → (A) usa la masa de un solo vagón. → Además: (B) 0,315 m/s² divide dos veces por 3 (0,945/3); (C) 1,42 m/s² cuenta dos vagones (3500/2470).'},
  {st: 'Para ese tren (a = 0,945 m/s²), ¿cuál es la tensión de la cuerda entre los vagones B y C (esa cuerda arrastra solo al vagón C)?', opts: ['3500 N', '1,17·10³ N', '2,33·10³ N', '1166 kg'], c: 1, ex: 'La tensión de una cuerda es la fuerza que necesita para mover lo que queda delante de ella. La cuerda B-C solo arrastra al vagón C: T = m·a = 1235·0,945 = <b>1,17·10³ N</b>. → (A) es la fuerza aplicada al tren entero; (D) confunde N con kg. → Además: (C) 2,33·10³ N es la tensión de la cuerda A-B, que arrastra dos vagones (2·1235·0,945).'},
  {st: 'Máquina de Atwood: bloques de 20,0 kg y 23,5 kg por una polea ideal. ¿Aceleración del sistema? (g = 9,80 m/s²)', opts: ['0,789 m/s²', '9,80 m/s²', '1,58 m/s²', '0,394 m/s²'], c: 0, ex: 'a = (m<sub>B</sub> − m<sub>A</sub>)·g/(m<sub>A</sub> + m<sub>B</sub>) = (23,5 − 20,0)·9,80/(43,5) = 34,3/43,5 = <b>0,789 m/s²</b>. → La diferencia de pesos impulsa; la masa total resiste. → (B) sería caída libre (sin la otra masa). → Además: (C) 1,58 m/s² es el doble y (D) 0,394 m/s² es la mitad de la correcta; ninguna sale de los datos (dividir por una sola masa daría 1,72 o 1,46 m/s²).'},
  {st: 'En ese Atwood, cuando el bloque pesado toca el piso queda el otro (20,0 kg) colgado en reposo. ¿Tensión de la cuerda entonces? (g = 9,80 m/s²)', opts: ['230 N', '0 N', '196 N', '426 N'], c: 2, ex: 'Con un solo bloque colgando en reposo, la cuerda solo aguanta su peso: T = m<sub>A</sub>·g = 20,0·9,80 = <b>196 N</b>. → Ya no hay aceleración, así que la tensión es exactamente el peso. → (A) es el peso del otro bloque. → Además: (B) 0 N valdría si el bloque estuviera apoyado, pero sigue colgado; (D) 426 N suma los dos pesos (43,5·9,80), y el que está en el piso ya no tira de la cuerda.'},
  {st: 'Un trineo + equipo de 140 kg sobre nieve (μe = 0,100). ¿Tensión mínima para que empiece a moverse? (g = 9,80 m/s²)', opts: ['91,0 N', '137 N', '1372 N', '89,2 N'], c: 1, ex: 'Para arrancar hay que vencer el rozamiento estático máximo: T = μ<sub>e</sub>·N = μ<sub>e</sub>·m·g = 0,100·140·9,80 = <b>137 N</b>. → (D) usaría μ<sub>d</sub> (0,065), pero para ARRANCAR manda el estático. → Además: (A) 91,0 N usa μ<sub>d</sub> y además g = 10 (0,065·140·10); (C) 1372 N es el peso entero: falta multiplicar por μ<sub>e</sub>.'},
  {st: 'Ese trineo recorre 250 m a velocidad constante (μd = 0,065). ¿Trabajo de la fuerza de rozamiento? (m = 140 kg, g = 9,80 m/s²)', opts: ['+2,23·10⁴ J', '−3,43·10⁴ J', '−89,2 J', '−2,23·10⁴ J'], c: 3, ex: 'F<sub>roz</sub> = μ<sub>d</sub>·m·g = 0,065·140·9,80 = 89,2 N. → W = −F<sub>roz</sub>·d = −89,2·250 = <b>−2,23·10⁴ J</b>. → Es NEGATIVO porque el roce se opone al movimiento (cos180°). → (A) le pone signo positivo; (C) olvida multiplicar por la distancia. → Además: (B) −3,43·10⁴ J usa μ<sub>e</sub> (0,100·140·9,80·250): ya en movimiento manda el dinámico.'}
]);

// SECCIÓN 8 · PLANO INCLINADO
registerExercises('fisica-final', '8', [
  {st: 'Un bloque de mármol sobre un plano tiene μe = 0,380 con la superficie. ¿Cuál es el ángulo mínimo de inclinación para que empiece a deslizar?', opts: ['22,3°', '38,0°', '20,8°', '14,0°'], c: 2, ex: 'En el umbral, la componente del peso que tira hacia abajo iguala al rozamiento estático máximo: m·g·senα = μ<sub>e</sub>·m·g·cosα → <b>tanα = μ<sub>e</sub></b>. → α<sub>mín</sub> = arctg(0,380) = <b>20,8°</b>. → Depende SOLO de μ<sub>e</sub> (la masa se cancela). → (B) confunde μ con el ángulo directo. → Además: (A) 22,3° es arcsen(0,380): usa seno en vez de tangente; (D) 14,0° es arctg(0,250): usa el coeficiente dinámico, que no decide si arranca.'},
  {st: 'Ese bloque (μd = 0,250) está en un plano a 30,0°. ¿Con qué aceleración desliza? (g = 9,80 m/s²)', opts: ['2,78 m/s²', '4,90 m/s²', '2,12 m/s²', '9,80 m/s²'], c: 0, ex: 'a = g·(senα − μ<sub>d</sub>·cosα) = 9,80·(sen30° − 0,250·cos30°) = 9,80·(0,500 − 0,250·0,866) = 9,80·0,2835 = <b>2,78 m/s²</b>. → Como 30° &gt; 20,8° (ángulo crítico), efectivamente desliza. → (B) olvida el término del rozamiento. → Además: (C) 2,12 m/s² es solo el término del rozamiento (μ<sub>d</sub>·g·cos30°), sin restarlo de g·sen30°; (D) 9,80 m/s² es caída libre: ni plano ni roce.'},
  {st: 'Un trineo desliza SIN roce por un techo cuyos catetos son 2,31 m (vertical) y 4,00 m (horizontal). ¿Con qué aceleración baja? (g = 9,80 m/s²)', opts: ['4,90 m/s²', '9,80 m/s²', '2,45 m/s²', '5,66 m/s²'], c: 0, ex: 'Sin roce, a = g·senα. → La hipotenusa es √(2,31² + 4,00²) = 4,619 m, así que senα = 2,31/4,619 = 0,500. → a = 9,80·0,500 = <b>4,90 m/s²</b>. → (B) sería caída vertical libre; (D) 5,66 m/s² es g·tanα (9,80·2,31/4,00): divide un cateto por el otro en vez de usar el seno. → Además: (C) 2,45 m/s² es la mitad: aplica el sen α dos veces (9,80·0,500²).'},
  {st: 'Ese trineo llega al borde b a 6,73 m/s y cae desde 3,00 m como proyectil (componentes en b: vx = 5,83, vy = −3,37 m/s). ¿A qué distancia horizontal del borde toca el suelo? (g = 9,80 m/s²)', opts: ['3,44 m', '1,49 m', '2,98 m', '6,73 m'], c: 2, ex: 'Es un tiro oblicuo desde b. → Tiempo: 0 = 3,00 − 3,37·t − 4,90·t² → resolviendo la cuadrática, t = 0,511 s. → Distancia horizontal = v<sub>bx</sub>·t = 5,83·0,511 = <b>2,98 m</b>. → (D) es la rapidez en b, no una distancia. → Además: (A) 3,44 m multiplica el tiempo por la rapidez entera (6,73·0,511) en vez de por v<sub>bx</sub>; (B) 1,49 m es la mitad de la correcta y no sale de los datos.'},
  {st: 'En un plano inclinado un ángulo α, ¿cuánto vale la fuerza normal sobre un bloque de masa m?', opts: ['N = m·g', 'N = m·g·senα', 'N = m·g·tanα', 'N = m·g·cosα'], c: 3, ex: 'El peso se descompone: la componente <b>perpendicular</b> al plano (la que aprieta) es m·g·cosα, y esa es la que equilibra la normal. → <b>N = m·g·cosα</b>. → La componente paralela (m·g·senα) es la que tiende a hacerlo deslizar. → (A) solo vale en plano horizontal (α = 0). → Además: (B) m·g·senα es la componente paralela al plano; (C) m·g·tanα no es ninguna componente del peso.'}
]);

// SECCIÓN 9 · CAÑITA VOLADORA + CONCEPTUAL V/F
registerExercises('fisica-final', '9', [
  {st: 'Una cañita de 88,0 g parte del reposo y acelera 2,50 s hasta 50,0 m (donde se apaga el motor). ¿Aceleración durante el impulso?', opts: ['20,0 m/s²', '16,0 m/s²', '40,0 m/s²', '8,00 m/s²'], c: 1, ex: 'Fase propulsada, MRUV desde el reposo: h = ½·a·t² → a = 2h/t² = 2·50,0/2,50² = 100/6,25 = <b>16,0 m/s²</b>. → (C) 40,0 es la rapidez al apagarse (v = a·t), no la aceleración. → Además: (A) 20,0 es la velocidad media (50,0/2,50), en m/s; (D) 8,00 m/s² olvida el 2 (h/t² en vez de 2h/t²).'},
  {st: 'Esa cañita se apaga a 50,0 m yendo a 40,0 m/s. ¿Qué altura máxima alcanza? (g = 9,80 m/s²)', opts: ['81,6 m', '50,0 m', '132 m', '90,0 m'], c: 2, ex: 'Tras apagarse sube como tiro vertical libre hasta que v = 0: h<sub>máx</sub> = h + v²/(2g) = 50,0 + 40,0²/(2·9,80) = 50,0 + 81,6 = <b>132 m</b>. → (A) es solo el tramo libre (falta sumar los 50 m del impulso). → Además: (B) 50,0 m es donde se apaga el motor, pero ahí todavía sube a 40,0 m/s; (D) 90,0 suma la altura con la rapidez (50,0 + 40,0), que no son la misma magnitud.'},
  {st: 'Para esa cañita (m = 88,0 g, a = 16,0 m/s²), ¿qué fuerza ejerció el motor durante el impulso? (g = 9,80 m/s²)', opts: ['2,27 N', '1,41 N', '0,862 N', '1,60 N'], c: 0, ex: '2ª ley en vertical: F<sub>motor</sub> − m·g = m·a → F = m·(a + g) = 0,088·(16,0 + 9,80) = 0,088·25,8 = <b>2,27 N</b>. → El motor vence el peso Y acelera. → (B) 1,41 N es m·a: olvida sumar el peso; (C) 0,862 N es solo el peso (m·g); (D) 1,60 N no sale de los datos (restar en vez de sumar daría 0,546 N).'},
  {st: 'Conceptual: la resta de vectores A − B, ¿es conmutativa?', opts: ['Sí, A − B = B − A', 'No, A − B = −(B − A)', 'Solo si son perpendiculares', 'Solo si tienen igual módulo'], c: 1, ex: 'La resta <b>NO es conmutativa</b>: A − B = −(B − A) (dan vectores opuestos). → Sí es conmutativa la SUMA (A + B = B + A). → Es una de las 6 afirmaciones del ejercicio conceptual de Feb 2026. → Por qué las otras están mal: (A) esa propiedad es de la suma; (C) y (D) ni siendo perpendiculares ni teniendo igual módulo coinciden: A − B y B − A solo son iguales si A = B.'},
  {st: 'Conceptual: dos trozos de oro de distinto tamaño, ¿tienen igual o distinta densidad?', opts: ['Distinta: el grande es más denso', 'Distinta: el chico es más denso', 'Depende de la temperatura ambiente', 'Igual: la densidad es una propiedad intensiva'], c: 3, ex: 'La densidad es una propiedad <b>intensiva</b>: no depende de la cantidad de material. → Dos trozos de oro (o de cualquier sustancia pura) tienen la <b>misma</b> densidad. → Igual pasa con presión y temperatura (intensivas); masa y volumen sí son extensivas. → Por qué las otras están mal: (A) y (B) el tamaño cambia la masa y el volumen en la misma proporción, así que el cociente no cambia; (C) los dos trozos están a la misma temperatura, eso no los diferencia.'},
  {st: 'Conceptual: dos cuerpos que FLOTAN, ¿qué relación hay entre el empuje que reciben y su peso?', opts: ['El empuje es mayor que el peso', 'El empuje es menor que el peso', 'No hay empuje si flotan', 'El empuje es igual al peso'], c: 3, ex: 'Un cuerpo que flota está en equilibrio: <b>empuje = peso</b>. → Por eso dos cuerpos que flotan reciben, cada uno, un empuje igual a su propio peso. → Si el empuje fuera mayor, subiría acelerando; si fuera menor, se hundiría. → Por qué las otras están mal: (A) si fuera mayor, subiría acelerando; (B) si fuera menor, se hundiría; (C) sin empuje nada lo sostendría: flotar es justamente que el empuje equilibra al peso.'},
  {st: 'Conceptual: ¿cuántas cifras significativas tiene 1,20×10⁻⁶?', opts: ['Una', 'Tres', 'Dos', 'Seis'], c: 1, ex: 'En notación científica cuentan todas las cifras del <b>coeficiente</b>: 1, 2 y 0 → <b>tres cifras</b>. → El exponente (10⁻⁶) no cuenta. → El 0 final SÍ cuenta (indica precisión). → (D) contaría los ceros del "0,00000120", que no cuentan (ceros a la izquierda). → Además: (A) sería 1×10⁻⁶; (C) sería 1,2×10⁻⁶: el cero final escrito es la tercera cifra.'}
]);

// SECCIÓN 10 · MIX INTEGRADOR
registerExercises('fisica-final', '10', [
  {st: 'Leés: "Con el objetivo de calibrar su arma, una tiradora apunta horizontalmente el cañón...". ¿Qué tipo de ejercicio es y cuál es la primera acción?', opts: ['Tiro oblicuo (horizontal); sacar el tiempo de la distancia y v0, luego la caída', 'Estática; hacer el DCL', 'Hidrostática; usar empuje', 'Energía; conservación'], c: 0, ex: 'Palabras clave: "apunta horizontalmente", "proyectil", "blanco a X metros" → <b>tiro horizontal</b>. → Primera acción: t = distancia/v<sub>0</sub> (MRU horizontal), luego la caída Δy = ½·g·t². → Es el subtipo A del TIPO 1, uno de los más repetidos. → Por qué las otras están mal: (B) no hay nada sostenido en reposo: hay un proyectil en vuelo; (C) no hay líquido ni cuerpo sumergido; (D) piden cuánto cae en un tiempo, y eso sale de la cinemática.'},
  {st: 'Leés: "En la situación estática representada, la soga izquierda forma 45° y la derecha 20° respecto de la vertical...". ¿Qué planteás?', opts: ['v² = v0² + 2·a·Δx', 'Empuje = peso', 'ΣFx = 0 y ΣFy = 0 (con cuidado: ángulos con la VERTICAL)', 'a = F/m'], c: 2, ex: 'Cuerpo en reposo con dos cuerdas → <b>estática</b>: ΣF<sub>x</sub> = 0 y ΣF<sub>y</sub> = 0. → OJO: los ángulos son con la <b>vertical</b>, así que la componente horizontal usa <b>seno</b> y la vertical <b>coseno</b> (al revés que si fueran con la horizontal). → Dibujar el DCL antes de plantear. → Por qué las otras están mal: (A) y (D) son para cuerpos que se mueven o aceleran, y acá está en reposo; (B) no hay ningún líquido.'},
  {st: '¿Cuál es el error más caro y frecuente del final Torti?', opts: ['No dibujar el vector', 'No convertir las unidades a SI (km/h, g/cm³, cm, L) antes de meter números', 'Usar g = 9,80 en vez de 10', 'Redondear al final'], c: 1, ex: 'No pasar a SI (km/h ÷ 3,6, g/cm³ × 1000, cm ÷ 100, L ÷ 1000) es la causa nº1 de resultados con la tercera cifra mal. → (C) al revés: hay que usar 9,80 (lo pide el examen); (D) redondear AL FINAL es lo correcto (el error es redondear en pasos intermedios). → Además: (A) no dibujar te cuesta el inciso del DCL, pero no arruina todas las cuentas como una unidad sin convertir.'},
  {st: 'Un tramo del recorrido tiene rozamiento (μ). ¿Podés usar conservación de energía mecánica ahí?', opts: ['Sí, siempre se conserva', 'Sí, si el cuerpo es liviano', 'Solo si va para arriba', 'No: con rozamiento usá W_roz = ΔEm (la energía no se conserva)'], c: 3, ex: 'Con rozamiento la energía mecánica NO se conserva: parte se disipa como calor. → Usá el teorema <b>W<sub>roz</sub> = ΔE<sub>m</sub></b> (el trabajo del roce es la variación de energía mecánica). → Ignorar el roce da rapideces de más. → La conservación pura solo vale en tramos SIN roce. → Por qué las otras están mal: (A) la energía mecánica solo se conserva si no hay fuerzas no conservativas; (B) la masa no cambia eso: el roce disipa igual; (C) subiendo o bajando, el roce siempre saca energía.'},
  {st: 'Un problema pide "la rapidez con que llega al suelo" tras caer desde cierta altura sin roce. ¿Newton o Energía?', opts: ['Newton: ΣF = m·a', 'Energía: conservación (mgh = ½mv²) o cinemática', 'Estática', 'Ninguna, falta el tiempo'], c: 1, ex: 'Piden <b>rapidez</b> a partir de una <b>altura</b> → <b>Energía</b> (o cinemática sin tiempo, v² = v0² + 2·a·Δx). → Sin roce: m·g·h = ½·m·v² → v = √(2·g·h), y no hace falta el tiempo. → Newton daría la aceleración, pero acá el atajo es energía. → Por qué las otras están mal: (A) Newton da la aceleración y todavía faltaría la cinemática para llegar a la rapidez; (C) el cuerpo cae, no está en equilibrio; (D) el tiempo no hace falta: v = √(2·g·h).'},
  {st: 'Un final reciente (2025-2026) típicamente combina...', opts: ['Un tiro oblicuo + un plano inclinado o trabajo-energía + una hidrostática (y a veces el V/F)', 'Solo cinemática 1D', 'Solo teoría', 'Circular y calorimetría'], c: 0, ex: 'Los finales recientes mezclan las <b>familias grandes</b>: tiro oblicuo (bala/pelota) + plano inclinado o trabajo-energía (bloque con μ) + hidrostática (peso aparente/resorte sumergido), a veces con el conceptual V/F de cierre. → Entrenar esas familias con sus dos versiones (Tema 1 y 2) cubre casi todo. → Por qué las otras están mal: (B) la cinemática en una dimensión casi no aparece sola (la cañita, 2 de 19); (C) el final es de desarrollo, con cuentas; (D) circular y calorimetría no figuran en el ranking de los 19 finales.'}
]);
