// ============================================================
// FÍSICA I · UTN FRBA · OSCILACIONES (MAS)
// Fuentes:
//   · 9 segundos parciales de la cátedra Prof. Patricia Martinelli
//     (2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017) — los 9
//     traen el ejercicio de MAS en el bloque A.
//   · Finales de UTN.BA (hojas de enunciado 2022–2025) para péndulo
//     simple, péndulo físico y los montajes mixtos del MAS horizontal.
// Convenciones de la cátedra: g = 10 m/s²; declarar sistema de
// referencia, DCL e hipótesis; puede haber datos que no interesen.
// ============================================================


// ============================================================
// SECCIÓN 1 · UN SOLO ESQUEMA RESUELVE LOS NUEVE
// ============================================================
registerExercises('fisica1-utn-oscilaciones', '1', [
  {st: 'Una masa cuelga en reposo de un resorte vertical y después se la hace oscilar. ¿Alrededor de qué posición oscila?',
   opts: ['Alrededor de la longitud natural l₀ del resorte', 'Alrededor de la posición de equilibrio l_eq = l₀ + mg/k', 'Alrededor del techo (x = 0)', 'Alrededor del punto más bajo del recorrido'],
   c: 1,
   ex: 'La gravedad <b>corre el centro de oscilación</b> una distancia mg/k hacia abajo, pero no deforma el movimiento: sigue siendo un MAS simétrico alrededor de <b>l_eq</b>. Por eso x(t) lleva el término constante <b>+ l_eq</b>. ▸ Por qué las otras: (A) es el error nº1 de todo el tema, y hace que la amplitud y la fase salgan mal; (C) el techo es sólo el origen del eje, no el centro del movimiento; (D) el punto más bajo es un extremo, donde la velocidad es cero, no el centro.'},

  {st: 'El mismo resorte con la misma masa se prueba primero horizontal y después colgado del techo. ¿Qué le pasa a la frecuencia angular ω?',
   opts: ['Aumenta, porque ahora también actúa la gravedad', 'Disminuye, porque el resorte ya está estirado', 'No cambia: ω = √(k/m) y no depende de g', 'Depende de la amplitud con que lo hagas oscilar'],
   c: 2,
   ex: '<b>ω = √(k/m)</b>: sólo la constante elástica y la masa. La gravedad únicamente desplaza el centro de oscilación. ▸ Es la trampa que la cátedra marca en las soluciones oficiales de 2009, 2013, 2014 y 2015. ▸ Por qué las otras: (A) y (B) intentan corregir ω por el peso, que es el error clásico; (D) en un MAS el período es <b>independiente de la amplitud</b> (isocronismo), y esa es justamente la propiedad que lo define.'},

  {st: '2P 2009: un resorte ideal de k = 100 N/m y longitud natural l₀ = 60 cm mide 80 cm con el cuerpo colgado en reposo. ¿Cuánto vale la masa? (g = 10 m/s²)',
   opts: ['0,8 kg', '2 kg', '6 kg', '8 kg'],
   c: 1,
   ex: 'La masa no es dato: sale del <b>equilibrio estático</b>. k(l_eq − l₀) = mg ⟹ m = 100·(0,80 − 0,60)/10 = 100·0,2/10 = <b>2 kg</b>. ▸ El estiramiento es la <b>diferencia</b>, 20 cm. ▸ Por qué las otras: (D) usa l_eq = 0,80 m entera (100·0,8/10); (C) usa l₀ = 0,60 m entera; (A) mezcla unidades o divide por k en vez de multiplicar.'},

  {st: 'Un resorte oscila entre l_mín = 40 cm y l_máx = 60 cm. ¿Cuánto valen la amplitud y el centro de oscilación?',
   opts: ['A = 20 cm, centro en 40 cm', 'A = 10 cm, centro en 50 cm', 'A = 20 cm, centro en 50 cm', 'A = 10 cm, centro en 40 cm'],
   c: 1,
   ex: 'La amplitud es la <b>semi</b>diferencia y el centro el <b>promedio</b>: A = (60 − 40)/2 = <b>10 cm</b>, l_eq = (60 + 40)/2 = <b>50 cm</b>. ▸ El movimiento va de l_eq − A a l_eq + A, o sea 10 cm para cada lado. ▸ Por qué las otras: (A) y (C) toman A = l_máx − l_mín, que es el <b>recorrido total</b> (2A), el error más repetido del tema; (D) confunde el centro con l_mín.'},

  {st: 'Eje x positivo hacia ABAJO, convención x(t) = A·cos(ωt + φ₀) + l_eq. El cuerpo arranca justo en el equilibrio con velocidad hacia abajo. ¿Cuál es la fase inicial?',
   opts: ['φ₀ = 0', 'φ₀ = +π/2', 'φ₀ = −π/2', 'φ₀ = π'],
   c: 2,
   ex: 'Dos condiciones. <b>(1)</b> x(0) = l_eq ⟹ A·cos φ₀ = 0 ⟹ φ₀ = ±π/2. <b>(2)</b> v(0) = −A·ω·sen φ₀ debe ser positiva (hacia abajo es el sentido +) ⟹ sen φ₀ &lt; 0 ⟹ <b>φ₀ = −π/2</b>. ▸ Es exactamente el planteo de 2P 2013 y 2P 2014. ▸ Por qué las otras: (B) +π/2 es la que corresponde si la velocidad inicial fuera hacia <b>arriba</b> (2P 2010) — elegirla es el error que la cátedra señala como el más común; (A) y (D) darían x(0) = l_eq ± A, o sea arrancar en un extremo con velocidad nula.'},

  {st: '2P 2011: una masa oscila con un resorte de K = 1000 N/m manteniendo su energía mecánica en 5 J. ¿Cuál es la amplitud?',
   opts: ['0,01 m', '0,1 m', '1 m', '0,32 m'],
   c: 1,
   ex: 'En los extremos toda la energía es elástica: <b>E = ½·K·A²</b> ⟹ A² = 2E/K = 10/1000 = 0,01 m² ⟹ <b>A = 0,1 m = 10 cm</b>. ▸ Por qué las otras: (A) 0,01 m es A² sin sacar la raíz; (C) 1 m sale de olvidar el factor ½ y confundirse de potencia; (D) 0,32 m es √0,1, que aparece si usás E = ½KA sin cuadrado.'},

  {st: 'Un cuerpo cuelga en reposo de un resorte y el estiramiento estático es δ = l_eq − l₀. No te dan ni k ni m. ¿Podés calcular ω?',
   opts: ['No, faltan datos', 'Sí: ω = √(g/δ)', 'Sí: ω = √(δ/g)', 'Sí, pero sólo si además te dan la amplitud'],
   c: 1,
   ex: 'Del equilibrio: k·δ = m·g ⟹ m/k = δ/g. Entonces <b>ω = √(k/m) = √(g/δ)</b>. ▸ Es un atajo que resuelve solo el problema del final donde te dan "el resorte está elongado 20 cm en el equilibrio" y nada más: ω = √(10/0,2) = 7,07 rad/s. ▸ Por qué las otras: (C) invierte la fracción (te daría 0,14 rad/s, un período de 45 s); (D) la amplitud no entra en ω, el MAS es isócrono; (A) sí alcanzan los datos.'}
]);


// ============================================================
// SECCIÓN 2 · MAS VERTICAL MASA-RESORTE
// ============================================================
registerExercises('fisica1-utn-oscilaciones', '2', [
  {st: '2P 2010: un cuerpo cuelga del techo por DOS resortes ideales idénticos colocados uno debajo del otro, cada uno con k = 200 N/m. ¿Cuál es la constante equivalente?',
   opts: ['400 N/m', '200 N/m', '100 N/m', '50 N/m'],
   c: 2,
   ex: 'Uno debajo del otro es <b>serie</b>: 1/k_eq = 1/k + 1/k ⟹ <b>k_eq = k/2 = 100 N/m</b>. El conjunto es <b>más blando</b> que cada resorte por separado. ▸ Por qué las otras: (A) 400 N/m es la suma, que corresponde al <b>paralelo</b> (los dos al lado, sosteniendo el mismo cuerpo); si la usás, la masa te sale mal por un factor 4; (B) sería si hubiera un solo resorte; (D) divide dos veces.'},

  {st: 'En ese mismo sistema, cada resorte tiene longitud natural l₀ = 60 cm. ¿Cuál es la longitud natural del conjunto?',
   opts: ['60 cm', '30 cm', '120 cm', '180 cm'],
   c: 2,
   ex: 'En serie las longitudes <b>se suman</b>: l₀_eq = 2·l₀ = <b>1,2 m</b>. ▸ Con el cuerpo a 160 cm del techo, el estiramiento del conjunto es 1,60 − 1,20 = 0,40 m (0,20 m cada resorte), y de ahí m = k_eq·Δl/g = 100·0,4/10 = 4 kg. ▸ Por qué las otras: (A) usar 60 cm da un estiramiento de 1 m y una masa de 10 kg, que es el error más frecuente del ejercicio; (B) y (D) no salen de ningún planteo.'},

  {st: '2P 2012: m = 2 kg, k = 200 N/m, l₀ = 50 cm. Se lleva el cuerpo hasta que el resorte mide 40 cm y se lo suelta con velocidad nula. ¿Cuál es la amplitud?',
   opts: ['10 cm', '20 cm', '40 cm', '60 cm'],
   c: 1,
   ex: 'Primero el equilibrio: l_eq = l₀ + mg/k = 0,50 + 20/200 = 0,50 + 0,10 = <b>60 cm</b>. Se suelta desde 40 cm, o sea <b>20 cm por encima</b> del equilibrio, y con velocidad nula: ese punto <b>es</b> un extremo ⟹ <b>A = 20 cm</b>. ▸ Por qué las otras: (A) 10 cm es el estiramiento estático mg/k, no la amplitud; (C) 40 cm es la longitud de partida; (D) 60 cm es l_eq. Todos son distractores que están en el enunciado.'},

  {st: '2P 2015: un cuerpo de m = 2 kg cuelga de un resorte y oscila con ω = 10 rad/s. ¿Cuál es la constante elástica?',
   opts: ['20 N/m', '100 N/m', '200 N/m', '400 N/m'],
   c: 2,
   ex: 'De ω = √(K/m) se despeja <b>K = m·ω²</b> = 2·10² = <b>200 N/m</b>. ▸ Por qué las otras: (A) 20 N/m es m·ω (olvidarse el cuadrado); (D) 400 N/m sale de usar ω² = 200 sin dividir bien o de duplicar; (B) 100 N/m es ω² solo, sin la masa. Chequeo rápido: con K = 200 y m = 2, √(200/2) = √100 = 10 ✓.'},

  {st: '2P 2016: un bloque cuelga de un resorte de l₀ = 1 m, oscila entre l_mín = 1,2 m y l_máx = 1,6 m, y la energía mecánica es E = 1 J. ¿Cuánto vale K?',
   opts: ['12,5 N/m', '25 N/m', '50 N/m', '100 N/m'],
   c: 2,
   ex: '<b>Paso 1:</b> A = (1,6 − 1,2)/2 = <b>0,2 m</b>. <b>Paso 2:</b> midiendo desde el equilibrio, E = ½·K·A² ⟹ K = 2E/A² = 2/0,04 = <b>50 N/m</b>. ▸ Por qué las otras: (A) 12,5 N/m sale de tomar A = 0,4 m (la diferencia entera en vez de la mitad); (D) 100 N/m sale de olvidar el ½; (B) 25 N/m combina los dos errores. Chequeo: l_eq = 1,4 m ⟹ δ = 0,4 m ⟹ m = K·δ/g = 50·0,4/10 = 2 kg y ω = √(50/2) = 5 rad/s, con v_máx = 1 m/s y E = ½·2·1² = 1 J ✓.'},

  {st: '2P 2014: el enunciado dice "la mínima distancia del cuerpo al techo es de 80 cm" y el equilibrio está en l_eq = 1 m. ¿Qué representa ese dato y cuánto vale A?',
   opts: ['Es el punto más bajo del recorrido; A = 20 cm', 'Es el punto más alto del recorrido; A = 20 cm', 'Es el punto más alto del recorrido; A = 80 cm', 'Es la longitud natural del resorte; A = 40 cm'],
   c: 1,
   ex: 'Menos distancia al techo = el resorte más corto = el cuerpo <b>más arriba</b>. Es l_mín, el extremo <b>superior</b>. Y la amplitud es la distancia de ahí al centro: <b>A = l_eq − l_mín = 100 − 80 = 20 cm</b>. ▸ Por qué las otras: (A) leerlo como el punto más bajo te deja una amplitud negativa y todo el inciso b) se cae; (C) 80 cm es una posición, no una amplitud; (D) la longitud natural es 60 cm y sólo sirve para ubicar el equilibrio.'}
]);


// ============================================================
// SECCIÓN 3 · MAS HORIZONTAL
// ============================================================
registerExercises('fisica1-utn-oscilaciones', '3', [
  {st: '2P 2017: un bloque oscila sobre una superficie horizontal sin rozamiento unido a un resorte; l_mín = 30 cm y l_máx = 50 cm. ¿Cuál es la longitud natural del resorte?',
   opts: ['30 cm', '40 cm', '50 cm', '20 cm'],
   c: 1,
   ex: 'En horizontal el peso lo compensa la normal y <b>no estira el resorte</b>: el centro de la oscilación coincide con la longitud natural. l₀ = (50 + 30)/2 = <b>40 cm</b>. ▸ Por qué las otras: (A) confundir l₀ con l_mín es el error típico — vale sólo si el resorte llegara a soltarse, que no es el caso; (C) l_máx es el otro extremo; (D) 20 cm es el recorrido total (2A). Ojo: si el resorte fuera <b>vertical</b> esto NO valdría, habría que restar mg/k.'},

  {st: 'Ese mismo bloque tiene A = 10 cm y v_máx = 2 m/s. ¿Cuál es la frecuencia angular?',
   opts: ['0,2 rad/s', '20 rad/s', '200 rad/s', '2 rad/s'],
   c: 1,
   ex: 'v_máx = A·ω ⟹ ω = v_máx/A = 2/<b>0,1</b> = <b>20 rad/s</b>. ▸ El detalle que decide: pasar A a metros <b>antes</b> de dividir. ▸ Por qué las otras: (A) 0,2 rad/s es A/v_máx invertido; (C) 200 rad/s sale de usar A = 10 (cm) sin convertir, y arrastra un error de 10⁴ en k; (D) 2 rad/s es la propia v_máx mal leída. Chequeo: con m = 0,5 kg, k = m·ω² = 0,5·400 = 200 N/m.'},

  {st: '2P 2011: m = 0,1 kg, K = 1000 N/m, A = 0,1 m (con ω = 100 s⁻¹). ¿Cuál es el módulo de la aceleración máxima?',
   opts: ['1 m/s²', '10 m/s²', '100 m/s²', '1000 m/s²'],
   c: 3,
   ex: '<b>a_máx = A·ω² = 0,1 · (100)² = 0,1 · 10 000 = 1000 m/s²</b>. ▸ Chequeo cruzado obligatorio: F_máx = K·A = 1000·0,1 = 100 N, y F = m·a ⟹ a = 100/0,1 = 1000 m/s² ✓. ▸ <b>Atención:</b> la solución oficial manuscrita de la cátedra escribe 1 m/s² y F = 0,1 N — es una <b>errata</b> de la propia clave, no la copies. ▸ Por qué las otras: (A) es justamente el valor erróneo del manuscrito; (B) y (C) salen de usar ω o ω² a medias.'},

  {st: 'Final UTN.BA: un bloque de 6 kg a 3 m/s choca contra otro de 12 kg unido a un resorte de k = 300 N/m en su longitud natural. El de 6 kg rebota a 1 m/s. ¿Amplitud de las oscilaciones del de 12 kg?',
   opts: ['0,2 m', '0,4 m', '0,6 m', '1,2 m'],
   c: 1,
   ex: '<b>Etapa 1 — choque</b> (el resorte todavía no actuó, se conserva p): 6·3 = 6·(−1) + 12·v₂ ⟹ 18 + 6 = 12·v₂ ⟹ v₂ = <b>2 m/s</b>. <b>Etapa 2 — MAS</b>: ω = √(300/12) = 5 rad/s, y como el choque ocurre con el resorte en su longitud natural, el bloque arranca <b>en el equilibrio</b> ⟹ A = v₂/ω = 2/5 = <b>0,4 m</b>. ▸ Por qué las otras: (A) 0,2 m sale de olvidar el signo del rebote (v₂ = 1 m/s); (C) y (D) salen de usar la velocidad del proyectil o de no dividir por ω. ▸ Verificación por energía: ½·12·2² = 24 J = ½·300·A² ⟹ A = 0,4 m ✓.'},

  {st: 'Final UTN.BA 21/02/24: bloque M = 10 kg con resorte k = 4 N/m sobre superficie sin fricción; encima, un bloque m = 2 kg con μe = 0,1 entre ambos. ¿Amplitud máxima para que el de arriba no resbale? (g = 10 m/s²)',
   opts: ['0,25 m', '3 m', '1 m', '12 m'],
   c: 1,
   ex: 'Al de arriba lo acelera <b>sólo el rozamiento</b>: f = m·a ≤ μe·m·g ⟹ <b>a_máx = μe·g = 1 m/s²</b> (la masa se cancela). Los dos oscilan juntos ⟹ ω² = k/(M + m) = 4/12 = 1/3 s⁻². Y como a_máx = A·ω²: <b>A = 1/(1/3) = 3 m</b>. ▸ Por qué las otras: (C) 1 m es a_máx confundida con amplitud; (A) 0,25 m usa ω² = k/M... sin sumar la masa de arriba mal despejado; (D) 12 m multiplica en vez de dividir. ▸ El paso que más se olvida: <b>ω² usa la masa TOTAL</b>, porque el sistema que oscila son los dos bloques.'}
]);


// ============================================================
// SECCIÓN 4 · PÉNDULO SIMPLE Y PÉNDULO FÍSICO
// ============================================================
registerExercises('fisica1-utn-oscilaciones', '4', [
  {st: '¿De qué depende el período de un péndulo simple (ángulos chicos)?',
   opts: ['De la masa y de la longitud', 'Sólo de la longitud y de g', 'De la amplitud y de la masa', 'De la masa, la longitud y la amplitud'],
   c: 1,
   ex: '<b>T = 2π√(l/g)</b>: no aparecen ni la masa ni la amplitud. ▸ Si el enunciado te da la masa del péndulo, o la necesitás para otro inciso (energía, tensión, choque) o es un <b>distractor deliberado</b>: la cátedra avisa que puede haber datos que no interesen. ▸ Por qué las otras: (A), (C) y (D) meten masa o amplitud, que no entran en T mientras el ángulo sea chico (isocronismo).'},

  {st: 'Final UTN.BA: un péndulo ideal de l = 2,5 m. ¿Cuánto vale su período? (g = 10 m/s²)',
   opts: ['π/2 s ≈ 1,57 s', 'π s ≈ 3,14 s', '2π s ≈ 6,28 s', '4 s'],
   c: 1,
   ex: 'ω = √(g/l) = √(10/2,5) = √4 = <b>2 rad/s</b> ⟹ T = 2π/ω = <b>π s ≈ 3,14 s</b>. ▸ Por qué las otras: (A) π/2 s corresponde a ω = 4; (C) 2π s a ω = 1 (sería l = 10 m); (D) 4 s confunde ω = 2 con el período. Chequeo: un péndulo de 2,5 m es "largo", tiene que tardar más de 1 s por oscilación completa.'},

  {st: 'En el péndulo físico, T = 2π√(I/(M·g·d)). ¿Qué es exactamente d?',
   opts: ['La longitud de la barra', 'La distancia del punto de suspensión al centro de masa del CONJUNTO', 'El radio del disco', 'La distancia del punto de suspensión al disco'],
   c: 1,
   ex: '<b>d es la distancia del pivote al centro de masa del cuerpo entero</b>. En la barra + disco del final: d = (m_b·L/2 + m_d·a)/(m_b + m_d) = (0,8·1 + 1,2·1,67)/2 = <b>1,402 m</b>. ▸ Por qué las otras: (D) usar a = 1,67 m (la distancia al disco) es el error típico y te da un T casi 9% más chico; (A) L = 2 m sería el CM sólo si toda la masa estuviera en la punta; (C) el radio del disco entra en I, nunca en d. ▸ Y acordate: M en la fórmula es la masa <b>total</b>.'},

  {st: 'Un disco homogéneo de masa m y radio r está enhebrado en una barra, a distancia a del punto de suspensión. ¿Cuál es su momento de inercia respecto de ese punto?',
   opts: ['m·r²/2', 'm·a²', 'm·r²/2 + m·a²', 'm·r²/2 + m·(a/2)²'],
   c: 2,
   ex: '<b>Steiner</b>: I = I_CM + m·s², con s la distancia del eje al CM del disco. I = <b>m·r²/2 + m·a²</b>. ▸ Con los números del final (m = 1,2 kg, r = 0,15 m, a = 1,67 m): 0,0135 + 3,347 = 3,360 kg·m². Fijate que el término de Steiner es <b>250 veces</b> el propio del disco. ▸ Por qué las otras: (A) olvida Steiner y deja I 250 veces más chico; (B) trata al disco como puntual (aproximación aceptable acá pero no es lo que piden); (D) parte a por la mitad sin motivo — a ya se mide desde el pivote.'},

  {st: 'En los 9 segundos parciales de la cátedra Martinelli, ¿cómo aparece el péndulo?',
   opts: ['Como el oscilador del bloque A, en lugar del masa-resorte', 'Como mecanismo para darle velocidad a un cuerpo antes de un choque', 'No aparece nunca en ningún ejercicio', 'Siempre como péndulo físico con barra y disco'],
   c: 1,
   ex: 'En el parcial el MAS del bloque A es <b>siempre masa-resorte</b>; cuando hay un péndulo, sirve para calcular con qué velocidad llega un cuerpo al punto más bajo (v = √(2gl(1−cos α))) y después viene un choque. ▸ Como oscilador, el péndulo aparece en el <b>final</b>: amplitud angular y fase inicial (péndulo ideal) y el reloj de barra + disco (péndulo físico). ▸ Por qué las otras: (A) invierte los roles; (C) sí aparece; (D) el péndulo físico es exclusivo del final.'}
]);


// ============================================================
// EJERCICIOS REALES · SECCIÓN 2 · MAS VERTICAL
// 7 ejercicios de parcial (Martinelli) + 1 de final (UTN.BA)
// ============================================================
registerReveals('fisica1-utn-oscilaciones', '2', [

{st: '<b>2do parcial 2009 · Tema 1 · Problema 3 · 07/12/2009 · Prof. Patricia Martinelli (UTN FRBA).</b><br>Un cuerpo se encontraba en reposo colgando de un techo, sostenido por un resorte ideal de constante elástica k=100N/m y longitud natural l0=60cm. En esas condiciones la longitud del resorte era 80cm. En el instante t=0s, estando el cuerpo el esa posición <span class="muted">[sic, dice "el" por "en"]</span>, se le imprimió al mismo una velocidad hacia abajo de módulo 60cm/s.<br>a) Calcule la masa del cuerpo y determine la frecuencia angular (o pulsación) y el período del movimiento oscilatorio que se tiene para t&gt;0s.<br>b) Obtenga la ecuación de movimiento, escriba las soluciones generales para la posición y la velocidad del cuerpo para todo t&gt;0s y determine la amplitud y la fase inicial del movimiento.',
 ans: 'a) m = 2 kg · ω = √50 ≈ 7,071 s⁻¹ · T ≈ 0,8886 s. b) Ecuación de movimiento: ẍ + ω²x = ω²·l_eq. Soluciones: x(t) = A·sen(ωt + φ₀) + 0,80 m y v(t) = A·ω·cos(ωt + φ₀), con A = 8,49 cm y φ₀ = 0.',
 sol: '<b>Referencia e hipótesis.</b> Eje x vertical, origen en el techo, <b>positivo hacia abajo</b>; x mide la longitud del resorte. Resorte ideal (sin masa), sin rozamiento, g = 10 m/s². DCL del cuerpo: elástica k(x − l₀) hacia arriba, peso mg hacia abajo. ▸ <b>a) Masa.</b> En el equilibrio inicial ΣF = 0: mg = k(l_eq − l₀) con l_eq = 0,80 m y l₀ = 0,60 m, o sea un estiramiento de <b>0,20 m</b> (no 0,80 ni 0,60). m = 100·0,20/10 = <b>2 kg</b>. ▸ <b>Frecuencia y período.</b> ω = √(k/m) = √(100/2) = √50 = <b>7,071 s⁻¹</b>; T = 2π/ω = <b>0,8886 s</b>. ▸ <b>b) Ecuación de movimiento.</b> Newton con x hacia abajo: mg − k(x − l₀) = mẍ. Dividiendo por m y reordenando: <b>ẍ + ω²x = ω²l₀ + g = ω²l_eq</b>. Verificación numérica: ω²l₀ + g = 50·0,6 + 10 = 40 = 50·0,8 ✓. ▸ <b>Soluciones generales.</b> x(t) = A·sen(ωt + φ₀) + 0,80 m; v(t) = A·ω·cos(ωt + φ₀). <span class="muted">(La solución oficial de esta fecha usa la convención SENO.)</span> ▸ <b>Condiciones iniciales.</b> x(0) = 0,80 m = l_eq ⟹ A·sen φ₀ = 0 ⟹ φ₀ = 0 o π. v(0) = +0,60 m/s (hacia abajo = sentido positivo) ⟹ A·ω·cos φ₀ &gt; 0 ⟹ cos φ₀ &gt; 0 ⟹ <b>φ₀ = 0</b>. ▸ <b>Amplitud.</b> A = v₀/ω = 0,60/7,071 = <b>0,0849 m = 8,49 cm</b>. ▸ <b>Chequeo.</b> Oscila entre 71,5 cm y 88,5 cm del techo; v_máx = A·ω = 0,0849·7,071 = 0,60 m/s, que es la velocidad inicial ✓.'},

{st: '<b>2do parcial 2010 · A2 · 30/11/2010 · Prof. Patricia Martinelli (UTN FRBA).</b><br>Un cuerpo se encuentra en reposo, colgando de un techo por medio de dos resortes ideales idénticos, colocados como se muestra en la figura <span class="muted">[los dos resortes van en SERIE, uno colgando del otro; ver la figura de la unidad 2]</span>. Cada resorte tiene constante elástica k=200N/m y longitud natural l0=60cm. En esas condiciones, el cuerpo está situado a 160cm del techo. Estando en esta posición, en determinado instante t=0s, se le imprime al mismo una velocidad de módulo v0=60cm/s, hacia arriba.<br>a) Calcule la masa del cuerpo y determine la frecuencia angular (o pulsación) y el período del movimiento oscilatorio que se tiene para t≥0s.<br>b) Escriba las ecuaciones que definen la posición y la velocidad del cuerpo para todo t≥0s, y determine la amplitud y la fase inicial del movimiento. Indique claramente el sistema de coordenadas utilizado.',
 ans: 'a) m = 4 kg · ω = 5 s⁻¹ · T = 2π/5 ≈ 1,257 s. b) x(t) = 0,12 m·cos(5 s⁻¹·t + π/2) + 1,60 m y v(t) = −0,60 m/s·sen(5 s⁻¹·t + π/2) = −0,60 m/s·cos(5 s⁻¹·t), con A = 12 cm y φ₀ = +π/2 (eje x positivo hacia abajo, origen en el techo).',
 sol: '<b>Referencia.</b> Eje x vertical, origen en el techo, positivo hacia abajo. ▸ <b>Resorte equivalente (el corazón del ejercicio).</b> Los dos resortes están <b>en serie</b>: k_eq = k·k/(k+k) = k/2 = <b>100 N/m</b> y l₀_eq = 2·l₀ = <b>1,20 m</b>. ▸ <b>a) Masa.</b> Equilibrio a x_eq = 1,60 m: k_eq(x_eq − l₀_eq) = mg ⟹ 100·(1,60 − 1,20) = 10·m ⟹ 40 N = 10·m ⟹ <b>m = 4 kg</b>. <span class="muted">Cada resorte se estira 0,20 m y el conjunto 0,40 m.</span> ▸ <b>Frecuencia.</b> ω = √(k_eq/m) = √(100/4) = <b>5 s⁻¹</b>; T = 2π/5 = <b>1,257 s</b>. ▸ <b>b) Convención.</b> Esta solución oficial usa COSENO: x(t) = A·cos(ωt + φ₀) + 1,60 m, v(t) = −A·ω·sen(ωt + φ₀). ▸ <b>Condiciones iniciales.</b> x(0) = 1,60 m = x_eq ⟹ cos φ₀ = 0 ⟹ φ₀ = ±π/2. La velocidad inicial es hacia <b>arriba</b>, o sea v(0) = <b>−0,60 m/s</b> con este eje ⟹ −A·5·sen φ₀ &lt; 0 ⟹ sen φ₀ &gt; 0 ⟹ <b>φ₀ = +π/2</b>. ▸ <b>Amplitud.</b> A = v₀/ω = 0,60/5 = <b>0,12 m = 12 cm</b>. ▸ <b>Ecuaciones.</b> x(t) = 0,12 m·cos(5t + π/2) + 1,60 m = 1,60 m − 0,12 m·sen(5t); v(t) = −0,60 m/s·cos(5t). ▸ <b>Chequeo.</b> Oscila entre 1,48 m y 1,72 m del techo, y v(0) = −0,60 m/s (hacia arriba) ✓. <span class="muted">Si hubieras tomado los resortes en paralelo (k_eq = 400 N/m, l₀ = 0,60 m) la masa te habría dado 10 kg y todo lo demás mal.</span>'},

{st: '<b>2do parcial 2012 · A2 · 29/11/2012 · Curso Z1022 · Prof. Patricia Martinelli (UTN FRBA).</b><br>Un cuerpo de masa m=2kg se encuentra inicialmente en reposo colgando de un techo, sostenido por un resorte ideal de constante elástica k=200N/m y longitud natural l0=50cm. Luego se lleva el cuerpo a la posición en que la longitud del resorte es 40cm y en el instante t=0s, se lo suelta desde allí con velocidad nula.<br>a) Calcule la longitud inicial del resorte, mientras el cuerpo está en reposo colgando del techo, y determine la frecuencia angular ω y el período del movimiento oscilatorio armónico que se tiene para t&gt;0s.<br>b) Determine la amplitud A y la fase inicial de este movimiento, y escriba las ecuaciones que definen la posición y la velocidad del cuerpo para todo t&gt;0s.',
 ans: 'a) l_eq = 60 cm · ω = 10 s⁻¹ · T = π/5 ≈ 0,6283 s. b) A = 20 cm · φ₀ = −π/2 · x(t) = 20 cm·sen(10 s⁻¹·t − π/2) + 60 cm · v(t) = 200 cm/s·cos(10 s⁻¹·t − π/2).',
 sol: '<b>Referencia.</b> Eje x con origen en el techo, positivo hacia abajo; x mide la longitud del resorte. ▸ <b>a) Longitud inicial (= de equilibrio).</b> Ojo con la palabra "inicial": no es l₀. mg = k(x_eq − l₀) ⟹ x_eq = l₀ + mg/k = 0,50 + (2·10)/200 = 0,50 + 0,10 = <b>0,60 m = 60 cm</b>. ▸ <b>Frecuencia.</b> ω = √(k/m) = √(200/2) = √100 = <b>10 s⁻¹</b>; T = 2π/10 = π/5 = <b>0,6283 s</b>. ▸ <b>b) Convención.</b> Esta solución oficial usa SENO: x(t) = A·sen(ωt + φ₀) + x_eq, v(t) = A·ω·cos(ωt + φ₀). ▸ <b>Condiciones iniciales:</b> x(0) = 40 cm y v(0) = 0. <br>(1) 40 = A·sen φ₀ + 60 ⟹ A·sen φ₀ = <b>−20 cm</b>.<br>(2) 0 = A·ω·cos φ₀ ⟹ cos φ₀ = 0 ⟹ φ₀ = ±π/2.<br>Como A debe ser positiva, (1) exige sen φ₀ &lt; 0 ⟹ <b>φ₀ = −π/2</b> y <b>A = 20 cm</b>. ▸ <b>Ecuaciones.</b> x(t) = 20 cm·sen(10t − π/2) + 60 cm; v(t) = 200 cm/s·cos(10t − π/2). Equivalente: x(t) = 60 cm − 20 cm·cos(10t), v(t) = 200 cm/s·sen(10t). ▸ <b>Lectura física.</b> Se suelta 20 cm por <b>encima</b> del equilibrio y en reposo: ese punto es un extremo del movimiento, por eso la amplitud sale directo. Oscila entre 40 cm y 80 cm del techo. ▸ <b>Trampa.</b> Elegir φ₀ = +π/2 en vez de −π/2 es el error que la cátedra marca como el más frecuente: cos φ₀ = 0 deja dos soluciones y hay que descartar la que da A negativa.'},

{st: '<b>2do parcial 2013 · A2 · 26/11/2013 · Curso O1122 · Prof. Patricia Martinelli (UTN FRBA).</b><br>Inicialmente, un cuerpo se encuentra en reposo colgando de un techo, sostenido por un resorte ideal de constante elástica K=100N/m y longitud natural l0=1m. En esas condiciones la longitud del resorte es leq=1.4m. En determinado instante, t=0s, estando el cuerpo en esa posición, se le imprime al mismo una velocidad hacia abajo v0=60cm/s.<br>a) Calcule la masa del cuerpo, y determine la frecuencia angular (o pulsación) y el período del movimiento oscilatorio que se tiene para t&gt;0s.<br>b) Determine la amplitud A y la fase inicial de este movimiento, y escriba las ecuaciones que definen la posición y la velocidad del cuerpo para todo t&gt;0s.',
 ans: 'a) m = 4 kg · ω = 5 s⁻¹ · T ≈ 1,26 s. b) A = 12 cm · φ₀ = −π/2 · x(t) = 12 cm·cos(5 s⁻¹·t − π/2) + 1,4 m · v(t) = −60 cm/s·sen(5 s⁻¹·t − π/2).',
 sol: '<b>Referencia.</b> Eje x con origen en el techo, positivo hacia abajo. ▸ <b>a) Masa.</b> Equilibrio: K(l_eq − l₀) = mg ⟹ m = 100·(1,4 − 1)/10 = 100·0,4/10 = <b>4 kg</b>. <span class="muted">El estiramiento es 0,4 m, no 1,4 m.</span> ▸ ω = √(K/m) = √(100/4) = <b>5 s⁻¹</b>; T = 2π/5 = <b>1,26 s</b>. ▸ <b>b) Convención COSENO</b> (la que usa esta clave): x(t) = A·cos(ωt + φ₀) + x_eq con x_eq = 1,4 m; v(t) = −A·ω·sen(ωt + φ₀). ▸ <b>Condiciones iniciales.</b> x(0) = 1,4 m = x_eq ⟹ cos φ₀ = 0 ⟹ φ₀ = ±π/2. v(0) = +0,60 m/s (hacia abajo = +) ⟹ −A·ω·sen φ₀ &gt; 0 ⟹ sen φ₀ &lt; 0 ⟹ <b>φ₀ = −π/2</b>. ▸ <b>Amplitud.</b> Arranca <b>en el equilibrio</b>, así que x₀′ = 0 y A = v₀/ω = 0,60/5 = <b>0,12 m = 12 cm</b>. ▸ <b>Ecuaciones.</b> x(t) = 12 cm·cos(5t − π/2) + 1,4 m; v(t) = −60 cm/s·sen(5t − π/2). ▸ <b>Chequeo.</b> Oscila entre 1,28 m y 1,52 m; v_máx = 0,12·5 = 0,60 m/s = v₀ ✓. ▸ <b>Nota de método.</b> Si en vez de reconocer que arranca en el equilibrio usás A = √(x₀′² + (v₀/ω)²), acordate de que x₀′ se mide <b>desde el equilibrio</b>: acá x₀′ = 1,4 − 1,4 = 0 y da lo mismo.'},

{st: '<b>2do parcial 2014 · A2 · 29/11/2014 · Curso I1021 · Prof. Patricia Martinelli (UTN.BA).</b><br>Un cuerpo de masa m=2kg, que cuelga de un techo sostenido por un resorte ideal de constante elástica k=50N/m y longitud natural l0=60cm, realiza un movimiento oscilatorio armónico. La mínima distancia del cuerpo al techo es de 80cm.<br>a) Determine la frecuencia angular ω y la amplitud A de dicho movimiento.<br>b) Sabiendo que a t=0s el cuerpo se encontraba a 1m del techo y tenía velocidad hacia abajo, determine la fase inicial φ0 del movimiento, y escriba las ecuaciones que definen la posición y la velocidad del cuerpo para todo t&gt;0s.',
 ans: 'a) ω = 5 rad/s · l_eq = 1 m · A = 20 cm. b) φ₀ = −π/2 · x(t) = 20 cm·cos(5 s⁻¹·t − π/2) + 1 m · v(t) = 1 m/s·cos(5 s⁻¹·t).',
 sol: '<b>Referencia y DCL.</b> Eje x positivo hacia abajo, origen en el techo. DCL: elástica k(l_eq − l₀) hacia arriba, peso mg hacia abajo. ▸ <b>Posición de equilibrio</b> (no la piden pero es indispensable): l_eq = l₀ + mg/k = 0,60 + 20/50 = 0,60 + 0,40 = <b>1 m</b>. ▸ <b>a) Frecuencia.</b> ω = √(k/m) = √(50/2) = √25 = <b>5 rad/s</b>. ▸ <b>Amplitud.</b> "La mínima distancia al techo" es el <b>punto más alto</b> del recorrido, l_mín = 80 cm. Como el centro está en 100 cm: A = l_eq − l_mín = 100 − 80 = <b>20 cm</b>. ▸ <b>b) Convención COSENO:</b> x(t) = A·cos(ωt + φ₀) + l_eq; v(t) = −A·ω·sen(ωt + φ₀). ▸ <b>Condiciones iniciales.</b> x(0) = 1 m = l_eq ⟹ 20 cm·cos φ₀ = 0 ⟹ φ₀ = ±π/2. v(0) &gt; 0 (hacia abajo, sentido +) ⟹ −5·0,2·sen φ₀ &gt; 0 ⟹ sen φ₀ &lt; 0 ⟹ <b>φ₀ = −π/2</b>. ▸ <b>Ecuaciones.</b> x(t) = 20 cm·cos(5t − π/2) + 1 m, que es lo mismo que x(t) = 1 m + 0,2 m·sen(5t); v(t) = −1 m/s·sen(5t − π/2) = <b>1 m/s·cos(5t)</b>. ▸ <b>Chequeo.</b> v(0) = 1 m/s hacia abajo, y v_máx = A·ω = 0,2·5 = 1 m/s: a t = 0 el cuerpo pasa por el equilibrio con velocidad máxima, coherente con haber arrancado en el centro. ▸ <b>Datos que se usan bien.</b> l₀ = 60 cm parece un dato suelto, pero es el que ubica el equilibrio: sin él no hay amplitud. Si tomás 60 cm como centro de la oscilación, la amplitud sale mal.'},

{st: '<b>2do parcial 2015 · A2 · 25/11/2015 · Curso Z1102 · Prof. Patricia Martinelli (UTN FRBA).</b><br>Un cuerpo de masa m=2kg que cuelga de un techo sostenido por un resorte ideal, realiza un movimiento oscilatorio armónico en la dirección vertical. Las longitudes mínima y máxima del resorte son, respectivamente, lmin=40cm y lmax=60cm. La frecuencia angular (o pulsación) del movimiento es ω=10rad/s.<br>a) Determine la amplitud A del movimiento, la constante elástica K del resorte y la velocidad máxima del cuerpo.<br>b) Calcule la longitud natural del resorte, l0.',
 ans: 'a) A = 10 cm = 0,1 m · K = 200 N/m · v_máx = 1 m/s. b) l₀ = 40 cm = 0,4 m.',
 sol: '<b>Referencia.</b> Eje x con origen en el techo, positivo hacia abajo; x(t) = A·cos(ωt + φ₀) + x_eq, v(t) = −A·ω·sen(ωt + φ₀). ▸ <b>a) Amplitud.</b> Como el coseno va entre −1 y 1: l_máx − l_mín = (A + x_eq) − (−A + x_eq) = 2A ⟹ 20 cm = 2A ⟹ <b>A = 10 cm = 0,1 m</b>. ▸ <b>Constante.</b> De ω = √(K/m): K = m·ω² = 2·100 = <b>200 N/m</b>. ▸ <b>Velocidad máxima.</b> v_máx = A·ω = 0,1·10 = <b>1 m/s</b> (= 100 cm/s). ▸ <b>b) Longitud natural.</b> El centro de oscilación es el promedio: x_eq = (60 + 40)/2 = <b>50 cm</b>. En el equilibrio K(x_eq − l₀) = mg ⟹ l₀ = x_eq − mg/K = 0,50 − 20/200 = 0,50 − 0,10 = <b>0,40 m = 40 cm</b>. ▸ <b>La coincidencia peligrosa.</b> l₀ = 40 cm da <b>numéricamente igual</b> a l_mín. Es casualidad: en un resorte vertical la longitud natural NO es el extremo superior del recorrido. Si "acertás" diciendo "l₀ = l_mín", el resultado está bien pero el razonamiento está mal, y en un ejercicio con otros números te va a fallar. ▸ <b>Chequeo.</b> Estiramiento estático = 50 − 40 = 10 cm = mg/K = 20/200 ✓.'},

{st: '<b>2do parcial 2016 · A2 · 14/11/2016 · Curso R1022 · Prof. Patricia Martinelli (UTN.BA).</b> <span class="muted">(Esta fecha no trae solución oficial: la resolución de abajo es propia.)</span><br>Un bloque cuelga de un techo, sostenido por un resorte ideal, de longitud natural l0=1m. Este bloque realiza un movimiento oscilatorio armónico en la dirección vertical, de manera tal que las longitudes mínima y máxima del resorte son lmin=1.2m y lmax=1.6m, respectivamente. La energía mecánica es E=1J.<br>a) Determine la amplitud del movimiento, A, y la constante elástica del resorte, K.<br>b) Calcule la frecuencia angular (o pulsación) del movimiento, ω, y la masa del bloque, m.',
 ans: 'a) A = 0,2 m · K = 50 N/m. b) ω = 5 rad/s (T ≈ 1,26 s) · m = 2 kg.',
 sol: '<b>Referencia.</b> Eje vertical con origen en la <b>posición de equilibrio</b> del bloque, positivo hacia abajo. ▸ <b>a) Amplitud.</b> A = (l_máx − l_mín)/2 = (1,6 − 1,2)/2 = <b>0,2 m</b>. Y el centro: l_eq = (1,6 + 1,2)/2 = 1,4 m, con estiramiento estático δ = l_eq − l₀ = <b>0,4 m</b>. ▸ <b>Constante.</b> Midiendo desde el equilibrio, el peso y la parte constante de la elástica se cancelan y la energía mecánica del oscilador vertical se escribe igual que la del horizontal: E = ½·K·A² ⟹ K = 2E/A² = 2·1/0,04 = <b>50 N/m</b>. ▸ <b>b) Frecuencia.</b> Del equilibrio K·δ = m·g sale m/K = δ/g, así que ω = √(K/m) = √(g/δ) = √(10/0,4) = √25 = <b>5 rad/s</b> (T = 2π/5 ≈ 1,26 s, f ≈ 0,80 Hz). ▸ <b>Masa.</b> m = K/ω² = 50/25 = <b>2 kg</b> (o directo m = K·δ/g = 50·0,4/10 = 2 kg). ▸ <b>Verificación.</b> v_máx = ω·A = 5·0,2 = 1 m/s ⟹ E = ½·m·v_máx² = ½·2·1² = <b>1 J</b> ✓ coincide con el dato. ▸ <b>La trampa del inciso a).</b> Escribir E = ½KA² + mgh, sumando aparte la potencial gravitatoria medida desde la longitud natural, mezcla dos referencias y te da un K equivocado. Con origen en el equilibrio, E = ½KA² es exacta. <span class="muted">Con g = 9,8 daría ω = 4,95 rad/s y m = 2,04 kg; en FRBA se usa g = 10.</span>'},

{st: '<b>Final UTN.BA · Problema 5</b> <span class="muted">(hoja de enunciado sin encabezado visible: la foto recorta la fecha y la grilla de notas)</span>.<br>Una masa m cuelga de un resorte vertical fijo al techo y se encuentra en equilibrio cuando el resorte está elongado 20 cm respecto de su posición natural (posición A). Luego, la masa se eleva suavemente hasta que el resorte recupera su longitud natural y se libera sin velocidad inicial, iniciando un movimiento oscilatorio armónico simple, Despreciando el rozamiento determinar a) la frecuencia de oscilación del sistema, y b) la velocidad de la masa al pasar por la posición A.',
 ans: 'a) ω = 7,07 rad/s ⟹ f ≈ 1,13 Hz (T ≈ 0,889 s). b) v = 1,41 m/s (es la velocidad máxima, porque A es la posición de equilibrio).',
 sol: '<b>Lo primero: no te dan ni m ni k.</b> Y no hacen falta. ▸ <b>Referencia.</b> Eje vertical positivo hacia abajo, origen en la posición A (el equilibrio). ▸ <b>a) Frecuencia.</b> Del equilibrio: k·δ = m·g con δ = 0,20 m ⟹ m/k = δ/g. Entonces ω = √(k/m) = <b>√(g/δ) = √(10/0,20) = √50 = 7,071 rad/s</b>. f = ω/(2π) = 7,071/6,2832 = <b>1,13 Hz</b>; T = 1/f = <b>0,889 s</b>. ▸ <b>b) Amplitud.</b> La masa se lleva hasta la longitud natural, que está <b>20 cm por encima</b> del equilibrio, y se suelta <b>en reposo</b>: ese punto es un extremo ⟹ <b>A = 0,20 m</b>. ▸ <b>Velocidad en A.</b> La posición A es el <b>centro</b> de la oscilación, donde la rapidez es máxima: v = A·ω = 0,20·7,071 = <b>1,414 m/s ≈ 1,41 m/s</b>. ▸ <b>Verificación por energía</b> (con origen en el equilibrio): ½kA² = ½mv² ⟹ v = A√(k/m) = A·ω, lo mismo. ▸ <b>Lo que hace difícil este ejercicio.</b> Parece que faltan datos porque no hay números para m ni k; la clave es ver que el estiramiento estático δ ya contiene la relación m/k, que es lo único que ω necesita. Y notar que "posición A" es el equilibrio, no un extremo: por eso ahí la velocidad es la máxima y no cero.'}

]);


// ============================================================
// EJERCICIOS REALES · SECCIÓN 3 · MAS HORIZONTAL
// 2 ejercicios de parcial (Martinelli) + 3 de final (UTN.BA)
// ============================================================
registerReveals('fisica1-utn-oscilaciones', '3', [

{st: '<b>2do parcial 2011 · A1 · 24/11/2011 · Prof. Patricia Martinelli (UTN FRBA).</b><br>Una masa m=0,1kg, oscila horizontalmente mediante un resorte de constante elástica K=1000N/m, manteniendo constante su energía mecánica en 5J. Haga un esquema donde indique el sistema de referencia que utilizará.<br>a) Escriba las ecuaciones x(t), v(t) y a(t), para este movimiento.<br>b) ¿Qué expresión tiene la fuerza que recibe el cuerpo en función del tiempo?',
 ans: 'ω = 100 s⁻¹ · A = 0,1 m. a) x(t) = 0,1 m·cos(100 s⁻¹·t + φ₀); v(t) = −10 m/s·sen(100 s⁻¹·t + φ₀); a(t) = −1000 m/s²·cos(100 s⁻¹·t + φ₀). b) F(t) = −100 N·cos(100 s⁻¹·t + φ₀). La fase φ₀ queda indeterminada: el enunciado no da condiciones iniciales.',
 sol: '<b>Esquema y referencia.</b> Pared vertical a la izquierda, resorte horizontal, bloque apoyado en superficie horizontal. Eje x hacia la derecha con <b>origen en la posición de equilibrio</b> (que en horizontal coincide con la longitud natural), eje y hacia arriba. ▸ <b>Frecuencia.</b> ω = √(K/m) = √(1000/0,1) = √10000 = <b>100 s⁻¹</b>. ▸ <b>Amplitud desde la energía.</b> En los extremos toda la energía es elástica: E = ½KA² ⟹ A² = 2E/K = 10/1000 = 0,01 m² ⟹ <b>A = 0,1 m = 10 cm</b>. ▸ <b>a) Ecuaciones horarias</b> (convención coseno, medidas desde el equilibrio):<br>x(t) = 0,1 m·cos(100t + φ₀)<br>v(t) = −A·ω·sen(100t + φ₀) = −10 m/s·sen(100t + φ₀)<br>a(t) = −A·ω²·cos(100t + φ₀) = <b>−1000 m/s²</b>·cos(100t + φ₀)<br><span class="muted">Con la variante seno: x = 0,1·sen(100t+φ₀), v = 10·cos(100t+φ₀), a = −1000·sen(100t+φ₀).</span> ▸ <b>b) La fuerza.</b> DCL: en y, N − mg = 0 ⟹ N = 1 N (no hay movimiento vertical). En x la única fuerza es la elástica, así que la resultante es F = m·a(t) = <b>−100 N·cos(100t + φ₀)</b>. Equivalentemente F = −K·x, con amplitud K·A = 1000·0,1 = 100 N. ▸ <b>Sobre φ₀.</b> El enunciado <b>no</b> da posición ni velocidad inicial: la fase queda como constante arbitraria. Escribilo así, o elegí una y justificala. Inventar un número sin decir por qué es lo único que está mal.',
 },

{st: '<b>2do parcial 2011 · A1 · ERRATA de la solución oficial</b> <span class="muted">(mismo enunciado que el ejercicio anterior — leelo como control)</span>.<br>La clave manuscrita de la cátedra escribe, para este ejercicio, a(t) = −1 m/s²·cos(100 s⁻¹·t + φ₀) y F(t) = −0,1 N·cos(100 s⁻¹·t + φ₀). Verificá si esos valores son correctos y, si no lo son, corregilos y explicá con qué chequeo se detecta el error.',
 ans: 'Están mal por un factor 1000. Lo correcto es a_máx = A·ω² = 1000 m/s² y F_máx = K·A = 100 N. El chequeo que lo detecta es F = m·a: 0,1 kg · 1000 m/s² = 100 N.',
 sol: '<b>El cálculo correcto.</b> a_máx = A·ω² = 0,1 m · (100 s⁻¹)² = 0,1 · 10 000 = <b>1000 m/s²</b>. Y F_máx = K·A = 1000 N/m · 0,1 m = <b>100 N</b>. ▸ <b>De dónde sale el error.</b> El manuscrito escribe a_máx = 1 m/s², como si hubiera hecho 0,1 · 10 en lugar de 0,1 · 100² — y después arrastra ese valor a la fuerza: F = m·a = 0,1 · 1 = 0,1 N. Los dos números de la clave están mal, pero son <b>coherentes entre sí</b>, que es lo que hace que el error pase desapercibido. ▸ <b>Los dos chequeos que te salvan.</b><br><b>1)</b> Calculá la fuerza por el camino independiente: <b>F = −K·x</b>, así que la amplitud de la fuerza es K·A = 1000·0,1 = 100 N, sin pasar por la aceleración.<br><b>2)</b> Contrastá con F = m·a: 0,1 · 1000 = 100 N ✓. Si a fuera 1 m/s², F sería 0,1 N, y una fuerza de 0,1 N sobre un resorte de 1000 N/m lo estiraría 0,1 mm, no 10 cm. El absurdo salta solo. ▸ <b>Moraleja para el final.</b> Cuando dos resultados salen del mismo camino de cálculo, un error se propaga sin dejar rastro. Buscá siempre una <b>segunda vía</b> (energía, F = −Kx, F = ma) para cerrar el número.'},

{st: '<b>2do parcial 2017 · A2 · 13/11/2017 · Curso R1022 · Prof. Patricia Martinelli (UTN FRBA).</b><br>Un cuerpo de masa m=0.5kg, realiza un movimiento oscilatorio armónico sobre una superficie horizontal sin rozamiento, unido a uno de los extremos de un resorte ideal. El otro extremo del resorte está unido a una pared fija. Las longitudes mínima y máxima del resorte son, respectivamente, lmin=30cm y lmax=50cm, y la velocidad máxima del cuerpo es vMAX=2m/s.<br>a) Determine la amplitud del movimiento, A, y la longitud natural del resorte, l0.<br>b) Calcule la frecuencia angular (o pulsación) del movimiento, ω, y la constante elástica k del resorte.',
 ans: 'a) A = 10 cm = 0,1 m · l₀ = 40 cm = 0,4 m. b) ω = 20 rad/s · k = 200 N/m.',
 sol: '<b>Referencia.</b> Eje x horizontal hacia la derecha, origen en la posición de equilibrio del bloque. Hipótesis: resorte ideal, superficie sin rozamiento, el peso lo compensa la normal. ▸ <b>a) Amplitud.</b> A = (l_máx − l_mín)/2 = (50 − 30)/2 = <b>10 cm = 0,1 m</b>. ▸ <b>Longitud natural.</b> En horizontal el peso no estira el resorte, así que la posición de equilibrio <b>es</b> la longitud natural, y el equilibrio es el punto medio de la oscilación: l₀ = l_eq = (50 + 30)/2 = <b>40 cm = 0,4 m</b>. ▸ <b>b) Frecuencia.</b> De v_máx = A·ω: ω = v_máx/A = 2/0,1 = <b>20 s⁻¹ (20 rad/s)</b>. <span class="muted">Convertir A a metros antes de dividir; si usás 10 te da ω = 0,2 y k sale mal por 10⁴.</span> ▸ <b>Constante.</b> De ω = √(k/m): k = m·ω² = 0,5·400 = <b>200 N/m</b>. ▸ <b>Datos que no interesan (todavía).</b> La masa no entra en el inciso a): esa parte es puramente geométrica. Recién aparece en b) para pasar de ω a k. Es un ejemplo del "puede haber datos que no interesen" que avisa el encabezado — acá el dato sí sirve, pero no donde uno lo esperaría. ▸ <b>Contraste con el vertical.</b> Si este mismo resorte estuviera colgado, l₀ NO sería 40 cm: habría que restarle mg/k al punto medio.'},

{st: '<b>Final UTN.BA 27/02/2025 · Problema 6.</b><br>Una partícula en un plano horizontal unida a un resorte describe un movimiento armónico simple con una frecuencia de 10 Hz y 5 cm de amplitud. Determine el módulo de la velocidad cuando la elonga[ción] del resorte es de 2.5 cm. <span class="muted">(dato reconstruido: la última palabra del enunciado se corta en el borde derecho de la foto; se lee "la elonga" y el contexto la completa como "elongación")</span>',
 ans: 'v ≈ 2,72 m/s.',
 sol: '<b>Referencia.</b> Eje x horizontal con origen en la posición de equilibrio (= longitud natural, porque es horizontal); la "elongación" es entonces la coordenada x medida desde ahí. ▸ <b>Frecuencia angular.</b> ω = 2π·f = 2π·10 = <b>62,83 rad/s</b>. ▸ <b>Camino 1 — la fórmula directa.</b> v(x) = ω·√(A² − x²) = 62,83·√(0,05² − 0,025²) = 62,83·√(0,0025 − 0,000625) = 62,83·√0,001875 = 62,83·0,04330 = <b>2,72 m/s</b>. ▸ <b>Camino 2 — por energía</b> (por si no te acordás la fórmula): ½kA² = ½kx² + ½mv² ⟹ v² = (k/m)(A² − x²) = ω²(A² − x²), que es lo mismo. ▸ <b>Atajo elegante.</b> Como x = A/2, queda v = ω·A·√(1 − ¼) = v_máx·(√3/2) = 0,866·v_máx, con v_máx = ω·A = 62,83·0,05 = 3,14 m/s ⟹ v = <b>2,72 m/s</b>. A la mitad de la amplitud todavía conservás el <b>87%</b> de la rapidez máxima: el MAS pierde velocidad muy despacio cerca del centro y muy rápido cerca de los extremos. ▸ <b>Trampas.</b> No confundir <b>frecuencia f (Hz)</b> con <b>frecuencia angular ω (rad/s)</b>: si usás 10 en vez de 62,83 el resultado sale 6,3 veces más chico. Y pasar los cm a metros antes de restar.'},

{st: '<b>Final UTN.BA 21/02/2024 · Problema 3.</b> <span class="muted">(el encabezado imprime "Para todos los ejercicios use g = 10 m/s²"; el día de la fecha está manuscrito y podría ser 21 o 24)</span><br>Un bloque de masa M = 10kg descansa sobre una superficie sin fricción y está conectado a un resorte horizontal con una constante k = 4N/m. El otro extremo del resorte está fijo a una pared. Un segundo bloque de masa m = 2kg está sobre el primero. El coeficiente de fricción estática entre los bloques es μe = 0,1. Determine la amplitud de oscilación máxima que hace que el bloque superior no resbale.',
 ans: 'A_máx = 3 m (con ω² = k/(M+m) = 1/3 s⁻² y a_máx = μe·g = 1 m/s²).',
 sol: '<b>Referencia y DCL.</b> Eje x horizontal en el sentido del movimiento. DCL del bloque de <b>arriba</b> (m): peso mg hacia abajo, normal N = mg hacia arriba, y la <b>única</b> fuerza horizontal es el <b>rozamiento estático</b> que le hace el bloque de abajo. ▸ <b>Paso 1 — la condición física.</b> El de arriba se mueve porque el rozamiento lo arrastra. Ese rozamiento tiene un techo: f ≤ μe·N = μe·m·g. Y como f = m·a: <b>a ≤ μe·g = 0,1·10 = 1 m/s²</b>. La masa se cancela: la aceleración máxima que el rozamiento puede imponer no depende de m. ▸ <b>Paso 2 — la frecuencia del sistema.</b> Mientras no resbalen, los dos bloques oscilan <b>juntos</b> como un solo cuerpo de masa M + m: ω² = k/(M + m) = 4/12 = <b>1/3 s⁻²</b>. ▸ <b>Paso 3 — atar amplitud con aceleración.</b> En un MAS la aceleración máxima es a_máx = A·ω². Igualando con el límite del paso 1:<br>A·ω² = μe·g ⟹ <b>A_máx = μe·g/ω² = 1/(1/3) = 3 m</b>. ▸ <b>Los tres errores.</b> (1) Usar ω² = k/M olvidando la masa de arriba: el sistema que oscila son los dos. (2) Confundir a_máx (1 m/s²) con la amplitud. (3) Plantear el rozamiento sobre el bloque de abajo en vez del de arriba: sobre el de arriba es la única fuerza horizontal, y por eso el planteo sale en una línea. ▸ <b>Chequeo de razonabilidad.</b> Un resorte muy blando (4 N/m) con 12 kg oscila lentísimo: T = 2π/ω = 2π·√3 ≈ 10,9 s. Con aceleraciones tan chicas, una amplitud de 3 m es coherente.'},

{st: '<b>Final UTN.BA · Problema 3</b> <span class="muted">(hoja de enunciado sin encabezado visible: la foto recorta la fecha)</span>.<br>Un bloque de masa m1 = 6 kg desliza por una superficie horizontal sin rozamiento con una velocidad v0 = 3 m/s. En cierto instante choca con otro bloque de masa m2 = 12 kg que está unido a un resorte de constante elástica k = 300 N/m, el cual posee, en el instante del choque, su longitud natural y su otro extremo está fijo a una pared. Después del choque el bloque de masa m1 retrocede con una velocidad de módulo 1 m/s. Calcule la amplitud de las oscilaciones que realiza el cuerpo m2 después del choque.',
 ans: 'v₂ = 2 m/s después del choque · ω = 5 rad/s · A = 0,4 m = 40 cm.',
 sol: '<b>El problema tiene dos etapas y hay que separarlas.</b> ▸ <b>Etapa 1 — el choque.</b> Es instantáneo y el resorte está en su longitud natural, así que no ejerce fuerza: se conserva la <b>cantidad de movimiento</b>. Eje x en el sentido de v₀:<br>m₁v₀ = m₁v₁′ + m₂v₂ ⟹ 6·3 = 6·(−1) + 12·v₂ ⟹ 18 + 6 = 12·v₂ ⟹ <b>v₂ = 2 m/s</b>.<br><span class="muted">El signo menos en v₁′ es lo que decide el ejercicio: "retrocede" significa que m₁ vuelve, o sea velocidad negativa. Si le ponés +1, te da v₂ = 1 m/s y A = 0,2 m, mal.</span> ▸ <b>Etapa 2 — el MAS.</b> ω = √(k/m₂) = √(300/12) = √25 = <b>5 rad/s</b>. El bloque m₂ arranca <b>en la posición de equilibrio</b> (el resorte está sin deformar en el instante del choque) con velocidad v₂: por lo tanto v₂ es la velocidad máxima y<br><b>A = v₂/ω = 2/5 = 0,4 m = 40 cm</b>. ▸ <b>Verificación por energía.</b> Justo después del choque toda la energía de m₂ es cinética: E = ½·12·2² = 24 J. En el extremo toda es elástica: 24 = ½·300·A² ⟹ A² = 0,16 ⟹ A = 0,4 m ✓. ▸ <b>Por qué NO se conserva la energía en el choque.</b> Ec inicial = ½·6·9 = 27 J; Ec después = ½·6·1 + ½·12·4 = 3 + 24 = 27 J. Da igual, así que este choque resultó <b>elástico</b> — pero eso es una consecuencia de los números, no algo que puedas suponer de entrada. Siempre arrancá por cantidad de movimiento.'}

]);


// ============================================================
// EJERCICIOS REALES · SECCIÓN 4 · PÉNDULOS (todos de FINAL)
// ============================================================
registerReveals('fisica1-utn-oscilaciones', '4', [

{st: '<b>Final UTN.BA 02/03/2023 · Problema 5.</b> <span class="muted">(el encabezado de esa hoja imprime: "Utilice, donde lo necesite, I(CM) disco = m R²/2, I(CM) barra = m L²/12")</span><br>Con una barra y un disco se construye un dispositivo para un reloj de péndulo antiguo. La barra tiene una longitud L = 2 m y una masa m_b = 0,8 kg. El disco es homogéneo, de masa m_d = 1,2 kg y radio r = 0,15 m. Si la distancia a entre el punto de suspensión y el centro del disco es de 1,67 m, halle el período de oscilación del péndulo.',
 ans: 'I = 4,427 kg·m² · d = 1,402 m · M = 2 kg · T ≈ 2,50 s.',
 sol: '<b>Es un péndulo FÍSICO</b> (cuerpo rígido colgado de un punto que no es su CM), así que T = 2π√(I/(M·g·d)) y hay que armar tres cosas: I respecto del pivote, la masa total M y la distancia d del pivote al CM del conjunto. ▸ <b>1) Momento de inercia respecto del punto de suspensión O</b> (extremo superior de la barra), con Steiner en cada pieza:<br>· <b>Barra</b> (CM en L/2 = 1 m): I_b = m_b·L²/12 + m_b·(L/2)² = 0,8·4/12 + 0,8·1² = 0,2667 + 0,8 = <b>1,0667 kg·m²</b> <span class="muted">(el clásico m_b L²/3)</span><br>· <b>Disco</b> (CM a a = 1,67 m): I_d = m_d·r²/2 + m_d·a² = 1,2·0,0225/2 + 1,2·2,7889 = 0,0135 + 3,3467 = <b>3,3602 kg·m²</b><br>· <b>Total:</b> I = 1,0667 + 3,3602 = <b>4,4268 kg·m²</b> ▸ <b>2) Masa total.</b> M = 0,8 + 1,2 = <b>2 kg</b>. ▸ <b>3) Distancia al centro de masa del conjunto.</b><br>d = (m_b·L/2 + m_d·a)/M = (0,8·1 + 1,2·1,67)/2 = (0,8 + 2,004)/2 = <b>1,402 m</b> ▸ <b>4) Período.</b><br>T = 2π√(I/(M·g·d)) = 2π√(4,4268/(2·10·1,402)) = 2π√(4,4268/28,04) = 2π√0,15788 = 2π·0,39734 = <b>2,50 s</b> ▸ <b>Chequeos.</b> Un péndulo <b>simple</b> de longitud 1,402 m daría T = 2π√(1,402/10) = 2,35 s: el físico oscila un poco <b>más lento</b>, como corresponde a un cuerpo con masa repartida. Si te diera <b>menos</b>, revisá Steiner. ▸ <b>Los errores que matan este ejercicio.</b> (1) Usar T = 2π√(l/g) con l = 2 m o l = 1,67 m: esa fórmula es para masa puntual. (2) Poner d = 1,67 m (la distancia al disco) en vez de 1,402 m: te da T = 2,29 s. (3) Olvidar el término m_d·a² del disco: es 250 veces más grande que m_d r²/2 y sin él el I sale 4 veces más chico.'},

{st: '<b>Final UTN.BA · Problema 4</b> <span class="muted">(hoja compuesta en LaTeX, sin encabezado ni fecha visible en la foto)</span>.<br>Un péndulo ideal de longitud l = 2,5 m tiene un extremo atado al techo y del otro extremo cuelga una masa puntual encontrándose en equilibrio; en esas condiciones se le imprime una velocidad inicial hacia la derecha de v0 = 0,4 m/s. Eligiendo el sentido positivo del apartamiento hacia la derecha, calcule la amplitud angular y la fase inicial, suponiendo que el apartamiento del equilibrio es proporcional a cos(ω t + φ).',
 ans: 'ω = 2 rad/s (T = π s ≈ 3,14 s) · θ_máx = 0,08 rad ≈ 4,58° · φ₀ = −π/2.',
 sol: '<b>Es el mismo esquema del masa-resorte, con θ en vez de x.</b> ▸ <b>Referencia.</b> θ mide el apartamiento angular desde la vertical, <b>positivo hacia la derecha</b> (lo fija el enunciado). Hipótesis: cuerda ideal, masa puntual, amplitud chica (sen θ ≈ θ). ▸ <b>1) Frecuencia angular.</b> ω = √(g/l) = √(10/2,5) = √4 = <b>2 rad/s</b>. T = 2π/ω = <b>π s ≈ 3,14 s</b>. <span class="muted">Fijate que la masa no aparece: por eso el enunciado ni te la da.</span> ▸ <b>2) La convención te la dictan.</b> El enunciado dice "proporcional a cos(ωt + φ)", así que:<br>θ(t) = θ_máx·cos(ωt + φ₀) &nbsp;·&nbsp; θ̇(t) = −θ_máx·ω·sen(ωt + φ₀) ▸ <b>3) Condiciones iniciales.</b> Arranca <b>en el equilibrio</b>: θ(0) = 0 ⟹ cos φ₀ = 0 ⟹ φ₀ = ±π/2.<br>La velocidad de la masa es tangencial: v = l·θ̇, así que θ̇(0) = v₀/l = 0,4/2,5 = <b>+0,16 rad/s</b> (positiva, porque va hacia la derecha).<br>θ̇(0) = −θ_máx·ω·sen φ₀ &gt; 0 ⟹ sen φ₀ &lt; 0 ⟹ <b>φ₀ = −π/2</b>. ▸ <b>4) Amplitud angular.</b> θ_máx = θ̇(0)/ω = 0,16/2 = <b>0,08 rad</b>, o sea 0,08·180/π = <b>4,58°</b>. ▸ <b>5) Respuesta escrita.</b> θ(t) = 0,08 rad·cos(2 s⁻¹·t − π/2), que es lo mismo que θ(t) = 0,08·sen(2t). ▸ <b>Chequeos.</b> 4,58° es un ángulo chico: la hipótesis sen θ ≈ θ es válida (el error es menor al 0,1%). Y la máxima separación horizontal de la masa es l·θ_máx = 2,5·0,08 = 0,2 m. ▸ <b>Trampa.</b> Confundir la velocidad lineal v₀ = 0,4 m/s con la angular: <b>θ̇ = v/l</b>. Si metés 0,4 directo en lugar de 0,16, la amplitud angular te da 0,2 rad (11,5°) — cinco veces más grande.'},

{st: '<b>Final UTN.BA 12/12/2023 · Problema 3.</b><br>Un proyectil de masa m₁ = 0,5 kg con una velocidad de modulo v₀ = 8 m/s impacta horizontalmente en un péndulo ideal de masa m₂ = 20 kg y longitud l = 3 m, que se encuentra inicialmente en reposo en su posición de equilibrio. Después del choque el proyectil no queda adherido a la masa del péndulo y este realiza oscilaciones con una amplitud angular de 3°. Calcule la perdida de energía en el choque.',
 ans: 'v₂ = 0,287 m/s (péndulo) · v₁′ = −3,47 m/s (el proyectil rebota) · ΔE ≈ 12,2 J perdidos.',
 sol: '<b>Este es el uso que la cátedra le da al péndulo: es un medidor de velocidad.</b> Hay que ir <b>al revés</b>: de la amplitud angular sacar la velocidad del péndulo, y recién ahí plantear el choque. ▸ <b>Paso 1 — de la amplitud angular a la velocidad.</b> Después del choque el péndulo sale del equilibrio con v₂ y sube hasta que θ = 3°. Conservación de energía en el péndulo:<br>½·m₂·v₂² = m₂·g·l·(1 − cos 3°) ⟹ v₂² = 2·g·l·(1 − cos 3°)<br>cos 3° = 0,998630 ⟹ 1 − cos 3° = 0,0013695<br>v₂² = 2·10·3·0,0013695 = 0,08217 ⟹ <b>v₂ = 0,2867 m/s</b><br><span class="muted">La altura que sube es h = l(1 − cos 3°) = 4,11 mm. Con la aproximación de ángulo chico h ≈ lθ²/2 = 3·(0,05236)²/2 = 4,11 mm: da lo mismo hasta la tercera cifra.</span> ▸ <b>Paso 2 — el choque (cantidad de movimiento).</b> El proyectil <b>no</b> queda adherido, así que hay dos velocidades finales. El choque es instantáneo (la gravedad y la tensión no alcanzan a impulsar nada):<br>m₁v₀ = m₁v₁′ + m₂v₂ ⟹ 0,5·8 = 0,5·v₁′ + 20·0,2867<br>4 = 0,5·v₁′ + 5,733 ⟹ 0,5·v₁′ = −1,733 ⟹ <b>v₁′ = −3,47 m/s</b><br>El signo negativo dice que <b>el proyectil rebota</b>: sale para atrás a 3,47 m/s. Es un resultado sorprendente pero es el que exige el momento: 20 kg moviéndose a 0,287 m/s ya se llevan más cantidad de movimiento (5,73 kg·m/s) que la que traía el proyectil (4 kg·m/s). ▸ <b>Paso 3 — la energía perdida.</b><br>Ec inicial = ½·0,5·8² = <b>16 J</b><br>Ec final = ½·0,5·(3,466)² + ½·20·(0,2867)² = 3,004 + 0,822 = <b>3,83 J</b><br><b>ΔE = 16 − 3,83 ≈ 12,2 J</b> de energía perdida en el choque. ▸ <b>Trampas.</b> (1) Suponer que el proyectil <b>queda incrustado</b>: el enunciado dice explícitamente que no, y con choque plástico la respuesta cambia por completo. (2) Usar h = l·cos α o l·sen α: la altura que sube es <b>l(1 − cos α)</b>. (3) Olvidar la energía cinética que se lleva el proyectil rebotado (3 J de los 3,83 J finales): si la salteás, la pérdida te da 15,2 J.'}

]);
