registerExercises('psicologia', '1', [
  {st: 'Para Bleger, el objeto de estudio de la psicología como ciencia es:', opts: ['El alma', 'La mente aislada del cuerpo', 'La conducta del ser humano como totalidad en situación', 'El cerebro'], c: 2, ex: 'En <i>Psicología de la conducta</i> (1963), Bleger define la psicología como ciencia cuyo objeto es la conducta humana: lo que la persona hace en tanto ser concreto que vive en una situación.'},
  {st: 'Las tres áreas de la conducta según Bleger son:', opts: ['Icc, Pcc, Cc', 'Mente, cuerpo y mundo externo', 'Pasada, presente y futura', 'Oral, anal y fálica'], c: 1, ex: 'Bleger distingue área 1 (mente: pensamientos, fantasías), área 2 (cuerpo: fenómenos corporales) y área 3 (mundo externo: actuación). En toda conducta coexisten las tres, aunque una predomine.'},
  {st: 'La diferencia entre conducta molar y molecular refiere a:', opts: ['Cuerpo vs. mente', 'Consciente vs. inconsciente', 'Unidades amplias de significado vs. elementos discretos', 'Individuo vs. grupo'], c: 2, ex: 'Molar = unidades amplias ("hizo una escena", "está deprimido"). Molecular = elementos discretos (un gesto, una palabra). Son dos niveles de análisis, no dos tipos de conducta.'},
  {st: 'El concepto de "campo" en Bleger es tomado de:', opts: ['Pavlov', 'Kurt Lewin', 'Skinner', 'Watson'], c: 1, ex: 'Bleger toma de Kurt Lewin la idea de campo como organización dinámica de relaciones entre el sujeto y su mundo. Toda conducta debe entenderse en su campo, no aisladamente.'},
  {st: 'Bleger critica el dogmatismo porque:', opts: ['Limita el pensamiento científico y la práctica profesional', 'Es incompatible con la religión', 'Es inevitable en toda ciencia', 'Favorece al paciente'], c: 0, ex: 'Bleger sostiene que ser psicólogo no es adherir a una escuela única. Requiere integrar teoría y práctica, tolerar ansiedades y trabajar en equipo. El instrumento es la propia personalidad del profesional.'},
  {st: '¿Cuál de estas afirmaciones es correcta sobre la conducta según Bleger?', opts: ['Hay conductas absurdas, sin sentido', 'Toda conducta es comprensible si se la sitúa en su contexto', 'Solo las conductas observables son conducta', 'La mente y la conducta son opuestas'], c: 1, ex: 'Para Bleger no hay conducta absurda: solo conducta cuyo sentido no se ha descifrado. Toda conducta es comprensible si se la sitúa en su contexto.'}
]);

registerExercises('psicologia', '2', [
  {st: 'Skinner rechaza los términos mentalistas ("mente", "voluntad") porque:', opts: ['No existen subjetivamente', 'No son verificables experimentalmente', 'Son religiosos', 'Fueron inventados por Freud'], c: 1, ex: 'Skinner no niega la vida interna: sostiene que no es objeto de ciencia porque no se puede medir intersubjetivamente. Es una posición metodológica, no metafísica.'},
  {st: 'La diferencia central entre condicionamiento clásico y operante es que:', opts: ['El clásico usa animales; el operante, humanos', 'El clásico asocia estímulos; el operante asocia conducta con su consecuencia', 'El clásico es más moderno', 'El operante es involuntario'], c: 1, ex: 'Clásico (Pavlov): asocia un estímulo nuevo con uno que ya produce la respuesta. Operante (Skinner): asocia una conducta con su consecuencia. El operante refiere a respuestas voluntarias.'},
  {st: 'El refuerzo negativo consiste en:', opts: ['Aplicar un castigo', 'Retirar un estímulo aversivo tras la conducta, aumentándola', 'Quitar algo agradable', 'Nada, es lo mismo que castigo'], c: 1, ex: 'Refuerzo negativo: se <b>retira</b> un estímulo aversivo y la conducta <b>aumenta</b>. Ejemplo: dejar de taladrar cuando el niño se acuesta. Refuerzo = aumenta; negativo = se retira algo.'},
  {st: '¿Cuál de estos ejemplos es castigo negativo?', opts: ['Pegarle al niño', 'Gritarle', 'Sacarle el celular', 'Darle un caramelo'], c: 2, ex: 'Castigo negativo: se retira un estímulo agradable y la conducta disminuye. Sacar el celular es el ejemplo típico. No confundir "negativo" con "malo": indica retirar, no agregar.'},
  {st: 'Los programas de reforzamiento intermitente producen:', opts: ['Aprendizaje más lento pero más resistente a la extinción', 'Aprendizaje más rápido y más frágil', 'Ausencia de aprendizaje', 'Solo conductas reflejas'], c: 0, ex: 'Con refuerzo continuo el aprendizaje es rápido pero se extingue rápido. Con intermitente es más lento, pero la conducta resiste mucho más a la extinción. Base de conductas persistentes (apuestas, etc.).'},
  {st: 'El moldeamiento (shaping) consiste en:', opts: ['Cambiar la forma del estímulo', 'Reforzar aproximaciones sucesivas a la conducta meta', 'Castigar toda conducta incorrecta', 'Ignorar la conducta'], c: 1, ex: 'El shaping refuerza acercamientos progresivos a la conducta meta. Base del entrenamiento de animales y de muchas intervenciones educativas y clínicas.'}
]);

registerExercises('psicologia', '3', [
  {st: 'En <i>Tótem y tabú</i> (1913), Freud sostiene que la cultura nace de:', opts: ['El amor mutuo entre los hombres', 'El contrato social racional', 'El asesinato del padre de la horda y la culpa consecuente', 'Un decreto divino'], c: 2, ex: 'Freud imagina una horda dominada por un padre violento. Los hijos lo matan y devoran. La culpa lleva a instituir las dos prohibiciones universales: parricidio e incesto. El padre muerto es más fuerte que el padre vivo.'},
  {st: 'Las dos prohibiciones universales que surgen tras el asesinato del padre son:', opts: ['Robar y mentir', 'Parricidio e incesto', 'Adorar imágenes y trabajar en sábado', 'Comer carne y beber alcohol'], c: 1, ex: 'Tras matar al padre, los hijos instituyen: 1) no matar al tótem (sustituto del padre), 2) no unirse con las mujeres del clan. De ahí la ley y el lazo social.'},
  {st: 'Según Lacan, la demanda se distingue de la necesidad porque:', opts: ['Es más intensa', 'Está articulada en palabra y dirigida al Otro, excediendo siempre al objeto', 'Es inconsciente', 'Es exclusiva de los animales'], c: 1, ex: 'La necesidad es exigencia biológica (hambre, frío). La demanda es esa necesidad puesta en palabra y dirigida al Otro: siempre demanda también amor, más allá del objeto concreto.'},
  {st: 'El deseo, en Lacan, es:', opts: ['Sinónimo de necesidad intensa', 'El residuo entre demanda y lo que la necesidad podía saturar; inconsciente e insatisfecho', 'Un producto de la educación', 'Una necesidad fisiológica'], c: 1, ex: 'El deseo se distingue de la necesidad. Es el resto entre lo que se pide y lo que se necesita: inconsciente, insatisfecho, indestructible. No se satura con ningún objeto.'},
  {st: 'El Nombre-del-Padre, para Lacan:', opts: ['Es el padre biológico', 'Es el apellido paterno', 'Es el operador simbólico que corta la relación dual madre-hijo e introduce la ley', 'Es lo mismo que el Superyó'], c: 2, ex: 'El Nombre-del-Padre es un significante que transmite la prohibición del incesto y habilita al sujeto a desear fuera de la madre. No se identifica con el padre biológico ni con su apellido: es función simbólica.'},
  {st: 'La forclusión del Nombre-del-Padre, en Lacan, se asocia con fenómenos de:', opts: ['Neurosis', 'Psicosis (alucinaciones, delirio, certeza)', 'Timidez', 'Alegría'], c: 1, ex: 'Si el Nombre-del-Padre no opera (forclusión), la ley no se inscribe y sobrevienen fenómenos psicóticos. Por eso la función paterna no es "tener papá": es que alguien/algo opere el corte simbólico.'}
]);

registerExercises('psicologia', '4', [
  {st: 'En la primera tópica freudiana (1900), los sistemas son:', opts: ['Ello, Yo, Superyó', 'Inconsciente, Preconsciente, Consciente', 'Oral, anal, fálica', 'Neurosis, psicosis, perversión'], c: 1, ex: 'Primera tópica: Icc (reprimido, proceso primario), Pcc (accesible), Cc (percepción actual). La segunda tópica (1923) introduce Ello/Yo/Superyó. Son dos modelos complementarios, no sucesivos.'},
  {st: 'Entre los caracteres del inconsciente NO se encuentra:', opts: ['Atemporalidad', 'Ausencia de contradicción', 'Ausencia de negación', 'Principio de realidad'], c: 3, ex: 'El Icc se rige por el principio de placer, no el de realidad. Sus caracteres son atemporalidad, ausencia de contradicción, ausencia de negación y proceso primario (condensación y desplazamiento).'},
  {st: 'La represión primaria (originaria):', opts: ['Opera sobre recuerdos adultos', 'Es constitutiva del Icc y establece el primer núcleo reprimido', 'Es un mecanismo de defensa menor', 'Solo opera en neurosis obsesiva'], c: 1, ex: 'La represión primaria es el acto fundacional que constituye el Icc. La represión secundaria opera sobre retoños o derivados de ese núcleo primario ya reprimido.'},
  {st: 'En la segunda tópica, el Ello se caracteriza por ser:', opts: ['Consciente', 'Moral y crítico', 'Inconsciente total, pulsional, regido por el principio de placer', 'Heredero del Edipo'], c: 2, ex: 'El Ello es reservorio pulsional, totalmente inconsciente, principio de placer puro. El Yo media; el Superyó es heredero del Edipo y función moral.'},
  {st: 'El Superyó, según Freud, es:', opts: ['Totalmente consciente', 'Heredero del complejo de Edipo e instancia moral mayormente inconsciente', 'Sinónimo del Yo', 'Parte del Ello'], c: 1, ex: 'El Superyó es mayoritariamente inconsciente, heredero del Edipo. Es la instancia moral, ideal del yo y función crítica. Se forma al sepultarse el Edipo.'},
  {st: 'Los mecanismos de defensa del Yo fueron sistematizados por:', opts: ['Sigmund Freud', 'Anna Freud', 'Melanie Klein', 'Donald Winnicott'], c: 1, ex: 'Anna Freud (hija de Freud) sistematizó los mecanismos defensivos: represión, proyección, formación reactiva, racionalización, desplazamiento, sublimación, identificación con el agresor, regresión, aislamiento, anulación.'}
]);

registerExercises('psicologia', '5', [
  {st: 'Winnicott acuña la expresión "madre suficientemente buena" para indicar que:', opts: ['Toda madre es insuficiente', 'La madre debe ser perfecta', 'La frustración óptima es constitutiva: la madre se adapta al bebé pero falla gradualmente para permitir la diferenciación', 'Solo la madre biológica sirve'], c: 2, ex: 'Good enough mother: se adapta casi totalmente al principio y va fallando en grado dosificable. La frustración óptima es constitutiva, no dañina: permite que el bebé se diferencie.'},
  {st: 'Holding (sostén) y handling (manejo), en Winnicott, se diferencian en que:', opts: ['Son sinónimos', 'Holding es contención psíquica-emocional; handling es el cuidado físico concreto', 'Holding es solo para bebés varones', 'Handling reemplaza al holding'], c: 1, ex: 'Holding: función psíquica de contener, ofrecer entorno emocional previsible. Handling: cuidado físico (bañar, vestir, alimentar). Ambos, junto con la presentación del objeto, constituyen el marco constitutivo del sí-mismo.'},
  {st: 'El objeto transicional, para Winnicott, es:', opts: ['El primer objeto interno del bebé', 'El primer objeto "no-yo" que el bebé ama y posee: osito, manta, chupete', 'Un concepto psicoanalítico descartado', 'La madre biológica'], c: 1, ex: 'El objeto transicional no es puro mundo interno ni pura realidad externa: ocupa un espacio entre ambos. Es precursor de la simbolización, la creatividad y la cultura.'},
  {st: 'La "paradoja" del objeto transicional consiste en que:', opts: ['Aparece y desaparece', 'Es a la vez creado y encontrado: no hay que preguntarle al bebé cuál de las dos', 'Es invisible', 'Solo existe en la adultez'], c: 1, ex: 'El objeto transicional es creado por el bebé y a la vez encontrado (la madre lo pone a disposición). La paradoja es constitutiva: no se resuelve, se sostiene.'},
  {st: 'El espacio potencial es:', opts: ['Solo una metáfora sin uso clínico', 'Una tercera zona entre el mundo interno y el externo donde ocurren el juego, el arte, la cultura y la religión', 'El espacio físico del consultorio', 'El útero materno'], c: 1, ex: 'El espacio potencial es una tercera zona: ni pura fantasía ni pura realidad. Allí se despliega la experiencia creativa. Sin espacio potencial no hay cultura posible.'},
  {st: 'El self falso, en Winnicott, surge cuando:', opts: ['Hay exceso de espacio potencial', 'La madre sostiene muy bien', 'La madre no sostiene adecuadamente y el bebé se adapta a las demandas del entorno, protegiendo al verdadero', 'Se juega demasiado'], c: 2, ex: 'Self verdadero: organización espontánea del sentirse vivo. Self falso: adaptación protectora cuando falla el holding. En exceso, deja al sujeto "viviendo una vida que no es la suya".'}
]);

registerExercises('psicologia', '6', [
  {st: 'El Complejo de Edipo se despliega, según Freud, entre:', opts: ['0 y 2 años (fase oral)', '3 y 5-6 años (fase fálica)', '8 y 10 años', 'La adolescencia'], c: 1, ex: 'El Edipo coincide con la fase fálica (3-5/6 años). Su resolución marca el paso al período de latencia (6 años a pubertad), donde los deseos edípicos quedan reprimidos.'},
  {st: 'El sepultamiento del Edipo (Freud, 1924) ocurre por:', opts: ['Olvido evolutivo natural', 'Amenaza de castración que fuerza la renuncia a los objetos edípicos', 'Intervención educativa', 'Maduración biológica'], c: 1, ex: 'Freud aclara que el Edipo no desaparece por olvido: es sepultado, reprimido activamente bajo la amenaza de castración. Es un acto psíquico, no un proceso madurativo.'},
  {st: 'El Superyó, en el esquema freudiano, es:', opts: ['Una instancia externa', 'Heredero del complejo de Edipo', 'Sinónimo del Ello', 'Una estructura exclusivamente femenina'], c: 1, ex: 'Al sepultar el Edipo, el niño introyecta la ley parental. El Superyó es heredero de los objetos edípicos: lo antes amado y temido se convierte en instancia interna de exigencia y castigo.'},
  {st: 'La castración, en el psicoanálisis freudiano, es:', opts: ['Un hecho físico', 'Una operación simbólica', 'Un rito religioso', 'Una enfermedad del varón'], c: 1, ex: 'La castración no es hecho físico: es operación simbólica. En el niño opera como amenaza. Lecturas posteriores (feminista, lacaniana) la reformulan como falta simbólica que afecta a ambos sexos.'},
  {st: 'La amnesia infantil, según Freud, es prueba de:', opts: ['Daño cerebral en la infancia', 'El inconsciente y la represión: los primeros años quedan olvidados por represión activa', 'Inmadurez cerebral', 'Un fenómeno sin importancia'], c: 1, ex: 'Tras el sepultamiento del Edipo sobreviene la amnesia infantil. No es ausencia de memoria: es represión de lo edípico. Es una de las pruebas más contundentes del inconsciente, según Freud.'},
  {st: 'La lectura lacaniana del Edipo lo entiende como:', opts: ['Un evento evolutivo biológico', 'Una estructura simbólica: la inscripción del Nombre-del-Padre y el corte de la ley', 'Un ritual religioso', 'Un mito superado'], c: 1, ex: 'Lacan desbiologiza el Edipo: lo central es la inscripción del Nombre-del-Padre como corte simbólico que introduce la ley. Es estructura, no evento del desarrollo.'}
]);

registerExercises('psicologia', '7', [
  {st: 'El DSM-5 TR (2022) es:', opts: ['Una ley argentina', 'El Manual Diagnóstico y Estadístico de los Trastornos Mentales, publicado por la American Psychiatric Association', 'Un manual europeo', 'Un test proyectivo'], c: 1, ex: 'DSM-5 TR (Text Revision, 2022) actualiza la DSM-5 (2013). Es el sistema de clasificación más utilizado. Alternativa: CIE-11 de la OMS, con clasificación similar pero no idéntica.'},
  {st: 'El cluster B de los trastornos de personalidad agrupa:', opts: ['Paranoide, esquizoide, esquizotípico', 'Antisocial, límite, histriónico, narcisista', 'Evitativo, dependiente, obsesivo-compulsivo', 'Depresivo, maníaco, bipolar'], c: 1, ex: 'Cluster A (raro/excéntrico): paranoide, esquizoide, esquizotípico. Cluster B (dramático/errático): antisocial, límite (TLP), histriónico, narcisista. Cluster C (ansioso/temeroso): evitativo, dependiente, obsesivo-compulsivo.'},
  {st: 'El Trastorno Antisocial de la Personalidad (TAP) en DSM-5 TR requiere:', opts: ['Ser menor de 18 años', 'Ser mayor de 18 años y haber tenido evidencia de trastorno de conducta antes de los 15', 'Haber cometido un delito grave', 'Diagnóstico exclusivo en varones'], c: 1, ex: 'El TAP exige ≥ 3 criterios (incumplimiento de normas, deshonestidad, impulsividad, agresividad, imprudencia, irresponsabilidad, ausencia de remordimiento), mayor de 18 años, trastorno de conducta antes de los 15, y no debido a esquizofrenia ni episodio maníaco.'},
  {st: 'La diferencia central entre TAP (DSM) y psicopatía (PCL-R) es que:', opts: ['Son sinónimos', 'El TAP incluye dimensión afectiva; la psicopatía no', 'La psicopatía agrega dimensión afectiva e interpersonal (empatía ausente, manipulación, frialdad)', 'Solo TAP puede diagnosticarse en mujeres'], c: 2, ex: 'El TAP se basa en conductas observables. La psicopatía (PCL-R de Hare) añade dimensión afectiva e interpersonal. La psicopatía es más restringida (~15-25% de los TAP) y con respuesta muy limitada al tratamiento.'},
  {st: 'El tratamiento de referencia para el Trastorno Límite de la Personalidad (TLP) es:', opts: ['Psicoanálisis freudiano clásico', 'Terapia dialéctico-conductual (Linehan)', 'Medicación única', 'Internación permanente'], c: 1, ex: 'La DBT (Marsha Linehan) es el tratamiento de referencia para el TLP: inestabilidad en relaciones, autoimagen, afectos, impulsividad marcada, miedo al abandono, conductas autolesivas, ira inapropiada, sensación crónica de vacío.'},
  {st: 'La personalidad, en psicopatología, se define como:', opts: ['Un trastorno leve', 'Un patrón estable de pensar, sentir y relacionarse', 'Sinónimo de psicopatía', 'Algo que solo algunos tienen'], c: 1, ex: 'La personalidad es un patrón estable. El trastorno de personalidad es ese patrón vuelto inflexible y desadaptativo, estable en el tiempo, que aparta al sujeto de las expectativas culturales y genera malestar o disfuncionalidad.'}
]);

registerExercises('psicologia', '8', [
  {st: 'La victimología es:', opts: ['La disciplina que estudia al delincuente', 'La disciplina que estudia a la víctima, sus características, el proceso de victimización y la reparación', 'El derecho penal aplicado', 'Una rama del derecho civil'], c: 1, ex: 'La victimología estudia a la víctima, sus características, la victimogénesis (factores que la vuelven víctima), la victimodinámica (proceso concreto) y las políticas de reparación.'},
  {st: 'Hans von Hentig y Benjamin Mendelsohn son:', opts: ['Filósofos griegos', 'Pioneros de la victimología científica (años 40-50)', 'Juristas argentinos', 'Psiquiatras actuales'], c: 1, ex: 'Von Hentig y Mendelsohn fundan la victimología científica en los 40-50. Von Hentig propuso tipologías de víctimas y la idea de pareja penal. Sus categorías hoy son criticadas por culpabilizar a la víctima, pero inauguraron el campo.'},
  {st: 'La "pareja penal" de von Hentig refiere a:', opts: ['Dos delincuentes que actúan juntos', 'La diada víctima-victimario que explica mejor el hecho que cada uno por separado', 'El matrimonio del acusado', 'La fiscalía y la defensa'], c: 1, ex: 'La pareja penal es categoría analítica: víctima y victimario forman una diada. No es juicio moral ni afirma que "la víctima se lo buscó": es marco para entender la dinámica del hecho.'},
  {st: 'La victimización secundaria se refiere al daño producido por:', opts: ['El hecho delictivo mismo', 'Las instituciones que debían asistir a la víctima (policía, justicia, medios)', 'Los vecinos', 'Problemas económicos posteriores'], c: 1, ex: 'Primaria: daño directo del hecho. Secundaria: daño adicional de las instituciones (revictimización). Terciaria: estigmatización y efectos a largo plazo en vida social, laboral, familiar. La secundaria es especialmente grave en delitos sexuales.'},
  {st: 'La "indefensión aprendida" es un concepto asociado a:', opts: ['Freud', 'Seligman', 'Bleger', 'Winnicott'], c: 1, ex: 'Seligman: tras intentos fallidos repetidos, la persona deja de intentar escapar aun cuando hay salidas. Concepto clave para entender la pasividad en víctimas de violencia prolongada.'},
  {st: 'La visión contemporánea de la víctima en victimología la concibe como:', opts: ['Derrotada y pasiva', 'Culpable de lo sucedido', 'Sujeto sufriente activo que puede reconstruirse, con derecho a reconocimiento, autonomía y reparación', 'Testigo incidental'], c: 2, ex: 'La victimología moderna rechaza tratar a la víctima como "derrotada". Es sujeto activo, sufriente pero con capacidad de reconstrucción. El profesional debe ofrecer cuidado, no sospecha: reconocimiento, autonomía, reparación.'}
]);
