registerExercises('led-finales', '1', [
  {st: 'El final de LED tiene 10 ejercicios. ¿Cuántos hay que tener correctos para aprobar?', opts: ['5', '6 ejercicios correctos', 'Los 10', '8'], c: 1, ex: 'La consigna explícita: "PARA APROBAR ES NECESARIO TENER 6 EJERCICIOS CORRECTOS". No hay puntaje parcial: cada ítem es 1 ó 0.'},
  {st: 'En el final, dejar una pregunta en blanco es:', opts: ['Mejor que arriesgar', 'Equivalente a marcar mal (ambos = 0)', 'Te da medio punto', 'Te penaliza con −0.5'], c: 1, ex: 'Sin marca = 0, marca incorrecta = 0. Como no hay penalidad, siempre conviene arriesgar incluso con baja confianza.'},
  {st: 'Estrategia óptima si descartaste 2 de 4 opciones:', opts: ['Dejar en blanco', 'Elegir la primera de las dos restantes', 'Elegir la que parezca más probable; tenés 50% de chance', 'Marcar las dos'], c: 2, ex: 'Cuando reducís a 2, tenés 50% de probabilidad. Eso es valor esperado positivo. Marcar dos opciones invalida el ítem.'},
  {st: 'Las preguntas 1–2 del final típicamente son sobre:', opts: ['Lógica y cuantificadores', 'Recurrencias', 'Grafos', 'Grupos'], c: 0, ex: 'Las primeras dos preguntas suelen ser de lógica/cuantificadores: simbolización, razonamientos válidos, valor de verdad de proposiciones cuantificadas.'},
  {st: 'Si en una pregunta del final ves la palabra "siempre" o "nunca", ¿qué hacés?', opts: ['Aceptás de entrada porque es categórico', 'Buscás un contraejemplo: si lo encontrás, descartás esa opción', 'La marcás como correcta', 'La salteás'], c: 1, ex: 'Las afirmaciones absolutas se refutan con un solo contraejemplo. Antes de aceptar "siempre", probá 2-3 casos puntuales mentalmente.'}
]);

registerExercises('led-finales', '2', [
  {st: '"Todos los aspirantes trajeron DNI" se simboliza como:', opts: ['∀x: A(x) ∧ D(x)', '∀x: A(x) → D(x)', '∃x: A(x) ∧ D(x)', '∃x: A(x) → D(x)'], c: 1, ex: '"Todos los X son Y" usa CONDICIONAL: ∀x: X(x) → Y(x). La conjunción ∀x: A(x) ∧ D(x) significaría "todo objeto del universo es aspirante Y trajo DNI", que es absurdo.'},
  {st: '"Algún sillón es cómodo" se simboliza:', opts: ['∀x: S(x) → C(x)', '∃x: S(x) ∧ C(x)', '∃x: S(x) → C(x)', '∀x: S(x) ∨ C(x)'], c: 1, ex: '"Algún X es Y" usa CONJUNCIÓN: ∃x: X(x) ∧ Y(x). El condicional ∃x: S(x) → C(x) es trivialmente verdadero (basta tomar x que NO sea sillón) y no expresa la idea.'},
  {st: 'De ∀x: ∃y: p(x,y) verdadera se deduce:', opts: ['∃y: ∀x: p(x,y)', '∀x: ∀y: p(x,y)', '∃x: ∃y: p(x,y) (si U≠∅)', 'Nada'], c: 2, ex: 'La premisa garantiza que para CADA x hay algún y. Tomando un x cualquiera, ∃y: p(x,y), por lo tanto ∃x ∃y. Las opciones a) y b) son MÁS FUERTES y no se deducen.'},
  {st: 'Si r: ∀x: ∀y: p(x,y) es Verdadera, ¿cuál NO se puede asegurar?', opts: ['∃x: ∃y: p(x,y)', '∀y: ∀x: p(x,y)', '∃x: ∀y: ¬p(x,y)', '∀x: ∃y: p(x,y)'], c: 2, ex: 'Si vale para todo par (x,y), no puede haber un x donde TODA y falle. Las opciones a, b, d se deducen. La c) se contradice con r.'},
  {st: 'Razonamiento "Algunos A son B. Todos los B son C. ⊢ Algunos A son C" es:', opts: ['Inválido', 'Válido (silogismo categórico clásico)', 'Solo válido si A = B', 'Inválido por equivocación de cuantificadores'], c: 1, ex: 'Por PE: existe a con A(a) ∧ B(a). De B(a) y la premisa universal: C(a). Entonces A(a) ∧ C(a), por GE: ∃x: A(x) ∧ C(x). Válido.'},
  {st: 'La negación de "∀x: ∃y: p(x,y)" es:', opts: ['∃x: ∀y: ¬p(x,y)', '∀x: ∃y: ¬p(x,y)', '∃x: ∃y: ¬p(x,y)', '∀x: ∀y: p(x,y)'], c: 0, ex: 'Negar cuantificadores: ¬∀x → ∃x; ¬∃y → ∀y; y la proposición se niega. Resultado: ∃x: ∀y: ¬p(x,y).'}
]);

registerExercises('led-finales', '3', [
  {st: 'R ∩ S, donde R y S son ambas relaciones de equivalencia, es:', opts: ['Siempre de equivalencia', 'Nunca de equivalencia', 'Solo si R ⊆ S', 'Solo si tienen mismas clases'], c: 0, ex: 'Reflexividad, simetría y transitividad se preservan al intersecar relaciones. Si (a,b) ∈ R∩S, está en ambas, y todo lo que se deduce vale en ambas. R ∩ S siempre es de equivalencia.'},
  {st: 'R ∪ S, ambas de equivalencia, es de equivalencia:', opts: ['Siempre', 'Nunca', 'Solo si R∘S = S∘R (o R⊆S, o S⊆R)', 'Solo si R = S'], c: 2, ex: 'Reflexiva y simétrica se preservan en la unión. Pero la transitividad NO en general. La condición exacta es R∘S = S∘R o que una contenga a la otra.'},
  {st: '(D₄₀, |) con D₄₀ = {1,2,4,5,8,10,20,40} es:', opts: ['Álgebra de Boole', 'Conjunto totalmente ordenado', 'Red distributiva pero no complementada (4 no tiene complemento)', 'Isomorfa a (D₃₀, |)'], c: 2, ex: '40 = 2³·5 NO es libre de cuadrados. Es red distributiva (operaciones MCD/MCM) pero no complementada: el 4 no tiene complemento. NO isomorfa a D₃₀ (que sí es Boole).'},
  {st: '¿Cuál se puede demostrar por inducción completa? P1: ∀x ∈ ℝ: x≥0 ⇒ x² ≥ x. P2: ∀n ∈ ℕ: 1+2ⁿ ≤ 3ⁿ. P3: ∀n ∈ ℕ: n+2ⁿ = 3ⁿ.', opts: ['Las tres', 'Solo P1', 'Solo P2', 'P1 y P3'], c: 2, ex: 'P1 es en reales (no se hace inducción en reales). P3 es falsa: con n=2 da 2+4=6 ≠ 9. P2 es la única verdadera y en naturales. Caso base 1+2≤3 ✓; HI 1+2ʰ≤3ʰ; TI 1+2ʰ⁺¹ = 1+2·2ʰ ≤ 1+2(3ʰ) ≤ 3·3ʰ = 3ʰ⁺¹.'},
  {st: 'Si A es un conjunto, |P(A)| = ?', opts: ['|A|', '|A|²', '2^|A|', '|A|!'], c: 2, ex: 'Cantidad de subconjuntos de A = 2^|A|. Cada elemento puede o no estar en cada subconjunto.'},
  {st: 'Sea R definida en P(A) por X R Y ⇔ X ⊆ Y. ¿Qué propiedades tiene?', opts: ['Reflexiva, antisimétrica, transitiva (orden parcial)', 'Equivalencia', 'Solo simétrica', 'No es de orden'], c: 0, ex: 'X ⊆ X (refl). X ⊆ Y ∧ Y ⊆ X ⇒ X = Y (antisim). X ⊆ Y ∧ Y ⊆ Z ⇒ X ⊆ Z (trans). Es ORDEN PARCIAL (NO total: P(A) tiene elementos incomparables si |A|≥2).'}
]);

registerExercises('led-finales', '4', [
  {st: 'Juan trabaja 8 hs extra en 5 días, al menos 1 por día (hasta 4). ¿De cuántas formas?', opts: ['8! / 5!', 'C(7,3) = 35', 'C(8,5)', '8⁵'], c: 1, ex: 'Asigno 1 hora a cada uno de los 5 días (5 hs). Quedan 3 hs libres, sin restricción de máximo (3 ≤ 4). Combinaciones con repetición C\'(5,3) = C(7,3) = 35.'},
  {st: '¿De cuántas formas se reparten 25 paquetes idénticos a 12 familias, cada una recibe al menos uno?', opts: ['C(24, 11)', '12²⁵', '25! / 12!', 'C(25, 12)'], c: 0, ex: 'Asigno 1 a cada familia → quedan 13 libres entre 12. Combinaciones con repetición C\'(12, 13) = C(13+12−1, 13) = C(24, 13) = C(24, 11).'},
  {st: 'La ecuación 72x ≡ 54 (126) tiene cuántas soluciones principales?', opts: ['1', '7', '18 (porque MCD(72,126)=18 y 18|54)', 'No tiene solución'], c: 2, ex: 'MCD(72,126): 126=72·1+54; 72=54·1+18; 54=18·3+0. MCD=18. 18|54 ✓. Hay exactamente 18 soluciones principales mod 126.'},
  {st: 'V o F: si ∃ s, t ∈ ℤ: 3 = a·s + b·t entonces MCD(a,b) = 3.', opts: ['V siempre', 'F. Lo correcto: MCD(a,b) | 3, así que MCD ∈ {1, 3}', 'V solo si a y b son positivos', 'F: MCD(a,b) ≥ 3'], c: 1, ex: 'Por Bezout, MCD(a,b) | (a·s + b·t) = 3, así que MCD divide a 3, es decir MCD ∈ {1, 3}. Ej: a=1, b=0, 3 = 1·3 + 0·t. MCD(1,0) = 1 ≠ 3.'},
  {st: 'Halle el resto de dividir 22³⁰ por 5.', opts: ['1', '4', '0', '3'], c: 0, ex: '22 ≡ 2 (5). Entonces 22³⁰ ≡ 2³⁰ (5). Por Fermat (o calculando): 2⁴ ≡ 1 (5). 30 = 4·7 + 2, así que 2³⁰ ≡ 2² ≡ 4 (5). Wait — 4 no es 1; revisa cuidadosamente. 22 mod 5 = 2. 2² = 4, 2⁴ = 16 ≡ 1 (5). 30 = 4·7 + 2 → 2³⁰ ≡ 2² = 4 (5). Resto = 4.'},
  {st: 'Anagramas de FELICIDADES (11 letras: F-E-L-I-C-I-D-A-D-E-S).', opts: ['11!', '11! / (2!·2!·2!) (E×2, I×2, D×2)', '11! / 8!', '11! · 8'], c: 1, ex: 'Letras repetidas: E (2), I (2), D (2). Permutaciones con repetición: 11! / (2!·2!·2!) = 11! / 8 = 4 989 600.'}
]);

registerExercises('led-finales', '5', [
  {st: 'Dada aₙ₊₁ − 4aₙ = −6·2ⁿ, la sucesión aₙ = 3·2ⁿ es:', opts: ['Solución general', 'Solución particular (verifica la recurrencia pero no tiene parámetro libre)', 'NO es solución', 'Solución de la homogénea'], c: 1, ex: 'Verifico: 3·2^(n+1) − 4·3·2ⁿ = 6·2ⁿ − 12·2ⁿ = −6·2ⁿ ✓. Pero la solución general tiene 1 parámetro libre (orden 1): aₙ = α·4ⁿ + 3·2ⁿ. Sin α, es solo PARTICULAR.'},
  {st: 'Recurrencia con característica r² − 5r + 6 = 0 tiene raíces:', opts: ['r = 2 y r = 3', 'r = 5 y r = 6', 'r = 1 y r = 6', 'r doble r = 5/2'], c: 0, ex: '(r−2)(r−3) = r² − 5r + 6. Raíces 2 y 3 distintas. Solución general homogénea: α·2ⁿ + β·3ⁿ.'},
  {st: 'INV(ℤ₈, ·) tiene cuántos elementos y es cíclico?', opts: ['4 elementos, cíclico', '4 elementos {1,3,5,7}, NO cíclico (cada uno tiene orden 2)', '8 elementos cíclico', 'φ(8) = 4 elementos, sí cíclico generado por 3'], c: 1, ex: 'INV(ℤ₈) = {1,3,5,7}. 3²=9=1, 5²=25=1, 7²=49=1. Cada elemento NO trivial tiene orden 2 → NO cíclico. ≅ ℤ₂×ℤ₂.'},
  {st: '"H = {x ∈ ℤ : x = 3a + 5b, a, b ∈ ℤ} es subgrupo de (ℤ, +)". V o F:', opts: ['F, no es cerrado', 'V. Por Bezout MCD(3,5)=1, así que H = ℤ', 'V solo si a, b > 0', 'F'], c: 1, ex: 'MCD(3,5)=1, por Bezout existen s,t enteros con 3s+5t=1. Por lo tanto, todo entero se escribe como combinación lineal entera de 3 y 5. H = ℤ → subgrupo trivial total.'},
  {st: 'En INV(ℤ₉, ·), 2 es generador. ¿Cuál es el orden del subgrupo ⟨2³⟩?', opts: ['6', '3 (porque 2³ = 8 y |⟨8⟩| = 6/MCD(3,6) = 2)', '2', '1'], c: 2, ex: 'INV(ℤ₉) = ⟨2⟩ es cíclico de orden 6. ⟨2³⟩ tiene orden 6/MCD(3,6) = 6/3 = 2. Entonces 2³ = 8, y ⟨8⟩ = {1, 8}.'},
  {st: 'La red de subgrupos de un grupo cíclico de orden 12 es isomorfa a:', opts: ['(D₁₂, |)', '(P({a,b,c}), ⊆)', '(ℤ₁₂, +)', 'Ninguna anterior'], c: 0, ex: 'Para un grupo cíclico de orden n, la red de subgrupos es isomorfa a (D_n, |). D₁₂ = {1,2,3,4,6,12}, 6 divisores → 6 subgrupos.'}
]);

registerExercises('led-finales', '6', [
  {st: 'ES FALSO que existe un grafo G con A=4 y V=5 tal que:', opts: ['Sea simple y no conexo', 'Sea conexo, simple y sin aristas puente', 'Sea conexo y tenga camino de Euler', 'Tenga 3 vértices colgantes'], c: 1, ex: 'Conexo con 4 aristas y 5 vértices ⇒ A = V−1 ⇒ es ÁRBOL ⇒ todas las aristas son puentes. Imposible que sea conexo y SIN aristas puente. Las otras propiedades son realizables.'},
  {st: 'Suma de grados en un grafo simple = ', opts: ['|V|', '|A|', '2·|A| (handshaking)', '|V|·|A|'], c: 2, ex: 'Cada arista contribuye 2 al total de grados (una para cada extremo). Por lo tanto ∑grados = 2|A|. Esto implica que la cantidad de vértices de grado impar es par.'},
  {st: 'Un grafo simple con V=20 y A=170 ¿es necesariamente conexo?', opts: ['Sí siempre', 'No: 170 ≤ 171 = C(19,2), puede ser K₁₉ + vértice aislado', 'Solo si es bipartito', 'Solo si todos los grados son ≥ 2'], c: 1, ex: 'C(V−1, 2) = C(19,2) = 171. Si A ≤ 171, puede no ser conexo. Solo cuando A > 171 es necesariamente conexo. Con A=170 no se garantiza.'},
  {st: 'Un grafo conexo tiene camino de Euler si:', opts: ['Tiene 0 ó 2 vértices de grado impar', 'Todos los vértices tienen grado par', 'Tiene exactamente un vértice de grado impar', 'Es bipartito'], c: 0, ex: 'Teorema de Euler: el grafo conexo tiene CAMINO de Euler ⇔ 0 ó 2 vértices de grado impar. Si 0 → CIRCUITO de Euler. Si 2 → camino abierto entre los dos vértices de grado impar.'},
  {st: 'Un árbol binario regular con 7 vértices internos tiene cuántas hojas?', opts: ['7', '8 (i+1 con i=7)', '14', '15'], c: 1, ex: 'En árbol binario regular, hojas = i + 1, total = 2i + 1. Aquí i=7, hojas=8, total=15.'},
  {st: 'Un árbol binario regular puede tener exactamente 7 vértices en total?', opts: ['Sí', 'No (total = 2i+1 → 7 = 2i+1 → i=3 internos, 4 hojas, total 7. Sí es posible)', 'Solo si es balanceado', 'No, mínimo 8'], c: 0, ex: 'Total = 2i + 1 con i = internos. Para total 7: i = 3, hojas = 4. SÍ es posible (ej: raíz con 2 hijos cada uno con 2 hijos hojas, falta uno → 3 internos, 4 hojas).'}
]);

registerExercises('led-finales', '7', [
  {st: '(Final 19/02/2024) ¿De cuántas formas se hacen 8 hs extra L–V con al menos 1 por día y máximo 4 por día?', opts: ['25', '35', '40', '56'], c: 1, ex: 'Asigno 1 a cada día (5 hs ya distribuidas). Me quedan 3 hs libres entre 5 días sin restricción de máx (3 ≤ 4). C\'(5,3) = C(7,3) = 35. Ojo: si quedaran más de 4 hs por día habría que descontar; con 3 no.'},
  {st: '(Final 19/02/2024) (D₄₀, |) es:', opts: ['Álgebra de Boole', 'Red isomorfa a (D₃₀, |)', 'Conjunto totalmente ordenado', 'Red distributiva pero no complementada'], c: 3, ex: 'D₄₀={1,2,4,5,8,10,20,40}. 40=2³·5 NO libre de cuadrados → NO Álgebra de Boole. NO totalmente ordenado (2 y 5 incomparables). NO isomorfa a D₃₀ (esa SÍ es Boole). Distributiva por ser red de divisores, NO complementada (4 sin complemento).'},
  {st: 'En el final clásico: ax ≡ b(n) tiene 18 soluciones principales. ¿Cuál es la condición?', opts: ['MCD(a,n) = 18 y 18 | b', 'a = 18 y b = 18', 'n = 18', 'MCD(a,b) = 18'], c: 0, ex: 'La cantidad de soluciones principales es MCD(a,n) cuando este divide a b. La condición es exactamente MCD(a,n) = 18 y 18 | b.'},
  {st: 'Dada aₙ₊₁ − 4aₙ = −6·2ⁿ, ¿qué tipo de sucesión es aₙ = 3·2ⁿ?', opts: ['Solución general', 'Solución particular', 'No es solución', 'Solución de la homogénea'], c: 1, ex: 'Verifica la recurrencia (sí es solución) pero no tiene parámetro libre, así que NO es general. La general sería α·4ⁿ + 3·2ⁿ. Por lo tanto, particular.'},
  {st: 'Estrategia de tiempo para el final de 2 horas:', opts: ['Resolver en orden estricto del 1 al 10', 'Pasada 1 (30 min) seguros, pasada 2 (60 min) dudosos, pasada 3 (30 min) revisar', 'Empezar por las difíciles', 'Saltarse las V/F'], c: 1, ex: 'La estrategia óptima es: primero resolver todo lo seguro (cubrís 6+ rápido), luego dedicar tiempo a las dudosas, y dejar 30 min finales para revisión y NO dejar en blanco.'},
  {st: '"R y T son simétricas ⇒ R ∩ T es simétrica" es:', opts: ['Verdadero (demostrable)', 'Falso, hace falta contraejemplo', 'Solo si R = T', 'Solo si R ⊆ T'], c: 0, ex: 'Si (a,b) ∈ R ∩ T, entonces (a,b) ∈ R y (a,b) ∈ T. Por simetría de cada una, (b,a) ∈ R y (b,a) ∈ T → (b,a) ∈ R ∩ T. ✓ La intersección preserva la simetría.'}
]);
