registerExercises('led-finales', '1', [
  {st: 'El final de LED tiene 10 ejercicios. ¿Cuántos hay que tener correctos para aprobar?', opts: ['5', '6 ejercicios correctos', 'Los 10', '8'], c: 1, ex: 'Consigna explícita: "PARA APROBAR ES NECESARIO TENER 6 EJERCICIOS CORRECTOS". No hay puntaje parcial: cada ítem es 1 punto si está bien, 0 si está mal o en blanco. ▸ Por qué las otras están mal: (A) "5" sería 50% (insuficiente); (C) "los 10" exige perfección innecesaria; (D) "8" sería 80% (más alto que el mínimo).'},
  {st: 'En el final, dejar una pregunta en blanco es:', opts: ['Mejor que arriesgar', 'Equivalente a marcar mal (ambos = 0)', 'Te da medio punto', 'Te penaliza con −0.5'], c: 1, ex: 'Sin marca = 0 puntos. Marca incorrecta = 0 puntos. Como no hay penalidad por equivocarse, SIEMPRE conviene arriesgar (incluso 25% de chance ciega es mejor que 0% garantizado). ▸ Por qué las otras están mal: (A) "mejor que arriesgar" es contraintuitivo; (C) (D) inventan medios puntos / penalizaciones que no existen.'},
  {st: 'Estrategia óptima si descartaste 2 de 4 opciones:', opts: ['Dejar en blanco', 'Elegir la primera de las dos restantes', 'Elegir la que parezca más probable; tenés 50% de chance', 'Marcar las dos opciones'], c: 2, ex: 'Cuando reducís a 2, tenés 50% de chance. Valor esperado: 0,5·1 = 0,5 (positivo) vs 0 si dejás en blanco. ▸ Por qué las otras están mal: (A) en blanco garantiza 0; (B) "primera" arbitrariamente es peor que evaluar; (D) marcar dos invalida el ítem.'},
  {st: 'Las preguntas 1–2 del final típicamente son sobre:', opts: ['Lógica y cuantificadores (simbolización, razonamientos, valor de verdad)', 'Recurrencias', 'Grafos', 'Grupos'], c: 0, ex: 'Las primeras dos preguntas suelen ser de lógica/cuantificadores (simbolización, razonamientos válidos, valor de verdad). El final tiene una estructura predecible. ▸ Por qué las otras están mal: (B) recurrencias suelen aparecer hacia la mitad; (C) grafos van al final; (D) grupos también al final.'},
  {st: 'Si en una pregunta del final ves la palabra "siempre" o "nunca", ¿qué hacés?', opts: ['Aceptás de entrada porque es categórico', 'Buscás un contraejemplo: si lo encontrás, descartás esa opción', 'La marcás como correcta', 'La salteás'], c: 1, ex: 'Las afirmaciones absolutas ("siempre", "nunca") se REFUTAN con UN solo contraejemplo. ▸ Antes de aceptar "siempre" probá 2-3 casos puntuales mentalmente. ▸ Por qué las otras están mal: (A) (C) aceptan sin verificar (peligroso); (D) saltearse pierde el ítem garantizado.'}
]);

registerExercises('led-finales', '2', [
  {st: '"Todos los aspirantes trajeron DNI" se simboliza como:', opts: ['∀x: A(x) ∧ D(x)', '∀x: A(x) → D(x)', '∃x: A(x) ∧ D(x)', '∃x: A(x) → D(x)'], c: 1, ex: '"Todos los X son Y" usa CONDICIONAL: ∀x: X(x) → Y(x). ▸ Si fuera ∀x: A(x) ∧ D(x), significaría "TODO objeto del universo es aspirante Y trajo DNI" (incluso piedras y libros), absurdo. ▸ Por qué las otras están mal: (A) ∀∧ tiene esa interpretación absurda; (C) ∃∧ es "algún aspirante trajo DNI"; (D) ∃→ es trivialmente verdadero (basta tomar algo NO aspirante).'},
  {st: '"Algún sillón es cómodo" se simboliza:', opts: ['∀x: S(x) → C(x)', '∃x: S(x) ∧ C(x)', '∃x: S(x) → C(x)', '∀x: S(x) ∨ C(x)'], c: 1, ex: '"Algún X es Y" usa CONJUNCIÓN: ∃x: X(x) ∧ Y(x) ("existe algo que es X y además es Y"). ▸ El condicional ∃x: S(x) → C(x) es trivialmente verdadero (basta tomar x que NO sea sillón → S(x) falso → condicional verdadero). ▸ Por qué las otras están mal: (A) ∀→ es "Todos los sillones son cómodos"; (C) trivial verdadero; (D) ∀∨ no expresa la idea.'},
  {st: 'De ∀x: ∃y: p(x,y) verdadera se deduce:', opts: ['∃y: ∀x: p(x,y) (mismo y para todo x)', '∀x: ∀y: p(x,y) (todos los pares)', '∃x: ∃y: p(x,y) (si U≠∅)', 'Nada con seguridad'], c: 2, ex: 'La premisa garantiza que para CADA x hay ALGÚN y (que puede depender de x). Tomando un x cualquiera, ∃y: p(x,y) → ∃x∃y: p(x,y). ▸ Por qué las otras están mal: (A) cambiar el orden ∃y∀x exige un MISMO y para todo x (más fuerte); (B) ∀x∀y exige TODOS los pares (más fuerte aún); (D) sí se puede deducir lo de C.'},
  {st: 'Si r: ∀x: ∀y: p(x,y) es Verdadera, ¿cuál NO se puede asegurar?', opts: ['∃x: ∃y: p(x,y)', '∀y: ∀x: p(x,y)', '∃x: ∀y: ¬p(x,y)', '∀x: ∃y: p(x,y)'], c: 2, ex: 'Si r es V, todos los pares cumplen p. Por lo tanto NO puede haber un x donde TODA y falle (eso contradice r). ▸ Por qué las otras están bien: (A) ∃x∃y se sigue de ∀x∀y (asumiendo U≠∅); (B) cambiar orden de cuantificadores universales es válido; (D) "∀x∃y" es más débil y se sigue de "∀x∀y".'},
  {st: 'Razonamiento "Algunos A son B. Todos los B son C. ⊢ Algunos A son C" es:', opts: ['Inválido', 'Válido (silogismo categórico clásico)', 'Solo válido si A = B', 'Inválido por equivocación de cuantificadores'], c: 1, ex: 'Premisas: ∃x: A(x)∧B(x); ∀x: B(x)→C(x). ▸ De la 1ª por PE: existe a con A(a)∧B(a). ▸ De la 2ª aplicada a a: B(a)→C(a). Como B(a) → C(a). ▸ Tengo A(a)∧C(a) → por GE: ∃x: A(x)∧C(x). VÁLIDO (silogismo "Darii"). ▸ Por qué las otras están mal: (A) (D) descartan la validez sin justificar; (C) no requiere A=B.'},
  {st: 'La negación de "∀x: ∃y: p(x,y)" es:', opts: ['∃x: ∀y: ¬p(x,y)', '∀x: ∃y: ¬p(x,y)', '∃x: ∃y: ¬p(x,y)', '∀x: ∀y: p(x,y)'], c: 0, ex: 'Negar cuantificadores: cada ∀ pasa a ∃ y viceversa, la proposición interna se niega. ▸ ¬(∀x: ∃y: p) = ∃x: ¬(∃y: p) = ∃x: ∀y: ¬p. ▸ Por qué las otras están mal: (B) no cambió el primer cuantificador; (C) no cambió ninguno; (D) no negó nada.'}
]);

registerExercises('led-finales', '3', [
  {st: 'R ∩ S, donde R y S son ambas relaciones de equivalencia, es:', opts: ['Siempre de equivalencia', 'Nunca de equivalencia', 'Solo si R ⊆ S', 'Solo si tienen mismas clases'], c: 0, ex: 'La INTERSECCIÓN preserva las 3 propiedades: ▸ Reflexiva: si (a,a)∈R y (a,a)∈S → (a,a)∈R∩S. ▸ Simétrica: si (a,b)∈R∩S, está en ambas → (b,a)∈ambas → (b,a)∈R∩S. ▸ Transitiva: similar. ▸ Por qué las otras están mal: (B) NUNCA es absurdo; (C) (D) no requiere condiciones extra.'},
  {st: 'R ∪ S, ambas de equivalencia, es de equivalencia:', opts: ['Siempre', 'Nunca', 'Solo si R∘S = S∘R (o una contiene a la otra)', 'Solo si R = S'], c: 2, ex: 'Reflexiva y simétrica se preservan en la unión. Pero la transitividad NO en general (puede haber a R b ∈ R y b S c ∈ S sin que aRc ni aSc). La condición exacta es R∘S = S∘R o R⊆S o S⊆R. ▸ Por qué las otras están mal: (A) "siempre" es falso (la transitividad puede fallar); (B) "nunca" es absurdo; (D) R=S es muy restrictivo.'},
  {st: '(D₄₀, |) con D₄₀ = {1,2,4,5,8,10,20,40} es:', opts: ['Álgebra de Boole', 'Conjunto totalmente ordenado', 'Red distributiva pero NO complementada (4 no tiene complemento)', 'Isomorfa a (D₃₀, |)'], c: 2, ex: '40 = 2³·5. NO es libre de cuadrados. ▸ Es red distributiva (operaciones MCD/MCM) pero NO complementada: ¿complemento de 4? Necesita c con MCD(4,c)=1 (c impar) Y MCM(4,c)=40 → c|40 y c·4/MCD=40 → no existe. ▸ Por qué las otras están mal: (A) NO es Boole (4 sin complemento); (B) 2 y 5 son incomparables → no es total; (D) D₃₀ es Boole, D₄₀ no, no son isomorfas.'},
  {st: '¿Cuál se puede demostrar por inducción completa? P1: ∀x∈ℝ: x≥0 ⇒ x²≥x. P2: ∀n∈ℕ: 1+2ⁿ ≤ 3ⁿ. P3: ∀n∈ℕ: n+2ⁿ = 3ⁿ.', opts: ['Las tres', 'Solo P1', 'Solo P2', 'P1 y P3'], c: 2, ex: '▸ P1 está en ℝ → la inducción NO se aplica a reales (sólo a ℕ). ▸ P3 es FALSA: con n=2 da 2+4=6 ≠ 9. ▸ P2 es la única VERDADERA y en ℕ. Caso base 1+2=3 ≤ 3 ✓; HI 1+2ʰ ≤ 3ʰ; TI: 1+2ʰ⁺¹ = 1 + 2·2ʰ ≤ 1 + 2(3ʰ−1) ≤ 3·3ʰ = 3ʰ⁺¹. ▸ Por qué las otras están mal: incluyen P1 (fuera de ℕ) o P3 (falsa).'},
  {st: 'Si A es un conjunto, |P(A)| = ?', opts: ['|A|', '|A|²', '2^|A|', '|A|!'], c: 2, ex: 'P(A) es el conjunto de todos los subconjuntos de A. Cada elemento de A puede o no estar en cada subconjunto → 2 opciones por elemento → 2^|A| subconjuntos en total. ▸ Por qué las otras están mal: (A) |A| sería el cardinal de A; (B) (D) no surgen del conteo.'},
  {st: 'Sea R definida en P(A) por X R Y ⇔ X ⊆ Y. ¿Qué propiedades tiene?', opts: ['Reflexiva, antisimétrica, transitiva (orden parcial)', 'Equivalencia (ref+sim+trans)', 'Solo simétrica', 'No es de orden'], c: 0, ex: 'Verifico: ▸ X ⊆ X ✓ (reflexiva). ▸ X ⊆ Y ∧ Y ⊆ X ⇒ X = Y ✓ (antisimétrica). ▸ X ⊆ Y ∧ Y ⊆ Z ⇒ X ⊆ Z ✓ (transitiva). ▸ ORDEN PARCIAL (NO total: si |A|≥2, hay subconjuntos incomparables como {a} y {b}). ▸ Por qué las otras están mal: (B) NO es simétrica (X⊆Y ≠ Y⊆X en general); (C) (D) descartan propiedades que sí cumple.'}
]);

registerExercises('led-finales', '4', [
  {st: 'Juan trabaja 8 hs extra en 5 días, al menos 1 por día (hasta 4). ¿De cuántas formas?', opts: ['8! / 5!', 'C(7,3) = 35', 'C(8,5)', '8⁵'], c: 1, ex: 'Asigno 1 a cada uno de los 5 días (5 hs distribuidas). Quedan 3 hs libres entre 5 días, sin restricción de máx (3 ≤ 4 cada uno). ▸ Combinaciones con repetición: C\'(5,3) = C(5+3−1, 3) = C(7, 3) = 35. ▸ Por qué las otras están mal: (A) 8!/5! cuenta variaciones ordenadas; (C) C(8,5) elige sin repetición; (D) 8⁵ asume distinguibles las horas (variaciones con rep).'},
  {st: '¿De cuántas formas se reparten 25 paquetes idénticos a 12 familias, cada una recibe al menos uno?', opts: ['C(24, 11)', '12²⁵', '25! / 12!', 'C(25, 12)'], c: 0, ex: '"Al menos uno" → asigno 1 a cada familia (12 paquetes) → quedan 13 libres entre 12 familias. ▸ Combinaciones con repetición: C\'(12, 13) = C(12+13−1, 13) = C(24, 13) = C(24, 11). ▸ Por qué las otras están mal: (B) 12²⁵ trataría paquetes como distinguibles; (C) 25!/12! no aplica (paquetes idénticos); (D) C(25,12) elige sin repartir.'},
  {st: 'La ecuación 72x ≡ 54 (126) tiene cuántas soluciones principales?', opts: ['1', '7', '18 (porque MCD(72,126)=18 y 18|54)', 'No tiene solución'], c: 2, ex: 'Algoritmo: ▸ MCD(72, 126): 126 = 72·1 + 54; 72 = 54·1 + 18; 54 = 18·3 + 0 → MCD = 18. ▸ ¿18 | 54? Sí (54 = 18·3) → tiene solución. ▸ Cantidad: d = MCD = 18 soluciones principales mod 126. ▸ Por qué las otras están mal: (A) "1" sería con MCD=1; (B) "7" sería para otro caso; (D) sí tiene solución.'},
  {st: 'V o F: si ∃ s, t ∈ ℤ tal que 3 = a·s + b·t, entonces MCD(a,b) = 3.', opts: ['V siempre', 'F. Lo correcto: MCD(a,b) | 3, así que MCD ∈ {1, 3}', 'V solo si a y b son positivos', 'F: MCD(a,b) ≥ 3'], c: 1, ex: 'Por Bezout, MCD(a,b) divide a CUALQUIER combinación lineal entera de a y b, incluyendo 3. Entonces MCD | 3 → MCD ∈ {1, 3}. ▸ Contraejemplo: a=1, b=0, 3 = 1·3 + 0·0. MCD(1,0) = 1 ≠ 3. ▸ Por qué las otras están mal: (A) "V siempre" descartado por contraejemplo; (C) (D) condiciones extra incorrectas.'},
  {st: 'Halle el resto de dividir 22³⁰ por 5.', opts: ['1', '4', '0', '3'], c: 1, ex: 'Aritmética modular: ▸ 22 ≡ 2 (5) → 22³⁰ ≡ 2³⁰ (5). ▸ Calcular potencias de 2 mod 5: 2¹=2, 2²=4, 2³=8≡3, 2⁴=16≡1. Ciclo de longitud 4. ▸ 30 = 4·7 + 2 → 2³⁰ ≡ 2² ≡ 4 (5). ▸ Resto = 4. ▸ Por qué las otras están mal: (A) "1" es 2⁰; (C) "0" implicaría 22 múltiplo de 5; (D) "3" es 2³ mod 5.'},
  {st: 'Anagramas de FELICIDADES (11 letras: F-E-L-I-C-I-D-A-D-E-S).', opts: ['11!', '11! / (2!·2!·2!) (E×2, I×2, D×2)', '11! / 8!', '11! · 8'], c: 1, ex: 'Letras repetidas: E (2), I (2), D (2). Otras (F,L,C,A,S) aparecen 1 vez. ▸ Permutaciones con repetición: 11! / (2!·2!·2!) = 11! / 8 = 4 989 600. ▸ Por qué las otras están mal: (A) 11! sin dividir trata todas como distintas; (C) 11!/8! cancela demasiado; (D) multiplicar por 8 (no dividir).'}
]);

registerExercises('led-finales', '5', [
  {st: 'Dada aₙ₊₁ − 4aₙ = −6·2ⁿ, la sucesión aₙ = 3·2ⁿ es:', opts: ['Solución general', 'Solución particular (verifica la recurrencia pero no tiene parámetro libre)', 'NO es solución', 'Solución de la homogénea'], c: 1, ex: 'Verifico: 3·2^(n+1) − 4·3·2ⁿ = 6·2ⁿ − 12·2ⁿ = −6·2ⁿ ✓. SÍ es solución. ▸ Pero la solución GENERAL tiene 1 parámetro libre (orden 1): aₙ = α·4ⁿ + 3·2ⁿ. Sin α, es solo PARTICULAR. ▸ Por qué las otras están mal: (A) sin α, no es general; (C) sí es solución; (D) la homogénea es α·4ⁿ (con la raíz 4, no 2).'},
  {st: 'Recurrencia con característica r² − 5r + 6 = 0 tiene raíces:', opts: ['r = 2 y r = 3', 'r = 5 y r = 6', 'r = 1 y r = 6', 'r doble r = 5/2'], c: 0, ex: '(r−2)(r−3) = r² − 5r + 6. Raíces 2 y 3 (distintas). ▸ Verificación: 2·3=6 ✓, 2+3=5 ✓ (suma = coef. con signo opuesto). ▸ Por qué las otras están mal: (B) 5+6=11 ≠ 5; (C) 1·6=6 ✓ pero 1+6=7 ≠ 5; (D) discriminante = 25−24 = 1 > 0 → raíces distintas, no doble.'},
  {st: 'INV(ℤ₈, ·) tiene cuántos elementos y es cíclico?', opts: ['4 elementos, cíclico', '4 elementos {1,3,5,7}, NO cíclico (cada uno tiene orden 2)', '8 elementos, cíclico', 'φ(8) = 4 elementos, sí cíclico generado por 3'], c: 1, ex: 'INV(ℤ₈) = {1, 3, 5, 7} (4 elementos coprimos con 8). ▸ Verifico ciclicidad: 3²=9≡1, 5²=25≡1, 7²=49≡1. Cada elemento no trivial tiene orden 2 → NO cíclico. ▸ Es ≅ ℤ₂ × ℤ₂ (Klein four-group). ▸ Por qué las otras están mal: (A) (D) afirman cíclico falsamente; (C) tiene 4, no 8.'},
  {st: '"H = {x ∈ ℤ : x = 3a + 5b, a, b ∈ ℤ} es subgrupo de (ℤ, +)". V o F:', opts: ['F, no es cerrado', 'V. Por Bezout MCD(3,5)=1, así que H = ℤ', 'V solo si a, b > 0', 'F'], c: 1, ex: 'Como MCD(3,5)=1, por Bezout existen s,t enteros con 3s+5t=1. Multiplicando por k cualquier entero: 3(ks)+5(kt) = k. Es decir, todo entero se escribe como combinación lineal entera de 3 y 5. H = ℤ. Es subgrupo (el todo). ▸ Por qué las otras están mal: (A) (D) sí es cerrado; (C) si a,b>0 sólo, no obtendrías 0=3·0+5·0 (excluye el neutro).'},
  {st: 'En INV(ℤ₉, ·), 2 es generador. ¿Cuál es el orden del subgrupo ⟨2³⟩?', opts: ['6', '3', '2 (porque 2³ = 8 en ℤ₉, y |⟨8⟩| = 6/MCD(3,6) = 2; los elementos son {1, 8})', '1'], c: 2, ex: 'INV(ℤ₉) = ⟨2⟩ es cíclico de orden 6. ▸ Fórmula: el orden de ⟨gᵏ⟩ en un grupo cíclico de orden n es n / MCD(k, n). ▸ Acá k=3, n=6: orden = 6/MCD(3,6) = 6/3 = 2. ▸ Verificación: 2³ = 8 en ℤ₉; 8² = 64 ≡ 1 (9). ⟨8⟩ = {1, 8} → orden 2. ▸ Por qué las otras están mal: (A) "6" es el orden total del grupo; (B) "3" es k (no el orden); (D) "1" sería trivial.'},
  {st: 'La red de subgrupos de un grupo cíclico de orden 12 es isomorfa a:', opts: ['(D₁₂, |)', '(P({a,b,c}), ⊆)', '(ℤ₁₂, +)', 'Ninguna anterior'], c: 0, ex: 'Teorema: para un grupo cíclico de orden n, la red de subgrupos es isomorfa a (D_n, |) (divisores de n con divisibilidad). ▸ D₁₂ = {1, 2, 3, 4, 6, 12} → 6 subgrupos. ▸ Por qué las otras están mal: (B) P({a,b,c}) tiene 8 elementos (≠ 6); (C) (ℤ₁₂, +) es el grupo MISMO, no su red de subgrupos; (D) hay isomorfismo claro.'}
]);

registerExercises('led-finales', '6', [
  {st: 'ES FALSO que existe un grafo G con A=4 y V=5 tal que:', opts: ['Sea simple y no conexo', 'Sea conexo, simple y SIN aristas puente', 'Sea conexo y tenga camino de Euler', 'Tenga 3 vértices colgantes'], c: 1, ex: 'Conexo con A=4 y V=5: A = V−1 = 4 → es ÁRBOL. En un árbol, TODAS las aristas son puentes. ▸ Imposible que sea conexo y SIN aristas puente. ▸ Por qué las otras están mal: (A) sí existe (K₃ + K₂ tiene 3+1=4 aristas y 5 vértices, no conexo); (C) sí (ej: cadena de 5 vértices); (D) sí (estrella K₁,₄ tiene 4 colgantes, restringible).'},
  {st: 'Suma de grados en un grafo simple = ', opts: ['|V|', '|A|', '2·|A| (handshaking lemma)', '|V| · |A|'], c: 2, ex: 'Cada arista contribuye 2 al total de grados (una para cada extremo). ▸ ∑grados = 2·|A|. ▸ Consecuencia: la cantidad de vértices de grado IMPAR es siempre par. ▸ Por qué las otras están mal: (A) (B) son lineales en V o A; (D) producto V·A no tiene sentido geométrico.'},
  {st: 'Un grafo simple con V=20 y A=170 ¿es necesariamente conexo?', opts: ['Sí siempre', 'No: 170 ≤ 171 = C(19,2), puede ser K₁₉ + un vértice aislado', 'Solo si es bipartito', 'Solo si todos los grados son ≥ 2'], c: 1, ex: 'Umbral: A > C(V−1, 2) = C(19, 2) = 171 garantiza conexión. ▸ Como A=170 ≤ 171, puede ser no conexo (K₁₉ tiene 171 aristas; sacar 1 → 170 + un vértice aislado de 13ᵃ posición → 5 vértices y 4 aristas, oops ahí me confundí, dejame mejor: K₁₉ tiene 19 vértices. Falta el vértice 20. Sacando 1 arista de K₁₉ deja 170 aristas; agregando un vértice 20 aislado → 20 vértices, 170 aristas, NO conexo. ✓. ▸ Por qué las otras están mal: (A) afirma sin justificar; (C) (D) condiciones no relevantes.'},
  {st: 'Un grafo conexo tiene camino de Euler si:', opts: ['Tiene 0 ó 2 vértices de grado impar', 'Todos los vértices tienen grado par', 'Tiene exactamente un vértice de grado impar', 'Es bipartito'], c: 0, ex: 'Teorema de Euler: en grafo conexo, hay CAMINO de Euler ⟺ exactamente 0 ó 2 vértices de grado impar. ▸ Si 0 → CIRCUITO de Euler (cerrado). ▸ Si 2 → camino abierto entre los dos vértices impares. ▸ Por qué las otras están mal: (B) "todos par" describe circuito (caso particular); (C) "1 impar" es imposible (suma de grados par); (D) bipartito no es ni necesario ni suficiente.'},
  {st: 'Un árbol binario regular con 7 vértices internos tiene cuántas hojas?', opts: ['7', '8 (i+1 con i=7)', '14', '15'], c: 1, ex: 'Fórmula: en árbol binario REGULAR (cada interno tiene 2 hijos), hojas = i + 1, total = 2·i + 1. ▸ Para i=7: hojas = 8, total = 15. ▸ Por qué las otras están mal: (A) "7" iguala internos y hojas (incorrecto); (C) "14" = 2·i; (D) "15" es el total de nodos (no solo hojas).'},
  {st: 'Un árbol binario regular puede tener exactamente 7 vértices en total?', opts: ['Sí, con i=3 internos y 4 hojas', 'No, viola la fórmula', 'Solo si es balanceado', 'No, mínimo 8'], c: 0, ex: 'Total = 2i + 1. Para total=7: 2i+1=7 → i=3 (entero). Hojas = i+1 = 4. ▸ Sí es posible: ej. raíz con 2 hijos; el hijo izquierdo es interno con 2 hijos hojas; el hijo derecho es hoja. Total: raíz(1) + 2 hijos(2) + 2 hojas del interno(2) + 2 hojas... cuenta diferente, mejor: raíz + 2 internos + 4 hojas = 7. ▸ Por qué las otras están mal: (B) (D) descartan sin verificar; (C) balanceado no es requisito.'}
]);

registerExercises('led-finales', '7', [
  {st: '(Final 19/02/2024) ¿De cuántas formas se hacen 8 hs extra L–V con al menos 1 por día y máximo 4 por día?', opts: ['25', '35', '40', '56'], c: 1, ex: 'Asigno 1 a cada uno de los 5 días (5 hs distribuidas). Quedan 3 hs libres entre 5 días sin restricción (3 ≤ 4 cada uno). ▸ C\'(5,3) = C(7,3) = 35. ▸ Por qué las otras están mal: (A) "25" no surge del cálculo; (C) "40" tampoco; (D) "56" sería C(8,3) o similar.'},
  {st: '(Final 19/02/2024) (D₄₀, |) es:', opts: ['Álgebra de Boole', 'Red isomorfa a (D₃₀, |)', 'Conjunto totalmente ordenado', 'Red distributiva pero NO complementada'], c: 3, ex: 'D₄₀={1,2,4,5,8,10,20,40}. 40=2³·5 NO libre de cuadrados → NO Boole. ▸ NO totalmente ordenado (2 y 5 son incomparables). ▸ NO isomorfa a D₃₀ (esa SÍ es Boole). ▸ Distributiva (toda red de divisores lo es), pero NO complementada (4 sin complemento). ▸ Por qué las otras están mal: (A) (B) (C) cada una es falsa por motivos distintos.'},
  {st: 'En el final clásico: ax ≡ b(n) tiene 18 soluciones principales. ¿Cuál es la condición?', opts: ['MCD(a,n) = 18 y 18 | b', 'a = 18 y b = 18', 'n = 18', 'MCD(a,b) = 18'], c: 0, ex: 'La cantidad de soluciones principales de ax≡b(n) es MCD(a,n) cuando este divide a b. ▸ "18 sols" → MCD(a,n)=18 Y 18|b. ▸ Por qué las otras están mal: (B) (C) confunden valores específicos; (D) MCD(a,b) NO determina la cantidad de soluciones (es MCD(a,n)).'},
  {st: 'Dada aₙ₊₁ − 4aₙ = −6·2ⁿ, ¿qué tipo de sucesión es aₙ = 3·2ⁿ?', opts: ['Solución general', 'Solución particular', 'No es solución', 'Solución de la homogénea'], c: 1, ex: 'Verifica la recurrencia (sí es solución) pero NO tiene parámetro libre → no es general. La general sería aₙ = α·4ⁿ + 3·2ⁿ. ▸ Por qué las otras están mal: (A) le falta el α·4ⁿ; (C) sí es solución (verificable); (D) la homogénea tendría raíz r=4 (no 2).'},
  {st: 'Estrategia de tiempo para el final de 2 horas:', opts: ['Resolver en orden estricto del 1 al 10', 'Pasada 1 (30 min) seguros, pasada 2 (60 min) dudosos, pasada 3 (30 min) revisar', 'Empezar por las difíciles', 'Saltarse las V/F'], c: 1, ex: 'Estrategia óptima: ▸ Pasada 1 (30 min): preguntas seguras (cubrís rápido los 6 mínimos). ▸ Pasada 2 (60 min): dudosas con calma. ▸ Pasada 3 (30 min): revisión, NO dejar nada en blanco. ▸ Por qué las otras están mal: (A) orden estricto pierde tiempo si una difícil te traba; (C) "empezar por difíciles" arriesga llegar al final sin las seguras; (D) saltar V/F es mala idea.'},
  {st: '"R y T son simétricas ⇒ R ∩ T es simétrica" es:', opts: ['Verdadero (demostrable)', 'Falso, hace falta contraejemplo', 'Solo si R = T', 'Solo si R ⊆ T'], c: 0, ex: 'Demostración: si (a,b) ∈ R∩T, entonces (a,b) ∈ R y (a,b) ∈ T. Por simetría de cada una, (b,a) ∈ R y (b,a) ∈ T → (b,a) ∈ R∩T. ✓ ▸ La intersección PRESERVA la simetría. ▸ Por qué las otras están mal: (B) sí se demuestra sin contraejemplo; (C) (D) no requieren condiciones extra.'}
]);
