// UNIDAD INICIAL: LA MEDICIÓN
registerExercises('fisica', '0', [
  {st: '¿Cuántos metros hay en 2,5 km?', opts: ['25 m', '250 m', '2500 m', '25000 m'], c: 2, ex: '1 km = 10³ m = 1000 m. ▸ 2,5 km = 2,5 · 1000 = 2500 m. ▸ Por qué las otras están mal: (A) (B) corren la coma mal; (D) multiplica por 10⁴.'},
  {st: 'Pasar 90 km/h a m/s.', opts: ['9 m/s', '15 m/s', '25 m/s', '324 m/s'], c: 2, ex: 'Conversión: km/h → m/s se DIVIDE por 3,6 (= 3600s/1000m). ▸ 90/3,6 = 25. Verificación: 90·1000/3600 = 90000/3600 = 25 m/s. ▸ Por qué las otras están mal: (A) divide por 10; (B) por 6; (D) multiplica por 3,6 en vez de dividir.'},
  {st: '¿Cuántas cifras significativas tiene el número 0,00405?', opts: ['2', '3', '5', '6'], c: 1, ex: 'Reglas: ceros a la izquierda NO son significativos; ceros entre dígitos SÍ. ▸ Cifras significativas: 4, 0 (entre 4 y 5), 5 → 3 cifras. ▸ Por qué las otras están mal: (A) cuenta 4 y 5 sin el 0 del medio; (C) (D) cuentan los ceros de la izquierda.'},
  {st: '¿Cuál es el resultado de 12,4 + 0,356 respetando cifras decimales?', opts: ['12,756', '12,76', '12,8', '13'], c: 2, ex: 'Regla de suma/resta: el resultado tiene tantos decimales como el dato MENOS preciso. ▸ 12,4 (1 decimal) + 0,356 (3 decimales) → resultado con 1 decimal. ▸ 12,756 → 12,8. ▸ Por qué las otras están mal: (A) (B) más decimales que 12,4; (D) entero (cero decimales) ya redondea de más.'},
  {st: 'Expresar 384.000.000 en notación científica.', opts: [M('38,4 · 10⁷'), M('3,84 · 10⁸'), M('0,384 · 10⁹'), M('3,84 · 10⁶')], c: 1, ex: 'Notación científica: a · 10ⁿ con 1 ≤ |a| &lt; 10. ▸ 384.000.000: corro la coma 8 lugares hacia la izquierda → 3,84 · 10⁸. ▸ Por qué las otras están mal: (A) "38,4" no cumple a&lt;10; (C) "0,384" no cumple a≥1; (D) "10⁶" la coma corrida solo 6 lugares.'},
  {st: 'Verificar la ecuación v = a·t dimensionalmente. ¿Es consistente?', opts: ['Sí, ambos lados son m/s', 'No, a·t da m/s²', 'Sí, ambos lados son m/s²', 'No, v es escalar y a·t es vector'], c: 0, ex: '[v] = m/s. [a·t] = (m/s²)·s = m/s. ▸ Coinciden → CONSISTENTE. ▸ Por qué las otras están mal: (B) confunde unidades de a con a·t; (C) v no tiene unidades de aceleración; (D) ambos pueden ser vectoriales.'},
  {st: '¿Cuál de las siguientes NO es una unidad fundamental del SI?', opts: ['kg', 'm', 's', 'N'], c: 3, ex: 'El Newton es DERIVADA: N = kg·m/s². Las 7 fundamentales del SI son: m, kg, s, A, K, mol, cd. ▸ Por qué las otras están mal: (A) (B) (C) son fundamentales (kg masa, m longitud, s tiempo).'},
  {st: 'El orden de magnitud de 4,8 · 10⁵ es:', opts: [M('10⁴'), M('10⁵'), M('10⁶'), M('5')], c: 1, ex: 'Orden de magnitud = potencia de 10 más cercana al número. ▸ Como 4,8 &lt; 5, el redondeo va hacia abajo → 10⁵ (no 10⁶). ▸ Por qué las otras están mal: (A) "10⁴" sería para 0,1 a 0,5; (C) "10⁶" sería si 4,8 ≥ 5; (D) "5" es solo el coeficiente.'}
]);

// UNIDAD 1: VECTORES
registerExercises('fisica', '1', [
  {st: 'Si '+M('A⃗ = 3î + 4ĵ')+', ¿cuál es su módulo?', opts: ['3', '4', '5', '7'], c: 2, ex: '|A⃗| = √(Aₓ² + Aᵧ²) = √(9+16) = √25 = 5. ▸ Triángulo 3-4-5 (Pitágoras clásico). ▸ Por qué las otras están mal: (A) (B) son las componentes; (D) "7" sería 3+4 sin Pitágoras.'},
  {st: 'Dados '+M('A⃗ = (2, 3)')+' y '+M('B⃗ = (−1, 4)')+', calcular '+M('A⃗ + B⃗')+'.', opts: [M('(1, 7)'), M('(3, −1)'), M('(1, 12)'), M('(−2, 12)')], c: 0, ex: 'Suma componente a componente: (2+(−1), 3+4) = (1, 7). ▸ Por qué las otras están mal: (B) hace resta; (C) (D) multiplica componentes.'},
  {st: 'Un vector de módulo 10 forma 30° con el eje x. ¿Cuál es su componente x?', opts: ['5', '5√3 ≈ 8,66', '10', '10/√3'], c: 1, ex: 'Aₓ = |A⃗|·cos(θ). ▸ Aₓ = 10·cos(30°) = 10·(√3/2) = 5√3 ≈ 8,66. ▸ Por qué las otras están mal: (A) "5" sería con sen (componente y); (C) "10" es el módulo; (D) "10/√3" no surge.'},
  {st: 'Calcular '+M('A⃗ · B⃗')+' con '+M('A⃗ = 2î + 3ĵ')+' y '+M('B⃗ = 4î − ĵ')+'.', opts: ['5', '8', '11', '14'], c: 0, ex: 'Producto escalar: A·B = Aₓ·Bₓ + Aᵧ·Bᵧ = 2·4 + 3·(−1) = 8 − 3 = 5. ▸ Por qué las otras están mal: (B) "8" es solo Aₓ·Bₓ; (C) (D) confunden suma con multiplicación.'},
  {st: '¿Cuándo dos vectores son perpendiculares?', opts: ['Cuando tienen el mismo módulo', 'Cuando su producto escalar es cero', 'Cuando su suma es cero', 'Cuando su producto vectorial es cero'], c: 1, ex: 'A⃗·B⃗ = |A||B|cos(θ). Si θ=90° → cos=0 → producto escalar 0. ▸ Por qué las otras están mal: (A) módulo no se relaciona; (C) suma cero implica opuestos (paralelos en sentidos opuestos); (D) producto vectorial cero implica PARALELOS.'},
  {st: 'Si '+M('A⃗ = 3î + 4ĵ')+' y '+M('B⃗ = 2î − ĵ')+', ¿cuánto vale '+M('A⃗ × B⃗')+'?', opts: [M('(−11) k̂'), M('11 k̂'), M('2 k̂'), M('10 k̂')], c: 0, ex: 'Producto vectorial 2D: Aₓ·Bᵧ − Aᵧ·Bₓ = 3·(−1) − 4·2 = −3 − 8 = −11. Apunta en −k̂. ▸ Por qué las otras están mal: (B) signo invertido; (C) (D) cálculos parciales.'},
  {st: 'El ángulo entre '+M('A⃗ = (1, 0)')+' y '+M('B⃗ = (1, 1)')+' es:', opts: ['0°', '30°', '45°', '60°'], c: 2, ex: 'cos(θ) = (A·B)/(|A||B|) = 1/(1·√2) = 1/√2 → θ = 45°. ▸ Por qué las otras están mal: (A) θ=0 → mismos vectores; (B) (D) cosenos no coinciden.'},
  {st: 'Un vector tiene componente y = 13 m y forma 32° con el eje +y (sentido antihorario). ¿Cuál es su componente x?', opts: ['−8,12 m', '8,12 m', '11,0 m', '15,3 m'], c: 0, ex: 'Antihorario desde +y → hacia −x. ▸ Aᵧ = |A|·cos(32°) = 13 → |A| = 13/cos(32°) ≈ 15,3 m. Aₓ = −|A|·sen(32°) ≈ −15,3·0,53 ≈ −8,12 m. ▸ Por qué las otras están mal: (B) signo positivo (no respeta el cuadrante); (C) (D) cálculos parciales.'},
  {st: 'Dos fuerzas de 100 N y 80 N actúan en direcciones opuestas. ¿Cuál es la fuerza resultante?', opts: ['20 N en el sentido de la de 80 N', '20 N en el sentido de la de 100 N', '180 N', '0 N'], c: 1, ex: 'Direcciones opuestas → restar módulos. 100 − 80 = 20 N en sentido de la mayor (100 N). ▸ Por qué las otras están mal: (A) sentido invertido; (C) suma como si fueran paralelas; (D) cero solo si fueran iguales.'}
]);

// UNIDAD 2: ESTÁTICA
registerExercises('fisica', '2', [
  {st: 'Un niño de 21,0 kg se sienta a 2,00 m del centro de un subibaja. ¿A qué distancia del centro debe sentarse, del otro lado, su padre de 105 kg para equilibrar?', opts: ['0,20 m', '0,40 m', '0,80 m', '10,0 m'], c: 1, ex: 'Equilibrio de momentos: m₁·d₁ = m₂·d₂. ▸ 21·2 = 105·d → d = 42/105 = 0,40 m. ▸ Intuición: padre 5× más pesado → 1/5 de distancia. ▸ Por qué las otras están mal: cálculos parciales o invertidos.'},
  {st: '¿Cuál es la condición para que un cuerpo extenso esté en equilibrio?', opts: ['Solo Σ F = 0', 'Solo Σ M = 0', 'Σ F = 0 Y Σ M = 0', 'Σ F = ma'], c: 2, ex: 'Cuerpo extenso necesita AMBAS: ▸ ΣF=0 (equilibrio traslacional, no se mueve). ▸ ΣM=0 (equilibrio rotacional, no rota). ▸ Por qué las otras están mal: (A) (B) condiciones individuales (insuficientes); (D) implica aceleración (no equilibrio).'},
  {st: '¿Qué es la "normal" en un DCL?', opts: ['La fuerza gravitatoria', 'La reacción de la superficie, perpendicular a ella', 'La fuerza de rozamiento', 'Siempre es igual al peso'], c: 1, ex: 'Normal: reacción perpendicular a la superficie de apoyo. ▸ Por qué las otras están mal: (A) "gravitatoria" es el peso; (C) "rozamiento" es paralelo a la superficie; (D) "siempre igual al peso" es FALSO (depende del DCL: en planos inclinados, otras fuerzas, etc.).'},
  {st: 'Una lámpara de peso P está sostenida por dos cuerdas simétricas con tensión P cada una. ¿Cuáles son los ángulos α y β con la horizontal?', opts: ['45° y 45°', '37° y 53°', '30° y 60°', '30° y 30°'], c: 3, ex: 'Por simetría α=β. Equilibrio vertical: 2T·sen(α) = P. Como T=P: 2P·sen(α) = P → sen(α) = 1/2 → α = 30°. Ambos 30°. ▸ Por qué las otras están mal: (A) sería con T = P/√2; (B) (C) asimétricos.'},
  {st: 'En una palanca en equilibrio, si DUPLICÁS la fuerza en un extremo sin cambiar su distancia, ¿qué pasa con el otro extremo?', opts: ['Se duplica su fuerza (manteniendo d)', 'La distancia debe duplicarse', 'Nada cambia', 'La fuerza debe reducirse a la mitad'], c: 0, ex: 'F₁·d₁ = F₂·d₂. Si duplicás F₁ y dejás d₁: 2F₁·d₁ = F₂\'·d₂. Para mantener igualdad, F₂\' = 2F₂ (o d₂ duplica si F₂ no cambia). ▸ Por qué las otras están mal: (D) es lo opuesto.'},
  {st: 'Un cable vertical sostiene un peso P. ¿Cuál es la tensión del cable?', opts: ['0', 'P/2', 'P', '2P'], c: 2, ex: 'Equilibrio: T − P = 0 → T = P. ▸ Por qué las otras están mal: (A) cero implicaría sin tensión (cuerda floja); (B) (D) no surgen.'},
  {st: 'Un auto tiene 53% de su peso sobre las ruedas delanteras y 47% sobre las traseras, con 2,46 m entre ejes. ¿A qué distancia del eje TRASERO está el centro de gravedad?', opts: ['1,16 m', '1,30 m', '1,50 m', '2,46 m'], c: 1, ex: 'Momentos respecto al eje trasero: 0,530·P·2,46 = P·x → x = 0,530·2,46 = 1,30 m. ▸ Por qué las otras están mal: (A) usa el 47% mal; (C) (D) sin cálculo.'},
  {st: 'El momento de una fuerza depende de:', opts: ['Solo de la magnitud de la fuerza', 'Solo de la distancia al eje', 'De la fuerza, la distancia al eje y el ángulo entre ambos', 'Solo del ángulo'], c: 2, ex: 'M = F·d·sen(α). ▸ Si F paralela al brazo (α=0°) → torque cero. Perpendicular (α=90°) → torque máximo. ▸ Por qué las otras están mal: (A) (B) (D) factores parciales.'},
  {st: '¿Dónde conviene plantear la ecuación de momentos en un problema de estática?', opts: ['En el centro del cuerpo', 'En cualquier punto, pero conviene donde haya una fuerza desconocida', 'Siempre en el piso', 'Siempre en el punto más alto'], c: 1, ex: 'La elección es libre. Estratégicamente: si elegís el punto donde actúa una fuerza desconocida, su momento es 0 (brazo cero) y NO aparece en la ecuación. Simplifica mucho. ▸ Por qué las otras están mal: (A) (C) (D) opciones rígidas, no estratégicas.'}
]);

// UNIDAD 3: HIDROSTÁTICA
registerExercises('fisica', '3', [
  {st: 'Una varilla cilíndrica de acero mide 85,8 cm de longitud y 2,85 cm de diámetro. ¿Cuál es su peso? (δ_acero = 7,80·10³ kg/m³)', opts: ['4,2 N', '41,8 N', '418 N', '4180 N'], c: 1, ex: 'V = π·r²·L = π·(0,01425)²·(0,858) ≈ 5,47·10⁻⁴ m³. m = δ·V ≈ 7800·5,47·10⁻⁴ ≈ 4,27 kg. P = m·g ≈ 4,27·9,8 ≈ 41,8 N. ▸ Por qué las otras están mal: (A) (C) (D) órdenes de magnitud incorrectos.'},
  {st: '¿Cuál es la unidad SI de la presión?', opts: ['Newton (N)', 'Pascal (Pa)', 'kg/m³', 'atm'], c: 1, ex: 'Pa = N/m². 1 atm = 1,013·10⁵ Pa. ▸ Por qué las otras están mal: (A) N es fuerza; (C) "kg/m³" es densidad; (D) atm no es SI.'},
  {st: '¿Cómo varía la presión con la profundidad en un fluido?', opts: ['Constante', 'Aumenta linealmente', 'Aumenta con el cuadrado', 'Disminuye'], c: 1, ex: 'Teorema fundamental: p = p₀ + δ·g·h. Lineal en h. ▸ Por qué las otras están mal: (A) cambia con h; (C) sería δgh²; (D) aumenta, no disminuye.'},
  {st: 'Un objeto tiene densidad mayor que la del agua. Si lo tirás al agua:', opts: ['Flota en la superficie', 'Queda en el medio', 'Se hunde hasta el fondo', 'Flota con la mitad sumergida'], c: 2, ex: 'δ_cuerpo &gt; δ_agua → empuje &lt; peso → SE HUNDE. ▸ Por qué las otras están mal: requieren densidades específicas (igual o menor).'},
  {st: 'Un cubo de 8,50 cm de lado tiene masa de 0,650 kg. ¿Flota en agua? (δ_agua = 1,00·10³ kg/m³)', opts: ['Sí, porque δ &lt; 1000', 'No, porque δ &gt; 1000', 'Sí, siempre flota', 'Depende de la temperatura'], c: 1, ex: 'V = (0,085)³ ≈ 6,14·10⁻⁴ m³. δ = m/V ≈ 1059 kg/m³ &gt; 1000 → SE HUNDE. ▸ Por qué las otras están mal: (A) δ es mayor; (C) sin verificar densidad; (D) la temperatura aquí no cambia significativamente.'},
  {st: 'Una pieza de metal pesa 90 g en aire y 75 g sumergida en agua. ¿Cuál es su densidad? (δ_agua = 1 g/cm³)', opts: ['1,2 g/cm³', '6,0 g/cm³', '15 g/cm³', '90 g/cm³'], c: 1, ex: 'Empuje = peso aire − peso sumergido = 90 − 75 = 15 g (corresponde a V de agua desalojado). V = 15 cm³. δ = m/V = 90/15 = 6,0 g/cm³. ▸ Por qué las otras están mal: (A) (C) (D) cálculos parciales.'},
  {st: 'El principio de Pascal dice que la presión aplicada a un fluido encerrado:', opts: ['Se transmite solo hacia abajo', 'Se transmite por igual en todas direcciones', 'Se disipa con la distancia', 'Solo aumenta la temperatura'], c: 1, ex: 'Pascal: presión se transmite EN TODAS DIRECCIONES sin disminuir. Base de prensas hidráulicas. ▸ Por qué las otras están mal: confunden el principio.'},
  {st: 'En una prensa hidráulica, el émbolo pequeño tiene área A y el grande 6A. ¿Qué F necesitás en el pequeño para sostener 600 N en el grande?', opts: ['100 N', '600 N', '1200 N', '3600 N'], c: 0, ex: 'Pascal: F/A = 600/(6A) → F = 100 N. ▸ Multiplicador de fuerza: factor 6. ▸ Por qué las otras están mal: (B) ignora el factor de multiplicación; (C) (D) inverten o exageran.'},
  {st: '¿Por qué se usa mercurio en barómetros (no agua)?', opts: ['Es más barato', 'Su densidad es mucho mayor → columna corta', 'Es transparente', 'Por razones históricas'], c: 1, ex: 'p_atm = δ·g·h. Con Hg (13,6 g/cm³): h ≈ 76 cm. Con agua (1 g/cm³): h ≈ 10 m. ▸ Por qué las otras están mal: (A) Hg es caro; (C) Hg no es transparente; (D) razón física, no histórica.'}
]);

// UNIDAD 4: CINEMÁTICA 1D
registerExercises('fisica', '4', [
  {st: '¿Cuál es la diferencia entre velocidad y rapidez?', opts: ['Son lo mismo', 'Velocidad es vectorial (dirección y sentido); rapidez es escalar (módulo)', 'Rapidez es vectorial; velocidad escalar', 'Rapidez es la derivada de velocidad'], c: 1, ex: 'Velocidad = vector (módulo + dirección). Rapidez = solo módulo. ▸ 60 km/h al N tiene misma rapidez que 60 km/h al S, pero distinta velocidad. ▸ Por qué las otras están mal: (A) son distintas; (C) invertido; (D) la derivada de velocidad es ACELERACIÓN.'},
  {st: 'En MRUV con aceleración constante a, ¿cuál es la ecuación horaria de POSICIÓN?', opts: [M('x(t) = x₀ + v·t'), M('x(t) = x₀ + v₀·t + ½·a·t²'), M('x(t) = x₀ + a·t²'), M('x(t) = v₀ + a·t')], c: 1, ex: 'MRUV: posición es CUADRÁTICA en t. ▸ x(t) = x₀ + v₀·t + ½·a·t². ▸ Por qué las otras están mal: (A) MRU (sin aceleración); (C) le falta ½ y v₀·t; (D) es la ecuación de VELOCIDAD.'},
  {st: 'Un antílope con aceleración constante tarda 7,00 s en pasar 70,0 m, con rapidez final 15,0 m/s. ¿Rapidez inicial?', opts: ['3,0 m/s', '5,0 m/s', '10,0 m/s', '12,5 m/s'], c: 1, ex: 'v_media = Δx/Δt = 70/7 = 10 m/s. En MRUV: v_media = (v_i + v_f)/2 → (v_i + 15)/2 = 10 → v_i = 5 m/s. ▸ Por qué las otras están mal: (C) "10" es v_media; (A) (D) no surgen.'},
  {st: 'Con los datos del ejercicio anterior, ¿qué aceleración lleva el antílope?', opts: ['0,71 m/s²', '1,43 m/s²', '2,14 m/s²', '4,29 m/s²'], c: 1, ex: 'a = (v_f − v_i)/Δt = (15 − 5)/7 = 10/7 ≈ 1,43 m/s². ▸ Por qué las otras están mal: (A) "0,71" sería 5/7; (C) "2,14" sería 15/7; (D) "4,29" no surge.'},
  {st: 'Un malabarista lanza un cuchillo hacia arriba con v₀ = 8,20 m/s. ¿Cuánto tarda en volver a su mano?', opts: ['0,84 s', '1,67 s', '2,50 s', '8,20 s'], c: 1, ex: 'Tiempo de vuelo = 2·tiempo de subida. ▸ En punto alto v=0: 0 = 8,2 − 9,8·t_sub → t_sub ≈ 0,837 s. ▸ Total: ≈ 1,67 s. ▸ Por qué las otras están mal: (A) solo el tiempo de subida; (C) (D) órdenes equivocados.'},
  {st: 'En Marte (g = 3,71 m/s²), una pelota golpeada hacia arriba vuelve al mismo nivel 8,50 s después. ¿Rapidez inicial?', opts: ['7,9 m/s', '15,8 m/s', '31,5 m/s', '63,0 m/s'], c: 1, ex: 't_subida = 8,50/2 = 4,25 s. v₀ = g·t_sub = 3,71·4,25 ≈ 15,8 m/s. ▸ Por qué las otras están mal: (A) usa todo el tiempo dividido por 2; (C) (D) sin dividir t.'},
  {st: 'Una roca cae 1,75 s desde el reposo en la Tierra. La misma caída tarda 18,6 s en Encélado (luna). ¿Cuál es g en Encélado?', opts: ['0,087 m/s²', '0,87 m/s²', '1,05 m/s²', '9,80 m/s²'], c: 0, ex: 'h fija. Tierra: h = ½·9,8·1,75² ≈ 15 m. Encélado: 15 = ½·g·18,6² → g ≈ 30/345,96 ≈ 0,087 m/s². ▸ Por qué las otras están mal: (B) (C) órdenes equivocados; (D) "9,80" es g de la Tierra.'},
  {st: 'En el gráfico v(t) de un movimiento, ¿qué representa el ÁREA bajo la curva?', opts: ['La aceleración', 'La velocidad media', 'El desplazamiento Δx', 'La posición inicial'], c: 2, ex: 'Geometría: ∫v dt = Δx. ▸ Por qué las otras están mal: (A) "aceleración" es la PENDIENTE de v(t), no el área; (B) v_media es Δx/Δt; (D) x₀ es solo un valor.'},
  {st: 'Un cohete parte del suelo con v₀ = 50 m/s y acelera 2 m/s² hacia arriba, hasta apagarse a 150 m. ¿Rapidez al apagarse?', opts: ['50 m/s', '54 m/s', '56 m/s', '70 m/s'], c: 2, ex: 'Ecuación sin tiempo: v² = v₀² + 2·a·Δx = 2500 + 600 = 3100 → v ≈ 55,7 ≈ 56 m/s. ▸ Por qué las otras están mal: (A) sin acelerar; (B) (D) cálculos parciales.'}
]);

// UNIDAD 5: CINEMÁTICA 2D
registerExercises('fisica', '5', [
  {st: 'En tiro oblicuo (sin rozamiento), ¿qué pasa con la componente HORIZONTAL de la velocidad durante el vuelo?', opts: ['Aumenta', 'Permanece constante', 'Disminuye', 'Varía con t²'], c: 1, ex: 'Única fuerza: gravedad (vertical). NO hay fuerza horizontal → vₓ = v₀·cos(α) constante. ▸ Por qué las otras están mal: (A) (C) (D) implican fuerza horizontal (no existe sin rozamiento).'},
  {st: 'Un proyectil se lanza a 20 m/s formando 30° con horizontal. ¿Velocidad inicial en x?', opts: ['10 m/s', '17,3 m/s', '20 m/s', '10√3/2 m/s'], c: 1, ex: 'vₓ₀ = v₀·cos(30°) = 20·(√3/2) = 10√3 ≈ 17,3 m/s. ▸ Por qué las otras están mal: (A) "10" es vᵧ₀ (con sen 30°=1/2); (C) v₀ módulo total; (D) cálculo equivocado.'},
  {st: '¿Con qué ángulo se obtiene el alcance MÁXIMO en tiro oblicuo (igual altura)?', opts: ['30°', '45°', '60°', '90°'], c: 1, ex: 'R = v₀²·sen(2α)/g. Máximo cuando sen(2α)=1 → 2α=90° → α=45°. ▸ Por qué las otras están mal: (A) (C) son menores; (D) sería tiro vertical (R=0).'},
  {st: 'En el punto más alto de un tiro oblicuo, la velocidad es:', opts: ['Cero', 'Igual a la inicial', 'Solo horizontal (vₓ inicial)', 'Solo vertical'], c: 2, ex: 'En la cumbre: vᵧ=0 (por eso es la cumbre), vₓ sigue siendo v₀·cos(α). Velocidad horizontal. ▸ Por qué las otras están mal: (A) cero solo en lanzamiento vertical; (B) cambia durante el vuelo; (D) sería tiro vertical.'},
  {st: 'Un auto en MCU a 20 m/s en curva de radio 40 m. Aceleración centrípeta:', opts: ['0,5 m/s²', '2 m/s²', '10 m/s²', '800 m/s²'], c: 2, ex: 'a_c = v²/R = 400/40 = 10 m/s². ▸ Por qué las otras están mal: (A) (B) cálculos parciales; (D) "800" es v² (sin dividir).'},
  {st: '¿Qué significa que un movimiento circular sea "uniforme"?', opts: ['La aceleración es cero', 'La RAPIDEZ (módulo) es constante', 'El vector velocidad es constante', 'No hay fuerza'], c: 1, ex: 'MCU: rapidez constante, pero velocidad CAMBIA dirección → hay aceleración (centrípeta). ▸ Por qué las otras están mal: (A) "aceleración cero" implicaría MRU; (C) velocidad como vector cambia constantemente; (D) sí hay fuerza centrípeta.'},
  {st: 'Si un cuerpo da 2 vueltas por segundo, su período T es:', opts: ['0,5 s', '1 s', '2 s', '4π s'], c: 0, ex: 'f = 2 Hz. T = 1/f = 1/2 = 0,5 s. ▸ Por qué las otras están mal: confusiones entre T y f.'},
  {st: 'Relación entre velocidad lineal v, angular ω y radio R en circular:', opts: [M('v = ω/R'), M('v = ω·R'), M('v = R/ω'), M('v = ω + R')], c: 1, ex: 'v = ω·R. ▸ Intuición: a más radio, más rápido recorrés a igual ω. ▸ Por qué las otras están mal: invierten o confunden la relación.'}
]);

// UNIDAD 6: DINÁMICA
registerExercises('fisica', '6', [
  {st: '¿Qué dice la 2ª ley de Newton?', opts: [M('F = m·v'), M('ΣF⃗ = m·a⃗'), M('F = m·g'), M('F·d = m·a')], c: 1, ex: 'Fuerza neta = masa × aceleración (vectorial). ▸ Por qué las otras están mal: (A) m·v es momento lineal; (C) m·g es peso (caso particular); (D) F·d es trabajo (otra ley).'},
  {st: 'Un cuerpo de 5 kg con fuerza neta de 20 N. Aceleración:', opts: ['0,25 m/s²', '4 m/s²', '15 m/s²', '100 m/s²'], c: 1, ex: 'a = F/m = 20/5 = 4 m/s². ▸ Por qué las otras están mal: (A) invierte; (C) suma; (D) multiplica.'},
  {st: '¿En qué situación se aplica la 1ª ley de Newton?', opts: ['Solo en reposo', 'Solo en movimiento', 'Cuando ΣF=0: reposo o MRU (equivalentes)', 'Cuando hay aceleración'], c: 2, ex: 'Inercia: si ΣF=0 → reposo o MRU se mantienen. ▸ Por qué las otras están mal: (A) (B) son casos particulares; (D) implica ΣF≠0 (2ª ley).'},
  {st: 'Las fuerzas del par acción-reacción actúan:', opts: ['Sobre el mismo cuerpo', 'Sobre cuerpos DISTINTOS y son opuestas', 'Sobre el mismo cuerpo en la misma dirección', 'Solo cuando hay movimiento'], c: 1, ex: '3ª ley: A→B con F implica B→A con −F. ▸ Sobre cuerpos DIFERENTES → nunca se cancelan en el DCL del mismo cuerpo. ▸ Por qué las otras están mal: confunden 3ª ley con anulación.'},
  {st: '¿Cuál es la fuerza normal sobre un cuerpo de 10 kg en mesa horizontal? (g=9,8)', opts: ['0', '10 N', '98 N', '980 N'], c: 2, ex: 'En vertical: N − P = 0 → N = P = m·g = 98 N. ▸ Por qué las otras están mal: (A) cuerpo apoyado tiene N&gt;0; (B) sin g; (D) confunde con kg·g·g.'},
  {st: '¿Cuál de estas afirmaciones sobre el rozamiento es correcta?', opts: ['El rozamiento estático máximo siempre vale μ·N', 'El dinámico siempre &gt; estático', 'Dinámico vale μd·N mientras se mueve', 'El rozamiento no depende de N'], c: 2, ex: 'f_d = μ_d·N (cinético, con la fórmula). ▸ Estático puede valer entre 0 y μ_s·N (se ajusta). Generalmente μ_s &gt; μ_d. ▸ Por qué las otras están mal: (A) "máximo" no es "siempre"; (B) invertido; (D) sí depende.'},
  {st: 'Resorte k=200 N/m se estira 5 cm. ¿Fuerza?', opts: ['0,4 N', '10 N', '40 N', '1000 N'], c: 1, ex: 'Ley de Hooke: |F| = k·x = 200·0,05 = 10 N. ▸ Por qué las otras están mal: cálculos con unidades equivocadas (cm en vez de m).'},
  {st: 'Péndulo simple de 1 m. Período aproximado: (g=9,8)', opts: ['0,5 s', '1 s', '2 s', '2π s'], c: 2, ex: 'T = 2π·√(L/g) = 2π·√(1/9,8) ≈ 2π·0,32 ≈ 2,0 s. NO depende de la masa. ▸ Por qué las otras están mal: (A) (B) (D) cálculos equivocados.'},
  {st: 'En un auto en curva, ¿qué fuerza produce la aceleración centrípeta?', opts: ['El peso', 'La fuerza centrífuga', 'El rozamiento de los neumáticos con el piso', 'La normal'], c: 2, ex: 'En curva plana: rozamiento estático lateral apunta al centro → produce a_c. ▸ Por qué las otras están mal: (A) peso es vertical; (B) "centrífuga" es ficticia (no existe en sistema inercial); (D) normal es vertical también.'}
]);

// UNIDAD 7: TRABAJO Y ENERGÍA
registerExercises('fisica', '7', [
  {st: '¿Cuánto trabajo hace una fuerza PERPENDICULAR al desplazamiento?', opts: ['El máximo', 'La mitad', 'Cero', 'Depende de la velocidad'], c: 2, ex: 'W = F·d·cos(θ). θ=90° → cos=0 → W=0. ▸ Ej: la normal NUNCA hace trabajo (perpendicular al movimiento). ▸ Por qué las otras están mal: el trabajo máx es con θ=0; resto no aplica.'},
  {st: 'Una F de 50 N empuja una caja 10 m en la misma dirección. Trabajo:', opts: ['5 J', '50 J', '500 J', '5000 J'], c: 2, ex: 'W = F·d·cos(0°) = 50·10·1 = 500 J. ▸ Por qué las otras están mal: cálculos con factores equivocados.'},
  {st: 'Un cuerpo de 2 kg a 5 m/s. Energía cinética:', opts: ['5 J', '10 J', '25 J', '50 J'], c: 2, ex: 'E_c = ½·m·v² = ½·2·25 = 25 J. ▸ Por qué las otras están mal: (A) sin v²; (B) sin ½; (D) sin ½ con v² mal.'},
  {st: 'Si DUPLICÁS la velocidad de un cuerpo, su energía cinética:', opts: ['Se duplica', 'Se cuadruplica', 'Se mantiene', 'Se reduce a la mitad'], c: 1, ex: 'E_c ∝ v². v→2v ⟹ (2v)²=4v² → ENERGÍA × 4. ▸ Por eso colisión a 100 km/h es 4× más destructiva que a 50 km/h. ▸ Por qué las otras están mal: linealidad equivocada.'},
  {st: 'El teorema del trabajo y energía cinética dice:', opts: [M('W_neto = m·g·h'), M('W_neto = ΔE_c'), M('W_neto = E_c + E_p'), M('W_neto = F·d')], c: 1, ex: 'W_neto = E_cf − E_ci = ΔE_c. ▸ Por qué las otras están mal: (A) trabajo del peso específico; (C) suma errónea; (D) definición de W (no teorema).'},
  {st: 'Un cuerpo de 3 kg a 10 m de altura. Ep gravitatoria respecto del suelo: (g=9,8)', opts: ['30 J', '98 J', '294 J', '2940 J'], c: 2, ex: 'E_pg = m·g·h = 3·9,8·10 = 294 J. ▸ Por qué las otras están mal: cálculos parciales o desplazamientos de coma.'},
  {st: '¿Cuál de estas fuerzas es CONSERVATIVA?', opts: ['Rozamiento', 'Tensión', 'Peso (gravedad)', 'Normal'], c: 2, ex: 'Conservativa: el trabajo depende solo del cambio de POSICIÓN, no del CAMINO. Peso y elástica son conservativas. ▸ Por qué las otras están mal: (A) rozamiento depende del camino; (B) (D) no son conservativas en el sentido estricto.'},
  {st: 'Se suelta una piedra desde 20 m sin rozamiento. ¿Velocidad al llegar al suelo? (g=9,8)', opts: ['9,8 m/s', '14 m/s', '19,8 m/s', '392 m/s'], c: 2, ex: 'Conservación de energía: m·g·h = ½·m·v² → v = √(2·g·h) = √(2·9,8·20) = √392 ≈ 19,8 m/s. NO depende de la masa. ▸ Por qué las otras están mal: (A) sin elevar al cuadrado; (B) √200; (D) "392" es v² sin raíz.'},
  {st: 'Si hay rozamiento, la energía mecánica:', opts: ['Se conserva', 'Aumenta', 'Disminuye (se transforma en calor)', 'Cambia de dirección'], c: 2, ex: 'Rozamiento es no conservativo → "consume" energía mecánica → calor en la superficie de contacto. ▸ Por qué las otras están mal: (A) sí se conserva si NO hay rozamiento; (B) la energía no aumenta; (D) "dirección" no aplica a energía (escalar).'}
]);
