// UNIDAD INICIAL: LA MEDICIÓN
registerExercises('fisica', '0', [
  {st: '¿Cuántos metros hay en 2,5 km?', opts: ['25 m', '250 m', '2500 m', '25000 m'], c: 2, ex: 'Un kilómetro son 10³ m = 1000 m. Entonces 2,5 km = 2,5 · 1000 = 2500 m.'},
  {st: 'Pasar 90 km/h a m/s.', opts: ['9 m/s', '15 m/s', '25 m/s', '324 m/s'], c: 2, ex: 'Para pasar km/h → m/s se divide por 3,6. 90 / 3,6 = 25 m/s. Verificación: 90 · 1000 / 3600 = 90000/3600 = 25.'},
  {st: '¿Cuántas cifras significativas tiene el número 0,00405?', opts: ['2', '3', '5', '6'], c: 1, ex: 'Los ceros a la izquierda de la primera cifra distinta de cero NO son significativos. Los que están entre dos dígitos SÍ lo son. Las cifras significativas son 4, 0 y 5: son 3.'},
  {st: '¿Cuál es el resultado correcto de 12,4 + 0,356 respetando cifras decimales?', opts: ['12,756', '12,76', '12,8', '13'], c: 2, ex: 'En sumas y restas, el resultado tiene tantos decimales como el dato con menos decimales. 12,4 tiene 1 decimal, 0,356 tiene 3. Se redondea a 1 decimal: 12,8.'},
  {st: 'Expresar 384.000.000 en notación científica.', opts: [M('38,4 · 10⁷'), M('3,84 · 10⁸'), M('0,384 · 10⁹'), M('3,84 · 10⁶')], c: 1, ex: 'La notación científica tiene forma a · 10ⁿ con 1 ≤ |a| < 10. Corriendo la coma 8 lugares: 3,84 · 10⁸.'},
  {st: 'Verificar la ecuación v = a·t dimensionalmente. ¿Es consistente?', opts: ['Sí, ambos lados son m/s', 'No, a·t da m/s²', 'Sí, ambos lados son m/s²', 'No, v es escalar y a·t es vector'], c: 0, ex: '[v] = m/s. [a·t] = (m/s²)·s = m/s. Ambos lados tienen las mismas unidades, así que la ecuación es dimensionalmente consistente.'},
  {st: '¿Cuál de las siguientes NO es una unidad fundamental del SI?', opts: ['kg', 'm', 's', 'N'], c: 3, ex: 'El Newton (N) es una unidad derivada: N = kg·m/s². Las unidades fundamentales del SI son: m, kg, s, A, K, mol y cd.'},
  {st: 'El orden de magnitud de 4,8 · 10⁵ es:', opts: [M('10⁴'), M('10⁵'), M('10⁶'), M('5')], c: 1, ex: 'El orden de magnitud es la potencia de 10 más cercana. Como 4,8 < 5, redondea hacia abajo, el orden queda en 10⁵.'}
]);

// UNIDAD 1: MAGNITUDES FÍSICAS / VECTORES
registerExercises('fisica', '1', [
  {st: 'Si '+M('A⃗ = 3î + 4ĵ')+', ¿cuál es su módulo?', opts: ['3', '4', '5', '7'], c: 2, ex: 'El módulo es |A⃗| = √(Ax² + Ay²) = √(9+16) = √25 = 5.'},
  {st: 'Dados '+M('A⃗ = (2, 3)')+' y '+M('B⃗ = (−1, 4)')+', calcular '+M('A⃗ + B⃗')+'.', opts: [M('(1, 7)'), M('(3, −1)'), M('(1, 12)'), M('(−2, 12)')], c: 0, ex: 'La suma se hace componente a componente: (2+(−1), 3+4) = (1, 7).'},
  {st: 'Un vector de módulo 10 forma 30° con el eje x. ¿Cuál es su componente x?', opts: ['5', '5√3 ≈ 8,66', '10', '10/√3'], c: 1, ex: 'Ax = |A⃗|·cos(θ) = 10·cos(30°) = 10·(√3/2) = 5√3 ≈ 8,66.'},
  {st: 'Calcular '+M('A⃗ · B⃗')+' con '+M('A⃗ = 2î + 3ĵ')+' y '+M('B⃗ = 4î − ĵ')+'.', opts: ['5', '8', '11', '14'], c: 0, ex: 'Producto escalar por componentes: A·B = Ax·Bx + Ay·By = 2·4 + 3·(−1) = 8 − 3 = 5.'},
  {st: '¿Cuándo dos vectores son perpendiculares?', opts: ['Cuando tienen el mismo módulo', 'Cuando su producto escalar es cero', 'Cuando su suma es cero', 'Cuando su producto vectorial es cero'], c: 1, ex: 'A⃗ · B⃗ = |A||B|·cos(θ). Si θ = 90°, cos(θ) = 0, y el producto escalar da cero. Es la definición más práctica de perpendicularidad.'},
  {st: 'Si '+M('A⃗ = 3î + 4ĵ')+' y '+M('B⃗ = 2î − ĵ')+', ¿cuánto vale '+M('A⃗ × B⃗')+'?', opts: [M('(−11) k̂'), M('11 k̂'), M('2 k̂'), M('10 k̂')], c: 0, ex: 'Ax·By − Ay·Bx = 3·(−1) − 4·2 = −3 − 8 = −11. El producto vectorial apunta en la dirección −k̂ (hacia "abajo" del plano).'},
  {st: 'El ángulo entre '+M('A⃗ = (1, 0)')+' y '+M('B⃗ = (1, 1)')+' es:', opts: ['0°', '30°', '45°', '60°'], c: 2, ex: 'cos(θ) = (A·B)/(|A||B|) = 1/(1·√2) = 1/√2. Entonces θ = 45°. B⃗ es la diagonal del primer cuadrante.'},
  {st: 'Un vector tiene componente y = 13 m y forma 32° con el eje +y (sentido antihorario). ¿Cuál es su componente x?', opts: ['−8,12 m', '8,12 m', '11,0 m', '15,3 m'], c: 0, ex: 'Medir desde +y en sentido antihorario significa ir hacia −x. Ax = −|A|·sen(32°). Pero |A|·cos(32°) = 13, entonces |A| = 13/cos(32°) ≈ 15,3 m. Ax = −15,3·sen(32°) ≈ −8,12 m.'},
  {st: 'Dos fuerzas de 100 N y 80 N actúan en direcciones opuestas. ¿Cuál es la fuerza resultante?', opts: ['20 N en el sentido de la de 80 N', '20 N en el sentido de la de 100 N', '180 N', '0 N'], c: 1, ex: 'Al ser opuestas se restan. 100 − 80 = 20 N. La resultante apunta en el sentido de la más grande, es decir, la de 100 N.'}
]);

// UNIDAD 2: ESTÁTICA
registerExercises('fisica', '2', [
  {st: 'Un niño de 21,0 kg se sienta a 2,00 m del centro de un subibaja. ¿A qué distancia del centro debe sentarse, del otro lado, su padre de 105 kg para equilibrar?', opts: ['0,20 m', '0,40 m', '0,80 m', '10,0 m'], c: 1, ex: 'Para equilibrio de momentos: m₁·d₁ = m₂·d₂. 21·2 = 105·d, entonces d = 42/105 = 0,40 m. El padre, al ser 5 veces más pesado, se sienta a 1/5 de la distancia.'},
  {st: '¿Cuál es la condición para que un cuerpo extenso esté en equilibrio?', opts: ['Solo Σ F = 0', 'Solo Σ M = 0', 'Σ F = 0 y Σ M = 0', 'Σ F = ma'], c: 2, ex: 'Para un cuerpo extenso hacen falta AMBAS condiciones: la suma de fuerzas debe ser cero (equilibrio traslacional) Y la suma de momentos respecto de cualquier punto debe ser cero (equilibrio rotacional).'},
  {st: '¿Qué es la "normal" en un DCL?', opts: ['La fuerza gravitatoria', 'La reacción de la superficie, perpendicular a ella', 'La fuerza de rozamiento', 'Siempre es igual al peso'], c: 1, ex: 'La normal es la reacción que una superficie ejerce sobre un cuerpo apoyado. Siempre es perpendicular a la superficie. Su módulo depende de las otras fuerzas, NO es siempre igual al peso.'},
  {st: 'Una lámpara de peso P está sostenida por dos cuerdas simétricas a 30° de la horizontal cada una. La tensión de cada cuerda vale P. ¿Cuáles son los ángulos α y β?', opts: ['45° y 45°', '37° y 53°', '30° y 60°', '30° y 30°'], c: 3, ex: 'Por simetría, ambas cuerdas tensan lo mismo. Si ambos ángulos con la horizontal son iguales y la tensión vale P, de la ecuación vertical: 2·T·sen(α) = P → 2·P·sen(α) = P → sen(α) = 1/2 → α = 30°. Ambos ángulos son 30°.'},
  {st: 'En una palanca en equilibrio, si duplicás la fuerza en un extremo sin cambiar su distancia al apoyo, ¿qué pasa con el otro extremo?', opts: ['Se duplica su fuerza', 'La distancia al apoyo debe duplicarse', 'Nada cambia', 'La fuerza debe reducirse a la mitad'], c: 0, ex: 'Si F₁·d₁ = F₂·d₂ y duplicás F₁ sin cambiar d₁, entonces para mantener la igualdad, F₂ (o d₂) también se duplica. Si d₂ no cambia, F₂ duplica. Si F₂ no cambia, es d₂ la que duplica.'},
  {st: 'Un cable vertical sostiene un peso P. ¿Cuál es la tensión del cable?', opts: ['0', 'P/2', 'P', '2P'], c: 2, ex: 'Equilibrio del cuerpo: T − P = 0, entonces T = P. La tensión del cable iguala al peso que sostiene.'},
  {st: 'Un auto tiene 53% de su peso sobre las ruedas delanteras y 47% sobre las traseras, con 2,46 m de distancia entre ejes. ¿A qué distancia del eje trasero está el centro de gravedad?', opts: ['1,16 m', '1,30 m', '1,50 m', '2,46 m'], c: 1, ex: 'Planteando momentos respecto del eje trasero: 0,530·P·2,46 = P·x, donde x es la distancia del CG al eje trasero. x = 0,530·2,46 = 1,30 m.'},
  {st: 'El momento de una fuerza depende de:', opts: ['Solo de la magnitud de la fuerza', 'Solo de la distancia al eje', 'De la fuerza, la distancia al eje y el ángulo entre ambos', 'Solo del ángulo'], c: 2, ex: 'M = F · d · sen(α). Si la fuerza es paralela al brazo (α = 0°), no genera torque. Si es perpendicular (α = 90°), el torque es máximo: M = F · d.'},
  {st: '¿Dónde conviene plantear la ecuación de momentos en un problema de estática?', opts: ['En el centro del cuerpo', 'En cualquier punto, pero conviene donde haya una fuerza desconocida', 'Siempre en el piso', 'Siempre en el punto más alto'], c: 1, ex: 'La elección es libre. Pero elegir un punto donde actúa una fuerza desconocida hace que su momento se anule (brazo cero) y no aparezca en la ecuación. Eso simplifica mucho: se suele tomar el punto de apoyo.'}
]);

// UNIDAD 3: HIDROSTÁTICA
registerExercises('fisica', '3', [
  {st: 'Una varilla cilíndrica de acero mide 85,8 cm de longitud y 2,85 cm de diámetro. ¿Cuál es aproximadamente su peso? (δ_acero = 7,80·10³ kg/m³)', opts: ['4,2 N', '41,8 N', '418 N', '4180 N'], c: 1, ex: 'V = π·r²·L = π·(0,01425)²·(0,858) ≈ 5,47·10⁻⁴ m³. m = δ·V = 7800·5,47·10⁻⁴ ≈ 4,27 kg. P = m·g = 4,27·9,8 ≈ 41,8 N.'},
  {st: '¿Cuál es la unidad SI de la presión?', opts: ['Newton (N)', 'Pascal (Pa)', 'kg/m³', 'atm'], c: 1, ex: 'El Pascal (Pa) es la unidad SI: 1 Pa = 1 N/m². Una atmósfera equivale a 1,013·10⁵ Pa. Los kg/m³ son unidades de densidad, no presión.'},
  {st: '¿Cómo varía la presión con la profundidad en un fluido?', opts: ['Se mantiene constante', 'Aumenta linealmente con la profundidad', 'Aumenta con el cuadrado de la profundidad', 'Disminuye con la profundidad'], c: 1, ex: 'Por el teorema fundamental de la hidrostática: p = p₀ + δ·g·h. Aumenta linealmente con la profundidad h.'},
  {st: 'Un objeto tiene densidad mayor que la del agua. Si lo tirás al agua:', opts: ['Flota en la superficie', 'Queda en el medio del fluido', 'Se hunde hasta el fondo', 'Flota con la mitad sumergida'], c: 2, ex: 'Cuando δ_cuerpo > δ_fluido, el empuje es menor que el peso y el cuerpo se hunde. Si son iguales, queda suspendido. Si es menor, flota.'},
  {st: 'Un cubo de 8,50 cm de lado tiene una masa de 0,650 kg. ¿Flota en agua? (δ_agua = 1,00·10³ kg/m³)', opts: ['Sí, porque δ < 1000', 'No, porque δ > 1000', 'Sí, siempre flota', 'Depende de la temperatura'], c: 1, ex: 'V = (0,085)³ = 6,14·10⁻⁴ m³. δ = m/V = 0,650 / 6,14·10⁻⁴ ≈ 1059 kg/m³. Como δ > 1000, se hunde.'},
  {st: 'Una pieza de metal pesa 90 g en el aire y 75 g sumergida en agua. ¿Cuál es su densidad? (δ_agua = 1 g/cm³)', opts: ['1,2 g/cm³', '6,0 g/cm³', '15 g/cm³', '90 g/cm³'], c: 1, ex: 'El empuje es la diferencia de pesos: E = 90 − 75 = 15 g fuerza. Esto corresponde al volumen de agua desalojado: V = 15 cm³ (porque δ_agua = 1 g/cm³). δ_metal = 90/15 = 6,0 g/cm³.'},
  {st: 'El principio de Pascal dice que la presión aplicada a un fluido encerrado:', opts: ['Se transmite solo hacia abajo', 'Se transmite por igual en todas direcciones', 'Se disipa con la distancia', 'Solo aumenta la temperatura'], c: 1, ex: 'El principio de Pascal: la presión aplicada se transmite sin disminuir a todos los puntos del fluido y a las paredes del recipiente. Es la base de la prensa hidráulica.'},
  {st: 'En una prensa hidráulica, si el émbolo pequeño tiene área A y el grande 6A, ¿qué fuerza F se necesita en el pequeño para sostener un peso de 600 N en el grande?', opts: ['100 N', '600 N', '1200 N', '3600 N'], c: 0, ex: 'Por Pascal: F/A = 600/(6A), entonces F = 600/6 = 100 N. La prensa multiplica la fuerza por la razón entre áreas.'},
  {st: '¿Por qué se usa mercurio y no agua en los barómetros?', opts: ['Porque es más barato', 'Porque su densidad es mucho mayor, la columna necesaria es más corta', 'Porque es transparente', 'Por razones históricas solamente'], c: 1, ex: 'Como p_atm = δ·g·h, con una densidad mayor (Hg: 13,6 g/cm³) la altura necesaria es menor (≈76 cm). Con agua (1 g/cm³) haría falta un tubo de ≈10 m. Por eso Torricelli eligió mercurio.'}
]);

// UNIDAD 4: CINEMÁTICA 1D
registerExercises('fisica', '4', [
  {st: '¿Cuál es la diferencia entre velocidad y rapidez?', opts: ['Son lo mismo', 'La velocidad es vectorial (tiene dirección); la rapidez es escalar', 'La rapidez es vectorial; la velocidad escalar', 'La rapidez es la derivada de la velocidad'], c: 1, ex: 'La rapidez es el módulo de la velocidad: solo un número positivo. La velocidad, como vector, también tiene dirección y sentido. Ir a 60 km/h al norte tiene la misma rapidez que ir a 60 km/h al sur, pero la velocidad es diferente.'},
  {st: 'En MRUV con aceleración constante a, ¿cuál es la ecuación horaria correcta de posición?', opts: [M('x(t) = x₀ + v·t'), M('x(t) = x₀ + v₀·t + ½·a·t²'), M('x(t) = x₀ + a·t²'), M('x(t) = v₀ + a·t')], c: 1, ex: 'En MRUV, la posición es cuadrática en t: x(t) = x₀ + v₀·t + ½·a·t². La opción 4 es la ecuación de velocidad, no posición.'},
  {st: 'Un antílope con aceleración constante tarda 7,00 s en pasar por dos puntos separados 70,0 m. Su rapidez en el segundo punto es 15,0 m/s. ¿Qué rapidez tenía en el primer punto?', opts: ['3,0 m/s', '5,0 m/s', '10,0 m/s', '12,5 m/s'], c: 1, ex: 'Δx = v_media · Δt. v_media = 70/7 = 10 m/s. En MRUV, v_media = (v_i + v_f)/2, entonces 10 = (v_i + 15)/2, y v_i = 5 m/s.'},
  {st: 'Con los datos del ejercicio anterior, ¿qué aceleración lleva el antílope?', opts: ['0,71 m/s²', '1,43 m/s²', '2,14 m/s²', '4,29 m/s²'], c: 1, ex: 'Con v_i = 5 y v_f = 15 en Δt = 7 s: a = (v_f − v_i)/Δt = (15 − 5)/7 = 10/7 ≈ 1,43 m/s².'},
  {st: 'Un malabarista lanza un cuchillo hacia arriba con v₀ = 8,20 m/s. ¿Cuánto tarda en volver a su mano?', opts: ['0,84 s', '1,67 s', '2,50 s', '8,20 s'], c: 1, ex: 'El tiempo de vuelo es el doble del tiempo de subida. v_f = 0 en el punto alto: 0 = 8,2 − 9,8·t_sub, t_sub = 0,837 s. Total: 2·0,837 ≈ 1,67 s.'},
  {st: 'En Marte (g = 3,71 m/s²), una pelota es golpeada hacia arriba y vuelve al mismo nivel 8,50 s después. ¿Con qué rapidez fue golpeada?', opts: ['7,9 m/s', '15,8 m/s', '31,5 m/s', '63,0 m/s'], c: 1, ex: 'El tiempo de subida es la mitad del total: 4,25 s. En el punto alto v = 0: v₀ = g·t_sub = 3,71·4,25 ≈ 15,8 m/s.'},
  {st: 'Una roca se suelta desde el reposo en la Tierra y llega al suelo en 1,75 s. En Encélado (luna de Saturno) la misma caída tarda 18,6 s. ¿Cuál es g en Encélado?', opts: ['0,087 m/s²', '0,87 m/s²', '1,05 m/s²', '9,80 m/s²'], c: 0, ex: 'h es la misma. Con Tierra: h = ½·9,8·(1,75)² ≈ 15 m. En Encélado: 15 = ½·g·(18,6)², entonces g = 2·15 / 18,6² ≈ 0,087 m/s².'},
  {st: 'En el gráfico v(t) de un movimiento, ¿qué representa el ÁREA bajo la curva?', opts: ['La aceleración', 'La velocidad media', 'El desplazamiento', 'La posición inicial'], c: 2, ex: 'El área bajo la curva v(t) es el desplazamiento Δx. La pendiente de v(t) es la aceleración. La pendiente de x(t) sería la velocidad.'},
  {st: 'Un cohete parte del suelo con v₀ = 50 m/s y acelera a 2 m/s² hacia arriba, hasta que se apagan los motores a 150 m de altura. ¿Con qué rapidez se apagan los motores?', opts: ['50 m/s', '54 m/s', '56 m/s', '70 m/s'], c: 2, ex: 'Usamos la ecuación sin tiempo: v² = v₀² + 2·a·Δx = 50² + 2·2·150 = 2500 + 600 = 3100. v ≈ 55,7 m/s ≈ 56 m/s.'}
]);

// UNIDAD 5: CINEMÁTICA 2D
registerExercises('fisica', '5', [
  {st: 'En el tiro oblicuo, ¿qué pasa con la componente horizontal de la velocidad durante el vuelo (sin rozamiento)?', opts: ['Aumenta linealmente', 'Permanece constante', 'Disminuye linealmente', 'Varía con el tiempo según t²'], c: 1, ex: 'La única fuerza durante el vuelo es la gravedad, que actúa solo en la dirección vertical. Como no hay fuerza horizontal, vₓ = v₀·cos(α) se mantiene constante durante todo el vuelo.'},
  {st: 'Un proyectil se lanza a 20 m/s formando 30° con la horizontal. ¿Cuál es su velocidad inicial en x?', opts: ['10 m/s', '17,3 m/s', '20 m/s', '10√3/2 m/s'], c: 1, ex: 'vₓ₀ = v₀·cos(30°) = 20·(√3/2) = 10√3 ≈ 17,3 m/s.'},
  {st: '¿Con qué ángulo de lanzamiento se obtiene el alcance máximo en tiro oblicuo (a igual altura)?', opts: ['30°', '45°', '60°', '90°'], c: 1, ex: 'El alcance es R = v₀²·sen(2α)/g. Máximo cuando sen(2α) = 1, es decir 2α = 90°, o sea α = 45°.'},
  {st: 'En el punto más alto de un tiro oblicuo, la velocidad es:', opts: ['Cero', 'Igual a la inicial', 'Solo horizontal (la inicial en x)', 'Solo vertical'], c: 2, ex: 'En el punto más alto, vᵧ = 0 (por eso es el más alto), pero vₓ sigue siendo v₀·cos(α). El vector velocidad es horizontal en ese instante.'},
  {st: 'Un auto en movimiento circular uniforme a rapidez 20 m/s en una curva de radio 40 m tiene aceleración centrípeta de:', opts: ['0,5 m/s²', '2 m/s²', '10 m/s²', '800 m/s²'], c: 2, ex: 'a_c = v²/R = (20)²/40 = 400/40 = 10 m/s².'},
  {st: '¿Qué significa que un movimiento circular sea "uniforme"?', opts: ['La aceleración es cero', 'La rapidez es constante', 'El vector velocidad es constante', 'No hay fuerza'], c: 1, ex: 'En MCU la RAPIDEZ (módulo de velocidad) es constante. Pero la velocidad como vector cambia (cambia su dirección), por eso hay aceleración centrípeta. NO es cierto que no haya aceleración: hay, y apunta al centro.'},
  {st: 'Si un cuerpo da 2 vueltas por segundo, su período T es:', opts: ['0,5 s', '1 s', '2 s', '4π s'], c: 0, ex: 'La frecuencia es f = 2 Hz. El período es T = 1/f = 1/2 = 0,5 s.'},
  {st: 'La relación entre velocidad lineal v, velocidad angular ω y radio R en un movimiento circular es:', opts: [M('v = ω/R'), M('v = ω·R'), M('v = R/ω'), M('v = ω + R')], c: 1, ex: 'La relación es v = ω·R. Dos ciclistas en una rueda que gira: el que está más lejos del centro (R grande) tiene más velocidad lineal, aunque la angular es la misma.'}
]);

// UNIDAD 6: DINÁMICA
registerExercises('fisica', '6', [
  {st: '¿Qué dice la segunda ley de Newton?', opts: [M('F = m·v'), M('ΣF⃗ = m·a⃗'), M('F = m·g'), M('F·d = m·a')], c: 1, ex: 'La 2° ley: la fuerza neta es igual a masa por aceleración (vector). La aceleración tiene la misma dirección que la fuerza neta.'},
  {st: 'Un cuerpo de 5 kg tiene una fuerza neta de 20 N aplicada. ¿Qué aceleración adquiere?', opts: ['0,25 m/s²', '4 m/s²', '15 m/s²', '100 m/s²'], c: 1, ex: 'Por 2° ley: a = F/m = 20/5 = 4 m/s².'},
  {st: '¿En qué situación se aplica la primera ley de Newton?', opts: ['Solo en reposo', 'Solo en movimiento', 'Cuando la fuerza neta es cero: reposo o MRU', 'Cuando hay aceleración'], c: 2, ex: 'La primera ley dice: si ΣF = 0, el cuerpo permanece en reposo o con velocidad constante (MRU). Abarca ambos casos como equivalentes.'},
  {st: 'Las fuerzas del "par acción-reacción" actúan:', opts: ['Sobre el mismo cuerpo y se cancelan', 'Sobre cuerpos distintos y son opuestas', 'Sobre el mismo cuerpo en la misma dirección', 'Solo cuando hay movimiento'], c: 1, ex: 'La 3° ley: si A ejerce F sobre B, entonces B ejerce −F sobre A. Actúan sobre cuerpos DIFERENTES, nunca se cancelan en el DCL de un mismo cuerpo. La Tierra te atrae (peso), vos atraés a la Tierra: fuerzas sobre cuerpos distintos.'},
  {st: '¿Cuál es la fuerza normal sobre un cuerpo de 10 kg apoyado sobre una mesa horizontal? (g = 9,8 m/s²)', opts: ['0', '10 N', '98 N', '980 N'], c: 2, ex: 'En el eje vertical: N − P = 0, entonces N = P = m·g = 10·9,8 = 98 N. En este caso particular, coincide con el peso.'},
  {st: '¿Cuál de estas afirmaciones sobre el rozamiento es correcta?', opts: ['El rozamiento estático máximo siempre vale μ·N', 'El rozamiento dinámico siempre es mayor que el estático', 'El rozamiento dinámico vale μd·N mientras el cuerpo se mueve', 'El rozamiento no depende de la normal'], c: 2, ex: 'f_d = μ_d·N cuando el cuerpo se mueve. El rozamiento estático puede valer cualquier cosa entre 0 y μ_s·N (se ajusta a lo necesario). Generalmente μ_s > μ_d.'},
  {st: 'Un resorte de constante k = 200 N/m se estira 5 cm. ¿Qué fuerza ejerce?', opts: ['0,4 N', '10 N', '40 N', '1000 N'], c: 1, ex: 'Ley de Hooke: |F| = k·x = 200·0,05 = 10 N. El signo es restaurador (hacia el equilibrio), pero en módulo es 10 N.'},
  {st: 'Un péndulo simple de 1 m de longitud. ¿Cuál es su período (aproximadamente)? (g = 9,8 m/s²)', opts: ['0,5 s', '1 s', '2 s', '2π s'], c: 2, ex: 'T = 2π·√(L/g) = 2π·√(1/9,8) ≈ 2π·0,32 ≈ 2,0 s. No depende de la masa.'},
  {st: 'En un auto que toma una curva, ¿qué fuerza produce la aceleración centrípeta?', opts: ['El peso', 'La fuerza centrífuga', 'El rozamiento de los neumáticos con el piso', 'La fuerza normal'], c: 2, ex: 'En una curva plana, es el rozamiento estático lateral de los neumáticos el que apunta hacia el centro y produce la aceleración centrípeta. La "fuerza centrífuga" es una fuerza ficticia (no existe en el sistema inercial).'}
]);

// UNIDAD 7: TRABAJO Y ENERGÍA
registerExercises('fisica', '7', [
  {st: '¿Cuánto trabajo hace una fuerza perpendicular al desplazamiento?', opts: ['El máximo', 'La mitad del máximo', 'Cero', 'Depende de la velocidad'], c: 2, ex: 'W = F·d·cos(θ). Si θ = 90°, cos(θ) = 0, por lo tanto W = 0. La fuerza normal, al ser perpendicular al movimiento sobre una superficie, nunca hace trabajo.'},
  {st: 'Una fuerza de 50 N empuja una caja 10 m en la misma dirección. ¿Cuánto trabajo hace?', opts: ['5 J', '50 J', '500 J', '5000 J'], c: 2, ex: 'W = F·d·cos(0°) = 50·10·1 = 500 J.'},
  {st: 'Un cuerpo de 2 kg se mueve a 5 m/s. ¿Cuál es su energía cinética?', opts: ['5 J', '10 J', '25 J', '50 J'], c: 2, ex: 'E_c = ½·m·v² = ½·2·(5)² = 25 J.'},
  {st: 'Si duplicás la velocidad de un cuerpo, su energía cinética:', opts: ['Se duplica', 'Se cuadruplica', 'Se mantiene igual', 'Se reduce a la mitad'], c: 1, ex: 'E_c depende de v². Si v → 2v, entonces E_c → (2v)² = 4v², o sea se cuadruplica. Por eso una colisión a 100 km/h es 4 veces más destructiva que a 50 km/h.'},
  {st: 'El teorema del trabajo y la energía cinética dice:', opts: [M('W_neto = m·g·h'), M('W_neto = ΔE_c'), M('W_neto = E_c + E_p'), M('W_neto = F·d')], c: 1, ex: 'El trabajo neto de todas las fuerzas sobre un cuerpo equivale al cambio en su energía cinética: W_neto = E_cf − E_ci.'},
  {st: 'Un cuerpo de 3 kg está a 10 m de altura. ¿Cuál es su energía potencial gravitatoria respecto del suelo? (g = 9,8 m/s²)', opts: ['30 J', '98 J', '294 J', '2940 J'], c: 2, ex: 'E_pg = m·g·h = 3·9,8·10 = 294 J.'},
  {st: '¿Cuál de estas fuerzas es conservativa?', opts: ['Rozamiento', 'Tensión de una cuerda que tira', 'Peso (gravedad cerca de la Tierra)', 'Fuerza normal'], c: 2, ex: 'El peso es conservativa: su trabajo depende solo del cambio de altura (no del camino). La fuerza elástica y la gravitatoria también lo son. El rozamiento NO es conservativo (depende del camino).'},
  {st: 'Se suelta una piedra desde 20 m de altura (sin rozamiento). ¿Con qué velocidad llega al suelo? (g = 9,8 m/s²)', opts: ['9,8 m/s', '14 m/s', '19,8 m/s', '392 m/s'], c: 2, ex: 'Por conservación de energía: m·g·h = ½·m·v², entonces v = √(2·g·h) = √(2·9,8·20) = √392 ≈ 19,8 m/s. No depende de la masa.'},
  {st: 'Si hay rozamiento en un sistema, la energía mecánica:', opts: ['Se conserva igual', 'Aumenta', 'Disminuye (se transforma en calor)', 'Cambia de dirección'], c: 2, ex: 'El rozamiento hace trabajo negativo (se opone al movimiento), y al no ser conservativa, "se come" energía mecánica, que se disipa como calor en la superficie de contacto.'}
]);
