registerExercises('fisiologia-digestiva', '1', [
  {st: 'El plexo de Auerbach (mientérico) controla principalmente:', opts: ['La secreción glandular y el flujo sanguíneo local', 'La motilidad del músculo liso digestivo', 'La absorción de nutrientes', 'La producción de hormonas GI'], c: 1, ex: 'Auerbach (mientérico) = entre capa circular y longitudinal → <b>motilidad</b>. Meissner (submucoso) regula secreción y flujo. Regla mnemotécnica: "Meissner — Mucosa — Mucho secreta".'},
  {st: 'Las ondas lentas del músculo liso digestivo:', opts: ['Producen contracción por sí mismas', 'Son despolarizaciones rítmicas generadas por células intersticiales de Cajal; solo contraen si aparecen potenciales en espiga sobre ellas', 'Son potenciales de acción típicos de motoneuronas', 'Se generan en el plexo submucoso'], c: 1, ex: 'Las células intersticiales de Cajal son los marcapasos del tubo digestivo. Generan ondas lentas sublímiticas; solo cuando la despolarización alcanza umbral aparecen espigas que disparan la contracción.'},
  {st: 'El sistema nervioso entérico:', opts: ['Depende del SNC para funcionar', 'Es capaz de coordinar reflejos locales de manera autónoma', 'Solo regula la secreción hormonal', 'Está formado por fibras simpáticas exclusivamente'], c: 1, ex: 'El SNE tiene ~100 millones de neuronas y ejecuta reflejos cortos sin pasar por el SNC. El SNA extrínseco (vago y simpático) modula pero no es indispensable: por eso se lo llama "segundo cerebro".'},
  {st: 'La inervación parasimpática del tubo digestivo:', opts: ['Se realiza por el simpático', 'Inhibe motilidad y secreción', 'Estimula motilidad y secreción vía Ach sobre receptores M3', 'Solo llega al colon distal'], c: 2, ex: 'El vago inerva desde esófago hasta la mitad del colon transverso; los nervios pélvicos inervan el resto. La Ach actúa sobre M3 del músculo liso y sobre células efectoras. El simpático en cambio inhibe.'},
  {st: '¿Cuál de estas hormonas digestivas es orexígena y se libera en ayuno?', opts: ['Leptina', 'Ghrelina', 'CCK', 'Secretina'], c: 1, ex: 'Ghrelina (fundus gástrico) aumenta en ayuno y estimula el apetito. La leptina, producida por adipocitos, es anorexígena. CCK y secretina son duodenales y se liberan postingesta.'}
]);

registerExercises('fisiologia-digestiva', '2', [
  {st: '¿Quién inicia el reflejo de la deglución?', opts: ['La presencia del alimento en la boca', 'El movimiento de la lengua hacia la faringe', 'Receptores sensoriales de la pared posterior de la faringe', 'La secreción de saliva inducida por el alimento'], c: 2, ex: 'Fase oral es voluntaria; la fase refleja dispara cuando el bolo toca la pared posterior de la faringe. La aferencia va por IX y X al bulbo, que coordina la secuencia motora.'},
  {st: '¿Qué es lo primero que se evacua del estómago?', opts: ['Electrolitos y H<sub>2</sub>O', 'Hidratos de carbono', 'Proteínas', 'Grasas'], c: 0, ex: 'Orden de vaciamiento: electrolitos/H<sub>2</sub>O &gt; HC &gt; proteínas &gt; grasas. Las grasas retrasan el vaciamiento (vía CCK y reflejos enterogástricos): por eso las comidas grasas generan plenitud.'},
  {st: 'El Complejo Motor Migratorio (CMM):', opts: ['Se induce postingesta', 'Es controlado por el SNE y la motilina; aparece cada 90–120 min en ayuno', 'Inhibe la secreción del páncreas', 'No se induce durante el sueño'], c: 1, ex: 'El CMM "barre" el tubo digestivo en ayuno. Se interrumpe al comer. La motilina (células M) dispara la fase III cada 90 min. Ocurre también durante el sueño.'},
  {st: 'Marque la opción correcta sobre motilidad gástrica:', opts: ['La grasa en el quimo acelera el vaciamiento gástrico', 'La distensión del íleon estimula la motilidad gástrica', 'La pérdida de células parietales disminuye la absorción de calcio', 'La aldosterona inhibe la absorción de Na+'], c: 2, ex: 'Sin HCl (pérdida de parietales), el Ca<sup>2+</sup> dietario se solubiliza peor y cae su absorción duodenal. La grasa enlentece el vaciamiento; la distensión ileal genera el reflejo íleo-gástrico que inhibe, no estimula.'},
  {st: 'Ante una lesión de las raíces sacras (S2–S4) se pierde:', opts: ['La contracción refleja del esfínter anal externo ante estímulo perianal', 'La secreción salival', 'El vaciamiento gástrico', 'El CMM'], c: 0, ex: 'El arco reflejo del esfínter anal externo (músculo estriado) pasa por nervios motores sacros (pudendo). Si la lesión es sacra, el estímulo perianal no produce respuesta del esfínter. Lesiones supra-sacras conservan el reflejo.'},
  {st: 'El reflejo gastrocólico consiste en:', opts: ['Distensión gástrica que inhibe motilidad colónica', 'Distensión gástrica que aumenta motilidad colónica, favoreciendo la defecación', 'Distensión colónica que inhibe motilidad gástrica', 'Contracción ileal que relaja el píloro'], c: 1, ex: 'Al distenderse el estómago con la comida, aumenta la motilidad del colon. Por eso muchas personas sienten ganas de defecar poco después del desayuno. Es mediado por el SNE y amplificado por la gastrina/CCK.'}
]);

registerExercises('fisiologia-digestiva', '3', [
  {st: 'Con respecto a la secreción salival:', opts: ['En condiciones basales predomina la secreción serosa', 'Presenta siempre una secreción hipotónica con respecto al plasma', 'Las concentraciones de Na+ y Cl– son mayores que las del plasma', 'Las concentraciones de HCO<sub>3</sub><sup>–</sup> y K+ son menores que las del plasma'], c: 1, ex: 'El acino secreta isotónico; los ductos reabsorben Na+/Cl– y secretan K+/HCO<sub>3</sub><sup>–</sup> sin dejar salir agua → saliva final hipotónica siempre. A flujos altos se parece más a la primaria pero nunca llega a isotónica.'},
  {st: '¿Cómo será la saliva que llegue a la boca en un sujeto que está por almorzar?', opts: ['Abundante e hipertónica respecto del plasma', 'Escasa e hipotónica respecto del plasma', 'Escasa e isotónica respecto del plasma', 'Abundante e hipotónica respecto del plasma'], c: 3, ex: 'Reflejo salival anticipatorio (fase cefálica vagal) → saliva abundante. La saliva nunca es hipertónica: la modificación ductal siempre quita solutos sin dejar salir agua.'},
  {st: 'La regulación de la secreción salival:', opts: ['Está controlada principalmente por CCK y secretina', 'Es 100% nerviosa (autónoma), sin control hormonal', 'Depende de la gastrina', 'Solo responde al simpático'], c: 1, ex: 'La saliva es la única secreción digestiva regulada exclusivamente por SNA, sin componente hormonal. Parasimpático (principal, abundante/acuosa) y simpático (escasa/viscosa).'},
  {st: '¿Qué enzima salival inicia la digestión del almidón?', opts: ['Lipasa lingual', 'Amilasa salival (ptialina)', 'Pepsina', 'Tripsina'], c: 1, ex: 'La α-amilasa salival (ptialina) hidroliza los enlaces α-1,4 del almidón. Actúa a pH ~7 y se inactiva en el pH gástrico. La amilasa pancreática continúa la digestión en el duodeno.'}
]);

registerExercises('fisiologia-digestiva', '4', [
  {st: 'Las células enterocromafines-like (ECL) del estómago liberan un mediador que estimula a la célula parietal. ¿Qué receptor debe bloquearse para neutralizar ese estímulo?', opts: ['CCK-A', 'CCK-B', 'M3', 'H2'], c: 3, ex: 'ECL libera histamina por vía paracrina sobre la parietal, que responde vía receptor <b>H2</b>. Bloqueantes H2 (ranitidina, famotidina) reducen la secreción ácida. La terapia más potente son los IBP (omeprazol) que bloquean la bomba H+/K+ ATPasa final.'},
  {st: '¿Cuál es un estímulo para la secreción de gastrina?', opts: ['Aminoácidos en la luz del estómago', 'Somatostatina', 'pH luminal &lt; 2', 'Adrenalina'], c: 0, ex: 'Estímulos de gastrina: aminoácidos/péptidos en luz, distensión, GRP vagal. Freno: pH &lt; 3 (vía somatostatina), que es la razón del feedback negativo cuando baja mucho el pH gástrico.'},
  {st: 'La célula parietal secreta HCl a través de:', opts: ['Canal de Cl– pasivo luminal', 'Bomba H+/K+ ATPasa en la membrana luminal', 'Bomba Na+/K+ ATPasa basolateral', 'Cotransporte Na+/H+'], c: 1, ex: 'La H+/K+ ATPasa luminal intercambia un H+ por un K+ consumiendo ATP. Los IBP (omeprazol) bloquean esta bomba. El HCO<sub>3</sub><sup>–</sup> que se genera sale por la basolateral → "marea alcalina" postprandial.'},
  {st: 'El factor intrínseco:', opts: ['Se secreta en el páncreas y sirve para activar pepsinógeno', 'Se secreta en la célula parietal y es necesario para absorber vitamina B12 en íleon terminal', 'Se sintetiza en el hígado', 'Absorbe hierro en duodeno'], c: 1, ex: 'FI es una glicoproteína de la parietal. Se une a B12 y el complejo se absorbe en íleon terminal por endocitosis (cubilina). Sin FI (gastrectomía, anemia perniciosa por autoAc anti-parietal) → déficit de B12.'},
  {st: 'La fase cefálica de la secreción gástrica:', opts: ['Se dispara por distensión gástrica', 'Se dispara por quimo en duodeno', 'Se dispara por ver, oler o pensar en comida; llega por el vago', 'Está mediada por CCK'], c: 2, ex: 'Cefálica = estímulos sensoriales o cognitivos → vago → Ach (M3 parietal) y GRP (célula G). Aporta ~30% de la secreción. Gástrica ~60%, intestinal neta ~10% (por la inhibición de secretina/GIP).'},
  {st: '¿Por qué el omeprazol es más potente que los bloqueantes H2?', opts: ['Aumenta la secreción de somatostatina', 'Bloquea directamente la bomba H+/K+ ATPasa, vía final común', 'Inhibe a la gastrina en las células G', 'Neutraliza el HCl en la luz'], c: 1, ex: 'Los bloqueantes H2 solo eliminan la amplificación por histamina, pero las vías vagal (M3) y gastrina (CCK-B) siguen funcionando. El omeprazol inactiva irreversiblemente la bomba final → secreción cae a casi cero.'}
]);

registerExercises('fisiologia-digestiva', '5', [
  {st: 'La secreción exocrina del páncreas:', opts: ['Es estimulada por la presencia de un pH luminal bajo', 'Es inhibida por la acetilcolina', 'Contiene pepsinógeno', 'Se regula sólo por vía hormonal'], c: 0, ex: 'El pH ácido en duodeno libera secretina, que estimula a los ductos a secretar HCO<sub>3</sub><sup>–</sup>. La Ach (vago, M3) estimula, no inhibe. El pepsinógeno se produce en estómago. Hay regulación nerviosa y hormonal.'},
  {st: '¿Qué hormona estimula principalmente la secreción de enzimas pancreáticas ante grasa y proteínas en duodeno?', opts: ['Secretina', 'CCK (colecistocinina)', 'GIP', 'Gastrina'], c: 1, ex: 'CCK (células I, duodeno/yeyuno) responde a AG de cadena larga y péptidos: estimula ácinos pancreáticos, contrae la vesícula y relaja el esfínter de Oddi. Secretina estimula HCO<sub>3</sub><sup>–</sup> ductal.'},
  {st: 'La activación de las enzimas pancreáticas en el duodeno depende de:', opts: ['El pH ácido del HCl gástrico', 'La enterocinasa del borde en cepillo duodenal que activa el tripsinógeno', 'La amilasa salival', 'La bilis'], c: 1, ex: 'Enterocinasa (enteropeptidasa) duodenal activa tripsinógeno → tripsina → activa en cascada al resto. Los zimógenos se secretan inactivos para evitar autodigestión del páncreas; SPINK1 aporta protección adicional en el ácino.'},
  {st: 'El líquido pancreático rico en HCO<sub>3</sub><sup>–</sup>:', opts: ['Lo producen los ácinos', 'Lo producen las células ductales en respuesta a secretina', 'Se produce constitutivamente sin estímulo', 'Depende exclusivamente del vago'], c: 1, ex: 'División de tareas: <b>ácinos → enzimas</b> (estímulo CCK y Ach); <b>ductos → HCO<sub>3</sub><sup>–</sup></b> (estímulo secretina). CCK y secretina se potencian entre sí en la fase intestinal, que aporta ~65% de la secreción total.'},
  {st: 'En la pancreatitis aguda:', opts: ['Hay hipersecreción de HCO<sub>3</sub><sup>–</sup> como evento principal', 'Falla la barrera antiautoactivación y las enzimas se activan dentro del páncreas produciendo autodigestión', 'Se debe a exceso de amilasa salival', 'Se inicia por bloqueo del esfínter esofágico inferior'], c: 1, ex: 'Mecanismos de protección normales: zimógenos, enterocinasa solo en duodeno, SPINK1. Si tripsina se activa prematuramente (cálculo biliar, alcohol, trauma) → cascada de autodigestión → pancreatitis.'}
]);

registerExercises('fisiologia-digestiva', '6', [
  {st: '¿Cuál es la función principal del hígado durante la digestión de alimentos?', opts: ['Síntesis de enzimas digestivas', 'Generar una sustancia alcalina que amortigüe el pH ácido luminal', 'Emulsionar las grasas de la dieta para permitir su absorción', 'Activar las proteasas pancreáticas'], c: 2, ex: 'La bilis contiene ácidos biliares anfipáticos que emulsionan las grasas en micelas, aumentando la superficie para la lipasa pancreática. Sin bilis → esteatorrea. No tiene enzimas digestivas.'},
  {st: '¿Cómo hace el duodeno para evitar el aumento del pH ácido que llega desde el estómago?', opts: ['Aumentando la secreción de saliva', 'Por la secreción ductal pancreática y canalicular biliar de HCO<sub>3</sub><sup>–</sup> ante secretina', 'Inhibiendo la motilidad intestinal', 'Activando pepsina'], c: 1, ex: 'El pH &lt; 4.5 en duodeno libera secretina, que estimula HCO<sub>3</sub><sup>–</sup> de ductos pancreáticos y biliares (colangiocitos). Ese HCO<sub>3</sub><sup>–</sup> neutraliza el HCl, protege la mucosa y permite el pH óptimo de las enzimas.'},
  {st: 'Ante hipoalbuminemia con función renal y hepática conservadas, la causa más probable es:', opts: ['Disminución de la reabsorción de proteínas en TCP', 'Aumento de la filtración de proteínas por la barrera glomerular', 'Disminución de la síntesis de proteínas hepáticas', 'Desnutrición proteica'], c: 3, ex: 'Si hígado y riñón funcionan (no hay pérdida por orina ni déficit de síntesis), la hipoalbuminemia indica menor aporte. La albúmina se produce exclusivamente en el hígado.'},
  {st: 'Si el hígado fallara:', opts: ['La presión oncótica aumentaría y la osmolaridad quedaría igual', 'Ambas disminuirían', 'La presión oncótica aumentaría al igual que la osmolaridad', 'La presión oncótica disminuiría y la osmolaridad no cambiaría'], c: 3, ex: 'Sin hígado, cae la síntesis de albúmina → ↓ P oncótica → edema/ascitis. La osmolaridad (determinada por electrolitos y urea) apenas se afecta: las proteínas contribuyen poco a la osmolaridad total.'},
  {st: 'La circulación enterohepática de los ácidos biliares:', opts: ['Los ácidos biliares se reabsorben en el duodeno', 'Se reabsorben en el íleon terminal por transporte activo Na+-dependiente (ASBT) y vuelven al hígado por la vena porta', 'Se pierden en un 90% por heces', 'Solo ocurre en ayuno'], c: 1, ex: 'Reabsorción ileal activa (ASBT) → vena porta → hígado resecreta. Cada molécula recircula 6–10 veces/día. Solo ~5% se pierde por heces y el hígado lo repone desde colesterol.'},
  {st: 'La contracción de la vesícula biliar durante la comida se produce por:', opts: ['Secretina', 'Gastrina', 'CCK liberada ante grasas y proteínas en duodeno', 'Somatostatina'], c: 2, ex: 'CCK contrae la vesícula y relaja el esfínter de Oddi → la bilis concentrada cae al duodeno. Secretina estimula el componente ductal biliar (HCO<sub>3</sub><sup>–</sup>).'}
]);

registerExercises('fisiologia-digestiva', '7', [
  {st: 'La glucosa se absorbe en el intestino por:', opts: ['Difusión simple por vía paracelular', 'SGLT1 acoplado a Na+ en la membrana apical', 'GLUT4 (dependiente de insulina)', 'Endocitosis'], c: 1, ex: 'Apical: SGLT1 (2 Na+ : 1 glucosa) = transporte activo secundario. Basolateral: GLUT2 (pasivo). La fructosa entra por GLUT5. GLUT4 es muscular/adiposo, dependiente de insulina.'},
  {st: 'Con respecto a los GLUT:', opts: ['GLUT2 son dependientes de insulina y están en hígado y páncreas', 'GLUT4 son dependientes de insulina y están en hígado y páncreas', 'GLUT2 son independientes de insulina y están en hígado y páncreas', 'GLUT4 son independientes de insulina y están en músculo y adiposo'], c: 2, ex: 'GLUT2 = hígado, páncreas (β), enterocito basolateral, de alta Km, independiente de insulina. GLUT4 = músculo y adiposo, dependiente de insulina (se trasloca a membrana por estímulo de insulina).'},
  {st: 'Los quilomicrones formados en el enterocito:', opts: ['Se vuelcan directamente a la sangre portal', 'Salen por el polo basolateral al vaso linfático (quilífero)', 'Se almacenan en la luz intestinal', 'Van al hígado vía arteria hepática'], c: 1, ex: 'AG y MAG entran al enterocito por difusión pasiva desde micelas → reesterificación a TG en REL → ensamble con apo-B48 → exocitosis basolateral al quilífero linfático. De ahí al conducto torácico y vena subclavia.'},
  {st: 'El aumento de vitamina D3 (calcitriol) en el intestino:', opts: ['Aumenta la reabsorción de calcio y fósforo', 'Disminuye la de calcio y aumenta la de fósforo', 'Disminuye ambas', 'Aumenta solo la de calcio y disminuye la de fósforo'], c: 0, ex: 'El calcitriol induce la síntesis de TRPV6, calbindina y PMCA en el enterocito duodenal → aumenta la absorción activa de Ca<sup>2+</sup>. También aumenta absorción de fosfato. Por eso el déficit de vit D causa raquitismo/osteomalacia.'},
  {st: '¿En qué segmento del tubo digestivo se absorbe principalmente el calcio por vía activa?', opts: ['Estómago', 'Duodeno (regulada por vit D)', 'Íleon terminal', 'Colon'], c: 1, ex: 'Duodeno es el sitio principal de absorción activa regulada por vit D. Hay absorción paracelular menor a lo largo del intestino. La pérdida de células parietales (↓ HCl) disminuye la solubilización del Ca<sup>2+</sup> y su absorción.'},
  {st: 'La hepcidina:', opts: ['Aumenta la reabsorción renal de hierro', 'Se sintetiza en el hígado y disminuye la absorción intestinal de hierro al bloquear la ferroportina', 'Aumenta la absorción intestinal de hierro', 'Es producida por los eritrocitos'], c: 1, ex: 'Hepcidina hepática es el regulador maestro del hierro. Bloquea ferroportina en enterocitos y macrófagos, impidiendo la salida de hierro a la sangre. ↑ en inflamación (anemia de enfermedad crónica); ↓ en déficit de hierro.'},
  {st: 'La vitamina B12:', opts: ['Se absorbe en el duodeno por DMT1', 'Se absorbe en el íleon terminal en complejo con factor intrínseco', 'Es sintetizada por el hígado', 'Se absorbe en el estómago junto con el FI'], c: 1, ex: 'FI gástrico se une a B12 y el complejo FI-B12 es endocitado por cubilina en íleon terminal. Gastrectomía o resección ileal → déficit de B12 → anemia megaloblástica. Distancia FI↔sitio de absorción es la clave de muchos casos clínicos.'}
]);

registerExercises('fisiologia-digestiva', '8', [
  {st: 'La secretina:', opts: ['Se libera ante la presencia de grasas en duodeno y estimula enzimas pancreáticas', 'Se libera ante pH &lt; 4.5 en duodeno y estimula HCO<sub>3</sub><sup>–</sup> pancreático/biliar ductal', 'Es producida por el estómago', 'Contrae la vesícula biliar'], c: 1, ex: 'Regla simple: CCK → enzimas + vesícula (estímulo: grasas y proteínas); secretina → HCO<sub>3</sub><sup>–</sup> (estímulo: ácido). Se potencian mutuamente. Es un feedback negativo: al neutralizar el ácido, la secretina baja.'},
  {st: 'El efecto incretina consiste en que:', opts: ['Una carga oral de glucosa libera más insulina que la misma carga por vía IV, por acción de GIP y GLP-1', 'La insulina IV actúa más que la oral', 'La glucagón se libera con más fuerza por vía oral', 'No hay diferencia entre oral e IV'], c: 0, ex: 'Incretinas GIP (células K) y GLP-1 (células L) se liberan con nutrientes en el tubo y potencian la secreción de insulina ante glucosa en la célula β. Los agonistas de GLP-1 (semaglutide) y los inhibidores de DPP-4 son tratamientos en DBT2.'},
  {st: 'La somatostatina:', opts: ['Estimula la liberación de gastrina', 'Es un inhibidor universal: reduce gastrina, HCl, enzimas y motilidad', 'Contrae la vesícula biliar', 'Estimula la motilidad gástrica'], c: 1, ex: 'Somatostatina (células D) se libera con pH gástrico bajo y frena casi todo: gastrina, HCl, enzimas pancreáticas, motilidad. Los análogos (octreotide) se usan clínicamente en hemorragia por várices, tumores neuroendocrinos, acromegalia.'},
  {st: 'CCK se libera principalmente ante:', opts: ['Ácido en duodeno', 'Ácidos grasos de cadena larga y proteínas en duodeno/yeyuno', 'Distensión gástrica', 'Glucosa solamente'], c: 1, ex: 'CCK (células I) responde a lípidos y péptidos. Efectos: ↑ enzimas pancreáticas, contrae vesícula, relaja Oddi, enlentece vaciamiento gástrico, saciedad central. Actúa vía CCK-A en ácinos/vesícula.'},
  {st: 'Durante la fase intestinal de la secreción gástrica:', opts: ['Predomina la estimulación neta', 'Inicialmente hay estímulo (gastrina intestinal) pero pronto predomina la inhibición por secretina, GIP, CCK y reflejos enterogástricos', 'No hay cambios respecto de la fase gástrica', 'Se reactiva la fase cefálica'], c: 1, ex: 'Fase intestinal: pequeño estímulo inicial, luego inhibición neta. Las hormonas duodenales frenan al estómago (enterogastronas) y regulan el vaciamiento para no sobrecargar al duodeno.'}
]);
