registerExercises('algebra-segundo-parcial', '1', [
  {st: 'El 2° parcial Escayola tiene 8 ejercicios de opción múltiple. ¿Cuánto vale cada uno?', opts: ['1 punto', '1,25 puntos', '1,5 puntos', '2 puntos'], c: 1, ex: 'Mismo formato que el 1° parcial: 10 puntos repartidos en 8 ejercicios → 10/8 = 1,25 cada uno, todos por igual. ▸ Por qué las otras están mal: "1 punto" (×8 = 8) no llega a 10; "1,5" (×8 = 12) y "2" (×8 = 16) se pasan del total.'},
  {st: 'Si en el enunciado ves "discutir según k", "rango" y "SCD / SCI / SI", el tema es:', opts: ['Números complejos', 'Polinomios', 'Sistemas de ecuaciones lineales', 'Transformaciones lineales'], c: 2, ex: 'Rango y la clasificación SCD/SCI/SI son el lenguaje de los sistemas lineales (unidad 5). Se resuelven escalonando la matriz ampliada. ▸ Por qué las otras están mal: complejos hablan de módulo/argumento; polinomios de raíces/grado; las TL de núcleo/imagen (aunque internamente también usan sistemas, el enunciado diría "T(x)=...").'},
  {st: 'Para una matriz A de 3×3, ¿a qué es igual det(2A)?', opts: ['2·det(A)', '6·det(A)', '8·det(A)', 'det(A)'], c: 2, ex: 'La propiedad es det(k·A) = kⁿ·det(A), con n = tamaño de la matriz. Para 3×3: det(2A) = 2³·det(A) = 8·det(A). ▸ Intuición: el factor 2 multiplica las 3 filas, y cada fila aporta un 2 al determinante. ▸ Por qué las otras están mal: "2·det(A)" olvida el exponente; "6·det(A)" confunde 2³ con 2·3; "det(A)" ignora el escalar.'},
  {st: 'Toda transformación lineal T cumple obligatoriamente:', opts: ['T(0) = 0', 'T(1) = 1', 'T(x) = x para todo x', 'T(0) = 1'], c: 0, ex: 'De T(k·u) = k·T(u) con k = 0 sale T(0) = 0·T(u) = 0. Es el test relámpago: si T(0) ≠ 0, no es lineal. ▸ Por qué las otras están mal: "T(1)=1" y "T(x)=x" describen la identidad, no toda TL; "T(0)=1" contradice justamente la propiedad (una constante no nula rompe la linealidad).'},
  {st: 'El teorema de las dimensiones, para T: ℝⁿ → ℝᵐ, afirma que:', opts: ['dim Nu(T) + dim Im(T) = m', 'dim Nu(T) + dim Im(T) = n', 'dim Nu(T) = dim Im(T)', 'dim Nu(T) · dim Im(T) = n'], c: 1, ex: 'La suma de las dimensiones del núcleo y la imagen es la dimensión del DOMINIO, que es n (no m, que es la del codominio). ▸ Sirve para hallar una dimensión gratis si conocés la otra. ▸ Por qué las otras están mal: usar m confunde dominio con codominio; "iguales" o "producto = n" no son el teorema.'},
  {st: 'Para calcular zⁿ con n grande (por ejemplo z⁸), lo más eficiente es:', opts: ['multiplicar z por sí mismo n veces en binómica', 'pasar z a forma polar y aplicar De Moivre', 'calcular el conjugado de z', 'sumar la parte real y la imaginaria'], c: 1, ex: 'En polar, zⁿ = rⁿ·e^(inθ): elevás el módulo a la n y multiplicás el argumento por n. Dos pasos. ▸ Por qué las otras están mal: multiplicar en binómica 8 veces es lento y propenso a error; el conjugado y "sumar partes" no tienen nada que ver con potencias.'},
  {st: 'Si P ∈ ℝ[x] y 3 − 2i es raíz de P, entonces también es raíz:', opts: ['3 + 2i', '−3 + 2i', '2 − 3i', '−3 − 2i'], c: 0, ex: 'En ℝ[x] las raíces complejas vienen de a pares conjugados: si 3 − 2i es raíz, su conjugada 3 + 2i también (con la misma multiplicidad). ▸ El conjugado cambia SOLO el signo de la parte imaginaria. ▸ Por qué las otras están mal: cambian además el signo de la parte real (−3) o intercambian partes (2−3i), cosas que el conjugado no hace.'}
]);

registerExercises('algebra-segundo-parcial', '2', [
  {st: 'El determinante de la matriz [[2, 1], [5, 3]] es:', opts: ['1', '11', '−1', '13'], c: 0, ex: 'det 2×2 = a·d − b·c = 2·3 − 1·5 = 6 − 5 = 1. ▸ Como da ≠ 0, la matriz es inversible. ▸ Por qué las otras están mal: "11" suma en vez de restar (6+5); "−1" invierte el orden de la resta; "13" mezcla productos cruzados mal.'},
  {st: 'A es una matriz 3×3 con det(A) = 3. Entonces det(2A) vale:', opts: ['6', '24', '9', '48'], c: 1, ex: 'det(2A) = 2³·det(A) = 8·3 = 24 (el escalar va elevado a n=3). ▸ Por qué las otras están mal: "6" hace 2·3 (olvida el exponente); "9" sería det(A)²; "48" usaría 2⁴ (n=4, pero la matriz es 3×3).'},
  {st: 'Para el sistema kx + y = 1, x + ky = 1, ¿qué tipo es cuando k = −1?', opts: ['SCD (solución única)', 'SCI (infinitas soluciones)', 'SI (sin solución)', 'no se puede determinar'], c: 2, ex: 'Con k = −1 el sistema es −x + y = 1 y x − y = 1, es decir x − y = −1 y x − y = 1: la misma combinación da dos valores distintos → contradicción → SI. ▸ Por qué las otras están mal: el determinante k²−1 se anula en k=−1, así que NO es SCD; y NO es SCI porque los términos independientes son incompatibles (por eso siempre hay que mirar la columna de b cuando det = 0).'},
  {st: 'La matriz [[k,1,1],[1,k,1],[1,1,k]] tiene det = (k−1)²(k+2). ¿Para qué k NO es inversible?', opts: ['k = 1 o k = −2', 'k = −1 o k = 2', 'solo k = 0', 'para ningún valor de k'], c: 0, ex: 'No inversible ⟺ det = 0 ⟺ (k−1)²(k+2) = 0 ⟺ k = 1 (raíz doble) o k = −2. ▸ Por qué las otras están mal: "−1 o 2" son los signos cambiados de las raíces; "solo k=0" da det = (−1)²·2 = 2 ≠ 0 (sí es inversible); "ningún k" es falso, sí hay valores que la anulan.'},
  {st: 'Si A = [[2,1],[5,3]] y b = (1, 1), la solución de A·x = b es:', opts: ['(2, −3)', '(−3, 2)', '(1, 1)', '(2, 3)'], c: 0, ex: 'det(A)=1, así que A⁻¹ = [[3,−1],[−5,2]]. Entonces x = A⁻¹·b = (3·1 + (−1)·1, (−5)·1 + 2·1) = (2, −3). ▸ Verificación: 2·2+1·(−3)=1 ✓ y 5·2+3·(−3)=1 ✓. ▸ Por qué las otras están mal: "(−3,2)" invierte las componentes; "(1,1)" es b, no x; "(2,3)" falla la 2ª ecuación (10+9=19≠1).'},
  {st: 'Si A es 3×3 con det(A) = 3, entonces det(A⁻¹) vale:', opts: ['3', '1/3', '−3', '9'], c: 1, ex: 'det(A⁻¹) = 1/det(A) = 1/3 (porque det(A)·det(A⁻¹) = det(A·A⁻¹) = det(I) = 1). ▸ Por qué las otras están mal: "3" es det(A), no su inverso; "−3" inventa un signo; "9" sería det(A)² o det(A²).'},
  {st: 'Sobre el producto de matrices, ¿qué afirmación es VERDADERA?', opts: ['siempre A·B = B·A', 'en general A·B ≠ B·A', 'si existe A·B nunca existe B·A', 'A·B = B·A solo si son 2×2'], c: 1, ex: 'El producto de matrices NO es conmutativo en general: el orden importa. ▸ Ejemplo: [[1,2],[0,1]]·[[1,0],[3,1]] = [[7,2],[3,1]] pero al revés da [[1,2],[3,7]]. ▸ Por qué las otras están mal: la conmutatividad falla casi siempre; B·A puede existir aunque dé otra cosa; el tamaño 2×2 no garantiza conmutar.'}
]);

registerExercises('algebra-segundo-parcial', '3', [
  {st: '¿Cuál de estas funciones NO es una transformación lineal?', opts: ['T(x,y) = (x+y, 2x)', 'T(x,y) = (2x, 3y)', 'T(x,y) = (x+1, y)', 'T(x,y) = (x, −y)'], c: 2, ex: 'T(x,y)=(x+1,y) da T(0,0)=(1,0) ≠ (0,0): falla T(0)=0, así que NO es lineal (la constante +1 la rompe). ▸ Por qué las otras SÍ son TL: las tres tienen solo términos lineales y cumplen T(0)=0; se verifican suma y producto por escalar sin problema.'},
  {st: 'La matriz canónica de T(x,y,z) = (x + 2y, y − z) es:', opts: ['[[1,2,0],[0,1,−1]]', '[[1,0],[2,1],[0,−1]]', '[[1,2],[0,−1]]', '[[1,1,0],[0,2,−1]]'], c: 0, ex: 'Las columnas son las imágenes de los canónicos: T(e₁)=(1,0), T(e₂)=(2,1), T(e₃)=(0,−1). Puestas como columnas: [[1,2,0],[0,1,−1]] (2 filas = llegada ℝ², 3 columnas = salida ℝ³). ▸ Por qué las otras están mal: la 2ª es la traspuesta (3×2); la 3ª olvida una variable; la 4ª arma mal los coeficientes.'},
  {st: 'Para T(x,y,z) = (x + y, y − z), la dimensión del núcleo es:', opts: ['0', '1', '2', '3'], c: 1, ex: 'Resuelvo T(x,y,z)=(0,0): x+y=0 → y=−x; y−z=0 → z=−x. Soluciones (x,−x,−x)=x·(1,−1,−1) → Nu = ⟨(1,−1,−1)⟩, dim 1. ▸ Por qué las otras están mal: "0" significaría inyectiva (Nu trivial), pero acá hay todo un eje de soluciones; "2" o "3" sobreestiman (solo queda un parámetro libre, x).'},
  {st: 'Para esa misma T (de ℝ³ en ℝ²), la dimensión de la imagen es:', opts: ['0', '1', '2', '3'], c: 2, ex: 'Por el teorema de las dimensiones: dim Im = n − dim Nu = 3 − 1 = 2. Como Im ⊆ ℝ² y tiene dim 2, Im = ℝ² (T es sobreyectiva). ▸ Por qué las otras están mal: "3" es imposible, la imagen vive en ℝ² (dim máx 2); "0" o "1" contradicen el teorema con dim Nu = 1.'},
  {st: 'T(x,y) = (x + ay, ax + y) tiene matriz [[1,a],[a,1]] (det = 1 − a²). ¿Para qué a es biyectiva?', opts: ['para todo a', 'para a ≠ 1 y a ≠ −1', 'solo para a = 0', 'para a = 1 o a = −1'], c: 1, ex: 'Va de ℝ² en ℝ², así que biyectiva ⟺ det ≠ 0 ⟺ 1 − a² ≠ 0 ⟺ a ≠ ±1. ▸ Por qué las otras están mal: "todo a" ignora que en a=±1 falla; "solo a=0" es innecesariamente restrictivo (a=2 también sirve); "a=±1" es justo donde NO es biyectiva (ahí det=0).'},
  {st: 'Una transformación lineal T: ℝ³ → ℝ³ es inyectiva si y solo si:', opts: ['Nu(T) = {0}', 'Im(T) = {0}', 'dim Nu(T) = 3', 'el det de su matriz = 0'], c: 0, ex: 'Inyectiva ⟺ núcleo trivial (Nu = {0}) ⟺ dim Nu = 0 ⟺ det ≠ 0. ▸ Como dominio y codominio tienen igual dimensión (3), esto equivale a sobreyectiva y biyectiva. ▸ Por qué las otras están mal: Im={0} sería la transformación nula; dim Nu=3 es lo contrario (todo se aplasta al 0); det=0 caracteriza la NO inyectividad.'},
  {st: 'Si T y S son TL componibles, la matriz de la composición S∘T es:', opts: ['M(S)·M(T)', 'M(T)·M(S)', 'M(S) + M(T)', 'M(S) − M(T)'], c: 0, ex: 'La matriz de S∘T es el producto M(S)·M(T): la que se aplica PRIMERO (T) va a la derecha, porque actúa primero sobre el vector. ▸ Por qué las otras están mal: M(T)·M(S) invierte el orden (daría T∘S); sumar o restar matrices no representa composición de funciones.'}
]);

registerExercises('algebra-segundo-parcial', '4', [
  {st: 'El cociente (2 + i) / (1 − i) es igual a:', opts: ['1/2 + (3/2)i', '3/2 + (1/2)i', '1 + 3i', '1/2 − (3/2)i'], c: 0, ex: 'Multiplico arriba y abajo por el conjugado del denominador (1+i): numerador (2+i)(1+i)=2+2i+i+i²=1+3i; denominador (1−i)(1+i)=1−i²=2. Resultado (1+3i)/2 = 1/2 + (3/2)i. ▸ Por qué las otras están mal: "3/2 + 1/2 i" intercambia partes; "1+3i" olvida dividir por 2; "1/2 − 3/2 i" erra el signo de la parte imaginaria.'},
  {st: 'El módulo de z = −1 + √3·i es:', opts: ['1', '2', '4', '√3'], c: 1, ex: '|z| = √(a²+b²) = √((−1)² + (√3)²) = √(1+3) = √4 = 2. ▸ El signo de a no afecta (va al cuadrado). ▸ Por qué las otras están mal: "1" toma solo la parte real; "4" olvida la raíz (4 es a²+b²); "√3" toma solo la parte imaginaria.'},
  {st: 'El argumento (principal) de z = −1 + √3·i es:', opts: ['π/3', '2π/3', '−π/3', 'π/6'], c: 1, ex: 'El punto (−1, √3) está en el 2° cuadrante (a<0, b>0). El ángulo de referencia es arctan(√3/1)=π/3, así que θ = π − π/3 = 2π/3. ▸ Verificación: 2·cos(2π/3)=2·(−1/2)=−1 ✓ y 2·sen(2π/3)=2·(√3/2)=√3 ✓. ▸ Por qué las otras están mal: π/3 y −π/3 corresponden al 1° y 4° cuadrante; π/6 no encaja. Olvidar ajustar el cuadrante es el error clásico.'},
  {st: '(1 + i)⁸ es igual a:', opts: ['16', '−16', '16i', '256'], c: 0, ex: 'Para 1+i: r=√2, θ=π/4. Por De Moivre: (√2)⁸·e^(i·8·π/4) = 2⁴·e^(i·2π) = 16·1 = 16. ▸ Por qué las otras están mal: "−16" usaría e^(iπ); "16i" usaría un argumento π/2; "256" confunde (√2)⁸=16 con 2⁸=256.'},
  {st: 'La ecuación z³ = 8 tiene:', opts: ['una sola solución (z = 2)', 'tres soluciones: 2, −1+√3 i, −1−√3 i', 'dos soluciones', 'infinitas soluciones'], c: 1, ex: 'zⁿ=w tiene exactamente n soluciones. Acá |8|=8, arg 0 → z_k = 2·e^(i·2kπ/3), k=0,1,2: dan 2, −1+√3 i, −1−√3 i (triángulo equilátero de radio 2). ▸ Por qué las otras están mal: "solo z=2" olvida las raíces complejas; "dos" o "infinitas" contradicen el teorema (grado 3 → 3 raíces).'},
  {st: 'Para cualquier número complejo z, el producto z·z̄ es igual a:', opts: ['|z|²', '2·Re(z)', '0', 'z²'], c: 0, ex: 'Si z=a+bi, z·z̄ = (a+bi)(a−bi) = a² − (bi)² = a²+b² = |z|² (un real ≥ 0). ▸ Por eso multiplicar por el conjugado "realiza" el denominador en las divisiones. ▸ Por qué las otras están mal: 2·Re(z)=z+z̄ (suma, no producto); "0" solo si z=0; z² es (a+bi)², distinto.'},
  {st: '(−1 + √3·i)³ es igual a:', opts: ['8', '−8', '8i', '2'], c: 0, ex: 'r=2, θ=2π/3. Por De Moivre: 2³·e^(i·3·2π/3) = 8·e^(i·2π) = 8·1 = 8. ▸ Da real y positivo: coherente, porque −1+√3 i es una de las raíces cúbicas de 8. ▸ Por qué las otras están mal: "−8" usaría argumento final π; "8i" un argumento π/2; "2" confunde el módulo r=2 con el resultado r³=8.'}
]);

registerExercises('algebra-segundo-parcial', '5', [
  {st: 'El resto de dividir P(x) = x³ − 2x + 5 entre (x − 1) es:', opts: ['0', '4', '5', '−2'], c: 1, ex: 'Por el teorema del resto, el resto de dividir por (x−a) es P(a). Acá P(1) = 1 − 2 + 5 = 4. ▸ Como P(1) = 4 ≠ 0, además 1 NO es raíz. ▸ Por qué las otras están mal: "0" diría que 1 es raíz (falso); "5" es P(0); "−2" es solo un término intermedio.'},
  {st: 'El polinomio P(x) = (x − 2)²·(x + 1)·(x² + 1) tiene grado:', opts: ['3', '4', '5', '6'], c: 2, ex: 'El grado es la suma de los grados de los factores: 2 + 1 + 2 = 5 (equivale a sumar multiplicidades: raíz 2 doble, raíz −1 simple, y i, −i simples). ▸ Por qué las otras están mal: "3" o "4" olvidan algún factor; "6" cuenta de más (quizá toma (x−2)² como grado 4).'},
  {st: 'Si P ∈ ℝ[x] tiene a 1 + i como raíz, otra raíz segura es:', opts: ['1 − i', '−1 + i', '−1 − i', 'i'], c: 0, ex: 'En ℝ[x] las complejas vienen de a pares conjugados: la conjugada de 1+i es 1−i (cambia solo el signo de la parte imaginaria). ▸ El factor real es (x−(1+i))(x−(1−i)) = x²−2x+2. ▸ Por qué las otras están mal: cambian también el signo de la parte real (−1±i) o introducen i sola, que no es la conjugada de 1+i.'},
  {st: 'Buscás P ∈ ℚ[x] de grado mínimo con √5 como raíz e i como raíz doble. El grado mínimo es:', opts: ['4', '5', '6', '8'], c: 2, ex: 'Raíces obligatorias: √5 en ℚ[x] fuerza −√5 (factor x²−5, grado 2); i doble fuerza −i doble (factor (x²+1)², grado 4). Total mínimo: 2+4 = 6. ▸ Por qué las otras están mal: "4" olvida una de las conjugaciones; "5" no respeta que todo viene de a pares; "8" cuenta multiplicidades de más.'},
  {st: 'Ese polinomio es P(x) = k·(x² − 5)·(x² + 1)². Si P(−2) = −75, entonces k vale:', opts: ['3', '−3', '25', '75'], c: 0, ex: 'P(−2) = k·((−2)²−5)·((−2)²+1)² = k·(4−5)·(4+1)² = k·(−1)·25 = −25k. Igualando: −25k = −75 → k = 3. ▸ Por qué las otras están mal: "−3" erra el signo (−25·(−3)=75≠−75); "25" y "75" confunden k con factores intermedios del cálculo.'},
  {st: 'En ℝ[x], la factorización completa de x⁴ − 1 es:', opts: ['(x−1)(x+1)(x²+1)', '(x−1)(x+1)(x−i)(x+i)', '(x²−1)²', '(x−1)⁴'], c: 0, ex: 'x⁴−1 = (x²−1)(x²+1) = (x−1)(x+1)(x²+1). En ℝ[x] el factor x²+1 es irreducible (sin raíces reales), así que se deja así. ▸ Por qué las otras están mal: (x−1)(x+1)(x−i)(x+i) es la factorización en ℂ[x] (usa i, no permitido en ℝ[x]); (x²−1)² y (x−1)⁴ están directamente mal (no dan x⁴−1).'},
  {st: 'El número a es raíz del polinomio P si y solo si:', opts: ['P(a) = 0', 'P(0) = a', 'el grado de P es a', 'P(a) = 1'], c: 0, ex: 'Por definición, a es raíz ⟺ P(a)=0 ⟺ (x−a) divide a P. ▸ Por qué las otras están mal: P(0)=a es el término independiente evaluado, no una raíz; el grado es un número fijo, no "a"; P(a)=1 no tiene significado especial.'}
]);

registerExercises('algebra-segundo-parcial', '6', [
  {st: 'Para el sistema kx + y = 1, x + ky = 1, ¿qué tipo es cuando k = 1?', opts: ['SCD (única)', 'SCI (infinitas soluciones)', 'SI (sin solución)', 'no se puede clasificar'], c: 1, ex: 'Con k=1 las dos ecuaciones son x+y=1 y x+y=1: la misma recta repetida → infinitas soluciones → SCI. ▸ El determinante k²−1 se anula en k=1, y como los términos independientes coinciden, es compatible. ▸ Por qué las otras están mal: NO es SCD (det=0); NO es SI porque las ecuaciones son idénticas, no contradictorias (eso pasa en k=−1).'},
  {st: 'A es una matriz 3×3 con det(A) = 5. Entonces det(2A) vale:', opts: ['10', '40', '15', '80'], c: 1, ex: 'det(2A) = 2³·det(A) = 8·5 = 40. ▸ Por qué las otras están mal: "10" hace 2·5 (sin exponente); "15" hace 3·5; "80" usa 2⁴ en lugar de 2³ (la matriz es 3×3, no 4×4).'},
  {st: 'Una TL T: ℝ⁴ → ℝ³ es sobreyectiva, así que dim Im = 3. ¿Cuánto vale dim Nu?', opts: ['0', '1', '2', '3'], c: 1, ex: 'Teorema de las dimensiones: dim Nu + dim Im = dim dominio = 4. Entonces dim Nu = 4 − 3 = 1. ▸ Por qué las otras están mal: "0" haría inyectiva, imposible aquí (de ℝ⁴ a ℝ³ nunca es inyectiva, sobran dimensiones); "2" o "3" no cierran la cuenta con dim Im = 3.'},
  {st: 'El complejo 2·e^(iπ), pasado a forma binómica, es:', opts: ['2', '−2', '2i', '−2i'], c: 1, ex: '2·e^(iπ) = 2·(cos π + i·sen π) = 2·(−1 + 0i) = −2. ▸ Geométricamente, módulo 2 y argumento π = apuntar hacia la izquierda sobre el eje real. ▸ Por qué las otras están mal: "2" sería argumento 0; "2i" argumento π/2; "−2i" argumento 3π/2 (o −π/2).'},
  {st: 'P ∈ ℝ[x] de grado 3 tiene como raíces a 2 y a 1 + i. Un factor de P es:', opts: ['x² − 2x + 2', 'x² + 2x + 2', 'x² − 2x − 2', 'x² + 4'], c: 0, ex: 'Como 1+i es raíz, también lo es 1−i (conjugada). Su factor: (x−(1+i))(x−(1−i)) = x² − (1+i+1−i)x + (1+i)(1−i) = x² − 2x + (1−i²) = x² − 2x + 2. ▸ Por qué las otras están mal: "+2x" erra el signo de la suma de raíces; "−2" erra el producto (debería ser +2); "x²+4" correspondería a raíces ±2i, no a 1±i.'},
  {st: '¿Cuál de estas igualdades sobre determinantes es FALSA?', opts: ['det(A·B) = det(A)·det(B)', 'det(Aᵀ) = det(A)', 'det(2A) = 2·det(A) para A de 3×3', 'det(A⁻¹) = 1/det(A)'], c: 2, ex: 'La falsa es det(2A) = 2·det(A): lo correcto es det(2A) = 2³·det(A) = 8·det(A) para una 3×3. ▸ Por qué las otras son verdaderas: el determinante del producto es el producto de determinantes; la traspuesta tiene el mismo determinante; el de la inversa es el inverso. Este error (olvidar el exponente n) es el más caro del bloque.'}
]);
