// Quizzes por unidad — Algoritmos y Estructuras de Datos (AyED) · UTN FRBA · DISI · C++

registerExercises('ayed', '1', [
  {st: '¿Cuál de estas NO es una propiedad de un algoritmo?', opts: ['Finito (termina en algún momento)', 'Ordenado (los pasos tienen un orden definido)', 'Preciso (cada paso no deja lugar a dudas)', 'Infinito (puede no terminar nunca)'], c: 3, ex: 'Un algoritmo debe ser FINITO: terminar después de una cantidad limitada de pasos. "Infinito" es lo contrario de una propiedad deseada. Las otras tres (finito, ordenado, preciso) sí son propiedades que todo buen algoritmo cumple.'},
  {st: 'Cuando ejecutás un programa en C++, ¿por dónde empieza?', opts: ['Por la primera línea del archivo (el <code>#include</code>)', 'Por la función <code>main</code>', 'Por la última línea', 'Por donde el usuario haga clic'], c: 1, ex: 'Todo programa en C++ arranca en <code>int main()</code>: la computadora busca esa función y ejecuta las líneas entre sus llaves, de arriba hacia abajo. El <code>#include</code> es una directiva previa, no el punto de arranque de la ejecución.'},
  {st: '¿Para qué sirve la línea <code>#include &lt;iostream&gt;</code>?', opts: ['Para terminar el programa', 'Para habilitar la entrada/salida: poder usar <code>cout</code> y <code>cin</code>', 'Para crear una variable', 'Para dejar un comentario'], c: 1, ex: '<code>iostream</code> (input/output stream) trae las herramientas de entrada y salida. Sin ese include, el compilador no sabría qué son <code>cout</code> (mostrar en pantalla) ni <code>cin</code> (leer del teclado).'},
  {st: '¿Qué muestra en pantalla <code>cout &lt;&lt; "Edad: " &lt;&lt; 5 &lt;&lt; endl;</code>?', opts: ['<code>Edad: 5</code> y un salto de línea', '<code>Edad: </code> solamente', '<code>Edad: " &lt;&lt; 5</code>', '<code>5</code> y nada más'], c: 0, ex: 'El operador <code>&lt;&lt;</code> empuja cada cosa a la pantalla en orden: primero el texto <code>Edad: </code> (sin las comillas, que solo delimitan el texto), después el número <code>5</code>, y por último <code>endl</code> baja un renglón. Resultado: <code>Edad: 5</code>.'},
  {st: 'Que C++ sea un lenguaje COMPILADO significa que…', opts: ['El código se ejecuta línea por línea cada vez que corre, sin traducir', 'El código fuente se traduce entero a un ejecutable (con el compilador) ANTES de poder correrlo', 'No necesita ningún programa para ejecutarse', 'Solo funciona en internet'], c: 1, ex: 'En un lenguaje compilado, el compilador lee todo tu <code>.cpp</code>, revisa que esté bien escrito y genera un ejecutable. Esa traducción se hace una vez; después corrés el ejecutable las veces que quieras. (Traducir línea por línea en cada ejecución es lo propio de los lenguajes interpretados, como Python.)'},
]);

registerExercises('ayed', '2', [
  {st: 'Tenés esta línea: <code>unsigned short int x;</code>. ¿Cuál es el mayor valor que podés guardar en x?', opts: ['32767', '65535', '255', 'No hay límite, entra cualquier número'], c: 1, ex: 'Un short int ocupa 2 bytes. Con signo (signed) llega hasta 32767, pero al ser unsigned no gasta rango en negativos y duplica el máximo positivo: llega hasta 65535. Es justo el caso del código de la cátedra.'},
  {st: 'Escribís <code>int x;</code> y en la línea siguiente <code>cout &lt;&lt; x;</code> sin asignarle nada antes. ¿Qué muestra?', opts: ['Siempre 0', 'Un valor basura, impredecible y distinto en cada ejecución', 'Da error de compilación', 'Una cadena vacía'], c: 1, ex: 'Definir una variable solo crea la cajita: NO la pone en 0. Hasta que vos no le asignás un valor, contiene basura (lo que haya quedado en esa memoria). Por eso conviene inicializar al definir: <code>int x = 0;</code>.'},
  {st: '¿Cuál de estas definiciones es CORRECTA para guardar la letra A en una variable de tipo char?', opts: ['<code>char c = "A";</code>', '<code>char c = A;</code>', '<code>char c = \'A\';</code>', '<code>string c = "A";</code> (eso no es char)'], c: 2, ex: 'Un char guarda UN solo carácter y va con comilla SIMPLE, como en <code>char c = \'A\';</code>. Las comillas dobles arman un string (texto), por eso <code>char c = "A";</code> da error de tipos. Y <code>A</code> sin comillas se interpretaría como el nombre de una variable inexistente.'},
  {st: 'En la línea <code>x = 10;</code>, ¿qué hace el signo <code>=</code>?', opts: ['Compara si x es igual a 10 y devuelve verdadero o falso', 'Asigna: guarda el valor 10 dentro de la variable x', 'Define una variable nueva llamada x', 'Suma 10 a x'], c: 1, ex: 'En C++ el <code>=</code> es el operador de ASIGNACIÓN, no de igualdad: toma el valor de la derecha (10) y lo guarda en la variable de la izquierda (x). Comparar igualdad es otro operador, <code>==</code>.'},
  {st: '¿Cuál es la forma correcta de leer un número entero escrito por el usuario y guardarlo en la variable <code>x</code>?', opts: ['<code>cout &lt;&lt; x;</code>', '<code>cin &lt;&lt; x;</code>', '<code>cin &gt;&gt; x;</code>', '<code>x &gt;&gt; cin;</code>'], c: 2, ex: 'Para leer del teclado se usa <code>cin</code> con el operador <code>&gt;&gt;</code>, cuya flecha apunta DESDE el teclado HACIA la variable: <code>cin &gt;&gt; x;</code>. <code>cout &lt;&lt; x;</code> sería mostrar x en pantalla, y <code>cin</code> usa <code>&gt;&gt;</code>, no <code>&lt;&lt;</code>.'},
]);

registerExercises('ayed', '3', [
  {st: '¿Cuánto vale la expresión <code>7 / 2</code> en C++ (ambos enteros)?', opts: ['3.5', '3', '4', '0'], c: 1, ex: 'Como los dos operandos son enteros, la división es ENTERA: el resultado real 3,5 se trunca descartando el decimal, queda 3 (no redondea).'},
  {st: '¿Cuál es el resultado de <code>17 % 5</code>?', opts: ['3', '2', '3.4', '12'], c: 1, ex: 'El operador <code>%</code> devuelve el RESTO de la división entera: 17 = 5·3 + 2, así que sobra 2.'},
  {st: 'Con <code>x</code> valiendo 2, ¿cuánto vale <code>x + 3 * 4</code>?', opts: ['20', '14', '24', '11'], c: 1, ex: 'La multiplicación tiene más prioridad que la suma: primero 3·4=12, después 2+12=14. (Con paréntesis, <code>(x + 3) * 4</code> daría 20.)'},
  {st: 'Si <code>p</code> es false y <code>q</code> es true, ¿cuánto valen <code>p &amp;&amp; q</code> y <code>p || q</code> respectivamente?', opts: ['true y true', 'false y false', 'false y true', 'true y false'], c: 2, ex: 'El AND (<code>&amp;&amp;</code>) es true solo si ambos son true: false &amp;&amp; true = false. El OR (<code>||</code>) es true si al menos uno es true: false || true = true.'},
  {st: 'Con <code>i = 10</code> y <code>j = 20</code>, tras ejecutar <code>int k = (++i + j++);</code> ¿cuánto valen i, j y k?', opts: ['i=10, j=20, k=30', 'i=11, j=21, k=31', 'i=11, j=21, k=32', 'i=10, j=21, k=30'], c: 1, ex: '<code>++i</code> es pre-incremento: sube i a 11 y aporta 11. <code>j++</code> es post-incremento: aporta 20 y luego sube j a 21. La suma 11+20=31 se guarda en k. Final: i=11, j=21, k=31.'},
]);

registerExercises('ayed', '4', [
  {st: 'Dado este código:<br><code>int n = 3;</code><br><code>if (n &gt; 5) {</code><br><code>&nbsp;&nbsp;cout &lt;&lt; "A";</code><br><code>} else {</code><br><code>&nbsp;&nbsp;cout &lt;&lt; "B";</code><br><code>}</code><br>¿Qué imprime?', opts: ['A', 'B', 'A y B', 'No imprime nada'], c: 1, ex: 'La condición 3 &gt; 5 es false, así que se saltea el bloque del if y se ejecuta el del else: imprime B. En un if/else siempre corre exactamente uno de los dos caminos.'},
  {st: '¿Cuál de estas líneas es equivalente al if/else <code>if (a &gt; b) { m = a; } else { m = b; }</code>?', opts: ['<code>int m = (a &gt; b) ? a : b;</code>', '<code>int m = if (a &gt; b) a : b;</code>', '<code>int m = (a &gt; b) : a ? b;</code>', '<code>int m = a &gt; b ? b : a;</code>'], c: 0, ex: 'El operador ternario es <code>COND ? valorSiTrue : valorSiFalse</code>. Como el if asigna a cuando a&gt;b, el ternario es <code>(a &gt; b) ? a : b</code>. La opción con a y b al revés daría el menor, no el mayor.'},
  {st: 'En un switch, si un case ejecuta sus sentencias pero le falta el <code>break</code>, ¿qué ocurre?', opts: ['Da error de compilación', 'Sale del switch igual que con break', 'Sigue ejecutando los case de abajo hasta encontrar un break (fallthrough)', 'Vuelve a evaluar el switch desde el principio'], c: 2, ex: 'Sin break, el switch "cae" (fallthrough) hacia los case siguientes y los ejecuta aunque no coincidan, hasta toparse con un break o llegar al final. Por eso se pone break al final de cada case.'},
  {st: 'Tenés <code>bool listo = true;</code> y querés mostrar "Esperá" SOLO cuando NO está listo. ¿Cuál es la forma correcta y prolija?', opts: ['<code>if (listo == false)</code> es lo único válido', '<code>if (!listo) { cout &lt;&lt; "Esperá"; }</code>', '<code>if (listo) {} else { cout &lt;&lt; "Esperá"; }</code>', '<code>if (listo = false) { cout &lt;&lt; "Esperá"; }</code>'], c: 1, ex: 'Se niega la condición con <code>!</code> (NO lógico): <code>if (!listo)</code> ejecuta el cuerpo cuando listo es false. No conviene dejar el if verdadero vacío con todo en el else, ni usar <code>=</code> (asignación) en la condición.'},
  {st: '¿Qué problema tiene la condición <code>if (x = 5)</code>?', opts: ['Ninguno, compara correctamente si x vale 5', 'Usa <code>=</code> (asignación) en vez de <code>==</code> (comparación): le asigna 5 a x y la condición da siempre true', 'Faltan las llaves obligatorias', 'El 5 debería ir entre comillas'], c: 1, ex: 'Un solo <code>=</code> asigna: mete 5 en x y usa ese 5 como condición (distinto de cero = true), así que es siempre verdadera y además pisa el valor de x. Para comparar igualdad van dos signos: <code>if (x == 5)</code>.'},
]);

registerExercises('ayed', '5', [
  {st: '¿Cuántas veces se ejecuta el cuerpo de este ciclo?<br><code>for (int i = 1; i &lt;= 10; i = i + 1) { cout &lt;&lt; "hola"; }</code>', opts: ['9 veces', '10 veces', '11 veces', 'Infinitas veces'], c: 1, ex: 'El índice i toma los valores 1, 2, 3, …, 10. Como la condición es <code>i &lt;= 10</code> (menor o IGUAL), el 10 se incluye. Son 10 valores, por lo tanto 10 vueltas. (En la vuelta siguiente i vale 11, 11 &lt;= 10 da false y corta.)'},
  {st: 'Un ciclo do-while, ¿cuántas veces ejecuta su cuerpo como MÍNIMO?', opts: ['0 veces (puede no entrar nunca)', '1 vez (siempre al menos una)', 'Depende de la condición inicial', 'Las mismas que un while equivalente'], c: 1, ex: 'El do-while evalúa la condición al FINAL, después de ejecutar el cuerpo. Por eso el cuerpo corre sí o sí al menos 1 vez. El while, en cambio, evalúa al principio y puede dar 0 vueltas.'},
  {st: '¿En qué momento se evalúa la condición en un while?', opts: ['Al final, después del cuerpo', 'Al principio, antes de ejecutar el cuerpo', 'En el medio del cuerpo', 'Solo una vez, al entrar'], c: 1, ex: 'El while chequea la condición AL PRINCIPIO de cada vuelta. Si arranca en false, el cuerpo no se ejecuta ni una vez (0 vueltas). Se re-evalúa antes de cada iteración. (El do-while es el que evalúa al final.)'},
  {st: 'Para leer números hasta un centinela 999 sin procesarlo, con <code>while (x != 999)</code>, ¿dónde van las lecturas (lectura adelantada)?', opts: ['Una sola lectura adentro del cuerpo', 'Una lectura antes del while y otra al final del cuerpo', 'Solo una lectura antes del while', 'Una lectura después del while'], c: 1, ex: 'Como la condición depende del dato, se necesita lectura adelantada: un <code>cin &gt;&gt; x</code> ANTES del while (para que la condición tenga un primer valor) y otro al FINAL del cuerpo (para traer el siguiente). Así, al ingresar 999, el while ve 999 != 999 = false y sale sin procesarlo.'},
  {st: '¿Cuál es la causa más común de que este ciclo sea INFINITO?<br><code>int i = 1; while (i &lt;= 10) { cout &lt;&lt; "hola"; }</code>', opts: ['La condición usa &lt;= en vez de &lt;', 'Falta incrementar i dentro del cuerpo (i nunca cambia)', 'i arranca en 1 en lugar de 0', 'El cout está mal escrito'], c: 1, ex: 'Dentro del cuerpo nunca se modifica i, así que i vale 1 para siempre y la condición 1 &lt;= 10 da true eternamente. Falta un <code>i = i + 1;</code> en el cuerpo. Regla: en cada vuelta algo debe acercar la condición a hacerse falsa.'},
]);

registerExercises('ayed', '6', [
  {st: 'Vas a buscar el MÁXIMO de un conjunto de enteros que puede contener negativos, positivos y ceros (dominio desconocido). ¿Con qué valor conviene inicializar la variable <code>max</code>?', opts: ['Con 0, que es un valor neutro', 'Con el primer elemento leído (usando una bandera o un contador de posición)', 'Con 100, un número grande', 'Da igual, C++ la inicializa sola'], c: 1, ex: 'Si el dominio NO está acotado, no existe un "más chico que todos" para usar como valor inicial. Lo seguro es tomar el PRIMER dato como máximo provisorio: con bandera (<code>esLaPrimeraVez || valor &gt; max</code>) o con contador de posición (<code>i == 1 || valor &gt; max</code>). Inicializar en 0 falla si todos son negativos; en 100 falla si todos son menores; y una variable sin inicializar arranca con basura.'},
  {st: 'Un programa hace <code>int max = 0;</code> y luego, por cada dato, <code>if (valor &gt; max) max = valor;</code> sobre el conjunto −5, −2, −9, −1. ¿Qué queda en <code>max</code>?', opts: ['−1 (el máximo real)', '−9', '0, un valor que ni siquiera estaba en el conjunto', 'Da error de compilación'], c: 2, ex: 'Todos los datos son negativos, así que ninguno supera al 0 inicial: el <code>if</code> nunca entra y <code>max</code> queda en 0, un valor que no pertenece al conjunto. Es el bug clásico de inicializar el máximo en 0. El máximo real es −1, pero solo lo obtendrías tomando el primer elemento (bandera o contador de posición).'},
  {st: 'Se descompone el monto $387 en billetes de 100, 50, 20, 10, 5, 2 y 1 (mínima cantidad, de mayor a menor). ¿Cuántos billetes de $20 se usan?', opts: ['1', '4', '0', '3'], c: 0, ex: 'Se va dividiendo y guardando el resto: 387/100 = 3 (resto 87); 87/50 = 1 (resto 37); 37/20 = 1 (resto 17); 17/10 = 1 (resto 7); 7/5 = 1 (resto 2); 2/2 = 1 (resto 0). Entonces se usa 1 billete de $20. El distractor "4" es el error de dividir 87/20 sin haber actualizado el resto.'},
  {st: 'Se quiere el promedio de un conjunto cuya suma es 7 y cuya cantidad es 2 (ambas <code>int</code>). El programa escribe <code>int prom = suma / cant;</code>. ¿Qué valor queda en <code>prom</code>?', opts: ['3.5', '3', '4', '3.50'], c: 1, ex: 'Al dividir dos enteros, C++ trunca la parte decimal: 7 / 2 = 3 (no redondea a 4 ni guarda el .5). Para obtener 3.5 hay que usar variables reales y castear ANTES de dividir: <code>float prom = (float) suma / cant;</code>.'},
  {st: 'Para CONTAR cuántos valores negativos hay en un conjunto, ¿cuál es la línea correcta dentro del ciclo?', opts: ['<code>suma = suma + valor;</code>', '<code>if (valor &lt; 0) { cantidad++; }</code>', '<code>if (valor &lt; 0) { suma = suma + valor; }</code>', '<code>cantidad = cantidad + valor;</code>'], c: 1, ex: 'CONTAR responde "cuántos son": por cada negativo se suma 1 al contador, <code>cantidad++</code>. Acumular el valor (<code>suma + valor</code>) es el patrón SUMAR, no contar; y sumarle el valor al contador mezcla las dos cosas. La clave: contar = +1 siempre; sumar = +valor.'},
]);

registerExercises('ayed', '7', [
  {st: '¿Cuál es la diferencia central entre un procedimiento (<code>void</code>) y una función?', opts: ['El procedimiento es más rápido que la función', 'La función devuelve un valor con <code>return</code>; el procedimiento (<code>void</code>) no devuelve nada', 'El procedimiento puede recibir parámetros y la función no', 'No hay ninguna diferencia, son sinónimos'], c: 1, ex: 'Un <b>procedimiento</b> se declara con <code>void</code> y NO devuelve ningún valor: se lo llama suelto, como <code>raya();</code>. Una <b>función</b> declara un tipo de retorno (<code>int</code>, <code>bool</code>, <code>float</code>…) y entrega un valor con <code>return</code>, que hay que usar: <code>int w = obtenerNumero();</code>. Ambos pueden recibir parámetros, así que esa no es la diferencia.'},
  {st: 'Dado <code>void duplicarMal(int n){ n = n*2; }</code>, ¿qué imprime <code>int x=5; duplicarMal(x); cout &lt;&lt; x;</code>?', opts: ['10', '5', '0', 'Error de compilación'], c: 1, ex: 'El parámetro <code>int n</code> se pasa <b>por valor</b>: la función recibe una COPIA de <code>x</code>. El <code>n = n*2</code> modifica solo esa copia (la pone en 10), pero el original <code>x</code> queda intacto en <b>5</b>. "10" sería el resultado si el parámetro fuera por referencia (<code>int&amp; n</code>).'},
  {st: 'Dado <code>void duplicar(int&amp; n){ n = n*2; }</code>, ¿qué imprime <code>int x=5; duplicar(x); cout &lt;&lt; x;</code>?', opts: ['5', '10', '25', 'No compila'], c: 1, ex: 'El parámetro <code>int&amp; n</code> (con <code>&amp;</code>) se pasa <b>por referencia</b>: <code>n</code> es otro nombre para el MISMO casillero que <code>x</code>, no una copia. Entonces <code>n = n*2</code> escribe 10 en la variable original, y al volver <code>x</code> vale <b>10</b>. "5" sería sin el <code>&amp;</code> (por valor).'},
  {st: 'Ya existe <code>void mostrarPersona(string nombre, string apellido)</code>. ¿Cuál de estas SÍ es una sobrecarga válida (firma distinta)?', opts: ['<code>void mostrarPersona(string apellido, string nombre)</code>', '<code>int mostrarPersona(string nombre, string apellido)</code>', '<code>void mostrarPersona(string nombre, int dni)</code>', 'Ninguna: no se puede repetir el nombre'], c: 2, ex: 'La <b>firma</b> = NOMBRE + TIPOS de los parámetros (en orden). La existente es <code>mostrarPersona(string, string)</code>. La correcta, <code>mostrarPersona(string, int)</code>, cambia el segundo tipo → firma distinta → sobrecarga válida. Cambiar solo el NOMBRE de los parámetros, o solo el tipo de RETORNO, no cambia la firma.'},
  {st: 'En el ejemplo de scope: afuera <code>int z = 10;</code>, y dentro de un <code>if</code> se declara <code>int z = 20;</code>. Justo DESPUÉS de cerrar el <code>if</code>, ¿cuánto vale <code>z</code>?', opts: ['20', '10', '30', 'z ya no existe'], c: 1, ex: 'El <code>z = 20</code> es una variable <b>local del bloque del if</b> que OCULTA al <code>z</code> externo solo mientras dura ese bloque. Al cerrar el <code>if</code> con <code>}</code>, ese z interno muere y vuelve a verse el z externo, que nunca se tocó: vale <b>10</b>.'},
  {st: 'Para <code>int factorial(int nro){ if(nro!=0) res = nro*factorial(nro-1); else res = 1; … }</code>, ¿cuánto da <code>factorial(3)</code> y cuál es el caso base?', opts: ['Da 9; el caso base es <code>nro==1</code>', 'Da 6; el caso base es <code>nro==0</code> (devuelve 1)', 'Da 6; no tiene caso base', 'Da infinito: se cuelga siempre'], c: 1, ex: '<code>factorial(3)</code> = 3·factorial(2) = 3·2·factorial(1) = 3·2·1·factorial(0). El <b>caso base</b> es <code>nro==0</code> (rama else: <code>res=1</code>), que corta la recursión sin volver a llamarse. Subiendo: 1·1·2·3 = <b>6</b>.'},
]);

registerExercises('ayed', '8', [
  {st: 'En la declaración <code>int arr[5];</code>, ¿cuál es el índice válido MÁXIMO al que podés acceder?', opts: ['5', '4', '6', '0'], c: 1, ex: 'Los índices arrancan en <b>0</b> y llegan hasta <b>CANTIDAD_MAX − 1</b>. En <code>int arr[5]</code> hay 5 lugares numerados 0, 1, 2, 3, 4, así que el índice máximo es <b>4</b>. Acceder a <code>arr[5]</code> es salirse de rango, un error grave de memoria.'},
  {st: '¿Qué imprime este recorrido?<br><code>int arr[4] = {10, 25, 3, 8};</code><br><code>for (int i = 0; i &lt; 4; i++) cout &lt;&lt; arr[i] &lt;&lt; " ";</code>', opts: ['10 25 3 8', '10 25 3', '25 3 8', '0 1 2 3'], c: 0, ex: 'El <code>for</code> recorre i = 0, 1, 2, 3 (mientras <code>i &lt; 4</code>) e imprime <code>arr[i]</code> en cada vuelta: arr[0]=10, arr[1]=25, arr[2]=3, arr[3]=8. La opción "0 1 2 3" sería imprimir los índices i, no los valores arr[i].'},
  {st: 'Declarás <code>int v[100];</code> pero solo cargás datos en las primeras 30 posiciones y llevás <code>N = 30</code>. Para procesar SOLO los datos válidos, ¿hasta dónde recorrés?', opts: ['De 0 a 99 (el tamaño físico)', 'De 0 a 29 (de 0 a N − 1)', 'De 0 a 100', 'De 1 a 30'], c: 1, ex: 'Hay que distinguir el <b>tamaño físico</b> (100, lo reservado) de los <b>elementos útiles</b> (N = 30, lo realmente cargado). Se recorre de <b>0 a N − 1</b>, o sea de 0 a 29. De la 30 en adelante hay basura que arruinaría las cuentas.'},
  {st: 'Una función hace <code>void cargar(int a[]) { a[0] = 7; }</code> y desde main llamás <code>cargar(miArr);</code>. Al volver, <code>miArr[0]</code> vale 7. ¿Por qué el cambio PERSISTE afuera?', opts: ['Porque la función devolvió una copia con <code>return</code>', 'Porque los arreglos se pasan por referencia: viaja la dirección de memoria, así que la función modifica el MISMO arreglo', 'Porque los arreglos son variables globales', 'Porque <code>a[0] = 7</code> vuelve a declarar miArr'], c: 1, ex: 'Los arreglos se pasan SIEMPRE por referencia: no se copia el arreglo entero, se pasa la dirección donde empieza. Por eso dentro de la función <code>a</code> es el mismo arreglo que <code>miArr</code>, y lo que escribe queda. La función es <code>void</code>: no devuelve nada.'},
  {st: 'Se dice que acceder a <code>arr[i]</code> es de "acceso directo en tiempo constante", O(1). ¿Por qué cuesta lo mismo llegar a <code>arr[0]</code> que a <code>arr[9999]</code>?', opts: ['Porque la máquina recorre el arreglo desde el principio, pero es muy rápida', 'Porque la máquina calcula la dirección con una sola cuenta: inicio + i × (tamaño del tipo), sin recorrer nada', 'Porque todos los arreglos tienen como máximo una posición', 'Porque el compilador ordena el arreglo antes de acceder'], c: 1, ex: 'El arreglo vive en un bloque contiguo de memoria y el nombre guarda la dirección de comienzo. Para ubicar <code>arr[i]</code> la máquina hace una única cuenta: <code>inicio + i × tamañoDelTipo</code>. Una multiplicación y una suma, sin importar la posición → tiempo constante, O(1).'},
]);

registerExercises('ayed', '9', [
  {st: '¿Cuál es la forma correcta de definir un registro en C++?', opts: ['<code>struct Punto { int x; int y; }</code>', '<code>struct Punto { int x; int y; };</code>', '<code>struct Punto ( int x; int y; );</code>', '<code>Punto struct { int x; int y; };</code>'], c: 1, ex: 'La definición de un <code>struct</code> es una declaración y termina con <code>;</code> después de la <code>}</code> de cierre. Olvidar ese punto y coma es el error de compilación más típico con structs.'},
  {st: 'Tenés <code>Punto p1;</code>. ¿Cómo guardás un 3 en su campo <code>x</code>?', opts: ['<code>p1-&gt;x = 3;</code>', '<code>x.p1 = 3;</code>', '<code>p1.x = 3;</code>', '<code>p1[x] = 3;</code>'], c: 2, ex: 'A los campos de un struct se accede con el operador punto: <code>variable.campo</code>. Se lee "el x de p1", y <code>p1.x</code> se usa como cualquier variable int.'},
  {st: 'Con <code>struct Recta { string nombre; Punto p1; Punto p2; };</code> y una variable <code>Recta r;</code>, ¿cómo llegás a la coordenada x del primer punto?', opts: ['<code>r.x</code>', '<code>r.p1.x</code>', '<code>r.x.p1</code>', '<code>p1.r.x</code>'], c: 1, ex: 'En structs anidados se encadena el punto de izquierda a derecha: <code>r</code> es la recta, <code>.p1</code> su primer punto, <code>.x</code> la coordenada x de ese punto.'},
  {st: 'Hacés <code>r.p1.x = 9;</code>, después <code>Recta r3 = r;</code> y luego <code>r3.p1.x = 2;</code>. ¿Cuánto vale <code>r.p1.x</code>?', opts: ['2', '9', 'Queda sin valor', 'Da error de compilación'], c: 1, ex: 'Asignar un struct copia TODOS sus campos (semántica de valor): <code>r3</code> es una copia independiente de <code>r</code>. Modificar <code>r3</code> no afecta a <code>r</code>, así que <code>r.p1.x</code> sigue valiendo 9.'},
  {st: 'Con <code>void incX(Punto&amp; p) { p.x = p.x + 1; }</code> y <code>punto1.x</code> en 3, ¿qué vale <code>punto1.x</code> después de <code>incX(punto1);</code>?', opts: ['3, porque se modifica una copia', '4, porque se recibe por referencia', '0', 'Da error porque no se puede pasar un struct'], c: 1, ex: 'El <code>&amp;</code> hace que <code>p</code> sea el MISMO dato que <code>punto1</code> (paso por referencia), no una copia. Por eso <code>p.x = p.x + 1</code> modifica el original: pasa de 3 a 4.'},
]);

registerExercises('ayed', '10', [
  {st: '¿Cuántos casilleros reserva en memoria la declaración <code>int m[3][4];</code>?', opts: ['7', '12', '34', '81'], c: 1, ex: 'Una matriz de FILAS×COLUMNAS tiene ese producto de casilleros: 3 filas × 4 columnas = <b>12</b> celdas de tipo int.'},
  {st: 'En <code>int m[3][4]</code>, ¿qué celda referencia <code>m[1][2]</code>?', opts: ['Fila 2, columna 1', 'Fila 1, columna 2', 'La celda número 12', 'Fila 2, columna 3'], c: 1, ex: 'El orden es siempre <code>m[fila][columna]</code> y ambos arrancan en 0: <code>m[1][2]</code> es la <b>fila 1, columna 2</b>. No confundir con <code>m[2][1]</code>.'},
  {st: '¿Cuál es la forma correcta de recorrer TODA una matriz?', opts: ['Un solo <code>for</code> de 0 a FILAS', 'Un doble <code>for</code> anidado: uno para filas y otro para columnas', 'Un <code>for</code> de 0 a FILAS*COLUMNAS sin corchetes', 'Un <code>while</code> sin índices'], c: 1, ex: 'Como hay dos índices (fila y columna), se usan dos <code>for</code> anidados: el externo mueve la fila <code>i</code> y el interno las columnas <code>j</code>, accediendo a <code>m[i][j]</code>.'},
  {st: 'Al pasar una matriz a una función, ¿por qué hay que indicar el número de columnas, como en <code>void mostrar(int m[][3], int filas)</code>?', opts: ['Por una regla de estilo, se puede omitir', 'Porque el compilador necesita el ancho de cada fila para calcular la posición de cada celda en memoria', 'Porque las filas no se pueden pasar nunca', 'Para que la matriz se copie más rápido'], c: 1, ex: 'La matriz se guarda como una tira fila tras fila; para ubicar <code>m[i][j]</code> el compilador necesita saber cuántas columnas tiene cada fila. Por eso las columnas son obligatorias y las filas se pasan aparte.'},
  {st: 'Con un doble <code>for</code> (externo = filas, interno = columnas) sobre una matriz 2×3, ¿en qué orden se visitan las celdas?', opts: ['m[0][0], m[1][0], m[0][1]…', 'Toda la fila 0 (m[0][0], m[0][1], m[0][2]) y después toda la fila 1', 'Toda la columna 0 primero, después la columna 1', 'm[2][3], m[2][2], m[2][1]… en reversa'], c: 1, ex: 'El <code>for</code> externo fija la fila y no avanza hasta que el interno recorre todas sus columnas: se completa la fila 0 entera, luego la fila 1 entera (izquierda a derecha, arriba hacia abajo).'},
]);
