registerExercises('analisis-segundo-parcial', '1', [
  {st: 'Según los parciales reales, ¿cuántos ejercicios suele tener el 2° parcial de la cátedra Cabana?', opts: ['4', '6', '8', '10'], c: 1, ex: 'Los parciales (TEMA 1–4 de 2022 y 2024) tienen 6 ejercicios sobre los mismos temas (integrales, áreas, TFC, Taylor, series), por 10 puntos. ▸ Por qué las otras están mal: 8 es el formato de Álgebra; 4 y 10 no corresponden al de Análisis.'},
  {st: 'Si en el enunciado ves "radio de convergencia" o una sumatoria Σ, el tema es:', opts: ['Integrales', 'Polinomio de Taylor', 'Series', 'Áreas'], c: 2, ex: 'Radio de convergencia y Σ son exclusivos de SERIES (la última unidad). ▸ Por qué las otras están mal: integrales usan ∫; Taylor usa P(x) y derivadas en un punto; áreas usan ∫ con límites y "región encerrada".'},
  {st: 'Para una "integral con un dato" (te dan f(5) y ∫t·f(t)dt, y piden ∫f′(…)dx), la estrategia es:', opts: ['Cambio de variable y luego integración por partes', 'Fracciones simples', 'Derivar y evaluar', 'Calcular el radio de convergencia'], c: 0, ex: 'Primero un cambio de variable para "limpiar" el argumento, y después por partes para que aparezcan los datos f(a) y ∫t·f(t)dt. ▸ Por qué las otras están mal: fracciones simples es para cocientes de polinomios; no se deriva (es una integral); el radio es de series.'},
  {st: 'Una serie geométrica '+M('Σ<sub>n=0</sub><sup>∞</sup> a·rⁿ')+' converge (a '+M('a/(1−r)')+') si y solo si:', opts: [M('r > 0'), M('|r| < 1'), M('r < 1'), 'Siempre converge'], c: 1, ex: 'La geométrica converge ⟺ |r| < 1 (la razón, en valor absoluto, menor que 1). ▸ Por qué las otras están mal: r>0 no alcanza (puede ser ≥1); r<1 admite r muy negativo (diverge si r ≤ −1); "siempre" es falso.'},
  {st: 'Por el Teorema Fundamental del Cálculo, '+M('d/dx ∫<sub>0</sub><sup>x</sup> f(t) dt')+' es igual a:', opts: [M('f(x)'), M('F(x) − F(0)'), M('f′(x)'), M('f(t)')], c: 0, ex: 'Derivar una integral con límite superior x devuelve el integrando evaluado en x: f(x). ▸ Por qué las otras están mal: F(x)−F(0) es la integral (sin derivar); f′(x) deriva de más; f(t) deja la variable muda (hay que poner x).'},
  {st: 'En el polinomio de Taylor de f centrado en c, el coeficiente del término '+M('(x−c)<sup>k</sup>')+' es:', opts: [M('f⁽ᵏ⁾(c)'), M('f⁽ᵏ⁾(c)/k!'), M('k!·f⁽ᵏ⁾(c)'), M('f(c)/k')], c: 1, ex: 'El coeficiente es la derivada k-ésima en c dividida por k!. ▸ De ahí el atajo: f⁽ᵏ⁾(c) = k!·(coeficiente). ▸ Por qué las otras están mal: (A) olvida el factorial; (C) multiplica en lugar de dividir; (D) no usa la derivada k-ésima.'}
]);

registerExercises('analisis-segundo-parcial', '2', [
  {st: 'La integral '+M('∫ sec(2x)·tan(2x) dx')+' es igual a:', opts: [M('½·sec(2x) + C'), M('½·tan(2x) + C'), M('½·cot(2x) + C'), M('2·sec(2x) + C')], c: 0, ex: 'Como d/dx sec(2x) = 2·sec(2x)tan(2x), al integrar sec(2x)tan(2x) queda ½·sec(2x) + C. ▸ Por qué las otras están mal: tan, cot vienen de otras primitivas; "2·sec" olvida dividir por la derivada interna (2).'},
  {st: '¿Qué método conviene para '+M('∫ x·cos(x) dx')+'?', opts: ['Sustitución', 'Integración por partes', 'Fracciones simples', 'Está en la tabla directa'], c: 1, ex: 'Es un producto de un polinomio (x) por una trigonométrica (cos x): el caso típico de por partes (u = x). Da x·sen x + cos x + C. ▸ Por qué las otras están mal: no hay una sustitución útil; fracciones simples es para cocientes de polinomios; no está en la tabla.'},
  {st: 'En '+M('A = ∫<sub>0</sub><sup>125</sup> f′(x<sup>1/3</sup>) dx')+', con el cambio '+M('y = x<sup>1/3</sup>')+' la integral queda:', opts: [M('3·∫<sub>0</sub><sup>5</sup> f′(y)·y² dy'), M('∫<sub>0</sub><sup>5</sup> f′(y) dy'), M('∫<sub>0</sub><sup>125</sup> f′(y)·y² dy'), M('3·∫<sub>0</sub><sup>5</sup> f′(y)·y dy')], c: 0, ex: 'y = x^(1/3) → x = y³, dx = 3y² dy. Los límites cambian: x=0→y=0, x=125→y=5. Queda 3·∫₀⁵ f′(y)·y² dy. ▸ Por qué las otras están mal: (B) olvida el 3y² del dx; (C) no reescala los límites (deja 125); (D) usa y en vez de y².'},
  {st: 'Usando f(5)=2 y '+M('∫<sub>0</sub><sup>5</sup> t·f(t) dt = 15')+', el valor de '+M('A = ∫<sub>0</sub><sup>125</sup> f′(x<sup>1/3</sup>) dx')+' es:', opts: [M('60'), M('20'), M('45'), M('15')], c: 0, ex: 'Tras el cambio queda 3∫₀⁵y²f′(y)dy; por partes (u=y², v=f(y)): 3[y²f(y)|₀⁵ − ∫₀⁵2y·f(y)dy] = 3[25·f(5) − 2·15] = 3[50−30] = 60. ▸ Por qué las otras están mal: 20 olvida el factor 3; 45 y 15 son cuentas parciales mal hechas.'},
  {st: 'Al separar '+M('∫ (√(3x))/x³ dx')+', la parte de potencias '+M('√3·∫ x<sup>−5/2</sup> dx')+' da:', opts: [M('−(2√3/3)·x<sup>−3/2</sup> + C'), M('(2√3/3)·x<sup>−3/2</sup> + C'), M('√3·x<sup>−5/2</sup> + C'), M('−(2√3/3)·x<sup>−1/2</sup> + C')], c: 0, ex: '∫x^(−5/2)dx = x^(−3/2)/(−3/2) = −(2/3)x^(−3/2). Multiplicado por √3: −(2√3/3)x^(−3/2) + C. ▸ Por qué las otras están mal: (B) erra el signo (el exponente −3/2 viene de −5/2+1); (C) deriva en vez de integrar; (D) erra el exponente.'},
  {st: 'Por integración por partes, '+M('∫ ln(x) dx')+' es igual a:', opts: [M('x·ln(x) − x + C'), M('1/x + C'), M('x·ln(x) + C'), M('ln(x) − x + C')], c: 0, ex: 'Truco: u = ln x, dv = dx → v = x. ∫ln x dx = x·ln x − ∫x·(1/x)dx = x·ln x − x + C. ▸ Por qué las otras están mal: (B) es la derivada de ln x; (C) olvida el −x; (D) no aplica bien partes.'}
]);

registerExercises('analisis-segundo-parcial', '3', [
  {st: 'Hallar '+M('a > 0')+' para que el área entre el eje x, '+M('f(x) = a·√x')+' y la recta '+M('x = 1')+' sea 10.', opts: [M('a = 15'), M('a = 10'), M('a = 6'), M('a = 2/3')], c: 0, ex: '∫₀¹ a·√x dx = a·(2/3)·x^(3/2)|₀¹ = 2a/3. Igualo: 2a/3 = 10 → a = 15. ▸ Por qué las otras están mal: a=6 daría área 4; a=10 daría 20/3; 2/3 es el factor de la integral, no a.'},
  {st: 'Para '+M('h(x) = x·∫<sub>0</sub><sup>x</sup> e<sup>t²</sup> dt + 9')+', ¿cuánto vale '+M('h′(x)')+'?', opts: [M('∫<sub>0</sub><sup>x</sup> e<sup>t²</sup> dt + x·e<sup>x²</sup>'), M('x·e<sup>x²</sup>'), M('e<sup>x²</sup>'), M('2x·e<sup>x²</sup>')], c: 0, ex: 'Regla del producto: deriva x (da 1) por la integral, más x por la derivada de la integral (TFC: e^(x²)). h′(x) = ∫₀ˣe^(t²)dt + x·e^(x²). ▸ Por qué las otras están mal: olvidan el primer término (la derivada del factor x) o aplican mal el TFC.'},
  {st: 'Hallar '+M('a ∈ [0, π/4]')+' sabiendo que el área entre '+M('f(x) = cos(2x)')+', los ejes y '+M('x = a')+' es '+M('√2/4')+'.', opts: [M('a = π/8'), M('a = π/4'), M('a = π/12'), M('a = π/6')], c: 0, ex: '∫₀ᵃcos(2x)dx = ½sen(2a) = √2/4 → sen(2a) = √2/2 → 2a = π/4 → a = π/8. ▸ Por qué las otras están mal: π/12 daría área ¼ (sen(2a)=½); π/4 y π/6 no satisfacen la ecuación.'},
  {st: '¿Dónde corta al eje x la función '+M('f(x) = 4·ln(x/7) − 1')+'?', opts: [M('x = 7e<sup>1/4</sup>'), M('x = 7e'), M('x = 7'), M('x = e<sup>1/4</sup>')], c: 0, ex: '4·ln(x/7) − 1 = 0 → ln(x/7) = 1/4 → x/7 = e^(1/4) → x = 7e^(1/4). Eso fija el límite inferior del área. ▸ Por qué las otras están mal: x=7 da ln(1)=0 → f=−1 (no corta); x=7e da f=3; e^(1/4) olvida el factor 7.'},
  {st: 'Por el TFC con regla de la cadena, '+M('d/dx ∫<sub>0</sub><sup>x²</sup> g(t) dt')+' es igual a:', opts: [M('g(x²)·2x'), M('g(x²)'), M('g(x)·2x'), M('2x')], c: 0, ex: 'El límite superior es x² (no x): F′(x) = g(x²)·(x²)′ = g(x²)·2x. ▸ Por qué las otras están mal: (B) olvida multiplicar por la derivada del límite (2x); (C) evalúa g en x; (D) se olvida la g.'},
  {st: 'La Regla de Barrow dice que '+M('∫<sub>a</sub><sup>b</sup> f(x) dx')+' es igual a (F primitiva de f):', opts: [M('F(b) − F(a)'), M('F(a) − F(b)'), M('f(b) − f(a)'), M('F(b)·F(a)')], c: 0, ex: 'Integral definida = primitiva en el límite superior menos en el inferior. ▸ Por qué las otras están mal: (B) está al revés (cambia el signo); (C) usa f en vez de su primitiva; (D) no se multiplica.'}
]);

registerExercises('analisis-segundo-parcial', '4', [
  {st: 'Si '+M('f(x) = 3·ln(g(x)) + 4x²')+', ¿cuánto vale '+M('f′(x)')+'?', opts: [M('3·g′(x)/g(x) + 8x'), M('3/g(x) + 8x'), M('3·g′(x)/g(x) + 4x'), M('3·ln(g′(x)) + 8x')], c: 0, ex: 'Regla de la cadena en el ln: d/dx ln(g(x)) = g′(x)/g(x). Y d/dx (4x²) = 8x. Total: 3·g′(x)/g(x) + 8x. ▸ Por qué las otras están mal: (B) olvida g′ en el numerador; (C) deriva mal 4x² (sería 8x); (D) deriva mal el logaritmo.'},
  {st: 'Con '+M('P(x) = 1 + 9(x+1) + 40(x+1)²')+' (Taylor de g en x₀=−1) y '+M('f(x)=3·ln(g(x))+4x²')+', ¿cuánto vale '+M('f′(−1)')+'?', opts: [M('19'), M('27'), M('11'), M('30')], c: 0, ex: 'Del polinomio: g(−1)=1 (término independiente) y g′(−1)=9 (coef de (x+1)). f′(−1) = 3·(9/1) + 8·(−1) = 27 − 8 = 19. ▸ Por qué las otras están mal: 27 olvida el −8; 11 resta mal; 30 usa otra constante.'},
  {st: 'El polinomio de Taylor de orden 2 en x₀=0 de '+M('h(x) = x·∫<sub>0</sub><sup>x</sup> e<sup>t²</sup> dt + 9')+' es:', opts: [M('9 + x²'), M('9 + x'), M('x²'), M('9 + 2x²')], c: 0, ex: 'h(0)=9, h′(0)=0 y h″(0)=2 (porque h″(x)=2e^(x²)(1+x²), en 0 da 2). P(x) = 9 + 0·x + (2/2!)x² = 9 + x². ▸ Por qué las otras están mal: 9+x olvida que h′(0)=0; x² olvida h(0)=9; 9+2x² olvida dividir por 2!.'},
  {st: 'Si '+M('P(x) = 1 + 9(x+1) + 40(x+1)²')+' es el Taylor de g en x₀=−1, ¿cuánto vale '+M('g″(−1)')+'?', opts: [M('40'), M('80'), M('20'), M('120')], c: 1, ex: 'El coeficiente de (x+1)² es g″(−1)/2!, y vale 40. Entonces g″(−1) = 2!·40 = 80. ▸ Por qué las otras están mal: 40 es el coeficiente (falta multiplicar por 2!); 20 divide en vez de multiplicar; 120 usaría 3!.'},
  {st: 'Del mismo polinomio '+M('P(x) = 1 + 9(x+1) + 40(x+1)²')+', ¿cuánto vale '+M('g′(−1)')+'?', opts: [M('9'), M('1'), M('40'), M('80')], c: 0, ex: 'El coeficiente de (x+1)¹ es g′(−1)/1! = g′(−1), y vale 9. ▸ Por qué las otras están mal: 1 es g(−1) (término independiente); 40 es el coef de (x+1)²; 80 es g″(−1).'}
]);

registerExercises('analisis-segundo-parcial', '5', [
  {st: 'El radio de convergencia de la serie '+M('Σ<sub>n=1</sub><sup>∞</sup> (4ⁿ/n³)·(x−3)ⁿ')+' es:', opts: [M('1/4'), M('4'), M('1'), M('3')], c: 0, ex: 'Por el criterio de la raíz: lim ⁿ√(4ⁿ/n³)·|x−3| = 4·|x−3| (porque ⁿ√(n³)→1). Pido <1: |x−3|<1/4 → R = 1/4. ▸ Por qué las otras están mal: 4 es el límite del coeficiente (R es su inverso); 1 y 3 no salen del criterio.'},
  {st: 'El intervalo de convergencia de '+M('Σ (4ⁿ/n³)·(x−3)ⁿ')+' (analizando los extremos) es:', opts: [M('[11/4, 13/4]'), M('(11/4, 13/4)'), M('(−1/4, 1/4)'), 'todo ℝ'], c: 0, ex: 'Con R=1/4 el intervalo abierto es (11/4, 13/4). En x=13/4 queda Σ1/n³ (converge, p=3); en x=11/4 queda Σ(−1)ⁿ/n³ (converge). Ambos extremos convergen → cerrado [11/4, 13/4]. ▸ Por qué las otras están mal: el abierto olvida que los extremos convergen; (−1/4,1/4) es |x−3| sin sumar el centro 3; "todo ℝ" ignora el radio.'},
  {st: 'La suma de la serie '+M('Σ<sub>n=2</sub><sup>∞</sup> (4·3ⁿ + 4ⁿ)/7ⁿ')+' es:', opts: [M('43/21'), M('13/3'), M('28/3'), M('59/42')], c: 0, ex: 'Separo: 4·Σ₂(3/7)ⁿ + Σ₂(4/7)ⁿ. Σ₂(3/7)ⁿ = 7/4 − 1 − 3/7 = 9/28 → por 4 = 9/7. Σ₂(4/7)ⁿ = 7/3 − 1 − 4/7 = 16/21. Total: 9/7 + 16/21 = 43/21. ▸ Por qué las otras están mal: surgen de no restar los términos n=0,1 o de sumar mal las fracciones.'},
  {st: 'La suma '+M('Σ<sub>n=0</sub><sup>∞</sup> (3/7)ⁿ')+' vale:', opts: [M('7/4'), M('3/4'), M('3/7'), M('7/3')], c: 0, ex: 'Geométrica con a=1, r=3/7: a/(1−r) = 1/(1−3/7) = 1/(4/7) = 7/4. ▸ Por qué las otras están mal: 3/4 confunde el cálculo; 3/7 es la razón; 7/3 sería con r=4/7.'},
  {st: '¿Por qué el criterio de la raíz/cociente NO decide la convergencia en los extremos del intervalo?', opts: ['Porque ahí el límite da exactamente 1 (caso no concluyente)', 'Porque la serie siempre diverge en los extremos', 'Porque la serie siempre converge en los extremos', 'Porque no se pueden calcular'], c: 0, ex: 'En x = c ± R el límite del criterio da exactamente 1, y con 1 el criterio NO concluye: por eso hay que analizar cada extremo aparte (a mano). ▸ Por qué las otras están mal: en los extremos puede converger o divergir según el caso, no hay regla fija; sí se pueden estudiar.'}
]);

registerExercises('analisis-segundo-parcial', '6', [
  {st: 'Ante "Hallar a para que el área encerrada sea …", ¿cuál es el primer paso?', opts: ['Plantear la integral del área (con a adentro), resolverla e igualar al valor', 'Derivar la función', 'Calcular el radio de convergencia', 'Hacer el polinomio de Taylor'], c: 0, ex: 'Se plantea ∫ del área dejando el parámetro a, se resuelve con Barrow y se iguala al valor dado para despejar a. ▸ Por qué las otras están mal: derivar no da área; el radio es de series; Taylor no aplica a un problema de áreas.'},
  {st: 'La suma de la serie '+M('Σ<sub>n=2</sub><sup>∞</sup> (2·3ⁿ + 4ⁿ)/7ⁿ')+' es:', opts: [M('59/42'), M('43/21'), M('35/6'), M('17/6')], c: 0, ex: 'Separo: 2·Σ₂(3/7)ⁿ + Σ₂(4/7)ⁿ = 2·(9/28) + 16/21 = 9/14 + 16/21. Común denominador 42: 27/42 + 32/42 = 59/42. ▸ Por qué las otras están mal: salen de olvidar restar n=0,1 o de sumar mal las fracciones.'},
  {st: 'El polinomio de Taylor de orden 2 en 0 de '+M('h(x) = x·∫<sub>0</sub><sup>x</sup> e<sup>t²</sup> dt + 7')+' es:', opts: [M('7 + x²'), M('9 + x²'), M('7 + x'), M('x²')], c: 0, ex: 'Igual que el caso con +9, pero con h(0)=7: h′(0)=0, h″(0)=2 → P(x) = 7 + (2/2!)x² = 7 + x². ▸ Por qué las otras están mal: 9+x² usa otra constante; 7+x olvida h′(0)=0; x² olvida el término independiente 7.'},
  {st: 'El error más caro al hacer un cambio de variable en una integral DEFINIDA es:', opts: ['No reescalar los límites de integración', 'No poner el +C', 'Usar la regla de la cadena', 'Factorizar el denominador'], c: 0, ex: 'En la definida, al sustituir hay que cambiar también los límites (o volver a la variable original antes de Barrow). ▸ El +C es de la indefinida, no de la definida; la cadena y factorizar no son errores.'},
  {st: 'Para calcular '+M('∫<sub>1/2</sub><sup>1</sup> f(2x)/x³ dx')+' sabiendo f(1), f(2) y '+M('∫<sub>1/2</sub><sup>1</sup> f′(2x)/x² dx')+', el método es:', opts: ['Integración por partes', 'Sustitución sola', 'Fracciones simples', 'Tabla directa'], c: 0, ex: 'Se hace por partes (u = f(2x), dv = x^(−3)dx): aparecen f(1), f(2) y la integral de f′(2x)/x² que es dato. ▸ Por qué las otras están mal: una sustitución sola no usa los datos; fracciones simples es para polinomios; no está en la tabla.'}
]);
