// Física I · Dinámica — UTN FRBA
// Fuentes: 1º parciales de la cátedra Martinelli (UTN FRBA, 2009 a 2017, con resolución oficial),
// 1º parcial FRBA 2023 Tema A (Prof. Dibarbora, sin resolución oficial) y finales de UTN.BA
// (12/12/23, 13/02/25 y un final sin fecha compuesto en LaTeX).
// Convenciones de la cátedra usadas en todas las resoluciones: g = 10 m/s²,
// sen37° = 0,6 · cos37° = 0,8 · sen53° = 0,8 · cos53° = 0,6 · sen30° = 0,5 · cos30° = 0,866.

/* ============================================================
   UNIDAD 1 · LA RECETA DE NEWTON + EL DILEMA μe / μd
   ============================================================ */

registerExercises('fisica1-utn-dinamica', '1', [
  {st: 'Un bloque desliza por un plano inclinado de 30° con rozamiento. ¿Cuánto vale la fuerza normal que hace el plano sobre el bloque?',
   opts: ['N = m·g', 'N = m·g·cos30° = 0,866·m·g', 'N = m·g·sen30° = 0,5·m·g', 'N = m·g / cos30°'],
   c: 1,
   ex: 'Con los ejes rotados (x a lo largo del plano, y perpendicular), la ecuación en y da a<sub>y</sub> = 0, y ahí solo entran N y la componente del peso perpendicular al plano, que es P·cos30°. Por eso N = m·g·cos30° y el rozamiento vale f = μ·m·g·cos30°. ▸ Por qué las otras: <b>N = m·g</b> es el error nº1 de la cátedra — vale únicamente en piso horizontal y sin nada empujando; en el parcial 2017 usar m·g te da μ<sub>d</sub> = 0,2 en vez de 0,25. <b>N = m·g·sen30°</b> confunde las dos componentes: sen va sobre el plano (es la que lo hace bajar), cos es la que aprieta contra la superficie. <b>N = m·g/cos30°</b> es más grande que el peso, imposible: sobre un plano inclinado la normal siempre es <i>menor</i> que m·g.'},

  {st: 'El enunciado te da μe = 0,30 y μd = 0,25, y aclara que el sistema se mueve hacia la derecha con aceleración a = 4 m/s² (parcial 2010). ¿Con cuál calculás el rozamiento?',
   opts: ['Con μe, porque hay que vencerlo primero para que arranque', 'Con μd, y μe es un dato que no interviene', 'Con el promedio de los dos', 'Con μe en el bloque del plano y μd en el de la meseta'],
   c: 1,
   ex: 'La única pregunta que importa es: <b>¿las dos superficies en contacto están resbalando una sobre la otra?</b> Acá sí — el sistema se mueve y los bloques deslizan sobre las superficies —, así que el rozamiento es dinámico, f = μ<sub>d</sub>·N, y μe es uno de los distractores deliberados que anuncia la nota del parcial ("puede haber datos que no interesen"). ▸ Por qué las otras: <b>μe para arrancar</b> mezcla dos instantes distintos: el arranque ya pasó, el problema te describe el sistema en movimiento. <b>El promedio</b> no existe como concepto físico. <b>Uno para cada bloque</b> tampoco: los dos deslizan, los dos van con μ<sub>d</sub>; lo que sí es distinto en cada bloque es la <i>normal</i> (N₁ = m₁·g·cos30° y N₂ = m₂·g).'},

  {st: 'Parcial 2016: el bloque 1 está apoyado ARRIBA del bloque 2 y se aplica sobre el 2 una fuerza F horizontal, la máxima posible para que el 1 no deslice sobre el 2 (μe = 0,3 · μd = 0,2). ¿Qué fuerza acelera al bloque 1?',
   opts: ['La fuerza F, que se transmite por el contacto entre los bloques', 'El rozamiento estático que le hace el bloque 2, apuntando hacia adelante, con μe en su valor máximo', 'El rozamiento dinámico que le hace el bloque 2, apuntando hacia atrás, con μd', 'La normal entre los bloques, que es horizontal'],
   c: 1,
   ex: 'F se aplica al bloque de abajo: sobre el bloque 1 no hay ninguna fuerza horizontal aplicada, y sin embargo acelera. La única candidata es el <b>rozamiento estático</b> que le hace el bloque 2, y por eso apunta <b>en el sentido del movimiento</b>. Como F es "la máxima posible para que no deslice", ese rozamiento está en su techo: μe·N₁₂ = μe·P₁ = 0,3·50 N = 15 N = m₁·a, de donde a = 3 m/s² y después F = (m₁+m₂)·a = 45 N. ▸ Por qué las otras: <b>F transmitida por contacto</b> no existe como fuerza sobre el 1: entre los bloques solo hay normal y rozamiento. <b>μd = 0,2</b> es el distractor de este ejercicio (al revés que en 2010 y 2014): el bloque 1 <i>no</i> desliza sobre el 2, así que el rozamiento es estático; usar μd te da a = 2 m/s² y F = 30 N, todo mal. <b>La normal entre los bloques</b> es vertical (la superficie de contacto es horizontal): no puede acelerar a nadie hacia adelante.'},

  {st: 'Sobre un cuerpo apoyado en un piso horizontal se aplica una fuerza F formando 37° POR DEBAJO de la horizontal (parcial 2014). ¿Cuánto vale la normal?',
   opts: ['N = m·g − F·sen37°', 'N = m·g', 'N = m·g + F·sen37°', 'N = m·g + F·cos37°'],
   c: 2,
   ex: 'La componente vertical de F apunta hacia abajo y <b>aprieta</b> el cuerpo contra el piso: la ecuación en y queda N − m·g − F·sen37° = 0, o sea N = m·g + F·sen37°. El rozamiento crece con F, y por eso F aparece en las dos ecuaciones y hay que resolver el sistema (sale F = 14 N). ▸ Por qué las otras: <b>N = m·g − F·sen37°</b> es el caso de la fuerza tirando 37° por <i>encima</i> de la horizontal; el texto solo dice "en la dirección indicada en la figura", así que hay que mirar el dibujo sí o sí. <b>N = m·g</b> ignora la componente vertical de F. <b>N = m·g + F·cos37°</b> mezcla las componentes: cos37° es la componente <i>horizontal</i>, la que empuja hacia adelante.'},

  {st: 'Un cuerpo se mueve con velocidad constante sobre una superficie con rozamiento. ¿Qué se deduce?',
   opts: ['Es un problema de estática: el rozamiento es estático y vale f ≤ μe·N', 'a = 0 y ΣF = 0, pero el rozamiento es dinámico: f = μd·N, un número determinado', 'a = 0 y por lo tanto no hay rozamiento', 'La velocidad constante no dice nada sobre la aceleración'],
   c: 1,
   ex: 'Velocidad constante ⇒ <b>a = 0</b> ⇒ ΣF = 0. Hasta ahí es igual que la estática, pero el cuerpo <b>está deslizando</b>, así que el rozamiento es dinámico y vale exactamente μ<sub>d</sub>·N. Es equilibrio <i>dinámico</i>. Esa diferencia es la que te permite despejar μ<sub>d</sub> = 0,25 en el parcial 2017 en vez de quedarte con una desigualdad inútil. ▸ Por qué las otras: <b>estática con f ≤ μe·N</b> te deja una desigualdad y no podés despejar ningún número. <b>a = 0 ⇒ no hay rozamiento</b> confunde fuerza neta nula con ausencia de fuerzas: el rozamiento está y es justo el que equilibra al resto. <b>No dice nada</b> es falso: constante significa que no cambia, ni en módulo ni en dirección, y esa es la definición de a = 0.'},

  {st: 'Una caja de 10 kg sube inmóvil sobre una cinta transportadora inclinada 37° que se mueve con rapidez constante de 2 m/s (parcial FRBA 2023). ¿Qué fuerza hace subir a la caja y hacia dónde apunta?',
   opts: ['El rozamiento estático, paralelo al plano y hacia arriba', 'El rozamiento dinámico, paralelo al plano y hacia arriba', 'La normal, que tiene una componente hacia arriba del plano', 'La cinta la empuja por atrás con una fuerza de contacto'],
   c: 0,
   ex: 'La caja está <b>inmóvil respecto de la cinta</b>: no hay deslizamiento relativo, así que el rozamiento es <b>estático</b>. Y es la única fuerza que puede equilibrar la componente del peso que tira hacia abajo del plano: f<sub>e</sub> = P·sen37° = 60 N, hacia arriba del plano. Otro contraejemplo de la frase "el rozamiento siempre frena". ▸ Por qué las otras: <b>dinámico</b> requeriría que la caja resbalara sobre la banda, y no lo hace (se mueven juntas). <b>La normal</b> es perpendicular a la superficie por definición: no tiene componente a lo largo del plano. <b>Un empuje por atrás</b> no existe: la cinta es plana y no tiene ningún tope, solo puede rozar. Ojo también con el dato de 2 m/s: es distractor puro, lo único que importa es que sea <i>constante</i> (a = 0).'}
]);

registerReveals('fisica1-utn-dinamica', '1', [
  {st: '<b>B:</b> Un plato de masa m<sub>P</sub> = 500g, viaja sobre la bandeja de un mozo de bar. La bandeja tiene aceleración a<sub>B</sub> en la dirección indicada en la figura (horizontal, hacia adelante). Se sabe que el valor máximo que puede tener a<sub>B</sub> para que el plato no deslice respecto de la bandeja es 4m/s², y que el coeficiente de rozamiento dinámico entre el plato y la bandeja es μ<sub>D</sub>=0.3.<br>a) Determine el coeficiente de rozamiento estático entre la bandeja y el plato.<br>b) Si a<sub>B</sub> = 6m/s², ¿qué aceleración tiene el plato respecto del suelo? <span class="muted">(1er parcial 2013, cátedra Martinelli, curso O1122, 3/9/2013)</span>',
   ans: 'a) μe = 0,4 &nbsp;·&nbsp; b) a<sub>P</sub> = 3 m/s² respecto del suelo, hacia adelante (la bandeja se le escapa con 3 m/s² relativos).',
   sol: '<b>Sistema de referencia.</b> x horizontal, positivo en el sentido de a<sub>B</sub>; y vertical hacia arriba. Todo medido desde el suelo (sistema inercial). Hipótesis: la bandeja es horizontal, el plato es puntual.<br><br><b>Paso 1 · DCL del plato.</b> Peso P = m·g hacia abajo, normal N hacia arriba, rozamiento f horizontal. <b>No hay ninguna otra fuerza horizontal</b>: si no hubiera rozamiento el plato se quedaría quieto y la bandeja se le iría de abajo. En y: N − m·g = 0 ⇒ <b>N = m·g</b>.<br><br><b>Paso 2 · Inciso a): el caso límite.</b> Mientras no desliza, el plato tiene la misma aceleración que la bandeja (a<sub>P</sub> = a<sub>B</sub>) y quien se la da es el rozamiento <b>estático</b>. El valor máximo de a<sub>B</sub> corresponde al rozamiento estático en su techo:<br>f<sub>e,máx</sub> = μe·N = μe·m·g = m·a<sub>B,máx</sub><br>La masa se cancela (los 500 g son un dato que no interesa):<br>μe = a<sub>B,máx</sub> / g = 4 m/s² / 10 m/s² ⇒ <b>μe = 0,4</b><br><br><b>Paso 3 · Inciso b): ahora sí desliza.</b> Con a<sub>B</sub> = 6 m/s² &gt; 4 m/s² se superó el techo estático: el plato <b>desliza</b> respecto de la bandeja y el rozamiento pasa a ser dinámico, con un valor <b>fijo</b>:<br>f<sub>d</sub> = μ<sub>D</sub>·m·g = m·a<sub>P</sub> ⇒ a<sub>P</sub> = μ<sub>D</sub>·g = 0,3 · 10 m/s²<br>⇒ <b>a<sub>P</sub> = 3 m/s²</b>, en el mismo sentido que a<sub>B</sub>, medida <b>respecto del suelo</b>.<br><br><b>Paso 4 · Chequeos.</b> μe = 0,4 &gt; μ<sub>D</sub> = 0,3 ✓. Y fijate en lo contraintuitivo: por más que el mozo acelere la bandeja a 20 m/s², el plato nunca pasa de 3 m/s², porque su aceleración queda fijada por el rozamiento dinámico. La aceleración <i>relativa</i> (el plato yéndose para atrás sobre la bandeja) es 6 − 3 = 3 m/s², pero eso no es lo que te preguntan.'},

  {st: '<b>Problema B2:</b> Se tiene el sistema mostrado en la figura. Las masas de los bloques son m₁=5kg y m₂=10kg, respectivamente. Entre ambos bloques existe rozamiento, siendo los coeficientes de rozamiento estático y dinámico μe=0.3 y μd=0.2. La superficie horizontal no tiene rozamiento. Desde el reposo y durante 6s, sobre el bloque 2 se aplica una fuerza horizontal constante F, que tiene el máximo valor posible como para que el bloque 1 no deslice sobre el 2. Determine:<br>a) La aceleración que adquieren los bloques y el valor de la fuerza F.<br>b) El trabajo realizado por F. <span class="muted">(1er parcial 2016, cátedra Martinelli, curso R1022, 1/8/2016. El bloque 1 va apoyado ARRIBA del 2, y F se aplica al de abajo)</span>',
   ans: 'a) a = 3 m/s² y F = 45 N &nbsp;·&nbsp; b) W<sub>F</sub> = 2430 J',
   sol: '<b>Sistema de referencia.</b> x horizontal positivo en el sentido de F, y vertical hacia arriba, medido desde el piso.<br><b>Vínculos.</b> Como el 1 no desliza sobre el 2: a₁ₓ = a₂ₓ = a, y a₁y = a₂y = 0.<br><br><b>Paso 1 · Las normales (ecuaciones en y).</b> Sobre el bloque 1 solo apoya su propio peso:<br>N₁₂ = P₁ = m₁·g = 50 N<br>Sobre el piso apoya el peso de los dos:<br>N<sub>2S</sub> = P₁ + P₂ = 150 N<br>Confundirlas es el error clásico: <b>la normal entre los bloques NO es el peso total</b>.<br><br><b>Paso 2 · El bloque de arriba manda.</b> Sobre el bloque 1 la única fuerza horizontal es el rozamiento que le hace el 2, y apunta <b>hacia adelante</b> (es lo único que lo puede acelerar). Como F es la máxima posible sin que deslice, ese rozamiento está en su valor límite:<br>f<sub>e,máx</sub> = μe·N₁₂ = 0,3 · 50 N = 15 N = m₁·a<br>⇒ <b>a = 15 N / 5 kg = 3 m/s²</b><br>Fijate que la aceleración sale del bloque de arriba <b>solo</b>, no del sistema.<br><br><b>Paso 3 · Ahora sí, F.</b> Con el sistema completo (el rozamiento entre bloques es interno y se cancela, y el piso es liso):<br>F = (m₁ + m₂)·a = 15 kg · 3 m/s² ⇒ <b>F = 45 N</b><br>(Control por el bloque 2: F − f′<sub>e</sub> = m₂·a ⇒ F = 15 + 30 = 45 N ✓)<br><br><b>Paso 4 · Inciso b): el trabajo.</b> Parte del <b>reposo</b>, así que Δx = ½·a·Δt²:<br>Δx = ½ · 3 m/s² · (6 s)² = 54 m<br>W<sub>F</sub> = F·Δx = 45 N · 54 m ⇒ <b>W<sub>F</sub> = 2430 J</b><br>Control por el teorema de las fuerzas vivas: v<sub>f</sub> = a·Δt = 18 m/s, y W<sub>TOT</sub> = ½·(m₁+m₂)·v<sub>f</sub>² = ½·15·324 = 2430 J ✓ (el par de rozamiento interno no disipa nada porque no hay deslizamiento relativo).<br><br><b>Trampa principal.</b> μd = 0,2 es el <b>distractor</b>: el bloque 1 no desliza sobre el 2, así que va μe. Con μd te daría a = 2 m/s² y F = 30 N.'},

  {st: '<b>4.</b> Una caja de 10 kg se encuentra inmóvil sobre una correa transportadora que la hace ascender con rapidez constante de 2 m/s. La correa es plana y forma con la horizontal un ángulo de 37º. Respecto de esta situación: a) Calcule el valor o módulo de la fuerza de roce estático que actúa sobre la caja y el valor del coeficiente de roce estático entre la caja y la correa para que ésta no deslice pero esté a punto de hacerlo (situación límite). Realizar el DCL. <span class="muted">(1º parcial FRBA 2023, Tema A, Prof. Dibarbora. El examen imprime g = 10 m/s² en el encabezado)</span>',
   ans: 'f<sub>e</sub> = 60 N paralela al plano y hacia arriba &nbsp;·&nbsp; N = 80 N &nbsp;·&nbsp; μe = 0,75 (= tg37°)',
   sol: '<b>Sistema de referencia.</b> Ejes propios: x a lo largo de la correa, positivo hacia arriba del plano; y perpendicular a la correa. (El examen exige el DCL y los desarrollos en tinta.)<br><br><b>Paso 1 · DCL de la caja: son tres fuerzas y nada más.</b><br>• Peso P = m·g = 100 N, vertical hacia abajo.<br>• Normal N, perpendicular a la superficie de la correa.<br>• Rozamiento <b>estático</b> f<sub>e</sub>, paralelo a la correa y <b>hacia arriba</b> del plano.<br>La correa no empuja a la caja: solo la roza. Es estático porque la caja no desliza respecto de la banda, aunque el conjunto se traslade.<br><br><b>Paso 2 · La clave conceptual.</b> Rapidez <b>constante</b> y trayectoria recta ⇒ <b>a = 0</b> ⇒ equilibrio. Los 2 m/s son un dato distractor: no entran en ninguna cuenta, solo importa que la velocidad no cambie.<br><br><b>Paso 3 · Ecuaciones.</b><br>En x: f<sub>e</sub> − P·sen37° = 0 ⇒ f<sub>e</sub> = 100 N · 0,6 ⇒ <b>f<sub>e</sub> = 60 N</b><br>En y: N − P·cos37° = 0 ⇒ N = 100 N · 0,8 ⇒ <b>N = 80 N</b><br><br><b>Paso 4 · La situación límite.</b> "A punto de deslizar" significa que el rozamiento estático está en su techo: f<sub>e</sub> = μe·N.<br>μe = f<sub>e</sub>/N = 60 N / 80 N ⇒ <b>μe = 0,75</b><br>Que es exactamente tg37°: el resultado clásico del plano inclinado en el límite. Con cualquier μe ≥ 0,75 la caja sube sin deslizar.<br><br><b>Ojo con la redacción.</b> El enunciado dice "para que ésta no deslice" refiriéndose a la <b>caja</b>, no a la correa: es una concordancia confusa del original.'}
]);

/* ============================================================
   UNIDAD 2 · BLOQUES VINCULADOS POR CUERDA Y POLEA
   ============================================================ */

registerExercises('fisica1-utn-dinamica', '2', [
  {st: 'Dos bloques unidos por una cuerda bajan por el MISMO plano inclinado. El de arriba tiene μ₁ = 0,4 y el de abajo μ₂ = 0,2 (parcial 2009). Si los dos coeficientes fueran iguales, ¿qué pasaría con la tensión?',
   opts: ['Se duplicaría', 'Sería T = 0 y la cuerda quedaría floja', 'Seguiría igual: la tensión no depende de los coeficientes', 'La cuerda se cortaría'],
   c: 1,
   ex: 'Con μ iguales los dos bloques tendrían exactamente la misma aceleración por su cuenta (g·senα − μ·g·cosα no depende de la masa), así que no se empujarían ni se estirarían entre sí: <b>la cuerda queda floja y T = 0</b>. La cuerda está tensa justamente porque el de arriba frena más (μ₁ &gt; μ₂) y el de abajo se le adelantaría. ▸ Por qué las otras: <b>Se duplicaría</b> no sale de ninguna ecuación. <b>La tensión no depende de los coeficientes</b> es falso: si sumás las dos ecuaciones en x, T se cancela solo para hallar la aceleración; para obtener T hay que volver a una ecuación individual, donde el μ de ese cuerpo aparece explícito (acá T = 11,55 N). <b>Se cortaría</b> es al revés: la cuerda ideal no se corta y, con μ iguales, ni siquiera trabaja.'},

  {st: 'Rampa de 30° que termina en una meseta horizontal, con una polea en el vértice: M₁ está en la rampa y M₂ en la meseta, unidos por una cuerda, y desde afuera se tira de M₂ con una tensión T (parcial 2010). ¿Cuántas normales distintas hay y cuánto valen?',
   opts: ['Una sola: N = (m₁ + m₂)·g', 'Dos: N₁ = m₁·g·cos30° y N₂ = m₂·g', 'Dos, pero las dos con cos30°: N₁ = m₁·g·cos30° y N₂ = m₂·g·cos30°', 'Ninguna, porque el sistema está acelerando'],
   c: 1,
   ex: 'Cada cuerpo tiene <b>su propia</b> ecuación en y, y por lo tanto su propia normal, calculada sobre <b>su</b> superficie: M₁ apoya en el plano inclinado (N₁ = m₁·g·cos30° = 8,66 N) y M₂ apoya en la meseta horizontal (N₂ = m₂·g = 20 N). Con μd = 0,25 eso da rozamientos de 2,165 N y 5 N. ▸ Por qué las otras: <b>Una normal para el sistema</b> no existe: la normal es una fuerza de contacto por superficie, no una propiedad del conjunto. <b>Las dos con cos30°</b> le aplica la geometría de la rampa al bloque que está en la meseta plana, que es horizontal. <b>Ninguna porque acelera</b> confunde ejes: en la dirección perpendicular a cada superficie la aceleración es cero (los cuerpos no se hunden ni se despegan), y de ahí sale la normal.'},

  {st: 'Doble plano 37° / 53° con polea en el vértice, m₁ = m₂ = 1 kg, el plano de la derecha (53°) es liso, y el sistema se mueve hacia la derecha con velocidad constante (parcial 2017). ¿Cuánto vale la tensión?',
   opts: ['T = 6 N', 'T = 8 N', 'T = 10 N', 'No se puede saber sin conocer μd del plano izquierdo'],
   c: 1,
   ex: 'Empezá siempre por el bloque más simple. El plano derecho es <b>liso</b> y la velocidad es constante (a = 0), así que la ecuación en x de m₂ tiene solo dos términos: m₂·g·sen53° − T = 0 ⇒ <b>T = 1·10·0,8 = 8 N</b>, sin resolver ningún sistema. Recién después, con T y N₁ = m₁·g·cos37° = 8 N, sale μd = (8 − 6)/8 = 0,25. ▸ Por qué las otras: <b>6 N</b> sale de usar sen37° = 0,6 en el bloque de la derecha: son ángulos complementarios y hay que asignarle a cada bloque el suyo (sen53° = 0,8). <b>10 N</b> es m·g completo, como si el bloque colgara en el aire en vez de apoyar en un plano. <b>Necesito μd</b> invierte el orden: μd es la incógnita que sale al final, T es lo que se despeja primero.'},

  {st: 'Polea del techo, dos bloques colgando EN SERIE (el 2 cuelga del 1), cada uno de 20 N de peso, y se tira del extremo libre de la cuerda de manera que ascienden con a = 3 m/s² (parcial 2012). ¿Cuánto vale la tensión de la cuerda que une el bloque 1 con el 2?',
   opts: ['T₂ = 20 N', 'T₂ = 26 N', 'T₂ = 46 N', 'T₂ = 52 N'],
   c: 1,
   ex: 'La cuerda de abajo sostiene <b>solo</b> al bloque 2, así que su DCL tiene dos fuerzas: T₂ − P₂ = m·a ⇒ T₂ = 20 N + 2 kg·3 m/s² = <b>26 N</b>. Después, en el bloque 1: T₁ − P₁ − T₂ = m·a ⇒ T₁ = 6 + 20 + 26 = 52 N, y la fuerza con la que se tira es F = T₁ = 52 N (polea ideal). ▸ Por qué las otras: <b>20 N</b> es el peso: solo valdría si el bloque estuviera quieto o a velocidad constante; acá está <b>acelerando</b>, así que T &gt; P. <b>46 N</b> suma los dos pesos más m·a de uno solo: mezcla los dos DCL. <b>52 N</b> es T₁, la tensión de la cuerda de <i>arriba</i>, que sostiene a los dos bloques: suponer T₁ = T₂ es el error típico — <b>una cuerda distinta es una tensión distinta</b>.'},

  {st: 'Plano inclinado 30° con rozamiento, polea en la cima y un cuerpo colgando, ambos de igual masa m (parcial 2011). ¿Cuál es el mínimo coeficiente de rozamiento estático para que el sistema quede en reposo?',
   opts: ['μe = 0,5', 'μe = 0,577', 'μe = 0,866', 'No se puede calcular sin el valor de m'],
   c: 1,
   ex: 'Sin rozamiento el colgante bajaría (m·g &gt; m·g·sen30°), así que el rozamiento sobre el bloque del plano apunta <b>hacia abajo</b> del plano. En reposo: T = m·g (del colgante) y T = f + m·g·sen30° (del bloque), de donde f = m·g/2. En el caso límite f = μe·N = μe·m·g·cos30°, y queda μe = 0,5/0,866 = <b>0,577 = tg30°</b>. ▸ Por qué las otras: <b>0,5</b> es sen30°: sale de usar N = m·g en vez de N = m·g·cos30°. <b>0,866</b> es cos30°: está la fracción dada vuelta. <b>Falta m</b> es el distractor más lindo del ejercicio: las dos masas son iguales y m se cancela en toda la cuenta, por eso el enunciado <i>no te la da</i>.'},

  {st: 'Te piden la aceleración Y la tensión de un sistema de dos bloques vinculados. ¿Cuándo podés tratarlos como un solo cuerpo de masa m₁ + m₂?',
   opts: ['Nunca: siempre hay que plantear los dos DCL por separado', 'Para hallar la aceleración sí (la tensión se cancela al sumar), pero para la tensión hay que volver a una ecuación individual', 'Para las dos cosas, si la cuerda y la polea son ideales', 'Solo si los coeficientes de rozamiento son iguales'],
   c: 1,
   ex: 'Al sumar las dos ecuaciones en x, la tensión aparece con signo + en una y − en la otra y <b>se cancela</b>: queda una sola ecuación con la aceleración como única incógnita. Pero la tensión es una fuerza <b>interna</b> del conjunto, así que al sumarlas la perdés: hay que reemplazar la a que hallaste en el DCL de <i>uno</i> de los cuerpos. ▸ Por qué las otras: <b>Nunca</b> es demasiado estricto — sumar es un atajo perfectamente válido y rápido para la aceleración (y es lo que hace la resolución oficial del 2009). <b>Para las dos cosas</b> es el error: por más ideales que sean cuerda y polea, una fuerza interna nunca sale de la ecuación del conjunto. <b>Solo con μ iguales</b> mezcla dos temas: los μ distintos afectan el valor de T, no la validez del método.'}
]);

registerReveals('fisica1-utn-dinamica', '2', [
  {st: '<b>A · 2)</b> Dos cuerpos unidos por una cuerda ideal, descienden por un plano inclinado de ángulo 30°, como se muestra en la figura. Sabiendo que el peso del cuerpo 1 es 100N, el peso del cuerpo 2 es 200N y que los coeficientes de rozamiento dinámico entre el cuerpo 1 y el plano y entre el cuerpo 2 y el plano son, respectivamente, 0.4 y 0.2, calcule:<br>a) La aceleración de los cuerpos y la tensión de la cuerda.<br>b) Si en el instante inicial, t = 0s, ambos cuerpos se encuentran en reposo, cuánto tardarán en recorrer sobre el plano inclinado una distancia de 2m, a partir de sus posiciones iniciales. <span class="muted">(1er parcial 2009, tema 1, cátedra Martinelli, 22/10/09. El cuerpo 1 va arriba y el 2 abajo)</span>',
   ans: 'a) a = 2,691 m/s² hacia abajo del plano y T = 11,55 N &nbsp;·&nbsp; b) t = 1,22 s',
   sol: '<b>Sistema de referencia.</b> Para cada cuerpo: x paralelo al plano, positivo <b>hacia abajo</b> (sentido del movimiento); y perpendicular al plano, positivo hacia afuera.<br><b>Vínculos.</b> a₁ₓ = a₂ₓ = a y a₁y = a₂y = 0.<br><b>Primero, las masas.</b> Te dan <b>pesos</b> en newtons, no masas: m₁ = 100/10 = 10 kg y m₂ = 200/10 = 20 kg.<br><br><b>Paso 1 · Ecuaciones en y (las normales).</b><br>N₁ = P₁·cos30° = 100 · 0,866 = 86,6 N<br>N₂ = P₂·cos30° = 200 · 0,866 = 173,2 N<br>Cada cuerpo con su propia normal y su propio coeficiente.<br><br><b>Paso 2 · Ecuaciones en x.</b> Bajan, así que el rozamiento apunta hacia arriba del plano (negativo). La cuerda tira del 1 hacia abajo y del 2 hacia arriba:<br>(1) T + P₁·sen30° − μ₁·N₁ = m₁·a<br>(2) −T + P₂·sen30° − μ₂·N₂ = m₂·a<br><br><b>Paso 3 · Sumo (1) + (2): T se cancela.</b><br>(P₁+P₂)·sen30° − (μ₁·P₁ + μ₂·P₂)·cos30° = (m₁+m₂)·a<br>300·0,5 − (40 + 40)·0,866 = 30·a<br>150 − 69,28 = 80,72 N = 30 kg · a<br>⇒ <b>a = 2,691 m/s²</b>, hacia abajo del plano<br><br><b>Paso 4 · Vuelvo a (1) para la tensión.</b><br>T = m₁·a − P₁·sen30° + μ₁·P₁·cos30° = 26,91 − 50 + 34,64<br>⇒ <b>T = 11,55 N</b><br><br><b>Paso 5 · Inciso b): MRUV desde el reposo.</b><br>2 m = ½ · 2,691 m/s² · t² ⇒ t² = 1,486 s² ⇒ <b>t = 1,22 s</b><br><br><b>Chequeos.</b> a = 2,691 &lt; g·sen30° = 5 m/s² ✓ (el rozamiento frena, como debe). Los 2 m son medidos <b>sobre el plano</b>, no en altura ni en proyección horizontal.'},

  {st: '<b>B · B1)</b> Se tiene el sistema que se muestra en la figura. Los bloques tienen igual masa y están unidos por una cuerda ideal. El plano inclinado presenta rozamiento y forma un ángulo de 30º con la horizontal. La polea es ideal.<br>a) Determine qué valor debe tener, como mínimo, el coeficiente de rozamiento estático para que los bloques puedan permanecer en reposo.<br>b) Calcule qué valor debe tener el coeficiente de rozamiento dinámico para que el bloque de la derecha descienda con aceleración 1m/s². <span class="muted">(1er parcial 2011, cátedra Martinelli, 20/10/11. Bloque 1 sobre el plano, bloque 2 colgando de la polea de la cima)</span>',
   ans: 'a) μe<sub>mín</sub> = 0,577 (= tg30°) &nbsp;·&nbsp; b) μd = 0,346',
   sol: '<b>Sistema de referencia.</b> Bloque 1: x a lo largo del plano, positivo <b>hacia arriba</b> de la pendiente; y perpendicular al plano. Bloque 2: x vertical, positivo <b>hacia abajo</b>. Con esos ejes el vínculo es a₁ₓ = a₂ₓ = a.<br><br><b>Paso 0 · ¿Para dónde tiende a moverse?</b> Sin rozamiento, m·g (lo que tira el colgante) &gt; m·g·sen30° (lo que tira el del plano). Entonces el 2 baja y el 1 sube ⇒ el rozamiento sobre el bloque 1 apunta <b>hacia abajo</b> del plano. Esto se decide <b>antes</b> de escribir nada.<br><br><b>Paso 1 · Inciso a): reposo, a = 0.</b><br>Bloque 1 en x: T − f<sub>e</sub> − m·g·sen30° = 0<br>Bloque 1 en y: N = m·g·cos30°<br>Bloque 2 en x: m·g − T = 0 ⇒ T = m·g<br>Reemplazando: m·g − f<sub>e</sub> − m·g/2 = 0 ⇒ f<sub>e</sub> = m·g/2<br>Caso límite (mínimo μe posible): f<sub>e</sub> = μe·N = μe·m·g·cos30°<br>0,5·m·g = μe·0,866·m·g ⇒ <b>μe<sub>mín</sub> = 0,577 = tg30°</b><br>La masa se cancela: por eso el enunciado no te la da.<br><br><b>Paso 2 · Inciso b): ahora desliza, a = 1 m/s².</b><br>(4) T − μd·N − m·g·sen30° = m·a<br>(6) m·g − T = m·a &nbsp;&nbsp;<span class="muted">(ojo: acá T = m(g−a) ≠ m·g)</span><br>Sumo (4)+(6) y uso N = m·g·cos30°:<br>m·g − μd·m·g·cos30° − m·g·sen30° = 2·m·a<br>g·(1 − 0,866·μd − 0,5) = 2 m/s²<br>10·(0,5 − 0,866·μd) = 2 ⇒ 0,5 − 0,866·μd = 0,2<br>⇒ <b>μd = 0,3/0,866 = 0,346</b><br><br><b>Chequeo.</b> μd = 0,346 &lt; μe<sub>mín</sub> = 0,577 ✓, coherente con que ahora sí desliza.'},

  {st: '<b>C · B2)</b> Se tiene el sistema que se muestra en la figura. Los bloques, de masas M1=1kg y M2=2kg, están unidos por una cuerda ideal, y mediante otra cuerda ideal se tira del bloque 2 con una tensión T. El plano inclinado forma un ángulo de 30º con la horizontal y la polea es ideal. Entre los bloques y las superficies existe rozamiento, siendo los coeficientes de rozamiento estático y dinámico µe=0.30 y µd=0.25, respectivamente.<br>a) Calcule el valor de T, sabiendo que el sistema se mueve hacia la derecha, con una aceleración a=4m/s².<br>b) En esas condiciones, indique qué velocidad tienen los bloques a los 2s de iniciado el movimiento. <span class="muted">(1er parcial 2010, cátedra Martinelli, 26/10/10. M1 en la rampa, M2 en la meseta horizontal, polea en el vértice)</span>',
   ans: 'a) T = 24,165 N (y la cuerda interna T₂ = 11,165 N) &nbsp;·&nbsp; b) v = 8 m/s',
   sol: '<b>Sistema de referencia.</b> Origen en la polea, con un eje x que "dobla" en ella: para M₁ apunta hacia arriba de la rampa, para M₂ horizontal hacia la derecha. El eje y es perpendicular a la superficie de apoyo de cada bloque.<br><b>Vínculos.</b> a₁ₓ = a₂ₓ = a = 4 m/s² y a₁y = a₂y = 0.<br><b>Coeficiente.</b> El sistema <b>se mueve</b> ⇒ rozamiento dinámico, μd = 0,25. μe = 0,30 no interviene.<br><br><b>Paso 1 · Las dos normales (en y).</b><br>N₁ = m₁·g·cos30° = 1·10·0,866 = <b>8,66 N</b> &nbsp;(bloque de la rampa)<br>N₂ = m₂·g = 2·10 = <b>20 N</b> &nbsp;(bloque de la meseta)<br><br><b>Paso 2 · Bloque 1 (sube por la rampa).</b> Llamemos T₂ a la cuerda que une los bloques:<br>T₂ − m₁·g·sen30° − μd·N₁ = m₁·a<br>T₂ = 1·4 + 1·10·0,5 + 0,25·8,66 = 4 + 5 + 2,165<br>⇒ <b>T₂ = 11,165 N</b><br><br><b>Paso 3 · Bloque 2 (en la meseta).</b> Recibe T hacia la derecha, T₂ hacia la izquierda (tira hacia la polea) y el rozamiento:<br>T − T₂ − μd·N₂ = m₂·a<br>T = 11,165 + 0,25·20 + 2·4 = 11,165 + 5 + 8<br>⇒ <b>T = 24,165 N</b><br><br><b>Paso 4 · Inciso b): MRUV.</b> "Iniciado el movimiento" ⇒ v₀ = 0.<br>v = a·t = 4 m/s² · 2 s ⇒ <b>v = 8 m/s</b> (los dos bloques, por el vínculo de la cuerda).<br><br><b>Las dos trampas.</b> (1) Hay <b>dos tensiones distintas</b>: T₂ interna y T externa; confundirlas te deja una ecuación de menos. (2) Hay rozamiento en <b>las dos</b> superficies ("entre los bloques y las superficies"), con normales distintas.'},

  {st: '<b>D · B1)</b> Se tiene el sistema que se muestra en la figura. Los dos cuerpos, 1 y 2, tienen igual masa m1 = m2 = 1 kg, y la cuerda y la polea son ideales. El plano de la izquierda forma un ángulo de 37° con la horizontal y tiene rozamiento, y el de la derecha forma un ángulo de 53° con la horizontal y carece de rozamiento. En esas condiciones, las masas se mueven hacia la derecha con velocidad constante. Determinen el coeficiente de rozamiento dinámico del plano de la izquierda y la tensión de la cuerda. <span class="muted">(1er parcial 2017, cátedra Martinelli, curso R1022, 26/6/2017)</span>',
   ans: 'T = 8 N &nbsp;·&nbsp; μd = 0,25',
   sol: '<b>Sistema de referencia.</b> Cada cuerpo con <b>sus propios ejes rotados</b>: para m₁, x a lo largo del plano izquierdo apuntando hacia arriba (sube); para m₂, x a lo largo del plano derecho apuntando hacia abajo (baja). Usar un solo par de ejes para los dos es el error más común de este ejercicio.<br><b>Vínculos.</b> a₁y = a₂y = 0, a₁ₓ = a₂ₓ. Y como la velocidad es <b>constante</b>: a₁ₓ = a₂ₓ = <b>0</b> (equilibrio dinámico, no estática: el cuerpo desliza, así que el rozamiento es <b>dinámico</b>).<br><b>Sentido del movimiento.</b> "Hacia la derecha" ⇒ m₂ baja y m₁ sube, porque sen53° &gt; sen37°. El rozamiento sobre m₁ va entonces <b>hacia abajo</b> de su plano.<br><br><b>Paso 1 · Empezá por el cuerpo fácil: m₂ (plano liso, a = 0).</b><br>m₂·g·sen53° − T = 0<br>T = 1 kg · 10 m/s² · 0,8 ⇒ <b>T = 8 N</b><br>Sale sola, sin resolver ningún sistema.<br><br><b>Paso 2 · Normal de m₁.</b><br>N₁ = m₁·g·cos37° = 1·10·0,8 ⇒ N₁ = <b>8 N</b><br><br><b>Paso 3 · Ecuación en x de m₁.</b><br>T − m₁·g·sen37° − μd·N₁ = 0<br>μd = (T − m₁·g·sen37°)/N₁ = (8 − 6)/8<br>⇒ <b>μd = 0,25</b><br><br><b>Los complementarios.</b> Para m₁ (37°): sen = 0,6 y cos = 0,8. Para m₂ (53°): sen = 0,8 y cos = 0,6. Intercambiarlos te arruina el ejercicio. Y si usás N₁ = m₁·g = 10 N en vez de 8 N, te da μd = 0,2 en lugar de 0,25.<br><br><b>Dato que no interesa.</b> La normal de m₂ no hace falta para nada.'},

  {st: '<b>E · B1)</b> Se tiene el sistema que se muestra en la figura. Cada bloque tiene masa m=2kg, y las cuerdas y la polea son ideales. Del extremo de una de las cuerdas se tira hacia abajo, como se muestra, de manera tal que los bloques ascienden con aceleración 3m/s².<br>a) Determine qué valor tiene la tensión de cada cuerda.<br>b) ¿Con qué fuerza debe tirarse hacia abajo? <span class="muted">(1er parcial 2012, cátedra Martinelli, 18/10/12. Polea en el techo; del ramal izquierdo cuelga el bloque 1 y de él, en serie, el bloque 2)</span>',
   ans: 'a) T₂ = 26 N (cuerda de abajo) y T₁ = 52 N (cuerda de la polea) &nbsp;·&nbsp; b) F = 52 N',
   sol: '<b>Sistema de referencia.</b> Un solo eje vertical, positivo <b>hacia arriba</b> (sentido de la aceleración). P₁ = P₂ = m·g = 20 N.<br><br><b>Paso 1 · DCL de cada bloque. Son dos cuerdas ⇒ DOS tensiones.</b><br>Bloque 2 (el de abajo): recibe T₂ hacia arriba y su peso hacia abajo. Nada más.<br>Bloque 1 (el de arriba): recibe T₁ hacia arriba, su peso hacia abajo <b>y T₂ hacia abajo</b> (la reacción de la cuerda de la que cuelga el bloque 2). Olvidarse de ese T₂ es el otro error típico.<br><br><b>Paso 2 · Ecuaciones.</b><br>Bloque 2: T₂ − P₂ = m·a ⇒ T₂ = 20 + 2·3 ⇒ <b>T₂ = 26 N</b><br>Bloque 1: T₁ − P₁ − T₂ = m·a ⇒ T₁ = 6 + 20 + 26 ⇒ <b>T₁ = 52 N</b><br><br><b>Paso 3 · Inciso b): la fuerza aplicada.</b> Como la polea y la cuerda son ideales, la tensión es la misma en todo ese ramal: lo que tirás en el extremo libre <b>es</b> T₁. No hay ecuación nueva y <b>no se duplica nada</b>.<br>⇒ <b>F = 52 N</b><br><br><b>Chequeo global.</b> F = (m₁+m₂)·(g+a) = 4 kg · 13 m/s² = 52 N ✓<br>Y control de sentido: los bloques <b>ascienden acelerando</b>, así que T &gt; P en las dos cuerdas ✓.'},

  {st: '<b>F · B1)</b> Un cuerpo de masa m=1kg, se encuentra sobre una superficie horizontal cuyos coeficientes de rozamiento estático y dinámico son, respectivamente, μe=0.7 y μd=0.5. Sobre el mismo está aplicada una fuerza externa de módulo F, en la dirección indicada en la figura (37° POR DEBAJO de la horizontal). En esas condiciones la aceleración del cuerpo es 2m/s².<br>a) Calcule F.<br>b) Si en el instante en que la velocidad del cuerpo es 5m/s deja de aplicarse esa fuerza externa, ¿qué distancia recorre el mismo hasta detenerse? <span class="muted">(1er parcial 2014, cátedra Martinelli, curso I1021, 21/8/2014)</span>',
   ans: 'a) F = 14 N &nbsp;·&nbsp; b) D = 2,5 m',
   sol: '<b>Sistema de referencia.</b> x horizontal positivo en el sentido del movimiento, y vertical hacia arriba. sen37° = 0,6 · cos37° = 0,8.<br><b>Coeficiente.</b> El cuerpo está acelerando, o sea deslizando ⇒ va <b>μd = 0,5</b>. μe = 0,7 es dato que no interesa.<br><br><b>Paso 1 · Las dos ecuaciones (ojo: F aparece en las dos).</b><br>En y: N − m·g − F·sen37° = 0 ⇒ <b>N = m·g + 0,6·F</b><br>La componente vertical de F apunta hacia <b>abajo</b> y aprieta el cuerpo contra el piso: la normal es <i>mayor</i> que el peso.<br>En x: F·cos37° − μd·N = m·a<br><br><b>Paso 2 · Reemplazo y agrupo F.</b><br>0,8·F − 0,5·(10 + 0,6·F) = 1·2<br>0,8·F − 5 − 0,3·F = 2<br>0,5·F = 7 ⇒ <b>F = 14 N</b><br>(Con esa F: N = 10 + 8,4 = 18,4 N y el rozamiento vale 9,2 N.)<br><br><b>Paso 3 · Inciso b): al sacar F, CAMBIA la normal.</b> Este es el error más frecuente del ejercicio: arrastrar la N del inciso a).<br>N′ = m·g = 10 N ⇒ f = μd·N′ = <b>5 N</b> (antes eran 9,2 N)<br><br><b>Paso 4 · La distancia.</b> Por el teorema del trabajo y la energía cinética:<br>0 − ½·m·v₀² = −f·D ⇒ −12,5 J = −5 N · D<br>⇒ <b>D = 2,5 m</b><br>Control por cinemática: a′ = −μd·g = −5 m/s², D = v₀²/(2·5) = 25/10 = 2,5 m ✓'}
]);

/* ============================================================
   UNIDAD 3 · CINEMÁTICA PURA
   ============================================================ */

registerExercises('fisica1-utn-dinamica', '3', [
  {st: 'Dos autos: B va a 20 m/s constante y arranca 60 m adelante; A arranca a 10 m/s y acelera con a constante, y lo alcanza 30 s después (parcial 2017). ¿Cómo conviene atacarlo?',
   opts: ['Igualando x<sub>A</sub>(t) = x<sub>B</sub>(t) y resolviendo la cuadrática con a como incógnita', 'Evaluando x<sub>B</sub>(30 s), que es la ecuación más simple: el tiempo de encuentro YA es dato', 'Calculando la velocidad relativa y dividiendo los 60 m por ella', 'No alcanzan los datos: falta la posición inicial de A'],
   c: 1,
   ex: 'El tiempo de encuentro te lo <b>dan</b> (30 s), así que no hay ninguna ecuación de encuentro que resolver: evaluás la horaria más simple, la de B (MRU), y listo: x<sub>E</sub> = 60 + 20·30 = <b>660 m</b>. Recién ahí imponés que A esté en esa posición: 660 = 10·30 + ½·a·900 ⇒ a = 0,8 m/s². ▸ Por qué las otras: <b>La cuadrática</b> se puede plantear, pero con dos incógnitas (a y t) te trabás; es exactamente donde se cuelga la mayoría. <b>La velocidad relativa</b> solo sirve si los dos van a velocidad constante, y A está acelerando. <b>Falta la posición de A</b>: no falta, la elegís vos — poné el origen donde está A en t = 0 y declaralo por escrito.'},

  {st: 'En ese mismo problema, ¿por qué la respuesta puede ser 660 m o 600 m según quién la resuelva?',
   opts: ['Porque depende de si se toma g = 9,8 o g = 10', 'Porque depende de dónde pongas el origen: 660 m si está en A, 600 m si está en B', 'Porque una es la posición y la otra la distancia recorrida por B', 'Porque uno de los dos resultados está mal'],
   c: 1,
   ex: 'La posición es una coordenada, y una coordenada <b>no significa nada sin origen</b>. Con el origen donde estaba A en t = 0, el encuentro es en x = 660 m; con el origen en B, en x = 600 m. Las dos son correctas, y por eso el enunciado exige "indique explícitamente los sistemas de referencia que adopta": sin declararlo, la respuesta es ambigua y te la pueden bajar. ▸ Por qué las otras: <b>g</b> no aparece en ningún lado de este problema: es movimiento horizontal. <b>La distancia recorrida por B</b> en 30 s es 600 m, es cierto, pero eso es coincidencia numérica con el otro origen, no la explicación. <b>Uno está mal</b>: no, es el mismo punto físico descripto desde dos orígenes distintos.'},

  {st: 'El inciso b) del parcial 2017 pide el gráfico esquemático x(t) de los dos autos. ¿Cómo son las curvas?',
   opts: ['Las dos rectas, cortándose en t = 30 s', 'B recta desde 60 m, A parábola desde el origen con pendiente inicial 10 m/s: se separan al principio y se cruzan una sola vez, en t = 30 s', 'B parábola y A recta', 'Las dos parábolas, porque los dos se mueven'],
   c: 1,
   ex: 'B tiene velocidad constante ⇒ x(t) es una <b>recta</b> de pendiente 20 m/s que arranca en 60 m. A tiene aceleración constante ⇒ x(t) es una <b>parábola</b> de concavidad positiva que arranca en el origen con pendiente inicial 10 m/s (más chica que la de B). Detalle que se corrige: al principio B se aleja todavía más, y el cruce es <b>único</b>, en (30 s ; 660 m). ▸ Por qué las otras: <b>Las dos rectas</b> es error conceptual: A acelera. <b>B parábola y A recta</b> está al revés. <b>Las dos parábolas</b> confunde moverse con acelerar: B se mueve, pero a velocidad constante.'},

  {st: 'Jimena perdió el colectivo por 15 minutos y sale a perseguirlo en moto desde el reposo (parcial FRBA 2023). ¿Cómo se escribe la posición del colectivo?',
   opts: ['x<sub>c</sub>(t) = 25·t, y el adelanto se suma al final', 'x<sub>c</sub>(t) = 25·(t + 900), con t = 0 cuando arranca la moto', 'x<sub>c</sub>(t) = 25·t − 900', 'x<sub>c</sub>(t) = 25·t + 15'],
   c: 1,
   ex: 'Con <b>un solo t = 0</b> para los dos (el instante en que arranca la moto), el colectivo ya lleva 900 s andando: en t = 0 está en 25·900 = 22.500 m y sigue a 25 m/s. Eso se escribe x<sub>c</sub> = 25·(t + 900) = 25t + 22.500. Igualando con x<sub>m</sub> = 0,04·t² sale t = 1125 s y x = 50.625 m. ▸ Por qué las otras: <b>Sumar el adelanto al final</b> no funciona: la ventaja es en <i>tiempo</i>, y hay que meterla adentro de la horaria. <b>25·t − 900</b> le resta 900 metros, mezclando unidades (900 es un tiempo en segundos, no una posición). <b>25·t + 15</b> usa los 15 minutos como si fueran metros; además hay que pasar 15 min a 900 s y 90 km/h a 25 m/s antes de operar.'},

  {st: 'Una flecha sale a 60° del suelo con v₀ = 15 m/s y da contra un árbol a los 2 s (parcial 2011). En ese instante, ¿la flecha está subiendo o bajando?',
   opts: ['Subiendo: todavía no llegó al punto más alto', 'Bajando: la altura máxima es a los 1,3 s', 'Justo en el punto más alto', 'Depende de la altura del árbol'],
   c: 1,
   ex: 'El tiempo de altura máxima es cuando v<sub>y</sub> = 0: t = v₀·sen60°/g = 15·0,866/10 = <b>1,3 s</b>. A los 2 s ya pasó ese instante, así que la flecha viene <b>bajando</b>, y por eso impacta a h = 5,98 m y no en el máximo. Es el dato que justifica el dibujo de la trayectoria. ▸ Por qué las otras: <b>Subiendo</b> saldría si el impacto fuera antes de 1,3 s. <b>En el punto más alto</b> pasaría solo si el tiempo dado coincidiera con 1,3 s. <b>Depende del árbol</b>: no — la altura de impacto es consecuencia del tiempo, no al revés; el árbol solo fija la coordenada horizontal (15 m), que es lo que te da v₀ = 15 m/s.'}
]);

registerReveals('fisica1-utn-dinamica', '3', [
  {st: '<b>A2:</b> Dos automóviles, A y B, se mueven en el mismo sentido por una ruta rectilínea, con velocidades constantes vA = 10 m/s y vB = 20 m/s, respectivamente. En determinado instante, B se encuentra 60 m delante de A. En ese momento, B no cambia su movimiento, pero A comienza a acelerar con aceleración constante aA, hasta alcanzar a B 30 segundos después.<br>a) Determine la posición a la que se produce el encuentro y el valor de aA.<br>b) Realice un gráfico esquemático de las posiciones de A y B en función del tiempo. <span class="muted">(1er parcial 2017, cátedra Martinelli, curso R1022, 26/6/2017)</span>',
   ans: 'a) x<sub>E</sub> = 660 m (medida desde donde estaba A en t = 0) y a<sub>A</sub> = 0,8 m/s² &nbsp;·&nbsp; b) recta para B, parábola para A, cruce único en (30 s ; 660 m)',
   sol: '<b>Sistema de referencia (declaralo, lo puntúan aparte).</b> t = 0 en el instante en que A empieza a acelerar. Eje x en el sentido del movimiento, con el <b>origen donde está A en t = 0</b>. Entonces x<sub>A</sub>(0) = 0 y x<sub>B</sub>(0) = +60 m (B está <i>delante</i>).<br><br><b>Paso 1 · Ecuaciones horarias.</b><br>(1) x<sub>A</sub>(t) = 10·t + ½·a<sub>A</sub>·t² &nbsp;(MRUV)<br>(2) x<sub>B</sub>(t) = 60 + 20·t &nbsp;(MRU)<br><br><b>Paso 2 · El atajo: el tiempo de encuentro ya es dato.</b> No hay que resolver ninguna cuadrática. Evaluá la ecuación más simple en t = 30 s:<br>x<sub>E</sub> = x<sub>B</sub>(30 s) = 60 + 20·30 ⇒ <b>x<sub>E</sub> = 660 m</b><br><br><b>Paso 3 · Ahora la aceleración.</b> Impongo que A esté en esa misma posición:<br>660 = 10·30 + ½·a<sub>A</sub>·(30)²<br>660 − 300 = 450·a<sub>A</sub> ⇒ 360 = 450·a<sub>A</sub><br>⇒ <b>a<sub>A</sub> = 0,8 m/s²</b><br><br><b>Paso 4 · Inciso b): el gráfico.</b> Lo que se corrige es:<br>• <b>B</b>: recta que arranca en 60 m con pendiente 20 m/s.<br>• <b>A</b>: parábola de concavidad positiva que arranca en el origen con pendiente inicial 10 m/s (empieza más plana que la de B y se va abriendo).<br>• Al principio <b>se separan</b> (B es más rápido); hay <b>un único cruce</b>, en (30 s ; 660 m); después A queda por encima.<br>Dibujar las dos como rectas es error conceptual.<br><br><b>Ojo con el origen.</b> Si ponés el origen en B, la posición del encuentro es 600 m. Las dos son correctas <b>si declarás cuál usaste</b>.'},

  {st: '<b>A2:</b> Se arroja una flecha desde el suelo, formando un ángulo de 60° con la dirección horizontal. La misma impacta 2s después, en un árbol que se encuentra 15m por delante del punto de lanzamiento. Determine:<br>a) El módulo de la velocidad inicial de la flecha.<br>b) La altura a la que impacta en el árbol. <span class="muted">(1er parcial 2011, cátedra Martinelli, 20/10/11)</span>',
   ans: 'a) v₀ = 15 m/s &nbsp;·&nbsp; b) h = 5,98 m (≈ 6 m)',
   sol: '<b>Sistema de referencia.</b> Origen en el punto de lanzamiento (x₀ = 0, y₀ = 0), eje y vertical hacia arriba, eje x horizontal hacia el árbol, t = 0 en el lanzamiento.<br><b>Hipótesis.</b> Tiro oblicuo sin resistencia del aire, aceleración constante (0, −g), g = 10 m/s².<br><br><b>Paso 1 · Ecuaciones horarias.</b><br>(1) x(t) = v₀·cos60°·t &nbsp;(v<sub>x</sub> es constante todo el vuelo)<br>(2) y(t) = v₀·sen60°·t − ½·g·t²<br>Dato: x(2 s) = 15 m.<br><br><b>Paso 2 · El tiempo lo manda el eje que tiene el dato.</b> Acá el dato está en la horizontal:<br>15 m = v₀·0,5·2 s = v₀·(1 s)<br>⇒ <b>v₀ = 15 m/s</b><br><br><b>Paso 3 · Inciso b): con v₀ voy a la vertical.</b><br>h = y(2 s) = 15·0,866·2 − 5·(2)² = 25,98 − 20<br>⇒ <b>h = 5,98 m</b> ≈ 6 m<br><br><b>Las trampas.</b> (1) La flecha <b>no llega al suelo</b>: choca contra el árbol, así que y(2 s) ≠ 0 y no sirve ninguna fórmula de alcance ni de tiempo de vuelo. (2) Los "15 m por delante" son la <b>coordenada horizontal</b>, no la distancia recorrida sobre la trayectoria (que es mayor). (3) sen60° = 0,866 y cos60° = 0,5, no al revés. (4) A los 2 s la flecha ya viene <b>bajando</b>: la altura máxima es a los t = v₀·sen60°/g = 1,3 s.'},

  {st: '<b>1.</b> Jimena ha llegado tarde a la estación y ha perdido el colectivo por 15 minutos. Sabe que la velocidad del colectivo es constante) de 90 km/h. Sale en su persecución con ayuda de la moto de una amiga, con la que partiendo del reposo consigue una aceleración de 0,08 m/s2. ¿Cuándo y dónde alcanzará al colectivo? <span class="muted">(1º parcial FRBA 2023, Tema A, Prof. Dibarbora. El paréntesis suelto después de "constante)" es una errata del enunciado original)</span>',
   ans: 't = 1125 s = 18 min 45 s después de que arranca la moto &nbsp;·&nbsp; x = 50.625 m = 50,6 km desde la estación',
   sol: '<b>Sistema de referencia.</b> Origen de posiciones: la estación. Origen de tiempos: t = 0 cuando <b>arranca la moto</b> (el colectivo ya lleva 900 s andando).<br><b>Conversión de unidades, primero.</b> 90 km/h = 25 m/s. 15 min = 900 s.<br><br><b>Paso 1 · Las dos horarias, con el adelanto ADENTRO.</b><br>Colectivo (MRU, ya venía andando):<br>(1) x<sub>c</sub>(t) = 25·(t + 900) = 25·t + 22.500 &nbsp;[m]<br>Moto (MRUV desde el reposo):<br>(2) x<sub>m</sub>(t) = ½·0,08·t² = 0,04·t² &nbsp;[m]<br><br><b>Paso 2 · Condición de encuentro.</b><br>0,04·t² = 25·t + 22.500<br>0,04·t² − 25·t − 22.500 = 0 &nbsp;→ dividiendo por 0,04 →&nbsp; t² − 625·t − 562.500 = 0<br>t = [625 ± √(390.625 + 2.250.000)]/2 = [625 ± √2.640.625]/2 = (625 ± 1625)/2<br>⇒ <b>t = 1125 s</b> (la raíz t = −500 s se descarta)<br>1125 s = <b>18 min 45 s</b> después de arrancar la moto, o 2025 s = 33 min 45 s después de que salió el colectivo.<br><br><b>Paso 3 · Dónde.</b><br>x = 0,04·(1125)² = 0,04·1.265.625 ⇒ <b>x = 50.625 m = 50,6 km</b><br>Control con el colectivo: 25·(1125 + 900) = 25·2025 = 50.625 m ✓<br><br><b>Comentario que conviene escribir.</b> Con ese dato la moto llega al encuentro a v = a·t = 0,08·1125 = 90 m/s = 324 km/h, físicamente absurdo: <b>la aceleración 0,08 m/s² es ridículamente chica</b> para una moto (parece un typo por 0,8 m/s²). Se resuelve con el dato tal como está dado y se aclara la incoherencia — eso suma, no resta. <span class="muted">(Si fuera 0,8 m/s²: t ≈ 270 s ≈ 4,5 min y x ≈ 29,3 km.)</span>'}
]);

/* ============================================================
   UNIDAD 4 · SISTEMAS NO INERCIALES (TEMA DE FINAL)
   ============================================================ */

registerExercises('fisica1-utn-dinamica', '4', [
  {st: 'Un disco apoyado sobre una plataforma giratoria da vueltas sin deslizar. Si resolvés el problema DESDE EL PISO del laboratorio, ¿qué fuerzas van en el DCL del disco?',
   opts: ['Peso, normal, rozamiento y fuerza centrífuga', 'Peso, normal y rozamiento estático apuntando hacia el centro', 'Peso, normal y fuerza centrípeta hacia el centro', 'Solo la fuerza centrípeta, que es la resultante'],
   c: 1,
   ex: 'El piso del laboratorio es un sistema <b>inercial</b>: van solo las fuerzas reales. Horizontalmente la única que hay es el <b>rozamiento estático</b>, apuntando hacia el centro, y es el que hace de fuerza centrípeta: μe·m·g = m·ω²·r. La aceleración centrípeta va del <b>otro lado</b> del igual. ▸ Por qué las otras: <b>La centrífuga</b> es una fuerza de inercia y solo aparece si te subís a la plataforma; ponerla en un DCL desde tierra y además igualar a m·a<sub>c</sub> te deja con 0 = 0. <b>"Fuerza centrípeta" como una fuerza más</b> es el error de nombre clásico: centrípeta no es una fuerza aparte, es el <i>rol</i> que cumple alguna de las reales. <b>Solo la centrípeta</b> se olvida del peso y la normal, que existen aunque se cancelen.'},

  {st: '¿Cuál es la descripción correcta de la fuerza de inercia?',
   opts: ['Vale m·a<sub>sist</sub>, va en el mismo sentido que la aceleración del sistema y tiene reacción', 'Vale m·a<sub>sist</sub>, va en sentido contrario a la aceleración del sistema y NO tiene reacción: nadie la ejerce', 'Vale m·g y siempre apunta hacia abajo', 'Existe en cualquier sistema de referencia, inercial o no'],
   c: 1,
   ex: 'F<sub>in</sub> = −m·a<sub>sist</sub>: misma dirección que la aceleración del sistema, <b>sentido contrario</b>, módulo m·a<sub>sist</sub>. Es la sensación de irte para atrás cuando el colectivo arranca. Es ficticia: no la ejerce ningún cuerpo, no tiene par de acción y reacción, y desaparece si volvés a mirar desde tierra. ▸ Por qué las otras: <b>Mismo sentido y con reacción</b> es exactamente al revés en las dos cosas. <b>m·g hacia abajo</b> es el peso, otra cosa. <b>En cualquier sistema</b> es falso por definición: en un sistema inercial vale ΣF = m·a con las fuerzas reales solas, y agregarle una F<sub>in</sub> sería contar de más.'},

  {st: 'Una cuña de 24 kg con la cara inclinada 37° es empujada horizontalmente por una fuerza F, sobre piso liso, con un bloque de 8 kg apoyado en su cara inclinada (final 12/12/23). Mientras el bloque no desliza, ¿cuánto vale la normal sobre el bloque?',
   opts: ['N = m₂·g·cos37° = 64 N, como en cualquier plano inclinado', 'N = m₂·(g·cos37° − a·sen37°): la aceleración horizontal la modifica', 'N = m₂·g = 80 N', 'N = (m₁ + m₂)·g·cos37°'],
   c: 1,
   ex: 'El bloque no está en equilibrio: acelera horizontalmente junto con la cuña, a = F/(m₁+m₂). Al proyectar ΣF = m·a sobre los ejes, la ecuación perpendicular al plano ya <b>no</b> da a = 0, y queda N = m₂·(g·cos37° − a·sen37°): cuanto más acelera el conjunto, <b>menos</b> aprieta el bloque contra la cara. Al mismo tiempo hace falta más rozamiento para sostenerlo. Los dos efectos van en contra y por eso existe una F máxima (acá, F = 10 N). ▸ Por qué las otras: <b>m₂·g·cos37°</b> es la fórmula del plano inclinado <i>en reposo o con el plano quieto</i>: acá el plano acelera. <b>m₂·g</b> es la normal en piso horizontal. <b>Con la masa total</b> mete la masa de la cuña en el contacto entre cuña y bloque, donde solo actúa el peso del bloque.'},

  {st: 'Un bloque de 20 kg apoyado sobre otro que adquiere una aceleración de 6,25 m/s² inclinada 37° POR DEBAJO de la horizontal (final 13/02/25). La superficie de contacto es horizontal. ¿Cuánto vale la normal entre los bloques?',
   opts: ['200 N, el peso del bloque de arriba', '125 N, porque N = m·(g − a·sen37°)', '275 N, porque N = m·(g + a·sen37°)', '160 N, porque N = m·g·cos37°'],
   c: 1,
   ex: 'El bloque de arriba acompaña al de abajo, así que <b>también acelera hacia abajo</b> con a·sen37° = 3,75 m/s². La ecuación vertical queda N − m·g = m·(−a·sen37°) ⇒ N = 20·(10 − 3,75) = <b>125 N</b>. El bloque "pesa menos" contra el otro, igual que vos en un ascensor que arranca a bajar. ▸ Por qué las otras: <b>200 N</b> = m·g valdría solo si la aceleración fuera puramente horizontal. <b>275 N</b> tiene el signo cambiado: sería si la aceleración apuntara hacia <i>arriba</i>. <b>m·g·cos37°</b> aplica la geometría del plano inclinado, pero acá la superficie de contacto es <b>horizontal</b> (lo inclinado es la aceleración, no el plano): la normal es vertical y el rozamiento horizontal.'},

  {st: 'Estás resolviendo desde el sistema acelerado y ya agregaste la fuerza de inercia F<sub>in</sub> = −m·a. ¿Qué escribís del lado derecho de la ecuación para un cuerpo que viaja pegado al sistema?',
   opts: ['m·a, la aceleración del sistema', 'Cero: con F<sub>in</sub> incluida el cuerpo está en equilibrio en ese sistema', 'm·a/2', 'Depende del rozamiento'],
   c: 1,
   ex: 'El sentido de la fuerza de inercia es justamente ese: <b>desde adentro</b> del sistema acelerado el cuerpo que viaja junto está <b>quieto</b>, así que ΣF + F<sub>in</sub> = 0 y el problema se vuelve una estática común. ▸ Por qué las otras: <b>m·a del lado derecho</b> es el error clásico: estarías contando la misma cosa dos veces (una como fuerza ficticia y otra como masa por aceleración). O ponés F<sub>in</sub> y escribís equilibrio, o no la ponés y escribís ΣF = m·a desde tierra — nunca las dos. <b>m·a/2</b> no sale de ningún lado. <b>Depende del rozamiento</b> confunde: el rozamiento es una fuerza más del miembro izquierdo, no cambia la estructura de la ecuación.'}
]);

registerReveals('fisica1-utn-dinamica', '4', [
  {st: '<b>4.</b> Un cuerpo en forma de cuña, de masa m₁ = 24 kg y ángulo de inclinación α = 37° respecto de la horizontal se encuentra en reposo sobre un plano horizontal sin rozamiento. Sobre el esta apoyado un bloque de masa m₂ = 8 kg que se mantiene en equilibrio debido al rozamiento con la cuña. Se aplica una fuerza horizontal de modulo F a la cuña, como indica la figura. Sabiendo que el coeficiente de rozamiento estático entre ambos cuerpos es μe = 0,8, halle el máximo valor de F para que el bloque no deslice respecto de la cuña. <span class="muted">(Final UTN.BA 12/12/23, problema 4. En la figura la cara inclinada asciende en el mismo sentido en que empuja F)</span>',
   ans: 'a<sub>máx</sub> = 0,3125 m/s² &nbsp;·&nbsp; <b>F<sub>máx</sub> = 10 N</b>',
   sol: '<b>Sistema de referencia.</b> Conviene resolver <b>desde tierra</b> (inercial): x horizontal positivo en el sentido de F, y vertical hacia arriba. sen37° = 0,6 · cos37° = 0,8.<br><b>Vínculo.</b> Mientras el bloque no desliza, los dos cuerpos tienen la <b>misma aceleración horizontal</b>:<br>(1) a = F / (m₁ + m₂) = F / 32 kg<br><br><b>Paso 1 · DCL del bloque m₂.</b> Tres fuerzas: peso m₂·g hacia abajo, normal N perpendicular a la cara inclinada y rozamiento f a lo largo de esa cara. Su aceleración es <b>horizontal</b>, de módulo a (no tiene componente vertical: no sube ni baja respecto del piso).<br><br><b>Paso 2 · Proyecto sobre horizontal y vertical.</b> Con la cara ascendiendo en el sentido de F, la normal apunta hacia arriba y hacia atrás, y el rozamiento (que sostiene al bloque) apunta hacia arriba de la cara:<br>x: −N·sen37° + f·cos37° = m₂·a<br>y: N·cos37° + f·sen37° − m₂·g = 0<br>Resolviendo el sistema de dos por dos:<br>(2) <b>N = m₂·(g·cos37° − a·sen37°)</b> &nbsp;← la normal <b>baja</b> cuando el conjunto acelera<br>(3) <b>f = m₂·(a·cos37° + g·sen37°)</b> &nbsp;← y el rozamiento necesario <b>sube</b><br>Los dos efectos van en contra: por eso hay un máximo.<br><br><b>Paso 3 · Condición de no deslizamiento.</b> f ≤ μe·N:<br>a·cos37° + g·sen37° ≤ μe·(g·cos37° − a·sen37°)<br>a·(cos37° + μe·sen37°) ≤ g·(μe·cos37° − sen37°)<br>a ≤ g·(0,8·0,8 − 0,6)/(0,8 + 0,8·0,6) = 10·(0,64 − 0,60)/1,28 = 0,4/1,28<br>⇒ <b>a<sub>máx</sub> = 0,3125 m/s²</b><br><br><b>Paso 4 · La fuerza.</b><br>F<sub>máx</sub> = (m₁ + m₂)·a<sub>máx</sub> = 32 kg · 0,3125 m/s² ⇒ <b>F<sub>máx</sub> = 10 N</b><br><br><b>Por qué da tan chico.</b> Mirá el numerador: μe·cos37° − sen37° = 0,64 − 0,60 = 0,04. Es decir, μe = 0,8 apenas supera tg37° = 0,75: con la cuña quieta el bloque ya está <b>casi</b> al borde de resbalar, y basta una aceleración mínima para tirarlo. Si te da un número raro, ese es el control: verificá si μe está apenas por encima de tgα.<br><br><b>La misma cuenta desde la cuña.</b> Agregando F<sub>in</sub> = m₂·a hacia atrás, el bloque queda en equilibrio sobre un plano inclinado y sale idéntico. Elegí una lectura y no las mezcles.'},

  {st: '<b>5.</b> Un pequeño disco se deposita sobre una plataforma giratoria a una distancia r = 10 cm de su eje de rotación. El coeficiente de rozamiento estático entre el disco y la plataforma es μe = 0,4. Calcule el máximo valor de la frecuencia de rotación de la plataforma para el cual el disco no desliza respecto de ella. <span class="muted">(Final UTN.BA 12/12/23, problema 5)</span>',
   ans: 'ω<sub>máx</sub> = 6,32 rad/s &nbsp;·&nbsp; <b>f<sub>máx</sub> ≈ 1,01 Hz</b> (≈ 1 vuelta por segundo, ≈ 60 rpm)',
   sol: '<b>Sistema de referencia.</b> Desde tierra (inercial), con la dirección radial positiva <b>hacia el centro</b> y la vertical hacia arriba. Pasá las unidades primero: r = 10 cm = <b>0,1 m</b>.<br><br><b>Paso 1 · DCL del disco: tres fuerzas y ninguna centrífuga.</b><br>• Peso m·g hacia abajo.<br>• Normal N hacia arriba.<br>• Rozamiento <b>estático</b> f<sub>e</sub>, horizontal y apuntando <b>hacia el centro</b>. Es la <b>única</b> fuerza horizontal, así que es la que hace de fuerza centrípeta.<br><br><b>Paso 2 · Ecuaciones.</b><br>Vertical: N − m·g = 0 ⇒ N = m·g<br>Radial: f<sub>e</sub> = m·a<sub>c</sub> = m·ω²·r<br><br><b>Paso 3 · El caso límite.</b> "Máximo valor de la frecuencia" ⇒ el rozamiento estático está en su techo:<br>μe·m·g = m·ω²·r &nbsp;→ la masa se cancela (no te la dan, y no hace falta)<br>ω² = μe·g/r = 0,4 · 10 / 0,1 = 40 s<sup>−2</sup><br>⇒ <b>ω<sub>máx</sub> = √40 = 6,32 rad/s</b><br><br><b>Paso 4 · De ω a frecuencia.</b> Te piden la <b>frecuencia</b>, no la velocidad angular:<br>f = ω/(2π) = 6,32 / 6,283<br>⇒ <b>f<sub>máx</sub> = 1,01 Hz</b> ≈ 1 vuelta por segundo ≈ 60 rpm<br><br><b>Los dos errores de este ejercicio.</b> (1) Dejar r en centímetros: te da un ω diez veces más grande. (2) Contestar 6,32 y no dividir por 2π: te preguntan frecuencia. Y por supuesto, (3) meter una "fuerza centrífuga" en el DCL desde tierra: no existe ahí.'},

  {st: '<b>3.</b> Sobre un piso horizontal sin rozamiento desliza, con aceleración a, una plataforma que posee una polea ideal fija a la misma. Dos cuerpos, de masas iguales m1 = m2 = m se encuentran ligados por una cuerda ideal que pasa por la polea, dispuestos como indica la figura. El coeficiente de rozamiento estático entre el cuerpo 1 y la plataforma es µe = 0,5 y no existe rozamiento entre el cuerpo 2 y la pared frontal de la plataforma. Calcule el valor máximo de la aceleración a para que el cuerpo 1 no deslice hacia atrás respecto de la plataforma. <span class="muted">(Final UTN.BA, hoja impresa en LaTeX sin encabezado: no se puede fechar. El cuerpo 1 va arriba de la plataforma, la cuerda pasa por la polea del borde y baja hasta el cuerpo 2, apoyado contra la pared frontal)</span>',
   ans: '<b>a<sub>máx</sub> = g·(1 + μe) = 15 m/s²</b> &nbsp;·&nbsp; no depende de m',
   sol: '<b>Sistema de referencia.</b> Desde tierra (inercial): x horizontal positivo en el sentido de a, y vertical hacia arriba. Los dos cuerpos viajan con la plataforma, así que su aceleración es <b>a horizontal</b>.<br><br><b>Paso 1 · Empezá por el cuerpo 2, que es el que regala una ecuación.</b> Cuelga del ramal vertical de la cuerda y apoya contra la pared frontal, que es <b>lisa</b>. Sus fuerzas: T hacia arriba, peso m·g hacia abajo, normal de la pared N<sub>p</sub> horizontal.<br>En y: T − m·g = m·a<sub>y</sub> = 0 &nbsp;(no sube ni baja: viaja con la plataforma)<br>⇒ <b>T = m·g</b><br>En x: N<sub>p</sub> = m·a &nbsp;(la pared es la que lo arrastra hacia adelante)<br><br><b>Paso 2 · Cuerpo 1, arriba de la plataforma.</b> Fuerzas horizontales: la tensión T tirando <b>hacia adelante</b> (la cuerda va horizontal hacia la polea del borde) y el rozamiento f.<br>En y: N = m·g<br>En x: T + f = m·a ⇒ <b>f = m·a − m·g = m·(a − g)</b><br><br><b>Paso 3 · Leé el signo.</b> Si a &gt; g, f sale positiva: el rozamiento tiene que empujar <b>hacia adelante</b> porque la tensión sola no alcanza para arrastrar al cuerpo 1, y el cuerpo tiende a quedarse atrás. Ese es exactamente el caso que te preguntan ("que no deslice hacia atrás").<br><br><b>Paso 4 · Condición límite.</b> f ≤ μe·N = μe·m·g:<br>m·(a − g) ≤ μe·m·g &nbsp;→ la masa se cancela<br>a ≤ g·(1 + μe) = 10·(1 + 0,5)<br>⇒ <b>a<sub>máx</sub> = 15 m/s²</b><br><br><b>Dato de regalo.</b> El resultado <b>no depende de m</b>: por eso el enunciado se limita a decir m₁ = m₂ = m sin darte ningún número. Y si te interesa el otro extremo: para que tampoco deslice hacia <i>adelante</i> hace falta a ≥ g·(1 − μe) = 5 m/s².<br><br><b>Desde la plataforma.</b> Agregando F<sub>in</sub> = m·a hacia atrás sobre cada cuerpo, los dos quedan en equilibrio y sale lo mismo. La ventaja de resolverlo desde tierra es que no hay ningún signo que se te pueda dar vuelta.'},

  {st: '<b>4.</b> Un bloque 1 de masa m1 = 20 kg se encuentra apoyado sobre otro bloque 2 horizontal. En cierto instante, el bloque 2 adquiere una aceleración a inclinada un ángulo α = 37° respecto de la horizontal (hacia abajo y hacia adelante), como indica la figura. Los coeficientes de rozamiento estático y cinético entre el bloque 1 y el 2 son respectivamente μe = 0,8 y μc = 0,5.<br>a) Calcule el máximo valor de a para que el bloque 1 no deslice respecto del 2.<br>b) Suponiendo ahora que a = 12 m/s², calcule la componente horizontal de la aceleración del bloque 1 y el valor de la fuerza normal de contacto entre ambos bloques. <span class="muted">(Final UTN.BA 13/02/25, problema 4. Enunciado reconstruido de memoria por alumnos: el original no circuló, y en esa reconstrucción el inciso b) figura tachado — igual conviene saberlo hacer)</span>',
   ans: 'a) <b>a<sub>máx</sub> = 6,25 m/s²</b> &nbsp;·&nbsp; b) a<sub>1x</sub> = 1,4 m/s² y N = 56 N',
   sol: '<b>Sistema de referencia.</b> Desde tierra: x horizontal positivo hacia adelante, y vertical hacia arriba. <b>La superficie de contacto entre los bloques sigue siendo HORIZONTAL</b> (lo inclinado es la aceleración, no el plano): la normal es vertical y el rozamiento horizontal. sen37° = 0,6 · cos37° = 0,8.<br><br><b>Paso 1 · Inciso a): si no desliza, viaja con el 2.</b> Entonces el bloque 1 tiene la misma aceleración: componentes (a·cos37° ; −a·sen37°) = (0,8·a ; −0,6·a).<br>En y: N − m₁·g = m₁·(−a·sen37°)<br>⇒ <b>N = m₁·(g − a·sen37°)</b> &nbsp;← la normal <b>baja</b> (el bloque acompaña una caída parcial)<br>En x: f = m₁·a·cos37° &nbsp;← y el rozamiento necesario <b>crece</b><br>Otra vez los dos efectos en contra.<br><br><b>Paso 2 · Condición límite f ≤ μe·N.</b><br>m₁·0,8·a ≤ 0,8·m₁·(10 − 0,6·a) &nbsp;→ m₁ se cancela<br>0,8·a ≤ 8 − 0,48·a ⇒ 1,28·a ≤ 8<br>⇒ <b>a<sub>máx</sub> = 6,25 m/s²</b><br>(Con ese valor: N = 20·(10 − 3,75) = 125 N y f = 20·5 = 100 N = 0,8·125 ✓)<br><br><b>Paso 3 · Inciso b): con a = 12 m/s² ya desliza.</b> Ahora el bloque 1 <b>no</b> acompaña la componente horizontal, pero <b>sí</b> la vertical: mientras siga apoyado, baja junto con la superficie.<br>a<sub>1y</sub> = −a·sen37° = −7,2 m/s² &nbsp;(menor que g en módulo, así que no se despega ✓)<br>En y: N = m₁·(g − 7,2) = 20 · 2,8 ⇒ <b>N = 56 N</b><br><br><b>Paso 4 · La aceleración horizontal.</b> Hay deslizamiento relativo (el bloque 2 se le escapa hacia adelante), así que el rozamiento es <b>cinético</b> y arrastra al bloque 1 hacia adelante:<br>f = μc·N = 0,5 · 56 N = 28 N = m₁·a<sub>1x</sub><br>⇒ <b>a<sub>1x</sub> = 28/20 = 1,4 m/s²</b><br><br><b>La misma lógica que el plato del mozo.</b> Por más que el bloque 2 acelere a 12 m/s², la componente horizontal del 1 queda <b>fijada</b> por el rozamiento cinético en 1,4 m/s². Cambian los números, no el razonamiento.'}
]);
