// ==========================================================================
// ALGORITMOS Y PROGRAMACIÓN I (TB021 / TA130) · PARCIAL E INTEGRADOR
// FIUBA · Cátedra Azcurra · Lenguaje C
// Guía hija de 'fiuba-algoritmos'.
//
// La cátedra NO publica enunciados de parcial (verificado en el campus el
// 19/8/2026: los archivos de "Notas" son planillas de calificaciones).
// Lo que hay son 12 tareas del campus, 9 con enunciado completo y 3 sin.
// Secciones 3 y 4 = esas consignas, verbatim.
// Secciones 6 y 7 = simulacros propios, marcados como tales.
// Todos los programas fueron compilados con MSVC 2022 y ejecutados: las
// salidas que aparecen en la guía son las reales.
// ==========================================================================

/* ============ SECCIÓN 1 · Qué se sabe del examen y qué no ============ */

registerExercises('fiuba-algoritmos-parcial', '1', [
  {st: 'En la sección "Notas" del campus hay un archivo llamado "Parcial 1er Cuat 2026". ¿Qué contiene?',
   opts: ['El enunciado del parcial de ese cuatrimestre', 'Una planilla de calificaciones exportada de Excel, con padrones y notas', 'El parcial resuelto por la cátedra', 'Las pautas de corrección'],
   c: 1,
   ex: 'Lo abrimos el 19/8/2026: es una <b>planilla de notas</b>, no un examen. Y lo mismo los otros seis archivos de esa sección (los dos recuperatorios y los cuatro integradores). ▸ La consecuencia es incómoda pero hay que decirla: <b>no existe un corpus de parciales de esta cátedra</b>, así que ninguna guía puede decirte qué tema cae en qué posición. ▸ Y la consecuencia práctica: si alguien te pasa un "parcial de Azcurra", <b>no salió del campus</b>. Usalo como práctica si querés, pero no como palabra de la cátedra.'},

  {st: 'De las 12 tareas entregables del campus, ¿cuántas traen el enunciado escrito?',
   opts: ['Las 12', '9 de 12: faltan Struct Alumno, Ejercicio Recursividad y TDA Número Complejo', '6 de 12', 'Sólo las dos "Tipo Parcial"'],
   c: 1,
   ex: 'Las contamos una por una. <b>Nueve</b> traen consigna completa. <b>Tres no</b>: "Struct Alumno" sólo indica el nombre del archivo a entregar, "Ejercicio Recursividad" trae únicamente el texto administrativo, y el cuerpo del enunciado de "TDA Número Complejo" es <b>la letra E</b> y nada más. ▸ En esta guía las tres están resueltas igual, pero con el enunciado marcado como propio. Si te toca entregarlas, <b>pedí la consigna en clase</b>: el alcance lo define la cátedra, no nosotros.'},

  {st: 'Las dos tareas "Tipo Parcial" se abrieron el 4/5/2026; las de struct, el 27/5. ¿Qué se puede inferir de eso?',
   opts: ['Nada, las fechas de apertura son arbitrarias', 'Que el parcial se juega en funciones, arreglos y cadenas, y que struct, archivos, recursividad y memoria dinámica caen del lado del integrador', 'Que el parcial incluye structs porque se dictan antes', 'Que las tareas de struct son las que se toman en el parcial'],
   c: 1,
   ex: 'Los dos ejercicios que la cátedra bautizó "Tipo Parcial" son de <b>vectores</b> y de <b>funciones con parámetros de salida</b>, y se abrieron <b>tres semanas antes</b> de que se dictaran structs y archivos. Ninguno de los dos usa struct, archivo, recursión ni memoria dinámica. ▸ Es una <b>inferencia sobre las fechas</b>, no una afirmación de la cátedra, y así está dicha en la guía. Pero es la inferencia que ordena el estudio, y por eso esta guía tiene dos simulacros distintos: uno de parcial y uno de integrador.'},

  {st: 'Cinco tareas del campus tienen apertura y cierre el mismo día. ¿Cuánto dura la ventana en tres de ellas?',
   opts: ['2 horas', 'Exactamente 25 minutos', '10 minutos', 'Toda la clase'],
   c: 1,
   ex: 'Factorial (17:40 a 18:05), Recorriendo tu nombre y apellido (17:20 a 17:45) y Mostrando palabras en orden (18:20 a 18:45): <b>25 minutos clavados</b> las tres. La de archivos son 27 y la de timestamp 45. ▸ Es el dato de tiempo más accionable que publica la cátedra: en 25 minutos hay que <b>leer, escribir la función, escribir el main, compilar, probar y entregar</b>. No hay margen para diseñar desde cero, sólo para reconocer el patrón y ejecutarlo. ▸ Por eso los simulacros de esta guía están cronometrados con ese número.'},

  {st: 'Hay cuatro planillas de "Integrador" con fechas 01-07, 29-07, 05-08 y 14-08 de 2026. ¿Qué se deduce y qué no?',
   opts: ['Que hay cuatro integradores obligatorios y hay que rendir los cuatro', 'Que existen integradores con fechas propias repartidas en seis semanas; cuántas veces podés presentarte NO está publicado', 'Que el integrador reemplaza al parcial', 'Que los integradores son opcionales'],
   c: 1,
   ex: 'De los nombres se deduce <b>que existen</b> y <b>cuándo se rindieron</b>: cuatro fechas en seis semanas, separadas por 4 semanas, 1 semana y 9 días. Eso se parece más a una <b>instancia con varios llamados</b> que a un examen único. ▸ Lo que <b>no</b> está publicado, y por lo tanto no se afirma en esta guía: cuántas veces podés presentarte, cuánto pesa en la nota, si es obligatorio para todos. Preguntalo en clase. ▸ Inventar esos datos sería lo mismo que hacen las guías que dicen qué tema cae en el parcial.'},

  {st: 'Estás preparando el parcial y tenés la guía con todos los programas resueltos y compilados. ¿Cuál es el método correcto?',
   opts: ['Leer las soluciones con atención hasta entenderlas todas', 'Escribir cada programa vos primero, aunque no compile, y recién después comparar contra la solución', 'Copiar los programas a mano para memorizarlos', 'Leer sólo las trampas, que es lo que se toma'],
   c: 1,
   ex: 'Leer código <b>no</b> es programar: la sensación de "esto lo entiendo" dura hasta que estás con la hoja en blanco y 25 minutos. ▸ El valor de una guía de programas resueltos está en el <b>diff</b> entre lo tuyo y lo de acá — qué caso borde no probaste, qué firma pusiste mal, dónde te faltó el puntero. Ese diff no existe si no escribiste nada. ▸ Copiar a mano tampoco: reproduce el texto sin reproducir las decisiones.'},
]);

/* ============ SECCIÓN 2 · Formato de entrega y auditoría de estilo ============ */

registerReveals('fiuba-algoritmos-parcial', '2', [

{st: 'Auditá este fragmento contra la convención de la cátedra y reescribilo. Hay <b>siete</b> violaciones distintas.<pre class="code-block">#define tamMax 20<br>int BuscarMayor(int V[],int N){<br>int m=V[0];<br>for(int i=1;i&lt;N;i++)<br>{<br>if(V[i]&gt;m){m=V[i];}<br>}<br>return m;}</pre>',
 ans: 'Constante en minúscula/camelCase, nombre de función en PascalCase, nombres de variables no descriptivos, falta de espacios después de las palabras reservadas y alrededor de los operadores, llave de la función al final del renglón en vez de la primera columna, llave del for en su propia línea (al revés de lo que corresponde), y llaves innecesarias en un if de una sola sentencia.',
 sol: '<b>Las siete, una por una.</b> ▸ <b>1.</b> <span class="code">#define tamMax 20</span> → las constantes van en <b>MAYÚSCULA con guión bajo</b>: <span class="code">#define TAM_MAX 20</span>. ▸ <b>2.</b> <span class="code">BuscarMayor</span> es PascalCase → snake_case: <span class="code">buscar_mayor</span>. ▸ <b>3.</b> <span class="code">V</span>, <span class="code">N</span>, <span class="code">m</span> no describen nada → <span class="code">vector</span>, <span class="code">cantidad</span>, <span class="code">mayor</span> (la excepción de nombre corto es sólo <span class="code">i</span>, <span class="code">j</span> como índices). ▸ <b>4.</b> Faltan espacios después de <span class="code">for</span> e <span class="code">if</span>, y a cada lado de <span class="code">= &lt; &gt;</span>. ▸ <b>5.</b> La llave de <b>la función</b> va en la primera columna, en su propia línea; acá está pegada al final del renglón. ▸ <b>6.</b> La llave del <b>for</b> va al final del renglón; acá está en su propia línea. Es exactamente al revés en los dos casos: <b>la función es el caso especial</b>. ▸ <b>7.</b> El <span class="code">if</span> ejecuta una sola sentencia: la cátedra dice textual que <i>"es conveniente omitir las llaves si una sola sentencia será ejecutada"</i>. ▸ <b>Bonus que no es de estilo pero es un bug:</b> declarar <span class="code">int i</span> dentro del <span class="code">for</span> es C99 y la cátedra escribe las declaraciones al principio del bloque. ▸ <b>Resultado:</b><pre class="code-block">#define TAM_MAX 20<br><br>/* Devuelve el mayor de las primeras cantidad posiciones del vector. */<br>int buscar_mayor(const int vector[], int cantidad)<br>{<br>    int mayor = vector[0];<br>    int i;<br><br>    for (i = 1; i &lt; cantidad; i++) {<br>        if (vector[i] &gt; mayor)<br>            mayor = vector[i];<br>    }<br>    return mayor;<br>}</pre>'},

{st: 'Terminaste el "Ejercicio Tipo Parcial 02" y estás por subirlo. Tu padrón es 108456. Enumerá todo lo que tenés que verificar <b>antes</b> de tocar el botón de entregar.',
 ans: 'Nombre del archivo actividad-02-108456.c exacto; compilación sin warnings; los 12 puntos de la auditoría de estilo; que el .c incluya la función Y el main que la invoca; que el main pruebe casos borde; y tener presente que sólo hay 2 intentos.',
 sol: '<b>El orden importa, porque los primeros son los que te dejan sin entrega.</b> ▸ <b>1 · El nombre.</b> <span class="code">actividad-02-108456.c</span>: guiones, minúsculas, tu padrón, extensión <span class="code">.c</span>. La cátedra da el ejemplo <span class="code">actividad-02-101203.c</span>, así que no hay margen de interpretación. ▸ <b>2 · Compila sin warnings.</b> No alcanza con "compila": un warning de conversión de tipos es un bug esperando. Con gcc, <span class="code">gcc -Wall -g actividad-02-108456.c -o prueba.exe</span>. ▸ <b>3 · Los 12 controles de estilo</b> de la sección 2, que son tres minutos. ▸ <b>4 · La función <i>y</i> el programa.</b> El enunciado termina con <i>"Escribir un programa que invoque dicha funcion"</i>: entregar la función sola es media entrega. ▸ <b>5 · Los casos borde en el main.</b> Insertar al principio, al medio, al final, un repetido, y el vector lleno para ver el <span class="code">false</span>. Un main que prueba un solo caso feliz no demuestra nada. ▸ <b>6 · Los dos intentos.</b> El campus dice <i>"Este es el intento 1 (2 intentos permitidos)"</i>. Nunca subas para ver si anda.'},

]);

registerExercises('fiuba-algoritmos-parcial', '2', [
  {st: 'La cátedra adopta para el curso las características principales de una convención concreta. ¿Cuál, y qué implica para las llaves?',
   opts: ['GNU coding standard: todas las llaves en su propia línea', 'Linux kernel coding style: la llave de las funciones va en la primera columna y la del resto (if, for, while, do, switch) al final del renglón', 'K&R puro: todas las llaves al final del renglón', 'Ninguna en particular, cada uno elige'],
   c: 1,
   ex: 'El documento de la cátedra lo dice textual: adopta <b>las características principales del Linux kernel coding style</b>, que es una variante de la de Kernighan y Ritchie. ▸ Y de ahí sale la regla que más se lleva mal: <b>hay dos casos</b>. La <b>función</b> es el especial —llave de apertura en la primera columna, en su propia línea— y todo el resto va al final del renglón. ▸ Poner todas al final es K&R puro, no lo que adoptó la cátedra. Poner todas en su propia línea es el estilo Allman, que tampoco.'},

  {st: 'Un programa calcula el promedio de {8, 6, 10, 4, 9} y muestra "Promedio: 7". La función está declarada <span class="code">int CalcularPromedio(float V[],int N)</span> y devuelve <span class="code">s/N</span> con <span class="code">s</span> float. ¿Qué pasó?',
   opts: ['El promedio es 7, está bien', 'El tipo de retorno es int: la expresión float 7.4 se trunca a 7. El compilador lo avisa con un warning de conversión, pero compila igual', 'Falta un printf con %f', 'El vector está mal inicializado'],
   c: 1,
   ex: 'El promedio real es <b>7,4</b>. La función devuelve <span class="code">int</span>, así que 7.4 se trunca a 7 al salir. MSVC lo avisa: <span class="code">warning C4244: return: conversion de float a int; posible perdida de datos</span>. ▸ Lo interesante es <b>por qué el bug es difícil de ver</b>: con la función escrita en una sola línea pegada a la llave y llamada <span class="code">CalcularPromedio</span> con parámetros <span class="code">V</span> y <span class="code">N</span>, el <span class="code">int</span> no chirría. Escrita con la convención —prototipo en su renglón, comentario que dice qué devuelve, variable <span class="code">promedio</span>— el <span class="code">int</span> salta a la vista. ▸ El estilo de la cátedra declara entre sus propósitos <i>"simplificar la detección de errores"</i>, y éste es el ejemplo.'},

  {st: '¿Cuál de estas líneas cumple las tres reglas de espaciado de la cátedra a la vez?',
   opts: ['<span class="code">for(i=0;i&lt;n;i++){</span>', '<span class="code">for (i = 0; i &lt; n; i++) {</span>', '<span class="code">for (i = 0; i &lt; n; i ++) {</span>', '<span class="code">for(i = 0; i &lt; n; i++){</span>'],
   c: 1,
   ex: 'Tres reglas cerradas y literales del documento: <b>espacio siempre después</b> de <span class="code">if switch case for do while</span>; <b>espacio a cada lado</b> de <span class="code">= + - &lt; &gt; * / % || &amp;&amp; ^ &lt;= &gt;= == !=</span>; y <b>nunca espacio</b> en pre/post incremento y decremento. ▸ La primera y la cuarta violan la del espacio después de <span class="code">for</span>. ▸ La tercera pone espacio en <span class="code">i ++</span>, que es exactamente lo que la regla prohíbe. ▸ Y fijate qué <b>no</b> está en la lista de operadores: la coma, el punto y coma, el <span class="code">!</span> unario y el <span class="code">&amp;</span> de dirección. Por eso <span class="code">scanf("%d", &amp;edad);</span> se escribe así.'},

  {st: 'Tu programa necesita un arreglo cuyo tamaño se conoce recién en ejecución. Escribís <span class="code">int vector[n];</span> con n leído por teclado. ¿Qué pasa?',
   opts: ['Anda en todos los compiladores', 'Compila con gcc pero MSVC lo rechaza con "se esperaba una expresión constante"; la salida de esta materia es malloc, o un arreglo de tamaño MAX con máximo lógico', 'Es un error de sintaxis siempre', 'Anda pero pierde memoria'],
   c: 1,
   ex: 'Lo probamos: MSVC devuelve <span class="code">error C2057: se esperaba una expresion constante</span> más dos errores más. Los arreglos de tamaño variable son C99 y MSVC no los soporta. ▸ Y no es un problema sólo de portabilidad: si tu entrega se compila con un compilador distinto al tuyo, no compila, y una entrega que no compila no se corrige. ▸ Las dos salidas correctas: si el tamaño se conoce recién en ejecución, <b>memoria dinámica</b> con <span class="code">malloc</span>; si hay una cota conocida, <b>arreglo de tamaño MAX más máximo lógico</b>, que es lo que hace la propia cátedra en el Tipo Parcial 02.'},

  {st: 'El ejercicio "Cargar Alumnos" pide subir el código. ¿Alcanza con eso?',
   opts: ['Sí, el código es la entrega', 'No: la consigna pide además subir el archivo alumnos.dat generado, con al menos 5 alumnos', 'No: hay que subir también un informe', 'Sí, pero en formato .cpp'],
   c: 1,
   ex: 'Textual de la consigna: <i>"Deberá subir el archivo generado, con al menos 5 datos de alumnos"</i>, y más abajo lo repite: <i>"Además, subí el archivo generado alumnos.dat, con al menos 5 alumnos"</i>. ▸ Es la única de las 12 tareas que pide <b>dos</b> archivos, y la razón es buena: el <span class="code">.dat</span> demuestra que el programa <b>corrió</b>, no sólo que compila. ▸ Detalle práctico: el archivo aparece en el directorio desde donde ejecutás el programa, que con un IDE no siempre es la carpeta del <span class="code">.c</span>.'},

  {st: 'Estás por subir una entrega y no compilaste. Pensás "subo y si está mal lo arreglo". ¿Qué tiene de malo?',
   opts: ['Nada, se puede subir infinitas veces', 'El campus permite 2 intentos: si el primero no compila, te queda uno solo para todo el resto', 'Hay que avisar al docente antes de subir', 'El campus no acepta archivos que no compilen'],
   c: 1,
   ex: 'El campus lo dice en cada tarea: <i>"Este es el intento 1 (2 intentos permitidos)"</i>. ▸ El segundo intento existe para arreglar algo puntual que descubriste tarde, no para descubrir que el programa no compila. Quemarlo en eso te deja sin red. ▸ Y el costo de evitarlo es de treinta segundos: <span class="code">gcc -Wall -g archivo.c -o prueba.exe</span> y correr el ejecutable una vez.'},
]);

/* ============ SECCIÓN 3 · Los dos "Tipo Parcial" ============ */

registerReveals('fiuba-algoritmos-parcial', '3', [

{st: '<b>Variante del Tipo Parcial 02.</b> El mismo enunciado, pero ahora el vector está cargado en <b>orden DESCENDENTE</b>. ¿Qué cambia en la función <span class="code">intercalar</span>?',
 ans: 'Una sola cosa: la comparación del while pasa de <span class="code">vec[i] &gt; valor</span> a <span class="code">vec[i] &lt; valor</span>. Todo lo demás —la dirección del recorrido, el corrimiento, el vec[i+1] = valor, el ++(*max_logico), la guarda del vector lleno— queda idéntico.',
 sol: 'La lógica del recorrido de atrás hacia adelante <b>no depende del sentido del orden</b>: depende de que corrés hacia posiciones ya visitadas. Lo único específico del orden ascendente es la pregunta "¿este elemento tiene que quedar <b>después</b> del nuevo?". ▸ Con orden ascendente, un elemento va después del nuevo si es <b>mayor</b>. Con orden descendente, si es <b>menor</b>. Un carácter. ▸ <b>El chequeo de que lo entendiste:</b> probá con <span class="code">[21, 13, 8, 5, 2]</span> insertando el 10. El <span class="code">while</span> corre el 8 (menor que 10) y el 5 y el 2, y se detiene en el 13. Queda <span class="code">[21, 13, 10, 8, 5, 2]</span>. ▸ Y el mismo razonamiento resuelve la variante "vector de structs ordenado por apellido": la comparación pasa a ser <span class="code">strcmp(vec[i].ape_nom, nuevo.ape_nom) &gt; 0</span>. La estructura no se toca.'},

{st: '<b>Variante del Tipo Parcial 02.</b> Ahora se pide que <b>no se inserte</b> el valor si ya está en el vector, devolviendo <span class="code">false</span> en ese caso. Seguís teniendo una sola pasada y sin arreglo auxiliar. ¿Cómo lo resolvés?',
 ans: 'Se agrega la detección del duplicado dentro del mismo recorrido: cuando el while corta, el candidato a igual es vec[i]. Si i >= 0 y vec[i] == valor, hay que deshacer los corrimientos y devolver false.',
 sol: 'La trampa es que el recorrido de atrás hacia adelante <b>ya movió elementos</b> cuando descubre el duplicado, así que no alcanza con devolver <span class="code">false</span>: hay que dejar el vector como estaba. ▸ <b>Dos soluciones válidas.</b> ▸ <b>A · Deshacer.</b> Al cortar el <span class="code">while</span>, si <span class="code">i &gt;= 0 &amp;&amp; vec[i] == valor</span>, recorrés hacia adelante devolviendo cada elemento a su lugar (<span class="code">vec[j] = vec[j + 1]</span>) y devolvés <span class="code">false</span>. Cumple "una sola pasada" en el caso exitoso, pero en el caso de duplicado toca las mismas posiciones dos veces. ▸ <b>B · Preguntar antes de mover.</b> Reescribís el ciclo para que compare primero y recién mueva si el elemento es estrictamente mayor:<pre class="code-block">i = *max_logico - 1;<br>while (i &gt;= 0 &amp;&amp; vec[i] &gt; valor)<br>    --i;              /* solo busco, todavia no muevo */<br>if (i &gt;= 0 &amp;&amp; vec[i] == valor)<br>    return false;     /* duplicado: no toque nada */</pre>…pero eso vuelve a ser <b>dos pasadas</b>. ▸ <b>La respuesta correcta es la A</b>, y la conclusión conceptual vale para todo el parcial: cuando una función modifica y además puede fallar, <b>el diseño tiene que garantizar que el fracaso no deje el dato a medio modificar</b>. En este ejercicio eso significa poder deshacer.'},

{st: '<b>Variante del Tipo Parcial 03.</b> Escribir una función que reciba un entero y devuelva por parámetro <b>la suma de sus dígitos impares</b> y <b>el número dado vuelta</b>. Sin arreglos, en un solo recorrido de los dígitos.',
 ans: 'Un solo do-while que pela dígitos y hace las dos cosas a la vez: si el dígito es impar lo suma, y siempre lo agrega al invertido con invertido = invertido * 10 + digito.',
 sol: '<b>El molde es el mismo</b>, y ése es todo el punto: <span class="code">do { digito = n % 10; … n = n / 10; } while (n &gt; 0);</span> con dos acumuladores en vez de uno.<pre class="code-block">void procesar(int numero, int *suma_impares, int *invertido)<br>{<br>    int digito;<br><br>    if (numero &lt; 0)<br>        numero = -numero;<br><br>    *suma_impares = 0;<br>    *invertido = 0;<br>    do {<br>        digito = numero % 10;<br>        if (digito % 2 != 0)<br>            *suma_impares = *suma_impares + digito;<br>        *invertido = *invertido * 10 + digito;<br>        numero = numero / 10;<br>    } while (numero &gt; 0);<br>}</pre>▸ <b>Por qué el invertido sale gratis:</b> el ciclo pela los dígitos <b>de derecha a izquierda</b>, que es exactamente el orden en que hay que <b>armarlos</b> para el número dado vuelta. ▸ <b>El caso que hay que probar:</b> un número terminado en 0, como 1230. El invertido da 321, no 0321, porque los ceros a la izquierda no existen en un entero. Eso no es un bug, es aritmética, pero conviene mencionarlo en un comentario. ▸ <b>Y el acumulador correcto:</b> la suma arranca en <b>0</b>, el producto arrancaría en <b>1</b>. Confundirlos es el error más común de este molde.'},

]);

registerExercises('fiuba-algoritmos-parcial', '3', [
  {st: 'En el Tipo Parcial 02, ¿por qué hay que recorrer el vector de atrás hacia adelante y no al revés?',
   opts: ['Porque es más rápido en promedio', 'Porque yendo hacia atrás corrés cada elemento hacia una posición ya visitada o libre, así que nunca pisás un elemento que todavía no leíste; yendo hacia adelante lo pisarías', 'Porque el vector está ordenado ascendente', 'Porque C no permite recorrer arreglos hacia adelante escribiendo'],
   c: 1,
   ex: 'Es la idea entera del ejercicio. Si vas de izquierda a derecha y hacés <span class="code">vec[i + 1] = vec[i]</span>, la posición <span class="code">i + 1</span> contiene un dato <b>que todavía no leíste</b> y lo destruís. ▸ Yendo de derecha a izquierda, <span class="code">i + 1</span> es o bien el hueco libre del final, o bien una posición cuyo contenido ya moviste. ▸ Y el beneficio adicional es el que hace que la restricción tenga sentido: yendo hacia atrás, <b>comparar y correr pasan a ser la misma visita</b>, así que buscar la posición deja de ser un recorrido aparte.'},

  {st: 'Después del <span class="code">while</span> de <span class="code">intercalar</span>, ¿por qué la asignación es <span class="code">vec[i + 1] = valor</span> y no <span class="code">vec[i] = valor</span>?',
   opts: ['Porque hay que dejar un lugar libre al final', 'Porque el while corta cuando vec[i] NO es mayor que el valor: ese elemento se queda donde está, y el hueco quedó en i + 1', 'Porque los índices de C empiezan en 0', 'Es indistinto, las dos andan'],
   c: 1,
   ex: 'El ciclo se detiene en el <b>primer elemento que no hay que mover</b>. Ese elemento sigue en su posición <span class="code">i</span>, y el lugar que quedó vacío por el último corrimiento es <span class="code">i + 1</span>. ▸ Escribir <span class="code">vec[i] = valor</span> pisaría un elemento válido y perdería un dato. ▸ El caso que confirma que el índice está bien es el vector vacío: con máximo lógico 0, <span class="code">i</span> arranca en <b>−1</b>, el <span class="code">while</span> ni entra, y <span class="code">vec[i + 1]</span> es <span class="code">vec[0]</span>. Sale correcto <b>sin escribir un caso especial</b>, y ése es el sello de que el diseño es el bueno.'},

  {st: 'Medimos cuántas posiciones toca cada versión al insertar en [2, 5, 8, 13, 21]. Insertando el 34 (al final): una pasada toca 1, dos pasadas toca 5. ¿Por qué?',
   opts: ['Porque la de dos pasadas tiene un bug', 'Porque yendo hacia atrás la primera comparación (21 no es mayor que 34) ya corta; la de dos pasadas recorre el vector entero buscando la posición y recién ahí descubre que no tiene que mover nada', 'Porque la de una pasada no verifica el orden', 'Porque insertar al final es un caso especial que no se cuenta'],
   c: 1,
   ex: 'Es la fila que mejor explica la restricción. La versión de atrás hacia adelante hace <b>una</b> comparación y termina. La de dos pasadas recorre los cinco elementos para encontrar la posición y después no corre ninguno: <b>cinco visitas para no mover nada</b>. ▸ En el peor caso —insertar al principio— la de una pasada toca 5 y la de dos toca 6. O sea: <b>nunca es peor, y casi siempre es mejor</b>. ▸ La restricción del enunciado no es un capricho didáctico: te está pidiendo el algoritmo correcto.'},

  {st: 'En <span class="code">intercalar</span> escribís <span class="code">*max_logico++</span> en vez de <span class="code">++(*max_logico)</span>. ¿Qué pasa?',
   opts: ['Es lo mismo', 'Se lee como *(max_logico++): incrementa el PUNTERO, no el entero apuntado. El máximo lógico nunca cambia y el puntero queda apuntando a memoria ajena. Compila sin avisar', 'No compila', 'Incrementa el entero pero después del return'],
   c: 1,
   ex: 'El <span class="code">++</span> postfijo tiene <b>más precedencia</b> que el <span class="code">*</span> de indirección, así que <span class="code">*max_logico++</span> es <span class="code">*(max_logico++)</span>. ▸ Efecto: el entero del invocante queda intacto —el vector "creció" pero el máximo lógico dice lo mismo, así que el elemento nuevo es invisible— y el puntero quedó corrido cuatro bytes, apuntando a lo que haya al lado. ▸ Y lo peor: <b>compila sin un solo warning</b>. Los paréntesis en <span class="code">++(*max_logico)</span> no son opcionales.'},

  {st: 'En el Tipo Parcial 03, ¿por qué el ciclo tiene que ser <span class="code">do-while</span> y no <span class="code">while</span>?',
   opts: ['Porque es más rápido', 'Porque con while (numero > 0) el número 0 no entra nunca al ciclo, y el 0 tiene un dígito, que además es par', 'Porque el do-while permite usar break', 'Porque el enunciado lo pide'],
   c: 1,
   ex: 'Con <span class="code">while (numero &gt; 0)</span>, invocar la función con <b>0</b> devuelve cantidad 0 y la función contesta "no tiene dígitos pares". Pero el 0 <b>es</b> un dígito y <b>es</b> par: la respuesta correcta es producto 0, cantidad 1. ▸ El <span class="code">do-while</span> ejecuta el cuerpo al menos una vez y el caso sale bien sin ningún <span class="code">if</span> especial. ▸ Es el primer caso borde que prueba un corrector, porque separa a quien probó su programa de quien lo escribió y lo entregó.'},

  {st: 'El número 105 pasado al Tipo Parcial 03 devuelve producto 0 y cantidad 1. ¿Está bien?',
   opts: ['No, debería devolver 5', 'Sí: el único dígito par de 105 es el 0, y el producto de un solo factor que vale 0 es 0. Conviene declararlo en un comentario', 'No, el 0 no es par', 'Sí, pero por casualidad'],
   c: 1,
   ex: 'Los dígitos de 105 son 1, 0 y 5. El único par es el <b>0</b> (y <span class="code">0 % 2 == 0</span> lo confirma: el cero es par). El producto de ese único factor es 0 y la cantidad es 1. ▸ No es un bug, es aritmética. Lo que sí corresponde es <b>dejarlo escrito en un comentario</b> arriba de la función, para que el corrector vea que la decisión está tomada y no olvidada. ▸ Distinto es el caso de <b>ningún</b> dígito par (1357): ahí el producto de cero factores sería 1, pero informar "producto 1" cuando no hubo dígitos engaña al invocante. La guía devuelve producto 0 con cantidad 0, y el que decide qué mostrar es el main mirando la cantidad.'},
]);

/* ============ SECCIÓN 4 · Las otras 10 consignas ============ */

registerReveals('fiuba-algoritmos-parcial', '4', [

{st: 'El ejercicio de timestamp pide validar que el valor sea entero positivo. Escribís <span class="code">scanf("%d", &amp;total); if (total &lt;= 0) …</span>. Encontrá el agujero y tapalo.',
 ans: 'Si el usuario escribe algo no numérico, scanf no asigna nada y total queda con basura, que puede ser positiva. Hay que mirar lo que devuelve scanf: la cantidad de campos leídos.',
 sol: '<span class="code">scanf</span> <b>devuelve un valor</b> y casi nadie lo usa: es la cantidad de campos que logró convertir. Si el usuario tipea <span class="code">hola</span>, devuelve <b>0</b> y no toca <span class="code">total</span>, que sigue con lo que hubiera en esa posición de memoria. ▸ La validación completa son <b>dos</b> condiciones en el mismo <span class="code">if</span>:<pre class="code-block">leidos = scanf("%d", &amp;total);<br>if (leidos != 1 || total &lt;= 0) {<br>    printf("\\nValor ingresado invalido\\n");<br>    return 0;<br>}</pre>▸ Lo probamos con <span class="code">-40</span> y con <span class="code">hola</span>: las dos entradas dan <span class="code">Valor ingresado invalido</span>. ▸ <b>Y el mensaje va textual</b>: la consigna escribe <i>"Valor ingresado inválido"</i>. Si lo escribís distinto, no cumpliste la consigna aunque la lógica esté bien.'},

{st: 'La función de cociente por restas sucesivas se invoca con a = 15 y b = 0. Sin la guarda, ¿qué pasa exactamente? ¿Y por qué la guarda devuelve <span class="code">bool</span> en vez de devolver 0?',
 ans: 'Con b = 0 el while resta cero indefinidamente y el programa se cuelga. Devolver 0 sería mentir, porque 0 es un cociente válido para otras entradas: por eso el éxito viaja por el return y el resultado por puntero.',
 sol: '<b>El cuelgue.</b> El ciclo es <span class="code">while (resto &gt;= b) resto = resto - b;</span>. Con <span class="code">b = 0</span>, la condición <span class="code">resto &gt;= 0</span> es verdadera y la resta no cambia nada: <b>ciclo infinito</b>. Un ejercicio que se cuelga es un cero completo, sin crédito parcial posible. ▸ <b>Por qué bool.</b> Si la función devolviera el cociente y usara el 0 para señalar el error, no habría forma de distinguir "no pude dividir" de "el cociente es 0", que es la respuesta legítima de <span class="code">15 / 20</span> — un caso que <b>está en los ejemplos del propio enunciado</b>. ▸ Compará con el factorial: ahí la cátedra sí pide devolver 0 como error, y funciona porque <b>ningún factorial vale 0</b>. El valor centinela sólo sirve cuando es imposible como resultado. ▸ <b>El bonus que casi nadie hace:</b> <span class="code">a</span> negativo. Con <span class="code">a = -15, b = 4</span> el ciclo ni arranca y el cociente da 0, cuando C dice que <span class="code">-15 / 4</span> es <b>−3</b>. Se resuelve trabajando en positivo y aplicando el signo al final.'},

{st: 'En el ejercicio de las consonantes, tu programa cuenta 7 consonantes en "Ariel Secchi" en vez de 6. ¿Qué te falta?',
 ans: 'El filtro isalpha: sin él, el espacio entre nombre y apellido cuenta como consonante, porque no es vocal.',
 sol: 'La definición perezosa de consonante es "todo lo que no es vocal", y con eso <b>el espacio, la coma, el punto y los dígitos son consonantes</b>. ▸ La definición correcta tiene dos partes y el orden importa: <span class="code">isalpha(letra) &amp;&amp; !es_vocal(letra)</span>. Primero "es una letra", después "no es vocal". ▸ Las consonantes reales de "Ariel Secchi" son <b>r, l, S, c, c, h</b>: seis. Las vocales son A, i, e, e, i. Total 11 letras más un espacio, 12 caracteres. ▸ <b>Y el detalle que no se arregla con isalpha:</b> las tildes y la ñ no son caracteres ASCII y pueden ocupar dos bytes. Si tu nombre las tiene, el conteo va a dar mal por razones de codificación, no de lógica. Para esta consigna: usá tu nombre sin tildes y dejá un comentario explicando la limitación.'},

]);

registerExercises('fiuba-algoritmos-parcial', '4', [
  {st: 'El ejercicio del factorial dice "si no se puede calcular el factorial del valor recibido, la función deberá devolver 0". ¿Cuáles son los casos en que no se puede?',
   opts: ['Sólo el negativo', 'El negativo y el desborde: 21! ya no entra en un long long de 64 bits y el resultado sale silenciosamente falso', 'Sólo el cero', 'Ninguno, el factorial siempre se puede calcular'],
   c: 1,
   ex: 'El obvio es el <b>negativo</b>: el factorial no está definido. ▸ El que casi nadie escribe es el <b>desborde</b>. 20! entra justo en un <span class="code">long long</span>; 21! no, y el resultado no da error: da un número cualquiera, a veces negativo. Una guarda <span class="code">if (n &lt; 0 || n &gt; MAX_FACTORIAL)</span> con <span class="code">MAX_FACTORIAL 20</span> convierte un resultado falso en el 0 que pide la consigna. ▸ Lo probamos: <span class="code">factorial(25)</span> devuelve 0 y <span class="code">factorial(5)</span> devuelve 120.'},

  {st: 'La consigna del factorial dice en negrita "No debe imprimir el valor, debe solamente devolverlo". ¿Por qué insiste con eso?',
   opts: ['Por prolijidad de la salida', 'Porque una función que imprime adentro no se puede reutilizar: no la podés usar para calcular un combinatorio ni para comparar dos factoriales. Separar cálculo de presentación es lo que evalúa la unidad de funciones', 'Porque printf es lento', 'Porque el campus no muestra la salida'],
   c: 1,
   ex: 'Es la idea central de la unidad de funciones y ésta es la consigna donde se evalúa. Una función que calcula <b>y</b> muestra sirve para un solo uso. ▸ Si <span class="code">factorial</span> devuelve el valor, podés escribir <span class="code">factorial(n) / (factorial(k) * factorial(n - k))</span>. Si imprime adentro, no podés hacer nada con el resultado. ▸ El mismo criterio aplica a todas las demás: el que muestra es el <span class="code">main</span>, o una función <span class="code">mostrar_…</span> aparte.'},

  {st: 'Al cargar la librería, el título y el autor tienen espacios. Leés el código con <span class="code">scanf("%d")</span> y el título con <span class="code">fgets</span>. ¿Qué pasa?',
   opts: ['Anda bien', 'El scanf deja el Enter en el buffer, el fgets se lo come y devuelve una cadena vacía: el título queda en blanco y el programa parece "saltarse" un campo', 'No compila', 'El título se lee sin el primer carácter'],
   c: 1,
   ex: 'Es el bug número uno del ejercicio de structs. <span class="code">scanf("%d")</span> lee el número y <b>deja el salto de línea</b> en el buffer de entrada; el <span class="code">fgets</span> siguiente encuentra ese Enter, lo consume, y devuelve inmediatamente una cadena vacía. ▸ Hay parches (<span class="code">getchar()</span> después del scanf, <span class="code">"%d "</span> con espacio, <span class="code">fflush</span> que además no es portable), pero la solución de fondo es <b>no mezclar</b>: leer <b>todo</b> con <span class="code">fgets</span> línea por línea y sacar los números con <span class="code">sscanf</span> sobre esa línea. Tres funciones de cinco renglones y el problema desaparece del programa entero.'},

  {st: 'La consigna de la librería pide tres ordenamientos y después una búsqueda binaria por código. ¿En qué orden van en el main y por qué?',
   opts: ['En cualquier orden, son independientes', 'El ordenamiento por código va ÚLTIMO, porque la búsqueda binaria exige que el vector esté ordenado por la clave que busca. Si queda vigente el orden por stock, la búsqueda contesta mal sin que nada falle', 'La búsqueda binaria va primero', 'Hay que ordenar por título último porque es el criterio principal'],
   c: 1,
   ex: 'La consigna lo dice: <i>"Una vez ordenado el vector por código, realizar una búsqueda binaria"</i>. ▸ La binaria descarta la mitad de los elementos en cada paso <b>asumiendo</b> el orden. Si el vector quedó ordenado por stock, la asunción no vale y la búsqueda no falla: <b>miente</b>. Devuelve "no encontrado" sobre un libro que está en el vector. ▸ Es el error más caro del ejercicio precisamente porque el programa compila, corre, no avisa nada y la salida parece razonable.'},

  {st: 'El struct t_regAlumno tiene un int (4 bytes), un char[30] y un float (4). ¿Cuánto devuelve sizeof, y cuánto pesa un archivo con 5 registros?',
   opts: ['38 bytes y 190 bytes', '40 bytes y 200 bytes: el compilador agrega 2 bytes de relleno para alinear el float', '34 bytes y 170 bytes', 'Depende del contenido de las cadenas'],
   c: 1,
   ex: 'Lo medimos: <span class="code">sizeof(t_regAlumno)</span> devuelve <b>40</b> y el archivo con 5 registros pesa exactamente <b>200 bytes</b> en disco. La suma de los campos da 38; el compilador mete <b>2 bytes de padding</b> después del arreglo de 30 para que el <span class="code">float</span> arranque en una dirección múltiplo de 4. ▸ Dos consecuencias: <b>nunca calcules el tamaño de un registro sumando campos</b> —usá <span class="code">sizeof</span>, que es lo que usa <span class="code">fwrite</span>—, y un <span class="code">.dat</span> escrito con un compilador puede no leerse igual con otro, porque el relleno depende del compilador y de la arquitectura.'},

  {st: 'Para recorrer un archivo binario de registros, ¿cuál es la condición de fin correcta?',
   opts: ['<span class="code">while (!feof(archivo))</span>', '<span class="code">while (fread(&amp;reg, sizeof(reg), 1, archivo) == 1)</span>', '<span class="code">while (archivo != NULL)</span>', '<span class="code">for (i = 0; i &lt; cantidad; i++)</span> con cantidad pedida al usuario'],
   c: 1,
   ex: '<span class="code">fread</span> devuelve <b>cuántos elementos leyó</b>: comparar contra 1 corta exactamente cuando ya no hay un registro completo. ▸ <span class="code">feof</span> <b>procesa el último registro dos veces</b>: no adivina que el archivo terminó, se prende recién <b>después</b> de una lectura fallida. En esa última vuelta el struct conserva los datos anteriores y los imprimís de nuevo. ▸ <span class="code">archivo != NULL</span> no cambia nunca dentro del ciclo: es infinito. ▸ Y pedirle la cantidad al usuario es delegar en él un dato que el archivo ya tiene: se calcula con <span class="code">fseek</span> y <span class="code">ftell</span>.'},

  {st: 'La versión "ingenua" del capicúa recursivo dice que 10201 NO es capicúa y que 1000021 SÍ lo es. ¿Cuál es la falla de diseño?',
   opts: ['El caso base está mal', 'Recalcula la cantidad de dígitos en cada llamada: al pelar el primer y el último dígito, los ceros que quedan adelante desaparecen del número. La cantidad de dígitos tiene que viajar como parámetro', 'Falta convertir el negativo a positivo', 'Usa división entera en vez de módulo'],
   c: 1,
   ex: 'Con 10201: después de comparar el 1 con el 1 queda <span class="code">(10201 % 10000) / 10 = 20</span>. El cero de adelante <b>se perdió</b>, la función recuenta y ve dos dígitos, compara 2 con 0 y dice que no. ▸ Con 1000021 es peor: queda <span class="code">(1000021 % 1000000) / 10 = 2</span>, un solo dígito, caso base, "es capicúa". <b>Perdió cuatro ceros de una sola vez</b> y dio un falso positivo. ▸ La corrección no es un parche: la cantidad de dígitos es parte del <b>estado del problema</b>, así que se pasa como parámetro y se le resta 2 en cada llamada. Con eso, 10201 da capicúa y 1000021 no.'},

  {st: 'En la exponenciación binaria recursiva, ¿por qué hay que guardar la mitad en una variable en vez de escribir <span class="code">potencia(b, e/2) * potencia(b, e/2)</span>?',
   opts: ['Por legibilidad', 'Porque son DOS llamadas en vez de una: el árbol de recursión se duplica en cada nivel y el algoritmo deja de ser binario, pasa a costar lo mismo que multiplicar de a uno', 'Porque la segunda llamada da un resultado distinto', 'Porque el compilador no lo permite'],
   c: 1,
   ex: 'La gracia de la exponenciación binaria es que cada nivel <b>divide el exponente por dos con una sola llamada</b>: unos 10 pasos para un exponente de 1000. ▸ Con dos llamadas idénticas, cada nivel genera dos ramas y el árbol tiene tantas hojas como el exponente: el algoritmo pasa a costar lo mismo que multiplicar de a uno, y además con el overhead de la recursión. ▸ Es exactamente el mismo error que hace lento a Fibonacci recursivo. Una línea —<span class="code">mitad = potencia(base, exponente / 2);</span>— y el algoritmo vuelve a ser el que pide la consigna.'},
]);

/* ============ SECCIÓN 5 · Los siete patrones ============ */

registerReveals('fiuba-algoritmos-parcial', '5', [

{st: 'Para cada uno de estos cinco enunciados, decidí <b>sin escribir código</b> qué patrón toca y cuál es la primera línea que escribís. <b>a)</b> "…devuelva el promedio de las notas, o informe que no se puede calcular si no hay alumnos cargados". <b>b)</b> "…elimine del vector los elementos negativos, sin usar otro arreglo". <b>c)</b> "…indique si el número es capicúa. No se pueden usar arreglos". <b>d)</b> "…lea el archivo de productos y muestre los que tienen stock cero". <b>e)</b> "…busque un alumno por padrón en el vector ordenado por padrón".',
 ans: 'a) Patrón 1 (bool + puntero). b) Patrón 3, variante eliminar (dos índices, hacia adelante). c) Patrón 4 (pelar dígitos con do-while). d) Patrón 6 (abrir, chequear, usar, cerrar). e) Patrón 7 (binaria, con la precondición verificada).',
 sol: '<b>a · Patrón 1.</b> "o informe que no se puede" es la frase disparadora. Primera línea: <span class="code">bool promedio_general(const t_alumno alumnos[], int cantidad, float *promedio)</span>, y adentro <span class="code">if (cantidad == 0) return false;</span> antes de dividir. ▸ <b>b · Patrón 3, variante eliminar.</b> "sin usar otro arreglo" con el vector achicándose: dos índices, <b>hacia adelante</b>. Primera línea: <span class="code">escritura = 0;</span> y después el <span class="code">for</span> de lectura. El máximo lógico nuevo es <span class="code">escritura</span>. ▸ <b>c · Patrón 4.</b> "no se pueden usar arreglos" con un número: <span class="code">do { digito = n % 10; … } while (n &gt; 0);</span>. Y la advertencia: para capicúa hay que llevar la cantidad de dígitos como parámetro. ▸ <b>d · Patrón 6.</b> Primera línea: <span class="code">archivo = fopen(nombre, "rb");</span> y en la siguiente <span class="code">if (archivo == NULL)</span>. El recorrido va con <span class="code">while (fread(…) == 1)</span>, nunca con <span class="code">feof</span>. ▸ <b>e · Patrón 7.</b> Binaria, con <span class="code">primero &lt;= ultimo</span>, movimientos a <span class="code">medio ± 1</span> y <span class="code">-1</span> como "no encontrado". Y antes de escribirla, <b>verificá en el main que el último ordenamiento haya sido por padrón</b>. ▸ El ejercicio real de esta actividad no es acertar los cinco: es <b>tardar menos de treinta segundos por enunciado</b>. Ése es el tiempo que tenés en un examen de 25 minutos por ejercicio.'},

{st: 'Escribí de memoria el esqueleto de la <b>carga con centinela</b> y explicá qué se rompe si sacás cada una de sus tres piezas.',
 ans: 'Lectura anticipada antes del while, condición doble (centinela y máximo), y relectura al final del cuerpo. Sin la anticipada, la condición evalúa basura; sin la doble, escribís fuera del arreglo; sin la relectura, el ciclo es infinito.',
 sol: '<pre class="code-block">printf("Codigo (0 termina): ");<br>clave = leer_entero();                     /* 1. lectura ANTICIPADA */<br>while (clave != 0 &amp;&amp; *cantidad &lt; MAX_LIBROS) {   /* 2. condicion DOBLE */<br>    /* … cargar los demas campos … */<br>    ++(*cantidad);<br>    printf("Codigo (0 termina): ");<br>    clave = leer_entero();                 /* 3. relectura al FINAL */<br>}</pre>▸ <b>Sin la 1:</b> la condición del <span class="code">while</span> evalúa una variable sin inicializar en la primera vuelta. Puede entrar o no, al azar. ▸ <b>Sin la mitad "cantidad &lt; MAX" de la 2:</b> el usuario carga 150 libros en un arreglo de 100 y escribís fuera del arreglo. El enunciado de la librería lo pide explícito: <i>"permitir ingresar hasta MAX_LIBROS libros"</i>. ▸ <b>Sin la 3:</b> la clave nunca cambia y el ciclo es infinito. ▸ <b>Y la cuarta pieza, invisible:</b> el centinela <b>no se guarda</b>. El 0 marca el fin, no es un dato. Si lo guardás, aparece un libro fantasma con código 0 en todos los listados y en el total del inventario.'},

{st: 'Este fragmento intenta contar cuántos elementos tiene un vector desde adentro de una función. ¿Qué devuelve y por qué?<pre class="code-block">int contar(int vec[])<br>{<br>    return sizeof(vec) / sizeof(vec[0]);<br>}</pre>',
 ans: 'Devuelve 2 en un sistema de 64 bits: el parámetro es un puntero (8 bytes) dividido por el tamaño de un int (4). Nunca la cantidad de elementos.',
 sol: 'En C, un parámetro declarado <span class="code">int vec[]</span> <b>es un puntero</b>, no un arreglo: la información de tamaño se pierde al pasarlo. ▸ <span class="code">sizeof(vec)</span> son <b>8 bytes</b> (el tamaño de un puntero en 64 bits) y <span class="code">sizeof(vec[0])</span> son 4: la cuenta da <b>2</b>, siempre, sin importar el vector. ▸ Lo que hace el error especialmente confuso es que <b>en el main la misma cuenta sí funciona</b>, porque ahí el arreglo está declarado de verdad y el compilador conoce su tamaño. ▸ La regla, sin excepciones en esta materia: <b>la cantidad se pasa por parámetro</b>, junto con el vector, siempre. Y si la función la modifica, por puntero.'},

]);

registerExercises('fiuba-algoritmos-parcial', '5', [
  {st: 'Un enunciado dice "devuelva true si pudo y false si no". ¿Qué escribís primero, antes de pensar el algoritmo?',
   opts: ['El main', 'La firma: bool de retorno y el resultado por puntero, con el chequeo del caso de falla al principio del cuerpo', 'Los #define', 'Un comentario con el enunciado'],
   c: 1,
   ex: 'Es el patrón 1 y es el más frecuente de la cátedra: aparece en el Tipo Parcial 02, en el cociente por restas sucesivas, en el promedio del curso y en la división de complejos. ▸ La firma correcta te ordena el resto: el <span class="code">return</span> informa <b>si se pudo</b>, el resultado sale por puntero, y el caso de falla se chequea <b>al principio</b> para no anidar todo el cuerpo dentro de un if gigante. ▸ Y la regla que se olvida: si devuelve <span class="code">false</span>, <b>los parámetros de salida quedan como estaban</b>. El invocante tiene que poder confiar en eso.'},

  {st: '¿Cuál es la diferencia entre la técnica de dos índices para insertar y la de eliminar?',
   opts: ['Son la misma', 'La dirección: insertar recorre de atrás hacia adelante (el vector crece), eliminar de adelante hacia atrás (el vector se achica y el índice de escritura queda siempre detrás del de lectura)', 'Insertar necesita un arreglo auxiliar', 'Eliminar no puede hacerse en una sola pasada'],
   c: 1,
   ex: 'Las dos son "dos índices sobre el mismo vector, una sola pasada, sin auxiliar", pero <b>la dirección se elige por una razón</b>. ▸ Al <b>insertar</b>, el vector crece: si fueras hacia adelante corriendo, pisarías datos no leídos. Yendo hacia atrás, el destino del corrimiento siempre es una posición ya visitada o libre. ▸ Al <b>eliminar</b>, el vector se achica: yendo hacia adelante, el índice de escritura avanza <b>más lento</b> que el de lectura, así que nunca lo alcanza y nunca pisa nada pendiente. ▸ Cambiando la condición del if, la de eliminar sirve para cualquier filtro: sacar los negativos, dejar sólo los pares, eliminar repetidos.'},

  {st: 'Al pelar dígitos con <span class="code">% 10</span> y <span class="code">/ 10</span>, ¿qué pasa con un número negativo en C?',
   opts: ['El módulo devuelve el dígito positivo', '<span class="code">-25 % 10</span> da −5, no 5: hay que pasar el número a positivo ANTES del ciclo', 'El ciclo no arranca', 'El compilador convierte automáticamente'],
   c: 1,
   ex: 'En C el resto <b>toma el signo del dividendo</b>: <span class="code">-25 % 10</span> es <b>−5</b>. Si tu condición pregunta <span class="code">digito % 2 == 0</span>, un −5 no rompe nada, pero un producto o una comparación de "mayor dígito" sí: con acumulador arrancando en −1, un dígito negativo puede ganar. ▸ La defensa es una línea, <b>antes</b> del ciclo: <span class="code">if (numero &lt; 0) numero = -numero;</span> ▸ Y el signo no es un dígito: el enunciado del Tipo Parcial 03 habla de "sus dígitos", y −25831 tiene los mismos que 25831.'},

  {st: 'Estás por hacer una búsqueda binaria. ¿Qué verificás antes de escribirla?',
   opts: ['Que el vector no esté vacío', 'Que el ÚLTIMO ordenamiento aplicado haya sido por la misma clave que vas a buscar', 'Que la cantidad sea potencia de dos', 'Que el vector sea de enteros'],
   c: 1,
   ex: 'La binaria no verifica su precondición: la <b>asume</b>. Si el vector quedó ordenado por otra clave, la búsqueda no da error — devuelve "no encontrado" sobre un elemento que sí está. ▸ En el ejercicio de la librería, la consigna pide tres ordenamientos y después la binaria por código: por eso <b>el ordenamiento por código va último en el main</b>. Dejar el de stock al final es el bug más caro del ejercicio, porque es invisible. ▸ Si no podés garantizar el orden, la respuesta correcta es búsqueda <b>lineal</b>, que no tiene precondición.'},

  {st: 'Tu búsqueda binaria devuelve 0 cuando no encuentra el elemento. ¿Cuál es el problema?',
   opts: ['Ninguno', '0 es una posición válida: el invocante no puede distinguir "está en la primera posición" de "no está". Se devuelve −1 y se pregunta if (posicion >= 0)', 'Debería devolver la cantidad', 'Debería devolver NULL'],
   c: 1,
   ex: 'Es el mismo razonamiento del valor centinela que aparece en el factorial y en el cociente: un valor sólo sirve como marca de error si es <b>imposible</b> como resultado legítimo. ▸ La posición 0 es perfectamente válida —es el primer elemento del vector—, así que devolverla para decir "no está" hace que el invocante muestre el libro equivocado. ▸ <span class="code">-1</span> no es una posición posible, y el invocante pregunta <span class="code">if (posicion &gt;= 0)</span>. ▸ Los otros dos errores clásicos de la binaria: usar <span class="code">&lt;</span> en vez de <span class="code">&lt;=</span> en la condición del while (con un solo elemento restante no entra), y mover los extremos a <span class="code">medio</span> en vez de <span class="code">medio ± 1</span> (ciclo infinito).'},

  {st: '¿Cuándo se usa <span class="code">"ab"</span> en vez de <span class="code">"wb"</span> al abrir un archivo binario?',
   opts: ['Nunca, son equivalentes', 'Cuando hay que AGREGAR registros a un archivo que ya existe: "wb" trunca el archivo a cero y se pierde todo lo anterior', '"ab" es para archivos de texto', '"ab" es más rápido'],
   c: 1,
   ex: '<span class="code">"wb"</span> crea el archivo si no está, pero si existía lo <b>trunca a cero</b>: adiós a todo lo que había. Es el modo correcto para <i>"asuma que el archivo es inexistente"</i>, que es lo que dice el enunciado de Cargar Alumnos. ▸ <span class="code">"ab"</span> (append) escribe siempre al final y conserva lo anterior: es el modo de "dar de alta" sobre un archivo que ya tiene datos. ▸ Y la <b>b</b> no es optativa en Windows: sin ella el sistema traduce los bytes que valen <span class="code">0x0A</span> y un archivo binario de structs queda corrupto.'},
]);

/* ============ SECCIÓN 6 · Simulacro de parcial ============ */

registerReveals('fiuba-algoritmos-parcial', '6', [

{st: '<b>SIMULACRO · Ejercicio 1.</b> Eliminar del vector todas las apariciones de un valor, devolviendo <span class="code">true</span> si eliminó al menos uno, con vector y máximo lógico por parámetro, <b>recorriendo una sola vez y sin arreglo auxiliar</b>.',
 ans: 'Dos índices sobre el mismo vector, recorriendo hacia adelante: uno de lectura que avanza siempre y uno de escritura que avanza sólo cuando el elemento se conserva. Al final, el máximo lógico nuevo es el índice de escritura.',
 sol: '<b>Por qué hacia adelante y no hacia atrás:</b> el vector se <b>achica</b>, así que el índice de escritura avanza más lento que el de lectura y <b>nunca lo alcanza</b>. Nunca pisás un elemento que todavía no leíste. Es la imagen especular del Tipo Parcial 02.<pre class="code-block">bool eliminar_valor(t_vector vec, int *max_logico, int valor)<br>{<br>    int lectura;<br>    int escritura = 0;<br><br>    for (lectura = 0; lectura &lt; *max_logico; lectura++) {<br>        if (vec[lectura] != valor) {<br>            vec[escritura] = vec[lectura];<br>            ++escritura;<br>        }<br>    }<br>    if (escritura == *max_logico)<br>        return false;<br><br>    *max_logico = escritura;<br>    return true;<br>}</pre>▸ <b>Cómo sabe si eliminó algo:</b> si el índice de escritura terminó igual al máximo lógico, no se descartó ninguno. No hace falta un contador aparte. ▸ <b>Salida real</b>, con <span class="code">[7, 3, 7, 1, 7, 9, 2, 7]</span>:<pre class="code-block">Vector inicial:  [7, 3, 7, 1, 7, 9, 2, 7]  (max logico = 8)<br>Elimino el 7:  true<br>[3, 1, 9, 2]  (max logico = 4)<br>Elimino el 7 otra vez:  false<br>[3, 1, 9, 2]  (max logico = 4)</pre>▸ <b>Los casos que tenía que probar tu main:</b> eliminar un valor que no está (devuelve <span class="code">false</span> y no toca nada), eliminar todos los elementos (máximo lógico queda en 0), y máximo lógico 0 de entrada (el <span class="code">for</span> no entra, <span class="code">escritura</span> queda en 0, devuelve <span class="code">false</span>). Los tres salen bien sin ningún <span class="code">if</span> especial. ▸ <b>Trampa:</b> las posiciones que quedan más allá del nuevo máximo lógico conservan valores viejos. Eso <b>no</b> es un error: fuera del máximo lógico no hay datos, hay basura, y no hay que "limpiarlas".'},

{st: '<b>SIMULACRO · Ejercicio 2.</b> Devolver el mayor dígito de un entero y cuántas veces aparece, sin usar arreglos. 919293 → 9 y 3.',
 ans: 'Un do-while que pela dígitos con % 10 y / 10, con el mayor inicializado en −1 y el contador que se reinicia en 1 cada vez que aparece un dígito estrictamente mayor.',
 sol: '<pre class="code-block">void mayor_digito(int numero, int *mayor, int *repeticiones)<br>{<br>    int digito;<br><br>    if (numero &lt; 0)<br>        numero = -numero;<br><br>    *mayor = -1;<br>    *repeticiones = 0;<br>    do {<br>        digito = numero % 10;<br>        if (digito &gt; *mayor) {<br>            *mayor = digito;<br>            *repeticiones = 1;<br>        } else if (digito == *mayor) {<br>            ++(*repeticiones);<br>        }<br>        numero = numero / 10;<br>    } while (numero &gt; 0);<br>}</pre>▸ <b>Las tres decisiones que deciden el ejercicio.</b> <b>1 · El mayor arranca en −1</b>, no en 0: si arrancara en 0, un número como 105 nunca "encontraría" el 0 como mayor y el contador quedaría mal. Con −1, cualquier dígito real gana en la primera vuelta. ▸ <b>2 · El contador se reinicia en 1</b> cuando aparece un dígito mayor, no se incrementa. Es el error clásico: <span class="code">++(*repeticiones)</span> en la rama del <span class="code">if</span> hace que el contador acumule apariciones de dígitos distintos. ▸ <b>3 · El <span class="code">else if</span> con <span class="code">==</span></b>, no un segundo <span class="code">if</span> suelto: si el dígito acaba de convertirse en el nuevo mayor, un <span class="code">if (digito == *mayor)</span> independiente lo contaría dos veces. ▸ <b>Salida real:</b><pre class="code-block">25831   -&gt; mayor digito 8, aparece 1 vez/veces<br>919293  -&gt; mayor digito 9, aparece 3 vez/veces<br>0       -&gt; mayor digito 0, aparece 1 vez/veces<br>-4004   -&gt; mayor digito 4, aparece 2 vez/veces</pre>▸ El <b>0</b> sale bien gracias al <span class="code">do-while</span>, y el <b>−4004</b> gracias a la conversión a positivo del principio.'},

{st: '<b>SIMULACRO · Ejercicio 3.</b> Dada una frase, devolver por parámetro la palabra más larga y la cantidad de palabras, recorriendo la frase una sola vez y sin <span class="code">strtok</span>.',
 ans: 'Un solo recorrido con una máquina de dos estados: dentro de palabra o fuera. Se lleva el inicio y el largo de la palabra actual, y el inicio y el largo de la mejor hasta el momento. Al final se copia con strncpy y se cierra con el terminador.',
 sol: '<b>La idea:</b> no hace falta guardar las palabras, sólo <b>dónde empieza</b> y <b>cuánto mide</b> la mejor. Cuatro enteros y un recorrido.<pre class="code-block">void palabra_mas_larga(const char frase[], char destino[], int *cant_palabras)<br>{<br>    int i;<br>    int inicio_actual = 0;<br>    int largo_actual = 0;<br>    int inicio_mejor = 0;<br>    int largo_mejor = 0;<br><br>    *cant_palabras = 0;<br>    for (i = 0; ; i++) {<br>        if (frase[i] != &#39; &#39; &amp;&amp; frase[i] != &#39;\\0&#39;) {<br>            if (largo_actual == 0)<br>                inicio_actual = i;<br>            ++largo_actual;<br>        } else {<br>            if (largo_actual &gt; 0) {<br>                ++(*cant_palabras);<br>                if (largo_actual &gt; largo_mejor) {<br>                    largo_mejor = largo_actual;<br>                    inicio_mejor = inicio_actual;<br>                }<br>                largo_actual = 0;<br>            }<br>            if (frase[i] == &#39;\\0&#39;)<br>                break;<br>        }<br>    }<br>    strncpy(destino, frase + inicio_mejor, largo_mejor);<br>    destino[largo_mejor] = &#39;\\0&#39;;<br>}</pre>▸ <b>Las cuatro decisiones.</b> <b>1 · El terminador se trata igual que un espacio</b>, y por eso el <span class="code">for</span> no tiene condición de corte: entra también en la posición del <span class="code">\\0</span>, cierra la última palabra, y recién ahí hace <span class="code">break</span>. Sin eso, la palabra final no se cuenta. ▸ <b>2 · La palabra se cuenta al cerrarla</b>, no al abrirla, y sólo si tenía largo mayor que cero. Eso hace que los <b>espacios repetidos</b> y los espacios del principio y del final no generen palabras fantasma. ▸ <b>3 · <span class="code">&gt;</span> estricto</b> al comparar con el mejor: ante un empate gana la <b>primera</b>, que es la convención razonable. ▸ <b>4 · <span class="code">strncpy</span> no pone el terminador</b> cuando copia exactamente <span class="code">largo_mejor</span> caracteres: hay que escribirlo a mano en la línea siguiente. Es el olvido que hace que la salida arrastre basura. ▸ <b>Salida real:</b><pre class="code-block">Frase: "el parcial de algoritmos se aprueba programando"<br>Palabra mas larga: "programando"  (11 letras)<br>Cantidad de palabras: 7<br>Frase "   uno   dos   " -&gt; mas larga "uno", 2 palabras</pre>▸ La segunda prueba es la que importa: tres espacios adelante, tres en el medio y tres al final, y devuelve <b>2</b> palabras.'},

]);

registerExercises('fiuba-algoritmos-parcial', '6', [
  {st: 'En el ejercicio 1 del simulacro, ¿cómo sabe la función si eliminó algún elemento, sin usar un contador aparte?',
   opts: ['Comparando el vector con una copia', 'Si el índice de escritura terminó igual al máximo lógico original, no se descartó ninguno: devuelve false', 'Contando las apariciones en un primer recorrido', 'No se puede saber en una sola pasada'],
   c: 1,
   ex: 'El índice de escritura avanza <b>sólo cuando el elemento se conserva</b>. Si al final vale lo mismo que el máximo lógico original, se conservaron todos y no se eliminó nada. ▸ Un contador aparte funcionaría igual, pero el dato ya está: agregarlo es ruido. ▸ Y la comparación contra una copia violaría "sin arreglo auxiliar", y un primer recorrido para contar violaría "una sola pasada". Las dos restricciones del enunciado apuntan a esta solución.'},

  {st: 'En el ejercicio 2 del simulacro, ¿por qué el mayor dígito se inicializa en −1 y no en 0?',
   opts: ['Por costumbre', 'Porque con 0 un número como 105 nunca registraría el 0 como mayor en la primera comparación y el contador quedaría mal; con −1 cualquier dígito real gana en la primera vuelta', 'Porque −1 es más rápido', 'Porque el 0 no es un dígito'],
   c: 1,
   ex: 'El inicializador de un acumulador de máximo tiene que ser <b>menor que cualquier valor posible</b>. Los dígitos van de 0 a 9, así que 0 <b>no</b> sirve: es un valor alcanzable. ▸ Con <span class="code">*mayor = 0</span>, en un número como 100 el primer dígito procesado es 0 y la condición <span class="code">digito &gt; *mayor</span> es falsa, así que el contador nunca se pone en 1 y quedaría en 0 aunque el mayor sí sea 0. ▸ Con −1, el primer dígito siempre entra por la rama del <span class="code">if</span> y deja el contador consistente. ▸ La alternativa correcta sería inicializar con el primer dígito antes del ciclo, pero con <span class="code">-1</span> el código queda más corto y sin caso especial.'},

  {st: 'En el ejercicio 2, ¿qué pasa si en la rama del dígito mayor escribís <span class="code">++(*repeticiones)</span> en vez de <span class="code">*repeticiones = 1</span>?',
   opts: ['Nada, es lo mismo', 'El contador acumula apariciones de dígitos distintos: cuando aparece un dígito mayor hay que EMPEZAR a contar de nuevo, no seguir sumando', 'El programa se cuelga', 'Cuenta uno de menos'],
   c: 1,
   ex: 'Es el error central de este ejercicio. Encontrar un dígito <b>mayor</b> invalida todo lo contado hasta ahí: el máximo cambió, así que el contador de ese máximo arranca en <b>1</b>. ▸ Con <span class="code">++</span>, procesando 1234 el contador terminaría en 4 (una por cada dígito, porque cada uno es mayor que el anterior) cuando la respuesta es <b>4 aparece 1 vez</b>. ▸ Y el otro detalle del mismo bloque: la segunda rama tiene que ser <span class="code">else if (digito == *mayor)</span>. Un <span class="code">if</span> suelto contaría dos veces el dígito que acaba de convertirse en el nuevo máximo.'},

  {st: 'En el ejercicio 3, el <span class="code">for</span> no tiene condición de corte: <span class="code">for (i = 0; ; i++)</span>. ¿Por qué?',
   opts: ['Es un error', 'Para que el ciclo entre también en la posición del terminador y pueda cerrar la última palabra antes de salir con break', 'Porque la frase puede ser infinita', 'Porque strlen es lento'],
   c: 1,
   ex: 'Si el ciclo cortara en <span class="code">frase[i] != &#39;\\0&#39;</span>, la <b>última palabra nunca se cerraría</b>: se saldría del ciclo con <span class="code">largo_actual</span> mayor que cero y sin haberla contado ni comparado. La frase "el parcial" devolvería 1 palabra en vez de 2. ▸ La solución es tratar el terminador <b>igual que un espacio</b> —los dos cierran palabra— y hacer el <span class="code">break</span> recién después de cerrarla. ▸ Es el mismo problema que aparece al procesar cualquier flujo con delimitadores: el último elemento no tiene delimitador al final, así que el fin del dato tiene que actuar como uno.'},

  {st: 'En el ejercicio 3 usás <span class="code">strncpy(destino, frase + inicio_mejor, largo_mejor)</span> y no escribís nada más. ¿Qué falta?',
   opts: ['Nada', 'El terminador: strncpy no lo agrega cuando copia exactamente n caracteres. Hay que escribir destino[largo_mejor] = 0 en la línea siguiente', 'Hay que usar strcpy', 'Falta reservar memoria para destino'],
   c: 1,
   ex: '<span class="code">strncpy</span> copia a lo sumo n caracteres y <b>sólo agrega el terminador si encontró uno en el origen dentro de esos n</b>. Acá el origen es la mitad de una frase más larga, así que no lo encuentra. ▸ Sin la línea siguiente, <span class="code">destino</span> no es una cadena válida: cualquier <span class="code">printf("%s")</span> sigue leyendo memoria hasta encontrar un cero por casualidad, y la salida arrastra basura. ▸ Es una de las diferencias que hay que tener presentes: <span class="code">strcpy</span> siempre pone el terminador pero no controla el tamaño; <span class="code">strncpy</span> controla el tamaño pero puede no poner el terminador.'},
]);

/* ============ SECCIÓN 7 · Simulacro de integrador ============ */

registerReveals('fiuba-algoritmos-parcial', '7', [

{st: '<b>Extensión 1 del integrador.</b> Agregar un punto: <b>modificar la cuota de un socio dado su número</b>, actualizando el archivo binario sin reescribirlo entero. ¿Cómo se hace?',
 ans: 'Se abre el archivo en modo "r+b", se busca el registro secuencialmente llevando la cuenta de la posición, se vuelve a esa posición con fseek y se sobrescribe sólo ese registro con fwrite.',
 sol: '<b>La clave es el modo de apertura y el <span class="code">fseek</span> de reposicionamiento.</b><pre class="code-block">bool modificar_cuota(const char nombre_archivo[], int nro_socio, float cuota_nueva)<br>{<br>    FILE *archivo;<br>    t_socio socio;<br>    long posicion = 0;<br>    bool encontrado = false;<br><br>    archivo = fopen(nombre_archivo, "r+b");<br>    if (archivo == NULL)<br>        return false;<br><br>    while (!encontrado &amp;&amp; fread(&amp;socio, sizeof(t_socio), 1, archivo) == 1) {<br>        if (socio.nro_socio == nro_socio)<br>            encontrado = true;<br>        else<br>            ++posicion;<br>    }<br>    if (encontrado) {<br>        socio.cuota = cuota_nueva;<br>        fseek(archivo, posicion * (long) sizeof(t_socio), SEEK_SET);<br>        fwrite(&amp;socio, sizeof(t_socio), 1, archivo);<br>    }<br>    fclose(archivo);<br>    return encontrado;<br>}</pre>▸ <b>Los tres puntos finos.</b> <b>1 · El modo <span class="code">"r+b"</span></b>: lectura <i>y</i> escritura sobre un archivo existente, sin truncar. Con <span class="code">"wb"</span> perderías todo; con <span class="code">"rb"</span> el <span class="code">fwrite</span> falla en silencio. ▸ <b>2 · El <span class="code">fseek</span> antes de escribir</b>: después del <span class="code">fread</span> el cursor quedó <b>después</b> del registro leído. Si escribís ahí, pisás el registro siguiente. Hay que volver a <span class="code">posicion * sizeof(t_socio)</span> desde <span class="code">SEEK_SET</span>. ▸ <b>3 · La posición se cuenta en registros, no en bytes</b>, y se multiplica por <span class="code">sizeof</span> recién al usarla. ▸ Este punto es el que separa "sé usar archivos" de "sé usar archivos de acceso directo", y es material típico de integrador.'},

{st: '<b>Extensión 2 del integrador.</b> Ahora la cantidad de socios no se conoce ni siquiera al leer: los datos vienen de teclado directo a memoria, sin archivo intermedio. Resolvelo con <span class="code">realloc</span>.',
 ans: 'Se arranca con un puntero en NULL y capacidad 0, y cada vez que la cantidad alcanza la capacidad se duplica con realloc, verificando el resultado en un puntero auxiliar antes de asignarlo.',
 sol: '<pre class="code-block">t_socio *cargar_a_memoria(int *cantidad)<br>{<br>    t_socio *socios = NULL;<br>    t_socio *auxiliar;<br>    t_socio socio;<br>    int capacidad = 0;<br><br>    *cantidad = 0;<br>    while (pedir_socio(&amp;socio)) {<br>        if (*cantidad == capacidad) {<br>            if (capacidad == 0)<br>                capacidad = 4;<br>            else<br>                capacidad = capacidad * 2;<br>            auxiliar = (t_socio *) realloc(socios, capacidad * sizeof(t_socio));<br>            if (auxiliar == NULL) {<br>                free(socios);<br>                *cantidad = 0;<br>                return NULL;<br>            }<br>            socios = auxiliar;<br>        }<br>        socios[*cantidad] = socio;<br>        ++(*cantidad);<br>    }<br>    return socios;<br>}</pre>▸ <b>El error que arruina este patrón</b> es escribir <span class="code">socios = realloc(socios, …)</span> directo. Si <span class="code">realloc</span> falla devuelve <span class="code">NULL</span>, y al asignarlo <b>perdés el puntero al bloque anterior</b>: la memoria queda reservada y sin dueño. Por eso el resultado va a un <b>auxiliar</b> que se verifica antes de reemplazar. ▸ <b>Por qué duplicar y no crecer de a uno:</b> <span class="code">realloc</span> puede tener que copiar el bloque entero. Creciendo de a uno, cargar N socios cuesta del orden de N² copias; duplicando, del orden de N. ▸ <b>Y <span class="code">realloc(NULL, n)</span> es legal</b>: se comporta como <span class="code">malloc(n)</span>. Por eso el puntero puede arrancar en <span class="code">NULL</span> sin ningún caso especial.'},

{st: '<b>Extensión 3 del integrador.</b> Tu programa termina, corre bien y muestra todo. ¿Cómo verificás que <b>no perdiste memoria</b>, y qué buscás exactamente?',
 ans: 'Un free por cada malloc/realloc, en todos los caminos de salida incluidos los de error, y el puntero a NULL después de liberar. La cátedra publica material sobre Valgrind para verificarlo en Linux.',
 sol: '<b>La revisión a ojo, que es la que vas a hacer en el examen.</b> ▸ <b>1 · Contá los <span class="code">malloc</span> y los <span class="code">free</span>.</b> Tienen que dar igual, y no sólo en el camino feliz: cada <span class="code">return</span> temprano <b>después</b> de una reserva tiene que liberar antes de salir. En <span class="code">leer_a_memoria</span> hay dos: el del <span class="code">malloc</span> fallido (no hay nada que liberar) y el del <span class="code">fread</span> incompleto (ahí sí va el <span class="code">free</span>). ▸ <b>2 · <span class="code">socios = NULL</span> después del <span class="code">free</span>.</b> No evita la fuga, evita algo peor: usar un puntero que ya no es tuyo. Con <span class="code">NULL</span>, el error se manifiesta al instante en vez de corromper datos en silencio. ▸ <b>3 · Nunca liberes dos veces</b> el mismo puntero. Con el <span class="code">NULL</span> del punto 2 esto queda cubierto, porque <span class="code">free(NULL)</span> es legal y no hace nada. ▸ <b>La verificación mecánica:</b> la cátedra publica un apunte de <b>Valgrind</b> en la sección de Memoria Dinámica. En Linux, <span class="code">valgrind --leak-check=full ./programa</span> te dice exactamente cuántos bytes quedaron sin liberar y en qué línea se reservaron. ▸ Y el detalle que sorprende: <b>un programa con fugas anda perfecto</b> y muestra la salida correcta. Por eso la fuga se busca leyendo, no probando.'},

]);

registerExercises('fiuba-algoritmos-parcial', '7', [
  {st: 'El punto 2 del integrador prohíbe pedirle al usuario la cantidad de registros. ¿Cómo se averigua?',
   opts: ['Leyendo el archivo dos veces', 'Con fseek al final, ftell para saber el tamaño en bytes, rewind para volver al principio, y dividiendo por sizeof del registro', 'Con strlen del archivo', 'Contando con feof'],
   c: 1,
   ex: '<span class="code">fseek(archivo, 0, SEEK_END)</span> lleva el cursor al final ▸ <span class="code">ftell</span> devuelve la posición del cursor, que estando al final <b>es el tamaño en bytes</b> ▸ <span class="code">rewind</span> lo vuelve al principio, y ésta es la línea que más se olvida: sin ella el <span class="code">fread</span> siguiente lee desde el final y no trae nada, con el síntoma engañoso de "el archivo está vacío" ▸ la división por <span class="code">sizeof(t_socio)</span> da la cantidad exacta. ▸ Leerlo dos veces funcionaría pero es el doble de trabajo, y con <span class="code">feof</span> tendrías que contar de a un registro para después volver a empezar.'},

  {st: 'El struct t_socio tiene un int, un char[41], un char[16] y un float. La suma da 65, pero sizeof devuelve 68 y reservar 6 registros pide 408 bytes. ¿Por qué?',
   opts: ['Porque malloc reserva de más', 'Por el padding: el compilador agrega 3 bytes de relleno para que el float arranque en una dirección múltiplo de 4', 'Porque el char[41] ocupa 44', 'Es un error del programa'],
   c: 1,
   ex: 'El compilador alinea los campos: 4 + 41 + 16 = 61 bytes hasta el <span class="code">float</span>, que necesita arrancar en un múltiplo de 4, así que se agregan <b>3 bytes de relleno</b> y el struct queda en <b>68</b>. ▸ Por eso la reserva se escribe siempre <span class="code">malloc(cantidad * sizeof(t_socio))</span> y nunca con la suma de los campos calculada a mano. ▸ Y la misma cuenta explica el archivo: 6 registros × 68 = 408 bytes, no 390.'},

  {st: 'Después de ordenar por cuota descendente, el punto 4b pide el socio de cuota más alta. ¿Qué hacés?',
   opts: ['Recorrer el vector buscando el máximo', 'Devolver socios[0]: el vector ya está ordenado por esa clave, así que el máximo es el primero', 'Ordenar de nuevo', 'Usar búsqueda binaria'],
   c: 1,
   ex: 'Los puntos de un integrador <b>dependen unos de otros</b>, y ésa es la diferencia con un parcial de ejercicios sueltos. Como el punto 3 ordenó por cuota descendente, el máximo quedó en la posición 0. ▸ Recorrer buscando el máximo no está mal —da el mismo resultado— pero delata que no viste la dependencia. ▸ Y en el caso inverso el descuido sí da mal: buscar binariamente por número de socio en un vector ordenado por cuota devuelve "no encontrado" sobre un socio que está.'},

  {st: 'En la salida del integrador, Benítez y Escalante tienen los dos cuota 32000 y después de ordenar Benítez sigue primero, como en el archivo. ¿Por qué?',
   opts: ['Por casualidad', 'Porque la inserción directa con < estricto en la condición del while es estable: no reordena los elementos empatados', 'Porque Benítez es alfabéticamente menor', 'Porque el archivo se leyó en ese orden y el ordenamiento no funcionó'],
   c: 1,
   ex: 'La condición es <span class="code">while (j &gt;= 0 &amp;&amp; socios[j].cuota &lt; actual.cuota)</span>: el elemento que está en el vector se corre <b>sólo si es estrictamente menor</b>. Ante un empate, el ciclo corta y el nuevo queda <b>detrás</b> del que ya estaba. Eso es <b>estabilidad</b>. ▸ Con <span class="code">&lt;=</span> los empatados se darían vuelta en cada inserción. ▸ Y no es un detalle cosmético: si el informe pide "a igual cuota, primero el que se dio de alta antes", la estabilidad <b>es</b> la respuesta correcta, y se consigue con un carácter.'},

  {st: 'El punto 5 pide generar morosos.txt. ¿Con qué se escribe?',
   opts: ['Con fwrite del struct completo', 'Con fprintf y formato, abriendo en modo "wt": es un archivo de texto que tiene que poder abrirse con un editor', 'Con printf redirigido', 'Con fputc carácter por carácter'],
   c: 1,
   ex: 'Un <span class="code">.txt</span> es <b>texto</b>: se escribe con <span class="code">fprintf</span>, que es igual a <span class="code">printf</span> pero con el archivo como primer parámetro. ▸ Volcarlo con <span class="code">fwrite</span> del struct generaría un archivo con el nombre correcto y el contenido equivocado: bytes crudos, ilegibles en un editor, con el padding incluido. ▸ <span class="code">fputc</span> funcionaría pero carácter por carácter, sin formato: perderías el <span class="code">%.2f</span> de la cuota. ▸ Y la simetría para leerlo después es <span class="code">fgets</span> línea por línea, no <span class="code">fread</span>.'},

  {st: 'Escribís <span class="code">socios = realloc(socios, nueva_capacidad * sizeof(t_socio));</span> ¿Qué tiene de malo?',
   opts: ['Nada, es la forma normal', 'Si realloc falla devuelve NULL y al asignarlo perdés el puntero al bloque anterior: la memoria queda reservada y sin dueño. El resultado va a un auxiliar que se verifica antes de reemplazar', 'realloc no se puede usar con structs', 'Falta el cast'],
   c: 1,
   ex: 'Es la fuga de memoria más clásica de C y se escribe así en la mitad de los ejemplos que circulan. ▸ Cuando <span class="code">realloc</span> no consigue el bloque nuevo, devuelve <span class="code">NULL</span> <b>y deja el bloque viejo intacto</b>. Si asignás ese <span class="code">NULL</span> sobre tu única referencia, el bloque viejo queda reservado y sin forma de liberarlo. ▸ La forma correcta: <span class="code">auxiliar = realloc(socios, …); if (auxiliar == NULL) { free(socios); … } socios = auxiliar;</span> ▸ Y el dato que hace el patrón cómodo: <span class="code">realloc(NULL, n)</span> se comporta como <span class="code">malloc(n)</span>, así que el puntero puede arrancar en <span class="code">NULL</span> sin ningún caso especial.'},
]);
