registerExercises('criminologia-ii', '1', [
  {st: 'Según Foucault, en <i>La verdad y las formas jurídicas</i>, la verdad jurídica es:', opts: ['Un dato natural que la ley descubre', 'Un resultado de prácticas sociales e institucionales históricamente variables', 'Una propiedad exclusiva del juez profesional', 'Equivalente al consenso de la mayoría'], c: 1, ex: 'Foucault sostiene que cada sociedad, en cada época, construye las formas de determinar qué es verdad. Las prácticas judiciales son espacios donde se produce esa verdad, no donde se la descubre.'},
  {st: '¿Qué régimen de verdad jurídica se corresponde con la Edad Media según Foucault?', opts: ['Prueba-desafío (ordalía, combate, juramento)', 'Indagación (el soberano reconstruye un hecho pasado)', 'Examen (se busca conocer al sujeto)', 'Confesión libre'], c: 1, ex: 'En la Edad Media aparece la indagación: una autoridad centralizada (el rey) interroga testigos para reconstruir el hecho. Es el modelo del saber moderno y el antecedente del juicio.'},
  {st: 'La disciplina moderna, según Foucault, se distingue del suplicio del Antiguo Régimen porque:', opts: ['Es más cruel y más visible', 'Es más oculta, continua y normalizadora, y apunta al alma más que al cuerpo', 'Se aplica solo a los más pobres', 'Elimina el castigo'], c: 1, ex: 'Foucault describe el pasaje del suplicio público (poder soberano visible) a la prisión disciplinaria (poder continuo e invisible que busca corregir al sujeto). No se castiga menos: se castiga mejor.'},
  {st: 'El panóptico de Bentham, para Foucault, es:', opts: ['Un invento técnico superado por las cámaras', 'Una metáfora de la lógica de vigilancia moderna donde el vigilado se autovigila', 'El diseño original de la cárcel de Alcatraz', 'Una crítica al sistema feudal'], c: 1, ex: 'El panóptico es la figura ideal del poder disciplinario: muchos vigilados, uno que puede ver sin ser visto. Su efecto central es que el vigilado internaliza la mirada y se controla a sí mismo.'},
  {st: '¿Qué concepto agrega Foucault a la disciplina para explicar el control de poblaciones enteras?', opts: ['Biopoder', 'Panóptico', 'Inquisición', 'Estado de derecho'], c: 0, ex: 'El biopoder se ocupa de la gestión de la vida a escala poblacional: natalidad, salud, higiene, raza. Complementa la disciplina individual con la regulación colectiva.'}
]);

registerExercises('criminologia-ii', '2', [
  {st: '¿En qué año publica Beccaria <i>De los delitos y de las penas</i>?', opts: ['1689', '1764', '1810', '1876'], c: 1, ex: 'Beccaria publica su obra en 1764, en plena Ilustración. Es un texto fundacional del derecho penal moderno.'},
  {st: 'Según Beccaria, lo que más previene el delito es:', opts: ['La severidad extrema de la pena', 'La certeza y la prontitud de la pena', 'El tamaño de la cárcel', 'El perdón del soberano'], c: 1, ex: 'Beccaria sostiene que una pena moderada pero segura y rápida disuade más que una pena brutal pero improbable. La certeza supera a la severidad.'},
  {st: 'Beccaria se opone a la pena de muerte principalmente porque:', opts: ['Es ineficaz y carece de legitimidad en el contrato social', 'Es muy cara', 'Solo se aplica a los pobres', 'Contradice la religión católica'], c: 0, ex: 'Beccaria argumenta que nadie cedió al Estado el derecho sobre su propia vida (argumento contractualista) y que la pena perpetua disuade más que la muerte (argumento utilitario).'},
  {st: 'El supuesto antropológico de la escuela clásica es un sujeto:', opts: ['Determinado biológicamente', 'Libre, racional y calculador', 'Subordinado al inconsciente', 'Producto de la clase social'], c: 1, ex: 'Para el clasicismo el delincuente es un sujeto libre que calcula costos y beneficios. Por eso la respuesta es la pena proporcional: desalentar el cálculo.'},
  {st: 'El principio "nullum crimen, nulla poena sine lege" significa:', opts: ['Ninguna pena puede ser menor a la establecida', 'No hay delito ni pena sin ley previa', 'El juez decide la pena libremente', 'Toda ley debe ser retroactiva'], c: 1, ex: 'Es el principio de legalidad estricta que impone la escuela clásica: solo la ley previa puede crear delitos y penas. Es base de todas las constituciones modernas.'},
  {st: 'Una limitación central de la escuela clásica es que:', opts: ['Niega el contrato social', 'Al suponer sujetos iguales y libres, invisibiliza desigualdades sociales y causas del delito', 'Propone penas demasiado leves', 'No distingue delito de pecado'], c: 1, ex: 'Al centrarse en el acto y asumir igualdad formal, la escuela clásica no explica por qué delinquen unos más que otros. De esa carencia surge la reacción positivista.'}
]);

registerExercises('criminologia-ii', '3', [
  {st: 'Según Vidaurri, la criminología es:', opts: ['Una rama del derecho penal', 'Una ciencia empírica e interdisciplinaria que estudia el fenómeno delictivo', 'La rama judicial que dicta sentencias', 'Un saber exclusivamente biológico'], c: 1, ex: 'Vidaurri define a la criminología como ciencia empírica e interdisciplinaria: estudia la realidad del delito, el delincuente, la víctima y el control social. Se distingue del derecho penal, que estudia la norma.'},
  {st: 'Los cuatro objetos clásicos de la criminología son:', opts: ['Delito, delincuente, víctima y control social', 'Policía, fiscal, juez y cárcel', 'Ley, acto, culpa y pena', 'Estado, mercado, familia y escuela'], c: 0, ex: 'Son los cuatro objetos que organiza Vidaurri. La víctima fue incorporada tardíamente (victimología, años 60) y el control social es lo que incluye las respuestas institucionales y sociales.'},
  {st: 'La "cifra negra" en criminología designa:', opts: ['El total de condenas por año', 'Los delitos no denunciados o no registrados', 'La tasa de reincidencia', 'Las estadísticas del Poder Judicial'], c: 1, ex: 'La cifra negra (Dunkelfeld) es el conjunto de hechos delictivos que nunca llegan al sistema oficial. Por eso las estadísticas oficiales son parciales y se complementan con encuestas de victimización.'},
  {st: '¿Cuál de estas corrientes centra su análisis en los procesos de criminalización y no en el delincuente?', opts: ['Criminología clínica', 'Criminología sociológica', 'Criminología crítica', 'Criminología positivista'], c: 2, ex: 'La criminología crítica se pregunta quién define qué es delito y cómo se aplica esa definición, desplazando el foco del sujeto desviado al aparato que lo produce.'},
  {st: 'La criminología clínica tiene raíz en:', opts: ['La escuela clásica', 'El positivismo biológico y el estudio del individuo delincuente', 'El marxismo estructural', 'La fenomenología'], c: 1, ex: 'La criminología clínica surge del positivismo: foco en el sujeto delincuente, diagnóstico, pronóstico y tratamiento. Es la vertiente más ligada a psiquiatría y medicina.'}
]);

registerExercises('criminologia-ii', '4', [
  {st: '¿Qué concepto central introduce Lombroso en <i>L\'uomo delinquente</i> (1876)?', opts: ['La elección racional', 'El delincuente nato como atavismo biológico', 'La anomia estructural', 'El contrato social'], c: 1, ex: 'Lombroso postula que el criminal es un atavismo: un regreso evolutivo con estigmas físicos identificables. La tesis biológica está refutada, pero inaugura el estudio empírico del delincuente.'},
  {st: 'La "ley de saturación criminal" fue propuesta por:', opts: ['Lombroso', 'Enrico Ferri', 'Garófalo', 'Beccaria'], c: 1, ex: 'Ferri sostiene que cada sociedad tiene un nivel "normal" de delito ligado a condiciones dadas. De ahí los sustitutivos penales: mejor prevenir modificando condiciones sociales que castigar.'},
  {st: 'Garófalo aporta al positivismo el concepto de:', opts: ['Subcultura', 'Delito natural y peligrosidad (temibilitá)', 'Panóptico', 'Desistimiento'], c: 1, ex: 'Garófalo define delito natural como atentado a los sentimientos de piedad y probidad, y propone la peligrosidad (temibilitá) como medida de la pena.'},
  {st: 'La gran ruptura de la escuela positiva respecto de la clásica consiste en:', opts: ['Bajar las penas', 'Pasar de una criminología del acto a una criminología del autor', 'Eliminar el contrato social', 'Despenalizar el robo'], c: 1, ex: 'La clásica se centra en el acto libre; la positiva en el autor peligroso. Esa es la fractura central entre ambas escuelas y explica todo el conflicto político-penal del siglo XX.'},
  {st: 'La Escuela de Chicago estudia el delito como fenómeno:', opts: ['Hereditario', 'Urbano y ecológico (zonas concéntricas, desorganización social)', 'Exclusivamente religioso', 'Genético'], c: 1, ex: 'Park, Burgess, Shaw y McKay analizan la ciudad como ecosistema. Las zonas de transición, con fuerte inmigración y deterioro, concentran delito por desorganización de los controles informales.'},
  {st: 'La teoría de la desorganización social explica que:', opts: ['Los migrantes son más delictivos', 'Ciertas zonas urbanas mantienen tasas altas de delito aunque cambie su población por la debilidad de los controles informales', 'El delito es genético en algunos barrios', 'No hay delincuencia en zonas residenciales'], c: 1, ex: 'Shaw y McKay observan que las tasas persisten aunque cambie quién vive ahí: el problema está en el barrio y sus redes, no en los individuos.'}
]);

registerExercises('criminologia-ii', '5', [
  {st: 'Según Bandura, el aprendizaje social implica que la conducta delictiva se adquiere:', opts: ['Por contagio biológico', 'Por observación e imitación de modelos', 'Por traumas inconscientes exclusivos', 'Por mutación genética'], c: 1, ex: 'Bandura muestra con sus experimentos que conductas complejas se aprenden observando modelos significativos. El delito sigue la misma lógica que otros aprendizajes.'},
  {st: 'La PCL-R (Psychopathy Checklist-Revised) fue desarrollada por:', opts: ['Freud', 'Robert Hare', 'Lombroso', 'Eysenck'], c: 1, ex: 'Robert Hare construyó la PCL-R, instrumento estándar para evaluar psicopatía, con 20 ítems organizados en dos factores (interpersonal-afectivo y conducta antisocial).'},
  {st: 'Una afirmación correcta sobre psicopatía es:', opts: ['Todo delincuente violento es psicópata', 'La psicopatía es un trastorno de personalidad con déficits afectivos e interpersonales; no coincide con delincuencia', 'Los psicópatas no se pueden identificar', 'Todos los psicópatas delinquen'], c: 1, ex: 'Psicopatía y delincuencia no coinciden: hay psicópatas no delincuentes y delincuentes no psicópatas. La psicopatía describe un perfil de personalidad con déficits empáticos centrales.'},
  {st: 'La teoría de Eysenck sobre personalidad y delito combina:', opts: ['Psicoanálisis y sociología', 'Biología y aprendizaje (condicionamiento)', 'Marxismo y fenomenología', 'Religión y derecho'], c: 1, ex: 'Eysenck propone que sujetos con alto neuroticismo y alta extraversión condicionan peor las respuestas inhibitorias y tienden más al delito. Integra biología y aprendizaje.'},
  {st: 'Bowlby asocia con la conducta antisocial posterior:', opts: ['La lectura temprana', 'La ruptura del vínculo madre-hijo en la infancia', 'La clase social baja', 'El bajo CI'], c: 1, ex: 'Bowlby mostró en estudios longitudinales cómo la discontinuidad del apego temprano se asocia a trastornos de conducta y dificultades para la regulación afectiva.'},
  {st: 'La diferencia entre trastorno antisocial de la personalidad (TAP, DSM) y psicopatía (PCL-R) es que:', opts: ['Son sinónimos', 'TAP se basa en conductas observables; psicopatía incluye además dimensión afectiva e interpersonal', 'La psicopatía es más frecuente que el TAP en la cárcel', 'Solo la psicopatía es diagnosticable en mujeres'], c: 1, ex: 'El TAP del DSM se apoya en conductas; la PCL-R agrega déficits afectivos e interpersonales (falta de empatía, manipulación, superficialidad). La psicopatía es más restringida.'}
]);

registerExercises('criminologia-ii', '6', [
  {st: '¿En qué año se fundó el Instituto de Criminología en la Penitenciaría Nacional argentina?', opts: ['1880', '1907', '1921', '1946'], c: 1, ex: 'José Ingenieros funda el Instituto de Criminología en 1907, primero de su tipo en América Latina. Fue sede de estudios clínicos sobre condenados durante décadas.'},
  {st: 'José Ingenieros clasifica a los delincuentes según:', opts: ['El tipo de delito', 'Anomalías morales, intelectuales y volitivas', 'La clase social', 'La nacionalidad de origen'], c: 1, ex: 'Ingenieros mezcla biología, psicología y sociología. Clasifica por anomalías morales (sin sentido ético), intelectuales (dementes, oligofrénicos) y volitivas (impulsivos).'},
  {st: '¿Cuál de estas obras es de Ingenieros?', opts: ['<i>Criminología</i> (1916)', '<i>El criminal nato</i>', '<i>Vigilar y castigar</i>', '<i>El hombre delincuente</i>'], c: 0, ex: '<i>Criminología</i> (1916) es una de las obras centrales de Ingenieros. Las otras pertenecen a Lombroso o Foucault, no a Ingenieros.'},
  {st: 'La tensión ideológica central de la criminología argentina positivista fue:', opts: ['Entre liberalismo y religión', 'Entre programa humanitario de prevención social y efectos de control sobre pobres e inmigrantes', 'Entre marxismo y capitalismo', 'Entre derecho canónico y civil'], c: 1, ex: 'La criminología argentina de principios del XX combinaba la aspiración humanitaria (prevención, educación, trabajo) con la patologización de inmigrantes y sectores populares en las tipologías clínicas.'},
  {st: 'Eugenio Raúl Zaffaroni se asocia en Argentina con:', opts: ['El positivismo biológico', 'La criminología crítica y el derecho penal humanista', 'La Escuela de Chicago', 'El realismo de derecha'], c: 1, ex: 'Zaffaroni es la figura más destacada de la criminología crítica argentina y de una dogmática penal con fuerte énfasis en derechos humanos.'}
]);

registerExercises('criminologia-ii', '7', [
  {st: 'Según López Puerta, el control social informal está formado por:', opts: ['Policía y cárcel', 'Familia, escuela, religión, trabajo y redes comunitarias', 'Solo el derecho penal', 'Las Fuerzas Armadas'], c: 1, ex: 'El control social informal son las instancias socializadoras primarias y secundarias. Operan mediante interiorización de normas, son más efectivas y silenciosas que el formal.'},
  {st: 'El control social formal entra en juego:', opts: ['Siempre primero', 'Cuando fallan los controles informales', 'Solo en regímenes autoritarios', 'Nunca en democracia'], c: 1, ex: 'El formal (policía, justicia, cárcel) se activa cuando los controles informales no alcanzaron para sostener la conformidad. Reforzar solo el formal sin recuperar el informal es ineficaz.'},
  {st: 'Durkheim define "anomia" como:', opts: ['Ausencia total de reglas', 'Estado de desregulación y pérdida de legitimidad normativa en sociedades en transición', 'Una psicosis individual', 'Una subcultura delictiva'], c: 1, ex: 'Anomia para Durkheim no es falta de normas sino normas contradictorias, debilitadas o no legitimadas. Suele aparecer en cambios sociales rápidos.'},
  {st: 'En la teoría de Merton, el modo de adaptación "innovación" es:', opts: ['Aceptar fines y medios legítimos', 'Aceptar los fines culturales pero rechazar los medios legítimos', 'Rechazar fines y medios', 'Crear nuevos fines y nuevos medios'], c: 1, ex: 'Innovación = acepta el mandato de éxito pero lo busca con medios no legítimos (por ejemplo, fraude). Es la más criminógena de las adaptaciones.'},
  {st: 'Albert Cohen describe la subcultura delictiva juvenil como:', opts: ['Conducta utilitaria racional', 'Reacción formativa frente al fracaso en la escala escolar de clase media', 'Imitación directa del cuello blanco', 'Resultado genético'], c: 1, ex: 'Cohen muestra delincuencia juvenil "no utilitaria, maliciosa y negativista": invierte los valores de clase media como reacción a la humillación del fracaso escolar.'},
  {st: 'Un cuadro de anomia estructural en América Latina, según Huertas Díaz, se caracteriza por:', opts: ['Excelente acceso a medios legítimos', 'Desigualdad extrema y Estados débiles que producen anomia permanente', 'Ausencia total de conflicto social', 'Conformidad generalizada'], c: 1, ex: 'Huertas Díaz relee a Merton para contextos donde el Estado ni garantiza fines ni provee medios legítimos: la anomia se vuelve estructural y permanente, no coyuntural.'}
]);

registerExercises('criminologia-ii', '8', [
  {st: 'La pregunta invertida de Hirschi es:', opts: ['¿Por qué delinquen algunos?', '¿Por qué la mayoría no delinque?', '¿Por qué las leyes son injustas?', '¿Por qué hay cárcel?'], c: 1, ex: 'Hirschi cambia el planteo tradicional. Asume que delinquir puede ser atractivo y pregunta qué nos frena: los vínculos sociales.'},
  {st: 'Los cuatro vínculos sociales de Hirschi son:', opts: ['Familia, iglesia, escuela, vecinos', 'Apego, compromiso, participación y creencia', 'Educación, trabajo, religión, ocio', 'Policía, juez, cárcel, libertad condicional'], c: 1, ex: 'Hirschi postula cuatro dimensiones: apego (attachment), compromiso (commitment), participación (involvement) y creencia (belief). Todos inhiben el delito cuando están fuertes.'},
  {st: 'El concepto central de la "Teoría general del delito" de Gottfredson y Hirschi es:', opts: ['Alta empatía', 'Baja autocontrol (low self-control) como rasgo estable desde la infancia', 'Herencia genética directa', 'Pobreza absoluta'], c: 1, ex: 'Postulan que la baja autocontrol —formada por la crianza— predispone al delito y a conductas imprudentes en general (adicciones, accidentes, abandono escolar).'},
  {st: 'El estudio de Cambridge de David Farrington siguió:', opts: ['A 100 mujeres por 5 años', 'A 411 varones londinenses desde los 8 años durante décadas', 'A jueces en ejercicio', 'A policías retirados'], c: 1, ex: 'El Cambridge Study in Delinquent Development siguió a 411 varones desde los 8 años. Es la base empírica más citada de la Developmental and Life-Course Criminology.'},
  {st: 'Según los hallazgos de Moffitt y la DLC, aproximadamente:', opts: ['Todos los que delinquen siguen haciéndolo de adultos', 'Un 6% de "life-course persistent" explica cerca de la mitad de los delitos', 'Nadie desiste del delito', 'Los "adolescence-limited" son los más violentos'], c: 1, ex: 'El grupo persistente ("life-course persistent") es minoritario pero concentra gran parte del delito; los "adolescence-limited" delinquen en adolescencia y desisten solos.'},
  {st: 'Los "puntos de inflexión" (turning points) de Sampson y Laub son:', opts: ['Sentencias firmes', 'Vínculos adultos como matrimonio estable, trabajo fijo o servicio militar que reorganizan la vida', 'Castigos corporales', 'Cambios de residencia aleatorios'], c: 1, ex: 'Los turning points funcionan cuando generan supervisión, rutina y redes pro-sociales. Por sí solos no curan nada: lo hacen las nuevas dinámicas que habilitan.'}
]);

registerExercises('criminologia-ii', '9', [
  {st: 'La teoría de la asociación diferencial de Sutherland sostiene que:', opts: ['El delito es hereditario', 'El delito se aprende en interacción comunicativa con otros, sobre todo en grupos íntimos', 'El delito es fruto exclusivo de la pobreza', 'El delito no se puede explicar'], c: 1, ex: 'Nueve proposiciones enumeran que la conducta delictiva es aprendida, se da en grupos íntimos, incluye técnicas y motivos, y depende del balance de "definiciones" favorables o desfavorables a la ley.'},
  {st: 'El principio clave de la asociación diferencial es:', opts: ['Un sujeto delinque cuando pertenece a una clase social pobre', 'Un sujeto delinque cuando en su entorno predominan las definiciones favorables al delito sobre las desfavorables', 'Un sujeto delinque cuando es víctima', 'Un sujeto delinque por trauma infantil exclusivo'], c: 1, ex: 'La ecuación decisiva es el balance entre definiciones favorables y desfavorables a la ley en los grupos de pertenencia. Explica tanto al delincuente callejero como al corporativo.'},
  {st: 'Sutherland acuña el término "delito de cuello blanco" en:', opts: ['1880', '1940', '1970', '2000'], c: 1, ex: 'Sutherland introduce "white-collar crime" en una conferencia de la Sociedad Americana de Sociología en 1939, con desarrollo publicado al año siguiente.'},
  {st: 'El delito de cuello blanco se define como:', opts: ['Cualquier delito grave', 'Delito cometido por persona respetable y de alto estatus social en el curso de su ocupación', 'Delito en barrios pobres', 'Delito juvenil'], c: 1, ex: 'Lo distintivo del cuello blanco es el estatus del autor y que ocurre en el ejercicio de su actividad profesional o empresarial. Incluye fraude, evasión, corrupción, etc.'},
  {st: 'Las tres condiciones del fraude ocupacional según Donald Cressey son:', opts: ['Pobreza, bajo CI y falta de educación', 'Presión financiera no compartible, oportunidad y racionalización', 'Juventud, rebeldía y drogas', 'Mentira, engaño y astucia'], c: 1, ex: 'El "triángulo del fraude" de Cressey integra la presión no compartible, la oportunidad percibida y la racionalización ("se lo devuelvo", "todos lo hacen").'},
  {st: 'Una consecuencia política de la tesis de Sutherland es:', opts: ['Endurecer las penas del delito callejero', 'Reconocer que las estadísticas oficiales subrepresentan el crimen empresarial y profesional', 'Despenalizar todo delito económico', 'Abolir el sistema penal'], c: 1, ex: 'Si solo se persigue el delito callejero, la estadística presenta la criminalidad como problema de pobres. El cuello blanco es masivo, costoso y en gran parte invisible.'}
]);

registerExercises('criminologia-ii', '10', [
  {st: 'La criminología crítica desplaza el foco de análisis hacia:', opts: ['La biología del delincuente', 'Los procesos de criminalización primaria y secundaria', 'Las víctimas en sentido psicológico', 'La elección racional'], c: 1, ex: 'Baratta y la criminología crítica dejan de preguntar "por qué delinque este sujeto" y preguntan "por qué este acto es definido como delito y perseguido selectivamente".'},
  {st: 'La criminalización primaria es:', opts: ['La actividad policial', 'La definición legal de qué es delito mediante leyes penales', 'La condena en un juicio', 'La detención preventiva'], c: 1, ex: 'La primaria es la ley penal: qué se decide definir como delito. La secundaria es la selección que hacen policía y justicia al aplicar esa ley.'},
  {st: 'La criminalización secundaria es:', opts: ['La selección que realizan policía, fiscalía y jueces al aplicar la ley', 'La tipificación legal', 'La promulgación de leyes', 'La reincidencia del condenado'], c: 0, ex: 'Secundaria = práctica policial-judicial concreta: a quién se investiga, detiene, procesa y condena. También es selectiva (clase, raza, género).'},
  {st: 'La tesis central de Baratta sobre el sistema penal es que:', opts: ['Persigue delitos de forma neutral', 'Reproduce desigualdades sociales seleccionando a los "clientes" habituales (pobres, jóvenes, racializados)', 'Funciona bien en América Latina', 'Debería reemplazar al derecho civil'], c: 1, ex: 'Baratta muestra que el sistema penal es estructuralmente selectivo. No persigue "al delincuente" en general, produce un tipo de clientela.'},
  {st: 'El concepto de "etiquetamiento" o labeling approach implica que:', opts: ['Todos somos etiquetados por igual', 'La etiqueta social produce desviación secundaria y reorganiza la identidad del sujeto', 'Las etiquetas desaparecen tras la condena', 'Solo los jueces pueden etiquetar'], c: 1, ex: 'Becker y Lemert muestran que la etiqueta no solo describe: produce. El sujeto procesado reorganiza su identidad alrededor de la etiqueta y tiende a confirmarla (desviación secundaria).'},
  {st: 'Los principios de mínimo derecho penal que propone Baratta incluyen:', opts: ['Máxima expansión punitiva', 'Legalidad estricta, subsidiariedad, proporcionalidad, humanidad y protección de bienes jurídicos efectivos', 'Pena de muerte para reincidentes', 'Supresión de defensa técnica'], c: 1, ex: 'Baratta propone contener el daño del sistema con principios mínimos. Son garantías para reducir la violencia estatal sin abolirla de golpe.'}
]);

registerExercises('criminologia-ii', '11', [
  {st: 'La teoría de "broken windows" (Wilson y Kelling, 1982) sostiene que:', opts: ['Los edificios viejos son más seguros', 'Los pequeños desórdenes no atendidos señalan ausencia de control y habilitan escaladas delictivas', 'La policía no debe intervenir en incivilidades', 'La violencia es siempre genética'], c: 1, ex: 'Wilson y Kelling sostienen que pequeños indicios de desorden (grafitis, vagancia, vidrios rotos) transmiten que "nadie vigila" y favorecen mayor deterioro. De ahí surge la política de "tolerancia cero".'},
  {st: 'Una crítica a la política de "tolerancia cero" aplicada en Nueva York es que:', opts: ['Es demasiado blanda', 'Generó criminalización de pobres y uso abusivo de la fuerza policial', 'No produjo ningún efecto medible', 'Solo se aplicó en Europa'], c: 1, ex: 'La implementación neoyorquina bajo Bratton generó graves costos democráticos: hostigamiento de minorías y abuso policial. El efecto sobre el delito es discutido por la literatura.'},
  {st: 'El realismo de izquierda (Young, Lea, Matthews) propone:', opts: ['Negar que haya víctimas', 'Tomarse el delito en serio reconociendo que las víctimas suelen ser pobres y atender al "cuadrado del delito" (víctima, ofensor, Estado, público)', 'Eliminar la policía', 'Aumentar solo las penas'], c: 1, ex: 'El realismo de izquierda rechaza romantizar al delincuente: las víctimas del delito callejero son mayoritariamente pobres. Propone reforma policial democrática y participación comunitaria.'},
  {st: 'La elección racional de Cornish y Clarke asume un sujeto:', opts: ['Con cálculo perfecto', 'Con racionalidad limitada que decide entre involucrarse y cometer el evento', 'Determinado biológicamente', 'Irracional puro'], c: 1, ex: 'La rational choice asume un decisor real, con información parcial, decisiones rápidas. Distingue la decisión de involucramiento (entrar a la carrera delictiva) y la decisión de evento concreto.'},
  {st: 'La prevención situacional busca:', opts: ['Modificar la personalidad del delincuente', 'Modificar el entorno para aumentar esfuerzo y riesgo, y reducir recompensas y provocaciones', 'Aumentar las penas', 'Recolocar la policía en barrios ricos'], c: 1, ex: 'Clarke sistematiza 25 técnicas agrupadas en cinco categorías: aumentar esfuerzo, aumentar riesgo, reducir recompensa, reducir provocaciones y quitar excusas. Intervienen sobre la oportunidad.'},
  {st: 'La teoría de las actividades rutinarias (Cohen y Felson) afirma que para que ocurra delito deben converger:', opts: ['Hambre, frío y aburrimiento', 'Delincuente motivado, blanco adecuado y ausencia de guardián capaz', 'Juez, fiscal y defensor', 'Policía, cámara y ley'], c: 1, ex: 'Los tres elementos convergen en tiempo y espacio. Cambios en las rutinas sociales modifican la probabilidad del delito sin necesidad de suponer más delincuentes motivados.'}
]);

registerExercises('criminologia-ii', '12', [
  {st: '¿Qué autora sistematizó las primeras críticas feministas a la criminología tradicional en los años 70?', opts: ['Kimberlé Crenshaw', 'Carol Smart', 'Hannah Arendt', 'Judith Butler'], c: 1, ex: 'Carol Smart en <i>Women, Crime and Criminology</i> (1976) denuncia el androcentrismo disciplinar y la condescendencia con que se trataba a la mujer delincuente.'},
  {st: 'El concepto de "interseccionalidad" fue acuñado por:', opts: ['Kimberlé Crenshaw', 'Pat Carlen', 'Elena Larrauri', 'Foucault'], c: 0, ex: 'Crenshaw introduce "intersectionality" en 1989. La tesis: género, raza y clase no se suman, se cruzan produciendo experiencias singulares que ningún movimiento unidimensional captura.'},
  {st: 'La "doble sanción" que describe Pat Carlen se refiere a:', opts: ['Dos condenas penales consecutivas', 'Sanción por el delito y sanción simbólica por transgredir el mandato de género', 'Cárcel más multa', 'Condena civil y penal'], c: 1, ex: 'Las mujeres en prisión son penalizadas dos veces: por el hecho y por romper con las expectativas del rol femenino (madre, cuidadora, sumisa).'},
  {st: 'En Argentina, la Ley 26.791 (2012) incorpora al Código Penal:', opts: ['La pena de muerte', 'El femicidio como agravante del homicidio', 'La tenencia de estupefacientes', 'La trata de personas'], c: 1, ex: 'La 26.791 modifica el artículo 80 del CP y agrega el inciso 11°: "a una mujer cuando el hecho sea perpetrado por un hombre y mediare violencia de género", como agravante.'},
  {st: 'La Ley 26.485 (2009) argentina se refiere a:', opts: ['Régimen penal juvenil', 'Protección integral para prevenir, sancionar y erradicar la violencia contra las mujeres', 'Delitos informáticos', 'Ley de alquileres'], c: 1, ex: 'La 26.485 establece un marco amplio de protección: define tipos (física, psicológica, sexual, económica, simbólica) y modalidades (doméstica, institucional, laboral, contra la libertad reproductiva, obstétrica, mediática).'},
  {st: '"Victimización secundaria" en delitos sexuales significa:', opts: ['Sufrir dos delitos', 'Revictimización por el propio sistema penal durante la denuncia, pericias y proceso', 'Ser testigo de un delito', 'Una segunda condena'], c: 1, ex: 'Victimización secundaria: el sistema penal, con interrogatorios invasivos, descrédito y repetición de testimonios, daña nuevamente a la víctima. Los protocolos con perspectiva de género buscan reducirla.'}
]);

registerExercises('criminologia-ii', '13', [
  {st: 'La Convención de Palermo (2000) define grupo delictivo organizado como:', opts: ['Dos personas con cualquier objetivo', 'Tres o más personas, estable en el tiempo, que actúa concertadamente para cometer delitos graves con fin de beneficio económico o material', 'Un grupo político', 'Una sociedad anónima'], c: 1, ex: 'La definición internacional del Protocolo contra la Delincuencia Organizada Transnacional fija estos cuatro elementos: tres o más personas, estabilidad temporal, concertación y finalidad económica.'},
  {st: 'Según Marcelo Sain, la delincuencia organizada en Argentina se distingue de la común porque:', opts: ['Es más antigua', 'Requiere regulación policial y connivencia estatal para operar', 'No usa violencia', 'Tiene menor impacto económico'], c: 1, ex: 'Tesis central de Sain: los mercados ilegales durables (narco, trata, juego, desarmaderos) no funcionan sin complicidad estatal. Por eso la reforma policial es política criminal prioritaria.'},
  {st: 'La diferencia entre "criminogénesis" y "criminodinámica" (Rodríguez Manzanera) es que:', opts: ['Son sinónimos', 'La génesis explica las causas de fondo; la dinámica describe el proceso concreto que actualiza esas causas en un acto', 'La génesis es legal y la dinámica ilegal', 'Una es genética, otra psicológica'], c: 1, ex: 'Rodríguez Manzanera separa causas (genéticas, psicológicas, sociales) del proceso concreto que las articula en una conducta delictiva específica. Una responde "por qué en general", la otra "cómo en este caso".'},
  {st: 'Los factores endógenos en la criminología de Rodríguez Manzanera son:', opts: ['Ambientales y sociales', 'Biológicos y psicológicos internos del sujeto', 'Políticos', 'Económicos globales'], c: 1, ex: 'Endógenos = internos del sujeto (biología, personalidad, aprendizaje). Exógenos = externos (ambiente, cultura, economía, Estado). Distinción clásica que organiza el análisis multicausal.'},
  {st: 'Para García-Pablos de Molina, el crimen organizado se describe como:', opts: ['Una enfermedad mental', 'Una subcultura con valores alternativos, lealtades internas, códigos y ritos de iniciación', 'Una religión', 'Una anomalía genética'], c: 1, ex: 'García-Pablos describe el crimen organizado como subcultura: sistema axiológico propio, jerarquías, códigos de silencio, rituales. Recluta donde los vínculos al Estado son débiles.'},
  {st: 'Zaffaroni llama al crimen organizado un "concepto frustrado" porque:', opts: ['No existe realmente', 'Su definición es imprecisa y variable, lo que legitima poderes de excepción sin control', 'Solo se aplica a mafias italianas', 'Está prohibido discutirlo'], c: 1, ex: 'Zaffaroni advierte que la indefinición sirve a la excepción: con un concepto vago, la respuesta estatal se expande (escuchas, agentes encubiertos, imputaciones amplias) con poco control.'}
]);

registerExercises('criminologia-ii', '14', [
  {st: 'El modelo jerárquico de crimen organizado se caracteriza por:', opts: ['Estructura piramidal con jefe, lugartenientes, operadores; territorio controlado por una organización', 'Células autónomas sin liderazgo', 'Financiamiento estatal directo', 'Acciones humanitarias'], c: 0, ex: 'Clásico ejemplo: Cosa Nostra, Yakuza, viejos carteles colombianos. Su fortaleza es la disciplina; su debilidad es que descabezar al jefe debilita toda la estructura.'},
  {st: 'El modelo de red según Garzón Vergara se caracteriza por:', opts: ['Liderazgo único', 'Múltiples nodos interconectados, estructura horizontal, alta resiliencia ante la caída de un nodo', 'Ausencia total de violencia', 'Dependencia de un solo país'], c: 1, ex: 'El modelo de red es adaptable y resistente: la caída de un nodo no derriba la red. Es característico del crimen organizado contemporáneo (post-Medellín).'},
  {st: 'Una implicancia estratégica central del modelo de red es que:', opts: ['Basta con capturar al jefe', 'Hay que desconectar nodos, seguir flujos financieros e intervenir en lavado, no solo "descabezar"', 'No se puede investigar', 'Hay que legalizarlo todo'], c: 1, ex: 'Las redes exigen inteligencia financiera, decomiso, seguimiento de flujos y cooperación internacional. La política de "capos" es eficaz para pirámides, inadecuada para redes.'},
  {st: 'Ordená las fases del ciclo de vida de una organización criminal según Garzón:', opts: ['Expansión → emergencia → conflicto → consolidación', 'Emergencia → consolidación → expansión → conflicto → adaptación o fragmentación', 'Solo tiene una fase', 'Conflicto → adaptación → muerte'], c: 1, ex: 'Garzón describe cinco fases: emergencia, consolidación, expansión, conflicto y adaptación o fragmentación. Cada una tiene lógicas de violencia y estrategias distintas.'},
  {st: 'Los cuatro componentes de un mercado ilegal sostenible son:', opts: ['Demanda, oferta, infraestructura y protección (corrupción o violencia privada)', 'Policía, juez, ley y cárcel', 'Familia, escuela, trabajo y religión', 'Libertad, igualdad, fraternidad y progreso'], c: 0, ex: 'Un mercado ilegal durable necesita demanda (consumidores), oferta (productores/traficantes), infraestructura (rutas, logística, finanzas) y protección (corrupción pública o violencia privada).'},
  {st: 'La "tercerización de la violencia" en el crimen organizado contemporáneo implica que:', opts: ['La violencia desaparece', 'Las organizaciones contratan sicarios puntuales en vez de administrarla internamente', 'La policía ejerce toda la violencia', 'La violencia es simbólica'], c: 1, ex: 'Las redes tercerizan: contratan sicarios ad hoc. Esto explica la volatilidad de muchos homicidios urbanos: no son "guerras entre bandas", son encargos puntuales.'}
]);

registerExercises('criminologia-ii', '15', [
  {st: 'La definición de trata de personas en el Protocolo de Palermo incluye:', opts: ['Solo explotación sexual', 'Captación, transporte, traslado, acogida o recepción con fines de explotación mediante amenaza, fuerza o abuso de situación de vulnerabilidad', 'Solo secuestro', 'Tráfico ilegal de mercancías'], c: 1, ex: 'La definición articula tres elementos: acción (captación, transporte, traslado, acogida), medio (amenaza, fuerza, fraude, abuso de vulnerabilidad) y fin (explotación sexual, laboral, servidumbre, extracción de órganos, etc.).'},
  {st: 'Las fases clásicas del lavado de activos son:', opts: ['Robo, fuga y gasto', 'Colocación (placement), estratificación (layering) e integración (integration)', 'Deposito, transferencia, fin', 'Solo ingreso al banco'], c: 1, ex: 'Colocación = ingreso al sistema financiero; estratificación = operaciones múltiples para borrar rastro; integración = reintroducción como activos aparentemente legítimos. Modelo estándar internacional.'},
  {st: 'La Ley 25.246 argentina creó:', opts: ['El Ministerio Público Fiscal', 'La Unidad de Información Financiera (UIF)', 'El SPF', 'El Consejo de la Magistratura'], c: 1, ex: 'La 25.246 (2000) crea la UIF como organismo de análisis, tratamiento y transmisión de información para prevenir el lavado de activos. Posteriormente la 26.683 autonomiza el lavado como delito.'},
  {st: 'Martín-Baró distingue la violencia criminal común de la "violencia estratégica" porque esta última:', opts: ['No existe realmente', 'Es planificada y busca producir un efecto político sobre una comunidad (disciplinar, aterrorizar, desplazar)', 'Es solo psicológica', 'Afecta solo a hombres'], c: 1, ex: 'Martín-Baró, psicólogo social salvadoreño, destaca que ciertas violencias no son espontáneas: están diseñadas para aterrorizar y disciplinar poblaciones enteras. Crimen organizado y regímenes represivos la usan.'},
  {st: 'El concepto de "entornos disruptivos" fue desarrollado por:', opts: ['Freud', 'Moty Benyakar', 'Durkheim', 'Foucault'], c: 1, ex: 'Benyakar llama entornos disruptivos a situaciones de violencia extrema, catástrofe o represión sistemática que desbordan la capacidad psíquica normal y exigen modelos clínicos específicos.'},
  {st: 'El Síndrome de Estocolmo, según Spalletti, se sostiene en condiciones como:', opts: ['Brevedad del cautiverio y libertad plena', 'Desequilibrio extremo de poder, aislamiento, amabilidad ocasional del agresor, imposibilidad percibida de escape y tiempo prolongado', 'Solo el género femenino', 'Ausencia total de violencia'], c: 1, ex: 'Son las cinco condiciones descriptas: desequilibrio de poder, aislamiento, gestos mínimos de humanidad del agresor, imposibilidad de escape y duración prolongada. Juntas habilitan el vínculo paradojal.'},
  {st: 'Los mecanismos psíquicos primitivos involucrados en el Síndrome de Estocolmo incluyen:', opts: ['Sublimación exclusiva', 'Negación, idealización, identificación con el agresor e indefensión aprendida', 'Pensamiento lógico-formal', 'Humor maduro'], c: 1, ex: 'La víctima niega aspectos aterradores, idealiza gestos mínimos del agresor, se identifica con él (Anna Freud) y deja de intentar escapar tras intentos fallidos (indefensión aprendida, Seligman).'},
  {st: 'Una lectura criminológica correcta del Síndrome de Estocolmo es que:', opts: ['La víctima "consiente"', 'Son respuestas psíquicas adaptativas al terror que no deben judicializar a la víctima sino ser objeto de abordaje especializado', 'La víctima es cómplice', 'No tiene relación con el delito'], c: 1, ex: 'El síndrome explica conductas de víctimas de secuestros, trata, violencia intrafamiliar y sectas. No son consentimiento ni complicidad: son efectos del delito y parte del daño a reparar.'}
]);
