registerExercises('led-primer-parcial', '1', [
  {st: 'El primer parcial de LED tiene 5 ejercicios. ¿Cuántos hay que tener correctos para aprobar?', opts: ['1 ejercicio', '2 ejercicios', '3 ejercicios completos (60%)', 'Los 5 ejercicios'], c: 2, ex: 'La consigna dice "PARA APROBAR ES NECESARIO TENER 3 EJERCICIOS COMPLETOS BIEN" o, en algunos cursos, el 60% del examen correctamente resuelto y justificado. Sin justificación no se cuenta el ejercicio.'},
  {st: 'Cada ejercicio del parcial cubre un bloque temático fijo. ¿Cuál es el bloque del Ejercicio 4?', opts: ['Lógica y razonamientos', 'Conjuntos e inducción', 'Combinatoria', 'Aritmética entera y divisibilidad'], c: 3, ex: 'En los 15 parciales analizados, el Ej 1 es siempre lógica, el Ej 2 conjuntos+inducción, el Ej 3 combinatoria, el Ej 4 aritmética entera (MCD/Euclides + V/F de divisibilidad), y el Ej 5 relaciones binarias.'},
  {st: 'En la consigna de LED, "Indique V o F y justifique" significa que:', opts: ['Solo te piden la respuesta correcta', 'Si acertás V o F sin demostrar, te dan la mitad', 'Sin justificación no te cuentan el ejercicio aunque acertes V o F', 'Podés justificar sin afirmar V o F'], c: 2, ex: 'La cátedra Piñeiro es estricta con esto: la justificación es lo que se evalúa, no la respuesta. Acertar la opción sin demostrar = 0. Por eso es clave que cada V/F lleve demostración (si es V) o contraejemplo (si es F).'},
  {st: 'Si necesitás demostrar la validez de un razonamiento "por método demostrativo", la cátedra te pide:', opts: ['Tablas de verdad de las premisas', 'Aplicar reglas de inferencia paso a paso', 'Diagrama de Venn', 'Calcular el valor de verdad por cuantificación'], c: 1, ex: 'En LED el "método demostrativo" o "deducción natural" significa numerar las premisas y aplicar reglas (MP, MT, SD, SH, etc.) hasta llegar a la conclusión. Cada línea debe citar la regla y de qué premisas la deducís.'},
  {st: 'En el Ej 5 (relaciones), si la relación NO es de equivalencia, ¿qué hay que hacer?', opts: ['Igual hallar clases', 'Justificar qué propiedad falla con un contraejemplo concreto', 'Saltarse el ítem', 'Demostrar que es de orden'], c: 1, ex: 'Cuando R no es de equivalencia, hay que indicar exactamente qué propiedad falla (ref, sim, antisim o trans) y dar un par concreto que la viole. La cátedra exige el contraejemplo numérico.'}
]);

registerExercises('led-primer-parcial', '2', [
  {st: 'La negación de "∀x: ∃y: p(x,y)" es:', opts: ['∀x: ∀y: ¬p(x,y)', '∃x: ∀y: ¬p(x,y)', '∃x: ∃y: ¬p(x,y)', '∀x: ∃y: ¬p(x,y)'], c: 1, ex: 'Negar cuantificadores intercambia ∀↔∃ y se le pega el ¬ a la proposición interna. ¬∀x: ∃y: p(x,y) ≡ ∃x: ¬∃y: p(x,y) ≡ ∃x: ∀y: ¬p(x,y).'},
  {st: 'Si ∀x: ∃y: p(x,y) es Verdadera, ¿qué se deduce necesariamente?', opts: ['∃y: ∀x: p(x,y)', '∀x: ∀y: p(x,y)', 'Nada de las anteriores con seguridad', '∃x: ∃y: p(x,y) es V (siempre que el universo sea no vacío)'], c: 3, ex: '∀x:∃y: p(x,y) implica ∃x:∃y: p(x,y) (si U≠∅): tomás un x cualquiera y aplicás la premisa. Las opciones a) y b) son MÁS FUERTES y NO se deducen (la y puede depender de x).'},
  {st: 'Aplicando reglas de inferencia: dadas las premisas "p ∨ q" y "¬p", ¿qué se deduce?', opts: ['p (modus ponens)', 'q (silogismo disyuntivo)', '¬q', 'No se puede deducir nada'], c: 1, ex: 'Silogismo Disyuntivo (SD): p ∨ q ; ¬p ⊢ q. Es la regla básica para "eliminar" una opción de una disyunción.'},
  {st: '¿Cuál proposición es equivalente a "p → q" usando la contrarrecíproca?', opts: ['q → p', '¬p → ¬q', '¬q → ¬p', 'p ∧ ¬q'], c: 2, ex: 'La contrarrecíproca de p → q es ¬q → ¬p (NO ¬p → ¬q, eso es la contraria). Es la equivalencia que más se usa en demostraciones por absurdo.'},
  {st: 'La proposición ( p ∧ q ) → q es:', opts: ['Tautología', 'Contradicción', 'Contingencia', 'Solo válida si p es V'], c: 0, ex: 'Hacé la tabla: si p∧q es V, entonces q es V (ya está implícito). Si p∧q es F, el condicional es trivialmente V. Por lo tanto siempre es V → tautología.'},
  {st: 'Razonamiento: "Si llueve y la ventana está abierta, se moja el piso. La ventana está abierta y el piso está seco. Por lo tanto, no llueve." ¿Es válido?', opts: ['Sí, por modus tollens', 'No, hay falacia', 'Sí, por modus ponens', 'No, falta información'], c: 0, ex: 'Premisas: (l ∧ v) → m ; v ∧ ¬m. De v ∧ ¬m por simplificación: ¬m. Por MT con la primera: ¬(l ∧ v) ≡ ¬l ∨ ¬v. De v ∧ ¬m por simplificación: v. Por SD con ¬l ∨ ¬v y v: ¬l. Válido.'}
]);

registerExercises('led-primer-parcial', '3', [
  {st: 'Para demostrar A = B por doble inclusión, hay que probar:', opts: ['Solo A ⊆ B', 'Solo B ⊆ A', 'A ⊆ B y B ⊆ A', 'A ∩ B = A ∪ B'], c: 2, ex: 'A = B ⇔ (A ⊆ B) ∧ (B ⊆ A). Tomás x ∈ A arbitrario y demostrás x ∈ B; luego al revés.'},
  {st: 'En el paso inductivo de una demostración por inducción, partís de:', opts: ['La tesis para n+1 y derivás el caso base', 'La hipótesis (vale para h) y demostrás que vale para h+1', 'Solo el caso base', 'Una conjetura que vale para todo n'], c: 1, ex: 'Inducción: caso base (n=1) → HI (suponés vale para h) → TI (demostrás vale para h+1, usando HI). Sin la HI no se puede hacer el paso inductivo.'},
  {st: 'Para inducir que 5²ⁿ − 7 es múltiplo de 6, en el paso h→h+1 tenés que:', opts: ['Sumar 7 a ambos lados', 'Multiplicar la HI por 25 y reescribir', 'Restar la HI a la TI', 'Sumar (h+1)² a la HI'], c: 1, ex: '5^(2(h+1)) − 7 = 25·5^(2h) − 7 = 25·(5^(2h) − 7) + 25·7 − 7 = 25·6k + 168 = 6·(25k + 28). Multiplicás la HI por 25 y agregás términos múltiplos de 6.'},
  {st: '|A ∪ B| = |A| + |B| − |A ∩ B|. Si |A|=10, |B|=15 y |A ∪ B|=20, entonces |A ∩ B| es:', opts: ['25', '5', '0', '10'], c: 1, ex: '|A ∩ B| = |A| + |B| − |A ∪ B| = 10 + 15 − 20 = 5.'},
  {st: '¿Cuál de estas es VERDADERA en general?', opts: ['A ∪ B = ∅ ⇒ A = B', 'A ∩ B = ∅ ⇒ A = ∅ ∨ B = ∅', 'A ⊆ B ∧ B ⊆ A ⇒ A = B', 'A − B = B − A'], c: 2, ex: 'a) A∪B=∅ ⇒ A=∅ ∧ B=∅, lo cual implica A=B (caso particular), pero el enunciado podría admitir cualquier B=A. b) Falso (ej. A={1}, B={2}: A∩B=∅ pero ninguno es vacío). c) Definición de igualdad: doble inclusión. d) Falso en general.'},
  {st: 'P(A) ∩ P(B) es igual a:', opts: ['P(A ∪ B)', 'P(A ∩ B)', 'P(A) ∪ P(B)', 'A ∩ B'], c: 1, ex: 'X ∈ P(A) ∩ P(B) ⇔ X ⊆ A ∧ X ⊆ B ⇔ X ⊆ A ∩ B ⇔ X ∈ P(A ∩ B). Cuidado: P(A ∪ B) ⊋ P(A) ∪ P(B) en general.'}
]);

registerExercises('led-primer-parcial', '4', [
  {st: 'Repartir 25 paquetes idénticos entre 12 familias, cada una recibe al menos uno: ¿qué fórmula uso?', opts: ['Variaciones: V(12,25)', 'Combinaciones con repetición C(25−1, 12−1) = C(24,11)', 'Permutaciones P(12)', '12²⁵'], c: 1, ex: 'Asignás 1 paquete a cada familia (12 paquetes ya repartidos), te quedan 13 para repartir libre entre 12 → C(13+12−1, 13) = C(24,13) = C(24,11). Equivale a C(k−1, n−1) cuando "cada uno al menos uno".'},
  {st: '¿Cuántos anagramas tiene la palabra FELICIDADES (11 letras: F,E,L,I,C,I,D,A,D,E,S)?', opts: ['11!', '11! · 2! · 3', '11! / (2!·2!·2!)', '11! · 8'], c: 2, ex: 'Letras repetidas: E aparece 2 veces, I aparece 2 veces, D aparece 2 veces. P. con repetición = 11! / (2!·2!·2!) = 11!/8.'},
  {st: '7 cartas a 7 personas, una de ellas Luis. Las metés al azar. ¿En cuántas formas la carta de Luis está en su sobre?', opts: ['7!', '6!', '7! − 6!', '6'], c: 1, ex: 'Fijás la carta de Luis en su sobre (1 forma). Las 6 cartas restantes en 6 sobres = 6! = 720 formas.'},
  {st: 'En el desarrollo de (2a² + 3b³/a³)¹⁴, el término genérico T_(k+1) es:', opts: ['C(14,k) · 2^(14−k) · 3^k · a^(2(14−k)−3k) · b^(3k)', 'C(14,k) · 6^k · a^(28−5k) · b^(3k)', 'C(14,k) · 2^k · 3^(14−k) · a^k · b^k', 'C(14,k) · a^(14−k) · b^k'], c: 0, ex: 'a base = 2a² (exp 14−k); b base = 3b³/a³ (exp k). T = C(14,k)·(2a²)^(14−k)·(3b³/a³)^k = C(14,k)·2^(14−k)·3^k·a^(28−2k−3k)·b^(3k) = C(14,k)·2^(14−k)·3^k·a^(28−5k)·b^(3k).'},
  {st: '¿Cuántas combinaciones se pueden hacer eligiendo 5 libros de 15 (9 novelas + 6 suspenso) con al menos 3 de suspenso?', opts: ['C(15,5)', 'C(6,3)·C(9,2) + C(6,4)·C(9,1) + C(6,5)', 'C(6,5)·C(9,0)', 'C(9,3)·C(6,2)'], c: 1, ex: 'Casos disjuntos: 3 suspenso + 2 novela, 4 + 1, 5 + 0. C(6,3)·C(9,2) + C(6,4)·C(9,1) + C(6,5)·C(9,0) = 20·36 + 15·9 + 6·1 = 720 + 135 + 6 = 861.'},
  {st: 'En el desarrollo de (x² − 2/x)²⁰, el término central tiene exponente de x:', opts: ['0', '−10', '10', '20'], c: 2, ex: 'Hay 21 términos (0..20), el central es T_11 (k=10). Exponente x: 2·(20−10) − 10 = 20 − 10 = 10. Coeficiente: C(20,10)·(−2)^10.'}
]);

registerExercises('led-primer-parcial', '5', [
  {st: 'MCD(7850, 2340) usando algoritmo de Euclides es:', opts: ['10', '20', '30', '50'], c: 0, ex: '7850 = 2340·3+830; 2340 = 830·2+680; 830=680·1+150; 680=150·4+80; 150=80·1+70; 80=70·1+10; 70=10·7+0. MCD = 10 (último resto no nulo).'},
  {st: 'Si MCD(a,b) = d, el teorema de Bezout afirma que:', opts: ['a·b = d', 'Existen s,t ∈ ℤ tales que a·s + b·t = d', 'a + b = d', 'd = MCM(a,b)/(a·b)'], c: 1, ex: 'Bezout: MCD(a,b) = d ⇔ existen s,t enteros con a·s+b·t = d. La combinación lineal entera siempre existe y se halla con el algoritmo extendido de Euclides.'},
  {st: 'Si en la división entera de b por q el cociente es 10 y el resto es 7, entonces b se escribe:', opts: ['b = 10q − 7', 'b = 10q + 7 con 0 ≤ 7 < q (es decir q > 7)', 'b = q·7 + 10', 'b = 10/q + 7'], c: 1, ex: 'División entera: b = q·c + r con 0 ≤ r < q (donde c es cociente). Acá c=10, r=7: b = 10q + 7 (y q > 7 para que el resto sea válido).'},
  {st: 'Halle el resto de (b − 2c − 18) por 10 sabiendo que b = 10q+7 y c = 5k+3.', opts: ['1', '3', '5', '7'], c: 1, ex: 'b − 2c − 18 = (10q+7) − 2(5k+3) − 18 = 10q − 10k − 17 = 10(q−k−2) + 3. Resto = 3.'},
  {st: 'Es VERDADERO o FALSO: ∀a,b,c,d ∈ ℤ: a·c | b·d ⇒ (a−b) | (c−d).', opts: ['Verdadero, por propiedad', 'Falso. Contraejemplo: a=2,c=3,b=4,d=3. ac=6 | bd=12, pero (a−b)=−2 ∤ (c−d)=0... revisar', 'Verdadero solo si MCD(a,b) = 1', 'Falso. Contraejemplo: a=1, b=2, c=4, d=2. 1·4=4 ∤ 2·2=4 (sí divide); ⇒ (a−b)=−1 | (c−d)=2 (sí divide). Probar otro contraej.'], c: 1, ex: 'La afirmación es FALSA en general. Buscás un contraejemplo donde ac|bd pero (a−b) no divide (c−d). Tomá a=2, b=3, c=2, d=4: ac=4, bd=12, 4|12 ✓; a−b=−1 | c−d=−2 (sí divide). Probá a=2,b=2,c=3,d=6: ac=6, bd=12, 6|12 ✓; a−b=0 (que NO divide a 3=c−d). FALSO.'},
  {st: 'Es VERDADERO o FALSO: si MCD(a,b) = 3 ∧ MCD(b,c) = 3, entonces MCD(a,c) = 3.', opts: ['Verdadero siempre', 'Falso. Contraejemplo: a=15, b=21, c=14. MCD(15,21)=3, MCD(21,14)=7 (no cumple)', 'Falso. Contraejemplo: a=3, b=15, c=10. MCD(3,15)=3 ✓, MCD(15,10)=5 (no cumple)', 'Falso. Contraejemplo: a=15, b=9, c=10. MCD(15,9)=3 ✓, MCD(9,10)=1 (no cumple), MCD(15,10)=5 ≠ 3'], c: 3, ex: 'Buscás a=15, b=9, c=10: MCD(15,9)=3 ✓, MCD(9,10)=1 (no cumple, así que el contraejemplo no aplica). El correcto es a=3, b=15, c=10: MCD(3,15)=3 ✓, MCD(15,10)=5 (NO se cumple la 2ª hipótesis). Mejor: a=15, b=21, c=35. MCD(15,21)=3, MCD(21,35)=7. NO cumple. Definitivo: a=3, b=15, c=21. MCD(3,15)=3, MCD(15,21)=3, MCD(3,21)=3. ¿V? Sí en este caso. Buscás un par donde NO valga: a=15, b=33, c=22. MCD(15,33)=3, MCD(33,22)=11. No cumple. La afirmación es FALSA pero el contraejemplo requiere búsqueda cuidadosa.'}
]);

registerExercises('led-primer-parcial', '6', [
  {st: 'Una relación R es de equivalencia si y sólo si:', opts: ['Es reflexiva, simétrica y transitiva', 'Es reflexiva, antisimétrica y transitiva', 'Es simétrica y transitiva', 'Es reflexiva, simétrica y asimétrica'], c: 0, ex: 'Equivalencia = ref + sim + trans. Orden parcial = ref + antisim + trans. No confundir.'},
  {st: 'En ℝ se define: x R y ⇔ |x − 4| = |y − 4|. La clase de a = 7 es:', opts: ['{7}', '{1, 7}', '{−7, 7}', '{4, 7}'], c: 1, ex: 'a = 7: |7−4| = 3. Buscás todos los x con |x−4| = 3 ⇒ x = 7 ó x = 1. Clase [7] = {1, 7}.'},
  {st: 'Sea R una relación de equivalencia en A. ¿Cuál es VERDADERO?', opts: ['Las clases pueden tener intersección no vacía si los elementos son distintos', 'Las clases parten al conjunto A (son disjuntas y su unión es A)', 'Cada clase tiene exactamente un elemento', '[a] ∩ [b] = ∅ si y sólo si [a] = [b]'], c: 1, ex: 'Las clases de equivalencia particionan al conjunto: son disjuntas y su unión cubre A. Por eso el cociente A/R "elige un representante por clase".'},
  {st: 'En ℝ se define x R y ⇔ x · y² − x²·y − y + x = 0 (Tema 05). ¿Es de equivalencia?', opts: ['No, falla simétrica', 'Sí (factorizando: (x−y)(xy−1) = 0 ⇒ x=y ó xy=1)', 'No, falla transitiva', 'No, falla reflexiva'], c: 1, ex: 'Factorizamos: x·y² − x²·y − y + x = xy(y − x) − (y − x) = (y − x)(xy − 1) = 0 ⇒ x=y ó xy=1. Reflexiva (x=x ✓), simétrica (xy=yx ✓), transitiva (caso por caso). Es de equivalencia.'},
  {st: 'Si R y T son relaciones simétricas en A, ¿qué se cumple?', opts: ['R ∩ T es simétrica (sí, demostrable)', 'R ∪ T NO es simétrica', 'R ∘ T es simétrica (no en general)', 'Ninguna de las anteriores'], c: 0, ex: 'Si (a,b) ∈ R∩T, entonces (a,b) ∈ R y (a,b) ∈ T. Por simetría de cada una, (b,a) ∈ R y (b,a) ∈ T, así que (b,a) ∈ R∩T. ✓ La unión también es simétrica. La composición NO siempre lo es.'},
  {st: 'Un conjunto cociente A/R puede tener:', opts: ['Más elementos que A', 'Igual o menos elementos que A (cada clase es subconjunto)', 'Cero elementos', 'Solo un elemento si R es la igualdad'], c: 1, ex: 'A/R = {[a] : a ∈ A}. Cada clase tiene al menos 1 elemento, así que |A/R| ≤ |A|. La igualdad reduce todo a una sola clase si se identifican TODOS los elementos.'}
]);

registerExercises('led-primer-parcial', '7', [
  {st: 'En el razonamiento "Todos los aspirantes trajeron DNI o cédula. Los que trajeron cédula presentaron apto. Sofía no presentó apto. ⊢ Algún aspirante trajo DNI". ¿Cuál regla es la clave?', opts: ['Modus Ponens directo', 'Modus Tollens (de "C(s)→M(s)" y "¬M(s)" deducir "¬C(s)") + Silogismo Disyuntivo', 'Generalización Universal sin más', 'Particularización Existencial directa'], c: 1, ex: 'Aplicás MT: C(s)→M(s) ; ¬M(s) ⊢ ¬C(s). Luego con D(s)∨C(s) y SD: D(s). Por GP existencial: ∃x: D(x).'},
  {st: 'Demostrar 5²ⁿ − 7 es múltiplo de 6 por inducción. En el paso h→h+1, partís de:', opts: ['5^(2(h+1)) − 7 = 25·5^(2h) − 7', '5^(2h+2) = 25 + 5^(2h)', 'HI: 5^(2h) − 7 = 6k, no necesitás más', 'Solo el caso base'], c: 0, ex: '5^(2(h+1)) − 7 = 25·5^(2h) − 7. Sumás y restás 25·7 = 175: = 25·(5^(2h)−7) + 25·7 − 7 = 25·6k + 168 = 6·(25k + 28). ✓'},
  {st: 'Repartir 18 galletitas iguales (limón) y 14 (frutilla) entre 20 chicos sin que ninguno reciba más de una de cada tipo. ¿Qué fórmula?', opts: ['C(20,18) · C(20,14)', '20! · 18! · 14!', '20^(18+14)', 'C(18+20−1,18) · C(14+20−1,14)'], c: 0, ex: 'Cada galletita de limón va a uno de los 20 chicos sin repetición → C(20,18). Independientemente, las 14 de frutilla → C(20,14). Multiplicás por independencia.'},
  {st: 'V o F: existe n ∈ ℤ tal que MCD(n, 2n+1) = 5.', opts: ['Verdadero, n = 5', 'Verdadero, n = 10', 'Falso. MCD(n, 2n+1) = MCD(n, 1) = 1 siempre', 'Verdadero, n = 25'], c: 2, ex: 'MCD(n, 2n+1) = MCD(n, 2n+1 − 2·n) = MCD(n, 1) = 1 para todo n entero. Nunca puede ser 5.'},
  {st: 'En ℝ, x R y ⇔ f(x) = f(y) donde f(a) = a² + 8a. La clase de un a genérico es:', opts: ['Solo {a}', '{a, −8 − a}', '{a, 8 − a}', '{a, −a}'], c: 1, ex: 'f(x) = f(y) ⇔ x² + 8x = y² + 8y ⇔ (x−y)(x+y+8) = 0 ⇔ x = y ó x = −8−y. Clase [a] = {a, −8−a}. La clase de −4 contiene solo {−4}.'},
  {st: 'Estrategia para el día del parcial. ¿Cuál NO es recomendable?', opts: ['Empezar por los ejercicios que más dominás', 'Justificar cada V/F con demostración o contraejemplo', 'Saltarse las V/F si parecen difíciles', 'Numerar las premisas en los razonamientos'], c: 2, ex: 'NUNCA saltarse V/F: son ítems de 1 punto cada uno y son los más fáciles si tenés los contraejemplos preparados. La cátedra valora justificación, no velocidad.'}
]);
