registerExercises('led-primer-parcial', '1', [
  {st: 'El primer parcial de desarrollo de LED tiene...', opts: ['3 ejercicios', '4 ejercicios', '5 ejercicios (uno por bloque temático)', '11 ejercicios'], c: 2, ex: 'Los 8 parciales de desarrollo (temas 01–06, 08, 09) tienen <b>5 ejercicios</b>, uno por bloque: Ej1 lógica, Ej2 conjuntos+inducción, Ej3 combinatoria+binomio, Ej4 aritmética, Ej5 relaciones. ▸ Las otras: 3 y 4 se quedan cortas; 11 ítems es el formato del <b>tema 07</b>, que es la variante multiple choice (otra cosa).'},
  {st: 'En los temas 01 a 06 el encabezado dice que para aprobar hay que tener...', opts: ['Los 5 ejercicios perfectos', 'Un 60% correctamente resuelto Y JUSTIFICADO', 'Solo 1 ejercicio bien', 'La mitad de cada ejercicio'], c: 1, ex: 'El encabezado real (jul–sep 2023) dice <b>"PARA APROBAR ES NECESARIO TENER UN 60% CORRECTAMENTE RESUELTO Y JUSTIFICADO"</b> (equivale a 3 de 5). En feb 2024 (temas 08–09) lo escriben como "3 ejercicios completos bien". ▸ No hace falta el 100%; y nunca alcanza con "1 ejercicio".'},
  {st: 'El tema 07 (15/12/2023) es la variante multiple choice. Para aprobarlo hay que tener...', opts: ['3 de 5', '6 ejercicios correctos (de 11)', '60% de un ejercicio', '11 correctos'], c: 1, ex: 'El tema 07 tiene <b>11 preguntas de opción múltiple</b> y su encabezado dice "PARA APROBAR ES NECESARIO TENER 6 EJERCICIOS CORRECTOS". ▸ El "3 de 5" y el "60%" son de los parciales de desarrollo, no de este; "11 correctos" sería el 100%, no se exige.'},
  {st: 'El bloque temático fijo del Ejercicio 4 es:', opts: ['Lógica y razonamientos', 'Conjuntos e inducción', 'Combinatoria y binomio', 'Aritmética entera y divisibilidad'], c: 3, ex: 'En los 8 parciales de desarrollo el orden no cambia: Ej1 lógica, Ej2 conjuntos+inducción, Ej3 combinatoria+binomio, <b>Ej4 aritmética entera</b> (división entera, MCD/MCM por Euclides, combinación lineal, V/F de divisibilidad) y Ej5 relaciones. ▸ Las otras opciones son los Ej1, Ej2 y Ej3.'},
  {st: 'En LED, "Indique V o F y justifique" significa que:', opts: ['Solo te piden marcar V o F', 'Acertar V/F sin demostrar te da la mitad', 'Sin justificación NO cuenta, aunque aciertes V o F', 'Podés justificar sin decidir V o F'], c: 2, ex: 'La cátedra evalúa la <b>justificación</b>, no la respuesta: acertar V/F sin demostrar = 0. ▸ Cada V lleva DEMOSTRACIÓN; cada F lleva CONTRAEJEMPLO numérico concreto. ▸ Por eso conviene tener contraejemplos preparados (ej.: MCD(n, 2n+1) = 1 siempre).'},
  {st: 'Si la consigna pide probar la validez de un razonamiento "por método demostrativo", tenés que:', opts: ['Hacer la tabla de verdad de todo', 'Aplicar reglas de inferencia paso a paso (MP, MT, SD, SH...)', 'Dibujar un diagrama de Venn', 'Calcular cardinales'], c: 1, ex: '"Método demostrativo" = numerar las premisas y aplicar <b>reglas de inferencia</b> hasta llegar a la conclusión, citando en cada línea la regla y de qué premisas sale. ▸ La tabla de verdad no sirve para predicados con cuantificadores; el Venn es para conjuntos; los cardinales son del Ej2.'},
]);

registerExercises('led-primer-parcial', '2', [
  {st: 'La negación de "∀x: ∃y: p(x,y)" es:', opts: ['∀x: ∀y: ¬p(x,y)', '∃x: ∀y: ¬p(x,y)', '∃x: ∃y: ¬p(x,y)', '∀x: ∃y: ¬p(x,y)'], c: 1, ex: 'Al negar, cada ∀ se vuelve ∃, cada ∃ se vuelve ∀ y se niega la proposición interna: ¬(∀x: ∃y: p) ≡ ∃x: ∀y: ¬p(x,y). ▸ (A) no cambia el ∀; (C) no cambia el ∃; (D) no toca ningún cuantificador.'},
  {st: '(Tema 05, ít. 1.1) La proposición ¬(p ∨ q) ∧ q es:', opts: ['Tautología', 'Contradicción', 'Contingencia', 'Depende de q'], c: 1, ex: '¬(p∨q) ∧ q ≡ (¬p ∧ ¬q) ∧ q ≡ ¬p ∧ (q ∧ ¬q) ≡ ¬p ∧ F ≡ <b>F</b> para toda valuación → <b>contradicción</b>. ▸ Nunca da V, así que no es tautología ni contingencia.'},
  {st: '(Tema 05, ít. 1.2) "Si estudio, apruebo. Si apruebo, me pongo feliz. Estoy feliz. Por lo tanto, estudio y apruebo." Este razonamiento es:', opts: ['Categórico y válido', 'Categórico e inválido', 'No categórico y válido', 'No categórico e inválido'], c: 3, ex: 'Es <b>no categórico</b> (las premisas no son todas categóricas: hay condicionales) e <b>inválido</b>: afirmar "estoy feliz" y concluir "estudio" es la falacia de <b>afirmación del consecuente</b>. ▸ Contraejemplo: estoy feliz por otra razón sin haber estudiado. Las premisas pueden ser V y la conclusión F.'},
  {st: '(Tema 06, ít. 1.1) Si p: "la suma de dos enteros siempre es un entero", la proposición q: "si la suma de dos números es entera, entonces los dos números lo son" es:', opts: ['La recíproca de p', 'La contraria de p', 'La contrarrecíproca de p', 'Equivalente a p'], c: 0, ex: 'p tiene forma "si a, b son enteros → a+b es entero". q invierte hipótesis y conclusión: "si a+b es entero → a, b son enteros" = la <b>recíproca</b>. ▸ La recíproca NO es equivalente (de hecho q es falsa: 0,5 + 0,5 = 1). La contraria niega ambas; la contrarrecíproca niega e invierte.'},
  {st: '(Tema 06, ít. 1.2) "Todos los pasajeros llevaron DNI y subieron su equipaje" se simboliza:', opts: ['∀x: [p(x) ∧ d(x) ∧ e(x)]', '∀x: [p(x) → (d(x) ∧ e(x))]', '∀x: [(p(x) ∧ d(x)) → e(x)]', '∃x: [p(x) → (d(x) ∧ e(x))]'], c: 1, ex: 'Un "todos los P cumplen Q" se escribe con <b>condicional</b>: ∀x: [p(x) → (d(x) ∧ e(x))], siendo p(x) "x es pasajero". ▸ (A) con ∧ diría que TODO x es pasajero y llevó todo (falso); (C) cambia el significado; (D) usa ∃.'},
  {st: '(Tema 07, ít. 4) "Todos los archivos personales están dañados. Algunos archivos dañados tienen contraseña." Entonces necesariamente:', opts: ['"Algunos archivos personales tienen contraseña"', '"Algún archivo con contraseña es personal"', '"Algún archivo personal no tiene contraseña"', 'Ninguna de las anteriores'], c: 3, ex: 'Personales ⊆ Dañados, y "algunos dañados tienen contraseña", pero esos dañados-con-contraseña podrían NO ser personales. ▸ No se sigue (A) ni (B). (C) tampoco se deduce. La respuesta es <b>(D) ninguna</b>.'},
  {st: '(Tema 07, ít. 5 / Tema 08, Ej 1) Si ∀x: ∃y: p(x,y) es Verdadera, ¿qué se deduce con seguridad (universo no vacío)?', opts: ['∀x: ∀y: p(x,y)', '∃y: ∀x: p(x,y)', '∃x: ∃y: p(x,y)', 'Nada con seguridad'], c: 2, ex: 'Tomando un x cualquiera del universo existe algún y, luego <b>∃x: ∃y: p(x,y)</b>. ▸ (A) "todos los pares" es más fuerte; (B) exige UN mismo y para todo x (más fuerte, contraejemplo p: x+y=0 en ℤ); por eso (D) es falsa: algo sí se deduce.'},
  {st: '(Tema 09, Ej 1) "Algunos A son B. Todos los B son C." Entonces necesariamente:', opts: ['Algunos A son C', 'Todos los A son C', 'Algún A no es C', 'Ninguna de las anteriores'], c: 0, ex: 'Hay al menos un elemento que es A y B; como todo B es C, ese elemento también es C → <b>algunos A son C</b>. ▸ "Todos los A son C" no se deduce (puede haber A que no son B); "algún A no es C" tampoco; por eso (A) es la correcta.'},
]);

registerExercises('led-primer-parcial', '3', [
  {st: 'Para demostrar A = B por doble inclusión hay que probar:', opts: ['Solo A ⊆ B', 'Solo B ⊆ A', 'A ⊆ B Y B ⊆ A', 'A ∩ B = ∅'], c: 2, ex: 'A = B ⟺ (A ⊆ B) Y (B ⊆ A). Tomás x ∈ A arbitrario y probás x ∈ B; después al revés. ▸ Una sola inclusión no garantiza la igualdad; A ∩ B = ∅ es otra cosa.'},
  {st: 'En el paso inductivo de una demostración por inducción, partís de:', opts: ['La tesis para n+1 y derivás el caso base', 'La hipótesis (vale para h) y demostrás que vale para h+1', 'Solo el caso base', 'Una conjetura válida para todo n'], c: 1, ex: 'Inducción: <b>Caso base</b> (n=1) + <b>paso inductivo</b>: suponés la HI (vale para h) y a partir de ella demostrás la TI (vale para h+1). ▸ (A) está invertido; (C) el caso base solo no prueba para todo n; (D) no podés "asumir" lo que querés probar.'},
  {st: '(Tema 03, Ej 2b) Para probar por inducción que 5²ⁿ − 7 es múltiplo de 6, en el paso h → h+1 conviene:', opts: ['Sumar 7 a ambos lados', 'Multiplicar la HI por 25 y reescribir', 'Restar la HI a la tesis', 'Sumar (h+1)² a la HI'], c: 1, ex: 'Como 5²⁽ʰ⁺¹⁾ = 25·5²ʰ, la tesis 25·5²ʰ − 7 se reescribe usando la HI (5²ʰ − 7 = 6k): 25(6k+7) − 7 = 150k + 168 = 6(25k + 28). ▸ La clave es <b>multiplicar la HI por 25</b>; las otras no factorizan el 6.'},
  {st: '(Tema 04, Ej 2a) Con |A∩B∩C|=3, |A−B|=11, |A∪B|=33, |A∪B∪C|=35 y |C−A|=6, el valor de |B−C| es:', opts: ['6', '15', '19', '11'], c: 1, ex: '"Sólo C" = |A∪B∪C| − |A∪B| = 35 − 33 = 2. "B∩C sólo" = |C−A| − sóloC = 6 − 2 = 4. En |A∪B| = |A−B| + |B−C| + "B∩C sólo" + |A∩B∩C|: 33 = 11 + |B−C| + 4 + 3 ⇒ <b>|B−C| = 15</b>. ▸ Se resuelve solo con sumas y restas en el Venn.'},
  {st: '(Tema 07, ít. 11) De 50 personas, 28 toman café o mate. Los que toman café y NO mate son 9. ¿Cuántas toman mate?', opts: ['13', '19', '22', '41'], c: 1, ex: '|café ∪ mate| = (solo café) + (toman mate) ⇒ 28 = 9 + |mate| ⇒ <b>|mate| = 19</b>. ▸ 13, 22 y 41 no surgen de la relación entre la unión y el "solo café".'},
  {st: '(Tema 09, Ej 2) ¿Cuántas de estas son equivalentes a S = ∑(i=h..2h+1) i²?  (1) ∑(i=h+1..2h) i² + (2h+1)² + h²  ·  (2) ∑(i=h..2h+2) i² − (2h+2)²  ·  (3) ∑(i=h..2h) i² + (2h+1)²', opts: ['Ninguna', 'Solo una', 'Solo dos', 'Las tres'], c: 3, ex: 'Las <b>tres</b> son iguales a S. (1) saca y vuelve a sumar los extremos i=h e i=2h+1; (2) agrega y resta el término 2h+2; (3) agrega el faltante i=2h+1. ▸ Verificable en h=3: S = 9+16+25+36+49 = 135 (i de 3 a 7), y las tres opciones dan 135.'},
  {st: '|A ∪ B| = |A| + |B| − |A ∩ B|. Si |A|=10, |B|=15 y |A∪B|=20, entonces |A∩B| es:', opts: ['25', '5', '0', '10'], c: 1, ex: 'Despejo: |A∩B| = 10 + 15 − 20 = <b>5</b>. ▸ 25 sería sin restar la unión; 0 daría |A∪B|=25; 10 no sale de la cuenta.'},
]);

registerExercises('led-primer-parcial', '4', [
  {st: '(Tema 07, ít. 1) Con A = {1,…,9} (9 elementos) y B = {x,y,z} (3 elementos), la cantidad de funciones de A en B es:', opts: ['C(9,3)', '9³', '3⁹', 'C(11,3)'], c: 2, ex: 'Cada uno de los 9 elementos de A se asigna a uno de los 3 de B → 3 · 3 · … (9 veces) = <b>3⁹</b> = 19683. ▸ 9³ invierte los roles; las combinaciones no aplican (una función ordena el dominio).'},
  {st: '(Tema 07, ít. 2) La cantidad de anagramas de la palabra FELICIDADES es:', opts: ['11! − 2!·3', '11! / 8', '8!·2!·2!·2!', '11!'], c: 1, ex: 'FELICIDADES tiene 11 letras con E, I y D repetidas dos veces cada una. Permutaciones con repetición: 11! / (2!·2!·2!) = <b>11! / 8</b> = 4.989.600. ▸ 11! cuenta como si todas fueran distintas (sobrecuenta); las otras no corresponden.'},
  {st: '(Tema 07, ít. 3) La expresión (n+1)! − (n−1)!·n² es equivalente a:', opts: ['n²', '2n²', 'n!', '2n!'], c: 2, ex: '(n+1)! = (n+1)·n·(n−1)! y n²·(n−1)! comparten (n−1)!: sacando factor común (n−1)![(n+1)n − n²] = (n−1)!·n = <b>n!</b>. ▸ Las potencias n² y 2n² ignoran el factorial.'},
  {st: '(Tema 01, Ej 3a) Se lanzan 5 dados y se anota la sucesión (d1,…,d5). ¿Cuántas tienen cuatro números iguales y uno distinto?', opts: ['6·5·5 = 150', '6⁵', 'C(6,2)', '5! = 120'], c: 0, ex: 'Decisiones independientes: valor que se repite (6) · posición del distinto (5) · valor del distinto, ≠ del repetido (5) = <b>150</b>. ▸ 6⁵ cuenta todas las tiradas; C(6,2) ignora las posiciones; 5! no aplica.'},
  {st: '(Tema 01, Ej 3b) Repartir 25 paquetes idénticos entre 12 familias, cada una al menos uno:', opts: ['12²⁵', 'C(24, 11)', 'P(12)', 'V(12, 25)'], c: 1, ex: 'Asigno 1 a cada familia (quedan 13) y reparto con repetición: C(13+12−1, 13) = C(24,13) = <b>C(24,11)</b> = 2.496.144. ▸ 12²⁵ y V(12,25) suponen orden/repetición libre; P(12) permuta 12 elementos.'},
  {st: '(Tema 02, Ej 3a) Colgar 15 camisas, 8 vestidos y 7 camperas (todos distintos) con las camisas todas juntas y los vestidos también:', opts: ['30!', '9! · 15! · 8!', '15! · 8! · 7!', 'C(30, 3)'], c: 1, ex: 'Trato "camisas" y "vestidos" como dos bloques: quedan 9 unidades (2 bloques + 7 camperas) que se ordenan en 9!; dentro del bloque de camisas hay 15! órdenes y dentro del de vestidos 8!. Total = <b>9! · 15! · 8!</b>. ▸ 30! ignora que los bloques van juntos.'},
  {st: '(Tema 02, Ej 3b) ¿Cuántos términos del desarrollo de (2a² + 3(b/a)³)¹⁴ tienen el exponente de "a" múltiplo de 3?', opts: ['3 términos', '5 términos', '7 términos', '15 términos'], c: 1, ex: 'El exponente de a en T(k+1) es 2(14−k) − 3k = 28 − 5k. Es múltiplo de 3 ⟺ k ≡ 2 (3), o sea k ∈ {2,5,8,11,14} → <b>5 términos</b>. ▸ Hay 15 términos en total, pero solo 5 cumplen.'},
  {st: '(Tema 09, Ej 3b) Elegir 5 libros de 15 (9 novelas, 6 de suspenso) con al menos 3 de suspenso:', opts: ['C(15, 5)', 'C(6,3)·C(9,2) + C(6,4)·C(9,1) + C(6,5)·C(9,0)', 'C(6, 5)', 'C(9,3)·C(6,2)'], c: 1, ex: '"Al menos 3 de suspenso" = 3, 4 o 5 de suspenso (casos disjuntos): 20·36 + 15·9 + 6·1 = 720 + 135 + 6 = <b>861</b>. ▸ C(15,5)=3003 es sin condición; las otras cubren un solo caso o cuentan novelas.'},
  {st: '(Tema 08, Ej 3b) ¿Para qué n el 4º término de (x³ + 2/x)ⁿ es de grado 3?', opts: ['n = 3', 'n = 4', 'n = 5', 'n = 6'], c: 2, ex: 'El término genérico es C(n,k)·2ᵏ·x^(3n−4k); el 4º es k=3, con exponente 3n − 12. Igualo a 3: 3n − 12 = 3 ⇒ <b>n = 5</b> (y el término es C(5,3)·2³·x³ = 80x³).'},
]);

registerExercises('led-primer-parcial', '5', [
  {st: '(Tema 01, Ej 4a) MCD(7850, 2340) por el algoritmo de Euclides es:', opts: ['10', '20', '30', '50'], c: 0, ex: 'Divisiones sucesivas: 7850=2340·3+830 · 2340=830·2+680 · 830=680+150 · 680=150·4+80 · 150=80+70 · 80=70+10 · 70=10·7+0 → <b>MCD = 10</b>. Combinación lineal: 10 = (−31)·7850 + 104·2340. ▸ 20, 30, 50 son múltiplos de 10 pero no el MCD.'},
  {st: 'Si MCD(a,b) = d, el teorema de Bézout afirma que:', opts: ['a·b = d', 'Existen s, t ∈ ℤ tales que a·s + b·t = d', 'a + b = d', 'd = MCM(a,b)'], c: 1, ex: 'Bézout: el MCD se escribe como <b>combinación lineal entera</b> de a y b (los s, t salen de la vuelta atrás del algoritmo de Euclides). ▸ a·b = MCD·MCM (no = d); a+b no se relaciona con el MCD.'},
  {st: 'Si en la división entera de b por q el cociente es 10 y el resto es 7, entonces:', opts: ['b = 10q − 7', 'b = 10q + 7 con q > 7', 'b = 7q + 10', 'b = 10/q + 7'], c: 1, ex: 'División entera: dividendo = divisor·cociente + resto, con 0 ≤ resto < divisor. Acá b = q·10 + 7 = <b>10q + 7</b>, y como el resto 7 debe ser menor que el divisor q, hace falta <b>q > 7</b>. ▸ Las demás invierten signos o roles.'},
  {st: '(Tema 05 / Tema 08, Ej 4) Si b = 10q + 7 y c = 5k + 3, el resto de (b − 2c − 18) al dividir por 10 es:', opts: ['1', '3', '5', '7'], c: 1, ex: 'b − 2c − 18 = (10q+7) − (10k+6) − 18 = 10(q−k) − 17 = 10(q−k−2) + 3 ⇒ resto = <b>3</b>. ▸ El truco es agrupar los múltiplos de 10 y dejar el resto entre 0 y 9.'},
  {st: '(Tema 04, Ej 4a) ¿Es verdadera, ∀a,b,c ∈ ℤ, la afirmación "c | (a − b) ⇒ c | a ∨ c | b"?', opts: ['Verdadera siempre', 'Falsa: contraejemplo c=5, a=8, b=3', 'Verdadera solo si c es primo', 'Verdadera solo si a, b > 0'], c: 1, ex: '<b>Falsa.</b> Contraejemplo: c=5, a=8, b=3: 5 | (8−3) = 5 ✓, pero 5 ∤ 8 y 5 ∤ 3. ▸ (En cambio "a|b ∧ a|c ⇒ a|(b−c)" SÍ es verdadera, por combinación lineal.)'},
  {st: '(Tema 06, Ej 4b) Si a = 4n+1 y b = 6n−1 con n ∈ ℤ, ¿qué se puede afirmar de MCD(a, b)?', opts: ['Siempre es 1', 'Es 1 o 5 (porque divide a 5)', 'Siempre es 5', 'Puede ser cualquier número'], c: 1, ex: 'Si d = MCD(a,b), entonces d | (3a − 2b) = 3(4n+1) − 2(6n−1) = 5. Como d | 5, resulta d ∈ {1, 5}. ▸ Por eso "MCD = 1 ∨ MCD = 5" es <b>verdadero</b>; no siempre es 1 ni siempre 5.'},
  {st: '(Tema 07, ít. 9) ¿Cuál de estas es verdadera para todo n ∈ ℕ?', opts: ['(3n, n+4) = 1', '(5−2n, n−2) = 1', '(n+1, n+4) = 1', '(3n−2, 2n+1) = 1'], c: 1, ex: 'Para (5−2n, n−2): 1·(5−2n) + 2·(n−2) = 1, así que el MCD divide a 1 → es 1 ∀n. ▸ (3n,n+4) falla en n=4 (da 4); (n+1,n+4) divide a 3 (falla en n=2: da 3); (3n−2,2n+1) divide a 7 (falla en n=3: da 7).'},
  {st: '(Tema 02, Ej 4a) ¿Por qué x = (2a+1)² e y = 4a(a+1) son coprimos para todo a ∈ ℤ?', opts: ['Porque x es par e y impar', 'Porque y = x − 1, y dos enteros consecutivos son coprimos', 'Porque ambos son primos', 'Porque MCD(x,y) = 2'], c: 1, ex: '4a(a+1) = 4a²+4a = (2a+1)² − 1, así que y = x − 1. Dos <b>enteros consecutivos</b> siempre tienen MCD 1: MCD(x, x−1) = 1. ▸ x es impar (no par); no son primos en general; el MCD es 1, no 2.'},
]);

registerExercises('led-primer-parcial', '6', [
  {st: 'Una relación R es de equivalencia si y solo si es:', opts: ['Reflexiva, simétrica y transitiva', 'Reflexiva, antisimétrica y transitiva', 'Simétrica y transitiva', 'Reflexiva, simétrica y asimétrica'], c: 0, ex: 'Equivalencia = <b>reflexiva + simétrica + transitiva</b>. ▸ Reflexiva+antisimétrica+transitiva es orden parcial; sin reflexividad falta una propiedad; "asimétrica" es incompatible con "simétrica".'},
  {st: '(Tema 05, Ej 5a) La relación x R y ⟺ x·y² − x²·y − y + x = 0 equivale a:', opts: ['x = y únicamente', 'x = y ∨ x·y = 1', 'x + y = 0', 'x² = y²'], c: 1, ex: 'Factorizo: xy² − x²y − y + x = xy(y−x) − (y−x) = (y−x)(xy−1) = 0 ⟺ <b>x = y ∨ xy = 1</b>. Es de equivalencia; sus clases son [a] = {a, 1/a} (con [0] = {0}). ▸ Las otras pierden una de las dos ramas.'},
  {st: '(Tema 04, Ej 5a) Con f(x) = x² − 5x y x R y ⟺ f(x) = f(y), la clase de un a genérico es:', opts: ['{a}', '{a, 5 − a}', '{a, −a}', '{a, 5a}'], c: 1, ex: 'f(x)=f(y) ⟺ x²−5x = y²−5y ⟺ (x−y)(x+y−5) = 0 ⟺ x=y ∨ x+y=5. Clase [a] = <b>{a, 5 − a}</b> (dos elementos), salvo [5/2] que tiene uno solo. ▸ "−a" y "5a" no salen de la factorización.'},
  {st: '(Tema 04, Ej 5b) La relación en ℕ "x R y ⟺ MCD(x, y) = 1":', opts: ['Es de equivalencia', 'No es reflexiva (p. ej. MCD(2,2)=2≠1)', 'Es de orden', 'Es antisimétrica'], c: 1, ex: 'Falla la reflexividad: MCD(a,a)=a, que es 1 solo si a=1 → no es reflexiva. Tampoco es transitiva: MCD(2,3)=1 y MCD(3,4)=1 pero MCD(2,4)=2. ▸ Es simétrica, pero no de equivalencia ni de orden.'},
  {st: '(Tema 07, ít. 6) Una matriz 7×7 que representa una relación de EQUIVALENCIA puede tener:', opts: ['5 unos y 44 ceros', '28 unos y 21 ceros', '32 unos y 17 ceros', '49 unos'], c: 3, ex: 'La cantidad de unos es la suma de los cuadrados de los tamaños de las clases (dentro de cada clase, todos los pares están relacionados). Una sola clase de 7 → 7² = <b>49 unos</b> (relación universal). ▸ 5 es menos que los 7 de la diagonal (imposible); 28 y 32 no se obtienen con ninguna partición de 7.'},
  {st: '(Tema 07, ít. 7) En P(A), la relación X R Y ⟺ X ∩ Y ≠ ∅ es:', opts: ['Reflexiva', 'Simétrica', 'Antisimétrica', 'Transitiva'], c: 1, ex: 'Es <b>simétrica</b> (X∩Y ≠ ∅ ⟺ Y∩X ≠ ∅). ▸ No es reflexiva: ∅ ∩ ∅ = ∅, así que ∅ no se relaciona consigo mismo. No es antisimétrica ni transitiva (X={1}, Y={1,2}, Z={2}: X∩Y≠∅, Y∩Z≠∅, pero X∩Z=∅).'},
  {st: '(Tema 07, ít. 8) Para la equivalencia en ℤ×ℤ "(x,y) R (z,t) ⟺ 2 | (x+z) ∧ 3 | (y−t)", el conjunto cociente tiene:', opts: ['3 clases', '6 clases', 'Infinitas clases', '2 clases'], c: 1, ex: 'La primera coordenada se agrupa por paridad (2 clases) y la segunda por resto módulo 3 (3 clases): 2 · 3 = <b>6 clases</b>. ▸ Es finito porque ambas condiciones son congruencias.'},
  {st: '(Tema 09, Ej 5a) "Si R y T son transitivas, entonces R ∪ T es transitiva." Esto es:', opts: ['Verdadero', 'Falso: contraejemplo R={(1,2)}, T={(2,3)}', 'Verdadero solo si son finitas', 'Verdadero solo si R ⊆ T'], c: 1, ex: '<b>Falso.</b> R={(1,2)} y T={(2,3)} son transitivas (vacuosamente), pero R∪T={(1,2),(2,3)} no tiene (1,3). ▸ La intersección de transitivas sí es transitiva (Tema 06), pero la unión no.'},
  {st: '(Tema 03, Ej 5) Para x S y ⟺ |x²−2| = |y²−2|, ¿cuál conjunto sirve como conjunto cociente?', opts: ['P₁ = {[x]/x ≥ 1}', 'P₂ = {[x]/x ≥ 0}', 'P₃ = {[x]/x ≥ √2}', 'P₄ = {[x]/x ≥ 2}'], c: 2, ex: 'Hace falta exactamente un representante por clase. Para x ≥ √2, |x²−2| = x²−2 es creciente (clases distintas) y toda clase tiene un representante √(2+c) ≥ √2 → <b>P₃</b>. ▸ P₁ y P₂ repiten clases; P₄ deja afuera la clase de 1 (cuyos elementos son ≤ √3 < 2).'},
]);

registerExercises('led-primer-parcial', '7', [
  {st: '(Tema 07 · ít. 1) Dados A = {1,2,3,4,5,6,7,8,9} y B = {x,y,z}, la cantidad de funciones de A en B es:', opts: ['C(9,3)', '9³', '3⁹', 'C(11,3)'], c: 2, ex: 'Cada uno de los 9 elementos del dominio elige una de las 3 imágenes → <b>3⁹</b> = 19683. ▸ 9³ invierte dominio y codominio; las combinaciones no describen funciones.'},
  {st: '(Tema 07 · ít. 2) La cantidad de anagramas de FELICIDADES es:', opts: ['11! − 2!·3', '11! / 8', '8!·2!·2!·2!', '11!'], c: 1, ex: '11 letras con E, I y D repetidas (×2 cada una): 11! / (2!·2!·2!) = <b>11!/8</b> = 4.989.600. ▸ 11! sobrecuenta tratando iguales como distintas.'},
  {st: '(Tema 07 · ít. 3) La expresión (n+1)! − (n−1)!·n² es equivalente a:', opts: ['n²', '2n²', 'n!', '2n!'], c: 2, ex: '(n+1)! = (n+1)n(n−1)!; factor común (n−1)!: (n−1)![(n+1)n − n²] = (n−1)!·n = <b>n!</b>.'},
  {st: '(Tema 07 · ít. 4) "Todos los archivos personales están dañados. Algunos archivos dañados tienen contraseña." Entonces necesariamente:', opts: ['Algunos archivos personales tienen contraseña', 'Algún archivo con contraseña es personal', 'Algún archivo personal no tiene contraseña', 'Ninguna de las anteriores'], c: 3, ex: 'Personales ⊆ Dañados, pero los dañados-con-contraseña podrían no ser personales → no se deduce ninguna de (a), (b), (c). Correcta: <b>(d)</b>.'},
  {st: '(Tema 07 · ít. 5) Sabiendo que r: ∀x: ∃y: p(x,y) es Verdadera, también lo es:', opts: ['∀x: ∀y: p(x,y)', '∃y: ∀x: p(x,y)', '∃x: ∃y: p(x,y)', '∀x: ∃y: ¬p(x,y)'], c: 2, ex: 'De "para todo x existe y" se sigue, en universo no vacío, <b>∃x: ∃y: p(x,y)</b>. ▸ (a) y (b) son más fuertes; (d) no tiene relación.'},
  {st: '(Tema 07 · ít. 6) Una matriz de 7×7 que representa una relación de EQUIVALENCIA puede tener:', opts: ['5 unos y 44 ceros', '28 unos y 21 ceros', '32 unos y 17 ceros', '49 unos'], c: 3, ex: 'Cantidad de unos = suma de cuadrados de los tamaños de clase. Una clase de 7 → <b>49 unos</b> (relación universal). ▸ Ninguna partición de 7 da 5, 28 ni 32 unos (con la diagonal obligatoria de 7).'},
  {st: '(Tema 07 · ít. 7) La relación en P(A) dada por X R Y ⟺ X ∩ Y ≠ ∅ es:', opts: ['Reflexiva', 'Simétrica', 'Antisimétrica', 'Transitiva'], c: 1, ex: '<b>Simétrica</b>. No reflexiva (∅∩∅=∅); no antisimétrica; no transitiva ({1}, {1,2}, {2}).'},
  {st: '(Tema 07 · ít. 8) Para la equivalencia en ℤ×ℤ "(x,y) R (z,t) ⟺ 2|(x+z) ∧ 3|(y−t)", el conjunto cociente está formado por:', opts: ['3 clases de equivalencia', '6 clases de equivalencia', '∞ (infinitas) clases', 'n.a.'], c: 1, ex: 'Paridad de la 1ª coordenada (2 opciones) × resto módulo 3 de la 2ª (3 opciones) = <b>6 clases</b>.'},
  {st: '(Tema 07 · ít. 9) De las siguientes es verdadera ∀n ∈ ℕ:', opts: ['(3n, n+4) = 1', '(5−2n, n−2) = 1', '(n+1, n+4) = 1', '(3n−2, 2n+1) = 1'], c: 1, ex: '1·(5−2n) + 2·(n−2) = 1 ⇒ el MCD divide a 1 ⇒ es <b>(5−2n, n−2) = 1</b>. ▸ Las otras dividen a 4, 3 y 7 respectivamente (fallan para algún n).'},
  {st: '(Tema 07 · ít. 10) Es equivalente a ∑(i=h+1..2(h+1)) 3ⁱ la opción:', opts: ['∑(i=h+1..2h) 3ⁱ + 3^{2(h+1)}', '∑(i=h..2h) 3ⁱ + 3^{2h+1} + 3^{2h+2}', '∑(i=h..2h+1) 3ⁱ + 3^{2(h+1)} − 3ʰ', 'n.a.'], c: 2, ex: 'La suma va de h+1 a 2h+2. La opción (c): ∑(h..2h+1) agrega 3ʰ de más y le falta 3^{2h+2}; al sumar 3^{2(h+1)} y restar 3ʰ queda exactamente la original. ▸ (a) pierde 3^{2h+1}; (b) agrega 3ʰ de más.'},
  {st: '(Tema 07 · ít. 11) De 50 personas, 28 toman café o mate. Los que toman café y no mate son 9. La cantidad que toman mate es:', opts: ['13', '19', '22', '41'], c: 1, ex: '|café ∪ mate| = (solo café) + (toman mate): 28 = 9 + |mate| ⇒ <b>19</b>.'},
]);
