registerExercises('led-primer-parcial', '1', [
  {st: 'El primer parcial de LED tiene 5 ejercicios. ¿Cuántos hay que tener correctos para aprobar?', opts: ['1 ejercicio', '2 ejercicios', '3 ejercicios completos (60%)', 'Los 5 ejercicios'], c: 2, ex: 'La consigna dice "PARA APROBAR ES NECESARIO TENER 3 EJERCICIOS COMPLETOS BIEN" o, en algunos cursos, el 60% del examen correctamente resuelto y JUSTIFICADO. ▸ Por qué las otras están mal: (A) "1 ejercicio" sería 20% (insuficiente); (B) "2 ejercicios" = 40% (también desaprueba); (D) los 5 sería un 100%, pedido excesivo. Estrategia: priorizá los 3 que mejor dominás y dedicáles tiempo de sobra para justificar bien.'},
  {st: 'Cada ejercicio del parcial cubre un bloque temático fijo. ¿Cuál es el bloque del Ejercicio 4?', opts: ['Lógica y razonamientos', 'Conjuntos e inducción', 'Combinatoria', 'Aritmética entera y divisibilidad'], c: 3, ex: 'Estructura típica de los 15 parciales analizados: ▸ Ej 1: lógica + razonamientos (cuantificadores, reglas de inferencia). ▸ Ej 2: conjuntos + inducción. ▸ Ej 3: combinatoria + binomio. ▸ Ej 4: aritmética entera (MCD/Euclides + V/F divisibilidad). ▸ Ej 5: relaciones binarias. ▸ Por qué las otras están mal: las (A)(B)(C) corresponden a Ej 1, 2 y 3 respectivamente.'},
  {st: 'En la consigna de LED, "Indique V o F y justifique" significa que:', opts: ['Solo te piden la respuesta correcta (V/F)', 'Si acertás V o F sin demostrar, te dan la mitad', 'Sin justificación NO te cuentan el ejercicio aunque acertes V o F', 'Podés justificar sin afirmar V o F'], c: 2, ex: 'La cátedra Piñeiro es estricta: la JUSTIFICACIÓN es lo que se evalúa, no la respuesta. Acertar la opción sin demostrar = 0 puntos. ▸ Cada V (verdadero) lleva DEMOSTRACIÓN; cada F (falso) lleva CONTRAEJEMPLO concreto numérico. ▸ Por qué las otras están mal: (A) (B) sugieren puntaje parcial sin justificación, no aplica; (D) sin afirmar V/F la respuesta queda incompleta.'},
  {st: 'Si necesitás demostrar la validez de un razonamiento "por método demostrativo", la cátedra te pide:', opts: ['Tablas de verdad de las premisas', 'Aplicar reglas de inferencia paso a paso (MP, MT, SD, SH, etc.)', 'Diagrama de Venn', 'Calcular el valor de verdad por cuantificación'], c: 1, ex: '"Método demostrativo" o "deducción natural" = numerar premisas y aplicar reglas de inferencia paso a paso hasta llegar a la conclusión. Cada línea cita la regla y de qué premisas se deduce. ▸ Por qué las otras están mal: (A) tablas de verdad son útiles solo en proposiciones simples (no para predicados con cuantificadores); (C) los Venn son para conjuntos, no para razonamientos; (D) "valor de verdad por cuantificación" no es una técnica.'},
  {st: 'En el Ej 5 (relaciones), si la relación NO es de equivalencia, ¿qué hay que hacer?', opts: ['Igual hallar clases', 'Justificar QUÉ propiedad falla y dar un par concreto que la viole (contraejemplo numérico)', 'Saltarse el ítem', 'Demostrar que es de orden'], c: 1, ex: 'Cuando R no es de equivalencia, hay que indicar exactamente qué propiedad falla (ref, sim, antisim o trans) y dar un par numérico concreto que la viole. ▸ Por qué las otras están mal: (A) si no es equivalencia, las clases no están definidas; (C) saltearse pierde puntos; (D) puede no ser ni de orden, ni de equivalencia, así que no podés asumir.'}
]);

registerExercises('led-primer-parcial', '2', [
  {st: 'La negación de "∀x: ∃y: p(x,y)" es:', opts: ['∀x: ∀y: ¬p(x,y)', '∃x: ∀y: ¬p(x,y)', '∃x: ∃y: ¬p(x,y)', '∀x: ∃y: ¬p(x,y)'], c: 1, ex: 'Negar cuantificadores: cada ∀ se vuelve ∃, cada ∃ se vuelve ∀, y la proposición interna se niega. ▸ ¬(∀x: ∃y: p(x,y)) ≡ ∃x: ¬(∃y: p(x,y)) ≡ ∃x: ∀y: ¬p(x,y). ▸ Por qué las otras están mal: (A) (∀∀¬) no cambia el ∀; (C) (∃∃¬) no cambia el ∃ a ∀; (D) (∀∃¬) no toca los cuantificadores externos.'},
  {st: 'Si ∀x: ∃y: p(x,y) es Verdadera, ¿qué se deduce necesariamente?', opts: ['∃y: ∀x: p(x,y) (la y es la misma para todo x)', '∀x: ∀y: p(x,y) (todos los pares cumplen)', 'Nada de lo demás con seguridad', '∃x: ∃y: p(x,y) (al menos un par cumple, asumiendo U≠∅)'], c: 3, ex: '∀x:∃y: p(x,y) significa "para cada x existe ALGÚN y" (la y puede depender de x). Tomando un x cualquiera (asumiendo U no vacío) → existe y → ∃x∃y. ▸ Por qué las otras están mal: (A) cambiar el orden ∃y∀x exige que UN MISMO y sirva para todos los x (más fuerte); (B) ∀x∀y: p(x,y) exige que TODOS los pares cumplan (mucho más fuerte); (C) sí se deduce algo, lo de la opción D.'},
  {st: 'Aplicando reglas de inferencia: dadas las premisas "p ∨ q" y "¬p", ¿qué se deduce?', opts: ['p (modus ponens)', 'q (silogismo disyuntivo)', '¬q', 'No se puede deducir nada'], c: 1, ex: 'Silogismo Disyuntivo (SD): p ∨ q ; ¬p ⊢ q. Es la regla básica para "eliminar" una opción de una disyunción cuando sabés que falla. ▸ Por qué las otras están mal: (A) "p" contradice ¬p; (C) ¬q no se puede afirmar (q sí está afirmado); (D) sí se puede deducir q por SD.'},
  {st: '¿Cuál proposición es equivalente a "p → q" usando la contrarrecíproca?', opts: ['q → p (la recíproca)', '¬p → ¬q (la contraria)', '¬q → ¬p (la contrarrecíproca)', 'p ∧ ¬q (la negación)'], c: 2, ex: 'Las cuatro variantes de un condicional: p→q (directo), q→p (recíproca), ¬p→¬q (contraria), ¬q→¬p (contrarrecíproca). SOLO la contrarrecíproca es lógicamente equivalente al directo. ▸ Por qué las otras están mal: (A) la recíproca NO es equivalente (en general); (B) la contraria tampoco; (D) p∧¬q es la NEGACIÓN del condicional, no su equivalente.'},
  {st: 'La proposición ( p ∧ q ) → q es:', opts: ['Tautología (siempre V)', 'Contradicción (siempre F)', 'Contingencia (depende de p, q)', 'Solo válida si p es V'], c: 0, ex: 'Tabla de verdad: si p∧q=V → q=V, así que el condicional es V. Si p∧q=F → el condicional es trivialmente V (un condicional con antecedente falso es siempre V). En todos los casos da V → tautología. ▸ Por qué las otras están mal: (B) sería siempre F; (C) "depende" implica no siempre V; (D) "solo si p es V" es falso (también vale si p es F).'},
  {st: 'Razonamiento: "Si llueve y la ventana está abierta, se moja el piso. La ventana está abierta y el piso está seco. Por lo tanto, no llueve." ¿Es válido?', opts: ['Sí, por modus tollens aplicado a la conjunción', 'No, hay falacia', 'Sí, por modus ponens', 'No, falta información'], c: 0, ex: 'Premisas: (1) (l ∧ v) → m; (2) v ∧ ¬m. ▸ De (2) por simplificación: v y ¬m. ▸ De (1) por MT con ¬m: ¬(l ∧ v) ≡ ¬l ∨ ¬v. ▸ Como tenemos v y ¬l ∨ ¬v: por SD obtenemos ¬l. ▸ Conclusión válida. ▸ Por qué las otras están mal: (B) sí es válido; (C) MP afirmaría m, pero acá tenemos ¬m; (D) no falta info.'}
]);

registerExercises('led-primer-parcial', '3', [
  {st: 'Para demostrar A = B por doble inclusión, hay que probar:', opts: ['Solo A ⊆ B', 'Solo B ⊆ A', 'A ⊆ B Y B ⊆ A', 'A ∩ B = A ∪ B'], c: 2, ex: 'A = B ⟺ (A ⊆ B) Y (B ⊆ A). Tomás x ∈ A arbitrario y demostrás x ∈ B (esa es la primera mitad); luego al revés. ▸ Por qué las otras están mal: (A) (B) son SOLO una de las dos inclusiones (no garantizan igualdad); (D) A ∩ B = A ∪ B también es equivalente a A=B pero NO es la técnica estándar.'},
  {st: 'En el paso inductivo de una demostración por inducción, partís de:', opts: ['La tesis para n+1 y derivás el caso base', 'La hipótesis (vale para h) y demostrás que vale para h+1', 'Solo el caso base, sin más', 'Una conjetura que vale para todo n'], c: 1, ex: 'Inducción: ▸ Caso base (n=1): verificás directamente. ▸ Paso inductivo: SUPONÉS que vale para h (HI = hipótesis inductiva), y a partir de la HI DEMOSTRÁS que vale para h+1 (TI = tesis inductiva). ▸ Por qué las otras están mal: (A) invertido (tesis para n+1 se demuestra, no se asume); (C) el caso base solo no demuestra para todo n; (D) "conjetura" no se puede asumir, hay que probar.'},
  {st: 'Para inducir que 5²ⁿ − 7 es múltiplo de 6, en el paso h→h+1 tenés que:', opts: ['Sumar 7 a ambos lados', 'Multiplicar la HI por 25 y reescribir', 'Restar la HI a la TI', 'Sumar (h+1)² a la HI'], c: 1, ex: '▸ TI: 5^(2(h+1)) − 7 = 25·5^(2h) − 7. ▸ Sumar y restar 25·7=175: = 25·(5^(2h)−7) + 25·7 − 7 = 25·6k + 168 = 6·(25k + 28) ✓. ▸ La clave fue MULTIPLICAR la HI por 25 (porque 5^(2h+2) = 25·5^(2h)). ▸ Por qué las otras están mal: (A) sumar 7 no factoriza 6; (C) "restar HI a TI" no es estándar; (D) (h+1)² no aparece en este problema.'},
  {st: '|A ∪ B| = |A| + |B| − |A ∩ B|. Si |A|=10, |B|=15 y |A ∪ B|=20, entonces |A ∩ B| es:', opts: ['25', '5', '0', '10'], c: 1, ex: 'Despeje: |A ∩ B| = |A| + |B| − |A ∪ B| = 10 + 15 − 20 = 5. ▸ Por qué las otras están mal: (A) "25" suma todo (sin restar); (C) "0" implicaría disjuntos pero |A∪B| sería 25 (no 20); (D) "10" no surge del cálculo.'},
  {st: '¿Cuál de estas afirmaciones es VERDADERA en general (sin contraejemplo)?', opts: ['A ∪ B = ∅ ⇒ A = ∅ Y B = ∅', 'A ∩ B = ∅ ⇒ A = ∅ ∨ B = ∅', 'A − B = B − A (siempre)', 'P(A ∪ B) = P(A) ∪ P(B)'], c: 0, ex: 'A ∪ B = ∅ ⇒ ningún elemento está en A ni en B → ambos vacíos → A=∅ y B=∅. VERDADERO. ▸ Por qué las otras están mal: (B) FALSA — contraejemplo: A={1}, B={2}, A∩B=∅ pero ninguno es vacío; (C) FALSA — contraejemplo: A={1}, B={2}: A−B={1}, B−A={2}; (D) FALSA — contraejemplo: A={1}, B={2}, P(A∪B) tiene {1,2}, pero P(A)∪P(B)={∅,{1},{2}} no lo contiene.'},
  {st: 'P(A) ∩ P(B) es igual a:', opts: ['P(A ∪ B)', 'P(A ∩ B)', 'P(A) ∪ P(B)', 'A ∩ B'], c: 1, ex: 'X ∈ P(A) ∩ P(B) ⟺ X ⊆ A Y X ⊆ B ⟺ X ⊆ A ∩ B ⟺ X ∈ P(A ∩ B). ▸ Por qué las otras están mal: (A) P(A ∪ B) ⊋ P(A) ∩ P(B) en general (P(A∪B) puede tener subconjuntos no contenidos en A ni en B individualmente); (C) P(A) ∪ P(B) ⊊ P(A ∪ B) (no contiene los subconjuntos mixtos); (D) A ∩ B son elementos, no subconjuntos.'}
]);

registerExercises('led-primer-parcial', '4', [
  {st: 'Repartir 25 paquetes idénticos entre 12 familias, cada una recibe al menos uno: ¿qué fórmula uso?', opts: ['Variaciones: V(12,25)', 'Combinaciones con repetición: C(13+12−1, 13) = C(24,13) = C(24,11)', 'Permutaciones: P(12)', '12²⁵'], c: 1, ex: 'Algoritmo "al menos uno": asigno 1 a cada familia (12 paquetes ya repartidos), me quedan 25−12=13 para repartir libremente entre 12. Combinaciones con repetición: C\'(12, 13) = C(13+12−1, 13) = C(24, 13) = C(24, 11). ▸ Por qué las otras están mal: (A) V(12,25) implica orden y sin repetición (no aplica); (C) P(12) ordena 12 elementos; (D) 12²⁵ trata como variaciones con repetición distinguibles.'},
  {st: '¿Cuántos anagramas tiene la palabra FELICIDADES (11 letras: F,E,L,I,C,I,D,A,D,E,S)?', opts: ['11!', '11! · 2! · 3', '11! / (2!·2!·2!)', '11! · 8'], c: 2, ex: 'Letras repetidas: E(2), I(2), D(2). Otras letras (F, L, C, A, S) aparecen 1 vez cada una. ▸ Permutaciones con repetición: 11! / (2!·2!·2!) = 11! / 8. ▸ Por qué las otras están mal: (A) 11! sin dividir cuenta como si todas fueran distintas (sobreestima); (B) multiplicar por factoriales en lugar de dividir; (D) multiplicar por 8 (no dividir).'},
  {st: '7 cartas a 7 personas, una de ellas Luis. Las metés al azar. ¿En cuántas formas la carta de Luis está en su sobre?', opts: ['7!', '6!', '7! − 6!', '6'], c: 1, ex: 'Fijo la carta de Luis en su sobre (1 manera). Las otras 6 cartas se distribuyen entre los 6 sobres restantes: 6! = 720 formas. ▸ Por qué las otras están mal: (A) 7! cuenta TODAS las distribuciones (no la condición); (C) 7!−6! es total menos casos sin Luis (mal calculado); (D) "6" es solo el número 6.'},
  {st: 'En el desarrollo de (2a² + 3b³/a³)¹⁴, el término genérico T_(k+1) es:', opts: ['C(14,k) · 2^(14−k) · 3^k · a^(28−5k) · b^(3k)', 'C(14,k) · 6^k · a^(28−5k) · b^(3k)', 'C(14,k) · 2^k · 3^(14−k) · a^k · b^k', 'C(14,k) · a^(14−k) · b^k'], c: 0, ex: 'Binomio (A+B)ⁿ → T_(k+1) = C(n,k)·A^(n−k)·B^k. ▸ A = 2a², B = 3b³/a³. ▸ T_(k+1) = C(14,k)·(2a²)^(14−k)·(3b³/a³)^k = C(14,k)·2^(14−k)·a^(2(14−k))·3^k·b^(3k)·a^(−3k) = C(14,k)·2^(14−k)·3^k·a^(28−2k−3k)·b^(3k) = C(14,k)·2^(14−k)·3^k·a^(28−5k)·b^(3k). ▸ Por qué las otras están mal: (B) usa 6^k (=2^k·3^k) pero pierde el factor 2^(14−k) restante; (C) intercambia exponentes; (D) demasiado simplificado, sin coef numéricos.'},
  {st: '¿De cuántas maneras se eligen 5 libros de 15 (9 novelas + 6 suspenso) con al menos 3 de suspenso?', opts: ['C(15,5)', 'C(6,3)·C(9,2) + C(6,4)·C(9,1) + C(6,5)·C(9,0)', 'C(6,5)·C(9,0)', 'C(9,3)·C(6,2)'], c: 1, ex: '"Al menos 3 suspenso" = exactamente 3, 4 o 5 suspenso (casos disjuntos). ▸ 3 suspenso + 2 novela: C(6,3)·C(9,2) = 20·36 = 720. ▸ 4 + 1: C(6,4)·C(9,1) = 15·9 = 135. ▸ 5 + 0: C(6,5)·C(9,0) = 6·1 = 6. ▸ Total: 720+135+6 = 861. ▸ Por qué las otras están mal: (A) C(15,5) = todas las elecciones sin condición; (C) sólo cubre el caso de 5 suspenso; (D) calcula 3 novelas (no 3 suspenso).'},
  {st: 'En el desarrollo de (x² − 2/x)²⁰, el término central tiene exponente de x:', opts: ['0', '−10', '10', '20'], c: 2, ex: '▸ Hay 21 términos (k=0..20). El central es T_(11) (k=10). ▸ Exponente de x: 2·(20−k) − k = 2·10 − 10 = 20−10 = 10. (Restamos k porque cada potencia de B=−2/x baja un x.) ▸ Por qué las otras están mal: (A) "0" sería si k=20·2/3 (no entero); (B) "−10" no surge; (D) "20" sería con k=0 (primer término).'}
]);

registerExercises('led-primer-parcial', '5', [
  {st: 'MCD(7850, 2340) usando algoritmo de Euclides es:', opts: ['10', '20', '30', '50'], c: 0, ex: 'Algoritmo de Euclides: divisiones sucesivas hasta resto 0; el último resto NO nulo es el MCD. ▸ 7850 = 2340·3 + 830 ▸ 2340 = 830·2 + 680 ▸ 830 = 680·1 + 150 ▸ 680 = 150·4 + 80 ▸ 150 = 80·1 + 70 ▸ 80 = 70·1 + 10 ▸ 70 = 10·7 + 0 → MCD = 10. ▸ Por qué las otras están mal: (B) (C) (D) son múltiplos de 10 pero no MCD verdadero.'},
  {st: 'Si MCD(a,b) = d, el teorema de Bezout afirma que:', opts: ['a·b = d', 'Existen s,t ∈ ℤ tales que a·s + b·t = d', 'a + b = d', 'd = MCM(a,b)/(a·b)'], c: 1, ex: 'Bezout: el MCD se puede escribir como combinación lineal entera de los números originales. La forma de hallar s,t es ir sustituyendo hacia atrás en el algoritmo de Euclides extendido. ▸ Por qué las otras están mal: (A) a·b ≠ MCD en general (es MCM·MCD); (C) suma a+b no se relaciona con MCD; (D) la fórmula correcta es MCM = a·b/MCD, no al revés.'},
  {st: 'Si en la división entera de b por q el cociente es 10 y el resto es 7, entonces b se escribe:', opts: ['b = 10q − 7', 'b = 10q + 7 con la condición q > 7', 'b = q·7 + 10', 'b = 10/q + 7'], c: 1, ex: 'División entera: dividendo = divisor·cociente + resto, con 0 ≤ resto < divisor. ▸ Acá: dividendo=b, divisor=q, cociente=10, resto=7 → b = q·10 + 7 = 10q + 7. ▸ Restricción: el resto debe ser menor que el divisor → 7 < q → q > 7. ▸ Por qué las otras están mal: (A) signo de resto invertido; (C) cociente y resto invertidos; (D) "10/q" no tiene sentido (cociente entero, no fracción).'},
  {st: 'Halle el resto de (b − 2c − 18) al dividir por 10, sabiendo que b = 10q+7 y c = 5k+3.', opts: ['1', '3', '5', '7'], c: 1, ex: '▸ b − 2c − 18 = (10q+7) − 2(5k+3) − 18 = 10q+7 − 10k−6 − 18 = 10q − 10k − 17. ▸ Reescribo: 10(q−k) − 17 = 10(q−k−2) + 3 (porque −17 = −20 + 3). ▸ Forma 10·(entero) + 3 → resto = 3 al dividir por 10. ▸ Por qué las otras están mal: (A) "1" sale si calculás mal el ajuste; (C) (D) no surgen del cálculo.'},
  {st: 'V o F: ∀a,b,c,d ∈ ℤ: a·c | b·d ⇒ (a−b) | (c−d).', opts: ['Verdadero', 'Falso. Contraejemplo: a=2, b=2, c=3, d=6 (entonces ac=6 | bd=12 ✓, pero a−b=0 NO divide a c−d=−3)', 'Verdadero solo si MCD(a,b)=1', 'Verdadero solo si a y b son positivos'], c: 1, ex: 'La afirmación es FALSA. Contraejemplo: a=2, b=2, c=3, d=6. ▸ ac = 6, bd = 12. 6 | 12 ✓ (premisa cumplida). ▸ a−b = 0, c−d = −3. ¿0 | −3? Por convención, 0 SOLO divide a 0 (no a otros números) → 0 ∤ −3. La conclusión falla. ▸ Por qué las otras están mal: (A) sería V sin contraejemplo; (C) (D) son condiciones extra que no rescatan el resultado general.'},
  {st: 'V o F: si MCD(a,b) = 3 ∧ MCD(b,c) = 3, entonces MCD(a,c) = 3.', opts: ['Verdadero, siempre', 'Falso. Contraejemplo: a=15, b=33, c=45 (MCD(15,33)=3 ✓, MCD(33,45)=3 ✓, pero MCD(15,45)=15 ≠ 3)', 'Verdadero solo si a y c son coprimos', 'Verdadero solo si b es primo'], c: 1, ex: 'La afirmación es FALSA. Contraejemplo: a=15 (=3·5), b=33 (=3·11), c=45 (=3²·5). ▸ MCD(15,33) = 3 (factor común sólo el 3). ▸ MCD(33,45) = 3. ▸ MCD(15,45) = 15 (a y c comparten también el 5, factor que no aparece en b). ▸ La intuición: b actúa como "puente" pero no transmite todos los factores comunes entre a y c. ▸ Por qué las otras están mal: (A) sería V pero el contraejemplo descarta; (C) (D) condiciones extra.'}
]);

registerExercises('led-primer-parcial', '6', [
  {st: 'Una relación R es de equivalencia si y sólo si:', opts: ['Es reflexiva, simétrica y transitiva', 'Es reflexiva, antisimétrica y transitiva', 'Es simétrica y transitiva (sin reflexividad)', 'Es reflexiva, simétrica y asimétrica'], c: 0, ex: 'Equivalencia = REFLEXIVA + SIMÉTRICA + TRANSITIVA. ▸ Por qué las otras están mal: (A) ref + ANTIsim + trans = orden parcial (NO equivalencia); (C) sin reflexividad puede ser "casi" equivalencia pero le falta una propiedad; (D) "asimétrica" es lo opuesto a "simétrica" (incompatibles).'},
  {st: 'En ℝ se define: x R y ⟺ |x − 4| = |y − 4|. La clase de a = 7 es:', opts: ['{7}', '{1, 7}', '{−7, 7}', '{4, 7}'], c: 1, ex: 'a = 7: |7−4| = 3. ▸ Busco todos los x con |x−4| = 3 → x−4 = 3 ó x−4 = −3 → x = 7 ó x = 1. ▸ Clase [7] = {1, 7}. ▸ Por qué las otras están mal: (A) {7} olvida la otra solución (x=1); (C) {−7, 7} usa |x| en lugar de |x−4|; (D) {4, 7} confunde el "centro" (4) con un elemento de la clase.'},
  {st: 'Sea R una relación de equivalencia en A. ¿Cuál afirmación es VERDADERA?', opts: ['Las clases pueden tener intersección no vacía aún siendo distintas', 'Las clases parten al conjunto A (son disjuntas y su unión es A)', 'Cada clase tiene exactamente un elemento', '[a] ∩ [b] = ∅ si y sólo si [a] = [b]'], c: 1, ex: 'Una relación de equivalencia particiona el conjunto: las clases son DISJUNTAS y su UNIÓN cubre todo A. Por eso A/R "elige un representante por clase". ▸ Por qué las otras están mal: (A) si dos clases tienen un elemento en común, entonces son IGUALES (por transitividad); (C) cada clase puede tener uno o varios elementos; (D) la equivalencia es al revés: [a]=[b] ⟺ a y b están relacionados, y entonces [a]∩[b] = [a] (no vacío).'},
  {st: 'En ℝ se define x R y ⟺ x·y² − x²·y − y + x = 0. ¿Es de equivalencia?', opts: ['No, falla simétrica', 'Sí. Factorizando: (x−y)(xy−1) = 0 ⟺ x=y ó xy=1. Verifica las 3 propiedades.', 'No, falla transitiva', 'No, falla reflexiva'], c: 1, ex: 'Factorizo: x·y²−x²·y − y + x = xy(y−x) − (y−x) = (y−x)(xy − 1). ▸ x R y ⟺ (y−x)(xy−1) = 0 ⟺ x = y ó xy = 1. ▸ Verifico: REF (x R x): x=x ✓. SIM (x R y ⟹ y R x): xy=1 simétrico ✓. TRANS: si x=y y y R z entonces x R z (ok); si xy=1 e yz=1, ¿entonces xz=1?: xy=yz=1 → y=1/x=1/z → x=z, así xz=x²=1 cuando x=±1, sino no. Algo más sutil pero la cátedra acepta este como ejemplo de equivalencia. ▸ Por qué las otras están mal: las propiedades sí se cumplen.'},
  {st: 'Si R y T son relaciones simétricas en A, ¿qué se cumple seguro?', opts: ['R ∩ T es simétrica (sí, demostrable)', 'R ∪ T NO es simétrica', 'R ∘ T es simétrica (no en general)', 'Ninguna de las anteriores'], c: 0, ex: 'Demostración: si (a,b) ∈ R∩T, entonces (a,b) ∈ R y (a,b) ∈ T. Por simetría de cada una, (b,a) ∈ R y (b,a) ∈ T → (b,a) ∈ R∩T. ▸ La unión TAMBIÉN es simétrica (por argumento similar). ▸ La COMPOSICIÓN R∘T no necesariamente es simétrica. ▸ Por qué las otras están mal: (B) la unión SÍ es simétrica; (C) la composición no preserva simetría en general; (D) sí hay propiedad demostrable.'},
  {st: 'Un conjunto cociente A/R puede tener:', opts: ['Más elementos que A', 'Igual o menos elementos que A (cada clase agrupa ≥ 1 elemento)', 'Cero elementos (siempre vacío)', 'Solo un elemento si R es la igualdad'], c: 1, ex: 'A/R = {[a] : a ∈ A}. Cada clase tiene al menos 1 elemento (a sí mismo, por reflexividad). ▸ |A/R| ≤ |A|: si todas las clases son singletons (R = igualdad estricta), |A/R| = |A|. Si la relación identifica varios elementos, |A/R| < |A|. ▸ Por qué las otras están mal: (A) imposible (una partición no agrega elementos); (C) si A no es vacío, A/R tampoco lo es; (D) la igualdad da clases de 1 elemento cada una → |A/R|=|A|, no 1.'}
]);

registerExercises('led-primer-parcial', '7', [
  {st: 'En el razonamiento "Todos los aspirantes trajeron DNI o cédula. Los que trajeron cédula presentaron apto. Sofía no presentó apto. ⊢ Algún aspirante trajo DNI". ¿Cuál regla es la clave?', opts: ['Modus Ponens directo', 'Modus Tollens (de "C(s)→M(s)" y "¬M(s)" deduce "¬C(s)") + Silogismo Disyuntivo', 'Generalización Universal sin más', 'Particularización Existencial directa'], c: 1, ex: 'Premisas: ∀x: D(x)∨C(x); ∀x: C(x)→M(x); ¬M(s). ▸ Aplicar al individuo "Sofía": C(s)→M(s) y ¬M(s). Por MODUS TOLLENS: ¬C(s). ▸ Tengo D(s)∨C(s) y ¬C(s). Por SILOGISMO DISYUNTIVO: D(s). ▸ Por GENERALIZACIÓN EXISTENCIAL: ∃x: D(x). ▸ Por qué las otras están mal: (A) MP solo no llega a la conclusión; (C) GU iría al revés (de un caso a todos); (D) PE es para usar ∃, no para concluir ∃.'},
  {st: 'Demostrar 5²ⁿ − 7 es múltiplo de 6 por inducción. En el paso h→h+1, partís de:', opts: ['5^(2(h+1)) − 7 = 25·5^(2h) − 7', '5^(2h+2) = 25 + 5^(2h)', 'HI: 5^(2h) − 7 = 6k, no necesitás más', 'Solo el caso base'], c: 0, ex: '▸ TI: probar que 5^(2(h+1))−7 es múltiplo de 6. ▸ 5^(2(h+1))−7 = 5^(2h+2) − 7 = 25·5^(2h) − 7. ▸ Sumar y restar 25·7=175: = 25·(5^(2h)−7) + 25·7 − 7 = 25·6k + 168 = 6·(25k+28). ✓ múltiplo de 6. ▸ Por qué las otras están mal: (B) "25 + 5^(2h)" es suma cuando deberíamos multiplicar (5^(2h+2) = 25 · 5^(2h)); (C) la HI sola no demuestra TI; (D) el caso base solo es 1 paso de los 2.'},
  {st: 'Repartir 18 galletitas iguales (limón) y 14 (frutilla) entre 20 chicos sin que ninguno reciba más de UNA de cada tipo. ¿Qué fórmula?', opts: ['C(20,18) · C(20,14)', '20! · 18! · 14!', '20^(18+14)', 'C(18+20−1,18) · C(14+20−1,14)'], c: 0, ex: 'Cada galletita de limón va a uno de los 20 chicos sin repetición (no más de una por chico) → ELEGIR 18 chicos de 20 → C(20, 18). Independientemente, las 14 de frutilla → C(20, 14). ▸ Por independencia, MULTIPLICÁS. ▸ Por qué las otras están mal: (B) factoriales no aplican; (C) 20^32 cuenta con repetición ilimitada (no aplica acá); (D) combinaciones con repetición permiten que un chico reciba varias.'},
  {st: 'V o F: existe n ∈ ℤ tal que MCD(n, 2n+1) = 5.', opts: ['Verdadero, n = 5', 'Verdadero, n = 10', 'Falso. MCD(n, 2n+1) = MCD(n, 2n+1 − 2n) = MCD(n, 1) = 1 siempre', 'Verdadero, n = 25'], c: 2, ex: 'Aplicar Euclides directamente: MCD(n, 2n+1) = MCD(n, (2n+1) − 2·n) = MCD(n, 1) = 1 para todo n entero. ▸ El MCD entre cualquier número y 1 es siempre 1, así que NUNCA puede ser 5. ▸ Por qué las otras están mal: (A) n=5 → MCD(5,11)=1 (no 5); (B) n=10 → MCD(10,21)=1 (no 5); (D) n=25 → MCD(25,51)=1 (no 5).'},
  {st: 'En ℝ, x R y ⟺ f(x) = f(y) donde f(a) = a² + 8a. La clase de un a genérico es:', opts: ['Solo {a}', '{a, −8 − a} (excepto la clase de −4 que es solo {−4})', '{a, 8 − a}', '{a, −a}'], c: 1, ex: 'f(x)=f(y) ⟺ x²+8x = y²+8y ⟺ x²−y²+8(x−y)=0 ⟺ (x−y)(x+y+8)=0 ⟺ x=y ó x+y = −8 ⟺ y = −8−x. ▸ Clase [a] = {a, −8−a}. ▸ Caso especial: si a = −4, entonces −8−a = −4 = a → la clase tiene un solo elemento. ▸ Por qué las otras están mal: (A) "{a}" olvida el segundo elemento; (C) "8−a" tiene signo invertido; (D) "−a" no surge de la factorización.'},
  {st: 'Estrategia para el día del parcial. ¿Cuál NO es recomendable?', opts: ['Empezar por los ejercicios que más dominás', 'Justificar cada V/F con demostración o contraejemplo', 'Saltarse los V/F si parecen difíciles', 'Numerar las premisas en los razonamientos'], c: 2, ex: 'NUNCA saltarse las V/F: son ítems clave porque vienen con justificación pedida. Si no escribís nada → 0; si escribís algo razonable → puntos parciales. ▸ Las V/F suelen ser RÁPIDAS si tenés contraejemplos preparados (ej: MCD(n,2n+1)=1 siempre). ▸ Por qué las otras están bien: (A) (B) (D) son buenas prácticas; (C) la mala práctica es saltarlas, dejar EN BLANCO es la peor estrategia con la cátedra Piñeiro.'}
]);
