// ============================================================
// ANÁLISIS MATEMÁTICO A · FINAL CABANA · Guía intensiva
// Basada en 10 finales reales (B/C/D/E, 2022–2024).
// Respuestas ancladas a la opción marcada como correcta en cada
// escaneo. Explicaciones tipo walkthrough: identificar plantilla →
// método paso a paso → por qué las otras opciones están mal.
// ============================================================

// SECCIÓN 1 · ESTRATEGIA Y FORMATO DEL FINAL
registerExercises('analisis-final', '1', [
  {st: '¿Cómo es el examen final de Análisis A (Cátedra Cabana)?', opts: ['Desarrollo, 3 ejercicios', '~10 ejercicios de opción múltiple (una correcta, +1 c/u), 1:30 h, integrador de todo el programa', 'Solo teoría', 'Multiple choice pero sin integrales'], c: 1, ex: 'El final es <b>opción múltiple</b> (~10 ítems, +1 punto cada uno) en 1:30 h y es <b>integrador</b>: suma integrales, series y Taylor a lo del cursado. ▸ Algunas versiones (D/E) traen ítems "a completar". ▸ (D) es falso: integrales es el tema que MÁS cae (100%).'},
  {st: 'Cada fecha se toma en temas B, C, D, E. ¿Qué relación tienen entre sí?', opts: ['Son de materias distintas', 'Son el MISMO examen con los números cambiados (C 2022 y D 2022 son idénticos)', 'El tema E es el más fácil', 'No se parecen'], c: 1, ex: 'Los temas de una misma fecha son <b>el mismo examen con otras constantes</b>. ▸ C 2022 y D 2022 son idénticos ejercicio por ejercicio; igual C/D 2023 y C/D 2024. ▸ Por eso conviene estudiar por <b>plantillas</b> y memorizar el método, no el resultado.'},
  {st: 'Según los 10 finales analizados, ¿cuál es el tema que MÁS aparece?', opts: ['Asíntotas', 'Integrales (áreas, TFC, ecuaciones diferenciales): 100% de los finales', 'Números complejos', 'Continuidad'], c: 1, ex: 'Las <b>integrales</b> están en el 100% de los finales, con 2 a 4 ejercicios cada uno. ▸ Le siguen recta tangente/Taylor (90%), estudio de función (80%) y series (80%). ▸ Dominar esas cuatro columnas cubre casi todo.'},
  {st: 'El enunciado dice: "la recta tangente al gráfico de f en x=1 es y = 5x − 1". ¿Qué datos tenés GRATIS?', opts: ['Solo f(1) = 4', 'Solo f\'(1) = 5', 'f\'(1) = 5 (la pendiente) y f(1) = 4 (la recta evaluada en x=1)', 'f\'\'(1) = 5'], c: 2, ex: 'La recta tangente regala DOS datos: ▸ la <b>pendiente</b> es f\'(1) = 5; ▸ la <b>ordenada en x=1</b> es f(1) = 5·1 − 1 = 4. ▸ Con esos dos arrancás casi cualquier ejercicio de tangente o de reconstrucción de f.'},
  {st: 'En un límite te queda 1 elevado a infinito (por ejemplo (1 + algo→0)^(algo→∞)). ¿Qué usás?', opts: ['L\'Hôpital directo', 'lím (1+f)^g = e^(lím f·g)', 'Barrow', 'Que el resultado es siempre 1'], c: 1, ex: 'La indeterminación 1<sup>∞</sup> se resuelve con <b>lím (1+f)<sup>g</sup> = e<sup>lím f·g</sup></b> (con f→0, g→∞). ▸ (D) es un error clásico: 1<sup>∞</sup> NO es 1, es una indeterminación. ▸ L\'Hôpital se usa para 0/0 o ∞/∞, no directamente acá.'},
  {st: 'Ves una integral con el límite superior variable: d/dx ∫₀^(x²) f(t) dt. ¿Cuánto da?', opts: ['f(x²)', 'f(x²)·2x', 'F(x²) − F(0)', '2x'], c: 1, ex: 'Teorema Fundamental del Cálculo + regla de la cadena: <b>d/dx ∫₀^(u(x)) f = f(u(x))·u\'(x)</b>. ▸ Acá u(x)=x², u\'(x)=2x → <b>f(x²)·2x</b>. ▸ (A) olvida el factor 2x (el error más común); (C) sería el valor de la integral, no su derivada.'}
]);

// SECCIÓN 2 · INTEGRALES, ÁREAS Y TFC
registerExercises('analisis-final', '2', [
  {st: 'El área encerrada por f(x)=e^x y g(x)=e^(−x) en 0 ≤ x ≤ 1 es:', opts: ['1/e + 2', 'e + 1/e − 2', 'e', '1 − e'], c: 1, ex: 'En x ≥ 0, e^x ≥ e^(−x) → integrando (e^x − e^(−x)). ▸ ∫₀¹(e^x − e^(−x))dx = [e^x + e^(−x)]₀¹ = (e + 1/e) − (1 + 1) = <b>e + 1/e − 2</b>. ▸ (A) confunde signos en la primitiva de e^(−x).'},
  {st: 'El área entre f(x)=√x, su recta tangente en P=(1, f(1)) y la recta x=4 se calcula mediante:', opts: ['∫₁⁴ (½x + 1 − √x) dx', '∫₀⁴ (x + ½ − √x) dx', '∫₁⁴ (½x + ½ − √x) dx', '∫₀¹ (√x − ½x + ½) dx + ∫₁⁴ (½x + ½ − √x) dx'], c: 2, ex: 'La tangente en x=1: f\'(1)=1/(2√1)=½, f(1)=1 → y = 1 + ½(x−1) = <b>½x + ½</b>. ▸ La tangente queda por encima de √x en [1,4] → integrando (½x + ½ − √x), de 1 a 4. ▸ (B) y (D) cambian mal el límite inferior a 0 (la región arranca en el punto de tangencia x=1); (A) tiene mal la ordenada de la tangente.'},
  {st: 'El área entre f(x)=√(x+3), g(x)=√(3x−9) y el eje x se obtiene calculando:', opts: ['∫₋₃⁶ (f − g) dx', '∫₋₃³ f dx + ∫₃⁹ g dx', '∫₋₃⁶ f(x) dx − ∫₃⁶ g(x) dx', '∫₃⁶ (f − g) dx'], c: 2, ex: 'f existe desde x=−3; g desde x=3. <b>Corte:</b> x+3 = 3x−9 → x=6. ▸ El área es la de debajo de f (de −3 a 6) menos la parte que g recorta (de 3 a 6): <b>∫₋₃⁶ f − ∫₃⁶ g</b>. ▸ (A) resta g donde g ni existe (de −3 a 3).'},
  {st: 'Calcular lím(x→0⁺) ( ∫₀^(x²) sen(√t) dt ) / x³.', opts: ['0', '2/3', '1', '+∞'], c: 1, ex: 'Es 0/0 → L\'Hôpital. ▸ Numerador (TFC + cadena): d/dx ∫₀^(x²) sen(√t)dt = sen(√(x²))·2x = 2x·sen(x). ▸ Denominador: 3x². ▸ lím [2x·sen(x)]/[3x²] = (2/3)·lím sen(x)/x = (2/3)·1 = <b>2/3</b>. ▸ (A) olvida que sen(x)/x → 1.'},
  {st: 'Hallar f sabiendo que f\'(x) = 2(x+1)·f(x) y f(0) = 6.', opts: ['6·e^(x²+2x)', '6·e^(2x+2)', '6 + x² + 2x', '3·e^(x²+2x)'], c: 0, ex: 'Variables separables: f\'/f = 2(x+1) → ln|f| = x² + 2x + C → f = K·e^(x²+2x). ▸ f(0) = K = 6 → <b>f(x) = 6·e^(x²+2x)</b>. ▸ (D) toma mal la constante inicial (K=3).'},
  {st: 'Sea g continua con ∫₆⁸ g(t) dt = 8. Calcular ∫₃⁴ g(24/x)·(1/x²) dx.', opts: ['1/3', '−1/3', '8', '1/24'], c: 0, ex: 'Sustitución u = 24/x → du = −24/x² dx, o sea (1/x²)dx = −du/24. ▸ Límites: x=3→u=8, x=4→u=6. ▸ ∫ = ∫₈⁶ g(u)·(−1/24)du = (1/24)∫₆⁸ g du = 8/24 = <b>1/3</b>. ▸ En D 2024 el dato es 12 → 1/2. ▸ (C) es el dato sin transformar.'},
  {st: 'Piden hallar k para que el área entre f(x)=e^(kx) y g(x)=e^(kx)+1 en [0,1] sea igual a 1. La respuesta es:', opts: ['k = 0', 'k = 1', 'k ∈ ℝ (cualquier k)', 'No existe k'], c: 2, ex: 'Notá que g(x) − f(x) = (e^(kx)+1) − e^(kx) = <b>1</b> (constante). ▸ El área = ∫₀¹ 1 dx = 1 <b>para todo k</b>. ▸ El truco es ver que la diferencia es constante antes de integrar. Respuesta: k ∈ ℝ.'}
]);

// SECCIÓN 3 · RECTA TANGENTE Y POLINOMIO DE TAYLOR
registerExercises('analisis-final', '3', [
  {st: 'f tiene todas sus derivadas continuas. La recta tangente en x=1 es y = 5x − 1 y f\'\'(x) = 6x. ¿Cuánto vale f(2)?', opts: ['16', '12', '13', '11'], c: 2, ex: 'De la tangente: f\'(1)=5, f(1)=4. ▸ f\'(x)=∫6x dx = 3x²+C₁; f\'(1)=3+C₁=5 → C₁=2 → f\'(x)=3x²+2. ▸ f(x)=x³+2x+C₂; f(1)=3+C₂=4 → C₂=1 → f(x)=x³+2x+1. ▸ f(2)=8+4+1=<b>13</b>. ▸ (B) olvida alguna constante de integración.'},
  {st: 'Si f(x) = 1 + x² + ∫₀^x e^(bt) dt, hallar b para que el polinomio de Taylor de orden 2 en x₀=0 sea P(x) = 1 + x + 2x².', opts: ['0', '2', '1', '−1'], c: 1, ex: 'f(0)=1 ✓. ▸ f\'(x)=2x+e^(bx) (TFC) → f\'(0)=1 ✓ (coincide con el coef de x). ▸ f\'\'(x)=2+b·e^(bx) → f\'\'(0)=2+b. El coef de x² es f\'\'(0)/2=(2+b)/2=2 → 2+b=4 → <b>b=2</b>.'},
  {st: 'Para f(x) = cos(x) + a·x², el polinomio de Taylor de orden 2 en 0 es P(x) = 1 + b·x + 9x². Hallar a y b.', opts: ['a = 9, b = 0', 'a = 19/2, b = 0', 'a = 9, b = 1', 'a = 18, b = 0'], c: 1, ex: 'f\'(x)=−sen(x)+2ax → f\'(0)=0 → <b>b=0</b>. ▸ f\'\'(x)=−cos(x)+2a → f\'\'(0)=−1+2a. ▸ Coef de x²: (−1+2a)/2=9 → −1+2a=18 → <b>a=19/2</b>. ▸ (A) olvida el aporte de cos(x) (que da −1) en f\'\'(0).'},
  {st: 'f(x) = x·e^(cos(x)). Su recta tangente en x=0 es paralela a y = e^(4k)·x + 1. Hallar k.', opts: ['k = 1/4', 'k = 1', 'k = e', 'k = 0'], c: 0, ex: 'f\'(x) = e^(cos x) + x·e^(cos x)·(−sen x) → f\'(0) = e^(cos 0) = e^1 = e. ▸ Paralela ⇒ misma pendiente: e^(4k) = e → 4k = 1 → <b>k = 1/4</b>. ▸ En E 2022 la recta es e^(−k)x → k = −1.'},
  {st: 'g(x) = ln(kx − 3) tiene recta tangente de pendiente 3 en x=2. Hallar k.', opts: ['k = 3', 'k = 9/5', 'k = 5/9', 'k = 6'], c: 1, ex: 'g\'(x) = k/(kx − 3). ▸ Pendiente en x=2: g\'(2) = k/(2k − 3) = 3 → k = 3(2k − 3) = 6k − 9 → 9 = 5k → <b>k = 9/5</b>.'},
  {st: '¿Por qué la recta tangente a f en x=a "regala" dos datos?', opts: ['Porque siempre pasa por el origen', 'Porque su pendiente es f\'(a) y su valor en x=a es f(a)', 'Porque es horizontal', 'No regala datos'], c: 1, ex: 'La tangente y = f(a) + f\'(a)(x−a) contiene la <b>pendiente f\'(a)</b> y el <b>punto (a, f(a))</b>. ▸ Evaluándola en x=a obtenés f(a); su coeficiente de x es f\'(a). ▸ Con esos dos datos arrancás las reconstrucciones y los Taylor.'}
]);

// SECCIÓN 4 · ESTUDIO DE FUNCIÓN
registerExercises('analisis-final', '4', [
  {st: 'Sea f: [1;5] → ℝ, f(x) = ∛((x²−4x)²). ¿Cuál afirmación es correcta?', opts: ['x = 5 es máximo absoluto', 'x = 2 es máximo absoluto', 'f decrece en (1; 2)', 'f crece en (2; 4)'], c: 0, ex: 'f(x)=|x(x−4)|^(2/3). ▸ Comparo en [1,5]: f(1)=3^(2/3)≈2,08; f(4)=0 (mínimo); f(5)=5^(2/3)≈2,92. ▸ El mayor es f(5) → <b>x=5 máximo absoluto</b>. ▸ (B) x=2 da 4^(2/3)≈2,52, menor que f(5). ▸ En [1;6] (C/D 2022) el máximo cae en x=6.'},
  {st: 'Para f(x) = (x²−24)·e^(x+7), ¿en qué intervalo DECRECE?', opts: ['(−∞; −6)', '(−6; 4)', '(4; +∞)', 'En todo ℝ'], c: 1, ex: 'f\'(x) = e^(x+7)(x²+2x−24) = e^(x+7)(x+6)(x−4). ▸ Como e^(x+7)>0, el signo lo da (x+6)(x−4): negativo entre las raíces. ▸ f\' < 0 en <b>(−6; 4)</b> → decrece ahí (y crece afuera). ▸ x=−6 máximo local, x=4 mínimo absoluto.'},
  {st: 'La imagen de la campana f(x) = 3·e^(−5(x−8)²) es:', opts: ['[0; 3]', '(0; 3]', 'ℝ', '(0; +∞)'], c: 1, ex: 'f\'(x) se anula en x=8 (máximo absoluto): f(8)=3 (alcanzado). ▸ Cuando x→±∞, f→0 pero <b>nunca lo alcanza</b>. ▸ Imagen = <b>(0; 3]</b> (el 3 sí, el 0 no). ▸ (A) incluiría el 0, que no se alcanza.'},
  {st: 'En un intervalo CERRADO [a,b], ¿dónde puede estar el máximo absoluto de una función continua?', opts: ['Solo donde f\'=0', 'En un punto crítico (f\'=0 o f\' no existe) o en un extremo del intervalo', 'Siempre en el medio', 'Nunca en los extremos'], c: 1, ex: 'Por Weierstrass, en [a,b] hay máximo y mínimo absolutos. ▸ Los candidatos son los <b>puntos críticos</b> (f\'=0 o f\' no derivable) Y los <b>extremos a y b</b>. ▸ Error clásico: buscar solo en los críticos y olvidar evaluar f(a) y f(b) — de hecho en ∛((x²−4x)²) el máximo está en el extremo.'},
  {st: 'Para hacer el estudio del signo de f\' cuando f\'(x) = e^(x+7)·(x+6)(x−4), ¿qué factor podés ignorar para el signo?', opts: ['(x+6)', 'e^(x+7), porque siempre es positivo', '(x−4)', 'Ninguno'], c: 1, ex: 'La exponencial <b>e^(x+7) es siempre positiva</b>, así que no cambia el signo: el signo de f\' lo deciden solo (x+6)(x−4). ▸ Eso simplifica: raíces en −6 y 4, signo + fuera y − entre ellas.'}
]);

// SECCIÓN 5 · SERIES
registerExercises('analisis-final', '5', [
  {st: 'Hallar p para que la serie Σ (n^p / 5^(np))·(x^n / 3^n) converja para |x| < 75.', opts: ['p = 3', 'p > 2', 'p < 1', 'p = 2'], c: 3, ex: 'Criterio de la raíz: el factor (n^p)^(1/n) → 1, así que el radio es R = 3·5^p. ▸ Impongo R = 75: 3·5^p = 75 → 5^p = 25 → <b>p = 2</b>. ▸ En C/D 2022 es 2·3^p = 54 → p = 3.'},
  {st: '¿Para qué valores de a converge la serie geométrica Σ(n≥0) e^(an) / 3^n?', opts: ['a < ln 3', 'a > 3', 'a < 3', 'a > ln 3'], c: 0, ex: 'Es geométrica de razón r = e^a/3. ▸ Converge ⟺ |r| < 1 → e^a/3 < 1 → e^a < 3 → <b>a < ln 3</b>. ▸ En D 2023 (denominador 5^n): a < ln 5.'},
  {st: '¿Para qué valores de a converge la serie numérica Σ n / (n^a + 1)?', opts: ['a > 1', 'a > 2', 'a < 2', 'a ≥ 0'], c: 1, ex: 'Para n grande, n/(n^a+1) ~ n/n^a = 1/n^(a−1) (comparación en el límite). ▸ Es una p-serie con p = a−1, que converge ⟺ p > 1 → a−1 > 1 → <b>a > 2</b>.'},
  {st: 'Una p-serie Σ 1/n^p converge si y solo si:', opts: ['p > 0', 'p ≥ 1', 'p > 1', 'p < 1'], c: 2, ex: 'La p-serie converge <b>si y solo si p > 1</b>. ▸ Con p=1 es la serie armónica (diverge). ▸ Este criterio es la base de la comparación: llevás tu serie a la forma 1/n^p y mirás el exponente.'},
  {st: 'Para calcular la suma de una serie geométrica Σ(n≥0) A·r^n (con |r|<1), usás:', opts: ['A·r', 'A/(1 − r)', 'A/(1 + r)', 'A·(1 − r)'], c: 1, ex: 'La suma de una geométrica convergente es <b>A/(1 − r)</b>, con A el primer término y r la razón. ▸ Se usa, por ejemplo, para despejar el parámetro cuando dan el valor de la suma (B 2023: Σ 3^(n+1)/a^(2n) = 48/13 → a = 4 o −4).'}
]);

// SECCIÓN 6 · CONTINUIDAD Y DERIVABILIDAD DE PARTIDAS
registerExercises('analisis-final', '6', [
  {st: 'f(x) = (1 − cos(3ax))/(5(e^x − 1)) si x>0 ; 17x² + 90x si x ≤ 0. El valor de a ≥ 0 para que f sea derivable en x₀=0 es:', opts: ['a = 10', 'a = 0', 'a = 90', 'cualquier a positivo'], c: 0, ex: 'Rama izquierda: derivada 34x+90 → en 0 vale 90. ▸ Rama derecha con equivalentes: 1−cos(3ax) ~ 9a²x²/2, 5(e^x−1) ~ 5x → la rama ~ (9a²/10)·x, con "pendiente" 9a²/10. ▸ Derivable ⇒ derivadas laterales iguales: 9a²/10 = 90 → a² = 100 → <b>a = 10</b>.'},
  {st: 'La rama (2x·ln x + x² − 1)/(x − 1) cuando x→1 debe empalmar con un valor 2k − 10 para que f sea continua. Hallar k.', opts: ['k = 2', 'k = 7', 'k = 4', 'k = 3'], c: 1, ex: 'El límite es 0/0 → L\'Hôpital: numerador 2·ln x + 2 + 2x, denominador 1; en x=1: 0 + 2 + 2 = 4. ▸ Continuidad: 2k − 10 = 4 → 2k = 14 → <b>k = 7</b>. ▸ En E 2022 empalma contra k directo → k = 4.'},
  {st: '¿Qué relación hay entre continuidad y derivabilidad en un punto?', opts: ['Son lo mismo', 'Derivable ⇒ continua, pero continua NO implica derivable', 'Continua ⇒ derivable', 'No hay relación'], c: 1, ex: 'Toda función derivable en un punto es continua ahí, <b>pero no al revés</b> (ej: |x| es continua en 0 pero no derivable). ▸ Por eso para derivabilidad hay que igualar TAMBIÉN las derivadas laterales, no solo los valores.'},
  {st: 'Para que una función partida sea DERIVABLE en el empalme x₀, ¿qué hay que igualar?', opts: ['Solo los valores (límites laterales)', 'Los límites laterales Y las derivadas laterales', 'Solo las derivadas', 'Nada, se cumple siempre'], c: 1, ex: 'Derivabilidad exige <b>continuidad</b> (límites laterales iguales al valor) <b>y además</b> que las <b>derivadas laterales coincidan</b>. ▸ Si solo igualás los valores, garantizás continuidad pero no derivabilidad.'},
  {st: 'lím(x→1) (√x − 1)/sen(1 − x) da (por L\'Hôpital):', opts: ['1/2', '−1/2', '1', '0'], c: 1, ex: '0/0 → L\'Hôpital: numerador 1/(2√x) → en x=1 vale 1/2; denominador −cos(1−x) → en x=1 vale −1. ▸ Límite = (1/2)/(−1) = <b>−1/2</b>. ▸ Este límite fija la constante de continuidad en C/D 2024.'}
]);

// SECCIÓN 7 · LÍMITES
registerExercises('analisis-final', '7', [
  {st: 'Calcular lím(x→+∞) (1 + (√x + 4)/(3x + 1))^(2√x).', opts: ['e^(4/3)', 'e^2', 'e^(2/3)', '+∞'], c: 2, ex: 'Es 1^∞ → e^(lím f·g). ▸ Exponente: [(√x+4)/(3x+1)]·2√x, para x grande ~ (√x·2√x)/(3x) = 2x/(3x) = 2/3. ▸ Resultado <b>e^(2/3)</b>. ▸ Atajo: para denominador dx+1 da e^(2/d). ▸ (A) confunde el 4 del numerador con el exponente.'},
  {st: 'Determinar a tal que lím(x→+∞) ((5x² + 3)/(5x² − 1))^(a·x²) = e^20.', opts: ['a = 25', 'a = 20', 'a = 4', 'a = 5'], c: 0, ex: 'base − 1 = (5x²+3 − (5x²−1))/(5x²−1) = 4/(5x²−1). ▸ Exponente del e: lím (base−1)·a x² = lím 4a x²/(5x²−1) = 4a/5. ▸ Impongo 4a/5 = 20 → <b>a = 25</b>.'},
  {st: 'Calcular lím(x→9) 5·sen(x − 9)/(√x − 3).', opts: ['5', '30', '0', '+∞'], c: 1, ex: '0/0 → L\'Hôpital: numerador 5·cos(x−9) → en x=9 vale 5; denominador 1/(2√x) → en x=9 vale 1/6. ▸ Límite = 5/(1/6) = 5·6 = <b>30</b>. ▸ Con factor 3 (E 2022) da 18. Atajo: 6·(factor).'},
  {st: 'En el límite tipo e (1 + (√x+c)/(dx+1))^(2√x), el atajo para el resultado es:', opts: ['e^(c/d)', 'e^(2/d)', 'e^(2c)', 'e^d'], c: 1, ex: 'El exponente del e es lím [(√x+c)/(dx+1)]·2√x → 2/d (los términos c y +1 se vuelven despreciables frente a los de mayor orden). ▸ Resultado <b>e^(2/d)</b>: solo depende del coeficiente d del denominador.'},
  {st: '¿Cuándo se puede aplicar la regla de L\'Hôpital?', opts: ['Siempre', 'Cuando el límite da una indeterminación 0/0 o ∞/∞', 'Solo con senos', 'Cuando el resultado es infinito'], c: 1, ex: 'L\'Hôpital se aplica a las indeterminaciones <b>0/0</b> o <b>∞/∞</b>: derivás numerador y denominador por separado y volvés a evaluar. ▸ (A) es falso: si no hay indeterminación, no corresponde. ▸ Para 1^∞ primero pasás a la forma e^(lím f·g).'}
]);

// SECCIÓN 8 · DOMINIO, IMAGEN Y ASÍNTOTAS
registerExercises('analisis-final', '8', [
  {st: 'Sea f(x) = (x + 9)/√x, con x > 0. La imagen de f es:', opts: ['(0; 6]', '[9; +∞)', '[6; +∞)', '(0; +∞)'], c: 2, ex: 'Reescribo: f(x) = √x + 9/√x. ▸ Por AM-GM (o derivando), el mínimo es 2·√9 = 6, en x=9. ▸ Como f → +∞ en 0⁺ y en +∞, la imagen es <b>[6; +∞)</b>. ▸ Atajo: para (x+c)/√x la imagen es [2√c; +∞).'},
  {st: 'La imagen de f(x) = (x + 16)/√x (x > 0) es:', opts: ['[8; +∞)', '[16; +∞)', '[4; +∞)', '(0; +∞)'], c: 0, ex: 'Mismo patrón: mínimo = 2√c con c=16 → 2·4 = 8, en x=16. ▸ Imagen = <b>[8; +∞)</b>. ▸ Es la variante real de C/D 2022 del ejercicio de B 2022 (c=9 → [6;+∞)).'},
  {st: 'Para f(x) = (−2x³ + a(x²−x)) / (b(x²−x) + 1), la recta y = −2x + 3 es asíntota oblicua. Hallar a, b.', opts: ['a = 1; b = 5', 'a = −1; b = 5', 'a = −5; b = 1', 'a = 5; b = 1'], c: 3, ex: 'Pendiente: el cociente líder −2x³/(bx²) = −2x/b debe dar −2 → <b>b = 1</b>. ▸ Con b=1, la división de polinomios da cociente −2x + (a−2); el término independiente debe ser 3 → a−2 = 3 → <b>a = 5</b>.'},
  {st: 'Para que una función racional tenga asíntota OBLICUA, el grado del numerador respecto del denominador debe ser:', opts: ['Igual', 'Uno más (numerador = denominador + 1)', 'Uno menos', 'Dos más'], c: 1, ex: 'Hay asíntota oblicua cuando el <b>grado del numerador es exactamente uno más</b> que el del denominador: al dividir queda un polinomio de grado 1 (la recta) más un resto que → 0. ▸ Si son iguales, la asíntota es horizontal; si el numerador es 2+ mayor, no hay asíntota recta.'},
  {st: 'Para f(x) = √x · e^(algo), ¿qué condición impone la raíz sobre el dominio?', opts: ['x ≠ 0', 'x ≥ 0 (el radicando de una raíz par debe ser ≥ 0)', 'x > 1', 'ninguna'], c: 1, ex: 'Una raíz de índice par exige <b>radicando ≥ 0</b>: acá x ≥ 0 (x=0 está permitido, √0=0). ▸ La exponencial no agrega restricciones. ▸ Dominio = [0; +∞).'}
]);

// SECCIÓN 9 · MIX INTEGRADOR
registerExercises('analisis-final', '9', [
  {st: 'Leés: "El área comprendida entre los gráficos de f y g y el eje x se obtiene calculando:". ¿Qué hacés primero?', opts: ['Integro cualquier opción', 'Hallo los puntos de corte y dónde arranca cada función, y decido quién va arriba en cada tramo', 'Derivo f y g', 'Aplico L\'Hôpital'], c: 1, ex: 'En los ejercicios de "elegir el planteo" de área, la clave es <b>los puntos de corte</b> y el <b>orden</b> (mayor − menor) en cada tramo. ▸ No hace falta resolver la integral: solo armarla bien. ▸ Evaluá un punto de cada tramo para ver quién domina.'},
  {st: 'Leés: "Determinar todos los valores de p para que la serie... converja". ¿De qué tipo es y qué usás?', opts: ['Integral; Barrow', 'Serie; criterio del cociente/raíz (o geométrica/comparación)', 'Límite; L\'Hôpital', 'Tangente; derivar'], c: 1, ex: 'Palabras clave "serie", "converja", "para qué p" → <b>series</b>. ▸ Para serie de potencias: criterio del cociente o de la raíz (radio). Para geométrica: |r|<1. Para numérica: comparación con p-serie. ▸ El factor n^p no afecta el radio.'},
  {st: '¿Cuál es el error más caro al calcular un área entre curvas?', opts: ['Usar la variable x', 'Elegir mal quién va arriba (integrar menor − mayor y quedar con signo cambiado)', 'Escribir el dx', 'Usar Barrow'], c: 1, ex: 'Si integrás (menor − mayor) en vez de (mayor − menor), el área te sale negativa o mal. ▸ Solución: hallar los cortes y evaluar un punto de cada tramo para saber quién domina. ▸ En regiones con cambio de dominio, va la resta ordenada por tramo.'},
  {st: 'El enunciado da el polinomio de Taylor de orden 2 de f en 0. ¿Qué información te da directamente?', opts: ['Solo f(0)', 'f(0), f\'(0) y f\'\'(0) (los coeficientes son las derivadas)', 'La integral de f', 'El dominio de f'], c: 1, ex: 'En P(x) = f(0) + f\'(0)·x + (f\'\'(0)/2)·x², cada coeficiente ES una derivada: el término constante es f(0), el de x es f\'(0) y el de x² es f\'\'(0)/2. ▸ Igualando coeficientes despejás lo que te pidan (un parámetro, f\'\'(0), etc.).'},
  {st: 'Como los temas B/C/D/E repiten el mismo ejercicio con otros números, la mejor estrategia de estudio es:', opts: ['Memorizar los resultados exactos de un tema', 'Memorizar el MÉTODO de cada una de las ~10 plantillas', 'Estudiar solo el tema B', 'Improvisar en el examen'], c: 1, ex: 'Como la constante cambia entre temas, memorizar un resultado no sirve. ▸ Lo que se transfiere es el <b>método</b> de cada plantilla (área con tangente, límite tipo e, radio de convergencia, f(2) desde f\'\', etc.). ▸ Dominando ~10 plantillas cubrís casi todo el final.'},
  {st: 'Tenés lím(x→0⁺) [∫₀^(g(x)) h(t)dt] / (algo). ¿Qué combinás?', opts: ['Solo Barrow', 'TFC + regla de la cadena para derivar el numerador, y L\'Hôpital para el 0/0', 'Solo derivadas', 'Series'], c: 1, ex: 'Cuando hay una integral de límite variable dentro de un límite 0/0, se combinan dos herramientas: <b>L\'Hôpital</b> (por el 0/0) y el <b>TFC + cadena</b> para derivar el numerador: d/dx ∫₀^(g(x)) h = h(g(x))·g\'(x).'}
]);
