registerExercises('algebra', '1', [
  {st: 'Hallar '+M('p, q')+' tal que '+M('(2, −3, 4)')+' sea ortogonal a '+M('(p, 6, q)')+' y a '+M('(−2, 5, −p)')+'.', opts: [M('p = −19/4, q = 55/8'), M('p = 19/4, q = 55/3'), M('p = 0, q = 9'), M('p = 1, q = 4')], c: 0, ex: 'Dos condiciones (cada producto escalar = 0). ▸ (2,−3,4)·(p,6,q) = 2p − 18 + 4q = 0. ▸ (2,−3,4)·(−2,5,−p) = −4 − 15 − 4p = −19 − 4p = 0 → p = −19/4. ▸ Sustituyo en la 1ª: 2·(−19/4) + 4q = 18 → −19/2 + 4q = 18 → 4q = 18 + 19/2 = 55/2 → q = 55/8. ▸ Por qué las otras están mal: (B) tiene signo invertido en p; (C) p=0,q=9 no satisface la 2ª ecuación; (D) p=1 no satisface la 2ª.'},
  {st: 'Un vector '+M('v ∈ ℝ³')+' de norma '+M('15')+' paralelo a '+M('(2/7, −2/7, 1/7)')+' es:', opts: [M('(−10, 10, −5)'), M('(10, −10, 5)'), M('Ambas opciones anteriores'), M('(−70, 70, −35)')], c: 2, ex: 'v = k·(2/7, −2/7, 1/7) por paralelismo. ▸ ‖v‖² = k²·(4/49 + 4/49 + 1/49) = k²·9/49. ▸ Igualo a 225 (15²): k² = 225·49/9 = 1225 → k = ±35. ▸ k=35 → v = (10, −10, 5). k=−35 → v = (−10, 10, −5). HAY DOS soluciones (los dos sentidos de la dirección), por eso la respuesta es C "Ambas". ▸ Por qué las otras están mal: (A) y (B) son ambas correctas pero solo una de las DOS soluciones (incompletas); (D) tiene norma √(70²·3) que no es 15.'},
  {st: '¿Para qué valor de '+M('k')+' los vectores '+M('(k, 2, 1)')+' y '+M('(3, k, −3)')+' son ortogonales?', opts: [M('k = 0'), M('k = −3'), M('k = 3/5'), M('k = 1')], c: 2, ex: 'Ortogonales ⟺ producto escalar = 0. ▸ (k,2,1)·(3,k,−3) = 3k + 2k − 3 = 5k − 3 = 0 → k = 3/5. ▸ Por qué las otras están mal: con k=0 da −3 ≠ 0; con k=−3 da −18 ≠ 0; con k=1 da 2 ≠ 0. Truco: poné los k en forma de ecuación lineal y despejá.'},
  {st: 'La norma del vector '+M('(1, 2, −2)')+' es:', opts: [M('1'), M('3'), M('5'), M('9')], c: 1, ex: '‖v‖ = √(v₁² + v₂² + v₃²) = √(1 + 4 + 4) = √9 = 3. ▸ Por qué las otras están mal: (A) "1" sería la primera componente; (C) "5" sumaría 1+4 sin la última; (D) "9" es ‖v‖² (el cuadrado, no la norma).'},
  {st: 'Sea L: (x,y) = λ(1, 2). La proyección ortogonal del punto '+M('B = (3, 1)')+' sobre L es:', opts: [M('A = (1, 2)'), M('A = (3, 1)'), M('A = (2, 4)'), M('A = (0, 0)')], c: 0, ex: 'Algoritmo de proyección sobre recta paramétrica. ▸ Paso 1: A genérico de L = λ(1,2) = (λ, 2λ). ▸ Paso 2: B − A = (3 − λ, 1 − 2λ). ▸ Paso 3: imponer (B−A)·d = 0: (3−λ)·1 + (1−2λ)·2 = 3 − λ + 2 − 4λ = 5 − 5λ = 0 → λ = 1. ▸ Paso 4: A = (1, 2). ▸ Por qué las otras están mal: (B) (3,1) es B mismo, no su proyección; (C) (2,4) sale con λ=2 (no satisface perpendicularidad); (D) (0,0) sale con λ=0 (no satisface). Truco: A SIEMPRE pertenece a L (existe λ que la genera) Y (B−A) es perpendicular a la dirección.'},
  {st: '¿Cuál es el área del paralelogramo formado por '+M('u = (1, 0, 1)')+' y '+M('v = (0, 2, 0)')+'?', opts: [M('2'), M('2√2'), M('√5'), M('1')], c: 1, ex: 'Área = ‖u × v‖. ▸ u × v = (0·0 − 1·2, 1·0 − 1·0, 1·2 − 0·0) = (−2, 0, 2). ▸ ‖u × v‖ = √(4 + 0 + 4) = √8 = 2√2. ▸ Por qué las otras están mal: (A) "2" sería ‖v‖ solo; (C) "√5" no aparece; (D) "1" = ‖u·v‖ (producto escalar, no vectorial). Truco: producto escalar da número (medir ángulo); producto vectorial da vector (perpendicular a ambos, módulo = área).'}
]);

registerExercises('algebra', '2', [
  {st: 'Posición relativa de '+M('L<sub>1</sub>: (x,y,z) = α(1,0,−1) + (−1,2,3)')+' y '+M('L<sub>2</sub>: (x,y,z) = β(0,2,2) + (1,0,1)')+'.', opts: ['Paralelas', 'Iguales', 'Se cortan', 'Alabeadas'], c: 3, ex: 'Algoritmo posición relativa. ▸ Paso 1: ¿direcciones paralelas? d₁=(1,0,−1), d₂=(0,2,2). NO son múltiplos (la primera tiene 1ª coord no nula, la segunda tiene 1ª coord nula) → NO paralelas. ▸ Paso 2: ¿se cortan? Igualo: α−1=1, 2=2β, −α+3=2β+1. De las dos primeras: α=2, β=1. Reemplazo en la 3ª: −2+3=2+1 → 1=3 ✗ contradicción. NO se cortan. ▸ Conclusión: direcciones no paralelas + no se cortan = ALABEADAS (solo posible en ℝ³). ▸ Por qué las otras están mal: paralelas/iguales requeriría direcciones múltiplos; se cortan requeriría sistema compatible.'},
  {st: 'Una ecuación del plano que pasa por '+M('(1, 0, 2)')+' con normal '+M('n = (2, −1, 3)')+' es:', opts: [M('2x − y + 3z = 8'), M('2x − y + 3z = 0'), M('x − 2y + z = 1'), M('2x − y + 3z = 5')], c: 0, ex: 'Plano con normal (a,b,c) → ecuación ax+by+cz = d. ▸ Forma: 2x − y + 3z = d. ▸ d se obtiene reemplazando un punto del plano: 2·1 − 0 + 3·2 = 2 + 6 = 8. ▸ Por qué las otras están mal: (B) 2x−y+3z=0 pasa por el origen, no por (1,0,2); (C) usa normal (1,−2,1), distinta; (D) "5" no surge de reemplazar.'},
  {st: 'La distancia del punto '+M('(1, 2)')+' a la recta '+M('3x + 4y − 5 = 0')+' es:', opts: [M('6/5'), M('1'), M('6'), M('1/5')], c: 0, ex: 'Fórmula de distancia punto-recta: d = |a·x₀ + b·y₀ + c| / √(a² + b²). ▸ d = |3·1 + 4·2 − 5| / √(9+16) = |3+8−5|/√25 = 6/5. ▸ Por qué las otras están mal: (B) "1" se obtiene si te olvidás del valor absoluto y usás la división mal; (C) "6" se obtiene si te olvidás del denominador; (D) "1/5" sale si invertís numerador y denominador.'},
  {st: 'La proyección ortogonal de '+M('v = (3, 4)')+' sobre '+M('u = (1, 0)')+' es:', opts: [M('(3, 0)'), M('(0, 4)'), M('(3, 4)'), M('(1, 0)')], c: 0, ex: 'Fórmula: proy_u(v) = (v·u / ‖u‖²)·u. ▸ v·u = 3·1 + 4·0 = 3. ▸ ‖u‖² = 1² + 0² = 1. ▸ Resultado: (3/1)·(1, 0) = (3, 0). Es la "componente x" de v (la sombra sobre el eje x). ▸ Por qué las otras están mal: (B) (0,4) sería la proyección sobre el eje y; (C) (3,4) es v sin proyectar; (D) (1,0) es solo la dirección u.'},
  {st: 'Si A es la proyección ortogonal de B sobre L: X = λd, ¿qué dos condiciones debe cumplir A?', opts: ['Solo (B−A)·d = 0', 'Solo A ∈ L', 'A ∈ L (existe λ tal que A = λd) Y (B−A)·d = 0', 'Ninguna en particular'], c: 2, ex: 'La proyección de B sobre una recta L es el punto A ∈ L que minimiza la distancia a B. ▸ Geométricamente: el segmento BA debe ser perpendicular a la dirección de L (sino podrías acercarte más siguiendo L). ▸ Las DOS condiciones son necesarias: si solo se cumple (B−A)·d=0 pero A no está en L, no es proyección; si solo A ∈ L pero (B−A) no es perpendicular, tampoco. ▸ Por qué las otras están mal: (A) (B) son condiciones individuales pero ninguna alcanza sola; (D) la proyección sí tiene caracterización geométrica clara.'},
  {st: 'Para hallar la proyección ortogonal de '+M('P = (1, 0, 2)')+' sobre L: X = λ(2, −1, 0), ¿qué hacés?', opts: ['Calcular ‖P‖', 'Escribir A = (2λ, −λ, 0) y plantear (P−A)·(2,−1,0) = 0', 'Resolver el sistema P = λ·d', 'Producto vectorial de P con d'], c: 1, ex: 'Algoritmo del parcial (5 pasos). ▸ A genérico de L = (2λ, −λ, 0). ▸ P − A = (1−2λ, λ, 2). ▸ Imponer (P−A)·d = 0: 2(1−2λ) + (−1)·λ + 0·2 = 2 − 4λ − λ = 2 − 5λ = 0 → λ = 2/5. ▸ Reemplazo: A = (4/5, −2/5, 0). ▸ Por qué las otras están mal: (A) ‖P‖ no sirve para hallar proyección; (C) P = λd implicaría que P está en L (no se cumple); (D) producto vectorial da un vector perpendicular, no la proyección.'},
  {st: 'Para hallar la proyección ortogonal de P sobre el plano π: 2x − 3z = 0, ¿qué recta auxiliar usás?', opts: ['La recta paralela a π por P', 'La recta normal al plano por P, con dirección (2, 0, −3)', 'La recta y = x', 'No hace falta recta auxiliar'], c: 1, ex: 'La proyección de P sobre el plano π = "pie de la perpendicular" desde P. ▸ Receta: tomá la recta NORMAL a π que pasa por P (su dirección es el vector normal de π, que se lee de los coeficientes: 2x−3z=0 ⇒ n=(2,0,−3)), buscá la intersección con π, eso da la proyección. ▸ Por qué las otras están mal: (A) recta paralela no toca π (a menos que P ya estuviera en π); (C) "y=x" es arbitraria, no relacionada; (D) sí hace falta, sino no podrías construir la perpendicular.'},
  {st: 'El simétrico de P = (2, −4) respecto al punto Q = (−1, 1) es:', opts: [M('(−4, 6)'), M('(0, −2)'), M('(−1, −3)'), M('(3, −5)')], c: 0, ex: 'Q debe ser el punto medio entre P y P\' → fórmula P\' = 2Q − P. ▸ P\' = 2·(−1, 1) − (2, −4) = (−2, 2) − (2, −4) = (−2−2, 2+4) = (−4, 6). ▸ Verificación: (P+P\')/2 = ((2−4)/2, (−4+6)/2) = (−1, 1) = Q ✓. ▸ Por qué las otras están mal: (B) (0,−2) es el promedio; (C) (−1,−3) no coincide con la fórmula; (D) (3,−5) está cerca pero suma en lugar de restar.'},
  {st: 'Si el simétrico de P respecto a Q es P\', ¿cómo hallás Q?', opts: [M('Q = P − P\''), M('Q = (P + P\') / 2')+' (Q es el punto medio)', M('Q = 2P − P\''), M('Q = P · P\'')], c: 1, ex: 'Por definición, el simétrico se calcula con Q como punto medio: P\' = 2Q − P. ▸ Despejando Q: Q = (P + P\') / 2. Es el promedio coordenada por coordenada. ▸ Por qué las otras están mal: (A) Q = P − P\' daría un vector dirección, no un punto; (C) Q = 2P − P\' es la fórmula del simétrico de P\' respecto a P (al revés); (D) Q = P·P\' es producto escalar (un número), no un punto.'},
  {st: 'Para hallar el simétrico de P respecto a una recta L, la receta es:', opts: ['P\' = 2P − L', 'Hallar A = proy. ortogonal de P sobre L y luego P\' = 2A − P', 'Reflejar coordenada por coordenada', 'P\' = P + d (donde d es la dirección de L)'], c: 1, ex: 'Receta universal de simétrico respecto a recta o plano. ▸ Paso 1: A = proyección ortogonal de P sobre L (algoritmo de proyección clásico). ▸ Paso 2: P\' = 2A − P (A es punto medio entre P y P\'). ▸ Por qué las otras están mal: (A) "L" es una recta, no un punto; restarla no tiene sentido; (C) reflejar coord-por-coord solo funciona para los ejes coordenados, no para una recta cualquiera; (D) sumar d desplaza a P en la dirección, no lo refleja.'},
  {st: 'El simétrico de (3, −1) respecto al eje x es:', opts: [M('(3, 1)'), M('(−3, −1)'), M('(−3, 1)'), M('(1, 3)')], c: 0, ex: 'Atajo: simétrico respecto al eje X cambia de signo SOLO la coordenada y (el "espejo" es el eje x). ▸ (3, −1) → (3, +1). ▸ Tabla de atajos: respecto al eje X: (x,y)→(x,−y); respecto al eje Y: (x,y)→(−x,y); respecto al origen: (x,y)→(−x,−y); respecto a y=x: (x,y)→(y,x). ▸ Por qué las otras están mal: (B) (−3,−1) sería respecto al eje y (cambia x); (C) (−3,1) sería respecto al origen; (D) (1,3) sería respecto a y=x.'},
  {st: 'Para verificar que A es la proyección de P sobre L, ¿qué tenés que comprobar?', opts: ['Hallar λ que da A = λd + P₀ (que A ∈ L) Y (P−A)·d = 0', 'Solo (P−A)·d = 0', 'Solo ‖P − A‖ = mínimo', 'Solo A·d = 0'], c: 0, ex: 'Una proyección debe cumplir DOS condiciones: A ∈ L (existe un λ que lo da en la parametrización) Y (P−A) perpendicular a la dirección de L. ▸ Si solo verificás la perpendicularidad, podés acertar el vector dirección pero no asegurar que A esté en L (podría estar en cualquier paralela). ▸ Por qué las otras están mal: (B) (D) son condiciones parciales; (C) la "norma mínima" es CONSECUENCIA, no se verifica directamente sin medir todas las distancias.'}
]);

registerExercises('algebra', '3', [
  {st: 'Considerá '+M('S = {(x<sub>1</sub>, x<sub>2</sub>, x<sub>3</sub>, x<sub>4</sub>) ∈ ℝ⁴ : x<sub>1</sub> − x<sub>4</sub> = 0}')+'. ¿Cuál es su dimensión?', opts: [M('1'), M('2'), M('3'), M('4')], c: 2, ex: 'Regla: dim(S) = dim(espacio) − cantidad de ecuaciones independientes. ▸ Acá: dim(ℝ⁴)=4, una ecuación: dim(S) = 4 − 1 = 3. ▸ Verificación con base: x₁ = x₄, las variables libres son x₂, x₃, x₄. Una base es {(1,0,0,1), (0,1,0,0), (0,0,1,0)} → 3 vectores → dim 3. ▸ Por qué las otras están mal: (A) "1" sería con 3 ecuaciones; (B) "2" con 2 ecuaciones; (D) "4" implicaría que S = ℝ⁴ (sin restricción).'},
  {st: '¿'+M('(2, 0, 4)')+' es combinación lineal de '+M('(1, −1, 2)')+' y '+M('(1, 1, 2)')+'?', opts: ['Sí, con coeficientes (1, 1)', 'Sí, con coeficientes (2, 0)', 'No', 'Sí, pero con infinitas combinaciones'], c: 0, ex: 'Planteo α(1,−1,2) + β(1,1,2) = (2,0,4). Sistema: α+β=2, −α+β=0, 2α+2β=4. ▸ De la 2ª: α=β. Reemplazo en la 1ª: 2α=2 → α=β=1. Verifico la 3ª: 2·1+2·1=4 ✓. Coeficientes: (1, 1). ▸ Por qué las otras están mal: (B) (2,0) → 2(1,−1,2)+0=(2,−2,4) ≠ (2,0,4); (C) "No" está descartado por la solución; (D) los dos vectores son L.I. (no múltiplos), entonces la combinación es ÚNICA, no infinitas.'},
  {st: '¿Cuál de los siguientes vectores pertenece a '+M('S = {(x,y,z) ∈ ℝ³ : x + y − z = 0}')+'?', opts: [M('(1, 2, 3)'), M('(1, 1, 1)'), M('(2, 0, 0)'), M('(1, −1, 1)')], c: 0, ex: 'Reemplazo cada uno en la ecuación x+y−z=0: ▸ (1,2,3): 1+2−3 = 0 ✓ PERTENECE. ▸ (1,1,1): 1+1−1 = 1 ✗. ▸ (2,0,0): 2+0−0 = 2 ✗. ▸ (1,−1,1): 1−1−1 = −1 ✗. ▸ Por qué las otras están mal: ninguna satisface la ecuación; solo la (A).'},
  {st: '¿'+M('{(1, 1, 0), (1, 0, 1), (0, 1, 1)}')+' es L.I.?', opts: ['Sí', 'No, porque el tercero es suma de los otros dos', 'No, porque el primero es suma de los otros dos', 'Depende del cuerpo'], c: 0, ex: 'Test: α(1,1,0) + β(1,0,1) + γ(0,1,1) = (0,0,0). Sistema: α+β=0, α+γ=0, β+γ=0. ▸ De las dos primeras: β = γ = −α. Sustituyo en la 3ª: −α + (−α) = −2α = 0 → α=0 → β=γ=0. Solución única (la trivial) → L.I. ▸ Por qué las otras están mal: (B) (C) sostienen una dependencia que no existe (verificalo: (0,1,1) ≠ (1,1,0)+(1,0,1) = (2,1,1)); (D) en ℝ y ℂ el resultado es el mismo (no depende del cuerpo).'},
  {st: 'Si '+M('dim(S) = 2')+' en '+M('ℝ³')+' y '+M('{v<sub>1</sub>, v<sub>2</sub>}')+' es base de S, entonces '+M('{v<sub>1</sub>, v<sub>2</sub>, w}')+' con '+M('w ∉ S')+' es:', opts: ['Una base de ℝ³', 'L.D.', 'Una base de S', 'Genera solo S'], c: 0, ex: 'v₁, v₂ son L.I. (por ser base de S). Como w ∉ S, w no es combinación lineal de v₁ y v₂ → los 3 son L.I. ▸ Tres vectores L.I. en ℝ³ forman una base (ℝ³ tiene dimensión 3). ▸ Por qué las otras están mal: (B) L.D. supondría que w está en S, contradice la hipótesis; (C) base de S necesita exactamente 2 vectores; (D) generan TODO ℝ³, no solo S, porque w sale de S.'},
  {st: 'El subespacio generado por '+M('(1, 2)')+' y '+M('(2, 4)')+' tiene dimensión:', opts: [M('0'), M('1'), M('2'), M('3')], c: 1, ex: '¿(2,4) y (1,2) son L.I.? ▸ (2,4) = 2·(1,2) → SÍ son múltiplos → L.D. ▸ Solo uno de los dos es independiente, así que el subespacio que generan tiene dimensión 1 (es una recta por el origen). ▸ Por qué las otras están mal: (A) "0" implicaría que ambos son nulos; (C) "2" implicaría L.I.; (D) "3" no aplica en ℝ²/colineales.'}
]);

registerExercises('algebra', '4', [
  {st: 'El centro y radio de '+M('x² + y² − 6x + 2y = 0')+' son:', opts: [M('Centro (3, −1), radio √10'), M('Centro (−3, 1), radio √10'), M('Centro (3, −1), radio 10'), M('Centro (6, −2), radio 4')], c: 0, ex: 'Completar cuadrados. ▸ x² − 6x = (x−3)² − 9. ▸ y² + 2y = (y+1)² − 1. ▸ Sustituyo: (x−3)² − 9 + (y+1)² − 1 = 0 → (x−3)² + (y+1)² = 10. ▸ Forma canónica (x−h)² + (y−k)² = r²: centro (h,k) = (3, −1), radio r = √10. ▸ Por qué las otras están mal: (B) signos cambiados (atención: sumás 9 y 1 al "pasar al otro lado", no restás); (C) "radio 10" sería r², no r; (D) factores duplicados, no se completa así.'},
  {st: 'La ecuación de la parábola con foco '+M('(2, −1.5)')+' y directriz '+M('y = −0.5')+' es:', opts: [M('(x−2)² = −2(y+1)'), M('(x−2)² = 2(y+1)'), M('(y+1)² = −2(x−2)'), M('(x−2)² = −2(y−1)')], c: 0, ex: 'Vértice = punto medio entre foco y directriz a lo largo de la perpendicular a la directriz. ▸ La directriz es horizontal (y=cte), entonces la perpendicular es vertical: x = x_foco = 2. y = (y_foco + y_directriz)/2 = (−1.5 + (−0.5))/2 = −1. Vértice (2, −1). ▸ Forma canónica: (x−h)² = 4p(y−k), con h=2, k=−1. ▸ p = distancia con signo desde vértice al foco: −1.5 − (−1) = −0.5 (foco está debajo, signo negativo). 4p = −2. ▸ Ecuación: (x−2)² = −2(y+1). ▸ Por qué las otras están mal: (B) signo positivo abre hacia ARRIBA, contradice que foco esté abajo; (C) (y−k)²= ... abre horizontal, no aplica acá; (D) (y−1) tiene k=1 incorrecto.'},
  {st: 'El centro de la hipérbola con asíntotas '+M('y = 2x + 1')+' y '+M('y = −2x + 5')+' está en:', opts: [M('(1, 3)'), M('(−1, 3)'), M('(0, 3)'), M('(2, 1)')], c: 0, ex: 'Las asíntotas de una hipérbola se cruzan EN el centro. ▸ Igualo: 2x+1 = −2x+5 → 4x = 4 → x = 1. ▸ Sustituyo: y = 2·1+1 = 3. ▸ Centro = (1, 3). ▸ Por qué las otras están mal: (B) (−1,3) usa x=−1 (no satisface); (C) (0,3) tampoco satisface; (D) (2,1) lejos de la intersección.'},
  {st: 'Para la elipse '+M('x²/25 + y²/9 = 1')+', los focos están en:', opts: [M('(±4, 0)'), M('(0, ±4)'), M('(±3, 0)'), M('(±5, 0)')], c: 0, ex: 'En la elipse x²/a² + y²/b² = 1, el eje mayor está en la dirección del denominador más grande. ▸ Acá a²=25 (eje x), b²=9 → eje mayor en X (horizontal). ▸ Relación: c² = a² − b² = 16 → c = 4. ▸ Focos sobre el eje X: (±c, 0) = (±4, 0). ▸ Por qué las otras están mal: (B) (0,±4) sería para elipse vertical; (C) (±3, 0) usa b en lugar de c; (D) (±5, 0) usa a (los vértices del eje mayor, no los focos).'},
  {st: '¿'+M('(0, 4)')+' está sobre la circunferencia '+M('x² + (y−1)² = 9')+'?', opts: ['Sí', 'No, porque da 10', 'No, porque da 8', 'Solo si es complejo'], c: 0, ex: 'Reemplazo: 0² + (4−1)² = 0 + 9 = 9 ✓. Da exactamente 9 = r², así que SÍ pertenece. ▸ Por qué las otras están mal: (B) "10" sería con punto (1,4): 1+9=10 (afuera); (C) "8" sería con punto (1,3): 1+4=5 (adentro); (D) "complejo" no aplica acá.'},
  {st: 'La distancia del centro al foco de '+M('(x−1)²/4 + (y+2)²/1 = 1')+' es:', opts: [M('√3'), M('1'), M('2'), M('√5')], c: 0, ex: 'Identifico: a²=4 (eje mayor, x), b²=1. ▸ Relación de la elipse: c² = a² − b² = 4 − 1 = 3 → c = √3. ▸ La distancia centro-foco es exactamente c. ▸ Por qué las otras están mal: (B) "1" es b (semieje menor); (C) "2" es a (semieje mayor); (D) "√5" sería c² = a² + b² (eso es de la HIPÉRBOLA, no la elipse). Truco: en elipse c² = a² − b² (c < a); en hipérbola c² = a² + b² (c > a).'}
]);

registerExercises('algebra', '5', [
  {st: 'El determinante de '+M('A = [[2, 1], [3, 4]]')+' es:', opts: [M('5'), M('11'), M('−5'), M('8')], c: 0, ex: 'Determinante 2×2: det = a·d − b·c (cruzado). ▸ det(A) = 2·4 − 1·3 = 8 − 3 = 5. ▸ Por qué las otras están mal: (B) "11" suma todo en lugar de cruzar; (C) "−5" cambia signo; (D) "8" es solo 2·4 sin restar.'},
  {st: 'Si '+M('det(A) = 3')+' y '+M('A')+' es 3×3, entonces '+M('det(2A)')+' vale:', opts: [M('6'), M('12'), M('24'), M('3')], c: 2, ex: 'Propiedad: det(kA) = kⁿ · det(A) donde n es el tamaño de la matriz cuadrada. ▸ det(2A) = 2³ · 3 = 8 · 3 = 24. ▸ Por qué las otras están mal: (A) "6" = 2·det(A) (mal, no se multiplica solo por k); (B) "12" = 4·det(A); (D) "3" sin tocar k. Truco: cada fila multiplica por k → factor k por fila → kⁿ.'},
  {st: 'Si '+M('det(A) = 5')+' y '+M('det(B) = 2')+', entonces '+M('det(A·B)')+' vale:', opts: [M('7'), M('10'), M('2/5'), M('25')], c: 1, ex: 'Propiedad multiplicativa: det(A·B) = det(A) · det(B). ▸ det(AB) = 5 · 2 = 10. ▸ Por qué las otras están mal: (A) "7" suma en lugar de multiplicar; (C) "2/5" divide; (D) "25" multiplica solo el primero (det(A)·det(A)).'},
  {st: 'Un sistema homogéneo con matriz '+M('A')+' de '+M('n×n')+' tiene solución NO trivial ⟺:', opts: [M('det(A) ≠ 0'), M('det(A) = 0'), M('A es inversible'), M('rg(A) = n')], c: 1, ex: 'Sistema homogéneo Ax = 0 SIEMPRE tiene la solución trivial x=0. Tiene OTRA solución (no trivial) cuando A NO es inversible, es decir, det(A) = 0. ▸ Equivalencias: det(A)=0 ⟺ rg(A)<n ⟺ columnas L.D. ⟺ A no inversible. ▸ Por qué las otras están mal: (A) det≠0 implica solo solución trivial; (C) inversible ⟺ det≠0 (lo opuesto a lo buscado); (D) rg=n equivale a det≠0 también.'},
  {st: 'Clasificar el sistema: '+M('x + y = 1; 2x + 2y = 2; x − y = 3')+'.', opts: ['Compatible determinado (única solución)', 'Compatible indeterminado (infinitas)', 'Incompatible (sin solución)', 'Depende'], c: 0, ex: 'Observo que la 2ª ecuación = 2× la 1ª (redundante, no aporta info). El sistema efectivo es: x+y=1 y x−y=3. ▸ Sumando: 2x = 4 → x=2. Restando: 2y = −2 → y = −1. Solución única → COMPATIBLE DETERMINADO. ▸ Por qué las otras están mal: (B) indeterminado requeriría más variables que ecuaciones independientes; (C) incompatible requeriría contradicción; (D) está completamente determinado, no "depende".'},
  {st: 'La inversa de '+M('A = [[1, 2], [3, 5]]')+' existe si:', opts: ['Siempre, sin verificar', 'Nunca, es singular', 'det(A) = −1 ≠ 0, así que sí existe', 'Solo en ℂ'], c: 2, ex: 'Una matriz cuadrada es inversible ⟺ det ≠ 0. ▸ Calculo: det(A) = 1·5 − 2·3 = 5 − 6 = −1. ▸ −1 ≠ 0 → A es inversible. ▸ Por qué las otras están mal: (A) hay que VERIFICAR el determinante (no es automático); (B) "nunca" es falso porque det≠0; (D) "solo en ℂ" no aplica, el cálculo es real.'}
]);

registerExercises('algebra', '6', [
  {st: 'Si '+M('T : ℝ³ → ℝ²')+' está dada por '+M('T(x,y,z) = (x+y, y−z)')+', entonces '+M('T(1, 2, 3)')+' vale:', opts: [M('(3, −1)'), M('(1, 2)'), M('(3, 1)'), M('(3, 2)')], c: 0, ex: 'Reemplazo en la fórmula. ▸ x+y = 1+2 = 3 (1ª coordenada). ▸ y−z = 2−3 = −1 (2ª coordenada). ▸ T(1,2,3) = (3, −1). ▸ Por qué las otras están mal: (B) (1,2) sería los dos primeros valores sin aplicar T; (C) (3,1) sería con z=1; (D) (3,2) sería sin restar z.'},
  {st: 'Para la T del ejercicio anterior, '+M('dim(Im(T))')+' vale:', opts: [M('0'), M('1'), M('2'), M('3')], c: 2, ex: 'La imagen es el conjunto de todos los T(v) posibles. ▸ Matriz canónica: A = [[1, 1, 0], [0, 1, −1]] (las columnas son T(e_i)). ▸ Imagen = espacio columna. Las columnas son (1,0), (1,1), (0,−1) en ℝ². Las dos primeras son L.I. → Im(T) = ℝ² → dim(Im) = 2. ▸ Por qué las otras están mal: (A) (B) implicarían Im más chica; (D) imposible porque Im ⊆ ℝ² (codominio).'},
  {st: 'Para la misma T, '+M('dim(Nu(T))')+' vale:', opts: [M('0'), M('1'), M('2'), M('3')], c: 1, ex: 'Teorema de la dimensión: dim(dom) = dim(Nu(T)) + dim(Im(T)). ▸ Acá dom = ℝ³ (dim 3), Im(T) tiene dim 2 (calculado en el anterior). ▸ 3 = dim(Nu) + 2 → dim(Nu) = 1. ▸ Por qué las otras están mal: (A) "0" implicaría inyectiva pero ℝ³→ℝ² no puede ser inyectiva (T baja la dim); (C) (D) demasiado grandes.'},
  {st: 'Si '+M('T : ℝⁿ → ℝⁿ')+' es inyectiva, entonces también es:', opts: ['No se puede saber', 'Sobreyectiva (en dimensiones iguales son equivalentes)', 'No sobreyectiva', 'La identidad'], c: 1, ex: 'Teorema: en transformaciones lineales con dim(dominio) = dim(codominio), inyectividad ⟺ sobreyectividad ⟺ biyectividad. ▸ Justificación: si T es inyectiva → dim(Nu)=0 → dim(Im) = n − 0 = n = dim(codom) → Im = codom → sobreyectiva. ▸ Por qué las otras están mal: (A) sí se puede saber por teorema; (C) opuesto al teorema; (D) inyectiva no implica que sea la identidad (ej: T(x)=2x es inyectiva pero no identidad).'},
  {st: 'La matriz canónica de '+M('T(x, y) = (2x − y, x + 3y)')+' es:', opts: [M('[[2, −1], [1, 3]]'), M('[[2, 1], [−1, 3]]'), M('[[1, −1], [2, 3]]'), M('[[2, 3], [−1, 1]]')], c: 0, ex: 'Las columnas de la matriz canónica son las imágenes de la base canónica. ▸ T(e₁) = T(1,0) = (2·1−0, 1+3·0) = (2, 1). ▸ T(e₂) = T(0,1) = (2·0−1, 0+3·1) = (−1, 3). ▸ Matriz: [[2, −1], [1, 3]] (columnas T(e₁) y T(e₂)). ▸ Por qué las otras están mal: (B) tiene la matriz traspuesta; (C) (D) intercambian componentes/columnas mal.'},
  {st: 'Si '+M('T(x<sub>1</sub>, x<sub>2</sub>, x<sub>3</sub>, x<sub>4</sub>) = (−x<sub>2</sub> + x<sub>3</sub>, 5x<sub>2</sub>, 0)')+', entonces '+M('dim(Im(T))')+' vale:', opts: [M('0'), M('1'), M('2'), M('3')], c: 2, ex: 'Matriz canónica: A = [[0,−1,1,0],[0,5,0,0],[0,0,0,0]] (las columnas son T(e_i)). ▸ Columnas: c₁=(0,0,0), c₂=(−1,5,0), c₃=(1,0,0), c₄=(0,0,0). ▸ Las no nulas son c₂ y c₃, que son L.I. (no son múltiplos). c₁ y c₄ son cero. Imagen generada por c₂ y c₃ → dim(Im) = 2. ▸ Por qué las otras están mal: (A) "0" ignora las columnas no nulas; (B) "1" supondría que c₂ y c₃ son colineales; (D) "3" requeriría 3 columnas L.I., pero la 3ª coord siempre es 0.'}
]);

registerExercises('algebra', '7', [
  {st: 'El conjugado de '+M('z = 3 − 2i')+' es:', opts: [M('3 + 2i'), M('−3 + 2i'), M('−3 − 2i'), M('3 − 2i')], c: 0, ex: 'El conjugado de a + bi es a − bi (cambia signo SOLO de la parte imaginaria). ▸ z = 3 − 2i → z̄ = 3 + 2i. ▸ Por qué las otras están mal: (B) (−3+2i) cambia ambos signos; (C) (−3−2i) niega todo; (D) (3−2i) es el original sin tocar.'},
  {st: 'El módulo de '+M('z = 1 + i')+' es:', opts: [M('1'), M('√2'), M('2'), M('0')], c: 1, ex: '|z| = √(a² + b²) donde z = a + bi. ▸ |1 + i| = √(1² + 1²) = √2. ▸ Por qué las otras están mal: (A) "1" es solo Re(z); (C) "2" sería |z|² (sin la raíz); (D) "0" solo si z=0.'},
  {st: 'El argumento principal de '+M('z = 1 + i')+' (en (−π, π]) es:', opts: [M('0'), M('π/4'), M('π/2'), M('π')], c: 1, ex: 'Re(z) = Im(z) = 1, ambos positivos → primer cuadrante. ▸ arg(z) = arctan(b/a) = arctan(1/1) = arctan(1) = π/4 (45°). ▸ Por qué las otras están mal: (A) "0" sería para z real positivo; (C) "π/2" sería para z imaginario puro positivo (b/0 = inf); (D) "π" sería para z real negativo.'},
  {st: '¿Cuánto vale '+M('(1 + i)²')+'?', opts: [M('0'), M('2'), M('2i'), M('−1 + 2i')], c: 2, ex: 'Aplicar (a+b)² = a² + 2ab + b² con a=1, b=i. ▸ (1+i)² = 1 + 2i + i² = 1 + 2i − 1 = 2i. ▸ Truco: i² = −1 SIEMPRE. ▸ Por qué las otras están mal: (A) "0" sería si i² = −1 cancelara también el 2i; (B) "2" olvida que i²=−1 (lo trata como 1); (D) "−1 + 2i" usa i² = −1 mal en otro lugar.'},
  {st: '¿Cuántas soluciones tiene '+M('z³ = 8')+' en '+M('ℂ')+'?', opts: [M('1'), M('2'), M('3'), M('Infinitas')], c: 2, ex: 'Teorema: zⁿ = w (con w≠0) tiene exactamente n raíces complejas distintas, equiespaciadas en una circunferencia de radio |w|^(1/n). ▸ Para z³ = 8: tres raíces. La real es z=2; las otras dos son complejas conjugadas (z = 2·e^(±2πi/3)). ▸ Por qué las otras están mal: (A) "1" es la solución REAL solamente (incompleto en ℂ); (B) "2" no aplica (n=3); (D) "Infinitas" no, son siempre n exactas.'},
  {st: 'Si '+M('|z|² = z·z̄ = 4')+' y la parte real de z es 0, entonces z vale:', opts: [M('±2'), M('±2i'), M('2 + 2i'), M('4i')], c: 1, ex: '|z|² = a² + b² = 4. Re(z) = a = 0 → 0 + b² = 4 → b² = 4 → b = ±2. ▸ z = 0 + bi = ±2i. ▸ Por qué las otras están mal: (A) (±2) son reales (tendrían Re≠0); (C) (2+2i) tiene Re=2≠0 y |z|²=8; (D) (4i) tiene |z|²=16.'}
]);

registerExercises('algebra', '8', [
  {st: 'El resto de dividir '+M('P(x) = x³ − 2x + 5')+' entre '+M('x − 1')+' es:', opts: [M('0'), M('4'), M('−2'), M('5')], c: 1, ex: 'Teorema del resto: el resto de dividir P(x) por (x−a) es P(a). ▸ Acá a=1: R = P(1) = 1³ − 2·1 + 5 = 1 − 2 + 5 = 4. ▸ Por qué las otras están mal: (A) "0" sería si 1 fuera raíz, pero P(1)=4≠0; (C) "−2" surge si calculás P(−1) erróneamente; (D) "5" sería P(0).'},
  {st: 'Si '+M('a = 2')+' es raíz de '+M('P(x)')+', entonces '+M('P(x)')+' es divisible por:', opts: [M('x + 2'), M('x − 2'), M('x² + 2'), M('2x')], c: 1, ex: 'Teorema del factor: a es raíz de P ⟺ (x − a) divide a P. ▸ Si raíz = 2, factor = (x − 2). ▸ Por qué las otras están mal: (A) (x+2) significaría raíz −2, no 2; (C) (x²+2) no tiene raíces reales; (D) (2x) no tiene la forma (x−a).'},
  {st: 'Si '+M('P ∈ ℝ[x]')+' y '+M('2 + 3i')+' es raíz, ¿qué otra raíz tiene seguro?', opts: [M('2 − 3i'), M('−2 + 3i'), M('−2 − 3i'), M('3 + 2i')], c: 0, ex: 'Teorema: en P ∈ ℝ[x], si una raíz es compleja a+bi, su CONJUGADA a−bi también es raíz. ▸ Para 2+3i, la conjugada es 2−3i. ▸ Por qué las otras están mal: (B) (−2+3i) cambia signo de Re; (C) (−2−3i) cambia ambos; (D) (3+2i) intercambia parte real con imaginaria. Truco: en ℝ[x] los coeficientes son reales, así que las raíces complejas siempre vienen en pares conjugados.'},
  {st: 'Un polinomio '+M('P ∈ ℝ[x]')+' de grado mínimo con raíces '+M('3')+' e '+M('i')+' tiene grado:', opts: [M('2'), M('3'), M('4'), M('5')], c: 1, ex: 'En ℝ[x], si i es raíz, también lo es −i (conjugada). ▸ Factor para 3 (real): (x−3), grado 1. ▸ Factor para {i, −i}: (x−i)(x+i) = x²+1, grado 2. ▸ Grado mínimo: 1+2 = 3. ▸ Por qué las otras están mal: (A) "2" olvida que i obliga a −i; (C) (D) sobrarían factores.'},
  {st: 'Un polinomio '+M('P ∈ ℚ[x]')+' de grado mínimo con raíces '+M('√2')+' y '+M('1')+' tiene grado:', opts: [M('2'), M('3'), M('4'), M('5')], c: 1, ex: 'En ℚ[x], si √2 es raíz (irracional), también −√2 (su "conjugado" sobre ℚ). ▸ Factor para {√2, −√2}: (x−√2)(x+√2) = x²−2, grado 2 (con coeficientes racionales). ▸ Factor para 1: (x−1), grado 1. ▸ Total: 2+1 = 3. ▸ Por qué las otras están mal: (A) "2" si solo (x−√2) (pero ese factor solo no es de ℚ[x] porque √2 ∉ ℚ).'},
  {st: 'Sea '+M('P ∈ ℚ[x]')+' de grado mínimo con '+M('P(√5) = 0')+', '+M('i')+' raíz doble, y '+M('P(−2) = −75')+'. Entonces '+M('P(x)')+' es:', opts: [M('3(x² − 5)(x² + 1)²'), M('(x² − 5)(x² + 1)²'), M('−3(x − √5)(x² + 1)²'), M('3(x − √5)(x + √5)(x − i)(x + i)')], c: 0, ex: 'En ℚ[x] (raíces irracionales/imaginarias necesitan sus pares). ▸ √5 raíz → −√5 también (factor (x²−5)). ▸ i raíz DOBLE → −i raíz doble (factor (x²+1)²). ▸ Grado mínimo: 2 + 4 = 6. ▸ Forma: P(x) = k(x²−5)(x²+1)². ▸ Imponer P(−2) = k((−2)²−5)((−2)²+1)² = k(−1)(25) = −25k = −75 → k = 3. ▸ Resultado: 3(x²−5)(x²+1)². ▸ Por qué las otras están mal: (B) sin k; (C) (x−√5) suelto no es de ℚ[x]; (D) factores con i no son de ℚ[x].'}
]);
