// ============ UNIDAD 1 · VECTORES ============
registerExercises('algebra', '1', [
  {st: 'Hallar '+M('p, q')+' tal que '+M('(2, −3, 4)')+' sea ortogonal a '+M('(p, 6, q)')+' y a '+M('(−2, 5, −p)')+'.', opts: [M('p = −19/4, q = 55/8'), M('p = 19/4, q = 55/3'), M('p = 0, q = 9/2'), M('p = 1, q = 4')], c: 0, ex: 'Ortogonalidad ⟺ producto escalar = 0. Tengo dos condiciones: ▸ <b>Ec. 1:</b> (2,−3,4)·(p,6,q) = 2p − 18 + 4q = 0 → 2p + 4q = 18 → p + 2q = 9. ▸ <b>Ec. 2:</b> (2,−3,4)·(−2,5,−p) = −4 − 15 − 4p = −19 − 4p = 0 → p = −19/4. ▸ Sustituyo p en Ec. 1: −19/4 + 2q = 9 → 2q = 9 + 19/4 = 36/4 + 19/4 = 55/4 → q = 55/8. ▸ <b>Verificación:</b> (2,−3,4)·(−19/4, 6, 55/8) = −19/2 − 18 + 55/2 = 36/2 − 18 = 18 − 18 = 0 ✓. ▸ <b>Por qué las otras están mal:</b> (B) p=19/4 da −19−4(19/4) = −19−19 = −38 ≠ 0 en Ec. 2; (C) p=0 da −19 ≠ 0 en Ec. 2; (D) p=1 da −23 ≠ 0 en Ec. 2.'},
  {st: 'Indica TODOS los vectores de '+M('ℝ³')+' de norma '+M('15')+' paralelos a '+M('v = (2/7, −2/7, 1/7)')+'.', opts: [M('Solo (10, −10, 5)'), M('Solo (−10, 10, −5)'), M('(10, −10, 5) y (−10, 10, −5) (los dos sentidos)'), M('(70, −70, 35) y (−70, 70, −35)')], c: 2, ex: 'Por paralelismo, w = k·v con k ∈ ℝ. ▸ <b>Norma de v:</b> ‖v‖² = (2/7)² + (−2/7)² + (1/7)² = 4/49 + 4/49 + 1/49 = 9/49 → ‖v‖ = 3/7. ▸ <b>Imponer ‖w‖ = 15:</b> |k|·(3/7) = 15 → |k| = 35 → k = ±35. ▸ <b>Para k = 35:</b> w = 35·(2/7, −2/7, 1/7) = (10, −10, 5). ▸ <b>Para k = −35:</b> w = (−10, 10, −5). ▸ <b>Hay DOS soluciones</b> (los dos sentidos opuestos sobre la misma recta dirección). ▸ <b>Por qué las otras están mal:</b> (A) (B) son cada una solo una de las dos soluciones (incompleto); (D) ‖(70,−70,35)‖ = √(4900+4900+1225) = √11025 = 105 ≠ 15.'},
  {st: '¿Para qué valor de '+M('k')+' los vectores '+M('(k, 2, 1)')+' y '+M('(3, k, −3)')+' son ortogonales?', opts: [M('k = 0'), M('k = −3'), M('k = 3/5'), M('k = 1')], c: 2, ex: 'Ortogonales ⟺ producto escalar = 0. ▸ (k,2,1)·(3,k,−3) = 3k + 2k + (−3) = 5k − 3 = 0 → <b>k = 3/5</b>. ▸ <b>Verificación:</b> 5(3/5) − 3 = 3 − 3 = 0 ✓. ▸ <b>Por qué las otras están mal:</b> con k=0 → 0+0−3 = −3 ≠ 0; con k=−3 → −15−3 = −18 ≠ 0; con k=1 → 5−3 = 2 ≠ 0. <b>Truco:</b> ortogonalidad SIEMPRE se traduce a una ecuación lineal o cuadrática en k que se despeja directamente.'},
  {st: 'La norma del vector '+M('(1, 2, −2)')+' es:', opts: [M('1'), M('3'), M('5'), M('9')], c: 1, ex: 'Fórmula: ‖v‖ = √(v₁² + v₂² + v₃²). ▸ ‖(1,2,−2)‖ = √(1² + 2² + (−2)²) = √(1 + 4 + 4) = √9 = <b>3</b>. ▸ <b>Por qué las otras están mal:</b> (A) "1" es solo la primera componente (no la norma); (C) "5" suma 1²+4 = 5 (olvida la última componente al cuadrado); (D) "9" es ‖v‖² (la norma elevada al cuadrado, sin la raíz). <b>Recordá:</b> el signo NO importa porque se eleva al cuadrado.'},
  {st: 'Sea L: (x,y) = λ(1, 2). La proyección ortogonal del punto '+M('B = (3, 1)')+' sobre L es:', opts: [M('A = (1, 2)'), M('A = (3, 1)'), M('A = (2, 4)'), M('A = (0, 0)')], c: 0, ex: 'Algoritmo de proyección ortogonal sobre recta paramétrica. ▸ <b>Paso 1:</b> A es punto genérico de L → A = λ(1,2) = (λ, 2λ). ▸ <b>Paso 2:</b> vector B−A = (3−λ, 1−2λ). ▸ <b>Paso 3:</b> imponer perpendicularidad (B−A)·d = 0 con d=(1,2): 1·(3−λ) + 2·(1−2λ) = 3 − λ + 2 − 4λ = 5 − 5λ = 0 → λ = 1. ▸ <b>Paso 4:</b> reemplazar λ=1 en A → <b>A = (1, 2)</b>. ▸ <b>Verificación:</b> A está en L (λ=1 ✓), B−A = (2,−1), (2,−1)·(1,2) = 2−2 = 0 ✓. ▸ <b>Por qué las otras están mal:</b> (B) A=B mismo (no proyectó); (C) λ=2 da A=(2,4), pero B−A=(1,−3), (1,−3)·(1,2)=1−6=−5≠0; (D) λ=0 da A=O, pero B−O=B, B·d=3+2=5≠0.'},
  {st: '¿Cuál es el área del paralelogramo formado por '+M('u = (1, 0, 1)')+' y '+M('v = (0, 2, 0)')+'?', opts: [M('2'), M('2√2'), M('√5'), M('1')], c: 1, ex: 'Área = ‖u × v‖. ▸ <b>Producto vectorial:</b> u × v = | î  ĵ  k̂ |, fila 1: (1,0,1), fila 2: (0,2,0). Componentes: ▸ î: (0·0 − 1·2) = −2. ▸ ĵ: −(1·0 − 1·0) = 0. ▸ k̂: (1·2 − 0·0) = 2. ▸ u × v = (−2, 0, 2). ▸ <b>Norma:</b> ‖(−2,0,2)‖ = √(4 + 0 + 4) = √8 = <b>2√2</b>. ▸ <b>Por qué las otras están mal:</b> (A) "2" sería ‖v‖ solo (sin u); (C) "√5" no surge de los datos; (D) "1" no aplica. <b>Truco:</b> u·v (escalar) da número (relacionado con ángulo); u×v (vectorial) da vector perpendicular cuya norma es el área.'},
  {st: 'Si '+M('u = (1, 2, 3)')+' y '+M('v = (4, −1, 0)')+', ¿cuál es el coseno del ángulo entre ellos?', opts: [M('cos α = 2/(√14·√17)'), M('cos α = 0'), M('cos α = 1'), M('cos α = −1/2')], c: 0, ex: 'Fórmula: cos α = (u·v)/(‖u‖·‖v‖). ▸ <b>Producto escalar:</b> u·v = 1·4 + 2·(−1) + 3·0 = 4 − 2 + 0 = 2. ▸ <b>Normas:</b> ‖u‖ = √(1+4+9) = √14; ‖v‖ = √(16+1+0) = √17. ▸ <b>Resultado:</b> cos α = 2/(√14·√17) = 2/√238 ≈ 0,130. Ángulo agudo (cos > 0). ▸ <b>Por qué las otras están mal:</b> (B) "0" sería ortogonalidad (u·v = 0, pero acá u·v = 2 ≠ 0); (C) "1" sería paralelos en mismo sentido (no es el caso); (D) "−1/2" da ángulo de 120° (no es el caso).'}
]);

// ============ UNIDAD 2 · RECTAS Y PLANOS ============
registerExercises('algebra', '2', [
  {st: 'Posición relativa de '+M('L<sub>1</sub>: (x,y,z) = α(1,0,−1) + (−1,2,3)')+' y '+M('L<sub>2</sub>: (x,y,z) = β(0,2,2) + (1,0,1)')+'.', opts: ['Paralelas', 'Coincidentes', 'Se cortan en un punto', 'Alabeadas'], c: 3, ex: 'Algoritmo posición relativa en ℝ³. ▸ <b>Paso 1: ¿Direcciones paralelas?</b> d₁=(1,0,−1) vs d₂=(0,2,2). Si fueran múltiplos, existiría λ con (1,0,−1)=λ(0,2,2). De la 1ª coord: 1=0·λ=0 imposible. <b>NO son paralelas.</b> ▸ <b>Paso 2: ¿Se intersecan?</b> Igualar: α(1,0,−1)+(−1,2,3) = β(0,2,2)+(1,0,1). Sistema: x: α−1 = 1 → α=2. y: 2 = 2β → β=1. z: −α+3 = 2β+1 → −2+3 = 3 → 1 = 3 <b>contradicción</b>. ▸ <b>Conclusión:</b> direcciones no paralelas + sin intersección = <b>ALABEADAS</b> (caso exclusivo de ℝ³). ▸ <b>Por qué las otras están mal:</b> (A) (B) requieren direcciones múltiplos; (C) requiere sistema compatible.'},
  {st: 'Una ecuación del plano que pasa por '+M('(1, 0, 2)')+' con normal '+M('n = (2, −1, 3)')+' es:', opts: [M('2x − y + 3z = 8'), M('2x − y + 3z = 0'), M('x − 2y + z = 1'), M('2x − y + 3z = 5')], c: 0, ex: 'Plano con normal n=(a,b,c) → ecuación ax + by + cz = d. ▸ <b>Forma:</b> 2x − y + 3z = d. ▸ <b>Determinar d:</b> reemplazo el punto (1,0,2): 2·1 − 0 + 3·2 = 2 + 6 = 8 → d = 8. ▸ <b>Resultado:</b> 2x − y + 3z = 8. ▸ <b>Verificación:</b> el punto (1,0,2) cumple 2−0+6=8 ✓. ▸ <b>Por qué las otras están mal:</b> (B) 2x−y+3z=0 pasaría por el origen, pero (0,0,0) no es nuestro punto; (C) usa normal (1,−2,1), distinta de la pedida; (D) "5" no surge de reemplazar.'},
  {st: 'La distancia del punto '+M('(1, 2)')+' a la recta '+M('3x + 4y − 5 = 0')+' es:', opts: [M('6/5'), M('1'), M('6'), M('1/5')], c: 0, ex: 'Fórmula: d(P, L) = |a·x₀ + b·y₀ + c| / √(a² + b²) donde la recta es ax+by+c=0. ▸ <b>Numerador:</b> |3·1 + 4·2 + (−5)| = |3 + 8 − 5| = |6| = 6. ▸ <b>Denominador:</b> √(3² + 4²) = √(9+16) = √25 = 5. ▸ <b>Distancia:</b> 6/5 = 1,2. ▸ <b>Por qué las otras están mal:</b> (B) "1" se obtiene si olvidás el valor absoluto y usás 5/5; (C) "6" se obtiene si olvidás dividir por la norma del vector normal; (D) "1/5" invierte numerador y denominador. <b>Recordatorio:</b> el (a,b) del numerador es la NORMAL a la recta, por eso √(a²+b²) en el denominador.'},
  {st: 'La proyección ortogonal de '+M('v = (3, 4)')+' sobre '+M('u = (1, 0)')+' es:', opts: [M('(3, 0)'), M('(0, 4)'), M('(3, 4)'), M('(1, 0)')], c: 0, ex: 'Fórmula: proy<sub>u</sub>(v) = (v·u / ‖u‖²)·u. ▸ <b>Producto escalar:</b> v·u = 3·1 + 4·0 = 3. ▸ <b>Norma al cuadrado:</b> ‖u‖² = 1² + 0² = 1. ▸ <b>Resultado:</b> (3/1)·(1, 0) = <b>(3, 0)</b>. Es la "sombra" de v sobre el eje x. ▸ <b>Verificación:</b> el resultado es paralelo a u (multiplicado por escalar 3) ✓ y v − (3,0) = (0,4) que es ortogonal a u (producto escalar 0) ✓. ▸ <b>Por qué las otras están mal:</b> (B) sería proyección sobre eje y (la "sombra" sobre el eje vertical); (C) v sin proyectar; (D) solo u sin escalar.'},
  {st: 'Si A es la proyección ortogonal de B sobre L: X = λd, ¿qué dos condiciones debe cumplir A?', opts: ['Solo (B−A)·d = 0', 'Solo A ∈ L', 'A ∈ L (existe λ tal que A = λd) Y (B−A)·d = 0', 'No hay condiciones específicas'], c: 2, ex: 'La proyección de B sobre L es el ÚNICO punto A∈L que minimiza ‖B−A‖. ▸ <b>Geométricamente:</b> el segmento BA debe ser perpendicular a la dirección de L. ▸ <b>Las DOS condiciones son necesarias:</b> (1) A∈L (sino no es proyección sobre L sino sobre una paralela); (2) (B−A)⊥d (sino no minimiza distancia). ▸ <b>Por qué las otras están mal:</b> (A) si (B−A)·d=0 pero A∉L → cumple perpendicularidad pero no es proyección sobre L; (B) si A∈L pero (B−A) no es perpendicular → no minimiza; (D) sí hay condiciones precisas (las dos).'},
  {st: 'Para hallar la proyección ortogonal de '+M('P = (1, 0, 2)')+' sobre L: X = λ(2, −1, 0), ¿qué hacés?', opts: ['Calcular ‖P‖', 'Escribir A = (2λ, −λ, 0) y plantear (P−A)·(2,−1,0) = 0', 'Resolver el sistema P = λ·d', 'Producto vectorial de P con d'], c: 1, ex: 'Algoritmo del parcial Escayola: ▸ A genérico de L → A = λ(2,−1,0) = (2λ, −λ, 0). ▸ P − A = (1−2λ, λ, 2). ▸ Imponer (P−A)·d = 0 con d=(2,−1,0): 2(1−2λ) + (−1)·λ + 0·2 = 2 − 4λ − λ = 2 − 5λ = 0 → λ = 2/5. ▸ <b>Resultado:</b> A = (4/5, −2/5, 0). ▸ <b>Por qué las otras están mal:</b> (A) ‖P‖ es solo la norma de P, no útil para proyección; (C) "P = λd" implicaría P∈L (no se cumple porque P no es múltiplo de d); (D) producto vectorial da un vector perpendicular pero no localiza el punto sobre L.'},
  {st: 'Para hallar la proyección ortogonal de P sobre el plano π: 2x − 3z = 0, ¿qué recta auxiliar usás?', opts: ['La recta paralela a π por P', 'La recta normal al plano por P, con dirección (2, 0, −3)', 'La recta y = x', 'No hace falta recta auxiliar'], c: 1, ex: 'La proyección de P sobre el plano π = "pie de la perpendicular" desde P. ▸ <b>Receta:</b> (1) Recta normal a π por P: dirección = vector normal n del plano (se lee de los coeficientes). Para 2x−3z=0 → n=(2,0,−3). (2) Buscar intersección de la recta con π. (3) Ese punto es la proyección. ▸ <b>Por qué las otras están mal:</b> (A) recta paralela a π no toca π (a menos que P∈π); (C) "y=x" arbitraria, sin relación con π; (D) sí hace falta para construir la perpendicular.'},
  {st: 'El simétrico de P = (2, −4) respecto al punto Q = (−1, 1) es:', opts: [M('(−4, 6)'), M('(0, −2)'), M('(−1, −3)'), M('(3, −5)')], c: 0, ex: 'Fórmula del simétrico respecto a un punto: <b>P\' = 2Q − P</b>. ▸ <b>Justificación:</b> Q debe ser el punto medio entre P y P\' → Q = (P+P\')/2 → despejando P\' = 2Q − P. ▸ <b>Cálculo:</b> P\' = 2·(−1, 1) − (2, −4) = (−2, 2) − (2, −4) = (−2−2, 2−(−4)) = <b>(−4, 6)</b>. ▸ <b>Verificación:</b> punto medio = ((2+(−4))/2, (−4+6)/2) = (−1, 1) = Q ✓. ▸ <b>Por qué las otras están mal:</b> (B) (0,−2) es el promedio sin doblarlo; (C) (−1,−3) no surge; (D) (3,−5) sería con error de signo en la fórmula.'},
  {st: 'Si el simétrico de P respecto a Q es P\', ¿cómo hallás Q?', opts: [M('Q = P − P\''), M('Q = (P + P\') / 2 (Q es el punto medio)'), M('Q = 2P − P\''), M('Q = P · P\'')], c: 1, ex: 'De la fórmula P\' = 2Q − P, despejo Q: P\' + P = 2Q → Q = (P+P\')/2. <b>Q es el punto medio</b> entre P y P\'. ▸ <b>Coordenada por coordenada:</b> Q = ((Pₓ+P\'ₓ)/2, (Pᵧ+P\'ᵧ)/2). ▸ <b>Por qué las otras están mal:</b> (A) "P−P\'" da un VECTOR (dirección), no un punto; (C) "2P−P\'" sería el simétrico de P\' respecto a P (al revés); (D) "P·P\'" es producto escalar (un número), no un punto.'},
  {st: 'Para hallar el simétrico de P respecto a una recta L, la receta es:', opts: ['P\' = 2P − L', 'Hallar A = proy. ortogonal de P sobre L y luego P\' = 2A − P', 'Reflejar coordenada por coordenada', 'P\' = P + d (donde d es la dirección de L)'], c: 1, ex: 'Receta universal de simétrico respecto a recta o plano: ▸ <b>Paso 1:</b> A = proyección ortogonal de P sobre L (algoritmo clásico de proyección). ▸ <b>Paso 2:</b> P\' = 2A − P (porque A debe ser punto medio entre P y P\'). ▸ <b>Por qué las otras están mal:</b> (A) "L" es una recta (conjunto de puntos), no un punto; restar L no tiene sentido; (C) reflejar coord-por-coord solo funciona para EJES coordenados, no para una recta cualquiera; (D) sumar d desplaza a P en la dirección de L (lo "mueve a lo largo"), no lo refleja.'},
  {st: 'El simétrico de (3, −1) respecto al eje x es:', opts: [M('(3, 1)'), M('(−3, −1)'), M('(−3, 1)'), M('(1, 3)')], c: 0, ex: 'Atajo para simétricos respecto a ejes coordenados: ▸ Eje x → cambia signo de y: (x, y) → (x, −y). ▸ Eje y → cambia signo de x: (x, y) → (−x, y). ▸ Origen → cambia ambos signos: (x, y) → (−x, −y). ▸ Recta y=x → intercambia coordenadas: (x, y) → (y, x). ▸ <b>Aplicación:</b> (3, −1) respecto a eje x → (3, −(−1)) = <b>(3, 1)</b>. ▸ <b>Por qué las otras están mal:</b> (B) (−3,−1) sería respecto al eje y; (C) (−3,1) sería respecto al origen; (D) (1,3) sería respecto a la recta y=x.'},
  {st: 'Para verificar que A es la proyección ortogonal de P sobre L, ¿qué tenés que comprobar?', opts: ['Hallar λ que da A = λd + P₀ (que A ∈ L) Y (P−A)·d = 0', 'Solo (P−A)·d = 0', 'Solo ‖P − A‖ = mínimo', 'Solo A·d = 0'], c: 0, ex: 'Una proyección debe cumplir DOS condiciones simultáneamente: ▸ (1) <b>A ∈ L:</b> existe un λ tal que A = λd + P₀ (la proyección está sobre L). ▸ (2) <b>(P−A)·d = 0:</b> el vector P−A es perpendicular a la dirección de L. ▸ <b>Por qué las otras están mal:</b> (B) sin verificar A∈L podrías acertar dirección pero no estar SOBRE L; (C) "norma mínima" es CONSECUENCIA de (1) y (2), no se verifica directamente sin medir todas las distancias (ineficiente); (D) "A·d = 0" significaría que A es perpendicular a d, lo cual no tiene relación con la proyección.'}
]);

// ============ UNIDAD 3 · SUBESPACIOS ============
registerExercises('algebra', '3', [
  {st: 'Considerá '+M('S = {(x<sub>1</sub>, x<sub>2</sub>, x<sub>3</sub>, x<sub>4</sub>) ∈ ℝ⁴ : x<sub>1</sub> − x<sub>4</sub> = 0}')+'. ¿Cuál es su dimensión?', opts: [M('1'), M('2'), M('3'), M('4')], c: 2, ex: 'Regla: dim(S) = dim(espacio total) − cantidad de ecuaciones LINEALMENTE INDEPENDIENTES. ▸ <b>Aquí:</b> dim(ℝ⁴) = 4, hay 1 ecuación independiente: x₁ = x₄. dim(S) = 4 − 1 = <b>3</b>. ▸ <b>Verificación con base:</b> las variables libres son x₂, x₃ y una entre x₁/x₄ (digamos x₄ libre, x₁ = x₄). Vectores: (1,0,0,1), (0,1,0,0), (0,0,1,0). Tres vectores L.I. en S → dim S = 3. ▸ <b>Por qué las otras están mal:</b> (A) "1" sería con 3 ecuaciones independientes; (B) "2" con 2 ecuaciones; (D) "4" implicaría S = ℝ⁴ (sin restricción).'},
  {st: '¿'+M('(2, 0, 4)')+' es combinación lineal de '+M('(1, −1, 2)')+' y '+M('(1, 1, 2)')+'?', opts: ['Sí, con coeficientes (1, 1)', 'Sí, con coeficientes (2, 0)', 'No', 'Sí, pero con infinitas combinaciones'], c: 0, ex: 'Planteo α(1,−1,2) + β(1,1,2) = (2,0,4). ▸ <b>Sistema:</b> α + β = 2 (1ª); −α + β = 0 (2ª); 2α + 2β = 4 (3ª). ▸ <b>De la 2ª:</b> α = β. ▸ <b>En la 1ª:</b> 2α = 2 → α = β = 1. ▸ <b>Verifico la 3ª:</b> 2·1 + 2·1 = 4 ✓. ▸ <b>Resultado:</b> (2,0,4) = 1·(1,−1,2) + 1·(1,1,2). Coeficientes (1, 1). ▸ <b>Por qué las otras están mal:</b> (B) (2,0) → 2(1,−1,2)+0 = (2,−2,4) ≠ (2,0,4); (C) sí es combinación (mostrado arriba); (D) los dos vectores generadores son L.I. (no múltiplos), por lo tanto la combinación, si existe, es ÚNICA.'},
  {st: '¿Cuál de los siguientes vectores pertenece a '+M('S = {(x,y,z) ∈ ℝ³ : x + y − z = 0}')+'?', opts: [M('(1, 2, 3)'), M('(1, 1, 1)'), M('(2, 0, 0)'), M('(1, −1, 1)')], c: 0, ex: 'Para que un vector pertenezca a S, debe satisfacer la ecuación x+y−z=0. ▸ <b>Test cada opción:</b> ▸ (1,2,3): 1+2−3 = 0 ✓ <b>PERTENECE</b>. ▸ (1,1,1): 1+1−1 = 1 ≠ 0 ✗. ▸ (2,0,0): 2+0−0 = 2 ≠ 0 ✗. ▸ (1,−1,1): 1+(−1)−1 = −1 ≠ 0 ✗. ▸ <b>Por qué las otras están mal:</b> (B) (C) (D) no satisfacen la ecuación de S.'},
  {st: '¿'+M('{(1, 1, 0), (1, 0, 1), (0, 1, 1)}')+' es L.I.?', opts: ['Sí', 'No, porque el tercero es suma de los otros dos', 'No, porque el primero es suma de los otros dos', 'Depende del cuerpo'], c: 0, ex: 'Test de independencia: planteo α(1,1,0) + β(1,0,1) + γ(0,1,1) = (0,0,0). ▸ <b>Sistema:</b> α+β = 0 (1ª); α+γ = 0 (2ª); β+γ = 0 (3ª). ▸ <b>De la 1ª:</b> β = −α. <b>De la 2ª:</b> γ = −α. <b>En la 3ª:</b> −α + (−α) = −2α = 0 → α = 0 → β = γ = 0. ▸ <b>Solución única (la trivial)</b> → L.I. ▸ <b>Por qué las otras están mal:</b> (B) (C) afirman dependencias incorrectas. Verificación: (0,1,1) ≠ (1,1,0)+(1,0,1) = (2,1,1); (1,1,0) ≠ (1,0,1)+(0,1,1) = (1,1,2). (D) sobre ℝ y ℂ el resultado es el mismo (no depende del cuerpo).'},
  {st: 'Si '+M('dim(S) = 2')+' en '+M('ℝ³')+' y '+M('{v<sub>1</sub>, v<sub>2</sub>}')+' es base de S, entonces '+M('{v<sub>1</sub>, v<sub>2</sub>, w}')+' con '+M('w ∉ S')+' es:', opts: ['Una base de ℝ³', 'L.D.', 'Una base de S', 'Genera solo S'], c: 0, ex: '▸ v₁, v₂ son L.I. (por ser base de S). ▸ Como w ∉ S, w no es combinación lineal de v₁ y v₂ (sino estaría en S). ▸ Por lo tanto los TRES vectores son L.I. ▸ Tres vectores L.I. en ℝ³ (que tiene dim 3) forman una <b>BASE de ℝ³</b>. ▸ <b>Por qué las otras están mal:</b> (B) "L.D." requeriría que w fuera comb. lineal de v₁,v₂, pero w∉S contradice eso; (C) base de S necesita exactamente 2 vectores (no 3); (D) generan TODO ℝ³ (no solo S), porque w "saca" del subespacio.'},
  {st: 'El subespacio generado por '+M('(1, 2)')+' y '+M('(2, 4)')+' tiene dimensión:', opts: [M('0'), M('1'), M('2'), M('3')], c: 1, ex: '▸ <b>¿Son L.I. (1,2) y (2,4)?</b> Verifico si son múltiplos: (2,4) = 2·(1,2). ✓ → <b>SÍ son múltiplos → L.D.</b> ▸ Solo uno de ellos aporta dimensión (el otro es redundante). ▸ <b>Dim(span) = 1</b> (es una recta por el origen, dirección (1,2)). ▸ <b>Por qué las otras están mal:</b> (A) "0" implicaría que ambos son nulos (no es el caso); (C) "2" implicaría L.I. (pero son múltiplos); (D) "3" es imposible en ℝ² o con solo 2 vectores generadores.'},
  {st: '¿Cuál es una base del subespacio '+M('S = {(x,y,z) ∈ ℝ³ : x − 2y + z = 0}')+'?', opts: [M('{(2, 1, 0), (−1, 0, 1)}'), M('{(1, 0, 0), (0, 1, 0), (0, 0, 1)}'), M('{(1, −2, 1)}'), M('{(1, 1, 1)}')], c: 0, ex: 'S es el plano x−2y+z=0 (dim S = 3−1 = 2). Necesito 2 vectores L.I. que cumplan la ecuación. ▸ <b>Test (2,1,0):</b> 2−2·1+0 = 0 ✓. ▸ <b>Test (−1,0,1):</b> −1−0+1 = 0 ✓. ▸ <b>¿Son L.I.?</b> No son múltiplos (la 1ª coord es 2 vs −1, distinta proporción que la 2ª 1 vs 0) → L.I. ✓. ▸ <b>Es base.</b> ▸ <b>Por qué las otras están mal:</b> (B) base de ℝ³ (3 vectores, demasiados para un plano); (C) (1,−2,1) es la NORMAL al plano (el vector normal NO pertenece al plano, satisface 1+4+1=6≠0); (D) (1,1,1): 1−2+1 = 0 ✓ pertenece, pero solo un vector → dim 1 (insuficiente para una base de S).'}
]);

// ============ UNIDAD 4 · CÓNICAS ============
registerExercises('algebra', '4', [
  {st: 'El centro y radio de la circunferencia '+M('x² + y² − 6x + 2y = 0')+' son:', opts: [M('Centro (3, −1), radio √10'), M('Centro (−3, 1), radio √10'), M('Centro (3, −1), radio 10'), M('Centro (6, −2), radio 4')], c: 0, ex: 'Completar cuadrados para llevar a forma canónica (x−h)² + (y−k)² = r². ▸ <b>En x:</b> x²−6x = (x−3)² − 9. ▸ <b>En y:</b> y²+2y = (y+1)² − 1. ▸ <b>Sustituyo:</b> (x−3)² − 9 + (y+1)² − 1 = 0 → (x−3)² + (y+1)² = 10. ▸ <b>Centro:</b> (h, k) = <b>(3, −1)</b>. <b>Radio:</b> r = √10. ▸ <b>Por qué las otras están mal:</b> (B) signos invertidos en h y k (al "pasar al otro lado" se cambia signo correctamente, pero la opción los invierte mal); (C) "radio 10" sería r² (no r); (D) (6,−2) duplica los coeficientes lineales mal.'},
  {st: 'La ecuación de la parábola con foco '+M('(2, −1.5)')+' y directriz '+M('y = −0.5')+' es:', opts: [M('(x−2)² = −2(y+1)'), M('(x−2)² = 2(y+1)'), M('(y+1)² = −2(x−2)'), M('(x−2)² = −2(y−1)')], c: 0, ex: 'Análisis geométrico: ▸ <b>Directriz horizontal</b> (y=cte) → la parábola tiene EJE VERTICAL → ecuación tipo (x−h)² = 4p(y−k). ▸ <b>Vértice:</b> punto medio entre foco y la perpendicular desde foco a directriz. x_vért = x_foco = 2 (la perpendicular es vertical). y_vért = (y_foco + y_dir)/2 = (−1,5 + (−0,5))/2 = −1. <b>Vértice: (2, −1)</b>. ▸ <b>Distancia vértice-foco:</b> |y_foco − y_vért| = |−1,5−(−1)| = 0,5. Como el foco (y=−1,5) está DEBAJO del vértice (y=−1), la parábola abre hacia abajo → 4p es negativo. 4p = −2 (con |4p| = 4·0,5 = 2). ▸ <b>Ecuación:</b> (x−2)² = −2(y−(−1)) = <b>−2(y+1)</b>. ▸ <b>Por qué las otras están mal:</b> (B) signo positivo abriría hacia arriba (contradice foco abajo); (C) (y−k)²= ... abre horizontalmente; (D) (y−1) tiene k=1 (centro mal posicionado).'},
  {st: 'El centro de la hipérbola con asíntotas '+M('y = 2x + 1')+' e '+M('y = −2x + 5')+' está en:', opts: [M('(1, 3)'), M('(−1, 3)'), M('(0, 3)'), M('(2, 1)')], c: 0, ex: 'Las asíntotas de una hipérbola se intersecan EN el centro. ▸ <b>Igualar las dos asíntotas:</b> 2x + 1 = −2x + 5 → 4x = 4 → x = 1. ▸ <b>Sustituyo en cualquier asíntota:</b> y = 2·1 + 1 = 3. ▸ <b>Centro: (1, 3)</b>. ▸ <b>Verificación:</b> ¿(1,3) en la 2ª? y = −2·1 + 5 = 3 ✓. ▸ <b>Por qué las otras están mal:</b> (B) en y=2x+1 con x=−1: y = −1 ≠ 3; (C) en y=2·0+1 = 1 ≠ 3; (D) (2,1) no satisface ni 2·2+1=5 ni −2·2+5=1 (la 2ª sí pero la 1ª no, y el centro debe satisfacer ambas).'},
  {st: 'Para la elipse '+M('x²/25 + y²/9 = 1')+', los focos están en:', opts: [M('(±4, 0)'), M('(0, ±4)'), M('(±3, 0)'), M('(±5, 0)')], c: 0, ex: 'Análisis de elipse x²/a² + y²/b² = 1: ▸ <b>Identifico semiejes:</b> a² = 25 (denominador de x), b² = 9 (denominador de y). Como a² > b² → eje mayor a lo largo del EJE X (horizontal). ▸ <b>Relación pitagórica de la elipse:</b> c² = a² − b² = 25 − 9 = 16 → c = 4. ▸ <b>Focos sobre el eje mayor (eje x), simétricos al origen:</b> <b>(±4, 0)</b>. ▸ <b>Por qué las otras están mal:</b> (B) (0,±4) sería para elipse vertical (a² en y); (C) (±3,0) usa b en lugar de c (b es semieje menor, no la distancia focal); (D) (±5,0) usa a (los VÉRTICES del eje mayor, no los focos).'},
  {st: '¿'+M('(0, 4)')+' está sobre la circunferencia '+M('x² + (y−1)² = 9')+'?', opts: ['Sí, porque da exactamente 9', 'No, porque da 10', 'No, porque da 5', 'Solo si el radio fuera 4'], c: 0, ex: 'Reemplazo (x,y) = (0, 4) en la ecuación: ▸ x² + (y−1)² = 0² + (4−1)² = 0 + 3² = 0 + 9 = <b>9</b>. ▸ Como el resultado coincide con r² = 9, el punto <b>SÍ pertenece</b> a la circunferencia. ▸ <b>Verificación geométrica:</b> centro (0,1), radio 3. Distancia de (0,4) al centro: √(0² + 3²) = 3 = r ✓. ▸ <b>Por qué las otras están mal:</b> (B) "10" se obtendría con (1,4): 1+9=10 (afuera); (C) "5" con (1,3): 1+4=5 (adentro); (D) el radio actual sí es 3 (=√9), y (0,4) sí está sobre él.'},
  {st: 'La distancia del centro al foco de '+M('(x−1)²/4 + (y+2)²/1 = 1')+' es:', opts: [M('√3'), M('1'), M('2'), M('√5')], c: 0, ex: 'Análisis: ▸ <b>Identifico semiejes:</b> a² = 4 (en x), b² = 1 (en y). Como a² > b², es elipse con eje mayor horizontal. Centro (1, −2). ▸ <b>Relación de la ELIPSE:</b> c² = a² − b² = 4 − 1 = 3 → c = <b>√3</b>. ▸ Distancia centro-foco = c = √3. ▸ <b>Por qué las otras están mal:</b> (B) "1" es b (semieje menor); (C) "2" es a (semieje mayor); (D) "√5" sería c² = a²+b² (eso es la fórmula de la HIPÉRBOLA, no la elipse). <b>Truco crítico:</b> en elipse c² = a²−b² (con c < a, focos DENTRO); en hipérbola c² = a²+b² (con c > a, focos FUERA).'},
  {st: 'La hipérbola '+M('(x−2)²/9 − (y+1)²/16 = 1')+' tiene focos en:', opts: [M('(2±5, −1)'), M('(2±3, −1)'), M('(2, −1±5)'), M('(2±√7, −1)')], c: 0, ex: 'Hipérbola horizontal con centro (2, −1). ▸ <b>Semiejes:</b> a² = 9 → a = 3 (semieje real, sobre eje x); b² = 16 → b = 4 (semieje conjugado). ▸ <b>Relación pitagórica de hipérbola:</b> c² = a² + b² = 9 + 16 = 25 → c = 5. ▸ <b>Focos:</b> sobre el eje real (paralelo al eje x por el centro), a distancia c del centro. <b>F = (2±5, −1)</b> = (7, −1) y (−3, −1). ▸ <b>Por qué las otras están mal:</b> (B) usa a en lugar de c (esos serían los VÉRTICES, no focos); (C) (2, −1±5) sería para hipérbola vertical; (D) "√7" sería c²=a²−b² (eso es de elipse, y aquí daría 9−16=−7 imposible).'}
]);

// ============ UNIDAD 5 · SISTEMAS, MATRICES, DETERMINANTES ============
registerExercises('algebra', '5', [
  {st: 'El determinante de '+M('A = [[2, 1], [3, 4]]')+' es:', opts: [M('5'), M('11'), M('−5'), M('8')], c: 0, ex: 'Fórmula determinante 2×2: det = a·d − b·c (diagonal principal menos diagonal secundaria). ▸ <b>Para A = [[2,1],[3,4]]:</b> det = 2·4 − 1·3 = 8 − 3 = <b>5</b>. ▸ <b>Por qué las otras están mal:</b> (B) "11" = 8+3 (sumando en lugar de restando); (C) "−5" cambia el signo del resultado correcto; (D) "8" es solo 2·4 (olvida restar 1·3).'},
  {st: 'Si '+M('det(A) = 3')+' y '+M('A')+' es una matriz '+M('3×3')+', entonces '+M('det(2A)')+' vale:', opts: [M('6'), M('12'), M('24'), M('3')], c: 2, ex: 'Propiedad: <b>det(kA) = kⁿ · det(A)</b> donde n es el orden de la matriz cuadrada. ▸ <b>Aplico:</b> det(2A) = 2³ · det(A) = 8 · 3 = <b>24</b>. ▸ <b>Justificación:</b> al multiplicar TODA la matriz por k, cada una de las n FILAS queda multiplicada por k. Cada factor k aporta un k al determinante (linealidad por filas) → kⁿ total. ▸ <b>Por qué las otras están mal:</b> (A) "6" = 2·det(A) (mal: solo multiplicarías 1 fila por 2); (B) "12" = 4·det(A) = 2²·det(A) (sería para matriz 2×2); (D) "3" sin tocar k (olvida la propiedad).'},
  {st: 'Si '+M('det(A) = 5')+' y '+M('det(B) = 2')+', entonces '+M('det(A·B)')+' vale:', opts: [M('7'), M('10'), M('2/5'), M('25')], c: 1, ex: 'Propiedad multiplicativa del determinante: <b>det(A·B) = det(A) · det(B)</b>. ▸ <b>Cálculo:</b> det(AB) = 5 · 2 = <b>10</b>. ▸ <b>Importante:</b> esto requiere que A y B sean cuadradas del mismo orden. ▸ <b>Por qué las otras están mal:</b> (A) "7" = 5+2 (suma en lugar de multiplicar); (C) "2/5" divide; (D) "25" = 5² (det(A·A), no det(A·B)).'},
  {st: 'Un sistema homogéneo Ax = 0 con matriz '+M('A')+' de '+M('n×n')+' tiene solución NO trivial ⟺:', opts: [M('det(A) ≠ 0'), M('det(A) = 0'), M('A es inversible'), M('rg(A) = n')], c: 1, ex: 'Sistema homogéneo Ax=0 SIEMPRE tiene la solución trivial x=0. Tiene OTRA solución (no trivial) cuando A NO es inversible. ▸ <b>Equivalencias:</b> A no inversible ⟺ det(A) = 0 ⟺ rg(A) < n ⟺ columnas L.D. ⟺ ker(A) ≠ {0}. ▸ <b>Por qué las otras están mal:</b> (A) det≠0 → A inversible → solo solución trivial; (C) "A inversible" ⟺ det≠0 (lo OPUESTO a lo buscado); (D) rg=n equivale a det≠0 (también lo opuesto).'},
  {st: 'Clasificar el sistema: '+M('x + y = 1; 2x + 2y = 2; x − y = 3')+'.', opts: ['Compatible determinado (única solución)', 'Compatible indeterminado (infinitas)', 'Incompatible (sin solución)', 'Depende de los datos'], c: 0, ex: 'Análisis: ▸ <b>Detectar redundancia:</b> Ec. 2 (2x+2y=2) es exactamente 2× la Ec. 1 (x+y=1). No aporta información nueva. ▸ <b>Sistema efectivo:</b> 2 ecuaciones independientes con 2 incógnitas: x+y=1 y x−y=3. ▸ <b>Resolución:</b> Sumando: 2x = 4 → x = 2. Restando 1ª−2ª: 2y = −2 → y = −1. ▸ <b>Solución única (2, −1)</b> → <b>COMPATIBLE DETERMINADO</b>. ▸ <b>Por qué las otras están mal:</b> (B) indeterminado requiere más incógnitas que ecuaciones independientes; (C) incompatible requiere contradicción explícita (como 0 = 1); (D) está completamente determinado.'},
  {st: 'La inversa de '+M('A = [[1, 2], [3, 5]]')+' existe? Justificar.', opts: ['Siempre, sin verificar', 'Nunca, es singular', 'Sí, porque det(A) = −1 ≠ 0', 'Solo si trabajamos en ℂ'], c: 2, ex: 'Una matriz cuadrada es inversible ⟺ det ≠ 0. ▸ <b>Cálculo del determinante:</b> det(A) = 1·5 − 2·3 = 5 − 6 = <b>−1</b>. ▸ Como −1 ≠ 0 → A <b>SÍ es inversible</b>. ▸ <b>Inversa explícita (2×2):</b> A⁻¹ = (1/det)·[[d,−b],[−c,a]] = (1/(−1))·[[5,−2],[−3,1]] = [[−5,2],[3,−1]]. ▸ <b>Por qué las otras están mal:</b> (A) hay que VERIFICAR el determinante (no es automático para todas las matrices); (B) det = −1 ≠ 0, NO es singular; (D) el cálculo es real, no requiere ℂ.'},
  {st: 'Resolver el sistema '+M('2x + y = 5; x − y = 1')+'.', opts: [M('(x, y) = (2, 1)'), M('(x, y) = (1, 2)'), M('(x, y) = (3, −1)'), M('No tiene solución')], c: 0, ex: 'Sumar las dos ecuaciones para eliminar y: ▸ (2x+y) + (x−y) = 5 + 1 → 3x = 6 → <b>x = 2</b>. ▸ Sustituyo en la 2ª: 2 − y = 1 → y = 1. ▸ <b>Solución: (2, 1)</b>. ▸ <b>Verificación en 1ª:</b> 2·2 + 1 = 5 ✓. ▸ <b>Por qué las otras están mal:</b> (B) (1,2) en 1ª: 2+2 = 4 ≠ 5; (C) (3,−1) en 1ª: 6−1 = 5 ✓ pero en 2ª: 3−(−1) = 4 ≠ 1; (D) tiene solución única (las rectas no son paralelas).'},
  {st: 'Discutir según '+M('k')+' el sistema '+M('kx + y = 1; x + ky = 1')+'. ¿Para qué valor de k es INCOMPATIBLE (SI)?', opts: [M('k = 1'), M('k = −1'), M('k = 0'), M('Nunca es incompatible')], c: 1, ex: 'El determinante de la matriz de coeficientes manda la discusión. ▸ <b>det:</b> | k 1 ; 1 k | = k² − 1 = (k−1)(k+1). ▸ <b>Si k ≠ 1 y k ≠ −1:</b> det ≠ 0 → <b>SCD</b> (única solución). ▸ <b>Si k = 1:</b> las dos ecuaciones son x+y=1 y x+y=1 (idénticas) → <b>SCI</b> (infinitas). ▸ <b>Si k = −1:</b> queda −x+y=1 y x−y=1; sumando: 0 = 2 (contradicción) → <b>SI (incompatible)</b>. ▸ <b>Respuesta: k = −1</b>. ▸ <b>Por qué las otras están mal:</b> (A) k=1 da SCI, no SI; (C) k=0 da det=−1≠0 → SCD; (D) sí hay un valor (k=−1) que lo vuelve incompatible.'},
  {st: 'Escalonando, discutí según '+M('k')+' el sistema 3×3 '+M('x + y + z = 1; 2x + y + 3z = 4; x + y + kz = 2')+'. La clasificación es:', opts: [M('SCD si k ≠ 1; SI (incompatible) si k = 1'), M('SCD para todo k'), M('SCI si k = 1; SCD si k ≠ 1'), M('SI para todo k')], c: 0, ex: 'Escalono la matriz ampliada usando la 1ª fila como pivote. ▸ <b>F₂ ← F₂ − 2F₁:</b> (2−2, 1−2, 3−2 | 4−2) = (0, −1, 1 | 2) → −y + z = 2. ▸ <b>F₃ ← F₃ − F₁:</b> (0, 0, k−1 | 1) → (k−1)z = 1. ▸ <b>Caso k ≠ 1:</b> de la 3ª fila z = 1/(k−1); el escalonamiento tiene 3 pivotes (rango 3 = nº incógnitas) → <b>SCD</b>. ▸ <b>Caso k = 1:</b> la 3ª fila queda 0·z = 1 → <b>0 = 1, contradicción → SI (incompatible)</b>. ▸ <b>Por qué las otras están mal:</b> (B) ignora que k=1 rompe la consistencia; (C) k=1 NO da infinitas: el término independiente 1 ≠ 0 hace la fila incompatible (sería SCI solo si quedara 0=0); (D) para k≠1 sí hay solución única.'}
]);

// ============ UNIDAD 6 · TRANSFORMACIONES LINEALES ============
registerExercises('algebra', '6', [
  {st: 'Si '+M('T : ℝ³ → ℝ²')+' está dada por '+M('T(x,y,z) = (x+y, y−z)')+', entonces '+M('T(1, 2, 3)')+' vale:', opts: [M('(3, −1)'), M('(1, 2)'), M('(3, 1)'), M('(3, 2)')], c: 0, ex: 'Aplicar la fórmula de T: ▸ 1ª componente: x + y = 1 + 2 = 3. ▸ 2ª componente: y − z = 2 − 3 = −1. ▸ <b>T(1,2,3) = (3, −1)</b>. ▸ <b>Por qué las otras están mal:</b> (B) (1,2) son las dos primeras coordenadas del INPUT (sin aplicar T); (C) (3,1) sería con z=1 (no z=3); (D) (3,2) sería sin restar z en la 2ª.'},
  {st: 'Para la T del ejercicio anterior (T: ℝ³→ℝ², T(x,y,z) = (x+y, y−z)), '+M('dim(Im(T))')+' vale:', opts: [M('0'), M('1'), M('2'), M('3')], c: 2, ex: 'La imagen es el espacio columna de la matriz canónica. ▸ <b>Calcular T en base canónica:</b> T(e₁) = T(1,0,0) = (1, 0). T(e₂) = T(0,1,0) = (1, 1). T(e₃) = T(0,0,1) = (0, −1). ▸ <b>Matriz canónica</b> (columnas = T(e_i)): A = [[1, 1, 0], [0, 1, −1]]. ▸ <b>Imagen = espacio columna en ℝ²:</b> generado por (1,0), (1,1), (0,−1). Las dos primeras son L.I. (no múltiplos), entonces generan ℝ² → <b>dim(Im) = 2</b>. ▸ <b>Por qué las otras están mal:</b> (A) "0" sería T = 0; (B) "1" implicaría imagen recta; (D) "3" imposible: Im ⊆ codominio ℝ² (dim ≤ 2).'},
  {st: 'Para la misma T (T: ℝ³→ℝ²), '+M('dim(Nu(T))')+' vale:', opts: [M('0'), M('1'), M('2'), M('3')], c: 1, ex: 'Teorema de la dimensión: <b>dim(dom) = dim(Nu(T)) + dim(Im(T))</b>. ▸ <b>Aquí:</b> dim(dom) = 3 (ℝ³), dim(Im) = 2 (calculado antes). ▸ 3 = dim(Nu) + 2 → <b>dim(Nu) = 1</b>. ▸ <b>Verificación directa:</b> resolver T(x,y,z)=(0,0): x+y=0 e y−z=0 → x=−y, z=y. Núcleo: {y(−1,1,1) : y∈ℝ} → recta de dim 1. ✓ ▸ <b>Por qué las otras están mal:</b> (A) "0" implicaría T inyectiva, pero ℝ³→ℝ² nunca es inyectiva (la dim cae); (C) (D) demasiado grandes.'},
  {st: 'Si '+M('T : ℝⁿ → ℝⁿ')+' es inyectiva, entonces también es:', opts: ['No se puede saber', 'Sobreyectiva (en dim iguales son equivalentes)', 'No sobreyectiva', 'La identidad'], c: 1, ex: 'Teorema fundamental: en transformaciones lineales con <b>dim(dominio) = dim(codominio)</b>, las propiedades inyectividad ⟺ sobreyectividad ⟺ biyectividad son equivalentes. ▸ <b>Justificación:</b> T inyectiva ⟹ dim(Nu) = 0 (núcleo trivial) ⟹ dim(Im) = n − 0 = n = dim(codom) ⟹ Im = codom ⟹ sobreyectiva. ▸ <b>Por qué las otras están mal:</b> (A) sí se puede saber por teorema; (C) opuesto al teorema; (D) inyectiva no implica identidad (ej: T(x)=2x es inyectiva pero no es id).'},
  {st: 'La matriz canónica de '+M('T(x, y) = (2x − y, x + 3y)')+' es:', opts: [M('[[2, −1], [1, 3]]'), M('[[2, 1], [−1, 3]]'), M('[[1, −1], [2, 3]]'), M('[[2, 3], [−1, 1]]')], c: 0, ex: 'Las columnas de la matriz canónica son las imágenes de la base canónica. ▸ <b>T(e₁) = T(1,0):</b> 1ª comp: 2·1−0 = 2. 2ª comp: 1+3·0 = 1. → T(e₁) = (2, 1). ▸ <b>T(e₂) = T(0,1):</b> 1ª comp: 0−1 = −1. 2ª comp: 0+3 = 3. → T(e₂) = (−1, 3). ▸ <b>Matriz</b> (columnas = T(e₁), T(e₂)): [[2, −1], [1, 3]]. ▸ <b>Verificación:</b> A·(1,0)ᵀ = (2,1)ᵀ ✓; A·(0,1)ᵀ = (−1,3)ᵀ ✓. ▸ <b>Por qué las otras están mal:</b> (B) es la TRASPUESTA de la correcta; (C) (D) intercambian componentes incorrectamente.'},
  {st: 'Si '+M('T(x<sub>1</sub>, x<sub>2</sub>, x<sub>3</sub>, x<sub>4</sub>) = (−x<sub>2</sub> + x<sub>3</sub>, 5x<sub>2</sub>, 0)')+', entonces '+M('dim(Im(T))')+' vale:', opts: [M('0'), M('1'), M('2'), M('3')], c: 2, ex: 'Calcular columnas de la matriz canónica (T(e_i)): ▸ T(e₁) = T(1,0,0,0) = (0, 0, 0). ▸ T(e₂) = T(0,1,0,0) = (−1, 5, 0). ▸ T(e₃) = T(0,0,1,0) = (1, 0, 0). ▸ T(e₄) = T(0,0,0,1) = (0, 0, 0). ▸ <b>Columnas no nulas:</b> (−1,5,0) y (1,0,0). ¿Son L.I.? La 2ª coord es 5 vs 0 (no múltiplos) → SÍ L.I. ▸ <b>dim(Im) = 2</b>. ▸ <b>Por qué las otras están mal:</b> (A) "0" ignora las columnas no nulas; (B) "1" supondría que c₂ y c₃ son colineales (no lo son); (D) "3" requeriría 3 columnas L.I., pero la 3ª coord siempre es 0 (Im ⊂ {z=0}).'},
  {st: 'Si '+M('T : ℝ² → ℝ²')+' satisface '+M('T(1,0) = (3,−1)')+' y '+M('T(0,1) = (2,4)')+', ¿cuánto vale '+M('T(2,3)')+'?', opts: [M('(12, 10)'), M('(5, 3)'), M('(6, −2)'), M('(8, 6)')], c: 0, ex: 'Linealidad: T(2,3) = T(2·(1,0) + 3·(0,1)) = 2·T(1,0) + 3·T(0,1). ▸ <b>Cálculo:</b> 2·(3,−1) + 3·(2,4) = (6,−2) + (6,12) = <b>(12, 10)</b>. ▸ <b>Verificación con matriz canónica:</b> A = [[3,2],[−1,4]] (columnas son T(e_i)). A·(2,3)ᵀ = (3·2+2·3, −1·2+4·3)ᵀ = (12, 10)ᵀ ✓. ▸ <b>Por qué las otras están mal:</b> (B) (5,3) suma directamente las imágenes (sin escalar por (2,3)); (C) (6,−2) es solo 2·T(e₁); (D) (8,6) usa coeficientes equivocados.'}
]);

// ============ UNIDAD 7 · COMPLEJOS ============
registerExercises('algebra', '7', [
  {st: 'El conjugado de '+M('z = 3 − 2i')+' es:', opts: [M('3 + 2i'), M('−3 + 2i'), M('−3 − 2i'), M('3 − 2i')], c: 0, ex: 'El conjugado de a+bi es a−bi: <b>cambia signo SOLO de la parte imaginaria</b>. ▸ z = 3 − 2i → z̄ = 3 + 2i (la parte imaginaria −2i se vuelve +2i). ▸ <b>Propiedad útil:</b> z·z̄ = |z|² (siempre real positivo). Verificación: (3−2i)(3+2i) = 9 − (2i)² = 9+4 = 13 = |z|². ▸ <b>Por qué las otras están mal:</b> (B) (−3+2i) cambia ambos signos (eso sería −z̄); (C) (−3−2i) niega todo (eso es −z); (D) (3−2i) es z mismo sin tocar.'},
  {st: 'El módulo de '+M('z = 1 + i')+' es:', opts: [M('1'), M('√2'), M('2'), M('0')], c: 1, ex: 'Fórmula: |z| = √(a² + b²) donde z = a + bi. ▸ <b>Para z = 1 + i:</b> |z| = √(1² + 1²) = √2 ≈ 1,414. ▸ <b>Interpretación geométrica:</b> distancia de z al origen en el plano complejo. (1,1) está a √2 del origen. ▸ <b>Por qué las otras están mal:</b> (A) "1" es Re(z) o Im(z) (no la norma); (C) "2" es |z|² (sin la raíz); (D) "0" solo si z=0 (acá z=1+i ≠ 0).'},
  {st: 'El argumento principal de '+M('z = 1 + i')+' (en (−π, π]) es:', opts: [M('0'), M('π/4'), M('π/2'), M('π')], c: 1, ex: '▸ <b>Análisis del cuadrante:</b> Re(z) = 1 > 0, Im(z) = 1 > 0 → primer cuadrante. ▸ <b>Cálculo:</b> arg(z) = arctan(b/a) = arctan(1/1) = arctan(1) = <b>π/4</b> (45°). ▸ <b>Verificación:</b> z = √2·(cos(π/4) + i·sen(π/4)) = √2·(√2/2 + i·√2/2) = 1+i ✓. ▸ <b>Por qué las otras están mal:</b> (A) "0" es para z real positivo (eje x positivo); (C) "π/2" para imaginario puro positivo (eje y positivo); (D) "π" para z real negativo (eje x negativo).'},
  {st: '¿Cuánto vale '+M('(1 + i)²')+'?', opts: [M('0'), M('2'), M('2i'), M('−1 + 2i')], c: 2, ex: 'Aplicar (a+b)² = a² + 2ab + b² con a=1 y b=i. ▸ <b>Cálculo:</b> (1+i)² = 1² + 2·1·i + i² = 1 + 2i + (−1) = <b>2i</b>. ▸ <b>Truco crítico:</b> i² = −1 SIEMPRE. ▸ <b>Verificación con módulo y argumento:</b> |1+i|=√2 → |(1+i)²| = 2. arg(1+i)=π/4 → arg((1+i)²) = π/2. (1+i)² = 2(cos(π/2)+i·sen(π/2)) = 2·(0+i) = 2i ✓. ▸ <b>Por qué las otras están mal:</b> (A) "0" sería si i² cancelara también el 2i (no lo hace); (B) "2" trata i² como 1 (mal); (D) "−1+2i" usa i² = −1 mal en otro lugar (resultado: 1+2i−1 = 2i, no −1+2i).'},
  {st: '¿Cuántas soluciones tiene '+M('z³ = 8')+' en '+M('ℂ')+'?', opts: [M('1'), M('2'), M('3'), M('Infinitas')], c: 2, ex: 'Teorema fundamental: <b>zⁿ = w (con w ≠ 0) tiene EXACTAMENTE n raíces complejas distintas</b>, equiespaciadas en una circunferencia de radio |w|^(1/n). ▸ <b>Para z³ = 8:</b> exactamente 3 raíces. ▸ <b>Cálculo explícito:</b> 8 = 8·e^(i·0). Raíces: z_k = 2·e^(i·(0+2πk)/3), k=0,1,2 → z₀ = 2 (real), z₁ = 2·e^(i·2π/3) = −1 + i√3, z₂ = 2·e^(i·4π/3) = −1 − i√3. ▸ <b>Por qué las otras están mal:</b> (A) "1" solo cuenta la raíz real (incompleto en ℂ); (B) "2" no aplica; (D) "infinitas" no, son siempre exactamente n.'},
  {st: 'Si '+M('|z|² = z·z̄ = 4')+' y la parte real de z es 0, entonces z vale:', opts: [M('±2'), M('±2i'), M('2 + 2i'), M('4i')], c: 1, ex: 'Datos: |z|² = 4 y Re(z) = 0. ▸ Si z = a + bi, entonces |z|² = a² + b². ▸ <b>Como Re(z) = a = 0:</b> 0 + b² = 4 → b² = 4 → b = ±2. ▸ <b>z = 0 + bi = ±2i</b>. ▸ <b>Verificación:</b> z=2i → z̄=−2i → z·z̄ = (2i)(−2i) = −4i² = 4 ✓. ▸ <b>Por qué las otras están mal:</b> (A) (±2) son reales (Re(z)=±2 ≠ 0, contradice); (C) (2+2i) tiene Re=2 ≠ 0; (D) (4i) tiene |z|²=16 ≠ 4.'},
  {st: 'Si '+M('z = 2(cos(π/3) + i·sen(π/3))')+' (forma polar), ¿cuál es '+M('z²')+'?', opts: [M('z² = 4(cos(2π/3) + i·sen(2π/3))'), M('z² = 4(cos(π/3) + i·sen(π/3))'), M('z² = 2(cos(2π/3) + i·sen(2π/3))'), M('z² = 4i')], c: 0, ex: 'Teorema de De Moivre: para z = r(cos θ + i·sen θ), <b>zⁿ = rⁿ·(cos(nθ) + i·sen(nθ))</b>. ▸ <b>Para n=2, r=2, θ=π/3:</b> z² = 2²·(cos(2·π/3) + i·sen(2·π/3)) = <b>4·(cos(2π/3) + i·sen(2π/3))</b>. ▸ <b>En forma binómica:</b> 4·(−1/2 + i·√3/2) = −2 + 2√3 i. ▸ <b>Por qué las otras están mal:</b> (B) eleva el módulo pero olvida duplicar el argumento; (C) duplica el argumento pero deja el módulo en 2 (no en 4=r²); (D) "4i" sería para z=√2(cos(π/4)+i·sen(π/4)) (otro caso).'}
]);

// ============ UNIDAD 8 · POLINOMIOS ============
registerExercises('algebra', '8', [
  {st: 'El resto de dividir '+M('P(x) = x³ − 2x + 5')+' entre '+M('x − 1')+' es:', opts: [M('0'), M('4'), M('−2'), M('5')], c: 1, ex: 'Teorema del resto: <b>el resto de dividir P(x) entre (x−a) es P(a)</b>. ▸ <b>Aquí a = 1:</b> R = P(1) = 1³ − 2·1 + 5 = 1 − 2 + 5 = <b>4</b>. ▸ <b>Por qué las otras están mal:</b> (A) "0" sería si 1 fuera raíz (entonces (x−1) | P), pero P(1) = 4 ≠ 0; (C) "−2" es el coeficiente lineal, no surge del cálculo; (D) "5" es P(0) (el término independiente), no P(1).'},
  {st: 'Si '+M('a = 2')+' es raíz de '+M('P(x)')+', entonces '+M('P(x)')+' es divisible por:', opts: [M('x + 2'), M('x − 2'), M('x² + 2'), M('2x')], c: 1, ex: 'Teorema del factor: <b>a es raíz de P ⟺ (x − a) divide a P</b>. ▸ <b>Aquí raíz a = 2:</b> el factor es <b>(x − 2)</b>. ▸ <b>Verificación:</b> si (x−2) | P, entonces P(x) = (x−2)·Q(x) para algún Q. Evaluando en x=2: P(2) = 0·Q(2) = 0 → 2 es raíz. ✓ ▸ <b>Por qué las otras están mal:</b> (A) (x+2) significaría raíz −2 (no 2); (C) (x²+2) no tiene raíces reales; (D) "2x" no tiene la forma estándar (x−a).'},
  {st: 'Si '+M('P ∈ ℝ[x]')+' y '+M('2 + 3i')+' es raíz, ¿qué otra raíz tiene seguro?', opts: [M('2 − 3i'), M('−2 + 3i'), M('−2 − 3i'), M('3 + 2i')], c: 0, ex: 'Teorema clave: <b>en P ∈ ℝ[x] (coeficientes reales), si una raíz es compleja a+bi, entonces su CONJUGADA a−bi también es raíz</b>. ▸ <b>Justificación:</b> P(z̄) = P̄(z) (al conjugar una expresión con coef. reales). Si P(z)=0, entonces P̄(z)=0 → P(z̄)=0. ▸ <b>Para 2+3i, la conjugada es 2−3i</b>. ▸ <b>Por qué las otras están mal:</b> (B) (−2+3i) cambia signo de Re; (C) (−2−3i) niega todo; (D) (3+2i) intercambia Re e Im. <b>Recordá:</b> en ℝ[x] las raíces no reales SIEMPRE vienen en pares conjugados (por eso un polinomio real de grado impar tiene al menos una raíz real).'},
  {st: 'Un polinomio '+M('P ∈ ℝ[x]')+' de grado mínimo con raíces '+M('3')+' e '+M('i')+' tiene grado:', opts: [M('2'), M('3'), M('4'), M('5')], c: 1, ex: 'En ℝ[x], si i es raíz, entonces −i (conjugada) también lo es. Necesitamos contar todos los factores: ▸ <b>Para 3 (real):</b> factor (x−3), grado 1. ▸ <b>Para {i, −i} (par conjugado):</b> factor (x−i)(x+i) = x² − i² = x² + 1, grado 2 (con coeficientes reales ✓). ▸ <b>Total grado mínimo:</b> 1 + 2 = <b>3</b>. ▸ <b>Ejemplo concreto:</b> P(x) = (x−3)(x²+1) = x³ − 3x² + x − 3. ▸ <b>Por qué las otras están mal:</b> (A) "2" olvida que i obliga a −i (no podés tener un polinomio real solo con (x−i) porque sus coef. no serían reales); (C) (D) tendrían factores extra que no hace falta.'},
  {st: 'Un polinomio '+M('P ∈ ℚ[x]')+' de grado mínimo con raíces '+M('√2')+' y '+M('1')+' tiene grado:', opts: [M('2'), M('3'), M('4'), M('5')], c: 1, ex: 'En ℚ[x] (coeficientes racionales), si √2 es raíz (irracional cuadrático), entonces −√2 (su "conjugado en ℚ") también lo es. ▸ <b>Para {√2, −√2}:</b> factor (x−√2)(x+√2) = x² − 2, grado 2 (con coef. racionales ✓). ▸ <b>Para 1 (racional):</b> factor (x−1), grado 1. ▸ <b>Total grado mínimo:</b> 2 + 1 = <b>3</b>. ▸ <b>Por qué las otras están mal:</b> (A) "2" si solo (x−√2)(x−1), pero ese polinomio tendría coef. con √2 (no racional). En ℚ[x] necesitás (x²−2). (C) (D) tienen factores extra innecesarios.'},
  {st: 'Sea '+M('P ∈ ℚ[x]')+' de grado mínimo con '+M('P(√5) = 0')+', '+M('i')+' raíz doble, y '+M('P(−2) = −75')+'. Entonces '+M('P(x)')+' es:', opts: [M('3(x² − 5)(x² + 1)²'), M('(x² − 5)(x² + 1)²'), M('−3(x − √5)(x² + 1)²'), M('3(x − √5)(x + √5)(x − i)(x + i)')], c: 0, ex: 'En ℚ[x] (raíces irracionales/imaginarias necesitan sus pares con misma multiplicidad). ▸ <b>√5 raíz simple → −√5 también:</b> factor (x−√5)(x+√5) = x² − 5. ▸ <b>i raíz DOBLE → −i raíz doble:</b> factor (x−i)²(x+i)² = ((x−i)(x+i))² = (x²+1)². ▸ <b>Grado mínimo:</b> 2 + 4 = 6. ▸ <b>Forma:</b> P(x) = k·(x²−5)(x²+1)². ▸ <b>Imponer condición P(−2) = −75:</b> P(−2) = k·((−2)²−5)·((−2)²+1)² = k·(4−5)·(4+1)² = k·(−1)·25 = −25k. ▸ <b>Despejar:</b> −25k = −75 → k = 3. ▸ <b>Resultado:</b> <b>P(x) = 3(x²−5)(x²+1)²</b>. ▸ <b>Por qué las otras están mal:</b> (B) le falta el k=3 (no satisface P(−2)=−75); (C) (x−√5) suelto NO está en ℚ[x] (porque √5 ∉ ℚ); (D) factores con i NO están en ℚ[x] (i ∉ ℚ).'},
  {st: 'Factorizar el polinomio '+M('P(x) = x³ − 6x² + 11x − 6')+' en '+M('ℝ[x]')+' sabiendo que tiene raíz x = 1.', opts: [M('(x − 1)(x − 2)(x − 3)'), M('(x − 1)(x² − 5x + 6)'), M('(x − 1)²(x − 6)'), M('(x − 1)(x + 2)(x + 3)')], c: 0, ex: 'Si x=1 es raíz, P es divisible por (x−1). ▸ <b>División polinómica</b> (Ruffini con 1): coef [1, −6, 11, −6] → bajar 1, multiplicar y sumar: 1, 1−6+1·1=−5, 11+(−5)·1=6, −6+6·1=0 (resto). Cociente: x²−5x+6. ▸ <b>Factorizar el cociente:</b> x²−5x+6 = (x−2)(x−3) (suma de raíces 5, producto 6). ▸ <b>Resultado:</b> <b>P(x) = (x−1)(x−2)(x−3)</b>. Tres raíces: 1, 2, 3. ▸ <b>Verificación:</b> P(2) = 8−24+22−6 = 0 ✓. P(3) = 27−54+33−6 = 0 ✓. ▸ <b>Por qué las otras están mal:</b> (B) está incompleto (no factoriza el cociente); (C) (D) son factorizaciones incorrectas (verificalo evaluando).'}
]);
