registerExercises('biologia', '1', [
  {st: '¿Cuál de los siguientes ítems corresponde a tres características de TODOS los seres vivos?', opts: ['Metabolismo, evolución, irritabilidad', 'Mitosis, homeostasis, metabolismo', 'Crecimiento, respiración aeróbica, reproducción', 'Fotosíntesis, irritabilidad, homeostasis'], c: 0, ex: 'Metabolismo + evolución + irritabilidad las cumplen TODOS. ▸ Por qué las otras están mal: (B) mitosis NO en procariotas (fisión binaria); (C) respiración aeróbica NO en anaerobios estrictos; (D) fotosíntesis solo en autótrofos.'},
  {st: 'La homeostasis se refiere a:', opts: ['Reproducirse de manera constante', 'Mantener el medio interno relativamente constante a pesar de los cambios externos', 'La síntesis de moléculas orgánicas', 'Cambiar de forma según el ambiente'], c: 1, ex: 'Homeostasis = mantener T, pH, glucemia, osmolaridad estables. Ej: insulina al consumir azúcar. ▸ Por qué las otras están mal: (A) reproducción es otro proceso; (C) síntesis es metabolismo; (D) sería plasticidad fenotípica.'},
  {st: 'Ordenar de menor a mayor: Nitrógeno – aminoácido – enzima – célula – hígado.', opts: ['Enzima – célula – nitrógeno – hígado – aminoácido', 'Célula – nitrógeno – hígado – enzima – aminoácido', 'Nitrógeno – aminoácido – enzima – célula – hígado', 'Hígado – enzima – célula – aminoácido – nitrógeno'], c: 2, ex: 'Niveles: átomo (N) → molécula (aminoácido) → macromolécula/proteína (enzima) → célula → órgano (hígado). ▸ Por qué las otras están mal: desordenan las jerarquías biológicas.'},
  {st: '¿Cuál situación se vincula con homeostasis?', opts: ['Aerobios mueren en laguna sin O₂', 'Cultivo se reproduce ilimitado al aumentar nutrientes', 'Girasoles se marchitan sin luz prolongada', 'Liberar insulina al consumir golosina y regular glucemia'], c: 3, ex: 'Insulina mantiene glucemia en rango estable a pesar del input variable → homeostasis clásica. ▸ Por qué las otras están mal: son ejemplos de fallo o de respuesta NO homeostática (muerte, crecimiento ilimitado, marchitamiento).'},
  {st: '¿Cuántos dominios biológicos se reconocen?', opts: ['2 (procariota y eucariota)', '3 (Bacteria, Archaea y Eukarya)', '5 (Monera, Protista, Fungi, Plantae, Animalia)', '6'], c: 1, ex: '3 dominios: Bacteria, Archaea (procariotas pero genética distinta), Eukarya. Reinos son clasificación más fina. ▸ Por qué las otras están mal: (A) "2" agrupa demasiado; (C) "5" son los REINOS, no dominios; (D) inexistente.'},
  {st: 'En un ecosistema, los organismos AUTÓTROFOS:', opts: ['Consumen otros para obtener energía', 'Fijan energía solar o química y producen materia orgánica propia', 'Solo descomponen materia muerta', 'No participan en cadenas tróficas'], c: 1, ex: 'Auto + trofos = "se alimentan a sí mismos". Producen materia orgánica desde inorgánica (CO₂) usando luz (foto) o química (quimio). Base de cadenas tróficas. ▸ Por qué las otras están mal: (A) son los heterótrofos; (C) descomponedores son saprófitos; (D) son la base, sí participan.'}
]);

registerExercises('biologia', '2', [
  {st: '¿Cuál función es exclusiva de células EUCARIONTES?', opts: ['Fotosíntesis', 'Respiración celular', 'Transporte intracelular de vesículas', 'Síntesis de proteínas'], c: 2, ex: 'Transporte vesicular requiere endomembranas y citoesqueleto, ambos AUSENTES en procariotas. ▸ Por qué las otras están mal: (A) cianobacterias hacen fotosíntesis; (B) (D) son universales en todos los seres vivos.'},
  {st: '¿Qué proceso ocurre en VEGETALES pero NO en animales?', opts: ['Fijación de CO₂ en cloroplastos', 'Respiración celular', 'Mitosis y meiosis', 'Transcripción y traducción'], c: 0, ex: 'Cloroplastos solo en plantas/algas (animales no fijan CO₂). ▸ Por qué las otras están mal: (B) (C) (D) son universales en eucariotas.'},
  {st: 'Indica la opción que represente nivel SUBCELULAR EXCLUSIVO de vegetales:', opts: ['Almidón y ADN con histonas', 'Ribosomas y cloroplastos', 'Complejo de Golgi y pared celular', 'Cloroplastos y vacuola central'], c: 3, ex: 'Cloroplastos + vacuola central = exclusivos de plantas. ▸ Por qué las otras están mal: (A) ADN+histonas también animal; (B) ribosomas universales; (C) Golgi en todos los eucariotas.'},
  {st: '¿Cuál es EXCLUSIVA de un PROCARIONTE?', opts: ['Unicelulares y se dividen por mitosis', 'Pueden reproducirse sexualmente', 'ADN circular no asociado a histonas', 'Pared de quitina'], c: 2, ex: 'ADN circular sin histonas = procariota. ▸ Por qué las otras están mal: (A) procariotas hacen FISIÓN BINARIA, no mitosis; (B) reproducción sexual es eucariota; (D) quitina es de hongos.'},
  {st: 'Al comparar células eucariotas y procariotas:', opts: ['Procariotas dividen por fisión binaria; eucariotas por mitosis o meiosis', 'Ambas sintetizan proteínas en ribosomas y REG', 'Eucariotas son auto/hetero; procariotas solo hetero', 'La glucólisis ocurre en mitocondrias en eucariotas'], c: 0, ex: 'Procariotas: fisión binaria. Eucariotas somáticas: mitosis. Eucariotas gaméticas: meiosis. ▸ Por qué las otras están mal: (B) REG solo en eucariotas; (C) hay procariotas autótrofas (cianobacterias); (D) glucólisis ocurre en CITOSOL en ambas.'},
  {st: '¿Qué diferencia una célula PROCARIONTE autótrofa de una EUCARIONTE autótrofa?', opts: ['Pared celular', 'Permeabilidad selectiva', 'Mitocondrias', 'Ribosomas'], c: 2, ex: 'Solo eucariotas tienen mitocondrias (procariotas hacen respiración en su membrana). ▸ Por qué las otras están mal: (A) pared en ambas (peptidoglicano vs celulosa); (B) (D) universales.'},
  {st: 'La compartimentalización celular en eucariotas permite:', opts: ['Que las reacciones se mezclen libremente', 'Especializar microambientes (pH, enzimas) para procesos específicos en cada organela', 'Que la célula sea más pequeña', 'Eliminar la membrana plasmática'], c: 1, ex: 'Compartimentalización = innovación clave eucariota: cada organela tiene su microambiente (lisosoma pH 4.5, mitocondria con gradientes para ATP, etc.). ▸ Por qué las otras están mal: (A) lo opuesto; (C) eucariotas son MÁS GRANDES; (D) la membrana sigue presente.'}
]);

registerExercises('biologia', '3', [
  {st: 'Si se aísla una partícula infecciosa SOLO con proteínas, podría tratarse de:', opts: ['Un viroide', 'Un virus', 'Un prion', 'Un retrovirus'], c: 2, ex: 'Prion = solo proteína mal plegada (sin ácido nucleico). Causa enfermedades neurodegenerativas (Creutzfeldt-Jakob, vacas locas). ▸ Por qué las otras están mal: (A) viroide = solo ARN; (B) virus = ác. nucleico + cápside; (D) retrovirus = ARN + transcriptasa.'},
  {st: '¿Cuál afirmación sobre los virus es CORRECTA?', opts: ['Sintetizan sus proteínas: tienen genes y ribosomas', 'Requieren RIBOSOMAS celulares para sintetizar las proteínas virales', 'La cápside es membrana de intercambio', 'En ciclo lítico el ADN se integra al ADN celular'], c: 1, ex: 'Virus NO tienen ribosomas → parásitos intracelulares OBLIGADOS. ▸ Por qué las otras están mal: (A) no tienen ribosomas; (C) cápside es proteica, no membrana; (D) integración es del ciclo LISOGÉNICO.'},
  {st: 'Los viroides son agentes infecciosos que:', opts: ['Tienen cápside proteica', 'Solo ARN, sin cápside, afectan plantas', 'Solo afectan SNC animal', 'Son variante de prion'], c: 1, ex: 'Viroide = ARN circular pequeño SIN cápside, infecta plantas (papa, tubérculos). ▸ Por qué las otras están mal: (A) sin cápside; (C) son los priones quienes afectan SNC animal; (D) priones son proteína, viroides son ARN.'},
  {st: 'En un ciclo viral en eucariontes, el orden general es:', opts: ['Liberación → adsorción → biosíntesis → ensamblaje → entrada', 'Adsorción → entrada → decapsidación → biosíntesis → ensamblaje → liberación', 'Ensamblaje → adsorción → liberación → biosíntesis', 'Biosíntesis → adsorción → entrada'], c: 1, ex: 'Orden: (1) adsorción a receptor, (2) entrada/penetración, (3) decapsidación, (4) biosíntesis, (5) ensamblaje, (6) liberación (lisis o gemación). ▸ Por qué las otras están mal: pasos desordenados.'},
  {st: 'Los retrovirus se caracterizan por:', opts: ['Doble cadena de ADN', 'ARN y transcriptasa inversa que convierte ARN en ADN', 'No tener material genético', 'Solo infectar plantas'], c: 1, ex: 'Retrovirus (VIH) tienen ARN + transcriptasa inversa → ADN se integra al genoma. ▸ Por qué las otras están mal: (A) (C) descripción equivocada; (D) infectan animales mayoritariamente.'},
  {st: 'Diferencia entre ciclo LÍTICO y LISOGÉNICO:', opts: ['Lítico en eucariotas, lisogénico en procariotas', 'Lítico: replica y lisa la célula. Lisogénico: ADN viral se integra al genoma huésped', 'Lisogénico es más rápido', 'Son sinónimos'], c: 1, ex: 'Lítico = replicación rápida + lisis (ROMPE célula al liberar viriones). Lisogénico = profago integrado al cromosoma, replica con él silenciosamente. ▸ Por qué las otras están mal: (A) ambos en procariotas; (C) (D) descripciones equivocadas.'},
  {st: '¿Cuál NO es característica de los virus?', opts: ['Material genético (ADN o ARN)', 'Cápside proteica', 'Ribosomas propios', 'Replicación en célula huésped'], c: 2, ex: 'Virus NO tienen ribosomas → necesitan los del huésped. ▸ Por qué las otras están mal: (A) (B) (D) sí tienen.'}
]);

registerExercises('biologia', '4', [
  {st: 'El ADN y el ARN se DIFERENCIAN entre sí por:', opts: ['Adenina', 'Bases nitrogenadas en general', 'Citosina', 'Timina'], c: 3, ex: 'Solo ADN tiene timina; ARN tiene URACILO en su lugar. Otra diferencia: azúcar (desoxirribosa vs ribosa). ▸ Por qué las otras están mal: (A) (C) están en ambos; (B) hay bases comunes y diferentes.'},
  {st: '¿En qué opción TODAS las moléculas son de RESERVA energética?', opts: ['Glucógeno / triglicéridos / almidón', 'Glucógeno / colágeno / almidón', 'Glucógeno / tubulina / celulosa', 'Celulosa / glucógeno / almidón'], c: 0, ex: 'Reserva: glucógeno (animal), almidón (vegetal), triglicéridos (grasa). ▸ Por qué las otras están mal: colágeno, tubulina, celulosa son ESTRUCTURALES (no reserva).'},
  {st: 'Una proteína receptor con 5 cadenas polipeptídicas. ¿Mayor nivel estructural?', opts: ['Cuaternaria', 'Terciaria', 'Secundaria', 'Primaria'], c: 0, ex: 'Cuaternaria = >1 cadena. 5 cadenas → cuaternaria. ▸ Por qué las otras están mal: (B) terciaria sería 1 cadena plegada; (C) secundaria son α-hélice/β-plegada; (D) primaria es la secuencia.'},
  {st: '¿En qué grupo TODAS son proteínas (su hidrólisis libera AMINOÁCIDOS)?', opts: ['Insulina / colesterol', 'Acilglicérido / bomba de protones', 'Enzimas hidrolíticas / glucógeno', 'Hemoglobina / carrier de glucosa'], c: 3, ex: 'Hemoglobina + carrier de glucosa = ambas proteínas → liberan aminoácidos. ▸ Por qué las otras están mal: (A) colesterol es lípido; (B) acilglicérido es lípido; (C) glucógeno es polisacárido (libera glucosa).'},
  {st: 'En las moléculas biológicas, la energía disponible para metabolismo está en:', opts: ['Enlaces covalentes', 'Uniones iónicas', 'Puente hidrógeno', 'Átomos aislados'], c: 0, ex: 'Energía química principal en enlaces covalentes (C-C, C-H). Romperlos (oxidación) libera energía. ▸ Por qué las otras están mal: (B) (C) tienen mucha menos energía; (D) átomos aislados no almacenan energía aprovechable.'},
  {st: 'Un nucleótido está formado por:', opts: ['Solo una base nitrogenada', '1 azúcar (pentosa) + 1 base + 1 a 3 fosfatos', '2 aminoácidos', '1 ácido graso + glicerol'], c: 1, ex: 'Nucleótido = pentosa + base (A,T,G,C,U) + 1-3 fosfatos. Ej: ATP = adenina + ribosa + 3 fosfatos. ▸ Por qué las otras están mal: (A) base sola es solo una parte; (C) son péptidos; (D) son lípidos.'},
  {st: 'Los lípidos anfipáticos que conforman membranas son:', opts: ['Triglicéridos', 'Fosfolípidos', 'Esteroides', 'Ceras'], c: 1, ex: 'Fosfolípidos = anfipáticos: cabeza polar + 2 colas apolares. Forman bicapas. ▸ Por qué las otras están mal: (A) (C) (D) no anfipáticos en mismo grado, no estructurales.'}
]);

registerExercises('biologia', '5', [
  {st: 'Para AUMENTAR la fluidez de membranas:', opts: ['Más colesterol', 'Más colas insaturadas en fosfolípidos', 'Bajar la temperatura', 'Mayor pH'], c: 1, ex: 'Insaturadas tienen dobles enlaces que doblan cadena → impiden empaquetamiento → más fluidez. ▸ Por qué las otras están mal: (A) colesterol AMORTIGUA (regula); (C) bajar T disminuye fluidez; (D) pH no es determinante directo.'},
  {st: 'Una célula AUMENTA volumen en solución desconocida. ¿Cuál?', opts: ['Igual concentración (isotónica)', '50% más concentrada', '2× más concentrada', '2× más diluida (hipotónica)'], c: 3, ex: 'Aumenta volumen → entra agua → medio externo HIPOTÓNICO (menos solutos afuera). Solución diluida = hipotónica. ▸ Por qué las otras están mal: (A) sin cambio; (B) (C) hipertónicas → célula se encoge.'},
  {st: '¿Qué pasa con el transporte de CO₂ si se BLOQUEAN todas las proteínas de canal?', opts: ['CO₂ requiere energía', 'CO₂ pasa normal por difusión simple', 'CO₂ no puede ingresar pero sí salir', 'CO₂ no puede salir pero sí ingresar'], c: 1, ex: 'CO₂ es pequeño y apolar → difusión SIMPLE por la bicapa, sin canales. ▸ Por qué las otras están mal: (A) la difusión simple es pasiva; (C) (D) descripciones absurdas (canales no son selectivos por dirección).'},
  {st: 'En comunicación celular, el LIGANDO:', opts: ['Recorre cortas distancias en endocrina', 'Hidrofílico → receptor citosólico', 'Puede unirse a receptor en célula blanco', 'Es la respuesta de la célula diana'], c: 2, ex: 'Ligando se une al receptor (proteína) en célula blanco. ▸ Por qué las otras están mal: (A) endocrina es de LARGAS distancias; (B) hidrofílicos tienen receptor de MEMBRANA (no citosol); (D) la respuesta es lo que ocurre tras la unión.'},
  {st: 'Colesterol y proteína integral de canal en una membrana cumplen, respectivamente:', opts: ['Receptor y aporte energético', 'Receptor y transporte', 'Aporte energético y transporte de iones', 'Estabilizar membranas y enzimática/transporte'], c: 3, ex: 'Colesterol estabiliza/regula fluidez. Proteínas integrales pueden ser canal/transportador o enzima. ▸ Por qué las otras están mal: ninguna combina los roles correctos.'},
  {st: 'INGRESO de K⁺ en CONTRA de gradiente al citosol es:', opts: ['Exergónico no anabólico', 'Endergónico y anabólico', 'Endergónico no anabólico', 'Endergónico y catabólico'], c: 2, ex: 'Contra gradiente → endergónico (requiere ATP). Pero NO es anabólico (no sintetiza moléculas grandes), solo mueve un ion. ▸ Por qué las otras están mal: (A) endergónico (requiere energía); (B) (D) no es ni anabólico ni catabólico.'},
  {st: 'Comunicación celular con señal en sangre a LARGAS distancias:', opts: ['Autocrina', 'Paracrina', 'Endocrina', 'Sináptica'], c: 2, ex: 'Endocrina = hormonas en sangre, larga distancia. ▸ Por qué las otras están mal: (A) la propia célula; (B) células vecinas (corta distancia); (D) entre neuronas (cortísima).'}
]);

registerExercises('biologia', '6', [
  {st: 'Sin citoesqueleto en una célula eucariota animal, se afectaría:', opts: ['Difusión simple', 'Síntesis de proteínas citosólicas', 'División celular', 'Respiración celular'], c: 2, ex: 'División requiere huso mitótico (microtúbulos) + citoquinesis (microfilamentos). ▸ Por qué las otras están mal: (A) difusión es por la membrana; (B) síntesis ocurre en ribosomas; (D) respiración en mitocondrias.'},
  {st: '¿Qué funciones se relacionan con MICROTÚBULOS?', opts: ['Contracción muscular y transporte de vesículas', 'Contracción y formación de cilios', 'Formación de flagelos y transporte de vesículas', 'División del citoplasma y transporte'], c: 2, ex: 'Microtúbulos: cilios, flagelos, transporte vesicular (kinesina/dineína), huso mitótico. ▸ Por qué las otras están mal: contracción muscular y citoquinesis son por MICROFILAMENTOS de actina.'},
  {st: 'El sistema de Golgi:', opts: ['Polimeriza y glicosila proteínas', 'Forma vesículas de secreción', 'Sintetiza triglicéridos y colesterol', 'Sintetiza glucosa'], c: 1, ex: 'Golgi modifica (glicosilación, fosforilación) y EMPAQUETA proteínas en vesículas. ▸ Por qué las otras están mal: (A) glicosila pero no polimeriza; (C) eso es REL; (D) glucosa se hace en cloroplastos (fotosíntesis).'},
  {st: 'Si se elimina REL en células animales:', opts: ['No hay síntesis de colesterol ni detoxificación', 'No se sintetizan triglicéridos ni ATP', 'No se almacena Ca²⁺ ni se sintetizan proteínas de membrana', 'No se sintetizan fosfolípidos ni enzimas lisosomales'], c: 0, ex: 'REL: lípidos (colesterol, fosfolípidos, triglicéridos), detoxificación, almacén de Ca²⁺. ▸ Por qué las otras están mal: ATP en mitocondrias; proteínas y enzimas lisosomales en REG.'},
  {st: 'Las células del estómago secretan pepsinógeno (proteína). Tienen muy desarrollado:', opts: ['REL y Golgi', 'REG y Golgi', 'Mitocondrias y REL', 'Lisosomas y REG'], c: 1, ex: 'Cadena para secretar proteína: REG (síntesis) → Golgi (modificación) → vesícula → exocitosis. ▸ Por qué las otras están mal: REL es para lípidos; mitocondrias para ATP; lisosomas para digestión.'},
  {st: 'Los filamentos del citoesqueleto encargados de contracción muscular y citoquinesis:', opts: ['Microtúbulos', 'Microfilamentos (actina)', 'Filamentos intermedios', 'Lamininas'], c: 1, ex: 'Actina + miosina = contracción muscular y anillo contráctil de citoquinesis. ▸ Por qué las otras están mal: microtúbulos para huso/transporte; intermedios para soporte mecánico.'},
  {st: 'La matriz extracelular (ECM) en tejidos animales:', opts: ['Es solo agua', 'Contiene colágeno, elastina, fibronectina y proteoglicanos; las células se anclan via integrinas', 'No tiene función mecánica', 'Solo en plantas'], c: 1, ex: 'ECM = red de macromoléculas (colágeno, elastina, fibronectina, proteoglicanos). Integrinas anclan células a ECM. Da soporte y señales. ▸ Por qué las otras están mal: (A) (C) descripción equivocada; (D) plantas tienen pared, no ECM como animales.'}
]);

registerExercises('biologia', '7', [
  {st: '¿Cuál enunciado es aplicable a TODAS las enzimas?', opts: ['Si se altera su estructura terciaria pueden perder actividad', 'Aceleran solo reacciones catabólicas', 'Especificidad por sitio alostérico', 'Pierden actividad después de catalizar'], c: 0, ex: 'Actividad depende de estructura 3D (sitio activo). Desnaturalización = pierde actividad. ▸ Por qué las otras están mal: (B) catalizan ANABOLISMO también; (C) la especificidad es del SITIO ACTIVO (no alostérico); (D) NO se consumen.'},
  {st: 'En reacción enzimática X→Y:', opts: ['Más sustrato → menos producto', 'Vmax aumenta con más sustrato', 'Solo ocurre en T óptima', 'Vmax se relaciona con saturación enzimática'], c: 3, ex: 'A altas [sustrato], todas las enzimas saturadas → Vmax (depende de [enzima], no de sustrato). ▸ Por qué las otras están mal: (A) más sustrato → más producto (hasta saturar); (B) Vmax depende de [enzima]; (C) ocurre fuera del óptimo, solo más lento.'},
  {st: '¿Cuál reacción es CATABÓLICA?', opts: ['Glicina + alanina + prolina → tripéptido', 'Glucosa + glucosa → maltosa', 'Glucosa + O₂ → CO₂ + H₂O', 'Glicerol + 3 ácidos grasos → triglicérido'], c: 2, ex: 'Oxidación de glucosa = catabolismo (rompe molécula grande, libera energía). ▸ Por qué las otras están mal: (A) (B) (D) son anabolismo (sintetizan moléculas grandes desde pequeñas).'},
  {st: 'Inhibidores COMPETITIVOS:', opts: ['Se unen al sitio activo y disminuyen velocidad', 'Reguladores alostéricos en sitio activo', 'Disminuyen cantidad de sustrato', 'Se unen irreversiblemente'], c: 0, ex: 'Competitivo = compite con sustrato por SITIO ACTIVO. Se revierte aumentando [sustrato]. ▸ Por qué las otras están mal: (B) alostérico se une a sitio DISTINTO; (C) (D) describen otros mecanismos.'},
  {st: 'El ATP es "moneda energética" porque:', opts: ['Es la única molécula con energía', 'Acopla reacciones exergónicas (lo producen) con endergónicas (lo consumen)', 'Es lípido de alta energía', 'No participa en metabolismo'], c: 1, ex: 'ATP integra: catabolismo lo carga, anabolismo lo gasta. Es la unidad de intercambio energético celular. ▸ Por qué las otras están mal: (A) hay otras (NADH, GTP); (C) es nucleótido, no lípido; (D) es central al metabolismo.'},
  {st: 'Una reacción libera energía neta. ¿A qué proceso podría corresponder?', opts: ['Fotosíntesis completa', 'Respiración celular', 'Síntesis de polipéptido', 'Glicerol + ácido graso → monoglicérido'], c: 1, ex: 'Exergónica = libera energía → catabolismo. Respiración oxida glucosa, libera ~30-32 ATP. ▸ Por qué las otras están mal: (A) (C) (D) son anabolismo (endergónicas, requieren energía).'},
  {st: 'En reacciones óxido-reducción, OXIDARSE significa:', opts: ['Ganar electrones', 'Perder electrones (o H, o ganar O)', 'Ganar O y perder electrones', 'Descomponerse en H₂O'], c: 1, ex: 'Oxidación = pérdida de electrones. Reducción = ganancia. Siempre van juntas (acopladas). ▸ Por qué las otras están mal: (A) es REDUCCIÓN; (C) parcial; (D) sin sentido.'}
]);

registerExercises('biologia', '8', [
  {st: 'En célula muscular SIN O₂, la glucosa se degrada a:', opts: ['Solo ácido pirúvico', 'Etanol', 'Ácido láctico', 'CO₂'], c: 2, ex: 'Sin O₂, músculo hace fermentación LÁCTICA: glucosa → 2 pirúvico → 2 lactato (regenera NAD+). En levaduras es etanol. ▸ Por qué las otras están mal: (A) pirúvico es intermediario; (B) eso es en levaduras; (D) requiere O₂.'},
  {st: 'Orden CORRECTO de etapas de fotosíntesis:', opts: ['Captación / síntesis glucosa / ruptura agua', 'Liberación de O₂ / incorporación de CO₂ / síntesis de hidratos', 'Liberación O₂ / síntesis glucosa / síntesis ATP', 'Captación / degradación ATP / fijación CO₂'], c: 1, ex: 'Fase clara: fotólisis del agua (libera O₂) + ATP/NADPH. Fase oscura: ciclo de Calvin (fija CO₂ por RuBisCO) y sintetiza glucosa. ▸ Por qué las otras están mal: orden incorrecto.'},
  {st: 'Si los carbonos del pirúvico se marcan radiactivamente, aparecerán en:', opts: ['CO₂', 'ATP', 'Glucosa', 'NADH'], c: 0, ex: 'Pirúvico se DESCARBOXILA en oxidación y ciclo de Krebs → C sale como CO₂. ▸ Por qué las otras están mal: (B) ATP no incorpora esos C; (C) glucosa no se forma de pirúvico en respiración; (D) NADH lleva H, no C.'},
  {st: 'Mitocondrias aisladas con NAD+, FAD, ADP+Pi. Para completar oxidación se agrega:', opts: ['Glucosa, O₂, CO₂', 'Glucosa, luz, CO₂', 'Ácido pirúvico y O₂', 'Pirúvico y CO₂'], c: 2, ex: 'Mitocondria recibe pirúvico (NO glucosa, glucólisis es citosólica) y necesita O₂ (aceptor final de electrones). ▸ Por qué las otras están mal: (A) no usa glucosa directamente; (B) la luz es de fotosíntesis; (D) CO₂ es producto, no reactivo.'},
  {st: 'Los autótrofos contrarrestan aumento de CO₂ atmosférico porque:', opts: ['Degradan CO₂ en cloroplastos', 'Usan CO₂ en fase bioquímica de fotosíntesis (ciclo de Calvin)', 'Usan CO₂ en ciclo de Krebs', 'Disminuyen formación de CO₂ en Calvin'], c: 1, ex: 'Calvin: RuBisCO fija CO₂ → biomasa. ▸ Por qué las otras están mal: (A) lo fijan, no lo degradan; (C) Krebs es respiración (LIBERA CO₂); (D) Calvin lo CONSUME.'},
  {st: 'En un cloroplasto, la fase fotoquímica:', opts: ['Calvin transforma O₂ en glucosa', 'Krebs transforma CO₂ en glucosa', 'En tilacoides se fija CO₂', 'En tilacoides ocurre la fotólisis del agua (H₂O → O₂)'], c: 3, ex: 'Fotoquímica = en TILACOIDES. Fotólisis del agua libera O₂. La fijación de CO₂ es en estroma (Calvin). ▸ Por qué las otras están mal: (A) (B) Krebs es respiración; (C) fijación de CO₂ es en estroma.'},
  {st: '¿Dónde ocurre la GLUCÓLISIS en eucariotas?', opts: ['Matriz mitocondrial', 'Membrana interna mitocondrial', 'Citosol', 'Núcleo'], c: 2, ex: 'Glucólisis: CITOSOL (pre-mitocondria evolutivamente). No requiere O₂ ni organelas. Si hay O₂ después, el pirúvico entra a mitocondria. ▸ Por qué las otras están mal: (A) (B) Krebs y cadena respiratoria; (D) núcleo es para ADN.'},
  {st: 'En respiración aeróbica, el aceptor FINAL de electrones de la cadena es:', opts: ['NAD+', 'FAD', 'O₂', 'CO₂'], c: 2, ex: 'O₂ recibe electrones al final + H+ → H₂O. Sin O₂, cadena se detiene, no hay fosforilación oxidativa. Por eso respiramos. ▸ Por qué las otras están mal: (A) (B) son intermediarios (transportadores); (D) producto del ciclo de Krebs, no aceptor.'}
]);
