registerExercises('biologia', '1', [
  {st: '¿Cuál de los siguientes ítems corresponde a tres características de TODOS los seres vivos?', opts: ['Metabolismo, evolución, irritabilidad', 'Mitosis, homeostasis, metabolismo', 'Crecimiento, respiración aeróbica, reproducción', 'Fotosíntesis, irritabilidad, homeostasis'], c: 0, ex: 'Metabolismo + evolución + irritabilidad las cumplen TODOS. ▸ Por qué las otras están mal: (B) mitosis NO en procariotas (fisión binaria); (C) respiración aeróbica NO en anaerobios estrictos; (D) fotosíntesis solo en autótrofos.'},
  {st: 'La homeostasis se refiere a:', opts: ['Reproducirse de manera constante', 'Mantener el medio interno relativamente constante a pesar de los cambios externos', 'La síntesis de moléculas orgánicas', 'Cambiar de forma según el ambiente'], c: 1, ex: 'Homeostasis = mantener T, pH, glucemia, osmolaridad estables. Ej: insulina al consumir azúcar. ▸ Por qué las otras están mal: (A) reproducción es otro proceso; (C) síntesis es metabolismo; (D) sería plasticidad fenotípica.'},
  {st: 'Ordenar de menor a mayor: Nitrógeno – aminoácido – enzima – célula – hígado.', opts: ['Enzima – célula – nitrógeno – hígado – aminoácido', 'Célula – nitrógeno – hígado – enzima – aminoácido', 'Nitrógeno – aminoácido – enzima – célula – hígado', 'Hígado – enzima – célula – aminoácido – nitrógeno'], c: 2, ex: 'Niveles: átomo (N) → molécula (aminoácido) → macromolécula/proteína (enzima) → célula → órgano (hígado). ▸ Por qué las otras están mal: desordenan las jerarquías biológicas.'},
  {st: '¿Cuál situación se vincula con homeostasis?', opts: ['Aerobios mueren en laguna sin O₂', 'Cultivo se reproduce ilimitado al aumentar nutrientes', 'Girasoles se marchitan sin luz prolongada', 'Liberar insulina al consumir golosina y regular glucemia'], c: 3, ex: 'Insulina mantiene glucemia en rango estable a pesar del input variable → homeostasis clásica. ▸ Por qué las otras están mal: son ejemplos de fallo o de respuesta NO homeostática (muerte, crecimiento ilimitado, marchitamiento).'},
  {st: '¿Cuántos dominios biológicos se reconocen?', opts: ['2 (procariota y eucariota)', '3 (Bacteria, Archaea y Eukarya)', '5 (Monera, Protista, Fungi, Plantae, Animalia)', '6'], c: 1, ex: '3 dominios: Bacteria, Archaea (procariotas pero genética distinta), Eukarya. Reinos son clasificación más fina. ▸ Por qué las otras están mal: (A) "2" agrupa demasiado; (C) "5" son los REINOS, no dominios; (D) inexistente.'},
  {st: 'En un ecosistema, los organismos AUTÓTROFOS:', opts: ['Consumen otros para obtener energía', 'Fijan energía solar o química y producen materia orgánica propia', 'Solo descomponen materia muerta', 'No participan en cadenas tróficas'], c: 1, ex: 'Auto + trofos = "se alimentan a sí mismos". Producen materia orgánica desde inorgánica (CO₂) usando luz (foto) o química (quimio). Base de cadenas tróficas. ▸ Por qué las otras están mal: (A) son los heterótrofos; (C) descomponedores son saprófitos; (D) son la base, sí participan.'}
]);

registerExercises('biologia', '2', [
  {st: '¿Cuál función es exclusiva de células EUCARIONTES?', opts: ['Fotosíntesis', 'Respiración celular', 'Transporte intracelular de vesículas', 'Síntesis de proteínas'], c: 2, ex: 'Transporte vesicular requiere endomembranas y citoesqueleto, ambos AUSENTES en procariotas. ▸ Por qué las otras están mal: (A) cianobacterias hacen fotosíntesis; (B) (D) son universales en todos los seres vivos.'},
  {st: '¿Qué proceso ocurre en VEGETALES pero NO en animales?', opts: ['Fijación de CO₂ en cloroplastos', 'Respiración celular', 'Mitosis y meiosis', 'Transcripción y traducción'], c: 0, ex: 'Cloroplastos solo en plantas/algas (animales no fijan CO₂). ▸ Por qué las otras están mal: (B) (C) (D) son universales en eucariotas.'},
  {st: 'Indica la opción que represente nivel SUBCELULAR EXCLUSIVO de vegetales:', opts: ['Almidón y ADN con histonas', 'Ribosomas y cloroplastos', 'Complejo de Golgi y pared celular', 'Cloroplastos y vacuola central'], c: 3, ex: 'Cloroplastos + vacuola central = exclusivos de plantas. ▸ Por qué las otras están mal: (A) ADN+histonas también animal; (B) ribosomas universales; (C) Golgi en todos los eucariotas.'},
  {st: '¿Cuál es EXCLUSIVA de un PROCARIONTE?', opts: ['Unicelulares y se dividen por mitosis', 'Pueden reproducirse sexualmente', 'ADN circular no asociado a histonas', 'Pared de quitina'], c: 2, ex: 'ADN circular sin histonas = procariota. ▸ Por qué las otras están mal: (A) procariotas hacen FISIÓN BINARIA, no mitosis; (B) reproducción sexual es eucariota; (D) quitina es de hongos.'},
  {st: 'Al comparar células eucariotas y procariotas:', opts: ['Procariotas dividen por fisión binaria; eucariotas por mitosis o meiosis', 'Ambas sintetizan proteínas en ribosomas y REG', 'Eucariotas son auto/hetero; procariotas solo hetero', 'La glucólisis ocurre en mitocondrias en eucariotas'], c: 0, ex: 'Procariotas: fisión binaria. Eucariotas somáticas: mitosis. Eucariotas gaméticas: meiosis. ▸ Por qué las otras están mal: (B) REG solo en eucariotas; (C) hay procariotas autótrofas (cianobacterias); (D) glucólisis ocurre en CITOSOL en ambas.'},
  {st: '¿Qué diferencia una célula PROCARIONTE autótrofa de una EUCARIONTE autótrofa?', opts: ['Pared celular', 'Permeabilidad selectiva', 'Mitocondrias', 'Ribosomas'], c: 2, ex: 'Solo eucariotas tienen mitocondrias (procariotas hacen respiración en su membrana). ▸ Por qué las otras están mal: (A) pared en ambas (peptidoglicano vs celulosa); (B) (D) universales.'},
  {st: 'La compartimentalización celular en eucariotas permite:', opts: ['Que las reacciones se mezclen libremente', 'Especializar microambientes (pH, enzimas) para procesos específicos en cada organela', 'Que la célula sea más pequeña', 'Eliminar la membrana plasmática'], c: 1, ex: 'Compartimentalización = innovación clave eucariota: cada organela tiene su microambiente (lisosoma pH 4.5, mitocondria con gradientes para ATP, etc.). ▸ Por qué las otras están mal: (A) lo opuesto; (C) eucariotas son MÁS GRANDES; (D) la membrana sigue presente.'}
]);

registerExercises('biologia', '3', [
  {st: 'Si se aísla una partícula infecciosa SOLO con proteínas, podría tratarse de:', opts: ['Un viroide', 'Un virus', 'Un prion', 'Un retrovirus'], c: 2, ex: 'Prion = solo proteína mal plegada (sin ácido nucleico). Causa enfermedades neurodegenerativas (Creutzfeldt-Jakob, vacas locas). ▸ Por qué las otras están mal: (A) viroide = solo ARN; (B) virus = ác. nucleico + cápside; (D) retrovirus = ARN + transcriptasa.'},
  {st: '¿Cuál afirmación sobre los virus es CORRECTA?', opts: ['Sintetizan sus proteínas: tienen genes y ribosomas', 'Requieren RIBOSOMAS celulares para sintetizar las proteínas virales', 'La cápside es membrana de intercambio', 'En ciclo lítico el ADN se integra al ADN celular'], c: 1, ex: 'Virus NO tienen ribosomas → parásitos intracelulares OBLIGADOS. ▸ Por qué las otras están mal: (A) no tienen ribosomas; (C) cápside es proteica, no membrana; (D) integración es del ciclo LISOGÉNICO.'},
  {st: 'Los viroides son agentes infecciosos que:', opts: ['Tienen cápside proteica', 'Solo ARN, sin cápside, afectan plantas', 'Solo afectan SNC animal', 'Son variante de prion'], c: 1, ex: 'Viroide = ARN circular pequeño SIN cápside, infecta plantas (papa, tubérculos). ▸ Por qué las otras están mal: (A) sin cápside; (C) son los priones quienes afectan SNC animal; (D) priones son proteína, viroides son ARN.'},
  {st: 'En un ciclo viral en eucariontes, el orden general es:', opts: ['Liberación → adsorción → biosíntesis → ensamblaje → entrada', 'Adsorción → entrada → decapsidación → biosíntesis → ensamblaje → liberación', 'Ensamblaje → adsorción → liberación → biosíntesis', 'Biosíntesis → adsorción → entrada'], c: 1, ex: 'Orden: (1) adsorción a receptor, (2) entrada/penetración, (3) decapsidación, (4) biosíntesis, (5) ensamblaje, (6) liberación (lisis o gemación). ▸ Por qué las otras están mal: pasos desordenados.'},
  {st: 'Los retrovirus se caracterizan por:', opts: ['Doble cadena de ADN', 'ARN y transcriptasa inversa que convierte ARN en ADN', 'No tener material genético', 'Solo infectar plantas'], c: 1, ex: 'Retrovirus (VIH) tienen ARN + transcriptasa inversa → ADN se integra al genoma. ▸ Por qué las otras están mal: (A) (C) descripción equivocada; (D) infectan animales mayoritariamente.'},
  {st: 'Diferencia entre ciclo LÍTICO y LISOGÉNICO:', opts: ['Lítico en eucariotas, lisogénico en procariotas', 'Lítico: replica y lisa la célula. Lisogénico: ADN viral se integra al genoma huésped', 'Lisogénico es más rápido', 'Son sinónimos'], c: 1, ex: 'Lítico = replicación rápida + lisis (ROMPE célula al liberar viriones). Lisogénico = profago integrado al cromosoma, replica con él silenciosamente. ▸ Por qué las otras están mal: (A) ambos en procariotas; (C) (D) descripciones equivocadas.'},
  {st: '¿Cuál NO es característica de los virus?', opts: ['Material genético (ADN o ARN)', 'Cápside proteica', 'Ribosomas propios', 'Replicación en célula huésped'], c: 2, ex: 'Virus NO tienen ribosomas → necesitan los del huésped. ▸ Por qué las otras están mal: (A) (B) (D) sí tienen.'}
]);

registerExercises('biologia', '4', [
  {st: 'El ADN y el ARN se DIFERENCIAN entre sí por:', opts: ['Adenina', 'Bases nitrogenadas en general', 'Citosina', 'Timina'], c: 3, ex: 'Solo ADN tiene timina; ARN tiene URACILO en su lugar. Otra diferencia: azúcar (desoxirribosa vs ribosa). ▸ Por qué las otras están mal: (A) (C) están en ambos; (B) hay bases comunes y diferentes.'},
  {st: '¿En qué opción TODAS las moléculas son de RESERVA energética?', opts: ['Glucógeno / triglicéridos / almidón', 'Glucógeno / colágeno / almidón', 'Glucógeno / tubulina / celulosa', 'Celulosa / glucógeno / almidón'], c: 0, ex: 'Reserva: glucógeno (animal), almidón (vegetal), triglicéridos (grasa). ▸ Por qué las otras están mal: colágeno, tubulina, celulosa son ESTRUCTURALES (no reserva).'},
  {st: 'Una proteína receptor con 5 cadenas polipeptídicas. ¿Mayor nivel estructural?', opts: ['Cuaternaria', 'Terciaria', 'Secundaria', 'Primaria'], c: 0, ex: 'Cuaternaria = >1 cadena. 5 cadenas → cuaternaria. ▸ Por qué las otras están mal: (B) terciaria sería 1 cadena plegada; (C) secundaria son α-hélice/β-plegada; (D) primaria es la secuencia.'},
  {st: '¿En qué grupo TODAS son proteínas (su hidrólisis libera AMINOÁCIDOS)?', opts: ['Insulina / colesterol', 'Acilglicérido / bomba de protones', 'Enzimas hidrolíticas / glucógeno', 'Hemoglobina / carrier de glucosa'], c: 3, ex: 'Hemoglobina + carrier de glucosa = ambas proteínas → liberan aminoácidos. ▸ Por qué las otras están mal: (A) colesterol es lípido; (B) acilglicérido es lípido; (C) glucógeno es polisacárido (libera glucosa).'},
  {st: 'En las moléculas biológicas, la energía disponible para metabolismo está en:', opts: ['Enlaces covalentes', 'Uniones iónicas', 'Puente hidrógeno', 'Átomos aislados'], c: 0, ex: 'Energía química principal en enlaces covalentes (C-C, C-H). Romperlos (oxidación) libera energía. ▸ Por qué las otras están mal: (B) (C) tienen mucha menos energía; (D) átomos aislados no almacenan energía aprovechable.'},
  {st: 'Un nucleótido está formado por:', opts: ['Solo una base nitrogenada', '1 azúcar (pentosa) + 1 base + 1 a 3 fosfatos', '2 aminoácidos', '1 ácido graso + glicerol'], c: 1, ex: 'Nucleótido = pentosa + base (A,T,G,C,U) + 1-3 fosfatos. Ej: ATP = adenina + ribosa + 3 fosfatos. ▸ Por qué las otras están mal: (A) base sola es solo una parte; (C) son péptidos; (D) son lípidos.'},
  {st: 'Los lípidos anfipáticos que conforman membranas son:', opts: ['Triglicéridos', 'Fosfolípidos', 'Esteroides', 'Ceras'], c: 1, ex: 'Fosfolípidos = anfipáticos: cabeza polar + 2 colas apolares. Forman bicapas. ▸ Por qué las otras están mal: (A) (C) (D) no anfipáticos en mismo grado, no estructurales.'}
]);

registerExercises('biologia', '5', [
  {st: 'Para AUMENTAR la fluidez de membranas:', opts: ['Más colesterol', 'Más colas insaturadas en fosfolípidos', 'Bajar la temperatura', 'Mayor pH'], c: 1, ex: 'Insaturadas tienen dobles enlaces que doblan cadena → impiden empaquetamiento → más fluidez. ▸ Por qué las otras están mal: (A) colesterol AMORTIGUA (regula); (C) bajar T disminuye fluidez; (D) pH no es determinante directo.'},
  {st: 'Una célula AUMENTA volumen en solución desconocida. ¿Cuál?', opts: ['Igual concentración (isotónica)', '50% más concentrada', '2× más concentrada', '2× más diluida (hipotónica)'], c: 3, ex: 'Aumenta volumen → entra agua → medio externo HIPOTÓNICO (menos solutos afuera). Solución diluida = hipotónica. ▸ Por qué las otras están mal: (A) sin cambio; (B) (C) hipertónicas → célula se encoge.'},
  {st: '¿Qué pasa con el transporte de CO₂ si se BLOQUEAN todas las proteínas de canal?', opts: ['CO₂ requiere energía', 'CO₂ pasa normal por difusión simple', 'CO₂ no puede ingresar pero sí salir', 'CO₂ no puede salir pero sí ingresar'], c: 1, ex: 'CO₂ es pequeño y apolar → difusión SIMPLE por la bicapa, sin canales. ▸ Por qué las otras están mal: (A) la difusión simple es pasiva; (C) (D) descripciones absurdas (canales no son selectivos por dirección).'},
  {st: 'En comunicación celular, el LIGANDO:', opts: ['Recorre cortas distancias en endocrina', 'Hidrofílico → receptor citosólico', 'Puede unirse a receptor en célula blanco', 'Es la respuesta de la célula diana'], c: 2, ex: 'Ligando se une al receptor (proteína) en célula blanco. ▸ Por qué las otras están mal: (A) endocrina es de LARGAS distancias; (B) hidrofílicos tienen receptor de MEMBRANA (no citosol); (D) la respuesta es lo que ocurre tras la unión.'},
  {st: 'Colesterol y proteína integral de canal en una membrana cumplen, respectivamente:', opts: ['Receptor y aporte energético', 'Receptor y transporte', 'Aporte energético y transporte de iones', 'Estabilizar membranas y enzimática/transporte'], c: 3, ex: 'Colesterol estabiliza/regula fluidez. Proteínas integrales pueden ser canal/transportador o enzima. ▸ Por qué las otras están mal: ninguna combina los roles correctos.'},
  {st: 'INGRESO de K⁺ en CONTRA de gradiente al citosol es:', opts: ['Exergónico no anabólico', 'Endergónico y anabólico', 'Endergónico no anabólico', 'Endergónico y catabólico'], c: 2, ex: 'Contra gradiente → endergónico (requiere ATP). Pero NO es anabólico (no sintetiza moléculas grandes), solo mueve un ion. ▸ Por qué las otras están mal: (A) endergónico (requiere energía); (B) (D) no es ni anabólico ni catabólico.'},
  {st: 'Comunicación celular con señal en sangre a LARGAS distancias:', opts: ['Autocrina', 'Paracrina', 'Endocrina', 'Sináptica'], c: 2, ex: 'Endocrina = hormonas en sangre, larga distancia. ▸ Por qué las otras están mal: (A) la propia célula; (B) células vecinas (corta distancia); (D) entre neuronas (cortísima).'}
]);

registerExercises('biologia', '6', [
  {st: 'Sin citoesqueleto en una célula eucariota animal, se afectaría:', opts: ['Difusión simple', 'Síntesis de proteínas citosólicas', 'División celular', 'Respiración celular'], c: 2, ex: 'División requiere huso mitótico (microtúbulos) + citoquinesis (microfilamentos). ▸ Por qué las otras están mal: (A) difusión es por la membrana; (B) síntesis ocurre en ribosomas; (D) respiración en mitocondrias.'},
  {st: '¿Qué funciones se relacionan con MICROTÚBULOS?', opts: ['Contracción muscular y transporte de vesículas', 'Contracción y formación de cilios', 'Formación de flagelos y transporte de vesículas', 'División del citoplasma y transporte'], c: 2, ex: 'Microtúbulos: cilios, flagelos, transporte vesicular (kinesina/dineína), huso mitótico. ▸ Por qué las otras están mal: contracción muscular y citoquinesis son por MICROFILAMENTOS de actina.'},
  {st: 'El sistema de Golgi:', opts: ['Polimeriza y glicosila proteínas', 'Forma vesículas de secreción', 'Sintetiza triglicéridos y colesterol', 'Sintetiza glucosa'], c: 1, ex: 'Golgi modifica (glicosilación, fosforilación) y EMPAQUETA proteínas en vesículas. ▸ Por qué las otras están mal: (A) glicosila pero no polimeriza; (C) eso es REL; (D) glucosa se hace en cloroplastos (fotosíntesis).'},
  {st: 'Si se elimina REL en células animales:', opts: ['No hay síntesis de colesterol ni detoxificación', 'No se sintetizan triglicéridos ni ATP', 'No se almacena Ca²⁺ ni se sintetizan proteínas de membrana', 'No se sintetizan fosfolípidos ni enzimas lisosomales'], c: 0, ex: 'REL: lípidos (colesterol, fosfolípidos, triglicéridos), detoxificación, almacén de Ca²⁺. ▸ Por qué las otras están mal: ATP en mitocondrias; proteínas y enzimas lisosomales en REG.'},
  {st: 'Las células del estómago secretan pepsinógeno (proteína). Tienen muy desarrollado:', opts: ['REL y Golgi', 'REG y Golgi', 'Mitocondrias y REL', 'Lisosomas y REG'], c: 1, ex: 'Cadena para secretar proteína: REG (síntesis) → Golgi (modificación) → vesícula → exocitosis. ▸ Por qué las otras están mal: REL es para lípidos; mitocondrias para ATP; lisosomas para digestión.'},
  {st: 'Los filamentos del citoesqueleto encargados de contracción muscular y citoquinesis:', opts: ['Microtúbulos', 'Microfilamentos (actina)', 'Filamentos intermedios', 'Lamininas'], c: 1, ex: 'Actina + miosina = contracción muscular y anillo contráctil de citoquinesis. ▸ Por qué las otras están mal: microtúbulos para huso/transporte; intermedios para soporte mecánico.'},
  {st: 'La matriz extracelular (ECM) en tejidos animales:', opts: ['Es solo agua', 'Contiene colágeno, elastina, fibronectina y proteoglicanos; las células se anclan via integrinas', 'No tiene función mecánica', 'Solo en plantas'], c: 1, ex: 'ECM = red de macromoléculas (colágeno, elastina, fibronectina, proteoglicanos). Integrinas anclan células a ECM. Da soporte y señales. ▸ Por qué las otras están mal: (A) (C) descripción equivocada; (D) plantas tienen pared, no ECM como animales.'}
]);

registerExercises('biologia', '7', [
  {st: '¿Cuál enunciado es aplicable a TODAS las enzimas?', opts: ['Si se altera su estructura terciaria pueden perder actividad', 'Aceleran solo reacciones catabólicas', 'Especificidad por sitio alostérico', 'Pierden actividad después de catalizar'], c: 0, ex: 'Actividad depende de estructura 3D (sitio activo). Desnaturalización = pierde actividad. ▸ Por qué las otras están mal: (B) catalizan ANABOLISMO también; (C) la especificidad es del SITIO ACTIVO (no alostérico); (D) NO se consumen.'},
  {st: 'En reacción enzimática X→Y:', opts: ['Más sustrato → menos producto', 'Vmax aumenta con más sustrato', 'Solo ocurre en T óptima', 'Vmax se relaciona con saturación enzimática'], c: 3, ex: 'A altas [sustrato], todas las enzimas saturadas → Vmax (depende de [enzima], no de sustrato). ▸ Por qué las otras están mal: (A) más sustrato → más producto (hasta saturar); (B) Vmax depende de [enzima]; (C) ocurre fuera del óptimo, solo más lento.'},
  {st: '¿Cuál reacción es CATABÓLICA?', opts: ['Glicina + alanina + prolina → tripéptido', 'Glucosa + glucosa → maltosa', 'Glucosa + O₂ → CO₂ + H₂O', 'Glicerol + 3 ácidos grasos → triglicérido'], c: 2, ex: 'Oxidación de glucosa = catabolismo (rompe molécula grande, libera energía). ▸ Por qué las otras están mal: (A) (B) (D) son anabolismo (sintetizan moléculas grandes desde pequeñas).'},
  {st: 'Inhibidores COMPETITIVOS:', opts: ['Se unen al sitio activo y disminuyen velocidad', 'Reguladores alostéricos en sitio activo', 'Disminuyen cantidad de sustrato', 'Se unen irreversiblemente'], c: 0, ex: 'Competitivo = compite con sustrato por SITIO ACTIVO. Se revierte aumentando [sustrato]. ▸ Por qué las otras están mal: (B) alostérico se une a sitio DISTINTO; (C) (D) describen otros mecanismos.'},
  {st: 'El ATP es "moneda energética" porque:', opts: ['Es la única molécula con energía', 'Acopla reacciones exergónicas (lo producen) con endergónicas (lo consumen)', 'Es lípido de alta energía', 'No participa en metabolismo'], c: 1, ex: 'ATP integra: catabolismo lo carga, anabolismo lo gasta. Es la unidad de intercambio energético celular. ▸ Por qué las otras están mal: (A) hay otras (NADH, GTP); (C) es nucleótido, no lípido; (D) es central al metabolismo.'},
  {st: 'Una reacción libera energía neta. ¿A qué proceso podría corresponder?', opts: ['Fotosíntesis completa', 'Respiración celular', 'Síntesis de polipéptido', 'Glicerol + ácido graso → monoglicérido'], c: 1, ex: 'Exergónica = libera energía → catabolismo. Respiración oxida glucosa, libera ~30-32 ATP. ▸ Por qué las otras están mal: (A) (C) (D) son anabolismo (endergónicas, requieren energía).'},
  {st: 'En reacciones óxido-reducción, OXIDARSE significa:', opts: ['Ganar electrones', 'Perder electrones (o H, o ganar O)', 'Ganar O y perder electrones', 'Descomponerse en H₂O'], c: 1, ex: 'Oxidación = pérdida de electrones. Reducción = ganancia. Siempre van juntas (acopladas). ▸ Por qué las otras están mal: (A) es REDUCCIÓN; (C) parcial; (D) sin sentido.'}
]);

registerExercises('biologia', '8', [
  {st: 'En célula muscular SIN O₂, la glucosa se degrada a:', opts: ['Solo ácido pirúvico', 'Etanol', 'Ácido láctico', 'CO₂'], c: 2, ex: 'Sin O₂, músculo hace fermentación LÁCTICA: glucosa → 2 pirúvico → 2 lactato (regenera NAD+). En levaduras es etanol. ▸ Por qué las otras están mal: (A) pirúvico es intermediario; (B) eso es en levaduras; (D) requiere O₂.'},
  {st: 'Orden CORRECTO de etapas de fotosíntesis:', opts: ['Captación / síntesis glucosa / ruptura agua', 'Liberación de O₂ / incorporación de CO₂ / síntesis de hidratos', 'Liberación O₂ / síntesis glucosa / síntesis ATP', 'Captación / degradación ATP / fijación CO₂'], c: 1, ex: 'Fase clara: fotólisis del agua (libera O₂) + ATP/NADPH. Fase oscura: ciclo de Calvin (fija CO₂ por RuBisCO) y sintetiza glucosa. ▸ Por qué las otras están mal: orden incorrecto.'},
  {st: 'Si los carbonos del pirúvico se marcan radiactivamente, aparecerán en:', opts: ['CO₂', 'ATP', 'Glucosa', 'NADH'], c: 0, ex: 'Pirúvico se DESCARBOXILA en oxidación y ciclo de Krebs → C sale como CO₂. ▸ Por qué las otras están mal: (B) ATP no incorpora esos C; (C) glucosa no se forma de pirúvico en respiración; (D) NADH lleva H, no C.'},
  {st: 'Mitocondrias aisladas con NAD+, FAD, ADP+Pi. Para completar oxidación se agrega:', opts: ['Glucosa, O₂, CO₂', 'Glucosa, luz, CO₂', 'Ácido pirúvico y O₂', 'Pirúvico y CO₂'], c: 2, ex: 'Mitocondria recibe pirúvico (NO glucosa, glucólisis es citosólica) y necesita O₂ (aceptor final de electrones). ▸ Por qué las otras están mal: (A) no usa glucosa directamente; (B) la luz es de fotosíntesis; (D) CO₂ es producto, no reactivo.'},
  {st: 'Los autótrofos contrarrestan aumento de CO₂ atmosférico porque:', opts: ['Degradan CO₂ en cloroplastos', 'Usan CO₂ en fase bioquímica de fotosíntesis (ciclo de Calvin)', 'Usan CO₂ en ciclo de Krebs', 'Disminuyen formación de CO₂ en Calvin'], c: 1, ex: 'Calvin: RuBisCO fija CO₂ → biomasa. ▸ Por qué las otras están mal: (A) lo fijan, no lo degradan; (C) Krebs es respiración (LIBERA CO₂); (D) Calvin lo CONSUME.'},
  {st: 'En un cloroplasto, la fase fotoquímica:', opts: ['Calvin transforma O₂ en glucosa', 'Krebs transforma CO₂ en glucosa', 'En tilacoides se fija CO₂', 'En tilacoides ocurre la fotólisis del agua (H₂O → O₂)'], c: 3, ex: 'Fotoquímica = en TILACOIDES. Fotólisis del agua libera O₂. La fijación de CO₂ es en estroma (Calvin). ▸ Por qué las otras están mal: (A) (B) Krebs es respiración; (C) fijación de CO₂ es en estroma.'},
  {st: '¿Dónde ocurre la GLUCÓLISIS en eucariotas?', opts: ['Matriz mitocondrial', 'Membrana interna mitocondrial', 'Citosol', 'Núcleo'], c: 2, ex: 'Glucólisis: CITOSOL (pre-mitocondria evolutivamente). No requiere O₂ ni organelas. Si hay O₂ después, el pirúvico entra a mitocondria. ▸ Por qué las otras están mal: (A) (B) Krebs y cadena respiratoria; (D) núcleo es para ADN.'},
  {st: 'En respiración aeróbica, el aceptor FINAL de electrones de la cadena es:', opts: ['NAD+', 'FAD', 'O₂', 'CO₂'], c: 2, ex: 'O₂ recibe electrones al final + H+ → H₂O. Sin O₂, cadena se detiene, no hay fosforilación oxidativa. Por eso respiramos. ▸ Por qué las otras están mal: (A) (B) son intermediarios (transportadores); (D) producto del ciclo de Krebs, no aceptor.'}
]);

/* =================== SEGUNDO PARCIAL =================== */

registerExercises('biologia', '9', [
  {st: '¿Qué estructura del núcleo está formada por DOS membranas concéntricas con poros?', opts: ['Lámina nuclear', 'Envoltura nuclear (carioteca)', 'Nucléolo', 'Cromatina'], c: 1, ex: 'La carioteca tiene 2 membranas (interna + externa); la externa se continúa con el REG y tiene ribosomas. Los poros nucleares regulan el tráfico. ▸ Por qué las otras están mal: (A) lámina es filamentos proteicos por dentro; (C) nucléolo NO tiene membrana; (D) cromatina es ADN + histonas.'},
  {st: 'El nucléolo se caracteriza por:', opts: ['Estar rodeado por membrana propia', 'Ser donde se sintetiza el ARN ribosomal y se ensamblan las subunidades ribosomales', 'Contener las histonas listas para usar', 'Ser donde se duplica el ADN'], c: 1, ex: 'Nucléolo = región densa SIN membrana donde se hace ARNr y se ensamblan subunidades ribosomales. ▸ Por qué las otras están mal: (A) NO tiene membrana; (C) las histonas se sintetizan en el citosol; (D) la replicación es en todo el núcleo durante S.'},
  {st: 'Sobre el transporte por los poros nucleares es CORRECTO:', opts: ['Es siempre por difusión simple', 'Es selectivo y para moléculas grandes es transporte activo que consume GTP', 'Solo entran moléculas, nunca salen', 'Las importinas exportan ARNm al citoplasma'], c: 1, ex: 'Los poros son muy selectivos; la mayoría de moléculas requiere transporte activo con GTP. ▸ Por qué las otras están mal: (A) solo iones y moléc. pequeñas difunden; (C) hay entrada (NLS, importinas) y salida (NES, exportinas); (D) las importinas IMPORTAN, no exportan.'},
  {st: 'La unidad básica de la cromatina es:', opts: ['El cromosoma condensado', 'El solenoide', 'El nucleosoma (ADN + octámero de histonas)', 'La fibra de bucles'], c: 2, ex: 'Nucleosoma = ADN enrollado en un octámero de 8 histonas (2 H2A, 2 H2B, 2 H3, 2 H4). H1 estabiliza. ▸ Por qué las otras están mal: (A) (B) (D) son niveles SUPERIORES de empaquetamiento, no la unidad básica.'},
  {st: 'Comparando eucromatina y heterocromatina:', opts: ['Heterocromatina es laxa y se transcribe activamente', 'Eucromatina es laxa y se transcribe; heterocromatina es condensada y NO se transcribe', 'Ambas tienen el mismo grado de compactación', 'Eucromatina solo existe en procariotas'], c: 1, ex: 'Eucromatina = abierta = activa. Heterocromatina = condensada = silente. ▸ Por qué las otras están mal: (A) lo opuesto; (C) tienen niveles MUY distintos de compactación; (D) procariotas no tienen cromatina como tal.'},
  {st: 'Un cromosoma DUPLICADO típico (después de S) tiene:', opts: ['1 cromátide y 1 centrómero', '2 cromátides hermanas IDÉNTICAS unidas por un centrómero y 4 telómeros', '4 cromátides y 2 centrómeros', '1 cromátide unida a la membrana nuclear'], c: 1, ex: 'Tras S: 2 cromátides hermanas idénticas (= 2 moléculas de ADN), 1 centrómero (donde se unen), 4 telómeros (extremos). ▸ Por qué las otras están mal: descripciones equivocadas.'},
  {st: 'Una célula es 2n=8. ¿Qué significa?', opts: ['Tiene 8 cromosomas SIN agruparse', 'Tiene 2 cromosomas en 8 grupos', 'Tiene 8 cromosomas TOTALES, agrupados en 4 pares de homólogos', 'Es haploide con 8 cromátides'], c: 2, ex: '"2n" = diploide (2 juegos). "8" = total de cromosomas. Si 2n=8 → 4 pares de homólogos. ▸ Por qué las otras están mal: (A) eso sería n=8; (B) sin sentido; (D) si fuera haploide sería n=8.'},
  {st: 'Diferencia entre cromosomas homólogos y cromátides hermanas:', opts: ['Son sinónimos', 'Homólogos: uno del padre, uno de la madre, mismos genes pero pueden tener alelos distintos. Hermanas: dos copias IDÉNTICAS del mismo cromosoma duplicado', 'Homólogos son las copias post-replicación', 'Hermanas vienen una de cada progenitor'], c: 1, ex: 'Homólogos = pareja del mismo cromosoma con origen distinto (alelos pueden diferir). Hermanas = clones por replicación. ▸ Por qué las otras están mal: confusiones típicas de parcial.'}
]);

registerExercises('biologia', '10', [
  {st: '¿Qué es un gen, según la definición actual?', opts: ['Una proteína estructural', 'Una secuencia de ADN que lleva información para sintetizar una proteína O un ARN funcional', 'Cualquier región del ADN', 'Solo las secuencias que codifican enzimas'], c: 1, ex: 'Hoy se considera gen a cualquier secuencia de ADN que dé un producto funcional: proteína O ARN (ARNt, ARNr, ARNnc). ▸ Por qué las otras están mal: (A) los genes no son proteínas; (C) demasiado amplio; (D) demasiado restringido.'},
  {st: 'Durante la transcripción, la enzima ARN polimerasa:', opts: ['Lee la hebra molde de 5\' a 3\' y sintetiza ARN de 3\' a 5\'', 'Lee la hebra molde de 3\' a 5\' y sintetiza ARN de 5\' a 3\'', 'Usa desoxirribonucleótidos como sustrato', 'Necesita un cebador de ARN para empezar'], c: 1, ex: 'ARN pol: lee 3\'→5\', sintetiza 5\'→3\'. Usa RIBOnucleótidos trifosfatados, no desoxi. NO necesita cebador. ▸ Por qué las otras están mal: (A) direcciones invertidas; (C) eso es la ADN pol; (D) eso es la ADN pol.'},
  {st: 'En el ARN, la base que reemplaza a la timina del ADN es:', opts: ['Adenina', 'Citosina', 'Uracilo', 'Guanina'], c: 2, ex: 'ADN: A T G C. ARN: A U G C. La T se reemplaza por U. Pareja A-U en transcripción. ▸ Por qué las otras están mal: A, G, C están en ambos ácidos nucleicos.'},
  {st: 'En la transcripción, los sustratos son:', opts: ['Aminoácidos', 'Desoxirribonucleótidos trifosfatados (dATP, dTTP, dGTP, dCTP)', 'Ribonucleósidos trifosfatados (ATP, UTP, GTP, CTP)', 'Solo ATP'], c: 2, ex: 'Para hacer ARN se usan ribonucleósidos trifosfatados: ATP, UTP, GTP, CTP. Aportan los nucleótidos Y la energía. ▸ Por qué las otras están mal: (A) son para traducción; (B) son para REPLICACIÓN del ADN; (D) hacen falta los 4.'},
  {st: '¿Cuál de los siguientes es un proceso de maduración del ARNm en eucariotas?', opts: ['Capping en 5\'', 'Adición de cola poli-A en 3\'', 'Splicing (eliminación de intrones)', 'Todas las anteriores'], c: 3, ex: 'El pre-ARNm sufre 3 modificaciones en el núcleo antes de salir: capping (5\'), poli-A (3\') y splicing. ▸ Por qué las otras están mal: cada una sola es incompleta.'},
  {st: 'En un gen eucariota, los intrones:', opts: ['Codifican proteínas que se ensamblan a las del exón', 'Son secuencias no codificantes que se eliminan durante el splicing del ARNm', 'Se traducen pero no se transcriben', 'Solo existen en procariotas'], c: 1, ex: 'Intrones = "intra-génicos" no codificantes. Se transcriben pero se sacan del pre-ARNm en el splicing. Solo los EXONES (codificantes) quedan en el ARNm maduro. ▸ Por qué las otras están mal: (A) no codifican; (C) se transcriben y luego se eliminan; (D) son típicos de eucariotas, no de procariotas.'},
  {st: 'En procariotas, la traducción es CO-TRANSCRIPCIONAL porque:', opts: ['Tienen núcleo que separa ambos procesos', 'No hay membrana nuclear: mientras se transcribe el ARNm, ya se traduce', 'No hay ARNm en procariotas', 'No tienen ribosomas'], c: 1, ex: 'Sin núcleo, transcripción y traducción ocurren en el mismo lugar al mismo tiempo (citoplasma). En eucariotas son post-transcripcionales (núcleo separa). ▸ Por qué las otras están mal: descripciones falsas.'},
  {st: 'El splicing ALTERNATIVO permite:', opts: ['Que cada gen produzca solo una proteína', 'Generar varias proteínas distintas a partir de un mismo pre-ARNm (cambiando qué exones se empalman)', 'Que se transcriba todo el ADN', 'Eliminar los exones del ARN'], c: 1, ex: 'Splicing alternativo elige distintas combinaciones de exones → varias proteínas de un mismo gen. Por eso 20.000 genes → 90.000 proteínas en humanos. ▸ Por qué las otras están mal: (A) lo opuesto; (C) no es eso; (D) elimina INTRONES, no exones.'}
]);

registerExercises('biologia', '11', [
  {st: '¿Cuántos codones tiene el código genético y cuántos son STOP?', opts: ['20 codones, 3 son STOP', '64 codones en total, 61 codifican aminoácidos y 3 son STOP', '64 codones, todos codifican aminoácidos', '4 codones (uno por base)'], c: 1, ex: '4³=64 combinaciones. 61 codifican aminoácidos. 3 son STOP: UAA, UAG, UGA. ▸ Por qué las otras están mal: (A) 20 son aminoácidos; (C) hay 3 STOP; (D) cuenta de a uno, no de a tres.'},
  {st: 'El codón de INICIO de la traducción es:', opts: ['UAA', 'AUG (codifica para metionina)', 'GCC', 'TAC (codifica para tirosina)'], c: 1, ex: 'AUG inicia toda traducción y codifica para metionina. UAA es STOP. TAC tiene T = sería ADN no ARN. ▸ Por qué las otras están mal: (A) STOP; (C) codifica para alanina, no inicia; (D) tiene T, no existe en ARN.'},
  {st: '"El código genético es DEGENERADO" significa:', opts: ['Distintos codones pueden codificar el mismo aminoácido', 'Es ambiguo: un codón puede codificar varios aminoácidos', 'Tiene errores', 'No es universal'], c: 0, ex: 'Degenerado = redundante = varios codones sinónimos. Ej: CCA, CCC, CCU, CCG = todos prolina. ▸ Por qué las otras están mal: (B) lo opuesto (es específico, NO ambiguo); (C) tiene mucha eficiencia; (D) sí es universal.'},
  {st: 'Durante la traducción, ¿dónde llega el ARNt cargado con su aminoácido?', opts: ['Sitio P del ribosoma', 'Sitio A del ribosoma', 'Citosol libre', 'Lisosoma'], c: 1, ex: 'Sitio A (aminoacilo) = donde llega el nuevo ARNt cargado. Sitio P (peptidilo) = donde está la cadena creciente. ▸ Por qué las otras están mal: (A) el ARNt iniciador llega al P, los demás al A; (C) (D) no son sitios de traducción.'},
  {st: 'Si el codón del ARNm es 5\'-AUG-3\', el anticodón del ARNt es:', opts: ['5\'-AUG-3\'', '5\'-UAC-3\'', '3\'-UAC-5\'', '5\'-TAC-3\''], c: 2, ex: 'Anticodón es complementario Y antiparalelo: codón 5\'AUG3\' → anticodón 3\'UAC5\' (= 5\'CAU3\'). ▸ Por qué las otras están mal: (A) igual al codón; (B) misma dirección que codón; (D) tiene T (sería ADN).'},
  {st: 'Una inserción de un nucleótido en el ADN genera, con frecuencia:', opts: ['Una proteína idéntica', 'Cambio en el marco de lectura del ARN y proteína completamente distinta', 'Solo cambia un aminoácido', 'No tiene ningún efecto'], c: 1, ex: 'Insertar/eliminar un nucleótido CORRE el marco de lectura: todos los codones siguientes cambian. Suele dar proteína no funcional. ▸ Por qué las otras están mal: (A) (C) eso sería una sustitución silenciosa; (D) suele tener efecto grave.'},
  {st: 'Una proteína que será SECRETADA por exocitosis comienza su síntesis en:', opts: ['Ribosomas libres y se queda en el citosol', 'Ribosomas libres y se transporta a la mitocondria', 'Ribosomas libres pero al detectarse un péptido señal hidrofóbico se transporta al REG y continúa allí', 'Directamente en el aparato de Golgi'], c: 2, ex: 'Todas las proteínas inician en ribosomas libres. Si los primeros aminoácidos forman un péptido SEÑAL hidrofóbico → el ribosoma se acopla al REG → continúa síntesis ahí → Golgi → vesícula → exocitosis. ▸ Por qué las otras están mal: (A) (B) sin péptido señal; (D) Golgi no sintetiza, procesa.'},
  {st: 'Las proteínas que actúan en el CITOSOL o en la MITOCONDRIA se sintetizan:', opts: ['En ribosomas del REG', 'En ribosomas libres del citosol (no presentan péptido señal hidrofóbico)', 'En el aparato de Golgi', 'En el lisosoma'], c: 1, ex: 'Sin péptido señal hidrofóbico → ribosomas libres. Destinos: citosol, núcleo, mitocondrias, peroxisomas, cloroplastos. ▸ Por qué las otras están mal: (A) REG es para proteínas con péptido señal (membrana, secreción, lisosomas); (C) (D) no hacen síntesis.'}
]);

registerExercises('biologia', '12', [
  {st: 'Una neurona y una célula epitelial son tan distintas pero comparten:', opts: ['Distinto ADN, distintos genes', 'El mismo ADN, pero expresan genes diferentes', 'Distintos cromosomas', 'No comparten nada'], c: 1, ex: 'Todas las células somáticas de un organismo tienen el MISMO ADN. La diferenciación se debe a expresión génica diferencial: distintos patrones de genes activos. ▸ Por qué las otras están mal: (A) (C) tienen el MISMO genoma; (D) comparten todo el ADN.'},
  {st: 'La METILACIÓN del ADN generalmente:', opts: ['Activa la transcripción del gen', 'Silencia al gen y condensa la cromatina (regulación epigenética)', 'Reemplaza al ADN por ARN', 'Solo ocurre en procariotas'], c: 1, ex: 'Metilación del ADN (CH₃) → silenciamiento + condensación a heterocromatina. La acetilación de histonas ACTIVA. ▸ Por qué las otras están mal: (A) acetilación activa, metilación silencia; (C) absurdo; (D) es típica de eucariotas.'},
  {st: 'El splicing ALTERNATIVO permite que:', opts: ['Los intrones se traduzcan', 'Un mismo gen genere varias proteínas distintas eligiendo qué exones empalmar', 'Se eliminen los exones', 'Solo ocurre en procariotas'], c: 1, ex: 'Splicing alternativo = distintas combinaciones de exones → variantes proteicas. Explica por qué 20.000 genes humanos hacen 90.000 proteínas. ▸ Por qué las otras están mal: (A) los intrones no se traducen; (C) elimina INTRONES; (D) solo en eucariotas.'},
  {st: 'En el operón LAC de E. coli, EN AUSENCIA de lactosa:', opts: ['Se transcriben las enzimas de degradación de lactosa', 'El represor se une al operador e impide la transcripción', 'La lactosa se sintetiza activamente', 'El ADN se replica'], c: 1, ex: 'Sin lactosa: represor unido al operador → bloquea ARN pol → genes silenciados. Tiene sentido: no hace falta fabricar las enzimas si no hay sustrato. ▸ Por qué las otras están mal: (A) lo opuesto; (C) las bacterias no SINTETIZAN lactosa; (D) la replicación es otro proceso.'},
  {st: '¿Qué hace la LACTOSA cuando aparece en el medio de una bacteria con operón lac?', opts: ['Inhibe la transcripción de los genes lac', 'Se une al represor, lo despega del operador y permite la transcripción de las enzimas', 'Sintetiza glucosa', 'Inhibe la ARN polimerasa'], c: 1, ex: 'Lactosa = INDUCTOR: se une al represor, lo desactiva, libera el operador. ARN pol puede ahora transcribir los genes que codifican enzimas para degradar la lactosa. ▸ Por qué las otras están mal: (A) lo opuesto; (C) no la sintetiza, la degrada; (D) la libera, no la inhibe.'},
  {st: 'El ARNm policistrónico (que codifica varias proteínas) es típico de:', opts: ['Eucariontes', 'Procariontes (los operones)', 'Virus solamente', 'No existe'], c: 1, ex: 'Procariotas → operones → ARNm policistrónico (1 ARNm con varias proteínas). Eucariotas: 1 gen = 1 ARNm = 1 proteína (en general). ▸ Por qué las otras están mal: (A) eucariotas son monocistrónicos; (C) (D) sí existen, en procariotas.'},
  {st: '¿Qué proteína marca a otras proteínas para que sean degradadas en el proteasoma?', opts: ['Quinasa', 'Chaperona', 'Ubiquitina', 'Helicasa'], c: 2, ex: 'Ubiquitina = etiqueta que dirige proteínas dañadas o ya innecesarias al proteasoma para hidrólisis. ▸ Por qué las otras están mal: (A) fosforilan; (B) ayudan al plegamiento; (D) abre el ADN en la replicación.'}
]);

registerExercises('biologia', '13', [
  {st: 'El orden CORRECTO de las subfases de la interfase es:', opts: ['M → G1 → S', 'G1 → S → G2', 'S → G1 → G2', 'G2 → S → G1'], c: 1, ex: 'Interfase: G1 (crecimiento) → S (síntesis/replicación de ADN) → G2 (preparación división). Luego viene la fase M (mitosis + citocinesis). ▸ Por qué las otras están mal: orden incorrecto.'},
  {st: 'Una célula en G0:', opts: ['Está en mitosis activa', 'Está fuera del ciclo, no se divide (ej: neuronas, fibras musculares)', 'Acaba de duplicar su ADN', 'Es una célula tumoral'], c: 1, ex: 'G0 = células que abandonan el ciclo y no se dividen. Ej: neuronas adultas, miocitos esqueléticos. ▸ Por qué las otras están mal: (A) opuesto; (C) eso es G2; (D) las tumorales se dividen DEMASIADO (lo opuesto a G0).'},
  {st: 'Si una célula es 2n=6 en G2, ¿cuántas cromátides totales tiene?', opts: ['6', '12 (6 cromosomas × 2 cromátides cada uno)', '3', '24'], c: 1, ex: 'En G1: 6 cromosomas con 1 cromátide = 6 cromátides. Tras S: cada cromosoma duplicado tiene 2 cromátides hermanas. En G2: 6 cromosomas × 2 = 12 cromátides totales. ▸ Por qué las otras están mal: cuentan mal.'},
  {st: 'El punto de control de G1 verifica principalmente:', opts: ['Que el ADN se haya duplicado correctamente', 'Tamaño celular, nutrientes y daños al ADN antes de comprometerse a la división', 'Que el huso mitótico esté formado', 'Que la mitosis haya terminado'], c: 1, ex: 'G1 checkpoint: ¿tengo tamaño? ¿nutrientes? ¿ADN sin daños? ¿señales externas? Decide si entra a S o va a G0. ▸ Por qué las otras están mal: (A) es el checkpoint de G2; (C) es el checkpoint M; (D) el M chequea alineación, no terminación.'},
  {st: 'Los factores promotores del ciclo celular (FPS, FPM) están formados por:', opts: ['Solo una enzima quinasa', 'Solo una ciclina', 'Una quinasa (Cdk) + una ciclina reguladora', 'ATP y GTP'], c: 2, ex: 'Quinasa sola = inactiva. Ciclina sola = inerte. Solo el COMPLEJO quinasa-ciclina es activo (factor promotor) y puede fosforilar proteínas para avanzar el ciclo. ▸ Por qué las otras están mal: (A) (B) ninguno por sí solo funciona; (D) son moléculas energéticas.'},
  {st: 'La replicación del ADN es SEMICONSERVATIVA porque:', opts: ['Cada nueva molécula de ADN tiene una hebra vieja (molde) y una hebra nueva', 'Conserva solo una de las dos moléculas originales', 'Se conservan las dos moléculas originales completas', 'No conserva nada'], c: 0, ex: 'Semiconservativa: tras replicación, cada doble hélice nueva tiene 1 hebra original + 1 hebra recién sintetizada. ▸ Por qué las otras están mal: (B) es "dispersiva"; (C) es "conservativa" (descartada); (D) absurdo.'},
  {st: 'La enzima ADN polimerasa necesita un CEBADOR porque:', opts: ['No puede leer la hebra molde sin él', 'No puede INICIAR una cadena de cero, solo agregar nucleótidos a un OH 3\' libre', 'El cebador la activa enzimáticamente', 'El cebador es el sustrato principal'], c: 1, ex: 'ADN pol solo PROLONGA. Necesita un primer (cebador de ARN) que ofrezca un OH 3\' libre para empezar. Luego se elimina y se reemplaza por ADN. ▸ Por qué las otras están mal: (A) sí puede leer; (C) (D) descripciones erróneas.'},
  {st: 'Comparando replicación y transcripción:', opts: ['Ambas usan los mismos sustratos', 'Replicación copia AMBAS hebras del ADN; transcripción copia SOLO UNA hebra de un gen', 'Transcripción es bidireccional desde un ORI', 'Replicación produce ARN'], c: 1, ex: 'Replicación: duplica TODO el ADN (las 2 hebras). Transcripción: copia 1 hebra molde de un GEN puntual a ARN. ▸ Por qué las otras están mal: (A) replicación usa desoxinucleótidos, transcripción ribonucleótidos; (C) la transcripción es UNIdireccional desde el +1; (D) replicación produce ADN.'},
  {st: 'La proteína p53 ("guardián del genoma") cuando detecta daño en el ADN:', opts: ['Acelera la división para diluir el daño', 'Detiene el ciclo para reparar y, si el daño es irreparable, induce apoptosis', 'No tiene efecto sobre el ciclo celular', 'Activa la replicación del ADN dañado'], c: 1, ex: 'p53 es un supresor de tumores: frena el ciclo en el checkpoint para dar tiempo a reparar; si no se puede reparar, induce apoptosis (muerte programada). Si p53 está mutado, la célula se divide con ADN dañado → tumores (mutada en muchísimos cánceres). ▸ Por qué las otras están mal: (A) (D) lo opuesto a su función protectora; (C) sí actúa, es el control clave del daño.'}
]);

registerExercises('biologia', '14', [
  {st: 'La mitosis se produce en:', opts: ['Células germinales (gónadas)', 'Células somáticas (no germinales)', 'Solo en procariotas', 'Solo en gametas'], c: 1, ex: 'Mitosis: división de células somáticas (crecimiento, reparación). Meiosis: solo células germinales para formar gametas. ▸ Por qué las otras están mal: (A) (D) eso es meiosis; (C) procariotas hacen fisión binaria.'},
  {st: 'Al final de la mitosis, las células hijas son:', opts: ['Genéticamente DISTINTAS de la madre', '2 células IDÉNTICAS a la madre con la misma ploidía', '4 células haploides', 'Células sin núcleo'], c: 1, ex: 'Mitosis: 1 célula 2n → 2 células 2n GENÉTICAMENTE IDÉNTICAS. Meiosis: 1 célula 2n → 4 células n distintas. ▸ Por qué las otras están mal: (A) eso es meiosis; (C) eso es meiosis; (D) los glóbulos rojos pierden núcleo pero no es resultado normal de mitosis.'},
  {st: 'En la METAFASE de la mitosis, los cromosomas:', opts: ['Empiezan a condensarse', 'Se alinean en el plano ecuatorial; están MÁXIMAMENTE condensados (por eso se hacen cariotipos aquí)', 'Se separan hacia los polos', 'Se descondensan'], c: 1, ex: 'Metafase: alineación en placa metafásica + máxima condensación. Por eso los cariotipos se obtienen de células en metafase. ▸ Por qué las otras están mal: (A) eso es profase; (C) eso es anafase; (D) eso es telofase.'},
  {st: 'En la ANAFASE I de la MEIOSIS se separan:', opts: ['Cromátides hermanas', 'Los cromosomas HOMÓLOGOS (las cromátides hermanas siguen juntas)', 'Los centríolos', 'Los nucleolos'], c: 1, ex: 'Meiosis I es REDUCCIONAL: separa homólogos → de 2n a n. Las cromátides hermanas se separan en anafase II. ▸ Por qué las otras están mal: (A) eso es anafase II (o anafase mitótica); (C) (D) no son lo que se separa.'},
  {st: 'El CROSSING OVER ocurre en:', opts: ['Profase de la mitosis', 'Profase I de la meiosis: intercambio de fragmentos entre cromosomas homólogos', 'Anafase II', 'Citocinesis'], c: 1, ex: 'Crossing over (entrecruzamiento) = intercambio de fragmentos entre cromátides NO hermanas de homólogos. Es la principal fuente de variabilidad genética. ▸ Por qué las otras están mal: (A) en mitosis NO hay; (C) (D) tampoco.'},
  {st: 'En un cruzamiento Aa × Aa (A domina sobre a), la proporción FENOTÍPICA esperada en la F2 es:', opts: ['1 A : 1 a', '3 dominante : 1 recesivo', '1 : 1 : 1 : 1', '9 : 3 : 3 : 1'], c: 1, ex: 'Aa × Aa: gametas A y a de cada uno. Punnett: AA, Aa, Aa, aa = genotipos 1:2:1. Fenotipos: AA y Aa expresan A (dominante), aa expresa a → 3:1. ▸ Por qué las otras están mal: (A) no contempla dominancia; (C) 4 categorías sin sentido; (D) eso es dihíbrido (2 caracteres).'},
  {st: 'Si un individuo es HETEROCIGOTA para el gen del color de ojos (Aa):', opts: ['Tiene dos alelos iguales', 'Tiene dos alelos distintos (uno dominante, otro recesivo) y expresa el dominante', 'Tiene un solo alelo', 'Solo puede producir gametas con A'], c: 1, ex: 'Heterocigota = alelos distintos (Aa). Expresa el dominante. Produce gametas A y a en proporción 50:50. ▸ Por qué las otras están mal: (A) eso es homocigota; (C) tiene 2 alelos; (D) produce ambos tipos.'},
  {st: 'La fuente PRINCIPAL de variabilidad genética en la meiosis NO es:', opts: ['El crossing over en profase I', 'La distribución independiente de homólogos en anafase I', 'La replicación del ADN en S (es muy precisa)', 'La fecundación posterior (combinación de gametas)'], c: 2, ex: 'La replicación es muy fiel: NO genera variabilidad. Variabilidad: crossing over + distribución independiente + fecundación. ▸ Por qué las otras están mal: (A) (B) (D) sí son fuentes de variabilidad.'},
  {st: 'En la ovogénesis humana, a partir de UNA ovogonia se obtiene:', opts: ['4 óvulos viables', '1 óvulo viable y 2 o 3 cuerpos polares que degeneran', '2 óvulos y 2 espermatozoides', '4 cuerpos polares'], c: 1, ex: 'Ovogénesis: citocinesis DESIGUAL (todo el citoplasma a una sola célula). 1 ovogonia → 1 óvulo grande + cuerpos polares pequeños que mueren. En espermatogénesis sí se obtienen 4 espermatozoides. ▸ Por qué las otras están mal: descripciones equivocadas.'},
  {st: 'La meiosis en el ovocito humano se DETIENE en:', opts: ['Anafase I y telofase II', 'Profase I (desde la vida intrauterina hasta la pubertad) y metafase II (hasta que haya fecundación)', 'No tiene detenciones', 'Solo se detiene en telofase II'], c: 1, ex: 'Ovogénesis tiene 2 detenciones largas: profase I durante años (desde el 5to mes intrauterino) y metafase II (que se completa SOLO si hay fecundación). ▸ Por qué las otras están mal: descripciones erróneas.'},
  {st: 'Diferencia entre DOMINANCIA INCOMPLETA y CODOMINANCIA:', opts: ['Son sinónimos', 'Incompleta: fenotipo intermedio (rojo + blanco = rosa). Codominancia: ambos alelos se expresan a la vez con la misma intensidad (grupo sanguíneo AB)', 'Codominancia da fenotipo intermedio', 'Solo existen en plantas'], c: 1, ex: 'Incompleta: el heterocigota muestra un fenotipo MEZCLADO/intermedio. Codominancia: muestra LOS DOS al mismo tiempo, distinguibles. Ej clásico: grupo AB tiene antígenos A y B en su glóbulo rojo, no "uno intermedio". ▸ Por qué las otras están mal: confusiones típicas.'},
  {st: 'En el sistema sanguíneo ABO, una persona del grupo AB tiene genotipo:', opts: ['I^A I^A', 'I^A I^B (codominancia: expresa antígeno A y B en la misma membrana)', 'ii', 'Solo I^A'], c: 1, ex: 'Grupo AB = un alelo I^A + un alelo I^B; ambos son codominantes y se expresan simultáneamente. Grupo 0 = ii (recesivo, sin antígeno). ▸ Por qué las otras están mal: (A) sería grupo A; (C) sería grupo 0; (D) sin sentido.'},
  {st: 'Querés saber si un ratón negro es AA o Aa. ¿Qué cruce hacés (cruzamiento prueba)?', opts: ['AA × AA', 'Aa × Aa', 'Cruzarlo con un homocigota recesivo (aa). Si aparecen descendientes grises, era Aa; si todos son negros, era AA', 'No se puede saber'], c: 2, ex: 'Cruzamiento prueba/retrocruza: × aa. Si era AA → todas Aa (100% negro). Si era Aa → 50% Aa (negro) + 50% aa (gris). Aparición de UN solo gris ya delata heterocigota. ▸ Por qué las otras están mal: no permiten distinguir.'},
  {st: 'Un varón se dice HEMICIGOTA para un gen ligado al X porque:', opts: ['Tiene 2 alelos del gen', 'Tiene UN SOLO alelo (en su único X); el cromosoma Y no tiene el gen', 'Tiene el gen duplicado', 'No tiene el gen'], c: 1, ex: 'Hemicigota = un solo alelo presente. Los varones XY tienen un solo X → expresan cualquier alelo del X, aunque sea recesivo. Por eso enfermedades como hemofilia y daltonismo son más frecuentes en varones. ▸ Por qué las otras están mal: descripciones falsas.'},
  {st: 'Un padre daltónico (X^d Y) tiene hijos con una madre sana NO portadora (X^D X^D). ¿Qué hijos esperás?', opts: ['Todos los varones daltónicos', 'Todas las hijas daltónicas', 'Hijos varones SANOS (heredan Y del padre y X^D de la madre); todas las hijas SANAS PORTADORAS (X^d del padre + X^D de la madre)', '50% varones daltónicos'], c: 2, ex: 'X^d Y × X^D X^D: hijos varones heredan Y del padre + X^D de la madre = X^D Y (SANOS). Hijas heredan X^d del padre + X^D de la madre = X^D X^d (sanas portadoras). El padre daltónico NO transmite el alelo a sus hijos varones (les pasa Y), pero SÍ a todas sus hijas como portadoras. ▸ Por qué las otras están mal: descripciones equivocadas.'},
  {st: 'La NO-DISYUNCIÓN durante la meiosis puede producir:', opts: ['Gametas con la cantidad normal de cromosomas', 'Gametas con cromosomas de más o de menos → cigotos con aneuploidías como trisomía 21 (Down)', 'Cuerpos polares funcionales', 'Más variabilidad genética útil'], c: 1, ex: 'No-disyunción: los cromosomas (homólogos en anafase I, o cromátides en anafase II) NO se separan bien. Resultado: una gameta con un cromosoma de más, otra con uno de menos. Si se fecunda → trisomía 21 (Down), monosomía X (Turner), XXY (Klinefelter), etc. ▸ Por qué las otras están mal: descripciones erróneas.'}
]);

registerExercises('biologia', '15', [
  {st: '¿Quién o qué evoluciona?', opts: ['El individuo a lo largo de su vida', 'Las poblaciones a lo largo de las generaciones (cambia la frecuencia de alelos)', 'Las moléculas dentro de una célula', 'Las especies en un solo individuo'], c: 1, ex: 'La evolución ocurre en POBLACIONES, no en individuos. Es el cambio en frecuencias de alelos generación tras generación. ▸ Por qué las otras están mal: (A) individuos no evolucionan; (C) no es escala; (D) requiere población.'},
  {st: 'Para Darwin, la SELECCIÓN NATURAL requiere:', opts: ['Que los individuos quieran cambiar', 'Variabilidad heredable + sobreproducción + selección diferencial (los más aptos dejan más descendencia)', 'Solo mutaciones beneficiosas', 'Que el ambiente sea estable'], c: 1, ex: 'Selección natural: 1) variabilidad, 2) herencia, 3) sobreproducción, 4) selección diferencial → cambian frecuencias de alelos. ▸ Por qué las otras están mal: (A) no hay voluntad; (C) las mutaciones son al azar; (D) el cambio ambiental impulsa selección.'},
  {st: 'La principal fuente de variabilidad genética en la teoría sintética es:', opts: ['La fotosíntesis', 'La mutación (cambios al azar en el ADN)', 'La respiración celular', 'El metabolismo'], c: 1, ex: 'Mutación = fuente primaria de variabilidad genética. Recombinación, flujo génico, deriva génica reorganizan y modifican esa variabilidad. La selección natural FILTRA, no genera. ▸ Por qué las otras están mal: no tienen que ver con variabilidad.'},
  {st: 'Las mutaciones genéticas son:', opts: ['Dirigidas por las necesidades del individuo', 'Eventos al AZAR; la selección natural luego favorece a las que sirven en el ambiente actual', 'Siempre beneficiosas', 'Siempre dañinas'], c: 1, ex: 'Las mutaciones son aleatorias, no dirigidas. La selección natural NO es al azar: filtra lo aleatorio según ventajas adaptativas. ▸ Por qué las otras están mal: (A) no son dirigidas; (C) (D) hay benef., neutras y dañinas.'},
  {st: 'La TEORÍA ENDOSIMBIÓTICA (Lynn Margulis) explica el origen de:', opts: ['Los virus', 'Las mitocondrias y cloroplastos (a partir de procariotas englobadas que se quedaron como simbiontes)', 'El núcleo eucariota', 'Los priones'], c: 1, ex: 'Una eucariota ancestral englobó procariotas aerobias → mitocondrias. Otra englobó cianobacterias → cloroplastos. Evidencia: doble membrana, ADN circular propio, ribosomas 70S, fisión binaria. ▸ Por qué las otras están mal: (A) (C) (D) no las explica esta teoría.'},
  {st: '¿Qué evidencia apoya la teoría endosimbiótica?', opts: ['Mitocondrias tienen ADN circular propio y ribosomas tipo procariota 70S', 'Mitocondrias son organelas membranosas', 'Mitocondrias hacen fotosíntesis', 'Mitocondrias se sintetizan en el REG'], c: 0, ex: 'Mitocondrias y cloroplastos tienen: ADN circular propio, ribosomas 70S (como bacterias), doble membrana, dividen por fisión binaria. Todo apunta a un origen procariota. ▸ Por qué las otras están mal: (B) muy general; (C) las mitocondrias NO fotosintetizan; (D) se hacen por fisión binaria.'},
  {st: 'La ESPECIACIÓN ALOPÁTRICA requiere:', opts: ['Una barrera geográfica que separe poblaciones, que luego evolucionan independientemente', 'Que las dos poblaciones convivan en el mismo lugar', 'Que no haya variabilidad genética', 'Solo cambios cromosómicos'], c: 0, ex: 'Alopátrica = "otra patria": barrera geográfica (montaña, río) → aislamiento → evolución divergente → aislamiento reproductivo → especies distintas. La simpátrica es sin barrera geográfica. ▸ Por qué las otras están mal: (B) eso es simpátrica; (C) (D) descripciones equivocadas.'},
  {st: 'La SELECCIÓN NATURAL:', opts: ['Genera variabilidad genética', 'NO genera variabilidad: la filtra, favoreciendo a los más adaptados al ambiente actual', 'Solo actúa en bacterias', 'Solo actúa sobre caracteres adquiridos en vida'], c: 1, ex: 'Selección natural = filtro: no inventa variabilidad, elige entre la que existe (generada por mutación y recombinación). Favorece a los más aptos al ambiente. ▸ Por qué las otras están mal: (A) las que generan son mutación/recombinación; (C) actúa en todos los seres vivos; (D) los caracteres adquiridos NO se heredan (eso era Lamarck).'}
]);
