registerExercises('biologia', '1', [
  {st: '¿Cuál de los siguientes ítems corresponde a tres características de TODOS los seres vivos?', opts: ['Metabolismo, evolución, irritabilidad', 'Mitosis, homeostasis, metabolismo', 'Crecimiento, respiración aeróbica, reproducción', 'Fotosíntesis, irritabilidad, homeostasis'], c: 0, ex: 'Metabolismo, evolución (a nivel poblacional) e irritabilidad las cumplen TODOS los seres vivos. La mitosis NO (procariotas se dividen por fisión binaria); la respiración aeróbica NO (anaerobios estrictos no la hacen); la fotosíntesis NO (solo autótrofos).'},
  {st: 'La homeostasis se refiere a:', opts: ['La capacidad de reproducirse de manera constante', 'Mantener el medio interno relativamente constante a pesar de los cambios externos', 'La síntesis de moléculas orgánicas', 'Cambiar de forma según el ambiente'], c: 1, ex: 'Homeostasis = mantenimiento de un medio interno estable (temperatura, pH, glucemia, osmolaridad, etc.) frente a variaciones externas. Ejemplo: liberar insulina al consumir azúcar para regular la glucemia.'},
  {st: 'Ordenar de menor a mayor los siguientes niveles de organización: Nitrógeno – aminoácido – enzima – célula – hígado.', opts: ['Enzima – célula – nitrógeno – hígado – aminoácido', 'Célula – nitrógeno – hígado – enzima – aminoácido', 'Nitrógeno – aminoácido – enzima – célula – hígado', 'Hígado – enzima – célula – aminoácido – nitrógeno'], c: 2, ex: 'De menor a mayor complejidad: nitrógeno (átomo) → aminoácido (molécula) → enzima (proteína = macromolécula) → célula → hígado (órgano).'},
  {st: '¿Cuál de las siguientes situaciones se vincula al concepto de homeostasis?', opts: ['En una laguna con bajo oxígeno los aerobios mueren por no respirar', 'Al aumentar nutrientes en cultivo, las células se reproducen ilimitadamente', 'En ausencia de luz prolongada los girasoles se marchitan', 'Al consumir una golosina se libera insulina y se regula la glucemia'], c: 3, ex: 'La regulación de glucemia por insulina es el ejemplo clásico de homeostasis: el cuerpo mantiene la glucosa en sangre dentro de un rango estable a pesar del input variable.'},
  {st: '¿Cuántos dominios biológicos se reconocen?', opts: ['2 (procariota y eucariota)', '3 (Bacteria, Archaea y Eukarya)', '5 (Monera, Protista, Fungi, Plantae, Animalia)', '6 (uno por reino)'], c: 1, ex: 'Los 3 dominios son Bacteria, Archaea (ambos procariotas pero con genética distinta) y Eukarya. Los reinos son una clasificación más fina dentro de los dominios.'},
  {st: 'En un ecosistema, los organismos AUTÓTROFOS:', opts: ['Consumen otros organismos para obtener energía', 'Fijan energía solar o química y producen materia orgánica propia', 'Solo descomponen materia muerta', 'No participan de las cadenas tróficas'], c: 1, ex: 'Autótrofos = "se alimentan a sí mismos". Producen materia orgánica a partir de inorgánica (CO<sub>2</sub>) usando energía lumínica (fotoautótrofos: plantas, algas, cianobacterias) o química (quimioautótrofos). Son la base de las cadenas tróficas.'}
]);

registerExercises('biologia', '2', [
  {st: '¿Cuál de las siguientes funciones es exclusiva de células EUCARIONTES?', opts: ['Fotosíntesis', 'Respiración celular', 'Transporte intracelular de vesículas', 'Síntesis de proteínas'], c: 2, ex: 'El transporte intracelular de vesículas requiere endomembranas y citoesqueleto, ambos ausentes en procariotas. Fotosíntesis ocurre en cianobacterias (procariotas); respiración y síntesis de proteínas son universales.'},
  {st: '¿Cuál de los siguientes procesos se da en células EUCARIONTES VEGETALES pero NO en animales?', opts: ['Fijación de CO<sub>2</sub> en los cloroplastos', 'Respiración celular', 'Mitosis y meiosis', 'Transcripción y traducción'], c: 0, ex: 'La fijación de CO<sub>2</sub> requiere cloroplastos, que solo tienen las plantas y algas (no animales ni hongos). Los demás procesos son universales en eucariotas.'},
  {st: 'Indica la opción que represente el nivel SUBCELULAR en un individuo perteneciente al reino vegetal EXCLUSIVAMENTE:', opts: ['Almidón y ADN con histonas', 'Ribosomas y cloroplastos', 'Complejo de Golgi y pared celular de celulosa', 'Cloroplastos y vacuola central'], c: 3, ex: 'Cloroplastos y vacuola central son organelas exclusivas (o muy características) de plantas. La pared NO es subcelular sino estructura externa. Ribosomas y Golgi son universales en eucariotas. ADN con histonas también está en animales.'},
  {st: '¿Cuál es una característica EXCLUSIVA de un organismo PROCARIONTE?', opts: ['Son unicelulares y se dividen por mitosis', 'Pueden reproducirse sexualmente', 'Presentan una molécula de ADN circular no asociada a histonas', 'Presentan una pared de quitina'], c: 2, ex: 'ADN circular sin histonas es típico de procariotas. La mitosis es eucariota (procariotas hacen fisión binaria). Pared de quitina es de hongos. La reproducción sexual es eucariota (procariotas tienen mecanismos de transferencia genética pero no es sexual en sentido estricto).'},
  {st: 'Al comparar células eucariotas y procariotas se puede afirmar que:', opts: ['En procariotas la división es por fisión binaria; en eucariotas, mitosis o meiosis', 'Ambas sintetizan proteínas en ribosomas libres y en el REG', 'Las eucariotas pueden ser autótrofas o heterótrofas; las procariotas solo heterótrofas', 'La glucólisis ocurre en mitocondrias en eucariotas y en citoplasma en procariotas'], c: 0, ex: 'Procariotas: fisión binaria. Eucariotas: mitosis (somáticas) o meiosis (gaméticas). Procariotas pueden ser autótrofas (cianobacterias). El REG es exclusivo de eucariotas. La glucólisis ocurre en CITOPLASMA en ambas.'},
  {st: '¿Cuál de las siguientes características permite diferenciar una célula PROCARIONTE autótrofa de una EUCARIONTE autótrofa?', opts: ['La presencia de pared celular', 'La permeabilidad selectiva de la membrana', 'La presencia de mitocondrias', 'La presencia de ribosomas'], c: 2, ex: 'Solo las eucariotas tienen mitocondrias (las procariotas hacen respiración en su membrana). Pared celular tienen ambas. La permeabilidad selectiva y los ribosomas son universales.'},
  {st: 'La compartimentalización celular en eucariotas permite:', opts: ['Que las reacciones se mezclen libremente', 'Especializar microambientes (pH, enzimas) para procesos específicos en cada organela', 'Que la célula sea más pequeña', 'Eliminar la necesidad de membrana plasmática'], c: 1, ex: 'La compartimentalización (organelas membranosas) es la innovación clave de las eucariotas: cada compartimento tiene un microambiente especializado. Por ejemplo, lisosomas con pH 4.5 para digestión, mitocondrias con gradientes para producir ATP.'}
]);

registerExercises('biologia', '3', [
  {st: 'Si a partir de un tejido afectado se aísla una partícula infecciosa SOLO conformada por proteínas, podría tratarse de:', opts: ['Un viroide', 'Un virus', 'Un prion', 'Un retrovirus'], c: 2, ex: 'Priones = solo proteína mal plegada (sin ácido nucleico). Virus = ácido nucleico + cápside. Viroide = solo ARN. Retrovirus = virus con ARN y transcriptasa inversa.'},
  {st: '¿Cuál afirmación sobre los virus es CORRECTA?', opts: ['Pueden sintetizar sus propias proteínas porque tienen material genético y ribosomas', 'Requieren ribosomas celulares para sintetizar las proteínas virales', 'La cápside es una membrana que les permite intercambio con el medio', 'En los ciclos líticos, el ADN viral se integra al ADN celular'], c: 1, ex: 'Los virus NO tienen ribosomas, por eso son parásitos intracelulares obligados. Necesitan los ribosomas celulares. La cápside es proteica (no membrana). El ciclo donde el ADN viral se integra es el LISOGÉNICO, no el lítico.'},
  {st: 'Los viroides son agentes infecciosos que:', opts: ['Tienen cápside proteica', 'Están formados solo por ARN, sin cápside, y afectan plantas', 'Solo afectan al sistema nervioso de animales', 'Son una variante de prion'], c: 1, ex: 'Viroides = ARN circular pequeño SIN cápside, afectan plantas (causan enfermedades agrícolas como la del tubérculo en papa). Los priones (solo proteína) afectan sistema nervioso animal.'},
  {st: 'En un ciclo viral en células eucariontes, el orden general es:', opts: ['Liberación → adsorción → biosíntesis → ensamblaje → entrada', 'Adsorción al receptor → entrada → decapsidación → biosíntesis → ensamblaje → liberación', 'Ensamblaje → adsorción → liberación → biosíntesis', 'Biosíntesis → adsorción → entrada'], c: 1, ex: 'Orden general: 1) adsorción (unión a receptor específico), 2) entrada/penetración (endocitosis o fusión), 3) decapsidación (libera ác. nucleico), 4) biosíntesis (replica + sintetiza proteínas usando maquinaria celular), 5) ensamblaje, 6) liberación (lisis o gemación).'},
  {st: 'Los retrovirus se caracterizan por:', opts: ['Tener doble cadena de ADN', 'Tener ARN y la enzima transcriptasa inversa que convierte su ARN en ADN', 'No tener material genético', 'Solo infectar plantas'], c: 1, ex: 'Retrovirus (ej: VIH) tienen ARN. Su transcriptasa inversa hace ADN a partir del ARN, y ese ADN se integra al genoma del huésped. Por eso son particularmente difíciles de tratar.'},
  {st: 'La diferencia central entre ciclo LÍTICO y LISOGÉNICO es:', opts: ['El lítico ocurre en eucariotas y el lisogénico en procariotas', 'En el lítico se replica y lisa la célula; en el lisogénico el ADN viral se integra al genoma del huésped', 'El lisogénico es más rápido', 'No hay diferencia, son sinónimos'], c: 1, ex: 'Lítico = replicación rápida + lisis (rompe la célula al liberar viriones). Lisogénico = el ADN viral se integra como profago al cromosoma bacteriano y se replica con él silenciosamente, hasta que se induce al ciclo lítico.'},
  {st: '¿Cuál NO es una característica que tengan los virus?', opts: ['Material genético (ADN o ARN)', 'Cápside proteica', 'Ribosomas propios', 'Capacidad de replicarse en una célula huésped'], c: 2, ex: 'Los virus NO tienen ribosomas, por eso necesitan los de la célula huésped para sintetizar sus proteínas. Sí tienen ácido nucleico, cápside y capacidad de replicación intracelular.'}
]);

registerExercises('biologia', '4', [
  {st: 'El ADN y el ARN son ácidos nucleicos que se DIFERENCIAN entre sí por la presencia de:', opts: ['Adenina', 'Bases nitrogenadas', 'Citosina', 'Timina'], c: 3, ex: 'Solo el ADN tiene timina (T). El ARN tiene uracilo (U) en su lugar. Adenina, citosina y guanina están en ambos. Otra diferencia: el azúcar (desoxirribosa en ADN, ribosa en ARN).'},
  {st: '¿En cuál de las siguientes opciones, todas las moléculas tienen función de RESERVA de energía?', opts: ['Glucógeno / triglicéridos / almidón', 'Glucógeno / colágeno / almidón', 'Glucógeno / tubulina / celulosa', 'Celulosa / glucógeno / almidón'], c: 0, ex: 'Reserva: glucógeno (animal), almidón (vegetal), triglicéridos (grasa). Estructurales (NO reserva): colágeno, tubulina, celulosa, queratina.'},
  {st: 'Una proteína con función de receptor está formada por 5 cadenas polipeptídicas. ¿Cuál es el MAYOR nivel estructural que alcanza?', opts: ['Cuaternaria', 'Terciaria', 'Secundaria', 'Primaria'], c: 0, ex: 'La estructura cuaternaria existe solo cuando hay más de una cadena polipeptídica. 5 cadenas = cuaternaria. Si fuera una sola cadena, su mayor nivel sería terciaria.'},
  {st: '¿En cuáles de los siguientes grupos de biomoléculas el producto de su HIDRÓLISIS serán AMINOÁCIDOS?', opts: ['Insulina / colesterol', 'Acilglicérido / bomba de protones', 'Enzimas hidrolíticas lisosomales / glucógeno', 'Hemoglobina / carrier de glucosa'], c: 3, ex: 'Hemoglobina y carrier de glucosa son ambas proteínas → hidrólisis libera aminoácidos. Insulina es proteína pero el colesterol es lípido. Glucógeno = polisacárido (libera glucosa). Bomba de protones es proteína pero el acilglicérido es lípido.'},
  {st: 'En las moléculas biológicas, la energía disponible para el metabolismo se encuentra en:', opts: ['Los enlaces covalentes', 'Las uniones iónicas', 'Los enlaces de puente hidrógeno', 'Los átomos aislados'], c: 0, ex: 'La energía química está principalmente en los enlaces covalentes (especialmente C–C, C–H). Cuando se rompen estos enlaces (oxidación) se libera energía. Los puentes de H y las uniones iónicas tienen mucha menos energía.'},
  {st: 'El nucleótido es la unidad estructural de los ácidos nucleicos. Está formado por:', opts: ['Solo una base nitrogenada', '1 azúcar (pentosa) + 1 base nitrogenada + 1 a 3 grupos fosfato', '2 aminoácidos unidos', '1 ácido graso + glicerol'], c: 1, ex: 'Nucleótido = pentosa (ribosa o desoxirribosa) + base (A, T, G, C, U) + 1-3 fosfatos. El ATP es un nucleótido con adenina, ribosa y 3 fosfatos.'},
  {st: 'Los lípidos anfipáticos que conforman la base estructural de las membranas son:', opts: ['Triglicéridos', 'Fosfolípidos', 'Esteroides', 'Ceras'], c: 1, ex: 'Los fosfolípidos son anfipáticos: cabeza polar (glicerol + fosfato) y dos colas apolares (ácidos grasos). Por eso forman bicapas en agua. Los triglicéridos son apolares (reserva); el colesterol modula fluidez pero no es estructural.'}
]);

registerExercises('biologia', '5', [
  {st: 'Un investigador estudia cómo AUMENTAR la fluidez de las membranas plasmáticas. Los factores que podrían favorecerlo son:', opts: ['Una mayor presencia de colesterol', 'Una mayor cantidad de colas insaturadas en los fosfolípidos', 'Una menor temperatura del medio', 'Un mayor pH del medio'], c: 1, ex: 'Las colas insaturadas tienen dobles enlaces que "doblan" la cadena, impiden el empaquetamiento y aumentan la fluidez. Bajar la temperatura disminuye la fluidez. El colesterol amortigua (a alta T disminuye, a baja T aumenta).'},
  {st: 'Una célula AUMENTA su volumen luego de ser colocada en una solución desconocida. ¿Cuál solución provocó ese resultado?', opts: ['Una solución con la misma concentración que el medio intracelular', 'Una solución 50% más concentrada que el medio intracelular', 'Una solución 2 veces más concentrada que el medio intracelular', 'Una solución 2 veces más diluida que el medio intracelular'], c: 3, ex: 'Si la célula gana volumen, el agua entró → el medio externo es HIPOTÓNICO (menos solutos afuera). Una solución más diluida es hipotónica respecto al interior. Las opciones más concentradas serían hipertónicas y la célula se encogería.'},
  {st: '¿Qué ocurrirá con el transporte de CO<sub>2</sub> si se BLOQUEARAN todas las proteínas de canal de la membrana?', opts: ['El CO<sub>2</sub> requerirá energía para ingresar o salir', 'El CO<sub>2</sub> ingresará o saldrá normalmente por difusión simple', 'El CO<sub>2</sub> no podrá ingresar pero sí salir', 'El CO<sub>2</sub> no podrá salir pero sí ingresar'], c: 1, ex: 'El CO<sub>2</sub> es una molécula pequeña apolar que pasa por DIFUSIÓN SIMPLE a través de la bicapa, sin necesidad de proteínas de canal. Lo mismo pasa con el O<sub>2</sub>.'},
  {st: 'En el proceso de comunicación celular, el LIGANDO:', opts: ['Suele recorrer cortas distancias si la secreción es endocrina', 'Solo tendrá un receptor citosólico si es hidrofílico', 'Puede interactuar con una proteína (receptor) en la célula blanco o diana', 'Es la respuesta de la célula diana'], c: 2, ex: 'El ligando se une al receptor (proteína) en la célula blanco/diana. La señalización endocrina viaja LARGAS distancias (hormonas en sangre). Los ligandos hidrofóbicos (no hidrofílicos) tienen receptor citosólico/nuclear. La respuesta es lo que ocurre tras la unión, no el ligando en sí.'},
  {st: 'Las estructuras 1 (colesterol) y 2 (proteína integral de canal) en una membrana presentan respectivamente función de:', opts: ['Receptor y aporte energético', 'Receptor y transporte de sustancias', 'Aporte energético y transporte de iones', 'Estabilizar las membranas y enzimática'], c: 3, ex: 'El colesterol estabiliza/regula la fluidez de la membrana animal. Las proteínas integrales pueden ser transportadores, receptores o enzimas (en este caso enzimática o de transporte). Ni el colesterol ni las proteínas de membrana cumplen función de aporte energético.'},
  {st: 'El INGRESO del ión potasio EN CONTRA DE GRADIENTE al citosol es un proceso:', opts: ['Exergónico pero no anabólico', 'Endergónico y anabólico', 'Endergónico pero no anabólico', 'Endergónico y catabólico'], c: 2, ex: 'Contra gradiente requiere energía → endergónico. Pero no es anabolismo (no se sintetizan moléculas grandes a partir de pequeñas), es solamente movimiento de un ion. Por eso "endergónico pero no anabólico". Lo hace, por ejemplo, la bomba Na+/K+.'},
  {st: 'La comunicación celular donde la señal viaja por la sangre a largas distancias se llama:', opts: ['Autocrina', 'Paracrina', 'Endocrina', 'Sináptica'], c: 2, ex: 'Endocrina = a través del torrente sanguíneo, larga distancia (hormonas). Autocrina = la propia célula. Paracrina = a células vecinas. Sináptica = entre neuronas. La sináptica y la paracrina son cortas; la endocrina es la de mayor distancia.'}
]);

registerExercises('biologia', '6', [
  {st: 'Si una célula eucariota animal NO presentara citoesqueleto, se vería afectado:', opts: ['El mecanismo de transporte por difusión simple', 'La síntesis de proteínas citosólicas', 'El proceso de división celular', 'El proceso de respiración celular'], c: 2, ex: 'La división celular requiere el huso mitótico, formado por microtúbulos del citoesqueleto. Sin citoesqueleto no hay huso → no hay división. Difusión simple ocurre en la membrana, síntesis de proteínas en ribosomas y respiración en mitocondrias — ninguna requiere citoesqueleto.'},
  {st: '¿Cuál de los siguientes pares de funciones se relaciona con los MICROTÚBULOS?', opts: ['Contracción muscular y transporte intracelular de vesículas', 'Contracción muscular y formación de cilios', 'Formación de flagelos y transporte intracelular de vesículas', 'División del citoplasma y transporte intracelular de vesículas'], c: 2, ex: 'Microtúbulos (tubulina): transporte vesicular (motores kinesina/dineína), huso mitótico, cilios y flagelos. Contracción muscular y citoquinesis (división del citoplasma) son por microfilamentos de actina, no microtúbulos.'},
  {st: 'El sistema de Golgi pertenece al sistema de endomembranas. Entre sus funciones:', opts: ['La polimerización y glicosilación de proteínas', 'La formación de vesículas de secreción', 'La síntesis de triglicéridos y colesterol', 'La síntesis de glucosa'], c: 1, ex: 'El Golgi modifica (glicosilación final, fosforilación) y empaqueta proteínas en vesículas de secreción. NO sintetiza triglicéridos/colesterol (eso es REL) ni glucosa (eso ocurre en cloroplastos por fotosíntesis).'},
  {st: 'Mediante técnicas de laboratorio se elimina el REL en células de un tejido animal. Luego de un tiempo se verifica que:', opts: ['No se sintetiza colesterol ni hay detoxificación de sustancias', 'No se sintetizan triglicéridos ni se realiza síntesis de ATP', 'No se almacena calcio ni hay síntesis de proteínas de membrana', 'No se sintetizan fosfolípidos de membrana ni se sintetizan enzimas lisosomales'], c: 0, ex: 'REL: síntesis de lípidos (colesterol, fosfolípidos, triglicéridos), detoxificación, almacén de calcio. Sin REL → no hay síntesis de colesterol ni detoxificación. Las enzimas lisosomales y proteínas de membrana las sintetiza el REG. ATP se hace en mitocondrias.'},
  {st: 'Las células del estómago secretan activamente la proteína pepsinógeno y por lo tanto tendrán muy desarrollado/s:', opts: ['El REL y el Golgi', 'El REG y el complejo de Golgi', 'Las mitocondrias y el REL', 'Lisosomas y REG'], c: 1, ex: 'Para secretar proteínas, la célula usa la cadena REG (síntesis) → Golgi (modificación) → vesículas de secreción → exocitosis. Tendrá muy desarrollados ambos.'},
  {st: 'Los filamentos del citoesqueleto encargados de la contracción muscular y la citoquinesis son:', opts: ['Microtúbulos', 'Microfilamentos (actina)', 'Filamentos intermedios (queratina)', 'Lamininas'], c: 1, ex: 'Los microfilamentos de actina (junto con miosina en músculo) son responsables de la contracción muscular y de la formación del anillo contráctil que divide el citoplasma en la citoquinesis.'},
  {st: 'La matriz extracelular (ECM) en tejidos animales:', opts: ['Es solo agua', 'Contiene colágeno, elastina, fibronectina y proteoglicanos; las células se anclan a ella mediante integrinas', 'No tiene función mecánica', 'Solo existe en plantas'], c: 1, ex: 'ECM = red de macromoléculas (colágeno, elastina, fibronectina, GAGs, proteoglicanos) que rodea células animales. Las integrinas son las proteínas de membrana que anclan la célula a la matriz. Da soporte mecánico, hidratación y señales de adhesión.'}
]);

registerExercises('biologia', '7', [
  {st: 'Las enzimas son catalizadores biológicos que participan de las reacciones metabólicas. ¿Cuál enunciado es aplicable a TODAS las enzimas?', opts: ['Si se altera su estructura terciaria pueden perder su actividad', 'Actúan acelerando las reacciones catabólicas exclusivamente', 'Su especificidad está determinada por el sitio alostérico', 'Pierden su actividad después de haber catalizado la reacción'], c: 0, ex: 'La actividad enzimática depende de la estructura 3D que conforma el sitio activo. Si se desnaturaliza, pierde actividad. Las enzimas catalizan TANTO catabolismo como anabolismo. La especificidad la da el SITIO ACTIVO, no el alostérico. Las enzimas NO se consumen.'},
  {st: 'En una reacción donde una enzima cataliza X → Y, se observa que:', opts: ['Cuanto mayor es la cantidad de sustrato menor es la formación de producto', 'La velocidad máxima aumenta si aumenta la cantidad de sustrato presente', 'La reacción solamente ocurre si la temperatura es la óptima', 'La velocidad máxima está relacionada con la saturación enzimática'], c: 3, ex: 'A alta concentración de sustrato, todas las enzimas están ocupadas (saturadas) → se alcanza Vmax. Aumentar más el sustrato no acelera la reacción. La Vmax depende de la cantidad de enzima, no de sustrato. La reacción ocurre fuera del óptimo, solo más lento.'},
  {st: '¿Cuál de las siguientes reacciones puede ser calificada como CATABÓLICA?', opts: ['Glicina + alanina + prolina → tripéptido', 'Glucosa + glucosa → maltosa', 'Glucosa + O<sub>2</sub> → CO<sub>2</sub> + H<sub>2</sub>O', 'Glicerol + 3 ácidos grasos → triglicérido'], c: 2, ex: 'La oxidación completa de glucosa a CO<sub>2</sub> y H<sub>2</sub>O es catabolismo: rompe una molécula grande en pequeñas y libera energía. Las otras tres son anabólicas (síntesis): forman una molécula grande a partir de pequeñas.'},
  {st: 'En los procesos enzimáticos, los inhibidores COMPETITIVOS se caracterizan porque:', opts: ['Disminuyen la velocidad por unirse al sitio activo de las enzimas', 'Disminuyen la velocidad porque son reguladores alostéricos que se unen al sitio activo', 'Disminuyen la cantidad de sustrato presente en la reacción', 'Disminuyen la cantidad de producto por unirse irreversiblemente a las enzimas'], c: 0, ex: 'El inhibidor competitivo se une al SITIO ACTIVO compitiendo con el sustrato. Su efecto se revierte aumentando [sustrato]. El alostérico se une a un sitio DISTINTO del activo. La inhibición irreversible es otro mecanismo.'},
  {st: 'El ATP cumple el rol de "moneda energética" porque:', opts: ['Es la única molécula que tiene energía', 'Acopla reacciones exergónicas (que lo producen) con endergónicas (que lo consumen), distribuyendo energía en la célula', 'Es un lípido de alta energía', 'No participa en el metabolismo'], c: 1, ex: 'El ATP es la moneda integradora: las reacciones que liberan energía la "cargan" en ATP (catabolismo), y las que requieren energía la "gastan" desfosforilándolo (anabolismo, transporte activo, contracción). Es la unidad de intercambio energético.'},
  {st: 'Un gráfico que representa la variación de energía a lo largo de una reacción muestra que la reacción libera energía neta. ¿A qué proceso podría corresponder?', opts: ['Al proceso completo de fotosíntesis', 'Al proceso de respiración celular', 'Una reacción de síntesis de un polipéptido', 'Glicerol + ácido graso → monoglicérido'], c: 1, ex: 'Reacción exergónica = libera energía → catabolismo. La respiración celular oxida la glucosa y libera ~30-32 ATP (energía). La fotosíntesis y las síntesis de polipéptidos o triglicéridos son endergónicas (anabolismo, requieren energía).'},
  {st: 'En reacciones óxido-reducción, ¿qué significa que una molécula se OXIDA?', opts: ['Gana electrones', 'Pierde electrones (o pierde H, o gana O)', 'Gana O y pierde electrones', 'Se descompone en H<sub>2</sub>O'], c: 1, ex: 'Oxidación = pérdida de electrones (o de H, o ganancia de O). Reducción = ganancia de electrones (o de H, o pérdida de O). Siempre van juntas: si una se oxida, otra se reduce. Los transportadores universales son NAD+/NADH y FAD/FADH<sub>2</sub>.'}
]);

registerExercises('biologia', '8', [
  {st: 'En una célula muscular, en AUSENCIA de oxígeno, la glucosa se puede degradar a:', opts: ['Ácido pirúvico solamente', 'Etanol', 'Ácido láctico', 'Dióxido de carbono'], c: 2, ex: 'Sin O<sub>2</sub>, las células musculares hacen fermentación láctica: glucosa → 2 pirúvico → 2 ácido láctico (regenerando NAD+). En levaduras la fermentación da etanol + CO<sub>2</sub>. La oxidación completa a CO<sub>2</sub> requiere O<sub>2</sub>.'},
  {st: 'La fotosíntesis se desarrolla en etapas. El orden CORRECTO es:', opts: ['Captación de energía solar / síntesis de glucosa / ruptura del agua', 'Liberación de oxígeno / incorporación de CO<sub>2</sub> a una biomolécula / síntesis de hidratos de carbono', 'Liberación de oxígeno / síntesis de glucosa / síntesis de ATP', 'Captación de energía solar / degradación de ATP / fijación de CO<sub>2</sub>'], c: 1, ex: 'En fase clara: se libera O<sub>2</sub> (fotólisis del agua) y se produce ATP/NADPH. En fase oscura: se incorpora CO<sub>2</sub> al ciclo de Calvin (a la RuBP por RuBisCO) y se sintetiza glucosa. Eso da el orden: liberación de O<sub>2</sub> → fijación de CO<sub>2</sub> → síntesis de glúcidos.'},
  {st: 'Si durante la respiración celular se marcaran radiactivamente los carbonos del ácido pirúvico, al cabo de un rato los carbonos podrán detectarse en:', opts: ['El CO<sub>2</sub>', 'El ATP', 'La glucosa', 'El NADH'], c: 0, ex: 'En la oxidación del piruvato y en el ciclo de Krebs, los carbonos del pirúvico se descarboxilan (se pierden como CO<sub>2</sub>). El ATP no incorpora esos C, el NADH tampoco (incorpora H, no C), y la glucosa no se forma de pirúvico en la respiración.'},
  {st: 'Si se aíslan mitocondrias y se las coloca en un medio con NAD+, FAD y ADP+Pi, el proceso de oxidación se completará agregando:', opts: ['Glucosa, O<sub>2</sub> y CO<sub>2</sub>', 'Glucosa, luz y CO<sub>2</sub>', 'Ácido pirúvico y O<sub>2</sub>', 'Ácido pirúvico y CO<sub>2</sub>'], c: 2, ex: 'La mitocondria recibe pirúvico (no glucosa, la glucólisis ocurre en citosol) y necesita O<sub>2</sub> para la cadena transportadora (aceptor final de electrones). El CO<sub>2</sub> es producto, no sustrato.'},
  {st: 'Los autótrofos pueden contrarrestar el aumento de CO<sub>2</sub> atmosférico porque:', opts: ['Degradan el CO<sub>2</sub> a nivel de los cloroplastos', 'Utilizan el CO<sub>2</sub> durante la fase bioquímica de la fotosíntesis (ciclo de Calvin)', 'Utilizan el CO<sub>2</sub> para sintetizar glucosa en el ciclo de Krebs', 'Disminuyen la formación de CO<sub>2</sub> durante el ciclo de Calvin'], c: 1, ex: 'En la fase bioquímica de la fotosíntesis (ciclo de Calvin) la enzima RuBisCO fija el CO<sub>2</sub> uniéndolo a la RuBP. Esa fijación retira CO<sub>2</sub> de la atmósfera. El ciclo de Krebs es de la respiración (libera CO<sub>2</sub>, no lo fija).'},
  {st: 'En un cloroplasto, durante la fase fotoquímica:', opts: ['En el ciclo de Calvin el oxígeno se transforma en glucosa', 'Durante el ciclo de Krebs el CO<sub>2</sub> se transforma en glucosa', 'A nivel de los tilacoides el CO<sub>2</sub> se fija a una molécula biológica', 'Durante la fase fotoquímica el agua se transforma en oxígeno (fotólisis)'], c: 3, ex: 'En la fase fotoquímica (en tilacoides) ocurre la fotólisis del agua: H<sub>2</sub>O se rompe liberando O<sub>2</sub>. La fijación de CO<sub>2</sub> es en el estroma (ciclo de Calvin), NO en tilacoides. El ciclo de Krebs es respiración, no fotosíntesis.'},
  {st: '¿Dónde ocurre la GLUCÓLISIS en una célula eucariota?', opts: ['En la matriz mitocondrial', 'En la membrana interna mitocondrial', 'En el citosol', 'En el núcleo'], c: 2, ex: 'La glucólisis ocurre en el CITOSOL (citoplasma) tanto en eucariotas como en procariotas. No requiere O<sub>2</sub> y no necesita organelas. El piruvato resultante luego entra a la mitocondria si hay O<sub>2</sub>.'},
  {st: 'En la respiración celular aeróbica, el aceptor FINAL de electrones de la cadena transportadora es:', opts: ['NAD+', 'FAD', 'O<sub>2</sub>', 'CO<sub>2</sub>'], c: 2, ex: 'El O<sub>2</sub> es el aceptor final: recibe los electrones que pasaron por la cadena y, con H+, forma H<sub>2</sub>O. Sin O<sub>2</sub>, la cadena se detiene y no se produce ATP por fosforilación oxidativa. Por eso necesitamos respirar.'}
]);
